### PR TITLE
OADP-543 Change setting of includeClusterResources

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
[OADP-543](https://issues.redhat.com//browse/OADP-543) Change setting of includeClusterResources

https://issues.redhat.com/browse/OADP-543

OCP 4.x from 4.6

Preview:

### CODE REVIEW

**Comment by mperetzred** [comment]
could you please also remove the inclusterClusterResources: true from the schedule example?
https://docs.openshift.com/container-platform/4.9/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.html#oadp-scheduling-backups_backing-up-applications
 Thanks

**Comment by mperetzred** [comment]
lgtm

**Comment by RichardHoch** [comment]
LGTM

**Comment by sbeskin-redhat** [comment]
@mburke5678 
Hi Michael,
Could you merge this PR?

**Pull request merged**
