### PR TITLE
CNV- 22640: Update HCO version - 4.13.3

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13

Issue:  [CNV-22640](https://issues.redhat.com//browse/CNV-22640)

Link to docs preview: [Installing with CLI - verification step](https://63340--docspreview.netlify.app/openshift-enterprise/latest/virt/install/installing-virt-cli#virt-deploying-operator-cli_installing-virt-cli)

QE review:
- [ ] QE has approved this change.

Additional information: To be merged on 4.14.3 GA (Aug 15)

### CODE REVIEW

**Comment by xenolinux** [comment]
looks good to me!

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead before implementing any feedback. Thanks!

**Comment by abhatt-rh** [comment]
> looks good to me!
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead before implementing any feedback. Thanks!

@apinnick and @xenolinux Peer review looks good!

**Pull request merged**
