### PR TITLE
BZ1878472: correction

### PR DESCRIPTION
**Pull request by skrthomas**
correction to a list of requirements
Direct link to preview: https://deploy-preview-31318--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-vnet.html#installation-about-custom-azure-vnet-requirements_installing-azure-vnet

for 4.5 +

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1878472

### CODE REVIEW

**Comment by skrthomas** [comment]
Ready for QA: @qinpingli

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by gpei** [comment]
LGTM.

**Pull request merged**
