### PR TITLE
Added OpenShift Container Storage considerations

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1590286

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@ahardin-rh - is this ready for QE?

**Comment by ahardin-rh** [comment]
@vikram-redhat I received some QE feedback directly in the BZ and will try to address those comments today to move this along. Thanks!

**Comment by vikram-redhat** [comment]
@ahardin-rh adding 3.11 label to this just as a reminder.

**Comment by ahardin-rh** [comment]
QE accepted in the BZ.

**Pull request merged**
