### PR TITLE
for ‘v1.ProjectRequest’, declare as required ‘apiVersion’ and ‘metadata.name’

### PR DESCRIPTION
**Pull request by tnguyen-rh**
This is (a) from https://bugzilla.redhat.com/show_bug.cgi?id=1244889#c11

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@adellape PTAL

**Comment by tnguyen-rh** [comment]
BZ status: Got feedback, tweaked, got LGTM (https://bugzilla.redhat.com/show_bug.cgi?id=1244889#c18).  Branch squashed.

@vikram-redhat  @adellape  PTAL

**Comment by adellape** [comment]
@tnguyen-rh LGTM, though AFAIK this will be overwritten the next time the API docs are re-generated[1], unless it was addressed in origin itself. See this old Issue which I believe is related:

https://github.com/openshift/openshift-docs/issues/756

I can go ahead and merge here though if you're still keen.

[1] https://github.com/openshift/origin/blob/master/api/README.md

**Comment by tnguyen-rh** [comment]
@adellape 
Thanks for the tip.  Good catch -- that is the same issue.  It looks like a code-enhancement opportunity for Somebody (/me salivates).  Yes, please merge for now, so that we can log partial (and only temporary) relief.  I see that the initial commit (generated) was in 2015-06-02, followed by a handful of manual tweaks, so there is some precedence, anyway.

**Comment by adellape** [comment]
:+1:

**Pull request merged**
