### PR TITLE
ROX-18622: Add doc entry for custom TLS certificates when using operator

### PR DESCRIPTION
**Pull request by connorgorman**
Version(s):

Merge to rhacs-docs; cherry pick to rhacs-docs-4.1, rhacs-docs-4.2, rhacs-docs-4.3

Issue:

[ROX-18622](https://issues.redhat.com/browse/ROX-18622)

[Link to docs preview
](https://62708--docspreview.netlify.app/openshift-acs/latest/configuration/add-custom-certificates.html#custom-cert-existing_add-custom-cert)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kcarmichael08** [comment]
Just checking that it should also be applied to 4.1; otherwise, lgtm! (made a couple small suggestions to comply with style guide)

**Review by ludydoo — APPROVED** [review]

**Comment by kcarmichael08** [comment]
See #68164

**Pull request closed without merging**
