### PR TITLE
BZ1975701: Clarify static IP workaround for Tang encryption on vSphere

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ1975701](https://bugzilla.redhat.com/show_bug.cgi?id=1975701)
Adds a Known Issue to the OCP 4.9 Release Notes including a verified workaround located here: https://docs.google.com/document/d/1rnAutjuxzUAauqOZwc8Iccl7SSZVWGJXH5VJL08YvTU/edit?usp=sharing
@jinyunma PTAL for QE ack.
Cc: @dustymabe and @miabbott for awareness

**Preview link:** https://deploy-preview-37500--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes#ocp-4-9-known-issues

### CODE REVIEW

**Comment by bobfuru** [comment]
I _think_ I finally have the formatting looking right in the YAML example 😥

**Comment by jinyunma** [comment]
I verified the ignition file generated by butane to append systemd unit, node boot up as expected, it works well.

**Review by bergerhoffer — COMMENTED** [review]
A few thoughts!

**Review by bobfuru — COMMENTED** [review]
Applied SME and peer review feedback.

**Review by jlebon — APPROVED** [review]
Some minor comments, but apart from that and some other comments already raised by others, this LGTM overall.

**Pull request closed without merging**
