### PR TITLE
Fix list of possible architectures in Optional configuration parameters sections

### PR DESCRIPTION
**Pull request by yselkowitz**
Applies to: 4.10+

﻿arm64 is only supported on AWS and Bare Metal; all other platforms (besides IBM Power and IBM Z) are still limited to amd64.

Preview (check `compute.architecture` and `controlPlane.architecture`):
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_alibaba/installing-alibaba-customizations.html#installation-configuration-parameters-optional_installing-alibaba-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-configuration-parameters-optional_installing-aws-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-configuration-parameters-optional_installing-azure-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.html#installation-configuration-parameters-optional_installing-azure-stack-hub-network-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters-optional_installing-gcp-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.html#installation-configuration-parameters-optional_installing-ibm-cloud-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-configuration-parameters-optional_installing-bare-metal
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-configuration-parameters-optional_installing-openstack-installer-custom
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-customizations.html#installation-configuration-parameters-optional_installing-rhv-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-configuration-parameters-optional_installing-vsphere-installer-provisioned-customizations
https://deploy-preview-43724--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-vmc-customizations.html#installation-configuration-parameters-optional_installing-vmc-customizations

/cc @kelbrown20

### CODE REVIEW

**Comment by yselkowitz** [comment]
Bare metal isn't working as expected.  The definitions of `:bare:` seem to be commented out, yet the conditional is used elsewhere in this module. :man_shrugging: 
/hold

**Comment by yselkowitz** [comment]
This could go in now, the only drawback being that BM UPI will incorrectly list only `amd64` until #43728 merges.  But that seems better than implying that all these platforms support `arm64` when they do not.
/hold cancel

**Comment by ahardin-rh** [comment]
LGTM! Is this work being tracked in JIRA or Bugzilla? If so, please provide a link for tracking purposes. We’ll be able to merge once we get an ack from QE. Thank you!

**Comment by yselkowitz** [comment]
This is a follow-up to #41036 (OSDOCS-3178) but isn't being tracked separately.

**Comment by aleskandro** [comment]
Thanks @yselkowitz 

/lgtm

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
