### PR TITLE
machine-config-operator: A few fixes

### PR DESCRIPTION
**Pull request by cgwalters**
- Fix a typo.
- Clarify the name and purpose of the operator component
- List CRDs as is done for e.g. the machine-api-operator

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@cgwalters - are these changes specific to the 4.6 branch only?

@chrisnegus

**Comment by cgwalters** [comment]
> @cgwalters - are these changes specific to the 4.6 branch only?

Nope, fixed.

**Comment by vikram-redhat** [comment]
@mike-nguyen can you ack this from a QE perspective?

**Comment by cgwalters** [comment]
Mike is on paternity leave, this is a pretty small PR and IMO obviously correct - I'm trying to get into a flow where the engineering team touches the docs more so...let's get this in?

**Pull request closed without merging**
