### PR TITLE
Fixing build warnings

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@adellape Can you please review this update since it touches your files? It's to fix these build warnings:

```
asciidoctor: WARNING: modules/osdk-owned-crds.adoc: line 6: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: modules/osdk-required-crds.adoc: line 6: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: modules/osdk-crd-templates.adoc: line 6: section title out of sequence: expected level 2, got level 3
```

**Comment by vikram-redhat** [comment]
Thanks @bergerhoffer!

**Review by adellape — APPROVED** [review]
:+1: Thanks!

**Pull request merged**
