### PR TITLE
Bz 2055940-49 Updating IPI to include a callout for 3 node cluster support

### PR DESCRIPTION
**Pull request by kquinn1204**
Addresses  https://bugzilla.redhat.com/show_bug.cgi?id=2055940

This needs merged into 4.9

### CODE REVIEW

**Comment by kquinn1204** [comment]
Hi @reihl I know you gave an LGTM on https://github.com/openshift/openshift-docs/pull/43695. This is the same note for 4.9 and maybe needs a LGTM for you too.

**Review by reihl — APPROVED** [review]
/I'll double verify soon, but 4.9 supporting 3 master only configuration as well

**Comment by kquinn1204** [comment]
@reihl So is that an LGTM for 4.9 or am I missing some additional guidance here

**Comment by reihl** [comment]
/LGTM, yes, but this is from my memory, I want to verify it one more time

**Comment by kquinn1204** [comment]
Cheers, I appreciate your diligence

**Comment by reihl** [comment]
@kquinn1204 I approve 4.9 and verify the case:
```
[root@ ~]# oc get node
NAME                                              STATUS   ROLES           AGE   VERSION
master-0-0   Ready    master,worker   18h   v1.22.5+a36406b
master-0-1   Ready    master,worker   18h   v1.22.5+a36406b
master-0-2  Ready    master,worker   18h   v1.22.5+a36406b
[root@ ~]# oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.0-0.nightly-2022-04-04-160205   True        False         17h     Cluster version is 4.9.0-0.nightly-2022-04-04-160205
```

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

**Comment by GroceryBoyJr** [comment]
Side note: FWIW, 0 is also an integer.

**Comment by GroceryBoyJr** [comment]
Requesting merge from the peer review team. Please stand by.

**Pull request merged**
