### PR TITLE
#CNV-33122: rn for moved tab

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.15 RN

Issue: [CNV-33122](https://issues.redhat.com//browse/CNV-33122)

Link to docs preview: https://71930--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-web

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by sabrinajess** [comment]
@lkladnit Please provide QE review.

**Pull request merged**
