### PR TITLE
[enterprise-4.14] OSDOCS-9689: update from dep to rem

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-9689

Link to docs preview: https://73713--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-deprecated-removed-features scroll to 'Installation deprecated and removed features' table

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Comment by jldohmann** [comment]
@melvinjoseph86 could you PTAL at this docs PR for QE ack? This is another PR that amends the deprecated and removed features table in the OCP 4.14 release notes to reflect the removal of CoreDNS supporting wildcard queries. thanks!

**Pull request merged**
