### PR TITLE
Attribute and typo fix

### PR DESCRIPTION
**Pull request by RichardHoch**
OADP 1.2; OCP 4.12+

Adds an attribute and fixes minor typos from a PR that got merged last week

### CODE REVIEW

**Comment by RichardHoch** [comment]
Please expedite because these errors are in the customer-facing documentation.  Thanks.

**Comment by kcarmichael08** [comment]
LGTM. For next time, can you please add the direct link in the body of the PR to the HTML preview so that the reviewer can quickly see it? Thanks!

**Pull request merged**
