### PR TITLE
Editied Per Scale topic for clarity

### PR DESCRIPTION
**Pull request by mburke5678**
I reworked the wording some for clarity. See https://coreos.slack.com/archives/CNKHL6076/p1580756040315400 for discussion.

### CODE REVIEW

**Comment by mburke5678** [comment]
@chaitanyaenr PTAL. I did add the inverted equation at the end of the doc, just for clarity.

**Comment by mburke5678** [comment]
@chaitanyaenr Any thoughts on this PR?

**Comment by mburke5678** [comment]
@xltian Can you please ask someone to review these changes? I want to make sure I didn't change the technical aspects. Thank you!

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by xltian** [comment]
@wabouhamad can you review this doc from QE? cc @mffiedler

**Review by wabouhamad — APPROVED** [review]
LGTM

**Pull request merged**
