### PR TITLE
OSDOCS-3850 updated manual defrag etcd

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-3850

Link to docs preview:
[Manual etcd defragmentation](http://file.rdu.redhat.com/antaylor/osdocs3850/scalability_and_performance/recommended-host-practices.html#manual-defrag-etcd-data_recommended-host-practices)

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@paigerube14 please review. Thanks!

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
