### PR TITLE
Bug 1487518 Added two variables to table in aggregated logging

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1487518

@openshift/team-documentation PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@bfallonf LGTM. 🎉 My only thought about this page in general, which may be considered outside of the scope of this PR, is that there are inconsistent references to ES and Elasticsearch. Lots of back and forth on what we call it. Perhaps the first usage on the page should be Elasticsearch (ES) and then just ES for the remainder of the topic.

**Comment by ewolinetz** [comment]
:+1:

**Comment by bfallonf** [comment]
@ahardin-rh You're right! I updated the first reference to have an (ES) in there, but it might be too much to change every use. Plus, I'm sure any future updates will mess with it more.

Thanks! I'll merge.

**Comment by ruromero** [comment]
I think it will be very helpful for users to give some hint about the implications of having replicas=0 and that this value is not recommended for production environments. Maybe something simple like this:

> The number of replica shards per primary shard for every new index. Defaults to '0'. A minimum amount replica shards of 1 is advisable for production clusters

**Comment by bfallonf** [comment]
Sure. Thanks @ruromero . I added what you suggested in #5481

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Added the `openshift_logging_es_number_of_replicas` and `openshift_logging_es_number_of_shards` variables to the table in xref:../install_config/aggregate_logging.adoc#aggregate-logging-ansible-variables[Specifying Logging Ansible Variables].
%

**Pull request merged**
