### PR TITLE
OSSMDOC-542 document non support for dual-stack.

### PR DESCRIPTION
**Pull request by JStickler**
Version(s): 4.6 - 4.11

Issue: [OSSMDOC-542](https://issues.redhat.com/browse/OSSMDOC-542

Link to docs preview:  http://file.bos.redhat.com/jstickle/OSSMDOC-542/service_mesh/v2x/servicemesh-release-notes.html#ossm-rn-known-issues_ossm-release-notes

QE review - mattmahoneyrh
Peer review - tmalove and ahardin-rh

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
LGTM

**Review by tmalove — COMMENTED** [review]
/LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
