### PR TITLE
fuse.adoc: Fix a misspelling of "OpenShift"

### PR DESCRIPTION
**Pull request by Miciah**

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
Label rationale:
PR #1332 introduced the typo, so we copy its label as well.

**Comment by mfojtik** [comment]
We should probably avoid using "shit" in GIT commit messages ;-) Now it will be there forever.

**Comment by Miciah** [comment]
The diffs are just as much a permanent part of the Git history, so there's no getting around that.  I'll change the PR title though...

**Comment by tnguyen-rh** [comment]
@adellape 
Looks like @tpoitras did the needful w/ #2490 so we can revert the orig labels/milestone.

**Pull request merged**
