### PR TITLE
Examples 1.9 updates

### PR DESCRIPTION
**Pull request by nebelsprachen**
• **Aligned team:** Dev Tools

Version(s):

`gitops-docs-1.9`  

Issue:

[RHDEVDOCS#5794](https://issues.redhat.com/browse/RHDEVDOCS-5794)

Link to docs preview:

* : https://72015--docspreview.netlify.app/openshift-gitops/latest/understanding_openshift_gitops/gathering-gitops-diagnostic-information-for-support

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by chengfang — APPROVED** [review]
LGTM

**Review by skopacz1 — COMMENTED** [review]
Just one question, otherwise LGTM!

**Pull request merged**
