### PR TITLE
Add warning about runlevels.

### PR DESCRIPTION
**Pull request by mcoops**
Missing entirely is a warning about runlevels and the fact that they disable SCCs on a given namespace. This adds a short notice of the dangers of adding runlevels.

### CODE REVIEW

**Comment by mcoops** [comment]
Might be good to back port this to 4.6, 4.7, but happy for now if it ends up in 4.8 doco.

**Comment by vikram-redhat** [comment]
@bergerhoffer could you take a look?

**Comment by bergerhoffer** [comment]
Thanks for submitting this @mcoops! I'll have some minor style changes to request. Would you like me to take over the PR and make them, or do you want me to comment on the requested changes and make them yourself?

Also, is there any sort of related BZ to this? Thanks!

**Comment by mcoops** [comment]
Not at all, happy for you to make whatever changes you feel necessary!

The only real related BZ is here: https://bugzilla.redhat.com/show_bug.cgi?id=1805488

**Pull request closed without merging**
