### PR TITLE
fixing the ordering to align with other install guides

### PR DESCRIPTION
**Pull request by sferich888**
@rvanderp3 please review

### CODE REVIEW

**Review by rvanderp3 — APPROVED** [review]

**Review by kalexand-rh — COMMENTED** [review]
I think this change looks good, but I think we need it in https://github.com/openshift/openshift-docs/blob/master/installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc, too.

**Comment by sferich888** [comment]
@kalexand-rh I pushed another update to get that other file too.

**Comment by kalexand-rh** [comment]
Thank you for the update! Merging.

**Pull request merged**
