### PR TITLE
[OCPBUGS#42254] Fix broken links in ShiftStack docs

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.15+ (earlier versions require a different PR)

Issue: [OCPBUGS-42254](https://issues.redhat.com/browse/OCPBUGS-42254)

Link to docs preview:

- https://82716--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html
- https://82716--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-nfv-preparing.html
- https://82716--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user.html
- https://82716--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-managing-machines.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by maxwelldb** [comment]
FYI @EmilienM

**Comment by EmilienM** [comment]
/lgtm
thanks!

**Comment by maxwelldb** [comment]
Squashed

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
