### PR TITLE
OCPBUGS#2367: Add a note

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-2367

Link to docs preview: https://53402--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#sts-mode-installing-manual-run-installer_cco-mode-sts

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by giofontana** [comment]
In my perspective would be more clear if the statement is added in the Prerequisites of that section. 

Suggested text: "For the following procedure you will need to configure the AWS CLI to use an IAM User with enough privileges required to install OpenShift, as described [here](https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account)."

**Comment by yunjiang29** [comment]
looks good to me, cc @jianping-shu for final review.

**Comment by xenolinux** [comment]
> Besides AWS STS, there's one more place with same issue for [GCP WIF](https://docs.openshift.com/container-platform/4.11/authentication/managing_cloud_provider_credentials/cco-mode-gcp-workload-identity.html#sts-mode-installing-manual-run-installer_cco-mode-gcp-workload-identity).
> 
> If we looked at the other places for using "openshift-install create cluster" for sample [installing azure default](https://docs.openshift.com/container-platform/4.11/installing/installing_azure/installing-azure-default.html#installation-launching-installer_installing-azure-default)
> 
> So how about to make all of them consistent i.e. adding the following bullet into pages of AWS STS and GCP WIF?
> 
>     * "Configure an account with the cloud platform that hosts your cluster."

@jianping-shu Addressed the comment

**Comment by jianping-shu** [comment]
Looks good to me, LGTM

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
