### PR TITLE
Add restart info in steps about upgrade proc

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1775463](https://bugzilla.redhat.com/show_bug.cgi?id=1775463) - 3.11 only

### CODE REVIEW

**Comment by bobfuru** [comment]
[BZ 1775463](https://bugzilla.redhat.com/show_bug.cgi?id=1775463)
For master-3 and enterprise-3.11 branches only

**Comment by bobfuru** [comment]
@jianlinliu PTAL

**Comment by jianlinliu** [comment]
@jiajliu PTAL.

**Comment by bobfuru** [comment]
This PR combines changes in [BZ 1775463](https://bugzilla.redhat.com/show_bug.cgi?id=1775463) with [BZ 1701102](https://bugzilla.redhat.com/show_bug.cgi?id=1701102). 
@jiajliu PTAL again and confirm this now looks complete. Thanks.

**Comment by bobfuru** [comment]
@jiajliu Can I please get a LGTM?

**Comment by bobfuru** [comment]
Also opened [PR 18620](https://github.com/openshift/openshift-docs/pull/18620) to merge changes into `master-3` branch.

**Pull request merged**
