### PR TITLE
OSDOCS-10959: Fixed a DNS example in the Examples: IP management file

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.13+

Issue:
[OSDOCS-10959](https://issues.redhat.com/browse/OSDOCS-10959)

Link to docs preview:
[DNS](https://78118--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html#virt-example-nmstate-IP-management-dns_k8s_nmstate-updating-node-network-config)

- [x] SME has approved this change.
- [x] QE has approved this change.

### CODE REVIEW

**Review by bhardesty — COMMENTED** [review]
LGTM!

**Review by cathay4t — APPROVED** [review]
LGTM

**Comment by ShaunaDiaz** [comment]
Does not need to be picked back to 4.12 per Slack.

**Pull request merged**
