### PR TITLE
OSDOCS-10290: removes machine mgmt content for Alicloud

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.16+

Issue:
[OSDOCS-10290](https://issues.redhat.com//browse/OSDOCS-10290)

Link to docs preview:
* [Managing compute machines](https://80824--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/index.html#machine-mgmt-intro-managing-compute_overview-of-machine-management)
* [Creating infrastructure machine sets for different clouds](https://80824--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#creating-infrastructure-machinesets-clouds)
* [Cloud Controller Manager Operator](https://80824--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/operator-reference.html#cluster-cloud-controller-manager-operator_cluster-operators-ref)

QE review:
- [x] QE has approved this change.

Additional information:
Rel Notes updates in #80970 (4.16), #80829 (4.17)

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@jcpowermac PTAL

**Review by skopacz1 — APPROVED** [review]
LGTM, I'm assuming one of the checks would fail if there's a remaining link to one of these deleted pages/sections 😛

**Comment by jeana-redhat** [comment]
> LGTM, I'm assuming one of the checks would fail if there's a remaining link to one of these deleted pages/sections 😛

thanks! yeah, these are hard to check... I searched the local repo for any instances of the removed files' filenames and it looks clear to me :crossed_fingers:

**Comment by jeana-redhat** [comment]
Merging into main and CP into 4.17, will get change mgmt acks for 4.16 CP

**Pull request merged**
