### PR TITLE
RHDEVDOCS 6078 fix custom parameters in resolvers

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.11, pipelines-docs-1.12, pipelines-docs-1.13, pipelines-docs-1.14, pipelines-docs-1.15

Issue:

RHDEVDOCS 6078

Link to docs preview:

https://77894--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html#resolver-hub-specify_remote-pipelines-tasks-resolvers
https://77894--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html#resolver-bundles-specify_remote-pipelines-tasks-resolvers
https://77894--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html#resolver-cluster-specify_remote-pipelines-tasks-resolvers
https://77894--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html#resolver-git-specify_remote-pipelines-tasks-resolvers

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by ppitonak — APPROVED** [review]

**Review by bergerhoffer — COMMENTED** [review]
Two minor nits about whitespace, but otherwise LGTM!

**Pull request merged**
