### PR TITLE
BZ#1962763 conditionalize machine-pool ref in parameter description for RHV only

### PR DESCRIPTION
**Pull request by emarcusRH**
https://bugzilla.redhat.com/show_bug.cgi?id=1962763
enterprise-4.9
enterprise 4.10
can also be ported to any recent versions that are actively used by customers.

Previews: 
AWS - no mention of Machine-pools table - 
https://deploy-preview-37384--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-configuration-parameters-optional_installing-aws-customizations
RHV - mention of "Additional RHV parameters for machine pools" table.
https://deploy-preview-37384--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-customizations.html#installation-configuration-parameters-optional_installing-rhv-customizations

### CODE REVIEW

**Comment by emarcusRH** [comment]
Michael Burman 2021-10-19 06:59:10 UTC

(In reply to Eli Marcus from comment #3)
> received ack/lgtm from Gal Z
> needs QE ack 
> and then final peer review

ack from QE, thanks

**Review by michaelryanpeter — COMMENTED** [review]
Just a small note. Please add the enterprise branch you need this merged to in the first comment of your PR.

Otherwise, LGTM.

**Pull request merged**
