### PR TITLE
PR38413: fix get packagemanifest command for SRO

### PR DESCRIPTION
**Pull request by kmccarron-rh**
Based on this PR: https://github.com/openshift/openshift-docs/issues/38413
Applies to 4.9+
Direct link to change:
https://deploy-preview-38434--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator#installing-the-special-resource-operator-using-cli_special-resource-operator

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
@liqcui @bthurber Please review!

**Review by bthurber — APPROVED** [review]
/lgtm

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
