### PR TITLE
OCPBUGS-37863: Documented a private infra notice for ARO

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.15+

Issue:
[OCPBUGS-37863](https://issues.redhat.com/browse/OCPBUGS-37863)

Link to docs preview:
* [Configuring a private storage endpoint on Azure](https://79914--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-private-cluster.html#registry-configuring-private-storage-endpoint-azure_configuring-private-cluster)
* [Optional: Preparing a private Microsoft Azure cluster for a private image registry
](https://79914--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/ipi/installing-azure-private.html#installing-private-image-registry-private-azure)

- [x] SME has approved this change.
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by ehvs — COMMENTED** [review]
To avoid any confusions, Id suggest to add *ARO* as well , which is the official acronym for the managed offer
> Azure Red Hat OpenShift (ARO)

**Comment by anuragthehatter** [comment]
cc @mgahagan73 for QE review

**Review by mffiedler — APPROVED** [review]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by tiguelu — APPROVED** [review]
lgtm

**Comment by JoeAldinger** [comment]
Merge review requested via slack.

**Pull request merged**
