### PR TITLE
dev_guide/deployments.adoc: mention that resources may be used for all type of strategies

### PR DESCRIPTION
**Pull request by php-coder**
See: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-deploymentstrategy

@rhcarvalho PTAL.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
Content LGTM.
Needs to update Asciidoc formatting.

I think for the note you want this syntax:

```asciidoc
[NOTE]
====
Lorem ipsum...
====
```

At least we use that elsewhere.

@openshift/team-documentation PTAL

**Comment by php-coder** [comment]
>Needs to update Asciidoc formatting.

@rhcarvalho Updated. Thanks!

**Comment by php-coder** [comment]
@openshift/team-documentation ping. PTAL, please.

**Comment by adellape** [comment]
@php-coder How about remove it from the "NOTE" block, and just say:

Deployment resources can be used with the Recreate, Rolling, or Custom deployment strategies.

**Comment by php-coder** [comment]
@adellape Yes, I don't mind. I've updated change accordingly.

**Comment by adellape** [comment]
:cool:

**Comment by php-coder** [comment]
@adellape Thanks!

**Pull request merged**
