### PR TITLE
ROX-18907: Remove Limited Availability text for Cloud Services GA

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

4.4 - will need a manual cherry pick after July 17
4.5 - can be merged now

[Issue](https://issues.redhat.com/browse/ROX-24907)

[Link to docs preview
](https://78157--ocpdocs-pr.netlify.app/openshift-acs/latest/cloud_service/rhacs-cloud-service-service-description.html)

QE review: (**ACS has no QE, approved by SME**)
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mkumku** [comment]
Hi Kerry,

1.     The commit looks great -> goal achieved and we removed the LA references.
2.     I am not fond of referencing Scope of Support for RHEL in our ACS documentation. It does not seem relevant. I do not remember why we reference it there and I went to see how other services do it. And they do not reference it. Maybe we should rewrite it in the same way?
-         OSD: https://docs.openshift.com/dedicated/support/getting-support.html
-         ROSA: https://docs.openshift.com/rosa/support/getting-support.html

**Comment by kcarmichael08** [comment]
> Hi Kerry,
> 
> 1. The commit looks great -> goal achieved and we removed the LA references.
> 2. I am not fond of referencing Scope of Support for RHEL in our ACS documentation. It does not seem relevant. I do not remember why we reference it there and I went to see how other services do it. And they do not reference it. Maybe we should rewrite it in the same way?
> 
> * OSD: [docs.openshift.com/dedicated/support/getting-support.html](https://docs.openshift.com/dedicated/support/getting-support.html)
> * ROSA: [docs.openshift.com/rosa/support/getting-support.html](https://docs.openshift.com/rosa/support/getting-support.html)

**Comment by kcarmichael08** [comment]
Doron approved via Slack.

**Pull request merged**
