### PR TITLE
Fix typo in dynamic plugin example

### PR DESCRIPTION
**Pull request by Bloom-P**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-9759

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by yapei** [comment]
looks good to me

**Comment by Bloom-P** [comment]
@opayne1  @kalexand-rh  Can you check this further?

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
