### PR TITLE
OSDOCS-4457: Bump OSDK version and dependencies

### PR DESCRIPTION
**Pull request by michaelryanpeter**
* Bump OSDK to version 1.25.1
* Bump Go dependency to 1.19+
* Remove `product-version-n1` variable because it is no longer used
* [Minor update after SME and QE review] Replace `ocp_ver` variable with`{product-version}`, the standard way to define the OCP version in the repo

Version(s): 4.12

Issue: [OSDOCS-4457](https://issues.redhat.com//browse/OSDOCS-4457)

Link to docs preview:

**OSDK installation docs**
* [Installing the OSDK CLI](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html) (Note admonition)
  * file: [`operators/operator_sdk/osdk-installing-cli.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-4935ab3e5656397ebbd295e53757cf82feb7be47db4fede33e233d4f72cc1534)
* [Installing OSDK CLI on Linux and MacOS](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html#osdk-installing-cli-linux-macos_osdk-installing-cli)
  * file: [`operators/operator_sdk/osdk-installing-cli.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-9411c438386474c7e81cbb7e60a063b10c0b4083923aa46580a9378fd326834c)
  
**OSDK project migration docs**
* [Updating Go-based Operator projects](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-updating-projects.html)
  * file: [`operators/operator_sdk/golang/osdk-golang-updating-projects.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-faecd9489ae0b9ca940985b8f6e900d6701664d6541209e2e74db2a7c9b35969)
* [Updating Ansible-based Operator projects](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html)
  * file: [`operators/operator_sdk/ansible/osdk-ansible-updating-projects.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-69ed593920a10e90485adc4572e5630da1bd3e3869627470235529abd0e7fcdf)
* [Updating Helm-based Operator projects](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-updating-projects.html)
  * file: [`operators/operator_sdk/helm/osdk-helm-updating-projects.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-1b2a5a346fcac4c881fb0327724131bf8551109849f7463e3b351aa1c2a55b40)
* [Updating Hybrid Helm-based Operator projects](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.html)
  * file: [`operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files)

**OSDK quickstarts and tutorials**
file: [`modules/osdk-common-prereqs.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-2602d1db64bb34f790b289868d49463375a0fddbac17a2a766527ceb6aa95e0f)
* [Go quickstart](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-quickstart.html#osdk-common-prereqs_osdk-golang-quickstart)
* [Go tutorial](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-tutorial.html)
* [Ansible quickstart](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-quickstart.html#osdk-common-prereqs_osdk-ansible-quickstart)
* [Ansible tutorial](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-tutorial.html#osdk-common-prereqs_osdk-ansible-tutorial)
* [Helm quickstart](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-quickstart.html#osdk-common-prereqs_osdk-helm-quickstart)
* [Helm tutorial](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-tutorial.html#osdk-common-prereqs_osdk-helm-tutorial)
* [Hybrid Helm](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm.html#osdk-common-prereqs_osdk-hybrid-helm)
* [Java quickstart](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-quickstart.html#osdk-common-prereqs_osdk-java-quickstart)
* [Java tutorial](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-tutorial.html#osdk-common-prereqs_osdk-java-tutorial)

**Scorecard docs**
 This changes the tag on the quay hosted image to 1.25.1.
 
image

 
* [Scorecard config](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-config_osdk-scorecard)
  * file: [`modules/osdk-scorecard-config.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-134d658e6dec394f52d0c22ba9ba347a965cc3a08e90d91fd385874483de0e8a)
* [Scorecard output](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-output_osdk-scorecard)
  * file: [`modules/osdk-scorecard-output.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-25cd4a09255552059240143dcd97d44c962ee3ed5e66a6b4292bcbc631d4d984)
* [Scorecard parallel](https://52647--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-parallel_osdk-scorecard)
  * file: [`modules/osdk-scorecard-parallel.adoc`](https://github.com/openshift/openshift-docs/pull/52647/files#diff-07264f252d3f738c0937cecf313fb214be77784b13017fb62220f71f694540af)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by KeenonLee** [comment]
Remove product-version-n1
Doing this correctly?  @everettraven 
and then
/lgtm

**Review by everettraven — APPROVED** [review]
Seems pretty straight forward.

/lgtm

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

Nice preview links!

**Comment by skrthomas** [comment]
@michaelryanpeter merge review /lgtm! There's no merge-review-done label. Perhaps we should create one for instances where the person seeking merge review has merge rights and wants to merge.

**Pull request merged**
