### PR TITLE
Change title to encrypting traffic

### PR DESCRIPTION
**Pull request by ghost**
@openshift/team-documentation PTAL. This is a follow-up to https://github.com/openshift/openshift-docs/issues/10097.

### CODE REVIEW

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM.
Did we decide to use Title case instead of Sentence case for now? (I seem to recall the convereation, but forget the outcome)
Also, out of curiosity, I see that `scaling_performance/network_optimization.adoc` topic uses IPSec in a couple of places. Is it worth changing it there too?

**Comment by tmorriso-rh** [comment]
@mburke5678 No, it's sentence case. I changed this on the document and in the topic map. Thanks.

**Comment by bfallonf** [comment]
@tmorriso-rh @mburke5678 Yes, sentence case.

Traci, is there a reason why you're deleting the anchors? I believe they can still exist with the discrete anchors. I can see that the `admin-guide-ipsec-opportunistic-group-configuration` anchor has links to it within this file, but you're deleting them as well. Is that intentional?

**Comment by tmorriso-rh** [comment]
@bfallonf I followed the guidance in the template. The templates don't show the discrete anchors used within the file.

**Comment by kalexand-rh** [comment]
This isn't a module, though, so I don't think that guidance from the template applies here. I'd put the anchors back in and remove the discrete tags.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Can you take a look at the "The command "pip install aura.tar.gz" failed and exited with 2 during" error message in the build? Thanks.

**Pull request merged**
