### PR TITLE
OSDOCS-9801: New Diagram for HCP Architecture Section

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-9801](https://issues.redhat.com//browse/OSDOCS-9801): New Diagram for HCP Architecture Section

Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-9801

Link to docs preview:
https://75515--ocpdocs-pr.netlify.app/openshift-rosa/latest/architecture/rosa-architecture-models.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @bchandra-ocp - Can you please review this PR? Thank you!

**Review by bchandra-ocp — APPROVED** [review]
looks good, thanks

**Comment by jneczypor** [comment]
Hi @yuwang-RH - Can you please review this PR when you have a moment? Thank you!

**Review by skopacz1 — APPROVED** [review]
LGTM, great looking image too!

**Pull request merged**
