### PR TITLE
BZ-2070861: Clarifying minor version update for CVO

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.6+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2070861
QE ack required.
Preview Links:

- [Support policy for monitoring Operators](https://deploy-preview-44187--osdocs.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack.html#unmanaged-monitoring-operators_configuring-the-monitoring-stack)
- [Support policy for unmanaged Operators](https://deploy-preview-44187--osdocs.netlify.app/openshift-enterprise/latest/architecture/architecture-installation.html#unmanaged-operators_architecture-installation)

### CODE REVIEW

**Comment by sagidlow** [comment]
@jiajliu PTAL :)

**Review by GroceryBoyJr — COMMENTED** [review]
Writer has offered to improve surrounding text so it's congruent with the output message. Standing by for changes.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

**Comment by jiajliu** [comment]
CVO overrides should block all upgrades(both of z-stream and y-stream), so no need changes for cvo.overrides.

**Pull request closed without merging**
