### PR TITLE
OSDOCS#11670 Fix cron scaler limitations note for CMA 2.14.1

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-11670

Removed note from the docs that was based on ambiguous upstream docs. 

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mburke5678** [comment]
@jkyros PTAL

**Comment by jkyros** [comment]
Thanks @mburke5678! sorry for the trouble
/lgtm

**Comment by mburke5678** [comment]
@asahay19 PTAL

**Review by xenolinux — COMMENTED** [review]
Changes LGTM!

I think `enterprise-4.12` label can be removed since we target 4.13+.

The preview link is missing.

**Pull request merged**
