### PR TITLE
Bug 1487015, updated Node.js version numbers

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1487015

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@dinhxuanvu Thanks for your guidance! PTAL

**Review by dinhxuanvu — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
Approved by QE

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
