### PR TITLE
OCPBUGS-27426:Add admin groups info to NetObserv

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issues:

There are two related bugs addressed in this PR: 
- https://issues.redhat.com/browse/OCPBUGS-27426 
- https://issues.redhat.com/browse/OCPBUGS-29538

Link to docs preview:

Loki docs: [Custom admin group access](https://72058--ocpdocs-pr.netlify.app/openshift-enterprise/latest/logging/log_storage/cluster-logging-loki) (note that the asciidoc tags effectively keep all the Loki topics for _Fine grained access to Loki logs_ and render a different callout 1 than for NetObserv)

NetObserv docs: 
- [Creating a new group for the cluster admin user role](https://72058--ocpdocs-pr.netlify.app/openshift-enterprise/latest/network_observability/installing-operators#logging-creating-new-group-cluster-admin-user-role_network_observability)
- [Custom admin group access](https://72058--ocpdocs-pr.netlify.app/openshift-enterprise/latest/network_observability/installing-operators#custom-admin-group-access) (note that the asciidoc tags render a different code callout 1 for NetObserv than Loki. 

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by libander — APPROVED** [review]
Minor nits. Looks great, the tag naming convention makes it really easy to follow.

**Comment by libander** [comment]
I think the modules for loki can be [leveloffset =+1], but the preview looks fine as is. Looks great!

**Review by memodi — COMMENTED** [review]
@skrthomas - could you add the the doc preview of these changes? the one attached on PR sends me to landing page.

**Comment by skrthomas** [comment]
@memodi there are links to the previews for Logging and Network Observability in the initial comment box where I have the versions and links to the OCPBUGS tickets. The ocp previewbot preview comment isn't the one to check because it will put you on the landing page.

**Review by jpinsonneau — APPROVED** [review]

**Review by jotak — APPROVED** [review]

**Review by memodi — APPROVED** [review]
/label qe-approved

**Comment by skrthomas** [comment]
@kalexand-rh can you PTAL at the tagging used here to include regions?

**Review by bburt-rh — APPROVED** [review]
LGTM. 

Perfect use case for tags!

**Comment by skrthomas** [comment]
TY @bburt-rh <3

**Pull request merged**
