### PR TITLE
[OSDOCS-10464] Remove HCP references in OSD docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4;15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10464

Link to docs preview:

**OSD:**  https://75543--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_cluster_admin/osd_nodes/osd-managing-worker-nodes.html#creating_machine_pools_ocm_osd-managing-worker-nodes
https://75543--ocpdocs-pr.netlify.app/openshift-dedicated/latest/architecture/index.html#openshift-architecture-common-terms_architecture-overview

**ROSA**
https://75543--ocpdocs-pr.netlify.app/openshift-rosa/latest/architecture/#openshift-architecture-common-terms_architecture-overview
https://75543--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes#creating_a_machine_pool_rosa-managing-worker-nodes

**OCP** https://75543--ocpdocs-pr.netlify.app/openshift-enterprise/latest/architecture/#openshift-architecture-common-terms_architecture-overview

QE review:
- [x] QE has approved this change.

Additional information:

**During content porting from OCP docs to ROSA/OSD docs, HCP was not conditioned out of OSD docs. This fix removes via conditions HCP from OSD docs while maintaining the reference to HCP in ROSA and OCP docs (where applicable).**

### CODE REVIEW

**Comment by mletalie** [comment]
@xueli181114,
   Can you please review this PR when you have a moment? Thx!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
