### PR TITLE
Correcting typo referring to Web Console

### PR DESCRIPTION
**Pull request by bgaydosrh**
Correcting typo in this module referring to Web Console.

Test Build: http://file.bos.redhat.com/bgaydos/100719/cnv/cnv_users_guide/cnv-edit-vms.html

Open for Peer Review from @kalexand-rh @mburke5678 @huffmanca

Copying @alexxa

Thanks
Bob

### CODE REVIEW

**Comment by mburke5678** [comment]
@bgaydosrh LGTM

**Comment by bgaydosrh** [comment]
> @bgaydosrh LGTM

Thanks @mburke5678. once @alexxa signs off we can merge and pick.

Bob

**Review by alexxa — APPROVED** [review]

**Comment by bgaydosrh** [comment]
Thanks @alexxa 

Please merge and pick to Enterprise-4.2 @mburke5678 - thanks so much!

Bob

**Pull request merged**
