### PR TITLE
Fixed conditionals in Kubernetes Deployments Support Tech Preview statement

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@spurtell Is it okay to call this "Technology Preview" in the Dedicated docs? Thanks!

**Comment by ahardin-rh** [comment]
@vikram-redhat FYI

**Comment by ahardin-rh** [comment]
Updated after discussion with Shawn.

**Comment by ahardin-rh** [comment]
No revision history needed

**Comment by david-martin** [comment]
@ahardin-rh is there a timeline or release that kubernetes will move out of technology preview in openshift?

**Pull request merged**
