### PR TITLE
MCO399: Added entitled host requirement for libreswan layering example

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/MCO-399

### CODE REVIEW

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by sinnykumari** [comment]
/lgtm

Note that we also have mentioned this in example comment https://github.com/openshift/rhcos-image-layering-examples/blob/master/libreswan/Containerfile#L8 , so user would still be aware of the requirement of RHEL entitled system.

**Comment by mburke5678** [comment]
@sergiordlr PTAL

**Comment by sergiordlr** [comment]
The fish and the libreswan examples worked fine when we used an entitled machine to create the images and our own base images (the base image in the Containerfile does not work).

We specify in the documentation to use the cluster's base image, so I think it is ok.

The example works now, but we can't guarantee that this example will continue working, since we don't test this github repo for every commit, though. I don't know if it is possible, but wouldn't it be better to embed the examples instead of linking them?

cc: @rioliu-rh

**Comment by sinnykumari** [comment]
> The fish and the libreswan examples worked fine when we used an entitled machine to create the images and our own base images (the base image in the Containerfile does not work).
> 
> We specify in the documentation to use the cluster's base image, so I think it is ok.
> 
> The example works now, but we can't guarantee that this example will continue working, since we don't test this github repo for every commit, though. I don't know if it is possible, but wouldn't it be better to embed the examples instead of linking them?

Yeah agree. In future, we maybe able to add some test cases in repo. But testing each example for each PR won't be feasible. Mostly what we would to test is what goes into our product doc repo.

**Comment by sergiordlr** [comment]
LGTM

**Pull request merged**
