### PR TITLE
Fix GitHub issue #39473: Update URLs on persistent-storage-ocs.adoc

### PR DESCRIPTION
**Pull request by lbscorpio**
@vikram-redhat This PR is to fix the issue#39473, the change applies to should be 4.9 ONLY, could you arrange someone to review it? Thanks.

### CODE REVIEW

**Comment by lbscorpio** [comment]
@vikram-redhat Any update? Thanks.

**Comment by vikram-redhat** [comment]
@lpettyjo PTAL

**Comment by lbscorpio** [comment]
@lpettyjo Any update about this PR? Thanks.

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by lbscorpio** [comment]
@lpettyjo @vikram-redhat Could you help to merge this PR to branch enterprise-4.9 if no problem? Over 3 months so far, thanks.

**Comment by kalexand-rh** [comment]
@lbscorpio, if you rebase, I'll merge it.

**Comment by kalexand-rh** [comment]
It looks like this change applies to 4.8 and was fixed on [this PR](https://github.com/openshift/openshift-docs/pull/40906/files). This file has also been updated for 4.9 on [this PR](https://github.com/openshift/openshift-docs/pull/41140/files).

Because changes that only apply to specific versions need to be opened against that specific branch, I'm going to close this one. But thank you for opening it!

**Comment by lbscorpio** [comment]
@kalexand-rh Thanks for your feedback. But it is a long time for the reaction even my PR was more earlier than this PR https://github.com/openshift/openshift-docs/pull/41140, result in I have no patient and lost power to track it. @vikram-redhat FYI

**Pull request closed without merging**
