### PR TITLE
CNV-15340: Relocate content for configuring certificate rotation

### PR DESCRIPTION
**Pull request by lmandavi**
This PR is associated with https://issues.redhat.com/browse/CNV-15430. The objective is to relocate this content to an appropriate section in the doc content as noted in the Jira story.

The content was originally in the networking section. It has been moved to Advanced VM management section.

Applies to CNV 4.8, 4.9, and 4.10.

### CODE REVIEW

**Comment by lmandavi** [comment]
This is the HTML content:
https://deploy-preview-40362--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/advanced_vm_management/virt-configuring-certificate-rotation.html

**Comment by lmandavi** [comment]
@stu-gott - Please review.

**Review by stu-gott — COMMENTED** [review]
/lgtm

**Comment by ousleyp** [comment]
LGTM. Based on our Slack conversation, I am going to cherrypick this to 4.8, 4.9, and 4.10. Thanks, Lavanya!

**Pull request merged**
