### PR TITLE
CNV-19043: Release notes: CHANGE

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/CNV-19043

Link to docs preview: https://57058--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-13-release-notes.html#virt-4-13-removed

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
Hi @stu-gott, are you able to review the release note related to removal of support for RHEL 6? You will see the note as the first one under Removed features. (Pay no attention to the other removed features that are left over from 4.12. I'll be cleaning those up.)  Thanks, Audrey

**Comment by dominikholler** [comment]
@stu-gott you might be better suitable to review this PR.

**Comment by stu-gott** [comment]
LGTM

**Comment by kbidarkar** [comment]
LGTM

**Comment by kcarmichael08** [comment]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
