### PR TITLE
MULTIARCH-696 - NMState Operator - Add IBM P/Z to supported platforms

### PR DESCRIPTION
**Pull request by SNiemann15**
OCP version:   enterprise-4.10 and later

Jira epic: https://issues.redhat.com/browse/MULTIARCH-696
See discussion: https://github.com/openshift/openshift-docs/pull/42539#discussion_r816994534
Related PR for RNs: https://github.com/openshift/openshift-docs/pull/42666

Preview: [About the Kubernetes NMSTATE Operator](https://deploy-preview-42647--osdocs.netlify.app/openshift-enterprise/latest/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html)

QE review

-  IBM Z: Holger Wolf
-  IBM Power: Manoj Kumar

### CODE REVIEW

**Comment by lsmcfadden** [comment]
@SNiemann15 I request that @manojnkumar answers for p like you have Holger answering for z.

**Comment by holgwolf** [comment]
LGTM

**Review by maxwelldb — APPROVED** [review]
lgtm.

**Pull request merged**
