### PR TITLE
RN CNV-5460 New logo branding for OpenShift Virtualization

### PR DESCRIPTION
**Pull request by lmandavi**
This PR is associated with https://issues.redhat.com/browse/CNV-5460 and it introduces the new OpenShift Virtualization logo in the release notes.

### CODE REVIEW

**Comment by lmandavi** [comment]
Ready for QE review:
http://file.rdu.redhat.com/lmandavi/July24_Draft2/RN-CNV-5460-Branding-Logo/virt/virt-2-4-release-notes.html

**Review by orenc1 — APPROVED** [review]
/lgtm

**Comment by lmandavi** [comment]
Thanks @orenc1 for the quick turnaround. Moving the PR to peer review.

**Comment by lmandavi** [comment]
@adellape Redundant images were deleted. Commits were squashed.

**Review by adellape — APPROVED** [review]
:+1:

**Pull request merged**
