### PR TITLE
[enterprise-4.1] Replace NFS suggestion with OCS

### PR DESCRIPTION
**Pull request by codyhoag**
Suggested in #18036.

### CODE REVIEW

**Comment by mburke5678** [comment]
@codyhoag LGTM

**Comment by liangxia** [comment]
The OCS used for OCP 4 is OCS 4.2. I'm not sure it's supported in OCP 4.1 or not.  Need OCS QE to confirm.

**Comment by codyhoag** [comment]
@vamahaja are you able to confirm this? Or point me to someone who can? Thanks!

**Comment by vamahaja** [comment]
@codyhoag, @petr-balogh or @vavuthu are right persons to contact for this, Thanks!

**Comment by codyhoag** [comment]
@petr-balogh or @vavuthu PTAL? We'd like to confirm that suggesting OCS in this context for 4.1 OCP is accurate. Thanks!

**Comment by vavuthu** [comment]
> @petr-balogh or @vavuthu PTAL? We'd like to confirm that suggesting OCS in this context for 4.1 OCP is accurate. Thanks!

OCS 4.2 is supported on the OCP 4.2 version ( not on ocp 4.1 )

**Comment by codyhoag** [comment]
@dmage Since OCS 4.2 isn't supported in OCP 4.1, what do you think we should add for our 4.1 suggestion to replace NFS?

**Comment by dmage** [comment]
@codyhoag in 4.1 NFS is the only supported option.

**Comment by codyhoag** [comment]
Thanks, @dmage. I'll leave NFS for 4.1 and add OCS for 4.2+. With that said, I'll close this PR without merging.

**Pull request closed without merging**
