### PR TITLE
BZ#2024667 Fix Windows server version URL

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=2024667

Preview: https://deploy-preview-38923--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-4-x.html#supported-windows-server-versions

### CODE REVIEW

**Comment by codyhoag** [comment]
@sgaoshang can you verify? Thanks!

**Comment by sgaoshang** [comment]
@codyhoag /lgtm, thanks.

**Review by skrthomas — APPROVED** [review]
LGTM!

**Pull request merged**
