### PR TITLE
OSDOCS#6178:LSO auto discovery is fully supported for ODF

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OSDOCS-6178

Link to docs preview: https://60441--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-local.html#local-storage-discovery_persistent-storage-local

QE review:
- [ ] QE has approved this change.

Additional information:

**PTAL**: @gcharot, @jsafrane, @duanwei33, @sferich888, @mawerner, @xltian

### CODE REVIEW

**Comment by gcharot** [comment]
LGTM

**Comment by jboxman-rh** [comment]
@lpettyjo, LGTM, thanks!

**Comment by jsafrane** [comment]
lgtm

**Comment by duanwei33** [comment]
LGTM

**Comment by xltian** [comment]
lgtm

**Comment by mwerner2113** [comment]
LGTM

**Pull request merged**
