### PR TITLE
CNV#40182: Release note: VM Export API now beta

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.17

Issue: [CNV-40182](https://issues.redhat.com/browse/CNV-40182)

Link to docs preview: Storage section (https://81183--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html#virt-4-17-storage)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
Hi @mhenriks, can you please review this release note? It corresponds to the other updates done for [CNV-40181](https://issues.redhat.com/browse/CNV-40181). Thanks!

**Review by lahinson — COMMENTED** [review]
lgtm

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
