### PR TITLE
Updating the Compliance Operator supported profiles

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.8+

Issue:
Power (and s390) support is not available at this time and will be added at a later date.

Link to docs preview:
[Supported compliance profiles](http://file.rdu.redhat.com/antaylor/co-support/security/compliance_operator/compliance-operator-supported-profiles.html)

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@prb112 does this look correct? Thanks!
@rhmdnd as well ^
/assign sheriff-rh
/label peer-review-needed

**Comment by prb112** [comment]
Yes - thanks Andrew

/lgtm

**Review by prb112 — APPROVED** [review]

**Comment by bscott-rh** [comment]
LGTM.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
