### PR TITLE
CNV-23962: Added missing content-type attribute

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 
4.11+

Issue:
[CNV-23962 Check all assembly metadata](https://issues.redhat.com/browse/CNV-23962)

Link to docs preview:
https://55444--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-using-the-cli-tools.html

QE review: N/A

### CODE REVIEW

**Comment by aspauldi** [comment]
@ousleyp 

Please review; thanks

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
