### PR TITLE
OADP-2130 for OCP-4.11: : Restructure of Backup, OADP Installation, Features, Plugins, and Configuring Restructure

### PR DESCRIPTION
**Pull request by anarnold97**
### PR 
[OADP-2130](https://issues.redhat.com/browse/OADP-2130)

Kathryn's note: This PR is a manual CP of https://github.com/openshift/openshift-docs/pull/64811, so the scope of the review is limited to ensuring that the PR is a reasonable CP. To maintain consistency between branches, no additional changes to the text should be suggested at this point.

### Version(s):

* Enterprise 4.11 → branch/enterprise-4.11

* For more details about the information requested in this template, see:
  https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/create_or_edit_content.adoc#submit-PR --->

### Version(s):

* OCP 4.11 

### Issue:

* [OADP-2130](https://issues.redhat.com/browse/OADP-2130)
### Link to docs preview:

* [OADP Backing up](https://66114--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications)
* [OADP Restoring](https://66114--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications)
* [OADP Data Mover](https://66114--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/data-mover-intro)

### QE review:
- [ ] QE has approved this change.
For approval, see [THIS PR](https://github.com/openshift/openshift-docs/pull/64811)

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
* Please note this has been reviewed in previous [PR](https://github.com/openshift/openshift-docs/pull/64811)

* This PR is to resolve cherry-picking issues. 

* It was tested locally with 4.11 against Travis

**Comment by anarnold97** [comment]
@kalexand-rh - please see this PR in response to [your request](https://github.com/openshift/openshift-docs/pull/64811#issuecomment-1757846678). Thanks.

**Comment by kalexand-rh** [comment]
@anarnold97, thank you! I've asked the peer review squad to just confirm that this is a reasonable cherry-pick instead of doing a full re-review.

**Comment by skrthomas** [comment]
This looks good to me. Seems reasonable and previews look okay.

**Comment by anarnold97** [comment]
@skrthomas thanks for the review

@kalexand-rh  thanks and apologies for causing trouble

**Pull request merged**
