### PR TITLE
Adding OCP 4.11 Image Registry release notes

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.11

Issue:
https://github.com/openshift/openshift-docs/issues/43249
https://issues.redhat.com/browse/OSDOCS-3754
https://issues.redhat.com/browse/OSDOCS-3602

Link to docs preview:
http://file.rdu.redhat.com/bmcelvee/bmcelvee:4.11-registry-releasenotes/release_notes/ocp-4-11-release-notes.html#ocp-4-11-registry

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
One link is not yet live, so the build will initially fail.

**Comment by bmcelvee** [comment]
Hi @ricardomaraschini! Would you mind reviewing these release notes, please? Thanks!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by bmcelvee** [comment]
Hi @dmage! I'm going ahead and merging these today. If we need to make any changes, I will open a follow-up PR on Monday. Thanks!

**Pull request merged**
