### PR TITLE
[BZ1978139]:fixes the broken link

### PR DESCRIPTION
**Pull request by xenolinux**
OCP version: 3.11
[Preview](https://deploy-preview-42711--osdocs.netlify.app/openshift-enterprise/latest/install_config/aggregate_logging.html#aggregate-logging-ansible-variables)
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1978139)
QE contact @anpingli LGTMed

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
The change looks good to me, though I am not comfortable merging it with the netlify preview not working. On my system and others, the top navigation bar is broken. Though this is probably just an issue with the Netlify preview, I want to pause until someone with more experience confirms.

**Comment by xenolinux** [comment]
Closing this PR due to broken preview error

**Comment by xenolinux** [comment]
Also this PR is not needed anymore since the fix is already in the system.

**Pull request closed without merging**
