### PR TITLE
OSDOCS-10051#updating link

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions: 
4.12+ 

Issue:
https://issues.redhat.com/browse/OSDOCS-10051

Link to docs preview:
https://75586--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-creating-registry.html#mirror-registry-ssl-cert-replace_installing-mirroring-creating-registry

QE review:
- [x] QE has approved this change (see comment in https://issues.redhat.com/browse/OSDOCS-10051)

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
As I don't have permissions, please add labels for 4.12+.

**Review by xenolinux — COMMENTED** [review]
LGTM 

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
