### PR TITLE
metering: Fix misspelling of 'configuing' in metering-installing-metering.adoc

### PR DESCRIPTION
**Pull request by timflannagan**

### CODE REVIEW

**Comment by timflannagan1** [comment]
@lbarbeevargas I was reviewing the metering 4.4 documentation and saw this misspelling. When I did a quick search, this appears to be the only instance of configuring being misspelled.

**Comment by lbarbeevargas** [comment]
@timflannagan1 Thanks for catching this and making the update. I don't have merge permissions, but will ask someone on the team to review and merge.

@openshift/team-documentation PTAL, add milestone and labels, and merge. Looks like the typo is in 4.2 and 4.4 (but not 4.3). Please CP to 4.2 and 4.4. Thank you!

**Comment by ahardin-rh** [comment]
@timflannagan1 Thanks for this! :+1:

**Pull request merged**
