### PR TITLE
Osdocs 3859

### PR DESCRIPTION
**Pull request by eohartman**
Added .metal and other AWS instance types to ROSA and OSD-CCS. Changed "compute types" to "instance types" to match AWS. Also added footnotes for special instance types, and added links to AWS under additional resources.

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-3859
https://issues.redhat.com/browse/OSDOCS-3902

Link to docs preview:
<b>ROSA:</b>
1. Changed "Compute types" to "instance types": https://51260--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-instance-types_rosa-service-definition
2. Added instance types, footnotes, and link to additional information: https://51260--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-aws-instance-types_rosa-service-definition

<b>OSD:</b>
1. Changed "Compute types" to "instance types": https://51260--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#instance-types_osd-service-definition
2. Added instance types, footnotes, and link to additional information: https://51260--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#aws-instance-types-ccs_osd-service-definition

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by eohartman** [comment]
@arendej See links above for previews, including notes regarding .metal instance types.

**Review by nalhadef — COMMENTED** [review]
Hi, Elisabeth. Just a few comments.

**Comment by tzhou5** [comment]
QE lgtm

**Pull request merged**
