### PR TITLE
ML-RHDEVDOCS-5097:Added OCP v4.13 to GitOps v1.8.2 RN for the upcoming OCP v4.13 release.

### PR DESCRIPTION
**Pull request by LunguTheEngineer**
• JIRA issue: [RHDEVDOCS-5097](https://issues.redhat.com/browse/RHDEVDOCS-5097)
• Aligned team: DevTools
• OCP version for cherry-picking: enterprise-4.10 and later
• Preview page: [gitops-release-notes-1-8-2](https://59284--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/gitops-release-notes.html#gitops-release-notes-1-8-2_gitops-release-notes)
• SME Review: @jaideepr97
• QE review: @varshab1210 
• Peer-review: @Srivaralakshmi and @ekristova

### CODE REVIEW

**Comment by jaideepr97** [comment]
LGTM

**Comment by varshab1210** [comment]
LGTM

**Review by Srivaralakshmi — APPROVED** [review]
@masauso-lungu Nice work! Approved!

**Comment by ekristova** [comment]
LGTM

**Review by rolfedh — APPROVED** [review]
LGTM

**Pull request merged**
