### PR TITLE
OADP 2664  -  Upgrade to 1.3

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP 1.3.0

OCP 4.11+

Resolves - https://issues.redhat.com/browse/OADP-2664

Deploy preview - https://66141--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp#about-oadp-update-channels_about-installing-oadp

### CODE REVIEW

**Comment by CarmiWisemon** [comment]
> I'm assuming we'd wanna link user to release notes section to review the changes?

Yes, I'm waiting to see if there are any more changes.

**Review by PrasadJoshi12 — APPROVED** [review]

**Comment by PrasadJoshi12** [comment]
LGTM. Thank you @CarmiWisemon

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Pull request merged**
