### PR TITLE
Router - changes to A/B weights discussion

### PR DESCRIPTION
**Pull request by pecameron**
OCP 3.7

Bug: 1477685
https://bugzilla.redhat.com/show_bug.cgi?id=1477685

Trello: BhWCH3vu
https://trello.com/c/BhWCH3vu/543-3-fix-problem-in-a-b-weight-algorithm

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc @mburke5678 PTAL

**Comment by mburke5678** [comment]
@pecameron LGTM

**Comment by bfallonf** [comment]
@pecameron I've been given the trello card to catch up on. This LGTM. Can I get a rebase? Then I'll merge. Sorry we missed this one.

Please let me know if there's anything else for this card.

**Comment by duyanyan** [comment]
LGTM

**Comment by knobunc** [comment]
@pecameron Please rebase and then this can merge.

**Comment by pecameron** [comment]
@bfallonf I did the rebase. PTAL.

**Pull request merged**
