### PR TITLE
Bug 1416223 fixed secure forwarding config in aggregating logging docs

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://bugzilla.redhat.com/show_bug.cgi?id=1416223

@richm PTAL

### CODE REVIEW

**Comment by richm** [comment]
lgtm

**Comment by ahardin-rh** [comment]
LGTM as well!

**Comment by bfallonf** [comment]
Great. I'll merge. Thanks, all. I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Fixed example in the xref:../install_config/aggregate_logging.adoc#fluentd-external-log-aggregator[Configuring Fluentd to Send Logs to an External Log Aggregator] section.
%

**Pull request merged**
