### PR TITLE
Bug 1297501 added substep to obtain the latest image stream

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1297501

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@adellape Peer review.

**Comment by tmorriso-rh** [comment]
@sdodson PTAL and let me know if this is OK.

**Comment by tmorriso-rh** [comment]
If this looks good, then we will apply it to the manual upgrades section as well.

**Review by sdodson — APPROVED** [review]

**Comment by sdodson** [comment]
Looks fine thanks.

**Comment by adellape** [comment]
@tmorriso-rh :+1:

**Review by adellape — APPROVED** [review]

**Comment by tmorriso-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/automated_upgrades.adoc#install-config-upgrading-automated-upgrades[Upgrading a Cluster -> Performing Automated In-place Cluster Upgrades]
|Added a step in xref:../nstall_config/upgrading/automated_upgrades.html#preparing-for-an-automated-upgrade[Preparing for an Automated Upgrade] section to change the file location use to update the streams and templates.
|xref:../install_config/upgrading/automated_upgrades.adoc#install-config-upgrading-automated-upgrades[Upgrading a Cluster -> Performing Manual In-place Cluster Upgrades]
|Added a step in xref:../install_config/upgrading/manual_upgrades.html#preparing-for-a-manual-upgrade[Preparing for a Manual Upgrade] section to change the file location use to update the streams and templates.
%

**Pull request merged**
