### PR TITLE
[OSDOCS-5466]: Swap "shared' and "cloud provider" for specifics

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-5466
Link to docs preview:

https://57498--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hi @xueli181114 or @yuwang-RH, can I get a QE review on this PR when you get a moment? Thanks!

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by arendej** [comment]
Should this preview not show the replacement for the 'Identity and Access Management' titles?

**Review by arendej — APPROVED** [review]
see my comment, then lgtm

**Comment by mletalie** [comment]
Hello @arendej,
    Thanks for reviewing this PR. Because this is a separate branch and not merged yet, don't think it would show the changes from the other branch. However, I do see that the changes made to the 'Identity and Access Management' titles are live. https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html

**Pull request merged**
