### PR TITLE
Update nw-networkpolicy-audit-disable.adoc

### PR DESCRIPTION
**Pull request by ccardenosa**
**Missing _oc_ command**

Version(s):
PR applies to all versions after a specific version (e.g. 4.8): 4.8+

Issue:
Missing oc command.

Link to docs preview:
https://docs.openshift.com/container-platform/4.8/networking/network_policy/logging-network-policy.html#nw-networkpolicy-audit-disable_logging-network-policy
https://docs.openshift.com/container-platform/4.9/networking/network_policy/logging-network-policy.html#nw-networkpolicy-audit-disable_logging-network-policy
https://docs.openshift.com/container-platform/4.10/networking/network_policy/logging-network-policy.html#nw-networkpolicy-audit-disable_logging-network-policy
https://docs.openshift.com/container-platform/4.11/networking/network_policy/logging-network-policy.html#nw-networkpolicy-audit-disable_logging-network-policy

### CODE REVIEW

**Comment by Amrita42** [comment]
lgtm

**Comment by ccardenosa** [comment]
Extra changes:

*Missing required network prefix*

Version(s):

    PR applies to all versions after a specific version: 4.6+

Issue:
POD creation fails due to this:

Warning FailedCreatePodSandBox 3s kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_multus-training-6f8cbbbf74-vn7v2_multus-training_b397a304-a920-4cd6-97c1-203f0ca2dc33_0(1a6516c279b60da692fb0dd3fc7206b49bf8904748f0fa3e68ab3530f01d7b71): error adding pod multus-training_multus-training-6f8cbbbf74-vn7v2 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [multus-training/multus-training-6f8cbbbf74-vn7v2/b397a304-a920-4cd6-97c1-203f0ca2dc33:work-network]: error adding container to network "work-network": the 'address' field is expected to be in CIDR notation, got: '192.168.10.10'

Link to docs preview:
https://docs.openshift.com/container-platform/4.6/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network
https://docs.openshift.com/container-platform/4.7/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network
https://docs.openshift.com/container-platform/4.8/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network
https://docs.openshift.com/container-platform/4.9/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network
https://docs.openshift.com/container-platform/4.10/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network
https://docs.openshift.com/container-platform/4.11/networking/multiple_networks/configuring-additional-network.html#nw-multus-ipvlan-config-example_configuring-additional-network

**Comment by mburke5678** [comment]
@ccardenosa The `nw-networkpolicy-audit-disable.adoc` file does not exist in the `enterprise-4.6` or `enterprise-4.7` branches. Merging the other two modules requires a separate PR.

**Comment by ccardenosa** [comment]
Hello @mburke5678 .

I have created two separate PR:

- https://github.com/openshift/openshift-docs/pull/50079
- https://github.com/openshift/openshift-docs/pull/50080

You can close this on. Sorry for the inconveniences.

BR,
Carlos.

**Comment by ccardenosa** [comment]
@mburke5678 Can we close this PR?

**Comment by mburke5678** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/50079 and https://github.com/openshift/openshift-docs/pull/50080

**Pull request closed without merging**
