### PR TITLE
Fix incorrect indefinite article used with {product-title}

### PR DESCRIPTION
**Pull request by aireilly**
This PR fixes incorrect indefinite article usage with {product-title}.  Merge to main, enterprise-4.9, enterprise-4.10.

`{product-title}` on it's own shouldn't take the indefinite article - "a/an Openshift Container platform" is incorrect. However, when we use `{product-title}` in the adjectival position it should take the indefinite article, and follow regular grammar rules when it does.

Previews (search for "an OpenShift Container Platform") : 

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-troubleshooting.html#troubleshooting-the-installer-workflow

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/operators/understanding/crds/crd-extending-api-with-crds.html#crd-creating-aggregated-cluster-role_crd-extending-api-with-crds

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#infrastructure-node-sizing_

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-troubleshooting.html#troubleshooting-the-installer-workflow

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-troubleshooting.html#ipi-install-troubleshooting-cluster-nodes-will-not-pxe_ipi-install-troubleshooting

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-osp.html#machineset-creating_creating-machineset-osp

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/operators/understanding/olm/olm-understanding-dependency-resolution.html#olm-dependency-catalog-ordering_olm-understanding-dependency-resolution

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/network-configuration.html#post-installation-osp-fips

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-4.9-release-notes.html#fips-compatability-rn

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-cluster-admin-serving.html

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-eventing.html

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/serverless/knative_serving/serverless-configuring-routes.html

https://deploy-preview-39688--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-ebs.html

### CODE REVIEW

**Comment by sagidlow** [comment]
LGTM!

**Comment by aireilly** [comment]
Thanks @sagidlow! Please merge/CP at your convenience :)

**Pull request merged**
