### PR TITLE
OCPBUGS4880 Changing 'data' to  'binaryData' avoid storing the logo in the wrong file

### PR DESCRIPTION
**Pull request by agantony**
Version(s): 
4.10+

Issue:
https://issues.redhat.com/browse/OCPBUGS-4880

Link to docs preview:
https://54146--docspreview.netlify.app/openshift-enterprise/latest/web_console/customizing-the-web-console.html#adding-a-custom-logo_customizing-web-console

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by agantony** [comment]
QE review: @yapei Please review the PR :-)

**Comment by yapei** [comment]
the changes look good to me

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Pull request merged**
