### PR TITLE
Adding missing images and modules symlinks to subdirectories

### PR DESCRIPTION
**Pull request by bergerhoffer**
@vikram-redhat We ran into an issue today with someone adding an image but it not rendering. And it ended up being because there wasn't the images symlink in that subdirectory. So I took a sweep of our existing directories and added images and modules symlinks where I saw that they were missing.

Do you see any issue with adding these? And if not, do you have a preference of whether this gets backported to 4.5, or just keep it to master/4.8?

FYI @bobfuru 

Also note I did all I found except the symlinks I knew were being added by that PR mentioned, to avoid conflicts.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
LGTM. If it is not already in the guidelines, please add it (and add to the agenda for next week for a reminder).

**Comment by vikram-redhat** [comment]
Yes, need to backport too.

**Comment by bobfuru** [comment]
LGTM. Thank you, @bergerhoffer!

**Pull request merged**
