### PR TITLE
Bug 1388691, Added new Manually Update Certificates for the Registry and Router section

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1388691

This PR covers 3.3 and 3.4. A separate PR will be created for 3.2.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@abutcher @adellape PTAL

**Comment by ahardin-rh** [comment]
@abutcher @adellape bump

**Review by adellape — COMMENTED** [review]
Looks good overall, @ahardin-rh and I chatted IRL just now and I'm gonna pick this up since I'm working on 3.5 cert stuff too. Will ping for review in a new PR shortly and close this one at that time.

**Comment by adellape** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/3851.

**Comment by adellape** [comment]
[Document: Certificate Redeploy Improvements](https://trello.com/c/w7yhGoeU/425-document-certificate-redeploy-improvements)

**Pull request closed without merging**
