### PR TITLE
OSDOCS-2918

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-2918](https://issues.redhat.com//browse/OSDOCS-2918)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-2918

Link to docs preview:
ROSA: https://57199--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can you please take a look at this PR when you have a moment? Thanks!

**Comment by xueli181114** [comment]
LGTM

**Comment by jboxman-rh** [comment]
@jneczypor, LGTM.

**Pull request merged**
