### PR TITLE
OSSM-6247 Add Kiali and OSSMC plugin attributes to common-attributes.adoc

### PR DESCRIPTION
**Pull request by gwynnemonahan**
[OSSM-6247](https://issues.redhat.com//browse/OSSM-6247) Add Kiali and OSSMC plugin attributes to common-attributes.adoc

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSSM-6247

Link to docs preview:
N/A

QE review:
QE review is not needed for this PR.

Additional information:
Adds 3 attributes under //service mesh v2:

:KialiProduct: Kiali Operator provided by Red Hat
:SMPlugin: OpenShift Service Mesh Console (OSSMC) plugin
:SMPluginShort: OSSMC plugin

### CODE REVIEW

**Comment by mburke5678** [comment]
@gwynnemonahan The format of the attributes LGTM

**Review by opayne1 — COMMENTED** [review]
lgtm

**Comment by opayne1** [comment]
@gwynnemonahan looks like you will need to do a manual CP for 4.12-4.14

**Comment by gwynnemonahan** [comment]
@opayne1 Wait...so the common-attributes file doesn't exist on 4.12, 4.13, or 4.14?

**Comment by opayne1** [comment]
It exists there is just a conflict on the lines you are trying to add to in those branches.

**Comment by libander** [comment]
Manual CPs: 
4.12: https://github.com/openshift/openshift-docs/pull/74093 
4.13: https://github.com/openshift/openshift-docs/pull/74094
4.14: https://github.com/openshift/openshift-docs/pull/74095

**Pull request merged**
