### PR TITLE
Fix a gramatic error

### PR DESCRIPTION
**Pull request by liamwarfield**
Changed line 255 to be clearer

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Hi @liamwarfield! Thanks for submitting this PR. Will you please change the base branch to `master-3` and rebase?

**Comment by liamwarfield** [comment]
Sure thing

**Comment by kalexand-rh** [comment]
@mburke5678, does this sound right to you?

**Comment by liamwarfield** [comment]
Fixed, sorry about the rebase havoc.

**Comment by mburke5678** [comment]
@sttts can you take a look? I worked with you on this document last year some time. The submitter is suggesting a wording change that changes the meaning of the sentence.

**Comment by mburke5678** [comment]
@wanghaoran1988 Can you look at this small change? You reviewed this topic when I added it last year.

**Comment by mburke5678** [comment]
@vikram-redhat Can you recommend a good QE resource for this?

**Comment by vikram-redhat** [comment]
@mburke5678 no QE approval required.

**Pull request merged**
