### PR TITLE
Update release links for OKD/OCP

### LINKED ISSUE #24715: Nightly builds site wrongly referenced url in https://docs.okd.io/latest/updating/updating-cluster-cli.html
### Which section(s) is the issue in?
it is in the **candidate-Latest channel** informational paragraph  in https://docs.okd.io/latest/updating/updating-cluster-cli.html

### What needs fixing?
Link referenced  in the line:
   "Release candidates differ from the nightly builds found on the https://www.openshift.com/try site."
should read as:
    "Release candidates differ from the nightly builds found on the https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/"

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #24715

### CODE REVIEW

**Comment by codyhoag** [comment]
@jiajliu PTAL? Thanks!

**Comment by jiajliu** [comment]
LGTM

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
