### PR TITLE
Customizing the console's About page

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1398163

### CODE REVIEW

**Comment by jwforres** [comment]
docs are valid for 3.3 and up

**Comment by jwforres** [comment]
@spadgett FYI

**Comment by ahardin-rh** [comment]
Thank you! I will apply some minor style edits in a separate  follow-up PR.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/web_console_customization.adoc#install-config-web-console-customization[Customizing the Web Console]
|Added a new xref:../install_config/web_console_customization.adoc#customizing-the-about-page[Customizing the About Page] section.
%

**Pull request merged**
