### PR TITLE
OSDOCS-6820 add External ID configuration description

### PR DESCRIPTION
**Pull request by xJustin**
added External ID configuration description

Version(s):

4.13+

Issue:

https://issues.redhat.com/browse/OSDOCS-6820

Link to docs preview:

https://68156--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations#rosa-sts-creating-cluster-customizations-cli_rosa-sts-creating-a-cluster-with-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by sheriff-rh — APPROVED** [review]
LGTM, setting peer review done.

**Comment by xJustin** [comment]
@sheriff-rh - This one never got cherry-picked to the other branches.

**Comment by sheriff-rh** [comment]
My apologies @xJustin  I'll take care of it now.

**Comment by sheriff-rh** [comment]
@xJustin  looks like you'll have to do manual cherrypicks for 4.13 and 4.14.

**Pull request merged**
