### PR TITLE
CNV-20075: reversing redirects for CNV GA

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): No CP

Issue: https://issues.redhat.com/browse/CNV-20075

Link to docs preview: N/A

Additional information: 
- To be merged _after_ merging the PR to reverse the about-virt placeholder (https://github.com/openshift/openshift-docs/pull/48519)
- Do not merge until CNV 4.11 GA

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by ousleyp** [comment]
@sjhala-ccs Please reapprove when you get the chance. Thanks!

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
