### PR TITLE
Add a tool for generating master and node configuration description file

### PR DESCRIPTION
**Pull request by soltysh**
@openshift/team-documentation this tool will allow generating a reasonable tabular documentation for master and node config. Lemme know what you think. 

@derekwaynecarr @mfojtik we've talked about it some time ago, sorry it took me this long :blush: 
Derek, do we want to generate appropriate docs for 3.9 as well?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, thoughts?

**Comment by vikram-redhat** [comment]
This is a hard one after the F2F last week. This is clearly reference documentation which will be good for developers, but I don't know if we want to add this to install docs and how to modularize it.

@soltysh - is this for origin only and/or for 3.7? How does the script actually run? Would we need to run this script every few days?

**Comment by soltysh** [comment]
> @soltysh - is this for origin only and/or for 3.7? How does the script actually run? Would we need to run this script every few days?

This should be working on any release. For the actual run see the `Makefile`. It needs running only when API gets updated, which should not happen that often, but running it automatically every X days does make sense.

**Comment by soltysh** [comment]
This doc is more useful for administrator modifying master- and node- configs more than devs.

**Comment by soltysh** [comment]
@openshift/team-documentation do we want to pursuit this one, I think this will be a valuable piece of information for the admins in 3.10.

**Comment by vikram-redhat** [comment]
@soltysh - ok let me figure out where this goes with the team. 

@aheslin - sorry if we talked about this already, but let's have another chat?

**Comment by vikram-redhat** [comment]
@soltysh - sorry still working on this one. Give me a few more days.

**Comment by vikram-redhat** [comment]
@soltysh - sorry Maciej this has taken so long, but in the end we decided to not go ahead with this as it doesn't offer much value to an administrator. Further, there are maintenance issues with this script that we don't have the bandwidth to work on. 

I am going to close this PR, but please feel free to reopen if you have more details as to why it would fit into a good user story for admins/devs.

@aheslin

**Comment by soltysh** [comment]
The original idea was to provide extensive guidance about master config fields. But with the upcoming changes it might not be necessary anymore. We can always return back to this, if needed.

**Pull request closed without merging**
