### PR TITLE
Bug 1758583 Clarify default routes cannot be changed

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1758583

Will add label for 4.1 with approval.

### CODE REVIEW

**Comment by bmcelvee** [comment]
@lihongan would you mind giving this a review when you get a chance, please? Thanks!

**Comment by lihongan** [comment]
LGTM. thank you @bmcelvee

**Comment by bmcelvee** [comment]
@vikram-redhat would it be appropriate to cherry pick this to 4.1? It applies to 4.2+ as well. Thanks!

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL?

**Comment by jboxman** [comment]
@bmcelvee LGTM

**Comment by vikram-redhat** [comment]
> @vikram-redhat would it be appropriate to cherry pick this to 4.1? It applies to 4.2+ as well. Thanks!

Confirm with the bug reporter to reopen the bug and then cherry pick it.

**Comment by bmcelvee** [comment]
So far I've been able to cherry pick this to 4.2, 4.3, and 4.5. 4.4 is still giving me trouble, so I will have to check back on it.

**Pull request merged**
