### PR TITLE
Updating infrastructure components list to include components for monitoring user-defined projects

### PR DESCRIPTION
**Pull request by lbarbeevargas**
Update to wording for [OpenShift Container Platform infrastructure components](https://docs.openshift.com/container-platform/4.6/machine_management/creating-infrastructure-machinesets.html#infrastructure-components_creating-infrastructure-machinesets) to include components for monitoring user-defined projects.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
@sichvoge PTAL

**Review by lilic — APPROVED** [review]
lgtm

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
