### PR TITLE
RHCOS URLS for beta6

### PR DESCRIPTION
**Pull request by kalexand-rh**
@jianlinliu, since beta 6 was released, I updated the image URLs to match https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/4.1.0-rc.4/.

Will you PTAL?

### CODE REVIEW

**Comment by jianlinliu** [comment]
I think final beta6 build should be rc.5, some fix is not merged into rc.4, so rc.5 came out.

**Comment by kalexand-rh** [comment]
Figures. I don't see rc5 posted. I'll check again my afternoon and update the links.

**Comment by kalexand-rh** [comment]
I still don't see new bits.

**Comment by jianlinliu** [comment]
Ah, rc.5 is for beta7, pls check "Announcing OpenShift 4.1 - Beta 7 [4.1.0-rc.5]" email in aos-devel, seem like this PR need some polish to keep up-to-date.

**Comment by kalexand-rh** [comment]
From that thread:
> There are no changes for the RHCOS assets as the latest there is still 4.1.0-rc.4?

> right, there are no changes to rhcos assets.

We don't explicitly mention the beta version in this PR, so I think it's right.
@jianlinliu, I'm going to merge this PR, but if there are problems with it, I am happy to submit another one.

**Pull request merged**
