### PR TITLE
HCIDOCS-128: vCPU mismatch in installation with the Assisted Installer

### PR DESCRIPTION
**Pull request by tshwartz**
SME: AJ van Woensel
QE: Alexander Chuzoy

Version(s):
main, 4.16, 4.15, 4.14, 4.13, 4.12

Issue:
https://issues.redhat.com/browse/HCIDOCS-128

Link to docs preview:
https://76224--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_sno/install-sno-preparing-to-install-sno

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by achuzhoy — APPROVED** [review]

**Comment by tshwartz** [comment]
Print preview: https://76224--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms

**Comment by tshwartz** [comment]
HCIDOCS - Assisted Installer

/label peer-review-needed

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by tshwartz** [comment]
Thank you, Shauna and Sebastian.

**Comment by jakobmoellerdev** [comment]
@tshwartz @ShaunaDiaz This PR needs to be reverted in all releases. This addition is in the LVMS docs and not the SNO docs. Additionally the values for LVMS already exist here https://github.com/openshift/openshift-docs/pull/76224/files#diff-3e2cdd52a562df52099f33b768c14c16f777376548099650e32ef93159a34a50R23. TBH not sure how this slipped through, sorry about that.

**Comment by ShaunaDiaz** [comment]
@tshwartz Please submit another PR that reverses these changes and submit for merge review citing this PR and @jakobmoellerdev's comment.

**Pull request merged**
