### PR TITLE
Fix Ignition doc links, spec versions, some wording

### PR DESCRIPTION
**Pull request by bgilbert**
Link to the Ignition docs site, not directly to the GitHub repo. Update spec 3.1 references to 3.2.  Improve some wording.  Fix capitalization of Ignition.

### CODE REVIEW

**Comment by bgilbert** [comment]
cc @bobfuru

**Comment by bobfuru** [comment]
Nice, @bgilbert - thanks for this. Would you mind squashing? Thx.

@mike-nguyen or @miabbott Could you ack for QE, please?

**Comment by bgilbert** [comment]
Squashed.

**Review by miabbott — APPROVED** [review]
QE ack'ed

**Comment by miabbott** [comment]
FYI this should get cherry-picked to `release-4.6` too

**Comment by bgilbert** [comment]
Not as-is for 4.6, since it updates the Ignition spec to version 3.2.

**Comment by bobfuru** [comment]
Thanks, I'll open a separate PR for a fix to 4.4-4.6 that doesn't include the Ignition spec bump.

**Comment by miabbott** [comment]
> Not as-is for 4.6, since it updates the Ignition spec to version 3.2.

Right, so 4.6 is using spec v3.1?

**Comment by miabbott** [comment]
> Thanks, I'll open a separate PR for a fix to 4.4-4.6 that doesn't include the Ignition spec bump.

4.4 + 4.5 are still using Ignition spec v2.2.0

**Comment by bobfuru** [comment]
> Right, so 4.6 is using spec v3.1?
> 4.4 + 4.5 are still using Ignition spec v2.2.0

Thanks.  I will be sure to reflect this in the separate PRs.

**Comment by bgilbert** [comment]
cc me, please, and I'll double-check them.

**Comment by bobfuru** [comment]
LGTM

**Review by vikram-redhat — APPROVED** [review]
lgtm

**Pull request merged**
