### PR TITLE
Change the channel for ALBO

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: None

Link to docs preview: https://53157--docspreview.netlify.app/openshift-enterprise/latest/networking/aws_load_balancer_operator/install-aws-load-balancer-operator.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
@lihongan Please take a look at this PR

**Comment by Amrita42** [comment]
lgtm

**Comment by lihongan** [comment]
Looks good. thanks you!

**Pull request merged**
