### PR TITLE
Document how to configure the PROXY protocol

### PR DESCRIPTION
**Pull request by Miciah**
Document how to configure the HAProxy router to expect incoming connections to use the PROXY protocol and how to configure Amazon ELB to forward requests using the PROXY protocol.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@Miciah Is this targeted for 3.5? Thanks!

**Comment by Miciah** [comment]
@ahardin-rh, sorry, I should have thought to mention to what versions this documentation applies.  We [backported the feature to 3.3](https://github.com/openshift/ose/pull/522) and [to 3.4](https://github.com/openshift/ose/pull/523).

**Comment by ahardin-rh** [comment]
@Miciah Thanks so much! I am going to follow up with some very minor style edits in a separate PR.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../ install_config/router/proxy_protocol.adoc#install-config-router-proxy-protocol[Configuring the HAProxy Router to Use the PROXY Protocol]
|New topic on configuring the HAProxy router to use the PROXY protocol.
%

**Pull request merged**
