### PR TITLE
Fix invalid admonition type in ShiftStack Kuryr limitations

### LINKED ISSUE #21207: Invalid admonition in 4.3 ShiftStack w/Kuryr limitations
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/installing/installing_openstack/installing-openstack-installer-kuryr.html#installation-osp-kuryr-known-limitations_installing-openstack-installer-kuryr

### What needs fixing?

The musl section uses "INFO" as an admonition, which is not a valid type. As a result, the admonition doesn't render properly.

### PR DESCRIPTION
**Pull request by maxwelldb**
Resolves #21207

### CODE REVIEW

**Comment by maxwelldb** [comment]
@kalexand-rh Could you +1 this? It fixes a tiny issue that's introduced by #20728.

**Review by kalexand-rh — COMMENTED** [review]
+1

**Pull request merged**
