### PR TITLE
OSSM-6379 [OSSM][DOC] Update possible values for .general.logging.componentLevels

### PR DESCRIPTION
**Pull request by gwynnemonahan**
[OSSM-6379](https://issues.redhat.com//browse/OSSM-6379) [OSSM][DOC] Update possible values for .general.logging.componentLevels

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSSM-6379

Link to docs preview:
https://75142--ocpdocs-pr.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-reference-smcp.html#ossm-cr-general_ossm-reference

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by pbajjuri20 — APPROVED** [review]
LGTM..!

**Review by jldohmann — APPROVED** [review]
nice work! LGTM

**Pull request merged**
