### PR TITLE
nocache should be noCache

### PR DESCRIPTION
**Pull request by wanghaoran1988**
fix this : https://github.com/openshift/origin/issues/7817

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but needs a rebase.

**Comment by wanghaoran1988** [comment]
@bparees rebased

**Comment by bparees** [comment]
lgtm
@openshift/team-documentation ptal/merge.

**Comment by tnguyen-rh** [comment]
[rev_history]
|link:../dev_guide/builds.html[Developer Guide -> Builds -> Docker Strategy Options]

|Spelled `noCache` correctly in the example.

**Comment by tnguyen-rh** [comment]
@adellape PTAL r.note.

**Comment by adellape** [comment]
@tnguyen-rh :+1:

**Comment by wewang58** [comment]
@tnguyen-rh , Hi, I have a question ,if set noCache: false, will not set in dockerStrategy of bc, right? 
because  I set noCache: true ,it's ok , set noCache: false, it's not exist in dockerStragegy of bc.

**Comment by bparees** [comment]
Since false is the default value, it will be omitted when you view the BC.
It's somewhat unfortunate, but expected, behavior.

Ben Parees | OpenShift

**Pull request merged**
