### PR TITLE
OSDOCS-3829: Update lifecycle dates

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.10, 4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3829

Link to docs preview:
ROSA: http://file.rdu.redhat.com/bmcelvee/20221807/rosa_policy_service_definition/rosa-life-cycle.html#rosa-life-cycle-dates_rosa-life-cycle
OSD: http://file.rdu.redhat.com/bmcelvee/20221807/osd_policy/osd-life-cycle.html#rosa-life-cycle-dates_osd-life-cycle

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
/LTGM

**Review by arendej — APPROVED** [review]
thank you

**Comment by bmcelvee** [comment]
Thanks, all! @GroceryBoyJr I updated the _Module included in the following assemblies:_ section to reflect ROSA and OSD.

**Pull request merged**
