### PR TITLE
OADP-2130: Restructure of Backup, OADP Installation, Features, Plugins 4.12

### PR DESCRIPTION
**Pull request by anarnold97**
### Reason for PR

* [cherry pick failure for 4.12](https://github.com/openshift/openshift-docs/pull/64811#issuecomment-1734017062)
* as this is a fix for a cherry pick failure can it be moved to merge review (same PR with two unneeded links removed)
* see [this PR](https://github.com/openshift/openshift-docs/pull/65862) as well

### Jira

* [OADP-2130](https://issues.redhat.com/browse/OADP-2130)

### Version(s):

* Enterprise 4.12 → branch/enterprise-4.12

### Issue:

https://issues.redhat.com/browse/OADP-2130

This PR is predominantly related to a restructure of existing OADP documentation

## Link to docs preview:

* [OADP Backing up](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications)
* [OADP Restoring](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications)
* [OADP Data Mover](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/data-mover-intro)
* [Advanced OADP features and functionalities](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-advanced-topics)

### QE review:

- [x ] QE has approved this change.

Please see this [PR](https://github.com/openshift/openshift-docs/pull/64811)

### CODE REVIEW

**Comment by anarnold97** [comment]
@adellape - there is no hurry on this so do not kill yourself, if you have other things

**Review by adellape — APPROVED** [review]
Same comment as https://github.com/openshift/openshift-docs/pull/65862#pullrequestreview-1662783086.

**Pull request merged**
