### PR TITLE
OSDOCS-9726 STS and ALBO - retitling the section to be appropriate

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-9726

Link to docs preview: https://75799--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/aws_load_balancer_operator/installing-albo-sts-cluster.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

Preview: https://75799--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/aws_load_balancer_operator/installing-albo-sts-cluster.html

**Comment by jmanthei** [comment]
@ShudiLi please QE check

**Comment by ShudiLi** [comment]
/lgtm
thanks

**Comment by jab-rh** [comment]
@jmanthei, what versions is this for? Thanks!

**Comment by ShaunaDiaz** [comment]
@jmanthei Please indicate the versions in the opening commit message so we know where you need CPs (or if only going in main). TY!

**Comment by jmanthei** [comment]
@ShaunaDiaz my apologies- this should be applied to all currently supported versions of OpenShift.

**Pull request merged**
