### PR TITLE
Remove the cluster max limits for minor releases

### PR DESCRIPTION
**Pull request by mburke5678**
Per @tkatarki and @mcurry-rh , we need to remove the OpenShift Container Platform tested cluster maximums (for minor releases) section and table for 4.9 GA, and backport that change (removal) to previous releases. We should leave the OpenShift Container Platform tested cluster maximums for major releases section and table as is. Marc will work with the team post-GA to refine the content in the remaining section.
We have acks from @tkatarki and @mcurry-rh on these changes.

~~We reached out to Marc Curry, who is the PerfScale PM, and he agrees with Tushar that we should reset the tested maximum nodes and pods to 2,000 and 150,000 respectively. this PR reverts change: https://github.com/openshift/openshift-docs/pull/25591/files~~
~~Preview: https://deploy-preview-36588--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/planning-your-environment-according-to-object-maximums?utm_source=github&utm_campaign=bot_dp#cluster-maximums_object-limits~~
~~Also, perhaps we can change the presentation of the table so we don't need a different file for each OpenShift version?~~

~~https://coreos.slack.com/archives/G019L1Q2CN7/p1632176528000100~~

### CODE REVIEW

**Comment by mburke5678** [comment]
@mcurry-rh @chaitanyaenr I understand from @sjstout That we want to revert the tested maximum numbers we report in the docs? Can you PTAL to make sure I understand the request correctly? 

Also, can we change the table to have two columns? _4.1 and 4.2 tested maximum_ and _4.3+ tested maximums_? It appears the numbers are the same for 4.3+.

**Comment by mcurry-rh** [comment]
LGTM

**Pull request merged**
