### PR TITLE
OSDOCS-10967: Update responsibility matrix

### PR DESCRIPTION
**Pull request by bhardesty**
Version(s):
* enterprise-4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-10967

Link to docs preview:
* Responsibility matrix: https://79796--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html
* Release management table: https://79796--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-release-management_rosa-policy-responsibility-matrix

QE review:
* Not required

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM. One style suggestion, your call on using it or not.

**Review by adellape — APPROVED** [review]

**Pull request merged**
