### PR TITLE
Fix tiny typo in other_api_objects.adoc

### PR DESCRIPTION
**Pull request by pabrahamsson**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM. Thank you!

**Comment by ahardin-rh** [comment]
No revision history needed.

**Comment by vikram-redhat** [comment]
@ahardin-rh - this is not in dedicated 3.6 stage. Is that right?

**Comment by ahardin-rh** [comment]
@vikram-redhat Good catch. Not sure how that was skipped, but here's the PR: https://github.com/openshift/openshift-docs/pull/7041

**Comment by vikram-redhat** [comment]
@ahardin-rh - np. I wasn't sure if it was just missed or it didn't apply. In any case, it can get published next week.

**Pull request merged**
