### PR TITLE
GitHub-31619: Updating login procedure to pass in username

### LINKED ISSUE #31619: [enterprise-4.7] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc
### Which section(s) is the issue in?

"Logging in to the OpenShift CLI"

### What needs fixing?

"oc login" no longer works in the "oc" cli 4.7 version

See...

https://bugzilla.redhat.com/show_bug.cgi?id=1920427

and...

https://github.com/openshift/oc/commit/cb6b001f198b6554a03738f355e69cc0d8e383b4

You must specify "--username=NAMEOFUSER" to log in.

The example output the the documentation is also incorrect.

If you type "oc login https:....." you will get:

```
oc login https://api.cluster-XXX.sandboxXXX.opentlc.com:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

You must obtain an API token by visiting https://oauth-openshift.apps.cluster-XXX.sandboxXXX.opentlc.com/oauth/token/request
```

Instead, you must type:

```
oc login --username=NAMEOFUSER https://api.cluster-XXX.sandboxXXX.opentlc.com:6443
```

Example:

```
oc login --username=NAMEOFUSER https://api.cluster-XXX.sandboxXXX.opentlc.com:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y 
Authentication required for https://api.cluster-XXX.sandboxXXX.opentlc.com:6443 (openshift)
Username: NAMEOFUSER
Password: 
```

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #31619.

Preview: https://deploy-preview-32261--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in_cli-developer-commands

### CODE REVIEW

**Review by codyhoag — APPROVED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review this update? Thanks!

Preview: https://deploy-preview-32261--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in_cli-developer-commands

**Pull request merged**
