### PR TITLE
BZ1989948: Added Important paragraph

### PR DESCRIPTION
**Pull request by darshan-nagaraj**
Added Important paragraph, which is required for sections containing Docker v2-2.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1989948#

OCP Version: 4.6+

Direct Doc Preview Links: 
https://deploy-preview-36594--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/samples-operator-alt-registry.html#installation-about-mirror-registry_samples-operator-alt-registry

https://deploy-preview-36594--osdocs.netlify.app/openshift-enterprise/latest/installing/installing-mirroring-installation-images.html#prerequisites_installing-mirroring-installation-images

https://deploy-preview-36594--osdocs.netlify.app/openshift-enterprise/latest/operators/admin/olm-restricted-networks.html#olm-mirror-catalog_olm-restricted-networks

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@mburke5678 I don't think this one was cherry picked to 4.10 (and so not carried forward to 4.11+ either). It was causing conflicts in the olm-mirroring-catalog.adoc file, which had since been resolved manually, so it likely won't pick cleanly anymore. But it's probably important for these changes to get brought forward, especially in the other files. 

Can you please look into it when you get a chance?

**Comment by mburke5678** [comment]
@bergerhoffer It appears the changes in this PR found their way into 4.10. 

installing-mirroring-installation-images.adoc is removed in 4.10+
[olm-mirroring-catalog.adoc](https://github.com/openshift/openshift-docs/pull/52631)
[installation-about-mirror-registry.adoc](https://github.com/openshift/openshift-docs/pull/41057)

My [manual  cherrypick PR](https://github.com/openshift/openshift-docs/pull/52957
) from today:
 
```
These merge commits were added into this branch cleanly.
There are no new changes to show.  

```

**Comment by bergerhoffer** [comment]
Thanks for looking into it @mburke5678. Folks must've included some of these during manual cherry picks then.

**Pull request merged**
