### PR TITLE
OBSDOCS-813: Update rhobs/prometheus-example-app version in monitoring docs to 0.4.2

### PR DESCRIPTION
**Pull request by machine424**
Version(s): 4.11+

Issue: https://issues.redhat.com//browse/OBSDOCS-813

Link to docs previews:
- https://71344--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/cluster_observability_operator/configuring-the-cluster-observability-operator-to-monitor-a-service
- https://71344--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/managing-metrics#deploying-a-sample-service_managing-metrics

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bburt-rh** [comment]
@machine424 - What version(s) of the OCP docs do these changes apply to?

**Comment by bburt-rh** [comment]
LGTM

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
