### PR TITLE
OSDOCS#10104:Removed warning from Networking docs as transparent forward proxies now supported in OSD/ROSA

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.15+

Issue:
[OSDOCS-10104](https://issues.redhat.com/browse/OSDOCS-10104)

Link to docs preview:
[Configuring a cluster-wide proxy](https://74572--ocpdocs-pr.netlify.app/openshift-rosa/latest/networking/configuring-cluster-wide-proxy.html#configuring-a-proxy-after-installation-ocm_configuring-a-cluster-wide-proxy)
[Creating a cluster on AWS with CCS](https://74572--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-an-aws-cluster#osd-create-aws-cluster-ccs_osd-creating-a-cluster-on-aws)

Peer reviewer:
- [x] Peer reviewer has approved this change.

SME review:
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by agantony** [comment]
LGTM!
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by oriAdler — APPROVED** [review]

**Comment by oriAdler** [comment]
@michaelryanmcneill is it worth mentioning that transparent proxies are only supported from version 4.12.0?

**Comment by michaelryanmcneill** [comment]
Since 4.11 installations are no longer supported, I think we are good to leave the issue silent.

**Comment by oriAdler** [comment]
LGTM

**Review by michaelryanmcneill — APPROVED** [review]
LGTM

**Comment by AedinC** [comment]
QE approval in comment in related Jira issue: https://issues.redhat.com/browse/OSDOCS-10104.

**Pull request merged**
