### PR TITLE
OSDOCS-10536: adds 4.14.26 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.14

Issue:
[OSDOCS-10536](https://issues.redhat.com/browse/OSDOCS-10536)

Link to docs preview:
[4.14.26 async release note](https://76222--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-14-release-notes.html#microshift-4-14-26-dp)
[Embedding MicroShift containers for offline deployments from 4.14.0 - 4.14.13](https://76222--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-14-release-notes.html#microshift-4-14-0-dp)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by aravipra** [comment]
hold

**Pull request merged**
