### PR TITLE
OSDOCS-3834: Adding ap-southeast-3 to support AWS regions

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
CP to 4.11

Issue:
This PR addresses [osdocs-3834](https://issues.redhat.com/browse/OSDOCS-3844)

Link to docs preview:
[AWS public regions](http://file.rdu.redhat.com/mpytlak/AWSRegion/installing/installing_aws/installing-aws-account.html#installation-aws-public_installing-aws-account)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@yunjiang29 PTAL. Just added a new AWS supported region per https://issues.redhat.com/browse/RFE-2511

**Comment by opayne1** [comment]
LGTM!

**Comment by mjpytlak** [comment]
@opayne1 please merge when you have a moment. Thank you.

**Pull request merged**
