### PR TITLE
OSDOCS-11884#updating 4.16 RN

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version:
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-11884

Link to docs preview:
https://83426--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-technology-preview-tables_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@makentenza, PTAL

**Comment by dfitzmau** [comment]
Thanks for this update, @brendan-daly-red-hat .

LGTM!

**Comment by soumyadbanik** [comment]
LGTM

**Review by makentenza — CHANGES_REQUESTED** [review]
Not sure why there are 3 different entries for OCI in the release notes:

- Installing OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI) with VMs
- Installing OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI) on bare metal
-  OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI)

Can we please remove the third one?

**Comment by pamoedom** [comment]
> Not sure why there are 3 different entries for OCI in the release notes:
> 
>     * Installing OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI) with VMs
> 
>     * Installing OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI) on bare metal
> 
>     * OpenShift Container Platform on Oracle® Cloud Infrastructure (OCI)
> 
> 
> Can we please remove the third one?

Hi @makentenza, the removal of that third entry is already part of this PR as requested, please double check.

**Comment by makentenza** [comment]
My bad, I saw 3 entries and I took that wrongly. Thanks for clarifying @pamoedom 

LGTM

**Review by makentenza — APPROVED** [review]

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
