### PR TITLE
modules/installation-aws-user-infra-rhcos-ami: Bump to RHCOS 44.81.202001030903.0

### PR DESCRIPTION
**Pull request by wking**
Catching up with openshift/installer@a8e9991876 (openshift/installer#2714) and its encryption fixes.  Generated with:

```console
$ git cat-file -p a8e9991876:data/data/rhcos.json | jq -r '.amis | to_entries | sort_by(.key)[] | "\n|`" + .key + "`\n|`" + .value.hvm + "`"'
```

and pasting the output into the module doc.

### CODE REVIEW

**Comment by wking** [comment]
4.3 "backport" is #18396, although since 4.4 and 4.3 have diverged in the installer it's not a clean cherrypick.  4.2 and 4.1 docs match the current installer tips for 4.1 and 4.2 releases.

**Comment by kalexand-rh** [comment]
@jianlinliu, do you agree?

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL?

**Comment by jianlinliu** [comment]
What version I gotten from https://github.com/openshift/installer/blob/release-4.3/data/data/rhcos.json is 43.81.201912131630.0, which is not consistent with this PR. QE always align with https://github.com/openshift/installer/blob/release-4.3/data/data/rhcos.json for our testing.

**Comment by wking** [comment]
> This is for 4.3, right?

This PR is for 4.4/master.  4.3 backport was #18396 (as mentioned [here][1]), but that's landed.  And I wouldn't be surprised if both have advanced further since ;).

[1]: https://github.com/openshift/openshift-docs/pull/18395#issuecomment-560949950

**Comment by wking** [comment]
New 4.3 bump: #18917

**Comment by wking** [comment]
This 4.4/master PR needs to be rerolled to catch up with openshift/installer@068e3df3f (openshift/installer#2826).  I'll do that tonight.

**Comment by jianlinliu** [comment]
> New 4.3 bump: #18917

If we plan to bump boot RHCOS image version, then I think https://github.com/openshift/installer/blob/release-4.3/data/data/rhcos.json also need a PR.
Now version is rhcos-43.81.201912131630.0 in https://github.com/openshift/installer/blob/release-4.3/data/data/rhcos.json, while version is 43.81.201911221453.0 in #18917.

**Comment by jianlinliu** [comment]
> This 4.4/master PR needs to be rerolled to catch up with [openshift/installer@068e3df](https://github.com/openshift/installer/commit/068e3df3f) ([openshift/installer#2826](https://github.com/openshift/installer/pull/2826)). I'll do that tonight.

Once ready, will check again.

**Comment by wking** [comment]
> ... while version is 43.81.201911221453.0 in #18917.

No, it's 43.81.201912131630.0, I just flubbed the commit message.  Fixed now.

**Comment by wking** [comment]
I've pushed 263f466f0 -> 0cc4ba1bb48, bumping this PR to 44.81.202001030903.0 to catch up with openshift/installer@068e3df3f.  Bahrain (me-south-1) is still getting worked on, but the installer side of that has landed via openshift/installer#2826, and we can drop it here if it turns out that other components are not ready for Bahrain in 4.4.

**Comment by jianlinliu** [comment]
> > ... while version is 43.81.201911221453.0 in #18917.
> 
> No, it's 43.81.201912131630.0, I just flubbed the commit message. Fixed now.

Acked.

**Comment by jianlinliu** [comment]
LGTM for this 4.4 PR.

**Pull request merged**
