### PR TITLE
OCPBUGS-44024 Clarify that bonding mode 6 is not supported 4.12+

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-44024

Link to docs preview: https://84464--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html#virt-example-bond-nncp_k8s_nmstate-updating-node-network-config

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@ahardin-rh just for your info/tracking

**Comment by jmanthei** [comment]
@zhaozhanqi for QE please

**Comment by jmanthei** [comment]
@EightZeroUnicorn please provide SME review

**Comment by zhaozhanqi** [comment]
@rbbratta @qiowang721 ^^ Could you help confirm this?

**Comment by EightZeroUnicorn** [comment]
@jmanthei looks good to me!

**Comment by obrown1205** [comment]
/label peer-review-done
/remove-label peer-review-in-progress
LGTM!

**Comment by jmanthei** [comment]
Legal approval ack from Alexis Mei (no github access). https://redhat-internal.slack.com/archives/D07V7BEBMLZ/p1730842844108119

**Pull request merged**
