### PR TITLE
TELCODOCS-2065 - PTP events REST API v1 is deprecated

### PR DESCRIPTION
**Pull request by aireilly**
Announce ORAN Events API v1 as deprecated in 4.17. Change management is complete.

Related: https://github.com/openshift/openshift-docs/pull/83619

Version(s):
enterprise-4.17+

Issue:
https://issues.redhat.com/browse/TELCODOCS-2065

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jzding — APPROVED** [review]
/lgtm

**Review by maxwelldb — COMMENTED** [review]
This seems sensible. @aireilly Is the removal of configuring-ptp.html supposed to be part of this PR?

**Comment by aireilly** [comment]
> This seems sensible. @aireilly Is the removal of configuring-ptp.html supposed to be part of this PR?

Yes - looks like an accidental commit of a build file from a previous PR :fearful:

**Pull request merged**
