### PR TITLE
Enterprise-4.8 - Update AWS AMIs based on recent boot image updates

### PR DESCRIPTION
**Pull request by EricPonvelle**

### CODE REVIEW

**Comment by EricPonvelle** [comment]
@miabbott Can you verify these AMIs?

**Review by kalexand-rh — COMMENTED** [review]
As long as QE approves it, it LGTM.

**Review by vikram-redhat — APPROVED** [review]

**Comment by vikram-redhat** [comment]
I have added my ack to this. AS soon as QE approves, we can merge this.

**Comment by yunjiang29** [comment]
@EricPonvelle , looks like `ap-northeast-3` is missing,  https://github.com/openshift/installer/blob/release-4.8/data/data/rhcos.json#L15-L17

**Comment by EricPonvelle** [comment]
@yunjiang29 thanks for the catch!

@vikram-redhat I think we can merge now

**Comment by yunjiang29** [comment]
@EricPonvelle LGTM

**Pull request merged**
