### PR TITLE
OSSMDOC-179

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSMDOC-179

Added warning to annotation section about creating your own resources.

### CODE REVIEW

**Review by dgn — APPROVED** [review]
lgtm, maybe add an easy rule of thumb ("anything prefixed maistra.io/ should not be used")

**Comment by JStickler** [comment]
I didn't really understand this warning and had to go back to the JIRA.  I was also confused because ALL of our YAML examples start with apiVersion: maistra.io/v2 and this seemed to be saying that all of those resources would be invalid.  So I took a whack at revising this.

`maistra.io/`  labels and annotations should never be included in user-created resources, as they indicate that the resources are generated and managed by the Operator.  If you are copying content from an Operator-generated resource when creating your own resources, do not include labels or annotations that start with `maistra.io/` or your resource will be overwritten or deleted by the Operator during the next reconciliation.

**Review by JStickler — APPROVED** [review]

**Pull request merged**
