### PR TITLE
OSDOCS-4024: Add SR-IOV supported device IDs

### PR DESCRIPTION
**Pull request by jboxman-rh**
This PR adds several additionally supported devices.

- https://issues.redhat.com/browse/OSDOCS-4024

Version(s):

- 4.12
- 4.11

Issue:

Link to docs preview: https://49777--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-done

**Comment by michaelryanpeter** [comment]
:+1: @JoeAldinger's review

**Comment by bergerhoffer** [comment]
@jboxman-rh This was marked for 4.11 too, does it still need to be CPd to 4.11?

**Pull request merged**
