### PR TITLE
RN edits

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.16 RN only

Issue: Minor edits per DPM

Link to docs preview:

QE review:
- None needed

Additional information:

### CODE REVIEW

**Comment by tmalove** [comment]
Preview link: https://78669--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-16-release-notes.html#virt-4-16-notable-technical-changes_virt-4-16-release-notes

/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
