### PR TITLE
OSDOCS-4322: Updates to Using the Node Tuning Operator topic

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-4322

Preview build:
https://53621--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/using-node-tuning-operator.html#custom-tuning-default-profiles-set_node-tuning-operator

### CODE REVIEW

**Comment by jmencak** [comment]
> Version(s):
> 4.8+

Note this change applies to 4.11+ only!

**Comment by ahardin-rh** [comment]
@jmencak Thanks for confirming! Labels updated. 
@liqcui Can you please provide QE review? Thanks!

**Pull request merged**
