### PR TITLE
fix for BZ#1762038 - wrong iptables table in the command, should be O…

### PR DESCRIPTION
**Pull request by vwalek**
fix for BZ#1762038 - wrong iptables table in the command, should be OS_FIREWALL_ALLOW

https://bugzilla.redhat.com/show_bug.cgi?id=1762038

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianlin, will you PTAL or suggest a different reviewer?

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL or suggest a different reviewer?

**Comment by jianlinliu** [comment]
@lihongan Could you help review this?

**Comment by lihongan** [comment]
LGTM. thank you.

**Pull request merged**
