### PR TITLE
OSDOCS-4378: updates table to include hybrid cloud

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-4378](https://issues.redhat.com//browse/OSDOCS-4378)

Version(s):
4.11+

Issue:
[Jira](https://issues.redhat.com/browse/OSDOCS-4378)

Link to docs preview:
[Preview](https://51815--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@JoeAldinger, this isn't for 4.12 as well? It's targeted at main, so we normally cherry-pick from there.

**Comment by JoeAldinger** [comment]
@jboxman-rh you are correct. I missed the +

**Comment by jboxman-rh** [comment]
@JoeAldinger LGTM

**Pull request merged**
