### PR TITLE
Update persistent_storage_nfs.adoc

### PR DESCRIPTION
**Pull request by erinboyd**
Updated nfs persistent storage with storage security settings @screeley44 @jeffvance

### CODE REVIEW

**Comment by screeley44** [comment]
@erinboyd  - not sure you are going to keep full pod def in the admin guide, but if you are noticed that line 73 should be:
      supplementalGroups: [100003]  -  can't be a string

**Comment by erinboyd** [comment]
@screeley44 updated document to remove groups as they will be added to the developer guide

**Comment by adellape** [comment]
> updated document to remove groups as they will be added to the developer guide

@erinboyd So just to confirm, the admin doesn't need to define the `securityContext.supplementalGroup` in the PV definition, and it should go in the pod spec instead, as shown in https://github.com/swagiaal/openshift-docs/blob/add-pod-sc-docs/admin_guide/persistent_storage/pod_security_context.adoc?

PR looks good tho, will merge once the Travis build passes.

**Comment by erinboyd** [comment]
@adellape Your assumption about the securityContext.supplementalGroup for the PV is correct. Thanks.

**Pull request merged**
