### PR TITLE
Moving section 'Higher workload density' from 'Virtual machines' to 'Post-installation'

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Copy of https://github.com/openshift/openshift-docs/pull/80259

CNV 4.16+
OCP 4.16+

Preview: https://80340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/post_installation_configuration/virt-configuring-higher-vm-workload-density

### CODE REVIEW

**Comment by sbeskin-redhat** [comment]
Approved by [fabiand](https://github.com/fabiand) and [enp0s3](https://github.com/enp0s3)

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-process

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-process

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Comment by jab-rh** [comment]
@sbeskin-redhat, looks like 4.16 fails the portal prow test: https://github.com/openshift/openshift-docs/pull/80350

**Pull request merged**
