### PR TITLE
Adding descheduler GA and profiles to release notes

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1652

Preview: https://odsocs-1652-rn--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-descheduler-ga

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra Here is the release notes for the descheduler profiles and going GA, if you can please review. Thanks!

Preview: https://odsocs-1652-rn--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-descheduler-ga

**Review by sfortner-RH — APPROVED** [review]
lgtm!

**Comment by kasturinarra** [comment]
@bergerhoffer one minor comment, should we change the Title to Descheduler and profiles GA, instead of Descheduler profiles and GA ?

**Comment by bergerhoffer** [comment]
> @bergerhoffer one minor comment, should we change the Title to Descheduler and profiles GA, instead of Descheduler profiles and GA ?

@kasturinarra That sounds good, I made that update, thanks!

**Pull request merged**
