### PR TITLE
Removed the "catalog" column from the compatability matrix for consis…

### PR DESCRIPTION
**Pull request by LunguTheEngineer**
Jira issue : [OCPBUGS-17885](https://issues.redhat.com/browse/OCPBUGS-17885)

Aligned team: DevTools

OCP Version(s): 4.10 and later

Docs preview: [64066-DocPreview](https://64066--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/op-release-notes#compatibility-support-matrix_op-release-notes)

SME review: @piyush-garg 

QE review: @ppitonak 

Peer review: @Srivaralakshmi

### CODE REVIEW

**Comment by piyush-garg** [comment]
lgtm cc @vdemeester

**Review by vdemeester — APPROVED** [review]
Thanks 👼🏼

**Review by ppitonak — APPROVED** [review]

**Comment by ppitonak** [comment]
lgtm

**Review by Srivaralakshmi — APPROVED** [review]
@masauso-lungu Approved!

**Comment by jeana-redhat** [comment]
@masauso-lungu nice work! It looks like versions 4.10 and 4.11 need manual cherrypicks, but I will get 4.12 merged when they finish building.

**Pull request merged**
