### PR TITLE
ocp-glines-conscious-lang-machines: Updated the concious lang. sectio…

### PR DESCRIPTION
**Pull request by dfitzmau**
Internal OCP docs team update. No Jira required. 

Version(s):
Main

Link to docs preview: [Using conscious language](http://file.emea.redhat.com/dfitzmau/ocp-glines-conscious-lang-machines/doc_guidelines.html#using-conscious-language:~:text=You%20can%20replace,and%20infra%20role.)

Additional resources:

[OCP Guidelines](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#using-conscious-language)

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM

**Comment by dfitzmau** [comment]
Thanks, @bmcelvee . I see that my PR is blocked, so do you need to approve the PR through the Files changed tab?

**Review by bmcelvee — APPROVED** [review]

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
