### PR TITLE
OSDCOS#9316:Correct AWS Block in-tree migration info

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-9316

Link to docs preview: https://70255--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-aws

QE review:
- [ ] QE has approved this change.

Additional information:

**PTAL**: @gcharto @tsmetana

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
Same feedback as other similar PRs

**Comment by gcharot** [comment]
lgtm

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
