### PR TITLE
[OSDOCS-6893]Field presentation mistake in example, string instead of list of strings

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-6893
Link to docs preview:

https://69952--ocpdocs-pr.netlify.app/openshift-rosa/latest/nodes/cma/nodes-cma-autoscaling-custom-install#sd-nodes-cma-autoscaling-custom-install_nodes-cma-autoscaling-custom-install
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
SME has approved. https://issues.redhat.com/browse/OSDOCS-6893?focusedId=23751403&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23751403

**Comment by mletalie** [comment]
Hello @xueli181114 ,
    Could I get a peer review  for this PR when you get a moment? Thanks!

**Comment by mletalie** [comment]
Hello @weinliu, 
Could I please get a QE review for this PR? Thanks!

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Comment by mburke5678** [comment]
@mletalie @weinliu Can we CP this PR to [4.12](https://docs.openshift.com/container-platform/4.12/nodes/cma/nodes-cma-autoscaling-custom-install.html#nodes-cma-autoscaling-custom-install_nodes-cma-autoscaling-custom-install) and [4.13](https://docs.openshift.com/container-platform/4.13/nodes/cma/nodes-cma-autoscaling-custom-install.html#nodes-cma-autoscaling-custom-install_nodes-cma-autoscaling-custom-install) also? The error appears there also.

**Pull request merged**
