### PR TITLE
ocpbugs21585: changing label for selector node

### PR DESCRIPTION
**Pull request by DCChadwick**
Version(s): 4.11+

Issue: OCPBUGS-21585

Link to docs preview: https://74787--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-creating-infrastructure-nodes.html#creating-an-infra-node_creating-infrastructure-nodes

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by DCChadwick** [comment]
@sunilcio This PR is ready for QE review.

**Comment by sunilcio** [comment]
@sunzhaohua2 Is your team correct team to review this?

**Comment by DCChadwick** [comment]
I got the QE LGTM from Zhaohua Sun via Slack.

/label peer-review-needed

**Review by jldohmann — APPROVED** [review]
nice work! LGTM

**Pull request merged**
