### PR TITLE
EO - ClusterLogging Status messages when cluster logging is not functional

### PR DESCRIPTION
**Pull request by mburke5678**
https://jira.coreos.com/browse/LOG-339

### CODE REVIEW

**Comment by mburke5678** [comment]
@jcantrill @anpingli I would appreciate any thoughts on how best to present this information. What do the users need to know about the various status information they can get?

**Comment by jcantrill** [comment]
@ewolinetz can you provide the high level list of status items.  Maybe we should not identify any of them specifically and just tell user's how to see the operator status?

**Comment by ewolinetz** [comment]
We will expose any events from the scheduler specific to a pod such as:
 * Container Waiting (for both the ES and Proxy containers)
 * Container Terminated (for both the ES and Proxy containers)
 * Pod unschedulable

We will also display conditions regarding the ES node storage. If the threshold setting is enabled (which is by default), we will update the conditions when the low and high watermark has been met.

All of this will be available in the `Status.Nodes` section of the `Elasticsearch` object.

**Comment by mburke5678** [comment]
@QiaolingTang Please take a look. I am going to merge for beta 3 and can follow changes in a follow up.

**Comment by mburke5678** [comment]
Follow-up to move information into their own files.
https://github.com/openshift/openshift-docs/pull/14370

**Comment by mburke5678** [comment]
Reviewed via https://github.com/openshift/openshift-docs/pull/14456

**Pull request merged**
