### PR TITLE
Document quota support for requests.storage

### PR DESCRIPTION
**Pull request by derekwaynecarr**
/cc @ncdc @deads2k @pmorie

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
This should not be merged until OpenShift rebases on Kubernetes 1.4.

**Comment by qwang1** [comment]
@derekwaynecarr  Seems there is a markdown typo. Is the addition contained in the table?

**Comment by derekwaynecarr** [comment]
Yes.  Will fix.

**Comment by adellape** [comment]
@derekwaynecarr I take it this can merge now?

**Comment by derekwaynecarr** [comment]
this can merge now.

**Pull request merged**
