### PR TITLE
OSDOCS-11295 Kube bump to 1.30 in 4.17 RNs

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.17

Issue: [OSDOCS-11295](https://issues.redhat.com/browse/OSDOCS-11295)

Link to [docs preview:](https://80258--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-about-this-release_release-notes)

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by cbippley** [comment]
@kasturinarra Can you PTAL?

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Pull request merged**
