### PR TITLE
OSDOCS-3849 updated maxUnavailable field

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-3849

Link to docs preview:
[Modifying the number of unavailable worker nodes](http://file.rdu.redhat.com/antaylor/osdocs-3849/scalability_and_performance/recommended-host-practices.html#modify-unavailable-workers_recommended-host-practices)

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@paigerube14 please review. Thanks!

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
