### PR TITLE
TELCODOCS-971 Make Enhanced SRO cluster upgrade support information m…

### PR DESCRIPTION
**Pull request by slovern**
[TELCODOCS-971](https://issues.redhat.com//browse/TELCODOCS-971) Make Enhanced SRO cluster upgrade support information more findable/accessible

Version(s): 4.12, 4.11

Issue: https://issues.redhat.com/browse/TELCODOCS-971

Link to docs preview: https://52855--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#additional-resources_special-resource-operator

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bthurber** [comment]
This will be for 4.11 only as there is no SRO in 4.12.

/lgtm

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
