### PR TITLE
[enterprise-4.11] Add remaining NE RN entries

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11

Issue:
- https://issues.redhat.com/browse/NE-813
- https://issues.redhat.com/browse/NE-585

Link to docs preview:
- http://file.rdu.redhat.com/jdohmann/OSDOCS-3419-RN/release_notes/ocp-4-11-release-notes.html#ocp-4-11-ne-haproxy-update
- http://file.rdu.redhat.com/jdohmann/OSDOCS-3419-RN/release_notes/ocp-4-11-release-notes.html#ocp-4-11-ne-ingress-health-check

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi PTAL for QE ack, thank you!

**Comment by ahardin-rh** [comment]
LGTM

**Comment by mffiedler** [comment]
LGTM for GA exception approval from QE.   @lihongan please comment if there is anything that needs to change or be updated post GA - I know Shudi is out.

**Review by mffiedler — APPROVED** [review]

**Review by ahardin-rh — APPROVED** [review]

**Comment by ShudiLi** [comment]
/label qe-approved
@jldohmann thanks

**Pull request merged**
