### PR TITLE
changed the var to caps

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.6+
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2065787)
- [Preview](http://file.del.redhat.com/asakthiv/BZ2065787/migration_toolkit_for_containers/advanced-migration-options-mtc.html)

### CODE REVIEW

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by Amrita42** [comment]
@pranavgaikwad ptal

**Review by sheriff-rh — COMMENTED** [review]
LGTM! Please ping the peer review squad when you are ready for merge.

**Review by pranavgaikwad — APPROVED** [review]

**Pull request merged**
