### PR TITLE
OSDOCS#7755: Adding documentation to support MemoryPressure notification

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
4.13, 4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-7755

Link to docs preview:
https://64892--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/nodes-cluster-resource-configure

QE review:
- [x] QE has approved this change.

Additional information:
MOBB-F2F

### CODE REVIEW

**Comment by laubai** [comment]
Noting that QE has approved this content (@tsze-redhat) for this notification in person

**Review by arendej — COMMENTED** [review]
lgtm

**Pull request merged**
