### PR TITLE
Trello-570-Bug 1511266 Registry Hard Prune Procedure Command Fix

### PR DESCRIPTION
**Pull request by bmcelvee**
https://trello.com/c/Kf4mvSgt/570-document-registry-hard-prune-procedure

https://bugzilla.redhat.com/show_bug.cgi?id=1511266

### CODE REVIEW

**Comment by dongboyan77** [comment]
LGTM, thanks

**Comment by bmcelvee** [comment]
@openshift/team-documentation please peer review (very minor change)

**Review by ncbaratta — APPROVED** [review]
LGTM

**Comment by bmcelvee** [comment]
Thanks, @dongboyan77 and @nengard!

**Comment by bmcelvee** [comment]
No revision history required.

**Pull request merged**
