### PR TITLE
Bug#1581015 - fixes - removed /etc/sysconfig/atomic-openshift-master from list

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1581015

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@wmengRH is this applicable to OCP 3.6 and OCP 3.7 ?

**Comment by wmengRH** [comment]
yes. OCP 3.6 and OCP 3.7, too

**Pull request merged**
