### PR TITLE
OSDOCS-3194: Adding AWS on ARM as a choice target cluster

### PR DESCRIPTION
**Pull request by kelbrown20**
https://issues.redhat.com/browse/OSDOCS-3191
For Versions: 4.10+

Preview: https://deploy-preview-40786--osdocs.netlify.app/openshift-enterprise/latest/installing/installing-preparing.html

### CODE REVIEW

**Comment by kelbrown20** [comment]
@SaravanaStorageNetwork. Thank you for your feedback! That change can be found in this PR: https://github.com/openshift/openshift-docs/pull/41036/files

**Comment by kelbrown20** [comment]
Going to change AWS (ARM) to AWS (aarch64)

**Comment by jeffdyoung** [comment]
> 

Yeah, `arm64` is cleaner and consistent with the use of `arm64` in the install-config.yaml

**Comment by jeffdyoung** [comment]
👍 from devel.

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
