### PR TITLE
[SRVKE-1276]: Add trigger event delivery order docs

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+

Issue:
https://issues.redhat.com/browse/SRVKE-1276

Link to docs preview:
- https://51031--docspreview.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-event-delivery.html#trigger-event-delivery-config_serverless-event-delivery
- https://51031--docspreview.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-triggers.html#trigger-event-delivery-config_serverless-triggers
- https://51031--docspreview.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-triggers.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by matzew** [comment]
LGTM

**Comment by jrangelramos** [comment]
QE Approved

**Review by Wiharris — COMMENTED** [review]
It looks like you have 2 commits and may need to squash in order to have 1 commit.

**Comment by abrennan89** [comment]
@Wiharris done!

**Review by Wiharris — COMMENTED** [review]
LGTM! 

Someone else from the peer review squad will complete the review as I am still on-boarding. :)

**Pull request merged**
