### PR TITLE
removed multi-zone configuration workaround

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Removed multi-zone configuration workaround, as it is no longer required.

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
[Document: Enable cloudprovider configuration in admission controller](https://trello.com/c/3yOvEDP3/468-document-enable-cloudprovider-configuration-in-admission-controller)

**Comment by gnufied** [comment]
lgtm

**Comment by gaurav-nelson** [comment]
@bfallonf review please

**Comment by bfallonf** [comment]
Looks good @gaurav-nelson :shipit:

**Comment by gaurav-nelson** [comment]
No Rev History needed.

**Pull request merged**
