### PR TITLE
CNV 33127: Release note: NEW (SR-IOV network interface hot-plug for VMs)

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.15

Issue: [CNV-33127](https://issues.redhat.com/browse/CNV-33127)

Link to docs preview: See the release note in the [Web console](https://72085--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-web) section.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
@pcbailey, Can you please review this PR for a release note update? Thanks!

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Review by JoeAldinger — APPROVED** [review]

**Comment by aspauldi** [comment]
@JoeAldinger, I see that this PR is approved but not yet merged. Is there anything else I need to do? Thanks.

**Pull request merged**
