### PR TITLE
Increment copyright year 2020

### PR DESCRIPTION
**Pull request by bobfuru**
This PR updates the copyright year to 2020 for docs.openshift.com. ([PR 13383](https://github.com/openshift/openshift-docs/pull/13383) was used as reference.)

Merge to `master` only and CP to branches.

@openshift/team-documentation PTAL

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
Just need to add the applicable version label(s).

**Comment by bobfuru** [comment]
> Just need to add the applicable version label(s).

It's only being merged to `master`, which is why I didn't add version labels. I've often wondered why we don't have a `master` label.

**Comment by bobfuru** [comment]
@vikram-redhat PTAL to confirm I won't need to CP to branches. Thanks.

**Comment by vikram-redhat** [comment]
@bobfuru it needs to be CPed to all branches.

**Pull request merged**
