### PR TITLE
Swaps references of SPDY with HTTP2

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s): 4.6+

Issue: https://github.com/openshift/openshift-docs/issues/45628

Link to docs preview: https://deploy-preview-45734--osdocs.netlify.app/openshift-enterprise/latest/nodes/containers/nodes-containers-port-forwarding.html#nodes-containers-port-forwarding-protocol_nodes-containers-port-forwarding, 

https://deploy-preview-45734--osdocs.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/installing-mtc.html#migration-configuring-proxies_installing-mtc

Additional information: Pending QE

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
/LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
