### PR TITLE
OADP-3365: Fix issues in OADP docs

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [OADP-3365](https://issues.redhat.com/browse/OADP-3365)

#### Versions

OCP 4.12 → branch/enterprise-4.12
OCP 4.13 → branch/enterprise-4.13
OCP 4.14 → branch/enterprise-4.14
OCP 4.15 → branch/enterprise-4.15

### Preview

* [OADP ROSA docs](https://70486--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications)

#### Copy fix

* [Preparing AWS credentials for OADP](https://70486--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications#preparing-aws-credentials-for-oadp_oadp-rosa-backing-up-applications)

### QE review

@PrasadJoshi12 [X ] - QE Approved

### CODE REVIEW

**Comment by anarnold97** [comment]
@PrasadJoshi12 - added indents through the code blocks. Pretty sure i have them all now

**Review by PrasadJoshi12 — APPROVED** [review]

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
