### PR TITLE
Updating to use an example that is not the default

### PR DESCRIPTION
**Pull request by bergerhoffer**
Per https://issues.redhat.com/browse/OSDOCS-1788?focusedCommentId=18813494&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18813494

Preview: https://deploy-preview-35510--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-profiles.html#nodes-scheduler-profiles-configuring_nodes-scheduler-profiles

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra for review please!

Preview: https://deploy-preview-35510--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-profiles.html#nodes-scheduler-profiles-configuring_nodes-scheduler-profiles

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
Didn't meant to cherry pick to 4.6. The failure above is fine, since the docs don't exist in 4.6.

**Pull request merged**
