### PR TITLE
BZ#1823387 Add networking and port info for Azure/GCP UPI

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1823387

Previews:
- [Azure UPI](https://deploy-preview-25083--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-network-user-infra_installing-azure-user-infra)
- [GCP UPI](https://deploy-preview-25083--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-network-user-infra_installing-gcp-user-infra)
- [GCP UPI shared VPC](https://deploy-preview-25083--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-network-user-infra_installing-gcp-user-infra-vpc)
- [GCP UPI restricted](https://deploy-preview-25083--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html)

### CODE REVIEW

**Comment by codyhoag** [comment]
@e-tienne @tsze-redhat can you confirm this general networking information I included for Azure and GCP UPI sections? This info is available in other cloud provider UPI sections, but was never included for Azure/GCP:

- **Azure**
    - [Azure UPI with ARM Templates](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-infrastructure-user-infra_installing-azure-user-infra)
- **GCP**
    - [GCP UPI with Deployment Manager templates](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-infrastructure-user-infra_installing-gcp-user-infra)
    - [GCP UPI with Deployment Manager templates and shared VPC](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-infrastructure-user-infra_installing-gcp-user-infra-vpc)
    - [GCP restricted network](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-infrastructure-user-infra_installing-restricted-networks-gcp)

**Comment by codyhoag** [comment]
@e-tienne @tsze-redhat bump. Let me know if these inclusions are good to go. Thanks!

**Comment by codyhoag** [comment]
FYI, these are the modules included in those doc assemblies:

- https://github.com/openshift/openshift-docs/blob/master/modules/installation-infrastructure-user-infra.adoc
- https://github.com/openshift/openshift-docs/blob/master/modules/installation-network-user-infra.adoc
- https://github.com/openshift/openshift-docs/blob/master/modules/installation-dns-user-infra.adoc

The preview links I provided previously reference the starting point for those three sections, which are listed consecutively.

**Comment by e-tienne** [comment]
Hello Cody, 

I would remove the `Creating the user-provisioned infrastructure` as I find it confusing. Most of those steps are either already in this document or just not required for Azure.

I think that we should say that if you follow the steps below without any customization, it will cover those requirements.

LGTM for the requirements sections.

**Comment by codyhoag** [comment]
@fabianofranz what are your thoughts on the three UPI networking sections being included for Azure UPI docs?

https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-infrastructure-user-infra_installing-azure-user-infra

**Comment by codyhoag** [comment]
@fabianofranz thoughts on the three UPI networking sections being included for Azure UPI docs?

 - [Azure UPI with ARM Templates](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-infrastructure-user-infra_installing-azure-user-infra)

@tsze-redhat thoughts on the UPI networking and port info being included for GCP?
 - [GCP UPI with Deployment Manager templates](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-infrastructure-user-infra_installing-gcp-user-infra)
- [GCP UPI with Deployment Manager templates and shared VPC](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-infrastructure-user-infra_installing-gcp-user-infra-vpc)
- [GCP restricted network](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-infrastructure-user-infra_installing-restricted-networks-gcp)

FYI: these are the modules included in those doc assemblies:

https://github.com/openshift/openshift-docs/blob/master/modules/installation-infrastructure-user-infra.adoc
https://github.com/openshift/openshift-docs/blob/master/modules/installation-network-user-infra.adoc
https://github.com/openshift/openshift-docs/blob/master/modules/installation-dns-user-infra.adoc

**Comment by fabianofranz** [comment]
LGTM, @codyhoag sorry about missing this the first time you pinged me. ;-)

**Comment by codyhoag** [comment]
@gpei can you verify the UPI networking and port info being included for GCP?

- [GCP UPI with Deployment Manager templates](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-infrastructure-user-infra_installing-gcp-user-infra)
- [GCP UPI with Deployment Manager templates and shared VPC](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-infrastructure-user-infra_installing-gcp-user-infra-vpc)
- [GCP restricted network](https://port-info-for-azure-gcp--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-infrastructure-user-infra_installing-restricted-networks-gcp)

FYI: these are the modules included in those doc assemblies:

https://github.com/openshift/openshift-docs/blob/master/modules/installation-infrastructure-user-infra.adoc
https://github.com/openshift/openshift-docs/blob/master/modules/installation-network-user-infra.adoc
https://github.com/openshift/openshift-docs/blob/master/modules/installation-dns-user-infra.adoc

**Comment by gpei** [comment]
@tsze-redhat Could you help on the above sections which are related to GCP?

**Comment by staebler** [comment]
None of those sections make sense to me to include for either Azure or GCP. They mostly pertain to on-prem installations where the user needs to manually provide a lot more infrastructure. For the cloud environments, either the cloud provider provides the feature or the provisioning code that we are providing (eg, the python scripts for GCP) take care of it.

**Comment by staebler** [comment]
Let's take for example, the DNS requirements. The last three rows are not needed for cloud environments. I already get asked fairly regularly for on-prem installations whether the PTR records for machines are needed; I would not want to have to field that question for clouds as well.

**Comment by codyhoag** [comment]
@staebler I've updated this PR to only include the networking port and load balancer info for Azure/GCP. I added conditionals to exclude info that should be avoided for the cloud providers, but this needs a close review to ensure I excluded/included the right info specific to the referenced clouds. Thanks!

**Review by staebler — COMMENTED** [review]
LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
