### PR TITLE
bug 1685731 - broken link to reference example

### PR DESCRIPTION
**Pull request by bgaydosrh**
Fixing bug https://bugzilla.redhat.com/show_bug.cgi?id=1685731

### CODE REVIEW

**Comment by ousleyp** [comment]
LGTM

**Comment by vikram-redhat** [comment]
@bgaydosrh I mentioned it in our chat but will leave here for reference as well. Make sure to only merge if the build passes, not before. If the build fails, you should fix the cause and then resubmit.

cc: @ousleyp

**Pull request merged**
