### PR TITLE
Differentiate current BM / IBM Cloud installation process

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: https://deploy-preview-39716--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_on_ibm_cloud/install-ibm-cloud-prerequisites.html

### CODE REVIEW

**Comment by codyhoag** [comment]
@johnwilkins this PR is a stab in the dark for possible rename for the current Telco docs for BM/IBM Cloud installation. Feel free to suggest something more accurate; this was just to get the ball rolling.

Some background: I'm preparing docs for the generic process for installing OCP on IBM Cloud ([CORS-1513](https://issues.redhat.com/browse/CORS-1513)). I feel the future title for that would clash with the current one we have up for a different use case. Hoping to give a bit more context in the top title so they're easily distinguishable.

So the initial proposal for titles:
- Installing bare metal clusters on IBM Cloud (current doc title to hopefully tweak for more context)
- Installing on IBM Cloud (coming soon)

Let me know your thoughts and any counter proposals. Just hoping to present two titles that are easily distinguishable. Thanks!

**Comment by codyhoag** [comment]
@johnwilkins what are your thoughts on this proposed title change?

**Comment by racedo** [comment]
@johnwilkins the two options describe it as stated but without context isn't self-explanatory:

Current: Install on bare metal provided by IBM Cloud
New addition: Install on IBM Cloud

/cc @makentenza

**Comment by makentenza** [comment]
@mjpytlak can we use this PR or the one for IBM Cloud #42293 to get consistent link titles for the installation methods? So far all had the "Installing on..." convention and now we are adding new ones with "Deploy installer-provisioned clusters on..."

Screenshot 2022-02-24 at 10 33 48

**Comment by mjpytlak** [comment]
> @mjpytlak can we use this PR or the one for IBM Cloud #42293 to get consistent link titles for the installation methods? So far all had the "Installing on..." convention and now we are adding new ones with "Deploy installer-provisioned clusters on..."
> Also, we have 2 entries for BM:
> 
> * Installing on bare metal
> * Deploying installer-provisioned clusters on bare metal
> 
> I can open a BZ if you prefer to get this sorted out

@makentenza Ahead of Cody leaving, he had been coordinating with @johnwilkins  to work through this. I had a chance to talk to John yesterday. It would appear that he and @racedo are working through this now. I would prefer to leave the IBM Cloud IPI doc PR separate from this effort, as I am working through final SME comments and a peer review to get that content merged. @johnwilkins feel free to reach out to me if you would like to sync on your title updates.

**Review by makentenza — APPROVED** [review]
LGTM

**Comment by makentenza** [comment]
That's fine @mjpytlak, I'll create a BZ to review the inconsistency of the entries in topic_map

**Comment by johnwilkins** [comment]
@makentenza I corresponded with @racedo on this, and I am fine with the change in this PR. The basic difference with IPI is that my procedure does require a provisioner node, and some changes to the BMC. So it differs from other procedures that don't use a provisioner node. Feel free to make this change.

**Comment by bmcelvee** [comment]
This fix was implemented inhttps://github.com/openshift/openshift-docs/pull/42578. Closing this PR.

**Pull request closed without merging**
