### PR TITLE
Bug 1322352, added Browser Requirements section

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1322352

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jwforres Can you please take a look and let me know if this looks correct? Thanks!

**Comment by ahardin-rh** [comment]
@adellape @tnguyen-rh @bfallonf @tnguyen-rh PTAL as well. Information sourced from here: https://mojo.redhat.com/docs/DOC-1069079
Thanks!

**Comment by ahardin-rh** [comment]
Latest matrix per Jessica: https://mojo.redhat.com/docs/DOC-1013063. She suggests "latest stable" release instead of exact browser version. I will make edits per her comments.

**Comment by ahardin-rh** [comment]
@jwforres thanks for your suggestions. Edits complete.

**Comment by bfallonf** [comment]
@ahardin-rh Looks good to me!

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../getting_started/developers/developers_console.html[Getting Started for Developers: Web Console]
|Added a link:../getting_started/developers/developers_console.html#browser-requirements[Browser Requirements] section, which outlines browser versions and operating systems that can be used to access the Web Console.
%

**Pull request merged**
