### PR TITLE
OSDOCS-4591: Adding to install the resources as next steps

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4298

Link to docs preview:
https://54201--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-oci-format_installing-mirroring-disconnected

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Looks great!
/lgtm

**Review by sherine-k — APPROVED** [review]
Perfect!
Let's merge it once https://github.com/openshift/oc-mirror/pull/543 merges

**Comment by sherine-k** [comment]
https://github.com/openshift/oc-mirror/pull/543 merged! we're good to go

**Comment by bergerhoffer** [comment]
Thanks @sherine-k! Merging

**Pull request merged**
