### PR TITLE
2059159: Fixing API version in YAML file

### PR DESCRIPTION
**Pull request by stoobie**
Applies to 4.6+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2059159
QE ack required.
Preview Link:

### CODE REVIEW

**Comment by stoobie** [comment]
@dymurray Please review.

**Comment by dymurray** [comment]
@stoobie looks good! Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM - please stand by for merge as we are in merge freeze now.

**Comment by stoobie** [comment]
@GroceryBoyJr Can this be merged yet? Is the merge freeze over?

**Comment by mburke5678** [comment]
/enterprise-4.6

**Pull request merged**
