### PR TITLE
[OCPBUGS-25925]

### PR DESCRIPTION
**Pull request by krishnanshruthi**
Version(s):
4.14+

Issue: https://issues.redhat.com/browse/OCPBUGS-25925

Link to docs preview:
https://69740--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-configuring 

QE review:
- [x] QE has approved this change.

cc: @SNiemann15

### CODE REVIEW

**Comment by SNiemann15** [comment]
/lgtm

The preview link doesn't work.  Please update the link before asking QE for approval.

**Comment by veera-damisetti** [comment]
Approved

**Comment by krishnanshruthi** [comment]
@alishaIBM Gentle reminder to pls get this PR reviewed from the Power team. thank you!

**Comment by alishaIBM** [comment]
@dharaneeshvrd request you to approve for IBM Power. Thanks.

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done

@krishnanshruthi will you squash your commits before requesting a merge. Thanks!

**Comment by krishnanshruthi** [comment]
> /remove-label peer-review-in-progress /label peer-review-done
> 
> @krishnanshruthi will you squash your commits before requesting a merge. Thanks!

Yes, will squash my commits. Thanks!

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging!

**Pull request merged**
