### PR TITLE
[RHACS] Update Alpine Linux version format in release notes

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://issues.redhat.com/browse/ROX-16826

Added an item under Notable technical changes listing the change. 

Preview: https://75329--ocpdocs-pr.netlify.app/openshift-acs/latest/release_notes/44-release-notes.html#notable-technical-changes_release-notes-44

Cherrypick:
- `rhacs-docs-4.4`

---

NOTE:

- This PR is for RHACS docs.
- It doesn't require any special labels or milestones.

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @gaurav-nelson . WOuld a change management be need for this update (it's a change to existing release notes)?

See the [Change Management](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit?pli=1#bookmark=id.khm4rxl210qm) section in the COP Docs Manual.

**Comment by gaurav-nelson** [comment]
Thank you @dfitzmau This is a minor change so we don't need to follow that. I'll update the branch to fix the conflicts.

**Pull request merged**
