### PR TITLE
OCPRHV-426-master

### PR DESCRIPTION
**Pull request by stoobie**
https://issues.redhat.com/browse/OCPRHV-426

This applies only to [enterprise-4](https://issues.redhat.com/browse/enterprise-4).7.

### CODE REVIEW

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Comment by sfortner-RH** [comment]
QE and SME acked in this related PR: https://github.com/openshift/openshift-docs/pull/28320.

**Comment by mburke5678** [comment]
@stoobie May I ask why you changed the title of the `installing-rhv-default.adco` fire from `{rh-virtualization}` to `RHV`? It is the only document in the set that uses the hard-coded `RHV` in the title instead of the variable.

**Comment by stoobie** [comment]
> @stoobie May I ask why you changed the title of the `installing-rhv-default.adco` fire from `{rh-virtualization}` to `RHV`? It is the only document in the set that uses the hard-coded `RHV` in the title instead of the variable.

@mburke5678 This is embarrassing, but I honestly don't remember...you're right, that does not seem to be correct in that instance...

@janoszen Was that change something you asked me to do, or was that just me fat thumbing something?

**Pull request merged**
