### PR TITLE
Fix migration-mtc-workflow.adoc

### PR DESCRIPTION
**Pull request by ptux**
Version(s):

All

Issue:

PVs are cluster-scoped and PVCs are namespace-scoped resources.

### CODE REVIEW

**Comment by ptux** [comment]
@RichardHoch 

this is a friendly reminder.
Cloud you review this?

**Comment by RichardHoch** [comment]
@ptux My apologies; I must not have seen the notification from @kalexand-rh . Let me check this out and, if needed, add it to our queue. Thanks for bringing it to our attention.

**Comment by anarnold97** [comment]
JIRAPROJECT-MIG-1300

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by RichardHoch** [comment]
MTC 1.x; OCP 4.9+ -- that is, ready for immediate addition to MTC documentation.

**Comment by ptux** [comment]
@RichardHoch 
This is a friendly reminder.

**Comment by RichardHoch** [comment]
MTC 1.x; OCP 4.9+ -- that is, ready for immediate addition to MTC documentation.

**Comment by RichardHoch** [comment]
@ptux Sending it again for inclusion; this time with command to bot typed correctly.

**Review by RichardHoch — APPROVED** [review]

**Comment by RichardHoch** [comment]
MTC 1.x; OCP 4.9+ -- that is, ready for immediate addition to MTC documentation.
QE passed.

**Comment by RichardHoch** [comment]
@ptux This error was fixed in https://github.com/openshift/openshift-docs/pull/55466. Please let me know if that PR did not solve the problem.

**Comment by RichardHoch** [comment]
OCP docs team -- this PR does not need review.

**Comment by gaurav-nelson** [comment]
Closing this one, already done via https://github.com/openshift/openshift-docs/pull/55466

**Comment by RichardHoch** [comment]
Thanks @gaurav-nelson -- sorry for the confusion. I didn't have an active Close button for some reason or I would have closed it myself.

**Pull request closed without merging**
