### PR TITLE
Logging updated workflow to create CL instance

### PR DESCRIPTION
**Pull request by mburke5678**
Updates to include changes to the process for creating a Cluster Logging instance/CR as seen in newest Dev Preview build 0.16.1, `oc version` v4.0.0-alpha.0+ba88cb2-1091.

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli  PTAL

**Comment by anpingli** [comment]
@mburke5678 
The example is out of date in Verify the install.  you can use the following

#oc get pods -n openshift-logging
NAME                                            READY   STATUS    RESTARTS   AGE
cluster-logging-operator-bd84d7858-qpssx        1/1     Running   0          50m
elasticsearch-cdm-9iocf35u-1-5b5fcbb696-pplgx   2/2     Running   0          38m
elasticsearch-cdm-9iocf35u-2-55b8c95d66-q87rs   2/2     Running   0          38m
elasticsearch-cdm-9iocf35u-3-6855b5ff4c-wpq49   2/2     Running   0          38m
fluentd-8gwpz                                   1/1     Running   0          38m
fluentd-bt4c8                                   1/1     Running   0          38m
fluentd-c5bvn                                   1/1     Running   0          38m
fluentd-cf858                                   1/1     Running   0          38m
fluentd-kwzf2                                   1/1     Running   0          38m
fluentd-nxtld                                   1/1     Running   0          38m
kibana-f5db689bd-pvhr6                          2/2     Running   0          38m

**Comment by mburke5678** [comment]
@anpingli Thank you for catching the change to the output! I didn't notice the change.

**Comment by anpingli** [comment]
@mburke5678   It is better the replace 0/2 with 2/2 .   0/2 means there are 2 containers in pos, 0 are ready. 2/2 means there are 2 containers, 2 ready.

elasticsearch-cdm-clientdatamaster-0-1-7c78b-qwpz7   0/2     Running             0          35s
->
elasticsearch-cdm-clientdatamaster-0-1-7c78b-qwpz7   2/2     Running             0          35s

**Comment by mburke5678** [comment]
@anpingli Thanks for pointing out the `0/2` Ready status.

I updated the full `oc get pods` output, as some of the Fluentd pods were `1/2` and the Kibana was `0/2`. All pods are up in the example now.

**Pull request merged**
