### PR TITLE
[OSDOCS-5603] ShiftStack 4.13 release notes

### PR DESCRIPTION
**Pull request by maxwelldb**
Issue: [OSDOCS-5603](https://issues.redhat.com//browse/OSDOCS-5603)

Version: 4.13

Preview: https://57701--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html

QE: 

- [x] Acked!

### CODE REVIEW

**Review by MaysaMacedo — CHANGES_REQUESTED** [review]
The` Networking deprecated and removed features` needs update for the Kuryr version that it was deprecated, it started from 4.12 and not 4.13

**Comment by MaysaMacedo** [comment]
Also features stated at the `Red Hat OpenStack Platform (RHOSP) Technology Preview features` section need update on versions when it became GA. DCN and CCM became GA from 4.12

**Comment by maxwelldb** [comment]
TODO before peer review: Verify that deprecated/removed features list does not yet reflect https://github.com/openshift/openshift-docs/pull/57701#issuecomment-1482780575

**Comment by maxwelldb** [comment]
@dulek Anything that is changing specifically in this release is fair game. I'd probably stick it here: https://57701--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-notable-technical-changes

**Comment by maxwelldb** [comment]
@dulek Is exactly what to communicate re: versions settled?

**Comment by maxwelldb** [comment]
@MaysaMacedo This should be reflected in the preview shortly: https://github.com/openshift/openshift-docs/pull/57701/commits/8833ce11a5ee19b5c0cb9c501c3bf20bf882edb3

**Comment by MaysaMacedo** [comment]
Looks good @maxwelldb. Thanks

**Comment by maxwelldb** [comment]
@imatza-rh @rlobillo @itzikb-redhat Would one of you be able to QE ack this?

**Comment by dulek** [comment]
> @dulek Is exactly what to communicate re: versions settled?

Okay, nothing to communicate here really, versions are the same as in 4.12. I don't think we need to inform users that OSP 17.0 goes EOL soon, this is something that belongs in OSP release notes.

**Comment by kalexand-rh** [comment]
Assuming the build passes, LGTM. Remember to squash.

**Pull request merged**
