### PR TITLE
BZ1823675 Remove statement about use of golang crypto

### PR DESCRIPTION
**Pull request by jeana-redhat**
For https://bugzilla.redhat.com/show_bug.cgi?id=1823675

### CODE REVIEW

**Comment by knewcomerRH** [comment]
Would you also remove this sentence: "Red Hat verifies that all other packages use the FIPS validated / Implementation Under Test OpenSSL module." There are crypto modules other than OpenSSL that are used, such as SSH. It's simplest just to remove the sentence. Otherwise, looks good. Thanks!

**Comment by jeana-redhat** [comment]
For the record, I am incorporating the changes I got via email from Kirsten with this PR:

> And, while reviewing the changes, I also noticed this sentence: 
> 
>     "When you enable FIPS mode for your cluster, Red Hat’s golang compiler calls RHEL and RHCOS cryptographic libraries for all OpenShift Container Platform components that require cryptographic signing."
> 
> which should be changed to 
> 
>     "When you enable FIPS mode for your cluster, all OpenShift Container Platform components that require cryptographic signing call RHEL and RHCOS cryptographic libraries."

**Comment by jeana-redhat** [comment]
Updated to resolve merge conflict

**Pull request merged**
