### PR TITLE
OSDOCS#10522: Remove platform Operators TP

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.16

Issue: [OSDOCS-10522](https://issues.redhat.com//browse/OSDOCS-10522)

Link to docs preview:
https://76362--ocpdocs-pr.netlify.app/openshift-enterprise/latest/architecture/control-plane.html
https://76362--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/arch/olmv1-rukpak.html
https://76362--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/understanding/olm-packaging-format.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@jianzhangbjz PTAL

**Review by adellape — APPROVED** [review]

**Pull request merged**
