### PR TITLE
Cleanup F5 ramp node instructions

### PR DESCRIPTION
**Pull request by ramr**
Cleanup F5 ramp node instructions. 
Fix multitenant plugin openflow rules on the ramp node. These now match up to the sdn plugin rules, so special handling is not required anymore.

@adellape / @bfallonf  PTAL  thx

/cc @zhaozhanqi @knobunc @rajatchopra

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr Looks fine. Does it require anyone else's ack before merging?

**Comment by ramr** [comment]
@bfallonf  - nope it was just cc/fyi on the others.

**Comment by bfallonf** [comment]
@ramr Cool. I'll give this a merge. Thanks!

**Comment by adellape** [comment]
@ramr Was this a result of an actual change to the multitenant plug-in? If so, should this only target OSE 3.2+?

**Comment by ramr** [comment]
@adellape correct this was as a result of the openshift-sdn multi-tenant plugin changes - it should target OSE 3.2 (and above) and origin I guess.

**Comment by adellape** [comment]
@ramr Thanks.

@bfallonf We'll need to remove this from that weekly release PR you have pending, which included this: https://github.com/openshift/openshift-docs/pull/1952

**Comment by adellape** [comment]
@bfallonf The OSE 3.0 one too: https://github.com/openshift/openshift-docs/pull/1953

**Pull request merged**
