### PR TITLE
[OCPBUGS-10654]: Fix a typo and remove a list item

### PR DESCRIPTION
**Pull request by tmalove**
[OCPBUGS-10654](https://issues.redhat.com/browse/OCPBUGS-10654)

Version(s): 4.10 +

Link to docs preview: (March 24)
[Installing the Network Observability Operator](http://file.rdu.redhat.com/tlove/netobserv-ocpbugs-10654-tlove/networking/network_observability/installing-operators.html#network-observability-operator-installation_network_observability)
[Create roles for Authentication and authorization module](http://file.rdu.redhat.com/tlove/netobserv-ocpbugs-10654-tlove/networking/network_observability/installing-operators.html#network-observability-roles-create_network_observability)
[View the FlowCollector resource](http://file.rdu.redhat.com/tlove/netobserv-ocpbugs-10654-tlove/networking/network_observability/configuring-operator.html#network-observability-flowcollector-view_network_observability)

QE review:
- [ x] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @nathan-weinberg will you verify the changes and lgtm? Thanks!

**Comment by tmalove** [comment]
> +1 to @skrthomas's comment, once that is also fixed I can approve this from QE side

Hi @nathan-weinberg  I made the additional change and updated the preview...thanks!

**Comment by tmalove** [comment]
> Looks good, Tami!! I think there's one more place to remove tenantID in the sample FlowCollector: [docs.openshift.com/container-platform/4.12/networking/network_observability/configuring-operator.html#network-observability-flowcollector-view_network_observability](https://docs.openshift.com/container-platform/4.12/networking/network_observability/configuring-operator.html#network-observability-flowcollector-view_network_observability)

@skrthomas The update is complete and the preview link is updated...thanks!

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by tmalove** [comment]
> Hi @stleerh will you review and ack these changes at your earliest convenience? Thank you.

Hi @stleerh Checking in to ask for the Ack for this PR...thanks!

**Review by stleerh — APPROVED** [review]

**Comment by skrthomas** [comment]
Adding a comment here- this is OK to merge, as opposed to other NetObserv docs PRs, because the line item removed here needs to be removed since Loki Operator 5.6 is in the wild, which it has been since Jan 18th-ish. Otherwise, the typo is benign. Other NetObserv docs PRs for feature-related bugs or features can't be merged until April 18th, which is the Operator GA.

**Pull request merged**
