### PR TITLE
PTP events with OC is GA in OCP 4.10

### PR DESCRIPTION
**Pull request by aireilly**
PTP events with OC is GA in OCP 4.10

Merge to enterprise-4.10

Preview: http://file.emea.redhat.com/aireilly/fix-ptp-tp-note/release_notes/ocp-4-10-release-notes.html#ocp-4-10-technology-preview

### CODE REVIEW

**Comment by aireilly** [comment]
@aneeshkp Can you review please. PTP events for OC GA'd in 4.10.

**Comment by Amrita42** [comment]
lgtm

**Comment by ahardin-rh** [comment]
@aireilly This update LGTM. Before we merge, however, I think you have to send this through the change management process because you are updating a feature's support status in a past release.

**Comment by aireilly** [comment]
> @aireilly This update LGTM. Before we merge, however, I think you have to send this through the change management process because you are updating a feature's support status in a past release.

Ack. Will do.

**Comment by aireilly** [comment]
@ahardin-rh This has gone through change management and is now ready for merge. Thanks for reminding me :)

**Review by bergerhoffer — COMMENTED** [review]
LGTM, merging per slack request!

**Pull request merged**
