### PR TITLE
BZ-2004834: Updating recommendation and example for default node sele…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ctor

https://bugzilla.redhat.com/show_bug.cgi?id=2004834

Preview: https://deploy-preview-36836--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks.html#creating-an-infra-node_post-install-cluster-tasks

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please QE review?

Preview: https://deploy-preview-36836--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks.html#creating-an-infra-node_post-install-cluster-tasks

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
