### PR TITLE
for BZ1698640 -- auto upgrades values and params

### PR DESCRIPTION
**Pull request by jhoyt-rh**
This is for bug https://bugzilla.redhat.com/show_bug.cgi?id=1698640. Created new PR so it could be applied to enterprise-3.9

### CODE REVIEW

**Comment by jhoyt-rh** [comment]
For cherrypicking to enterprise-3.9.

**Comment by kalexand-rh** [comment]
@jhoyt-rh, this PR introduces more changes than https://github.com/openshift/openshift-docs/pull/14638 did. Please confirm that this is correct.

**Comment by jhoyt-rh** [comment]
@kalexand-rh Yes, in the 3.9 version, there were some changes in the file (re deleting the line about the oc command and using care upgrading the nodes) from PR #14638  and this is correct.   These extra changes are correct. They were not included in 3.10 and 3.11 because the functionality was accomplished automatically after release 3.9, and was not included in the docs; hence no need to remove it. That particular information was only for release 3.9.

**Comment by kalexand-rh** [comment]
@jhoyt-rh, I'm more concerned about the changes to the daemonset label commands. There's no indication from the bug that they need to change.

**Comment by jhoyt-rh** [comment]
@kalexand-rh Yes, I understand. Those were related to the other bug, which
has not yet been closed. They are from bug BZ1698640.


Joan Hoyt

She/Her/Hers

Sr. Technical Writer, CCS/OpenShift Enhanced Delivery

Red Hat <https://www.redhat.com/>

Westford, MA

jhoyt@redhat.com    IM: jhoyt
<https://red.ht/sig>TRIED. TESTED. TRUSTED.

**Comment by mbearer** [comment]
@jhoyt-rh BZ1698640 does not mention removing the daemonset label commands from what I can see.

**Comment by jhoyt-rh** [comment]
@mbearer That is correct. However, as explained in the comment above, that material comes from BZ1698198. That BZ addressed an issue that was strictly for Rel 3.9; releases 3.10 and 3.11 did not need that fix because the code had taken care of the matter that required this fix in 3.9.

The other BZ fix was based on "enterprise-3.9" whereas this one was based on "master." Since that deletion had been made in 3.9, and this BZ applies to 3.9, 3.10, and 3.11, this 3.9 material appeared to be "new content" for this bug because Travis saw this deletion which was not in 3.10 and 3.11. I believe that was due to deletion being part of release 3.9 -- concerning the other bug.

@vikram-redhat can you PTAL.  I was surprised myself to see this called out as a new edit for this BZ, which doesn't concern the daemonset issue. However, since what this PR lists is correct, and had to be based on master since it concerned all releases, I thought that was why this happened. But essentially, the content is correct. For release 3.9 (which this cherrypick is <from master>), it is showing that material also.

**Comment by vikram-redhat** [comment]
@jhoyt-rh I haven't delved deep into this, but looks like you have content in this PR for another fix (separate PR: https://github.com/openshift/openshift-docs/pull/14809). The most likely reason is that when you created this PR, you created it off the branch for #14809 instead of enterprise-3.9.

It might be best to close this PR, and open another one, making sure you create it off a freshly rebased local enterprise-3.9 against the upstream enterprise-3.9.

**Comment by jhoyt-rh** [comment]
@Vikram Goyal <vigoyal@redhat.com>  Thank you for looking into this. I feel
quite certain that I created it off enterprise-3.9, not another branch, but
it sounds as if what you suggest is the best way to get this resolved is to
close and create another one from enterprise-3.9.  I'll do that. Thank you.

Joan Hoyt

She/Her/Hers

Sr. Technical Writer, CCS/OpenShift Enhanced Delivery

Red Hat <https://www.redhat.com/>

Westford, MA

jhoyt@redhat.com    IM: jhoyt
<https://red.ht/sig>TRIED. TESTED. TRUSTED.

**Comment by jhoyt-rh** [comment]
@vikram-redhat  Per your suggestion, I am closing this PR, and will open a new one just for enterprise-3.9, based on a freshly based local enterprise-3.9

**Comment by vikram-redhat** [comment]
@jhoyt-rh - what is the status with the follow up to this and https://github.com/openshift/openshift-docs/pull/14617?

**Pull request closed without merging**
