### PR TITLE
Revert footnote syntax

### PR DESCRIPTION
**Pull request by jboxman**
```
footnote:(\w+)\[([^\]+])
footnoteref:[$1,$2

footnote:(\w+)\[\]
footnoteref:[$1]

footnote:([^\[]+)\[([^\]+])
footnoteref:[$1,$2
```

### CODE REVIEW

**Comment by jboxman** [comment]
@vikram-redhat, FYI.

**Comment by vikram-redhat** [comment]
Thanks. Need to let the team know as well. :(

**Comment by vikram-redhat** [comment]
@openshift/team-documentation @openshift/team-aligned-docs 

Looks like the portal doesn't like the new footnoteref as it is displaying verbatim.

https://bugzilla.redhat.com/show_bug.cgi?id=1847497

**Comment by vikram-redhat** [comment]
@jboxman if we updated the guidelines, please revert those, and also make the changes for the 4.2 and 3.11 branches.

**Comment by jboxman** [comment]
@vikram-redhat, so that new table style I mentioned last week, maybe we need to adopt that going forward?

In truth, footnotes obscure information, and perhaps avoiding them is a better approach in any case. All of us left college papers far behind, I think.

**Comment by vikram-redhat** [comment]
> @vikram-redhat, so that new table style I mentioned last week, maybe we need to adopt that going forward?
> 
> In truth, footnotes obscure information, and perhaps avoiding them is a better approach in any case. All of us left college papers far behind, I think.

Lol. Yeah that is fine but let's talk about it in the team meeting first.

**Comment by bergerhoffer** [comment]
@jboxman @vikram-redhat  If we really do want to adopt the method presented in last week's meeting, then I might suggest some improvements before adopting more widely. 

Like possibly:

* Putting all of the footnotes in a single cell instead of a row for each. 
* Using the `options="footer"` table option to set the cell with the footnotes apart from a regular row of the table.
* Being consistent with how many spaces there are before the footnote indicator. Right now there seems to be 3 for some reason with one of them being {nbsp}. I'd suggest just a single space of the {nbsp}.
* And ideally it would be nice to make the indicator an xref that jumps down to the respective footnote, to be closer to the current footnote behavior. But this goes against our current no xrefs at all in modules rule unfortunately.

**Comment by mburke5678** [comment]
> Putting all of the footnotes in a single cell instead of a row for each.
+1. I had the same thought.

**Comment by bobfuru** [comment]
+1 to footnotes in single cell, set apart, and single space before indicator.

**Comment by jboxman** [comment]
This team is genius!

**Pull request merged**
