### PR TITLE
Revert to TP for IBM PowerVS in 4.15 Release Notes

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.15

Issue:
- https://issues.redhat.com/browse/MULTIARCH-4115
- Related to this PR: https://github.com/openshift/openshift-docs/pull/71984

Link to docs preview:
- https://71985--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-ibm-power
- [Technology Preview features](https://71985--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-technology-preview-tables) (tables 18 and 21)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by SNiemann15** [comment]
/label peer-review-needed

This PR adddresses the issue discussed here: https://redhat-internal.slack.com/archives/C04DLQNN7B9/p1708425169198359

**Comment by manojnkumar** [comment]
LGTM

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by jldohmann — APPROVED** [review]
LGTM! nice work, Silke 😄

**Pull request merged**
