### PR TITLE
OSDOCS#4859: Updating life cycle dates for ROSA as of OCP 4.13 GA

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
4.13, 4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-4859

Link to docs preview:
https://59887--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.html#sd-life-cycle-dates_rosa-life-cycle

QE review:
- [ ] QE has approved this change.

Additional information:
N/A

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by laubai** [comment]
@kalexand-rh Pinging you here for OCP GA purposes

**Pull request merged**
