### PR TITLE
MIG-1549: Attribute Updates for MTC 1.8.4

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [MIG-1549](https://issues.redhat.com/browse/MIG-1549)

### Version(s):

* OCP 4.12 +

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
Delayed release - MTC GA on 29th August (but could be delayed further)

**Comment by anarnold97** [comment]
@stillalearner & @rayfordj - please can you approve this simple PR to update the MTC version for 1.8.4?
Thanks

**Review by rayfordj — APPROVED** [review]
/lgtm

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by stillalearner — APPROVED** [review]
lgtm

**Pull request merged**
