### PR TITLE
OADP-74: Uninstall OADP

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/OADP-74

Add assembly for uninstalling OADP.

Preview: https://deploy-preview-40992--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/uninstalling-oadp.html

QE approved. Ready for peer review.

### CODE REVIEW

**Review by nitishSr — APPROVED** [review]
LGTM :+1:

**Review by sagidlow — COMMENTED** [review]
One small comment. Make sure to resolve your merge conflicts before merging :)

**Pull request merged**
