### PR TITLE
Updates OMR to 1.3.5

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.10+ 

Issue:
https://issues.redhat.com/browse/OSDOCS-6144

Link to docs preview:
https://60181--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-creating-registry.html#mirror-registry-for-openshift-1-3-5

QE review:
Not needed

Additional information:

### CODE REVIEW

**Review by jldohmann — COMMENTED** [review]
generally LGTM, though I can't check the link works without a preview

**Comment by stevsmit** [comment]
> generally LGTM, though I can't check the link works without a preview

Oops. I guess I opened it and never copied it over. Preview is attached, but link won't load bc the advisory isn't shipped yet. 

Holding to merge for when it goes live.

**Pull request merged**
