### PR TITLE
[OSDOCS-11762]:Fix typo in Shared VPC docs (several locations, GCP)

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-11762
Link to docs preview:

https://80782--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-gcp-cluster-ccs_osd-creating-a-cluster-on-gcp

https://80782--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-gcp-account_osd-creating-a-cluster-on-gcp

https://80782--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-rhm-gcp-account_osd-creating-a-cluster-on-gcp

QE review:
- [ ] QE has approved this change. **QE N/A as this is a typo.**

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-needed

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
