### PR TITLE
GH#31545 GH#31527 Additional AWS permissions

### LINKED ISSUE #31527: [enterprise-4.7] Issue in file installing/installing_aws/installing-aws-account.adoc
### Which section(s) is the issue in?
Required AWS permissions

### What needs fixing?
ec2:DescribeInstanceTypes is missing from the list of required permissions for installation

### LINKED ISSUE #31545: [enterprise-4.7] Issue in file installing/installing_aws/installing-aws-account.adoc
### Which section(s) is the issue in?
Required AWS permissions

### What needs fixing?
The Required IAM permissions for installation is missing 

iam:CreateServiceLinkedRole

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #31545
Resolves #31527

Preview: https://deploy-preview-31629--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account

### CODE REVIEW

**Comment by codyhoag** [comment]
@staebler PTAL. Does this apply for OCP 4.5-4.8?

**Comment by staebler** [comment]
> @staebler PTAL. Does this apply for OCP 4.5-4.8?

The ec2:DescribeInstanceTypes permission requirement only goes back to 4.7.

**Comment by codyhoag** [comment]
@yunjiang29 can you confirm for QE? Thanks!

**Comment by codyhoag** [comment]
I will manually backport the `iam:CreateServiceLinkedRole` note for 4.5-4.6, since the `ec2:DescribeInstanceTypes` does not apply for those versions of OCP.

**Comment by yunjiang29** [comment]
@codyhoag LGTM.

**Review by adellape — COMMENTED** [review]
:+1:

**Pull request merged**
