### PR TITLE
[SRVOCF-620] Developing Go functions in Serverless Functions - TP

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.34+

Issue:
https://issues.redhat.com/browse/SRVOCF-620

Link to docs preview:
https://81070--ocpdocs-pr.netlify.app/openshift-serverless/latest/functions/reference/serverless-developing-go-functions

QE review:
- [x] QE has approved this change.

Additional info: 
Readded the Building Go Functions assembly as a TP.

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Review by adellape — APPROVED** [review]
LGTM, see Slack DM re: timing of merge.

**Comment by mburke5678** [comment]
@ochromy I need a preview before I can merge to make sure all looks OK.

**Comment by ochromy** [comment]
@mburke5678 Apologies, this is the readded assembly: https://81070--ocpdocs-pr.netlify.app/openshift-serverless/latest/functions/reference/serverless-developing-go-functions

**Pull request merged**
