### PR TITLE
OSDOCS#4649: Copy relevant APIs for MicroShift, strip broken links

### PR DESCRIPTION
**Pull request by kowen-rh**
This is a temporary solution to ensure that we can build the Rest API reference materials needed specifically for MicroShift. The two named APIs copied here are needed for the MicroShift documentation but normally contain numerous links to `object` APIs. These links are removed in these copied versions to facilitate building the books.

Version(s):
MicroShift (4.12)

Issue:
https://issues.redhat.com/browse/OSDOCS-4649

Link to docs preview:
https://53964--docspreview.netlify.app/microshift/latest/microshift_rest_api/network_apis/route-route-openshift-io-v1.html#route-route-openshift-io-v1
https://53964--docspreview.netlify.app/microshift/latest/microshift_rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html#securitycontextconstraints-security-openshift-io-v1

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@robin-owen Just add the specific preview for peer reviews. 
looks good to me!

**Comment by kalexand-rh** [comment]
Except for the xrefs in modules, this scans well. Please either rework the content to remove them now or post a link to the issue where you're going to fix them later.

**Comment by robin-owen** [comment]
> [...] or post a link to the issue where you're going to fix them later.

Created an issue for this. Thanks!

https://issues.redhat.com/browse/OSDOCS-4710

**Pull request merged**
