### PR TITLE
[OSDOCS-12058]Review of cp and infra node size/scaling AND removal of ROSA references from OSD docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-12058
Link to docs preview:

https://82239--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/osd-limits-scalability.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
**QE/Peer Review.** Please note that this PR is specific to removing ROSA reference from OSD docs. There is another PR being worked on that is in regard to number of increase in nodes for ROSA. Also note that there is now a split between ROSA and HCP limits and scalability topics. 
image

**Comment by mletalie** [comment]
@xueli181114, Can I please get a QE review for this PR? Thanks!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
