### PR TITLE
document rsync --watch

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal but do not merge until https://github.com/openshift/origin/pull/8268 merges.

**Comment by bparees** [comment]
@openshift/team-documentation feature has merged, review/merge at will.

**Comment by adellape** [comment]
:+1:

**Comment by bparees** [comment]
@thesteve0 fyi, includes your update request.
@adellape added a new paragraph.

**Comment by bfallonf** [comment]
@bparees I've been given this in BZ form for the 3.3 release: https://bugzilla.redhat.com/show_bug.cgi?id=1351443

But I've already done a followup PR and it's merged. Because it's tagged Future Release, this isn't live in Enterprise yet, but you've labeled it for 3.2 here. So, the question is, is this for 3.2 or 3.3? When should it go live? Thanks!

**Comment by bparees** [comment]
This feature shipped in 3.2

Ben Parees | OpenShift

**Comment by bfallonf** [comment]
@bparees I can't see it in my 3.2 test machine:

http://pastebin.test.redhat.com/389771

Am I missing something?

**Comment by bparees** [comment]
maybe it didn't make it until 3.2.1


On Wed, Jul 6, 2016 at 12:54 AM, Brice Fallon-Freeman <
notifications@github.com> wrote:

> @bparees <https://github.com/bparees> I can't see it in my 3.2 test
> machine:
>
> http://pastebin.test.redhat.com/389771
>
> Am I missing something?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-docs/pull/1880#issuecomment-230670782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEvl3rZkk3TzW9k-33FpkGxBYtFwdtLwks5qSzUFgaJpZM4IDPNB>
> .
>



-- 
Ben Parees | OpenShift

**Comment by bparees** [comment]
strange, i checked the OSE history and it was not picked up for 3.2.x at all.  i'm not sure why not.  so yeah, only for 3.3. i guess.

**Comment by adellape** [comment]
@bfallonf Adjusting the labels per latest comment.

**Comment by thesteve0** [comment]
Will there be a 3.2.2 before 3.3 and can we get it in for that?

**Pull request merged**
