### PR TITLE
Adding a note that you must have cluster-admin permissions to use oc …

### PR DESCRIPTION
**Pull request by bergerhoffer**
…adm commands

Preview: https://deploy-preview-38500--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please QE review this?

Preview: https://deploy-preview-38500--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
