### PR TITLE
OSDOCS-11769: adds clarity for audit logs MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.16, 4.17

Issue:
[OSDOCS-11769](https://issues.redhat.com/browse/OSDOCS-11769)

Link to docs preview:
[RHEL audit log admonition and link--right above linked heading](https://80998--ocpdocs-pr.netlify.app/microshift/latest/microshift_configuring/microshift-audit-logs-config.html#about-audit-log-profiles_microshift-audit-logs-config)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by DanielFroehlich — APPROVED** [review]
/lgtm

**Review by kcarmichael08 — COMMENTED** [review]
LGTM!

**Review by arthur-r-oliveira — COMMENTED** [review]
/lgtm 
thanks for the heads-up @ShaunaDiaz !

**Pull request merged**
