### PR TITLE
Describe and mark loopback ports in the master-to-master table

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Fixes bug 1287949 ([link](https://bugzilla.redhat.com/show_bug.cgi?id=1287949)).

@nak3 PTAL
Marking as WIP pending resolution of [which ports are affected](https://bugzilla.redhat.com/show_bug.cgi?id=1287949#c1).

@ahardin-rh @adellape @bfallonf @tpoitras 
Peer-review please?

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@tnguyen-rh LGTM! :star2:

**Comment by bfallonf** [comment]
@tnguyen-rh Looks good!

**Comment by tpoitras** [comment]
@tnguyen-rh Looks good! I'm diggin that "need not" brevity. :+1: :hamster: :+1:

**Comment by tnguyen-rh** [comment]
@ahardin-rh @tpoitras Thanks for the reviews.

[rev_history]
|link:../install_config/install/prerequisites.html[Installing -> Prerequisites]
|Described which link:../install_config/install/prerequisites.html#required-ports[required ports] are necessary for master self-communication.
%

**Pull request merged**
