### PR TITLE
Updated API impersonation section to link to Kubernetes docs

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@deads2k Can you review?

Preview: https://updating-impersonation-docs--ocpdocs.netlify.com/openshift-enterprise/latest/authentication/understanding-authentication.html#authentication-api-impersonation_understanding-authentication

Also make sure this page looks okay with the changes:
https://updating-impersonation-docs--ocpdocs.netlify.com/openshift-enterprise/latest/authentication/impersonating-system-admin.html

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
