### PR TITLE
CNV-12608: Updating language in nmstate examples

### PR DESCRIPTION
**Pull request by ousleyp**
- [CNV-12608](https://issues.redhat.com/browse/CNV-12608)
- related to [CNV-9233](https://issues.redhat.com/browse/CNV-9233)
- CP to enterprise-4.9 only

Preview builds:
- [first module](https://deploy-preview-36584--osdocs.netlify.app/openshift-enterprise/latest/virt/node_network/virt-updating-node-network-config.html#virt-example-bond-nncp_virt-updating-node-network-config)
- [second module](https://deploy-preview-36584--osdocs.netlify.app/openshift-enterprise/latest/virt/node_network/virt-updating-node-network-config.html#virt-example-nmstate-multiple-interfaces_virt-updating-node-network-config)

@phoracek please review! Thanks :)

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
/lgtm

Thanks @ousleyp o/

**Review by geetikakay — COMMENTED** [review]
enslaving still represents slave. Can we rephrase it. 
Line 38  under modules/virt-example-bond-nncp.adoc

**Comment by ousleyp** [comment]
> enslaving still represents slave. Can we rephrase it.
> Line 38 under modules/virt-example-bond-nncp.adoc

Great catch @geetikakay, thank you. Updated to "Bond with ports eth1 and eth2" after discussing with Petr.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM!

**Pull request merged**
