### PR TITLE
CNV - BZ#1861297 removing timeout note/rel_not

### PR DESCRIPTION
**Pull request by aburdenthehand**
BZ#1861297 has now been verified ahead of 2.4.1. Removing the release note and admonition from the docs

https://bugzilla.redhat.com/show_bug.cgi?id=1861297

@rnetser

### CODE REVIEW

**Comment by vikram-redhat** [comment]
errata is in_push. Merging this.

**Comment by vikram-redhat** [comment]
@aburdenthehand this contained a rel note file and a normal file. Should they have been in separate PRs so that the normal file went into master as well?

**Comment by aburdenthehand** [comment]
@vikram-redhat No, we knew this would be fixed for z-stream so the content was enterprise-4.5 only

**Pull request merged**
