### PR TITLE
removed support for multiple templates with oc process

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal, we removed this functionality in oc process a while ago.

**Comment by vikram-redhat** [comment]
@bparees - is it still present in 3.2?

**Comment by bparees** [comment]
@vikram-redhat i'm not positive if it was removed in 3.2 or 3.3, seemed safest to just update 3.3+

**Comment by bparees** [comment]
(it's not a critical enough change for me to think it's worth digging up the history)

**Comment by vikram-redhat** [comment]
Sure. Thanks Ben.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Removed an outdated reference regarding support for multiple templates with `oc process`.
%

**Pull request merged**
