### PR TITLE
Remove hard returns from file

### LINKED ISSUE #43428: Remove hard returns in backing_up_etcd.adoc
### Which section(s) is the issue in?

`backup_and_restore/control_plane_backup_and_restore/backing_up_etcd.adoc`

### What needs fixing?

File has hard returns, needs to be changed to wrap instead

### PR DESCRIPTION
**Pull request by jldohmann**
Hopefully fixes #43428

Trying with a base of `main` first before resorting to doing this for each branch 🙂

### CODE REVIEW

**Comment by jldohmann** [comment]
@EricPonvelle could you PTAL?

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by jldohmann** [comment]
@ahardin-rh thanks for checking! Yes, it should be for 4.6+

**Pull request merged**
