### PR TITLE
OSDOCS-4069: Instance name changed to namespace

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+

Issue:

https://issues.redhat.com/browse/OSDOCS-4069

Link to docs preview:

https://54693--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/setting-up-argocd-instance.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
@xueli181114, Can you please review this for me? Thanks.

**Review by skrthomas — COMMENTED** [review]
LGTM. Ok to merge post freeze.

**Pull request merged**
