### PR TITLE
[WIP] Bug 1346262 : removed deprecated credentials flag in favour of service-account flag

### PR DESCRIPTION
**Pull request by bfallonf**
As per:

https://bugzilla.redhat.com/show_bug.cgi?id=1346262

I'll ask for an ack in the BZ.

### CODE REVIEW

**Comment by bfallonf** [comment]
[rev_history]
|link:../install_config/docker_registry.html[Installing -> Deploying a Docker Registry]
|Replaced the deprecated `--credentials` option in place of `--service-account` option.
%

**Comment by tpoitras** [comment]
@bfallonf LGTM, dude. I think this BZ might be a duplicate of one I filed, or mine might be a duplicate of it.

**Comment by bfallonf** [comment]
@tpoitras if you find it, and it is, feel free to close it and link to this :carousel_horse: 

Merging.

**Comment by tpoitras** [comment]
I did find my BZ and closed it as a duplicate of yours: https://bugzilla.redhat.com/show_bug.cgi?id=1338574

**Pull request merged**
