### PR TITLE
updating log output example messages

### PR DESCRIPTION
**Pull request by lahinson**
GH#48077: Updating example log messages for etcd defragmentation

Version(s): 4.10, 4.11, 4.12

Issue: https://github.com/openshift/openshift-docs/issues/48077

Link to docs preview (VPN required): http://file.rdu.redhat.com/lahinson/etcd-auto-defrag/post_installation_configuration/cluster-tasks.html#etcd-defrag_post-install-cluster-tasks

Additional information:

### CODE REVIEW

**Comment by bscott-rh** [comment]
LGTM.

**Review by bscott-rh — APPROVED** [review]

**Comment by lahinson** [comment]
@geliu2016 @dusk125 When you can, PTAL at this update to the Automatic defragmentation docs for etcd. The preview link is in the first comment 👆 

Thanks!

**Review by opayne1 — APPROVED** [review]

**Pull request merged**
