### PR TITLE
fixed issue 4147 and added alternative command for provided example.

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For #4147

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf can you tag someone who can verify this?
PS: Github reviewers suggestions "bfallonf recently edited this file" :nerd_face:

**Comment by bfallonf** [comment]
Hmm maybe @liggitt or @csrwng ? They're featured in the file history... (thanks!)

**Comment by gaurav-nelson** [comment]
@liggitt @csrwng bump :flashlight:

**Comment by csrwng** [comment]
@gaurav-nelson sorry I'm not an expert in this area, but tagging @mfojtik who owns it now.

**Comment by gaurav-nelson** [comment]
@mfojtik Can you please check and confirm this change?

**Comment by gaurav-nelson** [comment]
ping @mfojtik

**Comment by gaurav-nelson** [comment]
small change no rev history needed.

**Pull request merged**
