### PR TITLE
Removing root prompt that isn't necessary

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://deploy-preview-36341--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review this? I just want to make sure that root isn't required (as indicated by the "#" prompt prior to my update) when logging in here. Thanks!

Preview: https://deploy-preview-36341--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Pull request merged**
