### PR TITLE
[SRVKE-1093] Update Kafka output

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
Applies for OCP 4.6+

Issue:
https://issues.redhat.com/browse/SRVKE-1093

Link to preview:
http://file.rdu.redhat.com/abrennan/050722/kafkaoutput/serverless/admin_guide/serverless-kafka-admin.html#serverless-install-kafka-odc_serverless-kafka-admin

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Comment by opayne1** [comment]
LGTM!

**Pull request merged**
