### PR TITLE
OSDOCS-2371 Update AMIs for 4.9 Ga

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2371

Preview: https://deploy-preview-36972--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-user-infra.html#installation-aws-user-infra-rhcos-ami_installing-aws-user-infra

### CODE REVIEW

**Comment by codyhoag** [comment]
@miabbott can you verify? Thanks!

**Review by miabbott — APPROVED** [review]
LGTM

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

**Pull request merged**
