### PR TITLE
OSDOCS 6764:Removed info on PV backups.

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-6764

Link to docs preview:
OSD: https://62498--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/policy-process-security.html#backup-recovery_policy-process-security

ROSA: https://62498--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-backup-policy_rosa-service-definition

QE review:
- [x] QE has approved this change.

SME review:
- [x] SME has approved this change.

Peer review:
- [x] Peer reviewer has approved this change.

### CODE REVIEW

**Review by arendej — APPROVED** [review]
this is fine

**Review by lahinson — COMMENTED** [review]
LGTM

**Pull request merged**
