### PR TITLE
OCPBUGS#20304: Remove `alpha` flag from `opm` script

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.15+

Issue: [OCPBUGS- 20304](https://issues.redhat.com/browse/OCPBUGS-20304)

Link to docs preview: [Understanding Operators > Packaging format > Example catalog (Step 2)](https://72547--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/understanding/olm-packaging-format#olm-fb-catalogs-example_olm-packaging-format)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@Xia-Zhao-rh or @jianzhangbjz: PTAL

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1: 

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
