### PR TITLE
[enterprise-4.4] BZ#1884298vSphere Networking version adjustments

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1884298

Cherrypick of #26439

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma can you please confirm this for OCP 4.4?

**Comment by codyhoag** [comment]
@jinyunma bump. Can you confirm this for OCP 4.4? Thanks!

**Comment by codyhoag** [comment]
Marc Curry confirmed that this has already been certified. No QE review necessary.

**Comment by mcurry-rh** [comment]
LGTM

**Pull request merged**
