### PR TITLE
Swaps order of assembly content to render product-registry

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.10+ 

Issue:
https://issues.redhat.com/browse/OCPBUGS-13047

Link to docs preview:
https://59568--docspreview.netlify.app/openshift-enterprise/latest/registry/index.html

QE review:
Not needed. Portal rendering issue. 

Additional information:
Should hopefully fix rendering issues here: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/registry/registry-overview#annotations:127c6d00-aee7-4f7d-b5d6-d255bfdede47

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
This lgtm but I don't know too much about portal rendering issues. Might be a good idea to check with Kathryn too. 🤷‍♀️  I am gonna go ahead and put on Peer review done and let you decide.

**Comment by stevsmit** [comment]
@opayne1 Yep I talked with Kathryn about it earlier. We're not sure what the actual issue is, but wanted to try this.

**Pull request merged**
