### PR TITLE
CNV-44933: Added EFS and EBS limitations table

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.16+

Issue: [CNV-44933](https://issues.redhat.com//browse/CNV-44933)

Link to docs preview: 

- OpenShift enterprise: https://80376--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/install/preparing-cluster-for-virt.html#virt-aws-bm_preparing-cluster-for-virt
- ROSA: https://80376--ocpdocs-pr.netlify.app/openshift-rosa/latest/virt/install/preparing-cluster-for-virt.html#virt-aws-bm_preparing-cluster-for-virt

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by stesrn** [comment]
The content looks good. 
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
