### PR TITLE
OSDOCS-10983: Remove and redirect outdated log forwarding to CloudWatch tutorial to official product docs

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Version(s): `enterprise-4.15`+

Issue: https://issues.redhat.com/browse/OSDOCS-10983

Link to docs preview: https://77816--ocpdocs-pr.netlify.app/

QE review: not required

Additional information: This includes a redirect from [https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-rosa-cloudwatch-sts.html](https://docs.openshift.com/rosa/cloud_experts_tutorials/cloud-experts-rosa-cloudwatch-sts.html) to [https://docs.openshift.com/rosa/observability/logging/log_collection_forwarding/configuring-log-forwarding.html#rosa-cluster-log[…]ng-log-forwarding](https://docs.openshift.com/rosa/observability/logging/log_collection_forwarding/configuring-log-forwarding.html#rosa-cluster-logging-collector-log-forward-sts-cloudwatch_configuring-log-forwarding).

### CODE REVIEW

**Comment by bhardesty** [comment]
This LGTM!

/label peer-review-done
/remove-label peer-review-in-progress

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
