### PR TITLE
Adding redirect for low latency changes

### PR DESCRIPTION
**Pull request by aireilly**
Adding redirects for rework done under [TELCODOCS-325](https://issues.redhat.com//browse/TELCODOCS-325)

Version(s):
Merge to main only.

Issue:
https://issues.redhat.com//browse/TELCODOCS-325

Link to docs preview:
N/A

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by kcarmichael08** [comment]
Unable to test but LGTM as far as syntax.

**Comment by aireilly** [comment]
Thanks @kcarmichael08 FYI, you cna test these rules here: https://htaccess.madewithlove.com?share=82e95514-53e5-429e-b829-cb004aa53caf.

**Comment by aireilly** [comment]
cc @bscott-rh @gaurav-nelson

**Comment by bscott-rh** [comment]
Tester checks out, looks good to me

**Comment by aireilly** [comment]
Cool. Should be good to merge :)

**Pull request merged**
