### PR TITLE
BZ-1748368: Adding details on optional vs required fields

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1748368

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bergerhoffer can this be closed or merged?

**Comment by bergerhoffer** [comment]
@stlaz I'm revisiting this old issue. Per a slack conversation you mentioned that we should try to clean up how large the descriptions were getting, so I moved some of it to a note after the callouts.

You also said that we should note that `teams` and `organizations` are also optional if the `mappingMethod` is set to `lookup`, so I've incorporated that as well.

Let me know if this looks good to you now. Preview (internal): http://file.rdu.redhat.com/~ahoffer/2020/BZ-1748368/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-github-CR_configuring-github-identity-provider

**Comment by ahardin-rh** [comment]
Looks great!

**Comment by stlaz** [comment]
/lgtm
> Looks great!

It does :+1:

**Comment by bergerhoffer** [comment]
Hi @rhpmali - can you please review this update?

Preview (internal): http://file.rdu.redhat.com/~ahoffer/2020/BZ-1748368/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-github-CR_configuring-github-identity-provider

**Pull request merged**
