### PR TITLE
OSSMDOC-602: updated cipher suite doc for SMCP v2

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.6-4.11

Issue: https://issues.redhat.com/browse/OSSMDOC-602

Link to v1 docs preview: http://file.bos.redhat.com/tokeefe/OSSMDOC-602/service_mesh/v1x/ossm-security.html#ossm-security-cipher-1x_ossm-security-v1x

Link to v2 doc preview: http://file.bos.redhat.com/tokeefe/OSSMDOC-602/service_mesh/v2x/ossm-security.html#ossm-security-cipher_ossm-security

Additional information:

Dev review: Rob 
QE Review: Prachi
Peer review: Jstickler

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Comment by prachiyadav** [comment]
Verified

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
