### PR TITLE
Update matchLabels parameter in network-policy

### PR DESCRIPTION
**Pull request by stevsmit**
For 4.7+

GH Issue: https://github.com/openshift/openshift-docs/issues/38168

Pending QE ack:
@zhaozhanqi @anuragthehatter please review :) I am unsure if this is 100% correct. 

Preview: https://deploy-preview-38283--osdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/multitenant-network-policy.html

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
openshifg-ingress namespace have both two label `network.openshift.io/policy-group=ingress` and `policy-group.network.openshift.io/ingress=`.  So using anyone is ok.  @asood-rh ^^  help double confirm? thanks

**Comment by jboxman-rh** [comment]
@zhaozhanqi, I was told that the newer label is the preferred one to use now. However, which cluster network provider is used matters:

- https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-network-policy-host-network-ingress-controllers
- https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-network-policy-host-network-ingress-controllers

So this seems to be 4.6+ for OVN-Kubernetes and 4.7+ for OpenShift SDN.

**Comment by asood-rh** [comment]
@jboxman-rh @stevsmit @zhaozhanqi 

Jason has it right, new labels (policy-group.network.openshift.io/ingress: "" and policy-group.network.openshift.io/host-network: "") are supported on 4.6 OVN-Kubernetes but not on openshiftSDN. I did find two issues with the policy support where in one case old label with openshiftSDN does not work and one new label does not work with OVN-kubernetes
(Watch out for  - https://bugzilla.redhat.com/show_bug.cgi?id=2019900 and https://bugzilla.redhat.com/show_bug.cgi?id=2019996)

4.7 inclusive and on wards all labels are supported and work.
policy-group.network.openshift.io/ingress: ""
policy-group.network.openshift.io/host-network: ""
network.openshift.io/policy-group: ingress

**Comment by jboxman-rh** [comment]
@stevsmit seems fine; My insight into this has drift somewhat in recent months. As long as it passes QE we're good to go for peer review I think.

**Review by maxwelldb — COMMENTED** [review]
Left a comment. I don't think this does anything that is a rule violation, but happy to chat about alternative treatments.

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
