### PR TITLE
Updates to RHACS registry integrations

### PR DESCRIPTION
**Pull request by kcarmichael08**
Bug fix to remove unsupported registry integrations. Release notes for release when integrations were removed: https://docs.openshift.com/acs/3.71/release_notes/371-release-notes.html#removed-features-371

Versions:
- `rhacs-docs`
- `rhacs-docs-3.71`

Labels:
- `RHACS`

[Issue](https://issues.redhat.com/browse/ROX-11177)

Links to docs preview:
- [Integrating with image registries](https://openshift-docs-9c2vtsnen-kcarmichael08.vercel.app/openshift-acs/master/integration/integrate-with-image-registries.html)
- [Integrating with generic webhooks](https://openshift-docs-9c2vtsnen-kcarmichael08.vercel.app/openshift-acs/master/integration/integrate-using-generic-webhooks.html) (removed extra line breaks)
- [Integrating with image vulnerability scanners](https://openshift-docs-9c2vtsnen-kcarmichael08.vercel.app/openshift-acs/master/integration/integrate-with-image-vulnerability-scanners.html)
	- [Integrating with CoreOS Clair](https://openshift-docs-9c2vtsnen-kcarmichael08.vercel.app/openshift-acs/master/integration/integrate-with-image-vulnerability-scanners.html#integrate-with-clair_integrate-with-image-vulnerability-scanners)

### CODE REVIEW

**Review by md2119 — COMMENTED** [review]
Kerry, inspired by this PR, I started digging more into the image integration docs. 
There seems to be a slight discrepancy in the name references. To verify I opened the integrations page and found the possible cause of confusion—some logo images also have product names that overshadow ACS's labels.

For example,
1)
In docs: IBM Cloud Container Registry
In UI: Image has **IBM Cloud Container Registry** and ACS label is **IBM Cloud**

2)
In docs:  Red Hat Registry
In UI: Image has **Red Hat** and ACS label is **Red Hat**

3)
In docs: Clair
In UI: Image has **Clair** and ACS label is **CoreOS Clair**

4)
In docs: Quay Container Registry
In UI: Image has **Red Hat Quay.io** and ACS label is **Quay.io**

I recommend we should stick with ACS labels.

**Comment by kcarmichael08** [comment]
> 
> In docs: Quay Container Registry In UI: Image has **Red Hat Quay.io** and ACS label is **Quay.io**

I'll make these changes except I think this one needs to be Red Hat Quay.io to comply with doc standards.

**Comment by kcarmichael08** [comment]
Also going to keep "IBM Cloud Container Registry" as is since that is the official product name. https://www.ibm.com/cloud/container-registry

**Comment by jvdm** [comment]
> Also going to keep "IBM Cloud Container Registry" as is since that is the official product name. https://www.ibm.com/cloud/container-registry

Should we update the ACS labels for these two cases to conform with the docs then?

**Comment by kcarmichael08** [comment]
I think whenever possible the ACS label should use the correct product name but there may be space limitations on GUIs, labels, etc. I found this list of product names: https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit?usp=sharing

**Comment by kcarmichael08** [comment]
(I wouldn't spend a lot of time fixing this as it's pretty clear from the combination of logo and label what each one is)

**Comment by kcarmichael08** [comment]
@md2119 Can you give a final OK? I changed the ones you said to match the label, except for Quay and IBM Cloud. I think it's fine to leave the labels as-is on the product since there are space issues with the GUI, but use the correct product names in the docs.

**Comment by md2119** [comment]
@kcarmichael08, I see changes related to new dashboard. The target versions for this PR also include 3.70, however the feature was only released in 3.71. That makes me believe the additional commits that I see on this PR are the result of a bad rebase, and that the additional changes—upgrade scanner, dashboard operations, etc., should not belong to this PR.

**Review by md2119 — APPROVED** [review]

**Review by jldohmann — APPROVED** [review]
/lgtm

**Pull request merged**
