### PR TITLE
Testing automatic review assignment

### PR DESCRIPTION
**Pull request by aireilly**
Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@aireilly I don't think this one should have tagged me for review. Not sure if you were looking for input on these from us yet or not

**Comment by aireilly** [comment]
> @aireilly I don't think this one should have tagged me for review. Not sure if you were looking for input on these from us yet or not

No it shouldn't have. But also. Pretty sure this workflow is not going to work for us. The assignments get made automatically as soon as the PR is opened.

**Pull request closed without merging**
