### PR TITLE
FCOS VMDK version confusion when installing OKD on AWS

### LINKED ISSUE #356: docs: FCOS VMDK version confusion when installing OKD on AWS
**Describe the bug**

I was requested by @vrutkovs to submit a docs bug around a confusing step for "Uploading a custom FCOS AMI in AWS" that appears a couple of times on the OKD docs website.

The sentence:
> The FCOS VMDK file must be the highest version that is less than or equal to the OKD version you are installing.

My question on slack: FCOS stable is currently at version 32, while OKD is at 4.5. How do these two versions relate? How can I make sure I am downloading the correct FCOS image for a particular version of OKD?

The recommendation/answer: it makes sense for OCP but needs to be removed from OKD docs. In OKD case you'd pick the latest stable VMDK

Pages I found that had this step listed:

1. https://docs.okd.io/latest/installing/installing_aws/installing-aws-user-infra.html#installation-aws-upload-custom-rhcos-ami_installing-aws-user-infra
2. https://docs.okd.io/latest/installing/installing_aws/installing-aws-government-region.html#installation-aws-upload-custom-rhcos-ami_installing-aws-government-region

Thank you!

**Version**

N/A

**How reproducible**

N/A

**Log bundle**

N/A

### PR DESCRIPTION
**Pull request by mburke5678**
/fixes https://github.com/openshift/okd/issues/356

### CODE REVIEW

**Comment by mburke5678** [comment]
Preview: https://issue-356--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-government-region.html#installation-aws-upload-custom-rhcos-ami_installing-aws-government-region

**Comment by mburke5678** [comment]
@vrutkovs PTAL 
https://github.com/openshift/openshift-docs/pull/28731

**Review by vrutkovs — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Comment by mburke5678** [comment]
Fixes https://github.com/openshift/okd/issues/356

**Pull request merged**
