### PR TITLE
SVRCOM-2208 restore TP for some runtimes

### PR DESCRIPTION
**Pull request by gabriel-rh**
Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-2208

Link to docs preview:
https://53913--docspreview.netlify.app/openshift-enterprise/latest/serverless/serverless-release-notes.html#new-features-1.26_serverless-release-notes
"New features
OpenShift Serverless Functions with Quarkus is now GA."

https://53913--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-quarkus-functions.html
(moved up in sidebar nav)

https://53913--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-nodejs-functions.html
"OpenShift Serverless Functions with NodeJS is a Technology Preview feature only..."

https://53913--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-typescript-functions.html
"OpenShift Serverless Functions with TypeScript is a Technology Preview feature only..."

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Review by lance — COMMENTED** [review]
/lgtm

**Review by rolfedh — APPROVED** [review]
LGTM

**Comment by jrangelramos** [comment]
QE Approved

**Comment by rh-max** [comment]
@gabriel-rh For 1.25, we agreed to instead of deleting this TP note:

https://github.com/openshift/openshift-docs/pull/53841/files#diff-4c56c4a6617baf201863d434beada953821b3bc77459fcd7c86675c902af3d7aL12

To modify it as follows:
```
:FeatureName: `node`, `typescript`, `go`, `python`, `springboot`, and `rust` function runtimes
+include::snippets/technology-preview.adoc[leveloffset=+1]
```

I suggest you use the same, minus the DPed runtimes.

**Pull request merged**
