### PR TITLE
OADP-298 Fixed indentation in yaml example.

### PR DESCRIPTION
**Pull request by stoobie**
This fixes: https://issues.redhat.com/browse/OADP-298

This applies to:
enterprise-4.9
enterprise-4.10
enterprise-4.11 (main)

Preview:
https://deploy-preview-42628--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html

### CODE REVIEW

**Comment by stoobie** [comment]
@kaovilai FYI, this replaces yours.

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by kaovilai — APPROVED** [review]

**Comment by stoobie** [comment]
@skrthomas This is ready for merge. I know we're in a freeze at the moment, so post-freeze is fine.

**Comment by kaovilai** [comment]
@skrthomas @stoobie 
Can we get these picked for 4.6, 4.7, 4.8 too ?

**Pull request merged**
