### PR TITLE
PSAP-900: added tuned release note update

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12

Issue:
[PSAP-900](https://issues.redhat.com//browse/PSAP-900)

Link to docs preview:
[Tuned profile](http://file.rdu.redhat.com/antaylor/psap-900/release_notes/ocp-4-12-release-notes.html#ocp-4-12-tuned)

Additional information:
Documenting a new setting enabled by default in the 4.12 release notes.

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@jmencak PTAL, thanks!

**Comment by jmencak** [comment]
/lgtm
Note that this will be effective once we have an updated TuneD FDP package, which we still do not have.  Also, when this happens, the changes will automatically happen to OCP 4.10, 4.11 and 4.12.

**Review by adellape — APPROVED** [review]

**Pull request merged**
