### PR TITLE
Add PHP DOCUMENTROOT environment variable

### PR DESCRIPTION
**Pull request by andrewklau**
Docs for this commit https://github.com/sclorg/s2i-php-container/commit/9fbddc8f7951feaa069a7b3910c55f1d0b119f56

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@andrewklau - does this apply to a particular enterprise version? 3.2 onwards?

**Comment by andrewklau** [comment]
I'm not too sure. It's been available in the origin/centos versions for a while.

**Comment by ahardin-rh** [comment]
Sorry for the long delay. Picking this back up. Looks like `DOCUMENTROOT` is mentioned in 3.2+, so I will label this as such. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/s2i_images/php.adoc#using-images-s2i-images-php[Source-to-Image (S2I) -> PHP]
|Added the `DOCUMENTROOT` environment variable to the PHP Environment Variables table.
%

**Pull request merged**
