### PR TITLE
OSDOCS-4798 Added another GCP Constraint

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-4798](https://issues.redhat.com//browse/OSDOCS-4798)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4798

Link to docs preview:
OSDOCS: https://56602--docspreview.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @xueli181114! Can I please have a review of this, when you have a spare moment? Thank you!

**Review by arendej — APPROVED** [review]
approved

**Comment by xueli181114** [comment]
LGTM

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1: 

/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
