### PR TITLE
RHDEVDOCS-3629 - Updating 4.6 EventRouter template to match 4.7+

### PR DESCRIPTION
**Pull request by libander**
Team: DevTools

Updated EventRouter template in 4.6 docs to match template in 4.7 - 4.10.

### CODE REVIEW

**Review by anpingli — COMMENTED** [review]
.Example output **changed**
[source,terminal]
----
serviceaccount/eventrouter created
clusterrole.authorization.openshift.io/event-reader created
clusterrolebinding.authorization.openshift.io/event-reader-binding created
configmap/eventrouter created
deployment.apps/eventrouter created

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by anpingli** [comment]
Must we use 0.3 in Openshift 4.6? We are still releasing 4.6  https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1995200

**Comment by anpingli** [comment]
I suggest using registry.redhat.io/openshift4/ose-logging-eventrouter:v4.6 in v4.6.

**Comment by anpingli** [comment]
I suggest using registry.redhat.io/openshift4/ose-logging-eventrouter:v4.6 in Openshift v4.6. @jcantrill  WDYT?

**Pull request closed without merging**
