### PR TITLE
CNV-21590: kubectl to oc

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.10+

Issue: [CNV-21590](https://issues.redhat.com//browse/CNV-21590)

Link to docs preview: https://51325--docspreview.netlify.app/openshift-enterprise/latest/virt/upgrading-virt.html#virt-viewing-outdated-workloads_upgrading-virt

QE review:
- [ ] QE has approved this change.

Additional information: n/a

### CODE REVIEW

**Comment by ousleyp** [comment]
Hi @djfjeff , please review this fix when you get the chance. Thanks!

**Comment by djfjeff** [comment]
Looks good to me, thanks!

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
