### PR TITLE
BZ1879066: modify the note regarding session persistence for 4.6

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applicable for 4.6

Doc preview link: https://deploy-preview-35546--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-network-user-infra_installing-bare-metal

https://bugzilla.redhat.com/show_bug.cgi?id=1879066

Requires QA ack from @gpei

### CODE REVIEW

**Comment by mburke5678** [comment]
@chinmayi-chandrasekar LGTM. Is this change only for 4.6??

**Comment by chinmayi-chandrasekar** [comment]
> @chinmayi-chandrasekar LGTM. Is this change only for 4.6??

Yes.

**Comment by lihongan** [comment]
LGTM
Thank you @chinmayi-chandrasekar

**Comment by mburke5678** [comment]
@chinmayi-chandrasekar LGTM

**Pull request merged**
