### PR TITLE
BZ-2020416: IPv6 is not supported for user-provisioned clusters

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://bugzilla.redhat.com/show_bug.cgi?id=2020416

Preview (no mention of IPv6): https://deploy-preview-38463--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-configuration-parameters-network_installing-bare-metal

### CODE REVIEW

**Comment by sjstout** [comment]
LGTM! :)

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
