### PR TITLE
Replacing "upgrade" wording in update docs

### PR DESCRIPTION
**Pull request by skopacz1**
Versions: 4.14+

This PR sweeps through the procedural content in the update docs and replaces instances of "upgrade" with the preferred term per the glossary, "update". The scope is limited to paragraph and heading content, and does not include commands, metadata, URLs, or any other instances that cannot be changed.

Preview:

- [Updating a cluster using the CLI](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli.html)
- [Updating a cluster using the web console](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-web-console.html)
- [Performing an EUS-to-EUS update](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/eus-eus-update.html)
- [Performing a canary rollout update](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/update-using-custom-machine-config-pools.html)
- [Updating a cluster that includes RHEL compute machines](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-rhel-compute.html)
- Updating a cluster in a disconnected environment
  - [About cluster updates in a disconnected environment](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating_disconnected_cluster/index.html)
  - [Mirroring OpenShift Container Platform images](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating_disconnected_cluster/mirroring-image-repository.html)
  - [Updating a cluster in a disconnected environment using OSUS](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating_disconnected_cluster/disconnected-update-osus.html)
  - [Updating a cluster in a disconnected environment without OSUS](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating_disconnected_cluster/disconnected-update.html)
- [Updating hardware on nodes running on vSphere](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-hardware-on-nodes-running-on-vsphere.html)
- [Migrating to a cluster with multi-architecture compute machines](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/migrating-to-multi-payload.html)
- [Updating hosted control planes](https://61788--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-hosted-control-planes.html)

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Looks great @skopacz1! Merging

**Pull request merged**
