### PR TITLE
Correct Elasticsearch naming

### PR DESCRIPTION
**Pull request by codyhoag**
@vikram-redhat I spotted an Elasticsearch capitalization issue, and went ahead and corrected everywhere. Does this look OK?

This could present some cherry pick issues. I can manually send to 4.1/4.2 if any creep up.

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
I suggest performing manual cherry picks and making sure that you've corrected all instances in each branch.

**Comment by vikram-redhat** [comment]
Looks good Cody. Thanks!

**Comment by codyhoag** [comment]
@kalexand-rh yeah; good call. I'll link those manual cherry picks in this PR when they're sent.

**Comment by codyhoag** [comment]
@vikram-redhat @kalexand-rh 

Manual changes made:

4.1: #17964 
4.2: #17965

If my understanding of the branches is correct, `master` is the same as `enterprise-4.3`, so I didn't do a manual cherry pick there. Let me know if that's necessary.

Please merge if everything looks good. Thanks!

**Comment by jboxman** [comment]
@codyhoag, _master_ is actually whatever the release after 4.3 will be. Definitely cherry-pick to 4.3 as well.

Thanks!

**Comment by codyhoag** [comment]
Thanks for explaining, @jboxman!

Here's the 4.3-specific PR: #17967

**Comment by codyhoag** [comment]
@vikram-redhat can you merge this PR if all looks good? Here are the manual cherry picks:

#17964 
#17965 
#17967

**Comment by vikram-redhat** [comment]
All done

**Pull request merged**
