### PR TITLE
added root_squash back to NFS

### PR DESCRIPTION
**Pull request by erinboyd**
@adellape @screeley44 @jeffvance Please review. Required for NFS security.

### CODE REVIEW

**Comment by adellape** [comment]
@erinboyd So https://github.com/openshift/openshift-docs/pull/1123 was not accurate?

**Comment by erinboyd** [comment]
No, that one was removing all_root_squash and no_root_squash.

We want the export to have (rw, root_squash)

Erin

**Comment by adellape** [comment]
Thanks, merging.

**Comment by nak3** [comment]
@erinboyd

You deleted `chmod 777 /<example_fs>` in your PR https://github.com/openshift/openshift-docs/pull/1142
`root_squash` needs NFS admin's  chmod to `/<example_fs>`. 

As far as I tested, current instruction in the doc doesn't work. We need some guide for the permission change for the `/<example_fs>`. Could you please update the doc, @erinboyd ?

**Comment by jeffvance** [comment]
This nfs doc appears under the openshift-docs/install_config/persistent_storage/ dir where I submitted PR #. (https://github.com/openshift/openshift-docs/pull/1564)[1564]. Did it get moved to ./admin_guide/ in v3.2?

**Comment by adellape** [comment]
@jeffvance The persistent_storage dir was moved from admin_guide to install_config (where it currently lives) when 3.1 was released.

**Comment by nak3** [comment]
Needs to set `777` is one of bug... I filed it https://bugzilla.redhat.com/show_bug.cgi?id=1318080

**Comment by erinboyd** [comment]
@nak3 it should not be set to 777. Please consult the proper instructions.

**Comment by nak3** [comment]
@erinboyd yes, sorry I didn't notice that we can setup `supplementalyGroups` manually. Thanks.

**Pull request merged**
