### PR TITLE
Editing out arch/networking content for dedicated

### PR DESCRIPTION
**Pull request by bfallonf**
Will verify over email

cc @spurtell @vikram-redhat @ahardin-rh 

Preview build: http://file.bne.redhat.com/bfallonf/28052018/arch_routes/routes_arch/architecture/networking/networking.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
:+1:

**Comment by bfallonf** [comment]
Thumbs up all round. Merging.

**Comment by bfallonf** [comment]
Met with conflicts, so:

3.10: https://github.com/openshift/openshift-docs/pull/9682
3.9: https://github.com/openshift/openshift-docs/pull/9683
3.7: https://github.com/openshift/openshift-docs/pull/9684

cc @vikram-redhat

**Pull request merged**
