### PR TITLE
Update configuring_aws.adoc

### PR DESCRIPTION
**Pull request by laidback**
Update the document to conform with:
https://github.com/kubernetes-incubator/kube-aws/issues/1025
https://github.com/kubernetes/kubernetes/blob/v1.8.3/pkg/cloudprovider/providers/aws/tags.go#L44-L51

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@laidback Thanks! These changes look good to me. Just needs a rebase.
@jhou1 Can you please give this a QE review? Thanks!

**Comment by jhou1** [comment]
@chao007  PTAL

**Comment by chao007** [comment]
LGTM

**Comment by kalexand-rh** [comment]
@laidback, please rebase this PR so we can merge it.

**Comment by kalexand-rh** [comment]
@laidback, please rebase this PR so we can merge it.

**Comment by kalexand-rh** [comment]
This change goes back to [at least K8 1.6](https://github.com/kubernetes/kubernetes/blob/v1.6.3/pkg/cloudprovider/providers/aws/tags.go#L44-L51), so I'm going to open a new PR to merge it and cherry-pick it back to 3.6.

**Comment by kalexand-rh** [comment]
Finishing on https://github.com/openshift/openshift-docs/pull/10434

**Pull request closed without merging**
