### PR TITLE
SRVKS-753: Add deprecated note to serverless metering doc

### PR DESCRIPTION
**Pull request by abrennan89**
Applies for OCP 4.6+

Jira: https://issues.redhat.com/browse/SRVKS-753

Direct preview link: https://deploy-preview-33754--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-metering.html

### CODE REVIEW

**Comment by jrangelramos** [comment]
looks good to me
QE Approved

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
