### PR TITLE
Ocp migration 4 to 4

### PR DESCRIPTION
**Pull request by apinnick**
Formatted doc preview: http://file.tlv.redhat.com/~apinnick/ocp-migration-4-to-4/migration/migrating-4-4/migrating-openshift-4-to-4.html

### CODE REVIEW

**Comment by jwmatthews** [comment]
The steps in 'modules/migration-configuring-cors-4.adoc' need to be updated.
OCP 4.1 and OCP 4.2 have different setup steps.

Please see:  https://github.com/fusor/mig-operator/blob/master/README.md#openshift-4

**Comment by XinRedhat** [comment]
`:migrating-openshift-4-to-4!:` should be removed, right?
>Configuring cross-origin resource sharing on the OpenShift Container Platform 4.1 source cluster to enable communication with the CAM tool on the target cluster :migrating-openshift-4-to-4!:

**Comment by XinRedhat** [comment]
migration_controller and migration_ui can be deployed on OCP 4.1 or OCP 4.2. On which cluster to configure cross-origin resource depends on migration_controller installation. For example, if migration_controller installs in OCP 4.1, you should configure cross-origin resource in  OCP4.2. And note that configuring cross-origin resource has different setup steps OCP 4.1 and OCP 4.2.

**Comment by XinRedhat** [comment]
The number 3 should be changed to 4
>Cross-origin resource sharing must be configured on the OpenShift Container Platform 3 source cluster.

**Comment by XinRedhat** [comment]
Should cpma support 4=>4 migration? As there is no configuration files, such like /etc/origin/master/master-config.yaml .

**Comment by apinnick** [comment]
Moving changes to updated branch

**Pull request closed without merging**
