### PR TITLE
[OSDOCS-5514]: Release note about hosted control planes book and update to TP table

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-5514

Link to docs preview:
- TP table (See Architecture Technology Preview features section): https://58578--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-technology-preview
- Relnote entry: https://58578--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-hcp-book

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lahinson** [comment]
@zanetworker PTAL at this release note when you can. Thanks!

**Review by zanetworker — APPROVED** [review]
lgtm

**Pull request merged**
