### PR TITLE
BZ2026162 -update step order for troubleshooting managedCluster

### PR DESCRIPTION
**Pull request by slovern**
https://bugzilla.redhat.com/show_bug.cgi?id=2026162

For releases: 
- 4.9
- 4.10
- 4.11

### CODE REVIEW

**Comment by slovern** [comment]
@imiller0 Could you let me know if this looks good to you?
Thanks,
Shane

**Review by imiller0 — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@slovern LGTM

**Pull request merged**
