### PR TITLE
CNV-18768: VM metrics tab

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: [CNV-18768](https://issues.redhat.com//browse/CNV-18768)

Link to docs preview: [Reviewing resource usage by virtual machines](https://54338--docspreview.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-reviewing-vm-dashboard.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mburke5678** [comment]
@apinnick One nit. Otherwise LGTM

**Comment by apinnick** [comment]
> @apinnick One nit. Otherwise LGTM

@mburke5678 What is the nit?

**Comment by mburke5678** [comment]
@apinnick My bad. Monday error. Apparently, instead of adding a comment, I started a review, but didn't finish the review. Apparently, if you start a review and don't submit, the comments are hidden.  My [comment is now visible](https://github.com/openshift/openshift-docs/pull/54338#discussion_r1064594326) above.

**Comment by apinnick** [comment]
> @apinnick My bad. Monday error. Apparently, instead of adding a comment, I started a review, but didn't finish the review. Apparently, if you start a review and don't submit, the comments are hidden. My [comment is now visible](https://github.com/openshift/openshift-docs/pull/54338#discussion_r1064594326) above.

@mburke5678 No worries. I've done exactly the same thing, more times than I can count. I guess I could fix the formatting. Thanks.

**Pull request merged**
