### PR TITLE
[11868]:What's new for OSD on GCP: Support Document Support A2 (NVIDIA A100 80 GB) GCP nodes

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-11868
Link to docs preview:

https://81274--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_whats_new/osd-whats-new.html
QE review:
- [ ] QE has approved this change.

NO QE REQUIRED/This is an addition to "What's New" in OSD docs based on https://issues.redhat.com/browse/OSDOCS-11556
Additional information:

### CODE REVIEW

**Comment by aldiazRH** [comment]
LGTM!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
