### PR TITLE
OCPBUGS#4634 Use config CR instead of operator CR

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-4634

Link to docs preview:
https://53828--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/converting-to-dual-stack.html#nw-dual-stack-convert-back-single-stack_converting-to-dual-stack

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by cbippley** [comment]
@zhaozhanqi Please take a look, thanks!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@cbippley Actually, my apologies. I missed checking which branch this PR was opened against.

Since this is an issue in 4.11 and forward, this PR should actually have been opened against `main`. Then it would get cherry picked to 4.11 and 4.12.

We have some instructions in the manual on how to fix when you need to change your base branch. See https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.5s75lq4bcdl5

It's a two-step process: first you fix your local branch and push it, then you edit this PR to change the branch you're trying to merge into. Let me know if you run into any issues with this. Thanks!

**Comment by bergerhoffer** [comment]
LGTM now thanks! Merging

**Pull request merged**
