### PR TITLE
[enterprise-3.11] Complete 'Expanding service network' without playbook

### PR DESCRIPTION
**Pull request by eitchugo**
PR for enterprise-3.11. More information on issue #17227

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jboxman, will you PTAL?

**Comment by vikram-redhat** [comment]
@jboxman can you please move this forward or close if not relevant?

**Comment by jboxman** [comment]
Hi @danwinship, can you confirm if this change makes sense for _OCP 3.11_?

**Comment by jboxman** [comment]
@weliang1, can you verify this?

Screen Shot 2020-07-16 at 10 11 31 PM

Thanks!

**Comment by jboxman** [comment]
I'm going to merge this, and then cleanup in a fixup commit.

**Comment by jboxman** [comment]
Actually, going to merge under separate cover.

**Pull request closed without merging**
