### PR TITLE
OBSDOCS-902: YAML block bug fix

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.16, 4.15, 4.14, 4.13, 4.12

Issue:

https://issues.redhat.com/browse/OBSDOCS-902

Link to docs preview:

https://73103--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-sending-traces-and-metrics-to-otel-collector#sending-traces-and-metrics-to-otel-collector-without-sidecar_otel-sending-traces-and-metrics-to-otel-collector

QE review:
- [x] QE has approved this change. See QE's comment below: https://github.com/openshift/openshift-docs/pull/73103#issuecomment-1996504232

Additional information:

### CODE REVIEW

**Comment by IshwarKanse** [comment]
@max-cx In the step 3 in https://docs.openshift.com/container-platform/4.12/otel/otel-sending-traces-and-metrics-to-otel-collector.html#sending-traces-and-metrics-to-otel-collector-without-sidecar_otel-sending-traces-and-metrics-to-otel-collector The serviceaccount name in the subjects must be otel-collector-deployment like below.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector-deployment
  namespace: observability
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io
```

**Comment by agantony** [comment]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by IshwarKanse — APPROVED** [review]

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/lgtm

**Review by jeana-redhat — APPROVED** [review]
easy-breezy, LGTM :D

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
