### PR TITLE
OSDOCS-8988: adds FIPS release note MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.15 only

Issue:
https://issues.redhat.com/browse/OSDOCS-8988

Link to docs preview:
[FIPS release note](https://69381--docspreview.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes#microshift-4-15-security)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@eslutsky could you PTAL?

**Comment by mburke5678** [comment]
@ShaunaDiaz One nit. Otherwise LGTM

**Pull request merged**
