### PR TITLE
corrected variables for logging and metrics in upgrading docs

### PR DESCRIPTION
**Pull request by bfallonf**
For:
https://bugzilla.redhat.com/show_bug.cgi?id=1486255
https://bugzilla.redhat.com/show_bug.cgi?id=1486266

Will verify in the BZ.

### CODE REVIEW

**Comment by bfallonf** [comment]
Verified. @openshift/team-documentation PTAL

**Comment by bfallonf** [comment]
And the second commit is for https://bugzilla.redhat.com/show_bug.cgi?id=1441049

**Comment by mburke5678** [comment]
@bfallonf LGTM

**Comment by bfallonf** [comment]
Third commit for: https://bugzilla.redhat.com/show_bug.cgi?id=1486938

**Comment by adellape** [comment]
@bfallonf @mburke5678 The `admin_guide/scheduling/node_selector.adoc` topic wasn't added until 3.6+ (via https://github.com/openshift/openshift-docs/pull/4597), so I'm removing the xref to the topic here in the 3.5 branch via https://github.com/openshift/openshift-docs/pull/5747 but leaving the text otherwise.

**Pull request merged**
