### PR TITLE
CNV-27916: [2184998] [DOC] Procedure to edit filesystemOverhead is wrong

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.11+cherrypicks

Issue: 

[CNV-27916](https://issues.redhat.com/browse/CNV-27916)  
[BZ2184998](https://bugzilla.redhat.com/show_bug.cgi?id=2184998)

Link to docs preview: https://60479--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.html

QE review:
- [x] QE has approved this change.

Additional information:
Corrected indentation in sample file.

### CODE REVIEW

**Comment by aspauldi** [comment]
@nashok@redhat.com, please review the updated content and let me know if it's correct. Thanks.

**Comment by aspauldi** [comment]
Hi @nashok@redhat.com, can you please take a look at the corrected indentation and let me know if it's okay now? Thanks.

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Comment by ousleyp** [comment]
LGTM! :)

**Pull request merged**
