### PR TITLE
GH57499:[OKD] Broken link to install service mesh

### PR DESCRIPTION
**Pull request by mburke5678**
For OKD, remove OSSM from Post-install -> Network configuration

Link to docs preview (VPN needed):
OKD: Post-install -> [Network configuration](http://file.rdu.redhat.com/mburke/okd-remove-ossm/post_installation_configuration/network-configuration.html)

OCP : Post-install -> [Network configuration](https://docs.openshift.com/container-platform/4.12/post_installation_configuration/network-configuration.html)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mburke5678** [comment]
[LGTM in GH Issue](https://github.com/openshift/openshift-docs/issues/57499#issuecomment-1480849745)

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Comment by vrutkovs** [comment]
LGTM, thanks!

**Review by kelbrown20 — COMMENTED** [review]
Updates lgtm!

**Pull request merged**
