### PR TITLE
[SRVKS-1163] Linking Kafka related info in one place

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVKE-1163

Link to docs preview:
- https://78537--ocpdocs-pr.netlify.app/openshift-serverless/latest/eventing/kube-rbac-proxy-eventing.html
- https://78537--ocpdocs-pr.netlify.app/openshift-serverless/latest/install/serverless-kafka-admin.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by maschmid** [comment]
There seems to be a bug in `modules/serverless-configuring-kube-rbac-proxy-resources-for-kafka.adoc` 

```
spec:
  config:
    workload:
      "kube-rbac-proxy-cpu-request": "10m" 
      "kube-rbac-proxy-memory-request": "20Mi" 
      "kube-rbac-proxy-cpu-limit": "100m" 
      "kube-rbac-proxy-memory-limit": "100Mi" 
```

should be `.spec.config.deployment` instead (same as in  Eventing and Serving)
```
spec:
  config:
    deployment:
      "kube-rbac-proxy-cpu-request": "10m" 
      "kube-rbac-proxy-memory-request": "20Mi" 
      "kube-rbac-proxy-cpu-limit": "100m" 
      "kube-rbac-proxy-memory-limit": "100Mi" 
```

This error was probably introduced when the deprecated `.spec.deployments` was renamed to `.spec.workloads`, however, the `.spec.config.deployment` is a different thing.

**Review by snarayan-redhat — COMMENTED** [review]
LGTM!

**Pull request merged**
