### PR TITLE
ROX-23256: Update Cloud Service graphic with Scanner V4

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
`rhacs-docs-4.4`
`rhacs-docs-4.5`

[Issue](https://issues.redhat.com/browse/ROX-23256)

[Link to docs preview
](https://76208--ocpdocs-pr.netlify.app/openshift-acs/latest/cloud_service/acscs-architecture.html)

QE review:
- [ ] QE has approved this change. **ACS has no QE, approved by SME**

Additional information:

See https://github.com/openshift/openshift-docs/pull/76261 for redirect.

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Comment by mletalie** [comment]
image

**Review by mletalie — COMMENTED** [review]
/remove label peer-review-in-progress
/remove label peer-review-needed
/label peer-review-done
/lgtm

**Comment by kcarmichael08** [comment]
> Hello @kcarmichael08! This may be outside the scope of this ticket but do we need the same call out (as seen in attached image) in such close proximity to each other?

Oh, good catch - I don't think so. I'll remove the second one.

**Pull request merged**
