### PR TITLE
Added Information on current TP version to 3.10 installation instruct…

### PR DESCRIPTION
**Pull request by geekspertise**
I added an Important note to the Supported configurations section of the Installation documentation to be merged into the 3.10 branch. @knrc and @brian-avery can you have a look?

### CODE REVIEW

**Comment by brian-avery** [comment]
LGTM. Thanks!

**Comment by knrc** [comment]
+1, lgtm.  Thanks for chasing this

**Comment by geekspertise** [comment]
@ahardin-rh Apparently I can't cherrypick from here. Can you help?

**Comment by ahardin-rh** [comment]
@geekspertise Looks like there are some conflicts, so I will do a manual cherry-pick of this.

**Pull request merged**
