### PR TITLE
Modified command snippets and YAML samples according to RHDEVDOCS - 2625, 2626, and 2638

### PR DESCRIPTION
**Pull request by sounix000**
**Aligned team**: Dev Tools

**OCP version for cherry-picking**: `4.7`, `4.8`

**JIRA issues**:
- [RHDEVDOCS-2625](https://issues.redhat.com/browse/RHDEVDOCS-2625)
- [RHDEVDOCS-2626](https://issues.redhat.com/browse/RHDEVDOCS-2626)
- [RHDEVDOCS-2628](https://issues.redhat.com/browse/RHDEVDOCS-2628)

**Preview pages**: Command snippets and YAML samples in the following pages:
- [Configuring CPU and memory limits](https://deploy-preview-30943--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-memory.html#cluster-logging-memory-limits_cluster-logging-memory)
- [Using tolerations to control OpenShift Logging pod placement](https://deploy-preview-30943--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-tolerations.html)
- [Configure log collector CPU and memory limits](https://deploy-preview-30943--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-collector.html#cluster-logging-collector-limits_cluster-logging-collector)

**Reviewer SME/QE**: Oscar Casal Sanchez (@r2d2rnd)

### CODE REVIEW

**Comment by r2d2rnd** [comment]
Perhaps, for being more coherent with the rest of the documentation, it could be changed this:

 $ oc edit ClusterLogging instance -n openshift-logging

By this:

 $ oc -n openshift-logging edit ClusterLogging instance

Does it make sense for you this change @sounix000 ?

**Comment by sounix000** [comment]
> Perhaps, for being more coherent with the rest of the documentation, it could be changed this:
> 
> $ oc edit ClusterLogging instance -n openshift-logging
> 
> By this:
> 
> $ oc -n openshift-logging edit ClusterLogging instance
> 
> Does it make sense for you this change @sounix000 ?

@r2d2rnd - TBH, I have mostly seen the convention `tool verb -[option|flag] <value>`. But what you are suggesting also makes sense, because it basically translates to the following generic statement - "In the given namespace, do something about this custom resource of that instance." You are the SME - I will do whatever you suggest as a final call.

**Pull request merged**
