### PR TITLE
OSDOCS-3462-re: Removed port 80 reference from AWS firewall pre in RO…

### PR DESCRIPTION
**Pull request by dfitzmau**
Jira: [OSDOCS-3462](https://issues.redhat.com/browse/OSDOCS-3462)

Version(s):
ROSA (4.15, 4.14)

Link to docs preview:
[AWS firewall prerequisites](https://69896--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs#osd-aws-privatelink-firewall-prerequisites_rosa-sts-aws-prereqs)

SME review:
- [X] SME has approved this change.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by AbhishekSheth7** [comment]
Looks good to me.

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
