### PR TITLE
OCPBUGS-29468 SR-IOV operator non existing 4.14/4.15 channel

### PR DESCRIPTION
**Pull request by kquinn1204**
[OCPBUGS-28813]: SRIOV operator] Non existing 4.14/4.15 channel should read stable 

Version(s):main, 4.15. 4.14

Issue:https://issues.redhat.com/browse/OCPBUGS-28813

Link to docs preview:https://71670--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/hardware_networks/installing-sriov-operator.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by kquinn1204** [comment]
@zeeke Can you add LGTM if happy all around channel now being stable

**Comment by zeeke** [comment]
LGTM

Thanks for fixing this!

**Pull request merged**
