### PR TITLE
BZ1762753 correct 'tuningset' field name to 'tuningsets'

### PR DESCRIPTION
**Pull request by jeana-redhat**
https://bugzilla.redhat.com/show_bug.cgi?id=1762753

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by jeana-redhat** [comment]
@wjiangjay this is regarding https://bugzilla.redhat.com/show_bug.cgi?id=1762753
Please take a look and make sure I have it fixed correctly.

**Comment by jeana-redhat** [comment]
QE verified. @kalexand-rh please merge and CP to 3.11

**Pull request merged**
