### PR TITLE
OSDOCS-12780: Update incorrect GPU values in CAS example spec

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-12780](https://issues.redhat.com//browse/OSDOCS-12780)

Link to docs preview:
[Cluster autoscaler resource definition](https://85513--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@elmiko PTAL for this part (correcting the CAS YAML). 

I think when I update the machine set side, I'll add a line here directing them to the machine set docs for details.

**Review by elmiko — COMMENTED** [review]
i think this looks great, much clearer than before.

/lgtm

**Comment by jeana-redhat** [comment]
Thanks, Mike! @miyadav PTAL for QA :bow:

**Review by bscott-rh — APPROVED** [review]
Peer review LGTM.

**Pull request merged**
