### PR TITLE
TELCODOCS-791-Older: Apply Upgrade section to older versions

### PR DESCRIPTION
**Pull request by tshwartz**
Version(s):
4.10

Issue:
(https://issues.redhat.com/browse/TELCODOCS-791?filter=-1&jql=resolution%20in%20(Unresolved%2C%20Done)%20AND%20assignee%20in%20(currentUser())%20order%20by%20updated%20DESC)

Link to docs preview:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@jboxman-rh @tshwartz Just checking in on the status of this PR, since it says merge-review-in-progress, but hasn't been merged. Since it looks like it now is in conflict, can we remove that label, and then re-add the merge-review-needed when it's ready to merge?

**Comment by tshwartz** [comment]
Hi @jboxman-rh and @bergerhoffer, I am waiting to see if it needs merging into 4.9 and haven't received and answer yet. So yes, removing the label was fine. If it doesn't need merging, I'll go ahead and close the PR. Thanks for your feedback.

**Comment by tshwartz** [comment]
Closing the PR.

**Pull request closed without merging**
