### PR TITLE
Update prerequisites.adoc

### PR DESCRIPTION
**Pull request by arsogukpinar**
Public IaaS is not a requirement. I can be either public or private.

### CODE REVIEW

**Comment by adellape** [comment]
@arsogukpinar Thanks. Can you change them to say "public or private" instead of a slash?

**Comment by arsogukpinar** [comment]
@adellape, Ok. I have changed it.

**Comment by adellape** [comment]
Rev history note:

"Updated the System Requirements section to clarify that instances can be running on a private IaaS, not just a public one."

**Comment by tnguyen-rh** [comment]
@adellape @arsogukpinar 
Thanks for this change.  Note for next time: squash before merge helps simplify cherry-picking later.

**Comment by adellape** [comment]
> squash before merge helps simplify cherry-picking later.

+1

**Pull request merged**
