### PR TITLE
CNV-18330: RN DPDK checkup and configuring VM for DPDK

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.13

Issue: [CNV-18330](https://issues.redhat.com//browse/CNV-18330)

Link to docs preview: http://file.rdu.redhat.com/sjhala/cnv-18330/virt/virt-4-13-release-notes.html#virt-4-13-technology-preview

QE review:
- [x] QE has approved this change.

Additional information: This PR covers two TP release notes - one for the DPDK checkup and another for configuring VM for DPDK workloads

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
LGTM

**Comment by sjhala-ccs** [comment]
@yossisegev Can you please review?

**Comment by yossisegev** [comment]
lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
