### PR TITLE
GH#37930 Update RHCOS registry URL for firewall

### LINKED ISSUE #37930: [enterprise-4.9] Issue in file installing/install_config/configuring-firewall.adoc
### Which section(s) is the issue in?

Configuring your firewall for OpenShift Container Platform

### What needs fixing?

Section 1 / URL to whitelist
openshift.org --> should not be *.openshift.org ??? Can you check if wildcard is mandatory?

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #37930

Preview: https://deploy-preview-38559--osdocs.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall

### CODE REVIEW

**Comment by codyhoag** [comment]
@cgwalters can you confirm this update from your prior recommendations?

**Comment by cgwalters** [comment]
I glanced and this LGTM.  Better to get something more accurate out now.

**Comment by codyhoag** [comment]
@miabbott can you verify from a QE perspective?

**Comment by lautou** [comment]
Hi it's **.openshiftapps.com* that should be whitelisted and not *openshiftapps.com*. Please add the wildcard otherwise firewalls will not allow the traffic for this subdomain.

**Comment by miabbott** [comment]
I think the wildcard suggestion is wise; otherwise LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
