### PR TITLE
[OSDOCS-6368]: Add infrastructure reqs for hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-6368

Link to docs preview: https://62225--docspreview.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-configuring.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jiezhao16** [comment]
lgtm

**Review by jparrill — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by opayne1 — COMMENTED** [review]
lgtm!

**Pull request merged**
