### PR TITLE
Backporting netobserv to 4.10, 4.11

### PR DESCRIPTION
**Pull request by skrthomas**
ATTN PEER REVIEW: This is an exact mirror of the content live at 4.12. Peer review should not be heavy handed as content updates really shouldn't be happening in this PR. 
Version(s):

4.10, 4.11
Issue:

https://issues.redhat.com/browse/OSDOCS-5246
Link to docs preview:

https://55720--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/network-observability-overview.html

4.12 docs for 👀 and compare: https://docs.openshift.com/container-platform/4.12/networking/network_observability/network-observability-overview.html
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]

**Comment by skrthomas** [comment]
PM @mcurry-rh has approved this via Slack messages with myself and @ahardin-rh .

**Comment by jeana-redhat** [comment]
Note: checked this against the content in `main` because we think it's most important that this matches `main` (to avoid conflicts later). 

Process:
```
$ git checkout main
$ git fetch upstream pull/55720/head:NOO-4.11
$ git cherry-pick 641e4849d79040c09b93d3c533f7f2c6c0414083
```

Results:
```
Auto-merging _topic_maps/_topic_map.yml
On branch main
Your branch is ahead of 'origin/main' by 250 commits.
  (use "git push" to publish your local commits)

You are currently cherry-picking commit 641e4849d7.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
```

This indicates that the content is identical to what is in `main`. Merging with @skrthomas and @kalexand-rh's blessing, will attempt to CP this to 4.10.

**Pull request merged**
