### PR TITLE
Remove CCM from list of WINC windows services

### PR DESCRIPTION
**Pull request by mburke5678**
Per @aravindhp remove CCM from the list of Windows Services added by WMCO. 4.7-4.9 only. [Slack convo](https://coreos.slack.com/archives/CM4ERHBJS/p1665707017697599?thread_ts=1665602295.644929&cid=CM4ERHBJS).

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
/lgtm

The commit says WE. We only need to remove CCM which is what you have done but the commit and PR description should also reflect that.

**Review by adellape — APPROVED** [review]

**Comment by mburke5678** [comment]
@adellape Thanks!!

**Pull request merged**
