### PR TITLE
OSDOCS-7558: update networking diagram

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-7558

Link to docs preview:
https://65195--docspreview.netlify.app/microshift/latest/microshift_networking/microshift-networking#microshift-network-topology_microshift-networking

QE review:
- N/A, QE approved text changes for technical differences in previous PR.

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@pliurh Could you PTAL and LGTM? This PR just replaces the networking diagram. No other changes made.

**Review by opayne1 — COMMENTED** [review]
lgtm!

**Pull request merged**
