### PR TITLE
Technology Preview 3 - release notes updates

### PR DESCRIPTION
**Pull request by geekspertise**
Updated servicemesh release notes for technology preview 3. @JStickler can you peer review? Already reviewed new content with @knrc and @tvieira.

### CODE REVIEW

**Review by JStickler — CHANGES_REQUESTED** [review]
Just a couple of small fixes, but other than that, LGTM.

**Comment by kalexand-rh** [comment]
Per https://github.com/openshift/openshift-docs/pull/12589, it sounds like these changes should not be applied to 3.10.

**Comment by JStickler** [comment]
@kalexand-rh I've asked for clarification on that from @knrc .

**Comment by knrc** [comment]
@JStickler @kalexand-rh TP3 (maistra 0.3.0) is based on OCP 3.11.

**Comment by JStickler** [comment]
Confirmed that Service Mesh TP3 is only available on 3.11.

**Comment by JStickler** [comment]
@geekspertise, were you going to make updates on this PR so that we can merge it?  At the very least, we probably need to rebase against the latest changes to master.

**Comment by geekspertise** [comment]
@JStickler I rebased and force pushed to the servicemesh branch. @kalexand-rh and @vikram-redhat should be good to merge.

**Comment by kalexand-rh** [comment]
@geekspertise, @JStickler, what's your new release date?

**Comment by JStickler** [comment]
@kalexand-rh Wednesday 10/31.

**Comment by kalexand-rh** [comment]
@JStickler, if I merge now, they should go live overnight. Does that sound good to you?

**Comment by JStickler** [comment]
@kalexand-rh that sounds great.  Thanks!

**Comment by kalexand-rh** [comment]
Great! Merging this PR and https://github.com/openshift/openshift-docs/pull/12578

**Pull request merged**
