### PR TITLE
Pipelines 1.14 RN - Remove jib maven restriction for IBM P/Z

### PR DESCRIPTION
**Pull request by SNiemann15**
OCP version for cherry-picking: 4.7, 4.8
JIRA issues: https://issues.redhat.com/browse/SRVKP-1464
Reviewer: Nourhane Bziouech, Snehlata Mohite
Preview pages: [Release Notes Known Issues
](https://deploy-preview-32119--osdocs.netlify.app/openshift-enterprise/latest/cicd/pipelines/op-release-notes.html#known-issues-1-4_op-release-notes)

cc @sounix000

### CODE REVIEW

**Comment by snehlatamohite** [comment]
jib-maven failure is observed only on PSI due to docker.io pull rate limit exhausted. Also we have observed jib-maven test passed successfully on P & Z if docker limit is not exhausted. 

Error while pulling  adoptopenjdk:8-jre as a part of jib-maven pipeline execution when docker.io pull limit exhausted: 
`"message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
`
PASS logs on P & Z: 
```
[build : build-and-push] [INFO] Getting manifest for base image adoptopenjdk:8-jre...
[build : build-and-push] [INFO] Building resources layer...
[build : build-and-push] [INFO] Building classes layer...
[build : build-and-push] [INFO] Using credentials from Docker config (/tekton/creds/.docker/config.json) for image-registry.openshift-image-registry.svc:5000/catalog-tests/jib-maven
[build : build-and-push] [INFO] The base image requires auth. Trying again for adoptopenjdk:8-jre...
[build : build-and-push] [INFO] Using base image with digest: sha256:e873b3cd76edc27903a5c2d3e92dff993601367149379968ca723fe2ed820036
[build : build-and-push] [INFO]
[build : build-and-push] [INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, org.eclipse.che.examples.HelloWorld]
[build : build-and-push] [INFO]
[build : build-and-push] [INFO] Built and pushed image as image-registry.openshift-image-registry.svc:5000/catalog-tests/jib-maven
[build : build-and-push] [INFO]
[build : build-and-push] [INFO] ------------------------------------------------------------------------
[build : build-and-push] [INFO] BUILD SUCCESS
[build : build-and-push] [INFO] ------------------------------------------------------------------------
[build : build-and-push] [INFO] Total time:  56.714 s
[build : build-and-push] [INFO] Finished at: 2021-04-29T08:12:17Z
[build : build-and-push] [INFO] ------------------------------------------------------------------------

[build : digest-to-results] + cat /workspace/source/target/jib-image.digest
[build : digest-to-results] + tee /tekton/results/IMAGE_DIGEST
[build : digest-to-results] cat: /workspace/source/target/jib-image.digest: No such file or directory

===========================
All tests passed!
===========================
```

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
