### PR TITLE
Removing warning that was only applicable for 4.10

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11

Issue:

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2022/removing-warning/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html#secondary-scheduler-operator-release-notes-1.0.1

Additional information:

### CODE REVIEW

**Comment by ingvagabund** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please review this PR that removes a warning that isn't applicable for 4.11?

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2022/removing-warning/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html#secondary-scheduler-operator-release-notes-1.0.1

**Review by sayjadha — COMMENTED** [review]
LGTM.

**Review by kelbrown20 — COMMENTED** [review]
This also LGTM

**Pull request merged**
