### PR TITLE
RHDEVDOCS-3332 Add "Adding a subsection on making open source more inclusive" to the documentation guidelines

### PR DESCRIPTION
**Pull request by rolfedh**
Background and purpose: Presently, various product release notes within the openshift/openshift-docs repo include a "Making open source more inclusive" subsection. Many of those already do this by using an include statement that points to a `modules/con_making-open-source-more-inclusive.adoc` module. This PR adds guidance to `contributing_to_docs/doc_guidelines.adoc` to use this module, when needed.

- Aligned team: Dev Tools
- For branches: 4.8+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3332
- Direct link to doc preview: https://github.com/rolfedh/openshift-docs/blob/RHDEVDOCS-3332/contributing_to_docs/doc_guidelines.adoc#using-conscious-language
- Reviewed by: @pneedle-rh, @jeana-redhat, @StephenJamesSmith,  @codyhoag 
- <All reviews complete. Please merge now>

### CODE REVIEW

**Comment by rolfedh** [comment]
@jeana-redhat WDYT?

**Review by pneedle-rh — COMMENTED** [review]
@rolfedh I have added a couple of small suggestions. Other than those, this looks great!

**Comment by jeana-redhat** [comment]
Very nice addition to the guidelines :)

**Comment by ctauchen** [comment]
Some context would be helpful. Who should be using this? Where?

**Comment by rolfedh** [comment]
> _in the manual itself_

Yes, @ctauchen. I've done that.

**Review by adellape — APPROVED** [review]

**Pull request merged**
