### PR TITLE
BZ2073333: change SHA to sha

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.8+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2073333

Link to docs preview: https://deploy-preview-45132--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-user-infra-machines-iso_installing-platform-agnostic

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen could you PTAL for QE? Thank you!

**Review by mike-nguyen — APPROVED** [review]

**Pull request merged**
