### PR TITLE
Added 'nodeIP' option to node configuration

### PR DESCRIPTION
**Pull request by pravisankar**
If nodeIP is provided, this IP will be used for pod traffic routing.

### CODE REVIEW

**Comment by pravisankar** [comment]
Related to origin PR: https://github.com/openshift/origin/pull/4459

**Comment by pravisankar** [comment]
@adellape

**Comment by adellape** [comment]
Thanks, will wait for the code to merge.

**Comment by liggitt** [comment]
We need to be clear in the documentation that setting this makes it the preferred way for the master to contact the node (rather than by hostname)

**Comment by bfallonf** [comment]
@pravisankar Looks like the code has merged. Has work completed on this? Might just need a rebase before we can merge it. Thanks!

**Comment by pravisankar** [comment]
rebase done

**Pull request merged**
