### PR TITLE
[enterprise-4.16] OSDOCS#10356: Release notes update: hosted control planes on AWS is GA

### PR DESCRIPTION
**Pull request by xenolinux**
- Update OCP 4.16 release notes to reflect that hosted control planes on AWS is GA in OCP 4.16
- Remove the tech preview banner

Version(s): 4.16 

Issue: https://issues.redhat.com/browse/OSDOCS-10356

Link to docs preview:
- https://75200--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-hcp-aws-ga

- https://75200--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-getting-started.html#hcp-getting-started-aws

- Architecture Technology Preview features: https://75200--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-technology-preview-tables 

QE review:
- [x] QE has approved this change.

Additional information: 

 

- This PR has the change management approvals.
- This needs to be merged after ACM's GA 18th July.

### CODE REVIEW

**Comment by xenolinux** [comment]
Closing in favor of https://issues.redhat.com/browse/ACM-11225

**Comment by kalexand-rh** [comment]
LGTM

**Review by zanetworker — APPROVED** [review]

**Comment by xenolinux** [comment]
Note to the merge reviewer: This PR needs to hold off merging until the ACM 2.11 GA is announced.

**Comment by ShaunaDiaz** [comment]
Looks good to merge!

**Pull request merged**
