### PR TITLE
Bug 1408559, Added a link to the updated Registry and Router Certificates section 

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1408559

Related work:
https://github.com/openshift/openshift-docs/pull/3851

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape PTAL

**Comment by ahardin-rh** [comment]
@adellape bump

**Comment by vikram-redhat** [comment]
@ahardin-rh - can this be merged now? Looking at the changes, since it is only a link update, we should be able to merge it, right?

**Comment by ahardin-rh** [comment]
@vikram-redhat Yes, I will merge this now. If we need to make any adjustments, I can follow up in a separate PR. Thanks!

**Comment by ahardin-rh** [comment]
Link addition. No revision history needed.

**Pull request merged**
