### PR TITLE
Updated OpenShift instances to {product-title} in XPaaS Images

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tpoitras @tnguyen-rh PTAL

**Comment by adellape** [comment]
@ahardin-rh Not sure what the deal is w/ these topics since they were moved to their own repo(s). @vikram-redhat ?

**Comment by vikram-redhat** [comment]
@ahardin-rh @adellape Hey. Yes, these were moved to their own repo. Sorry, eventually they should be deleted from here.

**Comment by ahardin-rh** [comment]
@adellape @vikram-redhat Thanks! Should I just close this out?

**Comment by ahardin-rh** [comment]
Closing per conversation with @vikram-redhat

**Pull request closed without merging**
