### PR TITLE
BZ#1881509 Machine health checks went GA in 4.4

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1881509

### CODE REVIEW

**Comment by codyhoag** [comment]
@JoelSpeed can you give final confirmation for this? Thanks!

**Comment by JoelSpeed** [comment]
/lgtm

Please make sure this is backported all the way to 4.4

**Comment by codyhoag** [comment]
Exception given from @vikram-redhat to merge before GA, once verification is received from team.

**Comment by ahardin-rh** [comment]
LGTM!

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
