### PR TITLE
removing reference to 3.9

### PR DESCRIPTION
**Pull request by kalexand-rh**
This note's only in 3.9.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, I see that the cherrypick bot failed me. I'll make manual PRs on Monday.

**Comment by vikram-redhat** [comment]
@kalexand-rh ok. That is a weird one.

**Comment by kalexand-rh** [comment]
@vikram-redhat, no, I was wrong. It didn't need to be cherry-picked. The incorrect reference was only in master.

**Pull request merged**
