### PR TITLE
Adding GCP XPN mark for installation support table

### PR DESCRIPTION
**Pull request by codyhoag**
Previews:
- https://deploy-preview-30885--osdocs.netlify.app/openshift-enterprise/latest/installing/installing-preparing.html#supported-installation-methods-for-different-platforms
- https://deploy-preview-30885--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html

### CODE REVIEW

**Comment by codyhoag** [comment]
@katherinedube can you confirm I got the wording right for this entry? I was trying to stay uniform with the wording from the related IPI row.

**Comment by katherinedube** [comment]
I believe that should be fine. Maybe worth getting a second opinion from @jstuever as he did the original implementation work (want to be sure we're using the same terminology as GCP.)

**Comment by codyhoag** [comment]
@jstuever can you confirm the wording?
@tsze-redhat can you confirm from a QE perspective?

Thanks!

**Comment by tsze-redhat** [comment]
Yes, we do support / test XPN install.

A suggestion on wording:
In the preview doc, we say "Existing cross-project virtual private networks".
In the xpn install page / index for the site, we say "Installing a cluster with shared VPC on user-provisioned infrastructure in GCP by using Deployment Manager templates".

Can we choose something more consistent between the two?
Like, instead of "Existing cross-project virtual private networks", we say "Shared VPC on Deployment Manager templates"

It is easier to cross reference (especially for inexperienced readers who need to rely solely on the doc).

Thanks.

**Comment by tsze-redhat** [comment]
LGTM
Thanks.

**Review by jeana-redhat — APPROVED** [review]
lgtm

**Pull request merged**
