### PR TITLE
Revoke "RHOSP" initialism treatment

### PR DESCRIPTION
**Pull request by maxwelldb**
4.2+

Context: 

* https://github.com/openshift/openshift-docs/pull/17304
* https://github.com/openshift/openshift-docs/pull/17323

From the OSP DPM today:

> We had a larger conversation around RHOSP this morning, with overwhelming support for "a RHOSP...".
> 
> I'll send a note to the writer team to ensure we are consistent when we write RHOSP. We do use the full name a lot...

@bergerhoffer Would you like to take this, since you're pretty familiar with the issue at this point? :)

### CODE REVIEW

**Comment by maxwelldb** [comment]
@bobfuru Actually, you have the background on this, too, if you want it.

**Review by bergerhoffer — COMMENTED** [review]
Sorry for the delay @maxwelldb! As much as I'd prefer "an", I'm fine with honoring the team's decision. Thanks, this LGTM!

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
