### PR TITLE
OSDOCS#6558: Fix the Errata link in the release notes

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OSDOCS-6558

Link to docs preview: https://61492--docspreview.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/cert-manager-operator-release-notes.html#cert-manager-operator-release-notes-1.11.1

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
@xingxingxia can you PTAL at this PR?

**Review by skrthomas — COMMENTED** [review]
LGTM, link checks out good

**Comment by bergerhoffer** [comment]
Per slack convo with @xenolinux, this is ready to merge. Merging!

**Pull request merged**
