### PR TITLE
Is this still correct, I don't see this variable on 4.4

### PR DESCRIPTION
**Pull request by mburke5678**
Removing LOGGING_FILE_PATH variable.
https://bugzilla.redhat.com/show_bug.cgi?id=1846620

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli PTAL

**Review by anpingli — COMMENTED** [review]
LGTM

**Comment by mburke5678** [comment]
Need to verify source BZ for this change and which versions to CP. See https://bugzilla.redhat.com/show_bug.cgi?id=1846620#c4

**Review by anpingli — COMMENTED** [review]
LGTM

**Comment by mburke5678** [comment]
Eric Rich approval in email
[EricRichApproval.pdf](https://github.com/openshift/openshift-docs/files/4892768/EricRichApproval.pdf)

**Comment by mburke5678** [comment]
@sichvoge PTAL

**Comment by mburke5678** [comment]
@sichvoge This PR removes the section on setting log location in 4.x docs. I need your approval to complete our change management process.

**Comment by sichvoge** [comment]
LGTM

**Review by anpingli — COMMENTED** [review]
LGTM

**Pull request merged**
