### PR TITLE
document .s2iignore support

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@knrc @eparis fyi

**Comment by bparees** [comment]
@jwforres fyi for the page name change.

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge

**Comment by vikram-redhat** [comment]
@gaurav-nelson - PTAL.

**Comment by bmcelvee** [comment]
LGTM. I'll follow up with a few minor edits in a separate PR. Thanks!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/builds/build_strategies.adoc#configuring-the-source-environment[Environment Variables]
|Added xref:../dev_guide/builds/build_strategies.adoc#ignoring-source-files[Ignoring Source Files] section.
%

**Pull request merged**
