### PR TITLE
OSDOCS#3994:Port performance and scalability content to the ROSA doc set

### PR DESCRIPTION
**Pull request by tmalove**
Version(s):
4.15+

Issue:
[OSDOCS-3994](https://issues.redhat.com/browse/OSDOCS-3994)

Link to docs preview: https://73423--ocpdocs-pr.netlify.app/openshift-rosa/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices
(Updated 3/19/2024)

QE review:
- [ ] QE has approved this change.

Additional information:
The original [PR](https://github.com/openshift/openshift-docs/pull/65079) was based on 4.13. The most efficient way to get these updates in a PR based on 'main' was to start a new PR and add the changes.

### CODE REVIEW

**Comment by tmalove** [comment]
@arendej @bchandra-ocp @karanthshashank  See the attached preview link for the Performance and scalability content. Note that the 'bare metal' references will be removed shortly.

**Comment by tmalove** [comment]
This PR replaces the [original](https://github.com/openshift/openshift-docs/pull/65079) one. Use this one for ongoing communication, Thanks.

**Comment by sunzhaohua2** [comment]
LGTM

**Pull request closed without merging**
