### PR TITLE
[OSDOCS-7023]: Updating references to hypershift CLI

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-7023

Link to docs preview: https://62838--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/using-node-tuning-operator#advanced-node-tuning-hosted-cluster_node-tuning-operator

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lahinson** [comment]
/assign @bryan-cox 

PTAL when you can. Thanks!

**Comment by jiezhao16** [comment]
lgtm

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
