### PR TITLE
GH58576: Remove Support section from OKD docs

### PR DESCRIPTION
**Pull request by mburke5678**
Please remove the "Support" section of the OKD Product Docs.
4.9+

Product docs issue: https://github.com/openshift/openshift-docs/issues/58576

Preview: https://file.rdu.redhat.com/mburke/okd-remove-support/support/index.html

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mburke5678** [comment]
OKD-no-support

**Review by travier — APPROVED** [review]

**Review by travier — CHANGES_REQUESTED** [review]
Well, while we don't offer paid support OKD, the tools mentioned in this section also apply to OKD. We probably want something more focused here.

**Comment by kalexand-rh** [comment]
Since this is for OKD and seems vital, we should merge this to 4.9 as well.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by mburke5678** [comment]
**NOTE TO SELF**: Watch for [this change](https://github.com/openshift/openshift-docs/pull/65850/files#diff-7c4392ac3894b8af0cb70e0770dfec2ace9c0e650d162d278172c7325e2d62c9) in pre-4.14.

**Comment by travier** [comment]
I have not done a full review of the omitted sections but this looks much more focused and thus much better.

**Pull request closed without merging**
