### PR TITLE
OSDOCS-2372 AWS permission updates

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2372

Preview: https://deploy-preview-36416--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 can you verify? Thanks!

**Comment by yunjiang29** [comment]
@codyhoag LGTM. Thanks.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
