### PR TITLE
document git_ssl_no_verify support

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal.  yes this is kind of a lousy recommendation to have to make, but the mechanisms for overriding the trusted CAs list are not something i feel comfortable documenting right now.  We do now have a card in our backlog to make it easier to provide your own trusted CAs that will be used during the clone.

**Comment by csrwng** [comment]
It would be good to include an example of how to set the var, like:
```
oc set env bc/mybuild GIT_SSL_NO_VERIFY=true
```

**Comment by bparees** [comment]
@csrwng updated.

**Comment by csrwng** [comment]
not exactly an example :) but I think it's enough to lead users in the right direction.
LGTM

**Comment by bparees** [comment]
> not exactly an example :) but I think it's enough to lead users in the right direction.

yeah that was an intentional choice.  I always prefer linking to the primary source doc for something over providing an example that will bit rot if the tool in question changes.  Also it teaches users to fish instead of giving them a fish.

@openshift/team-documentation ptal/merge

**Comment by csrwng** [comment]
@bparees you give users too much credit. In the end, all I want to know is how to do something and copy/paste if possible. What, you think I'd actually want to read the doc? That's so last century ;)

**Comment by bparees** [comment]
> @bparees you give users too much credit. In the end, all I want to know is how to do something and copy/paste if possible. What, you think I'd actually want to read the doc? That's so last century ;)

:(

**Comment by ahardin-rh** [comment]
@bparees Is this for 3.3?

**Comment by bparees** [comment]
@ahardin-rh yes. labels added.

**Comment by ahardin-rh** [comment]
Thanks!

**Pull request merged**
