### PR TITLE
Fix "create VM" workflow

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.14

Issue: None

Link to docs preview:
- [Using disk image to install Windows](https://63407--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-automating-windows-sysprep#virt-using-disk-image-install-windows_virt-automating-windows-sysprep)
- [Specializing Windows VM](https://63407--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-automating-windows-sysprep#virt-specializing-windows-sysprep_virt-automating-windows-sysprep)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@gouyang Could you have a look at this PR? A couple older procedures needed to be updated for the 4.14 UI.

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
