### PR TITLE
CNV-13360: Use RHEL image for liveness and readiness probes doc

### PR DESCRIPTION
**Pull request by sabrinajess**
Re: [CNV-13360](https://issues.redhat.com//browse/CNV-13360)
For 4.11 and later

Preview: https://deploy-preview-44502--osdocs.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-monitoring-vm-health.html#virt-template-vm-probe-config_virt-monitoring-vm-health

### CODE REVIEW

**Review by stu-gott — COMMENTED** [review]
LGTM

**Comment by dshchedr** [comment]
I see several issues with provided example 
```
# oc create -f vm.yml
The request is invalid: 
* spec.template.spec.readinessProbe.httpGet: spec.template.spec.readinessProbe.httpGet is only allowed if the Pod Network is attached
* spec.running: One of Running or RunStrategy must be specified
```

Added more comments in Jira

**Review by stu-gott — COMMENTED** [review]
LGTM

**Comment by sabrinajess** [comment]
Effort on this story is larger than originally expected. Low ROI for minor issue. Opted to close as Will Not Fix.

**Pull request closed without merging**
