### PR TITLE
Added 'OpenShift Data Foundation' to install MCG procedure

### PR DESCRIPTION
**Pull request by HagayVider1**
@kaovilai 

GH# : 
OCPBUGS : [OADP-931](https://issues.redhat.com//browse/OADP-931)

Added "OpenShift Data Foundation" to MCG installation procedure
https://docs.openshift.com/container-platform/4.11/backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.html

This is intended to merge and eliminate a separate installation procedure for OCS
https://docs.openshift.com/container-platform/4.11/backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.html

Version: OADP 1.2.0
Issue: https://issues.redhat.com/browse/OADP-931

Version(s):

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14

Issue: [OADP-931](https://issues.redhat.com//browse/OADP-931)

Link to docs preview:

QE review:
- [X] QE has approved this change.

Approved by Shahaf Bahar

Additional information:

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by sbahar619** [comment]
lgtm.

**Review by snarayan-redhat — COMMENTED** [review]
lgtm

**Review by jeana-redhat — COMMENTED** [review]
This looks structurally fine for merge, but happened to notice a small style guide issue. Please revise and put this back in the merge queue when complete.

**Comment by kalexand-rh** [comment]
4.11 is now [EOL](https://access.redhat.com/support/policy/updates/openshift), and we are no longer updating it. Please set the versions to 4.12+.

**Comment by anarnold97** [comment]
@HagayVider1 - you can close this PR, it has been covered in another ticket, please

**Pull request closed without merging**
