### PR TITLE
BZ#1976798: Includes InventoryService.Tagging.ObjectAttachable privilege required to install OCP on vSphere 7

### PR DESCRIPTION
**Pull request by vagnerfarias**
Version(s): 4.7+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=1976798

Link to docs preview: Not Available

### CODE REVIEW

**Comment by johnsimcall** [comment]
The extra permission should also be added to the `vSphere vCenter Datacenter` section. I believe it's around line 129...

**Comment by vagnerfarias** [comment]
> The extra permission should also be added to the `vSphere vCenter Datacenter` section. I believe it's around line 129...

Indeed. Permission added.

**Comment by jinyunma** [comment]
LGTM

**Comment by GroceryBoyJr** [comment]
Preview available at http://file.rdu.redhat.com/jbrigman/ocp-on-vsphere/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

**Comment by kalexand-rh** [comment]
LGTM

**Pull request merged**
