### PR TITLE
Docker builds are not supported in ARO

### PR DESCRIPTION
**Pull request by thekad**
This warning should be displayed on ARO as well.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@thekad, please set this PR against the `master-3` branch.

**Comment by kalexand-rh** [comment]
Please rebase against `master-3`.

**Comment by thekad** [comment]
@kalexand-rh yep, should've done it from my clone instead of trusting GH's UI, should be OK now down to a single commit.

**Comment by kwoodson** [comment]
This looks good to me.  I do not see another reference to the openshift-aro product/project but syntactically looks correct.

**Comment by kalexand-rh** [comment]
Thank you both! I double-checked, and in the 3.x stream, `openshift-aro` is correct.

**Pull request merged**
