### PR TITLE
BZ2016590: Adding explicit ref IPI to dual-stack bare metal note

### PR DESCRIPTION
**Pull request by skrthomas**
https://bugzilla.redhat.com/show_bug.cgi?id=2016590

for 4.8+

preview: https://deploy-preview-38436--osdocs.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/converting-to-dual-stack.html

Ready for QA @zhaozhanqi

### CODE REVIEW

**Comment by mburke5678** [comment]
@skrthomas LGTM

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
