### PR TITLE
BZ2093076: Adds MetalLB in feature summary table

### PR DESCRIPTION
**Pull request by xenolinux**
Adds MetalLB in feature summary table

Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2093076

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/MetalLB-feature-summary-table/welcome/oke_about.html#feature-summary

Additional information:

QE: @asood-rh

### CODE REVIEW

**Review by asood-rh — APPROVED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
Looks great!

**Pull request merged**
