### PR TITLE
Fluentd label not being set on nodes during scaleup

### PR DESCRIPTION
**Pull request by bysnupy**
Correct closed BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1609089

This BZ was closed with changes, but the changes have been updated in wrong section.
So I correct this.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@bmcelvee, will you PTAL? I'm not sure why this one didn't get a build.

**Comment by bysnupy** [comment]
It seems influence of the crash on `github` recently. I had better to create the `PR` again after close this ?

**Comment by kalexand-rh** [comment]
@bysnupy, will you rebase and force push? That should trigger a new build.

@bmcelvee, will you PTAL at the change?

**Comment by bysnupy** [comment]
@kalexand-rh I'm done. Thank you for your great guide ! :^)

**Comment by bmcelvee** [comment]
LGTM :star2:

**Comment by kalexand-rh** [comment]
merging, then!

**Pull request merged**
