### PR TITLE
CNF-1483_updates: updates to merged PR 30717

### PR DESCRIPTION
**Pull request by kquinn1204**
Updates to the netqueues feature after content was merged. 
Original PR was https://github.com/openshift/openshift-docs/pull/30717

Preview: https://deploy-preview-33369--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes?utm_source=github&utm_campaign=bot_dp#reducing-nic-queues-using-the-performance-addon-operator_cnf-master

### CODE REVIEW

**Comment by yanirq** [comment]
looks good. 
I wonder if we should emphasis more the supported device section where : "Network devices that support multiple queues (channels)" ,  this might be vague for some users. A way to check can be manually on the node per device, but maybe its too specific.  @MarSik   any thoughts ?

**Comment by kquinn1204** [comment]
> looks good.
> I wonder if we should emphasis more the supported device section where : "Network devices that support multiple queues (channels)" , this might be vague for some users. A way to check can be manually on the node per device, but maybe its too specific. @MarSik any thoughts ?

**Comment by kquinn1204** [comment]
> > looks good.
> > I wonder if we should emphasis more the supported device section where : "Network devices that support multiple queues (channels)" , this might be vague for some users. A way to check can be manually on the node per device, but maybe its too specific. @MarSik any thoughts ?

I am not a great fan of vagueness or lack of clarity in docs. 
@MarSik - 
Is it too much to put in details on checking whether your NIC and the driver support multiqueue

something like this 

Check the NIC and the device driver loaded on your system provides multiqueue support using ethtool. For example, check eth0 as follows: 

$ sudo ethtool -l eth0

The output below indicates interface eth0 provides multiqueue support. 
. Example output 
Channel parameters for eth0:
Pre-set maximums:
RX:   0
TX:   0
Other:    0
Combined: 8
Current hardware settings:
RX:   0
TX:   0
Other:    0
Combined: 4

The following error is seen if the NIC does not provide multiqueue support: 


$ sudo ethtool -l eth0

.Example output 
Channel parameters for eth0:
Cannot get device channel parameters
: Operation not supported

**Pull request merged**
