### PR TITLE
use 1.0 example as default for send logs to an external log aggregator

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1700225

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli I moved the 1.0 version in the procedure and moved the 0.12 version to the end. Please let me know if this is what you expected.

**Comment by mburke5678** [comment]
From @anpingli in BZ:
_The template use for configmap fluentd is service side. I will provide you some template later._

Anping -- I cannot install Cluster Logging at this time due to CI changes. The team is working on this. In the meantime, any help you can provide is greatly appreciated. We are looking to close all PRs by the end of this week.

**Comment by anpingli** [comment]
https://docs.fluentd.org/output/forward.  
    <store>
      @type forward
      <server>
        host  $fluent_server
        port $fluentd_port
      </server>
    </store>

**Comment by anpingli** [comment]
No, the customer must setup the external fluentd server by themselves.  the configuration file may be vary, depend on what fluentd server they are using.

**Review by anpingli — COMMENTED** [review]
LGTM.

**Pull request merged**
