### PR TITLE
MIG-1611: Release notes for MTC-1.7.17

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [MIG-1611](https://issues.redhat.com/browse/MIG-1611)

### Link to docs preview:

* [MTC release notes 1.7.17](https://81322--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/release_notes/mtc-release-notes-1-7.html)

### QE review:
- [X ] [QE has approved this change](https://github.com/openshift/openshift-docs/pull/81322#pullrequestreview-2322295074)

Additional information:

### CODE REVIEW

**Review by midays — APPROVED** [review]
LGTM

**Review by skopacz1 — APPROVED** [review]
LGTM. In the PR description, can you please specify which versions of OCP this should be cherry picked to?

**Comment by anarnold97** [comment]
[Moved to REL_PREP](https://redhat-internal.slack.com/archives/CFN0XJEPR/p1727320222318639)

**Comment by skopacz1** [comment]
Clarified via slack DM that this is for 4.12+

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
