### PR TITLE
Update common-attributes.adoc to resolve formatting issues

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [OADP-5081](https://issues.redhat.com/browse/OADP-5081)

### Version(s):

* OCP 4.17
* OCP 4.18

### Link to docs preview:

* Issue shown - https://83509--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud
* Issue resolved - https://83858--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@anarnold97, do you know which versions this applies to?

**Comment by anarnold97** [comment]
@kalexand-rh - i have only seen it in main

**Comment by anarnold97** [comment]
@kalexand-rh but will check earlier versions when i come out of this meeting

**Comment by anarnold97** [comment]
@kalexand-rh - thanks very much

**Comment by anarnold97** [comment]
4.13 looks ok but could do with a tidy-up

**Comment by kalexand-rh** [comment]
@anarnold97, when you figure out how far back this one should go, update comment 0, and I'll get it on the right branches.

**Comment by anarnold97** [comment]
@kalexand-rh - thanks just working through the releases and doing a tidy-up

4.12 - https://github.com/openshift/openshift-docs/pull/83873
4.13 - https://github.com/openshift/openshift-docs/pull/83872

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Comment by skrthomas** [comment]
cherry-pickin's are SLO too slow to catch the W this morning 😅

**Pull request merged**
