### PR TITLE
GH#40104 Hide AWS-specific configs for installer proxy information

### LINKED ISSUE #40104: [enterprise-4.9] Issue in file installing/installing_azure/installing-azure-customizations.adoc
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/installing/installing_azure/installing-azure-customizations.html#installing-azure-customizations, specifically, this section:
Configuring the cluster-wide proxy during installation

### What needs fixing?
There are details about AWS but the section is specifically about Azure. This text should be reworked with Azure as a context instead or removed: 

If your cluster is on AWS, you added the ec2.<region>.amazonaws.com, elasticloadbalancing.<region>.amazonaws.com, and s3.<region>.amazonaws.com endpoints to your VPC endpoint. These endpoints are required to complete requests from the nodes to the AWS EC2 API. Because the proxy works on the container level, not the node level, you must route these requests to the AWS EC2 API through the AWS private network. Adding the public IP address of the EC2 API to your allowlist in your proxy server is not sufficient.

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #40104

Previews:
- [AWS China](https://deploy-preview-40236--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-china.html#installation-configure-proxy_installing-aws-china-region)
- [Non-AWS China](https://deploy-preview-40236--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-configure-proxy_installing-aws-customizations)
- [Azure](https://deploy-preview-40236--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-configure-proxy_installing-azure-customizations)

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 can you verify? Thanks!

**Comment by yunjiang29** [comment]
@codyhoag LGTM.

**Comment by bobfuru** [comment]
LGTM

**Pull request merged**
