### PR TITLE
[enterprise-4.2] Imagestream tags

### PR DESCRIPTION
**Pull request by ahardin-rh**
Cherry-pick of https://github.com/openshift/openshift-docs/pull/22308

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@apinnick Can you please cross-check this cherry-pick PR? There were a lot of conflicts and I just want to ensure it's all resolved properly before we merge. Thanks!

**Comment by apinnick** [comment]
> @apinnick Can you please cross-check this cherry-pick PR? There were a lot of conflicts and I just want to ensure it's all resolved properly before we merge. Thanks!

@ahardin-rh  What conflicts?

**Comment by ahardin-rh** [comment]
@apinnick I had to manually cherry-pick for 4.2 and 4.3 because conflicts within the files caused the bot to fail. I manually resolved the conflicts and I think this PR reflects what should be cherry-picked in for 4.2, but please check the files to confirm that it looks correct. Thanks!

**Comment by apinnick** [comment]
> @apinnick I had to manually cherry-pick for 4.2 and 4.3 because conflicts within the files caused the bot to fail. I manually resolved the conflicts and I think this PR reflects what should be cherry-picked in for 4.2, but please check the files to confirm that it looks correct. Thanks!

@ahardin-rh I do see a problem. Please don't merge this to 4.2. I see now that none of these changes should be applied. You can close this PR. Thanks!

**Pull request closed without merging**
