### PR TITLE
OBSDOCS-561: Clean up logging release notes and remove duplicate files

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
- 4.11+

Issue:
https://issues.redhat.com/browse/OBSDOCS-561

Link to docs preview:
- https://65622--docspreview.netlify.app/openshift-enterprise/latest/logging/logging_release_notes/logging-5-7-release-notes
- https://65622--docspreview.netlify.app/openshift-enterprise/latest/logging/logging_release_notes/logging-5-6-release-notes
- https://65622--docspreview.netlify.app/openshift-enterprise/latest/logging/logging_release_notes/logging-5-5-release-notes
- https://65622--docspreview.netlify.app/openshift-enterprise/latest/logging/logging_release_notes/logging-5-4-release-notes

QE review:
- No QE required.

Additional information:
- Remove release notes older than 5.4.0, since versions earlier than this were not supported on 4.11+
- Remove duplicate files after doing a `git diff`
- Split release notes main section by version
- Remove per version release note sections in favor of adding versions to one main section
- Cleaned up assembly / module structure of 5.4* release notes

### CODE REVIEW

**Comment by kalexand-rh** [comment]
I think this doesn't need QE or CM. Do check to see if you need a redirect. And if you can explain the scope of changes to the peer reviewers it might be kind - if you're truly removing duplicates, this might need a skim instead of a deep review.

**Review by jeana-redhat — APPROVED** [review]
Fantastic reorganization, LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
