### PR TITLE
add use cases for oc rsync

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@sallyom @danmcp ptal.

**Comment by danmcp** [comment]
@bparees No objection to this.  I was hoping for a nice example though :)

**Comment by bparees** [comment]
ok i'll leave that as a follow up for @sallyom if she wants to turn her sample into doc in here.

@openshift/team-documentation ptal/merge.

**Comment by sallyom** [comment]
@bparees will do, thanks

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by bparees** [comment]
@openshift/team-documentation rebased.

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
[rev_history]
|link:../dev_guide/copy_files_to_container.html[Copying Files to or from a Container]
|Added use cases for the `oc rsync` command to the Overview.
%

**Pull request merged**
