### PR TITLE
OCPBUGS-22335: remove old clevis note

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OCPBUGS-22335

Link to docs preview: https://66908--docspreview.netlify.app/openshift-enterprise/latest/installing/install_config/installing-customizing#installation-special-config-storage-procedure_installing-customizing (removal just before optional offline provisioning step)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mike-nguyen** [comment]
LGTM

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
