### PR TITLE
OSSM-4843: Update conditional tagging

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.10+

Issue:  https://issues.redhat.com/browse/OSSM-4843

Link to docs preview:

Preview of OCP docs that do not contain the conditionalized doc: https://docs.openshift.com/container-platform/4.13/service_mesh/v2x/ossm-create-smcp.html#ossm-about-smcp_ossm-create-smcp

Preview of ROSA docs containing the conditional text: https://docs.openshift.com/rosa/service_mesh/v2x/ossm-create-smcp.html#ossm-about-smcp_ossm-create-smcp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by luksa — APPROVED** [review]
LGTM

**Review by fjglira — APPROVED** [review]
LGTM

**Review by kowen-rh — APPROVED** [review]
LGTM! Nice change. :slightly_smiling_face:

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
