### PR TITLE
[OCPBUGS23916] Add HAproxy note to multiarchitecture compute procedure IBM Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OCPBUGS-23916

Link to docs preview: https://68464--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-ibm-z-kvm

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by holgwolf** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by jldohmann — APPROVED** [review]
nice work Silke, LGTM 😄

**Pull request merged**
