### PR TITLE
OSDOCS-8374 Migrate "Getting Started with Rosa - Deploy the Cluster (Simple UI)"

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-8374](https://issues.redhat.com//browse/OSDOCS-8374) Migrate "Getting Started with Rosa - Deploy the Cluster (Simple UI)" from the rosaworkshop.io content.

Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8374

Link to docs preview:
https://68155--docspreview.netlify.app/openshift-rosa/latest/cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deploying/cloud-experts-getting-started-simple-ui-guide

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can I please get a review of the following PR? Thanks!

**Comment by jneczypor** [comment]
Hi @jmekkatt - I updated the image based on the feedback you gave me for the "Detailed UI" tutorial. Can you please take a quick look at this one and confirm that it is correct? Thanks!

**Comment by mletalie** [comment]
Good job, @jneczypor! Added one comment, otherwise LGTM!

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/lgtm

**Pull request merged**
