### PR TITLE
OCPBUGS#13146: Update the Helm project file

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-13146

Link to docs preview: https://59979--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-tutorial.html#osdk-project-file_osdk-helm-tutorial

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by sheriff-rh — APPROVED** [review]
lgtm, merging.

**Pull request merged**
