### PR TITLE
Correct uninstall commands

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
cc: @aweiteka

**Review by aweiteka — APPROVED** [review]
Thanks, @thomasmckay !

**Comment by ahardin-rh** [comment]
@thomasmckay @aweiteka This is an oldie :ghost:  , but this looks like it's still valid. Merging.

**Comment by ahardin-rh** [comment]
This is for atomic docs: http://docs.projectatomic.io/registry/latest/registry_quickstart/administrators/uninstall.html

No revision history needed

**Pull request merged**
