### PR TITLE
To remove TP from IBM PowerVS in 4.15 Release Notes

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.15+

Requires CM

Issue: https://issues.redhat.com/browse/MULTIARCH-4115

Link to docs preview:
https://74135--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes.html

QE review:
- [x] QE has approved this change.

- [x] CM ack

Additional information:

### CODE REVIEW

**Comment by manojnkumar** [comment]
LGTM

**Review by opayne1 — COMMENTED** [review]
lgtm pending QE and the CM acks.

**Comment by alishaIBM** [comment]
> lgtm pending QE and the CM acks.

We have the QE approval for this change.

**Comment by alishaIBM** [comment]
PTAL: @sferich888, @davemulford, @xltian, @kalexand-rh, @sjstout

**Comment by davemulford** [comment]
LGTM

**Comment by alishaIBM** [comment]
@sjstout approved changes over slack

**Pull request merged**
