### PR TITLE
BZ-1722807: Adding note to wait a few minutes after recovering

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1722807

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sttts Can you take a look at see if this wording/location looks okay to you? Thanks!

Preview: https://bz-1722807--ocpdocs.netlify.com/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html#dr-scenario-1-recover-master-hosts_dr-infrastructure-recovery

**Comment by bobfuru** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review as well? Thanks!

**Comment by geliu2016** [comment]
LGTM, thanks

**Comment by bergerhoffer** [comment]
Thanks! Merging.

**Pull request merged**
