### PR TITLE
Follow-up edits for BZ1557274 and BZ1558430

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up edits for:
https://bugzilla.redhat.com/show_bug.cgi?id=1558430
https://bugzilla.redhat.com/show_bug.cgi?id=1557274

@sdodson Please review for accuracy and ensure that I adequately addressed QE's comments. Thanks!

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
looks good to me

**Comment by sdodson** [comment]
I believe QE's concerns are https://github.com/openshift/openshift-docs/blame/master/upgrading/automated_upgrades.adoc#L32-L54

The bulleted list is redundant with the paragraphs that follow. I think we should either remove the bulleted list or update the bulletted list as follows and remove the new paragraphs.
```
The automated 3.7 to 3.9 Control Plane upgrade performs the following steps for you:

* A backup of all etcd data is taken for recovery purposes
* Updates API and Controllers from 3.7 to 3.8
* Internal data structures are updated to 3.8
* A second backup of all etcd data is taken for recovery purposes
* Updates API and Controllers from 3.8 to 3.9
* Internal data structures are updated to 3.9
* Updates the default router from 3.7 to 3.9 if one exists
* Updates the default registry from 3.7 to 3.9 if one exists
* Updates default image streams and InstantApp templates

The automated 3.7 to 3.9 Node upgrade performs a rolling update of nodes :
* Marks a subset of nodes unschedulable and drains them of pods
* Updates node components from 3.7 to 3.9 (including openvswitch & container runtime)
* Returns those nodes to service

```

**Comment by ahardin-rh** [comment]
@sdodson Thanks! This is updated.

**Pull request merged**
