### PR TITLE
 remove atomic-registry docs

### PR DESCRIPTION
**Pull request by kalexand-rh**
Continuing https://github.com/openshift/openshift-docs/pull/9136

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@aweiteka, will you PTAL at the commit I added and confirm that it's ok to remove these files?

**Review by aweiteka — APPROVED** [review]
Thanks for catching these files.

**Comment by kalexand-rh** [comment]
Absolutely! Thanks for pulling them out for us.

**Comment by kalexand-rh** [comment]
@aweiteka, which version branches do you want this applied to?

**Comment by aweiteka** [comment]
> which version branches do you want this applied to?

@kalexand-rh  Since this is just pruning work I think it's fine just to apply this to current version / master. There's no impact or benefit to previous version, IMO.

**Pull request merged**
