### PR TITLE
BZ#1645577 - Egress IPs do not work with joined projects

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1645577

Preview: [Egress IP address assignment for project egress traffic](https://bz-1764587--ocpdocs.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/assigning-egress-ips.html#nw-egress-ips-about_egress-ips)

### CODE REVIEW

**Comment by jboxman** [comment]
@danwinship, is this update correct or did I misinterpret? Thanks!

**Comment by jboxman** [comment]
@danwinship, ping. Thanks!

**Comment by danwinship** [comment]
yes, that's correct

**Pull request merged**
