### PR TITLE
Bug 1347820, added support details in Selecting Fields

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1347820

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tpoitras @tnguyen-rh please peer review

**Comment by ahardin-rh** [comment]
@pweil- PTAL :bow:

**Comment by pweil-** [comment]
:+1:   

@pmorie - should we include this for all the other fields as well to say which are supported in env vars or volumes (or both)?

**Comment by tpoitras** [comment]
I had the same question  as @pweil- after reading the BZ

**Comment by ahardin-rh** [comment]
@pweil- @pmorie @tpoitras I made some additions per your comments. PTAL. Thanks!

**Comment by ahardin-rh** [comment]
Merged per QE

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/downward_api.adoc#dev-guide-downward-api[Downward API]
|Added support details in the Selecting Fields section.
%

**Pull request merged**
