### PR TITLE
Beautify Asciidoctor CSS

### PR DESCRIPTION
**Pull request by jboxman**
Leave the world a better place than when you found it.

### CODE REVIEW

**Comment by jboxman** [comment]
@openshift/team-documentation - this just beautifies the CSS. Should have no impact on styles at all.

Preview: http://file.bos.redhat.com/jboxman/pretty-css/welcome/

cc @vikram-redhat

**Comment by ahardin-rh** [comment]
Looks beautiful to me :sunflower:  :sun_with_face: :rainbow: :butterfly:

**Comment by jboxman** [comment]
@vikram-redhat, what additional testing might we want for this? Typically CSS re-formatters are safe, but I wouldn't want to merge anything that blew up our pages.

This change will make it easier to introduce additional style changes, such as adjusting the style for `monospace`.

**Comment by vikram-redhat** [comment]
@jboxman what are the changes that it introduces from a style perspective? It is hard to know looking at the diff. 

@maxwelldb would love to have your feedback on this as well.

**Comment by maxwelldb** [comment]
@vikram-redhat If it's just beautification, it shouldn't change anything on the glass. 

Problems that pre-exist this change:

- Not a valid CSS property: https://github.com/openshift/openshift-docs/blob/b1cd4cc8c9583fd5eadf6ec77c9a685b6e111f88/_stylesheets/docs.css#L1300 

- Not a valid background-color value: https://github.com/openshift/openshift-docs/blob/b1cd4cc8c9583fd5eadf6ec77c9a685b6e111f88/_stylesheets/docs.css#L246 (might want `transparent`)

**Comment by jboxman** [comment]
@vikram-redhat, no changes; I ran it through a _beautifier_ so it's coherent.

**Comment by jboxman** [comment]
@vikram-redhat, what do you think? Thanks.

**Comment by vikram-redhat** [comment]
merge away

**Pull request merged**
