### PR TITLE
OSDOCS-1043: Adding unsupported logging configurations

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1043

Preview: http://file.rdu.redhat.com/~ahoffer/2020/OSDOCS-1043-logging/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-logging (internal)

### CODE REVIEW

**Comment by bergerhoffer** [comment]
This PR can't be merged until #20269 is.

**Comment by bergerhoffer** [comment]
@mburke5678 Can you give this a review since it links to your new logging section in #20269.

Are you planning on having that PR get in for 4.5, or not necessarily? Thanks!

**Comment by mburke5678** [comment]
@bergerhoffer I would like to get that PR in for 4.5. Vikram asked me to work directly with him when it was time to merge as there are significant redirects. 
I should get the new 4.5 features documented first before merging.

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Comment by bergerhoffer** [comment]
Hi @anpingli, can you please take a look at these updates? It depends on (and links to) #20269, which you are reviewing. But I want to make sure that this PR is ready to be merged once that PR is merged. 

This PR is for updating migration planning content (from 3.11 to 4.5) to let users know of important differences in the versions when migrating. Let me know if you have any questions, thanks!

Preview: http://file.rdu.redhat.com/~ahoffer/2020/OSDOCS-1043-logging/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-logging (internal)

**Comment by vikram-redhat** [comment]
@anpingli BUMP

New cluster logging update PR: https://github.com/openshift/openshift-docs/pull/23502

**Comment by anpingli** [comment]
@bergerhoffer  I don't see any sections about how to migrate Logging from 3.11 to 4.5.   Does that mean we don't support logging migration from 3 to 4?  If yes, we should mention that here.

**Comment by XinRedhat** [comment]
No, we don't have.

**Comment by vikram-redhat** [comment]
@bergerhoffer I am merging this as @mburke5678's PR https://github.com/openshift/openshift-docs/pull/23502 has merged. 

As for @anpingli 's comment about mentioning no support for 3 to 4 migration, that can come post GA.

**Pull request merged**
