### PR TITLE
change release-01 to stable per lbragstad

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s):

Issue:

Urgent need to change channel to "stable" so customer will get the correct installation. 

Link to docs preview:

https://61939--docspreview.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation

QE review:
- [ ] QE has approved this change.

NO QE needed, 

Additional information:

This is an error correction request made by SME @rhmdnd

### CODE REVIEW

**Review by rhmdnd — APPROVED** [review]
/lgtm

Thanks!

**Review by sheriff-rh — APPROVED** [review]
lgtm, merging.

**Pull request merged**
