### PR TITLE
Bug 1546254- Add required path for openshift-ansible installer to succeed.

### PR DESCRIPTION
**Pull request by fabianvf**
https://bugzilla.redhat.com/show_bug.cgi?id=1546254

### CODE REVIEW

**Comment by fabianvf** [comment]
ping @sdodson , any idea who should review this?

**Comment by sdodson** [comment]
Yes we need it.

**Comment by ahardin-rh** [comment]
I'm now assigned to https://bugzilla.redhat.com/show_bug.cgi?id=1546247. Overall, this PR looks good to me. I can make some minor style edits in a follow-up PR.

I labeled this for 3.6+ is that correct? Requesting QE review before we merge. Thanks!

**Comment by sdodson** [comment]
Yes, it's relevant for pretty much any version of openshift.

**Comment by ahardin-rh** [comment]
QE verfied in the BZ

**Pull request merged**
