### PR TITLE
Update `_distro_map.yml` to publish Builds 1.1

### PR DESCRIPTION
**Pull request by nebelsprachen**
Version(s):

Publish v1.1

Issue:

This is to publish the docs for Builds 1.1

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mburke5678** [comment]
@buildbricks Can you help by generating a preview?

**Comment by mburke5678** [comment]
@buildbricks Can you help by generating a preview?

**Comment by adellape** [comment]
Bumping in Slack to request generating/uploading a manual preview.

**Pull request closed without merging**
