### PR TITLE
OSDOCS#12284: HCP: Update OADP backup, restore, and disaster recovery

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.16+

Issue: https://issues.redhat.com/browse/OSDOCS-12284

Link to docs preview:

- [Backing up the control plane workload](https://83238--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-oadp.html#hcp-dr-oadp-backup-cp-workload_hcp-disaster-recovery-oadp)
- [Restoring a hosted cluster by using OADP](https://83238--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-oadp.html#hcp-dr-oadp-restore_hcp-disaster-recovery-oadp)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Pull request merged**
