### PR TITLE
[OSDOCS-8985]: Allow exception for organizational constraint

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8985
Link to docs preview:

https://71897--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs#ccs-gcp-requirements-support_gcp-ccs
QE review:
- [x] QE has approved this change.

SRE and QE reviewed and approved. 
Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
SRE LGTM https://redhat-internal.slack.com/archives/C06ENQCNEMN/p1708526120789069?thread_ts=1708440519.706249&cid=C06ENQCNEMN

**Comment by mletalie** [comment]
SRE LGTM

**Comment by mletalie** [comment]
Hello @lento-sun, can you please provide QE Review for this PR? Thanks!

**Comment by aldiazRH** [comment]
LGTM!

**Pull request merged**
