### PR TITLE
BZ2053605: Add instructions on how to scale up AWS nodes

### PR DESCRIPTION
**Pull request by xenolinux**
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2053605)
[Preview](https://deploy-preview-44431--osdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-scaling-up.html)
OCP version: 4.6+
QE contact @sunilcio

### CODE REVIEW

**Comment by sunilcio** [comment]
@gpei hi, could you help check if your team can review this?

**Comment by gpei** [comment]
@sunilcio hi, this should be scaling up via machineset, @sunzhaohua2 could you help to check this?

**Comment by sunzhaohua2** [comment]
This is about master instancetype change, we didn't test this before, I can have a try tomorrow and let etcd team help to check, I feel this is not supported.

**Comment by sunzhaohua2** [comment]
@xenolinux I added a comment in https://bugzilla.redhat.com/show_bug.cgi?id=2053605#c7, tested with worker machine and master machine, this couldn't change instance type.

**Comment by sunzhaohua2** [comment]
@xenolinux sorry for the late reply. Yes, I think this is not supported, at least only this change in the doc is unsupported. We will support this feature in 4.12, this is epic https://issues.redhat.com/browse/OCPCLOUD-1372, this is enhancements doc pr https://github.com/openshift/enhancements/pull/1008

**Comment by xenolinux** [comment]
https://github.com/openshift/openshift-docs/pull/44431#issuecomment-1107698557 closing this PR since this change is unsupported in the docs.

**Pull request closed without merging**
