### PR TITLE
Followup to #1729: Gluster storage

### PR DESCRIPTION
**Pull request by bfallonf**
Followup edits to #1729 . Similar to #1944 

@adellape you managed the merging of all these PRs, can you make sure merging this and #1944 are not relying on any other PRs? This is up for review as well.

### CODE REVIEW

**Comment by adellape** [comment]
@bfallonf I should be able to get to these ones tmw to review, in the meantime you could rebase/re-push to pick up the Travis fix for any PRs you got outstanding atm.

**Comment by bfallonf** [comment]
@adellape Works for me. Thanks.

**Comment by adellape** [comment]
@bfallonf :fireworks: This LGTM, thank you.

@jeffvance Can you take a look since you worked on https://github.com/openshift/openshift-docs/pull/1729, which this PR is following up on?

**Comment by jeffvance** [comment]
LGTM

**Comment by adellape** [comment]
[rev_history]
.2+|link:../install_config/persistent_storage/persistent_storage_ceph_rbd.html[Configuring Persistent Storage -> Persistent Storage Using Ceph Rados Block Device (RBD)]
|Updated for clarity throughout.
|Enhanced the link:../install_config/persistent_storage/persistent_storage_glusterfs.html#gluster-volume-security[Volume Security] section significantly.
%

**Pull request merged**
