### PR TITLE
OCPBUGS-37477: fixes typo in code

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OCPBUGS-37477

Link to docs preview:
https://79506--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#nw-ovn-kubernetes-migration_migrate-from-openshift-sdn

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by djslavens — APPROVED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
