### PR TITLE
OCPBUGS#7781: Replace the wrong annotation with the correct one

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-7781

Link to docs preview: https://56188--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/configuring-hardware-offloading.html#create-network-attachment-definition_configuring-hardware-offloading

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Review by kelbrown20 — COMMENTED** [review]
LGTM as well

**Pull request merged**
