### PR TITLE
OCPBUGS-10994

### PR DESCRIPTION
**Pull request by smunje1**
[OCPBUGS-10994](https://issues.redhat.com/browse/OCPBUGS-10994): [rosa-] Issue in file rosa_architecture/rosa-sts-about-iam-resources.adoc

Aligned team: Service Delivery
OCP version for cherry-picking: enterprise-4.14+
JIRA issues: [OCPBUGS-10994](https://issues.redhat.com/browse/OCPBUGS-10994)
Preview pages: [Click to see the build preview in your browser for ROSA](https://68462--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources#rosa-sts-account-wide-roles-and-policies_rosa-sts-about-iam-resources)
SME review **completed**: @thomasphall
QE review **completed**: @yuwang-RH
Peer review **completed**: @dfitzmau

### CODE REVIEW

**Review by thomasphall — APPROVED** [review]
LGTM

**Comment by dfitzmau** [comment]
Hi @smunje1 . To avoid the repetitive update for each new release, would using a user-replaced value be better?

`--tags Key=rosa_openshift_version,Value=<opernshift_version> Key=rosa...`

THe Jira targets 4.14+ but really `4.14` is only relevant here. What about 4.13, and earlier releases?

**Comment by dfitzmau** [comment]
Consider appending the following clause to `The following command starts that process:`

> , where `<openshift_version>` refers to your version of the OpenShift Container Platform, such as `4.14`.

**Comment by smunje1** [comment]
I agree with @dfitzmau above [comment 1](https://github.com/openshift/openshift-docs/pull/68462#issuecomment-1833652267) and [comment 2](https://github.com/openshift/openshift-docs/pull/68462#issuecomment-1833654339) and planning to make the updates accordingly. 

@thomasphall @yuwang-RH Could you please let me know if you have other thoughts? Thank you!

**Comment by smunje1** [comment]
Hello @dfitzmau. I have incorporated your suggestions. Could you please take a look? Thank you!

Cc @thomasphall @yuwang-RH

**Comment by dfitzmau** [comment]
Hi @smunje1 . LGTM!

**Comment by abhatt-rh** [comment]
@dfitzmau and @smunje1 I see that peer review is marked in progress. Kindly confirm if it can be marked done.

**Review by jeana-redhat — COMMENTED** [review]
Just one thing about the use of product titles in here to address, please re-tag for merge when done.

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
