### PR TITLE
OSDOCS#8266: Fixing ami command in multi-arch AWS machine set example

### PR DESCRIPTION
**Pull request by kelbrown20**
**Version(s):** 4.13+
**Issue:** [OSDOCS-8266](https://issues.redhat.com//browse/OSDOCS-8266)

**Link to docs preview:**

[Creating a cluster with multi-architecture compute machines on AWS -> Adding an ARM64 compute machine set to your cluster](https://67667--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-aws#multi-architecture-modify-machine-set-aws_creating-multi-arch-compute-nodes-aws)

**QE review:**
- [x] QE has approved this change.

### CODE REVIEW

**Comment by kelbrown20** [comment]
@aleskandro Hey Alessandro! Could you PTAL at this PR when you get the chance, thank you!

**Comment by aleskandro** [comment]
Hi @kelbrown20 Thanks!

/label qe-approved

**Comment by kcarmichael08** [comment]
LGTM!

**Pull request merged**
