### PR TITLE
Bug 1554244 Addition example for throttling logs

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1554244

### CODE REVIEW

**Review by richm — APPROVED** [review]
/lgtm

**Comment by bmcelvee** [comment]
Thanks, @richm!

**Comment by bmcelvee** [comment]
@anpingli PTAL

**Comment by vikram-redhat** [comment]
@anpingli  PTAL

cc: @xltian

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL :fallen_leaf:

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
