### PR TITLE
Trello-664 Add HOSA variable

### PR DESCRIPTION
**Pull request by bmcelvee**
https://trello.com/c/TsPvBDhg/664-document-package-hosa-hawkular

https://trello.com/c/oyo2UlJ0/475-3-package-hosa-hawkular

### CODE REVIEW

**Comment by bmcelvee** [comment]
@mwringe PTAL

**Comment by mwringe** [comment]
@bmcelvee looks good, but we also need to delete the whole 'Deploying the Hawkular OpenShift Agent' section.

We may also want to add a note that setting the variable to false will remove HOSA from an installation.

**Comment by bmcelvee** [comment]
@mwringe thanks! I removed the 'Deploying/Undeploying the Hawkular OpenShift Agent' sections, and added the `false` variable.

**Comment by bmcelvee** [comment]
@openshift/team-documentation please peer review 🍂

**Comment by mwringe** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/cluster_metrics.adoc#install-config-cluster-metrics[Enabling Cluster Metrics]
|Added `openshift_metrics_install_hawkular_agent` variable in the xref:../install_config/cluster_metrics.adoc#metrics-ansible-variables[Specifying Metrics Ansible Variables] section, and removed the outdated Deploying and Undeploying the Hawkular OpenShift Agent steps. 
%

**Pull request merged**
