### PR TITLE
Updating the machine set docs to use newer GCP marketplace images

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.13+

Issue:
N/A

Link to docs preview:
* [Sample YAML for a compute machine set custom resource on GCP](https://70365--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-gcp#machineset-yaml-gcp_creating-machineset-gcp)
* [Sample GCP provider specification](https://70365--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-configuration#cpmso-yaml-provider-spec-gcp_cpmso-configuration)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@jianli-wei can you please verify this update?

**Comment by jianli-wei** [comment]
> @jianli-wei can you please verify this update?

It looks good to me. 

FYI we have monthly `gcp-ipi-marketplace` tests in PROW CI already, and one sample run [here](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-gcp-ipi-marketplace-f28/1745758399775117312) and the machine sets [JSON](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-gcp-ipi-marketplace-f28/1745758399775117312/artifacts/gcp-ipi-marketplace-f28/gather-extra/artifacts/machinesets.json). 
```
$ grep -E "as: gcp-ipi-.*marketplace" ci-operator/config/ -rl
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
$ grep -E "as: gcp-ipi-.*marketplace" ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml -n -A10
1255:- as: gcp-ipi-marketplace-f28
1256-  cron: 43 10 12 * *
1257-  steps:
1258-    cluster_profile: gcp-qe
1259-    env:
1260-      COMPUTE_OSIMAGE: projects/redhat-marketplace-public/global/images/redhat-coreos-ocp-413-x86-64-202305021736
1261-      CONTROL_PLANE_OSIMAGE: projects/redhat-marketplace-public/global/images/redhat-coreos-ocp-413-x86-64-202305021736
1262-    test:
1263-    - chain: openshift-e2e-test-qe
1264-    workflow: cucushift-installer-rehearse-gcp-ipi-workers-marketplace
1265:- as: gcp-ipi-marketplace-f28-destructive
1266-  cron: 27 17 10 * *
1267-  steps:
1268-    cluster_profile: gcp-qe
1269-    env:
1270-      COMPUTE_OSIMAGE: projects/redhat-marketplace-public/global/images/redhat-coreos-ocp-413-x86-64-202305021736
1271-      CONTROL_PLANE_OSIMAGE: projects/redhat-marketplace-public/global/images/redhat-coreos-ocp-413-x86-64-202305021736
1272-      TEST_ADDITIONAL: Network_Observability
1273-    test:
1274-    - chain: openshift-e2e-test-qe-destructive
1275-    workflow: cucushift-installer-rehearse-gcp-ipi-workers-marketplace
$

**Pull request merged**
