### PR TITLE
[OSDOCS-6909]: Update storage size for openshift dedicated on GCP

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-6909
Link to docs preview:

https://76842--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs.html#gcp-policy-storage_gcp-ccs
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114, Could I please get a review on this PR? Thanks!

**Comment by smunje1** [comment]
Hello @mletalie, this changes LGTM. As I am new to the peer review squad, I request that you wait until @bscott-rh  gives approval.

**Comment by mletalie** [comment]
> Hello @mletalie, this changes LGTM. As I am new to the peer review squad, I request that you wait until @bscott-rh gives approval.

Thanks @smunje1 and @bscott-rh!

**Comment by bscott-rh** [comment]
LGTM :)

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
