### PR TITLE
Fix image attribution popover

### PR DESCRIPTION
**Pull request by rhcarvalho**
- Popover functionality needs to be explicity initialized
  (http://getbootstrap.com/javascript/#callout-popover-opt-in)
- Need to set html=true to render contents properly

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by bparees** [comment]
lgtm.  @adellape

**Comment by adellape** [comment]
Will let @nhr take a look/merge.

**Comment by nhr** [comment]
Subscribe.

**Pull request merged**
