### PR TITLE
add blurb in docs for pipeline dsl

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees and @openshift/team-documentation PTAL

A small blurb in the official docs regarding the new DSL for the plugin.  As has been our convention, the precise details are handled in the README in the git repo for the plugin.

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
@openshift/team-documentation bump

**Comment by vikram-redhat** [comment]
@bfallonf - can you peer review the text?

**Comment by bfallonf** [comment]
@vikram-redhat Could do with a followup for all the instance of plugin vs plug-in, but that goes beyond what was added here. 

What's here looks good to me.

**Comment by vikram-redhat** [comment]
@tpoitras @bfallonf https://bugzilla.redhat.com/show_bug.cgi?id=1343292

**Pull request merged**
