### PR TITLE
[OSDOCS-6145]-Update Structure of Configuring machine pools/local zones for machine pools in ROSA docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-6145
Link to docs preview:

https://60227--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-configuring.html
QE review:
- [ ] QE has approved this change.

QE N/A
Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

**Review by michaelryanmcneill — APPROVED** [review]
LGTM

**Comment by bmcelvee** [comment]
No QE review required.

**Pull request merged**
