### PR TITLE
OSDOCS-1836: Add global admission plug-in for HSTS release note

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-1836

Related to https://github.com/openshift/openshift-docs/pull/35812 and https://github.com/openshift/openshift-docs/issues/33497.

Preview: https://deploy-preview-36815--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-networking-hsts

### CODE REVIEW

**Comment by bmcelvee** [comment]
@quarterpin would you mind reviewing this release note PR, please? Thank you!

**Comment by quarterpin** [comment]
The section could have a separate header like the other features. Currently, it looks like there is some formating error causing it to seem like part of the CNF VRF section:
```
[id="ocp-4-9-networking- ==== Global admission plug-in for HTTP Strict Transport Security requirements
```

**Comment by stevsmit** [comment]
LGTM!

**Pull request merged**
