### PR TITLE
[OSDOCS-8203]:Remove 4.11 warning

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8203
Link to docs preview:

https://67797--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations

https://67797--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources#rosa-sts-account-wide-roles-and-policies_rosa-sts-about-iam-resources
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 / @yuwang-RH,
   Can I get a QE review for this PR? Thanks!

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
