### PR TITLE
RHDEVDOCS-4006 - Helm-multicluster-updates

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
[RHDEVDOCS-4006](https://issues.redhat.com//browse/RHDEVDOCS-4006): Document on the Helm update for multi-cluster, for 4.11

- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.11` and later
- **JIRA issues**: [RHDEVDOCS-4006](https://issues.redhat.com/browse/RHDEVDOCS-4006)
- **Preview pages**: [Download to see the preview in your browser](https://drive.google.com/file/d/1qSf-yIYIfCoDLDE2u33RvjFgGWn7EZoN/view?usp=sharing)
- **SME Review**: Completed by @dperaza4dustbit
- **QE review**:  Completed by @tisutisu
- **Peer-review**: Completed by @rolfedh

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
Hi @dperaza4dustbit and @tisutisu: PTAL at this PR and provide your feedback. Thanks!

**Review by tisutisu — COMMENTED** [review]
LGTM

**Review by dperaza4dustbit — APPROVED** [review]
lgtm

**Review by rolfedh — APPROVED** [review]

**Comment by Preeticp** [comment]
As per @Srivaralakshmi this is valid only for 4.11, hence removing 4.10 label

**Pull request merged**
