### PR TITLE
OSSMDOC-615: Update supported configurations topic for 2.2

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.6-4.11

Link to docs preview: http://file.bos.redhat.com/tokeefe/OSSMDOC-615/service_mesh/v2x/preparing-ossm-installation.html#ossm-supported-configurations_preparing-ossm-installation

Dev review: Rob
QE Review: Prachi
Peer review: Jstickler

### CODE REVIEW

**Review by rcernich — APPROVED** [review]

**Comment by prachiyadav** [comment]
Verified

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
