### PR TITLE
Bug 1416556 Removed technology preview note

### PR DESCRIPTION
**Pull request by bmcelvee**

### CODE REVIEW

**Comment by bmcelvee** [comment]
@vikram-redhat @ahardin-rh @adellape  Please review when you get a chance. Thanks!

**Comment by ahardin-rh** [comment]
LGTM :+1:

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/secrets.adoc#service-serving-certificate-secrets[Service Serving Certificate Secrets]
|Removed Tech Preview note from the xref:../dev_guide/secrets.adoc#service-serving-certificate-secrets[Service Serving Certificate Secrets] section.
%

**Comment by bmcelvee** [comment]
Thanks! I'll go ahead and merge.

**Pull request merged**
