### PR TITLE
GitHub-25195: Removing wildcard as a valid option for noProxy during …

### PR DESCRIPTION
**Pull request by bergerhoffer**
…installation

https://github.com/openshift/openshift-docs/issues/25195

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@danehans Can you confirm if * is NOT a valid option for noProxy when configuring the proxy during installation? If that's correct, we'll remove this line saying that it is. Also added clarification on "." for subdomains only, if you can check that as well. Thanks!

Previews: 
* https://github-25195--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-configure-proxy_installing-restricted-networks-bare-metal
* https://github-25195--ocpdocs.netlify.app/openshift-enterprise/latest/networking/enable-cluster-wide-proxy.html#nw-proxy-configure-object_config-cluster-wide-proxy

**Review by masayag — COMMENTED** [review]
LGTM

**Comment by danehans** [comment]
`*` should be a valid `proxy.spec.noProaxy` value to bypass proxy for all destinations. The intent is to mirror the proxy support in [3.x](https://docs.openshift.com/container-platform/3.11/install_config/http_proxies.html#configuring-no-proxy):

> The only wildcard NO_PROXY accepts is a single * character, which matches all hosts, and effectively disables the proxy.

Based on the details of https://github.com/openshift/openshift-docs/issues/25195, a bug should be created with the installer team. After a quick review of the cluster-network-operator code, I don't see an issue handing `*` for `proxy.spec.noProxy` reconciliation. Please verify that `*` is being written to `proxy.status.noProxy` and open a [BZ](https://bugzilla.redhat.com/) with the network team if that's not the case.

**Comment by bergerhoffer** [comment]
Thanks @danehans! Can you verify that the other part of this update is okay to make? The clarification on the subdomain when using "."?

@masayag Can you open a BZ for the installer as @danehans recommends? I'm going to update this PR to keep the part about * for now.

**Comment by masayag** [comment]
> @masayag Can you open a BZ for the installer as @danehans recommends? I'm going to update this PR to keep the part about * for now.

Reported: https://bugzilla.redhat.com/show_bug.cgi?id=1877486

**Comment by bergerhoffer** [comment]
@danehans Can you review whether this clarification on matching subdomains only is correct to make? Thanks!

**Comment by danehans** [comment]
PR needs to be rebased, otherwise /lgtm.

**Comment by bergerhoffer** [comment]
@gpei Can you please review this? Previews:

* https://deploy-preview-25201--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-configure-proxy_installing-restricted-networks-bare-metal
* https://deploy-preview-25201--osdocs.netlify.app/openshift-enterprise/latest/networking/enable-cluster-wide-proxy.html#nw-proxy-configure-object_config-cluster-wide-proxy

**Comment by gpei** [comment]
LGTM

**Pull request merged**
