### PR TITLE
RHDEVDOCS-3158: Allow configuration of passphrase for fluent forward

### PR DESCRIPTION
**Pull request by rolfedh**
- Aligned team: Dev Tools
- For branches: Logging 5.2 [enterprise-TBD]
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3158
- Direct link to doc preview: https://deploy-preview-34744--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-external?utm_source=github&utm_campaign=bot_dp#cluster-logging-collector-log-forward-fluentd_cluster-logging-external
- SME reviewed and approved by @vparfonov 
- QE review: @kabirbhartiRH 
- Peer review: @jc-berger 
- CLOSED - DO NOT MERGE 
- SUPERSEDED BY [RHDEVDOCS-3226](https://issues.redhat.com/browse/RHDEVDOCS-3226) Logging 5.2 docs aggregated branch, https://github.com/openshift/openshift-docs/pull/35445

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by rolfedh** [comment]
/openshift-logging-5.2

**Pull request closed without merging**
