### PR TITLE
OSDOCS-1670 GCP install - personal disk encryption

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1670

### CODE REVIEW

**Comment by codyhoag** [comment]
Preview: http://file.rdu.redhat.com/~choag/010721/gcp-encrypt/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters_installing-gcp-customizations

**Comment by codyhoag** [comment]
@staebler can you review this PR for the new GCP disk encryption field? Thanks!

**Comment by tsze-redhat** [comment]
Thanks for working on this.

A few quick comments:


A) Example should look like this:

  name: master
  platform:
  gcp:
    type: n2-standard-4
    zones:
    - us-central1-a
    - us-central1-c
    osDisk:
      diskType: pd-ssd
      diskSizeGB: 256
      encryptionKey: 
        kmsKey:
          name: worker-key
          keyRing: test-machine-keys
          location: global
          projectID: project-id
        kmsKeyServiceAccount: dev-installer@xyz-devel.iam.gserviceaccount.com
  replicas: 3
compute: 
  - hyperthreading: Enabled 
  name: worker
  platform:
  gcp:
    type: n2-standard-4
    zones:
    - us-central1-a
    - us-central1-c
    osDisk:
      diskType: pd-standard
      diskSizeGB: 128
      encryptionKey: 
        kmsKey:
          name: worker-key
          keyRing: test-machine-keys
          location: global
          projectID: project-id
        kmsKeyServiceAccount: dev-installer@xyz-devel.iam.gserviceaccount.com

ie
kmsKeyServiceAccount only applies to worker (master has to use default compute service acccount)
master uses ssd


B) Optional: The personal encryption key section to encrypt both virtual machines and persistent volumes. 
should probably be
Optional: The custom encryption key section to encrypt both virtual machines and persistent volumes.

C) I am not sure if we need platform.gcp.osDisk.encryptionKey.kmsKey.name given we have:
controlPlane.platform.gcp.osDisk.encryptionKey.kmsKey.name
compute.platform.gcp.osDisk.encryptionKey.kmsKey.name
(will leave it to others to confirm)

Description for key related values for control and compute probably need to include reference to indicate they are for masters / workers to avoid potential confusion.

D) "The GCP Region" for the rows related to keys is referred to in GCloud doc as Location.

E) For kmsKeyServiceAccount: dev-installer@xyz-devel.iam.gserviceaccount.com,
it can be specified but it won't have effect at install time - it is there for any 2-day operations.
Master machines will be encrypted using the key specified provided the key has the correct permission for access by the default compute service account.

F) The GCP Compute Engine System service account email, like **dev-installer@xyz-devel.iam.gserviceaccount.com**.
should be
The GCP Compute Engine System service account email, like **service-<a series of numbers>@compute-system.iam.gserviceaccount.com--

@JoelSpeed can help review this too.

Thanks again.

**Comment by JoelSpeed** [comment]
I've had a look over this but @tsze-redhat has captured all the comments I would have made and more, so nothing to add here once those are fixed up

**Comment by codyhoag** [comment]
@tsze-redhat 
>kmsKeyServiceAccount only applies to worker (master has to use default compute service account)

Should I remove the `kmsKeyServiceAccount` from the control plane section of the YAML and remove the param entry `controlPlane.platform.gcp.osDisk.encryptionKey.kmsKeyServiceAccount`? If the default account is used for masters, is there a point in specifying the option of a personal service account?

**Comment by tsze-redhat** [comment]
I was told service account can be specified - just that it won't take effect at install time but it can be used for 2-day operations as some customers may choose to use different keys for install and 2-day operations.
Hope it is clear but please ping me if it isn't.
Thanks.

**Comment by codyhoag** [comment]
@tsze-redhat I have incorporated your feedback in a4a3fc59b23b0283163e7b78efd4231645e68bac. Can you confirm this is correct?

**Comment by codyhoag** [comment]
@tsze-redhat I don't follow your second point.
>Service account to be specified in kmsKeyServiceAccount (for both master and worker) has no restriction to the part before @ sign so in @<compute_system>.iam.gserviceaccount.com` is not necessary. In fact, I think the whole @<compute_system>.iam.gserviceaccount.com could be just something like (or something like that).

I've seen examples like the following for service accounts:
- `aos-qe-serviceaccount@openshift-qe.iam.gserviceaccount.com`
- `openshift-dev-installer@openshift-gce-devel.iam.gserviceaccount.com`

They appear to follow a similar `<x>@<y>.iam.gserviceaccount.com`. Is there a generic term better for `x` and `y` than `service` and `compute_system`?

**Comment by codyhoag** [comment]
@tsze-redhat can you verify this now with the latest updates? Thanks!

**Comment by codyhoag** [comment]
QE gave final verification via Slack

**Comment by codyhoag** [comment]
Preview: http://file.rdu.redhat.com/~choag/010721/gcp-encrypt/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters_installing-gcp-customizations

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
