### PR TITLE
Add procedure: listing acting alerting rules

### PR DESCRIPTION
**Pull request by rh-max**
@sheriff-rh Hey Andrew, could you please review this? Thanks. If it looks fine, please merge it and cherry-pick to enterprise-4.2.

### CODE REVIEW

**Comment by rh-max** [comment]
@sheriff-rh Update: please cherry-pick to enterprise-4.1 and enterprise-4.2.

**Review by sheriff-rh — APPROVED** [review]
Looks good! Merging and picking to 4.2. Thanks @rh-max !

**Comment by rh-max** [comment]
@sheriff-rh Hey man, could you please cherrypick to enterprise-4.1 too? Thanks!

**Pull request merged**
