### PR TITLE
For Issue#5105

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For #5105 
fixed one missing link and deleted one wrong link

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@php-coder Can you please check? I deleted the second link, I couldn't find a replacement. Could you suggest?

**Comment by php-coder** [comment]
> I deleted the second link, I couldn't find a replacement. Could you suggest?

I'd suggest to find out the author of this change and ask him.

**Comment by gaurav-nelson** [comment]
@php-coder I checked the history and this was added 3 years ago. I also tried to search and replace with new content but could not find anything related. I am moving forward with deletion.

**Comment by gaurav-nelson** [comment]
minor updates no rev history required.

**Comment by php-coder** [comment]
@gaurav-nelson Thanks!

**Pull request merged**
