### PR TITLE
removed link to dev guide

### PR DESCRIPTION
**Pull request by vikram-redhat**
@openshift/team-documentation - PTAL. We have a cherry pick robot!

To cherry pick to a branch, you use the syntax: "/cherrypick branchname". If the cherrypick is successful, it does the CP to that branch and creates a new PR in the branch for you (wait a few seconds while it does it - it will show you the link to the new PR). Go ahead and merge the new PR once Travis finishes (you may want to edit the title of the PR to remove stage).

If the cherry pick fails due to a merge conflict, it lets you know that and no PR is created. You need to CP like normal on command line.

See examples below. In this example I merged this to master and then used the "/cherrypick branchname" to create the new PRs. All my cherry picks were successful except the ones for the online branches, which I CP'ed from the command line. 

I encourage everyone to give this a try, and if no issues, we can add this as part of our process. This should reduce the time it takes to do CP. Remember:

1. To cherry pick to the stage branches (although this will change next week).
2. When there is a merge conflict, please CP on the command line as part of our current process and be diligent about resolving the conflicts.
3. Each cherrypick needs to be in a new comment. I tried combining them into one comment, but that doesn't work.

h/t to @gaurav-nelson for pointing out that engineering is using this.

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
👍 We need more robots :)

**Comment by ahardin-rh** [comment]
This is cool. Thanks @gaurav-nelson 🍒 ⛏

**Comment by tmorriso-rh** [comment]
I like this process. You get immediate feedback if the robot cannot do the cherry pick. The error messages are useful. The cross links between the PRs are useful. Thanks @gaurav-nelson! 👍

**Comment by gaurav-nelson** [comment]
Thanks to the OpenShift/Kubernetes  team, I just happened to discover this while going through the origin repo.

**Comment by vikram-redhat** [comment]
It took me a while, but I finally got that emoji reference @ahardin-rh 🤣

**Comment by adellape** [comment]
@vikram-redhat @gaurav-nelson How bout for PRs with multiple commits? Will it try to pick sequentially?

**Comment by vikram-redhat** [comment]
@adellape - I haven't tried, but I am guessing it will. Will try today.

**Comment by bfallonf** [comment]
@adellape I accidentally did this for #7849 and it's cherrypicks #7877 and #7878 . Looks like it does pick them sequentially. Works well enough.

**Pull request merged**
