### PR TITLE
OSDOCS#10324: Removed Tech Preview snippet and reference for Static IP assignment feature

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/OSDOCS-10324

Link to docs preview: 
https://75068--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs.html
https://75068--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks.html

QE review:
- [x] QE has approved this change. @sgaoshang

### CODE REVIEW

**Comment by sgaoshang** [comment]
@snarayan-redhat looks like we also have Tech Preview snippet and reference in Additional resources
 part here

**Comment by snarayan-redhat** [comment]
> @snarayan-redhat looks like we also have Tech Preview snippet and reference in Additional resources part here
> 
> Additional resources [Scaling machines to use static IP addresses](https://75068--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks#nodes-vsphere-scaling-machines-static-ip_post-install-node-tasks)
> 
> [Using a machine set to scale machines with configured static IP addresses](https://75068--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks#nodes-vsphere-machine-set-scaling-static-ip_post-install-node-tasks)

@sgaoshang Thanks for catching that! Done.

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
