### PR TITLE
CNV#35113: Remove obsolete 4.13 note from upgrade assembly

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/CNV-35113

Link to docs preview:
https://68398--docspreview.netlify.app/openshift-enterprise/latest/virt/updating/upgrading-virt.html

QE review: NA

Additional information:

### CODE REVIEW

**Comment by danielclowers** [comment]
hey @apinnick, any input on what @dfitzmau mentioned above regarding change management?

**Comment by danielclowers** [comment]
hi @dfitzmau, after speaking with the team it looks like this does not require a change management notification.

**Comment by dfitzmau** [comment]
> hi @dfitzmau, after speaking with the team it looks like this does not require a change management notification.

Thanks. NP. I'll remove the in progress label. 

/remove-label peer-review-in-progress

/label peer-review-done

**Comment by ousleyp** [comment]
LGTM!

**Pull request merged**
