### PR TITLE
Added Router Sharding Images

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview build:
http://file.rdu.redhat.com/~ahardin/03082017/adding-router-sharding-diagrams/install_config/router/default_haproxy_router.html#using-router-shards

@ramr PTAL at the placement of these diagrams and let me know if anything should be adjusted. Thanks!

### CODE REVIEW

**Comment by ramr** [comment]
@ahardin-rh  LGTM  but  @knobunc may want to take a look as well.

**Comment by ahardin-rh** [comment]
@knobunc bump

**Comment by ahardin-rh** [comment]
@knobunc PTAL

**Comment by ahardin-rh** [comment]
I am moving forward with this. If any adjustments need to be made, we can do so in a separate PR. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/router/default_haproxy_router.adoc#install-config-router-default-haproxy[Setting up a Router -> Using the Default HAProxy Router]
|Added graphics to the xref:../install_config/router/default_haproxy_router.adoc#using-router-shards[Using Router Shards] section.
%

**Pull request merged**
