### PR TITLE
OCPBUGS-23201-4.12:updates OS bump on 4.12

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-23201

Link to docs preview:
https://70264--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes#ocp-4-12-about-this-release

QE review:
- [x] QE has approved this change.

Additional information:
https://github.com/openshift/openshift-docs/pull/68009/files
PTAL @sdodson

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
LGTM. @JoeAldinger If we are now listing the supported versions as 8.6-8.9, I think that requires a QA review/approval on the PR. Presently, the check box isn't checked.

@bburt-rh as my onboarding buddy for the OCP peer review process, please also review and comment on the PR if you think I've missed anything. Thanks!

**Comment by bburt-rh** [comment]
@JoeAldinger - I think that @rh-tokeefe is correct. This one will need QE approval, and because it's altering already released RNs, it needs change managment as well, correct? I don't see any of those approvals yet either. That said, it LGTM, although it shouldn't merge before all the approvals are in. Thanks!

**Comment by mwerner2113** [comment]
LGTM

**Comment by xltian** [comment]
LGTM

**Pull request merged**
