### PR TITLE
RNs-4.9.40 Added with bug fix update

### PR DESCRIPTION
**Pull request by Wiharris**
**RNs-4.9.40**
Added with bug fix update

**Version(s):**
PR applies to enterprise-4.9 only

**Issue**
https://issues.redhat.com/browse/OCPPLAN-9406

**Link to docs preview:**
https://wiharris.github.io/openshift-docs/RNs-4.9.40/release_notes/ocp-4-9-release-notes.html#ocp-4-9-40

**Additional information:**
Not yet shipped live

### CODE REVIEW

**Review by johnwilkins — COMMENTED** [review]
The text looks good to me. The links to the errata give me a 404 error. Are those unpublished?

**Comment by Wiharris** [comment]
> The text looks good to me. The links to the errata give me a 404 error. Are those unpublished?

Yes, there are unpublished as they have no yet `shipped live`. Once they are `shipped live`, they should be public. :)

**Review by bergerhoffer — COMMENTED** [review]
LGTM too :)

**Review by opayne1 — COMMENTED** [review]
One little nit before I can merge :)

**Pull request merged**
