### PR TITLE
Mentioning that sensitive objects aren't logged

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1173

Preview: https://osdocs-1173-update--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-audit-config.html#about-audit-log-profiles_nodes-nodes-audit-config

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
This seems important enough that I might move it before the table, but it LGTM.

**Comment by bergerhoffer** [comment]
Thanks @kalexand-rh. I had considered that, but I don't mention the difference in levels (metadata/request bodies) until the table, so I was thinking it might not make sense until you read the table descriptions. Let me know if you still think it would be better before.

**Comment by bergerhoffer** [comment]
@wangke19 Can you please review this update for audit logging as well? Thanks!

Preview: https://osdocs-1173-update--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-audit-config.html#about-audit-log-profiles_nodes-nodes-audit-config

**Comment by kalexand-rh** [comment]
@bergerhoffer, I took it more as a caveat that the sensitive objects are exempt from some of the rules, which might be useful to know up front. :) I might make it a footnote tied to the strategies that use request bodies.

**Comment by bergerhoffer** [comment]
@kalexand-rh Great suggestion, thanks!

**Comment by wangke19** [comment]
@bergerhoffer we have some new updates for audit log content, https://github.com/openshift/cluster-openshift-apiserver-operator/pull/392#issue-487260262, @sttts Do you think if we need to document that?

**Comment by bergerhoffer** [comment]
@sttts So we don't need to worry about documenting the specifics about OAuth tokens as @wangke19 pointed out above?

**Pull request merged**
