### PR TITLE
[RHACS] Fixed permission related docs bug

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://issues.redhat.com/browse/ROX-12683

Merge into: `rhacs-docs`

Cherry pick into:
- `rhacs-docs-3.72`
- `rhacs-docs-3.71`
- `rhacs-docs-3.70`
- `rhacs-docs-3.69`

Preview: https://openshift-docs-git-rox12683-gnelson.vercel.app/openshift-acs/master/backup_and_restore/backing-up-acs.html#on-demand-backups-roxctl-api_backing-up-acs

### CODE REVIEW

**Comment by pneedle-rh** [comment]
LGTM

**Review by dhaus67 — APPROVED** [review]
Thanks for fixing this so quickly @gaurav-nelson !

**Pull request merged**
