### PR TITLE
Bug 1264182, added image support details

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1264182

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rjhowe , I added in the link and a brief statement. Does this meet your definition of done? Thanks!

**Comment by rjhowe** [comment]
@ahardin-rh  LGTM 

Thank You

**Comment by ahardin-rh** [comment]
@rjhowe , thanks! Added some additional details per a conversation with @adellape . Please let me know if further edits are needed.

**Comment by adellape** [comment]
@ahardin-rh Just thought of this: we'd want to wrap this in an openshift-enterprise ifdef so that your new text only shows up in the OSE build, since the situation is different for Origin.

@rjhowe Bump on Ashley's latest request above.

**Comment by rjhowe** [comment]
@ahardin-rh  LGTM

**Comment by ahardin-rh** [comment]
Added ifdef for this content for OSE.

**Comment by ahardin-rh** [comment]
Discussed this with @adellape and we're going to merge this and continue in the BZ if needed.

**Comment by adellape** [comment]
Adding the dedicated-3.1 label to this.

**Comment by adellape** [comment]
Followed-up with https://github.com/openshift/openshift-docs/pull/1512 to make it show up for Dedicated too.

**Pull request merged**
