### PR TITLE
tidy up STI testing

### PR DESCRIPTION
**Pull request by tpoitras**
trello: https://trello.com/c/YPYVt1lq 
trello: https://trello.com/c/TGNCjwsD

original dev-supplied docs: PR#92

### CODE REVIEW

**Comment by tpoitras** [comment]
ping @mfojtik for quick tech review

**Comment by mfojtik** [comment]
LGTM

**Comment by adellape** [comment]
@tpoitras Took a look, :+1:. LMK if I can merge.

**Comment by tpoitras** [comment]
@adellape -- go ahead! :+1:

**Pull request merged**
