### PR TITLE
[OSDOCS-5013]: GCP CPMS support implementation details

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.13+

Issue:
[OCPCLOUD-1774](https://issues.redhat.com//browse/OCPCLOUD-1774) | [OSDOCS-5013](https://issues.redhat.com//browse/OSDOCS-5013)

Link to docs preview:
[Supported cloud providers](https://56751--docspreview.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-getting-started.html#cpmso-platform-matrix_cpmso-getting-started)

QE review:
- [ ] QE has approved this change.

Additional information:
* Rel notes: #56750
* Includes changes from #55407, will refresh after that PR is merged to show the true diff.

### CODE REVIEW

**Comment by jeana-redhat** [comment]
This is also pretty straightforward. @odvarkadaniel and @miyadav PTAL

/label peer-review-needed

**Review by adellape — APPROVED** [review]

**Comment by odvarkadaniel** [comment]
I think that GCP has the same level of support as Azure right now.
Both of these providers get a generated CPMS in `Active` State (checked on nightly builds of 4.13), @jeana-redhat.

**Comment by jeana-redhat** [comment]
Thanks @odvarkadaniel! Revised the table to make Azure and GCP the same

**Comment by odvarkadaniel** [comment]
Thank you, @jeana-redhat. LGTM now!

**Comment by jeana-redhat** [comment]
Thanks! @miyadav this should now be ready for QE (apologies for the premature tag last week)

**Comment by miyadav** [comment]
Thanks @jeana-redhat ,  LGTM

**Pull request merged**
