### PR TITLE
OSSM 1.0.1 Release notes

### PR DESCRIPTION
**Pull request by neal-timpe**
For ~Tuesday Oct 8~. Thursday Oct 10.

However, that date is not completely solid.

### CODE REVIEW

**Comment by neal-timpe** [comment]
@gbaufake @mattmahoneyrh Can you take a look?

**Comment by neal-timpe** [comment]
@tiago @yxun Can you take a look?

**Comment by mattmahoneyrh** [comment]
Looks good to me

**Review by yxun — APPROVED** [review]

**Comment by hhovsepy** [comment]
These fixed issues are related to Kiali only. Even though they are in OSSM project.
Isn't is better to be moved to under "Kiali fixed Issues" section?

**Comment by hhovsepy** [comment]
Also, those fixed 3 issues are the ones which are logged into Kiali known issues section: "KIALI-3265", "KIALI-3251" and "KIALI-3246" (OSSM clones of that KIALI issues).
Shouldn't they be deleted from Documentation, to not cause confusion?

**Comment by neal-timpe** [comment]
@hhovsepy Good points. Just committed those changes.

**Comment by hhovsepy** [comment]
@neal-timpe Thank you, verified now.

**Comment by gbaufake** [comment]
LGTM

**Comment by neal-timpe** [comment]
@openshift/team-documentation Can you review this for a release today?

**Comment by mburke5678** [comment]
@neal-timpe LGTM

**Review by mburke5678 — APPROVED** [review]

**Comment by kalexand-rh** [comment]
@neal-timpe says this is ready for production. Merging.

**Pull request merged**
