### PR TITLE
In this RH Doc etcd versions are incorrect

### PR DESCRIPTION
**Pull request by BabbarPB08**
Version(s): 4.13

Issue:
In this RH Doc etcd versions are incorrect

This should be called as variable according to the OCP version.

Link to docs preview: 

QE review:
- [ ] QE has approved this change.

Additional information:

for additional info kindly refer:

```
[quickcluster@upi-0 ~]$ etcd_pod=$(oc get pods -n openshift-etcd -l app=etcd --no-headers | tail -1 | awk '{print $1}') 
[quickcluster@upi-0 ~]$ oc rsh -n openshift-etcd $etcd_pod etcdctl endpoint status --cluster -w table
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://10.74.209.147:2379 | 8ed7d505aaf45080 |   3.5.6 |  124 MB |      true |      false |        13 |   57933181 |           57933181 |        |
|  https://10.74.212.36:2379 | 9f9113345971d38f |   3.5.6 |  173 MB |     false |      false |        13 |   57933181 |           57933181 |        |
|  https://10.74.213.58:2379 | f2b2d0305cd96bd6 |   3.5.6 |  182 MB |     false |      false |        13 |   57933181 |           57933181 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
[quickcluster@upi-0 ~]$ oc get clusterversions
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.5    True        False         43d     Cluster version is 4.13.5
[quickcluster@upi-0 ~]$ etcd_pod=$(oc get pods -n openshift-etcd -l app=etcd --no-headers | tail -1 | awk '{print $1}') 
[quickcluster@upi-0 ~]$ oc rsh -n openshift-etcd $etcd_pod etcdctl endpoint status --cluster -w table
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://10.74.209.147:2379 | 8ed7d505aaf45080 |   3.5.6 |  124 MB |      true |      false |        13 |   57933287 |           57933287 |        |
|  https://10.74.212.36:2379 | 9f9113345971d38f |   3.5.6 |  173 MB |     false |      false |        13 |   57933287 |           57933287 |        |
|  https://10.74.213.58:2379 | f2b2d0305cd96bd6 |   3.5.6 |  182 MB |     false |      false |        13 |   57933287 |           57933287 |        |
+----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
[quickcluster@upi-0 ~]$ oc get clusterversions
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.5    True        False         43d     Cluster version is 4.13.5
```

### CODE REVIEW

**Comment by BabbarPB08** [comment]
Link to docs preview:

https://docs.openshift.com/container-platform/4.13/post_installation_configuration/cluster-tasks.html#etcd-defrag_post-install-cluster-tasks

**Review by kowen-rh — APPROVED** [review]
Verified that this is the correct version number with the commands specified in the PR. LGTM! :+1:

**Comment by kowen-rh** [comment]
I assume this applies for version 4.13+, not just 4.13, correct?

**Comment by geliu2016** [comment]
the VERSION is 3.5.9
# oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.12   True        False         13m     Cluster version is 4.13.12
sh-5.1# etcd --version
etcd Version: 3.5.9
Git SHA: GitNotFound
Go Version: go1.19.10 X:strictfipsruntime
Go OS/Arch: linux/amd64

sh-5.1# etcdctl endpoint status -w table
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|         ENDPOINT          |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://10.0.138.131:2379 | a0179e79ee803236 |   3.5.9 |  102 MB |     false |      false |         8 |      41128 |              41128 |        |
| https://10.0.172.137:2379 | 52a452f96358b9dc |   3.5.9 |  102 MB |      true |      false |         8 |      41128 |              41128 |        |
|  https://10.0.206.71:2379 | 428984e0534784ef |   3.5.9 |  102 MB |     false |      false |         8 |      41128 |              41128 |        |
+---------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

**Comment by BabbarPB08** [comment]
[updated the version from 4.5.6 to 4.5.9](https://github.com/openshift/openshift-docs/pull/64688/commits/2d0e2905fec568da8ddd3b2a2c35bf37be7f9235)

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

Note that the actual docs preview is here: https://64688--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks#etcd-defrag_post-install-cluster-tasks

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by JoeAldinger** [comment]
HI @BabbarPB08 can you squash your commits and then I'll merge, please and thanks.

**Pull request closed without merging**
