### PR TITLE
installing: OKD: Add note about Ignition SSH keys on FCOS

### PR DESCRIPTION
**Pull request by LorbusChris**
to troubleshooting page.

This documents the solution for BZ#1868062 [1].

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1868062

/cc @bgilbert @darkmuggle

### CODE REVIEW

**Comment by bgilbert** [comment]
I've tried to edit this down a bit.  Alternative proposal:

> On Fedora CoreOS, SSH keys specified in the Ignition config are normally written to `/home/core/.ssh/authorized_keys.d/core`.  However, the OKD Machine Config Operator configures `sshd` to ignore that file, and manages SSH keys in `/home/core/.ssh/authorized_keys` instead.  As a result, newly provisioned OKD nodes are not accessible via SSH until the Machine Config Operator first reconciles the MachineConfig with the `authorized_keys` file.  The inoperative `/home/core/.ssh/authorized_keys.d/core` file is not deleted automatically, but may be deleted manually if the cluster administrator chooses.

**Comment by LorbusChris** [comment]
Thank you @bgilbert! I wrestled with the wording here for a bit, I like your proposal better :) Will update

**Comment by bgilbert** [comment]
Text LGTM.  I'd like input from the docs team on whether there's a better place to put this, though.

**Comment by miabbott** [comment]
ping @openshift/team-documentation

**Comment by vikram-redhat** [comment]
@mburke5678 - can you move this forward?

**Comment by mburke5678** [comment]
@mike-nguyen Can you PTAL at this PR?

**Comment by mike-nguyen** [comment]
LGTM

**Comment by mburke5678** [comment]
@codyhoag I plan to edit this paragraph a bit. However, i wonder if there is a better place in the install docs for this information.

**Comment by codyhoag** [comment]
@mburke5678 this is a commonly included module that goes over the SSH generation and application: https://github.com/openshift/openshift-docs/blob/master/modules/ssh-agent-using.adoc. For example, for AWS [here](https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-customizations.html#ssh-agent-using_installing-aws-customizations).

It would probably be relevant there.

**Pull request merged**
