### PR TITLE
add default resources to BuildDefaults

### PR DESCRIPTION
**Pull request by wanghaoran1988**
Doc PR for https://trello.com/c/fdRnlbqn/1035-2-default-resource-limits-for-build-pods

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
@bparees PTAL

**Comment by bparees** [comment]
@openshift/team-documentation we need a enterprise/3.5 label.

**Comment by bparees** [comment]
lgtm, @openshift/team-documentation ptal but please do not merge until https://github.com/openshift/origin/pull/11575 merges.

this is for origin, online, dedicated, and enterprise3.5.

**Comment by ahardin-rh** [comment]
@bparees Label created and applied. Thanks!

I will have to do some minor style edits after this merges (to the topic as a whole), so I also applied a to_followup label :star2:

**Comment by bparees** [comment]
@ahardin-rh the pre-req PR has merged.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/build_defaults_overrides.adoc#install-config-build-defaults-overrides[Configuring Global Build Defaults and Overrides] 
|Added information to the xref:../install_config/build_defaults_overrides.adoc#manually-setting-global-build-defaults[Manually Setting Global Build Defaults] example about adding default resources to `BuildConfig`.
%

**Pull request merged**
