### PR TITLE
TELCODOCS:1152 - New advisory update for OSC 1.3.3

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): Only 4.12

Issue: [TELCODOCS-1152](https://issues.redhat.com/browse/TELCODOCS-1152)

[Link to docs preview
](https://55297--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-1.3-release-notes.html#sandboxed-containers-1-3-3)
QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by jensfr — APPROVED** [review]
looks good to me, thank you @MirzWeiss

**Review by cpmeadors — APPROVED** [review]
QE approval

**Pull request merged**
