### PR TITLE
OADP-1324: Correct typos

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/OADP-1324
OCP 4.6+
OADP 1.1.2
Preview: 
https://56528--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/troubleshooting.html#velero-obtaining-by-downloading_oadp-troubleshooting
https://56528--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-advanced-topics.html#oadp-checking-api-group-versions_oadp-advanced-topics

### CODE REVIEW

**Comment by sbeskin-redhat** [comment]
branch/enterprise-4.13

**Comment by mburke5678** [comment]
@sbeskin-redhat Did you intend to delete the `modules` symlink? If so, LGTM

**Review by PrasadJoshi12 — APPROVED** [review]

**Comment by sbeskin-redhat** [comment]
@mburke5678  Thank you! 
Yes, I removed the symlink.

**Comment by sbeskin-redhat** [comment]
@mjpytlak 
Done

**Comment by mjpytlak** [comment]
@sbeskin-redhat We are managing active doc for 4.9+. I will merge for 4.9+

**Comment by mjpytlak** [comment]
@sbeskin-redhat Please resolve the conflict in 4.10 and 4.9 and let me know when you have the manual CP up.

**Comment by sbeskin-redhat** [comment]
@mjpytlak 
Thank you!

**Pull request merged**
