### PR TITLE
[SRVCOM-961] Remove instructions to create namespaces

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per https://issues.redhat.com/browse/SRVCOM-961, these namespaces are now created automatically by the operator. The user doesn't have to do that anymore.

/hold

Until the code actually ships.

### CODE REVIEW

**Comment by abrennan89** [comment]
lgtm thanks @markusthoemmes 
@vikram-redhat are there any rules about redirects where we remove a module entirely? Do we just redirect to the main install doc or does this only matter for assembly level?

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by vikram-redhat** [comment]
@abrennan89 moving modules doesn't require redirects. Only assemblies.

**Comment by kalexand-rh** [comment]
Per @abrennan89, this is ready to merge.

**Pull request merged**
