### PR TITLE
CNV-33123_1: [docs] Filter VMs by IP address

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.15

Issue: [CNV-33123](https://issues.redhat.com/browse/CNV-33123)

Link to docs preview:
[Update to Search field description in VirtualMachines page on the web console](https://71755--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/getting_started/virt-web-console-overview#virtualmachines-page_virt-web-console-overview)

QE review: Completed

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by aspauldi** [comment]
@JoeAldinger, I added the peer-review-needed label prematurely. Sorry! I still need SME and QE approvals.

**Comment by tobiastal** [comment]
Hi, AFAIK we can't search by "node", other than that it's LGTM.
"Search for virtual machines by name, label, node, or IP address."

**Comment by aspauldi** [comment]
@lkladnit, can you please review this tiny documentation PR? Thanks!

**Review by lkladnit — APPROVED** [review]

**Pull request merged**
