### PR TITLE
OSDOCS-1005:removes limitation of InFW on ROSA and AWS

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10005

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by msherif1234** [comment]
is it worth to clarify starting from OCP 4.16 we can support INFW for ROSA default installation at least we make it clear for users with older release that still won't work ?

**Comment by JoeAldinger** [comment]
> is it worth to clarify starting from OCP 4.16 we can support INFW for ROSA default installation (MTU = 9000) at least we make it clear for users with older release that still won't work ?

Can we support ROSA? I thought ROSA didn't support any Operators. If we need to migrate the InFW Operator to the ROSA docs, we should get someone from ROSA to check functionality for us prior to migrating docs.

**Comment by JoeAldinger** [comment]
@msherif1234 is this [PR](https://github.com/openshift/openshift-docs/pull/76269) not correct then given your comments about older versions? Should this update be limited to just 4.16+ or should this be applied to 4.12+?

**Comment by JoeAldinger** [comment]
closing in favor of #76900

**Pull request closed without merging**
