### PR TITLE
update check-asciidoctor-build.sh error msg

### PR DESCRIPTION
**Pull request by aireilly**
update `check-asciidoctor-build.sh` log messages to be more meaningful.

Example error log: https://app.travis-ci.com/github/openshift/openshift-docs/jobs/606525069

### CODE REVIEW

**Comment by aireilly** [comment]
@jeana-redhat PTAL

**Comment by jeana-redhat** [comment]
Helpful info _and_ emoji-based enhancements, LGTM :tada:

**Comment by aireilly** [comment]
@gabriel-rh Can you PTAL at this one too please. It doesn't change anything except the log messages, so should be good to merge.

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
