### PR TITLE
OSDOCS-8408: adds KI for Azure AD eastus

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-8408

Link to docs preview:
https://67079--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-known-issues

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jeana-redhat — COMMENTED** [review]
Some editorial suggestions - thanks so much for getting this online

**Review by kalexand-rh — APPROVED** [review]
I confirmed that this is a lightly edited version of the content that QE provided on the issue. Because of the proximity to GA and the importance of this issue, if you can get approval from engineering, I am ok with merging it today and getting final QE ack on the live content.

**Comment by jstuever** [comment]
lgtm

**Comment by jianping-shu** [comment]
LGTM

**Pull request merged**
