### PR TITLE
BZ#2072087: Add release note for stricter HTTP header validation with HAProxy 2.2

### PR DESCRIPTION
**Pull request by Miciah**
* `release_notes/ocp-4-8-release-notes.adoc`: Add a release note that HAProxy 2.2 enforces stricter HTTP header parsing.

Version(s):
OpenShift 4.8

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2072087

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by ahardin-rh** [comment]
This update is going through our change management process.

**Comment by lihongan** [comment]
@quarterpin  please help take a look. Thanks,

**Comment by quarterpin** [comment]
/lgtm
thanks!

**Comment by ahardin-rh** [comment]
Change management complete

**Pull request merged**
