### PR TITLE
[enterprise-3.4] added a note to recreate routes on wildcard policy change

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1427093

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@vwalek Can you please take a look?

**Comment by gaurav-nelson** [comment]
@vwalek Can you please take a look?
Also,
Looks like this is applicable to OCP 3.5, 3.6, 3.7, 3.9 as well. Can you confirm?

**Comment by zhaozhanqi** [comment]
LGTM, sorry for late reply.

**Comment by gaurav-nelson** [comment]
@zhaozhanqi Can you please confirm if this is applicable to OCP 3.5, 3.6, 3.7 and 3.9?

**Comment by zhaozhanqi** [comment]
@gaura
yes, this can be applicable to 3.5/3.6/3.7/3.9 and later

**Comment by gaurav-nelson** [comment]
Thanks @zhaozhanqi I will add this to the said versions.

**Comment by gaurav-nelson** [comment]
PR for rest of the branches #10727

**Comment by gaurav-nelson** [comment]
Closing this in favor of #10727

**Pull request closed without merging**
