### PR TITLE
Add to allowlist for downloading RHCOS images

### LINKED ISSUE #24851: [enterprise-4.5] Issue in file installing/install_config/configuring-firewall.adoc
### Which section(s) is the issue in?
When installing OpenShift 4.5 on VMware vSphere, it requires access to download RHCOS from e.g. https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.5/45.82.202008010929-0/x86_64/rhcos-45.82.202008010929-0-vmware.x86_64.ova?sha256=e7fc00902051d3933bde11fe5e25fa6d252f5388a6d6daa54107a756aadcf899

### What needs fixing?
Add `openshift.org` to the whitelist

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #24851

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei PTAL? Thanks!

**Comment by gpei** [comment]
LGTM

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
