### PR TITLE
Bug 1437137, Added storage management guidance

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1437137

### CODE REVIEW

**Comment by mffiedler** [comment]
Nit:  Looks like other instances in the doc user CRI-O and CRIO in caps.   I know...I used cri-o in the bz.   Whatever is correct from a docs point of view is fine with me.

Example:  https://docs.openshift.com/container-platform/3.11/install_config/configuring_openstack.html#configuring-a-security-group-openstack

**Comment by portante** [comment]
Are we keeping in mind that RHEL uses `/var/log` for sysstat data (`/var/log/sa`) and systemd uses it for persistent journal data (`/var/log/journal`), while by default rsyslog and other log configurations use `/var/log` in random ways?

**Review by mffiedler — APPROVED** [review]

**Pull request merged**
