### PR TITLE
GH#49379:logging-network-policy.adoc typo fix

### PR DESCRIPTION
**Pull request by inderpaltiwana**
main branch

Version(s):
PR applies to all versions after a specific version: 4.8+

Issue:
https://github.com/openshift/openshift-docs/issues/49379

Link to docs preview:
modules/networking/network_policy/logging-network-policy.adoc
  * External contributors can request a generated preview from the OpenShift documentation team.

### CODE REVIEW

**Comment by inderpaltiwana** [comment]
@openshift/team-documentation can i get a reciew for this? also would need a generated preview on the typo update as per the PR process, should be an XS PR

**Comment by ahardin-rh** [comment]
Thank you! Looks like the Travis checks are stuck. Closing and reopening to see if that resolves it.

**Comment by ahardin-rh** [comment]
Ah! Looks like this was addressed in https://github.com/openshift/openshift-docs/pull/50079, which explains the failed cherry-picks. Thanks again!

**Pull request merged**
