### PR TITLE
New assembly and modules for About EFK Logging

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@openshift/team-documentation Can someone take a *quick* look at the -logging/efk-logging_ assembly and associated modules? I am still not 100% on the FCC program. 

I want to create an assembly to answer the user story: _As an administrator, I want to understand EFK logging_ (where EFK logging seems more specific than the current Aggregated Logging to me). I pulled concept material from the current [Aggregated Logging topic](https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html) and organized by feature.

Not looking for a full peer review or proof read. Just want to make sure this approach is what we are looking to accomplish.

(Please disregard the _configuring_nodes_ and _configuring_pods_ topics for the moment.

**Comment by kalexand-rh** [comment]
@mburke5678, your "about" modules and assembly look pretty legit.

I have a few comments/suggestions/requests:
- logging/efk-logging still needs the .adoc extension.
- logging/efk-logging shouldn't have an xref.
- I think you still need to paste the metadata, including the `toc::[]` statement, from a 3.11 topic into logging/efk-logging.
- I'd consider moving the "about" modules for the ELK stack components to offset=+2.

**Comment by mburke5678** [comment]
@kalexand-rh Assemblies can't have xrefs either?

**Comment by kalexand-rh** [comment]
@mburke5678, you're right. "You can use xrefs in assemblies." I think that means that we can't reuse assemblies, though.

**Comment by mburke5678** [comment]
@kalexand-rh Thanks for the tips!

**Comment by vikram-redhat** [comment]
@openshift/team-documentation - is the peer review done for this?

**Comment by kalexand-rh** [comment]
@vikram-redhat, enough for the initial merge. I think we need to have a more specific peer review at the same time as the E2E testing with QE.

**Comment by mburke5678** [comment]
@jcantrill 
In scrum today, @richm mentioned that we should review the logging docs for 4.0. This PR contains all of the 3.11 docs converted into our new docs format for 4.0. 
Can someone review these docs and let me know if anything need to be removed/changed for 4.0+? 
Also, comments on the new structure, headings, etc. would be greatly appreciated. 

I merged this PR, as I was having issues with our internal validation and once I got those problems settled, I wanted to get the docs in to the repo before any other issues came up. I will track any changes in a separate PR.

**Pull request merged**
