### PR TITLE
[RHACS] Release Notes updates for 3.71.1 Patch

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to `rhacs-docs-3.71`
- Cherry pick to `rhacs-docs`

[Issue](https://issues.redhat.com/browse/ROX-12852)

[Link to docs preview](http://file.rdu.redhat.com/kcarmich/rhacs-patch-371-1-new/release_notes/371-release-notes.html)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by 0x656b694d** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
