### PR TITLE
OpenStack: Fix endpointTrafficPolicy mistake

### PR DESCRIPTION
**Pull request by dulek**
It's externalTrafficPolicy.

### CODE REVIEW

**Comment by maxwelldb** [comment]
@eurijon Could you ack this?

**Comment by maxwelldb** [comment]
lgtm as far as docs changes go. Need QE ack to merge.

**Review by maxwelldb — APPROVED** [review]

**Comment by eurijon** [comment]
Looks good, nice catch @dulek !

**Comment by maxwelldb** [comment]
@dulek @eurijon 4.9+, right?

**Comment by maxwelldb** [comment]
Found it: https://github.com/openshift/openshift-docs/pull/46245

4.10+. TY!

**Pull request merged**
