### PR TITLE
TELCODOCS#1908: Adding xrefs for additional info on Encrypted devices

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.16

Issue:
[TELCODOCS-1908](https://issues.redhat.com/browse/TELCODOCS-1908)

Link to docs preview:
[About adding devices to a volume group](https://77473--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html#about-adding-devices-to-a-vg_logical-volume-manager-storage)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
Hi @jakobmoellerdev 
Could you please review this PR?
Thanks!

**Review by jakobmoellerdev — COMMENTED** [review]
/lgtm

**Comment by sr1kar99** [comment]
@radeore 
Could you please review this PR?
Thanks!

**Comment by stevsmit** [comment]
LGTM!

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
