### PR TITLE
CNV-27775: Sysprep link add

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.14+

Issue: [CNV-27775](https://issues.redhat.com//browse/CNV-27775)

Link to docs preview: https://sabrinajess.github.io/previews/CNV27775/virt/virtual_machines/virt-managing-vms-openshift-pipelines.html#example-pipelines_virt-managing-vms-openshift-pipelines
https://sabrinajess.github.io/previews/CNV27775/virt/virtual_machines/virt-managing-vms-openshift-pipelines.html#additional-resources_virt-managing-vms-openshift-pipelines 

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sabrinajess** [comment]
@geetikakay Please provide QE review.

**Review by tmalove — APPROVED** [review]

**Comment by geetikakay** [comment]
lgtm

**Pull request merged**
