### PR TITLE
OCPBUGS#13279: Update the explanation of graph:true field

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-13279

Link to docs preview: https://59714--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-creating-image-set-config_installing-mirroring-disconnected

QE review:
- [x] QE has approved this change.

Additional information: Created this follow-up PR to be consistent with the release notes wordings as SME suggested here https://github.com/openshift/openshift-docs/pull/59052#discussion_r1184815912

### CODE REVIEW

**Comment by xenolinux** [comment]
> > Version(s): 4.12+
> 
> hmm, graph:true is introduced in 4.11, right? Should we backport to 4.11 as well?

I am not 100% sure but I think it is 4.12(?). The merged PR (where we initially updated the explanation) was targetted to 4.12+ https://github.com/openshift/openshift-docs/pull/57989

**Comment by shellyyang1989** [comment]
> > > Version(s): 4.12+
> > 
> > 
> > hmm, graph:true is introduced in 4.11, right? Should we backport to 4.11 as well?
> 
> I am not 100% sure but I think it is 4.12(?). The merged PR (where we initially updated the explanation) was targetted to 4.12+ #57989

ah, okay. I'm fine with this one going to 4.12+. 

Could you please let me know why https://github.com/openshift/openshift-docs/pull/57989 was not backported to 4.11?

**Comment by xenolinux** [comment]
> > > > Version(s): 4.12+
> > > 
> > > 
> > > hmm, graph:true is introduced in 4.11, right? Should we backport to 4.11 as well?
> > 
> > 
> > I am not 100% sure but I think it is 4.12(?). The merged PR (where we initially updated the explanation) was targetted to 4.12+ #57989
> 
> ah, okay. I'm fine with this one going to 4.12+.
> 
> Could you please let me know why #57989 was not backported to 4.11?

I was not aware that it was introduced in 4.11. Should I make a PR to update this whole explanation in 4.11?

**Comment by shellyyang1989** [comment]
> > > > > Version(s): 4.12+
> > > > 
> > > > 
> > > > hmm, graph:true is introduced in 4.11, right? Should we backport to 4.11 as well?
> > > 
> > > 
> > > I am not 100% sure but I think it is 4.12(?). The merged PR (where we initially updated the explanation) was targetted to 4.12+ #57989
> > 
> > 
> > ah, okay. I'm fine with this one going to 4.12+.
> > Could you please let me know why #57989 was not backported to 4.11?
> 
> I was not aware that it was introduced in 4.11. Should I make a PR to update this whole explanation in 4.11?

Looks good to me. Let's double confirm with dev @wking @LalatenduMohanty

**Review by wking — APPROVED** [review]
/lgtm

And also matches [Lala's recommendations][1].

[1]: https://github.com/openshift/openshift-docs/pull/59052#discussion_r1184815912

**Comment by xenolinux** [comment]
@wking I wanted to confirm if `graph:true` was introduced in 4.11. If yes then do we need a PR for OCP 4.11 to update the `graph:true` field-related information in 4.11? This PR and the previous merged PR (https://github.com/openshift/openshift-docs/pull/57989) target 4.12+ versions

**Comment by wking** [comment]
Looking in [openshift/oc-mirror][1], it was new in 4.11, per:

```console
$ for Y in $(seq 9 12); do git --no-pager grep 'json:"graph' "origin/release-4.${Y}" pkg/api; done
fatal: ambiguous argument 'origin/release-4.9': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
origin/release-4.11:pkg/api/v1alpha1/config_types.go:   Graph    bool             `json:"graph,omitempty"`
origin/release-4.11:pkg/api/v1alpha2/types_config.go:   Graph bool `json:"graph,omitempty"`
origin/release-4.12:pkg/api/v1alpha1/config_types.go:   Graph    bool             `json:"graph,omitempty"`
origin/release-4.12:pkg/api/v1alpha2/types_config.go:   Graph bool `json:"graph,omitempty"`
```

And #47645 says GA in 4.11 and mentions `graph`.

[1]: https://github.com/openshift/oc-mirror

**Review by maxwelldb — APPROVED** [review]

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
