### PR TITLE
OSDOCS-11774: Move IBM Z post-install

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-11774

Link to docs preview:
https://81528--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/ibmz-post-install.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by holgwolf** [comment]
LGTM

**Comment by abrennan89** [comment]
LGTM, thanks @SNiemann15 ! 🙌🏻

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by ShaunaDiaz** [comment]
@SNiemann15 Please squash your commits down to 1.

**Pull request merged**
