### PR TITLE
SRVKE-837: BYO event source docs

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVKE-837

Applies for OCP 4.6+

Direct preview link: https://deploy-preview-37479--osdocs.netlify.app/openshift-enterprise/latest/serverless/event_sources/serverless-custom-event-sources.html

### CODE REVIEW

**Review by jrangelramos — COMMENTED** [review]
Hello, In general it looks good to me! Just 2 minor suggestion but I'll leave them up to you.

**Comment by jrangelramos** [comment]
QE Approved

**Review by michaelryanpeter — COMMENTED** [review]
Impressive work on a complex topic. I called out handful of instances of passive voice and passages where I lost the thread. Please feel free to take or ignore my suggestions as you see fit. Since this is my first time on the peer review squad, another member will follow up to check my review.

**Pull request merged**
