### PR TITLE
OSDOCS-4831:Lifecycle Updates

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-4831](https://issues.redhat.com//browse/OSDOCS-4831): Lifecycle Updates for 4.12

Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-4831

Link to docs preview: file: https://54881--docspreview.netlify.app/ 
OSD: https://54881--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-life-cycle.html
ROSA: https://54881--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
branch/enterprise-4.12
branch/enterprise-4.13

**Review by arendej — APPROVED** [review]
looks good, thank you.

**Comment by stevsmit** [comment]
LGTM.

**Pull request merged**
