### PR TITLE
BZ1958766: Updated note to be IPI-specific

### PR DESCRIPTION
**Pull request by skrthomas**
https://bugzilla.redhat.com/show_bug.cgi?id=1958766

for 4.5+

Preview: https://deploy-preview-32414--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#master-node-sizing

Will likely have merge conflicts due to s/master/control.

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
I have a suggestion for this change, but it's sounding good.

**Comment by skrthomas** [comment]
@geliu2016 can you have a look at this for QA?

**Comment by jhou1** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
