### PR TITLE
[OSP] Update Ignition files script - BZ1868439

### PR DESCRIPTION
**Pull request by maxwelldb**
https://bugzilla.redhat.com/show_bug.cgi?id=1868439

@pierreprinetti Is this 4.6 only or other releases, too?

### CODE REVIEW

**Comment by maxwelldb** [comment]
Preview link: https://osp-upi-ignition-script-1868439--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user.html#installation-osp-creating-control-plane-ignition_installing-openstack-user

**Comment by pierreprinetti** [comment]
4.6 only, thanks!

**Review by pierreprinetti — APPROVED** [review]

**Comment by maxwelldb** [comment]
Thanks!

Just need QE. @wjiangjay

**Comment by wjiangjay** [comment]
@maxwelldb LGTM

**Comment by maxwelldb** [comment]
Thanks!

**Comment by bmcelvee** [comment]
LGTM!

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
