### PR TITLE
Ignition config deprecation for release notes

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by chrisnegus** [comment]
LGTM

**Comment by codyhoag** [comment]
@marrusl can you confirm this release note for Ignition config v2 deprecation? Thanks!

**Comment by marrusl** [comment]
Hi @codyhoag LGTM too. Thank you both!

**Comment by codyhoag** [comment]
With peer review and SME review complete, I'm merging. Thanks!

**Pull request merged**
