### PR TITLE
[OSDOCS-8893]:Document additional GCP API service requirement (Organization Policy API)

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8893
Link to docs preview:

https://69912--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs#ccs-gcp-customer-procedure_gcp-ccs
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
**Reviewers: Do not merge as feature is not live as of 1/11/24**

**Comment by aldiazRH** [comment]
LGTM!

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Pull request merged**
