### PR TITLE
BZ-1791943: Specify for 3.7-3.10 clusters

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://bz-1791943-update--ocpdocs.netlify.com/openshift-enterprise/latest/migration/migrating-3-4/deploying_cam.html#installing-cam-operator-ocp-3_sourcecluster-3-4

### CODE REVIEW

**Comment by XinRedhat** [comment]
LGTM

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Review by jwmatthews — APPROVED** [review]
Technical approval of content

**Comment by bergerhoffer** [comment]
Merging with SME and QE approval.

**Pull request merged**
