### PR TITLE
Correct a IBM Power specific link

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.14+

Issue:

Link to docs preview:
https://70252--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing-preparing#installing-preparing-security

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by juliemathew** [comment]
lgtm

**Review by skopacz1 — APPROVED** [review]
Great catch, LGTM!

**Comment by ShaunaDiaz** [comment]
@alishaIBM LMK when you have the manual CP ready for 4.14 and I can merge it for you.

**Pull request merged**
