### PR TITLE
Bug 1384706, update screenshots for image catalog

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1384706

### CODE REVIEW

**Comment by jwforres** [comment]
@ahardin-rh those screenshots don't look right, that looks like the old catalog

**Comment by ahardin-rh** [comment]
@jwforres yeah, mistakenly used STG instead of INT. Reworking momentarily.

**Comment by ahardin-rh** [comment]
@jwforres @adellape Updated. PTAL. Thanks!

**Comment by adellape** [comment]
:+1:

**Comment by jwforres** [comment]
@luciddreamz has online not been updated with the templates that have the nice display names?

**Comment by jwforres** [comment]
INT version of online I mean

**Comment by luciddreamz** [comment]
@jwforres PR was merged (openshift/online/pull/618), but I don't think ops has updated this yet.

@abhgupta @dinhxuanvu Do we know when this is going to make it's way to INT?

**Comment by dinhxuanvu** [comment]
@luciddreamz According to the openshift-script RPM version that Ops used for INT, the newly updated templates should be in INT already. Please verify if you don't mind. Thanks

**Comment by luciddreamz** [comment]
@dinhxuanvu They are not in INT.

**Comment by dinhxuanvu** [comment]
@luciddreamz It is updated now :D.

**Comment by luciddreamz** [comment]
Looks good. 

Technically there is one issue in openshift/online repo, in that JWS should not be tagged with mongodb/database anymore: https://github.com/openshift/online/blob/master/templates/examples/jws30-tomcat8-mongodb-persistent-s2i.json#L9

Ignorning that for now.

**Comment by ahardin-rh** [comment]
Screenshots are now updated.

**Comment by jwforres** [comment]
@ahardin-rh thanks these look right now

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../getting_started/basic_walkthrough.adoc#getting-started-basic-walkthrough[Basic Walkthrough]
|Updated screenshots of the image catalog to reflect the latest user interface design.
%

**Pull request merged**
