### PR TITLE
GH#53709 Adding 'you' per request/typo.

### PR DESCRIPTION
**Pull request by mletalie**
Adding 'you' per request/typo.

Version(s):

4.10+
Issue:

https://github.com/openshift/openshift-docs/issues/53709
Link to docs preview:

https://54886--docspreview.netlify.app/openshift-enterprise/latest/networking/changing-cluster-network-mtu.html
image

QE review:
- [ ] QE has approved this change.

Typo fix only, no QE needed. 
Additional information:

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
This change lgtm. Only thing is your commit message does not match the title of your PR which they may mention in merge review.

**Comment by mletalie** [comment]
> This change lgtm. Only thing is your commit message does not match the title of your PR which they may mention in merge review.

Thank you @opayne1. I have changed to match the commit msg and title of PR. Appreciate it.

**Pull request merged**
