### PR TITLE
Non-preempting PriorityClass

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1654

Replaces #27676.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund Here is the new PR with my minor changes. Can you take a quick look to make sure that none of my adjustments are incorrect? Thanks!

Preview: https://osdocs-1654--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/pods/nodes-pods-priority.html#non-preempting-priority-class_nodes-pods-priority

**Comment by ingvagabund** [comment]
Looks good!!! Thanks

**Pull request merged**
