### PR TITLE
[OSDOCS#2464] Adding warning about --force for CLI cluster update

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-2464

Link to docs preview:
https://67438--docspreview.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Review by sheriff-rh — APPROVED** [review]
LGTM, merging.

**Pull request merged**
