### PR TITLE
OCPBUGS-35488_4.15#updating installation doc

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version:
4.15

Issue:
https://issues.redhat.com/browse/OCPBUGS-35488

Link to docs preview:

**AWS**
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations#installation-aws-arm-tested-machine-types_installing-aws-customizations

- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations#installation-aws-tested-machine-types_installing-aws-customizations 

**Azure**
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations#installation-azure-arm-tested-machine-types_installing-azure-customizations
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations#installation-azure-tested-machine-types_installing-azure-customizations

**GCP**
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types-arm_installing-gcp-customizations
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types_installing-gcp-customizations

**IBM Cloud**
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations#installation-ibm-cloud-tested-machine-types_installing-ibm-cloud-customizations
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-vpc
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-private
- https://83340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-restricted#installation-ibm-cloud-tested-machine-types_installing-ibm-cloud-restricted

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@jinyunma, Can you review the changes for AWS, Azure, and GCP? 

@MayXuQQ, Can you review the change for IBM Cloud?

**Comment by jinyunma** [comment]
LGTM, also cc @jianli-wei @yunjiang29 for awareness of AWS and GCP changes, and review.

**Comment by jianli-wei** [comment]
LGTM, for GCP changes, thanks!

**Comment by brendan-daly-red-hat** [comment]
@yunjiang29, PTAL at the AWS update.

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM to merge

**Pull request merged**
