### PR TITLE
RHDEVDOCS 6083 console plugin requires OCP 4.15

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

Please cp to pipelines-docs-1.15

Issue:

RHDEVDOCS 6083 

Link to docs preview:

https://77824--ocpdocs-pr.netlify.app/openshift-pipelines/latest/about/op-release-notes.html#breaking-changes-1-15_op-release-notes
https://77824--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/working-with-pipelines-web-console.html#op-enabling-plugin_working-with-pipelines-web-console

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6083

**Review by ppitonak — APPROVED** [review]

**Review by jkandasa — APPROVED** [review]
LGTM

**Review by koustavsaha — APPROVED** [review]

**Comment by dfitzmau** [comment]
LGTM, but is a change management needed? Is pipelines-docs-1.15 the latest release or an earlier release?

/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
