### PR TITLE
TELCODOCS-642: Factory pre-caching tool RN

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.12

Issue: https://issues.redhat.com/browse/TELCODOCS-642 and https://issues.redhat.com/browse/TELCODOCS-781

Link to docs preview: 

- https://54103--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#scalability-and-performance-factory-pre-staging-tool
- https://54103--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#scalability-and-performance-factory-pre-staging-tool-in-ztp
- https://54103--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-technology-preview under Scalability and performance technology preview features

QE review:
- [x] QE has approved this change.

Additional information: The tool common attribute and the link don't work until the [main content](https://github.com/openshift/openshift-docs/pull/53180) is merged.

### CODE REVIEW

**Comment by stevsmit** [comment]
LGTM

**Comment by amolnar-rh** [comment]
Only added "(Technology Preview)" to the entries after the LGTM

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
