### PR TITLE
Added videos for installation of CLI for Windows, Mac OS X, and Fedora

### PR DESCRIPTION
**Pull request by tpoitras**
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1285111

Created 3 new videos. They cover installing the CLI on Windows, Mac OS X, and Linux systems (I used Fedora).

Windows10: https://access.redhat.com/videos/2212891
Mac OS X: https://access.redhat.com/videos/2212921
Linux (Fedora): https://access.redhat.com/videos/2213051

Updated docs to include links to the videos, and image thumbnails to represent the videos.

### CODE REVIEW

**Comment by tpoitras** [comment]
@wsun1 tagging you for tech review, please and thank you. :octocat:

**Comment by tpoitras** [comment]
Tagging the team for Peer Review, please! :smile: 
@openshift/team-documentation 
@adellape @bfallonf @tnguyen-rh @ahardin-rh

**Comment by bfallonf** [comment]
@tpoitras I know this wasn't part of your PR, but there's a conditionalization that's making the render a little bit off. Just under the "Installing the CLI" heading. I think it might be easier to make that into two separate sentences instead of putting the gap in the middle.

Also, again not something from this PR, but the sentence "Follow the instructions that match the workstation where you will be running CLI operations." Is probably not necessary. The sentence before that makes this one redundant.

Other that that, everything you've added looks fine :moneybag:

**Comment by tpoitras** [comment]
Thanks Brice, I've made those changes.

**Comment by tpoitras** [comment]
[rev_history]
|link:../cli_reference/get_started_cli.html[Get Started with the CLI]
|Created 3 new videos about installing the CLI on Windows, Mac OS X, and Linux systems and updated written docs to include links to the videos, and image thumbnails to represent videos.
%

**Comment by adellape** [comment]
This got picked into the 3.2 GA release, so I've removed the related labels, but I'm leaving this in Next Release w/ the 3.1 labels on it to get in there.

**Comment by vikram-redhat** [comment]
@tpoitras I am guessing the peer_review got left here by mistake, right? In any case, I have removed it and picked it for the release. Let me know if not ok.

**Pull request merged**
