### PR TITLE
Adds base64 encoded note to access key id and access key secret

### PR DESCRIPTION
**Pull request by mikesmith0414**
Adds base64 encoded note to access key id and access key secret

Issue: https://github.com/openshift/openshift-docs/issues/49432

Versions: 4.10+

Preview: 
https://50531--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging-loki.html#logging-loki-deploy_cluster-logging-loki

Needs QE review.

### CODE REVIEW

**Comment by stevsmit** [comment]
cc @anpingli for QE review.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by tmalove — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
LGTM

**Pull request merged**
