### PR TITLE
OCPBUGS#13426: Update the Helm tutorial

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-13426

Link to docs preview: https://59984--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-tutorial.html#osdk-run-proxy_osdk-helm-tutorial

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
