### PR TITLE
OCPBUGS-9217 Include caveats for load balancer services

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.10

Issue: https://issues.redhat.com/browse/OCPBUGS-9217

Link to docs preview: https://63074--docspreview.netlify.app/openshift-enterprise/latest/networking/configuring_in[…]onfiguring-ingress-cluster-traffic-load-balancer.html](https://63074--docspreview.netlify.app/openshift-enterprise/latest/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer.html#nw-create-load-balancer-service_configuring-ingress-cluster-traffic-load-balancer)
](https://63074--docspreview.netlify.app/openshift-enterprise/latest/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer.html#nw-create-load-balancer-service_configuring-ingress-cluster-traffic-load-balancer)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@zhaozhanqi QE check please

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by cbippley** [comment]
@opayne1 Want to take a look?
/label peer-review-done
/remove-label peer-review-in-progress

**Review by opayne1 — COMMENTED** [review]
looks good pending a QE review

**Comment by mburke5678** [comment]
/enterprise-4.10

**Comment by mburke5678** [comment]
/enterprise-4.11

**Comment by mburke5678** [comment]
/enterprise-4.12

**Comment by mburke5678** [comment]
/enterprise-4.13

**Comment by mburke5678** [comment]
/enterprise-4.14

**Pull request merged**
