### PR TITLE
Correct Service ExternalIPs procedure

### PR DESCRIPTION
**Pull request by jboxman**
This procedure has always been incorrect.

- https://github.com/openshift/openshift-docs/issues/16900

Refs:

- https://github.com/openshift/openshift-docs/issues/16991
- https://github.com/openshift/openshift-docs/issues/18172
- https://github.com/openshift/openshift-docs/issues/18173
- https://github.com/openshift/openshift-docs/issues/20694
- https://github.com/openshift/openshift-docs/issues/21027
- https://github.com/openshift/openshift-docs/issues/23198
- https://github.com/openshift/openshift-docs/issues/23407

### CODE REVIEW

**Comment by jboxman** [comment]
@weliang1, can you verify this procedure? I've included a link to the KCS regarding configuring ExternalIP, because the PR for that is not yet complete. (https://github.com/openshift/openshift-docs/pull/21388)

Thanks!

**Comment by weliang1** [comment]
> @weliang1, can you verify this procedure? I've included a link to the KCS regarding configuring ExternalIP, because the PR for that is not yet complete. (#21388)
> 
> Thanks!

/LGTM

**Comment by jboxman** [comment]
Hi @danwinship,

Does this procedure for attaching an ExternalIP to a Service seem reasonable?

Thanks.

**Review by adellape — APPROVED** [review]
:+1:

**Pull request merged**
