### PR TITLE
OSDOCS#7832: Migrate sts cluster logging addon workaround from MOBB to ROSA

### PR DESCRIPTION
**Pull request by skopacz1**
Version(s): 4.13+

Issue:
[OSDOCS-7832](https://issues.redhat.com/browse/OSDOCS-7832)

Link to docs preview: [Workaround to fix the issue with the logging-addon on ROSA STS Clusters](https://64931--docspreview.netlify.app/openshift-rosa/latest/rosa_tutorials/rosa-mobb-sts-cluster-logging-addon)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by skopacz1** [comment]
@michaelryanmcneill could you PTAL? Thanks

**Comment by aldiazRH** [comment]
LGTM!

**Review by michaelryanmcneill — COMMENTED** [review]
It is my understanding that this guide is no longer necessary, as we do not recommend the use of the cluster logging addon. This is also covered in a KCS article as well: https://access.redhat.com/solutions/6485391, which I believe is better suited for this use case. I believe that we should close this and not merge it, but will do a final verification with the team, momentarily. Sorry for the unnecessary work.

**Comment by skopacz1** [comment]
@michaelryanmcneill no worries! I'll keep this open until you can confirm that this ought to be closed instead of merged

**Comment by michaelryanmcneill** [comment]
Confirmed, this should be closed. Thanks @skopacz1!

**Pull request closed without merging**
