### PR TITLE
Bug 1431804, added notes to verify cluster health before upgrading

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1431804

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@bmcelvee @mburke5678 please peer review

**Comment by bmcelvee** [comment]
LGTM 🎆

**Comment by mburke5678** [comment]
LGTM2

**Comment by ahardin-rh** [comment]
Acknowledged by QEin the BZ. Merging. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/automated_upgrades.adoc#install-config-upgrading-automated-upgrades[Upgrading a Cluster -> Performing Automated In-place Cluster Upgrades]
|Added a NOTE box about verifying the cluster health before upgrading.
%
|xref:../install_config/upgrading/manual_upgrades.adoc#install-config-upgrading-manual-upgrades[Upgrading a Cluster ->  Performing Manual In-place Cluster Upgrades]
|Added a NOTE box about verifying the cluster health before upgrading.
%

**Pull request merged**
