### PR TITLE
[enterprise-4.3] Imagestream tags

### PR DESCRIPTION
**Pull request by ahardin-rh**
Cherrypick of https://github.com/openshift/openshift-docs/pull/22308

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@apinnick Can you please cross-check this cherry-pick PR? There were a lot of conflicts and I just want to ensure it's all resolved properly before we merge. Thanks!

**Comment by ahardin-rh** [comment]
@apinnick I closed the 4.2 cherrypick PR, but can you please also cross-check this one?

**Comment by apinnick** [comment]
@ahardin-rh  It looks fine. Thanks

**Comment by ahardin-rh** [comment]
Thank you for checking!

**Pull request merged**
