### PR TITLE
BZ#2004025 Add updated machine requirements for AWS/Azure/GCP

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=2004025

This update deletes the current [Supported AWS machine types](https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-user-infra.html#installation-supported-aws-machine-types_installing-aws-user-infra) table and adds the "Required machines" and "Minimum resource requirements" tables for all AWS/Azure/GCP UPI assemblies. Example previews for each provider:
- [AWS](https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-user-infra.html#installation-requirements-user-infra_installing-aws-user-infra)
- [Azure](https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-requirements-user-infra_installing-azure-user-infra)
- [GCP](https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-requirements-user-infra_installing-gcp-user-infra)

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 can you verify for AWS?

@tsze-redhat can you confirm for Azure/GCP?

Thanks!

**Comment by tsze-redhat** [comment]
I saw the "Minimum resource requirements" section
https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#minimum-resource-requirements_installing-gcp-user-infra

While it applies to UPI, user can also specify machine types and disk sizes for IPI.

How do we handle this type of situation?
Put the same table in "Installing with customization" page like this one:
https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html

Or do we just not show these for IPI pages?

**Comment by codyhoag** [comment]
>While it applies to UPI, user can also specify machine types and disk sizes for IPI.
>
>How do we handle this type of situation?
>Put the same table in "Installing with customization" page like this one:
>https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp->customizations.html
>
>Or do we just not show these for IPI pages?

@tsze-redhat that's a really good question. That module I applied for AWS/Azure/GCP in this PR is only used in our UPI assemblies; we do not share the minimum machine resources in any IPI assemblies currently. So this PR is following that structure. Let me know if we should rethink that.

**Comment by yunjiang29** [comment]
@codyhoag got some questions:
1. same as @tsze-redhat, the `Supported AWS machine types` section was removed from all IPI and UPI documents, but `Minimum resource requirements` was added in UPI only, users may confuse that why the `Supported AWS machine types` removed and no any other guidance, they might think those instances will not be supported. 

2. regarding the IOPS, is there any document or PR that talking about the IOPS limitation on AWS? Or it just refer to the other platform.

3. regarding the bootstrap instance resources, the default bootstrap instance type in IPI is `m5.large`, which has 8GB memory, 2 vCPU, I tried to create a cluster which bootstrap machine has the same configuration (8GB memory, 2 vCPU), it works well, so I'm thinking do we need 16GB memory and 4 vCPU as minimum resource requirements? 

cc @patrickdillon 

##  Minimum resource requirements
Installing a cluster on user-provisioned infrastructure in AWS by using CloudFormation templates
	https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-user-infra.html#minimum-resource-requirements_installing-aws-user-infra

Installing a cluster on AWS in a restricted network with user-provisioned infrastructure
	https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-restricted-networks-aws.html#minimum-resource-requirements_installing-restricted-networks-aws


## Supported AWS machine types
Installing a cluster on AWS with customizations
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-customizations.html#installation-supported-aws-machine-types_installing-aws-customizations

Installing a cluster on AWS with network customizations
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-network-customizations.html#installation-supported-aws-machine-types_installing-aws-network-customizations

Installing a cluster on AWS into an existing VPC
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-vpc.html#installation-supported-aws-machine-types_installing-aws-vpc

Installing a private cluster on AWS
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-private.html#installation-supported-aws-machine-types_installing-aws-private

Installing a cluster on AWS into a government or secret region
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-government-region.html#installation-supported-aws-machine-types_installing-aws-government-region

Installing a cluster on user-provisioned infrastructure in AWS by using CloudFormation templates
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-aws-user-infra.html#installation-supported-aws-machine-types_installing-aws-user-infra

Installing a cluster on AWS in a restricted network with user-provisioned infrastructure
	https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-restricted-networks-aws.html#installation-supported-aws-machine-types_installing-restricted-networks-aws

**Comment by tsze-redhat** [comment]
@yuhuijiang This doc is where the disk recommendation is started.
https://docs.google.com/document/d/1yPpakMC1OSOWeeM4m_bHDuLECLPXrpq5ow2C9HEcs1A/edit

The minimum requirements also apply to GCP/AWS/Azure. same questions / comment also apply to Azure.

The table /section about resource requirements are showing up on Azure UPI page:
https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#minimum-resource-requirements_installing-azure-user-infra

As for (currently) not showing minimum requirements for IPI, I think we do need to rethink about where to put minimum requirements. Instead of putting it in various pages, maybe we can have a section in "Installing a cluster quickly on XXX" page like
https://deploy-preview-36663--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-default.html
@codyhoag Let me know if I can write a BZ to help kick start this rethinking about the structure.

Thanks.

**Comment by codyhoag** [comment]
Closing this PR, as I'm going to break this into multiple PRs for easier reviews.

**Pull request closed without merging**
