### PR TITLE
[Nodes][4.2] OCP documentation review

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1757972

### CODE REVIEW

**Comment by mburke5678** [comment]
@skordas Please take a look. This PR is for items 2-5 of your review. 
I am looking into item 1 and will use a separate PR. 
Do you know if all Admission Controllers are not supported in 4.x?

**Comment by skordas** [comment]
\lgtm

**Comment by mburke5678** [comment]
/enterprise-4.1

**Pull request merged**
