### PR TITLE
BZ1852128:added prerequisite step

### PR DESCRIPTION
**Pull request by skrthomas**
Link to doc preview: https://deploy-preview-31725--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-bootstrap_installing-gcp-user-infra

https://bugzilla.redhat.com/show_bug.cgi?id=1852128

For 4.5+

### CODE REVIEW

**Comment by skrthomas** [comment]
Ready for QA @tsze-redhat

**Comment by jboxman** [comment]
@skrthomas LGTM if it passes QE.

**Pull request merged**
