### PR TITLE
OSSMDOC-650: Clarify JWKS write up in release notes

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s):  4.6 - 4.12

Issue: https://issues.redhat.com/browse/OSSMDOC-650

Link to docs preview: http://file.bos.redhat.com/tokeefe/OSSMDOC-650/service_mesh/v2x/servicemesh-release-notes.html#ossm-rn-known-issues-ossm_ossm-release-notes

Additional information:

Yuanlin provided SME review and To Hung provided QA review.

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@yxun while Julie was reviewing the release notes, she suggested clarifications for the JWKS entry we previously worked on. Please review and provide comments. Thank you!

**Review by yxun — APPROVED** [review]

**Comment by tsze-redhat** [comment]
LGTM.
Thank you.

**Comment by rh-tokeefe** [comment]
@JStickler this is ready for peer review.

**Review by JStickler — APPROVED** [review]
LGTM but needs a rebase.

**Comment by rh-tokeefe** [comment]
@JStickler the rebase is now complete. We can merge this when you have time. Thanks!

**Pull request merged**
