### PR TITLE
BZ210198: Remove blocked upgrade restriction from vSphere CSI

### PR DESCRIPTION
**Pull request by lpettyjo**
We are not blocking upgrades to 4.11 when a 3rd-party vSphere CSI driver is detected due to feature parity issues with our driver vs 3rd-party drivers.

PR to add the upgrade blocking back for 4.13 is here: https://github.com/openshift/openshift-docs/pull/47535

Version(s): 4.10 and 4.11

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2103198

Link to docs preview: http://file.rdu.redhat.com/lpettyjo/BZ2103198_4_10and11/storage/container_storage_interface/persistent-storage-csi-vsphere.html#vsphere-csi-driver-reqs_persistent-storage-csi-vsphere

PTAL: @bscott-rh, @gnufied, @gcharot @duanwei33

### CODE REVIEW

**Comment by gcharot** [comment]
looks good thanks!

**Comment by duanwei33** [comment]
Just one query, are we going to mention 4.10 thing in 4.11 release as well?

**Pull request merged**
