### PR TITLE
OSDOCS-7812 added note about FIPS compliance to the CO docs

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-7812

Link to docs preview:
[Compliance Operator remediation (Important note, top of the page)](https://file.rdu.redhat.com/antaylor/OSDOCS-7812/security/compliance_operator/co-scans/compliance-operator-remediation.html)

Additional information:
None

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@knewcomerRH can you review when you have a chance? Thanks!

**Comment by sheriff-rh** [comment]
@knewcomerRH has suggested changes and approved this iteration of the FIPS statement in the Compliance Operator docs over Slack. 

Moving forward with peer review.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by sheriff-rh** [comment]
@mrunalp please review when you get a chance, thanks!

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
