### PR TITLE
Bug#1488607 - fixes

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1488607
Updated hyperlink for GlusterFS planning and fixed code blocks

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :squid: :paintbrush:

**Comment by gaurav-nelson** [comment]
Link updates, no revision history needed.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - parts of this applied to 3.5 and 3.6, but not to 3.4. For example, the link fix didn't apply to 3.4 because that section wasn't in the 3.4 guide.

**Pull request merged**
