### PR TITLE
Resolve asciidoctor warnings

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.14+

Issue: None

Link to docs preview: https://66013--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-restricted-networks-azure-installer-provisioned#installation-azure-config-yaml_installing-restricted-networks-azure-installer-provisioned

QE review: QE approval is not required 

Additional information: This PR does not add any new information. This PR fixes the following asciidoctor warnings:

```
asciidoctor: WARNING: modules/installation-azure-config-yaml.adoc: line 282: callout list item index: expected 15, got 10
asciidoctor: WARNING: modules/installation-azure-config-yaml.adoc: line 288: callout list item index: expected 16, got 11
asciidoctor: WARNING: modules/installation-azure-config-yaml.adoc: line 300: callout list item index: expected 15, got 17
asciidoctor: WARNING: modules/installation-azure-config-yaml.adoc: line 301: callout list item index: expected 16, got 18
asciidoctor: WARNING: modules/installation-azure-config-yaml.adoc: line 302: callout list item index: expected 17, got 19
```
Original PR https://github.com/openshift/openshift-docs/pull/61086

### CODE REVIEW

**Comment by mjpytlak** [comment]
@xenolinux Thanks for addressing this so quickly. Ahead of a merge, please verify that "Sample customized install-config.yaml file for Azure" renders correctly in each of the Azure installation assemblies. By renders correctly, I mean that the number of annotations in the sample match the number of descriptions in the descriptions.

Given that the a local build passed without warning, I suspect everything is fine, but just want to make sure because Travis does not report on these types of errors.

**Comment by xenolinux** [comment]
> @xenolinux Thanks for addressing this so quickly. Ahead of a merge, please verify that "Sample customized install-config.yaml file for Azure" renders correctly in each of the Azure installation assemblies. By renders correctly, I mean that the annotations in the sample match the annotation descriptions.
> 
> Given that the a local build passed without warning, I suspect everything is fine, but just want to make sure because Travis does not report on these types of errors.

@mjpytlak Yes I observed that after creating the PR so I added the [WIP] label. Some descriptions and numbers/callouts are mismatched in the "Sample customized install-config.yaml file for Azure"  section. I am checking each section if everything renders correctly.

**Review by mjpytlak — COMMENTED** [review]
Peer review lgtm.

**Pull request merged**
