### PR TITLE
SRVCOM-2151 remove references to buildpacks

### PR DESCRIPTION
**Pull request by gabriel-rh**
Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-2151

Link to docs preview:
https://52742--docspreview.netlify.app/openshift-enterprise/latest/serverless/cli_tools/kn-func-ref.html

https://52742--docspreview.netlify.app/openshift-enterprise/latest/serverless/discover/serverless-functions-about.html
https://52742--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-reference-guide.html

 QE has approved this change.

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved
/lgtm

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by Shermbo** [comment]
PX Approved
Thanks!

**Comment by nainaz** [comment]
Looks good.
Thank you @gabriel-rh

**Comment by gabriel-rh** [comment]
//cherry-pick enterprise-4.8

**Pull request merged**
