### PR TITLE
Replace ansible_sudo with ansible_become

### LINKED ISSUE #2720: Replace ansible_sudo with ansible_become
ansible_sudo is deprecated in ansible 1.8 and removed in 2.x

### PR DESCRIPTION
**Pull request by nekop**
fixes #2720

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing -> Advanced Installation]
|Replaced `*ansible_sudo*` with `*ansible_become*`.
%

**Comment by sdodson** [comment]
@ahardin-rh Can you get this change into the 3.2 docs too?

**Comment by sdodson** [comment]
@ahardin-rh Nevermind, 3.2 is done, 3.3 docs still lack this change.

**Comment by ahardin-rh** [comment]
@sdodson Thanks! Looks like I should have applied the 3.3 label here. As a result, this was missed in the 3.3 cherry-pick.

@vikram-redhat I am dropping the 3.2 label here, as this was already picked for 3.2. Adding a 3.3 label and changing the milestone to Next Release so that it is picked for 3.3 in the next weekly release. We will reapply the OCP 3.3 GA milestone following the weekly release.

**Pull request merged**
