### PR TITLE
Wrong description in featuregates document

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=2084577

Previews
[Enabling feature sets using the web console](https://deploy-preview-45629--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-console_nodes-cluster-enabling). Step 5, updated callout 2 to remove comma-separated list.
[Enabling feature sets using the CLI](https://deploy-preview-45629--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-cli_nodes-cluster-enabling), Step 1, updated callout 2 to remove comma-separated list.
[Additional resources](https://deploy-preview-45629--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html) corrected feature set name in intro paragraph

### CODE REVIEW

**Comment by mburke5678** [comment]
@sergiordlr @rioliu-rh PTAL

**Comment by sergiordlr** [comment]
Hello!. It looks good to me.

**Comment by JoelSpeed** [comment]
This fixes the immediate issue of the comma separated value comment but I think we may want to expand this section of the docs to talk about what features are included in each featureset and how customers can use the CustomNoUpgrade featureset to customise the tech preview features they want to have enabled.

That is, unless there has previously been discussion about this which concluded in support not wanting that information available

**Comment by JoelSpeed** [comment]
I've sent an email out to aos-devel and openshift-sme to talk about the topic of what we want to have documented here, that doesn't need to block this fix though

**Comment by mburke5678** [comment]
@rioliu-rh PTAL

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
