### PR TITLE
Adding HPE Nimble Kube Storage Controller to list of dynamic provisioners

### PR DESCRIPTION
**Pull request by datamattsson**
PR relevant for OpenShift Origin and OpenShift Enterprise (all versions from 3.5 and up). @openshift/team-documentation

### CODE REVIEW

**Comment by mburke5678** [comment]
@vikram-redhat PTAL

**Comment by vikram-redhat** [comment]
@drajen Hey Michael - we are seeking guideline on how this will be supported. Once we have that information we will let you know about merging it.

**Comment by drajen** [comment]
Thank you @vikram-redhat for reviewing. The provisioner and accompanied FlexVolume driver will be supported by HPE Nimble Storage support. This integration will eventually transition to CSI once stable.

**Comment by drajen** [comment]
@vikram-redhat any updates on this matter? Is there any way I can assist to move this forward?

**Pull request merged**
