### PR TITLE
Known issue for OCPBUGS#29236

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-9554
https://issues.redhat.com/browse/OCPBUGS-29236

Link to docs preview:

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@sgaoshang approved this via Slack DM. @vr4manta PTAL at this text summary of OCPBUGS-29236 for the 4.15 release notes. Thank you

**Comment by vr4manta** [comment]
/lgtm
Doc update looks good.

**Comment by GroceryBoyJr** [comment]
Detailed preview link: https://72009--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-known-issues

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
