### PR TITLE
Updated guidelines doc for clarification; removed custom markups

### PR DESCRIPTION
**Pull request by Bilhar-rh**
@adellape Quick sanity check, and please merge if all is good. doc_guidelines file updated to reflect the removal of custom markup. We'll be using the standard AsciiDoc markup in different combinations to achieve our goals.

### CODE REVIEW

**Comment by adellape** [comment]
@nhr @spurtell FYI. Of note, the [new markup reference table](https://github.com/CowboysFan/openshift-docs/blob/docs_guidelines/contributing_to_docs/doc_guidelines.adoc#quick-markup-reference).

**Comment by nhr** [comment]
Looks good. Ship it!

**Comment by adellape** [comment]
Thanks, @CowboysFan. I'm assuming the change to "[WIP]" in the topic title was intentional for the next few months or so as we continue to tweak, and not just placeholder during your edits this week. So, merging!

**Comment by CowboysFan** [comment]
@adellape Indeed, I think we'll have some more additions and further tweaking before we remove that in the next couple of months.

**Comment by tpoitras** [comment]
This revision clarifies so much for me. Thanks! :+1:

**Pull request merged**
