### PR TITLE
OSDOCS-1858 Subnet CIDR updates based on new way installer creates subnets

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1858

Release notes for this included in #32054

Previews:
* [GCP UPI update](https://deploy-preview-32061--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-user-infra-exporting-common-variables_installing-gcp-user-infra)
* [GCP UPI shared VPC update](https://deploy-preview-32061--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-creating-gcp-vpc_installing-gcp-user-infra-vpc)

### CODE REVIEW

**Comment by codyhoag** [comment]
@tsze-redhat PTAL

**Comment by tsze-redhat** [comment]
LGTM. Thanks!

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
