### PR TITLE
[GH#45419]: Fix indentation in Alibaba infra machineset CR

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.10+

Issue:
#45419

Link to docs preview:
- [Sample YAML for a machine set custom resource on Alibaba Cloud](https://deploy-preview-45443--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#machineset-yaml-alibaba_creating-infrastructure-machinesets) (infrastructure version)

Additional information:
N/A

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@miyadav or @sunzhaohua2 PTAL for QA

**Review by damdo — COMMENTED** [review]
/lgtm ++

**Pull request merged**
