### PR TITLE
OSDOCS-10171: Deduper merge mode

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

Only merge to `no-1.6`
Issue:

https://issues.redhat.com/browse/OSDOCS-10171
Link to docs preview:

Remove Show Duplicates: https://74435--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/observing-network-traffic.html#network-observability-quickfilternw-observe-network-traffic
QE review:
- [X] QE has approved this change.

Additional information:

Merge to only the `no-1.6` branch - no cherrypicks are required.
This PR is part of an experiment for simplifying merges for asynchronous content, and I will open one PR against main to incorporate all of the Network Observability 1.6 content just before its GA

### CODE REVIEW

**Comment by skrthomas** [comment]
@jpinsonneau I think this is all that's needed on the docs side for deduper? I have a release note draft here to explain the saved queries needing to be updated: https://docs.google.com/document/d/1xrnit6ZNrkvV-Qy0KEoKU8YO4H7kKmuPhXoYoMeqSDU/edit

**Comment by jpinsonneau** [comment]
> @jpinsonneau I think this is all that's needed on the docs side for deduper? I have a release note draft here to explain the saved queries needing to be updated: https://docs.google.com/document/d/1xrnit6ZNrkvV-Qy0KEoKU8YO4H7kKmuPhXoYoMeqSDU/edit

@skrthomas yes I think removing the deduplication mentions and adding details in release notes is good enough.
The auto generated doc on fields will also mention `Interfaces` and `Directions` arrays: https://github.com/netobserv/network-observability-operator/blob/main/docs/flows-format.adoc

FYI [NETOBSERV-1460](https://issues.redhat.com/browse/NETOBSERV-1460) remains open to find ways to migrate but I don't think we will make it. 
We decided to keep `FlowDirection` key to be able to query any previous data; other fields will still display but can't be filtered on old format as current state. This concern only **IfDirection** & **Interface** fields so the impact is very low.

cc @jotak @msherif1234

**Comment by skrthomas** [comment]
@memodi can you PTAL at the doc updates for deduper. More to come in RN PR.

**Review by memodi — APPROVED** [review]
/lgtm

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
