### PR TITLE
OLS-647: Create the lightspeed doc branch

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OLS 1

Issue:
https://issues.redhat.com/browse/OLS-647

Link to docs preview:
https://76899--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/install/ols-installing-openshift-lightspeed.html

QE review:
- [ ] QE has approved this change.

Additional information:

No QA Required for this PR.

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@aireilly looking at the [error log](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift-docs/build-docs/openshift-docs-build-docs-commands.sh) for this PR, I think the job is running into a problem with this [script](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift-docs/build-docs/openshift-docs-build-docs-commands.sh).

**Comment by aireilly** [comment]
Cool! All set

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
