### PR TITLE
TELCODOCS-1572 - accelerated container startup ZTP 4.12

### PR DESCRIPTION
**Pull request by aireilly**
Accelerated container startup MachineConfig in the docs out of sync with ZTP image for 4.12.

Version(s):
enterprise-4.12

Issue:
https://issues.redhat.com/browse/TELCODOCS-1572

Link to docs preview:
https://67862--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu#ztp-sno-du-accelerating-container-startup_sno-configure-for-vdu

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM as far as I can tell haha, does this need QE review?

**Comment by aireilly** [comment]
> LGTM as far as I can tell haha, does this need QE review?

No, not really but just following process :)

**Comment by mpmaruthu** [comment]
Telco CNF QE: Looks good to me. 

/Peri M

**Comment by aireilly** [comment]
@Missxiaoguo can you lgtm on this please.

**Comment by Missxiaoguo** [comment]
https://github.com/openshift-kni/cnf-features-deploy/pull/1402 is not in release 4.12. I think https://github.com/openshift-kni/cnf-features-deploy/pull/1371 is the latest PR for accelerated startup script change in 4.12.
@daosman could you please confirm?

**Comment by daosman** [comment]
> [openshift-kni/cnf-features-deploy#1402](https://github.com/openshift-kni/cnf-features-deploy/pull/1402) is not in release 4.12. I think [openshift-kni/cnf-features-deploy#1371](https://github.com/openshift-kni/cnf-features-deploy/pull/1371) is the latest PR for accelerated startup script change in 4.12. @daosman could you please confirm?

I beleive that change is in 4.12:
https://github.com/openshift-kni/cnf-features-deploy/commits/release-4.12/ztp/extra-manifests-builder/04-accelerated-container-startup

**Comment by Missxiaoguo** [comment]
> > [openshift-kni/cnf-features-deploy#1402](https://github.com/openshift-kni/cnf-features-deploy/pull/1402) is not in release 4.12. I think [openshift-kni/cnf-features-deploy#1371](https://github.com/openshift-kni/cnf-features-deploy/pull/1371) is the latest PR for accelerated startup script change in 4.12. @daosman could you please confirm?
> 
> I beleive that change is in 4.12: https://github.com/openshift-kni/cnf-features-deploy/commits/release-4.12/ztp/extra-manifests-builder/04-accelerated-container-startup

oh, great. See it now. Somehow I didnt see it the first time

**Pull request merged**
