### PR TITLE
Resolves unrendered attribute

### PR DESCRIPTION
**Pull request by briandooley**
Version(s): 4.15, 4.16, 4.17, 4.18

Issue: [OBSDOCS-1510](https://issues.redhat.com/browse/OBSDOCS-1510)

Link to docs preview: https://85429--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging-6.1/log6x-release-notes-6.1.html

QE review:
- No QE review necessary as this is just a simple text change.

Additional information:

### CODE REVIEW

**Review by dfitzmau — APPROVED** [review]

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Pull request merged**
