### PR TITLE
BZ2062352: add netfilter bug text

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.10

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2062352

Link to docs preview: https://deploy-preview-44885--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes.html#ocp-4-10-known-issues

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@miabbott could you PTAL? Also, what BZ ticket should I link to?

**Comment by jldohmann** [comment]
cb01d37..fd64df2 remove unended example block
20ee64d..181b395 remove upstream note

**Comment by jldohmann** [comment]
@miabbott I've updated the text to (hopefully 🤞) correctly reflect the issue, PTAL when you have a moment, thank you 🙇

**Review by miabbott — APPROVED** [review]
LGTM

**Comment by miabbott** [comment]
@sdodson does this match what you expected for the release notes?

**Comment by sdodson** [comment]
LGTM.

**Comment by jldohmann** [comment]
Closing and reopening to kick off Travis CI

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
