### PR TITLE
THREESCALE-7940: Updated to correct image.

### PR DESCRIPTION
**Pull request by dfennessy**
This pull requested is based on [THREESCALE-7940](https://issues.redhat.com/browse/THREESCALE-7940)

Reviewers

* 3scale QE: @pehala 
* CCS: @JStickler

### CODE REVIEW

**Comment by pehala** [comment]
LGTM!

**Review by pehala — APPROVED** [review]

**Comment by dfennessy** [comment]
> LGTM!

:sunglasses:

**Comment by dfennessy** [comment]
Happy New Year :fireworks:  

I hope you had a great holiday.

Please review this and move it forward accordingly. I think it's good to be merged with this change approved.

**Review by JStickler — APPROVED** [review]
LGTM

**Comment by JStickler** [comment]
@dfennessy  Which branches (releases) does this apply to?

**Comment by dfennessy** [comment]
> @dfennessy Which branches (releases) does this apply to?

@JStickler Same as the initial WebAssembly release: 4.6, 4.7, 4.8, 4.9, and 4.10

**Comment by dfennessy** [comment]
> LGTM

Cheers :tada:

**Pull request merged**
