### PR TITLE
OSDOCS-2888: Adding list of supported OIDC providers

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2888

Preview: https://deploy-preview-38743--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-oidc-identity-provider#identity-provider-oidc-supported_configuring-oidc-identity-provider

### CODE REVIEW

**Review by ctauchen — COMMENTED** [review]
Do we need to explain what OIDC is? Being unfamiliar with the product, and at times terribly thick, I was unable to work it out without a quick Google. 

LGTM

**Comment by bergerhoffer** [comment]
> Do we need to explain what OIDC is? Being unfamiliar with the product, and at times terribly thick, I was unable to work it out without a quick Google.
> 
> LGTM

@ctauchen I spelled out "OpenID Connect (OIDC)" here if that helps a bit. However, if you mean an actual description of what using an OIDC IDP is all about - that's something I could open a Jira to add later. I can see that a lot of the other IDP types have an "about" section... like "About LDAP authentication" and "About basic authentication". We could do something similar for OIDC.

I opened https://issues.redhat.com/browse/OSDOCS-2973 to track this enhancement. Thanks!

**Comment by ctauchen** [comment]
That's perfect, thanks!
/lgtm

**Pull request merged**
