### PR TITLE
Renaming CLI reference bucket to CLI tools

### PR DESCRIPTION
**Pull request by bergerhoffer**
Renamed bucket to "CLI tools". Also moved oc docs to a subdirectory called "OpenShift CLI (oc)" since the odo docs are being added here as well.

This PR should wait for the odo docs PR (#16627) to be merged first.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
FYI @vikram-redhat. I checked with @aheslin on this (and the rest of the team for naming preferences) but wanted to make sure you were okay with this change for 4.2 GA as well. 

Also, I assume you'll need to make changes for the 4.2 customer portal book due to this change?

**Comment by bergerhoffer** [comment]
@openshift/team-documentation For peer review please.

**Comment by vikram-redhat** [comment]
@bergerhoffer if this goes through peer review today, could you please merge?

**Review by kalexand-rh — COMMENTED** [review]
After you fix the merge conflict, it LGTM

**Comment by bergerhoffer** [comment]
Merging this since bucket name changes have to be in by today.

**Pull request merged**
