### PR TITLE
TELCODOCS-162: New PR to update CNF-792 already merged

### PR DESCRIPTION
**Pull request by kquinn1204**
Additional comments came in after https://issues.redhat.com/browse/CNF-792 was merged into main and cherry-picked to 4.8. Addressing these here.
Original dev Epic is [CNF-792](https://issues.redhat.com/browse/CNF-792)
Preview Link: https://deploy-preview-33021--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-create-performance-profiles.html

Original PR: https://github.com/openshift/openshift-docs/pull/30639

### CODE REVIEW

**Comment by kquinn1204** [comment]
preview doc is here https://deploy-preview-33021--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-create-performance-profiles.html

**Review by bergerhoffer — COMMENTED** [review]
LGTM, thanks a lot for following up on this feedback!

**Pull request merged**
