### PR TITLE
[OSDCOCS8489 ] 4.15 changes for multi-architecture tp and depr tables

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OSDOCS-8489

Link to docs preview: https://71084--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-technology-preview-tables

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Pull request merged**
