### PR TITLE
OSDOCS-1648: Adding API performance dashboard to the list

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1648

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! :snowman_with_snow:

**Comment by bergerhoffer** [comment]
@xingxingxia Can you please review this small update?

https://osdocs-1648--ocpdocs.netlify.app/openshift-enterprise/latest/monitoring/reviewing-monitoring-dashboards.html

**Comment by xingxingxia** [comment]
LGTM! Thanks

**Pull request merged**
