### PR TITLE
Changed service account section error

### PR DESCRIPTION
**Pull request by bfallonf**
@akram as per #1404 

Also, I didn't think to ask until after I created this PR, but am I replacing the line, or adding your suggested line? Both seemed to work for me...

### CODE REVIEW

**Comment by akram** [comment]
I added it as well, but apparently, since we are doing everything in the default namespace, the previous line is not required.
I suggest to remove it.

**Comment by bfallonf** [comment]
That works, because that's what I've already done :)

I'll get this merged. Thanks @akram

**Comment by bfallonf** [comment]
**revhistory note:**

(Install & Config -> Aggregating Container Logs )

```
Fixed an service account error in the link:../install_config/aggregate_logging.adoc[Aggregating Container Logs] topic.
```

**Comment by adellape** [comment]
@bfallonf Needs label/milestone.

**Comment by adellape** [comment]
Removed enterprise-3.0 label. This topic was `admin_guide/aggregate_logging.html` back then, but also this change isn't applicable to logging back then.

**Pull request merged**
