### PR TITLE
Change ignition sample to ignition Spec 3 for OKD:

### PR DESCRIPTION
**Pull request by jomeier**
https://github.com/openshift/openshift-docs/issues/23620

Current OKD example is wrong.

### CODE REVIEW

**Comment by vrutkovs** [comment]
@mburke5678 PTAL

**Comment by mburke5678** [comment]
@jomeier @vrutkovs LGTM. 
I wonder if the `append` parameter needs to change in the non-OKD docs. Is there something particular in OKD that requires `merge` rather than `append`?

**Comment by vrutkovs** [comment]
Right, filed https://github.com/openshift/openshift-docs/issues/23633 to track that

**Pull request merged**
