### PR TITLE
OSDOCS-8013 removed references to IMDS preference in GCP docs

### PR DESCRIPTION
**Pull request by xJustin**
This PR remove references to the IMDS configuration in the OSD-GCP docs.

Version(s):

4.13+

Issue:

https://issues.redhat.com/browse/OSDOCS-8013
Link to docs preview:

OSD-AWS:
https://66206--docspreview.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-an-aws-cluster#osd-create-aws-cluster-ccs_osd-creating-a-cluster-on-aws
OSD-GCP:
https://66206--docspreview.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xJustin** [comment]
Thanks @svmrh! I see those changes just happened. let me rebase and rebuild and see if they pop up.

**Review by jeana-redhat — APPROVED** [review]
LGTM, and **really** appreciate that you're linking both sides of conditionals in your previews :rocket: 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by xJustin** [comment]
Thanks @jeana-redhat!

**Pull request merged**
