### PR TITLE
OCPBUGS#20300: small Agent install-config.yaml fixes

### PR DESCRIPTION
**Pull request by skopacz1**
[OCPBUGS-20300](https://issues.redhat.com/browse/OCPBUGS-20300)

Versions: 4.13+

This PR fixes a few errors in the example install-config.yaml provided in the Agent docs
QE review:
- [x] QE has approved this change.

Preview: [install-config.yaml](https://67124--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/installing-with-agent-based-installer#installing-ocp-agent-inputs_installing-with-agent-based-installer:~:text=Create%20the%20install%2Dconfig.yaml%20file%3A)

### CODE REVIEW

**Comment by skopacz1** [comment]
@bmanzari could you PTAL? Thanks!

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Review by opayne1 — COMMENTED** [review]
Looks good to me!

**Pull request merged**
