### PR TITLE
bug 1672345 amended articles for grammar and context

### PR DESCRIPTION
**Pull request by sheriff-rh**
Bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1672345

@vikram-redhat  PTAL

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@sheriff-rh looks good. Are you waiting for QE contacts for the rest of the changes?

**Comment by sheriff-rh** [comment]
Correct @vikram-redhat , I'll hold the PR until QE is available to confirm the usage of `rhsub_` variables in the `all.yml` file.

**Comment by wjiangjay** [comment]
Hi, checked and all changes LGTM, but all the bold text in https://docs.openshift.com/container-platform/3.11/install_config/configuring_openstack.html#all-yaml-file did not take effect.

```yaml
openshift_openstack_public_dns_domain: *"example.com"*
openshift_openstack_dns_nameservers: *["10.19.115.228"]*
openshift_openstack_public_hostname_suffix: "-public"
openshift_openstack_nsupdate_zone: "{{ openshift_openstack_public_dns_domain }}"

openshift_openstack_keypair_name: *"openshift"*
openshift_openstack_external_network_name: *"public"*
```

All the *xxx* not work well.

**Comment by wjiangjay** [comment]
Sorry for my careless, I did not noticed the statement.
```
The values above that are enclosed by asterisks (*) require modification based
upon your OpenStack environment and DNS server.
```

**Pull request merged**
