### PR TITLE
bug 1709729 enabling feature gates for machinehealthchecks

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1709729

@mburke5678, I broke one of your assemblies in half. If you're not ok with the changes I'm proposing, I can revert them. 

@sunzhaohua2, will you PTAL? 

preview build: http://file.rdu.redhat.com/kalexand/051419/BZ1709729/machine_management/deploying-machine-health-checks.html

### CODE REVIEW

**Comment by mburke5678** [comment]
@kalexand-rh Why would Disabling Feature Gates not follow Enabling in the same topic?

**Comment by kalexand-rh** [comment]
@mburke5678, they're different user goals, so they should be different assemblies. This would be like putting installing and uninstalling in the same assembly - you do them at different times for different reasons.

**Comment by sunzhaohua2** [comment]
@kalexand-rh I think different features have different FeatureGate name, for machinehealthcheck it is machine-api. We should point this out to know how to enable machinehealthcheck.
```
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: machine-api
spec:
  featureSet: "TechPreviewNoUpgrade"
```
```
$ oc get featuregate
NAME          AGE
cluster       45h
machine-api   18h
```

**Comment by kalexand-rh** [comment]
https://github.com/openshift/openshift-docs/pull/14293#issuecomment-487084397 makes it sound like all of the tech preview features are supposed to be controlled by the same gate.

@enxebre, @ingvagabund, @rphillips, will you confirm that the machinehealthcheck should be controlled by a separate feature gate than the rest of the TP features?

**Comment by ingvagabund** [comment]
@kalexand-rh to my knowledge, there is only a single feature gate for all the features. So either all the extra features are enabled or all are disabled. Including `machinehealthcheck`.

**Comment by ingvagabund** [comment]
@kalexand-rh at the time of feature gating machinehealthcheck I was not aware all the extra features needs to gated by a specific `cluster` feature gate. Though, based on https://github.com/openshift/openshift-docs/pull/14853#issuecomment-492486276 it looks like there is one.

**Comment by ingvagabund** [comment]
Addressing our case in https://github.com/openshift/machine-api-operator/pull/318 (hoping it will get merged).

**Comment by kalexand-rh** [comment]
Jan's PR got merged, and Zhaohua Sun approved the change on the bug. Merging.

**Pull request merged**
