### PR TITLE
Add cluster and environment details

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit adds information about the cluster and cloud platform
used for testing the performance and scalability of OCP 4.5.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@ahardin-rh @jtaleric @mffiedler PTAL.

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
@chaitanyaenr Looks like this now has conflicts.
@mffiedler PTAL Can you please provide QE review? Thanks!

**Review by mffiedler — APPROVED** [review]

**Comment by ahardin-rh** [comment]
Thank you!

**Pull request merged**
