### PR TITLE
Update with TP snippet

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.12+

Issue:

Link to docs preview: http://file.rdu.redhat.com/jdohmann/ingress-autoscaling-update/networking/ingress-operator.html#nw-autoscaling-ingress-controller_configuring-ingress

QE review:
- [x] QE has approved this change.

Additional information: a follow up to #49786

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
Just a small question, is there a specific section on the Custom Metrics Autoscaler Operator? I see it in the prerequisites. Just wondering if this snippet should go with the section specifically on the Operator (unless this procedure is also part of the TP and there is no overview of the Custom Metrics Autoscaler Operator)?

**Comment by ShudiLi** [comment]
/label qe-approved
@jldohmann done, thanks.

**Comment by jldohmann** [comment]
@opayne1 there is a separate area of the docs that cover the CMA but not the application to Ingress and it also contains the snippet: https://docs.openshift.com/container-platform/4.11/nodes/pods/nodes-pods-autoscaling-custom.html both docs live in separate locations though, and I think without the snippet here there would be customer confusion

**Pull request merged**
