### PR TITLE
TELCODOCS-1852-updates extra field in installConfigOverrides

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-1852]: Doc updates for GitOps ZTP solution maintenance 4.16

Version(s): 4.16 and main

Issue: https://issues.redhat.com/browse/TELCODOCS-1852

Link to docs preview:https://77272--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/ztp-deploying-far-edge-sites#ztp-deploying-a-site_ztp-deploying-far-edge-sites

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by irinamihai** [comment]
LGTM
Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@kquinn1204 I noticed two commits: I was not sure if you MEAN to have two commits. Squash if not, thank you sir.

**Pull request merged**
