### PR TITLE
Update cluster-logging-removing-unused-components-if-no-elasticsearch…

### PR DESCRIPTION
**Pull request by pazpuwi**
….adoc

spec.collection.logs. description: Deprecated. Specification of Log Collection for the cluster See spec.collection

Version(s):

Issue:

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by libander — APPROVED** [review]
/lgtm

**Comment by libander** [comment]
@QiaolingTang / @anpingli / @kabirbhartiRH - QE lgtm please

**Comment by kalexand-rh** [comment]
@kabirbhartiRH, will you please confirm which OCP versions this change is valid in?

**Comment by kalexand-rh** [comment]
@kabirbhartiRH, will you please confirm which OCP versions this change is valid in?

**Comment by kalexand-rh** [comment]
@kabirbhartiRH, will you please confirm which OCP versions this change is valid in?

**Comment by libander** [comment]
> @kabirbhartiRH, will you please confirm which OCP versions this change is valid in?

@kalexand-rh - It'll be OCP 4.11+ as this change is valid across all currently supported versions of logging. 

https://github.com/openshift/cluster-logging-operator/blob/release-5.6/apis/logging/v1/clusterlogging_types_test.go 
https://github.com/openshift/cluster-logging-operator/blob/release-5.7/apis/logging/v1/clusterlogging_types_test.go
https://github.com/openshift/cluster-logging-operator/blob/release-5.8/apis/logging/v1/clusterlogging_types_test.go 

There's the source for each version for this change.

**Comment by anpingli** [comment]
@kalexand-rh  Looks good  to merge 4.11+ and  Logging 5.5+

**Pull request merged**
