### PR TITLE
OCPBUGS-29899: Remove migration to OpenShift SDN

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OCPBUGS-29899

Version(s): 4.15+

Issue:

Link to docs preview: https://72738--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/about-openshift-sdn

This removes the entry from the _topic map:

> Migrating to the OpenShift SDN network plugin
> Rolling back to the OVN-Kubernetes network plugin

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@zhaozhanqi, what do you think? Thanks!

**Comment by zhaozhanqi** [comment]
yes, that make sense if 4.15 is no longer supported to install
cc @weliang1

**Comment by weliang1** [comment]
@jab-rh Do you know why this PR still can not be merged? The https://issues.redhat.com/browse/OCPBUGS-29899 is waiting for the merging.

**Comment by jab-rh** [comment]
@weliang1, sorry, I hadn't realized this was approved, I'll get it merged this week. Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
