### PR TITLE
[OCDOCS-470] dot to slash in CIDR guidance note

### PR DESCRIPTION
**Pull request by maxwelldb**
Correcting a typo. 
https://jira.coreos.com/browse/OSDOCS-470
4.2.

### CODE REVIEW

**Comment by maxwelldb** [comment]
@bergerhoffer @lamek @bobfuru Whenever you have a sec--this needs :+1: / :-1: and merging.

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
