### PR TITLE
layering: Use `rhel-coreos` now

### PR DESCRIPTION
**Pull request by cgwalters**
This changed in https://github.com/openshift/machine-config-operator/pull/3485

### CODE REVIEW

**Comment by mburke5678** [comment]
@cgwalters For 4.12, use `rhel-coreos-8`. For 4.13+, use `rhel-coreos-9`?

**Comment by cgwalters** [comment]
For 4.13+ it's just `rhel-coreos`.  Sorry, I should have linked to https://github.com/openshift/machine-config-operator/pull/3596 instead.

**Comment by mburke5678** [comment]
In that case, I am thinking that the 4.12 docs are correct. Is so, the _In {product-title} 4.12, use `rhel-coreos-8` instead of `rhel-coreos`_ sentence in this PR isn't needed if we apply this PR to 4.13+. Am I mistaken?

**Comment by cgwalters** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/58561

**Pull request closed without merging**
