### PR TITLE
OSDOCS#10568: Deleted "Integrating RAID arrays with LVMS" proc

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.15+

Issue:
[OSDOCS-10568](https://issues.redhat.com/browse/OSDOCS-10568)

Link to docs preview:
[About adding devices to a volume group](https://75965--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html#about-adding-devices-to-a-vg_logical-volume-manager-storage)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@suleymanakbas91 @jakobmoellerdev 
Could you please review this PR?
Thanks!

**Comment by sr1kar99** [comment]
@mmakwana30 
Could you please review this PR?
Thanks!

**Review by jakobmoellerdev — COMMENTED** [review]
/lgtm
Sorry this took so long, lost in the cracks...

**Comment by sr1kar99** [comment]
> /lgtm Sorry this took so long, lost in the cracks...

NP! :) Thanks fore the review.

**Review by gwynnemonahan — COMMENTED** [review]
LGTM.

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
