### PR TITLE
[BZ2060048] Fix ShiftStack machine set CR YAML indentation

### PR DESCRIPTION
**Pull request by maxwelldb**
Resolves [BZ2060048](https://bugzilla.redhat.com/show_bug.cgi?id=2060048)

Preview: https://deploy-preview-43142--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#machineset-yaml-osp_creating-infrastructure-machinesets

### CODE REVIEW

**Comment by gouyang** [comment]
LGTM

**Comment by maxwelldb** [comment]
QE +1ed. Just need version confirmation.

**Comment by nalhadef** [comment]
Hi, Max. There are two commits on this PR. Everything else looks good to me. I'll request a veteran peer reviewer double checks this.

**Pull request merged**
