### PR TITLE
TELCODOCS-1966 - update variables

### PR DESCRIPTION
**Pull request by slovern**
[TELCODOCS-1966](https://issues.redhat.com//browse/TELCODOCS-1966) - update variables - change `4.16` to `4.17`

Version(s): 4.17

Issue: https://issues.redhat.com/browse/TELCODOCS-1966

Link to docs preview:[

- [Installing the Topology Aware Lifecycle Manager by using the web console](https://82358--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/cnf-talm-for-cluster-upgrades.html#installing-topology-aware-lifecycle-manager-using-web-console_cnf-topology-aware-lifecycle-manager)
- [Installing the Topology Aware Lifecycle Manager by using the CLI](https://82358--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/cnf-talm-for-cluster-upgrades.html#installing-topology-aware-lifecycle-manager-using-cli_cnf-topology-aware-lifecycle-manager)[
- [Applying update policies to managed clusters](https://82358--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/cnf-talm-for-cluster-upgrades.html#talo-apply-policies_cnf-topology-aware-lifecycle-manager)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by slovern** [comment]
Thanks for the review @lpettyjo

**Pull request merged**
