### PR TITLE
logging: Add region to LokiStack example secret

### PR DESCRIPTION
**Pull request by xperimental**
Version(s): 4.10+

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

The example secret listed in the "Deploying the LokiStack" section is missing the `region` attribute. I originally thought this was optional, but this does not seem to be the case as people are getting errors when specifying a secret without region.

While looking at that part of the docs I also noticed that it might be better to list the secret using `stringData` instead of `data`, so that the verbatim values are visible instead of the base64-encoded content. This should show an easier way of creating the secret instead of having to manually base64-encode all the values beforehand. Using `stringData` will not change how the secret is saved in Kubernetes.

/cc @libander

### CODE REVIEW

**Review by libander — CHANGES_REQUESTED** [review]
If base encoding isn't necessary, then I don't think these values need callouts, they're rather self explanatory.

**Comment by xperimental** [comment]
I've pushed a new version without callouts.

**Comment by libander** [comment]
@xperimental - If we want to submit this PR for merging, commits have to be squashed.

**Comment by xperimental** [comment]
@libander Done.

**Comment by libander** [comment]
@anpingli / @kabirbhartiRH / @QiaolingTang - LGTM, please.

**Pull request merged**
