### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by mmckinst**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@mmckinst Thanks for reaching out. The xref format looks correct per our [doc guidelines](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-hyperlinks-and-cross-references) for linking to a subtopic within the same topic file. I verified that the links work properly in the OCP 3.5 documentation on https://docs.openshift.com/ and https://access.redhat.com. Did you experience a broken link in another set of our documentation?

**Comment by mmckinst** [comment]
I'm seeing the broken link at https://docs.openshift.org/latest/install_config/install/prerequisites.html . If you click on the "Configuring Docker Storage" link, it tries to send you to the anchor 'configuring-docker-storage' on the same page, but no such anchor exists.

**Comment by ahardin-rh** [comment]
@mmckinst Thanks for clarifying! I took a closer look and somehow the link for the Origin documentation was not updated (following a topic migration), while the link for OCP 3.5 and other versions was updated . Your fix should correct this.

**Comment by ahardin-rh** [comment]
No revision history needed and no labels necessary, as this fix only needs applied to Origin.

**Pull request merged**
