### PR TITLE
OSDOCS#8311: cert-manager minor fixes

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OSDOCS-8311

Link to docs preview: https://72489--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/#cert-manager-operator-supported-versions_cert-manager-operator-about

QE review:
- [x] QE has approved this change. @lunarwhite 
- [x] SME has approved this change. @swghosh

### CODE REVIEW

**Review by lunarwhite — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@snarayan-redhat LGTM

**Pull request merged**
