### PR TITLE
Update the doc to restart the cluster gracefully

### PR DESCRIPTION
**Pull request by ShreyaSharma-shrsharm**
Reorder the steps to restart the cluster gracefully

Version(s):
4.14

Issue:
[OSDOCS-11571](https://issues.redhat.com/browse/OSDOCS-11571)

Link to docs preview:
https://79928--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/graceful-cluster-restart.html

QE review:
- [ ] QE has approved this change.

Additional information:
Opening this PR specifically for version 4.14 since the main [PR](https://github.com/openshift/openshift-docs/pull/79928) got merged for version 4.16+ but 4.12-4.15 doesn't cherry-pick cleanly.

### CODE REVIEW

**Comment by mramendi** [comment]
This PR is empty, please check

**Review by bergerhoffer — COMMENTED** [review]
Hi @ShreyaSharma-shrsharm, this PR isn't quite right. If you're trying to cherry pick the change from #79928 to these other versions, you'll need to submit the changes directly to those version branches, and not to main. (Plus there aren't actually any changes in this PR).

I believe you're trying to do the changes through the UI, which we usually don't like people doing. But for as a simple change as the original PR was, it might be fine. 

But first, this PR doesn't actually have any changes in the "Files changed" tab. And like I mentioned, you'd need to make the changes in the correct version branch.

So for example, if you're trying to make the change to that file on version 4.12, you'd have to go to that file on branch enterprise-4.12, like here: https://github.com/openshift/openshift-docs/blob/enterprise-4.12/modules/graceful-restart.adoc

And submit your exact same change there as a PR. And then repeat for 4.13 on branch enterprise-4.13 (just change the URL above to 4.13).

Can you go ahead and close these 4 PRs and then try again?

If you need any more help, feel free to tag @GroceryBoyJr, @jab-rh, or me. Thanks!

**Comment by ShreyaSharma-shrsharm** [comment]
@bergerhoffer Thanks for the feedback. I'll close the PR.

**Pull request closed without merging**
