### PR TITLE
Setting up redirects to Pipelines and GitOps landing page from OCP 4.14 to latest standalone docs

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
**Version(s):** `main` only

**Issue:**
-  [RHDEVDOCS 5713](https://issues.redhat.com/browse/RHDEVDOCS-5713)

**SME and QE review:** Not applicable

**Additional information:** This PR creates a redirect that should send the user to the 1.10 GitOps standalone doc and 1.12 Pipelines standalone doc when the "About OpenShift GitOps" and "About OpenShift Pipelines" links are clicked in the navigation tree. It does not alter documentation content.

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by Srivaralakshmi** [comment]
@lpettyjo Thanks for the review and approval. Can you please approve the PR from the Review section? Thank you!

**Review by lpettyjo — APPROVED** [review]
LGTM

**Review by bscott-rh — APPROVED** [review]
Merge review LGTM.

**Pull request merged**
