### PR TITLE
OSDOCS-6473 Change images from the 48 to the 413 ones

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-6473

Link to docs preview:

https://61064--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-gcp-marketplace_installing-gcp-customizations

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianli-wei, will you please confirm this change and which versions we should apply it to?

**Comment by jianli-wei** [comment]
> @jianli-wei, will you please confirm this change and which versions we should apply it to?

@kalexand-rh It looks good to me, and it should be applied to 4.13+, per the [comment](https://issues.redhat.com/browse/OCPBUGS-7367?focusedId=22310133&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22310133), thanks!

**Comment by mjpytlak** [comment]
@GroceryBoyJr There is one more reference to market place images that need an update. There is a footnote at the bottom of this topic. https://61064--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-worker_installing-gcp-user-infra

**Comment by GroceryBoyJr** [comment]
Thank you @Mike Pytlak ***@***.***> ! I see it - regarding GCP
Marketplace image. Great catch sir thank you!

**Comment by GroceryBoyJr** [comment]
@mjpytlak ready for you to take a look please.....seeking your LGTM.

**Pull request merged**
