### PR TITLE
[OSDOCS-12933]:Update OSD on GCP docs with Mobb Feedback

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-12933
Link to docs preview:

https://86325--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs.html#ccs-gcp-understand_gcp-ccs

https://86325--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs.html#ccs-gcp-customer-procedure_gcp-ccs

QE review:
- [x] QE has approved this change.

Additional information:

**Removed note that was misleading (and unnecessary) and removed duplicate info within an assembly.**

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM to merge!

**Pull request merged**
