### PR TITLE
OCPBUGS-10984: Document the --skip-pruning oc-mirror flag

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-10984

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:
**This should not be merged to 4.12 until the 4.12 z-stream goes out that it's included with**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sherine-k @lmzuccarelli Please review this one as well. I added the flag to the table and also mentioned how to disable in the section we had describing the pruning behavior.

@zhouying7780 Can you please review as well?

Preview: 
* https://57896--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-updating-registry-about_installing-mirroring-disconnected
* https://57896--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-command-reference_installing-mirroring-disconnected

**Review by sherine-k — APPROVED** [review]
Thanks @bergerhoffer 
This is good.
Thanks!

**Comment by bergerhoffer** [comment]
4.12.11 has shipped. Merging!

**Pull request merged**
