### PR TITLE
Adding info on removing taints and tolerations

### PR DESCRIPTION
**Pull request by mburke5678**
Needing to remove a taint, I had to look online to find out how. The question was raised in multiple forums. Thought we should add the info here, as there appears to be a general need.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning are these the proper ways to remove a taint and a toleration?

**Comment by mburke5678** [comment]
@jhou1 PTAL if this is in your area of responsibility.

**Comment by jhou1** [comment]
@weinliu PTAL

**Comment by mburke5678** [comment]
@weinliu PTAL

**Comment by weinliu** [comment]
@mbkurke5678, sorry for missing this. The content LGTM

**Comment by mburke5678** [comment]
@weinliu Thank you for the review!

**Pull request merged**
