### PR TITLE
RHDEVDOCS-6146: Update Condition management commands section to follow correct style

### PR DESCRIPTION
**Pull request by Maharshi-Project**
Version(s): `pipelines-docs-1.13`, `pipelines-docs-1.14`, `pipelines-docs-1.15`, `pipelines-docs-1.16`

Issue: https://issues.redhat.com/browse/RHDEVDOCS-6146

Link to docs preview: https://84396--ocpdocs-pr.netlify.app/openshift-pipelines/latest/tkn_cli/op-tkn-reference.html

QE review:
- [x] QE has approved this change.

Additional information:
Updated the document according to [RHDEVDOCS-6146](https://issues.redhat.com/browse/RHDEVDOCS-6146)

### CODE REVIEW

**Review by Srivaralakshmi — COMMENTED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
@eromanova97 PTAL

**Comment by Srivaralakshmi** [comment]
@eromanova97 Can you please tag the Pipeline QE person to review this PR and provide the Ack?

**Comment by Srivaralakshmi** [comment]
Hello @ppitonak could you please check and review this PR?
It is a part of a student education project.
Thank you!

**Review by ppitonak — CHANGES_REQUESTED** [review]
Tekton Conditions were removed long time ago, we should remove this doc.

**Comment by eromanova97** [comment]
Hello @ppitonak for which Pipelines versions are they removed?

**Comment by eromanova97** [comment]
Meanwhile, @Maharshi-Project  you can do the following:

* Remove the `op-tkn-condition-management.adoc` file from the `modules` folder.
* Make the following changes in the `tkn_cli/op-tkn-reference.adoc` file:

  Remove the lines 33-34:
  ```
  // Condition management commands
  include::modules/op-tkn-condition-management.adoc[leveloffset=+1]
  ```

**Comment by Maharshi-Project** [comment]
@eromanova97 Done 👍🏻

**Comment by ppitonak** [comment]
@eromanova97 

https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines/1.10/html/about_openshift_pipelines/op-release-notes#breaking-changes-1-9_op-release-notes

> 1.4.2. Breaking changes
> With this update, the Conditions custom resource definition (CRD) type has been removed. As an alternative, use the WhenExpressions instead.

**Comment by Srivaralakshmi** [comment]
@eromanova97 Please confirm that I can CP the changes from `1.9+`. TY!

**Review by lahinson — COMMENTED** [review]
LGTM. Be sure to squash your commits to 1 before you submit this PR for merge review.

**Comment by lahinson** [comment]
Also, it looks like this change might require change management according to the OpenShift docs manual: https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit?tab=t.0#bookmark=id.khm4rxl210qm

**Comment by eromanova97** [comment]
@Srivaralakshmi the supported versions are 1.13+, so please cherry-pick to those :) Thank you!
(Also, I believe this does not need change management since this was indicated in RNs in the past. It would be different if we did not mention it in the RNs, but if we did, there should be no need to go through the process)

**Comment by Srivaralakshmi** [comment]
@Maharshi-Project Please remove [WIP] from the PR title and squash your commits to 1. Thank you!

**Pull request merged**
