### PR TITLE
Add GitOps argocd CLI topic to the CLI tools section

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
**PR for GitOps layered product release. Do not merge until this date: Release date target March 14.**

Jira issue : [RHDEVDOCS-5950](https://issues.redhat.com/browse/RHDEVDOCS-5950)

Aligned team: DevTools 
Cherry-pick to versions: 4.12+

Docs preview: [GitOps CLI for use with Red Hat OpenShift GitOps](https://72735--ocpdocs-pr.netlify.app/openshift-enterprise/latest/cli_reference/gitops-argocd-cli-tools)

**Note to reviewers:** The link to the **Installing the GitOps CLI** section is correct, but will work only when the redirect PR is merged for 1.12 as part of the issue https://issues.redhat.com/browse/RHDEVDOCS-5804 at the time of GA.

SME review: @anandf

QE review: @varshab1210 

Peer review: Michael Burke

Additional information: This PR is related to #72634. Please review and approve them together. TY!

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@anandf and @varshab1210 This PR is related to https://github.com/openshift/openshift-docs/pull/72634. Please review and approve them together. TY!

**Review by anandf — APPROVED** [review]
LGTM

**Comment by varshab1210** [comment]
LGTM

**Comment by Srivaralakshmi** [comment]
NOTE: Requesting merge review only. Do not merge at this time. Release scheduled for March 14.

**Pull request merged**
