### PR TITLE
OCPBUGS#12826: Update the memcached_controller.go file

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-12826

Link to docs preview: https://59347--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-golang-implement-controller_osdk-golang-tutorial

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
This lgtm - formatting seems fine after updating the necessary parts of the file.

**Comment by stevsmit** [comment]
LGTM

**Pull request merged**
