### PR TITLE
OBSDOCS-1164-Logging 5.8.9 Release Notes

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Logging Z-Stream Release Notes - 5.8.9
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-1164

Fix Version: 4.12, 4.13, 4.14, 4.15

Doc Preview: https://78514--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-8-release-notes.html#logging-release-notes-5-8-9_logging-5-8-release-notes

SME Review: @periklis 
QE Review: @anpingli 
Peer Review: @abrennan89 @maxwelldb

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
LGTM

**Comment by xperimental** [comment]
@shreyasiddhartha Can we add a "known issue" for [LOG-5821](https://issues.redhat.com/browse/LOG-5821) to the release notes for 5.8.9 ?

**Comment by shreyasiddhartha** [comment]
> @shreyasiddhartha Can we add a "known issue" for [LOG-5821](https://issues.redhat.com/browse/LOG-5821) to the release notes for 5.8.9 ?

@xperimental As confirmed by @kabirbhartiRH, this issue will now be a part of 5.8.10. I am removing the known issue from 5.8.9.

**Comment by shreyasiddhartha** [comment]
@abrennan89 Can you please complete the peer review for the PR so that I can take it forward for merging? Thank you!

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
