### PR TITLE
OSDOCS-3192: vSphere install requirements (adding to storage content area)

### PR DESCRIPTION
**Pull request by lpettyjo**
4.10+

[OSDOCS-3192](https://issues.redhat.com/browse/OSDOCS-3192): vSphere install requirements (adding to storage content area) 

**Preview**: https://deploy-preview-42648--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html#vsphere-csi-driver-operator-requirements

**PTAL**: @gnufied @duanwei33

### CODE REVIEW

**Comment by gnufied** [comment]
lgtm

**Comment by bscott-rh** [comment]
> @bscott-rh is this duplicate of #42232 ?

This is not a duplicate - this PR references the snippet that I created in https://github.com/openshift/openshift-docs/pull/42232

**Pull request merged**
