### PR TITLE
BZ1799487 - Move OCS to Configuring persistent storage

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1799487](https://bugzilla.redhat.com/show_bug.cgi?id=1799487)
@liangxia PTAL

### CODE REVIEW

**Comment by bobfuru** [comment]
In 4.2+, moving RHOCS from parent-level Storage to "Configuring persistent storage" to be in line with other storage vendors. Includes filename change.
@openshift/team-documentation PTAL

**Comment by mburke5678** [comment]
@bobfuru LGTM. Did you add this to the redirects registry?

**Comment by bobfuru** [comment]
> @bobfuru LGTM. Did you add this to the redirects registry?

Thanks, Michael. Yes, I added it to "Redirects Register for OpenShift Docs."

**Pull request merged**
