### PR TITLE
[enterprise-4.16] CNV#34645: 4.16 RN Shell

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/CNV-34645

Link to docs preview:
https://74096--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-16-release-notes.html

QE review:
NA

Additional information:
* Updated release notes file name and anchor IDs
* Removed *Bug fixes* content
* Removed *Removed features* content

### CODE REVIEW

**Comment by danielclowers** [comment]
@sjhala-ccs @ousleyp Would one of you be able to take a look and see if I did (mostly) everything correctly? This is my first RN shell. I want to make sure that it's close enough for a proper peer review.

**Review by sjhala-ccs — COMMENTED** [review]
Initial review LGTM

**Pull request merged**
