### PR TITLE
Update with TP snippet

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.12

Issue:

Link to docs preview: 
- feature entry: http://file.rdu.redhat.com/jdohmann/ingress-autoscaling-update-RN/release_notes/ocp-4-12-release-notes.html#ocp-4-12-nw-ingress-autoscaling
- TP table: http://file.rdu.redhat.com/jdohmann/ingress-autoscaling-update-RN/release_notes/ocp-4-12-release-notes.html#ocp-4-12-technology-preview

QE review:
- [x] QE has approved this change.

Additional information: an update to #49962

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi could you PTAL for QE ack? This is an update to the RN entry for ingress autoscaling, to denote it as a TP feature. Thank you!

**Review by kelbrown20 — COMMENTED** [review]
Great work Jesse! 
/lgtm

**Comment by ShudiLi** [comment]
/label qe-approved
@jldohmann done, thanks.

**Pull request merged**
