### PR TITLE
[OSDOCS-7743]: ROSA Operator, Invalid IAM Policy

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-7743
Link to docs preview:

https://69773--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_backing_up_and_restoring_applications/backing-up-applications#oadp-preparing-aws-credentials_rosa-backing-up-applications
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 ,  when you get a moment could you please provide a QE review for this PR? Thank you!

**Comment by mletalie** [comment]
Hello @yuwang-RH  , when you get a moment could you please provide a QE review for this PR? Thank you!

**Comment by bscott-rh** [comment]
LGTM.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
LGTM, thanks for the handy screenshot of the change :sweat_smile: Merges are currently frozen, but this good to go when that's lifted.

/remove-label merge-review-in-progress
/remove-label merge-review-needed
/label ok-to-merge

**Pull request merged**
