### PR TITLE
Adds a few KCS links to migration and SDN dep docs

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OCPBUGS-41378

Link to docs preview:
https://81487--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/about-networking

https://81487--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn#best-practices-migrating-ovn-kubernetes-network-provider_migrate-from-openshift-sdn

https://81487--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn#best-practices-live-migrating-ovn-kubernetes-network-provider_migrate-from-openshift-sdn

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by CFields651** [comment]
3/3!  LGTM!

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by zhaozhanqi** [comment]
LGTM

**Pull request merged**
