### PR TITLE
Correcting location of Quota and Limit Ranges details

### PR DESCRIPTION
**Pull request by rhamilto**
Quota and Limit Ranges are now listed on the Quota page, so I'm updating the references to them.

@ahardin-rh, PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rhamilto Thanks! LGTM. This change is coming in 3.6, correct?

**Comment by rhamilto** [comment]
> This change is coming in 3.6, correct?

No, the change happened earlier.

**Comment by ahardin-rh** [comment]
@rhamilto Okay, thanks. I corrected the labels on this PR so that the edits are applied to 3.5 docs, but if it needs to be applied to 3.4 or earlier, please let me know.

**Comment by rhamilto** [comment]
> but if it needs to be applied to 3.4 or earlier, please let me know.

Gosh.  This goes all the way back to 3.3.  Hard to believe it's been that long...

**Comment by ahardin-rh** [comment]
Thanks! Updated. Yeah, time flies! :astonished:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/limits.adoc#admin-guide-limits[Setting Limit Ranges]
|Updated the references to quota and limit ranges, as they are now listed on the Quota page.
%
|xref:../admin_guide/quota.adoc#admin-guide-quota[Setting Quotas]
|Updated the references to quota and limit ranges, as they are now listed on the Quota page.
%

**Pull request merged**
