### PR TITLE
JIRA OSDOCS-1961 Added conceptual info for cluster autoscaling

### PR DESCRIPTION
**Pull request by jonquilwilliams**
JIRA: https://issues.redhat.com/browse/OSDOCS-1961

### CODE REVIEW

**Comment by jonquilwilliams** [comment]
**Preview is here:** https://deploy-preview-30690--osdocs.netlify.app/openshift-rosa/latest/nodes/nodes/rosa-enabling-autoscaling-nodes.html#rosa-enabling-autoscaling_rosa-enabling-autoscaling-nodes

Please merge to dedicated-4 branch when ready.

**Comment by bmcelvee** [comment]
Hey @jonquilwilliams! Has this PR gone through QE and SME review? And if not, does it? It looks like it is a direct port of existing content from OCP. If that's the case maybe we could link to the PR where it was reviewed previously.

**Comment by jonquilwilliams** [comment]
@bmcelvee QE review was requested but not completed yet. It is indeed a direct port of the OCP content, and requested by a SME because only these two paragraphs are applicable to ROSA. So I don;t need an additional SME review. I didn't know we could link it to an earlier PR. How would I find that PR? Thank you so much :)

**Comment by bmcelvee** [comment]
> @bmcelvee QE review was requested but not completed yet. It is indeed a direct port of the OCP content, and requested by a SME because only these two paragraphs are applicable to ROSA. So I don;t need an additional SME review. I didn't know we could link it to an earlier PR. How would I find that PR? Thank you so much :)

I'm not sure if it's standard practice, but it helps draw a thread between the content sources. I usually go to the original file on GitHub, then parse through the *Blame* tab. For this one, the OCP content was added in: https://github.com/openshift/openshift-docs/pull/13610.

**Comment by jonquilwilliams** [comment]
@vikram-redhat Since this content is a direct copy/paste from OCP - but just limited to the two paragraphs that apply to ROSA per a SME (Oren K) - can we go head and merge this without a QE rveiew? Brandi is suggesting that it might be ok to link this PR to the previous PR where it was reviewed (https://github.com/openshift/openshift-docs/pull/13610). Please advise. Thanks!

**Comment by vikram-redhat** [comment]
@jonquilwilliams yes works for me. You have already added a link so we are all good.

**Pull request merged**
