### PR TITLE
Update the outputs for oc get svc -n <myproject>

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/16893

### CODE REVIEW

**Comment by mburke5678** [comment]
@lihongan Please take a look. 
I think the tech writer who worked on this PR copied an example you provided when she should not have. 
https://github.com/openshift/openshift-docs/pull/14618#discussion_r306700764

**Comment by lihongan** [comment]
LGTM.  
Yes, that is just an example in #14618 (comment) and show the column `TYPE` is required.
Anyway, thank you @mburke5678

**Pull request merged**
