### PR TITLE
OSDOCS-6191-2 adding Israel Central to azure regions

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-6191

Link to docs preview:
https://66986--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account#installation-azure-regions_installing-azure-account

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jinyunma Here's the israel central azure region PR. Thank you

**Comment by skopacz1** [comment]
Preview: https://66986--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account#installation-azure-marketplace_installing-azure-account:~:text=israelcentral%20(Israel%20Central)

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by jinyunma** [comment]
@bscott-rh thanks for addressing this.
LGTM

**Pull request merged**
