### PR TITLE
Improve deployment hook docs

### PR DESCRIPTION
**Pull request by ironcladlou**

### CODE REVIEW

**Comment by thoraxe** [comment]
Better! I think there might still need to be some clarification (eg: if you had multiple containers in your pod template, you could execute hooks related to ... all? any?)

**Comment by adellape** [comment]
@ironcladlou Did you have anything more for this PR or should I merge?

**Comment by ironcladlou** [comment]
@adellape Let's merge this one and I'll try and provide followups.

**Pull request merged**
