### PR TITLE
BZ:1877387: Incorrect command for deleting a baremetal node in the docs

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1877387

This change is for 4.8 only. The text was added to 4.8 only in https://github.com/openshift/openshift-docs/pull/30696.

### CODE REVIEW

**Comment by mburke5678** [comment]
@ousleyp FYI

**Comment by ousleyp** [comment]
Thank you for fixing this!

**Comment by mburke5678** [comment]
@sunilcio Can you PTAL at this very small change? Thank you!

**Comment by sunilcio** [comment]
lgtm, thanks!

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
