### PR TITLE
BZ1999000: Adds build configs and secrets objects maximum values

### PR DESCRIPTION
**Pull request by darshan-nagaraj**
Adds 4K cluster-density * 10 = 40,000 secrets per iteration and 4K cluster-density * 3 = 12,000 build Configs. 
Reference doc: https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/kube-burner#cluster-density-variables

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1999000

OCP version: 4.6+

Direct Doc Preview Link: https://deploy-preview-40908--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums-major-releases_object-limits

### CODE REVIEW

**Comment by peterducai** [comment]
LGTM

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Comment by mffiedler** [comment]
@mohit-sheth @paigerube14 If you have any comments.

**Comment by mohit-sheth** [comment]
LGTM

**Review by paigerube14 — APPROVED** [review]
LGTM

**Pull request merged**
