### PR TITLE
removing AWS and GCP example from ARO documentation

### PR DESCRIPTION
**Pull request by gburges**

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
@gburges, please revert your change to line 36 and squash.

**Comment by kalexand-rh** [comment]
@vikram-redhat, given the upcoming repo changes, is this PR still relevant?

**Comment by vikram-redhat** [comment]
@kalexand-rh for the moment yes.

**Comment by kalexand-rh** [comment]
@vikram-redhat, @gburges  it looks like the original intent was to put just the Azure yaml in the `openshift-aro` distro. This file has changed quite a bit, but I think that this preserves the original intent. Will you PTAL?

**Comment by vikram-redhat** [comment]
This is fine by me, but @gburges should confirm.

**Comment by kalexand-rh** [comment]
@gburges, please confirm that this change is ready to merge.

**Comment by gburges** [comment]
Hi, asked around in the Azure team, and they told me it's moot now, so i'll close it

**Pull request closed without merging**
