### PR TITLE
Bug#1520744 - Added an instruction to set content type

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1520744

- Fixed the typo by removing extra backtick.
- Added instruction to set content type to `application/json`.

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@lucascosti PTAL

**Comment by lucascosti** [comment]
@gaurav-nelson this looks ok, but @bfallonf initially had a look at this issue and found there was already another procedure elsewhere in the docs that covered this use case adequately. Perhaps we could single-source this content with the other procedure so future updates will be easier?

@bfallonf Could you point Gaurav to where the other content is located?

**Comment by bfallonf** [comment]
@lucascosti @gaurav-nelson I think what Lucas is referring to is in the Online, Getting Started docs:

https://docs.openshift.com/online/getting_started/basic_walkthrough.html#bw-configuring-automated-builds

It's just one step in a different doc. It might be a little too fiddly and tricky to single-source. I think what Gaurav has here is fine.

**Comment by lucascosti** [comment]
okie dokies, fine with me!

**Comment by gaurav-nelson** [comment]
minor changes no revision history required.

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :boat:

**Pull request merged**
