### PR TITLE
Changed all instances of emptydir and EmptyDir to emptyDir

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Kubernetes uses the term `emptyDir`

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
no revision history needed.

**Comment by gaurav-nelson** [comment]
@mburke5678 @openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
LGTM 👍

**Comment by vikram-redhat** [comment]
@gaurav-nelson - hey Gaurav - the cherry pick for 3.4 introduced a table which was not there before. Can you please check how that happened as this PR was only changing emptyDir variables.

**Comment by vikram-redhat** [comment]
@gaurav-nelson fixed via: https://github.com/openshift/openshift-docs/pull/6134/files. Let us know if not correct.

**Comment by gaurav-nelson** [comment]
Thank you @vikram-redhat for fixing it. These additions were part of resolving merge conflicts and making sure that `install_config/cluster_metrics.adoc` is same as master `install_config/cluster_metrics.adoc`.

I now know what the problem was, thank you again for fixing this.

**Pull request merged**
