### PR TITLE
OCPBUGS-19881: adds prerequisites for RHEL 8 ovnkube-trace tool

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OCPBUGS-19881

Link to docs preview:
https://66120--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/ovn-kubernetes-tracing-using-ovntrace

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by qiowang721** [comment]
Hi @JoeAldinger , thanks for helping this.
Seems {op-base-system-full} is not translated correctly in the docs preview, could you please check?
And if it is better to move this note to step2 of installation procedure? As it is more likely a step but not a prerequest.

**Comment by bscott-rh** [comment]
Peer review LGTM.

**Pull request merged**
