### PR TITLE
[DO NOT MERGE] Bug 1262176: difference between AEP and OSE

### PR DESCRIPTION
**Pull request by bfallonf**
@vikram-redhat @CowboysFan as discussed. If this is not what you had imagined, please make comments.

Also, the placement might not be the best. Taking suggestions for that too.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bfallonf  - thanks. This is a good start. But it is missing comparison with Atomic Host. We need that as well, or do you think that adding that would confuse people more?

**Comment by adellape** [comment]
I know the doc in the BZ only says "Atomic Enterprise", but AFAIK it should be "Atomic Enterprise Platform" everywhere.

**Comment by bfallonf** [comment]
@vikram-redhat As discussed, I included a note about not confusing Atomic Enterprise Platform with Atomic Host. 

@adellape Fix as per your comment above. I'll also email around and see if this info is right for the docs, as per your comment in the BZ.

**Comment by vikram-redhat** [comment]
@adellape - nice catch. Yes, the official name is Atomic Enterprise Platform.

**Comment by bfallonf** [comment]
Decided not to go forward with this for now. At least until there's more info and it's closer to the AEP release.

**Comment by adellape** [comment]
@bfallonf Gonna close this for now, can revisit later if needed.

**Pull request closed without merging**
