### PR TITLE
SRVOCF-360: Updated curl command to kn

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVOCF-360

Direct preview link: https://deploy-preview-38560--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-reference-guide#serverless-nodejs-context-object-reference-log_serverless-functions-reference-guide

Applies for OCP 4.6+

### CODE REVIEW

**Review by lance — COMMENTED** [review]
This looks fine, but I think several of the other `curl` commands in this document should be changed as well. Specifically...

* Line 84 should be `kn func emit -d '{"Hello": "world"}'`
* Line 111 should be `kn func emit`

I wonder, in general about having `http://example.com` as the endpoint for all of these. The `emit` command will take a `--sink=http://example.com` parameter, but it will also automatically send the request to the deployed function if `--sink` is omitted.

**Comment by abrennan89** [comment]
@lance thanks for the review!
I updated the additional lines, but I think re "having http://example.com as the endpoint" is out of scope for https://issues.redhat.com/browse/SRVOCF-360
Can you raise another issue for this please if it needs to be updated across the docs? I'd imagine there are quite a few instances of it for all the different func docs.

**Review by lance — APPROVED** [review]

**Comment by jrangelramos** [comment]
QE Approved

**Review by skrthomas — COMMENTED** [review]
LGTM

**Pull request merged**
