### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Review by pwright — COMMENTED** [review]
This whole module could do with some love, eg edit for passive voice, but here's a simple typo fix

**Comment by kalexand-rh** [comment]
Hi @pwright! Thank you for submitting this PR. You've found a module that was part of the mass port of 3.x content into the 4.x stream, so I am not surprised that it could use some editorial love. We do not currently have the bandwidth to edit published content, but you are welcome to submit another pull request with suggestions.

**Pull request merged**
