### PR TITLE
Removing docs for TP feature Prometheus Adapter

### PR DESCRIPTION
**Pull request by jeana-redhat**
We were asked to remove the item *HPA custom metrics adapter based on Prometheus* from the Tech Preview/GA table in the 4.8 Rel Notes, and to remove this related assembly as part of that effort.

Table update is in #34286

Preview:
- Removed link from [Next Steps](https://deploy-preview-34290--osdocs.netlify.app/openshift-enterprise/latest/monitoring/accessing-third-party-uis.html) here, and you can also see its removal from the **Monitoring** book TOC from this page.

### CODE REVIEW

**Review by ousleyp — APPROVED** [review]

**Comment by gauravsingh85** [comment]
We also want to remove pages in opemshift related to this topic  in 4.8  https://docs.openshift.com/container-platform/4.7/monitoring/exposing-custom-application-metrics-for-autoscaling.html

**Comment by jeana-redhat** [comment]
> We also want to remove pages in opemshift related to this topic in 4.8 https://docs.openshift.com/container-platform/4.7/monitoring/exposing-custom-application-metrics-for-autoscaling.html

Yes, see the last changed (removed) file in the Changed files tab: https://github.com/openshift/openshift-docs/pull/34290/files#diff-dcbf1d59d4cfa1dcb4a6b0996525958d217e7fc599cd1175cfc94aae4732c248

To confirm, if you look at the place where that page would be in the preview rendering, it is Not Found: https://deploy-preview-34290--osdocs.netlify.app/openshift-enterprise/latest/monitoring/exposing-custom-application-metrics-for-autoscaling.html

If this looks good, let me know!

**Comment by jeana-redhat** [comment]
Confirmed this is ready with Gaurav on Slack :+1:

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by gauravsingh85** [comment]
Thank you all for tour help

**Pull request merged**
