### PR TITLE
BZ2032500: Add link to IBM CEX plug-in

### PR DESCRIPTION
**Pull request by SNiemann15**
-OCP version for cherry-picking: enterprise-4.9, 4.10

- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2032500

- Preview https://deploy-preview-39885--osdocs.netlify.app/openshift-enterprise/latest/nodes/pods/nodes-pods-plugins.html

- QE review: Holger Wolf

### CODE REVIEW

**Comment by yselkowitz** [comment]
/retitle Bug 2032500: Add link to IBM CEX plug-in

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Pull request merged**
