### PR TITLE
Update link checker

### PR DESCRIPTION
**Pull request by aireilly**
Update the link checker to only check links that are present in modified lines in the PR.

Example error log:
https://app.travis-ci.com/github/openshift/openshift-docs/builds/268124484

Related: https://github.com/openshift/release/pull/46934

### CODE REVIEW

**Review by rohennes — COMMENTED** [review]
@aireilly - this is a great improvement. Only checking the changed lines reduces the execution time from 30 seconds to just 2 or 3 seconds. And it's functionally the same. Super!

This is the output I see in a test [build log](https://app.travis-ci.com/github/openshift/openshift-docs/builds/268116655):

````
$ ./scripts/check-RN-link-perms.sh || travis_terminate 1
ERROR: release_notes/ocp-4-13-release-notes.adoc:15
release_notes/ocp-4-13-release-notes.adoc:23
release_notes/ocp-4-13-release-notes.adoc:2856 Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/RHELPLAN-145492)

ERROR: release_notes/ocp-4-13-release-notes.adoc:15
release_notes/ocp-4-13-release-notes.adoc:23
release_notes/ocp-4-13-release-notes.adoc:2856 Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/RHELPLAN-145492)

ERROR: release_notes/ocp-4-13-release-notes.adoc:24
release_notes/ocp-4-13-release-notes.adoc:2098 Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/OCPBUGS-11813)

ERROR: release_notes/ocp-4-13-release-notes.adoc:31
release_notes/ocp-4-13-release-notes.adoc:2889 Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/OCPBUGS-4388)
````

My only quibble would perhaps be to making the error output a bit clearer? 

For example cut `release_notes/ocp-4-13-release-notes.adoc:2889` from the output? WDYT? No biggie really though.
````
ERROR: release_notes/ocp-4-13-release-notes.adoc:31
Do not include links to JIRA issues that require a login (https://issues.redhat.com/browse/OCPBUGS-4388)
````

Otherwise, thanks again this is great!

**Comment by aireilly** [comment]
@rohennes updated. This should work now. Adding a new commit here with errors.

**Comment by aireilly** [comment]
https://app.travis-ci.com/github/openshift/openshift-docs/builds/268120726

**Comment by aireilly** [comment]
See https://app.travis-ci.com/github/openshift/openshift-docs/builds/268124484

**Review by rohennes — APPROVED** [review]
LGTM. Thanks again Aidan!

**Pull request merged**
