### PR TITLE
OADP-2684: Document supported architecture to include arm64 support

### PR DESCRIPTION
**Pull request by anarnold97**
[OADP-2684](https://issues.redhat.com/browse/OADP-2684)

Version(s):

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14

Issue:

## Link to docs preview:

[OADP supported architecture](https://65620--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-features-plugins#oadp-supported-architecture_oadp-features-plugins)

QE review:
- [ X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by amastbau** [comment]
LGTM
doc now includes all 4 supported arc including arm64.

* AMD64
* arm64
* PPC64le
* s390x

**Review by xenolinux — COMMENTED** [review]
I left a few suggestions but otherwise looks good!

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead before implementing any feedback. Thanks!

**Comment by anarnold97** [comment]
@xenolinux - thanks for a good review: some good suggestions and some good correction spots. I always thought ARM was lowercase

**Comment by jeana-redhat** [comment]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
