### PR TITLE
[GH69134] - Corrected policy for user level permissions

### PR DESCRIPTION
**Pull request by sabre1041**
Version(s):
All versions with OpenShift GitOps

Issue:
#69134

Additional information:
Corrected user policy for OpenShift GitOps

### CODE REVIEW

**Comment by sabre1041** [comment]
@openshift/team-documentation

**Comment by Srivaralakshmi** [comment]
Sure @kalexand-rh. 

@varshab1210 PTAL at this change and provide feedback. Thank you!

**Review by iam-veeramalla — APPROVED** [review]
lgtm

**Comment by varshab1210** [comment]
LGTM, thanks

**Comment by ShaunaDiaz** [comment]
@sabre1041 Please provide a link to live docs so we can check versions. Having a hard time finding this module in the [docs](https://docs.openshift.com/container-platform/4.15/welcome/index.html).

**Comment by ShaunaDiaz** [comment]
@sabre1041 Please also rebase and force push this branch to remove the Travis check and get on the correct CI.

**Comment by sabre1041** [comment]
@ShaunaDiaz done!

**Comment by sabre1041** [comment]
> @sabre1041 Please find the preview of this change [here ](https://69135--ocpdocs-pr.netlify.app/), then add the link to a comment. Also list the versions to which this change should apply. TY!

This correction is applicable to all versions of OpenShift where OpenShift GitOps has been supported. This has been the functionality that has always been employed in Argo CD

**Comment by ShaunaDiaz** [comment]
> > @sabre1041 Please find the preview of this change [here ](https://69135--ocpdocs-pr.netlify.app/), then add the link to a comment. Also list the versions to which this change should apply. TY!
> 
> This correction is applicable to all versions of OpenShift where OpenShift GitOps has been supported. This has been the functionality that has always been employed in Argo CD

@sabre1041  Supportability versions aren't something for the docs teams to figure out, it needs to come from a SME (which I think is you in this case?). Do you know which version of OCP started supporting GitOps as GA?

**Comment by sabre1041** [comment]
> > > @sabre1041 Please find the preview of this change [here ](https://69135--ocpdocs-pr.netlify.app/), then add the link to a comment. Also list the versions to which this change should apply. TY!
> > 
> > 
> > This correction is applicable to all versions of OpenShift where OpenShift GitOps has been supported. This has been the functionality that has always been employed in Argo CD
> 
> @sabre1041 Supportability versions aren't something for the docs teams to figure out, it needs to come from a SME (which I think is you in this case?). Do you know which version of OCP started supporting GitOps as GA?

OpenShift GitOps GA support was added in 4.7

**Comment by ShaunaDiaz** [comment]
Attached issue has been closed. Fixed in https://github.com/openshift/openshift-docs/pull/74766/files#diff-83ea7b72174e88b4873f54606e3d1eee2965649a94fd820243539e21f0387353R31 in https://github.com/openshift/openshift-docs/pull/74766

**Pull request closed without merging**
