### PR TITLE
TELCODOCS-1683-image adding images

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-1683]: QinQ support in SR-IOV Network Operator (GA)

Version(s): 4.16 and main

Issue: https://issues.redhat.com/browse/TELCODOCS-1683
https://issues.redhat.com/browse/DXD-693

Link to docs preview: https://77081--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/hardware_networks/configuring-sriov-qinq-support.html

QE review:
- [x] QE has approved this change.

Additional information: Simple image update. Working on separate PR for some text.

### CODE REVIEW

**Comment by kquinn1204** [comment]
@mlguerrero12 Can you add a LGTM on this please and I can then revisit with description in a separate PR

**Comment by mlguerrero12** [comment]
@kquinn1204, why are there 3 diagrams? We only need one, right?

**Comment by kquinn1204** [comment]
@mlguerrero12 I just removed those extra ones, my mistake.

**Comment by mlguerrero12** [comment]
we should also delete the text. We can add it in another pr as you said

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM. Not something I'd stop the merge review over, but I'd recommend some sort of introduction or title (which I'm aware you said you're going to do in a separate PR), and also perhaps some more descriptive alt text for accessibility reasons.

**Pull request merged**
