### PR TITLE
OSDOCS-11223: Scalability and Performance Table for 4.17 Release Notes

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.17

Issue: https://issues.redhat.com/browse/OSDOCS-11223

Link to docs preview: https://82409--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html

QE review:
- [ ] QE has approved this change.

Additional information:
image

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@liqcui seeking your QE for this release table, please.

**Review by chentex — APPROVED** [review]
/lgtm

**Comment by GroceryBoyJr** [comment]
Removed the table for driver enablement - there are no tech preview features for the 4.17 release from driver enablement.

**Review by xenolinux — COMMENTED** [review]
LGTM!

**Comment by rioliu-rh** [comment]
@sergiordlr can you help to review section `Pinned Image Sets` ,thanks

**Review by mffiedler — APPROVED** [review]
LGTM

**Review by ffromani — COMMENTED** [review]
no changes about `Hyperthreading-aware CPU manager policy` from 4.16 to 4.17, correct.
I mistakely provided wrong information earlier, this version (no changes) is indeed correct.
LGTM

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM; merging.

**Pull request merged**
