### PR TITLE
[RHACS] Update to 3.71 Release Notes 

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- `rhacs-docs`
- `rhacs-docs-3.71`

Labels:

`RHACS`

Issue: none - see PR https://github.com/stackrox/stackrox/pull/2849 and [slack thread](https://srox.slack.com/archives/CGDK78KRV/p1661811353421829)

[Link to docs preview](https://openshift-docs-4mfwn7h4p-kcarmichael08.vercel.app/openshift-acs/master/release_notes/371-release-notes.html)

### CODE REVIEW

**Review by md2119 — APPROVED** [review]
Comment on target release, else everything lg

**Review by kelbrown20 — COMMENTED** [review]
Looks great! 
/lgtm

**Pull request merged**
