### PR TITLE
[enterprise-3.6] Logging and metrics version example uses v3.6 in 3.7 doc 

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1527274

### CODE REVIEW

**Comment by mburke5678** [comment]
Related to https://github.com/openshift/openshift-docs/pull/10196

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by nekop** [comment]
All changes are inside `ifdef::openshift-origin` so I don't think this is needed for enterprise branch.

**Comment by mburke5678** [comment]
@nekop There is one change in Enterprise: _The prefix for the component images. With `openshift3/ose-metrics-cassandra:v3.6.173.0.21`, set prefix `openshift/ose-`_

**Comment by anpingli** [comment]
Must we use the  prefix openshift/ose-? Why not use openshift/?  sometimes,  the image may be be tagged with the prefix ose- .

**Comment by anpingli** [comment]
@jcantril@redhat.com, I don't know how the origin images are managed. Could you review the document?

**Pull request merged**
