### PR TITLE
Bug 1483678, Added steps for Containerized etcd Deployments

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1483678

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rjhowe PTAL

**Comment by ahardin-rh** [comment]
@rjhowe bump

**Comment by ahardin-rh** [comment]
Verified by Ryan in the BZ and also verified by QE. 

@openshift/team-documentation Please peer review.

**Review by adellape — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../ admin_guide/backup_restore.adoc#admin-guide-backup-and-restore[Backup and Restore]
|Added a new xref:../ admin_guide/backup_restore.adoc#backup-containerized-etcd-deployments[Containerized etcd Deployments] section.
%

**Pull request merged**
