### PR TITLE
Release Notes for BYO RHEL 7, UBI8, and others

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@crawford PTAL. Thanks!

**Comment by codyhoag** [comment]
@miabbott do you mind giving this a review (or suggesting someone)? I pieced some of this together from multiple places, so I'd like a sanity check to make sure it all makes sense. Thanks!

**Comment by miabbott** [comment]
Looks sane to me, but I'm going to ask @sdodson @crawford for a glance

**Comment by sdodson** [comment]
/lgtm
Hooray on RHEL7 worker deprecation!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
