### PR TITLE
The new-app command creates a Deployment object, not a DeploymentConf…

### LINKED ISSUE #36055: [enterprise-4.8] Issue in file applications/application_life_cycle_management/creating-applications-using-cli.adoc
### Which section(s) is the issue in?
Create and application from source code - https://docs.openshift.com/container-platform/4.8/applications/application_life_cycle_management/creating-applications-using-cli.html#applications-create-using-cli-source-code_creating-applications-using-cli

### What needs fixing?
The text currently states that "The new-app command typically also creates a DeploymentConfig object to deploy...", though it actually creates a "Deployment" object and you need a flag in oc `--as-deployment-config=true` to force a deploymentconfig.  So correct it to state that it created a deployment object instead.

### PR DESCRIPTION
**Pull request by stevsmit**
For 4.6+

Fixes https://github.com/openshift/openshift-docs/issues/36055

QE approved. 

Preview: https://deploy-preview-36522--osdocs.netlify.app/openshift-enterprise/latest/applications/creating_applications/creating-applications-using-cli.html#applications-create-using-cli-source-code_creating-applications-using-cli

### CODE REVIEW

**Comment by stevsmit** [comment]
@wewang58 Please review this minor change. Thank you!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
