### PR TITLE
Fix v1.Probe

### PR DESCRIPTION
**Pull request by vbehar**
based on godoc from https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L851
and defaults from https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L135

### CODE REVIEW

**Comment by vbehar** [comment]
Hi,

can someone please merge this one ?

Thanks

**Comment by tnguyen-rh** [comment]
Does this conflict with https://github.com/openshift/openshift-docs/pull/1819 ?

**Comment by adellape** [comment]
@vbehar @tnguyen-rh I just merged https://github.com/openshift/openshift-docs/pull/1819 and am currently going through to re-apply any manual fixes we had come across in the last few months in those API docs. I'll verify whether this PR is now satisfied w/ the latest update.

**Comment by adellape** [comment]
@vbehar It looks like this has mostly been taken care of by https://github.com/openshift/openshift-docs/pull/1819, which updates the API docs to Origin v1.2.0. E.g.:

https://github.com/openshift/openshift-docs/blame/master/rest_api/kubernetes_v1.adoc#L11047-L11061

The new fields have been added, and some of the wording has been updated to match your changes, but there are still some slight differences. Let us know if you think they should still be updated further.

I've also evaluated and (where still relevant) re-applied any manual tweaks we had made since the last doc regeneration (cc @tnguyen-rh), which hadn't been since Origin v1.0.7: https://github.com/openshift/openshift-docs/pull/1835

**Comment by vbehar** [comment]
ok thanks, I'll close this one.

**Pull request closed without merging**
