### PR TITLE
OSDOCS-4792: Bump to Nutanix AOS version

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.12+

Issue:
This PR addresses [osdocs-4792](https://issues.redhat.com/browse/OSDOCS-4792)

Link to docs preview:

[Preparing to install on Nutanix](https://54593--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/preparing-to-install-on-nutanix.html)

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@sgaoshang Ready for QE review. PTAL.

**Review by vnephologist — APPROVED** [review]
lgtm

**Pull request merged**
