### PR TITLE
Fix mismatched chrony config info - BZ1881827

### PR DESCRIPTION
**Pull request by maxwelldb**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1881827

### CODE REVIEW

**Comment by gpei** [comment]
LGTM, thanks for the update!

**Comment by maxwelldb** [comment]
Thanks!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

@maxwelldb Don't forget that 4.3 is EOL, so you should remove that label.

**Pull request merged**
