### PR TITLE
remove vm templates section

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.14

Issue: None

Link to docs preview:
- "Virtual machine templates" folder and many assemblies removed because they duplicate content in VM folder.
- [Managing automatic boot source updates](https://63579--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-automatic-bootsource-updates) - assembly moved
- [Creating custom boot sources](https://63579--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-creating-and-using-boot-sources) - assembly moved and renamed

QE review:
- [ ] QE has approved this change.

Additional information: Moving templates out of the top level navigation because it is no longer a major use case. The assemblies for creating and managing boot sources have been moved to the VM folder.

### CODE REVIEW

**Comment by apinnick** [comment]
@dominikholler Could you please review?

**Comment by dominikholler** [comment]
@apinnick in the preview it looks like the "Managing automatic boot source updates" and the "Creating custom boot sources" are very prominent in the VM section.  This feels like these two topics are something a user should know very in the beginning, even before connecting to a VM. While this is true from a chronological view of a single VM, I would see those two topics more in the bottom.

**Comment by apinnick** [comment]
@dominikholler This folder will likely be only a temporary home. When I get further along in the "Storage" PR, I will find a better place to put the assemblies. In the meantime, I will move them to a less prominent place. Thanks.

**Review by skrthomas — COMMENTED** [review]
Reorganization looks thorough and checks out in preview. Good work :)

**Pull request merged**
