### PR TITLE
OBSDOCS-804: Update description for LokiStack tenant field

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OBSDOCS-804

Link to docs preview:
- https://73739--ocpdocs-pr.netlify.app/openshift-enterprise/latest/logging/log_storage/installing-log-storage#create-lokistack-cr-console_installing-log-storage
- https://73739--ocpdocs-pr.netlify.app/openshift-enterprise/latest/logging/log_storage/installing-log-storage#create-lokistack-cr-cli_installing-log-storage

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by r2d2rnd** [comment]
It looks good to me. Many thanks for the effort

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
