### PR TITLE
Removing extra full stop from optimizing storage assembly

### PR DESCRIPTION
**Pull request by pneedle-rh**
This applies to master, enterprise-4.6, enterprise 4.7 and enterprise-4.8.

The preview content is [here](https://deploy-preview-32257--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/optimizing-storage.html#recommended-configurable-storage-technology_persistent-storage).

### CODE REVIEW

**Comment by pneedle-rh** [comment]
@openshift/team-documentation for peer review please. Thanks!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
