### PR TITLE
OCPBUGS#9156: Change in  note for egress network policies

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.9

Issue: https://issues.redhat.com/browse/OCPBUGS-9156

Link to docs preview: [file.rdu.redhat.com/sdudhgao/9156/networking/network_policy/about-network-policy.html](http://file.rdu.redhat.com/sdudhgao/9156/networking/network_policy/about-network-policy.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
LGTM!

**Review by skrthomas — COMMENTED** [review]
Merge review lgtm

**Pull request merged**
