### PR TITLE
[OCPBUGS-30024] 4.14 RNs - Change SBO and NOO support for IBM Z and IBM Power

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14

Issue: Requires CM
- https://issues.redhat.com/browse/OCPBUGS-30024

Link to docs preview:
- [Deprecated and removed features](https://72995--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-deprecated-removed-features)
- [IBM Power/IBM Z section](https://72995--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-ibm-z)
- 
QE review:
- [x] QE has approved this change.

Additional information:
Related PRs: 
- PR for 4.15 RNs https://github.com/openshift/openshift-docs/pull/72919
- PR for 4.13 RNs https://github.com/openshift/openshift-docs/pull/72996

### CODE REVIEW

**Comment by holgwolf** [comment]
LGTM

**Comment by manojnkumar** [comment]
LGTM

**Review by sadlerap — APPROVED** [review]

**Comment by SNiemann15** [comment]
PTAL: @sferich888, @davemulford, @xltian, @kalexand-rh, @sjstout

**Comment by xltian** [comment]
LGTM

**Comment by kalexand-rh** [comment]
LGTM

**Comment by sferich888** [comment]
Based on what I read in this doc: https://docs.openshift.com/container-platform/4.13/applications/connecting_applications_to_services/sbo-release-notes.html updates need to be made to this table as well (depreciated means still supported; just not removed).

**Comment by SNiemann15** [comment]
> Based on what I read in this doc: https://docs.openshift.com/container-platform/4.13/applications/connecting_applications_to_services/sbo-release-notes.html updates need to be made to this table as well (depreciated means still supported; just not removed).

@Srivaralakshmi @sadlerap That's not in the scope of my OCP Release Notes PRs can you please work on changing the SBO support matrix accordingly.

**Review by sadlerap — APPROVED** [review]

**Comment by SNiemann15** [comment]
@sjstout @sferich888 approved changes over slack

**Review by xenolinux — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

LGTM

**Pull request merged**
