### PR TITLE
[SRVCOM-3368] Add Installing kn CLI links for OSL plugin

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVCOM-3368

Link to docs preview:
https://84881--ocpdocs-pr.netlify.app/openshift-serverless/latest/install/serverless-logic-install-kn-workflow-plugin-cli.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by dsimansk** [comment]
LGTM from Knative Client point of view.

**Comment by mgencur** [comment]
LGTM from QE

**Review by xenolinux — COMMENTED** [review]
LGTM

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Pull request merged**
