### PR TITLE
BUG 1434254 Made changes to the parameters as requested

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by penli1** [comment]
The change LGTM.

**Review by penli1 — APPROVED** [review]

**Comment by mburke5678** [comment]
@bmcelvee 
 PTAL. This change is Origin only.

**Comment by bmcelvee** [comment]
LGTM 🌟

**Comment by mburke5678** [comment]
[rev_history]
|xref:../ install_config/cluster_metrics.adoc#install-config-cluster-metrics[Enabling Cluster Metrics]
|Changed several `openshift_metric_` parameters to `openshift_metrics_` in the Ansible Variables table in the xref:/install_config/cluster_metrics.adoc#metrics-ansible-role[Metrics Ansible Variables] section.
%

**Pull request merged**
