### PR TITLE
BZ1754941 update minimum RHEL version

### PR DESCRIPTION
**Pull request by jeana-redhat**
https://bugzilla.redhat.com/show_bug.cgi?id=1754941
Update minimum RHEL version for 3.11 to 7.6 or later.

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@csheremeta this is wrt BZ1754941 which you reported.
Are you able to check this PR to make sure I have it right, or else let me know who I should get to verify the change?

**Comment by csheremeta** [comment]
Hey @jeana-redhat,

It looks like the 3.11 ansible playbooks were updated to include RHEL 7.5 as long as the kernel version is 3.10.0-862.31.1 or higher:

https://github.com/openshift/openshift-ansible/blob/release-3.11/playbooks/init/base_packages.yml#L44-L46

So I would change the instances of "7.6" to "7.5" and leave in the line with the minimum kernel version for RHEL 7.5

**Comment by jeana-redhat** [comment]
Thanks, @csheremeta - please take a look at this update and let me know if this looks better :)

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
