### PR TITLE
Adds OMR 173 release notes

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.10+

Issue:
https://issues.redhat.com/browse/OSDOCS-6975

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@stevsmit Changes lgtm, but I don't see a preview. Does it reside [here](https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-creating-registry.html)?

@maxwelldb Will you please verify my review? Thx!

**Review by maxwelldb — APPROVED** [review]
Assuming preview is https://62658--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-creating-registry.html#mirror-registry-for-openshift-1-3-7, lgtm.

**Comment by stevsmit** [comment]
@ShaunaDiaz @maxwelldb Yes. Sorry thanks--was EOD yesterday and I forgot to add the preview.

**Pull request merged**
