### PR TITLE
OSDOCS-4808:Consistent wording for AWS

### PR DESCRIPTION
**Pull request by mletalie**
[OSDOCS-4808](https://issues.redhat.com//browse/OSDOCS-4808):Consistent wording for AWS

Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-4808

Link to docs preview:

https://54771--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html#osd-aws-privatelink-firewall-prerequisites_rosa-sts-aws-prereqs
QE review:
- [ ] QE has approved this change.

Additional information:

PTAL: @arendej

### CODE REVIEW

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by skrthomas — COMMENTED** [review]
Merge review LGTM.

**Pull request merged**
