### PR TITLE
Fixing typos and other misc things

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.6+ (will backport applicable changes as far as possible)

Issue:
N/A

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2022/typo-check/welcome/

Additional information:

### CODE REVIEW

**Review by jboxman-rh — COMMENTED** [review]
@bergerhoffer, LGTM.

**Comment by bergerhoffer** [comment]
Waiting on #50177 to be cherry picked, then will re-issue the CP commands here

**Pull request merged**
