### PR TITLE
CNV#32306: v1alpha1 DDF

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/CNV-32306

Link to docs preview:
* https://67484--docspreview.netlify.app/openshift-enterprise/latest/virt/post_installation_configuration/virt-node-placement-virt-components#virt-node-placement-rule-examples_virt-node-placement-virt-components
* https://67484--docspreview.netlify.app/openshift-enterprise/latest/virt/install/installing-virt#installing-virt-operator-cli_installing-virt

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by danielclowers** [comment]
Closing/Reopening for Travis

**Comment by danielclowers** [comment]
Just a note, I can't seem to find the module `modules/virt-about-node-placement-virtualization-components` actually in use anywhere - but I went ahead and changed the apiVersion in it.

**Comment by ousleyp** [comment]
LGTM

**Review by dbasunag — APPROVED** [review]

**Pull request merged**
