### PR TITLE
add rhel 8.6 mention

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.12

Issue: n/a

Link to docs preview: http://file.rdu.redhat.com/jdohmann/RN-rhel-version-mention/release_notes/ocp-4-12-release-notes.html#ocp-4-12-rhcos-rhel-8-6-packages

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen PTAL for QE ack. I noticed in previous OCP release notes that the RHEL version is always mentioned, even if there have been no changes to the RHEL version RHCOS uses, so this PR adds a RN entry that mentions RHEL 8.6. Is there anything else that should be added about RHEL 8.6 here, like support timeline information?

**Comment by jldohmann** [comment]
b758520a2a..86e866cd23 add note about 4.10 using RHEL 8.4 packages

**Review by mike-nguyen — APPROVED** [review]
LGTM

**Pull request merged**
