### PR TITLE
Document BC deletion

### PR DESCRIPTION
**Pull request by mnagy**
This includes documentation for https://github.com/openshift/origin/pull/6185

### CODE REVIEW

**Comment by bparees** [comment]
lgtm.  @openshift/team-documentation ptal.

**Comment by mnagy** [comment]
The PR was merged, so this can go in.

**Comment by adellape** [comment]
:+1:

**Comment by adellape** [comment]
[rev_history]
|link../dev_guide/builds.html[Builds]
|Added a link:../dev_guide/builds.html#deleting-a-buildconfig[Deleting a BuildConfig] section.
%

**Pull request merged**
