### PR TITLE
BZ2013668: Updating the values in ContainerRuntimeConfig

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.9+ 
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2013668

Preview: https://deploy-preview-39560--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/machine-configuration-tasks.html#create-a-containerruntimeconfig_post-install-machine-configuration-tasks

Ready for QA: @sergiordlr 

For Peer reviewers: Can you please add the labels: 'enterprise-4.9', 'enterprise-4.10' Thank you!

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
Hi @kelbrown20 
Minor format nit on the first part of the PR title. 
s/BZ:2013668 -/BZ2013668:/

**Review by sergiordlr — APPROVED** [review]
Looks good to me.

Thank you very much!

**Pull request merged**
