### PR TITLE
Bump OCP 4.3 to cri-o 1.16

### PR DESCRIPTION
**Pull request by mburke5678**
https://jira.coreos.com/browse/OSDOCS-735

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by mburke5678** [comment]
Pending https://jira.coreos.com/browse/NODE-167, currently _In Progress_.

**Comment by mburke5678** [comment]
@vikram-redhat Any thoughts on a good QE resource for this?

**Comment by vikram-redhat** [comment]
@geliu2016 would you be able to review this?

**Comment by mburke5678** [comment]
@geliu2016 Please take a look. A simple change to update node output from v1.14 to v1.16.2

**Comment by geliu2016** [comment]
LGTM, thx

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. I just updated output to reflect new Kubernetes version, 1.14x to 1.16.2 (the current version for 4.3). I think this change and a release note are all we need to document for the Kubernetes version bump.

**Pull request merged**
