### PR TITLE
removing openshift.io/cluster-logging: 'true'

### PR DESCRIPTION
**Pull request by mburke5678**
Per @sichvoge

### CODE REVIEW

**Comment by mburke5678** [comment]
@QiaolingTang Can you review this small change?

**Comment by QiaolingTang** [comment]
@mburke5678 will these changes be in 4.1~4.3 ?

**Comment by mburke5678** [comment]
@QiaolingTang As far as I understand. @sichvoge please let us know if that is not true.

**Comment by sichvoge** [comment]
As far as I understood, that annotation had no effect from the get go. But I don't see this as urgent to "backport". It's ok if we only do a test on a newer version of OCP (e.g. next is 4.4).

**Comment by mburke5678** [comment]
@sichvoge @QiaolingTang I cherrypicked to 4.3 and 4.4. If you think we should back port to 4.2 and 4.1, let me know.

**Pull request merged**
