### PR TITLE
Add API resources

### PR DESCRIPTION
**Pull request by jboxman**
As separate pages.

```
$ rsync -avH --delete --exclude '*.html' ../gen-api-docs/build/ rest_api/
```

### CODE REVIEW

**Comment by jboxman** [comment]
@vikram-redhat, FYI.

**Comment by vikram-redhat** [comment]
Wow!

**Comment by jboxman** [comment]
@vikram-redhat, based on the feedback that I received today, I'm going to rework this into _Developer APIs_ and _Administator APIs_ and _Common objects_, I think.

Is it acceptable to descend 3 levels for the API docs? Level two is the API group, as it was suggested that I keep that grouping and expose it visually, and level three is each individual API for the API group. Or at least that was my understanding.

**REST APIs > Administrator APIs > config.openshift.io > DNS API** ect.

**Comment by vikram-redhat** [comment]
@jboxman what are common objects?

I would say the API guide is a special enough case to do this, yes.

**Comment by jboxman** [comment]
Separating common objects from APIs has proved a viable approach so far, although that does generate an index with roughly 175 entries:

```
$ wc -l build/index.adoc
     175 build/index.adoc
```
But those can be linked to directly, so it's probably okay.

**Comment by jboxman** [comment]
@vikram-redhat, rapidly approaching sanity. Cleaned up API groups, mostly complete. Eliminating _Related objects_ in favour of a global index, not included in `_topic-map.yaml` yet, but nearly implemented otherwise. Still missing proper refs between pages.

Need to add configuration for

- hand written examples
- hand written group overview

**Comment by vikram-redhat** [comment]
> @vikram-redhat, rapidly approaching sanity. Cleaned up API groups, mostly complete. Eliminating _Related objects_ in favour of a global index, not included in `_topic-map.yaml` yet, but nearly implemented otherwise. Still missing proper refs between pages.
> 
> Need to add configuration for
> 
> * hand written examples
> * hand written group overview

Brilliant. Let me know if you need a hand.

**Comment by jboxman** [comment]
@vikram-redhat, preview didn't update, sadly.

**Comment by jboxman** [comment]
@vikram-redhat @bobfuru @lbarbeevargas 

Build passes; Preview ought to update soon.

Once we have proper groups, we can theoretically go live.

**Comment by jboxman** [comment]
@vikram-redhat, this seems ready for release on a trial basis. [Preview](https://what-if-we-had-api-docs--ocpdocs.netlify.app/openshift-enterprise/latest/rest_api/objects/index.html).

**Comment by jboxman** [comment]
@vikram-redhat, and it's now possible to look at the delta between releases. This makes it easy to adjust the manifest of resources to include in the docs.

For 4.5.0-rc:

```
API version changes
- CSIDriver [storage.k8s.io]: v1beta1 => v1
APIs added
- Ingress [extensions/v1beta1]
- FlowSchema [flowcontrol.apiserver.k8s.io/v1alpha1]
- PriorityLevelConfiguration [flowcontrol.apiserver.k8s.io/v1alpha1]
- BareMetalHost [metal3.io/v1alpha1]
- Provisioning [metal3.io/v1alpha1]
- StorageState [migration.k8s.io/v1alpha1]
- StorageVersionMigration [migration.k8s.io/v1alpha1]
- ThanosRuler [monitoring.coreos.com/v1]
- OperatorPKI [network.operator.openshift.io/v1]
- IngressClass [networking.k8s.io/v1beta1]
- Config [operator.openshift.io/v1]
- CSIDriver [storage.k8s.io/v1]
- IPPool [whereabouts.cni.cncf.io/v1alpha1]
APIs dropped
- ServiceCatalogAPIServer [operator.openshift.io/v1]
- ServiceCatalogControllerManager [operator.openshift.io/v1]
- CatalogSourceConfig [operators.coreos.com/v1]
```

**Comment by jboxman** [comment]
@vikram-redhat, do we want to merge this? Any gates to pass first? Thanks.

**Comment by vikram-redhat** [comment]
@jboxman go for it!

**Pull request merged**
