### PR TITLE
BZ1860894: Added URL for AWS in step 4.

### PR DESCRIPTION
**Pull request by jonquilwilliams**
[https://bugzilla.redhat.com/show_bug.cgi?id=1860894]

Added URL for AWS in step 4, which allows access in environment that have stricter security requirements.

QE and peer review needed. Please merge and CP to 4.3.z, 4.4, 4.5, 4.6

### CODE REVIEW

**Comment by ahardin-rh** [comment]
I don't see a preview link, but assuming this builds nice locally the change LGTM!

**Comment by jonquilwilliams** [comment]
@ahardin-rh This has been verified by QE, so please merge. I think it needs to be CP to 4.7 also now. Thank you.

**Pull request merged**
