### PR TITLE
osdocs8440: adding service mesh to list of infrastructure components

### PR DESCRIPTION
**Pull request by DCChadwick**
Version(s): 4.11+

Issue: [OSDOCS-8440](https://issues.redhat.com//browse/OSDOCS-8440)

Link to docs preview: https://73429--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-creating-infrastructure-nodes.html#infrastructure-components_creating-infrastructure-nodes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by DCChadwick** [comment]
@sunilcio This PR is ready for QE review.

**Comment by sunilcio** [comment]
@wsun1 do you know who can help review this section for service mesh?

**Review by FilipB — APPROVED** [review]

**Comment by opayne1** [comment]
Hi @DCChadwick this PR needs to go through peer review before getting submitted for merge review. :) I am updating the label accordingly.

**Comment by DCChadwick** [comment]
@opayne1 Thanks! Sorry about that. Total brain glitch.

**Comment by jmanthei** [comment]
LGTM
/remove-label peer-review-needed
/remove-label peer-review-in-progress

**Comment by Srivaralakshmi** [comment]
@DCChadwick I am going ahead with the merge. 

But please note that I see that this module needs the content type in the Module file metadata. Refer to: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata

Ensure to create a JIRA and fix this issue. Also, if other modules in your component area are missing this file metadata, then you can fix it for all of them in one go. Hope this helps. Thank you!

**Pull request merged**
