### PR TITLE
Fix RHEL supported version in 4.6 RNs

### PR DESCRIPTION
**Pull request by jeana-redhat**
Requires change management process

### Previews

- [Release notes](https://deploy-preview-31721--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-6-release-notes.html#ocp-4-6-about-this-release)
- [System requirements for RHEL compute nodes](https://deploy-preview-31721--osdocs.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-rhel-compute.html#rhel-compute-requirements_adding-rhel-compute)
- [Minimum resource requirements table](https://deploy-preview-31721--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal)

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Requesting approvals for this change from @miabbott, @marrusl, @control-d, @sferich888, @xltian, and @vikram-redhat 

Xiaoli, thanks again for finding this one!

Also, when speaking to Bob Furu, I learned that "it was decided to change 4.6 docs to drop RHEL 7.8 and only indicate 7.9." So please let me know if this change should actually be from 7.7 -> 7.9.

**Comment by mburke5678** [comment]
@jeana-redhat LGTM

**Comment by control-d** [comment]
> Also, when speaking to Bob Furu, I learned that "it was decided to change 4.6 docs to drop RHEL 7.8 and only indicate 7.9." So please let me know if this change should actually be from 7.7 -> 7.9.

Yes, @marrusl and I discussed this, and it should be 7.9.  Thanks!

**Comment by vikram-redhat** [comment]
ack

**Comment by jeana-redhat** [comment]
@control-d & @marrusl - thanks, updated to 7.9. Ready for approval again :)

**Comment by control-d** [comment]
@jeana-redhat LGTM

**Comment by jeana-redhat** [comment]
@miabbott & @vikram-redhat - Mark uncovered a couple more places this version information needed to be updated, can you please take a look to make sure you still approve?

**Comment by vikram-redhat** [comment]
Ack

**Pull request merged**
