### PR TITLE
Removing Setting up {pipelines-shortname} in the web console to view Software Supply Chain Security elements from v1.13 and v1.12

### PR DESCRIPTION
**Pull request by gtrivedi88**
Purpose: This PR removes the Secure Supply Chain updates from v1.12 and v1.13 pipeline release. Resolve [[SRVKP-4398](https://issues.redhat.com/browse/SRVKP-4398)] 

Aligned team: DevTools

Version for cherrypicking: pipelines-docs-1.13 and pipelines-docs-1.12

Content for preview: 

SME review: @karthikjeeyar

QE review: @ppitonak 

Peer review:

### CODE REVIEW

**Comment by gtrivedi88** [comment]
@ppitonak This PR removes the Secure Supply Chain updates from v1.12 and v1.13 pipeline release. Could you please review and approve the PR.

**Review by ppitonak — APPROVED** [review]

**Review by bhardesty — COMMENTED** [review]
LGTM! I verified that the deleted content does not appear in the Pipelines preview.

**Pull request merged**
