### PR TITLE
OSDOCS-9463: Fix Azure availabilitySet label in spec

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11+

Issue:
[OSDOCS-9463](https://issues.redhat.com//browse/OSDOCS-9463)

Link to docs preview:
[Sample YAML for a compute machine set custom resource on Azure](https://70883--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-yaml-azure_creating-machineset-azure) (removes callout `<4>` and renumbers after)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@RadekManak for the bug you raised yesterday, PTAL

**Comment by dfitzmau** [comment]
/remove-label peer-review-in-progress

/label peer-review-done

LGTM

**Pull request merged**
