### PR TITLE
Bug 1684643, applied QE feedback to Performance and Scalability content

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1684643

Preview Build: http://file.rdu.redhat.com/~ahardin/03052019/scale-BZ-4-0/scalability_and_performance/recommended-host-practices.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@mffiedler @wabouhamad I started to address some of the [review feedback ](https://docs.google.com/document/d/1DyRpv4WtZKJteBWy6_q_Ej6TvB7-9rN_1R42ym2Xnug/edit?usp=sharing). There are still some open questions on how to handle some issues, but can you please take a look at what is in place and let me know if I missed anything? Thanks!

**Comment by mffiedler** [comment]
@hongkailiu Please help review as well.  Preview link:  https://scale-BZ-4-0--ocpdocs.netlify.com/

**Comment by hongkailiu** [comment]
> @hongkailiu Please help review as well. Preview link: https://scale-BZ-4-0--ocpdocs.netlify.com/

Will do tomorrow.

**Comment by ahardin-rh** [comment]
@hongkailiu  You mentioned on today's call that there are outstanding issues on this work, but I am not sure what you mean. Can you please let me know what I missed? Thanks!

**Comment by hongkailiu** [comment]
> @hongkailiu You mentioned on today's call that there are outstanding issues on this work, but I am not sure what you mean. Can you please let me know what I missed? Thanks!

Oh. I meant that there are still open issues in the gdoc.
I feel it would be easier to start the review as a whole when all issues get addressed.

**Comment by hongkailiu** [comment]
#3,8,9 are still open. Otherwise lgtm.

**Comment by ahardin-rh** [comment]
@akrzos Can you please help me confirm that the content on this page is still relevant for the 4.0/4.1 release? If not, I can remove that page.
http://file.rdu.redhat.com/~ahardin/03052019/scale-BZ-4-0/scalability_and_performance/optimizing-compute-resources.html

The review feedback says:

> Not sure if this page still applies to OCP 4.0 since RHCOS is the OS on the node. Maybe for bring your own host in the future?

Once we have this confirmed, I think we can merge these changes. We'll open new PRs to address the other 2 open issues noted by Hongkai. Ravi and Sebastian are working on those pieces, but that work should not block these fixes.

**Comment by akrzos** [comment]
> @akrzos Can you please help me confirm that the content on this page is still relevant for the 4.0/4.1 release? If not, I can remove that page.
> http://file.rdu.redhat.com/~ahardin/03052019/scale-BZ-4-0/scalability_and_performance/optimizing-compute-resources.html

Everything looks relevant to me.  I can run and see the rhel-tools containers by using the `oc debug node/<node>` cli referenced and debug/see things on the host from the container.

> 
> The review feedback says:
> 
> > Not sure if this page still applies to OCP 4.0 since RHCOS is the OS on the node. Maybe for bring your own host in the future?
> 
> Once we have this confirmed, I think we can merge these changes. We'll open new PRs to address the other 2 open issues noted by Hongkai. Ravi and Sebastian are working on those pieces, but that work should not block these fixes.

**Comment by ahardin-rh** [comment]
@akrzos Thanks for confirming! I will merge these changes and will follow up with Ravi and Sebastian on the other 2 forthcoming items in separate PRs.

**Pull request merged**
