### PR TITLE
OCPBUGS#3813: Move the note under prerequisite

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-3813 [PR is raised based on recent comments on the issue]

Link to docs preview: https://64574--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/graceful-cluster-shutdown.html#prerequisites

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
LGTM

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by sheriff-rh** [comment]
Hi @xenolinux  - 4.10 is now [EOL](https://access.redhat.com/support/policy/updates/openshift#dates). If you need these changes in 4.10, reach out to Kathryn for approval. 

I will merge to 4.11+ in the meantime. Thanks!

**Pull request merged**
