### PR TITLE
GitHub-39286: Updating CLI image

### LINKED ISSUE #39286: [enterprise-4.9] Issue in file authentication/ldap-syncing.adoc
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/authentication/ldap-syncing.html#ldap-auto-syncing_ldap-syncing-groups

cronjob YAML: **Example ldap-sync-cron-job.yaml**
 `             image: "openshift/origin-cli:latest"`

### What needs fixing?
the linked oc client image on docker is 3years old (BuildDate:"2019-04-10T12:24:28Z")
https://hub.docker.com/r/openshift/origin-cli/tags

```console
joe@server1~ $ docker run --rm -it openshift/origin-cli:latest  bash -c "oc version"
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.0-alpha.0+af45cda-1969-dirty", GitCommit:"af45cda", GitTreeState:"", BuildDate:"2019-04-10T12:24:28Z", GoVersion:"", Compiler:"", Platform:""}
```

should one from 
`image: registry.redhat.io/openshift4/ose-cli`
https://catalog.redhat.com/software/containers/openshift4/ose-cli/5cd9ba3f5a13467289f4d51d

or quay.io be used? 
https://quay.io/repository/openshift/origin-cli

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #39286

Preview: https://deploy-preview-39608--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing#ldap-auto-syncing_ldap-syncing-groups

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh Can you please review?

Preview: https://deploy-preview-39608--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing#ldap-auto-syncing_ldap-syncing-groups

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
