### PR TITLE
Tuning CNI IFNAME clarification (omits using eth0)

### PR DESCRIPTION
**Pull request by dougbtv**
Omits the usage of eth0 in the example (which will not work with tuning CNI)

Clarifies that the `IFNAME` token should be used literally.

Version(s):

* PR applies to all versions after a specific version (e.g. 4.8): 4.11+

Issue: discovered during assessment of https://issues.redhat.com/browse/RFE-2879

Additional information:

* The current docs @ https://docs.openshift.com/container-platform/4.11/nodes/containers/nodes-containers-sysctls.html seem to have some muddying of the waters between our "kinds of sysctls" -- that is, for a pod, for a node, or for a specific network interface. I will try to start a discussion.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@sunilcio, will you PTAL?

**Comment by JoeAldinger** [comment]
@dougbtv could you please provide a preview of the changes.

**Comment by bergerhoffer** [comment]
@JoeAldinger For people who aren't a writer on the team, we can generate/check the preview for them. It should have been done automatically since it's against main, not sure why it didn't. But I'll take care of it now!

**Review by bergerhoffer — COMMENTED** [review]
This LGTM!

@dougbtv Are you ready for us to merge this?

**Comment by dougbtv** [comment]
@bergerhoffer -- lost track of this one on my radar, but a-ok to merge! Thanks!!

**Comment by bergerhoffer** [comment]
No worries, thanks @dougbtv!

Merging

**Comment by bergerhoffer** [comment]
@dougbtv This is failing when cherry picking to 4.10 and earlier. I looked, and one file doesn't exist, and the other doesn't have the lines that you edited. Can you take a look and verify that this really does only need updated in 4.11+? Thanks!

**Comment by bergerhoffer** [comment]
Updates only apply to 4.11+, updating labels accordingly!

**Pull request merged**
