### PR TITLE
Updated second command under procedure to $ rosa list user-role

### PR DESCRIPTION
**Pull request by mikesmith0414**
Updated second command under procedure to $ rosa list user-role

Version(s): 4.11+

Issue:
https://github.com/openshift/openshift-docs/issues/49322

Preview: https://50661--docspreview.netlify.app/openshift-rosa/latest/rosa_support/rosa-troubleshooting-iam-resources.html#rosa-sts-ocm-roles-and-permissions-troubleshooting_rosa-troubleshooting-iam-resources

QE needed.

### CODE REVIEW

**Comment by xueli181114** [comment]
LGTM

**Review by mjpytlak — COMMENTED** [review]
Peer review LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
