### PR TITLE
Use 1400 MTU in OVN-Kubernetes example

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1821440

### CODE REVIEW

**Comment by jboxman** [comment]
Verified on Slack.

**Comment by jboxman** [comment]
@openshift/team-documentation, so this is odd, because _Generic Network Virtualization Encapsulation_ is actually _Geneve_. Is that valid as an abbreviation?

- The spec doesn't capitalize: https://tools.ietf.org/html/draft-gross-geneve-00
- But we do/have: https://www.redhat.com/en/blog/what-geneve

Usage is mixed.

**Comment by bobfuru** [comment]
> @openshift/team-documentation, so this is odd, because _Generic Network Virtualization Encapsulation_ is actually _Geneve_. Is that valid as an abbreviation?
> 
> * The spec doesn't capitalize: https://tools.ietf.org/html/draft-gross-geneve-00
> * But we do/have: https://www.redhat.com/en/blog/what-geneve
> 
> Usage is mixed.

It sounds valid to me, esp. because it's easier to remember than "Generic Network Virtualization Encapsulation". But shouldn't the acronym remain capitalized ("GENEVE") because it is derived from the first letters of each word?

**Comment by jboxman** [comment]
@bobfuru, yeah, I wasn't sure, and didn't consider that usage style. I thought it would be all or nothing.

**Pull request merged**
