### PR TITLE
BZ1699403 fix restorecon options

### PR DESCRIPTION
**Pull request by jeana-redhat**

### CODE REVIEW

**Comment by jeana-redhat** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1699403

**Comment by jeana-redhat** [comment]
@geliu2016 this is for BZ1699403, which is now ON_QA.

**Comment by geliu2016** [comment]
LGTM, thanks

**Comment by jeana-redhat** [comment]
@openshift/team-documentation PTAL :)

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
