### PR TITLE
OCPBUGS-37812: Removing erroneous mention of MTU

### PR DESCRIPTION
**Pull request by rohennes**
OCPBUGS-37812: Removing erroneous mention of MTU

Version(s):
4.16+

Issue:
https://issues.redhat.com/browse/OCPBUGS-37812

Link to docs preview:
https://79839--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html

Additional information:
Typo - does not change any YAML examples - no QE required

### CODE REVIEW

**Comment by kcarmichael08** [comment]
I was wondering if this needed Change Management, but I think because it's a tech preview feature and is removing something that was listed in error, it wouldn't require CM. 

lgtm.

**Review by Srivaralakshmi — COMMENTED** [review]
Lgtm

**Pull request merged**
