### PR TITLE
removing the --log-level debug option

### PR DESCRIPTION
**Pull request by kalexand-rh**
@abhinavdahiya, based your [comments](https://github.com/openshift/openshift-docs/pull/16374#discussion_r317220248) on the Azure draft, would you like this option removed from all of the installation docs?

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
So 2 things..
1) making sure most users are running at `info` level because that's designed for best UX.
2) informing users that they can indeed set log-level to something other than `info`, like `debug | info | warn | error` .

So maybe switching the docs to set `--log-level info <2>`  and then telling them `<2> you can set the log levels to these other values.... and info is the default one if you skip that flag` ..

if that becomes too troublesome, just dropping it like we do here is fine with me. :)

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL or tag someone else from QE?

**Comment by jianlinliu** [comment]
LGTM

**Comment by kalexand-rh** [comment]
@openshift/team-documentation PTAL

**Comment by mburke5678** [comment]
@kalexand-rh LGTM

**Pull request merged**
