### PR TITLE
Issue 20276, update command to edit the Operator configuration

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://github.com/openshift/openshift-docs/issues/20276

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@yapei PTAL

**Comment by lamek** [comment]
LGTM

**Comment by ahardin-rh** [comment]
@yapei Can you please provide QE review?

**Review by yapei — APPROVED** [review]
tested the command the code below, the changes can be applied. LGTM

**Pull request merged**
