### PR TITLE
Added missing redirection

### PR DESCRIPTION
**Pull request by ghost**
@e-minguez  Please review. This is a follow-up to https://github.com/openshift/openshift-docs/pull/6335. What versions of OCP does this change apply to?

### CODE REVIEW

**Comment by e-minguez** [comment]
LGTM!

**Comment by e-minguez** [comment]
It affects all of the versions where the redirection is missing.
Thanks

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by bmcelvee** [comment]
LGTM 🌈

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Pull request merged**
