### PR TITLE
ALM restructrue; intro of app promotion

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees the long awaited PR for https://trello.com/c/HlQpE52w/848-8-provide-example-of-promoting-application-between-datacenters-projects-evg based on the collaboration we've been doing in our google docs.

@openshift/team-documentation PTAL (FYI, we've already had a brief exchange with @adellape and @nhr on some of the structure and injection point for this content).

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Thanks @gabemontero . Might need a rebase. 

@adellape  - PTAL.

**Comment by vikram-redhat** [comment]
@gabemontero - is there anything specific in here for a particular version?

**Comment by gabemontero** [comment]
rebase done (yeah `git rebase` :-) no manual intervention needed )

@vikram-redhat - the content here is applicable to all versions

**Comment by adellape** [comment]
Here's a preview build for review:

http://file.rdu.redhat.com/~adellape/111616/alm_restructure/dev_guide/application_lifecycle/index.html

**Comment by vikram-redhat** [comment]
@adellape - I like the break up of the topics. That makes a lot of sense. Are you planning to do a follow up PR for the application promotion topic? 

cc @aheslin

**Comment by adellape** [comment]
@vikram-redhat Yes.

@gabemontero I'm going to build on this commit to fix links and do some edits. PR incoming today.

**Comment by adellape** [comment]
4 days later...

Following up here: https://github.com/openshift/openshift-docs/pull/3275

**Pull request closed without merging**
