### PR TITLE
Graduate HPA scaling based on Memory to GA

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-1215

### CODE REVIEW

**Comment by mburke5678** [comment]
@joelsmith PTAL. As i understand, there are no code changes or new features. I am simply removing the Tech Preview notice from the existing docs.

**Comment by mburke5678** [comment]
@weinliu PTAL. As i understand, there are no code changes or new features. I am simply removing the Tech Preview notice from the existing docs.

**Review by jeana-redhat — APPROVED** [review]
/lgtm

**Pull request merged**
