### PR TITLE
Add Rouge syntax highlighter CSS

### PR DESCRIPTION
**Pull request by jboxman**
Add the necessary CSS classes for syntax highlighting.

- https://spsarolkar.github.io/rouge-theme-preview/

### CODE REVIEW

**Comment by jboxman** [comment]
Preview: http://file.bos.redhat.com/jboxman/rouge-style/networking/using-sctp.html

cc @vikram-redhat

**Comment by jboxman** [comment]
I cheated and dumped the styles in a `<style>` tag.

**Comment by jboxman** [comment]
@vikram-redhat, this has the GH theme ready to go already.

**Comment by vikram-redhat** [comment]
@openshift/team-documentation @openshift/team-aligned-docs FYI that this will be merged this week.

**Comment by maxwelldb** [comment]
Just reiterating because poll comments are easy to lose: many of these styles, including the GH one, don't quite meet the latest WCAG AA contrast requirements. They'd need some modification to be accessible.

**Comment by jboxman** [comment]
@maxwelldb, did we meet that standard before?

**Comment by maxwelldb** [comment]
@jboxman Just doing a few spot checks, yeah, looks like it. I'm actually seeing AAA for terminal and YAML contrast ratios--8.38 and 8.97, respectively.

**Comment by maxwelldb** [comment]
As an aside, WCAG encourages allowing people to select from different themes. :smiling_imp: 

>Note: Some people with cognitive disabilities require color combinations or hues that have low contrast, and therefore we allow and encourage authors to provide mechanisms to adjust the foreground and background colors of the content. Some of the combinations that could be chosen may have contrast levels that will be lower than those found in the Success Criteria. This is not a violation of this Success Criteria provided there is a mechanism that will return to the default values set out in the Success Criteria.

**Comment by jboxman** [comment]
@maxwelldb, it looks like the styles can be adjusted manually with: https://accessible-colors.com

**Comment by maxwelldb** [comment]
Might make sense to implement an accessible theme from a common palette rather than adjusting text color + background color for each item in isolation, but that's definitely a quick and painless resource.

**Comment by jboxman** [comment]
@maxwelldb, all of this is completely outside my wheelhouse. So I wouldn't really know where to begin.

**Comment by maxwelldb** [comment]
@jboxman This is a good review: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast

**Comment by jboxman** [comment]
@maxwelldb, but not color palettes and such. I've never been a unicorn. I can do backend stuff on occasion, but I never took to frontend work. So my ability in this area is limited.

**Comment by maxwelldb** [comment]
@jboxman Could always just steal some high-contrast stylesheets from elsewhere. Ex: https://maxchadwick.xyz/pygments-high-contrast-stylesheets/

**Pull request merged**
