### PR TITLE
BZ1807463: Added restriction for FIPS on Azure File storage

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.5+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1807463
QE Approval Needed: @qinpingli 
Preview Link: https://deploy-preview-31266--osdocs.netlify.app/openshift-enterprise/latest/installing/installing-fips.html#installing-fips-mode_installing-fips and https://deploy-preview-31266--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-configuration-parameters_installing-azure-customizations (Table 2: Optional Parameters).

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM

**Comment by qinpingli** [comment]
@duanwei33 Could you help review it from QE side? Thanks!

**Comment by duanwei33** [comment]
LGTM

**Pull request merged**
