### PR TITLE
cnv: Clarify evictionStrategy usage in a few places

### PR DESCRIPTION
**Pull request by fabiand**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/CNV-39395

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by fabiand** [comment]
@stu-gott @acardace please review

**Review by jherrman — CHANGES_REQUESTED** [review]

**Comment by fabiand** [comment]
Thanks @jherrman I've addressed your comments.

**Review by acardace — APPROVED** [review]

**Comment by ousleyp** [comment]
Hi @fabiand , your changes LGTM, but please squash your commits to 1 commit and then, if you don't mind, please ping me for a final merge review. Thanks!

**Comment by ousleyp** [comment]
Closing and reopening to attempt to kick the builds.

**Comment by ousleyp** [comment]
FYI @fabiand, I'm closing this PR because I'm going to merge a copy of it shortly: https://github.com/openshift/openshift-docs/pull/78334 Thanks for contributing to the docs! :)

**Pull request closed without merging**
