### PR TITLE
SRVCOM-1501: Add Serverless 1.18.0 release notes

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+
Jira: https://issues.redhat.com/browse/SRVCOM-1501
Docs preview:
* The release notes for 1.18.0 https://deploy-preview-37574--osdocs.netlify.app/openshift-enterprise/latest/serverless/serverless-release-notes.html#serverless-rn-1-18-0_serverless-release-notes
* An added sentence regarding Camel-K to the 1.17.0 notes (the very last sentence in 1.17.0 notes) https://deploy-preview-37574--osdocs.netlify.app/openshift-enterprise/latest/serverless/serverless-release-notes.html#known-issues-1-17-0_serverless-release-notes
* Additional note regarding the LoadBalancer service type https://deploy-preview-37574--osdocs.netlify.app/openshift-enterprise/latest/serverless/knative_serving/serverless-applications.html#interacting-serverless-apps-http2-gRPC_serverless-applications

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
The default service type for Kourier will be changed in 1.19 not 1.18. (It is same with `defaultExternalScheme`.)
I'm sorry I forgot to update SRVKS-803.

**Review by mgencur — COMMENTED** [review]
Hi! A couple of comments. Otherwise it looks good to me.

**Review by cardil — CHANGES_REQUESTED** [review]

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

Small fix

**Pull request merged**
