### PR TITLE
[GH47273]: Fix utilizationThreshold example and clarify parameter requirements

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.10+

Issue:
#47273

Link to docs preview:
[ClusterAutoscaler resource definition](http://file.rdu.redhat.com/jrouth/GH47273/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling) (requires VPN)

/cc @mtulio

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM - please stand by for further review and merge.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too

**Pull request merged**
