### PR TITLE
[OSDOCS-10170]:Remove obsolete information about upgrading ROSA cluster sections

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10170
Link to docs preview:

https://74729--ocpdocs-pr.netlify.app/openshift-rosa/latest/upgrading/rosa-upgrading.html#rosa-upgrade-ocm_rosa-upgrading

https://74729--ocpdocs-pr.netlify.app/openshift-rosa/latest/upgrading/rosa-upgrading-sts.html#rosa-upgrade-ocm_rosa-upgrading-sts

https://74729--ocpdocs-pr.netlify.app/openshift-rosa/latest/upgrading/rosa-upgrading#rosa-upgrading-cli_rosa-upgrading

QE review:
- [x] QE has approved this change.

Additional information:

**Reviewers: Scope of ticket was to remove references to upgrading to 4.9 clusters as version is outdated.**

### CODE REVIEW

**Comment by mletalie** [comment]
QE review assigned to @jameszwang per https://redhat-internal.slack.com/archives/C0308P3FC7R/p1713313964903469?thread_ts=1713297356.765619&cid=C0308P3FC7R

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
