### PR TITLE
bz1941073 remove AWS EFS

### PR DESCRIPTION
**Pull request by lpettyjo**
https://bugzilla.redhat.com/show_bug.cgi?id=1941073

This PR addresses the changes for the book only: Removed topic "Storage" > "Configuring persistent storage" > "Persistent storage using Amazon EFS", and row from "Storage" > "Dynamic provisioning" > "Available dynamic provisioning plug-ins" table, and row from "Post-installation configuration" > "Storage configuration" > "Available dynamic provisioning plug-ins" table.

PTAL @jsafrane, @qinpingli, @xltian, @sferich888, @vikram-redhat 

I will send out a change notification email when I get your acks. Thanks!

Book:https://github.com/openshift/openshift-docs/pull/31446
RN 4.5: https://github.com/openshift/openshift-docs/pull/31449
RN 4.6: https://github.com/openshift/openshift-docs/pull/31448
RN 4.7: https://github.com/openshift/openshift-docs/pull/31447
RN 4.8: Coming later. Will incorporate the same changes as the other rel notes listed above.

### CODE REVIEW

**Comment by qinpingli** [comment]
LGTM

**Comment by jsafrane** [comment]
LGTM

**Comment by jhou1** [comment]
LGTM

**Comment by jhou1** [comment]
Does this PR get the `Persistent storage using AWS Elastic File System` content(aka storage/persistent_storage/persistent-storage-efs.adoc) removed for all versions?

**Comment by lpettyjo** [comment]
The PR removes AWS EFS for version 4.5 through 4.8.

**Comment by jsafrane** [comment]
lgtm

**Comment by sjstout** [comment]
LGTM

**Comment by bkunal** [comment]
LGTM

**Comment by lpettyjo** [comment]
@bkunal has approved on @xltian behalf
@jhou1 has approved on @sferich888 behalf
@sjstout has approved on behalf of docs (@vikram-redhat)
So all approvals have been obtained.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
