### PR TITLE
OSDOCS-1206: Updating kube version to 1.19 in release notes

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1206

### CODE REVIEW

**Comment by bergerhoffer** [comment]
PR is waiting on Kubernetes 1.19 to be released so that the link works.

**Comment by bergerhoffer** [comment]
Opened a question to Kubernetes docs as to whether there will be a 1.19-specific URL for the Kubernetes 1.19 release notes (as there was for 1.18 and earlier). Currently, the only URL that I can find for 1.19 is a generic URL that might get updated to 1.20, etc.: https://kubernetes.io/docs/setup/release/notes/

**Comment by bergerhoffer** [comment]
Going to use the existing URL that works (https://kubernetes.io/docs/setup/release/notes/) so that this works. We can go back and update once there is a 1.19-specific URL, but this was requested a few weeks ago and there hasn't been one added yet.

**Comment by ahardin-rh** [comment]
Looks good!

**Comment by bergerhoffer** [comment]
FYI @codyhoag I changed this PR to use the existing URL for the 1.19 release notes. I was hoping there would be the 1.19-specific URL, but I haven't heard anything on the issue I opened. So let's get this in and we can come back and update it if they ever address it.

**Comment by codyhoag** [comment]
@bergerhoffer sounds good! Thanks for the heads up!

**Pull request merged**
