### PR TITLE
Adds 373 RNs to OMR

### PR DESCRIPTION
**Pull request by stevsmit**
For 4.10+ 

Issue: https://issues.redhat.com/browse/PROJQUAY-3108

No QE needed. 

Preview: https://stevsmit.github.io/openshift-docs/OMR-373/installing/disconnected_install/installing-mirroring-creating-registry.html#mirror-registry-for-openshift-1-2-2

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @stevsmit  This might be something specific to Quay, but in the 'Files changed' it is a release notes file, but it was updated in 'main'. Also in the preview, the content is not in the release notes section...just checking!  Thanks.

**Review by tmalove — COMMENTED** [review]
Left a question, but LGTM!

**Comment by stevsmit** [comment]
@tmalove 

Yeah it's because this release note is specific to Mirror Registry for Red Hat OpenShift--a tool independent of OCP RNs. Those RNs are put in this module: https://docs.openshift.com/container-platform/4.10/installing/disconnected_install/installing-mirroring-creating-registry.html#mirror-registry-release-notes_installing-mirroring-creating-registry, and updated in the 4.10 and 4.11+ branches.

**Review by jeana-redhat — COMMENTED** [review]
Just sent you a Q about this link (and others in past ones) via DM but otherwise LGTM

**Pull request merged**
