### PR TITLE
[OSDOCS-6135]: Additional feedback

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.14+

Issue:
[OSDOCS-6135](https://issues.redhat.com//browse/OSDOCS-6135)

Link to docs preview:
- Installing a cluster on Azure using ARM templates > [Prerequisites](https://66488--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra#prerequisites)
- [Creating Azure resources with the Cloud Credential Operator utility](https://66488--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations#cco-ccoctl-creating-at-once_installing-azure-customizations)
- [Azure AD Workload Identity authentication process](https://66488--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-short-term-creds#cco-short-term-creds-auth-flow-azure_cco-short-term-creds)
- [Creating GCP resources with the Cloud Credential Operator utility](https://66488--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#cco-ccoctl-creating-at-once_installing-gcp-customizations)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jianping-shu** [comment]
LGTM except if you want to add manifests output of "ccoctl gcp create-all"

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by jeana-redhat** [comment]
rebase/refresh for merge

**Pull request merged**
