### PR TITLE
OADP-3181: Update attributes for OADP 1.3.1

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [OADP-3181](https://issues.redhat.com/browse/OADP-3181)

Moving attribute for OADP to 1.3.1

GA - 16th April

### Version(s):

OCP 4.13 → branch/enterprise-4.13
OCP 4.14 → branch/enterprise-4.14
OCP 4.15 → branch/enterprise-4.15
OCP 4.16 → branch/enterprise-4.16

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
@amastbau && @stillalearner - Thanks for approving the ticket and moving it to release pending

But please can you approve the PR. I am not sure OCP reviewers will merge without explicit approval

Thanks

**Comment by anarnold97** [comment]
@amastbau - thanks very much

**Review by bhardesty — COMMENTED** [review]
LGTM. Just to be sure: I see that the new `oadp-version` attribute was added, but it doesn't appear to be used anywhere. Is that correct?

**Comment by anarnold97** [comment]
we should have a {oadp-version} attribute. i am introducing it to help with future documentation

**Pull request merged**
