### PR TITLE
Add documentation for exposing router metrics and integrating haproxy with prometheus

### PR DESCRIPTION
**Pull request by ramr**
@bfallonf @adellape PTAL Thx

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr Might needs some follow-up edits, but looks good to me. I'll let @adellape have a look before merging.

**Comment by ramr** [comment]
@bfallonf  cool Thx.      @adellape  /bump

**Comment by eparis** [comment]
@adellape bump

**Comment by adellape** [comment]
Sorry for the delay. LGTM, merging.

@ramr @eparis I take it these are the related code PR and card?

https://github.com/openshift/origin/pull/4766
https://trello.com/c/SKiYdGl0

I see `--expose-metrics` is in OSE at least as of 3.1. Should this content be included in the OSE doc or is it still pending anything?

**Comment by ramr** [comment]
@adellape   yeah, it should be in OSE 3.1 docs. Not pending anything. Thx

**Comment by vikram-redhat** [comment]
@bfallonf followed up here: https://github.com/openshift/openshift-docs/pull/2554.

**Pull request merged**
