### PR TITLE
Add Kuryr caveats related to ShiftStack availability zone support

### PR DESCRIPTION
**Pull request by maxwelldb**
Context: https://issues.redhat.com/browse/OSDOCS-1492

@luis5tb Does this address what you were talking about here?

https://github.com/openshift/openshift-docs/pull/24834#issuecomment-685077426

### CODE REVIEW

**Comment by maxwelldb** [comment]
(PR is messy right now--most of the commits will resolve after 24834 is merged.)

**Comment by luis5tb** [comment]
> Context: https://issues.redhat.com/browse/OSDOCS-1492
> 
> @luis5tb Does this address what you were talking about here?
> 
> [#24834 (comment)](https://github.com/openshift/openshift-docs/pull/24834#issuecomment-685077426)

Looks great! thanks!

**Comment by maxwelldb** [comment]
Thanks!

Merge is blocked by default zone behavior detailed in #24834.

**Comment by maxwelldb** [comment]
Netlify preview should be updated within an hour: https://osp-azs-kuryr-caveats-osdocs1492--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-configuration-parameters_installing-openstack-installer-custom

**Comment by eurijon** [comment]
This PR looks good! thanks!

**Comment by maxwelldb** [comment]
@eurijon Thanks!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
