### PR TITLE
Fix command typo

### LINKED ISSUE #25309: [enterprise-4.5] Issue in file nodes/nodes/nodes-nodes-working.adoc - oc adm delete node is wrong
### Which section(s) is the issue in?
Deleting nodes from a bare metal cluster

### What needs fixing?
The command "oc adm delete node <node_name>" doesn't exists and gives an error:

$ oc adm delete node worker-1.mycluster
error: unknown command "delete node worker-1.mycluster"

The right command is "oc delete node <node_name>", for example:
$ oc delete node worker-1.mycluster
node "worker-1..mycluster" deleted

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #25309

### CODE REVIEW

**Comment by codyhoag** [comment]
QE confirmed in linked issue

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
