### PR TITLE
BZ-1892614 Update the optional pull-secret procedure

### PR DESCRIPTION
**Pull request by lbarbeevargas**
BZ-1892614 https://bugzilla.redhat.com/show_bug.cgi?id=1892614

Update `pull-secret.json` to `pull-secret.txt`, as well as `pull-secret-update.json` to `pull-secret-update.txt`.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
The PR was reviewed by the BZ reporter per [this comment in BZ-1892614](https://bugzilla.redhat.com/show_bug.cgi?id=1892614#c3).

**Review by adellape — APPROVED** [review]
:+1:

**Comment by lbarbeevargas** [comment]
@wjiangjay PTAL, thank you!

**Comment by lbarbeevargas** [comment]
@wjiangjay Bump. PTAL, thanks!

**Comment by wjiangjay** [comment]
@lbarbeevargas sorry for the late, LGTM.

**Pull request merged**
