### PR TITLE
Weekly Publishing Dedicated 31 May 2017

### PR DESCRIPTION
**Pull request by bmcelvee**

### CODE REVIEW

**Comment by bmcelvee** [comment]
@ahardin-rh PTAL 😸

**Comment by ahardin-rh** [comment]
LGTM! :stars:

**Comment by gaurav-nelson** [comment]
:100: 100th Million MR Yay! :octocat: :smile:

**Comment by Mindgamesnl** [comment]
100.00.00 Yeey!

**Comment by CarlosACepeda** [comment]
Hey, congrats.

**Comment by CarlosACepeda** [comment]
Mine was 99.999.999

**Comment by wbolster** [comment]
in case people wonder where the cheerful comments on this pr come from:

https://twitter.com/github/status/872512141978353664

**Comment by Qix-** [comment]
I'm just here for the history.

**Comment by Tyrrrz** [comment]
Still not too late to make a comment

**Comment by faure-finimize** [comment]
Sup

**Comment by marktani** [comment]
Congratulations :tada:

**Comment by mauricetmeyer** [comment]
This is history! 🥇

**Comment by maelsan** [comment]
♥ github ♥

**Comment by gautamkrishnar** [comment]
Congrats! @bmcelvee 🍺 👍

**Comment by b4mboo** [comment]
:sparkles:

**Comment by AykutCevik** [comment]
🎂

**Comment by 1DC** [comment]
🥇

**Comment by tiwillia** [comment]
🍕

**Comment by davidpelayo** [comment]
A woman making history!

**Comment by ploctaux** [comment]
oh hai! congrats ! 👍

**Comment by Arinerron** [comment]
Great job on being the 1,000,000th merge! :)

**Comment by mustafaismail22** [comment]
✨🎉🎊

**Comment by fpruitt** [comment]
image

**Comment by fabianofranz** [comment]
shuffling-duck

**Comment by grsabreu** [comment]
Look mom, I'm in history!

**Comment by leewaa** [comment]
https://giphy.com/gifs/ufc-boom-3o6Zt5hA1azGgc7WiQ

**Comment by xuezhma** [comment]
mom get the camera

**Comment by aeolusheath** [comment]
buddy, wait wait , I didn't pose well 

ok

come on! cheese !

**Comment by ploctaux** [comment]
😬

Отправлено с iPhone

**Comment by linky00** [comment]
whoooooooooooooooooooooooooooooooooo pls let me be in the screenshot k thx

**Comment by StevenCopeland** [comment]
Wow! Congrats @bmcelvee!

**Comment by Jeremyye2017** [comment]
hahaha

**Comment by juliuskrah** [comment]
I couldn't help myself

**Comment by Asumie** [comment]
How it work

**Comment by whackcat** [comment]
*sets history with pr*🎈🎉

**Comment by ParanoidBeing** [comment]
+1

**Comment by marcostudios** [comment]
Hi mom!

**Comment by supernerdhelloworld** [comment]
Happy one million! Wait, I mean ten million. Wait, one hundred million?? :clap:

**Comment by jeffhuys** [comment]
It feels like this PR will be locked soon 😃

**Comment by ponugoti** [comment]
This is pretty incredible! 😲

**Comment by 84915797613** [comment]
1'2'3' cung way len len len nao...
screenshot_2017-10-25-19-34-17

**Comment by ploctaux** [comment]
un-subbing from this thread, too many emails to read. thx for the fun !

**Comment by VutonDesign** [comment]
capture
....and another record is set for the most reactions on a PR comment this year! 😆 🚀

**Comment by OriginCode** [comment]
:laughing: :fireworks:

**Comment by qwertyuiop6** [comment]
100000000

**Comment by Akshayvs** [comment]
Sweeeett ! I am here for my spot in the history !

**Comment by vutondesign** [comment]
*leaves a mark with my name*

**Comment by xiaoleiPENG** [comment]
哦，我的上帝，这真是一个历史性的时刻

**Comment by hailduong** [comment]
Wow, congrats. 100M

**Comment by markspereira** [comment]
🎉 Open Source!! 🚀

**Comment by whackcat** [comment]
Unsubscribing now because I am bored of the notifications.

**Comment by AliFlux** [comment]
100M FTW 🎉

**Comment by gaurav-nelson** [comment]
got a mention in GitHub 10 years timeline https://github.com/ten

image

too bad, they didn't linked it back here.

**Comment by mu2** [comment]
🎉 👍 ✌️

**Pull request merged**
