### PR TITLE
OCPBUGS-21804 update NTO command syntax

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-21804

Link to docs preview:
[Verifying that the TuneD profiles are applied](https://file.rdu.redhat.com/antaylor/OCPBUGS-21804/scalability_and_performance/using-node-tuning-operator.html#verifying-tuned-profiles-are-applied_node-tuning-operator)
[Accessing an example Node Tuning Operator specification](https://file.rdu.redhat.com/antaylor/OCPBUGS-21804/scalability_and_performance/using-node-tuning-operator.html#accessing-an-example-node-tuning-operator-specification_node-tuning-operator)

QE review:
- [ ] QE has approved this change.

Additional information:
None

### CODE REVIEW

**Review by jmencak — APPROVED** [review]

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by sheriff-rh** [comment]
Merging. Thanks all!

**Pull request merged**
