### PR TITLE
OSDOCS-5746

### PR DESCRIPTION
**Pull request by smunje1**
[OSDOCS-5746](https://issues.redhat.com/browse/OSDOCS-5746): Hive deprovisioner removed load balancers on second cluster in VPC

Aligned team: Service Delivery
OCP version for cherry-picking: enterprise-4.13+
JIRA issues: [OSDOCS-5746](https://issues.redhat.com/browse/OSDOCS-5746)
Preview pages: [Click here to see the build preview in your browser](https://60117--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.html)
SME Review **completed**: @oarribas
QE review **completed**: @xueli181114 
Peer-review **completed**: @GroceryBoyJr

### CODE REVIEW

**Comment by smunje1** [comment]
We have the SME's approval. Jira [comment](https://issues.redhat.com/browse/OSDOCS-5746?focusedId=22373518&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22373518).

**Comment by xueli181114** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
