### PR TITLE
BZ-2097619-4-11 update vSphere driver version in 4.11

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
This is one of three PRs for this BZ, each documenting a different version of a third-party storage driver specific to each major OpenShift release.

Version(s):
PR applies to: 4.11

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2097619

Link to docs preview:
https://51369--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html#overview

Additional information:
https://github.com/openshift/openshift-docs/pull/51384
https://github.com/openshift/openshift-docs/pull/51371

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@gnufied Let me know if looks good to you, please. TY!

**Comment by Amrita42** [comment]
@ShaunaDiaz for 4.10 and 4.11 PRs , please create a feature branch from enterprise 4.10 and 4.11 respectively. For 4.12 its fine as is since main and enterprise 4.12 are ideally supposed to be identical.

**Comment by ShaunaDiaz** [comment]
Replaced with https://github.com/openshift/openshift-docs/pull/51385 per peer review.

**Pull request closed without merging**
