### PR TITLE
[WIP]Topology manager improvements

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/OSDOCS-1564

Continuous improvement task independent of 4.6 GA work

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vpickard Can you please take a look and offer suggestions for further improvements? Part of the request in https://issues.redhat.com/browse/OSDOCS-1564 is to improve the examples and to give better indication of when to use Topology Manager vs CPU Manager. I need some guidance there. Thanks!

cc @jtudelag

**Comment by vpickard** [comment]
@ahardin-rh I have added @fromanirh  as well. One or both of us should be able to help clean this up

**Comment by fromanirh** [comment]
ack. I will have a look ASAP next week.

**Comment by ahardin-rh** [comment]
@fromanirh  @vpickard Thanks so much in advance!

**Comment by jtudelag** [comment]
Hey, thanks @ahardin-rh for this!

Could we include this article [1] as reference? I know it might a bit old, but the explanation of what is Numa and the graphical examples are really good.

Also, the k8s docs in which we have based our docs are updated as well https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/#how-topology-manager-works, and include new sections/info.

Thanks!

[1] https://kubernetes.io/blog/2020/04/01/kubernetes-1-18-feature-topoloy-manager-beta/

**Comment by ahardin-rh** [comment]
@jtudelag @vpickard @fromanirh Wow, sorry this PR has been neglected. I'd like to pick this back up. Is the aim of the PR still relevant? Looking forward to finally closing this out. Thanks!

**Comment by ahardin-rh** [comment]
Closing this, but saving the notes and hope to revisit post-4.8 GA

**Pull request closed without merging**
