### PR TITLE
Update CAM installation for 4.4

### PR DESCRIPTION
**Pull request by apinnick**
Small UI changes in Operator installation.
CP for 4.4 and 4.5.

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!  @apinnick is there an issue or bug tied to this PR? Are QE and SME reviews needed?

**Comment by apinnick** [comment]
@bmcelvee No more reviews needed and no bugs created. These are only updates to align with the new 4.4 console. Thanks.

**Comment by bmcelvee** [comment]
Thanks! Sounds good. I'll go ahead with the merge + cherry pick.

**Pull request merged**
