### PR TITLE
Doc update: ROUTER_SYSLOG_FORMAT environment variable

### PR DESCRIPTION
**Pull request by louyihua**
This is the corresponding document update for Openshift PR https://github.com/openshift/origin/pull/13029.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@louyihua These changes look good to me. Thank you! I will wait for the Origin PR to merge before merging this.

@knobunc Is this relevant for earlier versions of OCP as well? Please double-check my labeling. Thanks!

**Comment by knobunc** [comment]
@ahardin-rh I just kicked the merge for the feature.  This will be 3.6 only.  Thanks!

**Comment by knobunc** [comment]
BTW the docs look good to me too.  Thanks @louyihua

**Comment by ahardin-rh** [comment]
@louyihua Looks like this needs a rebase, then I can merge. Thanks!

**Comment by louyihua** [comment]
@ahardin-rh Rebased

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/router.adoc#admin-guide-router[Monitoring and Debugging Routers]
|Described the `ROUTER_SYSLOG_FORMAT` environment variable.
%
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Described the `ROUTER_SYSLOG_FORMAT` environment variable.
%

**Pull request merged**
