### PR TITLE
Updated instances of svc to ksvc for 1.10.0 release

### PR DESCRIPTION
**Pull request by abrennan89**
@maschmid this is the PR to update for [SRVCOM-1066](https://issues.redhat.com/browse/SRVCOM-1066)
Not sure if all the instance apply, let me know if I need to revert any of these to `svc` or if you think I've missed any.
Thanks!

### CODE REVIEW

**Review by navidshaikh — APPROVED** [review]
lgtm

**Review by rhuss — COMMENTED** [review]
Thanks for the update, looks good to me.

The only thing you might want to update that for a Knative service you can completely omit the prefix. I.e. anything without a prefix is considered to be a knative service.

**Comment by maschmid** [comment]
QE approved

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
