### PR TITLE
OSDOCS#7528: Release note for PSA sync being disabled if PSA labels a…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…re modified

Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-7528

Link to docs preview:
https://64419--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-auth-psa-disable-sync-modified

QE review:
- [ ] QE has approved this change.

Additional information:

**The xref won't jump to the proper section until PR #64343 is merged.**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@gkarager Can you please review this release note entry?  Note that the link at the bottom won't jump to the correct section until #64343 is merged. Thanks!

Preview: https://64419--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-auth-psa-disable-sync-modified

**Review by jeana-redhat — APPROVED** [review]
LGTM, verified link with accompanying PR

/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
