### PR TITLE
Bug 1467361, Added  openshift_master_audit_config details

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1467361

@abutcher PTAL

### CODE REVIEW

**Review by abutcher — APPROVED** [review]

**Comment by ahardin-rh** [comment]
@openshift/team-documentation PTAL

**Comment by mburke5678** [comment]
@ahardin-rh LGTM

**Comment by bfallonf** [comment]
@ahardin-rh LGTM :car:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing a Cluster -> Advanced Installation]
|Added `openshift_master_audit_config` details.
%
|xref:../install_config/master_node_configuration.adoc#install-config-master-node-configuration[Master and Node Configuration]
|Expanded `openshift_master_audit_config` details.
%

**Pull request merged**
