### PR TITLE
OCPBUGS#32766 Fixing Service Telemetry Operator status for OKE

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-32766

Link to docs preview:
https://75043--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/oke_about.html#feature-summary

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ayefimov-1** [comment]
STO is not tests nor supported for OKE.

**Review by jneczypor — COMMENTED** [review]
lgtm. Because I am new to Peer Review, @michaelryanpeter will follow after with his review. Thank you for your patience!

**Comment by michaelryanpeter** [comment]
LGTM

**Pull request merged**
