### PR TITLE
adds/organizes several cloud provider name attributes

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11+

Issue:
N/A

Link to docs preview:
see [Files changed](https://github.com/openshift/openshift-docs/pull/67161/files)

QE review:
N/A

Additional information:
Proposed for the sake of standardization/typo reduction

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by jeana-redhat** [comment]
rebase/refresh pre-merge

**Pull request merged**
