### PR TITLE
OADP-512 Remove grep from `oc exec .. velero` examples

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
[OADP-512](https://issues.redhat.com//browse/OADP-512) Remove grep from `oc exec .. velero` examples

https://issues.redhat.com/browse/OADP-512

OCP 4.x from 4.6

Preview:

### CODE REVIEW

**Comment by mperetzred** [comment]
ack

**Comment by mperetzred** [comment]
@sbeskin-redhat same, yes, but it's MTC docs, I'm not sure if it's suppose to be on the same PR.
nm :)

**Comment by mperetzred** [comment]
ack

**Comment by RichardHoch** [comment]
1. General note: Squash your commits before asking for peer review.
2. You did not include any previews, so I cannot see if any commands are longer than the width of a page. If they are, break the lines with a \ and indent the next line two spaces.
So instead of $ shell command and more more and more this should be the next line, you have  

$ shell command and more more and more \ 
  this should be the next line
  
 Aside from that, lgtm -- so please fix any lines that are too long, squash your commits, and send the PR to the OCP docs squad. No need for me to review this again.

**Review by kaovilai — APPROVED** [review]

**Pull request merged**
