### PR TITLE
Fix HW offload supported devices table format

### PR DESCRIPTION
**Pull request by cgoncalves**
Format issue introduced in main (https://github.com/openshift/openshift-docs/pull/57126) as part of 4.13 development cycle. 

Version(s): main, 4.14, 4.13

Issue:

Link to docs preview:
https://62167--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/configuring-hardware-offloading.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by cgoncalves** [comment]
@jboxman-rh  @openshift/team-documentation please review

**Comment by jab-rh** [comment]
@cgoncalves, LGTM, thanks!

**Pull request merged**
