### PR TITLE
Update the doc to restart the cluster gracefully

### PR DESCRIPTION
**Pull request by ShreyaSharma-shrsharm**
Update the doc to restart the cluster gracefully

Version(s):
4.13

Issue:
[OSDOCS-11571](https://issues.redhat.com/browse/OSDOCS-11571)

Link to docs preview:

https://79928--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/graceful-cluster-restart.html

QE review:
- [ ] QE has approved this change.

Additional information:

Opening this PR specifically for version 4.13 since the main [PR](https://github.com/openshift/openshift-docs/pull/79928) got merged for version 4.16+ but 4.12-4.15 didn't cherry-pick cleanly.

### CODE REVIEW

**Comment by mramendi** [comment]
This PR is empty, please check

**Review by bergerhoffer — COMMENTED** [review]
Same comment as https://github.com/openshift/openshift-docs/pull/80656#pullrequestreview-2248303243

Please close this one and try again based on the advice in that comment

**Pull request closed without merging**
