### PR TITLE
Enhance must-gather to collect more node logs

### PR DESCRIPTION
**Pull request by mburke5678**
https://jira.coreos.com/browse/OSDOCS-733

### CODE REVIEW

**Comment by mburke5678** [comment]
@rphillips PTAL. I hope this is a tiny change.
For must-gather, at this time we are simply listing the types of information that must-gather gathers [1] and how to install. For Node, is listing _node logs_ sufficient?

[1] https://docs.openshift.com/container-platform/4.2/support/gathering-cluster-data.html

**Comment by rphillips** [comment]
must-gather is already gathering the node/kubelet logs. The idea is to add some more files to the must-gather, namely the crio, kubelet, and registries configuration on the host.

**Comment by mburke5678** [comment]
DO NOT MERGE pending https://jira.coreos.com/browse/NODE-158

**Comment by mburke5678** [comment]
Closing as the dev Jira is obsolete

**Pull request closed without merging**
