### PR TITLE
Add documentation about experimental registry feature

### PR DESCRIPTION
**Pull request by bmcelvee**
Signed-off-by: Gladkov Alexey <agladkov@redhat.com>

Recovered from https://github.com/openshift/openshift-docs/pull/13564

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bmcelvee which BZ or Jira is this for? Set this to QE and peer review?

**Comment by vikram-redhat** [comment]
@bmcelvee bump.

**Comment by vikram-redhat** [comment]
@bmcelvee hey -  can this be merged/closed or can I change the target branch to enterprise-3.11?

**Comment by bmcelvee** [comment]
I'm sorry for letting this one hang on. I'll request QE review and get it merged.

**Comment by bmcelvee** [comment]
@wzheng1 would you mind reviewing this PR please? Thanks!

**Pull request closed without merging**
