### PR TITLE
Bug 1908750 - 'queuedChunkLimitSize' parameter not getting applied in… [enterprise-4.5][enterprise-4.6][enterprise-4.7]

### PR DESCRIPTION
**Pull request by rolfedh**
… clusterlogging instance
https://bugzilla.redhat.com/show_bug.cgi?id=1908750

### CODE REVIEW

**Comment by rolfedh** [comment]
@periklis Please review and mark as LGTM.

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
LGTM! We can merge as soon as we have QE approval. Thanks!

**Comment by rolfedh** [comment]
@anpingli Please review and approve this minor change for https://bugzilla.redhat.com/show_bug.cgi?id=1908750

**Comment by QiaolingTang** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
Cherry-pick to 4.5 failed because the updated file does not exist in that version. Removing the enterprise-4.5 label.

**Pull request merged**
