### PR TITLE
Remove 'clusterID' from ShiftStack install-config.yaml mods

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR resolves https://bugzilla.redhat.com/show_bug.cgi?id=1916088

### CODE REVIEW

**Comment by maxwelldb** [comment]
@iamemilio Any disagreements with this? It seems like `clusterID` isn't part of the upstream docs, so I'd assume not.

**Comment by maxwelldb** [comment]
Taking that as a no. Promoting to QE.

**Comment by iamemilio** [comment]
lgtm

**Comment by maxwelldb** [comment]
@iamemilio TY!

**Comment by wjiangjay** [comment]
lgtm

**Comment by maxwelldb** [comment]
@wjiangjay Thanks!

**Comment by maxwelldb** [comment]
@openshift/team-documentation Small change in need of review. TY!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by maxwelldb** [comment]
@kalexand-rh TY.

**Pull request merged**
