### PR TITLE
ROX18664: Removed TP for the new collection Method

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.2+

Issue: [ROX-18664](https://issues.redhat.com/browse/ROX-18664)

Link to docs preview: [Preview 1](https://63891--docspreview.netlify.app/openshift-acs/latest/installing/installing_other/install-secured-cluster-other#secured-cluster-services-config_install-secured-cluster-other)- Check the table for collection method.

QE review not necessary.

SME review:
- [x] SME has approved the changes. 

Additional information: Needs to be cherry-picked into rhacs-docs-4.2

### CODE REVIEW

**Comment by kcarmichael08** [comment]
LGTM! 

Let's get an OK from @robbycochran to confirm that it's in 4.2 as a regular feature and it's OK to remove the Tech Preview language.

**Comment by robbycochran** [comment]
Yes, CORE ebpf will be a regular feature in 4.2

**Review by robbycochran — APPROVED** [review]

**Comment by robbycochran** [comment]
CC: @Stringy

**Pull request merged**
