### PR TITLE
modules/master-node-sizing: Raise CPU/memory cap from <=50% to <=60%

### PR DESCRIPTION
**Pull request by wking**
The outgoing "half" is from 7eb9504406 (#32230), with the sense fixed in 4c7a9552b8 (#34338).  But `HighOverallControlPlaneCPU` has [a `>60` trigger][1] [since it landed][2] [in 4.8][3].  It doesn't seem like we have a high-memory alert set yet.  But the idea is that if you take down one of three control plane nodes, the CPU usage on the others can be expected to rise by 50% (e.g. from 66% to 100%).  60 and 66 are pretty close together, probably not worth worrying about that.  50 and 60 aren't all that far apart either.  So I'm not all that particular about where the threshold is, but it makes sense to have the docs and the alerts agree on the chosen threshold.

[1]: https://github.com/openshift/cluster-kube-apiserver-operator/blame/4b25a7a948fd53b96a815c6012db911721c43744/bindata/assets/alerts/cpu-utilization.yaml#L29
[2]: https://github.com/openshift/cluster-kube-apiserver-operator/commit/21fedd4ddc25bf4072bdb1bd095fa40cd771f3fb#diff-aeaff49462b4a42ff78d32aa7c7fefeb9b772b9b8ba65067f4bed9d283a6a847R31
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1949306#c7

Preview: https://deploy-preview-43637--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#master-node-sizing_

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
LGTM! 

There is something odd going on with the URL (`https://deploy-preview-43637--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#master-node-sizing_` <-that underscore), but 1) it's not hurting anything and 2) it's not your problem :wink: Mentioning in hopes that I remember to look into it later.

**Comment by ahardin-rh** [comment]
@mffiedler Can you please provide a QE review or point us to the correct contact? Thanks so much!
@mohit-sheth PTAL as well. Thanks!

**Review by mffiedler — APPROVED** [review]
LGTM

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
Thank you, all!

**Pull request merged**
