### PR TITLE
BZ-2010700: Updated module to note that Secure Boot requires Redfish.

### PR DESCRIPTION
**Pull request by johnwilkins**
Updated module to note that Secure Boot requires Redfish.

See https://bugzilla.redhat.com/show_bug.cgi?id=2010700 for additional details.

Release: 4.8 and 4.9

Preview URL: N/A. Modified assembly to remove conditional text in another PR. Avoiding the otherwise inevitable merge conflict.

Signed-off-by: John Wilkins <jowilkin@redhat.com>

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
Nice, thank you!

**Review by mikemckiernan — COMMENTED** [review]
nits, please let me know what I can clarify.

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

Thanks for the tweaks.

**Pull request merged**
