### PR TITLE
Updates cluster MTU change docs for correct output

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-31918

Link to docs preview:
https://75195--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/changing-cluster-network-mtu.html#nw-cluster-mtu-change_changing-cluster-network-mtu

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anuragthehatter** [comment]
/lgtm

Thanks

**Review by jneczypor — COMMENTED** [review]
LGTM. I'm still onboarding, so another member of the review squad will follow after with their review. Thanks for your patience!

**Pull request merged**
