### PR TITLE
Changed HPA example for specific CPU

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/24646

### CODE REVIEW

**Comment by mburke5678** [comment]
@weinliu You have reviewed this module previously. Can you take a look at this suggested change?

**Comment by weinliu** [comment]
Good catch.. the updates /lgtm

**Comment by bmcelvee** [comment]
LGTM! :snowman:

**Comment by mburke5678** [comment]
@weinliu Thanks for the quick review!

**Pull request merged**
