### PR TITLE
[enterprise-4.13] CNV-27208

### PR DESCRIPTION
**Pull request by aspauldi**
Cherry-picked from 8dd90098a0f9ceaf49bbb1ba440294d6fdd41fc2 
xref: https://github.com/openshift/openshift-docs/pull/60623

### CODE REVIEW

**Comment by aspauldi** [comment]
(First time doing a manual cherry pick; let me know if I need to do something else. Thanks!)

**Comment by ousleyp** [comment]
LGTM! Full marks on your first manual CP :)

**Pull request merged**
