### PR TITLE
OCPBUGS#8957: Remove the double quotes

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OCPBUGS-8957

Link to docs preview: https://57141--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-user-infra-rhcos_installing-gcp-user-infra

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by gpei** [comment]
@jianli-wei could you help to check it?

**Review by jianli-wei — APPROVED** [review]
/lgtm

**Pull request merged**
