### PR TITLE
BZ2077574 Remove SRO Using Templates

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.9, 4.10, 4.11

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2077574
(This issue is high priority)

Link to docs preview: https://deploy-preview-44898--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#using-the-special-resource-operator_special-resource-operator

Additional information:
This information will be in effect in OCP going forward.

### CODE REVIEW

**Comment by tmalove** [comment]
LGTM!

**Review by tmalove — COMMENTED** [review]
LGTM!

**Review by jeana-redhat — APPROVED** [review]
LGTM but Travis won't check it :(

**Comment by GroceryBoyJr** [comment]
Walking through push process to see if I can restart Travis checks this morning.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM ("Review Changes" to awake Travis CI. This did not work.)

**Pull request merged**
