### PR TITLE
6894-3scaleIstioAdapterUpdates: Added updates for the procedure to configure the integration setting in 3scale

### PR DESCRIPTION
**Pull request by dfennessy**
This pull requested is based on [THREESCALE-6894](https://issues.redhat.com/browse/THREESCALE-6894)

Reviewers

@unleashed
@neal-timpe
@JStickler

Reviewed previously in this closed PR https://github.com/openshift/openshift-docs/pull/32951

### CODE REVIEW

**Comment by unleashed** [comment]
@dfennessy I think it would be beneficial to take the suggestion from the ticket about a troubleshooting section.

**Comment by dfennessy** [comment]
> @dfennessy I think it would be beneficial to take the suggestion from the ticket about a troubleshooting section.

Hi @unleashed 

Taking what I have in the comment from Laurent, this is a list of issues for which I've no context how to solve. Do we have procedures anywhere that cover these scenarios or do I have to recreate each one and figure out how to document the "fix"?

**Comment by dfennessy** [comment]
> > @dfennessy I think it would be beneficial to take the suggestion from the ticket about a troubleshooting section.
> 
> Hi @unleashed
> 
> Taking what I have in the [comment from Laurent](https://issues.redhat.com/browse/THREESCALE-6894?focusedCommentId=16380286&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16380286), this is a list of issues for which I've no context how to solve. Do we have procedures anywhere that cover these scenarios or do I have to recreate each one and figure out how to document the "fix"?

Under discussion with 3scale docs team, we decided that the content here is ready to be merged as is. @JStickler, unless you have some more comments to add, please go ahead with the merge of this.

@unleashed For the new troubleshooting section for the documentation, another JIRA will have to be created with the relevant title/description/information...

**Comment by unleashed** [comment]
> Taking what I have in the [comment from Laurent](https://issues.redhat.com/browse/THREESCALE-6894?focusedCommentId=16380286&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16380286), this is a list of issues for which I've no context how to solve. Do we have procedures anywhere that cover these scenarios or do I have to recreate each one and figure out how to document the "fix"?

No, this should be a small section at the end of the 3scale adapter specific docs (or any other part where you consider it is appropriate) that the reader can refer to when they are stuck, and there's no additional context than that list of items listed in the JIRA issue.

There's another request by Laurent to include a very basic smoke test that could read like the text below:

> You can perform the following steps to ensure the adapter is working correctly:
>
> 1. Ensure the 3scale-adapter pod is running in the control plane namespace (ie. `istio-system`).
> 2. Check that the 3scale-adapter pod has printed out information about itself booting up, such as its version.
> 3. When performing requests to the services protected by the 3scale adapter integration, always try requests that lack the right credentials and ensure they fail. Check out the 3scale adapter logs to gather additional information.
>
> If the steps above don't help, please check out the Troubleshooting section [below / reference].

Regarding where to place this, I'd say right before that troubleshooting section and after the configuration has been explained.

**Pull request merged**
