### PR TITLE
Adding golang language detection to docs

### PR DESCRIPTION
**Pull request by coreydaley**
Supported by https://github.com/openshift/origin/commit/77b08ef346ea6d2dd9003cb93f17448f8a07695e

### CODE REVIEW

**Comment by coreydaley** [comment]
@ahardin-rh please take a look

**Comment by ahardin-rh** [comment]
@coreydaley LGTM! Is this targeted for 3.5, or can it also go into 3.4? Thanks!

**Comment by coreydaley** [comment]
I don't believe it's going to be in 3.4, just 3.5
Thanks!

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/application_lifecycle/new_app.adoc#dev-guide-new-app[Application Life Cycle Management -> Creating New Applications]
|Added golang to the xref:../dev_guide/application_lifecycle/new_app.adoc#language-detection[Languages Detected by `new-app`] table.
%

**Pull request merged**
