### PR TITLE
Added Rotuter Variables for version 3.4

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Added Router variables for 3.4 https://github.com/openshift/openshift-docs/pull/3090#issuecomment-261547009

### CODE REVIEW

**Comment by adellape** [comment]
@gaurav-nelson This could probably use `dedicated` and `online` labels, considering https://github.com/openshift/openshift-docs/pull/3090 and https://github.com/openshift/openshift-docs/pull/3258 did?

**Comment by gaurav-nelson** [comment]
Thanks @adellape 
@vikram-redhat can you please confirm?

**Comment by vikram-redhat** [comment]
@gaurav-nelson - Yes that is correct. It should have the online and dedicated labels and marked with future release.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - might require a rev history. See: https://gitlab.cee.redhat.com/vigoyal/openshift-release-script#revision-history-format

**Comment by gaurav-nelson** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added two new parameters under Configuration Parameters in the xref:../architecture/core_concepts/routes.adoc#haproxy-template-router[HAProxy Template Router] section.
%

**Pull request merged**
