### PR TITLE
Change `service.alpha.openshift.io` to `service.beta.openshift.io`

### PR DESCRIPTION
**Pull request by mburke5678**
Per [Slack conversation](https://coreos.slack.com/archives/C2ZA5QGMV/p1636264482021400).

### CODE REVIEW

**Comment by mburke5678** [comment]
@deads2k PTAL

**Comment by mburke5678** [comment]
@s-urbaniak @stlaz David Eads suggested you could take a look at this PR for me. Thank you in advance!

**Comment by stlaz** [comment]
looks good

**Comment by mburke5678** [comment]
@y4sht Are you still the QE resource for the Authentication team? Can you take a look at this PR? Thank you in advance.

**Comment by mburke5678** [comment]
@lmurthyrh Can you please assign a QE resource for this PR? Thank you!

**Comment by sagidlow** [comment]
LGTM!

**Pull request merged**
