### PR TITLE
Fix for SRVKS-612: HTTP2 / gRPC

### PR DESCRIPTION
**Pull request by abrennan89**
OCP 4.5+
cc @nak3 for review

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

Thank you @abrennan89

**Comment by mgencur** [comment]
QE Approved

**Comment by bobfuru** [comment]
A few comments and suggestions but overall looks good!

**Review by bobfuru — COMMENTED** [review]
Hope this time works!

**Comment by abrennan89** [comment]
Thanks a million @bobfuru !
The feedback should all be addressed now if you want to take another look, but this doesn't need to be merged until our release next week AFAIK. I'll stick it in the Slack channel when it needs to be merged if that's OK :slightly_smiling_face:

**Comment by bobfuru** [comment]
LGTM and yeah, let the squad know when it's ready to be merged next week, thanks!

**Pull request merged**
