### PR TITLE
fix vSphere MachineSet issue #27437

### LINKED ISSUE #27437: [enterprise-4.6] Issue in file machine_management/creating-infrastructure-machinesets.adoc
### Which section(s) is the issue in?
Sample YAML for a MachineSet Custom Resource on vSphere

### What needs fixing?
the example yaml is not valid, causing cases for customers that follow the example.

### PR DESCRIPTION
**Pull request by annelson-rh**

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma can you confirm? Thanks!

**Comment by jinyunma** [comment]
@sunzhaohua2 could you help to review at this PR? thanks.

**Comment by jinyunma** [comment]
@miyadav could you please help to review this PR since Zhaohua is PTO this week? thanks.

**Review by codyhoag — APPROVED** [review]
I built this locally and it looks good. Thanks @annelson-rh for the fix!

**Pull request merged**
