### PR TITLE
backupStorageLocation ns should be consistent with Backup

### PR DESCRIPTION
**Pull request by lance5890**
Version(s):

4.12
Issue:

https://github.com/openshift/openshift-docs/issues/56873
Link to docs preview:

https://56874--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lance5890** [comment]
@lahinson @geliu2016 @dymurray

**Comment by lahinson** [comment]
LGTM

**Comment by lance5890** [comment]
@kaovilai

**Review by kaovilai — APPROVED** [review]
/lgtm

**Comment by lpettyjo** [comment]
@lance5890 do you need this in 4.12 only? Or 4.12 and 4.13 as well? Otherwise, you are good to merge.

**Comment by lance5890** [comment]
> @lance5890 do you need this in 4.12 only? Or 4.12 and 4.13 as well? Otherwise, you are good to merge.

I think this problem exists both in 4.13 and 4.12,  maybe 4.11 , we should  merge this in all related releases

**Comment by lance5890** [comment]
> > > @lance5890 do you need this in 4.12 only? Or 4.12 and 4.13 as well? Otherwise, you are good to merge.
> > 
> > 
> > I think this problem exists both in 4.13 and 4.12, maybe 4.11 , we should merge this in all related releases
> 
> @lance5890 Can you confirm that it should be merged to 4.11?

i have confirmed 4.11 has this problem too

**Comment by lpettyjo** [comment]
@geliu2016 can you please confirm all releases that this PR should be merged into? So far, we think it is 4.11, 4.12, and 4.13. Thanks!

**Comment by geliu2016** [comment]
> @geliu2016 can you please confirm all releases that this PR should be merged into? So far, we think it is 4.11, 4.12, and 4.13. Thanks!

Yes, lgtm

**Pull request merged**
