### PR TITLE
[OSDOCS-7925]: Restructure troubleshooting modules and add boilerplate to debug nodes module

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-7925

Link to docs preview: https://65263--docspreview.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-troubleshooting

QE review:
- [x] QE has approved this change.

**Note to reviewers**: The purpose of this PR is mainly to restructure content that has already been peer reviewed. Very little content was changed.

Additional information: The "Troubleshooting worker node issues" topic does not contain the Technology Preview boilerplate. It needs that boilerplate language because it is about hosted control planes on AWS, which is a Technology Preview feature for OCP 4.14.

Also, consider the placement of this topic. Currently, it is an assembly with one module. If we don't expect to add more modules about troubleshooting worker nodes, we might be able to restructure the "Troubleshooting worker nodes" assembly to a "Troubleshooting hosted control planes" assembly, and move all of the troubleshooting content there.

### CODE REVIEW

**Comment by lahinson** [comment]
@xenolinux PTAL at this PR when you can and let me know what you think. Thanks!

**Comment by xenolinux** [comment]
> @xenolinux PTAL at this PR when you can and let me know what you think. Thanks!

@lahinson It looks good to me. Thank you!!

**Pull request merged**
