### PR TITLE
Bug 1421811 Added subdomain file

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1421811

### CODE REVIEW

**Comment by bmcelvee** [comment]
@ahardin-rh @mburke5678 peer review please! 😸

**Comment by ahardin-rh** [comment]
@bmcelvee LGTM! As for the labels and milestone, if this is for the next weekly release, you can drop the 3.5 label for now. If this is targeted for when 3.5 is released, you can update the milestone to Future Release. :rainbow:

**Comment by bmcelvee** [comment]
Thank you, @ahardin-rh!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/install/stand_alone_registry.adoc#install-config-installing-stand-alone-registry[Installing a Stand-alone Registry]
|Added openshift_master_default_subdomain to the openshift_master_default_subdomain file in the xref:../install_config/install/stand_alone_registry.adoc#registry-advanced-installation[Advanced Installation for Stand-alone Registries] section.
%

**Pull request merged**
