### PR TITLE
RuntimeClass example uses wrong API version

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OCPBUGS-27036

Preview
[Creating a RuntimeClass object to encapsulate scheduling mechanisms](https://71716--ocpdocs-pr.netlify.app/openshift-enterprise/latest/windows_containers/scheduling-windows-workloads#creating-runtimeclass_scheduling-windows-workloads) -- Updated API in Step 1 code example.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio Is this an issue you can review or assign to someone who can? Thank you in advance.

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
