### PR TITLE
Fix typos in updating documentation

### PR DESCRIPTION
**Pull request by petr-muller**
Version(s): 4.12

Issue: N/A

Link to docs preview: 

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tmalove** [comment]
@petr-muller  Will you provide a direct preview link so I can verify the renderings? Thanks!

**Comment by petr-muller** [comment]
@tmalove I'm not sure about what you're asking (it's my first PR here and I don't know the expectations). Are you just asking to direct links to the modified docs in https://github.com/openshift/openshift-docs/pull/54045#issuecomment-1359568194 ? If yes then I think it is:

https://54045--docspreview.netlify.app/openshift-enterprise/latest/updating/understanding-upgrade-channels-release.html

If you expect me do provide something else then pls advise what I need to do ;)

**Comment by tmalove** [comment]
@petr-muller Thanks for that direct link! So for your future OpenShift PRs, ensure that you include a direct link to your updates so the reviewer can verify that not only the asciidoc formatting is OK, but the final output looks fine as well. The self-generating preview link does not take you to the place where your updates were made. Also, I notice that you made your updates in 'main', but you specify that the version that should be updated is '4.12'. Should this update be in version 4.12 and later instead of just 4.12? Usually, if something is for a particular version, it is a release note or an update for a particular branch(es). Let me know if you have any more questions!

**Comment by petr-muller** [comment]
@tmalove it should be 4.12 and later. Also, how do PRs get merged? Is there anything else I need to do on my side?

**Review by jldohmann — APPROVED** [review]

**Pull request merged**
