### PR TITLE
GH#40734: adding passthrough route as tlsinspectdelay option to docs

### PR DESCRIPTION
**Pull request by skrthomas**
Fix for GH issue https://github.com/openshift/openshift-docs/issues/40734

Preview: https://deploy-preview-42568--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress

SME request in [Slack discussion](https://coreos.slack.com/archives/CCH60A77E/p1642541682036000?thread_ts=1642539370.035300&cid=CCH60A77E) thread.

@lihongan @quarterpin  can you QE this docs update please? 

Applies to 4.9+

### CODE REVIEW

**Comment by skrthomas** [comment]
@sairameshv @steveteahan if all looks ok here (Steve I saw your thumbs up) can you plz leave a lgtm in the comments of this PR?

**Comment by lihongan** [comment]
@quarterpin Could you help take a look ? thanks

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by quarterpin** [comment]
/lgtm
looks good!

**Comment by mburke5678** [comment]
@skrthomas LGTM

**Pull request merged**
