### PR TITLE
OSDOCS-4330: Content review for Managing bare metal hosts

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.9+

Issue:
https://issues.redhat.com/browse/OSDOCS-4330

Link to docs preview:
https://57694--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/managing-bare-metal-hosts.html

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by yanpzhan** [comment]
LGTM from QE side.

**Pull request merged**
