### PR TITLE
OSDOCS-6953: Make S3 deletion optional for AWS

### PR DESCRIPTION
**Pull request by nalhadef**
[OSDOCS-6953](https://issues.redhat.com//browse/OSDOCS-6953): Make S3 deletion optional for AWS

Apply to Main

Version(s):4.14

Issue:
https://github.com/openshift/installer/pull/7288
https://issues.redhat.com/browse/OSDOCS-6953

Link to docs preview:
[See Table 4 in Installing  a cluster on AWS with customizations](https://63652--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations) - Updated August 24.

QE reviewer: [Jianlin Liu](jialiu@redhat.com)
- [x] QE has approved this change.

Additional Reviewers: [Aditya Narayanaswamy](https://github.com/rna-afk), [Ben Scott](bscott@redhat.com)

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @yunjiang29 to review.

**Comment by nalhadef** [comment]
Thanks, Jianlin!

**Comment by nalhadef** [comment]
Thanks, Yunfei!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
