### PR TITLE
Edit suggested in file logging/efk-logging-deploying.adoc

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/19436

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli Tiny change. I have a request to add the `source` parameter to the CSC for installing Elasticsearch in 4.1. Can you confirm if the source should be `source: "elasticsearch"` or `source: "redhat-operators"`?

**Comment by QiaolingTang** [comment]
> @QiaolingTang Tiny change. I have a request to add the `source` parameter to the CSC for installing Elasticsearch in 4.1. Can you confirm if the source should be `source: "elasticsearch"` or `source: "redhat-operators"`?

it should be `source: "redhat-operators"`

**Review by anpingli — COMMENTED** [review]
@mburke5678  The source should be elasticsearch here.   it is the name defined in the catalogsource above.

**Comment by QiaolingTang** [comment]
> @mburke5678 The source should be elasticsearch here. it is the name defined in the catalogsource above.

@anpingli I think you may confuse CSC and SUB, for CSC, the source is the operator source, for the subscription, the source is the catalog source. The change is for the CSC.  What you said is for the sub. https://github.com/openshift-qe/v3-testfiles/blob/master/logging/eleasticsearch/deploy_via_olm/4.1/05_eo-sub.yaml#L12

**Comment by anpingli** [comment]
@QiaolingTang  You are right.  @mburke5678  Ignore my comment.  The PR is done.

**Pull request merged**
