### PR TITLE
vSphere - remove bullet statement about multiple dc, clusters

### PR DESCRIPTION
**Pull request by jcpowermac**
This has been resolved since July and is causing customer
confusion. Removing bullet.

See: https://github.com/openshift/installer/pull/3863

### CODE REVIEW

**Comment by jcpowermac** [comment]
cc: 
@bobfuru 
@rna-afk 
@patrickdillon 
@jstuever

**Comment by bobfuru** [comment]
Thanks, @jcpowermac LGTM!
Can you confirm that this now applies to all OCP 4.x versions?

**Comment by jcpowermac** [comment]
> Thanks, @jcpowermac LGTM!
> Can you confirm that this now applies to all OCP 4.x versions?

Should be cherry-picked through 4.5 - 4.7

**Comment by bobfuru** [comment]
> > Thanks, @jcpowermac LGTM!
> > Can you confirm that this now applies to all OCP 4.x versions?
> 
> Should be cherry-picked through 4.5 - 4.7

Thanks - I'll also add 4.8 because that branch is now open, too.

**Comment by bobfuru** [comment]
@jcpowermac Let me know if this is ready to merge/CP and I can take care of that.

**Comment by patrickdillon** [comment]
LGTM too

**Comment by jcpowermac** [comment]
Thanks @patrickdillon !
@bobfuru I think we are good

**Comment by bobfuru** [comment]
All set, @jcpowermac - thanks again.

**Pull request merged**
