### PR TITLE
Issue 3366 edited out reference to OpenShift Enterprise

### PR DESCRIPTION
**Pull request by bfallonf**
As per #3366 

@nhr @adellape any qualms? I'm not sure if there's a better way to word what Origin is.

### CODE REVIEW

**Comment by nhr** [comment]
+1 - Works for me.

**Comment by bfallonf** [comment]
Ok. I'll merge away.

Unless @aheslin , you have any issues? ( @vikram-redhat said to check with you).

Hope the tags are right!

**Comment by aheslin** [comment]
@bfallonf That works for me.

**Comment by bfallonf** [comment]
Thanks @aheslin 

No rev history needed.

**Pull request merged**
