### PR TITLE
#CNV-36461 - rearrange map

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.15+

Issue: [CNV-36461](https://issues.redhat.com//browse/CNV-36461)

Link to docs preview:

QE review: not needed - just rearranging two things on the map

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
