### PR TITLE
Fix typo : secrets is an array

### PR DESCRIPTION
**Pull request by florianorpeliere**

### CODE REVIEW

**Comment by vbehar** [comment]
up ?

we have people facing the same issue each time they try to copy/paste from the doc.

thanks ;-)

**Comment by SiegfriedEhret** [comment]
Yes please !

**Comment by adellape** [comment]
@florianorpeliere The alignment for `name: secret-npmrc` has gotten off. This works (and is how OpenShift reformats it):

```
  source:
    git:
      uri: https://github.com/adellape/nodejs-ex.git
    secrets:
    - secret:
        name: secret-npmrc
    type: Git
```

**Comment by florianorpeliere** [comment]
@adellape Normally it's good this time ;)

**Comment by adellape** [comment]
:+1: Thanks.

**Pull request merged**
