### PR TITLE
OBSDOCS-1090-Logging 5.7.15 Release Notes

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Logging Z-Stream Release Notes - 5.7.15
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-1090

Fix Version: 4.12, 4.13, 4.14

Doc Preview: https://77213--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-7-release-notes.html#logging-release-notes-5-7-15_logging-5-7-release-notes

SME Review: @periklis 
QE Review: @anpingli 
Peer Review:

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
LGTM

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by shreyasiddhartha** [comment]
> /lgtm

Made the same changes matching your comments in the 5.8.8 PR.

**Pull request merged**
