### PR TITLE
GH#54189

### LINKED ISSUE #54189: [enterprise-4.11] Issue in file security/container_security/security-understanding.adoc
### Which section(s) is the issue in?
`What is OpenShift Container Platform?`

### What needs fixing?
The link "[OpenShift Security Guide](https://access.redhat.com/articles/5059881)" goes to a page that says "This resource has moved. Please update your bookmarks". The link should go directly to https://www.redhat.com/en/resources/openshift-security-guide-ebook instead.

### PR DESCRIPTION
**Pull request by reftel**
Update link to ebook

Version(s):
4.11

Issue:
fixes #54189

Link to docs preview:

QE review:
The change does not impact the meaning of the docs.

### CODE REVIEW

**Comment by reftel** [comment]
@openshift/team-documentation

**Review by kalexand-rh — COMMENTED** [review]
This change LGTM! Thank you for making this update. :)

**Pull request merged**
