### PR TITLE
OCPBUGS14271 correcting  the table

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OCPBUGS-14271

Link to docs preview:
https://61007--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jldohmann — APPROVED** [review]
LGTM. is this change just for 4.13, or did you mean 4.13+?

**Comment by jfrancoa** [comment]
LGTM The format of the table now looks good

**Comment by jmanthei** [comment]
https://github.com/openshift/openshift-docs/pull/61096

Fixed with another PR

**Pull request closed without merging**
