### PR TITLE
 [enterprise-4.11] OCPBUGS-10717 removing RHV warning that does not apply to generic

### PR DESCRIPTION
**Pull request by emarcusRH**
[OCPBUGS#10717](https://issues.redhat.com/browse/OCPBUGS-10717)

Version(s): 
enterprise-4.11
enterprise-4.10
enterprise-4.9

Issue:  remove mistaken admin

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by emarcusRH** [comment]
This PR removes an RHV note from a non-RHV module, and as such is in-line with typo-level doc updates. No dev or QE ack required.

**Comment by emarcusRH** [comment]
needs to be cherry-picked into enterprise-4.10 and enterprise-4.9

**Comment by jeana-redhat** [comment]
note that this is getting the changes from https://github.com/openshift/openshift-docs/pull/57659 into 4.9-4.11

**Pull request merged**
