### PR TITLE
OSDOCS-1808: Huge pages and Downward API

### PR DESCRIPTION
**Pull request by mikemckiernan**
One update, but in two parts:

* 4.8 enables the feature gate in k8s 1.21.  This helps
vanilla pods use Downward API with huge pages. This is mentioned in the Nodes area under heading [Support for huge pages with the Downward API](https://deploy-preview-31851--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-nodes-huge-pages-downward-api)

* SR-IOV Network Resource Injector automatically injects
pod specification fields to make use of the first bullet. This work is mentioned in the Networking area under heading [Enhancements to the SR-IOV Network Operator](https://deploy-preview-31851--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-enhancements-sriov-network-operator)

---
Applies to branch enterprise-4.8 and milestone Future Release.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
/assign @Billy99 
/assign @zshi-redhat 
/assign @zhaozhanqi 

PTAL.

**Review by dougbtv — APPROVED** [review]
/lgtm

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
