### PR TITLE
Updated kubevirt metrics names

### PR DESCRIPTION
**Pull request by sradco**
Updated kubevirt metrics names:

kubevirt_vmi_vcpu_wait_seconds to kubevirt_vmi_vcpu_wait_seconds_total

kubevirt_vmsnapshot_disks_restored_from_source_total to kubevirt_vmsnapshot_disks_restored_from_source

kubevirt_vmi_memory_swap_in_traffic_bytes_total to kubevirt_vmi_memory_swap_in_traffic_bytes

kubevirt_vmi_memory_swap_out_traffic_bytes_total to kubevirt_vmi_memory_swap_out_traffic_bytes

kubevirt_migrate_vmi_data_processed_bytes to kubevirt_vmi_migration_data_processed_bytes

kubevirt_migrate_vmi_data_remaining_bytes to kubevirt_vmi_migration_data_remaining_bytes

kubevirt_migrate_vmi_dirty_memory_rate_bytes to kubevirt_vmi_migration_memory_transfer_rate_bytes

kubevirt_migrate_vmi_pending_count to kubevirt_vmi_migrations_in_pending_phase

kubevirt_migrate_vmi_scheduling_count to kubevirt_vmi_migrations_in_scheduling_phase

kubevirt_migrate_vmi_running_count to kubevirt_vmi_migrations_in_running_phase

kubevirt_migrate_vmi_succeeded to kubevirt_vmi_migration_succeeded

kubevirt_migrate_vmi_failed to kubevirt_vmi_migration_failed

Based on PR https://github.com/kubevirt/kubevirt/pull/9821

Version(s):

Issue:

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ousleyp** [comment]
Hi @sradco, thanks so much for submitting this! It looks good to me, but there are a few things remaining before I can merge it.

1. Which OCP Virt versions does this change apply to, so I can correctly cherrypick it? 
2. Please squash your commits to one commit (a policy of the openshift-docs repo).
3. We need to get QE approval before merging. IIRC, that might be Denys (and maybe someone else?). 

@dshchedr , can you please review this? Thanks :)

**Comment by ousleyp** [comment]
Thanks for the QE review, @dshchedr!

@sradco - just a couple things outstanding and then I'll be glad to merge this. :)

> Hi @sradco, thanks so much for submitting this! It looks good to me, but there are a few things remaining before I can merge it.
> 
> 1. Which OCP Virt versions does this change apply to, so I can correctly cherrypick it?
> 2. Please squash your commits to one commit (a policy of the openshift-docs repo).

**Comment by sradco** [comment]
Hi, Waiting to get https://github.com/kubevirt/kubevirt/pull/9821. 
Will move this PR to hold until its merged.
/hold

**Comment by sradco** [comment]
Hi @ousleyp, Please review.

**Comment by ousleyp** [comment]
@sradco this still LGTM and I can merge it tomorrow after you confirm the applicable versions: does this change only apply to 4.14+ or is it backported? Thanks!

**Comment by sradco** [comment]
This applies to 4.15 only

**Comment by sradco** [comment]
@ousleyp Please merge. Its only for 4.15.

**Comment by ousleyp** [comment]
> @ousleyp Please merge. Its only for 4.15.

Hi @sradco , if this is only for 4.15+, I can't merge it until after the OCP 4.14 docs release (at that point, the 4.15 branch is created from the 4.14 branch, and we can start cherrypicking to it).

**Comment by ousleyp** [comment]
@sradco The 4.15 branch was just created (earlier than I expected)! I'll merge and cherrypick.

**Review by ousleyp — APPROVED** [review]

**Pull request merged**
