### PR TITLE
CNV-12358: Bumping HCO version to 2.6.6

### PR DESCRIPTION
**Pull request by sjhala-ccs**
[CNV-12358](https://issues.redhat.com/browse/CNV-12358)

[Example](https://deploy-preview-35327--osdocs.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-collecting-virt-data.html#gathering-data-specific-features_virt-collecting-virt-data) (must-gather command)

No CP

### CODE REVIEW

**Comment by sjhala-ccs** [comment]
@tiraboschi Can you please review/approve this HCO version bump PR for the 2.6.6 release scheduled to go out tomorrow, August 10?

**Review by tiraboschi — APPROVED** [review]

**Review by adellape — APPROVED** [review]
:+1:

**Comment by sjhala-ccs** [comment]
2.6.6 errata have shipped. Merging the PR now.

**Pull request merged**
