### PR TITLE
OSDOCS-4496 6th generation instance types

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-4496](https://issues.redhat.com//browse/OSDOCS-4496): 6th Generation Instance Types

* For more details about the information requested in this template, see:
  https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/create_or_edit_content.adoc#submit-PR --->

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4496 

Link to docs preview:
ROSA: https://55732--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html 
OSD: https://55732--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can you please take a quick look at this PR. If you aren't the right person for QE, please let me know who is. Thank you!

**Comment by jneczypor** [comment]
Hi @tzhou5! I have updated the instance type lists based on your comments and Aaren's comments from the JIRA ticket. Can you please take a quick look at the PR and approve? Thank you.

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by sheriff-rh** [comment]
/remove-label peer-review-needed

whoops!

**Pull request merged**
