### PR TITLE
OSSMDOC-731: Change OSSM Console from Dev Preview to Tech Preview

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OSSMDOC-731

Link to docs preview: https://53968--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/servicemesh-release-notes.html#openshift-service-mesh-console

QE review:
- [x] QE has approved this change.

Additional information:

Reviewers
PM: Jamie Longmuir
QA Lead: To Hung Sze
Dev Lead: Tomasso Bagassi
Product Experience: Vineet Kumar

### CODE REVIEW

**Comment by longmuir** [comment]
LGTM

**Comment by tsze-redhat** [comment]
I see the following
This release introduces a Technology Preview version of the OpenShift Container Platform Service Mesh Console, which integrates the Kiali interface directly into the OpenShift web console. For additional information, see [Introducing the OpenShift Service Mesh Console (A Developer Preview)](https://cloud.redhat.com/blog/introducing-the-openshift-service-mesh-console-a-developer-preview)

IMHO, that linked blog should be updated to also say tech preview BEFORE this can be published.

Tim, what do you think?

Thanks.

**Comment by TommasoBagassi** [comment]
I agree we should change the title of the blog post to reflect this but other than that LGTM

**Comment by rh-tokeefe** [comment]
@tsze-redhat Jamie has submitted a request to update the blog post. That content is not controlled by the doc team. I think it will be difficult to coordinate or gate updating one item by waiting for the other item as  they have two independent workflows. If we know both items are in process of being updated, then I think we should update the doc and believe that the right thing will happen and the blog content will be updated shortly thereafter.

**Comment by longmuir** [comment]
Agree. Let's not gate one change on the other. We are following up on having the blog post updated. If we can bring this PR to completion before the break, let's proceed.

**Comment by tsze-redhat** [comment]
Looks good.

**Comment by tsze-redhat** [comment]
LGTM

**Review by rolfedh — APPROVED** [review]
/lgtm

**Pull request merged**
