### PR TITLE
CNV-28689- minor update

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.14+

Issue: [CNV-28689](https://issues.redhat.com//browse/CNV-28689)

Link to docs preview: https://68233--docspreview.netlify.app/openshift-enterprise/latest/virt/install/preparing-cluster-for-virt#cpu-requirements_preparing-cluster-for-virt 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kbidarkar** [comment]
LGTM

**Comment by jab-rh** [comment]
@sabrinajess, confirm whether this goes into `main`, `enterprise-4.15`, and `enterprise-4.14`? Thanks!

**Comment by sabrinajess** [comment]
@jab-rh That is correct. This was originally labeled as 4.14+, then 4.14 only, but has been confirmed it should be 4.14+.

**Pull request merged**
