### PR TITLE
BZ-1528464: Added missing command option

### PR DESCRIPTION
**Pull request by bergerhoffer**
@openshift/team-documentation For peer review. In Atom, I have a setting to strip trailing whitespace (as seen in the diff). Let me know if that's not something you guys do and if I should turn that off.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@vikram-redhat This issue only affects 3.5, 3.6, and 3.7. I checked this out of enterprise-3.7 and was planning to cherry pick to enterprise-3.6 and enterprise-3.5 once merged. Let me know if this is the right way to do it or not.

**Comment by vikram-redhat** [comment]
@bergerhoffer yes, you should be able to CP to the older branches since this small change is unlikely to cause any merge conflicts.

I am not sure about the trailing space issue. We don't have a standard for that, AFAIK, but @adellape @kalexand-rh might be able to provide more info.

**Comment by kalexand-rh** [comment]
Oh, funny, @sheriff-rh and I were just talking about this. @vikram-redhat, we don't have a standard for dealing with whitespace trailing.

To some, trimming it is a coding best practice because it can introduce syntax errors in some languages, and it's often a best practice to standardize on trimming or not trimming to improve the git blame/commit history. (If not all the contributors deal with whitespace in the same way, git blame is less useful - no one cares if the last change to a line is to trim whitespace.)

I've noticed that PRs from devs often trim whitespace, and while I don't have a strong opinion on it, I think that it would be appropriate to add "trim your trailing whitespace" to the contributors guide. We're close enough to the start of the 4.0 stream to clean up most of it now, and maintaining a useful blame in the 3.x stream will become steadily less important with time.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Hi @anpingli, could you please take a look?

**Review by anpingli — APPROVED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Merging and cherry picking as peer review and QE review are complete.

**Comment by bergerhoffer** [comment]
Will cherry pick to 3.5 and 3.6 manually since I discovered that the /cherrypick command only works from the master branch.

**Pull request merged**
