### PR TITLE
[enterprise-4.9] TELCODOCS-415: Use of openshift-sdn with sno is deprecated.

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: [TELCODOCS-415](https://issues.redhat.com/browse/TELCODOCS-415)

For: Version 4.9 (See [PR 46078](https://github.com/openshift/openshift-docs/pull/46078) for 4.10 and [PR 45830](https://github.com/openshift/openshift-docs/pull/45830) for 4.11)

Doc Preview:
image (9)

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Comment by ktothill** [comment]
**Summary:** 4.11 PR [merged successfully](https://coreos.slack.com/archives/C025XCRRH28/p1653506397166989?thread_ts=1653505662.242889&cid=C025XCRRH28). 

 **Next Steps:** [Requested merge](https://coreos.slack.com/archives/C025XCRRH28/p1653587579467819) for 4.9 and 4.10.

**Comment by ktothill** [comment]
**Who:** Emily O'Neill, Content Strategist
**Contact Method:** Slack, Direct Message
**Date and Time:** May 27, 2022  09:16
**Summary:** Following up with Emily to identify if 4.9 and 4.10 backports need to complete the change management process, as described in the Openshift Docs Manual. Clarifying with Emily, as this is the first time I've been asked to do this for a backport.

**Next Steps:** Provide backport details to Max, so he can merge accordingly.

**Comment by ktothill** [comment]
**Who:** Tomas "Sheldon" Radej, DPM

**Contact Method:** Email 

**Date and Time:** May 31, 2022  15:42

**Summary:** Confirmed with Sheldon that change management is necessary (Scenario 1 in the OCP Docs Manual). Updated Max via the [existing](https://coreos.slack.com/archives/C025XCRRH28/p1654025998477629?thread_ts=1653587579.467819&cid=C025XCRRH28) merge request thread.

 

Next Steps: Going through the change management process for 4.9 & 4.10.

[Edit](https://issues.redhat.com/secure/EditComment!default.jspa?id=14412472&commentId=20357271)

**Comment by xltian** [comment]
ack

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#central-infrastructure-management](https://coreos.slack.com/archives/C01LZ5SBLLQ/p1656094490061719)
**Date and Time:** June 24, 2022  14:15
**Summary:** Requested approvals by Tuesday for Change Management process from Eng, PM and UX via Slack

**Next Steps:** Confirm approvals have been submitted. Once approvals are obtained, should be able to continue the change management process.

**Comment by xsgordon** [comment]
lgtm

**Comment by romfreiman** [comment]
lgtm

**Comment by jelkosz** [comment]
lgtm

**Comment by ktothill** [comment]
**Who:** Tim Rees, Eric Rich, PX
Contact Method: Slack [#central-infrastructure-management](https://coreos.slack.com/archives/C01LZ5SBLLQ/p1656094490061719) and email
**Date and Time:** June 28, 2022 15:01
**Summary:** Approvals received from Eng, PM and UX.

PX Approval still pending. Emailed Tim and Eric, as no response from Slack.

**Next Steps:** Follow up with Tim and Eric if approval is not received.

**Comment by reestr** [comment]
ack

**Pull request merged**
