### PR TITLE
Standardize compliance table for OSD/ROSA; add HIPAA

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
Direct preview link for ROSA: https://deploy-preview-40573--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-policy-process-security.html#rosa-policy-compliance_rosa-policy-process-security

Not sure why there's not an OSD preview page ¯\_(ツ)_/¯

**Comment by nermina-redhat** [comment]
@pneedle-rh, please take a look and merge when you get the chance. thank you!

**Comment by pneedle-rh** [comment]
@wgordon17 thank you for submitting this PR. This PR LGTM!

There is an intermittent issue with the automatic preview for OSD, which we are looking in to. In the meantime, I have uploaded the preview for OSD for this PR [here](http://people.redhat.com/pneedle/openshift-dedicated/osd_policy/policy-process-security.html#compliance_policy-process-security).

**Comment by pneedle-rh** [comment]
@xueli181114 or @yuwang-RH can you please review this PR from a QE perspective? Thanks!

**Comment by yuwang-RH** [comment]
LGTM.

**Comment by mburke5678** [comment]
@wgordon17 @pneedle-rh LGTM

**Pull request merged**
