### PR TITLE
#CNV-37343 - minor update

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.15+

Issue: [CNV-37343](https://issues.redhat.com//browse/CNV-37343)

Link to docs preview: https://71317--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-accessing-vm-ssh#virt-adding-public-key-cli_static-key

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by RoniKishner** [comment]
Looks good

**Comment by gwynnemonahan** [comment]
Hey @sabrinajess ,

LGTM! I'm in training, so @abrennan89 needs to also review.

Thanks!

**Comment by abrennan89** [comment]
lgtm

**Comment by sabrinajess** [comment]
@gwynnemonahan or @abrennan89 Can you please mark as peer review done so I can move to merge :)

**Pull request merged**
