### PR TITLE
Add RHCOS image format note - BZ 1763803

### PR DESCRIPTION
**Pull request by maxwelldb**
Specifying RHCOS image format more clearly as suggested in https://bugzilla.redhat.com/show_bug.cgi?id=1763803. 

4.2+.

### CODE REVIEW

**Comment by maxwelldb** [comment]
Waiting on QE.

**Comment by maxwelldb** [comment]
Looking at the comment from QE in [the ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1763803), @iamemilio...

1. Is there a specific version we want to recommend? How 'bout RHEL 7 vs. 8? It is a bit awkward that the "latest" selection in the combo box doesn't show an OpenStack image at all. 

2. It looks like the note about the raw format could be dropped entirely. Do you agree?

**Comment by maxwelldb** [comment]
@openshift/team-documentation Anyone able to review this? Small change.

**Review by sheriff-rh — APPROVED** [review]
Looks good!

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
