### PR TITLE
Bug 129381, updated examples

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1293818

@akostadinov @adellape, how do these updated examples (with corrected port numbers) look?

### CODE REVIEW

**Comment by adellape** [comment]
@ahardin-rh Since we're converting one example to YAML (which we ultimately want all the examples in the docs to be in), might as well get the others in this topic too - http://jsontoyaml.com/

@akostadinov Bump per previous comment.

**Comment by akostadinov** [comment]
@adellape , @ahardin-rh , Hello, for a minute I thought I'm crazy as I couldn't remember anything about this bug and it is filed pretty much recently. Moreover the style of writing very similar to mine :smile: . But the guy filing the issue is actually "Alexander Koksharov" (don't know his github id). While I'm `Kostadinov`.
While on it, I would say that `"targetPort": 80` for mysql looks strange to me.

**Comment by ahardin-rh** [comment]
@akostadinov Ha! So sorry! That's my mistake. Sorry to bother you and thanks for the feedback. I will look into that! :laughing:

**Comment by adellape** [comment]
:scream_cat: Oh my goodness, sorry from me as well. Thanks anyway!

**Comment by ahardin-rh** [comment]
@adellape converted examples to YAML. PTAL.

**Comment by ahardin-rh** [comment]
Made final edits after IRC discussion with Alexander Koksharov

**Comment by ahardin-rh** [comment]
**revhistory note:**
Corrected port numbers across the page and converted examples to YAML.

**Pull request merged**
