### PR TITLE
CNV-22037 - fix

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.14+

Issue: [CNV-22037](https://issues.redhat.com//browse/CNV-22037)

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:
minor fix to content that was just approved

### CODE REVIEW

**Review by jpeimer — APPROVED** [review]
Thank you Sabrina!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
