### PR TITLE
reworking installation links

### LINKED ISSUE #15108: [enterprise-4.1] Edit suggested in file welcome/index.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/welcome/index.html#cluster-installation-activities

### What needs fixing?

> Choose a deployment platform: Amazon AWS is the first supported platform for OpenShift Container Platform 4.1. Other supported platforms include bare metal and vSphere.

The language "first supported platform" gives undue weight to AWS.  I would describe this more like:

> Choose a deployment platform: The installer can provision and deploy to Amazon AWS, or you may elect to deploy onto pre-provisioned infrastructure on AWS, bare metal, or vSphere.

### PR DESCRIPTION
**Pull request by kalexand-rh**
Fixes https://github.com/openshift/openshift-docs/issues/15108

Built draft here: http://file.rdu.redhat.com/kalexand/060519/15108/welcome/index.html#cluster-installation-activities

### CODE REVIEW

**Comment by smarterclayton** [comment]
I like it

**Comment by kalexand-rh** [comment]
Thanks Clayton!

@vikram-redhat, can I merge?

**Pull request merged**
