### PR TITLE
 removes repeat content and correct replica

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to main and 4.12
- Scope is to remove repeated content and correct the replica number for SNO
- [Preview](https://52620--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/installing-with-agent-based-installer.html) >> removes repeat content
- [Preview](https://52620--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html#installation-bare-metal-agent-installer-config-yaml_preparing-to-install-with-agent-based-installer) >> replica changed from 3 to 1

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @Amrita42  WIll you provide a direct preview link for this change? Thank you!

**Comment by mjpytlak** [comment]
@Amrita42 I am not sure I agree with not needing QE on this. What prompted the change in the sample installation configuration file?

**Comment by Amrita42** [comment]
@mjpytlak QE has acked it

**Comment by mjpytlak** [comment]
Thanks @Amrita42. Is there a specific doc story or bug associated with this work?

**Comment by Amrita42** [comment]
@mjpytlak no.

**Comment by bergerhoffer** [comment]
@mjpytlak It looks like the CP for 4.12 for this one never opened - likely one of the days where the cherry pick bot was having issues. Can you please cherry pick it?

**Pull request merged**
