### PR TITLE
BZ2117868: Add a note that enabling network flow collectors impact performance

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.8+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2117868

Link to docs preview: [file.rdu.redhat.com/sdudhgao/addnote/networking/ovn_kubernetes_network_provider/tracking-network-flows.html](http://file.rdu.redhat.com/sdudhgao/addnote/networking/ovn_kubernetes_network_provider/tracking-network-flows.html)

Additional information:

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@rbbratta @memodi Can you take a look this ?

**Comment by memodi** [comment]
@xenolinux could you share docs preview link again? above link is not working.

**Comment by memodi** [comment]
> @xenolinux could you share docs preview link again? above link is not working.
Never mind, I was able to view from the one that bot created: https://50705--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/tracking-network-flows.html

/qe-approved

**Comment by xenolinux** [comment]
> @xenolinux could you share docs preview link again? above link is not working.

@memodi The preview link is up now. Thanks

**Comment by snarayan-redhat** [comment]
/lgtm

In case the PR is ready to be merged, please add merge-review-needed label.

**Comment by bergerhoffer** [comment]
Marking this QE approved

/label qe-approved

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Pull request merged**
