### PR TITLE
WIP: cnv-2.2 release notes: Add multiple new features

### PR DESCRIPTION
**Pull request by dankenigsberg**
This is a very raw draft of how cnv-2.2 release notes can cover positive progress. Text taken from Steve Gordon.

/cc @bgaydosrh

### CODE REVIEW

**Review by bgaydosrh — COMMENTED** [review]
@dankenigsberg - Thanks and here's my version of the draft:

* Enhancements to workflow for importing a single VMWare virtual machine.

* Health monitoring of Virtual Machine-backed services, equivalent to that for Pod-based services.

* Persistent local storage option for virtual machine images.

* New virtual machine dashboard screen. 

* The virtual machine creation wizard has been completely redesigned. It now uses an in-page style and includes a comprehensive review page.

* Ability to add, edit and view virtual CD-ROM devices attached to a virtual machine.

* Ability to add and view network attachment definitions with a graphical editor.

* Virtual machine templates can now be edited. Previously, only virtual machines could be edited.

Question: Can you elaborate on:
"A new virtual machine > dashboard screen." --- Has this screen been redesigned for better usability, navigation? Looking to qualify what's better about it for the user.

I'll update the notes once I get your feedback.

Thanks, this looks much more impressive!

Bob

cc: @jelkosz

**Comment by xsgordon** [comment]
Looks good, @bgaydosrh the virtual machine dashboard is net new. On old versions you didn't get a "nice" dashboard for VMs at all.

**Comment by jelkosz** [comment]
Just two comments

>  Enhancements to workflow for importing a single VMWare virtual machine.

Actually it is written as `VMware`

> Question: Can you elaborate on:
> "A new virtual machine > dashboard screen." --- Has this screen been redesigned for better usability, navigation? Looking to qualify what's better about it for the user.
> 

It is a new screen, it has not been there and it has been created in 2.2

**Comment by bgaydosrh** [comment]
Replaced by PR https://github.com/openshift/openshift-docs/pull/19620

**Pull request closed without merging**
