### PR TITLE
fix: opentelemetry collector config templates

### PR DESCRIPTION
**Pull request by frzifus**
Version(s):

4.12, 4.13, 4.14, 4.15, 4.16, 4.17, 4.18

Issue:

https://issues.redhat.com/browse/OBSDOCS-1554

Link to docs preview:

https://85448--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-collector/otel-collector-processors.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Review by IshwarKanse — APPROVED** [review]

**Review by max-cx — APPROVED** [review]

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Review by sheriff-rh — APPROVED** [review]
LGTM; merging.

**Pull request merged**
