### PR TITLE
OSDOCS-2996 AWS Secret Region rename

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2996

This will be added separately for `main` and `enterprise-4.10`, since the section is being reorganized for those branches.

Preview: https://deploy-preview-40350--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-government-region

### CODE REVIEW

**Comment by codyhoag** [comment]
@staebler can you confirm? Thanks!

**Review by staebler — COMMENTED** [review]
LGTM

**Comment by codyhoag** [comment]
@yunjiang29 can you verify? Thanks!

**Comment by yunjiang29** [comment]
@codyhoag  LGTM.

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
