### PR TITLE
OCPBUGS-42088: updates RNs for Egress IPs additional nwts

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OCPBUGS-42088

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:
4.15 [PR](https://github.com/openshift/openshift-docs/pull/81969)
4.16 [PR](https://github.com/openshift/openshift-docs/pull/81970)

### CODE REVIEW

**Comment by kalexand-rh** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Comment by anuragthehatter** [comment]
cc @jechen0648 as @huiran0826 is on PTO

**Comment by palonsoro** [comment]
LGTM

**Review by palonsoro — APPROVED** [review]

**Review by jldohmann — APPROVED** [review]
lgtm. do we have a consensus on how to mark things as being generally available? i see it sometimes as "Generally Available", which is in line with how we denote things as "Technology Preview", but i see it more commonly as "generally available". either way, this is outside the scope of this PR 😄

**Comment by palonsoro** [comment]
@jldohmann my two cents on your doubt: "Generally Available" is often abbreviated GA the same way "Technology Preview" is often abbreviated TP, so I guess keeping the capital letters makes sense when we talk about the feature supportability status. But as you said, this is beyond the scope of the PR.

**Comment by CFields651** [comment]
LGTM

**Pull request merged**
