### PR TITLE
OSDOCS-3421: Added a collapsible list to the ROSA documentation.

### PR DESCRIPTION
**Pull request by EricPonvelle**
This PR modifies an existing list to be collapsible. This change was made due to the size of the list increasing in a subsequent update.

JIRA: https://issues.redhat.com/browse/OSDOCS-3421

PREVIEW: https://deploy-preview-43995--osdocs.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-service-definition#rosa-sdpolicy-aws-compute-types_rosa-service-definition

### CODE REVIEW

**Review by arendej — APPROVED** [review]
excellent, thank you.

**Review by kalexand-rh — COMMENTED** [review]
I have one change, but this otherwise looks good!

**Pull request merged**
