### PR TITLE
BZ#2092710: Addling link to image registry config for Cinder volumes

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.8+

Issue:

https://bugzilla.redhat.com/show_bug.cgi?id=2092710
Link to docs preview:

https://52235--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-registry-osp-creating-custom-pvc_installing-openstack-installer-custom
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@eurijon @pierreprinetti @EmilienM Hi all, this BZ is sortof related to this [PR](https://github.com/openshift/openshift-docs/pull/47689) that you all reviewed, tied to a similar customer support case. Can you please review this small docs update? Thank you!

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
