### PR TITLE
Fixing some typos

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11 (will CP fixes back as far as they apply)

Issue:
N/A

Link to docs preview:

Only posting links that are formatting items to check:

* https://64676--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-marketplace_installing-gcp-customizations
* https://64676--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/installing-operators#network-observability-loki-installation_network_observability
* https://64676--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected#oc-mirror-imageset-config-params_installing-mirroring-disconnected
* The serverless one doesn't have a preview because I don't think it's currently used

QE review:
- N/A (formatting/typo fixes only)

Additional information:

**Note to reviewer: This PR only fixes typos; I do not plan to get into making any other additional improvements that might exist**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
/label peer-review-needed

**Reviewer: see note in description**

**Review by sheriff-rh — APPROVED** [review]
Looks great as always, Andrea! Thanks for fixing all of these!

**Pull request merged**
