### PR TITLE
OSDOCS#9462: Removed Hyper Protect from IBM Cloud BYOK RN

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.15

Issue:

This PR updates the Release Notes as part of [osdocs-9462](https://issues.redhat.com/browse/OSDOCS-9462). 

Link to docs preview:

QE review:
- [yes] QE has approved this change.

### CODE REVIEW

**Comment by jeffnowicki** [comment]
Looks good Mike. Thank you.

- lgtm
- ibm approved

**Comment by mjpytlak** [comment]
@MayXuQQ Ready for QE review. PTAL.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
