### PR TITLE
BZ 1622018 - storageclass default note added to master

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1622018](https://bugzilla.redhat.com/show_bug.cgi?id=1622018)
This PR is related to [PR 17641](https://github.com/openshift/openshift-docs/pull/17641), which applies the note to 3.10, 3.11. 
This PR is for master, CP to 4.1, 4.2, 4.3.
@liangxia PTAL

### CODE REVIEW

**Comment by liangxia** [comment]
The same here, https://github.com/openshift/openshift-docs/pull/17641#discussion_r339380114

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL

**Review by lamek — COMMENTED** [review]
LGTM. One suggestion: you can get rid of the word "therefore" if you swap the order of the sentences.

> Only one StorageClass should be set as the default. If more than one StorageClass is marked as default, a PVC can only be created if the `storageClassName` is explicitly specified.

**Comment by bobfuru** [comment]
> LGTM. One suggestion: you can get rid of the word "therefore" if you swap the order of the sentences.
> 
> > Only one StorageClass should be set as the default. If more than one StorageClass is marked as default, a PVC can only be created if the `storageClassName` is explicitly specified.

Going to leave it this way to keep the best practice stated first.

**Pull request merged**
