### PR TITLE
Add 'dedicated-readers' clusterrole documentation

### PR DESCRIPTION
**Pull request by jewzaam**
https://issues.redhat.com/browse/OSD-1500

### CODE REVIEW

**Comment by jewzaam** [comment]
/hold
need https://github.com/openshift/managed-cluster-config/pull/324 merged and promoted to prod first

**Comment by jewzaam** [comment]
/hold cancel

RBAC changes have been promoted, docs can be updated.

**Comment by lamek** [comment]
LGTM. I'll merge to master and CP to the 4.3 branch.

**Comment by bergerhoffer** [comment]
@lamek It looks like this change was only cherry picked to 4.3 and didn't make it to 4.4 or newer. (I'm noticing because I'm trying to cherry pick a PR to 4.6 and seeing this conflict). I assume that since it went into master, that it means it should be in the latest versions. 

Can you please let me know if this is okay to be cherry picked to 4.4/4.5/4.6 as well? That way once it is, my PR should merge cleanly. Thanks!

**Comment by lamek** [comment]
Cherry picked to 4.6, 4.5, and 4.4:
4.6 - https://github.com/openshift/openshift-docs/pull/24694
4.5 - https://github.com/openshift/openshift-docs/pull/24695
4.4 - https://github.com/openshift/openshift-docs/pull/24696

**Comment by lamek** [comment]
@bergerhoffer all set.

**Comment by bergerhoffer** [comment]
Thanks @lamek!

**Pull request merged**
