### PR TITLE
Bug 1498866 Added command parameter and details to install guide

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1498866

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by ahardin-rh** [comment]
LGTM 🎆

**Comment by tmorriso-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#configuring-cluster-variables[Configuring Cluster Variables]
|Updated Table 1 with information on the 'openshift_master_admission_plugin_config' parameter ] 
%

**Comment by tmorriso-rh** [comment]
@ahardin-rh Hi Ashley, can you review the revision history comment for this PR? Thanks!

**Comment by ahardin-rh** [comment]
@tmorriso-rh Sure! The first part should point to the impacted topic as a whole, Advanced Installation  (not the specific section, Configuring Cluster Variables).  So, that first bit should look like:

    |xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing a Cluster -> Advanced Installation]

With that said, you could edit the second part to reference the specific section, saying something like:

     |Added the `openshift_master_admission_plugin_config` parameter to the xref:../install_config/install/advanced_install.adoc#cluster-variables-table[Cluster Variables] table

Note the back-ticks around the parameter name. 

For reference, here's how the revision histories are built: https://docs.openshift.com/container-platform/3.6/welcome/revhistory_full.html. This should give you an idea of why we format the revision history comments in this way. Hope that helps!

**Comment by tmorriso-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing a Cluster -> Advanced Installation]
|Added the `openshift_master_admission_plugin_config` parameter to the xref:../install_config/install/advanced_install.adoc#cluster-variables-table[Cluster Variables] table.
%

**Comment by vikram-redhat** [comment]
Hey @tmorriso-rh - I noticed that you have two revision histories here. The script that processes the revision histories only looks for one revision history comment. You have two options here:

1. Delete the revision history comment that has an error.
OR
2. Edit the original comment to make the fix that @ahardin-rh had suggested and then delete the new comment. GitHub allows you to edit comments directly via the web interface. Click the pencil icon next to the comment. 

Now that this fix is in the master branch, you need to run the do-cp script to pick it into the relevant branches. By the looks of this, this needs to go into the enterprise-3.5-stage, enterprise-3.6-stage and enterprise-3.7-stage branches. You should run the do-cp script immediately afterwards merging your changes into the master branch.

**Pull request merged**
