### PR TITLE
Fixing the helm repo source and version of the helm chart

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.9`, 4.10 +
- **JIRA issues**: [RHDEVDOCS-3762](https://issues.redhat.com/browse/RHDEVDOCS-3762)
- **Preview pages**: [Installing a Helm chart on an OpenShift Container Platform cluster](https://deploy-preview-43087--osdocs.netlify.app/openshift-enterprise/latest/applications/working_with_helm_charts/configuring-custom-helm-chart-repositories.html#installing-a-helm-chart-on-an-openshift-cluster_configuring-custom-helm-chart-repositories), [Creating a custom Helm chart on OpenShift Container Platform](https://deploy-preview-43087--osdocs.netlify.app/openshift-enterprise/latest/applications/working_with_helm_charts/configuring-custom-helm-chart-repositories.html#creating-a-custom-helm-chart-on-openshift_configuring-custom-helm-chart-repositories)
- **SME Review**: Approved by @dperaza4dustbit 
- **QE review**: Approved by @tisutisu
- **Peer-review**:  Approved by @max-cx

### CODE REVIEW

**Review by max-cx — APPROVED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
@dperaza4dustbit and @tisutisu: PTAL at the PR and provide your feedback. Thanks!

**Review by tisutisu — COMMENTED** [review]
LGTM

**Review by dperaza4dustbit — APPROVED** [review]
lgtm

**Pull request merged**
