### PR TITLE
BZ#2050304: Updated endpoint names for the Top Secret region

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.9

Issue:
This PR address [bz-2050304](https://bugzilla.redhat.com/show_bug.cgi?id=2050304).

Link to docs preview:

[Requirements for using your VPC](http://file.rdu.redhat.com/mpytlak/bz-2050304-49/installing/installing_aws/installing-aws-government-region.html#installation-custom-aws-vpc-requirements_installing-aws-government-region) (Link requires access to RH VPN. A public build is not available for enterprise-4.9)

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
You can use the bot to CP this to 4.8.

**Review by GroceryBoyJr — COMMENTED** [review]
/lgtm

**Pull request merged**
