### PR TITLE
document buildconfig resource config

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@derekwaynecarr ptal since you are most familiar w/ resources and did the original build impl as i recall.  I copied the bulk of this content from the deployments doc.

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by bparees** [comment]
thanks @derekwaynecarr 
@openshift/team-documentation ptal

**Comment by vikram-redhat** [comment]
@bparees - thanks. Is this for 3.3?

**Comment by bparees** [comment]
@vikram-redhat goes back to at least 3.2, maybe even 3.1.  just never got doc'd properly.

**Comment by vikram-redhat** [comment]
@bfallonf - can you please follow up on this?

**Comment by bparees** [comment]
@bfallonf bump

**Comment by bfallonf** [comment]
@bparees is this ready to merge? I'll do a followup in another PR.

**Comment by bparees** [comment]
Yes

**Pull request merged**
