### PR TITLE
Document how to set env vars in Docker and Custom builds

### PR DESCRIPTION
**Pull request by rhcarvalho**
As per https://github.com/openshift/origin/issues/4470.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees PTAL, is this what you had in mind in terms of reorganizing the sections?

**Comment by bparees** [comment]
@rhcarvalho yup this is excellent, thanks.

@bfallonf ptal/merge, this may also have some impact on the proxy documentation work you were doing since you had some refs to how to define env variables.

**Comment by adellape** [comment]
Seems wise to me. @bfallonf Will wait for you to ack before merge.

**Comment by bfallonf** [comment]
@bparees thanks, good thinking. This should be fine from my perspective, though. I'm just linking to the Environment Files section, and that seems pretty untouched in this PR. @adellape this should be ok to merge.

**Pull request merged**
