### PR TITLE
vSphere IPI callouts

### PR DESCRIPTION
**Pull request by codyhoag**
@kalexand-rh PTAL? Thanks!

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@codyhoag a rebase should fix the build failure.

**Comment by codyhoag** [comment]
@vikram-redhat Rebased. All clear now :tada:

**Comment by vikram-redhat** [comment]
@codyhoag I am gonna merge this. If @kalexand-rh disagrees we can remove it.

**Pull request merged**
