### PR TITLE
Rename oc commands to use velero.io

### PR DESCRIPTION
**Pull request by shdeshpa07**
## Jira 

* [OADP-5268](https://issues.redhat.com/browse/OADP-5268)

##  Version

* OCP 4.13 → OCP 4.18

## Preview

* 

## QE Review

* [x] QE has approved this change.

### CODE REVIEW

**Comment by shdeshpa07** [comment]
@anarnold97 - Could you please review this PR? Thanks.

**Comment by shdeshpa07** [comment]
@bhardesty -  Hi, as a part of the blocker Jira ticket mentioned in this PR, we have corrected the `oc` commands related to OADP to use the `velero.io` API signature. This change also touches a ROSA doc set file. Could you please review and give a LGTM? Thanks.

cc: @anarnold97

**Review by kaovilai — APPROVED** [review]
Lgtm

**Comment by shdeshpa07** [comment]
> Lgtm

Thank you Sir.

**Comment by anarnold97** [comment]
@kalexand-rh - Please can you advise us on how to proceed with this PR?
The changes impact Hosted Control Panes docs, which I think are yours.
The JIRA [OADP-5268](https://issues.redhat.com/browse/OADP-5268) is a blocker, so we have already had it approved by a Dev and will pass it over to OADP QE. Are you happy with this, or is there anything else you want us to do?
Thanks

**Comment by kalexand-rh** [comment]
@bmcelvee or @lahinson, do you have suggestions for ROSA or HCP QE folks who might want to also review this?

**Comment by lahinson** [comment]
@kalexand-rh Thanks for the heads up! I asked the HCP QE team to take a look at the proposed changes to the two HCP-specific files.

**Comment by bhardesty** [comment]
@shdeshpa07 This LGTM from a ROSA perspective. Did OADP QE test this on ROSA?

**Comment by anarnold97** [comment]
> @shdeshpa07 This LGTM from a ROSA perspective. Did OADP QE test this on ROSA?

@amastbau - please can you confirm? thanks

**Review by sseago — APPROVED** [review]

**Comment by shdeshpa07** [comment]
Thank you folks for the quick reviews on this PR. I am tagging the PR for OCP peer review.

**Review by adellape — APPROVED** [review]

**Comment by jab-rh** [comment]
@shdeshpa07, this doesn't merge cleanly into earlier versions; can you manually cherry-pick? Thanks!

**Pull request merged**
