### PR TITLE
Add necessary storage classes

### PR DESCRIPTION
**Pull request by ghost**
Follow up to https://github.com/openshift/openshift-docs/issues/8670.

@akostadinov @qinpingli Please review.

Waiting for SME to confirm the versions before applying version labels.

### CODE REVIEW

**Comment by akostadinov** [comment]
LGTM

@toni-moreno FYI

**Comment by kalexand-rh** [comment]
@tmorriso-rh, I think there should be separate steps to create the yaml files and then create objects from the yaml files.
Are there variables in the yaml that need to be customized, or do you use the code snippets as-is?

**Comment by tmorriso-rh** [comment]
Thanks @kalexand-rh. @akostadinov Can you please address the comments about creating the YAML files?

**Pull request merged**
