### PR TITLE
Update folder name

### PR DESCRIPTION
**Pull request by apinnick**
Change 'migration-toolkit-for-containers' to 'migration_toolkit_for_containers' so that book builds correctly.

4.5+

Preview:

https://deploy-preview-34831--osdocs.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/about-mtc.html

https://deploy-preview-34831--osdocs.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/mtc-release-notes.html

No QE needed. Peer review needed

### CODE REVIEW

**Comment by apinnick** [comment]
@vikram-redhat 
Will this PR require redirects? If so, can you set it up?

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Pull request merged**
