### PR TITLE
BZ2101827: adds examples for RunAsUser

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.8 and above versions
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2101827)
- [Preview](https://54097--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing-security-context-constraints.html#authorization-SCC-strategies_configuring-internal-oauth)

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
Hi, for these examples, are they pieces of a larger YAML file? If so, I think there may be some formatting/indication needed to show that they are excerpts (such as `...` at the beginning and end). There is a section in the [guidelines for YAML examples](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#formatting-1) that seems to show this being done. Also not sure but since (I think) it is an excerpt, can you begin with the first line left justified?

**Comment by Amrita42** [comment]
Good point kerry , they are snippets of a yaml file

**Review by adellape — CHANGES_REQUESTED** [review]
Couple of backticks that need to be fixed.

Only a suggestion, but for minimalism sake you could drop the "of a" from each of the block titles, if you wanted. E.g., "Example `MustRunAs` snippet".

**Comment by Amrita42** [comment]
@adellape implemented feedback.

**Review by adellape — APPROVED** [review]

**Pull request merged**
