### PR TITLE
[RHACS] Added filter criteria for component and component source

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://issues.redhat.com/browse/ROX-21156
- Added filter criteria for component and component source

Cherrypick in `rhacs-docs-4.4`

### CODE REVIEW

**Review by Srivaralakshmi — COMMENTED** [review]
@gaurav-nelson Neat PR! LGTM. Thank you! Does this PR require an Ack from SME and QE? Please check and let us know.

As I am new to the peer review squad, I would ask @bmcelvee to give my review the go-ahead. Please wait until Brandi applies the peer-review-done label.

**Comment by bmcelvee** [comment]
LGTM!

**Comment by gaurav-nelson** [comment]
@Srivaralakshmi Thank you for reviewing. It's a minor change putting missing entries from the product UI, so that is why it doesn't need approval from the engineering team. We don't have a QE team for RHACS.

**Pull request merged**
