### PR TITLE
Fix #27584: Fix invalid argument for curl

### LINKED ISSUE #27584: [enterprise-4.6] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
### Which section(s) is the issue in?

In **Creating an RHCOS images cache (optional)**, **11. Download the images and place them in the /home/kni/rhcos_image_cache directory.**

### What needs fixing?

`curl` command fails because the `-o` option cannot be set to a directory name.

```
[kni@provisioner ~]$ curl -L ${RHCOS_PATH}${RHCOS_QEMU_URI} -o /home/kni/rhcos_image_cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0    151      0  0:00:01  0:00:01 --:--:--   151
  0  845M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to create the file /home/kni/rhcos_image_cache: Is a directory
  0  845M    0 15978    0     0   6730      0 36:35:48  0:00:02 36:35:46 12711
curl: (23) Failed writing body (0 != 15978)

[kni@provisioner ~]$ curl -L ${RHCOS_PATH}${RHCOS_OPENSTACK_URI} -o /home/kni/rhcos_image_cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0    201      0 --:--:-- --:--:-- --:--:--   201
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file /home/kni/rhcos_image_cache: Is a directory
  0  844M    0   618    0     0    352      0  29d 03h  0:00:01  29d 03h   881
curl: (23) Failed writing body (0 != 618)
```

### Workaround

Add filename in `-o` option:

```
[kni@provisioner ~]$ curl -L ${RHCOS_PATH}${RHCOS_QEMU_URI} -o /home/kni/rhcos_image_cache/${RHCOS_QEMU_URI}
[kni@provisioner ~]$ curl -L ${RHCOS_PATH}${RHCOS_OPENSTACK_URI} -o /home/kni/rhcos_image_cache/${RHCOS_OPENSTACK_URI}
```

### PR DESCRIPTION
**Pull request by kurokobo**
Add filename to `-o` option because `-o` have to be file path instead of directory path.

### CODE REVIEW

**Comment by kurokobo** [comment]
@vikram-redhat Please review this PR.

**Comment by vikram-redhat** [comment]
@johnwilkins please review and ack.

@ahardin-rh for peer review afterwards.

**Comment by iranzo** [comment]
@vikram-redhat we've already this in US

**Comment by vikram-redhat** [comment]
@iranzo this is acked by QE?

**Comment by iranzo** [comment]
> @iranzo this is acked by QE?

as "FORMAL" ACK, I'm unsure, but AFAIK, they use what we've in the repo and we validated it on RHEL 8.x where the issue with curl appeared before accepting the PR in US PR: https://github.com/openshift-kni/baremetal-deploy/pull/515/files

**Comment by rlopez133** [comment]
I don't know if QE validated this very specific piece, but I recall confirming this myself.

**Comment by ahardin-rh** [comment]
LGTM

**Comment by vikram-redhat** [comment]
@iranzo @rlopez133 I am worried about putting in content without formal QE ack. 

@xltian or @mffiedler - do you know who can give formal QE ack for this and other telco content?

https://github.com/openshift/openshift-docs/pulls/kurokobo

**Comment by rlopez133** [comment]
@vikram-redhat - I get your concern, but what is currently downstream doesn't work. We updated this upstream a while back.

**Comment by vikram-redhat** [comment]
> @vikram-redhat - I get your concern, but what is currently downstream doesn't work. We updated this upstream a while back.

Understood. So the QE team shouldn't have any concerns validating and giving their ack for this fix for the downstream content.

**Comment by ahardin-rh** [comment]
I reached out to Amit Ugol for QE review.

**Comment by tradej** [comment]
Tracked in [TELCODOCS-220](https://issues.redhat.com/browse/TELCODOCS-220).

**Comment by ktothill** [comment]
LGTM. Confirmed with John Wilkins that variables are valid and the issue has already been fixed upstream.

**Comment by kurokobo** [comment]
Thank you for the review here too, I've added a commit that resolves the conflict.

**Comment by tradej** [comment]
Thank you @kurokobo. QE will review this PR likely next week.

**Comment by tradej** [comment]
We are currently talking to QE about verification requirements, sorry for the delay.

**Review by awolffredhat — APPROVED** [review]
new curl commands execute successfully (whereas the old ones didn't).

**Review by bergerhoffer — COMMENTED** [review]
LGTM, merging!

**Comment by bergerhoffer** [comment]
Actually, I just noticed that this has 2 commits. Can you squash it so that the PR only has 1 commit?

**Comment by kurokobo** [comment]
Thanks for reviewing, squashed into 1 commit.

**Comment by bergerhoffer** [comment]
Thanks, merging!

**Pull request merged**
