### PR TITLE
Specify 'fluentd' secret name instead of elasticsearch in LogForwarding example

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1835708

### CODE REVIEW

**Comment by mburke5678** [comment]
@ewolinetz PTAL

**Comment by mburke5678** [comment]
@jcantrill PTAL

**Review by jcantrill — APPROVED** [review]

**Comment by mburke5678** [comment]
@anpingli PTAL. Very small change.

**Review by anpingli — COMMENTED** [review]
LGTM

**Pull request merged**
