### PR TITLE
Update content for OVN-Kubernetes GA [4.6]

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-985

Will incorporate at https://github.com/openshift/openshift-docs/pull/22669.

Previews (many because of conditional usage):

- [Network configuration parameters](https://osdocs-985--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-network-customizations.html#network-customization-config-yaml_installing-aws-network-customizations)
- [Modifying advanced network configuration parameters](https://osdocs-985--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-network-customizations.html#modifying-nwoperator-config-startup_installing-aws-network-customizations)
- [Configuration parameters for the OVN-Kubernetes default CNI network provider](https://osdocs-985--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-network-customizations.html#nw-operator-configuration-parameters-for-ovn-sdn_installing-aws-network-customizations)
- [Configuration parameters for the OVN-Kubernetes default CNI network provider](https://osdocs-985--ocpdocs.netlify.app/openshift-enterprise/latest/networking/cluster-network-operator.html#nw-operator-configuration-parameters-for-ovn-sdn_cluster-network-operator)
- [About the OVN-Kubernetes default Container Network Interface (CNI) network provider](https://osdocs-985--ocpdocs.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html)

### CODE REVIEW

**Comment by jboxman** [comment]
This needs additional scrubbing of TP notice now.

**Comment by jboxman** [comment]
Refs https://github.com/openshift/openshift-docs/pull/23802 as first step towards egress rules and ipblock.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
