### PR TITLE
GitHub-22311:  Providing information on where to download the supported kubectl

### LINKED ISSUE #22311: [enterprise-4.4] Edit suggested in file cli_reference/openshift_cli/usage-oc-kubectl.adoc
### Which section(s) is the issue in?
this section mentions the  kubectl binary that 'ships' with ocp, but where do I get it from?

image

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #22311

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@zhouying7780 can you please review this update?

Preview: https://github-22311--ocpdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/usage-oc-kubectl.html#the-kubectl-binary

**Pull request merged**
