### PR TITLE
OSDOCS-11170: Adding workload partitioning notes in microshift releas…

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.17

Issue:
[OSDOCS-11170](https://issues.redhat.com/browse/OSDOCS-11170)

Link to docs preview:
[workload partitioning](https://80281--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-17-release-notes.html#microshift-4-17-configuring_release-notes)

QE review:
- [x] QE has approved this change.

SME review:
- [x] SME has approved this change.

Additional Information:
related to https://github.com/openshift/openshift-docs/pull/80198

### CODE REVIEW

**Comment by aravipra** [comment]
WIP donot close

**Review by Srivaralakshmi — COMMENTED** [review]
@aravipra Nice work! LGTM.

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
