### PR TITLE
fixes vale script quoting expansion error

### PR DESCRIPTION
**Pull request by aireilly**
Fixes a quoting error introduced in https://github.com/openshift/openshift-docs/pull/50017

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gaurav-nelson PTAL?

**Comment by aireilly** [comment]
> @gaurav-nelson: #50034 failed to apply on top of branch "rhacs-docs-3.72.0":
> 
> ```
> Applying: fixes vale script
> Using index info to reconstruct a base tree...
> A	scripts/check-with-vale.sh
> Falling back to patching base and 3-way merge...
> CONFLICT (modify/delete): scripts/check-with-vale.sh deleted in HEAD and modified in fixes vale script. Version fixes vale script of scripts/check-with-vale.sh left in tree.
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 fixes vale script
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

@gaurav-nelson will need to patch this one by hand?

**Comment by gaurav-nelson** [comment]
Thank @aireilly There are some other issues with `3.72.0` branch as well, which I am looking at. I'll get this one in manually.

**Pull request merged**
