### PR TITLE
OCPBUGS-43902: remove FIPS compliance from 4.12 release notes

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12 only
Issue:

https://issues.redhat.com/browse/OCPBUGS-43902
Link to docs preview:

https://84243--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/network-observability-operator-release-notes.html#network-observability-operator-1.7.0-features-enhancements_network-observability-operator-release-notes-v0
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jotak — APPROVED** [review]

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by jeana-redhat — APPROVED** [review]
Edit LGTM, I am guessing this needs change mgmt if you haven't already kicked that off

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by skrthomas** [comment]
@STA @mcurry-rh I need to back out the FIPS compliance from the 4.12 release notes. At the time of merge, I didn't realize that this wasn't a 4.12 thing, and it got merged. Tagging you both for change mgmt approvals. Thank you!!

**Comment by mcurry-rh** [comment]
> @sta @mcurry-rh I need to back out the FIPS compliance from the 4.12 release notes. At the time of merge, I didn't realize that this wasn't a 4.12 thing, and it got merged. Tagging you both for change mgmt approvals. Thank you!!

@skrthomas This should really get @knewcomerRH oversight, rather than me.

**Comment by knewcomerRH** [comment]
Hi folks, Since this bug was opened, openssl in RHEL 9.2 and 9.4 have received a provisional certificate for FIPS validation. This is valid for two years and is the best NIST has been able to do given their backlog. So, assuming the FIPS status is tied to use of openssl by this operator when RHCOS is booted in FIPS mode, there is no longer any need to remove the claim of designed for FIPS. Timing is everything! This news just came in last week.

**Comment by jotak** [comment]
netobserv is based on rhel9-4-els indeed
ok to close the PR then!

**Pull request closed without merging**
