### PR TITLE
CNV -24846: Update getting started

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13+

Issue: [CNV-24846](https://issues.redhat.com//browse/CNV-24846)

Link to docs preview: [Getting started](https://61117--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-getting-started.html)

QE review: NA
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by fabiand** [comment]
lgtm afaict

**Review by mjpytlak — COMMENTED** [review]
@apinnick peer review lgtm.

**Pull request merged**
