### PR TITLE
link to registry secret doc from build output section

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bparees** [comment]
@openshift/team-documentation bump (it's an easy one)

**Comment by adellape** [comment]
@bparees Closing in favor of https://github.com/openshift/openshift-docs/pull/4282 (needed a unique anchor ID), and dropping 3.3 label since we didn't backport the Builds re-org that far.

**Comment by bparees** [comment]
thanks @adellape

**Pull request closed without merging**
