### PR TITLE
OCPBUGS 13378: Updating non-preempting priority classes to GA

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OCPBUGS-13378

Link to docs preview:
(single page / VPN required): http://file.rdu.redhat.com/~ahoffer/2023/OCPBUGS-13378-413/release_notes/ocp-4-13-release-notes.html#node-technology-preview-features

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @gauravsingh85 @xltian @kalexand-rh @sferich888 Please review for change management approval

**Comment by gauravsingh85** [comment]
LGTM

**Review by JoeAldinger — COMMENTED** [review]
/lgtm
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
