### PR TITLE
OCPBUGS#1872 - replacing backticks with doublequotes

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://issues.redhat.com/browse/OCPBUGS-1872

Version(s):
4.6+

Link to docs preview:
https://51220--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-user-infra-rhcos_installing-gcp-user-infra

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianli-wei, will you PTAL?

**Comment by jianli-wei** [comment]
FYI https://bugzilla.redhat.com/show_bug.cgi?id=1987290 is also for the issue, thanks!

**Review by adellape — APPROVED** [review]

**Pull request merged**
