### PR TITLE
Added nic binding method to ui docs

### PR DESCRIPTION
**Pull request by jelkosz**

### CODE REVIEW

**Comment by jelkosz** [comment]
@ousleyp

**Comment by yossisegev** [comment]
LGTM

**Comment by booxter** [comment]
@jelkosz I was told that these patches should belong to enterprise-4.1 branch not master. Otherwise I already have: https://github.com/openshift/openshift-docs/pull/14633 that is mostly the same (though I am happy to close it since you have one additional change here).

**Comment by booxter** [comment]
Also, we specifically should NOT mention SR-IOV in CNV docs because we don't support it (yet).

**Comment by ousleyp** [comment]
Hey @jelkosz and @booxter -

Sorry to step on your toes, but I just took these changes and added them to my PR for CNV-127: https://github.com/openshift/openshift-docs/pull/14351

I already had cnv-vm-create-nic-web.adoc* in my PR for CNV-127, and it seemed prudent to add the networking fields file to the same assembly, so I just went ahead and updated both files with the binding method info. There were a couple other changes I had to make for modular docs and I figured it would just be easier to do it all at once.

You can preview both files at the bottom of this assembly (uploaded local build): http://file.bos.redhat.com/pousley/050619/cnv-127/cnv/cnv_users_guide/cnv-attaching-vm-multiple-networks.html

Please review the changes on my PR if you can. I think both this PR and https://github.com/openshift/openshift-docs/pull/14712 can be closed. Thanks for submitting them :) Contributing to the docs will be simpler after we finish modularizing, so hang tight.

ccing @dankenigsberg 

*file names in CNV 2.0 need to be converted from using underscores to using hyphens - sorry for the additional confusion!

**Comment by dankenigsberg** [comment]
@ousleyp  generally, I like multiple small PRs. I think we would have all been better off if https://github.com/openshift/openshift-docs/pull/14633 was already merged, and any contentious matter postponed to its own localized PR.

But despite that, I'm happy that you accepted these suggestion. I think we can now close pr 14712

**Comment by ousleyp** [comment]
> @ousleyp generally, I like multiple small PRs. I think we would have all been better off if #14633 was already merged, and any contentious matter postponed to its own localized PR.

Thanks, Dan. I generally agree with you that smaller PRs are better. In this case, it seemed complicated by the requirements we have for the modularization effort (submitting directly to enterprise-4.1, moving files between branches, renaming them, adding the required metadata...). It's hard to track these tiny details, and time-consuming to explain them. Otherwise, I would've been happy to pursue merging the PRs individually.

When we're finished modularizing, the contribution process will be easier for everyone.

> But despite that, I'm happy that you accepted these suggestion. I think we can now close pr 14712

Glad to hear it :)

**Comment by jelkosz** [comment]
@ousleyp Thank you for incorporating this changes into your (actually correct :) ) PR. checked, looks good! Closing this one now.

**Pull request closed without merging**
