### PR TITLE
GH#34497: [OKD] RHCOS image download link instead of FCOS image link

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/34497

Direct internal-only preview: http://file.rdu.redhat.com/mburke/okd-issue-34497/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-specifying-rhcos-image-settings_installing-rhv-user-infra

### CODE REVIEW

**Comment by mburke5678** [comment]
@binnes PTAL

**Comment by vrutkovs** [comment]
LGTM, but in 4.8 I think the procedure is a bit different - URLs are now encoded in installer. See https://github.com/openshift/installer/blob/master/docs/user/overview.md#coreos-bootimages

**Comment by mburke5678** [comment]
@vrutkovs In [your comment](https://github.com/openshift/openshift-docs/pull/34516#issuecomment-879732973), are you suggesting this procedure is no longer necessary starting in 4.8? The [OKD installer](https://github.com/openshift/okd/releases) will pull down the correct images?

**Comment by vrutkovs** [comment]
Yeah, I think so. OKD installer can both pull images (for IPI) and print the expected artifact URL (for UPI).

I think its best be confirmed with installer / CoreOS team (@cgwalters might want to take a look)

**Comment by cgwalters** [comment]
Yep, the same procedure now works for both OCP/RHCOS and OKD/FCOS - it's the same metadata JSON format.

**Comment by mburke5678** [comment]
@cgwalters @vrutkovs What is the effect of [Colin's comment](https://github.com/openshift/openshift-docs/pull/34516#issuecomment-881533634) to the end user?

**Comment by vrutkovs** [comment]
Users now have a more convenient access to the RHCOS artifact location straight from installer, making their UPI installs closer to what IPI creates.

**Comment by mburke5678** [comment]
@vrutkovs @cgwalters Is this procedure no longer required? 
_Specifying the {op-system} image settings_
_Update the {op-system-first} image settings of the inventory.yml file. _

**Comment by mburke5678** [comment]
@vrutkovs @cgwalters Is this procedure no longer required?

```
Specifying the {op-system} image settings
Update the {op-system-first} image settings of the inventory.yml file. 

```

**Comment by mburke5678** [comment]
@vrutkovs @cgwalters Is this procedure no longer required?

Specifying the {op-system} image settings
Update the {op-system-first} image settings of the inventory.yml file.

**Pull request merged**
