### PR TITLE
updating autoscaler api versions

### PR DESCRIPTION
**Pull request by kalexand-rh**
per https://github.com/openshift/cluster-autoscaler-operator/tree/master/examples

@vikram-redhat, can I merge?

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@kalexand-rh - would this resource definition need changing as well? https://docs.openshift.com/container-platform/4.1/machine_management/applying-autoscaling.html#machine-autoscaler-cr-applying-autoscaling

**Comment by kalexand-rh** [comment]
@vikram-redhat, not according to the samples in that link.

**Comment by vikram-redhat** [comment]
Yikes. I thought that they would have wanted to keep them the same.

**Comment by kalexand-rh** [comment]
¯\_(ツ)_/¯
I'll check again before GA.

**Pull request merged**
