### PR TITLE
BZ1860508: Fixed incorrect commands

### PR DESCRIPTION
**Pull request by sagidlow**
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1860508
Applies to 4.5+
QE approval need: @wzheng1 
Preview Link: [Moving the default registry](https://deploy-preview-32997--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets) - See procedure steps 1 and 2.

### CODE REVIEW

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Comment by wzheng1** [comment]
I don't think this change is needed and the bug is invalid, user cannot just use **config** to get configs.imageregistry.operator.openshift.io resource.

**Pull request merged**
