### PR TITLE
Add DHCP note for SR-IOV network

### PR DESCRIPTION
**Pull request by zenghui-shi**

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, I'll look at this this week, thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I'll look at this this week, thanks!

@jboxman thanks!
This is related to the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1838432

**Comment by jboxman** [comment]
Can we instead say:

> A DHCP lease can only be obtained from a running DHCP server. However, the SR-IOV Network Operator does not deploy a DHCP server. To trigger the deployment of a DHCP server, you must create a shim network attachment by editing the Cluster Network Operator configuration.

_shim_ may be preferable to _dummy_.

**Comment by zshi-redhat** [comment]
> Can we instead say:
> 
> > A DHCP lease can only be obtained from a running DHCP server. However, the SR-IOV Network Operator does not deploy a DHCP server. To trigger the deployment of a DHCP server, you must create a shim network attachment by editing the Cluster Network Operator configuration.
> 
> _shim_ may be preferable to _dummy_.

@jboxman thanks for the review! I like the revised statement. One minor change might be the DHCP DaemonSet deployed by CNO is not a typical DHCP server, it only renews DHCP lease for container.  What about:

A DHCP DaemonSet is required to periodically renew the DHCP lease for the duration of container lifetime. However, the SR-IOV Network Operator does not deploy a DHCP DaemonSet. To trigger the deployment of a DHCP DaemonSet, you must create a shim network attachment by editing the Cluster Network Operator configuration.

**Comment by jboxman** [comment]
@zshi-redhat, I'll open a new PR; this content was updated and the DHCP configuration is now separate from the static configuration for clarity.

**Comment by jboxman** [comment]
Opened https://github.com/openshift/openshift-docs/pull/23553 for this.

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I'll open a new PR; this content was updated and the DHCP configuration is now separate from the static configuration for clarity.

@jboxman thanks, sounds good to me.

**Pull request closed without merging**
