### PR TITLE
BZ2071970 - Updating OCS registry link to ODF

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.9+
[Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2071970)

Ready for QE

Preview: [Gathering data about your cluster](https://deploy-preview-44325--osdocs.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data#gathering-data-specific-features_gathering-cluster-data)

### CODE REVIEW

**Comment by kelbrown20** [comment]
@xiuwang Hello XiuJuan! Do you know of a QE that could take a look at this?

**Comment by xiuwang** [comment]
Hi @kelbrown20 It's a ODF doc,  @nehaberry could you assign a right people to check it?

**Comment by nehaberry** [comment]
HI @xiuwang added @musoni123 to the bug. However, could you let us know what is the verification as we do not normally test this.
Cc @afreen23 @bipuladh

**Comment by xiuwang** [comment]
IMO, you could check this image could be pulled in ODF operator pod.

**Comment by nehaberry** [comment]
@xiuwang 

As tested by @musoni123 in https://bugzilla.redhat.com/show_bug.cgi?id=2071970#c9, pulling image "registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.9" worked and "registry.redhat.io/ocd4/ocs-must-gather-rhel8:v4.9" failed as expected

The ODF documentation is updated with the new path. Do we need anything else or we can add LGTM here?

**Comment by musoni123** [comment]
Hi Kelly ad mentioned in "https://github.com/openshift/openshift-docs/pull/44325#issuecomment-1103427133" , i validated the link and this image works "registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.9" .


podman pull --authfile ~/OCS4/ocs-ci/data/pull-secret  registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.9                                                                                          
Trying to pull registry.redhat.io/odf4/ocs-must-gather-rhel8:v4.9...
Getting image source signatures
Checking if image destination supports signatures
Copying blob c530010fb61c done  
Copying blob 3de00bb8554b done  
Copying blob f3e9c03bc3ab done  
Copying config 822786b0dc done  
Writing manifest to image destination
Storing signatures
822786b0dc237e8e48acb1e1d34605d69c19ae6593acec51cbcd5ae7e4e22de6
 ~  22-04-28 14:18  ✝  ~  podman pull --authfile ~/OCS4/ocs-ci/data/pull-secret  registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.9                                                  
Trying to pull registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.9...
Error: initializing source docker://registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.9: reading manifest v4.9 in registry.redhat.io/ocs4/ocs-must-gather-rhel8: StatusCode: 404, Not found


We could pull the image , but the image was not present as we can see error "Error: initializing source docker://registry.redhat.io/ocs4/ocs-must-gather-rhel8:v4.9: reading manifest v4.9 in registry.redhat.io/ocs4/ocs-must-gather-rhel8: StatusCode: 404, Not found "

Is there anything else that needs to be validated , please feel free to let me know .


Thanks 
Mugdha Soni

**Comment by musoni123** [comment]
Hi
https://bugzilla.redhat.com/show_bug.cgi?id=2071970#c10 , this comment of
assignee @Neha Berry ***@***.***> but I am just a little confused.
Is there any documentation that needs validation ?


Thanks and Regards
Mugdha Soni

**Comment by kelbrown20** [comment]
@nehaberry @musoni123 This PR was the only thing that needed validating. Thank you for helping with this! Going to merge this PR to the live documentation.

**Pull request merged**
