### PR TITLE
cnv 2.5: Set volume mode in UI and CLI

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/CNV-5944

CP for 4.5, 4.6

### CODE REVIEW

**Comment by istein1** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@apinnick are any other reviews needed on this, or is it ready to be merged?

**Comment by apinnick** [comment]
@bergerhoffer  No other reviews required. Ready to merge. Thanks!

**Pull request merged**
