### PR TITLE
SDN-1717, updated table with Pensando DSC support

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/SDN-1717
https://issues.redhat.com/browse/OSDOCS-3686

for 4.11

Preview build: http://file.rdu.redhat.com/~ahardin/Mar-11-2022/pensando-dsc-card-support/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

### CODE REVIEW

**Comment by vrindle** [comment]
LGTM

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by zhaozhanqi** [comment]
FYI, we have bug for this card https://bugzilla.redhat.com/show_bug.cgi?id=2084010
so please do not merge this until bug is fixed.  thanks

**Comment by ahardin-rh** [comment]
@zhaozhanqi Thank you for pointing that out! I do not have authorization to view that bug, so can you let me know when the fix is addressed?

**Comment by CFields651** [comment]
The documentation update LGTM.

**Comment by ahardin-rh** [comment]
@zhaozhanqi I updated the table with a footnote per Vrinda's latest update. PTAL. Thank you!

**Comment by vrindle** [comment]
LGTM

**Comment by zhaozhanqi** [comment]
How about adding this bug https://bugzilla.redhat.com/show_bug.cgi?id=2084010 in the docs to tell the customer the current situation

**Comment by ahardin-rh** [comment]
@zhaozhanqi Thank you for the suggestion! Since not everyone (including me) is authorized to see the contents of that link, I will keep the link out of the docs for now. Thanks again!

**Pull request merged**
