### PR TITLE
Online product name updates

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bmcelvee @mburke5678 This introduces name changes for when we launch Online pro. We are only calling the product OpenShift Online, but will differentiate between Online Pro and Online Starter when needed.

**Review by adellape — COMMENTED** [review]
LGTM. We also need to update distro_map to no longer say "Starter", too:

https://github.com/openshift/openshift-docs/blob/master/_distro_map.yml#L15-L24

For Dedicated (which is also versionless for docs), we just have "Latest" there. Could also be "3"... Or "Starter and Pro"... Really it's just going to show up in the breadcrumb at the top of the page on docs.openshift.com. I don't _think_ it has any bearing on Customer Portal title. @vikram-redhat ?

@aheslin WDYT ^ ?

**Comment by ahardin-rh** [comment]
@adellape Thanks! On https://docs.openshift.com/ we use 3 in the drop-down menu, so maybe we should keep consistent? I defer to @aheslin and @vikram-redhat, however

**Comment by vikram-redhat** [comment]
The portal will need a version but I handle that behind the scenes and just use 3 (same as dedicated). Other than that, there is no issue. 

Some of it might depend on whether we need to keep the version 2 docs? If we are only keeping one set of docs we can just go the dedicated route and call it latest. But that is @aheslin 's call :)

**Comment by aheslin** [comment]
We have to keep the Online v2 docs for now since there are support exceptions for it. I'm fine with using version 3.

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
