### PR TITLE
OCPBUGS-43885:Updating NetObserv w/o Loki table for multi-tenancy

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OCPBUGS-43885
Link to docs preview:

https://84241--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/installing-operators.html#network-observability-without-loki_network_observability
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jotak — APPROVED** [review]

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by adellape — APPROVED** [review]

**Pull request merged**
