### PR TITLE
 correct placement of ephemeral resources

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.7 and above versions
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2022076)
- [Preview](https://50840--docspreview.netlify.app/openshift-enterprise/latest/applications/quotas/quotas-setting-per-project.html#quotas-scopes_quotas-setting-per-project)
- @duanwei33 ptal

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
/label LGTM

**Comment by jrosenta** [comment]
lgtm

**Pull request merged**
