### PR TITLE
BZ#1908423 - Remove tech preview status

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1908423

### CODE REVIEW

**Comment by jboxman** [comment]
Hi @zshi-redhat,

Does this still look correct?

Thank you!

**Comment by vikram-redhat** [comment]
@jboxman this is doing more than removing the tech preview?

**Comment by zshi-redhat** [comment]
/cc @SchSeba

Sebastian mentioned that dpdk base image developed by his team is not yet GAed, we probably want to make that as a note in the document.  btw, what was the support level of dpdk if customer is not using our base image?

**Comment by jboxman** [comment]
@vikram-redhat, the content really needs to be rewritten, but time, so I made the changes necessary so that it is at least coherent. Without the TP notice there are dangling headings that make no sense.

**Comment by jboxman** [comment]
@zshi-redhat, so I added back in the TP notice for DPDK. With confirmation I can always remove it, also.

**Comment by zshi-redhat** [comment]
> @zshi-redhat, so I added back in the TP notice for DPDK. With confirmation I can always remove it, also.

Cool, thank you Jason!
We decided to delay DPDK GA until base image is ready and GA RDMA in 4.7.

**Pull request merged**
