### PR TITLE
css fix for table layout issue

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For 

1. https://bugzilla.redhat.com/show_bug.cgi?id=1541737
2. https://bugzilla.redhat.com/show_bug.cgi?id=1555448
3. https://bugzilla.redhat.com/show_bug.cgi?id=1541730
4. https://bugzilla.redhat.com/show_bug.cgi?id=1541731
5. https://bugzilla.redhat.com/show_bug.cgi?id=1556821

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf can you please build from this branch locally and check if this doesn't introduce any changes to other tables?

I did test it, but need confirmation. 
Use the following command to get the changes in a local branch `CheckPR8340`
```
git fetch upstream pull/8340/head:CheckPR8340
```

**Comment by bfallonf** [comment]
@gaurav-nelson Without checking each individual table, the few I saw looked good. This included the ones from the BZs. Good job :100:

**Pull request merged**
