### PR TITLE
Fix up vsphere dynamic provisoning docs

### PR DESCRIPTION
**Pull request by gnufied**
This brings back documentation removed from https://github.com/openshift/openshift-docs/pull/3330

Fixes - https://github.com/openshift/openshift-docs/issues/4982

### CODE REVIEW

**Comment by pospispa** [comment]
LGTM

**Comment by pospispa** [comment]
@gnufied this PR is for OpenShift version 3.6+, isn't it?

**Comment by gnufied** [comment]
@pospispa yep only for 3.6

**Comment by gaurav-nelson** [comment]
@gnufied Thanks for the PR. Merging this.

**Comment by gaurav-nelson** [comment]
close #4982

**Comment by vikram-redhat** [comment]
@gaurav-nelson - this had multiple commits. Make sure to request contributors to squash their commits.

cc: @gnufied .

**Pull request merged**
