### PR TITLE
RHDEVDOCS-5170: Updating 1.9 and 1.10 RNs to clearly mention compatib…

### PR DESCRIPTION
**Pull request by shipsing**
Aligned team: Dev Tools

Purpose: To resolve the following issues:
https://issues.redhat.com/browse/RHDEVDOCS-5170

OCP version this PR applies to: enterprise 4.11 and later versions

Link to docs preview: 
1.10 RN: https://60643--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/op-release-notes.html#op-release-notes-1-10_op-release-notes
1.9 RN: https://60643--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/op-release-notes.html#op-release-notes-1-9_op-release-notes

Need an ACK from Eng: @concaf 
Need an ACK from PM: @koustavsaha
Need an ACK from Product experience: @RickJWagner 
Need an ACK from QE: @ppitonak   
Need an ACK from CS: @Preeticp  
Need an ACK from DPM: @pmkovar 
Peer review: @Srivaralakshmi

### CODE REVIEW

**Review by ppitonak — APPROVED** [review]

**Comment by shipsing** [comment]
@concaf @koustavsaha @RickJWagner Please review the PR. Thanks

**Review by koustavsaha — APPROVED** [review]
Approved

**Review by concaf — APPROVED** [review]

**Comment by pmkovar** [comment]
Approved

**Review by Srivaralakshmi — APPROVED** [review]
@shipsing clean PR. Approved!

**Comment by Preeticp** [comment]
CS Ack

**Pull request merged**
