### PR TITLE
Fix typo in the cluster limits doc

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@chaitanyaenr - what is the typo?

**Comment by chaitanyaenr** [comment]
@vikram-redhat {product-title} is not needed in the title right?

**Comment by vikram-redhat** [comment]
@chaitanyaenr - why?

**Comment by vikram-redhat** [comment]
I will close this PR. Please open a new one if there is an issue.

**Pull request closed without merging**
