### PR TITLE
BZ1913279 Adding Known issue

### PR DESCRIPTION
**Pull request by kquinn1204**
@aireilly PLease review this PR against bug 1913279 https://bugzilla.redhat.com/show_bug.cgi?id=1913279

### CODE REVIEW

**Comment by kquinn1204** [comment]
@ahardin-rh A draft preview of this issue is here http://file.emea.redhat.com/kquinn/270121/BZ1913279/release_notes/ocp-4-7-release-notes.html#ocp-4-7-known-issues

**Comment by kquinn1204** [comment]
@ahardin-rh The description of this matches that in Bugzilla and that Doc text was reviewed and approved. So this is ready to merge

**Comment by kquinn1204** [comment]
@ahardin-rh the known issue to review can be found here https://deploy-preview-28839--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-known-issues "Precision Time Protocol (PTP) faults ..."

**Comment by ahardin-rh** [comment]
Looks good! Just needs a rebase now. Thanks!

**Comment by kquinn1204** [comment]
@ahardin-rh rebase done

**Review by codyhoag — APPROVED** [review]

**Comment by codyhoag** [comment]
FYI @vikram-redhat

**Pull request merged**
