### PR TITLE
OADP-2029: Data mover , Restore - CephFS PV create time is long or PV not created

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/OADP-2029
OCP 4.12+
OADP 1.3.0
Preview:

### CODE REVIEW

**Comment by sbeskin-redhat** [comment]
@weshayutin  Please review this PR.

**Review by weshayutin — CHANGES_REQUESTED** [review]
If one documents an amount of time to backup and restore w/o mentioning PV size and network speed the information is not helpful.  I would simply refer the customer to any public performance metrics for OADP 1.3.x

**Pull request closed without merging**
