### PR TITLE
Bug 1846845, removed hostprefix value

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1846845

@chaitanyaenr PTAL. Thanks!

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@RobertKrawitz PTAL.

**Comment by RobertKrawitz** [comment]
23 will not be enough for 500 _user_ pods per node, as there are system pods running on worker nodes.  For example, I currently see 15 system pods on one of my workers and 12 on the other.  Those would come out of the 510, allowing for 495 on one node and 498 on the other.

**Comment by RobertKrawitz** [comment]
23 is the default.  It should either say nothing at all, or it should say 22.  I believe we should specify 22 in this case.

If we think that specifying 22 will cause confusion, note that there are 10-15 system pods running on the worker nodes, and that each of those takes up one of the addresses.

**Comment by chaitanyaenr** [comment]
@RobertKrawitz The limit we mention in the docs as well the default ( 250 pods per node ) represents the maximum number of pods possible on a node including both system as well as user pods, so think it's better to stick with the default ( /23 ) to avoid any confusion IMHO. Thoughts?

**Comment by RobertKrawitz** [comment]
Then don't say anything at all about the prefix, since the default is already 23.

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
@wabouhamad Can you please provide QE ack?

**Comment by wabouhamad** [comment]
It would help our customers if we could add a sentence stating that if they need 500 user pods, they would need a hostPrefix of 22 since there are 10-15 system pods already running on the node.  If we have a link to the hostPrefix where it is defined, we could add it.   If we don't mention anything we are also covered, since total pods includes both user and system pods.  I am fine either way.  But I am leaning more towards informing the customer anything we know that they could benefit from.

**Comment by ahardin-rh** [comment]
@RobertKrawitz @chaitanyaenr @wabouhamad Updated. PTAL.

**Pull request merged**
