### PR TITLE
OADP-3145: OADP 1.3.0 Attributes Updates

### PR DESCRIPTION
**Pull request by anarnold97**
### Jira

* [OADP-3145](https://issues.redhat.com/browse/OADP-3145) - see [Slack discussion](https://redhat-internal.slack.com/archives/C0144ECKUJ0/p1701202173787149?thread_ts=1701200116.943819&cid=C0144ECKUJ0)

    * Velero version moves to 1.12 to OADP 1.3.0
    
     image

### Version(s):

* OCP 4.12 → branch/enterprise-4.12
* OCP 4.13 → branch/enterprise-4.13
* OCP 4.14 → branch/enterprise-4.14
* OCP 4.15 → branch/enterprise-4.15

### Link to docs preview:

* [OADP-Velero-OpenShift Container Platform version relationship](https://68597--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/oadp-installing-operator#velero-oadp-version-relationship_installing-oadp-operator)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
Am I ok to push this to `peer-review` without QE sign-off? No problems if necessary

**Comment by mburke5678** [comment]
@anarnold97 LGTM. Please get QE review before merge review.

**Comment by anarnold97** [comment]
@mburke5678  Will do! I am sure the one and only customer on OADP 1.3 can wait to know they are using 1.12 not 1.11  (LOL)

**Review by PrasadJoshi12 — APPROVED** [review]

**Pull request merged**
