### PR TITLE
[BZ2115693] Add LSO note to add serial number for IBM Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.11+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2115693

Link to docs preview: https://52097--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-local.html#local-volume-cr_persistent-storage-local

QE review: @LakshmiRavichandran1 
- [x ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by LakshmiRavichandran1** [comment]
lgtm

**Review by snarayan-redhat — COMMENTED** [review]
Looks great! Just one comment.

**Pull request merged**
