### PR TITLE
RHDEVDOCS-5900 Update changes to the OpenShift mirror registry links

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
Jira issue : [RHDEVDOCS-5900](https://issues.redhat.com/browse/RHDEVDOCS-5900)

Aligned team: DevTools 
Cherry-pick to versions: `gitops-docs-1.12`

Docs preview:

- [Installing the GitOps CLI](https://73529--docspreview.netlify.app/openshift-gitops/latest/installing_gitops/installing-argocd-gitops-cli)

SME review: Completed @anandf

QE review: Completed @varshab1210 

Peer review: Completed @shipsing

### CODE REVIEW

**Comment by shipsing** [comment]
If the links are correct and would work fine, i am giving an LGTM @Srivaralakshmi . Right now, i cannot check the links as they are pointing to a file not found error, which should automatically be resolved once the binaries are uploaded.  

/label peer-review-done

**Review by anandf — APPROVED** [review]
LGTM. Lets wait for the actual links to be available before merging.

**Comment by Srivaralakshmi** [comment]
Hi @anandf and @varshab1210: I have retained only the RPM section and commented out the rest. Please review the changes in the PR and provide approvals. TY!

FYI, as and when the links are available, @Dhruv-Soni11 will comment in back the sections with a new PR from his side.

**Comment by varshab1210** [comment]
LGTM, thanks

**Pull request merged**
