### PR TITLE
Add links to Helm welcome page and SBO topics with minor edits

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.9`
- **JIRA issues**: [RHDEVDOCS-3528 - Add EOD to the end of the block in step 1; it is missing now](https://issues.redhat.com/browse/RHDEVDOCS-3528), [RHDEVDOCS-3563 - Add links under the additional resources section](https://issues.redhat.com/browse/RHDEVDOCS-3563), [RHDEVDOCS-3511 - Add a link to the `Deploy Helm charts` topic in the welcome page of OCP documentation](https://issues.redhat.com/browse/RHDEVDOCS-3511)
- **Preview pages**: [Developer activities](https://deploy-preview-39623--osdocs.netlify.app/openshift-enterprise/latest/welcome/index.html#developer-activities), [Additional Resources in the ODC Service Binding section](https://deploy-preview-39623--osdocs.netlify.app/openshift-enterprise/latest/applications/connecting_applications_to_services/odc-connecting-an-application-to-a-service-using-the-developer-perspective.html#additional-resources), [Additional Resources in the Getting started section](https://deploy-preview-39623--osdocs.netlify.app/openshift-enterprise/latest/applications/connecting_applications_to_services/getting-started-with-service-binding.html#additional-resources), [Step 1 command snippet in the Connecting sample app to DB service procedure](https://deploy-preview-39623--osdocs.netlify.app/openshift-enterprise/latest/applications/connecting_applications_to_services/getting-started-with-service-binding.html#connecting-the-spring-petclinic-sample-application-to-the-postgresql-database-service)
- **SME Review**: Approved by @zonggen 
- **QE review**: Approved by @pmacik
- **Peer-review**: Approved by @sounix000

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@pedjak, @dperaza4dustbit, @zonggen, and @pmacik: PTAL at the PR (minor edits) and provide feedback. Thanks!

**Review by zonggen — COMMENTED** [review]
Helm section LGTM!

**Comment by pmacik** [comment]
LGTM

**Pull request merged**
