### PR TITLE
RHDEVDOCS 2129 add 'tt.' to referenced params in 'TriggerTemplate's

### PR DESCRIPTION
**Pull request by ghost**
https://issues.redhat.com/browse/RHDEVDOCS-2129

- [x] Reviewed by <QE/SME>
- [x] peer-reviewed by DT docs - not needed, extra small tech change.
- [ ] peer-reviewed by ocp docs
- merge to ? @Preeticp

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
Approved the content as-is. No idea how to search if these are all the references. But this is the intended change. 👍

**Review by ppitonak — APPROVED** [review]

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by Preeticp** [comment]
@kalexand-rh this needs to be merged into 4.6, request you to merge, please.

**Pull request merged**
