### PR TITLE
disconnected_install: registry-console is not optional

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/5248

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@ganhuang, do these changes sound reasonable for 3.10? (I'm updating the image list here: https://github.com/openshift/openshift-docs/pull/11185/files)

**Comment by ganhuang** [comment]
@kalexand-rh Yes, looks good.

**Comment by kalexand-rh** [comment]
Thank you!

**Pull request merged**
