### PR TITLE
BZ1879959 - updating vCenter datastore permissions

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1879959

@jiajliu, will you PTAL?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Sorry, @jianlinliu, will you PTAL?

**Comment by jinyunma** [comment]
Account on vsphere7.0 is created with privileged where doc described, pv can be provisioned correctly.
So the update is LGTM.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
