### PR TITLE
Removing must-gather from dedicated distro

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://github.com/openshift/openshift-docs/issues/19627

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you review this update please?

Preview: https://github-19627--ocpdocs.netlify.com/openshift-dedicated/latest/support/getting-support.html

**Comment by lamek** [comment]
LGTM.

**Comment by zhouying7780** [comment]
LGTM.

**Pull request merged**
