### PR TITLE
mark extended builds as tech preview

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bparees** [comment]
Hold off on merging this, the term.should be tech preview, not experimental

**Comment by bparees** [comment]
ok updated.

**Comment by ahardin-rh** [comment]
@bparees LGTM. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/builds.adoc#dev-guide-builds[Builds]
|Added a xref:../dev_guide/builds.adoc#extended-builds[Note box] indicating that extended builds is a technology preview feature.
%

**Comment by bparees** [comment]
@ahardin-rh apparently @smarterclayton would prefer we write this as "X is in technology preview" and not "X is a technology preview", can you update the doc and enforce it on future authors?

thanks

**Comment by ahardin-rh** [comment]
@bparees Sure! Follow-up edits are here: https://github.com/openshift/openshift-docs/pull/2638

**Pull request merged**
