### PR TITLE
[OCPBUGS-42690]Added $ before the start of the comment in `Deleting a hosted cluster from your source management cluster` procedure 

### PR DESCRIPTION
**Pull request by PoornimaSingour**
[OCPBUGS-42690]Added $ before the start of the comment

Version(s):

4.17, 4.16, 4.15,4.14
Issue:

https://issues.redhat.com/browse/OCPBUGS-42690

Link to docs preview:

https://82857--ocpdocs-pr.netlify.app/
https://82857--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-aws.html
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dfitzmau** [comment]
I see peer review and merge review labels. These labels should not be applied at the same time. Reason: the logical order of reviews is 1) peer review and 2) merge review. Please let me know if the peer review is needed here or if I missed something?

**Comment by mburke5678** [comment]
> I see peer review and merge review labels. 

@dfitzmau My bad. All apologies.

**Pull request merged**
