### PR TITLE
OSDOCS-4056: Update registry documentation for MCO behavior

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.10+

Issue:
https://issues.redhat.com/browse/OSDOCS-4056

Link to docs preview:
https://53915--docspreview.netlify.app/openshift-enterprise/latest/openshift_images/image-configuration.html#images-configuration-file_image-configuration

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
Hi @xiuwang! Would you mind giving this PR a review, please? 

And since this is MCO related, @rioliu-rh would you mind also giving this PR a review, please?

Thank you!

**Comment by xiuwang** [comment]
@bmcelvee the existing update LGTM
but we may need also update https://docs.openshift.com/container-platform/4.10/openshift_images/image-configuration.html#images-configuration-file_image-configuration step 2 in Procedure: to 
```
To check that the changes are applied, list your nodes:
Example output
NAME                                         STATUS                     ROLES                  AGE   VERSION
ip-10-0-137-182.us-east-2.compute.internal   Ready,SchedulingDisabled   worker                 65m   v1.25.4+77bec7a
ip-10-0-139-120.us-east-2.compute.internal   Ready,SchedulingDisabled   control-plane,master   74m   v1.25.4+77bec7a
ip-10-0-176-102.us-east-2.compute.internal   Ready                      control-plane,master   75m   v1.25.4+77bec7a
ip-10-0-188-96.us-east-2.compute.internal    Ready                      worker                 65m   v1.25.4+77bec7a
ip-10-0-200-59.us-east-2.compute.internal    Ready                      worker                 63m   v1.25.4+77bec7a
ip-10-0-223-123.us-east-2.compute.internal   Ready                      control-plane,master   73m   v1.25.4+77bec7a
```

**Comment by bmcelvee** [comment]
Thank you @xiuwang!

**Comment by jboxman-rh** [comment]
@bmcelvee LGTM

**Comment by xiuwang** [comment]
LGTM

**Pull request merged**
