### PR TITLE
autopreview: add vrutkovs

### PR DESCRIPTION
**Pull request by vrutkovs**
Adding myself to autopreview whitelist so that I could fix several
OTA/OKD doc issues efficiently

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, PTAL?

**Comment by vikram-redhat** [comment]
Hey @vrutkovs - I apologize. The autopreview is only available for docs team. To test it locally, just run asciibinder in your feature branch and view the content via your browser by navigating to it in the _preview folder.

**Comment by vrutkovs** [comment]
Oh, no worries, I managed to generate OKD docs locally

**Pull request closed without merging**
