### PR TITLE
OCPBUGS#13383: affinity rules in the YAML correction

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.12+

**Issue:** OCPBUGS-13383

**Link to docs preview:**
https://danielclowers.github.io/rh-previews/OCPBUGS-13383/virt/virtual_machines/advanced_vm_management/virt-specifying-nodes-for-vms.html#virt-example-vm-node-placement-pod-affinity_virt-specifying-nodes-for-vms

**QE review:**
- [x] QE has approved this change.

**Additional information:**
NA

### CODE REVIEW

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by kbidarkar** [comment]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
