### PR TITLE
Remove: apiserver cannot handle logLevel and operatorLogLevel

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1791888

New BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816115
Need to set a CR(s) to Unmanaged?

Update: Per Tushar Underlying bug might get fixed. Topic might not need to be removed.
https://bugzilla.redhat.com/show_bug.cgi?id=1791888#c6

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@sferich888 @xltian can you give an ack for us to remove this from the documentation. See: https://bugzilla.redhat.com/show_bug.cgi?id=1791888#c3. 

@mburke5678 not sure if @tkatarki is the right PM for this?

**Comment by mburke5678** [comment]
@sferich888 @xltian can you give an ack for us to remove this from the documentation. 
https://docs.openshift.com/container-platform/4.3/nodes/nodes/nodes-nodes-audit-log.html#nodes-nodes-audit-log-basic-config_nodes-nodes-audit-log

See: https://bugzilla.redhat.com/show_bug.cgi?id=1791888#c3.

**Comment by sferich888** [comment]
@deads2k  why is the original box not a product bug?

**Comment by xltian** [comment]
@xingxingxia  Can you review?

**Comment by xingxingxia** [comment]
LGTM

**Comment by mburke5678** [comment]
@sferich888 @deads2k Any thoughts on [Eric's comment above](https://github.com/openshift/openshift-docs/pull/19721#issuecomment-592284429) and for removing this topic from the docs?

**Comment by mburke5678** [comment]
@tkatarki Any thoughts on removing this topic from the docs?

**Comment by calfonso** [comment]
LGTM

**Comment by mburke5678** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/20905. That PR removes the topic and has other changes to the audit log docs.

**Pull request closed without merging**
