### PR TITLE
Admin command to isolate project network

### PR DESCRIPTION
**Pull request by pravisankar**
Docs for trello card: https://trello.com/c/RrVYvOJj/30-3-support-admin-cli-cmd-to-isolate-projects-sdn-functionality

### CODE REVIEW

**Comment by pravisankar** [comment]
@adellape PTAL

**Comment by ahardin-rh** [comment]
@pravisankar I have this marked for 3.3. Should it be in 3.2 as well? Thanks!

**Comment by ahardin-rh** [comment]
Continuing work in https://github.com/openshift/openshift-docs/pull/2912

**Comment by pravisankar** [comment]
@ahardin-rh This feature was implemented in 3.3. So mark it for 3.3 but not for 3.2

**Pull request closed without merging**
