### PR TITLE
OSDOCS-4327: Added ODF to list of supported storage solutions

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.9+

Issue:
https://issues.redhat.com/browse/OSDOCS-4327

Edits from content audit work.

Link to docs preview:
https://56832--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/optimizing-storage.html#scaled-registry

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jhou1 Can you please provide QE verification? Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by duanwei33** [comment]
I think ODF is supported, but cc @xiuwang (registry QE) to double confirm.

**Pull request merged**
