### PR TITLE
TELCODOCS-1893-RN creating RN

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-1893]: SriovOperatorConfig will no longer be created by the Operator in 4.16 and onwards

Version(s): 4.16 and main

Issue:https://issues.redhat.com/browse/TELCODOCS-1893

Link to docs preview: https://77280--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-networking-create-sriovoperatorconfig_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by kquinn1204** [comment]
Thank you @mletalie I squashed and set to merge review needed

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
