### PR TITLE
Fixed Global Build Defaults unit per BZ

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1520830

### CODE REVIEW

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL

**Comment by bfallonf** [comment]
@mburke5678 LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation BUMP

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by mburke5678** [comment]
[rev_history]
|xref:../install_config/build_defaults_overrides.adoc#install-config-build-defaults-overrides[Configuring Global Build Defaults and Overrides]
|Changed the units from `m` to `Mi` in the xref:../install_config/build_defaults_overrides.adoc#ansible-setting-global-build-defaults[Example Build Defaults Configuration].
%

**Pull request merged**
