### PR TITLE
OpenStack on OCP Ref Arch docs

### PR DESCRIPTION
**Pull request by vikram-redhat**
This is a follow up to fix the build issues in the original PR: #12043 and squash the commits.

This has been QE reviewed by @shlao and peer reviewed by @ahardin-rh . @ahardin-rh if there are more edits required, can you please follow up?

cc: @rlopez133 @aheslin

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@rlopez133 - I don't know if this would apply directly to the 3.11 branch? Can you confirm? If yes, I will CP to that branch as well. At the minimum, I guess we should need to change the comments from the original PR: https://github.com/openshift/openshift-docs/pull/12043#issuecomment-422578125

**Comment by vikram-redhat** [comment]
@ahardin-rh - some substitutions are not working. For example: {rhosp}: https://docs.openshift.com/container-platform/3.10/install_config/configuring_openstack.html. And I think there is an issue with headings as well. Can you please take a look and do a follow up?

**Comment by rlopez133** [comment]
It should be similar for OCP 3.11. Also, versions would need to be fixed for Ansible and OCP if you were to place it in the 3.11 branch.

**Comment by vikram-redhat** [comment]
Thanks @rlopez133. @ahardin-rh  - can you please do a follow up for 3.11?

**Pull request merged**
