### PR TITLE
OCPBUGS#6828: Correct the supported RHEL versions

### PR DESCRIPTION
**Pull request by xenolinux**
Correct the supported RHEL versions 

Version(s): 4.12 only

Issue:  https://issues.redhat.com/browse/OCPBUGS-6828

Link to docs preview: https://56115--docspreview.netlify.app/openshift-enterprise/latest/updating/updating-cluster-rhel-compute.html#rhel-compute-updating-minor_updating-cluster-rhel-compute

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by gpei** [comment]
The changes to 4.12 looks good to me

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by bergerhoffer** [comment]
@xenolinux Same thing as what I commented in #56113. This PR is marked for 4.12 only but it is targeting main. This needs to target enterprise-4.12 directly. Can you please do that? There are instructions in the manual about changing the branch if needed. That sometimes works instead of creating a whole new branch/PR.

**Comment by xenolinux** [comment]
PR is closed in favor of https://github.com/openshift/openshift-docs/pull/59636

**Pull request closed without merging**
