### PR TITLE
OSDOCS#8720: Clean up redundant content in Preparing to install on vS…

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.15+

Issue:
This PR addresses [osdocs-8720](https://issues.redhat.com/browse/OSDOCS-8720) and implements refactored installation content, which is detailed in this Miro [board](https://miro.com/app/board/uXjVNbUhuKQ=/). This refactor has been approved by Stephanie Stout (CS) and Ju Lim (Senior Manager, Product Management).

Link to docs preview:

[Installation methods](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/preparing-to-install-on-vsphere)

IPI

- [Installing a cluster on vSphere](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned)
- [Installing a cluster on vSphere with customizations](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations)
- [Installing a cluster on vSphere with network customizations](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations)
- [Installing a cluster on vSphere in a restricted network](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere)

UPI

- [Installing a cluster on vSphere](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-vsphere)
- [Installing a cluster on vSphere with network customizations](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-vsphere-network-customizations)
- [Installing a cluster on vSphere in a restricted network](https://70949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-restricted-networks-vsphere)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@jinyunma As part of a larger effort to simply the complexity of the vSphere installation docs, I am cleaning up `installing/installing_vsphere/preparing-to-install-on-vsphere.adoc` as this topic unnecessarily repeats content that already exists elsewhere in the vSphere installation docs - details are in [osdocs-8720](https://issues.redhat.com/browse/OSDOCS-8720).

I did want to bring one item to your attention. As part of the effort, I reconciled the list under `Prerequisites` and moved the following statement to each of the installation topics.

"You reviewed your VMware platform licenses. Red Hat does not place any restrictions on your VMware licenses, but some VMware infrastructure components require licensing."

Outside of the latter, no technical content has been updated or added. This PR simply removes redundant content. PTAL.

**Comment by jinyunma** [comment]
@sgaoshang could you help to review this doc PR? thanks.

**Pull request merged**
