### PR TITLE
BZ1894537: CNV RHV VM disk too large for Ceph RBD block

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1894537
CP to 4.5, 4.6, 4.7. If there is a problem with CP to 4.5, I will create a separate PR.

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by apinnick** [comment]
@bergerhoffer QE wants to add a note for the VMware that is related. Moving to draft for a little bit.

**Comment by apinnick** [comment]
@bergerhoffer QE has reviewed the latest change. Ready to merge.

**Pull request merged**
