### PR TITLE
OSSMDOC-629: add note to supported configurations topic.

### PR DESCRIPTION
**Pull request by JStickler**
[OSSMDOC-629](https://issues.redhat.com/browse/OSSMDOC-629)

Version(s): 4.6 - 4.11

This PR adds a sentence to clarify that the supported versions applies to the SMCP and not the Operator.
Also moves an XREF out of the module and into the Assembly file.

Link to docs preview: http://file.bos.redhat.com/jstickle/OSSMDOC-629/service_mesh/v2x/preparing-ossm-installation.html#ossm-supported-platforms_preparing-ossm-installation

QE review - pbajjuri20
Peer review - rolfedh

### CODE REVIEW

**Comment by pbajjuri20** [comment]
It looks perfect.

**Review by pbajjuri20 — APPROVED** [review]

**Review by rolfedh — APPROVED** [review]

**Pull request merged**
