### PR TITLE
Fix table entry to be pipeline (not custom)

### PR DESCRIPTION
**Pull request by sspeiche**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sspeiche Thanks! Does this apply to 3.3+?

**Comment by sspeiche** [comment]
@ahardin-rh hmm, pipelines was techpreview in 3.3 so maybe. It was officially supported in 3.4

**Comment by ahardin-rh** [comment]
@sspeiche Thanks!

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
