### PR TITLE
Ensure ROSA STS region is a var

### PR DESCRIPTION
**Pull request by jharrington22**
Ensure we creating the OIDC provider with the correct region spec for the S3 bucket

### CODE REVIEW

**Comment by vkareh** [comment]
This is wrong - the `rh-oidc` bucket is owned by App-SRE and it lives in `us-east-1`. OCM just creates a new folder with the cluster ID to put the OIDC config in it.

**Comment by jharrington22** [comment]
Thanks @vkareh clsoing.

**Comment by vkareh** [comment]
@jonquilwilliams - this PR is wrong, as the region is hard-coded by App-SRE to _always_ be `us-east-1`. Merging it will lead to the documentation being incorrect.

**Pull request merged**
