### PR TITLE
RHDEVDOCS-3431 -- removed  #32M from configuring-logging-collector

### PR DESCRIPTION
**Pull request by libander**
DevTools
Version(s): main, 4.11, 4.10, 4.9, 4.8, 4.7, 4.6
Issue: https://issues.redhat.com/browse/RHDEVDOCS-3431
Link to docs preview: https://deploy-preview-45166--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-collector.html#cluster-logging-collector-tuning_cluster-logging-collector
Reviewers: 
Peer: @rolfedh 
SME: [kabirbhartiRH](https://github.com/kabirbhartiRH) 
QE: [anpingli](https://github.com/anpingli)

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]

**Comment by kabirbhartiRH** [comment]
@libander I think we need to change the maximum size of the chunk buffer in ClusterLogging manifest as well.

Under 'Add or modify any of the following parameters', totalLimitSize should be less than or equal to 8M

`apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  forwarder:
    fluentd:
      buffer:
        chunkLimitSize: 8m 
        flushInterval: 5s 
        flushMode: interval 
        flushThreadCount: 3 
        overflowAction: throw_exception 
        retryMaxInterval: "300s" 
        retryType: periodic 
        retryWait: 1s 
        totalLimitSize: 32m 
...`

**Comment by libander** [comment]
> @libander I think we need to change the maximum size of the chunk buffer in ClusterLogging manifest as well.
> 
> Under 'Add or modify any of the following parameters', totalLimitSize should be less than or equal to 8M

I had another PR recently where the unit for values was case sensitive - is that the case here as well? (should it be `8M` for both?)

**Comment by kabirbhartiRH** [comment]
> > @libander I think we need to change the maximum size of the chunk buffer in ClusterLogging manifest as well.
> > Under 'Add or modify any of the following parameters', totalLimitSize should be less than or equal to 8M
> 
> I had another PR recently where the unit for values was case sensitive - is that the case here as well? (should it be `8M` for both?)

I actually tested with the below config
```
 <buffer>
      @type file
      path '/var/lib/fluentd/retry_default'
      flush_mode interval
      flush_interval 5s
      flush_thread_count 3
      retry_type periodic
      retry_wait 1s
      retry_max_interval 300s
      retry_timeout 60m
      queued_chunks_limit_size "#{ENV['BUFFER_QUEUE_LIMIT'] || '32'}"
      total_limit_size 8m
      chunk_limit_size 8M
      overflow_action throw_exception
    </buffer>
```

I don't see any issue on collector pods and i do see the logs. Think it's more of a convention to use cap M instead of m and keep it uniform through out our logging docs.

**Comment by anpingli** [comment]
Please update the the  fluentd.conf  example as below. 
   <buffer>
      @type file
      path '/var/lib/fluentd/default'
      flush_mode interval
      flush_interval 5s
      flush_thread_count 3
      retry_type periodic
      retry_wait 1s
      retry_max_interval 300s
      retry_timeout 60m
      queued_chunks_limit_size "#{ENV['BUFFER_QUEUE_LIMIT'] || '32'}"
      total_limit_size 32m
      chunk_limit_size 8m
      overflow_action throw_exception
    </buffer>

**Pull request merged**
