### PR TITLE
clarify secret injector behaviour with alternate git URI style

### PR DESCRIPTION
**Pull request by jim-minter**
Hopefully this change is a clarification.  It should go into all branches which have this doc section.

### CODE REVIEW

**Comment by jim-minter** [comment]
@bparees fyi

**Comment by bparees** [comment]
lgtm

**Comment by jim-minter** [comment]
@bmcelvee @ahardin-rh would it be possible to merge this?

**Comment by bmcelvee** [comment]
@jim-minter Sure thing!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/builds/build_inputs.adoc#dev-guide-build-inputs[Build Inputs]
|Clarified the xref:../dev_guide/builds/build_inputs.adoc#automatic-addition-of-a-source-secret-to-a-build-configuration[Automatically Adding a Source Clone Secret to a Build Configuration] section.
%

**Pull request merged**
