### PR TITLE
BZ1343292: Changed plugin to plug-in, where applicable

### PR DESCRIPTION
**Pull request by tpoitras**
https://bugzilla.redhat.com/show_bug.cgi?id=1343292

Still had some pesky uses of "plugin" laying around. There were plenty I couldn't change, due to them being in file names, env var names, lines of YAML, etc. But I changed the ones I could.

@bfallonf - mind taking a squizz here? Thanks! :octopus:

### CODE REVIEW

**Comment by bfallonf** [comment]
@tpoitras Looks good to me :fish:

**Comment by adellape** [comment]
@tpoitras This commit was picked to the 3.1 branches, but I'm going to revert them on those branches because the API topics changed a lot between 3.1 and 3.2. If you want to make the plug-in fixes for the 3.1 REST API topics, you'll probably need to go make those specifically on those branches. cc @vikram-redhat

**Comment by adellape** [comment]
Reverting the commit will unfortunately undo the legitimate changes in other topics tho. So basically at this point I think you'll need to go make these changes directly on the 3.1 branches for all the topics. Sorry.

**Comment by tpoitras** [comment]
@adellape - hey thanks for the heads-up on that one, sorry I seem to have missed this notification earlier.

@vikram-redhat - do you want me to make the plugin -> plug-in changes directly into the 3.1 branch?

**Comment by vikram-redhat** [comment]
@tpoitras - yeah. If I understand correctly, all the other branches have this change now and only 3.1 doesn't because of the other commits that got pulled in. So, yes, at this stage, I think the best thing to do is to make these changes directly in the 3.1 branch.

**Pull request merged**
