### PR TITLE
BZ1879066: modify the note regarding session persistence for 4.7

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applicable for 4.7

Doc preview link: https://deploy-preview-35547--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-network-user-infra_installing-bare-metal

https://bugzilla.redhat.com/show_bug.cgi?id=1879066

Requires QA ack from @gpei

### CODE REVIEW

**Comment by mburke5678** [comment]
@chinmayi-chandrasekar LGTM

**Comment by gpei** [comment]
sorry, no idea about the `session persistence for an API load balancer `, @wsun1 do you know anyone may be familiar with this?

**Comment by wsun1** [comment]
@lihongan HI Hongan, could you please review this one?

**Comment by lihongan** [comment]
LGTM
Thank you @chinmayi-chandrasekar

**Pull request merged**
