### PR TITLE
OSDOCS-10649: Adding update steps for Entra cluster

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.14+

Issue:
[OSDOCS-10649](https://issues.redhat.com//browse/OSDOCS-10649)

Link to docs preview:
[Updating cloud provider resources with the Cloud Credential Operator utility](https://77460--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/preparing_for_updates/preparing-manual-creds-update.html#cco-ccoctl-upgrading_preparing-manual-creds-update)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@huangmingxia this is ready for a look I think :)

**Review by huangmingxia — CHANGES_REQUESTED** [review]
LGTM for reset. ( After the update, I'll review it again. Thank you.)

**Comment by jeana-redhat** [comment]
> LGTM for reset. ( After the update, I'll review it again. Thank you.)

Awesome, thanks :)

**Comment by jeana-redhat** [comment]
> /lgtm

Thank you so much!

**Pull request merged**
