### PR TITLE
EDNS from TP to GA

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.11 only

Issue: None

Link to docs preview: [file.rdu.redhat.com/sdudhgao/edns-op/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview](http://file.rdu.redhat.com/sdudhgao/edns-op/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview)

Additional information:

### CODE REVIEW

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by kalexand-rh** [comment]
@xenolinux, you need to take this through change management.

**Comment by jboxman-rh** [comment]
I can confirm that email went out; I'll merge.

**Pull request merged**
