### PR TITLE
JIRA: OSDOCS-1964: User must be an IAM user

### PR DESCRIPTION
**Pull request by kmccarron-rh**
https://issues.redhat.com/browse/OSDOCS-1964

Direct link to the change:
https://deploy-preview-31468--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-aws-prereqs.html#rosa-customer-requirements_prerequisites

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
@0kashi  @sfortner-RH This is ready for review!

**Review by sfortner-RH — APPROVED** [review]
LGTM! Once @okashi18 acks the PR, I can merge it.

**Comment by kmccarron-rh** [comment]
Changed "Select" to "Login to" - per request in JIra comment

**Comment by kmccarron-rh** [comment]
@0kashi - Your email seemed to indicate this location for the note. Is this what you are expecting?

**Comment by 0kashi** [comment]
Looks good.

**Comment by kmccarron-rh** [comment]
@sfortner-RH  - Looks like we are good to merge!

**Pull request merged**
