### PR TITLE
Changed the HPA section to note and changed wording.

### PR DESCRIPTION
**Pull request by mburke5678**
See [4829](https://github.com/openshift/openshift-docs/pull/4829) for reference

### CODE REVIEW

**Comment by mburke5678** [comment]
@pmorie I added the "Autoscaling the metrics components, such as Hawkular and Heapster, is not supported by {product-title}." wording to the 3.4 docs, as we discussed in [4829](https://github.com/openshift/openshift-docs/pull/4829) for 3.5. 
The information in the 3.4 docs is in a different file. PTAL and let me know if this location is OK. 
Should we apply the same wording to 3.3?

**Review by DirectXMan12 — APPROVED** [review]
LGTM :+1:

**Comment by DirectXMan12** [comment]
> Should we apply the same wording to 3.3?

Yeah, probably a good idea :-)

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
LGTM (pending a squash) :eggplant: :smiley_cat:

**Comment by mburke5678** [comment]
Merging. No rev history needed.

**Pull request merged**
