### PR TITLE
Add Metering and Cost Management to TP Matrix

### PR DESCRIPTION
**Pull request by briantward**
Addition to the TP list for Metering and Cost Management

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Hi @briantward thanks for submitting this and the ones for the 4.3/4.4.

I am aware of Metering, but not Cost Management. Even with Metering, could we get acks from product experience (@sferich888), QE (@xltian) and PM (Sergio Ocón-Cárdenas for Metering) (I am not sure who the PMs are for Cost management).

Finally, although metering content is published by the OpenShift docs team, cost management docs are not. I am not sure what the integration of cost management with OCP is and if it makes sense to add this here.

**Comment by vikram-redhat** [comment]
@codyhoag ^

**Comment by sferich888** [comment]
Do we have feature docs for these?

**Comment by briantward** [comment]
@vikram-redhat Fair point... Sergio is the PM for cost management too, and it did escape me that they aren't published at OpenShift docs.  See https://issues.redhat.com/browse/COST-415

We could at least cover Metering here? My biggest concern was really Cost Management though, because there is no published information on when it went GA. So I'll chase that down on the customer portal docs.

**Comment by codyhoag** [comment]
@sferich888 We have Metering fully documented (i.e., [here](https://docs.openshift.com/container-platform/4.5/metering/metering-about-metering.html)). I don't know much about Cost Management, but there are docs for it on the Customer Portal (i.e., [here](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/getting_started_with_cost_management/index)).

@vikram-redhat Due to our current RN tracking process, we only list features in the TP table that were in TP within the past three releases. Therefore, if we follow that process here, we would not add anything to 4.5 (since both our GA'd from 4.3-4.5). For the other 4.3/4.4 PRs, we would need to adjust accordingly. Let me know if this does not apply for this case.

**Comment by vikram-redhat** [comment]
> @sferich888 We have Metering fully documented (i.e., [here](https://docs.openshift.com/container-platform/4.5/metering/metering-about-metering.html)). I don't know much about Cost Management, but there are docs for it on the Customer Portal (i.e., [here](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/getting_started_with_cost_management/index)).
> 
> @vikram-redhat Due to our current RN tracking process, we only list features in the TP table that were in TP within the past three releases. Therefore, if we follow that process here, we would not add anything to 4.5 (since both are GA'd from 4.3-4.5). For the other 4.3/4.4 PRs, we would need to adjust accordingly. Let me know if this does not apply for this case.

No exceptions for this, and we should get @briantward to change the PR.

**Comment by codyhoag** [comment]
Since Metering and Cost Management are both listed as GA for 4.5 and the previous two releases in the Tech Preview table, I'm closing this. These entries will be added into the 4.3 and 4.4 release notes, as discussed.

**Pull request closed without merging**
