### PR TITLE
BZ2080277 - Adding warning for RAID config

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.6+
[Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2080277)

Preview: [Scalability and performance -> Optimizing Storage](https://deploy-preview-45719--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/optimizing-storage.html#other-specific-application-storage-recommendations)

### CODE REVIEW

**Comment by kelbrown20** [comment]
@bharath-b-rh This is just a start for this bug fix. Were there other specific details that you thought would be informative to include?

**Comment by mburke5678** [comment]
@kelbrown20 I think the preferred wording for suggestions is _It is recommended_ or _It is not recommended_. 

Would something like _It is not recommended to use RAID configurations..._

**Comment by kelbrown20** [comment]
> @kelbrown20 I think the preferred wording for suggestions is _It is recommended_ or _It is not recommended_.
> 
> Would something like _It is not recommended to use RAID configurations..._

@mburke5678 Hi Michael! Just a question, I thought that we are not suppose to use the word recommend. 
https://redhat-documentation.github.io/supplementary-style-guide/#recommend
 I might be confused with the context though

**Pull request merged**
