### PR TITLE
RHDEVDOCS-6252: Remove deprecated tls_hostname_override parameter fro…

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `pipelines-docs-1.15`, `pipelines-docs-1.16`

Issue: [RHDEVDOCS-6252](https://issues.redhat.com/browse/RHDEVDOCS-6252)

Link to docs preview: https://84477--ocpdocs-pr.netlify.app/openshift-pipelines/latest/records/using-tekton-results-for-openshift-pipelines-observability.html#installing-results_using-tekton-results-for-openshift-pipelines-observability

QE review:
- [x] QE has approved this change.

**Additional information:**

### CODE REVIEW

**Comment by eromanova97** [comment]
Hello @ppitonak could you please review this PR? Thank you!

**Review by ppitonak — APPROVED** [review]

**Comment by eromanova97** [comment]
Waiting before merging this as I need verification from @khrm if this is reallly for Pipelines 1.15+ (see [comment](https://github.com/openshift/openshift-docs/pull/84478#discussion_r1830713708))

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Pull request merged**
