### PR TITLE
[4.3] BZ-1775210: Mention to have the proxy env variables set for DR proced…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ures

Transferred from #18705 so that that PR can be used to update 4.4+, as the procedures changed.

Preview: http://file.rdu.redhat.com/~ahoffer/2020/BZ-1775210-43/backup_and_restore/backing-up-etcd.html (internal)

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@geliu2016 This is the new PR for 4.3/4.2, if you can give it a quick double check that it's okay.

**Comment by geliu2016** [comment]
LGTM, thanks

**Pull request merged**
