### PR TITLE
4.11 Release notes stub

### PR DESCRIPTION
**Pull request by sheriff-rh**
Update per https://github.com/openshift/openshift-docs/issues/43249#issuecomment-1157438812

Version(s):
4.11 only

Issue:
https://github.com/openshift/openshift-docs/issues/43249#issuecomment-1157438812

Link to docs preview:
[FedRAMP High SCAP profile](http://file.rdu.redhat.com/antaylor/06-28-22/4.11RNs/release_notes/ocp-4-11-release-notes.html#ocp-4-11-fedramp-high)

[Known Issues](http://file.rdu.redhat.com/antaylor/06-28-22/4.11RNs/release_notes/ocp-4-11-release-notes.html#ocp-4-11-known-issues)

Additional information:
This update applies to 4.11 only and includes the FedRAMP High profile in the "new features and enhancements" section. This section cross references the Supported Compliance Operator profiles table, which will be merged separately: https://github.com/openshift/openshift-docs/pull/47169
     Those changes are made against the main branch so they are available in future releases and the pull request will be merged when the final Operator release version is available. 
     
I also added a bug to the known issue section of the release notes.

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@Vincent056  and @xiaojiey  please review when you have a chance. Thanks

**Comment by xiaojiey** [comment]
@sheriff-rh One question is that we are not following OCP release any more(since about 1 week ago, the milestones was changed to release-0.1/0.2). So I am not quite sure if we still need to add it in OCP 4.11 release notes or not. 
@Jhrozek @Vincent056  any comment?

**Comment by sheriff-rh** [comment]
That's true, we could make these changes to the CO release notes when they are available.

**Comment by jhrozek** [comment]
> That's true, we could make these changes to the CO release notes when they are available.

I think that would be better in the end, because our schedule will become over time completely random. And because we push the CO releases to all supported OCP releases, we would just have to keep the CO docs up to date.

**Comment by sheriff-rh** [comment]
Content was pulled into https://github.com/openshift/openshift-docs/pull/47169 and published to all maintained branches. Closing this PR.

**Pull request closed without merging**
