### PR TITLE
BZ-1920015: Added a paragraph about the maximum

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.5+
Pending QE Approval: @lihongan 
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1920015
Preview Link:https://deploy-preview-32154--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration [Route annotations table]

### CODE REVIEW

**Comment by sagidlow** [comment]
@lihongan for QE review.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by lihongan** [comment]
LGTM. 
Thank you @sagidlow . Sorry for the late feedback.

**Pull request merged**
