### PR TITLE
[OSDOCS-3677] Removing tech preview language

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.14

Issue:https://issues.redhat.com/browse/OSDOCS-6377

Link to docs preview:
https://63609--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal#installation-load-balancing-user-infra_installing-bare-metal

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
Which versions of OCP does this PR apply to? Please add this info to the first comment block. Otherwise, LGTM

**Comment by maxwelldb** [comment]
@itzikb-redhat Looks like this is ready for QE.

**Comment by jmanthei** [comment]
/label sme-review-needed
@ Itshak Brown (? Can't seem to find him here)

**Comment by maxwelldb** [comment]
@itzikb-redhat

**Comment by itzikb-redhat** [comment]
@imatza-rh

**Comment by bscott-rh** [comment]
Merge review LGTM. @jmanthei put the SME review label on the PR - is that still needed or am I good to merge?

**Comment by jmanthei** [comment]
@bscott-rh We are good to merge, SME gave it a LGTM, I squashed commits and "removed" the label.
Thank you so much.

**Comment by bscott-rh** [comment]
Merged and cherrypicked to 4.14.

**Pull request merged**
