### PR TITLE
[GH44741] Correct supported ShiftStack versions 

### LINKED ISSUE #44741: [enterprise-4.9] Issue in file architecture/architecture-installation.adoc
### Which section(s) is the issue in?
In "[Supported platforms for OpenShift Container Platform clusters](https://docs.openshift.com/container-platform/4.9/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation)"

### What needs fixing?
OpenStack 13 is listed as a supported platform for OCP 4.9 IPI.  We dropped support for 13 in 4.9.  4.9 AND 4.10 only supports OSP 16.1 and 16.2  We may also want to specify in the UPI section which versions of OSP we support (16.1/16.2)

### PR DESCRIPTION
**Pull request by maxwelldb**
FYI @EricArrakis 

Fixes #44741

Preview: https://deploy-preview-44750--osdocs.netlify.app/openshift-enterprise/latest/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation

QE ack: https://github.com/openshift/openshift-docs/pull/44750#issuecomment-1106473823

### CODE REVIEW

**Comment by maxwelldb** [comment]
@eurijon Could you confirm that OCP 4.9+ support only OSP 16.1 and 16.2 at the moment?

**Comment by eurijon** [comment]
> @eurijon Could you confirm that OCP 4.9+ support only OSP 16.1 and 16.2 at the moment?

That's correct :)
/lgtm

**Comment by tmalove** [comment]
LGTM!

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
