### PR TITLE
Fix typos to unify the style

### PR DESCRIPTION
**Pull request by lbscorpio**
@vikram-redhat There are some typos on button which not follow up the same style(confirmed with @Preeticp [here](https://github.com/openshift/openshift-docs/pull/35481#pullrequestreview-791445235)), minimum version that the change applies to should be 4.6 in my opinion, could you arrange someone to review them? Thanks.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
This might be best for peer review squad to look and comment on. I will tag them in Slack.

**Comment by bmcelvee** [comment]
These changes LGTM. @Preeticp would you mind also giving this PR an ack, please?

@reginapizza, would you mind giving this PR a review too? Thank you!

**Comment by Preeticp** [comment]
LGTM from my side as well @bmcelvee

**Review by reginaelyse — APPROVED** [review]
LGTM!

**Comment by Preeticp** [comment]
@lbscorpio if you resolve the conflict @bmcelvee can go ahead and merge this.

**Comment by lbscorpio** [comment]
@Preeticp @bmcelvee I have solved the conflict, could you have a quick look? Thanks.

**Comment by bmcelvee** [comment]
Looks good! Merging now.

**Pull request merged**
