### PR TITLE
Updated the script to track changes in _topic_maps folder

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Fixes the issues with preview generation for PR's like https://github.com/openshift/openshift-docs/pull/63705 in which only `_topic_maps/_topic_map.yml` file was modified.

Cherry-pick:
 - `enterprise-10+`
 - all other distro branches

### CODE REVIEW

**Review by aireilly — APPROVED** [review]
lgtm

**Comment by gaurav-nelson** [comment]
@kalexand-rh, @gabriel-rh please cherrypick this one to your distro branches. 🚀

**Pull request merged**
