### PR TITLE
HCCDOC#1687: remove basic authentication config options from the Usin…

### PR DESCRIPTION
**Pull request by kblake2016**
…g Insights Operator section

Version(s):
PR applies to 4.12+

Issue:
https://issues.redhat.com/browse/HCCDOC-1687

Link to docs preview:
https://67946--docspreview.netlify.app/

QE review:
- [x ] QE has approved this change. @tremes 

Additional information:
/label merge-review-needed

### CODE REVIEW

**Comment by tremes** [comment]
Great. Thank you. Please backport to 4.13 and 4.12 if possible.
/approve
/lgtm

**Comment by kblake2016** [comment]
PR applies to 4.12, 4.13, 4.14, 4.15

**Comment by kblake2016** [comment]
Please assign a peer reviewer and merge reviewer. Thank you.

**Comment by kblake2016** [comment]
PR applies to 4.12+

**Comment by kcarmichael08** [comment]
This looks good to me for peer review. 

One note: I'm not familiar with RH Insights, so I'm not sure if any type of [change management](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.nckpao8upx1u) is required on the OpenShift doc side. Maybe it has actually been done already since it looks from the ticket like there have been a lot of discussions with customers, KCS articles, etc. It is on the peer review checklist, so I thought I would note it here.

**Comment by kblake2016** [comment]
/label merge-review-needed

Also, for your reference, here's a link to the direct docs page in the preview [https://67946--docspreview.netlify.app/openshift-enterprise/latest/support/remote_health_monitoring/using-insights-operator#insights-o[…]ts-operator](https://67946--docspreview.netlify.app/openshift-enterprise/latest/support/remote_health_monitoring/using-insights-operator#insights-operator-configuring_using-insights-operator)

**Pull request merged**
