### PR TITLE
GitHub-27639: Switching blue and green references

### LINKED ISSUE #27639: [enterprise-4.6] Issue in file applications/deployments/route-based-deployment-strategies.adoc
### Which section(s) is the issue in?
In the introduction section, it is mentioned that the in-production version is the **green** version and the newer version is the **blue** version

### What needs fixing?
The common terminology is that the blue is the in production version and the green is the newer version.
This can cause mixed up terminology with common ground.

Reference:
https://martinfowler.com/bliki/BlueGreenDeployment.html
https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html
Cloud Native Patterns - Cornelia Davies -  Chapter 7. The application lifecycle: Accounting for constant change (7.2.1)
Many more..

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #27639

Preview: https://deploy-preview-30211--osdocs.netlify.app/openshift-enterprise/latest/applications/deployments/route-based-deployment-strategies.html

### CODE REVIEW

**Review by codyhoag — APPROVED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@zhouying7780 I'm looking for someone to review this update, which is switching our blue-green deployment docs so that blue is the production version and green is the new version. I'm not sure if Workloads is the right team for this, but I couldn't find a better option. Can you please review this, or let me know if you have any suggestions for who might be appropriate, if not you? Thanks!

Preview: https://deploy-preview-30211--osdocs.netlify.app/openshift-enterprise/latest/applications/deployments/route-based-deployment-strategies.html

**Pull request merged**
