### PR TITLE
CNV#21920: RN - Move instancetype API from v1alpha2 to v1beta1

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/CNV-21920

Link to docs preview:
https://72052--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-infrastructure

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by RoniKishner** [comment]
Looks good. QE approved

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
