### PR TITLE
Bug 1331656 added maven proxy section

### PR DESCRIPTION
**Pull request by bfallonf**
As per https://bugzilla.redhat.com/show_bug.cgi?id=1331656

Will get QE to test procedure.

### CODE REVIEW

**Comment by bfallonf** [comment]
Given the go ahead by QA.

@adellape @ahardin-rh @tnguyen-rh @tpoitras Peer review please?

**Comment by bfallonf** [comment]
[revhistory]
|xref:../install_config/http_proxies.adoc#[Working With HTTP Proxies]
|Added xref:../install_config/http_proxies.adoc#using-maven-behind-a-proxy[Using Maven Behind a Proxy] section.
%

**Comment by ahardin-rh** [comment]
@bfallonf Looks great! :+1:

**Comment by bfallonf** [comment]
Thanks @ahardin-rh . I'll merge.

**Pull request merged**
