### PR TITLE
BZ1935550: Changed api to ui to reflect front-end application

### PR DESCRIPTION
**Pull request by opayne1**
Needs 4.5 label

https://bugzilla.redhat.com/show_bug.cgi?id=1935550

https://deploy-preview-34612--osdocs.netlify.app/openshift-enterprise/latest/pipelines/creating-applications-with-cicd-pipelines.html#running-a-pipeline_creating-applications-with-cicd-pipelines

### CODE REVIEW

**Comment by opayne1** [comment]
@wewang58 PTAL

**Review by stevsmit — COMMENTED** [review]
LGTM!

**Comment by opayne1** [comment]
end of life

**Pull request closed without merging**
