### PR TITLE
bug 1686775 - Typo in Example #1

### PR DESCRIPTION
**Pull request by bgaydosrh**
In Example 1. Horizontal Pod Autoscaler Object Definition, replaced 'apps/v1' with 'apps.openshift.io/v1' in the spec.scaleTargetRef.apiVersion field in BOTH VERSIONS of this example (the primary and alternate methods).

### CODE REVIEW

**Comment by bgaydosrh** [comment]
Link to BugZilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1686775

**Comment by vikram-redhat** [comment]
@bgaydosrh - is this ready for review? If yes, request QE review by setting the bug on ON_QA and/or tagging the QE associate here.

**Comment by bgaydosrh** [comment]
Hi Vikram,

Yes, I'll tag this for QE and peer review. I'll also add a note to not
merge for 4.0.

I saw your email last night and was a little unsure if I should request
review or hold off.

Thanks,

Bob

**Comment by bgaydosrh** [comment]
@openshift/team-documentation PTAL for peer review
@zhouying7780 for QE review.
Setting appropriate flags in BugZilla next.

**Comment by bgaydosrh** [comment]
This should be all set for peer and QE review now. Thanks for labeling the
release Vikram.

Bob

**Comment by mburke5678** [comment]
@bgaydosrh LGTM from a docs perspective.

**Comment by bgaydosrh** [comment]
Thanks Michael!

**Pull request closed without merging**
