### PR TITLE
BZ1945073: Replace DeploymentConfig with Deployment

### PR DESCRIPTION
**Pull request by skrthomas**
for 4.6+

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1945073

Preview: https://deploy-preview-35001--osdocs.netlify.app/openshift-enterprise/latest/applications/deployments/route-based-deployment-strategies?utm_source=github&utm_campaign=bot_dp

Ready for QA: @zhouying7780

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM

**Comment by bergerhoffer** [comment]
Merging since this has been acked by QE and already peer reviewed.

**Pull request merged**
