### PR TITLE
OCP 4.12 : Cloud Controller Manager Doc updates for P

### PR DESCRIPTION
**Pull request by alishaIBM**
Preview : https://52209--docspreview.netlify.app/openshift-enterprise/latest/operators/operator-reference.html#cluster-cloud-controller-manager-operator_cluster-operators-ref

Reviewers :
Manjunath Kumatagi

Branch : enterprise-4.12 and later

### CODE REVIEW

**Comment by mkumatag** [comment]
/cc @clnperez 

ptal at the suitable platform name here for the PowerVS provider

**Comment by clnperez** [comment]
this should be `IBM Cloud Power VS` vs just `IBM Power VS`. Discussed with the doc writers several months ago. The guidelines at this time are:

when discussing the account itself: IBM Cloud
when discussing the platform: IBM Cloud Power VS

**Comment by clnperez** [comment]
fyi @mjpytlak

**Comment by mjpytlak** [comment]
Thanks @clnperez. With regard to the account itself, https://github.com/openshift/openshift-docs/pull/50595 updated those references to IBM Cloud account.

**Comment by alishaIBM** [comment]
> this should be `IBM Cloud Power VS` vs just `IBM Power VS`. Discussed with the doc writers several months ago. The guidelines at this time are:
> 
> when discussing the account itself: IBM Cloud when discussing the platform: IBM Cloud Power VS

Thanks @clnperez 

I have updated the platform name.

**Review by clnperez — APPROVED** [review]

**Review by snarayan-redhat — COMMENTED** [review]
LGTM!

**Pull request merged**
