### PR TITLE
[SRVKS-1260] Correct field name in HTTP/1 sample

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVKS-1260

Link to docs preview:
https://79738--ocpdocs-pr.netlify.app/openshift-serverless/latest/knative-serving/http-configuration/http1-full-duplex-support.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by JoeAldinger — APPROVED** [review]
/lgtm

**Comment by jab-rh** [comment]
@ochromy, looks like this doesn't merge cleanly into the newer version? Wouldn't this be based on the main version of serverless?

@bergerhoffer, who looks at merge issues for Serverless docs?

Thanks!

**Comment by ochromy** [comment]
Hey @jab-rh , yes, this change was made on a branch from the `serverless-docs-main` version of the docs. 
I'm not aware of any underlying issues that could be causing this.

**Comment by jab-rh** [comment]
@ochromy, perhaps it needs a manual cherry-pick to that branch then? Thanks!

**Comment by bergerhoffer** [comment]
@jab-rh I'm not sure who could help with merge issues on other branches. I only pay attention to main/the enterprise branches.

**Comment by jab-rh** [comment]
@ShaunaDiaz, looks like this needs a manual cherry-pick.

**Comment by ShaunaDiaz** [comment]
@ochromy Are you able to do a manual cherry pick for this one and resolve any merge conflicts? Anything going into main should go into the upcoming version to keep the repo in sync as far as I know.

**Comment by ShaunaDiaz** [comment]
> @ShaunaDiaz, looks like this needs a manual cherry-pick.

OK. I am unfamiliar with the serverless docs, but can ask in our team channel.

**Comment by jab-rh** [comment]
@ShaunaDiaz, oh, sorry, not sure why I thought to tag you. Thank you!

**Comment by ShaunaDiaz** [comment]
Cherry pick is not needed; docs should sync as the 1.34 was replaced and looks to have incorporated this change. See https://redhat-internal.slack.com/archives/C85JYPHL3/p1724095831451639

**Pull request merged**
