### PR TITLE
BZ2045022: Remove requirement for 10GB nics on bare-metal IPI

### PR DESCRIPTION
**Pull request by cherraz**
Fixes:  https://bugzilla.redhat.com/show_bug.cgi?id=2045022

Preview:  https://deploy-preview-41490--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#node-requirements_ipi-install-prerequisites  (scroll to Network Interfaces)

Versions: 4.9, 4.10

### CODE REVIEW

**Comment by cherraz** [comment]
@hardys @racedo @cybertron  Hi, thank you for your thoughts the other day.  This is the 4.9/4.10  changes, can you please take a look and leave me a comment if all looks good? Thank you!

**Comment by hardys** [comment]
> @hardys @racedo @cybertron Hi, thank you for your thoughts the other day. This is the 4.9/4.10 changes, can you please take a look and leave me a comment if all looks good? Thank you!

lgtm, thanks!

**Comment by racedo** [comment]
Yes, lgtm too. Thanks @cherraz

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
