### PR TITLE
GitHub-27766: Updating example object class filter to person

### LINKED ISSUE #27766: [enterprise-4.6] Issue in file authentication/ldap-syncing.adoc
Since I have had several customers hitting this issue, I would like to submit this issue. It's not extremely important but it could help.

### Which section(s) is the issue in?
- About the Active Directory configuration file
- About the augmented Active Directory configuration file
- LDAP nested membership sync example

In the three sections above, the examples are about Active Directory and the filter is

(objectclass=inetorgperson)

In general, AD does not include this objectclass by default. Most of the customers are copying the example literally and changing few parameters. They fail to change the filter and they open a case.

I would suggest to replace:
(objectclass=inetorgperson)
by 
(objectclass=person)

even if it's an example, as customers are copying it literally, it could help to include an objectclass that is present in the ldap schema of active directory by default.

Apologies for the noise.

Thanks a lot,

German.

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #27766

Preview: https://deploy-preview-30796--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing.html

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@rhpmali Can you please review this update to make sure it is still correct with the objectclass filter change to 'person'? Thanks!

Preview: https://deploy-preview-30796--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing.html

**Comment by rhpmali** [comment]
I have changed objectclass filter to person and tested with few of test cases and it worked well. 
/lgtm

**Pull request merged**
