### PR TITLE
Update installation-vsphere-infrastructure.adoc

### PR DESCRIPTION
**Pull request by Rupesh-git-eng**
If this option is not set, the hypervisor does not inform guests OS about stealing the CPU.  This makes troubleshooting difficult in most situations.

Version(s):
All openshift versions

Link to docs preview:
https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/preparing-to-install-on-vsphere.html#installation-vsphere-infrastructure_preparing-to-install-on-vsphere

### CODE REVIEW

**Comment by mjpytlak** [comment]
Thank you for the contribution @Rupesh-git-eng.

@rvanderp3 In the context of helping to facilitate troubleshooting, any concerns about adding this to the doc? @jinyunma Is this something that we test with? Also wanted to verify with you ahead of a possible doc update.

**Review by mjpytlak — COMMENTED** [review]
Thank you for the contribution @Rupesh-git-eng.

@rvanderp3 In the context of helping to facilitate troubleshooting, any concerns about adding this to the doc? @jinyunma Is this something that we test with? Also wanted to verify with you ahead of a possible doc update.

**Comment by jinyunma** [comment]
> @rvanderp3 In the context of helping to facilitate troubleshooting, any concerns about adding this to the doc? @jinyunma Is this something that we test with? Also wanted to verify with you ahead of a possible doc update.

Set `stealclock.enable = "TRUE"` in Advanced Configuration Parameters,  steal time start to be collected.
```
[root@jima-08052-7wkpd-master-2 ~]# top

top - 07:43:11 up 30 min,  1 user,  load average: 0.56, 0.66, 0.81
Tasks: 311 total,   2 running, 309 sleeping,   0 stopped,   0 zombie
%Cpu(s):  7.3 us,  3.4 sy,  0.0 ni, 85.9 id,  0.1 wa,  0.8 hi,  1.0 si,  1.6 st
MiB Mem :  16019.3 total,   5897.3 free,   4058.2 used,   6063.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  11541.1 avail Mem
```
The setting can be done when creating vm for UPI installation. But for IPI installation, as nodes are provisioned by installer, it can only be configured manually after installation is completed, and also need to poweroff node firstly.

so the configuration should be performed during or after VM creating, it seems not suitable to add it in doc ["Preparing to install on vSphere"](https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/preparing-to-install-on-vsphere.html#installation-vsphere-infrastructure_preparing-to-install-on-vsphere).

**Comment by mjpytlak** [comment]
This setting struck me as vSphere setting that could be enabled prior to installation. Do I not understand this correctly?

**Comment by Rupesh-git-eng** [comment]
> This setting struck me as vSphere setting that could be enabled prior to installation. Do I not understand this correctly?

Yes, it can be enabled before the OCP installation or after the OCP installation. 
This PR intends here to let the OCP admin know that this option is helpful in OCP troubleshooting and therefore we need to have it enabled.

I chose this page because I couldn't find any better place to put that.

**Comment by mjpytlak** [comment]
> Yes, it can be enabled before the OCP installation or after the OCP installation.

@jinyunma Given that `stealclock.enable` can be enabled prior to installation, is there any reason why we wouldn't be able to simply let admins know that enabling prior to installation might help facilitate any troubleshooting issues and add this statement to "Preparing to install on vSphere"? In addition to it being enabled in the vSphere environment prior to installation, I am a bit confused by your earlier comment. Is there anything that users would have to do during installation if `stealclock.enable` is set prior to installation? I am trying to understand (1) what steps would be required during a UPI installation; (2) why this could only be configured manually after an IPI installation.

@Rupesh-git-eng can you point me to vSphere doc that specifies how to enable `stealclock.enable`. If we do add the guidance, I would like to be able to reference the official vSphere doc.

**Comment by Rupesh-git-eng** [comment]
I couldn't find any official doc on their app. Here is what we have as of now:

https://access.redhat.com/solutions/302283
https://lkml.org/lkml/2020/3/20/1030
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=e73a8f38f82d

**Comment by jinyunma** [comment]
>Given that stealclock.enable can be enabled prior to installation, is there any reason why we wouldn't be able to simply let admins know that enabling prior to installation might help facilitate any troubleshooting issues and add this statement to "Preparing to install on vSphere"?

@mjpytlak That's ok to keep current update if just let admin know this option and no need to provide the details of how to add this option in VM.

> I am trying to understand (1) what steps would be required during a UPI installation; (2) why this could only be configured manually after an IPI installation.

It can be configured through virtual machine -> Edit Settings -> VM Options -> Advanced -> Configuration Parameters. 
So for UPI, infrastructure are created by user, user can enable `stealclock.enable` during virtual machine creating at step 9.g in section [Installing RHCOS and starting the OpenShift Container Platform bootstrap process](https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere). Of cause, it can also be enabled after OCP installation.
For IPI, as infrastructure are created automatically by ocp installer, user could enable `stealclock.enable` after installation is finished.

**Comment by Rupesh-git-eng** [comment]
Attaching doc bz here...  https://bugzilla.redhat.com/show_bug.cgi?id=2117604

**Comment by Rupesh-git-eng** [comment]
Any update on this, please?

**Comment by jinyunma** [comment]
@mjpytlak FYI. steal clock has already been enabled on ipi-on-vsphere on 4.11+, and also support on 4.10 once PR in https://issues.redhat.com/browse/OCPBUGS-537 is merged.

**Comment by mjpytlak** [comment]
@Rupesh-git-eng when I saw you refresh this PR (thanks for the nudge) I pulled in https://bugzilla.redhat.com/show_bug.cgi?id=2117604. From the sounds of this @jinyunma, I would only need to update the doc with the recommendation to enable steal clock accounting in the 4.8 and 4.9 doc, correct?

**Comment by jinyunma** [comment]
> I would only need to update the doc with the recommendation to enable steal clock accounting in the 4.8 and 4.9 doc, correct?

I don't think so, as steal clock accounting is only enabled on ipi-on-vsphere automatically. For upi-on-vsphere, user still need to enable it if requiring.

**Comment by Rupesh-git-eng** [comment]
@mjpytlak yes we have to mention that in all UPI (vspare) docs for supported versions.

**Comment by mjpytlak** [comment]
Sorry. I should have clarified @jinyunma and @Rupesh-git-eng. We are currently managing doc for 4.8+. I will pull a PR for the UPI docs and update 4.8+ with a note about enabling steal clock accounting. I will pull a separate PR for IPI, as based on my understanding, it is/will be enabled by default on 4.10+. That leaves us with 4.8 and 4.9 for a similar note in the IPI doc.

**Comment by mjpytlak** [comment]
@Rupesh-git-eng Any objections to closing this PR in favor of the referenced doc PRs?

**Comment by Rupesh-git-eng** [comment]
> @Rupesh-git-eng Any objections to closing this PR in favor of the referenced doc PRs?

Yes it can with ref link attached to it.

**Comment by mjpytlak** [comment]
The IPI and UPI documentation is in flight. Closing this PR in favor of the referenced documentation PRs.

**Pull request closed without merging**
