### PR TITLE
OCPBUGS#23348 Adding VRRP to vSphere firewall docs

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-23348

Link to docs preview:
https://76962--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs#installation-vsphere-installer-network-requirements_ipi-vsphere-installation-reqs
This module was relocated from the "Installing on vSphere with network customizations" assembly to a dedicated "vSphere installation requirements" assembly in 4.15. However, the content is the same for 4.12+.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@zhaozhanqi PTAL at this doc update adding VRRP to vSphere installation requirements. Thank you

**Comment by zhaozhanqi** [comment]
LGTM

**Pull request merged**
