### PR TITLE
Disabling automerging of PRs by the openshift-cherrypick-robot

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@gaurav-nelson Please let me know which rhacs branches this should go into

**Comment by bergerhoffer** [comment]
Per slack, should go into:

rhacs-docs
rhacs-docs-3.65
rhacs-docs-3.66
rhacs-docs-3.67
rhacs-docs-3.68
rhacs-docs-3.69

**Comment by gaurav-nelson** [comment]
@bergerhoffer The edits in this PR looks okay, but building enterprise branch off the `rhacs-docs` branch doesn't makes sense to me. I'll update the Travis CI script to instead build the `rhacs-docs` distro.

**Pull request merged**
