### PR TITLE
Update repos orgazation to sclorg

### PR DESCRIPTION
**Pull request by liangxia**
@openshift/team-documentation Please take a look.

It should apply to all enterprise-3.x versions.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bmcelvee - PTAL.

**Comment by vikram-redhat** [comment]
@bmcelvee - were you able to look at this?

**Comment by liangxia** [comment]
A simple way to check the pr is valid.

Take the first change as example.
It changes https://github.com/openshift/mysql to https://github.com/sclorg/mysql-container.
You can verify by access the origin/first url, and you will find out that it redirects you to the changed/second one.

**Comment by bmcelvee** [comment]
Thanks, @liangxia! LGTM

**Comment by bmcelvee** [comment]
I can cherry-pick this PR back to 3.6 fairly easily, but with restructuring 3.1-3.5 will present some challenges.

**Comment by bmcelvee** [comment]
I've CP'd back to 3.6 (merged 3.7-3.11). Starting with 3.6 and older there are conflicts with the versions supported with OCP. Should we stop updating 3.6 and earlier or open separate PRs to update the links but not the versions?

**Comment by liangxia** [comment]
> I've CP'd back to 3.6 (merged 3.7-3.11). Starting with 3.6 and older there are conflicts with the versions supported with OCP. Should we stop updating 3.6 and earlier or open separate PRs to update the links but not the versions?

I'll open a separate pr to fix the 3.6 and earlier versions.

**Comment by vikram-redhat** [comment]
@liangxia - thanks. Just FYI - Changes to some of the files in the follow up PRs will have no effect as these are driven from the master branch. For example, _distro_map.yml and anything under templates. Could you please keep the changes only to what was suggested by this PR?

**Comment by liangxia** [comment]
@vikram-redhat  Updated the 3.1 one, does it look good to you ? If yes, I will apply the change to the other ones.

**Comment by vikram-redhat** [comment]
@liangxia - looks good! Thanks

**Comment by liangxia** [comment]
3.2 ~ 3.6 are update, too.

**Comment by bmcelvee** [comment]
Thank you so much, @liangxia!

**Pull request merged**
