### PR TITLE
Adjusting attributes for API formatting updates

### PR DESCRIPTION
**Pull request by bergerhoffer**
Following up on issue from https://github.com/openshift/openshift-docs/pull/28288/files#r547490914.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Not sure why there's not an auto preview, so here's a manual preview (internal): 

* http://file.rdu.redhat.com/~ahoffer/2020/api-formatting-followup/machine_management/applying-autoscaling.html
* http://file.rdu.redhat.com/~ahoffer/2020/api-formatting-followup/post_installation_configuration/cluster-tasks.html

**Comment by bergerhoffer** [comment]
FYI @vikram-redhat no auto preview on this PR - at least not yet (an hour after the PR was opened)

**Comment by jeana-redhat** [comment]
yay thanks :smiley:

**Comment by bergerhoffer** [comment]
Wait to merge this until all cherry picks for #28288 have been merged.

**Pull request merged**
