### PR TITLE
OCPBUGS#29456: Removed a restriction related to adding/removing a deviceClass in the LVMCluster CR

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.16

Issue:
[OCPBUGS-29456](https://issues.redhat.com/browse/OCPBUGS-29456)

Link to docs preview:
[Preview](https://72957--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms#about-lvmcluster_logical-volume-manager-storage)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@jakobmoellerdev 
Can you please review this PR?
Thanks.

**Review by jakobmoellerdev — APPROVED** [review]
/lgtm

**Comment by tmalove** [comment]
Hi @sr1kar99  Will you add a direct link to the preview? Thanks!

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
