### PR TITLE
RHDEVDOCS-6175: creating a separate release note folder and a tile for d.r.c for Pipelines 1.16

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `pipelines-docs-1.16`

Issue: [RHDEVDOCS-6175](https://issues.redhat.com/browse/RHDEVDOCS-6175)

Link to docs preview: https://82220--ocpdocs-pr.netlify.app/openshift-pipelines/latest/release_notes/op-release-notes-1-16

QE review:
- Not needed, structural changes only

Additional information:

### CODE REVIEW

**Comment by mramendi** [comment]
/label peer-review-done

LGTM except for one small nit

**Review by jeana-redhat — COMMENTED** [review]
LGTM, sorry for the delay!

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
