### PR TITLE
Change KnativeServing's API group to the new value.

### PR DESCRIPTION
**Pull request by markusthoemmes**
This is a result of https://issues.redhat.com/browse/SRVKS-267. Added additional comments to the relevant release notes in https://github.com/openshift/openshift-docs/pull/19232.

### CODE REVIEW

**Comment by mgencur** [comment]
QE Approved

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by mgencur** [comment]
Looks good from QE

**Comment by kalexand-rh** [comment]
@markusthoemmes, will you squash your commits so that we can merge whenever the time is right?

**Comment by markusthoemmes** [comment]
@kalexand-rh done!

**Pull request merged**
