### PR TITLE
Remove RHV installing-rhv-creating-custom-vm.adoc [branch/enterprise-4.4] [branch/enterprise-4.5]

### PR DESCRIPTION
**Pull request by rolfedh**
"the RHV team is rushing fixes for this issue [...]. @Alex Crawford can you help them make sure these fixes land for that [...] Z stream. Once those land the whole 'customizing the RHV template' should be dropped or removed from the docs. So please work with the team to make sure that happens in the next 1-2 weeks (after the product fixes land). "

### CODE REVIEW

**Comment by rolfedh** [comment]
This change is for 4.4.6 which goes live (GA) on June 1st.

**Comment by ahardin-rh** [comment]
Looks great!

**Comment by rolfedh** [comment]
Removed WIP. Please merge this early on Monday, June 1st.

**Review by peterclauterbach — APPROVED** [review]
LGTM

**Comment by rolfedh** [comment]
Please merge this PR early on June 8th.

**Pull request merged**
