### PR TITLE
Removing Kibana troubleshooting

### PR DESCRIPTION
**Pull request by mburke5678**
Per issue https://github.com/openshift/openshift-docs/issues/20956 and private slack: https://coreos.slack.com/archives/GGUR75P60/p1601477449205900

Removing topics as they don't seem useful any longer.

### CODE REVIEW

**Comment by mburke5678** [comment]
@jcantrill @sichvoge PTAL. Which versions should we remove the topic from?

**Comment by mburke5678** [comment]
@jcantrill @sichvoge PTAL. Which versions should we remove the topic from?

**Comment by sichvoge** [comment]
I will leave this up to @jcantrill.

**Review by jcantrill — APPROVED** [review]
/approve

**Comment by mburke5678** [comment]
@xltian @sferich888 @vikram-redhat PTAL

**Comment by vikram-redhat** [comment]
/lgtm

But need to consider if we redirect users to something new?

**Comment by xltian** [comment]
@juzhao  to review from QE.

**Comment by anpingli** [comment]
@mburke5678  Why we remove troubleshooting?

**Comment by mburke5678** [comment]
@anpingli I was asked by @jcantrill to remove the information. He told me in Slack that the topics "they don't seem useful any longer".

**Comment by anpingli** [comment]
@mburke5678  /lgtm

**Comment by sichvoge** [comment]
As troublehooting Kibana might be important specifically for CEE/OSD what are our recommendations now?

**Comment by mburke5678** [comment]
@sferich888 PTAL

**Review by anpingli — APPROVED** [review]

**Comment by mburke5678** [comment]
@sferich888 PTAL

**Comment by mburke5678** [comment]
@sferich888 PTAL

**Comment by mburke5678** [comment]
@reestr Please take a look. Per @jcantrill the Kibana troubleshooting topics don't seem useful any longer.

**Comment by mburke5678** [comment]
@reestr Please take a look. Per @jcantrill the Kibana troubleshooting topics don't seem useful any longer.

**Comment by sferich888** [comment]
/lgtm 
Sorry for the delays with this.

**Pull request merged**
