### PR TITLE
bug 1493556. State support of JSON file driver for logging

### PR DESCRIPTION
**Pull request by jcantrill**
Remove verbiage of only supporting journald.  I think there are probably some gross updates we may wish to make that is tangential from these changes.
cc @tkatarki

### CODE REVIEW

**Review by richm — APPROVED** [review]

**Comment by richm** [comment]
needs rebase

**Comment by jcantrill** [comment]
@bmcelvee  Can you please make sure this gets fixed in the documentation?

**Comment by bmcelvee** [comment]
@jcantrill certainly. I'll fold this into: https://github.com/openshift/openshift-docs/pull/7347.

**Comment by bmcelvee** [comment]
@jcantrill as noted in my previous comment I'm combining the changes in this PR with https://github.com/openshift/openshift-docs/pull/7347. I erred on the side of caution and removed the *Having Fluentd Use the Systemd Journal as the Log Source* entirely. Is that okay?

I'm going to go ahead and close this PR and continue tracking in https://github.com/openshift/openshift-docs/pull/7347.

**Pull request closed without merging**
