### PR TITLE
OSDOCS#12039: Adding note of future Kubernetes API removal

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.18

Issue:
https://issues.redhat.com/browse/OSDOCS-12039

Link to docs preview:
https://84972--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-18-release-notes.html#ocp-4-18-future-removals

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@wangke19 Can you please QE review?

https://84972--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-18-release-notes.html#ocp-4-18-future-removals

**Review by lahinson — COMMENTED** [review]
lgtm

**Pull request merged**
