### PR TITLE
Updating console route procedures with formatting changes from OAuth …

### PR DESCRIPTION
**Pull request by bergerhoffer**
…procedure

Pulling in some adjustments made in #34947 for customizing the OAuth URL, so that the procedures stay similar.

CC @ahardin-rh for initial review.

Preview: https://deploy-preview-35405--osdocs.netlify.app/openshift-enterprise/latest/web_console/customizing-the-web-console.html#customizing-the-web-console-url_customizing-web-console

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM! 

@jhadvig @spadgett PTAL Thank you!

**Review by spadgett — APPROVED** [review]
lgtm

**Comment by bergerhoffer** [comment]
@yanpzhan Can you please review these adjustments to this procedure? The initial content was added via #33161. I'm making slight adjustments based on a similar procedure for OAuth routes being added for 4.9 via #34947. Thanks!

Preview: https://deploy-preview-35405--osdocs.netlify.app/openshift-enterprise/latest/web_console/customizing-the-web-console.html#customizing-the-web-console-url_customizing-web-console

**Pull request merged**
