### PR TITLE
OSDOCS#12767: Removing unsupported versions of OSSO for 4.18 until ne…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…xt version releases

Version(s):
4.18

Issue:
https://issues.redhat.com/browse/OSDOCS-12767

Link to docs preview:

- https://85813--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/index.html
- https://85813--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-configuring.html
- https://85813--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html
- https://85813--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-uninstalling.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra @ingvagabund Can you PTAL at this, just removing the unsupported OSSO versions for 4.18 GA. And then we'll add the OSSO version that comes in shortly after GA. Preview links in description.

**Comment by ingvagabund** [comment]
LGTM

**Pull request merged**
