### PR TITLE
Fix CRC URLs, add an xref, rewording.

### PR DESCRIPTION
**Pull request by yhontyk**
Branch 4.5

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@boczkowska These changes look good to me! You'll just need to squash the commits down to one before we can merge. Also, I assume that this content will need to persist in 4.6, so I added a label to cherrypick this content there as well. Please let me know if there should be any exception. Thank you!

**Comment by boczkowska** [comment]
@ahardin-rh Thank you! Yes, it should go into 4.6, my bad. 
I've squashed the commits. :blush: It is now ready to be merged.

**Pull request merged**
