### PR TITLE
[enterprise-4.12] TELCODOCS-1886: Add recommended one time time-sycn for worked and control plane nodes

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.12

Issue: https://issues.redhat.com/browse/TELCODOCS-1886

Link to docs preview: https://76293--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.html#ztp-sno-du-configuring-time-sync_sno-configure-for-vdu

QE review:
- [x] QE has approved this change.

Additional information: Content is already in 4.14+, [preview](https://docs.openshift.com/container-platform/4.14/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.html#ztp-sno-du-configuring-time-sync_sno-configure-for-vdu)

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
