### PR TITLE
Bug 1381292 added note box to advanced install

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://bugzilla.redhat.com/show_bug.cgi?id=1381292

Will ask for ack in the BZ

### CODE REVIEW

**Review by e-minguez — COMMENTED** [review]
The thing is, the default docker0 network is the 172.17.0.1/16

**Comment by bfallonf** [comment]
Ack given in the BZ. @adellape @tpoitras @ahardin-rh peer review plz?

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing a Cluster -> Advanced Installation]
|Added more information to the `*openshift_master_portal_net*` parameter description in the xref:../install_config/install/advanced_install.html#configuring-cluster-variables[Configuring Cluster Variables] section.
%

**Pull request merged**
