### PR TITLE
[enterprise-4.16] update networking TP table

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.16

Issue: n/a

Link to docs preview: https://78323--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-technology-preview-tables_release-notes Networking table

QE review: @lihongan PTAL
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by lihongan** [comment]
LGTM
Thank you @jldohmann

**Comment by lihongan** [comment]
cc @melvinjoseph86

**Pull request merged**
