### PR TITLE
OSSM 1.1.10 release notes

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSMDOC-129

### CODE REVIEW

**Comment by gbaufake** [comment]
Hi @neal-timpe 

Can you assign me as one of the reviewers?

**Comment by neal-timpe** [comment]
@yxun Can you or Guilherme take a look? Thanks!

**Review by gbaufake — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Review by JStickler — APPROVED** [review]

**Pull request merged**
