### PR TITLE
BZ2070034 URL for provisioner VM and CoreOS images (4.9 version of BZ…

### PR DESCRIPTION
**Pull request by slovern**
Version(s): 4.9

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2070034

Link to docs preview: https://deploy-preview-45177--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-creating-an-rhcos-images-cache_ipi-install-installation-workflow

Additional information:
This is the 4.9 version of BZ https://bugzilla.redhat.com/show_bug.cgi?id=2063509
(PR for the corresponding 4.10, 4.11 changes: https://github.com/openshift/openshift-docs/pull/45148)

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM - please stand by for further review and merge.

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
