### PR TITLE
Added rev history file to Admin Solutions guide

### PR DESCRIPTION
**Pull request by tpoitras**
as per @vikram-redhat

### CODE REVIEW

**Comment by tpoitras** [comment]
@vikram-redhat is this all you needed me to do? Or is there something else that needs editing in order to make this revhistory show up in "all" ?

**Comment by tpoitras** [comment]
closing, wrong branch

**Comment by vikram-redhat** [comment]
When closing - make sure to remove labels and milestones.

**Comment by tpoitras** [comment]
@vikram-redhat I'll be sure to remember that for all my future PRs. :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
