### PR TITLE
edits as per suggestion on issue 2828

### PR DESCRIPTION
**Pull request by bfallonf**
As per #2828 

I don't think requires review, but @adellape @ahardin-rh @tpoitras Would anyone like to give me the thumbs up?

### CODE REVIEW

**Comment by tpoitras** [comment]
well, I haven't tested it or anything, but LGTM :rocket:

**Comment by ahardin-rh** [comment]
:+1:

**Comment by bfallonf** [comment]
Cool. Thanks. I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../admin_guide/high_availability.adoc#admin-guide-high-availability[High Availability]
|Fixed deprecated commands in the xref:../admin_guide/high_availability.adoc#configuring-a-highly-available-routing-service[Configuring a Highly-available Routing Service] section.
%

**Pull request merged**
