### PR TITLE
eventrouter namespace is not created automatically when deploying a cluster

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1623442

### CODE REVIEW

**Comment by mburke5678** [comment]
@jcantrill PTAL

**Review by jcantrill — APPROVED** [review]
lgtm

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by mburke5678** [comment]
@openshift/team-documentation Small change. PTAL

**Comment by bmcelvee** [comment]
LGTM :apple:

**Pull request merged**
