### PR TITLE
Add a link to AMD GPU device plugin

### PR DESCRIPTION
**Pull request by y2kenny**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@y2kenny can you give more details about this request?

**Comment by y2kenny** [comment]
This is just to add another example of device-plugin available to OpenShift.

**Comment by y2kenny** [comment]
Are there any issue with this commit?

**Comment by vikram-redhat** [comment]
@y2kenny is this supported by Red Hat? @sferich888?

**Comment by sferich888** [comment]
No it's not (supported by Red Hat - the plug-in that is, Red Hat doesn't have a supported plug-in). With that said I Red Hat supports the capability of using such a plug-in.

This link is like line 51 and is an example of plug-in a user could use.

**Pull request closed without merging**
