### PR TITLE
Update step for deploying an odo single application

### PR DESCRIPTION
**Pull request by cdrage**
Missing important step to change to the Node.JS directory before running
the next command...

Ping @boczkowska @bergerhoffer

### CODE REVIEW

**Review by bergerhoffer — APPROVED** [review]
This LGTM.

@boczkowska - Can you also review and if it looks good to you, then I'll go ahead and merge.

Thanks @cdrage!

**Comment by boczkowska** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
Thanks @boczkowska! Merging now.

**Pull request merged**
