### PR TITLE
RHDEVDOCS-4491:- Release note for Doc: Support default resource type in User Preferences

### PR DESCRIPTION
**Pull request by smunje1**
Purpose: To resolve https://issues.redhat.com/browse/RHDEVDOCS-4491
Version(s): enterprise-4.12 only

Link to docs preview: https://drive.google.com/file/d/1anyubi_m0EaPOFgxsLub_0RMB5Wle3hK/view?usp=sharing

SME review needed: @vikram-raj 
QE review needed: @sanketpathak 
Peer review needed:

### CODE REVIEW

**Comment by smunje1** [comment]
Hello @vikram-raj 
Could you help with the SME review for this PR?

Thank you!

**Review by vikram-raj — APPROVED** [review]
Thanks @smunje1. LGTM.

**Comment by smunje1** [comment]
Hello @sanketpathak 
Could you help with the QE review for this PR?

Thank you!

**Comment by sanketpathak** [comment]
LGTM

**Comment by smunje1** [comment]
After rebase:
https://drive.google.com/file/d/1e9EIYn9HSsl4Z10kWGAf_YBhdNfz8oJt/view?usp=sharing
Screenshot:
image

Cc @vikram-raj @sanketpathak

**Review by gabriel-rh — APPROVED** [review]
/lgtm

Looks good!

**Pull request merged**
