### PR TITLE
CNV#33978: adding OCP Virt support to ROSA RNs

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.14+

Issue: related to [CNV-33978](https://issues.redhat.com//browse/CNV-33978)

Link to docs preview: https://67657--docspreview.netlify.app/openshift-rosa/latest/rosa_release_notes/rosa-release-notes#rosa-q4-2023_rosa-whats-new

QE review:
- [x] QE has approved this change.

Additional information: Also adding the `:VirtProductName: OpenShift Virtualization` attribute to the `_attributes/attributes-openshift-dedicated.adoc` file.

### CODE REVIEW

**Comment by laujohns89** [comment]
LGTM!

**Comment by ousleyp** [comment]
@dbasunag or @orenc1 - can you please review this PR? It adds a release note to the ROSA docs re: CNV support. Thanks!

**Review by dbasunag — APPROVED** [review]

**Pull request merged**
