### PR TITLE
RHDEVDOCS-3963 Create long and short attributes for the Builds product

### PR DESCRIPTION
**Pull request by rolfedh**
Aligned team: Dev Tools
- For branches: 4.11+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3963
- Direct link to doc preview: NA
- SME review: @adambkaplan 
- QE review: @jitendar-singh 
- Peer review: tbd
- <All reviews complete. Please merge now>

### CODE REVIEW

**Comment by rolfedh** [comment]
@adambkaplan @jitendar-singh  We use these attributes to standardize references to the product in our downstream and upstream documentation. Do you think the proposed equivalents, Shipwright Builds and Shipwright, for the openshift-origin (OKD) docs are correct?

**Comment by coreydaley** [comment]
fwiw I think that they look good.

**Review by rgormley — APPROVED** [review]
LGTM. Provides clarity for the sake of documentation.

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Review by rgormley — APPROVED** [review]
LGTM

**Comment by bburt-rh** [comment]
lgtm

**Pull request merged**
