### PR TITLE
BZ-1992431: Adding note about self-signed certs

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1992431

Preview: https://deploy-preview-36936--osdocs.netlify.app/openshift-enterprise/latest/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@yaoli-redhat Can you please review this and let me know if this is what you were looking for to address your comment here: https://bugzilla.redhat.com/show_bug.cgi?id=1992431#c3

Preview: https://deploy-preview-36936--osdocs.netlify.app/openshift-enterprise/latest/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth

**Comment by yaoli-redhat** [comment]
lgtm

**Comment by bergerhoffer** [comment]
@slaskawi Can you please take a look at this as well and let me know if you're okay with the wording being added here? Thanks!

Preview: https://deploy-preview-36936--osdocs.netlify.app/openshift-enterprise/latest/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth

**Review by slaskawi — APPROVED** [review]
/lgtm

**Pull request merged**
