### PR TITLE
TELCODOCS-1187: Release note for host networking setting for SR-IOV VFs

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1187](https://issues.redhat.com//browse/TELCODOCS-1187): Adding technology preview release note for #63405 

Version(s):
4.15

Issue:
https://issues.redhat.com/browse/TELCODOCS-1187

Link to docs preview:
https://72740--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-networking-nncp-host-network-settings

QE review:
- [x] QE has approved this change.

Additional information:
This has been through the change management process and received all necessary ACKs.

### CODE REVIEW

**Comment by dfitzmau** [comment]
/remove-label peer-review-in-progress

/label peer-review-done

LGTM!

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Pull request merged**
