### PR TITLE
CNV-49363: Release note: (two notes) New focused view and guided tour in OpenShift Virtualization

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.17+

Issue: [CNV-49363](https://issues.redhat.com/browse/CNV-49363)

Link to docs preview: [4.17 Release notes/New and changed features/Web console](https://82875--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html#virt-4-17-web) 

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
Hi @ronensdeor, I've created a couple of 4.17 release notes, thinking we should tell our customers about the new focused view and the guided tour. Can you please review them? Thanks!

**Comment by aspauldi** [comment]
Adding @gouyang to this PR review request. Thanks.

**Review by adellape — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
