### PR TITLE
[GH#49074] Fix supported platforms table error 

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.11

Issue: #49074

Link to docs preview:

- origin: http://file.rdu.redhat.com/~mbridges/table-fix/origin/installing/installing-preparing.html#supported-installation-methods-for-different-platforms
- enterprise: http://file.rdu.redhat.com/~mbridges/table-fix/enterprise/installing/installing-preparing.html#supported-installation-methods-for-different-platforms

Additional information: This PR (hopefully) corrects table errors introduced by a previous commit--possibly some messy conflict resolution, too. RHOSP SR-IOV is no longer an installation assembly: the procedure is delegated to various post-installation configuration topics.

### CODE REVIEW

**Comment by maxwelldb** [comment]
@tshwartz This PR seeks to make the number of heading items equal to the number of items per row.

**Review by adellape — APPROVED** [review]
👍

**Comment by bergerhoffer** [comment]
@maxwelldb Since this went into main, it should go into 4.12 as well. Can you please label and cherry pick this to 4.12 as well?

**Pull request merged**
