### PR TITLE
Fix callouts in pod_security_context.adoc

### PR DESCRIPTION
**Pull request by grdryn**
It looks like the numbering got out of sync.

### CODE REVIEW

**Comment by grdryn** [comment]
It was [on the OSE docs](https://docs.openshift.com/enterprise/3.2/install_config/persistent_storage/pod_security_context.html) that I noticed this, so I guess it should be cherry-picked to other branches

**Comment by ahardin-rh** [comment]
@grdryn Thanks! Can you please squash your commits?

**Comment by grdryn** [comment]
@ahardin-rh done! :)

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/persistent_storage/pod_security_context.adoc#install-config-persistent-storage-pod-security-context[Configuring Persistent Storage -> Volume Security]
|Fixed formatting of the `oc get project default -o yaml` example output within the xref:../install_config/persistent_storage/pod_security_context.adoc#sccs-defaults-allowed-ranges[SCCs, Defaults, and Allowed Ranges] section. 

%

**Pull request merged**
