### PR TITLE
Bug 1533508, Added an Update DNS for Custom Routes section for Online docs

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1533508

@wgordon17 PTAL

The Online docs will be updated to 3.7 in Q4 once the Pro upgrade happens. At that time, the other screenshot on the page will be updated.

### CODE REVIEW

**Comment by wgordon17** [comment]
@ahardin-rh I would include the paragraph above that in this section as well

> Once your custom route is created in in {product-title} Pro, you must update
 your DNS provider by creating a canonical name (CNAME) record. Your CNAME record
 should point your custom domain to the {product-title} router as the alias. The
 {product-title} router's domain is different for every cluster.

**Comment by ahardin-rh** [comment]
@wgordon17 Thanks! Updated.

**Comment by ahardin-rh** [comment]
@openshift/team-documentation Please peer review

**Comment by wgordon17** [comment]
@ahardin-rh And probably then *remove* that section from above...so it's not duplicated ;)

**Comment by ahardin-rh** [comment]
@wgordon17 Good catch. Updated.

**Comment by mburke5678** [comment]
@ahardin-rh LGTM

**Comment by ahardin-rh** [comment]
QE verified. Since this is only rendering in Online docs, no revision history is necessary.

**Comment by vikram-redhat** [comment]
@ahardin-rh - to confirm, you will still merge this into the stage branches, right?

**Comment by ahardin-rh** [comment]
@vikram-redhat Sorry for the delay while I was on PTO. The cherry-picks to stage are now complete.

**Pull request merged**
