### PR TITLE
OCPBUGS-29242: Removed the in-tree driver reference from vSphere inst…

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.14, 4.15. and 4.16

Issue:
[OCPBUGS-29242](https://issues.redhat.com/browse/OCPBUGS-29242)

Link to docs preview:
* [VMware vSphere infrastructure requirements](https://71448--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs)
* [VMware vSphere infrastructure requirements](https://71448--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/upi-vsphere-installation-reqs)

SME review: 
- [X] SME has approved this change.
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jcpowermac** [comment]
/lgtm

@gnufied you may want to take a look

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by duanwei33** [comment]
LGTM

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
