### PR TITLE
[OSDOCS-8096]: Update minimum SCP policy documentation

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8096
Link to docs preview:

https://69598--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources#rosa-minimum-scp_rosa-sts-about-iam-resources
QE review:
- [ ] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 / @yuwang-RH, could I please get a QE review on this PR when you get a chance? Thanks!

**Review by adellape — APPROVED** [review]

**Review by jldohmann — APPROVED** [review]
Nice work 😄 lgtm

**Comment by mletalie** [comment]
> Nice work 😄 lgtm

Thanks!

**Pull request merged**
