### PR TITLE
Change CDN 03 to 06

### PR DESCRIPTION
**Pull request by sveno1990**
Fix type-o in documentation

Version(s):
4.16

Issue:
N/A

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @sveno1990 . Thanks for the PR. Our Prow builds are a bit slow today, but hopefully they will come back to normalcy by Monday. 

I'm assuming `cdn0**[1-6]**.quay.io` references versions or iterations of an image? Just want to avoid this issue for future OCP releases, if possible.

**Comment by stevsmit** [comment]
LGTM. This is correct. Quay QE will also ack this.

**Pull request merged**
