### PR TITLE
OCPBUGS-6886-12: Fix typo in Ironic provisioning service update release note

### PR DESCRIPTION
**Pull request by dfitzmau**
PR raised to update the 4.12 release note, because of a change to the [4.10 PR](https://github.com/openshift/openshift-docs/pull/55415). Good practice would entail keeping the notes consistent across release. 

Version(s):
4.12 and 4.11

Issue:
[OCPBUGS-6886](https://issues.redhat.com/browse/OCPBUGS-6886)

Link to docs preview: [Bare Metal Hardware Provisioning: last listed bug](https://55458--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-bug-fixes)

Useful link: Note originally published in the [4.12 release notes](https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-bug-fixes).

QE review:
- [ ] QE has approved this change.

QE not required for this backporting release note update.

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @mburke5678 . Thanks for reviewing https://github.com/openshift/openshift-docs/pull/55415 . I created OCPBUGS-6886-12 to fix a typo. This update ensures that PR 6886-12 aligns with the change in PR 6886. 

I would need the 4.12 update cherry-picked to 4.11. Can you do this or do I need to create a PR for the 4.11 update?

**Comment by mburke5678** [comment]
@dfitzmau I did a manual CP into 4.11. PTAL: https://github.com/openshift/openshift-docs/pull/55473

**Pull request merged**
