### PR TITLE
Issue 10876 Fix ramp node config file setting

### PR DESCRIPTION
**Pull request by bfallonf**
For #10876 

@lihongan Can I please ask about the Note I've added? I think it would be better to explain how the settings can become persistent rather than saying it is not something the configuration shows. Do you have that information?

### CODE REVIEW

**Comment by lihongan** [comment]
@bfallonf unfortunately I don't have a solution to make those settings persistent and I think it is meaningless to find one.
 
As I have said that it just take F5 router as example to describe how to create IPIP tunnul on ramp node, and F5 native vxlan intergration is recommended for F5 BIG-IP version 12.x and above, so I can't see other user cases which need the ramp node. From OCP 3.11 even the F5 router also will be deprecated, so maybe we can delete all part of ramp node from the Doc. @rajatchopra what do you think ?

**Comment by bfallonf** [comment]
OK. Thanks @lihongan . It does look like those efforts are being tracked in trello, so we can leave that conversation for there. I'll move forward with this PR.

@openshift/team-documentation PTAL

**Review by kalexand-rh — COMMENTED** [review]
Couple of questions and suggestions. overall, LGTM

**Comment by bfallonf** [comment]
Thanks, all. I'll merge.

**Pull request merged**
