### PR TITLE
OSSMDOC-327: Architecture review

### PR DESCRIPTION
**Pull request by neal-timpe**
- Aligned team: Service mesh
- For branches: 4.6, 4.7, 4.8
- https://issues.redhat.com/browse/OSSMDOC-327
- Two style updates.
- https://deploy-preview-33782--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-architecture.html
- SME review: brian-avery
- QE review: yxun
- Peer review

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by yxun — APPROVED** [review]

**Review by mikemckiernan — APPROVED** [review]
Wow, data plural and datum singular makes it into tech docs.

Looks good.

**Pull request merged**
