### PR TITLE
update weight default in route to service

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**What**
Update route default to 100.

Based on my investigations the default value for the Route -> spec -> to -> weight is 100 when unspecified.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Related API change: https://github.com/openshift/api/pull/310

**Comment by vikram-redhat** [comment]
@laurafitzgerald - can you confirm if this change is in 4.1 or 3.11 (and below)?

**Comment by laurafitzgerald** [comment]
@vikram-redhat I saw this on 3.11, I haven't checked it on 4.x

**Comment by vikram-redhat** [comment]
@laurafitzgerald ok - let us know when the related PR is merged and we can merge this.

**Comment by laurafitzgerald** [comment]
@vikram-redhat The related pr is now merged.

**Comment by laurafitzgerald** [comment]
ping @vikram-redhat

**Pull request merged**
