### PR TITLE
Follow-up edits for PR #2199

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Follow-up edits for PR #2199

@ahardin-rh @adellape @bfallonf @tpoitras 
Peer review please?

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@tnguyen-rh LGTM :star2:

**Comment by bfallonf** [comment]
@tnguyen-rh LGTM!

**Comment by adellape** [comment]
@tnguyen-rh Needs a reb0rse.

**Comment by tnguyen-rh** [comment]
Added label `tech_review` for tie-in w/ [BZ 135946](https://bugzilla.redhat.com/show_bug.cgi?id=1355946).

**Comment by tnguyen-rh** [comment]
@jkaurredhat PTAL (but see [navigation tips](https://bugzilla.redhat.com/show_bug.cgi?id=1355946#c2) first)

**Comment by tnguyen-rh** [comment]
[rev_history]
xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
Improved explanation of _traditional_ vs _overlapped_ xref:../architecture/core_concepts/routes.adoc#router-sharding[router sharding], including an example of namespace-based sharding.
%
xref:../install_config/install/deploy_router.adoc#install-config-install-deploy-router[Installing -> Deploying a Router]
Clarified the need for the xref:../install_config/install/deploy_router.adoc#creating-the-router-service-account[`cluster-reader`] permission and added the xref:../install_config/install/deploy_router.adoc#using-namespace-router-shards[Using Namespace Router Shards] section.
%

**Comment by tnguyen-rh** [comment]
@ahardin-rh @bfallonf @adellape @jkaurredhat Thanks for the reviews.

**Pull request merged**
