### PR TITLE
OSDOCS-5423: add admonition kubelet configs affecting dependent pools

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OSDOCS-5423

Link to docs preview: https://68505--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/machine-configuration-tasks#create-a-kubeletconfig-crd-to-edit-kubelet-parameters_post-install-machine-configuration-tasks

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@sergiordlr could you PTAL at this docs PR for QE ack? It adds an important note about kubelet configs affecting infra nodes. Thank you!

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by sergiordlr** [comment]
@jldohmann

LGTM

**Pull request merged**
