### PR TITLE
BZ#1692701 Run openshift_node_group playbook before scaleup

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1692701

### CODE REVIEW

**Comment by codyhoag** [comment]
Preview: http://file.rdu.redhat.com/~choag/040120/scale-up-playbook-3-11/install_config/adding_hosts_to_existing_cluster.html

**Comment by codyhoag** [comment]
@gpei PTAL?

**Comment by gpei** [comment]
yes, the changes lgtm, thanks.

**Comment by bmcelvee** [comment]
Just one observation - there's some mixed punctuation before code blocks and examples (e.g., `.` and `:`). It looks like that was the case before this PR. Otherwise, LGTM!

**Comment by codyhoag** [comment]
Thanks, @bmcelvee! I'll make a second pass through the doc and clean up those inconsistencies.

**Pull request merged**
