### PR TITLE
[virt] known issue for BZ 1855182: cloning stalls out

### PR DESCRIPTION
**Pull request by ousleyp**
- https://bugzilla.redhat.com/show_bug.cgi?id=1855182
- [Preview build](https://deploy-preview-29662--osdocs.netlify.app/openshift-enterprise/latest/virt/virt-2-6-release-notes.html#virt-2-6-known-issues)
- Needs QE approval, code and peer review done

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by duyanyan** [comment]
LGTM

**Review by aburdenthehand — APPROVED** [review]
RN exception

**Pull request merged**
