### PR TITLE
WIP: Cnv migration

### PR DESCRIPTION
**Pull request by apinnick**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@ousleyp PTAL.

**Comment by ousleyp** [comment]
Hi @apinnick - I'm happy to help with a review soon. First, can you please clarify something? It looks like the files here are all still CNV 1.4-style modules, but for docs published in the OCP 4.1 collection, they need to be made into assemblies (one assembly per user story). The modules that the assemblies include also need to be updated to reflect the modular docs standards (anchor ID, header level). Are you planning to do the modularization part of this work in this PR, a different PR, or am I missing something?

In case you need them, the OCP 4.1 guidelines can be found here: https://github.com/openshift/openshift-docs/blob/enterprise-4.1/contributing_to_docs/doc_guidelines.adoc

Thanks!

**Comment by apinnick** [comment]
Good point! When I created the module, the CNV guide hadn't yet been moved over, so there was no convenient framework. I'll create an assembly.

**Comment by apinnick** [comment]
On second thought, I think the assembly should be created by OpenShift writers, so let's not review it until more of the CNV users guide has been moved over.

**Pull request closed without merging**
