### PR TITLE
OCPBUGS#42399: Update `oc get` and `describe clustercatalog` commands

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Addresses https://github.com/openshift/openshift-docs/pull/82415#issuecomment-2372802076
Version(s): 4.17

Issue :[OCPBUGS-42399](https://issues.redhat.com/browse/OCPBUGS-42399)

Link to docs preview:
* Verification step: https://82507--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/managing-catalogs.html#olmv1-adding-a-catalog-to-a-cluster_managing-catalogs
* Procedure and verification steps: https://82507--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/managing-catalogs.html#olmv1-deleting-catalog_managing-catalogs

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@KeenonLee PTAL

**Comment by DCChadwick** [comment]
Whoops! Looks like I don't know how to add an LGTM label. Regardless, it looks good to me! :)

**Review by KeenonLee — COMMENTED** [review]
/label qe-approved

**Pull request merged**
