### PR TITLE
Update node creation image

### PR DESCRIPTION
**Pull request by codyhoag**
New image: https://deploy-preview-35922--osdocs.netlify.app/openshift-enterprise/latest/architecture/architecture-installation.html#installation-process_architecture-installation

Old image: https://docs.openshift.com/container-platform/4.8/architecture/architecture-installation.html#installation-process_architecture-installation

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you verify the updated node creation image for our installation docs? Thanks!

https://github.com/openshift/openshift-docs/blob/87bfe4e9f171ce6dfa1f9dd5bcb0129266148643/images/create-nodes.png

**Comment by gpei** [comment]
@codyhoag hi, I compared the new image with the current one in https://docs.openshift.com/container-platform/4.8/architecture/architecture-installation.html#installation-process_architecture-installation

Seems we only changed the direction of the arrows and name of master/worker
Master Node -> Control Node
Worker Node -> Compute Node
Is that right?

**Comment by gpei** [comment]
@codyhoag hi, I compared the new image with the current one in https://docs.openshift.com/container-platform/4.8/architecture/architecture-installation.html#installation-process_architecture-installation

Seems we only changed the direction of the arrows and name of master/worker
Master Node -> Control Node
Worker Node -> Compute Node
Is that right?

**Comment by codyhoag** [comment]
@gpei yes, that's correct. Just a directional redesign and slight vocab updates.

**Comment by gpei** [comment]
Thanks for the confirmation, lgtm.

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

**Pull request merged**
