### PR TITLE
BZ1939774 duplicate permission records in configuring an AWS account document

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.9+

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1939774

Link to docs preview:
https://53684--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-permissions-iam-roles_installing-aws-account

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by cbippley** [comment]
@yunjiang29 Please take a look, thank you!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
