### PR TITLE
[enterprise-4.16+]: Fix typo in Kubernetes node ports range in network flow matrix

### PR DESCRIPTION
**Pull request by sabinaaledort**
Fix incorrect range.

https://docs.openshift.com/container-platform/4.16/networking/configuring-node-port-service-range.html

### CODE REVIEW

**Comment by jab-rh** [comment]
@anuragthehatter, can you confirm? Thanks!

**Review by rohennes — APPROVED** [review]

**Comment by rohennes** [comment]
This was a typo on my part. As Sabina linked, we saw `30000` elsewhere in the docs. And it says the same in the Kubernetes docs: https://kubernetes.io/docs/reference/networking/ports-and-protocols/#node

So missed a zero!

**Comment by ShaunaDiaz** [comment]
@rohennes This will need QE. Note that @jab-rh has not labeled as `peer-review-done` as he held the PR for QE.

**Pull request merged**
