### PR TITLE
TELCODOCS-475: Update channel to read stable for 4.9 and 4.10

### PR DESCRIPTION
**Pull request by kquinn1204**
Addresses: https://issues.redhat.com/browse/TELCODOCS-475
This change needs to be made in 4.10 and 4.9. 
The original dev JIRA ticket is https://issues.redhat.com/browse/ART-3107 

**SRO Section**: https://deploy-preview-41437--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html

**NFD Section**: https://deploy-preview-41437--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html

### CODE REVIEW

**Review by bthurber — COMMENTED** [review]
/lgtm

@dagrayvid please review for the Perf Addon Operator

**Review by bthurber — APPROVED** [review]
/lgtm

**Review by ctauchen — COMMENTED** [review]
LGTM, pending QE review.

**Comment by kquinn1204** [comment]
Hi @wabouhamad I need a QE to sign off on this, @bthurber have given his OK.

**Pull request merged**
