### PR TITLE
Nodes fix Creating and using secrets command

### PR DESCRIPTION
**Pull request by mburke5678**
Fix command per: https://issues.redhat.com/browse/OSDOCS-3989?focusedId=22871991&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22871991

### CODE REVIEW

**Comment by mburke5678** [comment]
@yingzhanredhat PTAL

**Comment by mburke5678** [comment]
Ying Zhang [lgtm in Jira](https://issues.redhat.com/browse/OSDOCS-3989?focusedId=23232312&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23232312).

**Review by skrthomas — APPROVED** [review]
/lgtm

**Pull request merged**
