### PR TITLE
Description repeats itself 

### PR DESCRIPTION
**Pull request by kobi86**
Paragraph has a line  that repeats it self twice that make it a duplicate line with a reference to Topic that refer to himself

### CODE REVIEW

**Comment by jboxman** [comment]
@kobi86, the goal was to explain that _subnet_ mode is essentially identical to _network policy_ mode with zero policies created.

**Comment by kobi86** [comment]
If this is the case then the sentence should be :

Source of : 
The network policy mode provides
the same functionality as the subnet mode.

Target: 
The subnet mode provides
the same functionality as the network policy.

**Pull request closed without merging**
