### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by sfortner-RH**
Fix Typo per [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1845236).

No QE required. CP to 4.3, 4.4 and 4.5.

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM (same build failure issue, unrelated to this PR)

**Comment by bmcelvee** [comment]
The build issue is fixed. Please rebase whenever you get a chance, then I'll go ahead with the merge. :)

**Comment by sfortner-RH** [comment]
@bmcelvee I have rebased :) Please merge.

**Pull request merged**
