### PR TITLE
BZ-1880925: Adding step to navigate to /home/core

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1880925

Preview: https://bz-1880925--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/backing-up-etcd.html#backing-up-etcd-data_backup-etcd

### CODE REVIEW

**Comment by retroflexer** [comment]
LGTM. Thanks Andrea for taking care of it quickly.

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review?

Preview: https://bz-1880925--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/backing-up-etcd.html#backing-up-etcd-data_backup-etcd

**Review by sheriff-rh — APPROVED** [review]
LGTM! Thanks!

**Comment by geliu2016** [comment]
LGTM,thanks

**Pull request merged**
