### PR TITLE
CNV-32741: Update version attributes for 4.17

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.17+

Issue: [CNV-32741](https://issues.redhat.com//browse/CNV-32741)

Link to docs preview:

- https://82032--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/about_virt/about-virt
- https://82032--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/install/installing-virt#virt-deploying-operator-cli_installing-virt

QE review: N/A
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by max-cx** [comment]
@sjhala-ccs, LGTM.

I'm in training for the peer review squad, so I will ask @dfitzmau to check this PR as a peer reviewer after me.

**Comment by dfitzmau** [comment]
Thanks, @max-cx . LGTM. Please add the peer-review-done label.

**Pull request merged**
