### PR TITLE
OSDOCS-9316#Correct Azure Disk in-tree migration info

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-9316

Link to docs preview: https://70246--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-azure

QE review:
- [ ] QE has approved this change.

Additional information:

**PTAL**: @gcharto @bertinatto

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
Hey Lisa, 
I reviewed the other two PRs so far with this exact update, and I'd say the same comments apply here too.

**Comment by kalexand-rh** [comment]
4.11 is now [EOL](https://access.redhat.com/support/policy/updates/openshift), and we are no longer updating it. Please set the versions to 4.12+.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Review by bertinatto — COMMENTED** [review]
LGTM, but shouldn't this PR target 4.11 branch?

**Comment by gcharot** [comment]
LGTM applies to 4.11+ but given 4.11 is EoL, we just need to update 4.12+

**Pull request merged**
