### PR TITLE
OCPBUGS#32777: Update OperatorConditions to `v2`

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.13+

Issue: [OCPBUGS-32777](https://issues.redhat.com/browse/OCPBUGS-32777)

Link to docs preview: https://79717--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/admin/olm-managing-operatorconditions.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
I think the fixed version should be 4.13+ since OCP 4.13 has the same issue, see https://docs.openshift.com/container-platform/4.13/operators/admin/olm-managing-operatorconditions.html
```console
jiazha-mac:~ jiazha$ oc get clusterversion
NAME      VERSION                                    AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.nightly-arm64-2024-07-30-122747   True        False         7h21m   Error while reconciling 4.13.0-0.nightly-arm64-2024-07-30-122747: an unknown error has occurred: MultipleErrors
jiazha-mac:~ jiazha$ oc get operatorcondition -n openshift-operator-lifecycle-manager -o yaml
apiVersion: v1
items:
- apiVersion: operators.coreos.com/v2
  kind: OperatorCondition
  metadata:
    creationTimestamp: "2024-07-30T18:12:39Z"
    generation: 1
    name: packageserver
    namespace: openshift-operator-lifecycle-manager
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: true
      kind: ClusterServiceVersion
      name: packageserver
      uid: 16d46c1c-0885-4242-b0d6-294635893c17
    resourceVersion: "9004"
    uid: 53f2d8bf-dcb1-4377-9691-1b148424d44a
  spec:
    deployments:
    - packageserver
    serviceAccounts:
    - olm-operator-serviceaccount
kind: List
metadata:
  resourceVersion: ""
```

**Review by m1kola — APPROVED** [review]
/lgtm

**Comment by michaelryanpeter** [comment]
> I think the fixed version should be 4.13+ since OCP 4.13 has the same issue, see https://docs.openshift.com/container-platform/4.13/operators/admin/olm-managing-operatorconditions.html

@jianzhangbjz Thank you! I will make sure this change is cherry picked to 4.13+

**Comment by dfitzmau** [comment]
Hi @michaelryanpeter . Maybe this change is very targeted, but I see instances of `apiVersion: operators.coreos.com/v1` in other Administrator docs. I assume this is intended? [Example](https://79717--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/admin/olm-config). 

/remove-label peer-review-in-progress

/label peer-review-done

**Comment by michaelryanpeter** [comment]
It is highly targeted, @dfitzmau. That API and URL is used to version a lot of APIs in OLM. This is specifically updating to `v2` for the `OperatorConditions` resourse. Good looking out, though!

**Pull request merged**
