### PR TITLE
TELCODOCS-2112: Update IBU doc prechaching partition label

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.16, 4.17, 4.18

Issue: https://issues.redhat.com/browse/TELCODOCS-2112

Link to docs preview:

- https://85235--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-shared-container-partition.html
- https://85235--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image_base_install/ibi-preparing-for-image-based-install.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Review by achuzhoy — APPROVED** [review]

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
