### PR TITLE
BZ1894007: CNV remove import provider secrets

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1894007

CP to 4.5, 4.6, 4.7. 
If there is a problem with 4.5 CP, I'll create a separate PR.

### CODE REVIEW

**Comment by ousleyp** [comment]
LGTM!

**Comment by apinnick** [comment]
@ousleyp 
Looks like the 4.5 CP didn't work. I will create a separate PR and ping you.

**Pull request merged**
