### PR TITLE
Updated step 8 EUS output -> 4.y+2.z

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.11+

Issue:
n/a

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
