### PR TITLE
OSDOCS-8012: fix attribute for microshift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8012

Link to docs preview:
NOTE: Most books have changes; install with rpms, backup and restore, and release notes are covered in other PRs.

I am including links for posterity, but in reality, the key peer review issue is to BOLO for unresolved attributes. It's not a catastrophe if we have the long form in some places because I missed one here or there. In some places, I left the long form in the assembly as a first reference; in others I did not, especially if "MicroShift" is the title.

https://66152--docspreview.netlify.app/microshift/latest/microshift_getting_started/microshift-understanding
https://66152--docspreview.netlify.app/microshift/latest/microshift_getting_started/microshift-architecture
Install book
https://66152--docspreview.netlify.app/microshift/latest/microshift_install/microshift-embed-in-rpm-ostree#adding-microshift-repos-image-builder_microshift-embed-in-rpm-ostree
https://66152--docspreview.netlify.app/microshift/latest/microshift_install/microshift-greenboot
https://66152--docspreview.netlify.app/microshift/latest/microshift_install/microshift-installing-troubleshooting
Support book
https://66152--docspreview.netlify.app/microshift/latest/microshift_support/microshift-etcd
https://66152--docspreview.netlify.app/microshift/latest/microshift_support/microshift-sos-report
Config book
https://66152--docspreview.netlify.app/microshift/latest/microshift_configuring/microshift-using-config-tools
https://66152--docspreview.netlify.app/microshift/latest/microshift_configuring/microshift-cluster-access-kubeconfig
https://66152--docspreview.netlify.app/microshift/latest/microshift_configuring/microshift-greenboot-checking-status
Networking
https://66152--docspreview.netlify.app/microshift/latest/microshift_networking/microshift-cni
https://66152--docspreview.netlify.app/microshift/latest/microshift_networking/microshift-networking-settings
https://66152--docspreview.netlify.app/microshift/latest/microshift_networking/microshift-firewall
The Storage book has assembly-level/intro changes in each assembly; the modules are mostly from OCP and have no changes (long form here is unavoidable where present)
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/understanding-ephemeral-storage-microshift
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/generic-ephemeral-volumes-microshift
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/understanding-persistent-storage-microshift
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/expanding-persistent-volumes-microshift
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/microshift-storage-plugin-overview
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/volume-snapshots-microshift
https://66152--docspreview.netlify.app/microshift/latest/microshift_storage/microshift-storage-migration
Running applications
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-embedded-apps-on-rhel-edge
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-embed-apps-offline-use
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-embedding-apps-tutorial
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-applications
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-operators
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-greenboot-workload-scripts
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-authentication
https://66152--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-deploy-with-mirror-registry
Troubleshooting
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-version
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-troubleshoot-backup-restore
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-troubleshoot-cluster
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-troubleshoot-updates
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-audit-logs
https://66152--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-things-to-know

QE review:
- N/A docs plumbing

Additional information:
This PR was created to adjust the attribute for MicroShift. The CP attribute value for {product-title} was changed to "Red Hat build of MicroShift" which is ungainly within doc text. This PR applies a {microshift-short} attribute throughout.

### CODE REVIEW

**Comment by aldiazRH** [comment]
LGTM!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
