### PR TITLE
CNV-33381: Added RN for windows server 2025 support

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s):
4.17

Issue: [CNV-33381](https://issues.redhat.com/browse/CNV-33381)

[Link to docs preview](https://84607--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html#virt-4-17-virtualization)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dominikholler** [comment]
Thanks @MirzWeiss !
LGTM

FYI: @mtessun meiravdn

@djfjeff Do you plan to update https://access.redhat.com/articles/4234591 ?

**Comment by djfjeff** [comment]
@dominikholler I have updated the kbase accordingly

**Comment by dominikholler** [comment]
> @dominikholler I have updated the kbase accordingly

Thanks a lot, looks good!

**Review by lahinson — COMMENTED** [review]
lgtm

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
