### PR TITLE
OSDOCS-4079: Bumped version number in mirror links

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.12

Issue:
This PR addresses [osdocs-4079](https://issues.redhat.com/browse/OSDOCS-4079).

Link to docs preview:
- [Creating the RHCOS cluster image for the GCP infrastructure](https://53496--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-user-infra-rhcos_installing-gcp-user-infra)
- [The inventory.yml file](https://53496--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-about-inventory-yml_installing-rhv-user-infra)
- [Specifying the RHCOS image settings](https://53496--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-specifying-rhcos-image-settings_installing-rhv-user-infra)
- [Installing RHCOS by using an ISO image](https://53496--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-iso_installing-bare-metal)
- [Installing RHCOS and starting the OpenShift Container Platform bootstrap process](https://53496--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-pxe_installing-bare-metal)

### CODE REVIEW

**Comment by gpei** [comment]
@mjpytlak yeah, the changes looks good to me, thanks.

**Comment by mjpytlak** [comment]
Thank you @gpei for the quick turnaround.

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
