### PR TITLE
OSDOCS-10407 clarified cluster creation vCPU requirement

### PR DESCRIPTION
**Pull request by xJustin**
Version(s):

4.15+

Issue:

https://issues.redhat.com/browse/OSDOCS-10407

Link to docs preview:

https://77096--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-required-aws-service-quotas.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — COMMENTED** [review]
what about HCP?

**Comment by xJustin** [comment]
Beyond scope for this issue.  
HCP to be covered in https://issues.redhat.com/browse/OSDOCS-9967
when the numbers are refined.

**Review by arendej — APPROVED** [review]
lgtm

**Comment by xueli181114** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by xJustin** [comment]
thanks @GroceryBoyJr !

**Pull request merged**
