### PR TITLE
Follow-up to Switch terminology (instant app vs. quickstart) PR#1724

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/1724

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @tnguyen-rh @bfallonf @tpoitras PTAL. A little uncertain about this follow-up. Looks like "Quickstart" terminology is favored, but both terms are used in Dev Preview. Not sure what the difference is exactly.

**Comment by tnguyen-rh** [comment]
@ahardin-rh
IIRC, both are valid and describe slightly different concepts.  One is intended to mean "no tinkering required" while the other is intended to mean "tinkering required" (which is which, i can't recall, unfortunately).

Since i'm here, i did a quick peer review.  LGTM.

**Comment by adellape** [comment]
@ahardin-rh @tnguyen-rh Here's how we're defining quickstarts:

https://docs.openshift.com/enterprise/latest/dev_guide/app_tutorials/quickstarts.html

Whereas I believe an "instant app" is meant to suggest that you'll end up with something actually usable out the gate, currently our only default template example of this being Jenkins. But something like WordPress could be an instant app, if we had a template for that. cc @bparees for corrections.

**Comment by bparees** [comment]
@adellape +1

quickstart is basically a starting point for app development.  it gives you something that's running, but not something useful.  the assumption is you'll take the code it gives you and start from there to develop your real app.

**Comment by ahardin-rh** [comment]
@tnguyen-rh @adellape @bparees  Thanks! Very helpful. :bow:

Do you think I should make a brief comment about that within this topic? Perhaps in the Overview?

**Comment by tnguyen-rh** [comment]
@ahardin-rh I think that's a good idea.

**Comment by ahardin-rh** [comment]
@adellape @tnguyen-rh Added a note box about Quickstarts vs Instant Apps. PTAL. Thanks!

**Comment by tnguyen-rh** [comment]
@ahardin-rh The body of the NOTE is fine, but the syntax is incorrect.  Here is a command you can use to see other (correct) examples in the tree:

    git grep NOTE

(Invoke from root dir for best results.)

Otherwise, LGTM. :+1:

**Comment by ahardin-rh** [comment]
@tnguyen-rh Oops! Good catch! fixed.

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../getting_started/developers/developers_cli.html[Developers -> Getting Started for Developers: CLI]
|Added Instant App and Quickstart information, including a Note box explaining the difference between them.
%

**Comment by adellape** [comment]
We never actually published the developers_cli topic into anything, so I've disabled the revhistory note above.

**Pull request merged**
