### PR TITLE
Bug 1337801 added TCP/UDP protocol to network access list

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://bugzilla.redhat.com/show_bug.cgi?id=1337801

Asking for ack over email

### CODE REVIEW

**Comment by bfallonf** [comment]
Got an ack this is all good.

@tpoitras @ahardin-rh @adellape @tnguyen-rh peer review plz?

**Comment by bfallonf** [comment]
(accidentally closed this... has been reopened)

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/install/prerequisites.adoc[Installing -> Prerequisites]
|Added TCP/UDP information to the xref:../install_config/install/prerequisites.adoc#prereq-network-access[Network Access} tables.
%

**Comment by tpoitras** [comment]
@bfallonf LGTM, hombre. :man: :cactus: :tada:

**Comment by tnguyen-rh** [comment]
@bfallonf LGTM.

**Comment by bfallonf** [comment]
Cool. Merging.

**Pull request merged**
