### PR TITLE
Bug 1291594, added warning admonition

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1291594

@adellape @nak3 How does this look?

### CODE REVIEW

**Comment by nak3** [comment]
LGTM. Thank you!

**Comment by adellape** [comment]
@ahardin-rh @nak3 It wasn't immediately clear to me from the Warning whether it was referring to the /etc/resolv.conf file of the master or node host, or from within a container. I'm assuming from the context of th topic and the linked material in the BZ that it's the former, but clarifying either way (e.g., "in the /etc/resolv.conf file on each host") may be helpful.

Also, the `nameserver` and `search` lines are both in the /etc/resolv.conf file, so the sentence could probably be restructured a bit.

**Comment by nak3** [comment]
Ah, I see. I agree @adellape 
Sorry, @ahardin-rh please add `in the /etc/resolv.conf file on each node host` (master is not supposed to be affected.)

**Comment by ahardin-rh** [comment]
@nak3 @adellape thanks for your feedback! I made the updates. Please let me know if further edits are needed.

**Pull request closed without merging**
