### PR TITLE
Bug 1437738, Relocated F5 Big-IP content

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1437738

Preview Build: http://file.rdu.redhat.com/~ahardin/04202017/f5-relocate/architecture/additional_concepts/f5_big_ip.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@juanluisvaladas @bfallonf PTAL

**Comment by bfallonf** [comment]
@ahardin-rh Fulfills the BZ :star:

I didn't give this a big review, because I'm not sure if it's new content. Let me know if you want a more thorough review. Either way, :100:

**Comment by juanluisvaladas** [comment]
@ahardin-rh Fullfills the bugzilla, the relocation is way more logical and looks perfect to me.

The content has several flaws that have to be fixed. To avoid duplication of work once this is fixed I'll open an issue and pull request.

**Comment by juanluisvaladas** [comment]
@ahardin-rh I just noticed this has the  label branch/enterprise-3.3 and that's not correct. OCP 3.3 doesn't support nattive integration of F5 routers. It must be done using ramp nodes, so this cannot be merged. into 3.3, only 3.4 and 3.5

**Comment by ahardin-rh** [comment]
@bfallonf @juanluisvaladas Thanks so much! I adjusted the labeling and will get this merged so that @juanluisvaladas can follow up with additional feedback. I appreciate the guidance. Brice, for the next round of edits based on the next round of feedback, I will likely reach out for further peer review. Thanks again!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/additional_concepts/f5_big_ip.adoc#architecture-additional-concepts-f5-big-ip[Additional Concepts -> F5 BIG-IP® Router Plug-in]
|F5 BIG-IP® Router Plug-in is now its own topic. 
%

**Pull request merged**
