### PR TITLE
OCPBUGS#15054: update PTP rest API endpoints

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-15054

Link to docs preview: https://67099--docspreview.netlify.app/openshift-enterprise/latest/networking/using-ptp#cnf-fast-event-notifications-api-refererence_using-ptp (removal)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@huiran0826 could you PTAL at this docs PR for QE ack? thank you 🙇

**Comment by jldohmann** [comment]
@gsr-shanks could you PTAL at this docs PR for QE ack? Thank you 😃

**Comment by xenolinux** [comment]
LGTM

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead.

**Comment by jldohmann** [comment]
thank you both @xenolinux and @abhatt-rh 🎉

**Pull request merged**
