### PR TITLE
document probe and template recommendations

### LINKED ISSUE #1938: example s2i should contain best practices (generation of template, liveiness and readiness probe, resource and quota limits)
Per https://github.com/openshift/source-to-image/issues/472#issuecomment-214076552

Context:  I'm trying to builda aspnet s2i image using the example contained in the s2i repo. I found it to be incomplete. https://github.com/openshift/s2i-base is also incomplete. Tagging @bparees.

We should provide best pratices documentation and a template that will stand up your image in a deployment config
1) provide a recommended readiness and liveness probe definition
2) ideally provide a template that will stand up your image in a deployment config.

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/openshift-docs/issues/1938

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal
@alberttwong fyi.

**Comment by bfallonf** [comment]
@bparees This looks OK to me. But it's having Travis problems. Maybe a re-push?

**Comment by ahardin-rh** [comment]
:raising_hand: @bfallonf The Travis issue is a known issue. I just learned that work to fix it will be started after 11:00am EST today.

**Comment by bparees** [comment]
@bfallonf passed travis

**Comment by bfallonf** [comment]
Cool. I'll merge this. Thanks all!

**Pull request merged**
