### PR TITLE
Removes MCE from TP table bc it has been GA since 4.10

### PR DESCRIPTION
**Pull request by opayne1**
Removes MCE from TP table bc it has been GA since 4.10

Version(s):
4.12

Issue:
No issue. Just change based on conversation in slack. FYI @lahinson 

Link to docs preview:
https://54887--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-technology-preview

QE review:
- [ ] QE has approved this change.
No QE needed

Additional information:
FYI @JoeAldinger

### CODE REVIEW

**Review by berenss — APPROVED** [review]
looks good! thank you for the quick updates.

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
