### PR TITLE
BZ2026814: Added support for NIC Mellanox ConnectX Lx 15b3:101f

### PR DESCRIPTION
**Pull request by ctauchen**
Added new NIC device to SR-IOV support table. 

4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2026814
4.10: https://bugzilla.redhat.com/show_bug.cgi?id=2026813

Preview: https://deploy-preview-39607--osdocs.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov#supported-devices_about-sriov

### CODE REVIEW

**Comment by ctauchen** [comment]
@zshi-redhat Can you take a look?

**Comment by zshi-redhat** [comment]
> @zshi-redhat Can you take a look?

@ctauchen  This change looks good to me, thanks for working on it!

/cc @zhaozhanqi

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
