### PR TITLE
Fixed CSI Driver Operator

### PR DESCRIPTION
**Pull request by AryanSharma9917**
Version(s):

Issue: #64747

Link to docs preview: https://docs.openshift.com/container-platform/4.13/storage/container_storage_interface/persistent-storage-csi-vsphere.html

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@duanwei33, will you please confirm this change?

**Comment by kalexand-rh** [comment]
> @duanwei33, will you please confirm this change?

@duanwei33, will you PTAL?

**Comment by duanwei33** [comment]
I'm so sorry that missed the reminders!

**Comment by stevsmit** [comment]
Preview: https://65605--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere

**Comment by stevsmit** [comment]
LGTM. Because this is a Hacktoberfest issue, I'm going to merge it.

**Pull request merged**
