### PR TITLE
GH49038: Fix YAML error in custom autoscaler

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/49038

[Preview in Step 2, callout 10](http://file.rdu.redhat.com/mburke/nodes-fix-custom-scaler-yaml/nodes/pods/nodes-pods-autoscaling-custom.html#nodes-pods-autoscaling-custom-creating-job_nodes-pods-autoscaling-custom)

### CODE REVIEW

**Comment by mburke5678** [comment]
@weinliu PTAL

**Review by bscott-rh — APPROVED** [review]
LGTM

**Pull request merged**
