### PR TITLE
RHDEVDOCS-5999: Removal of Fixed Issues and JIRA links from GitOps 1.9.4, 1.10.2, 1.11.1 releases

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

This PR must be CP'ed to the GitOps 1.12, 1.11, 1.10, and 1.9 releases.

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-5999

Link to docs preview:

https://74190--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#gitops-release-notes-1-11-1_gitops-release-notes
https://74190--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#gitops-release-notes-1-10-2_gitops-release-notes
https://74190--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#gitops-release-notes-1-9-4_gitops-release-notes

SME review: @reginapizza
QE review: @varshab1210 
Peer review: @Srivaralakshmi  

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Dhruv-Soni11** [comment]
Hi @reginapizza, @varshab1210, and @Srivaralakshmi - As per our discussion on the [Slack thread](https://redhat-internal.slack.com/archives/C01RQH8KQ87/p1711370722119709.), I have made the required changes and would request you to have a look and provide ACKs if everything looks fine.

**Comment by Srivaralakshmi** [comment]
LGTM

**Review by reginaelyse — APPROVED** [review]

**Comment by varshab1210** [comment]
LGTM

**Pull request merged**
