### PR TITLE
[SRVCOM-3270] Fix links in Dev metrics overview

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.28+

Issue:
https://issues.redhat.com/browse/SRVCOM-3270

Link to docs preview:
- https://81283--ocpdocs-pr.netlify.app/openshift-serverless/latest/observability/developer-metrics/serverless-developer-metrics.html

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
Peer review LGTM

**Comment by ShaunaDiaz** [comment]
@ochromy You can create manual cherry pick for the failed branches and resubmit either to me directly (Slack me) or put back in the queue.

**Pull request merged**
