### PR TITLE
Removing Event Router from 4.x docs

### PR DESCRIPTION
**Pull request by mburke5678**
Removing Event Router from the 4.x docs prior to 4.5, per Slack: https://coreos.slack.com/archives/CB3HXM2QK/p1596621331096100

Event Router was removed from 4.5+ in the Logging docs re-org.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sferich888 @xltian @sichvoge @vikram-redhat PTAL

**Comment by vikram-redhat** [comment]
@mburke5678 should this have been against the master branch?

**Comment by QiaolingTang** [comment]
lgtm

**Comment by mburke5678** [comment]
Eric Ricj ack in email

[ERichAck.pdf](https://github.com/openshift/openshift-docs/files/5041536/ERichAck.pdf)

**Comment by mburke5678** [comment]
@vikram-redhat I used the enterprise-4.4 branch because I had removed the files from master and 4.5 when I reorganized the cluster logging docs. (Turns out that I removed only the assembly and modified the topic map).

**Comment by sichvoge** [comment]
Thanks Michael. As discussed w/ the engineering team, supporting event router for 4.x was not planned as there have been several issues on how it worked in the first place. We will look back on this feature if we see a high demand for it.

This PR 👍  LGTM

**Review by codyhoag — APPROVED** [review]
LGTM!

**Comment by mburke5678** [comment]
@vikram-redhat OK to merge this?

**Comment by vikram-redhat** [comment]
> @vikram-redhat OK to merge this?

Change notification sent?

**Pull request merged**
