### PR TITLE
[BZ2106760] backport 4.7 Change delete-local-data to delete-emptydir-data

### PR DESCRIPTION
**Pull request by SNiemann15**
Backport of this PR to 4.7 https://github.com/openshift/openshift-docs/pull/47957

Version(s): 4.7

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2106760

Link to docs preview:

http://file.str.redhat.com/~sniemann/delete_emptydir_47/support/troubleshooting/troubleshooting-crio-issues.html#cleaning-crio-storage
http://file.str.redhat.com/~sniemann/delete_emptydir_47/post_installation_configuration/node-tasks.html#rhel-removing-rhcos_post-install-node-tasks
~~http://file.str.redhat.com/~sniemann/delete_emptydir_47/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-evacuating_nodes-nodes-working~~
~~http://file.str.redhat.com/~sniemann/delete_emptydir_47/virt/node_maintenance/virt-setting-node-maintenance.html~~
Working links from Michael: 
http://file.rdu.redhat.com/mburke/49246/virt/node_maintenance/virt-setting-node-maintenance.html
http://file.rdu.redhat.com/mburke/49246/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-evacuating_nodes-nodes-working
Additional information: Flag --delete-local-data has been deprecated see:
https://access.redhat.com/solutions/6801291

### CODE REVIEW

**Comment by SNiemann15** [comment]
/assign @weinliu 
Please review and approve.

**Review by bscott-rh — APPROVED** [review]
Thank you for updating the previews. LGTM

**Comment by opayne1** [comment]
LGTM!

**Pull request merged**
