### PR TITLE
OSSMDOC-429: Small edits to service mesh release notes

### PR DESCRIPTION
**Pull request by rh-tokeefe**
- Aligned team: Dev Tools
- For branches: 
- Jira: https://issues.redhat.com/browse/OSSMDOC-429
- Direct link to doc preview: https://deploy-preview-38435--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/servicemesh-release-notes#istio-1-9-support
- SME review: @longmuir
- QE review: @yxun
- Peer review: @ 	tbd
- Cherry pick to 4.6, 4.7, 4.8, 4.9, and 4.10

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Comment by longmuir** [comment]
LGTM - thank you!

**Comment by bburt-rh** [comment]
lgtm

**Review by yxun — APPROVED** [review]

**Pull request merged**
