### PR TITLE
OSDOCS-4887: moves SNO to installation and update in RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-4887

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
@johnwilkins PTAL cc @yunjiang29

### CODE REVIEW

**Comment by yunjiang29** [comment]
@JoeAldinger @johnwilkins I think we need to add some description to let users know SNO is officially supported.

**Comment by johnwilkins** [comment]
> @JoeAldinger @johnwilkins I think we need to add some description to let users know SNO is officially supported.

It was already added in this PR: https://github.com/openshift/openshift-docs/pull/58948/files

**Comment by yunjiang29** [comment]
@JoeAldinger @johnwilkins sorry I did not notice that, then we can delete `install-sno-requirements-for-installing-on-a-single-node` section from release note, wdyt?

**Comment by JoeAldinger** [comment]
closing PR as the contents have been covered in a PR #58948

**Pull request closed without merging**
