### PR TITLE
OBSDOCS-741: Span red alerts

### PR DESCRIPTION
**Pull request by max-cx**
Test PR for my review and edit of https://github.com/openshift/openshift-docs/pull/69962

Version(s):

4.11, 4.12, 4.13, 4.14, 4.15

Issue:

https://issues.redhat.com/browse/OBSDOCS-741
https://issues.redhat.com/browse/TRACING-3574

Link to docs preview:

https://70858--ocpdocs-pr.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring#span-red-metrics-and-alerting-rules

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Comment by max-cx** [comment]
Merged as https://github.com/pavolloffay/openshift-docs/pull/1.

**Pull request closed without merging**
