### PR TITLE
[Osdocs 6373]: Fix the audit log documentation for OSD/ROSA

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-6373
Link to docs preview:

OSD: https://60828--docspreview.netlify.app/openshift-dedicated/latest/welcome/index.html

ROSA: https://60828--docspreview.netlify.app/openshift-rosa/latest/welcome/index.html
QE review:
- [ ] QE has approved this change.

Q/A Review NA
Additional information:

### CODE REVIEW

**Comment by mburke5678** [comment]
@mletalie Will this need to be cherrypicked anywhere?

**Comment by mletalie** [comment]
Hello @mburke5678, 
    Thanks for looking into this; this should be applied to 4.13 and 4.14. Hope that helps, thanks again!

**Comment by 0kashi** [comment]
lgtm

**Pull request merged**
