### PR TITLE
[OSDOCS-6828]: AWS STS and GCP WID diagram enhancement

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.10+

Issue:
[OSDOCS-6828](https://issues.redhat.com//browse/OSDOCS-6828)

Link to docs preview:
* [About manual mode with AWS Security Token Service](https://62186--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#sts-mode-about_cco-mode-sts)
* [About manual mode with GCP Workload Identity](https://62186--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-mode-gcp-workload-identity.html#gcp-workload-identity-mode-about_cco-mode-gcp-workload-identity)

QE review:
- [x] QE has approved this change.

Additional information:
- AWS STS updated
- GCP Workload ID new

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@abutcher and @jianping-shu this PR updates the AWS STS authentication flow diagram and adds a similar one for GCP Workload ID. PTAL when you have a moment :bow:

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by abutcher** [comment]
LGTM

**Comment by jianping-shu** [comment]
LGTM

**Pull request merged**
