### PR TITLE
OSDOCS#11576: Adding note to not use memory ballooning

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-11576

Link to docs preview:
* https://80237--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/upi-vsphere-installation-reqs.html#installation-minimum-resource-requirements_upi-vsphere-installation-reqs

Also, here is an example of another assembly that uses this module, to show that this note only appears for vSphere: https://80237--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites#installation-minimum-resource-requirements_ipi-install-prerequisites

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@jianli-wei Can you please QE review?

Preview: https://80237--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/upi-vsphere-installation-reqs.html#installation-minimum-resource-requirements_upi-vsphere-installation-reqs

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
