### PR TITLE
Administrator CLI commands: use 4.1 example in release example

### PR DESCRIPTION
**Pull request by vrutkovs**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vrutkovs, I think we should show the delta between the last beta version and GA.

**Comment by vrutkovs** [comment]
@kalexand-rh good idea, updated

**Comment by kalexand-rh** [comment]
Thanks @vrutkovs!

@mffiedler, will you please +1? This looks right to me.

**Review by mffiedler — APPROVED** [review]
/lgtm

**Comment by kalexand-rh** [comment]
Thank you both! Merging.

**Pull request merged**
