### PR TITLE
Adds EOL banner for RHACS 4.0 docs

### PR DESCRIPTION
**Pull request by gaurav-nelson**
[RHACS 4.0 version reached its EOL on 3 Nov 2023](https://access.redhat.com/support/policy/updates/rhacs). This PR adds the version number to the unsupported version list to show up the unsupported banner on the docs page.

Similar to https://github.com/openshift/openshift-docs/pull/61033

No cherry-picks.

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

**Comment by abhatt-rh** [comment]
> LGTM
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead 

@gaurav-nelson @xenolinux LGTM!

**Pull request merged**
