### PR TITLE
Use official image for NFD Operator

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
Applies to 4.10+

Preview is [here](https://deploy-preview-40221--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html#create-cd-cli_node-feature-discovery-operator).

**Comment by kmccarron-rh** [comment]
There are two additional occurrences of 4.9 in this assembly that require change from 4.9 to 4.10.
https://deploy-preview-40221--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html#install-operator-cli_node-feature-discovery-operator.
I will open a separate PR to address those.

**Review by bergerhoffer — COMMENTED** [review]
LGTM merging!

**Pull request merged**
