### PR TITLE
Document s390x support for PCI -DSS profiles

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.12+

Issue: Update docs to show newly released support for s390x in the Compliance Operator

Link to docs preview: https://77783--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/compliance_operator/co-scans/compliance-operator-supported-profiles.html

QE review:
- [X] QE has approved this change.

Additional information: this PR is a "child" to https://github.com/openshift/openshift-docs/pull/77746, which is information provided by the prime SME.

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@xiaojiey PTAL

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
