### PR TITLE
OSDOCS-4760: remove use of oc login for microshift

### PR DESCRIPTION
**Pull request by dhellmann**
Version(s): 4.12

Issue: [OSDOCS-4760](https://issues.redhat.com//browse/OSDOCS-4760)

Link to docs preview:
Removed for MicroShift: https://54332--docspreview.netlify.app/microshift/latest/cli_reference/openshift_cli/getting-started-cli.html
Retained for OpenShift: https://54332--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in_cli-developer-commands

QE review:
N/A -- MicroShift is Developer Preview
SME approval is required, author is the SME approver

Additional information:

OCP has APIs called User and Project. We do not have those APIs in MicroShift. There is certificate-based authentication, using the kubeconfig file, but you can't use `oc login`.

### CODE REVIEW

**Review by ShaunaDiaz — COMMENTED** [review]
@dhellmann Should probably remove the Logout module as well? LGTM otherwise

**Comment by dhellmann** [comment]
> @dhellmann Should probably remove the Logout module as well? LGTM otherwise

Ha! Good catch, thank you. Done.

**Review by skrthomas — COMMENTED** [review]
LGTM

**Pull request merged**
