### PR TITLE
Remove vSphere IPv6 from release

### PR DESCRIPTION
**Pull request by jboxman-rh**
Per https://issues.redhat.com/browse/OPNET-198 this is no longer included in the release.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by snarayan-redhat** [comment]
@mkowalski @cybertron - I believe we are still are going ahead with dual-stack for vSphere clusters, but we are not allowing IPv6 as primary in this release. Hence this RN still is valid and need not be removed.  There is a related PR https://github.com/openshift/openshift-docs/pull/59232 which removes the dual-stack note for vSphere which also seems to be valid. Can you confirm?

**Comment by mkowalski** [comment]
The following are working for 4.13

* dual-stack on vSphere with IPv4 as primary and IPv6 as secondary

The following are not working for 4.13

* dual-stack on vSphere with IPv6 as primary and IPv4 as secondary (blocked by validation in o/installer)

**Comment by GroceryBoyJr** [comment]
@jboxman-rh I see that the correct docs will be provided in https://issues.redhat.com/browse/OSDOCS-3606, which makes this deletion make sense. :+1:

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by jboxman-rh** [comment]
@bscott-rh, from this, I can't tell if we're releasing IPv4/IPv6 on vSphere for this release or not? It's the IPv6-first that's not possible?

Thanks.

**Comment by mkowalski** [comment]
Folks, just to reiterate... This PR **removes** the following sentence

"On installer-provisioned vSphere clusters, you can use dual-stack networking with IPv4 as the primary IP family, and IPv6 as the secondary address family"

and this is incorrect. This sentence should **stay** in release notes for 4.13 because we are releasing this feature

**Comment by jboxman-rh** [comment]
@mkowalski, yes, that's what I _thought_ was true. Then there's no reason for this PR to remain open.

**Comment by jboxman-rh** [comment]
Closing as unnecessary.

**Pull request closed without merging**
