### PR TITLE
BZ-2013110:removes hostname from command copy button

### PR DESCRIPTION
**Pull request by JoeAldinger**
4.6+

BZ 2013110 https://bugzilla.redhat.com/show_bug.cgi?id=2013110

**Preview** file: https://deploy-preview-43025--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html

Removes hostname from commands to avoid copying them. 

I will need labels and milestones as well as a merge, please and thanks.

### CODE REVIEW

**Comment by shellyyang1989** [comment]
lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
