### PR TITLE
OSDOCS-5419: Added VMWare Cloud Verified info to vSphere docs

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-5419](https://issues.redhat.com/browse/OSDOCS-5419)

Version(s):
4.13

Issue:
[VMware vSphere infrastructure requirements](https://56456--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/preparing-to-install-on-vsphere.html#installation-vsphere-infrastructure_preparing-to-install-on-vsphere)

Link to docs preview:

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by racedo** [comment]
lgtm

**Comment by duanwei33** [comment]
I'm not sure if we need some test/verification.
Also I'm not sure if our vsphere on VMC is kind of "VMware Cloud Verified provider".

I'd leave it to installer QE to review.  
@sgaoshang

**Pull request merged**
