### PR TITLE
BZ1878374: updating AWS instance lists

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1878374

4.7+

The most interesting part of the preview is here: https://deploy-preview-33261--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-user-infra.html#installation-supported-aws-machine-types_installing-aws-user-infra

### CODE REVIEW

**Comment by cuppett** [comment]
:+1: from me.

**Comment by vikram-redhat** [comment]
+1

**Comment by xltian** [comment]
+1

**Comment by vikram-redhat** [comment]
Have received all acks. Change notifications were sent. Given the time sensitive nature of this, I am merging this.

**Comment by vikram-redhat** [comment]
Bypassing peer reviews as this is part of an existing documentation set that is being put back.

**Pull request merged**
