### PR TITLE
Update docs to remove Docker daemon

### PR DESCRIPTION
**Pull request by bmcelvee**
Initial draft of removing Docker daemon content. Commented out Docker builds for now, but will adjust as I get more information. 

https://jira.coreos.com/browse/DEVEXP-308

### CODE REVIEW

**Comment by adambkaplan** [comment]
@bmcelvee unforntunately `Docker` strategy is a bit of a misnomer - it's really a "Dockerfile" strategy as the input is a Dockerfile which buildah turns into an image.

https://jira.coreos.com/browse/DEVEXP-308 has been updated to reflect what we want to deprecate, which is the "Expose Docker socket" field on Custom strategy builds.

**Comment by adambkaplan** [comment]
(the Docker strategy build is not being deprecated)

**Comment by bmcelvee** [comment]
Thanks @adambkaplan! I'll update the PR. :star2:

**Comment by bmcelvee** [comment]
Closing PR. There are no references to the `Expose Docker socket` field in the 4.1 documentation.

**Pull request closed without merging**
