### PR TITLE
[OCPBUGS-6849]:  Update commands to find etcd pods

### PR DESCRIPTION
**Pull request by tmalove**
[OCPBUGS-6849](https://issues.redhat.com/browse/OCPBUGS-6849)

Command changes were made in 6 files.
Note: An errant commit was removed from this PR, which shows as the only commit after squashing.
Version(s):
4.12+ 
Merge reviewer: CP from 4.9 to 4.11

Issue:
[Engineering issue](https://github.com/openshift/openshift-docs/pull/55355)

Links to docs preview:
- https://55411--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state
- Manual defragmentation (step 1a): https://55411--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#manual-defrag-etcd-data_recommended-host-practices
- Determining the state of the unhealthy etcd member (step 3b): https://55411--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html
- Replacing an unhealthy etcd member whose etcd pod is crashlooping (step 2a): https://55411--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member
- Replacing an unhealthy  bare metal etcd member whose machine is not running or whose node is not ready (step 1a and verification step 1): https://55411--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-baremetal-etcd-member_replacing-unhealthy-etcd-member
- Replacing an unhealthy etcd member whose machine is not running or whose node is not ready (step 1a): https://55411--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-etcd-member_replacing-unhealthy-etcd-member

QE review:
- [ ] QE has approved this change. (Ge Liu)

### CODE REVIEW

**Comment by tmalove** [comment]
@wking Take a look at the 5th preview link for the 'bare metal' member. This is one of the files to update? Let me know if this looks good or if more changes/corrections are needed.

**Comment by tmalove** [comment]
/enterprise-4.9

**Comment by tmalove** [comment]
@wking I added a new line in both instances, take a look at the files to verify. If this is not what you want, we should do a quick screen share to get this done. Also, I will squash the commits later before I send this for a peer review. Thanks!

**Comment by tmalove** [comment]
@geliu2016 Please take a look at these updates. Thank you!

**Review by wking — APPROVED** [review]
/lgtm

**Comment by tmalove** [comment]
branch/enterprise-4.8

**Comment by bscott-rh** [comment]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
