### PR TITLE
[enterprise-4.15]TELCODOCS-1916: Moving under scalability and performance section

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1916](https://issues.redhat.com//browse/TELCODOCS-1916): This content was added as a top level assembly. However, it should be in the scalability and performance assembly. No content changes - just moving the files and adjusting paths for xrefs accordingly.

Version(s):
4.15

Issue:
https://issues.redhat.com/browse/TELCODOCS-1916

Link to docs preview:
https://78459--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/telco_ref_design_specs/telco-ref-design-specs-overview

Additional information:
QE not required, just moving content as it was in the wrong place. This content is not in 4.16 or later yet, but it is published in 4.15 and 4.14, so that is why I am targeting the release branch. This is the 4.14 PR: #78427

### CODE REVIEW

**Comment by mburke5678** [comment]
The new location of the files LGTM.

@rohennes Have you requested [redirects](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.dtk57a6enor2) for the moved assemblies?

**Comment by rohennes** [comment]
> The new location of the files LGTM.
> 
> @rohennes Have you requested [redirects](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.dtk57a6enor2) for the moved assemblies? Also, these changes are for `enterprise-4.15` only?

Good point about redirects, thanks! I will follow those instructions.

Yes, while I'm also moving this section in 4.14, the content itself is unique to each release branch.

**Comment by rohennes** [comment]
> The new location of the files LGTM.
> 
> @rohennes Have you requested [redirects](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.dtk57a6enor2) for the moved assemblies? Also, these changes are for `enterprise-4.15` only?

@mburke5678 - Having reviewed the redirect guidelines, I don't think this needs a redirect as the content was only published 2 days ago so I think there will be almost no traffic going to this page yet.

**Pull request merged**
