### PR TITLE
GH3912 osm_etcd_image

### PR DESCRIPTION
**Pull request by ckyriakidou**
https://github.com/openshift/openshift-docs/issues/3912
https://bugzilla.redhat.com/show_bug.cgi?id=1420510

### CODE REVIEW

**Comment by ckyriakidou** [comment]
@vikram-redhat would this satisfy BZ1420510?

**Comment by vikram-redhat** [comment]
Thanks @ckyriakidou . @bfallonf - PTAL.

**Comment by bfallonf** [comment]
Thanks @ckyriakidou . I'll merge this and do a quick followup PR for docs style.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/install/rpm_vs_containerized.adoc#install-config-install-rpm-vs-containerized[Installing a Cluster -> Containerized Components]
|Added paragraph about the `rhel7/etcd` image with containerized installs.
%

**Pull request merged**
