### PR TITLE
HTPasswd options

### PR DESCRIPTION
**Pull request by kalexand-rh**
Fixes https://github.com/openshift/openshift-docs/issues/11815

From https://github.com/openshift/openshift-docs/pull/11817 and https://github.com/openshift/openshift-docs/issues/11815#issuecomment-417218931

@vrutkovs, will you PTAL?

### CODE REVIEW

**Comment by vrutkovs** [comment]
LGTM, sorry for the delay

**Comment by kalexand-rh** [comment]
Thanks @vrutkovs! No worries on the delay.

**Pull request merged**
