### PR TITLE
Clarifying FIO documentation

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-35424

Link to docs preview:
[FileIntegrityNodeStatus CR failure status example](https://85905--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/file_integrity_operator/file-integrity-operator-understanding.html#file-integrity-node-status-failure_file-integrity-operator)

QE review:
- [ ] QE has approved this change.

Additional information:
None at this time.

### CODE REVIEW

**Review by Vincent056 — COMMENTED** [review]
thanks for the PR,
I wonder if we could change it to something like:
```
Due to the config map data size limit, AIDE logs over 1 MB are added to the failure config map as a base64-encoded gzip archive. In this case, you want to use following command to extract the log:
 [source,terminal]
----
$ oc get cm <failure-cm-name> -o json | jq -r '.data.integritylog' | base64 -d | gunzip
----


[NOTE]
====
Compressed logs are indicated by the presence of a `file-integrity.openshift.io/compressed` annotation key in the config map.
====
```

**Comment by sheriff-rh** [comment]
@xiaojiey  can you review this PR when you get a chance? Thanks.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
