### PR TITLE
OCPBUGS#4790 Changed link text and mentioned versions

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.10

Issue:
https://issues.redhat.com/browse/OCPBUGS-4790
https://issues.redhat.com/browse/OCPBUGS-4791

Link to docs preview:
https://cbippley.github.io/openshift-docs/OCPBUGS-4790/release_notes/ocp-4-10-release-notes.html#ocp-4-10-known-issues

QE review:
- [X] QE has approved this change.

Additional information:
Combined two bugs into one PR.

### CODE REVIEW

**Comment by cbippley** [comment]
@eurijon Please take a look, thank you!

**Comment by eurijon** [comment]
Hey @cbippley , sorry I missed this mention :(
The change looks good!

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
