### PR TITLE
OCPBUGS-30573: Fixed the IP addresses for vSphere config LB

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.16 - 4.12

Issue:
[OCPBUGS-30573](https://issues.redhat.com/browse/OCPBUGS-30573)

Link to docs preview:
[Configuring an external load balancer](https://73099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations#nw-osp-configuring-external-load-balancer_installing-vsphere-installer-provisioned-customizations)

- [x] SME has approved this change.
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by clarkhale** [comment]
lgtm!

**Review by skopacz1 — APPROVED** [review]
LGTM but on an unrelated note - jeez haha, is there any way this combo giant chunk of conceptual content + procedure can be reorganized to be more discrete at some point? I don't think I've ever seen a procedural module have this much conceptual info at the top

**Pull request merged**
