### PR TITLE
MetalLB Operator Doc updates for P/Z

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s) : 4.13+

Issue :
IBM P : https://issues.redhat.com/browse/MULTIARCH-3143
IBM Z : https://issues.redhat.com/browse/MULTIARCH-3144

Link to docs preview : https://55980--docspreview.netlify.app/openshift-enterprise/latest/networking/metallb/about-metallb.html#limitations-and-restrictions_about-metallb-and-metallb-operator

QE review :
- [x] QE has approved this change.

Additional information :

cc : @SNiemann15

### CODE REVIEW

**Comment by aemperador** [comment]
LGTM

**Comment by jschintag** [comment]
LGTM

**Review by skrthomas — COMMENTED** [review]
LGTM!

**Comment by sheriff-rh** [comment]
LGTM! Merging.

**Pull request merged**
