### PR TITLE
removing content from online

### PR DESCRIPTION
**Pull request by kalexand-rh**
Abhishek Gupta said that the high availability masters section shouldn't be visible in the Online collection.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation PTAL

**Comment by bfallonf** [comment]
@kalexand-rh Makes sense. @vikram-redhat Might have a better eye for it.

**Comment by vikram-redhat** [comment]
LGTM

**Comment by kalexand-rh** [comment]
Thanks @vikram-redhat!

**Comment by kalexand-rh** [comment]
3.10: https://github.com/openshift/openshift-docs/pull/10385
3.9: https://github.com/openshift/openshift-docs/pull/10386
3.7: https://github.com/openshift/openshift-docs/pull/10387
3.6: https://github.com/openshift/openshift-docs/pull/10388
3.5: https://github.com/openshift/openshift-docs/pull/10389
3.4: https://github.com/openshift/openshift-docs/pull/10390
3.3: https://github.com/openshift/openshift-docs/pull/10391
3.2: https://github.com/openshift/openshift-docs/pull/10392
3.1: https://github.com/openshift/openshift-docs/pull/10393
3.0: https://github.com/openshift/openshift-docs/pull/10394

**Pull request merged**
