### PR TITLE
[OCPBUGS-14494] Comment out fips in support matrix table

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OCPBUGS-14494

Block comments in table didn't work in this PR https://github.com/openshift/openshift-docs/pull/60829
Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM! Thank you!

**Comment by SNiemann15** [comment]
/label-merge-review-needed

No CM is needed for this PR because it only fixes a syntax that resolved incorrectly in this recently merged PR https://github.com/openshift/openshift-docs/pull/60829, which had an exception. 

cc: @mjpytlak @ahardin-rh

**Comment by ousleyp** [comment]
LGTM

**Pull request merged**
