### PR TITLE
OADP 3470 - DOC improvement - Must Gather Tool

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP 1.3.1

OCP 4.13+

Resolves - https://issues.redhat.com/browse/OADP-3470

Deploy preview - https://74328--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/troubleshooting.html#migration-using-must-gather_oadp-troubleshooting

### CODE REVIEW

**Review by PrasadJoshi12 — APPROVED** [review]

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by CarmiWisemon** [comment]
/do-not-merge/hold

**Comment by CarmiWisemon** [comment]
This was completed with a different PR

**Pull request closed without merging**
