### PR TITLE
[OSDOCS-10836]: What's New (RNs): XCMSTRAT-305

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10836
Link to docs preview:

https://77388--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_release_notes/rosa-release-notes.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by aldiazRH** [comment]
LGTM!

**Comment by davidleerh** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@EricPonvelle @mletalie This PR is marked for 4.15, but not cherry picked there. Should it be?

**Pull request merged**
