### PR TITLE
OCPBUG13560:Added a additional resources section to include the links related to worker nodes

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.11+

Issue: [OCPBUG13560](https://issues.redhat.com/browse/OCPBUGS-13560)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sjstout** [comment]
@subhtk , I think you added this in the Assisted Installer section, not the Agent Installer. The original bug is about the Agent installer. Also, I am not sure that this addresses the request in the original bug.

**Comment by subhtk** [comment]
Hi @sjstout, I think I have made a mistake there, let me change the location of the reference. Thank you for noticing it.

**Comment by kalexand-rh** [comment]
4.11 is now [EOL](https://access.redhat.com/support/policy/updates/openshift), and we are no longer updating it. Please set the versions to 4.12+.

**Pull request closed without merging**
