### PR TITLE
OCPBUGS-17767: Add warning about machine configs

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OCPBUGS-17767

This applies to 4.12+, but due to changes to this file, this PR can be applied on to 4.15+. A separate PR must address earlier OCP versions.

Version(s): 4.15+

Issue:

Link to docs preview: https://74554--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/changing-cluster-network-mtu.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Scotchman0** [comment]
This looks good to me and should address the concerns outlined in the bug; it is much clearer. Thank you!

**Comment by anuragthehatter** [comment]
looks good and agree with that warning

/lgtm

**Review by xenolinux — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

LGTM

**Pull request merged**
