### PR TITLE
Correct OLM full form to Operator Lifecycle Manager

### PR DESCRIPTION
**Pull request by ggore-rh**
This applies to 4.2 and onwards.

### CODE REVIEW

**Comment by ggore-rh** [comment]
@openshift/team-documentation

**Comment by vikram-redhat** [comment]
@adellape PTAL

**Comment by ggore-rh** [comment]
This commit fixes #25283

**Comment by vikram-redhat** [comment]
@kalexand-rh this can be merged without needing @adellape ack.

**Pull request merged**
