### PR TITLE
OSDOCS-2899 Update OCP mirror links for installations

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2899

Updates the same for all instances. The links will not be workable yet. Example preview:

https://deploy-preview-41157--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-user-infra-rhcos_installing-gcp-user-infra

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you confirm? Thanks!

**Comment by gpei** [comment]
LGTM

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
