### PR TITLE
Bug#1288488 - fixes - added build process section for all s2i images

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1288488
- Added overview
- Added link to existing detailed process

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@openshift/team-documentation PTAL 👓

**Review by ncbaratta — APPROVED** [review]
You might want to take that repeated build process and put it in its own adoc file and then just include it, but other than that the content is good.

**Comment by gaurav-nelson** [comment]
no rev history needed,

**Pull request merged**
