### PR TITLE
Adding cluster metrics docs to 4.0

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview Build:
http://file.rdu.redhat.com/~ahardin/11082018/scale-cluster-metrics-40/scalability_and_performance/scaling-cluster-metrics-components.html

Review tracker: https://jira.coreos.com/browse/ATS-171

Doc team card: https://jira.coreos.com/browse/OSDOCS-39

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@ekuric @jmencak PTAL and let me know if any changes are needed for 4.0. Thanks!

**Comment by ahardin-rh** [comment]
@ekuric @jmencak PTAL

**Comment by jmencak** [comment]
Haven't touched this stuff.  @ekuric is this still even relevant for 4.0?

**Comment by ahardin-rh** [comment]
Per discussion in today's meeting (https://docs.google.com/document/d/12S1LtXw1bCYEd_4hdhvadBOU3IzaOIfqAPV9UbHH0c0/edit), we're going to omit this content from 4.0. Closing this PR and updating Trello cards.

cc @jeremyeder

**Pull request closed without merging**
