### PR TITLE
added known issue for Grafana for 1.0.10-2

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSMDOC-98

### CODE REVIEW

**Comment by neal-timpe** [comment]
@yxun Can you take a look and approve this PR if you get a chance?

**Review by yxun — APPROVED** [review]

**Comment by yxun** [comment]
@neal-timpe Thanks, Neal. This PR is good. Approved.

**Review by brian-avery — APPROVED** [review]

**Review by JStickler — APPROVED** [review]

**Pull request merged**
