### PR TITLE
breaking a link to see what happens

### PR DESCRIPTION
**Pull request by kalexand-rh**
@vikram-redhat, I broke a link for you. ;)

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Thanks @kalexand-rh - so the first commit didn't actually fail the build? The second one did, right?

**Comment by kalexand-rh** [comment]
The first one passed, so I added a different sort of broken link. I didn't
hang around to see if it failed, but I assumed it would. :)

**Comment by vikram-redhat** [comment]
@kalexand-rh The first commit didn't trigger an error because that file is not included in any enterprise products :) https://github.com/openshift/openshift-docs/blob/master/_topic_map.yml#L660.

The build doesn't check for origin specific docs because it is targeted for publishing to the customer portal.

Having said that, even if it was included, it would only have triggered a warning, not an error. I am pushing through an update today that should fix that.

**Comment by kalexand-rh** [comment]
Got it! I'll be sure to rebase to pick up your change. :)

**Pull request closed without merging**
