### PR TITLE
BZ1670721: fix typo in config custom certs

### PR DESCRIPTION
**Pull request by dhoyle-rh**

### CODE REVIEW

**Comment by dhoyle-rh** [comment]
@openshift/team-documentation, this typo fix needs a peer review.

**Comment by mburke5678** [comment]
@dhoyle-rh LTGM Thanks for catching this. Looks like the typo is in 3.10 and 3.9 also.

**Comment by dhoyle-rh** [comment]
Thanks @mburke5678!

**Comment by vikram-redhat** [comment]
@dhoyle-rh - great work. Thanks! Reminder to cherry pick this content to the branches.

**Comment by dhoyle-rh** [comment]
> @dhoyle-rh - great work. Thanks! Reminder to cherry pick this content to the branches.

Thanks @vikram-redhat! I've cherry-picked this update -- for 3.11 I tried manually, then I used the bot for 3.10, then I had conflicts for 3.9, so I also did that one manually. When I first created the PRs for 3.9 and 3.11, each time they were trying to update master rather than the feature branch, which is why I closed those two. Subsequently I was able to create good PRs from 3.9 and 3.11 and merge those. I'm not sure yet why/how I created the bad PRs, but I'll see if I can figure it out on the next bug fix. But we should be good with this one.

**Comment by dhoyle-rh** [comment]
https://github.com/openshift/openshift-docs/pull/13744

**Pull request merged**
