### PR TITLE
[RHDEVDOCS-2327] Change all references from ''Add" view to "+Add" view

### PR DESCRIPTION
**Pull request by rishumehra**
Updated Add view to +Add view at all the required places.

JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2327
Version: OpenShift 4.7

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
The change itself looks fine to me, but it looks like the screenshot is out of date now.

**Comment by kalexand-rh** [comment]
Per @rishumehra, this change applies to 4.4+.

**Comment by kalexand-rh** [comment]
@rishumehra, if you squash your commits, I will merge them.

**Comment by rishumehra** [comment]
> @rishumehra, if you squash your commits, I will merge them.

@kalexand-rh Squashed commits to a single one. Please check and merge the PR.

**Pull request merged**
