### PR TITLE
CNV-16875: Update code sample on Configuring custom virtual machines

### PR DESCRIPTION
**Pull request by sabrinajess**
Re: [CNV-16875](https://issues.redhat.com/browse/CNV-16875)
For 4.6 and later
Preview: https://deploy-preview-43356--osdocs.netlify.app/openshift-enterprise/latest/virt/live_migration/virt-configuring-vmi-eviction-strategy.html#virt-configuring-vm-live-migration-cli_virt-configuring-vmi-eviction-strategy

### CODE REVIEW

**Review by sarahbx — APPROVED** [review]
lgtm 👍

**Comment by ousleyp** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@ousleyp Looks like the CPs to 4.6-4.8 failed, can you submit the manual CP soon please?

**Pull request merged**
