### PR TITLE
[OCPBUGS44653] Sync IBM Z file names

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.17+

Issue: https://issues.redhat.com/browse/OCPBUGS-44653

Link to docs preview:
- [Preparing to install on IBM Z ](https://84597--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/preparing-to-install-on-ibm-z)
-  [Configuring additional devices in an IBM Z or IBM LinuxONE environment](https://84597--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/ibmz-post-install)
- [Deploying hosted control planes on IBM Z](https://84597--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-deploy/hcp-deploy-ibmz)

QE review:
- [ NA no content change] QE has approved this change.

Additional information:

I didn't change names/ids in the following files since they show up in the _topic_map.yml:  
- ibmz-post-install
- hcp-deploy-ibmz
- disconnected-install-ibmz-hcp
- hcp-destroy-ibmz

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
The changes to the HCP files look good to me.

**Review by michaelryanpeter — COMMENTED** [review]
I left a couple of nits about not needing to add an `id` to trailing include additional references sections.

Otherwise, LGTM.

/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed

**Pull request merged**
