### PR TITLE
OSDOCS-2869 - Migrating common SD files in the Support book

### PR DESCRIPTION
**Pull request by pneedle-rh**
**Please do not merge this PR. After the `dedicated-4` freeze, we can check if any further updates are made to the corresponding files in `dedicated-4`. If so, we might need to add that content in further conditionals in this PR before we merge it. It will also be easier to add the scripted PR for the common files before we merge this one. Thanks!**

This applies to `main`, `enterprise-4.9` and `enterprise-4.10`.

The PR relates to https://issues.redhat.com/browse/OSDOCS-2869.

This pull request is part of the OSD and ROSA docs migration to the mainstream branches. The PR migrates the assembly, module and image files in the Support book (and related) that are commonly live in the `dedicated-4` branch and `main`, `enterprise-4.9` and `enterprise-4.10`.

There are a separate set of assemblies and modules for the ROSA Support book and none of those files are currently included in the mainstream branches. This is why the conditionals that are added in this PR only relate to `openshift-dedicated` and not `openshift-rosa`.

The automatically generated preview will not show the OSD build that uses the conditionals that are added in this PR, until the main migration PR is merged and multiple topic maps are possible. The main migration PR will be generated after `dedicated-4` is frozen.

For the purposes of reviewing this PR, I built a local test branch that will be very similar to the main migration feature branch and added the commit in this Support book PR to that branch. I used the branch to generate a local preview of the Support books for OCP and OSD that will be very similar to the migrated build:

- [The openshift-enterprise Support book preview is available here](http://people.redhat.com/pneedle/pr_38900_previews/openshift-enterprise/support/getting-support.html).
- [The openshift-dedicated Support book preview is available here](http://people.redhat.com/pneedle/pr_38900_previews/openshift-dedicated/support/getting-support.html).

Please let me know if you need previews for any other distributions. Thanks!

### CODE REVIEW

**Comment by pneedle-rh** [comment]
It might be useful me to highlight that I left the existing `{product-version}` entries in the common Support book files in `main`, in this PR. They should hopefully get silently dropped in the Netlify preview when we merge the migration PRs. This is the case in the  OSD docs in `dedicated-4` today, which also include most of the same `{product-version}` references in the Support book. 

In the distro map, the version is stated as `''` for `openshift-dedicated` in main. In the following code snippet, the name field relates to the version, I think:

```
    dedicated-4:
      name: ''
      dir: dedicated/
```

I think it's easier to just leave the version references as they are in `main`, rather than add `ifdef` conditionals for `openshift-dedicated` to remove all references to `{product-version}` in the commonly shared files for that distribution.

I've made a note to check if the version references are dropped in the OSD build after we merge the migration PRs.

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
