### PR TITLE
Added a section about inclusive language to the 4.7 release notes

### PR DESCRIPTION
**Pull request by ahardin-rh**
@vikram-redhat @sjstout PTAL. Thank you!

Preview build: https://inclusive-language--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-inclusive-language

### CODE REVIEW

**Comment by mbearer** [comment]
I think we should seek ack from Eng and PM as well. 
Please take a look @nstielau @mpbarrett

**Comment by sjstout** [comment]
LGTM!

**Comment by vikram-redhat** [comment]
lgtm

**Comment by ahardin-rh** [comment]
Received approval from Mike Barrett via Slack.

**Pull request merged**
