### PR TITLE
OSDOCS-3616

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-3616](https://issues.redhat.com//browse/OSDOCS-3616)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-3616

Link to docs preview:
ROSA: https://56740--docspreview.netlify.app/openshift-rosa/latest/rosa_cli/rosa-manage-objects-cli.html#rosa-install-addon_rosa-managing-objects-cli

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @yuwang-RH! When you have a moment, can you please take a look at this PR? Thank you!

**Comment by yuwang-RH** [comment]
LGTM~

**Review by arendej — APPROVED** [review]
lgtm, thanks

**Comment by eohartman** [comment]
Great job, @jneczypor !

**Pull request merged**
