### PR TITLE
Added a warning that recycle policy is being deprecated.

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://trello.com/c/V4i1uj8D/488-document-deprecate-recycle-function-starting-ose-36

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
[Document: Deprecate Recycle function starting OSE 3.6](https://trello.com/c/V4i1uj8D/488-document-deprecate-recycle-function-starting-ose-36)

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :car:

**Comment by childsb** [comment]
lgtm

**Pull request merged**
