### PR TITLE
bug 1713662 installer promts for AWS creds

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1713662

@wking, FYI

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, will you PTAL? QE's approved the change.

**Comment by mburke5678** [comment]
@kalexand-rh LGTM

**Comment by kalexand-rh** [comment]
Thanks @mburke5678! Merging.

**Comment by wking** [comment]
Late to the party, but all except for the "promts" title looks good to me ;)

**Pull request merged**
