### PR TITLE
Added optimizing storage content

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview build: http://file.rdu.redhat.com/~ahardin/12192018/optimizing-storage/storage/optimizing-storage.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sjug I think you're reviewing this section of the docs? Anyway, here it is, although a WIP  :tada:

**Comment by sjug** [comment]
Seems good so far, will need to check with the containers team to see if there's *any* specific tunings or optimizations to be had now.

**Comment by ahardin-rh** [comment]
@sjug Thank you! Let me know if you'd like me to reach out to the containers team directly.

**Comment by ahardin-rh** [comment]
Note to self :writing_hand: Still need to set the definitions of {gluster-native}/{gluster-external} in the footnotes

**Comment by ahardin-rh** [comment]
@sjug Any word from the containers team?

**Comment by ahardin-rh** [comment]
I need to apply minor edits from here too https://github.com/openshift/openshift-docs/pull/13249/files

**Comment by sjug** [comment]
@ahardin-rh Sorry I missed your ping from yesterday. There aren't any performance related tunings for CRI-O that I've heard of regarding storage.

**Comment by ahardin-rh** [comment]
@sjug Thanks! I applied the latest changes. Is this okay to merge? :steam_locomotive:

**Pull request merged**
