### PR TITLE
Making changes to the scheduler doc based on feedback

### PR DESCRIPTION
**Pull request by abhgupta**
@thoraxe PTAL

### CODE REVIEW

**Comment by adellape** [comment]
@abhgupta BTW, I was planning on moving this topic from the `dev_guide` dir to `admin_guide`. Feel free to do so in this PR if you wish, else I will after this merges.

**Comment by abhgupta** [comment]
@adellape Feel free to review and merge. We can always get inputs/changes into it later based on feedback from @thoraxe

**Comment by abhgupta** [comment]
@adellape Can you please look at this error?

In /home/travis/build/openshift/openshift-docs/_build_cfg.yml, could not find file scheduler under directory dev_guide for topic Scheduler in topic group Developer Guide.

**Comment by adellape** [comment]
@abhgupta Looks like you got it. :]

**Pull request merged**
