### PR TITLE
Terraform Post-Merge Clean-up

### PR DESCRIPTION
**Pull request by EricPonvelle**
This PR captures the missed feedback for #77311 

- Updates to the cluster overview:
  - **[Creating ROSA with HCP clusters using the default options](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-hcp-sts-creating-a-cluster-quickly)**
      image
  - **[Creating a default ROSA with HCP cluster using Terraform](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-hcp-creating-a-cluster-quickly-terraform)**
      image
  - **[Creating a ROSA cluster with STS using the default options](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-sts-creating-a-cluster-quickly)**
      image
      image
  - **[Creating a default ROSA (classic architecture) cluster using Terraform](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/terraform/rosa-classic-creating-a-cluster-quickly-terraform.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-classic-creating-a-cluster-quickly-terraform)**
    image
    image
- Additional resource updates:
  - **[ROSA with HCP](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.html#additional-resources_rosa-hcp-creating-a-cluster-quickly-terraform)**
  - **[ROSA with classic architecture](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/terraform/rosa-classic-creating-a-cluster-quickly-terraform.html#additional-resources_rosa-classic-creating-a-cluster-quickly-terraform)**

### CODE REVIEW

**Comment by EricPonvelle** [comment]
@radtriste and @andyrepton - can you two review this PR that caught the items that I missed in #77311? Thank you!

**Comment by EricPonvelle** [comment]
@radtriste in this comment, you mentioned these two items:

> Some cluster specifications has no sense in HCP, like:
> 
> Control plane node configuration component
> Infrastructure plane node configuration component
> ~~Cluster settings -> Default EC2 IMDS endpoints~~
> ~~Encryption -> No KMS key encryption by default~~

Would I remove those two rows from the overview sections on the HCP guides?

**Comment by radtriste** [comment]
> @radtriste in this comment, you mentioned these two items:
> 
> > Some cluster specifications has no sense in HCP, like:
> > Control plane node configuration component
> > Infrastructure plane node configuration component
> > ~Cluster settings -> Default EC2 IMDS endpoints~
> > ~Encryption -> No KMS key encryption by default~
> 
> Would I remove those two rows from the overview sections on the HCP guides?

In HCP, we do not have those CP and Infrastucture nodes as they are managed by Red Hat, we only have the compute nodes.
Where do you mean with ` overview sections on the HCP guides` ?

**Comment by EricPonvelle** [comment]
@radtriste, the way we structured `rosa-sts-overview-of-the-default-cluster-specificiations.adoc` is that it shows differently depending on the context. In HCP, we show it like this for [the normal installation method](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-hcp-sts-creating-a-cluster-quickly) and [like this for Terraform](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-hcp-creating-a-cluster-quickly-terraform).

In the classic guides, you can see the CP and Infrastructure nodes on the same table [if you use the normal installation guide](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-sts-creating-a-cluster-quickly) or [if you use the Terraform guide](https://78211--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/terraform/rosa-classic-creating-a-cluster-quickly-terraform.html#rosa-sts-overview-of-the-default-cluster-specifications_rosa-classic-creating-a-cluster-quickly-terraform).

I'm not sure if I clarified or muddled things...

**Comment by kcarmichael08** [comment]
I think I was able to follow the different flavors and check that everything appearing is what is supposed to/not supposed to. Tricky - nice job with parsing that! LGTM peer review wise.

**Pull request merged**
