### PR TITLE
[RHACS] ROX-19225: Updating architecture module to reflect scanner-slim

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.1, 4.2

Issue:
https://issues.redhat.com/browse/ROX-19225

Link to docs preview:

SME review:
- [x] SME has approved this change.

Additional information:
Merge into `rhacs-docs` and cherry-pick into:
- `rhacs-docs-4.2`
- `rhacs-docs-4.1`

### CODE REVIEW

**Comment by agantony** [comment]
@dcaravel Requesting review and approval, thx!

**Review by dcaravel — APPROVED** [review]
/LGTM

**Pull request merged**
