### PR TITLE
OCPBUGS#27181 Correct the RHCOS version in 4.14 RNs

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.14

Issue: [OCPBUGS-27181](https://issues.redhat.com/browse/OCPBUGS-27181)

Link to docs preview: [Preview](https://70300--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-about-this-release)

QE review:
- [X] QE has approved this change.

Additional information: Kathryn approved this change and said it doesn't need change management.

### CODE REVIEW

**Review by mffiedler — APPROVED** [review]
LGTM

**Comment by rh-tokeefe** [comment]
Hi @cbippley the change itself LGTM. 

I see the PR has been QA reviewed. I'm not sure it has an SME approval. 

If this change applies to release notes content that was previously published, does it have to go through the [change management process](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit?pli=1#heading=h.nckpao8upx1u)?

@bburt-rh as my OCP review onboarding buddy, please review the PR and let me know if there is anything I missed.

**Comment by cbippley** [comment]
I asked Kathryn and they said it doesn't need change management. The error was pointed out by an SME on [this PR](https://github.com/openshift/openshift-docs/pull/70294#discussion_r1452726477).

**Review by bburt-rh — APPROVED** [review]
Thanks @rh-tokeefe - Good catch on the possible need for change management. SME approval is always optional, btw. It's at the writer's discretion whether to get a SME to look at the PR. Thanks!

@cbippley - Just a suggestion, but consider adding a note to the description that Kathryn said that this doesn't require change management. When I do something that might require change management, I'll usually make a note of the status in the PR description so that reviewers will know where the PR stands wrt that process. Thanks!

LGTM

**Review by skrthomas — COMMENTED** [review]
Merge review lgtm

**Pull request merged**
