### PR TITLE
Removed Serverless monitoring docs for GA

### PR DESCRIPTION
**Pull request by abrennan89**
Applies for OCP 4.3+
Please do not merge until requested.

### CODE REVIEW

**Comment by maschmid** [comment]
QE approved

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by lamek** [comment]
To 4.4
https://github.com/openshift/openshift-docs/pull/21613

To 4.3
https://github.com/openshift/openshift-docs/pull/21614

**Pull request merged**
