### PR TITLE
Add --from-file to create secret

### PR DESCRIPTION
**Pull request by juanluisvaladas**
A customer faced that this command, with --from-file it works fine. According to the docs of oc create secret generic it should include the --from-file.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@soltysh, @zhaozhanqi, PTAL? I think this change is valid back to 3.9. Do you agree?

**Comment by juanluisvaladas** [comment]
I agree with 3.9.

**Review by soltysh — APPROVED** [review]
This is correct all the way back to 3.9.
/lgtm

**Comment by kalexand-rh** [comment]
Thanks @soltysh! I'm going to merge. (@zhaozhanqi, if you disagree, I'll be happy to revert.)

**Pull request merged**
