### PR TITLE
[enterprise-4.16] OSDOCS-9735: add RN entry

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/OSDOCS-9735

Link to docs preview: https://77427--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-iscsi-support_release-notes

QE review:
- [x] QE has approved this change.

Additional information: xrefs will fail, content PR: #77275

### CODE REVIEW

**Comment by jldohmann** [comment]
@HuijingHei PTAL for QE ack, this is the release note entry for iSCSI support. thank you 🙇

**Review by HuijingHei — APPROVED** [review]
/lgtm

**Comment by jldohmann** [comment]
@HuijingHei for release note entries, they get opened against their respective release branch 😄

**Pull request merged**
