### PR TITLE
Bug 1428139 Follow up to PR-4004

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
Incorporating @ahardin-rh 's comments from [4004](https://github.com/openshift/openshift-docs/pull/4004).

**Comment by mburke5678** [comment]
@ahardin-rh PTAL!

**Comment by ahardin-rh** [comment]
@mburke5678 LGTM! :rocket:

**Comment by mburke5678** [comment]
%
[rev_history]
|xref:../install_config/registry/deploy_registry_existing_clusters.adoc#install-config-deploy-registry-existing-clusters[Setting Up a Registry -> Deploying a Registry on Existing Clusters]|Added list of supported registry storage drivers to the xref:../install_config/registry/deploy_registry_existing_clusters.adoc#storage-for-the-registry[Storage for the Registry] section.
%
|xref:../install_config/registry/extended_registry_configuration.adoc#install-config-registry-extended-configuration[Setting Up a Registry -> Extended Registry Configuration]|Updated the list of supported registry storage drivers in the xref:../install_config/registry/extended_registry_configuration.adoc#docker-registry-configuration-reference-storage[Storage] section.
%

**Comment by ahardin-rh** [comment]
@mburke5678 In revision histories, there needs to be a new line between the first | and the second | so it should be like this, for example:
|xref:../install_config/registry/deploy_registry_existing_clusters.adoc#install-config-deploy-registry-existing-clusters[Setting Up a Registry -> Deploying a Registry on Existing Clusters]
|Added list of supported registry storage drivers to the xref:../install_config/registry/deploy_registry_existing_clusters.adoc#storage-for-the-registry[Storage for the Registry] section.

**Pull request merged**
