### PR TITLE
OBSDOCS-332 - Logging 5.5.13 Release Notes

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.10, 4.11, 4.12

Issue: [OBSDOCS-332](https://issues.redhat.com//browse/OBSDOCS-332) 

Link to docs preview: https://62327--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging-release-notes.html#cluster-logging-release-notes-5-5-13_cluster-logging-release-notes-v5x

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by periklis — COMMENTED** [review]
LGTM

**Review by gwynnemonahan — APPROVED** [review]
lgtm

**Comment by Preeticp** [comment]
Manual CP PRs are being created for each of the branches.

**Comment by kalexand-rh** [comment]
Only versions 4.11+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Pull request closed without merging**
