### PR TITLE
Fix changes - RHDEVDOCS-6142

### PR DESCRIPTION
**Pull request by hemantkumarc**
Version(s):
I am not sure which version of OpenShift this particular PR applies to. Please help me out here.

Issue:
The link to the issue is here - [RHDEVDOCS-6142](https://issues.redhat.com/browse/RHDEVDOCS-6142)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
I have changed the content in the documentation as presented in [RHDEVDOCS-6142](https://issues.redhat.com/browse/RHDEVDOCS-6142)

### CODE REVIEW

**Comment by hemantkumarc** [comment]
@openshift/team-documentation. 
Can you please review this PR.

**Comment by hemantkumarc** [comment]
@openshift-ci-robot /joke

**Comment by hemantkumarc** [comment]
@openshift-bot /joke

**Comment by hemantkumarc** [comment]
@openshift-ci-robot /joke

**Comment by eromanova97** [comment]
Great job! 
/lgtm

**Comment by eromanova97** [comment]
I answered the question regarding the versions here: 
https://issues.redhat.com/browse/RHDEVDOCS-6142?focusedId=25610854&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25610854

You can add it as following:
Version(s): `pipelines-docs-1.14`, `pipelines-docs-1.15`, `pipelines-docs-1.16`

**Comment by eromanova97** [comment]
And just one small comment. Please list the preview in the first comment. The preview got generated by the ocpdocs-previewbot here:
https://github.com/openshift/openshift-docs/pull/81609#issuecomment-2358274973

So please add the following:
Link to docs preview: https://81609--ocpdocs-pr.netlify.app/openshift-pipelines/latest/tkn_cli/op-tkn-reference.html#op-tkn-pipeline-management_op-tkn-reference

**Comment by eromanova97** [comment]
Hello @hemantkumarc I noticed an issue. Your changes are correct, however, I see you raised the PR against `pipelines-docs-main`, which is correct, however, you need to create your feature branch from the `pipelines-docs-main` (usually done by `git checkout -b <name_of_your_feature_branch>`. Please refer to the git instructions we provided you to see how to create this feature branch. Then you will have to raise this PR again. 

All the changes are correct, so you can just make the same changes :slightly_smiling_face: just on your feature branch.

**Pull request closed without merging**
