### PR TITLE
Updated CAM web console URL command

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1828696

Updated procedure and added example of CAM console URL

CP for 4.2, 4.3, 4.4, 4/5

### CODE REVIEW

**Comment by apinnick** [comment]
@XinRedhat Ready for QE

**Comment by XinRedhat** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
