### PR TITLE
Resolving BZ1756209 - Additional reorg of topics

### PR DESCRIPTION
**Pull request by bgaydosrh**
Reorganizing and renaming from suggestions in https://bugzilla.redhat.com/show_bug.cgi?id=1756209

Test Build is here:
http://file.bos.redhat.com/bgaydos/100819/cnv/cnv_users_guide/cnv-accessing-vm-consoles.html

Please label for Enterprise-4.2.

Peer review needed from either @mburke5678 @huffmanca or @kalexand-rh 

Thanks,

Bob

### CODE REVIEW

**Comment by mburke5678** [comment]
@bgaydosrh LGTM. Need a Merge and CP?

**Comment by bgaydosrh** [comment]
> @bgaydosrh LGTM. Need a Merge and CP?

Thanks Michael,

I'm going to let @alexxa approve first and then we can merge. This one had a few go-arounds and i want to make sure it's right.

Will notify when ready to merge and pick. Appreciate your help! :-)

Bob

**Comment by alexxa** [comment]
@bgaydosrh when I open that test build link, I don't see the update proposed in this PR.

**Comment by bgaydosrh** [comment]
> @bgaydosrh when I open that test build link, I don't see the update proposed in this PR.

Sorry, I pasted the wrong link. I overwrote the correct link by accident.
Here is the good link: http://file.bos.redhat.com/bgaydos/100919/cnv/cnv_users_guide/cnv-accessing-vm-consoles.html

**Review by alexxa — APPROVED** [review]

**Pull request merged**
