### PR TITLE
BZ1897654: Deleting migration controller operands for CAM 1.2 upgrade

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1897654

CP to 4.5, 4.6, 4.7

### CODE REVIEW

**Review by sergiordlr — APPROVED** [review]
Looks good to me,

Thank you very much!

**Review by pneedle-rh — COMMENTED** [review]
@apinnick I have added a couple of minor comments. Aside from those, this looks good to me!

**Comment by apinnick** [comment]
@pneedle-rh  PR updated. I will open a separate PR for other instances of migration controller.

**Comment by pneedle-rh** [comment]
> @pneedle-rh PR updated. I will open a separate PR for other instances of migration controller.

@apinnick LGTM!

**Comment by apinnick** [comment]
@pneedle-rh  Still waiting for you to merge this.

**Comment by pneedle-rh** [comment]
@apinnick thank you for your message!

My apologies, I am still in the process of learning when to merge PRs after peer review and when to leave it to the writer. I will merge this one now and will make a note to merge your PRs in future.

**Comment by apinnick** [comment]
@pneedle-rh  I do not have merge rights because I am not an OpenShift writer. If you happen to notice that someone never attends your team meetings, that's a pretty good indication that they do not have merge rights to this repo.

**Comment by pneedle-rh** [comment]
@apinnick I have now merged this PR and cherry picked to 4.5, 4.6 and 4.7.

We have also now added a step to our peer review checklist to determine whether a merge is required as part of a peer review.

Thanks for your contribution!

**Pull request merged**
