### PR TITLE
Adding Known Issue to 1.5 RN for kernel taint warning

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OCPBUGS-29826
Link to docs preview:

- [1.5 Known Issues](https://72349--ocpdocs-pr.netlify.app/openshift-enterprise/latest/network_observability/network-observability-operator-release-notes#network-observability-operator-1.5.0-known-issue)
- [1.4 Known Issues](https://72349--ocpdocs-pr.netlify.app/openshift-enterprise/latest/network_observability/network-observability-operator-release-notes#network-observability-operator-1.4.0-known-issues)
- [1.3 Known Issues](https://72349--ocpdocs-pr.netlify.app/openshift-enterprise/latest/network_observability/network-observability-operator-release-notes#network-observability-operator-1.3.0-known-issues)
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by jpinsonneau — APPROVED** [review]

**Review by mcurry-rh — APPROVED** [review]

**Comment by shipsing** [comment]
LGTM, @skrthomas
 
/label peer-review-done

**Pull request merged**
