### PR TITLE
SRVKS-812 + SRVKS-813 + SRVKS-820: Update domainmapping docs and add deprecation notes

### PR DESCRIPTION
**Pull request by abrennan89**
Jira issues:
- Adds Security section as per https://issues.redhat.com/browse/SRVKS-820
- https://issues.redhat.com/browse/SRVKS-812
- https://issues.redhat.com/browse/SRVKS-813

Applies for OCP 4.6+

Direct preview links:
- Moved to Security section:
  - https://deploy-preview-37123--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-ossm-with-kourier-jwt.html
  - https://deploy-preview-37123--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-custom-domains.html **(updated content to emphasize using domain mapping)**
  - https://deploy-preview-37123--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-ossm-tls-with-kourier.html **(deprecated note added)**
  - New section: https://deploy-preview-37123--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-custom-tls-cert-domain-mapping.html

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
/lgtm

Thank you!

**Review by mikemckiernan — COMMENTED** [review]
nits and mod docs comments from me.

I don't think it's part of the review, but I'll point it out in case it is and I missed it.  The IMPORTANT admonition at the top of the [Configuring JSON Web Token authentication for Knative services](https://deploy-preview-37123--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-ossm-with-kourier-jwt.html) page says that customers must set an annotation to use the readiness probe.   I think the first procedure that follows shows how to configure the annotation, but the config is Optional.  Just sharing that an admonition with "must" and the optional config have varying tones.

**Review by mikemckiernan — COMMENTED** [review]
two more nits.  Very sorry to have wasted your time by not noticing these previously.

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

Thanks for your time, help, and patience.

**Pull request merged**
