### PR TITLE
OSDOCS#9513: Hosted control planes: Update the welcome page

### PR DESCRIPTION
**Pull request by xenolinux**
The PR updates the welcome page with new hosted control planes tech preview feature and RHACM links

Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OSDOCS-9513

Link to docs preview: https://73771--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/#hosted-control-plane-activities

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by JoeAldinger** [comment]
@xenolinux this may need change management since it is updating a TP feature post GA. Could you check with cc @kalexand-rh

**Pull request merged**
