### PR TITLE
Commented out Adding New etcd Hosts section per BZ

### PR DESCRIPTION
**Pull request by ahardin-rh**
Removing section per https://bugzilla.redhat.com/show_bug.cgi?id=1405338#c12

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vikram-redhat PTAL

**Comment by vikram-redhat** [comment]
@ahardin-rh looks good. Need to keep track of https://github.com/openshift/openshift-ansible/issues/1772.

**Comment by ahardin-rh** [comment]
No revision history needed

**Comment by mffiedler** [comment]
@ahardin-rh @vikram-redhat Coincidentally, I was just working on a pull request to add the missing steps since I went through this procedure myself.   Should I proceed with the PR?  Or you want to leave the section out?   I think it is an important procedure if we have it correct.

**Comment by ahardin-rh** [comment]
@mffiedler If you can help us with correct steps, that would be great! We only commented them out for now since what we had was incorrect and causing issues.

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
