### PR TITLE
Replace instances of $ oc rsh <pod_ID> with $ oc rsh <pod>

### PR DESCRIPTION
**Pull request by ahardin-rh**
This work is related to https://bugzilla.redhat.com/show_bug.cgi?id=1333465 and the discussion in https://github.com/openshift/openshift-docs/pull/2107.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@xingxingxia This is follow-up per our discussion in https://github.com/openshift/openshift-docs/pull/2107. This is the only other instance of `*$ oc rsh <pod_ID>*` I could find. Please review. Thanks!

**Comment by xingxingxia** [comment]
@ahardin-rh Thank you.
In https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html, search "_id" (case insensitive), there are 19 occurrences.
I have examined: for each of them, the "_id" could be safely removed, including container_ID, _port_ID. And I found: for the same thing, there are object_type_name, object_id, object_name_or_id. This is not consistent. Could use one consistent word: object_name.
BTW, for 'oc port-forward', better to change <first_port_ID> <second_port_ID> to local_port:remote_port, (see oc port-forward -h) because the two ports are on different hosts, this is semantically proper.

**Comment by ahardin-rh** [comment]
@xingxingxia Updates complete. Please review and let me know if I missed anything.

**Comment by ahardin-rh** [comment]
@bfallonf @adellape @tnguyen-rh @tpoitras peer review?

 Also, just a general heads-up regarding these comments from @xingxingxia and how we should avoid "_ID" in our writing (for example, <pod_ID>, <port_ID>, etc.) Also, note the comment on object_type_name, object_id, object_name_or_id. These should all just be a consistent object_name. Thanks!

**Comment by tnguyen-rh** [comment]
@ahardin-rh LGTM.

**Comment by bfallonf** [comment]
@ahardin-rh LGTM

**Comment by xingxingxia** [comment]
@ahardin-rh Thanks. Just a minor point:
For `oc proxy --port=`,  the port is indeed a number, so please use \<port\> ('_name' seems to indicate a string).
BTW, I see pod_ID, container_ID are changed to pod_name, container_name. Though this looks good, there is one `oc rsh \<pod\>`. How about keeping consistent too, either all use \<pod\>, or all use \<pod_name\> (I prefer \<pod\>. \<container_name\> could be \<container\> too. E.g. usage in `oc exec -h`)
The rest LGTM.

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../cli_reference/basic_cli_operations.html[Developer CLI Operations]
|Replace instances of `oc rsh <pod_ID>` with `oc rsh <pod>` and fixed other formatting.
%

**Pull request merged**
