### PR TITLE
Adding information about reference for image stream tags and about dockerimage pointed tags

### PR DESCRIPTION
**Pull request by soltysh**
This is dependent on https://github.com/openshift/origin/pull/4853

@miminar for technical review
@adellape for usefulness review :wink:

### CODE REVIEW

**Comment by soltysh** [comment]
I've tagged it with do not merge until the aforementioned PR got merged.

**Comment by miminar** [comment]
:thumbsup:

**Comment by soltysh** [comment]
@adellape it's green for merge.

**Comment by adellape** [comment]
LGTM

**Comment by vikram-redhat** [comment]
Doesn't require a followup.

**Pull request merged**
