### PR TITLE
OSDOCS-2656: Adding section about Uninstalling the Compliance Operator

### PR DESCRIPTION
**Pull request by kmccarron-rh**
https://issues.redhat.com/browse/OSDOCS-2656
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=2005387

Direct link to new section: 
https://deploy-preview-37650--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-uninstallation

Affected version(s): 4.6+

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
/lgtm

**Review by adellape — APPROVED** [review]

**Pull request merged**
