### PR TITLE
OCPBUGS#5307 Adding Java-based Operator to developer task list

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.11 and 4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-5307

Link to docs preview:
https://54396--docspreview.netlify.app/openshift-enterprise/latest/operators/index.html#operators-overview-developer-tasks

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
LGTM.
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by jldohmann — APPROVED** [review]

**Pull request merged**
