### PR TITLE
OCPBUGS#5962:Add cloning support to GCP CSI driver

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-5962

Link to docs preview: https://64670--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi#csi-drivers-supported_persistent-storage-csi

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @duanwei33, @gcharot, @jsafrane, @sferich888, @xltian, @mwerner2113

### CODE REVIEW

**Comment by jab-rh** [comment]
@lpettyjo, LGTM, thanks!

**Comment by kalexand-rh** [comment]
@duanwei33, will you please confirm this change?

**Comment by duanwei33** [comment]
Hi all, QE have verified GCP PD CSI Driver supports Clone feature from 4.11 and it is already covered in CI.

**Comment by xltian** [comment]
LGTM.

**Comment by gcharot** [comment]
LGTM

**Comment by jsafrane** [comment]
lgtm

**Pull request merged**
