### PR TITLE
OCP 4.11 Netobserv updates RN

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

OCP 4.11 release notes
Issue:

Link to docs preview:

https://59415--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#new-network-observability

QE review:
- [ ] QE has approved this change.

Additional information:

This PR creates a small announcement of Network Observability in the big OpenShift Container Platform documentation release notes. It doesn't include specifics, but rather points to the Operator release notes.

### CODE REVIEW

**Comment by skrthomas** [comment]
@mcurry-rh Can you PTAL at this release notes addendum to the OCP release notes. Basically just creating a link to the Network Observability release notes, so customers can know that the Operator releases on a different cadence and where to find the updates.

**Review by nathan-weinberg — COMMENTED** [review]
/label qe-approved

**Comment by jotak** [comment]
There must have been a problem when creating this PR, no? There's a lot of commits that are unrelated

**Review by kelbrown20 — COMMENTED** [review]
Looks great! 
/lgtm

**Comment by skrthomas** [comment]
> There must have been a problem when creating this PR, no? There's a lot of commits that are unrelated

Yeah there was a problem. I somehow pulled in a lot of commits and I'm not sure how I did it. I think it's squared away now though.

**Pull request merged**
