### PR TITLE
OBSDOCS-611: Updating _content-type to _mod-docs-content-type

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.16, 4.15, 4.14, 4.13, 4.12, 4.11

Issue:

https://issues.redhat.com/browse/OBSDOCS-611

Link to docs preview:

This is a metadata change.
The other file is a typo fix.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by max-cx** [comment]
label/ peer-review-needed

**Comment by max-cx** [comment]
label/ peer-review-needed

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done
/lgtm

**Pull request merged**
