### PR TITLE
TELCODOCS-1869 -  CNF-11995 MetalLB: configurable BGP connect time (GA)

### PR DESCRIPTION
**Pull request by slovern**
[TELCODOCS-1869](https://issues.redhat.com//browse/TELCODOCS-1869) - [CNF-11995](https://issues.redhat.com//browse/CNF-11995) MetalLB: configurable BGP connect time (GA)

Version(s): 4.17

Issue: https://issues.redhat.com/browse/TELCODOCS-1869

Link to docs preview: [About the BGP peer custom resource](https://80280--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-configure-bgp-peers.html#nw-metallb-bgppeer-cr_configure-metallb-bgp-peers)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by gkopels — APPROVED** [review]

**Comment by gkopels** [comment]
lgtm

**Comment by slovern** [comment]
label peer-review-needed

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by kowen-rh** [comment]
@slovern Can you please update the description of the PR to show the documentation preview and QE approval status? :slightly_smiling_face:

**Comment by slovern** [comment]
thanks for the review @kowen-rh

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
