### PR TITLE
Update the current version of Kubernetes

### PR DESCRIPTION
**Pull request by php-coder**
The latest version of OpenShift uses Kubernetes 1.7 for some time already.

PTAL @simo5 @openshift/team-documentation

### CODE REVIEW

**Comment by mburke5678** [comment]
@php-coder This change is for 3.6 only? And, we are using Kubernetes 1.**7** and not 1.**6**?

**Comment by php-coder** [comment]
@mburke5678 This change is for the current state of `master` branch (for the next release). In 3.6 there should be Kubernetes 1.6

**Comment by mburke5678** [comment]
@php-coder In the 3.6, we list Kubernetes 3.5:
https://docs.openshift.com/container-platform/3.6/architecture/infrastructure_components/kubernetes_infrastructure.html
https://docs.openshift.org/latest/architecture/infrastructure_components/kubernetes_infrastructure.html
"

"OpenShift Origin uses Kubernetes 1.5 and Docker 1.12."

So, we need to change 3.6 to 1.6 immediately, and 3.7 to 1.7 for the next release?

**Comment by php-coder** [comment]
> So, we need to change 3.6 to 1.6 immediately, and 3.7 to 1.7 for the next release?

@mburke5678 Yes, that's right.

See also: https://docs.openshift.com/container-platform/3.6/release_notes/ocp_3_6_release_notes.html#ocp-36-kubernetes-upstream

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL to make sure this has correct milestone and label?

**Comment by bfallonf** [comment]
@mburke5678 LGTM

**Comment by mburke5678** [comment]
@vikram-redhat PTAL at labelling as discussed.

**Comment by vikram-redhat** [comment]
@mburke5678 - thanks! Although there seem to be a conflict now. Might need a rebase.

**Comment by mburke5678** [comment]
No rev history required.

**Comment by vikram-redhat** [comment]
@mburke5678 - not sure what has happened here, but:

a) There are two commits
b) The second commit is a merge commit that merges **master** into php-coder's branch and adds changes more than what was in the original work. Also the second commit seems to have been done via the web interface. Not sure how this all worked.

I am reverting this commit and manually adding the changes required for this.

**Comment by mburke5678** [comment]
@vikram-redhat Not sure what happened. I looked at the second commit and the message at the top says it merged into master from php-coder. 
_mburke5678 merged 2 commits into openshift:master from php-coder:fix_k8s_version 26 days ago_  

The Kubernetes version is correct. 
https://docs.openshift.com/container-platform/3.6/architecture/infrastructure_components/kubernetes_infrastructure.html

I don't know how to commit via the Web interface.

**Comment by vikram-redhat** [comment]
@mburke5678 perhaps when you did a rebase: https://github.com/openshift/openshift-docs/pull/5104#issuecomment-325527667 there was a mistake?

**Pull request merged**
