### PR TITLE
RHDEVDOCS-6137: Minor changes in the GitOps 1.12.2 RN

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.12, GitOps 1.13, GitOps 1.14

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6137

Link to docs preview:

[New features section in the GitOps 1.12.2 Release Notes](https://79917--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes#new-features-1-12-2_gitops-release-notes)

QE review:
- [x] QE has approved this change.

SME review: @jgwest 
QE review: @varshab1210 
Peer review: @GroceryBoyJr 

Additional information:

### CODE REVIEW

**Review by jgwest — APPROVED** [review]
LGTM, thanks @Dhruv-Soni11!

**Comment by varshab1210** [comment]
LGTM, thanks

**Comment by stevsmit** [comment]
Peer review was not finished by @GroceryBoyJr .

@Dhruv-Soni11 Please do not add the peer-review-done label yourself. A member of the peer review team will add this label only after they have completely finished their review.

**Comment by Dhruv-Soni11** [comment]
> Peer review was not finished by @GroceryBoyJr .
> 
> @Dhruv-Soni11 Please do not add the peer-review-done label yourself. This label is required to be added by members of the OpenShift Docs "Peer Review" team--not QE or SMEs. A member of the peer review team will add this label only after they have completely finished their review to check for style guide errors, etc.
> 
> I added the do-not-merge label until James confirms the peer review has been done.
> 
> Thanks!

Hey @stevsmit - I have never added the said label myself before as I know that as per process it is the peer-reviewer's responsibility. I thought in this instance that the reviewer has forgotten to add the required label. I think it was a simple misunderstanding. Thanks.

**Pull request merged**
