### PR TITLE
Added another two item to the list of information Insights Operator collects

### PR DESCRIPTION
**Pull request by mmuehlfeldRH**
@openshift/team-documentation
This update applies to OpenShift 4.5.

### CODE REVIEW

**Comment by martinkunc** [comment]
ACK
Thank you Marc !

**Comment by jboxman** [comment]
@mmuehlfeldRH, can you replace _OpenShift_ with _{product-title}_? Thanks!

**Comment by mmuehlfeldRH** [comment]
> @mmuehlfeldRH, can you replace _OpenShift_ with _{product-title}_? Thanks!

@jboxman done.

**Comment by jboxman** [comment]
@mmuehlfeldRH, does this apply to 4.6 as well? Thanks!

**Comment by mmuehlfeldRH** [comment]
> @mmuehlfeldRH, does this apply to 4.6 as well? Thanks!

@jboxman , yes. This is a change introduced in 4.5 and applies to future versions as well.

**Pull request merged**
