### PR TITLE
[HCCDOC#1628]: Clarify that Insights recommendations are based on a set…

### PR DESCRIPTION
**Pull request by kblake2016**
… of conditional rules

- Update paragraph to better explain the meaning of "conditions".

Version(s): 4.11+

Issue: https://issues.redhat.com/browse/HCCDOC-1628

Link to docs preview: https://70496--ocpdocs-pr.netlify.app/openshift-enterprise/latest/support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster#insights-operator-advisor-overview_using-insights-to-identify-issues-with-your-cluster

QE review: No impact to meaning, thus no QE review needed
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
LGTM, makes the text much more clear!

**Comment by kblake2016** [comment]
Thank you, @kcarmichael08.

/label merge-review-needed

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Pull request merged**
