### PR TITLE
Bug 1916082 bring forward updates to Automatically pruning images

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1916082

Content brought forward from https://github.com/openshift/openshift-docs/pull/23859/.

### CODE REVIEW

**Comment by bmcelvee** [comment]
@vikram-redhat since this is essentially a cherry pick of content to master, 4.6, and 4.7 does it need to go through reviews again (no content changes), or is it safe to go ahead and merge?

**Comment by vikram-redhat** [comment]
> @vikram-redhat since this is essentially a cherry pick of content to master, 4.6, and 4.7 does it need to go through reviews again (no content changes), or is it safe to go ahead and merge?

Should be ok to merge.

**Comment by bmcelvee** [comment]
Thank you!

**Pull request merged**
