### PR TITLE
Follow-up edits to PR#4202

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/4202

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape peer review please :bowtie:

**Comment by ahardin-rh** [comment]
@wongma7 @jsafrane FYI

**Comment by adellape** [comment]
:+1: LGTM

**Comment by vikram-redhat** [comment]
@ahardin-rh - this was marked with 3.4, 3.5 and 3.6 and for future release? I am guessing this was just an error, and it should have been marked with 3.4 and 3.5 and next release? 

I will release it with 3.6, but it won't make it to 3.4 and 3.5. Can you do a follow up and cherry pick to those branches tomorrow?

**Comment by ahardin-rh** [comment]
@vikram-redhat Yeah, looking at the discussion in the original PR and it looks like this is a mistake on my part. Neglected to update the milestone here. Yes, I will cherry-pick these follow-up edits to 3.4 and 3.5 tomorrow.

**Comment by ahardin-rh** [comment]
@vikram-redhat Interesting! Cross-checked 3.4 and 3.5 branches and the edits were already applied.  ❓  So, no cherry-picking needed!

**Comment by vikram-redhat** [comment]
@ahardin-rh - ha! Weird! :+1:

**Pull request merged**
