### PR TITLE
CNV-51691: Updated note about OVN-Kubernetes IPAM support

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.14+

Issue: [CNV-51691](https://issues.redhat.com//browse/CNV-51691)

Link to docs preview: https://85761--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/vm_networking/virt-connecting-vm-to-ovn-secondary-network.html#creating-ovn-nad_virt-connecting-vm-to-ovn-secondary-network

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sjhala-ccs** [comment]
@maiqueb Can you please review? Thanks!

**Review by yossisegev — APPROVED** [review]
/lgtm

**Review by maiqueb — APPROVED** [review]

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
