### PR TITLE
Typo: Moving IMPORTANT block into proper conditional statement where …

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
…it belongs

Version(s): 4.14 and `main`

Issue: https://issues.redhat.com/browse/OCPBUGS-10304 

Link to docs preview: https://68494--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal#installation-initializing-manual_installing-restricted-networks-bare-metal

QE review:
- [x] QE has approved this change.

Additional information: xref: https://github.com/openshift/openshift-docs/pull/63332

image

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@gpei PTAL This is a correction to the prior issue https://issues.redhat.com/browse/OCPBUGS-10304 and moves the IMPORTANT block into the restricted,restricted-upi conditional where it should correctly be.

**Comment by GroceryBoyJr** [comment]
@mjpytlak PTAL @bscott-rh PTAL

**Review by bscott-rh — COMMENTED** [review]
LGTM.

/remove-label peer-review-in-progress
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
LGTM and I see your peer reviewer was an install writer so I trust all is well in Install Land :nerd_face: 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
