### PR TITLE
SRVKS-814: Remove deprecated docs

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVKS-814

SME review: @nak3 

Applies for OCP 4.6+

Direct preview links:
- https://deploy-preview-38045--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-custom-domains.html
- https://deploy-preview-38045--osdocs.netlify.app/openshift-enterprise/latest/serverless/knative_serving/serverless-applications.html#knative-service-cluster-local_serverless-applications (moved to this section, no other changes)

Merge at Serverless 1.19.0 release

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
LGTM! Thank you :tada:

**Review by cardil — APPROVED** [review]
/lgtm

from QE

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
