### PR TITLE
OSDOCS-11794: ROSA CLI security refinements adding CLI output examples - UPDATE

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4.16+

Issue:
[OSDOCS-11794](https://issues.redhat.com/browse/OSDOCS-11794)

Link to docs preview:
[About IAM resources for ROSA clusters that use STS](https://82601--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources.html)

QE review:
- [ ] QE has approved this change.

Additional information:
This is an update from PR #81844 with the changes recommended.

### CODE REVIEW

**Comment by eohartman** [comment]
@agantony @arendej Can y'all please take a look at this revision of PR #81844 and let me know if it covers all the suggestions y'all made?

Thank you!

**Review by arendej — APPROVED** [review]
thanks

**Comment by bmcelvee** [comment]
Reviews compiled from https://github.com/openshift/openshift-docs/pull/81844 (closed and replaced by this PR). Because the OCP GA happened between that PR and this PR being merged, this now applies to 4.17+. 

Merging and cherry picking this PR now. If any additional changes are required, we can address them in a follow-up PR.

**Pull request merged**
