### PR TITLE
BZ#2118733: CNV: Add note about LM encryption

### PR DESCRIPTION
**Pull request by fabiand**
Version(s):
4.11+

apinnick: maybe 4.6+. Checking with Fabian.

Issue:
[BZ#2118733](https://bugzilla.redhat.com/show_bug.cgi?id=2118733)

Link to docs preview: apinnick: no preview but this change is probably small enough not to require it. fabiand is not a regular docs contributor.

Additional information: apinnick: I think it's ready for peer review.

### CODE REVIEW

**Comment by fabiand** [comment]
@bgaydosrh maybe you can help here?

**Comment by bgaydosrh** [comment]
@apinnick - Can you create a task for this for @fabiand? Thanks, Bob
cc: @ctomasko

**Comment by apinnick** [comment]
@bgaydosrh I don't think this PR requires a task. It's a small fix and it looks OK to me. I think it's ready for peer review.

**Comment by apinnick** [comment]
Closing because this PR is superseded by https://github.com/openshift/openshift-docs/pull/49426

**Pull request closed without merging**
