### PR TITLE
Added Title of Third Table

### PR DESCRIPTION
**Pull request by void-hr**
Version(s): 4.8

Issue: Title of third table is missing #50837

Link to docs preview: [Updated File](https://github.com/void-hr/openshift-docs/blob/793c33ebfb108aefb45ce13ac296b4c018e71788/modules/installation-minimum-resource-requirements.adoc)

QE review:
- [ ] QE has approved this change.

Additional information:

This PR resolves the issue #50837 that is the missing table title. As mentioned have added the title name as ".Minimum resource requirements".

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
@void-hr This looks great! The actual update is perfect. 

The only thing that needs to be done before we can merge this is that you'll need to squash your commits. Right now you have 2, but we only allow PRs to have a single commit. Let me know if you need any help with how to do that. Thanks!

**Comment by void-hr** [comment]
@bergerhoffer It would be great if you can help me with that as it sounds a bit unfamiliar to me.

**Comment by bergerhoffer** [comment]
I'm attaching a PDF of the instructions we use on our team to squash. Basically, you'll run the command `git rebase -i HEAD~2` (since you need to squash 2 commits), and then you'll have an editor pop up. The editor will list your 2 commits with the word "pick" in front of them. For the second commit, you change that "pick" to "f" and save. Then force push your changes.

Let me know if you have any questions!

[OSDOCS-Squashingyourcommits-041022-1432-70.pdf](https://github.com/openshift/openshift-docs/files/9707852/OSDOCS-Squashingyourcommits-041022-1432-70.pdf)

**Comment by void-hr** [comment]
Can I again clone my repo as I have made some irrelevant changes to my local repo

**Comment by bergerhoffer** [comment]
@void-hr yep you can do whatever you need to. I see you did the changes right on your 'main' branch. Which is fine if you're just doing a quick update. But normally what you'd want to do is check out a new branch do your changes. Again, you don't have to change anything now, but just for future reference.

So you likely don't need to re-clone your repo, you probably just need to fix your branch. Since this is such a small change, you could just reset your branch and make the change again. Or you could create a new branch and a new PR if you'd like. It's up to you.

Did you make the changes using a terminal, or through the UI?

**Comment by void-hr** [comment]
@bergerhoffer I am a bit confused, as I have cloned the repo again I still have to rebase while opening a new PR.

**Comment by void-hr** [comment]
@bergerhoffer Also I have updated my branch before cloning and while performing git rebase my commits are not in consecutive order.

**Comment by bergerhoffer** [comment]
@void-hr Since the change is so small (one line), I'd recommend resetting your branch and making the change again. Instead of sorting through the git issues.

Here's one way that you can do this:

1. Add a reference to the upstream remote repository if you don't have it already:
    `git remote add -f upstream git@github.com:openshift/openshift-docs.git`
2. Do a hard reset to the upstream main branch (this will wipe away your change and commits):
    `git reset --hard upstream/main`
3. Make your change again and make a new commit.
4. Force push those changes to your PR:
    `git push -f origin HEAD`

**Comment by void-hr** [comment]
@bergerhoffer I am clueless why on clicking compare this is showing too much changes

**Comment by bergerhoffer** [comment]
@void-hr Because there really aren't any changes compared to the last time you pushed (it's still the same single title line).

However, when I look at your PR now, it looks perfect. I see just the change you wanted to make, and only a single commit now. So you should be good to go now!

**Comment by void-hr** [comment]
@bergerhoffer It is showing me "Showing 70 changed files with 2,385 additions and 207 deletions" and I have made change of single line. Could you please explain me this.

**Comment by bergerhoffer** [comment]
@void-hr I see what you mean. Don't worry too much about that comparison button. Because you rebased/restarted - in the time since you had initially created this PR yesterday, other people have been making updates to the repository. And that's what you're seeing there. It's nothing that touches the file you changed - it's just the rest of the doc set becoming aware and up to date with the updates other people have made.

For you, what's important to pay attention to is the "Commit" tab of this PR (which has 1 commit, perfect), and the "Files changed" tab (which has your edit, and looks great).

Does that make sense?

**Comment by void-hr** [comment]
@bergerhoffer Thanks for helping me out and yes now I am more clear rather than being confused 💯. 
Now I only have to wait for the PR to merge and also in the meantime can I open another PR that will not affect this or should I wait.

**Comment by bergerhoffer** [comment]
@void-hr Great! I'm going to be merging this shortly. Thanks again for your contribution!

As long as you create a new branch next time, instead of working directly on main like you did this time, that won't affect this.

So when you're ready to work on your next issue, you would check out a new branch with a command like:

`git checkout -b new-branch-name upstream/main`

(but name it whatever you want) and work on that!

**Pull request merged**
