### PR TITLE
OSDOCS-4325: Revised Scaling the Cluster Monitoring Operator content

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-4325

Link to docs preview:
https://63485--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-infrastructure-practices#scaling-cluster-monitoring-operator_recommended-infrastructure-practices

### CODE REVIEW

**Review by skopacz1 — COMMENTED** [review]
Left a few nits/suggestions but otherwise looks good to me! Please wait until @adellape approves of my review before implementing any feedback. Thanks!

**Review by adellape — COMMENTED** [review]
@skopacz1 @ahardin-rh Peer review comments LGTM 👍

**Review by rsevilla87 — APPROVED** [review]
lgtm!

**Review by mffiedler — APPROVED** [review]
/LGTM

**Pull request merged**
