### PR TITLE
CNV#40183: RN - TP - Storage Class Migration

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/CNV-40183

Link to docs preview:
https://83353--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by duyanyan** [comment]
afaik, storage class migration is TP in 4.17, not GA

**Comment by danielclowers** [comment]
thanks for catching that @duyanyan. this has been fixed now.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
