### PR TITLE
Fix the wrong link reference that breaks the build

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `build-docs-1.2`

Issue: `n/a`

Link to docs preview: 

* https://85568--ocpdocs-pr.netlify.app/openshift-builds/latest/work_with_builds/using-builds.html#additional-resources_using-builds
* https://85568--ocpdocs-pr.netlify.app/openshift-builds/latest/installing/installing-openshift-builds

QE review: `n/a`

Additional information:

### CODE REVIEW

**Review by dfitzmau — APPROVED** [review]

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Comment by xenolinux** [comment]
As discussed on slack -- Manual CP PR for build-docs-1.1 will be created.

**Pull request merged**
