### PR TITLE
Reword the legacy log forward deprecation wording

### PR DESCRIPTION
**Pull request by mburke5678**
From @sichvoge in Slack conversation:
_i think the statement needs some improvements. it’s actually not the first time that someone asks for more clarification. maybe we should say something along the lines that the legacy mechanism will be replaced by the new log forwarding API._

https://coreos.slack.com/archives/CB3HXM2QK/p1587387926482800

### CODE REVIEW

**Comment by mburke5678** [comment]
@sichvoge PTAL

FYI: @jcantrill @anpingli Any concerns here?

**Review by anpingli — COMMENTED** [review]
@mburke5678  @jcantrill  Could  we have a naming convention  here.  Three methods to sent logs to syslog server.
1.  3.11, 4.1, 4.2. By Environment variable.     Legacy method
2.  4.3+.  By configuremap.    Log Forwarding API
3.  4.3+.   By logforward CRD.  TechPreview Log Forwarding API

**Comment by sichvoge** [comment]
What naming convention are you looking for @anpingli?

**Comment by anpingli** [comment]
> What naming convention are you looking for @anpingli?
> 
> Just a small note:
> 
>     * The logforward CRD = TechPreview Log Forwarding API
> 
>     * Legacy method = By configmap

Thanks for clarification.

**Comment by anpingli** [comment]
LGTM

**Comment by sichvoge** [comment]
Thanks Michael.

Maybe we should not call out "API" in the section names and only have a single chapter were customers learn how to forward their logs to a third party system. In that chapter we explain that customers can use 1) the ConfigMap approach for setting up forwarding for syslog and secure-forwarding, then we explain how, or 2) use our new API which is in tech preview and explain how.

For 1), I would add a note that this is deprecated and that it will be replaced by the Log Forwarding API in a future release; and point to the next section 2).

Basically, let's consolidate the following topics into one (eg. "Forward logs to a third party system"):

- Forwarding cluster logs using the Log Forwarding API
- Fowarding cluster logs using Fluentd plug-ins

And in the new single topic, my suggestion would be to divide into the following sub topics:

- Forward logs using secure-forward
- Forward logs using syslog
- Forward logs using the Log Forwarding API (TP)

The first two sub topics explain the ConfigMap approach and the last, the new CRD.

I think this is mostly a structural change and a copy/paste exercise :)

WDYT @mburke5678?

**Comment by mburke5678** [comment]
@sichvoge @anpingli I am closing this PR and we can follow these changes along with [Suggested changes to the log forwarding section](https://docs.google.com/document/d/1abKabUALXa2O6-cbFu8iGY7uo5vcLR3ago9JyQC7xjE/edit?ts=5e9ee5b7#) in https://github.com/openshift/openshift-docs/pull/21391

Let me know if anyone wants to keep this PR open and I can re-open.

**Pull request closed without merging**
