### PR TITLE
[OSDOCS-8238] Add AliCloud IPI to TP table in 4.11 RNs

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11

Issue:
[OSDOCS-8238](https://issues.redhat.com//browse/OSDOCS-8238)

Link to docs preview:
[Installation Technology Preview features](https://66415--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes#ocp-4-11-technology-preview)

QE review:
Not required.

Additional information:
Missing from 4.10+ TP tables, but correctly announced in 4.10 and has TP banners for all published versions

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM from peer review

@jeana-redhat just checking that it was determined that this didn't need to go through change management, since it was announced appropriately, just missing from the tables?

**Comment by jeana-redhat** [comment]
> LGTM from peer review
> 
> @jeana-redhat just checking that it was determined that this didn't need to go through change management, since it was announced appropriately, just missing from the tables?

That is my rationale (based on a similar deal last week) but I will get an explicit :+1: before merge. Thanks!

**Pull request merged**
