### PR TITLE
[WIP] OCPBUGS#10870: Change the kind parameter value to aws

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-10870

Link to docs preview: https://57842--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/manually-creating-iam.html#manually-create-iam_manually-creating-iam-aws

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jianping-shu** [comment]
Seems the doc is not update completely. 
Pls. ping me when it's done.

**Comment by xenolinux** [comment]
@jianping-shu Can you PTAL now? I updated the parameters.

**Comment by xenolinux** [comment]
> @xenolinux Not just change 'azure' to 'aws'. You need find the actual aws CR and secret sample files to update, because the formats of azure and aws files are quite different.

Okay. I thought so.

**Comment by xenolinux** [comment]
> @xenolinux Want me to pick this up? I need to do GCP as well and I am done with 4.13 deliverables

Yes please pick it up. Thank you :)

**Pull request closed without merging**
