### PR TITLE
Cloud config section not required on worker nodes

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1629354

### CODE REVIEW

**Comment by mburke5678** [comment]
Dan Phillips confirmed in BZ that the parameter can be removed.

**Comment by mburke5678** [comment]
@xltian PTAL

**Comment by xltian** [comment]
@jhou1 Will review from QE side.

**Comment by jhou1** [comment]
LG

**Pull request merged**
