### PR TITLE
Edits per PERFSCALE-367

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://jira.coreos.com/browse/PERFSCALE-367

Preview build: http://file.rdu.redhat.com/~ahardin/10292019/CL-edits/scalability_and_performance/using-cluster-loader.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jmencak @sjug PTAL

**Comment by ahardin-rh** [comment]
@mffiedler Can you please provide a QE review? Thanks!

**Comment by mffiedler** [comment]
@wabouhamad Please review based on your original bz.

**Comment by wabouhamad** [comment]
@ahardin-rh LGTM

**Pull request merged**
