### PR TITLE
Added Unmanged prereq for Fluentd config map changes

### PR DESCRIPTION
**Pull request by mburke5678**
Per conversation in Slack
yes unmanaged if you wish to alter the (fluentd) configmap
https://coreos.slack.com/archives/GGUR75P60/p1566246825327900

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli PTAL

@richm  @jcantrill FYI

**Review by jcantrill — APPROVED** [review]

**Review by anpingli — APPROVED** [review]
LGTM

**Pull request merged**
