### PR TITLE
GH-42367: Fix broken links

### LINKED ISSUE #42367: Broken links in kdump section
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/support/troubleshooting/troubleshooting-operating-system-issues.html

### What needs fixing?

- Testing the kdump configuration
    - Current link (broken): https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/system_design_guide/installing-and-configuring-kdump_system-design-guide#testing-the-kdump-configuration_installing-and-configuring-kdump
    - Proper link: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/configuring-kdump-on-the-command-line_managing-monitoring-and-updating-the-kernel#testing-the-kdump-configuration_configuring-kdump-on-the-command-line
- Analyzing a core dump
    - Current link (broken): https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/system_design_guide/installing-and-configuring-kdump_system-design-guide#analyzing-a-core-dump_installing-and-configuring-kdump
    - Proper link: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/analyzing-a-core-dump_managing-monitoring-and-updating-the-kernel
- Setting up kdump in RHEL (same link broken in sentence "Also refer to the RHEL kdump documentation for further information on configuring the dump target.")
    - Current link (broken): https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/system_design_guide/installing-and-configuring-kdump_system-design-guide
    - Proper link: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/installing-kdump_managing-monitoring-and-updating-the-kernel

### PR DESCRIPTION
**Pull request by jldohmann**
Fixes #42367

OCP Version: 4.6+

Current 4.10 docs: https://docs.openshift.com/container-platform/4.10/support/troubleshooting/troubleshooting-operating-system-issues.html#enabling-kdump

Direct doc preview link: https://deploy-preview-43448--osdocs.netlify.app/openshift-enterprise/latest/support/troubleshooting/troubleshooting-operating-system-issues#enabling-kdump

### CODE REVIEW

**Comment by jldohmann** [comment]
@loganmc10 This PR fixes the links in the issue you created. Can you double check that the link for configuring kdumps brings users to the right location in the RHEL docs? Thank you!

**Comment by loganmc10** [comment]
Yes just checked, looks good now!

**Review by adellape — APPROVED** [review]

**Comment by bergerhoffer** [comment]
@adellape Does this need to be CPd still?

**Comment by adellape** [comment]
@jldohmann The module was introduced in 4.7+, so no pick required for 4.6.

**Pull request merged**
