### PR TITLE
fixing bare metal URLs

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1704849

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, can I merge this, or do you want me to wait for QE?

**Comment by kalexand-rh** [comment]
Clayton has no objections to this change.

**Comment by kalexand-rh** [comment]
@jianlinliu, I'm going to merge. Will you PTAL? I'm happy to make more changes later.

**Comment by sferich888** [comment]
Its the wrong version! 
410.8.20190418.1 is the version that is pinned to beta4 

```
$ oc image info $(oc adm release info --pullspecs | grep "os-content" | awk '{print $2}') | grep -E '(version)=' | awk -F= '{print $2}' 
410.8.20190418.1
```

**Comment by sferich888** [comment]
use links from https://jira.coreos.com/browse/ART-600 (if we are not using mirror.openshift.com).

**Comment by jianlinliu** [comment]
> @jianlinliu, I'm going to merge. Will you PTAL? I'm happy to make more changes later.

@morenod, pls help ack.

**Pull request merged**
