### PR TITLE
update kubernetes & docker version.

### PR DESCRIPTION
**Pull request by warmchang**
update kubernetes & docker version for ocp3.4/origin1.4.

### CODE REVIEW

**Comment by warmchang** [comment]
same error on branch enterprise-3.4:
https://github.com/openshift/openshift-docs/edit/enterprise-3.4/architecture/infrastructure_components/kubernetes_infrastructure.adoc#L41

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
No revision history needed

**Comment by warmchang** [comment]
welcome!

**Pull request merged**
