### PR TITLE
Fixing one more build error

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixing build error and rendering `:leveloffset: +1` in the docs [1].

[1] https://docs.openshift.com/container-platform/4.2/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-ingress-controller.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@openshift/team-documentation For review.

Preview: http://file.rdu.redhat.com/~ahoffer/2019/one-more-error/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-ingress-controller.html

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
