### PR TITLE
OSSM-8224: change labelSelectors to memberSelector

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OCP 4.14+

Issue: https://issues.redhat.com/browse/OSSM-8224

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by FilipB — APPROVED** [review]

**Review by luksa — APPROVED** [review]

**Comment by rh-tokeefe** [comment]
Note for peer and merge reviewers. This is essentially a one word change in two places. All work was previously reviewed and published.

**Review by cbippley — COMMENTED** [review]
LGTM!

**Pull request merged**
