### PR TITLE
Changed MYSQL_PASSPHRASE to MYSQL_PASSWORD in External Database Envir…

### PR DESCRIPTION
**Pull request by ghost**
…onment Variables

This is a follow-up to https://github.com/openshift/openshift-docs/pull/6751

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL. No rev history needed.

**Comment by ahardin-rh** [comment]
LGTM! 🎆

**Comment by tmorriso-rh** [comment]
@shawkins Please review. This change will be applied to 3.1 -> 3.7. Thanks.

**Comment by tmorriso-rh** [comment]
Note to TW: manual cherry pick to 3.1 - 3.4. Use script for 3.5 - 3.9.

**Comment by shawkins** [comment]
@tmorriso-rh LGTM

**Pull request merged**
