### PR TITLE
Update monitoring-configuring-the-monitoring-stack.adoc

### PR DESCRIPTION
**Pull request by benben**
Fix prometheus config key in example config

Version(s):

Issue:

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by bburt-rh** [comment]
@benben I don't think your proposed change is correct. The Prometheus config map component is called `prometheusK8s` in the `cluster-monitoring-config` ConfigMap object and `prometheus` in the `user-workload-monitoring-config` ConfigMap object.

@juzhao @simonpasquier - Can one of you PTAL at the change proposed by this PR and confirm my assessment?

**Comment by simonpasquier** [comment]
> Can one of you PTAL at the change proposed by this PR and confirm my assessment?

you're correct, there's no mistake in the current documentation: prometheusK8s is the correct entry.

**Comment by benben** [comment]
It’s true that I worked with the cluster config and not the user workload confit. Are you saying these are two different keys for the same setting just in different configs? If this is the case then my PR can be closed without my change but that would be very confusing in general.

**Comment by bburt-rh** [comment]
> It’s true that I worked with the cluster config and not the user workload config. Are you saying these are two different keys for the same setting just in different configs? If this is the case then my PR can be closed without my change being merged but that would be very confusing in general.

@benben - please go ahead and close this  PR. Thanks!

**Pull request closed without merging**
