### PR TITLE
BZ-1754036: removed all instances of openshift_node_cert_expire_days …

### PR DESCRIPTION
**Pull request by lbarbeevargas**
…and related information.

BZ-1754036 https://bugzilla.redhat.com/show_bug.cgi?id=1754036

@barleyer Please take a look for 3.11 and confirm that this is the only impacted version.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
@barleyer BUMP

**Comment by barleyer** [comment]
@lbarbeevargas Hey,I think you should request installer team members to review this. @gpei

**Comment by gpei** [comment]
The change lgtm, `openshift_node_cert_expire_days` is not being used anymore since 3.10.

**Comment by lbarbeevargas** [comment]
@openshift/team-documentation PTAL. CP to enterprise-3.11.

**Comment by jboxman** [comment]
@lbarbeevargas, LGTM. I'll merge + CP.

**Pull request merged**
