### PR TITLE
OSDOCS-8688#fixing callouts

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
OCP 4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8688

Link to docs preview:
https://73684--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd#creating-single-etcd-backup_backup-etcd

QE review:
- [x] QE has approved this change (comment added in https://issues.redhat.com/browse/OSDOCS-8688)

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Hey @brendan-daly-red-hat  there are more of those in that same section, below the corrections you have made. Do you want to correct those also?

**Comment by brendan-daly-red-hat** [comment]
@GroceryBoyJr, Hi James, Thanks, I updated those other corrections further down the page. Can you review again? Thanks.

**Pull request merged**
