### PR TITLE
BZ1980040: Migration rollback leftovers

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1980040

4.5+

Added note about rollback leftovers

Previews:

https://deploy-preview-34418--osdocs.netlify.app/openshift-enterprise/latest/migration-toolkit-for-containers/troubleshooting-mtc.html#migration-rolling-back-migration-web-console_troubleshooting-mtc

https://deploy-preview-34418--osdocs.netlify.app/openshift-enterprise/latest/migration-toolkit-for-containers/troubleshooting-mtc.html#migration-rolling-back-migration-cli_troubleshooting-mtc

QE approved

### CODE REVIEW

**Comment by XinRedhat** [comment]
LGTM @apinnick

**Review by skrthomas — APPROVED** [review]
LGTM!

**Pull request merged**
