### PR TITLE
[SRVCOM-2727] Change name to OpenShift Serverless in TOC 

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
 serverless-docs-1.32+

Issue:
https://issues.redhat.com/browse/SRVCOM-2727

Link to docs preview:
https://74571--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/about-serverless (TOC)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Comment by dfitzmau** [comment]
LGTM

/remove-label peer-review-in-progress

/label peer-review-done

**Comment by mburke5678** [comment]
@ochromy Please squash the commits before we can merge!

**Comment by ochromy** [comment]
> @ochromy Please squash the commits before we can merge!

Apologies, they should be squashed now.

**Review by skopacz1 — APPROVED** [review]
merge review LGTM

**Pull request merged**
