### PR TITLE
RHDEVDOCS-2859 Tracker for Issue #30567 Issue in file machine_managem…

### PR DESCRIPTION
**Pull request by rolfedh**
- For versions 4.5+
- https://issues.redhat.com/browse/RHDEVDOCS-2859
- https://deploy-preview-30834--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-logging_creating-infrastructure-machinesets
- Ready for peer review and merge

### CODE REVIEW

**Comment by rolfedh** [comment]
@jcantrill confirmed this change in the following Slack thread: https://coreos.slack.com/archives/GGUR75P60/p1616530408302500?thread_ts=1616515248.288800&cid=GGUR75P60

**Comment by rolfedh** [comment]
@anpingli Please review and approve this pull request. Thank you.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
