### PR TITLE
Issues: Edit suggested in file admin_guide/overcommit.adoc 4x

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/13036

### CODE REVIEW

**Comment by mburke5678** [comment]
PR for fix in 3.11 docs: https://github.com/openshift/openshift-docs/pull/20030

**Comment by bmcelvee** [comment]
LGTM!

**Comment by mburke5678** [comment]
@QiaolingTang Please take a look.

**Pull request merged**
