### PR TITLE
Cloud

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
Adding the missing cloud provider links to compute machine set in docs.
Version:
`main`

Issue:
[#64725](https://github.com/openshift/openshift-docs/issues/64725l)
Link to docs preview:
[preview](https://github.com/7h3-3mp7y-m4n/openshift-docs/blob/main/machine_management/index.adoc)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@7h3-3mp7y-m4n content updates look good! This needs to be squashed to a single commit for merge.

---
**Information for repo standards**

Version:
4.11+

Issue:
[#64725](https://github.com/openshift/openshift-docs/issues/64725)

Link to docs preview:
[Managing compute machines](https://65562--docspreview.netlify.app/openshift-enterprise/latest/machine_management/#machine-mgmt-intro-managing-compute_overview-of-machine-management)

QE review:
- QE not required for this change

**Comment by 7h3-3mp7y-m4n** [comment]
sorry for responding so late but I'm on it :)

**Comment by jeana-redhat** [comment]
> sorry for responding so late but I'm on it :)

No problem! :)

**Comment by ShaunaDiaz** [comment]
@7h3-3mp7y-m4n Are you able to squash the commits and rebase? Let us know if you need help.

**Comment by bergerhoffer** [comment]
Closing - #72099 was opened to address this

**Pull request closed without merging**
