### PR TITLE
OSDOCS-10429 HCP topic map 

### PR DESCRIPTION
**Pull request by xJustin**
This PR adds an additional topic map for the new HCP documentation set.
Doc assemblies that need to be verified are commented out for now. These will be groomed in the future. 

Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10429
Link to docs preview:

N/A
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xJustin** [comment]
Tried to uncomment all high-level topics - if a given topic has no attached assemblies, the CI tests will fail.

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
