### PR TITLE
TELCODOCS:1153b - Update variables for OSC release 1.3.3

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): Main, 4.12

[Issue](https://issues.redhat.com/browse/TELCODOCS-1153)

Link to docs preview: This PR only includes an update to the common attributes file. No preview available.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by snarayan-redhat — COMMENTED** [review]
Looks good!

**Comment by mburke5678** [comment]
Preview, see Verification: https://55126--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads.html#sandboxed-containers-installing-operator-cli_deploying-sandboxed-containers

**Comment by mburke5678** [comment]
@MirzWeiss Merge error on 4.12. Can you do a manual cherry pick?

**Pull request merged**
