### PR TITLE
Bug 1563744, added disclaimers about images running as root in Online

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1563744

@wgordon17 PTAL

### CODE REVIEW

**Comment by wgordon17** [comment]
👍

**Comment by ahardin-rh** [comment]
@openshift/team-documentation Please peer review

**Review by kalexand-rh — COMMENTED** [review]
One nitpick, otherwise LGTM

**Comment by ahardin-rh** [comment]
@dongboyan77 PTAL

**Comment by dongboyan77** [comment]
LGTM, thanks

**Pull request merged**
