### PR TITLE
OBSDOCS-571: Release notes for the 2.9.1 patch of distributed tracing

### PR DESCRIPTION
**Pull request by max-cx**
:warning: Attention of reviewers: This PR introduces only [two new lines](https://github.com/openshift/openshift-docs/pull/66358/files#diff-fb054b2df68cd846ec4882960fe0fcbbb4bb63e3b38db86d3d15d7fd85e1fd56R30-R32), while all the other lines have been copied and pasted from already published content on another page. So you only need to review the two new lines in this PR.

Version(s):

OpenShift 4.11, 4.12, 4.13, 4.14

Issue:

https://issues.redhat.com/browse/OBSDOCS-571

Link to docs preview:

https://66358--docspreview.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_rn/distr-tracing-rn-2-9-1

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by IshwarKanse — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Review by frzifus — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
LGTM, thanks for the explanation up front :)

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
