### PR TITLE
Update 4.6 Release Notes for Image Registry

### PR DESCRIPTION
**Pull request by bmcelvee**
Adding release notes for Image Registry
4.6 Release Notes Tracker: https://github.com/openshift/openshift-docs/issues/22406#issuecomment-707163264

### CODE REVIEW

**Comment by bmcelvee** [comment]
@dmage and @lihongan adding the 4.6 Image Registry RNs

Note: the build is failing on the Azure Gov xref because it's not yet merged.

**Comment by lihongan** [comment]
@wzheng1  Please help take a look this, it is image registry related. thanks.

**Comment by wzheng1** [comment]
@bmcelvee there are some changes for image registry config too, spec.logging is changed to spec.loglevel and a new spec.operatorLogLevel is added too.
spec:
  logLevel: Normal
  operatorLogLevel: Normal

**Comment by dmage** [comment]
It's important to note that we added spec.storage.managementState (https://issues.redhat.com/browse/IR-129). If somebody decide to switch the image registry management state from Managed to Removed, the storage will be removed only if storage management state is Managed.

**Comment by bmcelvee** [comment]
This PR pulled in random changes not associated with Image Registry release notes. Rather than risking changes to relevant content not meant to be introduced in this PR, I opened a new PR: https://github.com/openshift/openshift-docs/pull/26659.

**Pull request closed without merging**
