### PR TITLE
[BZ2002435]: Change the Ansible version

### PR DESCRIPTION
**Pull request by xenolinux**
Changed the Ansible version and the link.

OCP version: 4.7+
QE contact @emmajiafan 
[Preview](https://deploy-preview-42644--osdocs.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-quickstart.html)
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2002435)

### CODE REVIEW

**Comment by mjpytlak** [comment]
Peer review LGTM.
@xenolinux Do you need a merge?

**Comment by xenolinux** [comment]
> Peer review LGTM. @xenolinux Do you need a merge?

@mjpytlak Yes please, need a merge

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM - Please stand by for later merge.

**Comment by xenolinux** [comment]
@GroceryBoyJr This PR is ready to merge. Can you please merge this PR?

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

Preview provided
OCP versions specified.
BZ link provided.

Commits look to all be squashed, that's excellent, thank you!
And you have links to BZ in both! Thank you!
Grammar and logic (of the text) look great, Thank You!

**Comment by mburke5678** [comment]
@xenolinux I am getting a merge error because the [Ansible Runner version in 4.7-4.9 is  v1.1.0+](https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/ansible/osdk-ansible-tutorial.html#osdk-common-prereqs_osdk-ansible-tutorial). This PR has it as v2.0.2+. It appears to have changed in [4.10](https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/ansible/osdk-ansible-tutorial.html#osdk-common-prereqs_osdk-ansible-tutorial). 
I don't want to change the version in 4.7-4.9 incorrecty.

**Comment by bergerhoffer** [comment]
@mburke5678 Can we at least get this CPd to 4.10 and 4.11 in the meantime?

**Comment by bergerhoffer** [comment]
Also, I think it's only a conflict because the line that was updating is touching that line that is different. It shouldn't actually try to also bring in the 2.0.2 change when doing the manual cherry pick.

**Comment by mburke5678** [comment]
That was my thinking. Just wanted to make sure. 
I can CP to 4.10 and 4.11

**Pull request merged**
