### PR TITLE
GitHub-49529: Updated versions to 4.10 in the examples

### LINKED ISSUE #49529: [enterprise-4.10] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc
### Which section(s) is the issue in?
Use case: Including arbitrary images and helm charts
https://docs.openshift.com/container-platform/4.10/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-image-set-examples_installing-mirroring-disconnected

### What needs fixing?
The documentation should be changed to reference version 4.10 instead of 4.9 in the OCP channel and Operator Catalog:
mirror:
 ocp:
   channels:
     - name: stable-4.9
 operators:
   - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9

Many thanks in advance!

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.10 only

Issue:
Fixes #49529

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2022/github-49529/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-image-set-examples_installing-mirroring-disconnected

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@jpower432 Can you confirm whether this update is okay to make? It's just updating the examples in the 4.10 docs to use 4.10 (instead of 4.9). Thanks!

Preview: http://file.rdu.redhat.com/~ahoffer/2022/github-49529/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-image-set-examples_installing-mirroring-disconnected

**Comment by jpower432** [comment]
@bergerhoffer, I do not see any issues with this update.

**Pull request merged**
