### PR TITLE
Bug batching for RHCOS 4.16

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.16

Issue:
N/A

Link to docs preview:
https://77899--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html

QE review:
N/A

Additional information:

### CODE REVIEW

**Comment by bscott-rh** [comment]
Peer review LGTM

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM.

**Pull request merged**
