### PR TITLE
Missing type in visualization for install via CLI

### PR DESCRIPTION
**Pull request by ssonigra**
Version(s):

4.13 to 4.16

Issue:
https://issues.redhat.com/browse/OBSDOCS-1336

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ssonigra** [comment]
Reference bug https://issues.redhat.com/browse/OBSDOCS-1232

**Review by xenolinux — COMMENTED** [review]
LGTM

A gentle reminder to add the preview link before sending for a merge! Also this PR must target - 4.17 too - right?

**Comment by maxwelldb** [comment]
@shreyasiddhartha Does this apply beyond 4.16, too? If not, the PR should not target `main`.

**Review by jeana-redhat — COMMENTED** [review]
This LGTM but waiting to get version applicability confirmation (with #82329)

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by libander** [comment]
@jeana-redhat  - 4.13+ 
/lgtm

**Comment by jeana-redhat** [comment]
@ssonigra this will need a manual cherrypick into the 4.13 branch of the docs.

**Comment by ssonigra** [comment]
Hello @jeana-redhat , is there any action needed from my side

**Comment by jeana-redhat** [comment]
> Hello @jeana-redhat , is there any action needed from my side

Yes, this will not go into 4.13 automatically. To get it into 4.13 docs, you will need to open a PR against `enterprise-4.13` with the changes and ask for merge review. 

Normally we do this with [this procedure](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.x2d4tdt5adta) (see: _To manual cherry pick using the command line, in the event of merge errors_), but I think in this case you could just open a PR and make the changes without using the `cherry-pick` command. 

You could include the changes for this PR and #82329 to have less tracking - just be sure to link your work to thes original PRs.

**Comment by jeana-redhat** [comment]
Hi Suarab,

Yes, likely the automatic cherrypick failed because that module has either been renamed or did not exist in 4.13. If you know for sure that this information needs to go into 4.13, I suggest working with one of the writers in this content area to help you find out where it should be added. I don't know this area well enough to be able to help much, unfortunately.

Thanks for sticking with this! :slightly_smiling_face:

**Comment by ssonigra** [comment]
@shreyasiddhartha @libander anyone of you can help me on this

**Pull request merged**
