### PR TITLE
Bug 1598338 - Fixing typo

### PR DESCRIPTION
**Pull request by ousleyp**
https://bugzilla.redhat.com/show_bug.cgi?id=1598338

@openshift/team-documentation PTAL

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by mburke5678** [comment]
@ousleyp LGTM. Do you know which versions this fix applies to?

**Comment by ousleyp** [comment]
@mburke5678 Just added the 3.6 and 3.7 labels - that should be it :)

**Comment by vikram-redhat** [comment]
@ousleyp Your first PR! 💯

**Pull request merged**
