### PR TITLE
OSDOCS#4002: Improve AWS quota links and guidance

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
current and future releases (main)

Issue:
https://issues.redhat.com/browse/OSDOCS-4002

Link to docs preview:
https://57255--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-required-aws-service-quotas.html

QE review:
- [ ] QE has approved this change.

Additional information:
- Added detail to the introductory text of the module to note AWS approval time
- Added more useful links to Additional resources section

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! @laubai Do you need me to merge as well? Thanks! :)

**Comment by laubai** [comment]
@bmcelvee Yes please! I don’t have merge access yet

**Comment by bmcelvee** [comment]
All set!

**Pull request merged**
