### PR TITLE
clarify jenkins template names

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge

**Comment by ahardin-rh** [comment]
LGTM! Thanks!

**Comment by ahardin-rh** [comment]
Removed Dedicated and Online labels, as this is an Install Config topic, which does not live in Dedicated or Online

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/configuring_pipeline_execution.adoc#install-config-configuring-pipeline-execution[Configuring Pipeline Execution]
|Clarified Jenkins template names.
%

**Pull request merged**
