### PR TITLE
BZ1945405: Adding port access requirement

### PR DESCRIPTION
**Pull request by amolnar-gh**
Bug link: https://bugzilla.redhat.com/show_bug.cgi?id=1945405

Link to preview (last subsection): https://deploy-preview-39280--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites#network-requirements_ipi-install-prerequisites

For releases 4.9, 4.10
4.6: https://github.com/openshift/openshift-docs/pull/39574
4.7: https://github.com/openshift/openshift-docs/pull/39575
4.8: https://github.com/openshift/openshift-docs/pull/39576

SME lgtm via Slack

### CODE REVIEW

**Comment by amolnar-rh** [comment]
Hi @lshilin-r! Could you please take a look at the changes and let me know if everything looks okay? Thank you!

**Review by lpettyjo — COMMENTED** [review]
I believe that when you state "IP" in this context, you mean "IP address". If so, please correct for clarity. Otherwise, LGTM.

**Pull request merged**
