### PR TITLE
CNV#32668: Update Service over NodePort UI documentation

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/CNV-32668

Link to docs preview:
* https://65186--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-accessing-vm-ssh.html#virt-creating-service-web_virt-accessing-vm-ssh
* https://65186--docspreview.netlify.app/openshift-enterprise/latest/virt/getting_started/virt-web-console-overview.html#virtualmachine-details-details_virt-web-console-overview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dfitzmau** [comment]
LGTM!

/remove-label peer-review-in-progress

/label peer-review-done

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
