### PR TITLE
Change cluster logging file name prefix from `efk-logging` to `cluster-logging`

### PR DESCRIPTION
**Pull request by mburke5678**
Changing the prefix on the file names of the cluster logging docs from `efk-logging` to `cluster-logging` to remove the EFK concept.
Also changed the associated context and ID strings.

### CODE REVIEW

**Comment by bparees** [comment]
@jcantrill @sichvoge  fyi

**Comment by mburke5678** [comment]
@vikram-redhat Manual cherry pick due to conflicts: https://github.com/openshift/openshift-docs/pull/16792

**Pull request merged**
