### PR TITLE
Add documentation for the router allowed and denied domains.

### PR DESCRIPTION
**Pull request by ramr**
For trello card: https://trello.com/c/Gj4hbRd3/424-document-the-wildcard-router-stuff-and-the-deny-and-allow-options

### CODE REVIEW

**Comment by ramr** [comment]
rebased for conflict. @knobunc  @pecameron  PTAL Thx

**Review by knobunc — APPROVED** [review]
LGTM

**Comment by knobunc** [comment]
@openshift/team-documentation ready for merge.

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL.

**Comment by bfallonf** [comment]
Thanks @ramr . I'll merge this and do a quick followup.

**Comment by bfallonf** [comment]
@ramr , I've labeled this a 3.4 -> because of #3483 . Let me know if that's incorrect.

**Comment by ramr** [comment]
@bfallonf  3.4 is correct.

**Pull request merged**
