### PR TITLE
Deployment hooks documentation

### PR DESCRIPTION
**Pull request by ironcladlou**
This documents deployment lifecycle hooks, implemented in https://github.com/openshift/origin/issues/1645.

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @pmorie

**Comment by bparees** [comment]
mostly lgtm, but the footnotes are rendering a bit strangely.  maybe they'll look better in our docs tooling than what github is currently doing though.

**Comment by ironcladlou** [comment]
Yeah- you need to compile and view the rendered version for best results. I wonder if we could automate that for PRs somehow (e.g. travis) so folks could review the final product a PR represents.

**Comment by ironcladlou** [comment]
@adellape @nhr 

My team has reviewed this, I think it's time to hand it over to the docs team.

**Comment by adellape** [comment]
:cool:

**Pull request merged**
