### PR TITLE
Changed base64 option to make it platform-agnostic. Closes #28376

### LINKED ISSUE #28376: [enterprise-4.6] Issue in file monitoring/managing-alerts.adoc
### Which section(s) is the issue in?

Applying a custom Alertmanager configuration

### What needs fixing?

Step  1  _Print the currently active Alertmanager configuration into file alertmanager.yaml_ in the Procedure description contains a Linux specific command that fails on a MacOS client (where `base64 -D` should be used to decode the base64 encoded secret).

A platform-agnostic command to extract the alertmanager.yaml could be used instead:

```
oc -n openshift-monitoring extract secret/alertmanager-main --keys=alertmanager.yaml
```

### PR DESCRIPTION
**Pull request by ctauchen**
This pull request changes all instances of `base64 -d` to `base64 --decode`, which makes these commands work on both Linux and Mac without unnecessary troubleshooting.

Across versions, macOS is inconsistent on the casing for the decoding option. In older versions, the `base64` command doesn't always have the lowercase option `-d`. In macOS 10.14.6, for example, the valid options for decoding are  `-D` and `--decode`.

* closes [GitHub Issue #28376](https://github.com/openshift/openshift-docs/issues/28376)
* applies to 4.5, 4.6, 4.7+
* QE @barleyer
* [Direct link (for one instance)](https://deploy-preview-31549--osdocs.netlify.app/openshift-enterprise/latest/monitoring/managing-alerts.html#applying-custom-alertmanager-configuration_managing-alerts)

### CODE REVIEW

**Comment by ctauchen** [comment]
@openshift/team-documentation for peer review please. Please can someone also add 'Peer Review Needed', 'branch/enterprise-4.5', 'branch/enterprise-4.6', 'branch/enterprise-4.7', and 'branch/enterprise-4.8' labels and 'Next Release' milestone? Thanks!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
