### PR TITLE
update sriov device discovery doc

### PR DESCRIPTION
**Pull request by zenghui-shi**
Fix dpConfigVersion example
Fix reference field for interface list

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, I didn't see this; Is it ready to go? For what versions? Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I didn't see this; Is it ready to go? For what versions? Thanks!

This is created against openshift-doc master for 4.4 release.
Once merged, it shall be cherry-picked to 4.3.

@pliurh PTAL.

**Comment by pliurh** [comment]
LGTM

**Comment by lamek** [comment]
LGTM. I'll merge and cherrypick to the correct versions.

**Pull request merged**
