### PR TITLE
OSSM-3535: Fixing Maistra version listed in common attribute file

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OSSM-3535

Link to docs preview: https://57251--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-create-smcp.html#ossm-control-plane-deploy-cli_ossm-create-smcp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@luksa please provide dev review.

**Comment by fjglira** [comment]
Hi, from QE LGTM

**Comment by luksa** [comment]
LGTM from dev

**Review by deerskindoll — APPROVED** [review]
lgtm

**Pull request merged**
