### PR TITLE
[OSDOCS-3790]: Add note about ensuring node is completely shut down.

### PR DESCRIPTION
**Pull request by emmahone**
Version(s):
main / 4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-3790

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

No current issues for this, but having the note should help prevent/warn customers about errantly tainting their nodes and causing FS corruption.

### CODE REVIEW

**Comment by emmahone** [comment]
@openshift/team-documentation or @kalexand-rh can I get a docs preview and review for this change? I used [IMPORTANT] but this might be better off having a warning / exclamation point instead. As long as a note explaining the risks is there I am happy.

**Comment by kalexand-rh** [comment]
@gaurav-nelson, do you know why netlify didn't pick this one up?

**Comment by kalexand-rh** [comment]
@lpettyjo, will you PTAL and loop in the best QE reviewer?

**Review by lpettyjo — COMMENTED** [review]
Please rewrite as:
"If the node is not completely shut down, do not proceed with tainting the node. If the node is still up and the taint is applied, filesystem corruption can occur."

**Comment by lpettyjo** [comment]
@radeore PTAL. Thanks!

**Comment by lpettyjo** [comment]
@emmahone please squash into one commit. Thanks!

**Comment by emmahone** [comment]
Syncing emmahone:main with openshift:main before my squash made things much more complicated here. Not sure how I want to untangle the mess I just created. I apologize for that. Should we close this PR and just have me make a new one without all the noise I just made?

**Comment by emmahone** [comment]
I think its cleaned up now. Sorry about that.

**Comment by emmahone** [comment]
@radeore Can you take another look so we can get this into the 4.13 docs at release?

**Review by sheriff-rh — COMMENTED** [review]
Performed a manual local build, and the IMPORTANT note appears in-line. Looks good! Merging.

**Pull request merged**
