### PR TITLE
OSDOCS-9855 branding fix

### PR DESCRIPTION
**Pull request by xJustin**
Small change to remove branding of possible third-party storage providers. 

Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-9855
Link to docs preview:

https://72572--ocpdocs-pr.netlify.app/openshift-rosa/latest/storage/container_storage_interface/persistent-storage-csi#csi-drivers-supported_persistent-storage-csi
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
thank you

**Comment by duanwei33** [comment]
Looks good to me (from QE side).

**Pull request merged**
