### PR TITLE
#CNV35091 - supportability vnc note

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.11+

Issue: [CNV-35091](https://issues.redhat.com//browse/CNV-35091)

Link to docs preview: https://68871--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-accessing-vm-consoles#vnc-console_virt-accessing-vm-consoles

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by geetikakay** [comment]
lgtm

**Comment by lahinson** [comment]
@sabrinajess I'm wondering if the reason this isn't showing up in the doc preview link because the module hasn't been added to the `virt-accessing-vm-consoles.adoc` assembly yet. It might be worthwhile to check that. I'm around for the rest of the day, but I will be on parental leave starting Monday (18 December). If you need to follow up on this one after today, please post in the #forum-ocp-docs-review channel on Slack.

**Comment by sabrinajess** [comment]
/label peer-review-needed

Requesting new peer review since I moved the content.

**Pull request merged**
