### PR TITLE
fixing typo "cassanda"

### PR DESCRIPTION
**Pull request by y-tabata**
Fixing typo "cassanda" to "cassandra".

### CODE REVIEW

**Comment by nekop** [comment]
Hold on. The parameter name `openshift_metrics_cassanda_pvc_storage_class_name` typo exists in Ansible playbook so this document typo is correct :roll_eyes:

We need to fix the openshift-ansible side first, I'll open a separate issue and follow up.

**Comment by nekop** [comment]
It's ok to merge this for 3.10+ releases. For 3.9 or older we need to wait for openshift-ansible fix.

**Comment by vikram-redhat** [comment]
@kalexand-rh - no QE required.

**Comment by kalexand-rh** [comment]
Thanks! @nekop, please open a new PR when you have a solution for versions 3.9 and before.

**Pull request merged**
