### PR TITLE
OCPBUGS-22329 Issue in file welcome/oke_about.adoc

### PR DESCRIPTION
**Pull request by libander**
[Replaces 68290](https://github.com/openshift/openshift-docs/pull/68290)

Version(s):
4.13+

Issue:
[OCPBUGS-22329 Issue in file welcome/oke_about.adoc](https://issues.redhat.com/browse/OCPBUGS-22329)

QE review:

 QE has approved this change.
Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@libander can you please link your preview? Thank you! Sorry I don't know where in the repo oke_about would be 🤷‍♀️ else I would look myself.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Comment by lahinson** [comment]
For peer-review purposes, I'm assuming that this is the correct preview link: https://69210--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/oke_about

**Review by lahinson — COMMENTED** [review]
lgtm

**Comment by libander** [comment]
> @libander can you please link your preview? Thank you! Sorry I don't know where in the repo oke_about would be 🤷‍♀️ else I would look myself.

Apologies, it hadn't generated right away yesterday.

**Comment by libander** [comment]
> For peer-review purposes, I'm assuming that this is the correct preview link: https://69210--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/oke_about

Yes, thank you!

**Pull request merged**
