### PR TITLE
OSDOCS-2906: Initial run of generating CLI docs for 4.10

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2906

Previews:
* https://deploy-preview-40656--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/developer-cli-commands.html
* https://deploy-preview-40656--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh I did an initial run for generating the CLI docs for 4.10. I'm seeing that these commands were removed. I'm just trying to see which, if any, we should note in the 4.10 release notes. 

* `oc ex dockergc` - Since this was under the experimental section (oc ex), I assume this doesn't need to be noted?
* `oc adm completion` - I'm not sure what this was ever used for (since I only see us referencing `oc completion` in the docs). Was this actually functional in 4.9, and should we note its removal in the 4.10 release notes?
* `oc adm config` - I'm not familiar with this command, and don't see it used anywhere in the docs. Should we note its removal in the 4.10 release notes?

**Comment by soltysh** [comment]
> @soltysh I did an initial run for generating the CLI docs for 4.10. I'm seeing that these commands were removed. I'm just trying to see which, if any, we should note in the 4.10 release notes.
> 
>     * `oc ex dockergc` - Since this was under the experimental section (oc ex), I assume this doesn't need to be noted?

Yeah, it was experimental and not being used for a while so it was dropped, I doubt we need to call this one out. 

>     * `oc adm completion` - I'm not sure what this was ever used for (since I only see us referencing `oc completion` in the docs). Was this actually functional in 4.9, and should we note its removal in the 4.10 release notes?
>     * `oc adm config` - I'm not familiar with this command, and don't see it used anywhere in the docs. Should we note its removal in the 4.10 release notes?
 
There's one more which was removed with these two it's `oc adm options`, all 3 were leftovers from the times when `oadm` existed, ie. a separate admin CLI. All three are duplicates from appropriate `oc` commands. Feel free to add them to release notes, but I doubt anyone was using them.

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review?

Previews:

* https://deploy-preview-40656--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/developer-cli-commands.html
* https://deploy-preview-40656--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html

**Pull request merged**
