### PR TITLE
OCPBUGS-16259: Corrected yaml formatting

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-16259

Link to docs preview (VPN required):
[Installing the Compliance Operator on Hosted control planes](https://file.rdu.redhat.com/antaylor/OCPBUGS-16259/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-hcp_compliance-operator-installation) (Step 5)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by sheriff-rh** [comment]
Merging!

**Pull request merged**
