### PR TITLE
ER-OBSDOCS-795: Fix rendering issue for power monitoing docs

### PR DESCRIPTION
**Pull request by eromanova97**
**OCP version(s)**: 4.14+

**Issue**: [OBSDOCS-795](https://issues.redhat.com/browse/OBSDOCS-795)

**Preview link**: https://71115--ocpdocs-pr.netlify.app/openshift-enterprise/latest/power_monitoring/power-monitoring-release-notes

- [x] **SME review**: @vimalk78 
- [x] **QE review**: @vprashar2929 
- [x] **Peer review**: @Srivaralakshmi 

**Additional information**: the issue can be seen on customer portal: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/power_monitoring/power-monitoring-release-notes

### CODE REVIEW

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Comment by Srivaralakshmi** [comment]
@ekristova I see that in the PR description, you have mentioned 1.14+ for the OCP version.

Did you mean 4.14+? Please clarify, as I am setting the labels. TY!

**Review by Srivaralakshmi — COMMENTED** [review]
@ekristova Neat PR! LGTM. Thank you! 

As I am new to the peer review squad, I would ask @bmcelvee to give my review the go-ahead. Please wait until Brandi applies the peer-review-done label.

**Comment by ekristova** [comment]
> @ekristova I see that in the PR description, you have mentioned 1.14+ for the OCP version.
> 
> Did you mean 4.14+? Please clarify, as I am setting the labels. TY!

Oh yes sorry! i am still influenced by GitOps and Pipelines docs :smile: It is corrected nowW

**Comment by Srivaralakshmi** [comment]
Thanks @ekristova!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
