### PR TITLE
OSDOCS-3796: Private/Public Subnet

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-3796](https://issues.redhat.com//browse/OSDOCS-3796)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-3796

Link to docs preview:
Page 1: https://58047--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html
Page 2: https://58047--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_architecture_sub/rosa-architecture-models.html
Page 3: https://58047--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xueli181114** [comment]
LGTM

**Review by wgordon17 — APPROVED** [review]
LGTM

**Review by kcarmichael08 — COMMENTED** [review]
I had a couple of formatting suggestions and I think one module needs an addition in the metadata, but otherwise lgtm!

**Pull request merged**
