### PR TITLE
OSDOCS-4646: add api tier and compatibility guidelines for microshift

### PR DESCRIPTION
**Pull request by dhellmann**
Version(s): 4.12

Link to docs preview:
https://54309--docspreview.netlify.app/microshift/latest/microshift_rest_api/understanding-api-support-tiers.html
https://54309--docspreview.netlify.app/microshift/latest/microshift_rest_api/understanding-compatibility-guidelines.html

QE review:
N/A -- MicroShift is Developer Preview
SME approval is required, the author is the approving SME

Additional information:

    We want to include compatiblity guidelines for the APIs in
    MicroShift. This PR updates the existing texts to leave out irrelevant
    sections for MicroShift and to include the modules in the topic map.

### CODE REVIEW

**Comment by dhellmann** [comment]
@ShaunaDiaz this is based in part on the discussion in OSDOCS-4646, but does not close that ticket. Let me know if I need to have another ticket in place to link to this PR.

**Comment by ShaunaDiaz** [comment]
@dhellmann You can use the existing OSDOCS-4646 ticket since we don't have a PR there yet. We can revise it, then make a new ticket for 4.13 with the remainder of the work that won't be done until then.

**Comment by ShaunaDiaz** [comment]
@dhellmann this looks good to me

You can replace the QE portion with:

QE review:
N/A -- MicroShift is Developer Preview
SME approval is required
Then if you are the approving SME, just note that.

When ready, plop the peer-review-needed label on it. When you get it back from peer review and made any changes needed, you can label it merge-review-needed.

**Comment by stevsmit** [comment]
Given that this is copied from OCP, I am not suggesting any textual edits at this time. I do believe the content should be revisited in the future, so that the original and MicroShift docs are both edited here.

**Pull request merged**
