### PR TITLE
CNV-24897: Doc: Wrong text on the page Virtualization\Node maintenance\About node maintenance

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.13, 4.12, 4.11

Issue: [CNV-24897](https://issues.redhat.com/browse/CNV-24897)

Link to docs preview:
https://55927--docspreview.netlify.app/openshift-enterprise/latest/virt/node_maintenance/virt-about-node-maintenance.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
/lgtm

**Pull request merged**
