### PR TITLE
The RuntimeDefault seccomp profile configuration is not exact.

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-3736

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
LGTM

**Review by kashyap-nirupma — COMMENTED** [review]
Hello team,

I just reviewed the requested PR, and in my opinion, the whole example should be updated to eflect that the seccompProfile should be added to the SCC instead of having it on the Pod specification. 

DefaultSeccomp Profile can be used using SCC instead of directly adding into pod specification that is failing. Please refer to the case# 03074930, where we resolved the issue by adding the DefaultSeccomp in the SCC under securityContext as follows instead of using it in the pod specifications:
~~~
seccompProfiles:
- "runtime/default"
~~~

You can also refer to the unpublished KCS[1] for more details. let me know in case you need anyfurther details.
[1] https://access.redhat.com/solutions/6529031

**Pull request merged**
