### PR TITLE
CNV-35121: Add MetalLB Operator to network post-install config

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-35121

OCP 4.12+

Preview: https://71820--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/post_installation_configuration/virt-post-install-network-config#installing-operators

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-in-progress

**Comment by jab-rh** [comment]
@sbeskin-redhat, looks like this needs a manual cherry-pick to 4.13 and 4.12.

**Comment by jab-rh** [comment]
@sbeskin-redhat, should this be included in 4.13 and 4.12? Thanks!

**Pull request merged**
