### PR TITLE
[OSDOCS-8170]: Release note about autorepair for hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-8170

Link to docs preview: https://66432--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-known-issues (scroll to the end of the Known issues list)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by jldohmann** [comment]
@lahinson the label bot doesn't seem to want to cooperate with you today 😭

**Comment by lahinson** [comment]
@jldohmann It really doesn't! Thanks for adding the label for me.

**Pull request merged**
