### PR TITLE
RHDEVDOCS 5646 clarify namespaces in CLI installation of Pipelines

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.10, pipelines-docs-1.11, pipelines-docs-1.12

Issue:

RHDEVDOCS 5646

Link to docs preview:

https://65852--docspreview.netlify.app/openshift-pipelines/latest/install_config/installing-pipelines#op-installing-pipelines-operator-using-the-cli_installing-pipelines

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
I think users can create a subscription with a specific param/env variable to disable the automatic installation. But I do not think it's documented anywhere (and not sure we want it to be documented ?)

**Review by ppitonak — APPROVED** [review]

**Pull request merged**
