### PR TITLE
BZ1756836 remove sidecars from note

### PR DESCRIPTION
**Pull request by bobfuru**
Per BZ [1756836](https://bugzilla.redhat.com/show_bug.cgi?id=1756836), remove sidecars from important note.
@chao007 Can I please get an ack?

### CODE REVIEW

**Comment by bobfuru** [comment]
@chao007 Bump

**Comment by chao007** [comment]
LGTM
Thanks

**Comment by bobfuru** [comment]
@openshift/team-documentation Please review and merge to 4.2 only

**Pull request merged**
