### PR TITLE
[srvls][SRVCOM-1290] Add image tag to must-gather images

### PR DESCRIPTION
**Pull request by abrennan89**
Applies for OCP 4.5+

### CODE REVIEW

**Comment by abrennan89** [comment]
Preview for QE/reviews: https://deploy-preview-32040--osdocs.netlify.app/openshift-enterprise/latest/serverless/serverless-support.html#serverless-about-collecting-data_serverless-support

**Comment by mgencur** [comment]
Looks good from QE point of view.

**Review by adellape — APPROVED** [review]
:+1:

**Pull request merged**
