### PR TITLE
Add OpenShift 4.17 APIs

### PR DESCRIPTION
**Pull request by jab-rh**
Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@kalexand-rh, I don't understand what this failure signifies or how to resolve it. This is a new error to me.

**Comment by kalexand-rh** [comment]
Aidan spotted the error: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_openshift-docs/80828/pull-ci-openshift-openshift-docs-main-validate-asciidoc/1828053430942306304#1:build-log.txt%3A197

I think it's this section: https://github.com/openshift/openshift-docs/pull/80828/files#diff-3ef3024dccea3b76ecce42e5e2e6b02fa7141020df788e43a98812defcb914d6R5915

**Pull request merged**
