### PR TITLE
[OSDOCS-10690]eu-north-1 region is missing from ROSA service definition

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10690
Link to docs preview:

(HCP) https://76567--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition.html#rosa-sdpolicy-regions-az_rosa-hcp-service-definition
Classic : https://76567--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-regions-az_rosa-service-definition 
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
great, thank you.

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
