### PR TITLE
OSDOCS-5255: Add temporary ROSA version snippet

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.12+ 

Issue:
https://issues.redhat.com/browse/OSDOCS-5255

Link to docs preview:
https://55864--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources.html#rosa-sts-ocm-roles-and-permissions_rosa-sts-about-iam-resources

https://55864--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.html

https://55864--docspreview.netlify.app/openshift-rosa/latest/rosa_cli/rosa-manage-objects-cli.html#rosa-create-cluster-command_rosa-managing-objects-cli

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by yuwang-RH** [comment]
LGTM.

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
