### PR TITLE
OSDOCS-11543: Upgrading- Classic-HCP migration

### PR DESCRIPTION
**Pull request by fmcdonal**
Version(s):
4.16+

https://issues.redhat.com/browse/OSDOCS-11543

Link to docs preview:
https://80813--ocpdocs-pr.netlify.app/openshift-rosa/latest/upgrading/rosa-hcp-upgrading.html

No QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by fmcdonal** [comment]
QE @Andrea Decorte approved the only change required here which was to remove the complete Troubleshooting section as it was referencing a KS article not applicable to HCP.

**Comment by fmcdonal** [comment]
the topic map had topics that were inherited incorrectly from rosa topic map and have also since been removed from rosa topic map: https://github.com/openshift/openshift-docs/blob/c47ab29aad7170fb4e491b56bbbf69eab0d4ef12/_topic_maps/_topic_map_rosa.yml#L699C16-L699C16

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
