### PR TITLE
Demo of collapsible code block and associated content

### PR DESCRIPTION
**Pull request by lbarbeevargas**
This PR is to demo adding the [`[%collapsible]` option](https://mrhaki.blogspot.com/2019/03/awesome-asciidoctor-collapsible-content.html) to large code blocks and content. If a code block includes notes or admonitions, you have to treat them as [nested delimited blocks](https://mrhaki.blogspot.com/2014/12/awesome-asciidoctor-nested-delimited.html).

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
[Demo](https://demo-collapsed-code-blocks--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-aws-config-yaml_installing-aws-customizations) of collapsed code block with >5 callouts. Also includes nested notes and admonitions.

**Comment by jboxman** [comment]
I've seen a few instances of this in the past; I skim pages, usually for examples, and if they're all hidden, I won't find the content I'm looking for.

**Comment by lbarbeevargas** [comment]
> I've seen a few instances of this in the past; I skim pages, usually for examples, and if they're all hidden, I won't find the content I'm looking for.

Good point @jboxman. We're going to poll the team to see what they think for longer code block examples (especially those in Installation).

**Comment by vikram-redhat** [comment]
> > I've seen a few instances of this in the past; I skim pages, usually for examples, and if they're all hidden, I won't find the content I'm looking for.
> 
> Good point @jboxman. We're going to poll the team to see what they think for longer code block examples (especially those in Installation).

Yeah good point. The thing to remember here is that this will only be used for those really long template installation files which are to be copy pasted into configuration sections and not actual code examples.

It does raise a good point about highlighting these collapsed segments better. @lbarbeevargas for the sake of the demo - possible to highlight the collapsed sections? We can agree on colors etc after the demo.

**Comment by lbarbeevargas** [comment]
@vikram-redhat Sounds good! I can adjust the CSS for the collapsed section title. I was going to bring that up during the demo as well--that `summary.title` will need to be styled.

**Comment by jboxman** [comment]
@lbarbeevargas FYI this provides all the necessary information for the customizations discussed on the call.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by lbarbeevargas** [comment]
[Demo](http://file.bos.redhat.com/lbarbeev/081020/demo-collapsed-code-blocks/installing/installing_aws/installing-aws-customizations.html#installation-aws-config-yaml_installing-aws-customizations) of collapsed code block with >5 callouts. Also includes nested notes and admonitions.

[Demo](http://file.bos.redhat.com/lbarbeev/081020/demo-collapsed-code-blocks/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account) of collapsed lists, which included nested notes.

**Comment by lbarbeevargas** [comment]
Note: The arrow does not show up in Firefox.

**Comment by lbarbeevargas** [comment]
New demos with "Collapse/Expand all" button at top of each page:

- http://file.bos.redhat.com/lbarbeev/08262020/demo-collapsed-code-blocks/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account
- http://file.bos.redhat.com/lbarbeev/08262020/demo-collapsed-code-blocks/installing/installing_aws/installing-aws-customizations.html#installation-aws-config-yaml_installing-aws-customizations

**Comment by lbarbeevargas** [comment]
New demo with "Collapse/Expand all" button at each module with collapsible content:
http://file.bos.redhat.com/lbarbeev/08312020/demo-collapsed-code-blocks/storage/persistent_storage/persistent-storage-efs.html#efs-authorization_persistent-storage-efs

**Comment by lbarbeevargas** [comment]
[Preview](http://file.bos.redhat.com/lbarbeev/10192020/demo-collapsed-code-blocks/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account) as of 10/19/2020 - "Collapse/Expand all" button is now added via javascript and not by including a module before the collapsed content.

**Comment by lbarbeevargas** [comment]
Closing this PR because the work was completed in a separate [PR-26605](https://github.com/openshift/openshift-docs/pull/26605).

**Pull request closed without merging**
