### PR TITLE
BZ#2097632: Added note about traffic on pod network vNICs

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.10+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2097632

Link to docs preview: http://file.rdu.redhat.com/sjhala/BZ2097632/virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by fabiand** [comment]
lgtm

@phoracek please review

**Review by phoracek — APPROVED** [review]
LGTM

**Review by jldohmann — APPROVED** [review]
/lgtm

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
