### PR TITLE
OCPBUGS#17152: Moving YAML to snippets

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.10+
Issue:

https://issues.redhat.com/browse/OCPBUGS-17152
Link to docs preview:

https://63562--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/installing-operators#network-observability-auth-mutli-tenancy_network_observability
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@nathan-weinberg @jpinsonneau not urgent, but when you have a moment, can you PTAL at these updates to the Configuring authorization and multi-tenancy YAML?

**Comment by nathan-weinberg** [comment]
@skrthomas Just to clarify, are we changing any content here or just the formatting of the existing content?

**Review by jpinsonneau — APPROVED** [review]

**Comment by skrthomas** [comment]
@nathan-weinberg This is just a reformatting of the content, not any new changes.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
