### PR TITLE
fix wrongful references to 4.6 content in cnf docs

### PR DESCRIPTION
**Pull request by yuvalk**

### CODE REVIEW

**Comment by yuvalk** [comment]
this is a fix to https://bugzilla.redhat.com/show_bug.cgi?id=1940460

**Comment by kquinn1204** [comment]
@ahardin-rh Is this something you can merge? It is an update to docs for incorrect 4.6 refs which should have been updated to 4.7.

**Comment by vikram-redhat** [comment]
Not sure if this should go in the master branch first. @ahardin-rh?

**Comment by yuvalk** [comment]
> Not sure if this should go in the master branch first. @ahardin-rh?

I'll open a PR for that too, NP

**Comment by yuvalk** [comment]
https://github.com/openshift/openshift-docs/pull/30838

**Pull request closed without merging**
