### PR TITLE
Bug 1542724 Add additional router metrics env var to docs

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1542724

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bmcelvee - is this ready for QE/SME/Peer review?

**Comment by bmcelvee** [comment]
@mburke5678 would you mind taking a look at this please? I can't seem to get the link to the Router environment variables working. 

Thanks! :icecream:

**Comment by bfallonf** [comment]
@bmcelvee Do you mean from line 61 in the haproxy file? Because the topics directory is not matching up well with the assembly file? Because of the modularization, it should be able to link to the assembly, but with the full path (because that's where the anchor is). So:

See router xref:../../architecture/networking/routes.adoc#env-variables[route environment variables] section for more information.

Sorry if I'm wrong or if I'm telling you what you already know... We came across this when I first moved the architecture stuff around.

**Comment by bmcelvee** [comment]
Thanks, @bfallonf! That worked. :smile_cat:

**Pull request merged**
