### PR TITLE
BZ-1691204: Adding note that it is unsupported to use unsupportedConf…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…igOverrides field

https://bugzilla.redhat.com/show_bug.cgi?id=1691204

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sferich888 Can you review this statement for the unsupportedConfigOverrides field?

Preview: https://bz-1691204--ocpdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-between-minor.html

FYI @mpbarrett @vikram-redhat in case you have any feedback on the statement.

**Comment by mburke5678** [comment]
@bergerhoffer The _It is unsupported to use_ wording feels awkward to me. Maybe something like: 

`Using the `unsupportedConfigOverrides` section to modify an Operator's configuration is unsupported and will block cluster upgrades. You must remove this setting before you can upgrade your cluster.`

**Comment by bergerhoffer** [comment]
Love it @mburke5678, thanks for the suggestion! Updated.

**Comment by mburke5678** [comment]
@bergerhoffer LGTM!

**Comment by bergerhoffer** [comment]
@xingxingxia Could you please review this update? Thanks!

Preview: https://bz-1691204--ocpdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-between-minor.html

**Comment by xingxingxia** [comment]
LGTM

**Pull request merged**
