### PR TITLE
CNV-22625: Update doc HCO variable 4.12.3

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.12.3

Issue: [CNV-22625](https://issues.redhat.com/browse/CNV-22625)

Link to docs preview: To verify HCO variable update to 4.12.3, see the Files changed in this PR.

QE review: N/A

Additional information: This PR must not be merged until errata has been shipped.

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by aspauldi** [comment]
/ merge-review-needed

**Pull request merged**
