### PR TITLE
OSSM 1.1.3 release notes

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSMDOC-66
Release notes for OSSM 1.1.3

Cherry pick to 4.2-4.5.

### CODE REVIEW

**Comment by neal-timpe** [comment]
@objectiser Can you take a look at the release note for TRACING-1208? I tried to add you as a reviewer.

**Review by objectiser — APPROVED** [review]

**Review by yxun — APPROVED** [review]

**Review by JStickler — APPROVED** [review]

**Review by rcernich — APPROVED** [review]
lgtm

**Pull request merged**
