### PR TITLE
[WIP] [DO NOT MERGE] [RHDEVDOCS-5452] Bump versions to 1.12

### PR DESCRIPTION
**Pull request by krishnanshruthi**
Do not merge before the Pipelines 1.12 GA

Version(s):
4.12+

Issue: https://issues.redhat.com/browse/RHDEVDOCS-5452

Links to doc preview: 

https://65179--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html#installing-pipelines-as-code-cli_using-pipelines-as-code

https://65179--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/tkn_cli/installing-tkn.html

Download links don't work yet. They need to be checked shortly before merging.

QE review: @ppitonak , @rupalibehera 

 QE has approved this change.

### CODE REVIEW

**Review by mramendi — APPROVED** [review]

**Review by ppitonak — APPROVED** [review]

**Comment by mramendi** [comment]
peer review LGTM

**Comment by mramendi** [comment]
This needs to also be cherry-picked to pipelines-docs-4.12 please. The cherry-pick should work automatically I think

**Comment by piyush-garg** [comment]
lgtm

**Review by vdemeester — APPROVED** [review]

**Comment by krishnanshruthi** [comment]
Please **DO NOT** merge this issue. The intention is to keep the **PRs merge ready with all approvals**. The PR merging can happen only on the **GA date (September 26th)**. So please hold off merging until I let you know. thank you!

**Review by khrm — APPROVED** [review]

**Comment by opayne1** [comment]
Does the 1.11 [here](https://65179--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html#creating-a-github-application-in-administrator-perspective_using-pipelines-as-code) need to be updated to 1.12?
otherwise /lgtm

**Comment by ppitonak** [comment]
> Does the 1.11 [here](https://65179--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html#creating-a-github-application-in-administrator-perspective_using-pipelines-as-code) need to be updated to 1.12? otherwise /lgtm

IMHO we can remove the `pipelines-1.11` string altogether.

**Comment by krishnanshruthi** [comment]
> > Does the 1.11 [here](https://65179--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html#creating-a-github-application-in-administrator-perspective_using-pipelines-as-code) need to be updated to 1.12? otherwise /lgtm
> 
> IMHO we can remove the `pipelines-1.11` string altogether.

Removed: https://github.com/openshift/openshift-docs/pull/65179/commits/67f8c00d011354e94e548b803bf67b28ffd01329

**Comment by ppitonak** [comment]
FYI all links are live now and I verified that they work

**Comment by mramendi** [comment]
The PR is not getting merged after all. I am working on RHDEVDOCS-5669 that will remove the need for such PRs.

**Comment by krishnanshruthi** [comment]
Closing this PR as Mikhail is handling this PR through https://issues.redhat.com//browse/RHDEVDOCS-5669

**Pull request closed without merging**
