### PR TITLE
OSDOCS-10266: Add links to Red Hat OpenShift Network Calculator

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-10266

Link to docs preview:

https://74741--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/configuring-cluster-network-range#configuring-cluster-network-range-additional-resources

https://74741--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#migrate-from-openshift-sdn-additional-resources

https://74741--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/#supported-platforms-for-openshift-clusters_ocp-installation-overview

https://74741--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/#installation-process_ocp-installation-overview

No QE review required.

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]

**Comment by CFields651** [comment]
LGTM!  Thanks!

**Pull request merged**
