### PR TITLE
OSDOCS#10152: Added ARM64 to the Supported Architectures table

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.14+

Issue:
[OSDOCS-10152](https://issues.redhat.com/browse/OSDOCS-10152)

Link to docs preview:
[Architecture and operating system support for Operators](https://75862--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-generating-csvs.html#olm-arch-os-support_osdk-generating-csvs)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@Prashanth684 
Could you please review this PR?
Thanks!

**Comment by sr1kar99** [comment]
@jeffdyoung 
Could you please review this PR?
Thanks!

**Review by bhardesty — COMMENTED** [review]
LGTM!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
