### PR TITLE
UPSTREAM: 30817: more explictly about NoDiskConflicts policy and applicable volume types

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by childsb** [comment]
[test]

**Comment by childsb** [comment]
Not sure about the title on this one.  It's not 1:1 with the upstream docs change, but its the same issue/fix.

**Comment by childsb** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1339975

**Comment by ahardin-rh** [comment]
@rootfs @childsb I am resurrecting this old PR :ghost: Is this still valid, or should I close it? Thanks!

**Comment by rootfs** [comment]
yes, still valid, thanks

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
