### PR TITLE
Pipelines are wrongly mentioned in the Forwarding to Azure Monitor Logs section

### PR DESCRIPTION
**Pull request by prithvipatil97**
- Pipelines are wrongly mentioned in the Advanced configuration options of Forwarding to Azure Monitor Logs sections.

- Here is the documentation link: https://docs.openshift.com/container-platform/4.16/observability/logging/log_collection_forwarding/configuring-log-forwarding.html#logging-forwarding-azure_configuring-log-forwarding

- Here are the current `Advanced configuration options` part: 
~~~ 
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
  - name: azure-monitor
    type: azureMonitor
    azureMonitor:
      customerId: my-customer-id
      logType: my_log_type
      azureResourceId: "/subscriptions/111111111" 
      host: "ods.opinsights.azure.com" 
    secret:
       name: my-secret
  pipelines:
   - name: app-pipeline          <<=== Wrong Indentation
    inputRefs:
    - application
    outputRefs:
    - azure-monitor
~~~

- Due to this ClusterLogForwarder can not get applied. It streams the following errors:

~~~
Error parsing YAML: YAMLException: bad indentation of a sequence entry at line 19, column 5:  
inputRefs: 

Error parsing YAML: YAMLException: bad indentation of a sequence entry at line 20, column 5:
- application

Error parsing YAML: YAMLException: bad indentation of a sequence entry at line 21, column 5:  outputRefs:

Error parsing YAML: YAMLException: bad indentation of a sequence entry at line 22, column 5:
- azure-monitor 
~~~

- Here is the correct indentation for `Advanced configuration options` part: 
~~~
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
  - name: azure-monitor
    type: azureMonitor
    azureMonitor:
      customerId: my-customer-id
      logType: my_log_type
      azureResourceId: "/subscriptions/111111111" 
      host: "ods.opinsights.azure.com" 
    secret:
       name: my-secret
  pipelines:
  - name: app-pipeline              <== Correct indentation
    inputRefs:
    - application
    outputRefs:
    - azure-monitor
~~~

Version(s):

RHCOP 4.16 
RHOCP 4.15 
RHOCP 4.14 
RHOCP 4.13

Issue:

https://issues.redhat.com/browse/OBSDOCS-1574

Link to docs preview:

https://86486--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html

https://86486--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html

https://86486--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by prithvipatil97** [comment]
Hello Team,
This PR has been linked to https://github.com/openshift/openshift-docs/pull/86391

I was facing a technical error while squashing the recent commit.
Hence I have created this similar new PR.

Peer review is done for this PR.
QE also approved it.

Kindly take a look at the linked PR, and hopefully, we can proceed with the merge review now.
So I am adding the merge review label.

Regards,
Prithviraj Patil

**Comment by skrthomas** [comment]
As stated by @prithvipatil97 , the prior ACKS are here: https://github.com/openshift/openshift-docs/pull/86391. I will go forward with merge.

**Pull request merged**
