### PR TITLE
OADP-2328: Label selector syntax not correct in Backup CR

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [OADP-2328](https://issues.redhat.com/browse/OADP-2328)

### VERSION

* OCP 4.12 → branch/enterprise-4.12
* OCP 4.13 → branch/enterprise-4.13
* OCP 4.14 → branch/enterprise-4.14
* OCP 4.15 → branch/enterprise-4.15
* OCP 4.16 → branch/enterprise-4.16

### Link to docs preview:

* [Creating a Backup CR](https://76043--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.html) 

### QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by anarnold97** [comment]
@stillalearner - Please can you review this PR for me?

Thanks

**Review by stillalearner — APPROVED** [review]
lgtm

**Review by bhardesty — COMMENTED** [review]
LGTM!

One minor suggestion (which is out of scope): the callouts in the yaml codeblock should be commented out (https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#using-asciidoc-callouts-in-the-yaml).

**Pull request merged**
