### PR TITLE
CNV-16553: Release notes: NEW (VM Backup and Restore with OADP (GA))

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14

Issue: [CNV-16553](https://issues.redhat.com/browse/CNV-16553)

Link to docs preview: [New and changed features](https://63243--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-new) 

QE review: Dev in lieu of QE, per CS suggestion

### CODE REVIEW

**Comment by aspauldi** [comment]
@aglitke , Can you please review this 4.14 release note? Thanks.

**Comment by aspauldi** [comment]
@kgoldbla@redhat.com, Can you review this for me? Thanks.

**Review by aglitke — APPROVED** [review]
lgtm

**Comment by aspauldi** [comment]
@kgoldbla@redhat.com, okay from a QE perspective?

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by cbippley** [comment]
As I am still in training please wait for another reviewer to ack before requesting merge review. 
/label peer-review-done
/remove-label peer-review-in-progress

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
