### PR TITLE
BZ-2012753 Updated ipi install prereqs to include firewall port config

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2012753

**For: Version 4.8+**

Doc Preview: https://deploy-preview-42104--osdocs.netlify.app

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Comment by ogradyp** [comment]
LGTM

**Comment by pamoedom** [comment]
Hi @ktothill, one question, the section embedded into IPI BM prerequisites is a link to `https://docs.openshift.com/container-platform/4.8/installing/install_config/configuring-firewall.html` or a copy of the same content? I'm asking thinking on future maintenance in case of modifications, thanks.
Also, I'm not sure why we should duplicate that info there when the Firewall configuration is common to all installations within `Installation configuration` section, if some customer has a Firewall in the middle, they should consult that section.

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by ktothill** [comment]
Date and Time: April 22, 2022  13:27
Summary: Closing PR, due to insufficient data, per Pedro's [request](https://bugzilla.redhat.com/show_bug.cgi?id=2012753#c13).

**Comment by ktothill** [comment]
Date and Time: April 22, 2022  13:27
Summary: Closing PR, due to insufficient data, per Pedro's [request](https://bugzilla.redhat.com/show_bug.cgi?id=2012753#c13).

**Pull request closed without merging**
