### PR TITLE
OCPBUGS#3803: Add Qatar Central region to azure installation docs

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.11 only

Issue: https://issues.redhat.com/browse/OCPBUGS-3803

Link to docs preview: https://56446--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account.html#installation-azure-regions_installing-azure-account

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Amrita42** [comment]
lgtm

**Comment by Amrita42** [comment]
peer-review-in-progress

**Comment by ousleyp** [comment]
LGTM! Merging now.

**Pull request merged**
