### PR TITLE
Update SR-IOV marketplace channel jsonpath

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/pull/20060

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, does this look correct? Thanks!

**Comment by jboxman** [comment]
@zshi-redhat, I think this also needs to be merged?

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I think this also needs to be merged?

@jboxman hi sorry for the late reply. Yes this needs to be merged in release-4.2 branch.

**Comment by jboxman** [comment]
@zshi-redhat, cool.

I didn't for this, but at some point we can probably replace every instance of _4.x_ with `{product-version}`, which always yields the major and minor version of OpenShift for each branch.

**Pull request merged**
