### PR TITLE
Add example of custom node groups

### LINKED ISSUE #12520: Add example of custom node groups
### Which section(s) is the issue in?
../install/configuring_inventory_file.adoc
-> configuring-inventory-defining-node-group-and-host-mappings
-> configuring-inventory-mapping-hosts-to-node-group

https://docs.okd.io/latest/install/configuring_inventory_file.html#configuring-inventory-defining-node-group-and-host-mappings
https://docs.okd.io/latest/install/configuring_inventory_file.html#configuring-inventory-mapping-hosts-to-node-groups

### What needs fixing?
Both openshift_node_groups and name mapping are explained, however how to extend node groups and make use of custom names and mapping would be benefited with a further example.

### PR DESCRIPTION
**Pull request by thomasdstewart**
Fix #12520

### CODE REVIEW

**Comment by kalexand-rh** [comment]
This sounds reasonable to me. @jianlinliu, will you PTAL? (I'm pretty sure this changed in 3.10. Let me know if I'm remembering wrong.)

**Comment by jianlinliu** [comment]
LGTM. Yeah, this is supported since 3.10.

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
