### PR TITLE
Document disk requirements other than /var

### PR DESCRIPTION
**Pull request by rhcarvalho**
Documentation part of RFE https://github.com/openshift/openshift-ansible/issues/4413.

Disk requirements verification implemented in https://github.com/openshift/openshift-ansible/pull/4436.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@adellape PTAL

**Comment by adellape** [comment]
@rhcarvalho LGTM :+1: 

Looking at https://github.com/openshift/openshift-ansible/pull/4436, looks like it's for 3.5+? Is it already shipped in the 3.5 installer or waiting on the next errata?

**Comment by rhcarvalho** [comment]
Thanks @adellape!

> it's for 3.5+? Is it already shipped in the 3.5 installer or waiting on the next errata?

Certainly was not shipped in 3.5. Even without the explicit check in the installer, it is recommendable to have some spare disk in those locations, so I'll leave it up to the docs team if you want to backport it or just have it for 3.6+.

**Comment by adellape** [comment]
[rev_history]
|xref:../install_config/install/prerequisites.adoc#install-config-install-prerequisites[Installing a Cluster -> Prerequisites]
|Added disk requirements other than *_/var/_*.
%

**Pull request merged**
