### PR TITLE
[SRVOCF-617] Update installing func-s2i and func-deploy tasks

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.34+

Issue:
https://issues.redhat.com/browse/SRVOCF-617

Link to docs preview:
- https://83142--ocpdocs-pr.netlify.app/openshift-serverless/latest/functions/serverless-functions-creating.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by tmalove — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
