### PR TITLE
Bug 1396340 Update to example daemonset definition

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1396340

### CODE REVIEW

**Comment by bmcelvee** [comment]
@mburke5678 @ahardin-rh peer review please 😺

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by mburke5678** [comment]
LGTM2

**Comment by mdshuai** [comment]
@bmcelvee there is two issue in this bug, you only fix one.
1. unable to decode "foo.yaml": json: cannot unmarshal array into Go value of type unversioned.TypeMeta
2. name error in fixed in the current pr.

The ' unable to decode....' also need fix, please remove "-" in the yaml file first line and make foo.yaml aligned.

**Comment by bmcelvee** [comment]
Thanks, @mdshuai! I removed the hyphen and extraneous spaces.

**Comment by mdshuai** [comment]
LGTM, thanks

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../admin_guide/manage_authorization_policy.adoc#admin-guide-manage-authorization-policy[Managing Authorization Policies]
|Updated the ClusterRole file in the xref:../admin_guide/manage_authorization_policy.adoc#admin-guide-granting-users-daemonset-permissions[Granting Users Daemonset Permissions] section.
%

**Comment by bmcelvee** [comment]
Thanks all!

**Comment by vikram-redhat** [comment]
@bmcelvee - needs a milestone.

**Comment by bmcelvee** [comment]
Thanks, @vikram-redhat!

**Pull request merged**
