### PR TITLE
Uninclude the IBM Z installation docs

### PR DESCRIPTION
**Pull request by rh-max**

### CODE REVIEW

**Comment by rh-max** [comment]
@bergerhoffer Could you PTAL and merge + cherry-pick into `enterprise-4.4`? Thank you.

**Comment by bergerhoffer** [comment]
@rh-max Sure, though did you check with @vikram-redhat on whether this needs to go through the change control process?

**Comment by bergerhoffer** [comment]
Worked with @rh-max, @aheslin, and Marci Wolfe to confirm that the necessary acks were received, and that an email is sent out to the appropriate OpenShift lists notifying of this change.

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Pull request merged**
