### PR TITLE
Updating ROSA docs to match AWS docs in regards to NLB, ELB, CLB, etc. 

### PR DESCRIPTION
**Pull request by mletalie**
Changing Elastic Load Balancers to Elastic Load Balancing

Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-4915
https://issues.redhat.com/browse/OSDOCS-5440
Link to docs preview:

QE review:
- [x] QE has approved this change.

**QE review N/A**
Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
1) https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html#rosa-elastic-load-balancers_prerequisites

2) 

3) https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_support/rosa-troubleshooting-deployments.html#rosa-troubleshooting-elb-service-role_rosa-troubleshooting-cluster-deployments

4)https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html#rosa-elastic-load-balancers_prerequisites
5) https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html#rosa-account_rosa-sts-aws-prereqs

6)https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_support/rosa-troubleshooting-deployments.html#rosa-troubleshooting-elb-service-role_rosa-troubleshooting-cluster-deployments

7https://55321--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html#rosa-account_rosa-sts-aws-prereqs)

**Comment by codymant** [comment]
@mletalie lgtm!

**Comment by mburke5678** [comment]
I cannot vouch for the technical accuracy of the changes; but, from a docs perspective /lgtm

**Comment by mletalie** [comment]
Hello @mburke5678, 
    Thanks for taking a look at this issue. Given this change was a direct result of input from our counterpart over at AWS (who was asking that we change some AWS terminology to match their docs), I think we should be good. The AWS TW also signed off, FWIW, and I do not think this warrants a QE review based on the context. Hope that helps, and thanks again! 
/merge-review-needed

**Review by arendej — COMMENTED** [review]
LGTM

**Pull request merged**
