### PR TITLE
[BZ1869315]: Change the playbook name

### PR DESCRIPTION
**Pull request by xenolinux**
OCP version 3.11
QE contact @sunzhaohua2 
[Preview](https://deploy-preview-42875--osdocs.netlify.app/openshift-enterprise/latest/admin_guide/cluster-autoscaler.html#deploying-cluster-auto-scaler-cluster-auto-scaler)
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1869315)

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
Due to the repo freeze, can't merge this today. Please ping after the repo is unfrozen for a merge!

**Comment by xenolinux** [comment]
@bergerhoffer Hello! This PR is ready to merge. Can you please merge this PR?

**Pull request merged**
