### PR TITLE
ROX-20706: Add pull secret info

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

4.1+

[Issue](https://issues.redhat.com/browse/ROX-20706)

Links to docs preview:

- non-OCP, Helm w/o customization: https://68724--docspreview.netlify.app/openshift-acs/latest/installing/installing_other/install-secured-cluster-other#installing-secured-cluster-services-quickly_install-secured-cluster-other
- non-OCP, Helm w/ customization: https://68724--docspreview.netlify.app/openshift-acs/latest/installing/installing_other/install-secured-cluster-other#install-secured-cluster-services-helm-chart_install-secured-cluster-other
- OCP, Helm w/o customizations: https://68724--docspreview.netlify.app/openshift-acs/latest/installing/installing_other/install-secured-cluster-other#install-secured-cluster-services-helm-chart_install-secured-cluster-other
- OCP, Helm w/ customizations: https://68724--docspreview.netlify.app/openshift-acs/latest/installing/installing_ocp/install-secured-cluster-ocp#install-secured-cluster-services-helm-chart_install-secured-cluster-ocp

QE review:
- [x] QE has approved this change.

Additional information:
Also added conditionals so that OCP info doesn't appear on non-OCP pages, and Kubernetes info doesn't appear on OCP pages.

### CODE REVIEW

**Comment by ludydoo** [comment]
Hey, I think the command `helm install -n stackrox --create-namespace \ ...` should include the 
```
--set imagePullSecrets.username=<username> \
--set imagePullSecrets.password=<password> 
```
commands

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
