### PR TITLE
JSON flows format reference updates

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.11+
Issue:

https://issues.redhat.com/browse/OSDOCS-7660

Link to docs preview:

https://64764--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/json-flows-format-reference
QE review:
- [X] QE has approved this change.

Additional information:

Doc generated from: https://github.com/netobserv/network-observability-operator/pull/417

### CODE REVIEW

**Review by jotak — APPROVED** [review]
LGTM!

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by kelbrown20 — COMMENTED** [review]
Hi Sara! This all LGTM, great work!

**Pull request merged**
