### PR TITLE
SRVCOM-2381 Info on selecting channel for Serverless operator other than stable

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
Serverless 1.29+

Issue:
https://issues.redhat.com/browse/SRVCOM-2381

Link to docs preview:
Step 4c in procedure: https://60662--docspreview.netlify.app/openshift-serverless/latest/install/install-serverless-operator.html#serverless-install-web-console_install-serverless-operator
First item in the description of the snippet: https://60662--docspreview.netlify.app/openshift-serverless/latest/install/install-serverless-operator.html#serverless-install-cli_install-serverless-operator

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Comment by rh-max** [comment]
> LGTM from QE

Thanks Martin!

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
