### PR TITLE
[RHACS] Fix Travis build for `openshift-acs` distro

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Travis build for RHACS docs

### CODE REVIEW

**Comment by kcarmichael08** [comment]
So I managed to fix the first issue with this: https://github.com/openshift/openshift-docs/pull/44203/commits/15d2e27818efe223956e1baffe92f17fc7f7fdbc

second issue, no luck yet :(

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
