### PR TITLE
OSDOCS-1650: Release notes for managing user OAuth access tokens

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1650

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Depends on #28506 being merged before the xref will work.

**Comment by bergerhoffer** [comment]
@sttts @rhpmali here is the release notes update for managing user OAuth access tokens. I don't currently have a preview because the link is dependent on the other PR, so if you can just worry about the text for now. Thanks!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
