### PR TITLE
OSDOCS-3899: Add ap-southeast-3 Jakarta region to OSD and ROSA service definition

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.11, 4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-3899

Link to docs preview:
OSD: http://file.rdu.redhat.com/bmcelvee/OSDOCS-3899/osd_architecture/osd_policy/osd-service-definition.html#regions-availability-zones_osd-service-definition
ROSA: http://file.rdu.redhat.com/bmcelvee/OSDOCS-3899/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-regions-az_rosa-service-definition

The only new content added was: 
`* ap-southeast-3 (Jakarta)`

I changed the formatting of the bullets in the ROSA documentation to match the standard OpenShift style.

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by arendej** [comment]
opt-in is required for ap-southeast-3

**Pull request merged**
