### PR TITLE
Update links to Rosa CLI download

### PR DESCRIPTION
**Pull request by kmccarron-rh**
Jira: https://issues.redhat.com/browse/OSDOCS-1951

Here are direct links to the preview:
See Step 1 in Setting up the rosa CLI
https://deploy-preview-30695--osdocs.netlify.app/openshift-rosa/latest/rosa_cli/rosa-get-started-cli.html#rosa-setting-up-cli_rosa-getting-started-cli

See Step 4 in Setting up the environment:
https://deploy-preview-30695--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-setting-up-environment.html#rosa-setting-up-environment_rosa-setting-up-environment

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
Review requested:
@jeremyeder, @vkareh

@yufchang - Just a heads-up, this will require QE ack.
Thanks all!

**Comment by sfortner-RH** [comment]
LGTM!

**Comment by 0kashi** [comment]
In Step 1
- Can we mark #2 as recommended instead of optional since thats is how the CLI is referred to throughout the documentation?
- Can we mark #3 as optional?
- #4 seems out of place.  At this point they have not set up a user, let alone granted it cluster-admin. Would it make more sense to have them just run `rosa` to see that it is recognized?

**Comment by sfortner-RH** [comment]
Karen can address the first two bullets, but I don't have an answer for #4. This content was already SME and QE-acked, so the only new change is the link update. But I see your point. Right now this is part of the CLI guide: https://docs.openshift.com/rosa/rosa_cli/rosa-get-started-cli.html

Would #4 fit better under "Using the Bash Script"? https://docs.openshift.com/rosa/rosa_cli/rosa-get-started-cli.html#rosa-using-bash-script_rosa-getting-started-cli

**Comment by 0kashi** [comment]
This would fit under the granting cluster-admin section which is already there.  Can we just remove it from here?

**Comment by sfortner-RH** [comment]
Works for me!

**Review by sfortner-RH — APPROVED** [review]
LGTM! Thanks for the updates Karen. Ready for QE.

**Comment by kmccarron-rh** [comment]
@sfortner-RH - QE ack received in the card. Looks like we are good to merge!

**Pull request merged**
