### PR TITLE
BZ1639375 - updating prereqs for the router wildcard

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1639375

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gpei, will you PTAL or help me find the right reviewer?

**Comment by gpei** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
Thank you both! Merging.

**Pull request merged**
