### PR TITLE
MIG-1330 Issue in file migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: 
https://issues.redhat.com/browse/MIG-1330
https://github.com/openshift/openshift-docs/issues/50593

OCP 4.10+

Preview:
https://61274--docspreview.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/installing-3-4.html#migration-installing-legacy-operator_installing-3-4
https://61274--docspreview.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/upgrading-3-4.html#migration-upgrading-mtc-with-legacy-operator_upgrading-3-4

### CODE REVIEW

**Comment by sbeskin-redhat** [comment]
@joaquinfll 
Please check this PR.

**Comment by joaquinfll** [comment]
Awesome, this looks great. Thank you.

**Comment by sbeskin-redhat** [comment]
@midays 
Please take a look at this PR.

**Review by midays — APPROVED** [review]
LGTM, thanks for the change

**Review by maxwelldb — APPROVED** [review]

**Comment by sbeskin-redhat** [comment]
@skrthomas 
Hi,
When can I expect this PR to be merged? 
Thank you

**Comment by skrthomas** [comment]
@sbeskin-redhat Sorry about that. I think I began review and then lost this PR. Taking a look now, but I think all is good for merging so I can go ahead with that. Thanks for pinging me about it.

**Review by skrthomas — APPROVED** [review]
Merge review lgtm

**Pull request merged**
