### PR TITLE
Updating to make saving the catalog to disk optional

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4298

Link to docs preview:
https://53749--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-oci-format_installing-mirroring-disconnected

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sherine-k @lmzuccarelli For review please!

preview: https://53749--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-oci-format_installing-mirroring-disconnected

**Review by sherine-k — APPROVED** [review]
Thank you so much @bergerhoffer ! This is great

**Comment by lmzuccarelli** [comment]
@bergerhoffer - Thanks again, contents look good

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review?

https://53749--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-oci-format_installing-mirroring-disconnected

**Pull request merged**
