### PR TITLE
[enterprise-4.14] HCCDOC-1415 Insights Operator RN tech preview features

### PR DESCRIPTION
**Pull request by xJustin**
Insights Operator RN -> Technology Preview Features 

Version(s):
4.14

Issue:
[HCCDOC-1415](https://issues.redhat.com//browse/HCCDOC-1415)

Link to docs preview:

https://65067--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-insights-operator
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tremes** [comment]
Thanks!
/lgtm

**Comment by xJustin** [comment]
@JoaoFula can you please take a look?

**Comment by JoaoFula** [comment]
LGTM

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
