### PR TITLE
HCIDOCS-549: Add iLO6 to our supported hardware

### PR DESCRIPTION
**Pull request by kdrake20**
**Fixes:** [HCIDOCS-549](https://issues.redhat.com/browse/HCIDOCS-549)

**For:** OCP 4.16, 4.17, 4.18

[**Preview**](https://85304--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/ipi/ipi-install-prerequisites.html#ipi-install-firmware-requirements-for-installing-with-virtual-media_ipi-install-prerequisites)

**Approvals -** `/lgtm`:
- [x] SME
- [x] QE
- [x] Peer Review

### CODE REVIEW

**Comment by kdrake20** [comment]
@sgoveas, thanks so much for providing that 11th gen table. 
Is the firmware version of 1.57 or later correct?
I'm just double-checking, because version 2.63 is much later and is in 10th Gen.
Thanks!

**Comment by kdrake20** [comment]
**Who:**
@iurygregory, SME
@sgoveas, QE

Summary: Hello! Could you please review this content? Please provide feedback directly in the PR.
Comment `/lgtm` if no changes are required. Thank you!

Next Steps:

- [ ] Receive `/lgtm` from SME
- [ ] Receive `/lgtm` from QE

**Comment by sgoveas** [comment]
Hi @kdrake20 
Yes, the firmware version is correct for iLO6 GEN11

/lgtm

**Review by opayne1 — APPROVED** [review]

**Pull request merged**
