### PR TITLE
Fix broken link to upstream cloud provider config

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commit updates the link to the upstream docs section listing the possible options to configure the OpenStack cloud provider.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dulek** [comment]
It's significantly more work, but maybe we just got to document all the supported options directly in the openshift-docs? @maxwelldb, what do you think?

**Comment by maxwelldb** [comment]
@dulek Eeeek. So, _usually_, we are disallowed from linking to GitHub resources from the downstream docs. 

That means that getting making this content available would require that I port and then maintain the substantial amount of info that is in https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.25/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager

In the past, I have sometimes received permission to link to GitHub resources that are versioned, and that one does look like it is (`release-1.25`), but it's not really my call. I can run it by support. 

@MaysaMacedo Could you get a QE ack on this before I do that?

Because the 4.12 external CCM story would also benefit from this change, either this PR or a port of the linked content will happen. 👍

**Comment by MaysaMacedo** [comment]
@rlobillo @imatza-rh Can you take a look on this PR? Thanks

**Comment by rlobillo** [comment]
/lgtm

Hello @maxwelldb!

I think we can address on this file, probably on different PR, the resolution of these doc bugs:

https://issues.redhat.com/browse/OCPBUGS-2350
https://issues.redhat.com/browse/OCPBUGS-2217
https://issues.redhat.com/browse/OCPBUGS-2789

Thanks!

**Comment by maxwelldb** [comment]
@MaysaMacedo So, if the info in this link is not entirely applicable to downstream, we'd definitely need to create a downstream doc that contains just the verified info. 

In that case, I think this PR could be closed.

**Comment by MaysaMacedo** [comment]
works for me. The previous releases would also need update

**Comment by maxwelldb** [comment]
Again, this is likely to not be an acceptable due to the GitHub link. Now that it's relevant, though, I'll check out if that can be allowed.

**Comment by MaysaMacedo** [comment]
@maxwelldb do you think using github link for previous versions is allowed?

**Comment by maxwelldb** [comment]
@MaysaMacedo Versions of what, to be clear? Generally, the answer is "no," though. :\

**Comment by MaysaMacedo** [comment]
@maxwelldb I'm trying to check if there is any update since your[ last coment](https://github.com/openshift/openshift-docs/pull/52294#issuecomment-1358118064), so we can take some action about this PR

**Comment by maxwelldb** [comment]
@MaysaMacedo "Versions" => "Versions of OCP?"

If that, there's really no difference to us. It's frowned upon in the official docs. 

I think it would be more stable to repurpose the language that went into https://github.com/openshift/openshift-docs/pull/53068, as the very first draft of that was inspired in part by what you linked to in this PR. 

Do you think that makes sense?

**Comment by eurijon** [comment]
Just posting the docs links with the broken references for clarity (look for "Modify the options based on the cloud.conf specification"):

- 4.9: https://docs.openshift.com/container-platform/4.9/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-setting-cloud-provider-options_installing-openstack-installer-custom
- 4.10: https://docs.openshift.com/container-platform/4.10/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-setting-cloud-provider-options_installing-openstack-installer-custom
- 4.11: https://docs.openshift.com/container-platform/4.11/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-setting-cloud-provider-options_installing-openstack-installer-custom

**Comment by MaysaMacedo** [comment]
> @MaysaMacedo "Versions" => "Versions of OCP?"
> 
> If that, there's really no difference to us. It's frowned upon in the official docs.
> 
> I think it would be more stable to repurpose the language that went into #53068, as the very first draft of that was inspired in part by what you linked to in this PR.
> 
> Do you think that makes sense?

Yup, but #53068 contains configurations that are not supported in OCP releases like 4.10/4.11 as those releases use the legacy cloud provider. If we want to use #53068 for releases older than 4.12 as well, we need to highlight the options not supported in certain verisons.

**Comment by maxwelldb** [comment]
@MaysaMacedo I don't think that I can directly port #53068 to previous versions, but it does seem like a lot of the language could be reused. I'll try to put something together late this week or early next week--after my 4.12 freeze commitments are handled.

**Comment by MaysaMacedo** [comment]
Thanks @maxwelldb :)

**Comment by maxwelldb** [comment]
FYI: https://issues.redhat.com/browse/OCPBUGS-5808

**Comment by MaysaMacedo** [comment]
@maxwelldb This PR can be closed, right?

**Pull request closed without merging**
