### PR TITLE
OCPBUGS-38864: Update link to Red Hat Best Practices for Kubernetes in Telco Core RDS

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/OCPBUGS-38864

Link to docs preview: https://85779--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/telco_ref_design_specs/core/telco-core-rds-use-cases.html#telco-core-ref-application-workloads_ran-core-design-overview

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by amolnar-rh** [comment]
To the peer reviewer: As we're just updating a broken link, would this need QE approval?

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

@amolnar-rh correcting a broken link should not require QE approval. Thx!

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM, I would agree that fixing a broken link doesn't need QE

**Pull request merged**
