### PR TITLE
ENTESB-17309: Camel-K bug for Serverless relnotes

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/ENTESB-17309

Direct preview link: https://deploy-preview-36457--osdocs.netlify.app/openshift-enterprise/latest/serverless/serverless-release-notes?utm_source=github&utm_campaign=bot_dp#known-issues-1-17-0_serverless-release-notes

Applies for OCP 4.6+

### CODE REVIEW

**Comment by alanfx** [comment]
@abrennan89 looks good to me. QE Approved :heavy_check_mark:

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
