### PR TITLE
OBSOLETE: Ocpbugs 10053 411 text

### PR DESCRIPTION
**Pull request by tshwartz**
Updated 'Red Hat OpenShift Container Platform' doc > 'Specialized hardware and driver enablement' chapter > 'Driver toolkit' section > 'Finding the Driver Toolkit image URL in the payload' subsection.

Updates for 4.11 version sentence structure only. Cherry-picking of original PR by squad failed for versions 4.12 and 4.11.

Version(s):
4.11

Issue:

Link to docs preview:
https://57547--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-driver-toolkit.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Nice work @tshwartz !

**Comment by tshwartz** [comment]
@kelbrown20 When I try to squash, it adds a commit that is not related to me. There is also something weird going on with the note. Will try create a separate branch and a new PR, and see if you can merge that one instead.

**Comment by tshwartz** [comment]
PR corrupt.

**Pull request closed without merging**
