### PR TITLE
Corrected ES endpoint in audit logs docs

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/25538

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli PTAL

**Review by anpingli — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
Added the change to 4.6 docs in https://github.com/openshift/openshift-docs/pull/25456 to avoid further merge conflicts.

**Comment by mburke5678** [comment]
@anpingli Thank you for the review!

**Pull request merged**
