### PR TITLE
RHDEVDOCS-4744: Added a fixed issue in SBO 1.3.1 release notes

### PR DESCRIPTION
**Pull request by shipsing**
**Purpose**: To resolve this RN issue https://issues.redhat.com/browse/RHDEVDOCS-4744

**Aligned team**: Dev Tools

**OCP version for cherry-picking**: enterprise-4.11 and later

**Preview pages**: https://52921--docspreview.netlify.app/openshift-enterprise/latest/applications/connecting_applications_to_services/sbo-release-notes.html#sbo-release-notes-1-3-1_servicebinding-release-notes

**SME Review completed**: @sadlerap 
**QE review completed**: @pmacik 
**Peer-review completed**: @gabriel-rh

### CODE REVIEW

**Comment by shipsing** [comment]
@sadlerap, Could you please help with SME review of this PR? 

Also, please verify the following points for correctness:
* OCP version for cherry-picking: enterprise-4.11 and later
* The support matrix table mentions 4.9-4.11 as the supported OpenShift version 

Thanks

**Review by sadlerap — APPROVED** [review]
Looks good to me; I think 4.9-4.11 is what we're still targeting, and I think enterprise-4.11 is the correct OCP version to cherry-pick.

**Comment by shipsing** [comment]
@pmacik, Could you please help with QE review of this PR? Thanks

**Comment by pmacik** [comment]
LGTM

**Review by gabriel-rh — APPROVED** [review]
/lgtm

**Pull request merged**
