### PR TITLE
Upgrade docs for OCP 3.11 - Example Given in Logging Ansible Variables Section is misleading

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1725279

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli Please take a look at this small change to the docs. Do you know how far back we can roll this change?

 Thank you as always for your help!

**Review by anpingli — COMMENTED** [review]
LGTM

**Comment by mburke5678** [comment]
@sosiouxme @sdodson Can this change be rolled back to earlier versions?

**Pull request merged**
