### PR TITLE
OSSMDOC-666: Add link to persistent storage docs.

### PR DESCRIPTION
**Pull request by JStickler**
Version(s): 4.6 - 4.12

Issue: [OSSMDOC-666](https://issues.redhat.com/browse/OSSMDOC-666)
(Also cleans up some content type metadata in outdated format)

Link to docs preview:  Link inserted after the Best Practices topic
http://file.bos.redhat.com/jstickle/OSSMDOC-666/distr_tracing/distr_tracing_install/distr-tracing-deploying-jaeger.html#distr-tracing-deployment-best-practices_deploying-distr-tracing-platform
http://file.bos.redhat.com/jstickle/OSSMDOC-666/service_mesh/v2x/ossm-reference-jaeger.html#distr-tracing-deployment-best-practices_jaeger-config-reference

Additional information:
QE review: jkandasa, iblancasa
Peer review: sheriff-rh

### CODE REVIEW

**Comment by JStickler** [comment]
@jkandasa or @iblancasa, could one of you review this for me please?

**Comment by jkandasa** [comment]
@JStickler from the [original bug](https://bugzilla.redhat.com/show_bug.cgi?id=1919785) my understanding is, we need to document configuration details of elasticsearch persistent storage in `ServiceMeshControlPlane` custom resource.
Otherwise the change looks good to me.

here is an example configuration,
```yaml
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  runtime:
    components:
      tracing.jaeger.elasticsearch:
        container:
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: false
    jaeger:
      install:
        storage:
          elasticsearch:
            storage:
              storageClassName: "standard" # (1)
              size: "5G" # (2)
          type: Elasticsearch
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.1
```
1. persistent storage class name
2. persistent storage disk size

**Comment by JStickler** [comment]
@jkandasa We've already got an example that shows configuring a Jaeger resource with Elasticsearch with persistent storage.  I don't know if that was added before or after this bug was created.  Since the SMCP doesn't support all of the Jaeger configuration options, I think that showing the configuration in the Jaeger object is probably better than in the SMCP.

https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/ossm-reference-jaeger.html#distr-tracing-config-storage_jaeger-config-reference
https://docs.openshift.com/container-platform/4.11/distr_tracing/distr_tracing_install/distr-tracing-deploying-jaeger.html#distr-tracing-config-storage_deploying-distr-tracing-platform

**Review by jkandasa — APPROVED** [review]
@JStickler Thanks! LGTM

**Review by iblancasa — APPROVED** [review]

**Review by sheriff-rh — APPROVED** [review]
LGTM! Ping the merge-review-squad if you need merge assistance.

**Pull request merged**
