### PR TITLE
OSDOCS-9452-RN: adds 4.16.1 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.16

Issue:
[OSDOCS-9452](https://issues.redhat.com/browse/OSDOCS-9452)

Link to docs preview:
[4.16.1 async release note](https://78446--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-16-release-notes.html)

QE review:
- N/A stock text

Additional information:
4.16.1 release date is changed. Hence old PR #78306 is closed and new PR #78446 is created with new release date.

### CODE REVIEW

**Comment by aravipra** [comment]
FYI ,this PR is similar the PR #78306 which had the peer-review-done label on it.

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by aravipra** [comment]
this needs to be added to Continuous Release milestone.

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
