### PR TITLE
OSDOCS-2453: Azure Disk TP -> GA

### PR DESCRIPTION
**Pull request by lpettyjo**
4.10+

**Preview**: https://deploy-preview-37580--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-azure.html

https://deploy-preview-37580--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

**PTAL**: @bertinatto, @duanwei33

### CODE REVIEW

**Comment by sdodson** [comment]
Is this ready to go @lpettyjo ?

**Comment by lpettyjo** [comment]
@sdodson I think so. I have several storage features for 4.10 that I haven't merged yet in case there are more changes needed.

**Pull request merged**
