### PR TITLE
Registry 2.4 updates

### PR DESCRIPTION
**Pull request by miminar**
Registry 2.4 has been back-ported!

### CODE REVIEW

**Comment by miminar** [comment]
@legionus PTAL
@sdodson, @mfojtik  fyi

**Comment by sdodson** [comment]
@miminar So if they've not provided a custom configuration file then there's really not much they need to do when upgrading?

**Comment by legionus** [comment]
LGTM!

**Comment by miminar** [comment]
@sdodson There's really not much to do. All should just work as before. I could probably mention at least enabling `acceptschema2` in the upgrade guide.

Shall I update release notes as well?

Shall I also mention recommended order of components upgrade? Or is this a job for installer?

**Comment by miminar** [comment]
@sdodson Updated release notes and mentioned `acceptschema2` in update guide.

**Comment by miminar** [comment]
The registry 2.4 hasn't been back-ported and, most probably, never will.

**Pull request closed without merging**
