### PR TITLE
adding eu-north-1 support

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1765308 also has doc impact for 4.2+

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@shlao, do you also approve the docs change?

**Comment by shlao** [comment]
@kalexand-rh LGTM

**Comment by kalexand-rh** [comment]
Thanks! I'll merge it as soon as it ships in a 4.2.x release.

**Comment by kalexand-rh** [comment]
Looks like the code for this change went out in yesterday's [errata](https://access.redhat.com/errata/RHBA-2019:3303?extIdCarryOver=true&sc_cid=701f2000001OH74AAG), so I'm going to merge.

**Pull request merged**
