### PR TITLE
BZ1873359 Changed example to foo: bar.

### PR DESCRIPTION
**Pull request by jonquilwilliams**
https://bugzilla.redhat.com/show_bug.cgi?id=1873359

This will need CP to 4.5 and 4.6 after QE reviews it.

### CODE REVIEW

**Comment by juzhao** [comment]
LGTM, thanks, 1873359 is closed

**Review by bergerhoffer — COMMENTED** [review]
Looks good! Glad that you got the branch sorted out. I'll merge and will cherry pick to 4.5 and 4.6.

**Pull request merged**
