### PR TITLE
changed path for bookinfo samples

### PR DESCRIPTION
**Pull request by neal-timpe**
In response to https://issues.redhat.com/browse/OSSMDOC-60, which incorporates 

https://github.com/Maistra/maistra.github.io/pull/121
and MAISTRA-1219

### CODE REVIEW

**Comment by neal-timpe** [comment]
@luksa Can you take a look at this. Does this respond correctly to the maistra book info path change?

@brian-avery and @tvieira Can you take a look too?

**Comment by luksa** [comment]
@neal-timpe Ideally, the image tag should match the version of Maistra that the docs are written for. I've just pushed tag `:1.2.0` of the images, but we also have a `:latest` tag, which we'll keep current from now on.

**Comment by neal-timpe** [comment]
Adding https://bugzilla.redhat.com/show_bug.cgi?id=1826189

**Review by brian-avery — APPROVED** [review]

**Review by tvieira — APPROVED** [review]
LGTM

**Review by JStickler — APPROVED** [review]
Oooh, look at you getting all fancy with the new variable to make updates easier.  Nice!

**Comment by neal-timpe** [comment]
@JStickler Are you ready to merge this to 4.2 4.3 and 4.4? If one doesn't work, I'll make a separate PR for it.

**Review by luksa — APPROVED** [review]

**Comment by neal-timpe** [comment]
https://github.com/openshift/openshift-docs/pull/21405 for 4.4

**Pull request merged**
