### PR TITLE
BZ2006015: etcd snapshot is non blocking

### PR DESCRIPTION
**Pull request by jldohmann**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2006015

OCP Version: 4.6+

Current 4.9 docs: https://docs.openshift.com/container-platform/4.9/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.html

Direct doc preview link: https://deploy-preview-43010--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.html

### CODE REVIEW

**Comment by jldohmann** [comment]
0c54a96...5d692b7 as --> because for less ambiguity

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
