### PR TITLE
Remove references to MERGE_JSON_LOG

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1833418

_After discussions with Jeff Cantril, given this feature is unsupported, known to cause problems (when it works), and currently isnt known to work, I suggest we remove reference to MERGE_JSON_LOG entirely._

### CODE REVIEW

**Comment by mburke5678** [comment]
Removing: 
* `cluster-logging-collector-json.adoc ` -- The _Configuring log collection JSON parsing_ topic [1] 
*  `cluster-logging-collector-undefined.adoc` -- The _Configuring how the log collector normalizes logs_ topic [2]
* `_unused_topics/cluster-logging-fluentd-json.adoc` -- a previous draft of the JSON parsing topic, not currently used. 

[1] https://docs.openshift.com/container-platform/4.4/logging/config/cluster-logging-collector.html#cluster-logging-collector-json_cluster-logging-collector
[2] https://docs.openshift.com/container-platform/4.4/logging/config/cluster-logging-collector.html#cluster-logging-collector-undefined_cluster-logging-collector

**Comment by mburke5678** [comment]
@sichvoge  @jcantrill PTAL

**Comment by sichvoge** [comment]
LGTM. We should backport this change as much as possible.

**Comment by mburke5678** [comment]
@sferich888 approved via email: _I think removing this is fine given the replies in https://issues.redhat.com/browse/RFE-706 and https://issues.redhat.com/browse/RFE-661_

**Comment by xltian** [comment]
@anpingli Can you take a look from QE?

**Review by anpingli — COMMENTED** [review]
LGTM

**Pull request merged**
