### PR TITLE
[enterprise-4.17] add rhel package version

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.17

Issue: n/a

Link to docs preview: https://82284--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-rhcos-rhel-9-4-packages_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen can you PTAL at this docs PR for QE ack? just adds the RHEL 9.4 notice. thanks!

**Comment by mike-nguyen** [comment]
LGTM

**Pull request merged**
