### PR TITLE
OCPBUGS-36648: Expand ignitionConfigOverride example in IBU

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.16, 4.17

Issue: https://issues.redhat.com/browse/OCPBUGS-36648

Link to docs preview: https://78656--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-shared-container-partition.html#ztp-image-based-upgrade-shared-container-partition_shared-container-partition

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tmalove** [comment]
Preview is at Step 3.
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
