### PR TITLE
BZ-1850350: Adding checks for stopped pods

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1850350

Preview: https://bz-1850350--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@retroflexer Please review this per https://bugzilla.redhat.com/show_bug.cgi?id=1850350.

**Comment by retroflexer** [comment]
LGTM. Thanks for the quick turnaround.

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review this? We're first going to cherry pick #25208 to 4.4, which adds a step to restart the kubelet service. Then adding this PR to 4.4 - 4.6 to check that the kube-apiserver pods stopped before continuing. Note that I have not had a chance to test this on a cluster yet.

Preview: https://bz-1850350--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Comment by geliu2016** [comment]
LGTM,thx

**Pull request merged**
