### PR TITLE
OCPBUGS-12894-11: Explicitly stated Rhel versions for RHEL compute ma…

### PR DESCRIPTION
**Pull request by dfitzmau**
[OCPBUGS-12894](https://issues.redhat.com/browse/OCPBUGS-12894)

Version(s):
4.11

Link to docs preview:
[Minimum resource requirements for cluster installation](https://file.emea.redhat.com/dfitzmau/OCPBUGS-12894-11/installing-bare-metal.html#installation-minimum-resource-requirements_installing-bare-metal)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by gpei** [comment]
@dfitzmau Although I didn't see any difference to use RHEL-8.5 or RHEL-8.6 as the OS to run the RHEL workers, but actually what tested by QE is  `RHEL-8.6, RHEL-8.7 and RHEL-8.8` for 4.11, so to be more strictly speaking, I would suggest to only add these three versions in the doc, thanks.

**Comment by dfitzmau** [comment]
> @dfitzmau Although I didn't see any difference to use RHEL-8.5 or RHEL-8.6 as the OS to run the RHEL workers, but actually what tested by QE is `RHEL-8.6, RHEL-8.7 and RHEL-8.8` for 4.11, so to be more strictly speaking, I would suggest to only add these three versions in the doc, thanks.

Thanks, @gpei , for the prompt review. I updated the content and the preview link based on your feedback. WDYT?

**Comment by dfitzmau** [comment]
#
/label peer-review-needed

**Review by aireilly — APPROVED** [review]
lgtm

**Review by aireilly — APPROVED** [review]

**Pull request merged**
