### PR TITLE
Issue #30065 fix indentation issue in service_mesh/v1x/customizing-in…

### PR DESCRIPTION
**Pull request by rolfedh**
…stallation-ossm.adoc and similar files.

- For versions 4.5+
- Issue #30065
- Direct link to doc preview: 
   - https://deploy-preview-30430--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/ossm-custom-resources.html#ossm-configuring-jaeger_ossm-controler-items-v1x
   - https://deploy-preview-30430--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/ossm-custom-resources.html#ossm-configuring-jaeger-elasticsearch_ossm-controler-items-v1x
   - https://deploy-preview-30430--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/prepare-to-deploy-applications-ossm.html#ossm-create-configmap_deploying-applications-ossm-v1x
   - https://deploy-preview-30430--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/prepare-to-deploy-applications-ossm.html#ossm-tutorial-bookinfo-install_deploying-applications-ossm
- Ready for QE, peer review, and merge
- Please close Issue #30065 after merge

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

**Comment by bmcelvee** [comment]
Talked with @rolfedh and since this is a formatting fix, it does not require QE review. Going ahead with the merge and cherry pick.

**Comment by bmcelvee** [comment]
@rolfedh this might require a separate PR directly on 4.5 because it looks like ossm-configuring-jaeger-v1x.adoc and ossm-control-plane-templates-1x.adoc are not in that version.

**Comment by rolfedh** [comment]
Thanks, @bmcelvee. I tried CP'ing the commit to 4.5 and discovered the files aren't in that branch. So, I think we can close the issue.

**Pull request merged**
