### PR TITLE
[OSDOCS-5535]: Adding instructions to delete hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-5535

Link to docs preview: https://57238--docspreview.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-managing.html#delete-hosted-cluster_hcp-managing

QE review:
- [x] QE has approved this change.

Additional information: This PR adds a page to the "Hosted control planes" book that points to instructions in the ACM docs to delete the hosted control planes feature.

### CODE REVIEW

**Comment by jiezhao16** [comment]
lgtm

**Comment by stevsmit** [comment]
lgtm!

**Review by kelbrown20 — COMMENTED** [review]
LGTM as well

**Pull request merged**
