### PR TITLE
GH-47886: add note about analyzing on separate RHEL system

### LINKED ISSUE #47886: [enterprise-4.8] Issue in file support/troubleshooting/troubleshooting-operating-system-issues.adoc
### Which section(s) is the issue in?
Analyzing a core dump

### What needs fixing?

It is fine that the documentation links to the RHEL 8 docs for analyzing a core dump. But the OpenShift documentation should mention that the `kernel-debuginfo` package is necessary to analyze the dump. This leads to a second reboot because of RHCOS immutability at runtime.

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.7+

Issue: fixes #47886

Link to docs preview: 
OCP: http://file.rdu.redhat.com/jdohmann/GH-47886/support/troubleshooting/troubleshooting-operating-system-issues.html#analyzing-core-dumps
OKD: http://file.rdu.redhat.com/jdohmann/GH-47886-okd/support/troubleshooting/troubleshooting-operating-system-issues.html#analyzing-core-dumps

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@gursewak1997 do you know if this note should also be added for analyzing vmcores on FCOS? I can update the conditional text for OKD docs as well if so

**Comment by gursewak1997** [comment]
> @gursewak1997 do you know if this note should also be added for analyzing vmcores on FCOS? I can update the conditional text for OKD docs as well if so

@jldohmann, yes you can update the conditional text for OKD docs as well. Thanks

**Comment by dustymabe** [comment]
> @jldohmann, yes you can update the conditional text for OKD docs as well. Thanks

may want to make the OKD docs mention Fedora instead of RHEL.. or just mention a separate system and not specify.

**Comment by jldohmann** [comment]
@mike-nguyen This PR adds a note suggesting users perform vmcore analysis on a separate RHEL/Fedora system. PTAL for QE ack, thank you!

**Review by bscott-rh — APPROVED** [review]

**Pull request merged**
