### PR TITLE
OCDOCS#3995: Port security and compliance content to the ROSA doc set

### PR DESCRIPTION
**Pull request by tmalove**
Version(s):
4.15+

Issue:
[OSDOCS-3995](https://issues.redhat.com/browse/OSDOCS-3995)

Link to docs preview: (https://72837--ocpdocs-pr.netlify.app/openshift-rosa/latest/security/#security-overview) (Updated 3/18/24) VPN required.

QE review:
- [ ] QE has approved this change.

Additional information:
The original [PR](https://github.com/openshift/openshift-docs/pull/62384) was based on 4.13. The most efficient way to get these updates in a PR based on 'main' was to start a new PR and add the changes.

### CODE REVIEW

**Comment by tmalove** [comment]
@arendej @rhmdnd @BillDett Will you take a look at the updated preview and let me know if you have any comments or ack. Thanks!

**Review by lunarwhite — COMMENTED** [review]
Hi @tmalove, notice that the [cert-manager operator](https://docs.openshift.com/container-platform/4.15/security/cert_manager_operator/index.html) sections have been removed in this PR. Is that intended?

**Pull request closed without merging**
