### PR TITLE
OSDOCS#5602: [4.11] OSDK 1.22.2 version bump and migration step

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.11

Issue: [OSDOCS-5602](https://issues.redhat.com//browse/OSDOCS-5602)

Link to docs preview:
_Procedure change_
* [Updating Hybrid Helm-based projects > step 5](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.html#osdk-upgrading-projects_osdk-hybrid-helm-updating-projects)

_Version updates_
* [About Operator SDK (Note admonition)](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-about.html)
* [Instaling Operator SDK CLI on Linux/MacOS](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html)
* [Scorecard configuration](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-config_osdk-scorecard)
* [Scorecard output](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-output_osdk-scorecard)
* [Scorecard parallel tests](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-parallel_osdk-scorecard)
* [Updating Go-based projects](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-updating-projects.html)
* [Updating Ansible-based projects](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html)
* [Updating Helm-based projects](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-updating-projects.html)
* [Updating Hybrid Helm-based projects](https://58106--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.html)
* [Notable technical changes > Operator SDK 1.22.2 (release notes)](https://58106--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-notable-technical-changes)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
LGTM

**Comment by mwerner2113** [comment]
LGTM

**Comment by xltian** [comment]
ACK

**Comment by oceanc80** [comment]
LGTM

**Review by sheriff-rh — APPROVED** [review]
Looks great! :rocket:

**Pull request merged**
