### PR TITLE
OCPBUGS#26212: Remove `channel` from spec in SR-IOV CLI installation docs

### PR DESCRIPTION
**Pull request by kowen-rh**
Version(s):
4.14

Issue:
[OCPBUGS-26212](https://issues.redhat.com/browse/OCPBUGS-26212)

Link to docs preview:
[CLI: Installing the SR-IOV Network Operator](https://72662--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/hardware_networks/installing-sriov-operator#install-operator-cli_installing-sriov-operator)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by kowen-rh** [comment]
@wizhaoredhat PTAL for SME review.

@zhaozhanqi PTAL for QE review.

Thank you both!

**Comment by zhaozhanqi** [comment]
`channel: stable`  is correct.  why removing this one?

**Comment by kowen-rh** [comment]
> `channel: stable` is correct. why removing this one?

@zhaozhanqi  According to the linked Jira ticket, the CLI steps on OCP 4.14 results in the following error message: `constraints not satisfiable: no operators found in channel 4.14 of package sriov-network-operator in the catalog referenced by subscription sriov-network-operator-subscription, subscription sriov-network-operator-subscription exists`

The additional information in the bug specifies that removing the `channel` key from the `spec` allows the Operator to be installed normally.

Is the bug report itself inaccurate?

**Comment by kowen-rh** [comment]
Testing something out with the openshift-ci-robot real quick. :slightly_smiling_face: 

/jira refresh

**Pull request closed without merging**
