### PR TITLE
OCPBUGS-30274 PerformanceProfile examples contain wrong type of quotation marks

### PR DESCRIPTION
**Pull request by kquinn1204**
[OCPBUGS-30274]: PerformanceProfile examples contain wrong type of quotation marks

Version(s): 4.12, 4.13, 4.14, 4.15, 4.16, main

Issue: https://issues.redhat.com/browse/OCPBUGS-30274

Link to docs preview:
* https://72784--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-low-latency-tuning#adjusting-nic-queues-with-the-performance-profile_cnf-master
* https://72784--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-low-latency-tuning#node-tuning-operator-disabling-CPUs-for-power-consumption_cnf-master

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by dfitzmau — COMMENTED** [review]
Hi @kquinn1204 . Overall LGTM. 

Is the following correct or should the euqals sign be replaced with a colon?

Screenshot from 2024-03-08 12-59-14

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
