### PR TITLE
Updated images in Architecture guide

### PR DESCRIPTION
**Pull request by ahardin-rh**
@vikram-redhat FYI, these are the updated images from Emma.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@enj Do you mind reviewing these updates, or pointing me in the direction of an appropriate reviewer or set of reviewers? Emma from the graphics team made these image tweaks. She especially needs technical review of F5-OpenShift-Connection-Diagram.png  Thanks!

**Comment by enj** [comment]
@bparees @mfojtik @smarterclayton @spadgett @danwinship @pmorie I think you guys own one or more images here.

@ahardin-rh I can only comment on the RBAC one, which I believe is unchanged in content (just a size change from what I can tell).  It looks fine regardless.

**Comment by ahardin-rh** [comment]
@enj Awesome. Thanks!

**Comment by bparees** [comment]
I'm not aware of owning any of them...  the only one related to devex would be the docker build one for which i can't actually see a change, so i guess i'm ok with it. :)

**Comment by danwinship** [comment]
flannel.png and router_model.png are clearly unchanged. Not sure about the changes to F5-OpenShift-Connection-Diagram.png. @rajatchopra ?

**Comment by rajatchopra** [comment]
Both the router and f5 connection diagram are correct.

**Comment by spadgett** [comment]
Web console diagram is unchanged and looks correct.

**Comment by ahardin-rh** [comment]
Thanks, all!

**Pull request merged**
