### PR TITLE
Updated verification output for NFD Operator procedure

### PR DESCRIPTION
**Pull request by ahardin-rh**
Updated per discussion with @sjug 

cc @ArangoGutierrez 

@wabouhamad Please provide QE review

Preview build: https://deploy-preview-35381--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/psap-node-feature-discovery-operator.html#install-operator-cli_node-feature-discovery-operator

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
Thanks for pointing this out @sjug 
/lgtm

**Comment by sjug** [comment]
Still want to keep the line:
```
$ oc get pods
```

Also I was thinking maybe we want to add an example after the instance is created to [show the end state](http://ix.io/3vya)?

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by ahardin-rh** [comment]
@sjug Thanks! Updated. Note that `oc get pods` is still there before the output; per our style guidelines, we separate commands from their output.

**Comment by ahardin-rh** [comment]
@wabouhamad PTAL. Thanks!

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
