### PR TITLE
[OSDOCS-5555]: Move MAPI overview to machine mgmt book overview

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.9+

Issue:
[OSDOCS-5555](https://issues.redhat.com//browse/OSDOCS-5555)

Link to docs preview:
*  Overview of machine management > [Machine API overview](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/index.html#machine-api-overview_overview-of-machine-management)
* Removed from:
  * [Creating a compute machine set on Alibaba Cloud](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-alibaba.html) 
  * [Creating a compute machine set on AWS](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-aws.html)
  * [Creating a compute machine set on Azure](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-azure.html)
  * [Creating a compute machine set on Azure Stack Hub](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-azure-stack-hub.html)
  * [Creating a compute machine set on GCP](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-gcp.html)
  * [Creating a compute machine set on IBM Cloud](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-ibm-cloud.html)
  * [Creating a compute machine set on Nutanix](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-nutanix.html)
  * [Creating a compute machine set on OpenStack](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-osp.html)
  * [Creating a compute machine set on RHV](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-rhv.html)
  * [Creating a compute machine set on vSphere](https://57370--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-vsphere.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
LGTM

**Comment by bscott-rh** [comment]
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

LGTM.

**Pull request merged**
