### PR TITLE
[enterprise-4.15] OSDOCS-7078-RN: add RN entry

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OSDOCS-7078

Link to docs preview: https://71266--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-ingress-dashboards

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi could you PTAL at this docs PR for QE ack? it adds a release note entry for Ingress Operator dashboards in the web console

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Comment by jldohmann** [comment]
@melvinjoseph86 could you PTAL at this docs PR for QE ack? it adds a release note entry for Ingress Operator dashboards in the web console. thank you 🙇

**Pull request merged**
