### PR TITLE
modules/cluster-logging-collector-collector: Remove unused module

### PR DESCRIPTION
**Pull request by wking**
And `logging/config/cluster-logging-collector.adoc`.  These were added by 83e613048a (#16898), but have never been used.

CC @mburke5678

### CODE REVIEW

**Comment by wking** [comment]
[Build failure][1]:

```
IOError: [Errno 2] No such file or directory: '/home/travis/build/openshift/openshift-docs/logging/config/cluster-logging-collector.adoc'
```

Was this content really [unused][2]?

[1]: https://travis-ci.com/openshift/openshift-docs/builds/138118839#L278
[2]: https://github.com/openshift/openshift-docs/pull/18267#discussion_r350221855

**Comment by mburke5678** [comment]
@wking The `logging/config/cluster-logging-collector.adoc` is used here:
https://docs.openshift.com/container-platform/4.2/logging/config/cluster-logging-collector.html

**Comment by wking** [comment]
Ah, I missed that the `include::...` reference was commented out.  @kalexand-rh also pointed me at the consumer [here][1].  Rerolled with 9e741c2d8 -> 07338c65b to just drop the module and commented-out `include::...`.

[1]: https://docs.openshift.com/container-platform/4.2/logging/config/cluster-logging-collector.html

**Pull request merged**
