### PR TITLE
Enhancement for static IP config using OVA

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1785122

### CODE REVIEW

**Comment by codyhoag** [comment]
@rbo PTAL?

**Comment by rbo** [comment]
I'm not a professional technical writer and not a native speaker, I suggest the following changes:  

```
You can now override the default Dynamic Host Configuration Protocol (DHCP)
networking by setting the relevant `guestinfo` property (`guestinfo.afterburn.initrd.network-kargs`) 
during deploying a VM from an OVA in vSphere. 
This lowers the barrier for automatic {op-system-first} deployment in environments without DHCP.

This enhancement allows for higher-level automation to provision an {op-system}
OVA in environments with static networking.
```

"An Ignition config that requires networking." is not supported anymore since OCP 4.3, I don't like to mention it.

**Comment by codyhoag** [comment]
@rbo thanks for the feedback! I've made your suggested updates and also added a command I extracted from the BZ. Can you confirm it is accurate now?

**Comment by rbo** [comment]
@codyhoag LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
