### PR TITLE
Fix SDN debugging command

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/13197

### CODE REVIEW

**Comment by jboxman** [comment]
Hi @zhaozhanqi,

Can you confirm this small change to an `oc` command?

Thanks!

**Comment by zhaozhanqi** [comment]
hi, @jboxman 
The old one is also LGTM, what's for this changed?

# oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}} PodIP: {{.status.podIP}}{{"\n"}}{{end}}'
HostIP: 10.0.151.155 PodIP: 10.0.151.155

# oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}}   PodIP: {{.status.podIP}}{{end}}{{"\n"}}'
HostIP: 10.0.151.155   PodIP: 10.0.151.155

**Comment by jboxman** [comment]
@zhaozhanqi, the difference is at the end:

`{{end}}{{"\n"}}'` vs `{{"\n"}}{{end}}'`

Maybe the output looks noticeably different when there is more than 1 row?

**Comment by zhaozhanqi** [comment]
aha. got it. 
So the changed LGTM
```
 oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}} PodIP: {{.status.podIP}}{{"\n"}}{{end}}'
HostIP: 10.0.151.155 PodIP: 10.0.151.155
HostIP: 10.0.151.159 PodIP: 10.0.151.159
```

**Comment by jboxman** [comment]
@zhaozhanqi thanks!

**Pull request merged**
