### PR TITLE
[OKD] GH #68234 Parse correct field for OKD

### PR DESCRIPTION
**Pull request by peterroth**
Version(s):
OKD docs, all version

Issue:
GitHub [#68234](https://github.com/openshift/openshift-docs/issues/68234)

### CODE REVIEW

**Comment by peterroth** [comment]
@aireilly could you please trigger a test if you think the change is correct?

**Comment by aireilly** [comment]
I can't seem to replicate the original issue on the okd build? https://docs.okd.io/3.6/security/hosts_multitenancy.html does not exist in latest. and when I click the version switcher it just works.

**Comment by aireilly** [comment]
Here's a demo output I built (needs VPN): https://file.emea.redhat.com/aireilly/parse-correct-field/welcome/index.html

Let me know if this works for you.

**Comment by peterroth** [comment]
As I'm not a RedHat employee, I don't have VPN to access it, unfortunately.
You can ping me on Slack and discuss it, find me in the openshift-users channel on kubernetes.slack.com

**Review by aireilly — APPROVED** [review]
lgtm

**Comment by aireilly** [comment]
can you rebase and push please, I need the prow jobs to pass before merging.

**Comment by peterroth** [comment]
Sure, I just pushed the code after I did a rebase.

**Comment by aireilly** [comment]
Should go live in the next hour or two

**Pull request merged**
