### PR TITLE
Moving files to security section

### PR DESCRIPTION
**Pull request by bergerhoffer**
* Proposed addition of new _Security_ bucket
* Moving files from _Authentication_ to _Security_
* Renaming _Authentication_ to _Authentication and authorization_ to be accurate

### CODE REVIEW

**Comment by bergerhoffer** [comment]
We plan to backport this to 4.4, but only after 4.5 GAs. 

To Do: Update redirect spreadsheet for the 6 assemblies that are moving from Authentication to Security.

**Comment by bobfuru** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
Just an FYI @sttts - here is the PR creating the new "Security" heading in the docs, moving the 6 sections to it from under "Authentication", and renaming that section to "Authentication and authorization".

Preview: https://moving-files-security--ocpdocs.netlify.app/openshift-enterprise/latest/security/certificates/replacing-default-ingress-certificate.html

**Pull request merged**
