### PR TITLE
Update ocm-overview.adoc

### PR DESCRIPTION
**Pull request by jseseCCS**
Added link to OCM docs higher up in this content, per Abhishek mention.

Version(s): 4.12+

Issue: [HCCDOC-2761](https://issues.redhat.com/browse/HCCDOC-2761)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jseseCCS** [comment]
@skopacz1 hi! i'm new to this project, so forgive my ignorance of any existing process!

are you the person who has to review/approve PRs in this repo?

**Comment by skopacz1** [comment]
Hey @jseseCCS, I don't believe this is my docs area, but let me ask around to see who could help you!

**Comment by EricPonvelle** [comment]
@jseseCCS I wrote this document originally. I can try to address any issues you may have with it.

**Comment by skopacz1** [comment]
Hi @jseseCCS I'm looking back at this PR and reading your request again. If you are asking for the specific writer of this doc to take a look and review your work, just to be sure, then @EricPonvelle can help. That said, if you just want to submit this PR through our typical process, here's a summary of what that would look like:

1. (Optional) SME review (I don't think that's needed in this case)
2. QE review (also in this case, I would argue that since you're only editing grammar and adding an additional resource as a link, you don't need a QE review in this specific case. Others may disagree though)
3. Peer review
4. Merge review

I can help guide this PR through each stage of review (in this case just the peer and merge review). Let me know if you'd like help with that!

**Comment by jseseCCS** [comment]
Thank you so much, @skopacz1 and @EricPonvelle! I apologize for my very late response! I got zero notifications that anyone had responded to me. :woman_shrugging: thanks for your patience!

Sebastian, yes, I just need the typical process that you outlined [here](https://github.com/openshift/openshift-docs/pull/78736#issuecomment-2221403515). i see that all checks have now passed. can we merge this now or do I need to do something else?

**Comment by skopacz1** [comment]
Also, please note somewhere which versions of the OCP docs this should apply to, thanks! The oldest version that's still supported is 4.12

**Comment by jseseCCS** [comment]
> Hi @jseseCCS. Thanks for your PR.
> 
> I'm waiting for a [openshift](https://github.com/orgs/openshift/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/openshift/people) to skip this step.
> 
> Once the patch is verified, the new status will be reflected by the `ok-to-test` label.
> 
> I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=openshift%2Fopenshift-docs).

how do I join the org?

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
