### PR TITLE
TELCODOCS-1332 - remove dual NIC PTP feature from 4.10 docs

### PR DESCRIPTION
**Pull request by aireilly**
PTP dual NICs feature is not available in OpenShift 4.10. This feature was added in 4.11.

Version(s):
enterprise-4.10 only

Issue:
https://issues.redhat.com/browse/TELCODOCS-1332

Link to docs preview:
https://59785--docspreview.netlify.app/openshift-enterprise/latest/networking/using-ptp.html#ptp-introduction_using-ptp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by sheriff-rh — COMMENTED** [review]
LGTM!

**Comment by obochan-rh** [comment]
\LGTM

**Comment by aireilly** [comment]
(Change management acks are in, and the change management emails are sent)

**Pull request merged**
