### PR TITLE
OSDOCS#9574: Release notes for OCP on ARM 4.15

### PR DESCRIPTION
**Pull request by kelbrown20**
**Version(s):** 4.15

**Issue:** [OSDOCS-9574](https://issues.redhat.com//browse/OSDOCS-9574)

**Link to docs preview:**

- [Installation and upgrade -> OpenShift container platform on 64-bit ARM](https://71255--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-installation-and-update)

**QE review:**
- [x] QE has approved this change.

### CODE REVIEW

**Comment by kelbrown20** [comment]
@jeffdyoung @aleskandro Hey guys! Do you think you could take a look at this release note when you get the chance? Thank you sm!

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Comment by jeffdyoung** [comment]
LGTM

**Pull request merged**
