### PR TITLE
[3.4] Secure vs insecure image pruning

### PR DESCRIPTION
**Pull request by miminar**
Document new options related to secure connection to integrated docker
registry and a mechanism that decides whether to fall-back to insecure
connection.

Backports #4471

### CODE REVIEW

**Comment by miminar** [comment]
Updated based on comments in #5535.

@openshift/team-documentation PTAL

**Comment by bmcelvee** [comment]
LGTM. @bparees would you mind if I go ahead and merge?

**Comment by bparees** [comment]
@bmcelvee go ahead

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../admin_guide/pruning_resources.adoc#admin-guide-pruning-resources[Pruning Objects]
|Added details on secure versus insecure image pruning, and hard pruning the registry.
%

**Pull request merged**
