### PR TITLE
[tech review] Fix labelsPresence missing

### PR DESCRIPTION
**Pull request by talset**
Example under labelsPresence with retiring have invalid argument. Ti seems missing something like labelsPresence

### CODE REVIEW

**Comment by bfallonf** [comment]
@talset Wondering if there's any more work for this PR, and if it's available for 3.0.2 or earlier? Thanks!

**Comment by talset** [comment]
I use this feature on my openshift 3.0.1

**Comment by adellape** [comment]
@abhgupta Can you ack?

And cc @nak3 since you worked on this bit recently.

**Comment by adellape** [comment]
@abhgupta Can you ack the above?

**Pull request closed without merging**
