### PR TITLE
BZ-2061452: Removing removed annotation in favor of using priority class

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.9+

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2061452

Link to docs preview:
* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-configmap-chart
* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-crd

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund Can you please review this update? There were now two instances of this annotation being used that I switched to using the priority class.

Previews:

* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-configmap-chart
* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-crd

**Comment by ingvagabund** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please review as well?

Previews:

* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-configmap-chart
* https://52628--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#deploy-simple-kmod-using-crd

**Pull request merged**
