### PR TITLE
OSDOCS#11534: Correcting structural error in ROSA HCP topic map

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-11534

Link to docs preview:
TBD

QE review: N/A

Additional information:
Fix for ROSA HCP topic map to aid further build_for_portal.py testing

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
