### PR TITLE
BZ1862279: Corrected syntax for export commands

### PR DESCRIPTION
**Pull request by sagidlow**
Applies 4.5+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1862279
QE Approval Needed: @tsze-redhat 
Preview Links: 
- https://deploy-preview-31313--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-lb_installing-gcp-user-infra
- https://deploy-preview-31313--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-iam-shared-vpc_installing-gcp-user-infra
- https://deploy-preview-31313--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-bootstrap_installing-gcp-user-infra
- https://deploy-preview-31313--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-control-plane_installing-gcp-user-infra
- https://deploy-preview-31313--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-worker_installing-gcp-user-infra

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
LGTM for formatting. LMK when QE signs off and I'll merge and cherrypick

**Comment by tsze-redhat** [comment]
LGTM
Thanks!

**Pull request merged**
