### PR TITLE
Add ScheduleDSPods

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/pull/14629

### CODE REVIEW

**Comment by mburke5678** [comment]
@ravisantoshgudimetla PTAL. Is there a use case for turning off the `ScheduleDaemonSetPods` feature?

**Comment by mburke5678** [comment]
@ravisantoshgudimetla PTAL. I want to make sure the edit I made do not change the technical details.

Also, is there a use case for turning off the ScheduleDaemonSetPods feature?

**Comment by ravisantoshgudimetla** [comment]
> Also, is there a use case for turning off the ScheduleDaemonSetPods feature?

Nope, we are not exposing that.

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

**Comment by sjenning** [comment]
@mburke5678 can you remove every after line 25.  we don't let the user disable ScheduleDaemonSetPods so not point mentioning what happens in that case.

**Comment by mburke5678** [comment]
@weinliu Is this something you can review from the QE side?

**Comment by mburke5678** [comment]
@weinliu Please take a look. we are trying to close all PRs by the end of the week for GA. 
If you cannot review, can you suggest someone who can?

cc. @xltian

**Comment by weinliu** [comment]
@mburke5678 ,sorry for missing this, I just got the doc reviewed, it LGTM. I'm checking on if anything else missed. @me if I did not figure them out

**Pull request merged**
