### PR TITLE
[enterprise-4.13] add rhel 9.2 mention

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-5137

Link to docs preview: http://file.rdu.redhat.com/jdohmann/OSDOCS-5137/release_notes/ocp-4-13-release-notes.html#ocp-4-12-rhcos-rhel-9-2-packages

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen could you PTAL for QE ack? This is an OCP 4.13 RN mention for RHEL 9.2. Thank you!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by mike-nguyen** [comment]
LGTM

**Pull request merged**
