### PR TITLE
#35338: bug fix

### LINKED ISSUE #35338: [enterprise-4.6] Issue in file serverless/admin_guide/installing-knative-serving.adoc
### Which section(s) is the issue in?
"Installing Knative Serving using YAML"

### What needs fixing?
The example output includes a `kn-cli-downloads-xxx` pod but this does not seem to appear in most, if any, installations. I think this pod name should be excluded from example output since installations can work without it + it does not seem to accurately reflect new installations (and is therefore likely to make users think their installation didn't succeed).

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes #35338
Applies for OCP 4.6+
Direct preview link: https://deploy-preview-35514--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/installing-knative-serving?utm_source=github&utm_campaign=bot_dp#serverless-install-serving-yaml_installing-knative-serving

### CODE REVIEW

**Comment by alanfx** [comment]
Looks good to me, @abrennan89 
QE approved

**Review by mikemckiernan — APPROVED** [review]

**Pull request merged**
