### PR TITLE
Remove downward api that does not work.

### PR DESCRIPTION
**Pull request by shawn-hurley**
* remove docs that will not work
* needs to be backported to 4.3 and 4.4

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianzhangbjz, will you please confirm this change?

**Comment by jianzhangbjz** [comment]
@kalexand-rh Looks good to me, thanks! BTW, I didn't see this section in [4.4 release doc](https://docs.openshift.com/container-platform/4.4/operators/olm-restricted-networks.html). Am I missing something?

**Comment by jianzhangbjz** [comment]
Never mind, I find it, it's here: https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

**Pull request merged**
