### PR TITLE
OSSMDOC-739: Update Istio version in release notes

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OSSMDOC-739

Link to docs preview: https://53922--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/servicemesh-release-notes.html#new-features-red-hat-openshift-service-mesh-version-2-3

QE review:
- [x] QE has approved this change.

Additional information:

SME review: Jacek
QA review: Praneeth

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@jewertow and @pbajjuri20 please review the component version changes. Thanks!

**Comment by jewertow** [comment]
Istio versions are correct.

**Comment by pbajjuri20** [comment]
Istio versions are correct.

**Review by pbajjuri20 — APPROVED** [review]

**Review by jc-berger — APPROVED** [review]
/lgtm

**Pull request merged**
