### PR TITLE
OCPBUGS-23201-4.11:updates RHEL OS in RNs 4.11

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OCPBUGS-23201

Link to docs preview:
https://68009--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes

QE review:
- [x] QE has approved this change.

Additional information:
Main and the rest of repo PR: https://github.com/openshift/openshift-docs/pull/67954

### CODE REVIEW

**Comment by shipsing** [comment]
@JoeAldinger, The change looks fine.
Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

**Comment by bburt-rh** [comment]
LGTM. Thanks all!

**Pull request merged**
