### PR TITLE
Fixes Bug 1704610: Moves route config to it's own topic

### PR DESCRIPTION
**Pull request by danehans**
This PR does the following:
- Adds route config topic to topic map.
- Moves route adoc references from ingress config topic to route config topic.

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM - thanks so much @danehans!

**Comment by bmcelvee** [comment]
@lihongan PTAL, thanks!

**Review by bmcelvee — APPROVED** [review]

**Comment by lihongan** [comment]
LGTM, thank you @danehans

**Pull request merged**
