### PR TITLE
OCPBUGS#43042: Added line back to installation-user-infra-generate-k8…

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.12+

Issue:
[OCPBUGS-43042](https://issues.redhat.com/browse/OCPBUGS-43042)

Link to docs preview:
[Creating the Kubernetes manifest and Ignition config files](https://83352--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/upi/installing-restricted-networks-aws#installation-user-infra-generate-k8s-manifest-ignition_installing-restricted-networks-aws)

Additional resources:
* https://redhat-internal.slack.com/archives/C68TNFWA2/p1726704724151759

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
