### PR TITLE
CNV#29983 - RN: free page reporting enabled by default

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/CNV-29983

Link to docs preview:
https://71710--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-virtualization

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by fossedihelm** [comment]
/lgtm
Thanks

**Review by bburt-rh — APPROVED** [review]
LGTM

**Pull request merged**
