### PR TITLE
OCPBUGS#15325: updates support status of K8s-NMstate on IPv6

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.10-4.13

Issue:
https://issues.redhat.com/browse/OCPBUGS-15325

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by cybertron** [comment]
This looks fine for older releases, but in 4.14 we should fully support ipv6: https://issues.redhat.com/browse/OPNET-227

We are hopefully going to backport that once it's been tested on 4.14 and we confirm that we've got everything working, but in the meantime this will be accurate for 4.10 to 4.13.

**Comment by qiowang721** [comment]
yeah, lgtm for 4.10 to 4.13 at the current moment.

**Review by opayne1 — COMMENTED** [review]
Preview at https://62465--docspreview.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/about-openshift-sdn.html#nw-ovn-kubernetes-matrix_about-openshift-sdn

LGTM

**Pull request merged**
