### PR TITLE
CNV-28726_revert: Remove CNV-28726 RN 

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14

Issue: [CNV-28726](https://issues.redhat.com/browse/CNV-28726)

Link to docs preview: [New and changed features](https://67010--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-new)

QE review:
- [x] QE has approved this change.

Additional information: Remove, per @dominikholler and @stu-gott

### CODE REVIEW

**Comment by aspauldi** [comment]
@dominikholler, can you please approve this PR? It removes the following release note from the New and changed features for 4.14:

**By default, Windows 11 virtual machines (VMs) are incompatible with the VM snapshot feature. You can, however, enable snapshots on a Windows 11 VM by configuring its trusted platform module (TPM) device's state as non-persistent. Note that a non-persistent TPM will, in turn, render the VM incompatible with software that relies on TPM persistence, such as BitLocker.**

Thanks.

**Comment by dominikholler** [comment]
@stu-gott might be a better fit

**Comment by aspauldi** [comment]
Hi @stu-gott, Can you review? This PR is just a confirmation that the release note has been removed. Thanks.

**Comment by stu-gott** [comment]
LGTM

**Comment by aspauldi** [comment]
@vsibirsk, can you please review this PR? All it does is remove a release note we had added earlier in the 4.14 release work. Thanks.

**Pull request merged**
