### PR TITLE
[RHACS] [4.5 and later versions] ROX-23837: Removing mentions of CIS Docker v1.2.0

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.5+

Issue:
https://issues.redhat.com/browse/ROX-23837

Link to docs preview:
https://81687--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/manage-compliance/monitoring-workload-and-cluster-compliance.html
https://81687--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/review-cluster-configuration.html

SME review:
- [x] SME has approved this change.

Additional information:
- Merge into `rhacs-docs-main` and cherry-pick to:
    - `rhacs-docs-4.6`
    - `rhacs-docs-4.5`

### CODE REVIEW

**Comment by agantony** [comment]
Approved in slack.
SME:Francois Duthilleul

**Review by lpettyjo — COMMENTED** [review]
For RHACS, I don't know if you are required to squash all commits to one. If so, please do.

Otherwise, LGTM!

**Pull request merged**
