### PR TITLE
BZ1703335 Updating the step: Update the spec.strategy.type field from…

### PR DESCRIPTION
**Pull request by jeana-redhat**
… Recreate to Rolling:
https://bugzilla.redhat.com/show_bug.cgi?id=1703335
Fix in master-3 per comment #3 on this bug

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@lihongan Please take a look and verify this change.

**Comment by lihongan** [comment]
LGTM. Thank you @jeana-redhat

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
