### PR TITLE
[OSDOCS-12681] Update PCI-DSS 4.0 in compliance table

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-12681
Link to docs preview:

https://84988--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/policy-process-security.html#compliance_policy-process-security

https://84988--ocpdocs-pr.netlify.app/openshift-rosa-hcp/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security.html#rosa-policy-compliance_rosa-policy-process-security

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
For ROSA, looks good

**Comment by svmrh** [comment]
For OSD, looks good. 
`PCI DSS 4.0   |    Yes   |   Yes`

**Review by lahinson — COMMENTED** [review]
lgtm

**Pull request merged**
