### PR TITLE
OSDOCS#10232: Add a verification step for scaling down node pools

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OSDOCS-10232

Link to docs preview: https://74505--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-managing.html#scale-down-data-plane_hcp-managing

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by bscott-rh** [comment]
Merge review LGTM

**Pull request merged**
