### PR TITLE
Updated instances of OpenShift to {product-title} across Install Config

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tnguyen-rh @tpoitras PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**I'll note that I just had a quick, glancing, sanity check through all these topics. I have full faith in you :100:

**Comment by tpoitras** [comment]
A cursory glance along the first or so topics looks great. My eyes were starting to go a little funny after that, haha. Do you want us to check every single substitution? If not, it LGTM! :octopus:

**Comment by ahardin-rh** [comment]
@bfallonf @tpoitras Perfect! Thanks!   :neckbeard:

**Comment by ahardin-rh** [comment]
No rev history needed

**Comment by adellape** [comment]
@ahardin-rh I removed the enterprise-3.1 label from this one because the conflicts were bonkers due to the wide difference between the 3.1 and 3.2/master Install&Config guides. How about after we land this week's release we do a new commit directly on enterprise-3.1 for updating its book to use `{product-title}`?

**Comment by ahardin-rh** [comment]
@adellape Sounds good to me. Thanks!

**Pull request merged**
