### PR TITLE
Remove ephemeral storage TP notes

### PR DESCRIPTION
**Pull request by bobfuru**
There are several lingering instances stating that ephemeral storage is disabled by default and/or in technology preview. This feature is GA in OCP 4.x and the feature gate was enabled starting in 4.3 (see https://bugzilla.redhat.com/show_bug.cgi?id=1769845#c13). This PR removes those notes, aligning with the work done in https://github.com/openshift/openshift-docs/pull/24731.

For merge post-4.7 GA and should be CP'ed to 4.5, 4.6, 4.7, 4.8.

[Preview link](https://deploy-preview-29689--osdocs.netlify.app/openshift-enterprise/latest/applications/deployments/managing-deployment-processes.html#deployments-setting-resources_deployment-operations)

### CODE REVIEW

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL

**Comment by bobfuru** [comment]
@qinpingli PTAL - we discovered a few lingering instances where ephemeral storage is still noted as TP, although it has been GA for some time. Thanks!

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by qinpingli** [comment]
@sunilcio Could you help take a look? Thanks!

**Comment by sunilcio** [comment]
LGTM!

**Pull request merged**
