### PR TITLE
BZ-1706537: Changing kubectl to oc

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@openshift/team-documentation For peer review please.

Preview: http://file.rdu.redhat.com/~ahoffer/2019/BZ-1706537/applications/operator_sdk/osdk-getting-started.html

**Comment by bergerhoffer** [comment]
@joelanford @LiliC @hasbro17 Could one of you, or someone on the team, please review these changes from kubectl -> oc to just double check that they're okay? Thanks!

Especially there was a line that looked like someone tried to comment it out but it was rendering with a "TODO" in the source block. I removed the TODO and kept the line if you can make sure that's right: https://github.com/openshift/openshift-docs/pull/14725/files#diff-3256bb7a1a6ecdf1adbecdd6d47f178dL206

Preview: http://file.rdu.redhat.com/~ahoffer/2019/BZ-1706537/applications/operator_sdk/osdk-getting-started.html

**Comment by ahardin-rh** [comment]
LGTM!

**Review by joelanford — APPROVED** [review]
LGTM

**Comment by liangxia** [comment]
LG ( from QE )

**Pull request merged**
