### PR TITLE
BZ1933244 - update to machineconfig example

### PR DESCRIPTION
**Pull request by SNiemann15**
https://bugzilla.redhat.com/show_bug.cgi?id=1933244

@vikram-redhat

### CODE REVIEW

**Comment by vikram-redhat** [comment]
lgtm - please make sure to get peer review squad and the QE team to sign off.

**Comment by SNiemann15** [comment]
@holgwolf Would you please QE review

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
