### PR TITLE
improve node selector docs

### PR DESCRIPTION
**Pull request by mburke5678**
Changing the node selector doc to move labeling the node first.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio You have looked at node selector docs before. Can you take a look at this small change?

If so, do you know why I cannot add a node selector to a pod in 4.1?
I am using a cluster-bot system with a recent 4.1 CI build.
```
$ oc whoami
system:admin
```
I tried editing a pod spec to add a node selector but was not allowed to make the change:
````
# pods "router-default-65b79fd87b-kpqtd" was not valid:
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
````
Similar result in the web console as `kube:admin`

**Comment by mburke5678** [comment]
@sunilcio You have looked at node selector docs before. Can you take a look at this small change?

**Comment by sunilcio** [comment]
@mburke5678 I do not think we can edit nodeSelector in pod spec after it is already scheduled and  created. In the above error is reporting what can be changed.
@sjenning could you please check if this is expected?

**Comment by mburke5678** [comment]
@sunilcio According to @joelsmith node selectors for existing scheduled pods need to be added to the pod's controlling  (owner) object. 
See my changes https://github.com/openshift/openshift-docs/pull/16513/commits/a64c55dd5a70a170fbeca015f5787c96c58d186f

**Comment by vikram-redhat** [comment]
@sunilcio could you confirm if you are happy with this change?

**Comment by sunilcio** [comment]
@vikram-redhat LGTM, thanks.

**Pull request merged**
