### PR TITLE
TOC and small fixes

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 14

Issue: None

Link to docs preview: [Preparing your cluster](https://62227--docspreview.netlify.app/openshift-enterprise/latest/virt/install/preparing-cluster-for-virt.html)

QE review: NA
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM! However, I'm new to reviewing, so please wait until @adellape approves my review before proceeding to merge review. Thanks!

**Review by adellape — COMMENTED** [review]
@skopacz1 Peer review LGTM 👍

**Pull request merged**
