### PR TITLE
OSDOCS-12393: Approved Access updates for SRE access information

### PR DESCRIPTION
**Pull request by fmcdonal**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-12393

Link to docs preview:
https://86238--ocpdocs-pr.netlify.app/openshift-rosa-hcp/latest/rosa_architecture/rosa_policy_service_definition/rosa-sre-access.html
https://86238--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-sre-access.html
https://86238--ocpdocs-pr.netlify.app/openshift-rosa/latest/support/approved-access.html

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by apahim** [comment]
lgtm

**Comment by fmcdonal** [comment]
Jm Zimmerman and @robpblake and @apahim has given the go ahead to merge this PR now.

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by fmcdonal** [comment]
@sraghupu please advise, thanks

**Pull request merged**
