### PR TITLE
OCPBUGS#23337: Fix format for example outputs

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-23337

Link to docs preview: https://68322--docspreview.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/cert-manager-customizing-api-fields.html#cert-manager-configure-cpu-memory_cert-manager-customizing-api-fields

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lunarwhite — COMMENTED** [review]
/lgtm

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
