### PR TITLE
added step to optionally remove bootstrap machine after control plane…

### LINKED ISSUE #23012: [enterprise-4.4] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-complete-user-infra_installing-bare-metal

### What needs fixing?

This section is missing a step indicating to the user that the bootstrap node can be removed after the control plane deployment is completed.

### PR DESCRIPTION
**Pull request by jeana-redhat**
… deployment
Fixes #23012

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Fixes #23012

**Comment by jeana-redhat** [comment]
Note: I made this step optional because of language used elsewhere in docs ("A bootstrap machine. This machine is required during installation, but **you can** remove it after your cluster deploys."). If it should not be optional (i.e., it's a best practice or what we expect people to do), let me know and I'll remove that word.

**Comment by jeana-redhat** [comment]
@morenod - I think this is in your area for QE? If so, PTAL. If not, please lmk who I should tag instead :)

**Comment by morenod** [comment]
lgtm

**Comment by jeana-redhat** [comment]
Actually it appears this is already covered earlier in the docs. See step 2 here: https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-installing-bare-metal_installing-bare-metal

**Pull request closed without merging**
