### PR TITLE
RHDEVDOCS 6161 fix wording for HTTP resolver

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.14, pipelines-docs-1.15, pipelines-docs-1.16

Issue:

RHDEVDOCS 6161

Link to docs preview:

https://81589--ocpdocs-pr.netlify.app/openshift-pipelines/latest/create/remote-pipelines-tasks-resolvers.html#resolver-http_remote-pipelines-tasks-resolvers

QE review:
- [x] QE has approved this change.

Additional information:

minor wording fix

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6161

**Review by ppitonak — APPROVED** [review]

**Review by skopacz1 — APPROVED** [review]
Peer review LGTM

**Pull request merged**
