### PR TITLE
OSDOCS-8157 adding azure confidential/trusted VMs to RN's

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-8157

Link to docs preview:
[Trusted launch](https://66836--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-trusted-launch-azure)
[Confidential VMs](https://66836--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-confidential-vms-azure)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jinyunma PTAL at the confidential/trusted VM release notes. Thank you

**Comment by jinyunma** [comment]
LGTM
cc @mresvanis to review

**Comment by mresvanis** [comment]
Thank you for this PR @bscott-rh and the review @jinyunma.

 LGTM

**Review by jeana-redhat — APPROVED** [review]
LGTM 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
