### PR TITLE
Fix asciibinder build errors introduced in #47681

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.8+

Issue: [Slack thread](https://coreos.slack.com/archives/C85JYPHL3/p1657881123168019)

Link to docs preview (VPN required): [Controlling Operator compatability with OCP versions](http://file.rdu.redhat.com/mipeter/fix-asciibinder-build-osdk-control-compat/operators/operator_sdk/osdk-working-bundle-images.html#osdk-control-compat_osdk-working-bundle-images)

Additional information:
Adds a missing `+` to fix the `asciibinder` error introduced in #47681:
`asciidoctor: WARNING: modules/osdk-control-compat.adoc: line 79: no callout found for <2>`
`asciidoctor: WARNING: modules/osdk-control-compat.adoc: line 89: callout list item index: expected 3, got 1`
`asciidoctor: WARNING: modules/osdk-control-compat.adoc: line 89: no callout found for <3>`

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
LGTM.

**Review by jeana-redhat — APPROVED** [review]
TIL

**Pull request merged**
