### PR TITLE
OSDOCS-10745: adds 4.15.17 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15

Issue:
[OSDOCS-10745](https://issues.redhat.com/browse/OSDOCS-10745)

Link to docs preview:
[4.15.17 async release note](https://77150--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes.html#microshift-4-15-17-dp)

QE review:
- N/A stock text, no other release notes

### CODE REVIEW

**Comment by aravipra** [comment]
do not merge this PR until the merge review label is added.  
Now only peer review is needed.

**Comment by mramendi** [comment]
LGTM for peer review

**Pull request merged**
