### PR TITLE
Updating instances of 'host name' to 'hostname'

### PR DESCRIPTION
**Pull request by bergerhoffer**
Per decision by style council to honor IBM style guide's new guidance of "hostname" one word.

Should probably wait until the following PR merges before merging this one: https://github.com/redhat-documentation/supplementary-style-guide/pull/114

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Style guide PR has been merged and the updates are live. This update is good to go now!

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
