### PR TITLE
add podIP example to table

### PR DESCRIPTION
**Pull request by pweil-**
@adellape 

cc @thoraxe

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@pweil- LGTM! Is this for a future release, or for 3.2? Thanks!

**Comment by pweil-** [comment]
ready for 3.2 :+1:

**Comment by ahardin-rh** [comment]
@pweil- Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/downward_api.adoc#dev-guide-downward-api[Downward API]
|Added `*status.podIP*` as a valid selector in the v1 API.
%

**Pull request merged**
