### PR TITLE
OSDOCS#12931: Update the 4.17.9 z-stream release notes

### PR DESCRIPTION
**Pull request by tmalove**
Version(s):
4.17

Issue:
[OSDOCS-12931](https://issues.redhat.com/browse/OSDOCS-12931)

Link to docs preview:
[4.17.9](https://86405--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-9_release-notes)

QE review:
- [ ] QE has approved this change.
N/A for z-stream RNs.

### CODE REVIEW

**Review by skopacz1 — COMMENTED** [review]
A few nits, otherwise LGTM!

**Review by bergerhoffer — COMMENTED** [review]
LGTM to merge!

**Pull request merged**
