### PR TITLE
[OSDOCS-7959]: Remove MCE operator from TP table in 4.13 release notes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-7959

Link to docs preview: https://65407--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes#ocp-4-13-technology-preview

QE review:
- [x] QE has approved this change.

Additional information: This change removes the MCE operator from the Technology Preview table in the 4.13 release notes. It has been approved by all required parties per the [Change management process](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.mq8u2godsmi4).

### CODE REVIEW

**Comment by kalexand-rh** [comment]
LGTM

**Comment by davemulford** [comment]
LGTM

**Comment by evelinec** [comment]
@xltian asked I ack in this PR from the QE perspective. MCE had GA'ed since the 2.0 version. Both the 2.2 and 2.3 versions support OCP 4.13.

**Comment by zanetworker** [comment]
+ @berenss @bweidenb

**Review by jldohmann — APPROVED** [review]
LGTM

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
