### PR TITLE
Update SR-IOV supported devices [webscale]

### PR DESCRIPTION
**Pull request by jboxman**
Prospective PR to update list of supported SR-IOV devices.

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, is there any associated Jira with this change?

Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, is there any associated Jira with this change?
> 
> Thanks!

@jboxman there is no JIRA for this change. Do you want me to create one?

**Comment by jboxman** [comment]
@zshi-redhat, we've had some confusion about the proper way to handle this PR.

Is this specifically part of the _vz_ release, or is this generally applicable?

Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, we've had some confusion about the proper way to handle this PR.
> 
> Is this specifically part of the _vz_ release, or is this generally applicable?
> 
> Thanks!

Generally applicable.

**Comment by bobfuru** [comment]
LGTM

**Comment by zhaozhanqi** [comment]
QE ack this

**Comment by jboxman** [comment]
@ahardin-rh, is there a process to get this merged into _webscale_? Thanks!

**Pull request merged**
