### PR TITLE
BZ#2081027 assignments changed to items

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.9+

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2081027

Link to docs preview:
https://54063--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.html#nw-egress-ips-node-architecture_configuring-egress-ips-ovn

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by cbippley** [comment]
@anuragthehatter Could you take a look at this? Thanks!

**Comment by cbippley** [comment]
@jechen0648 Could you take a look at this? Thank you!

**Review by jldohmann — APPROVED** [review]
LGTM!

**Pull request merged**
