### PR TITLE
Contains corrections for TELCODOCS-218.

### PR DESCRIPTION
**Pull request by johnwilkins**
Fixes: [TELCODOCS-218](https://issues.redhat.com/browse/TELCODOCS-218)

Signed-off-by: John Wilkins <jowilkin@redhat.com>

@ahardin-rh cherry pick to 4.6, 4.7 and 4.8.

### CODE REVIEW

**Comment by jboxman** [comment]
@johnwilkins why is this `[kni@provisioner ~]` being added back in? What is particular about this shell prompt that a user is confused without it?

Thanks.

**Comment by johnwilkins** [comment]
It's in the upstream. I'll remove it.

**Pull request merged**
