### PR TITLE
OSDOCS 12388 create dirs for CICD and Observability overviews to make books

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

cp to enterprise-4.18
cp to published versions to be agreed separately

Issue:

OSDOCS 12388

Link to docs preview:

https://83844--ocpdocs-pr.netlify.app/openshift-dedicated/latest/cicd/overview/index.html
https://83844--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/overview/index.html
https://83844--ocpdocs-pr.netlify.app/openshift-enterprise/latest/cicd/overview/index.html
https://83844--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/overview/index.html
https://83844--ocpdocs-pr.netlify.app/openshift-rosa/latest/cicd/overview/index.html
https://83844--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/overview/index.html

QE review:
N/A

Additional information:

This PR changes the navigation for CI/CD and Observability overview sections in order to create books on docs.redhat.com

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/OSDOCS-12388

**Comment by Preeticp** [comment]
@gabriel-rh request your LGTM if this seems like a good solution for the overview sections in CICD and Observability.

**Review by gabriel-rh — APPROVED** [review]
Not sure what this is for, but changes look fine

**Pull request merged**
