### PR TITLE
RHDEVDOCS-6278 Content improvement for builds

### PR DESCRIPTION
**Pull request by likhithj1996**
Version(s):

Builds v1.1
Builds v1.2

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6278

Link to docs preview:

[Using Builds in a network-restricted environment.](https://85707--ocpdocs-pr.netlify.app/openshift-builds/latest/configuring/using-builds-in-a-network-restricted-environment.html)
[Creating buildah build in a network-restricted environment](https://85707--ocpdocs-pr.netlify.app/openshift-builds/latest/work_with_builds/using-builds.html#ob-creating-source-to-image-build-in-a-network-restricted-environment_using-builds)
[Creating source-to-image build in a network-restricted environment](https://85707--ocpdocs-pr.netlify.app/openshift-builds/latest/work_with_builds/using-builds#ob-creating-source-to-image-build-in-a-network-restricted-environment_using-builds)

QE review:
- [x] QE has approved this change.

QE review:
SME review:
Peer review:
Internal Peer review: @Dhruv-Soni11 

Additional information:

### CODE REVIEW

**Review by avinal — APPROVED** [review]
/lgtm

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by skopacz1** [comment]
I see that build docs go up to 1.3, and that this PR is based off a main branch. Idk whether 1.3 is released yet, but if it was released, would these changes apply to that version as well?

I will review this PR as if it's just for 1.1 and 1.2. If I finish merge review and these changes should also apply to 1.3, please reach out to the OCP docs team to ask if someone could cherry pick this to that version as well. 

CC @Dhruv-Soni11 for version confirmation and @snarayan-redhat for merge availability during recharge

**Comment by skopacz1** [comment]
@likhithj1996 additionally, you'll need to make a manual CP for 1.1. Since I'll be gone for recharge, you can add that cherry pick to the merge review queue like you did with this PR.

**Comment by skopacz1** [comment]
Also just realized that I did not confirm whether this PR was peer reviewed first 😅. From a peer review perspective the PR LGTM, so I'll add the label, but in the future, you must finish peer review before requesting a merge review.

**Comment by shivanisathe25** [comment]
> I see that build docs go up to 1.3, and that this PR is based off a main branch. Idk whether 1.3 is released yet, but if it was released, would these changes apply to that version as well?
> 
> I will review this PR as if it's just for 1.1 and 1.2. If I finish merge review and these changes should also apply to 1.3, please reach out to the OCP docs team to ask if someone could cherry pick this to that version as well.
> 
> CC @Dhruv-Soni11 for version confirmation and @snarayan-redhat for merge availability during recharge

@skopacz1 , the PR is intended only for 1.2. 1.3 is not yet released. Please merge it into 1.2 only.

**Comment by snarayan-redhat** [comment]
@skopacz1 Thanks for looping me in. I see that this PR was peer reviewed but the labels were not updated. But I agree that this should go through the process that includes updating the required labels.

 @likhithj1996 @shivanisathe25 The PR is already merged to 1.2. I think if it is a 1.2 only feature, the PR should have branched out of 1.2 instead of main. If it applies to future versions as well, then we might have to CP it to 1.3 too as we already have a branch for the same.

**Comment by shivanisathe25** [comment]
> @skopacz1 Thanks for looping me in. I see that this PR was peer reviewed but the labels were not updated. But I agree that this should go through the process that includes updating the required labels.
> 
> @likhithj1996 @shivanisathe25 The PR is already merged to 1.2. I think if it is a 1.2 only feature, the PR should have branched out of 1.2 instead of main. If it applies to future versions as well, then we might have to CP it to 1.3 too as we already have a branch for the same.

okay. What I meant was the changes should be there in 1.2 and above versions but not 1.1. Could you CP it to 1.3 as well then?

**Comment by snarayan-redhat** [comment]
@shivanisathe25 I tried cherrypicking to 1.3, however, the builds don't seem to be configured for 1.3. Can you check and confirm how the features are pushed to 1.3?
cc: @Dhruv-Soni11

**Comment by snarayan-redhat** [comment]
Also, meanwhile can one of you update the PR description for the relevant version, like removing 1.1 and maybe adding 1.3?

**Comment by shivanisathe25** [comment]
builds is configured for 1.3 version now. @snarayan-redhat/@skopacz1 : Please merge it to 1.3 branch.

**Pull request merged**
