### PR TITLE
GH#50581 - Fixing wording in yaml

### PR DESCRIPTION
**Pull request by kelbrown20**
For version 4.10 
Fixes issue: #50581

Preview: [Remediating nodes with the Poison Pill Operator -> Configuring machine health checks to use the Poison Pill Operator](https://kelbrown20.github.io/bug-fix-previews/GH50581-fix-wording-in-nodes/nodes/nodes/eco-poison-pill-operator.html#configuring-machine-health-check-with-poison-pill_poison-pill-operator-remediate-nodes)

### CODE REVIEW

**Comment by kelbrown20** [comment]
Reported added their LGTM [here](https://github.com/openshift/openshift-docs/issues/50581#issuecomment-1270601607)
I don't believe this needs QE since its a wording change but please lmk

**Comment by kelbrown20** [comment]
Reporter added their LGTM [here](https://github.com/openshift/openshift-docs/issues/50581#issuecomment-1270601607)
I don't believe this needs QE since its a wording change, but please let me know. Thank you! 😄 

/label peer-review-needed

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Pull request merged**
