### PR TITLE
[OSDOCS-8941] clarifying create manifests command

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.14+

Issue:
[OSDOCS-8941](https://issues.redhat.com//browse/OSDOCS-8941)

Link to docs preview:
[Screenshots below](https://github.com/openshift/openshift-docs/pull/69160#issuecomment-1847608148) (online preview build currently broken)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Preview screenshots:
image
image

**Comment by jianping-shu** [comment]
LGTM

**Comment by kcarmichael08** [comment]
LGTM! I tried restarting the stuck Prow job, but it looks like it still may be stuck.... :(

**Comment by kcarmichael08** [comment]
Oh, it looks like the job is done now!

**Pull request merged**
