### PR TITLE
BZ#1987445: OVN-K all GR respond to ARP

### PR DESCRIPTION
**Pull request by mikemckiernan**
Address known issue from https://bugzilla.redhat.com/show_bug.cgi?id=1987445.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
/assign @asood-rh 

Attempting to address https://github.com/openshift/openshift-docs/issues/33497#issuecomment-941110034

**Review by asood-rh — COMMENTED** [review]
@mikemckiernan current text looks good.
Do you think it makes sense to inform to not put any policies in place that could block the route to service?
Context the comment in bug - "Adding as additional information, that this behavior might lead to policies blocking the arp traffic because it resembles arp-spoofing attacks"

**Pull request merged**
