### PR TITLE
OSDOCS-1807: SRIOV Intel XL710

### PR DESCRIPTION
**Pull request by mikemckiernan**
* Add Intel XL710 to the list of supported hw

-----
@openshift/team-documentation  PTAL.

Applies to branch enterprise-4.8 and milestone Future Release.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
/assign @zshi-redhat 
/assign @zhaozhanqi 

Sorry for the delay, PTAL.

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
