### PR TITLE
SRVKE-1215 FIPS issue in Knative Broker for Apache Kafka is fixed

### PR DESCRIPTION
**Pull request by pierDipi**
Jira: https://issues.redhat.com/browse/SRVKE-1215
fixVersion: 1.26

Version(s): 4.9+

Issue: https://issues.redhat.com/browse/SRVKE-1215

Link to docs preview:
https://58382--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/brokers/kafka-broker.html
Screenshot from 2023-04-06 23-31-56

Previously, this showed an Important warning:
https://docs.openshift.com/container-platform/4.12/serverless/eventing/brokers/kafka-broker.html

Screenshot from 2023-04-06 23-30-47

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by alanfx** [comment]
QE LGTM! Thanks

**Review by gabriel-rh — APPROVED** [review]
/LGTM

**Pull request merged**
