### PR TITLE
OSDOCS-10623: Egress Firewall

### PR DESCRIPTION
**Pull request by mpandya15**
**OSDOCS#10623: Egress Firewall moved to OpenShift network security**

Version(s):
4.16
Issue: https://issues.redhat.com/browse/OSDOCS-10623

Link to docs preview:
https://76668--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/openshift_network_security/egress_firewall/configuring-egress-firewall-ovn.html
https://76668--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/openshift_network_security/egress_firewall/editing-egress-firewall-ovn.html
https://76668--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/openshift_network_security/egress_firewall/removing-egress-firewall-ovn.html
https://76668--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/openshift_network_security/egress_firewall/viewing-egress-firewall-ovn.html

QE review: [NA]

### CODE REVIEW

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done

Hi @mpandya15 be sure to squash your commits for requesting a merge. Also, this structural change does not need QE approval, correct? If not I suggest adding an 'n/a' or something text in comment 0, Thanks!

**Comment by JoeAldinger** [comment]
Merge review requested via slack.

**Pull request merged**
