### PR TITLE
OSDOCS-3000:Changing tab name in web console documentation to match UI

### PR DESCRIPTION
**Pull request by opayne1**
[OSDOCS-3000](https://issues.redhat.com/browse/OSDOCS-3000)

- Applies to `enterprise-4.9`+
- [Preview link](https://deploy-preview-39180--osdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/default-network-policy.html#modifying-template-for-new-projects_default-network-policy)

### CODE REVIEW

**Comment by kdoberst** [comment]
Looks good to me

**Comment by opayne1** [comment]
@schituku PTAL

**Pull request merged**
