### PR TITLE
[4.9] Use official NFD image

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
This change applies to 4.9 only.
Preview is [here](https://deploy-preview-40222--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html#create-cd-cli_node-feature-discovery-operator).

@lenahorsley  @wabouhamad  Will one of you ptal? ty!

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM merging!

**Pull request merged**
