### PR TITLE
Changed number of max nodes from 300 to 2000

### PR DESCRIPTION
**Pull request by bfallonf**
As per email conversation

cc @vikram-redhat @jeremyeder

### CODE REVIEW

**Comment by bfallonf** [comment]
[rev_history]
|xref:../architecture/infrastructure_components/kubernetes_infrastructure.adoc#architecture-infrastructure-components-kubernetes-infrastructure[Infrastructure Components -> Kubernetes Infrastructure]
|Changed the maximum number of nodes from 300 to 2000.
%
|xref:..install_config/adding_hosts_to_existing_cluster.adoc#install-config-adding-hosts-to-cluster[Adding Hosts to an Existing Cluster]
|Changed the maximum number of nodes from 300 to 2000.
%
|xref:../install_config/install/quick_install.adoc#install-config-install-quick-install[Installing a Cluster -> Quick Installation]
|Changed the maximum number of nodes from 300 to 2000.
%

**Comment by bfallonf** [comment]
No review needed. Merging.

**Comment by jeremyeder** [comment]
I thought you were going to strike this line and link to the cluster_limits page?

**Comment by bfallonf** [comment]
@jeremyeder That...makes sense. I'll do another PR now.

**Pull request merged**
