### PR TITLE
BZ1981377: RHEL subscription must be purchased separately

### PR DESCRIPTION
**Pull request by xenolinux**
Add a note that RHEL subscription must be purchased separately when deploying load balancers

Version(s): 4.8+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=1981377

Link to docs preview: https://55092--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-load-balancing-user-infra_installing-bare-metal-network-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ohochman** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Thank you, @xenolinux for quickly adding this note to the documentation!

**Pull request merged**
