### PR TITLE
OCPBUGS-12184: Polishing nmstate CLI install

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.10+
Issue:

https://issues.redhat.com/browse/OCPBUGS-12184
Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@karampok I removed the `generateName: openshift-nmstate-` and the `-tn6k8` from the `name: openshift-nmstate`. I guess `generateName` is an optional specification and not needed? and then the `tn6k8` was just the generated name that got copy/pasted into the product docs. Please let me know if this example should be changed otherwise.

**Comment by karampok** [comment]
lgtm thanks

**Review by JoeAldinger — APPROVED** [review]
/lgtm

**Pull request merged**
