### PR TITLE
Changed curl: to curl and cURL to curl

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up to PR https://github.com/openshift/openshift-docs/pull/6965

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL. No rev history needed.

**Comment by ahardin-rh** [comment]
LGTM 🏆

**Comment by tmorriso-rh** [comment]
@jeffrey4l Please review the changes. Thanks.

**Review by jeffrey4l — APPROVED** [review]
LGTM

**Comment by mburke5678** [comment]
@tmorriso-rh @jeffrey4l 
Isn't `cURL` the _proper_ case when referring to the tool/project? I have always used it that way (including in the affected topic!)

**Comment by tmorriso-rh** [comment]
Thanks @mburke5678. I checked the curl documentation, and it uses "curl," but I see other documentation that uses "cURL." I will change this back to "cURL" since that is the standard.

**Pull request merged**
