### PR TITLE
RHDEVDOCS-3371 Tracker: 2002368 - samples should not go degraded when…

### PR DESCRIPTION
**Pull request by rolfedh**
… image allowedRegistries blocks imagestream creation

- Aligned team: Dev Tools
- For branches: 4.9+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3371
- Direct link to doc preview: https://deploy-preview-37372--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/configuring-samples-operator?utm_source=github&utm_campaign=bot_dp#samples-operator-bootstrapped
- SME review: @gabemontero 
- QE review: @jitendar-singh 
- Peer review: @ 	tbd
- <All reviews complete. Please merge now>

### CODE REVIEW

**Review by gabemontero — CHANGES_REQUESTED** [review]
just a minor suggestion @rolfedh - thanks !

**Review by gabemontero — APPROVED** [review]
LGTM

**Review by abrennan89 — COMMENTED** [review]
Minor suggestions 🙂

**Pull request merged**
