### PR TITLE
[enterprise-4.13] Add release note for new SR-IOV device support

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-8954

Specifically for https://github.com/openshift/openshift-docs/pull/68971.

Version(s): 4.13 only

Issue: 

Link to docs preview: https://69007--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes#ocp-4-13-networking-supported-hardware-for-sr-iov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@zhaozhanqi, this is the release note for 4.13.

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Comment by ahardin-rh** [comment]
LGTM. Thank you!

**Pull request merged**
