### PR TITLE
BZ1982550-4.9

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
BZ1982550-4.9, fixing footnote numbering on Customer Portal.

Version(s):
  * PR applies to: 4.9 only

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1982550

Link to docs preview:
http://file.rdu.redhat.com/shdiaz/BZ1982550_4.9/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html (please scroll to each provider module in this section)
http://file.rdu.redhat.com/shdiaz/BZ1982550_4.9/networking/ovn_kubernetes_network_provider/deploying-egress-router-ovn-redirection.html#nw-egress-router-ovn-cr_deploying-egress-router-ovn-redirection
http://file.rdu.redhat.com/shdiaz/BZ1982550_4.9/support/gathering-cluster-data.html#about-must-gather_gathering-cluster-data
http://file.rdu.redhat.com/shdiaz/BZ1982550_4.9/cli_reference/developer_cli_odo/odo-cli-reference.html#odo-build-images_odo-cli-reference

Additional information:

### CODE REVIEW

**Comment by snarayan-redhat** [comment]
/lgtm

Another reviewer will take a look before marking review as Done

**Review by bergerhoffer — COMMENTED** [review]
LGTM too!

**Comment by bergerhoffer** [comment]
@ShaunaDiaz if you are ready for this to be merged, please label with merge-review-needed. Thanks!

**Pull request merged**
