### PR TITLE
Documents node upgrade pre/mid/post hooks.

### PR DESCRIPTION
**Pull request by jtudelag**
Addresses https://github.com/openshift/openshift-docs/issues/8549.

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
lgtm

**Comment by adellape** [comment]
[Document: Node restart hooks](https://trello.com/c/PaOPFm9V/845-document-node-restart-hooks)

**Comment by jtudelag** [comment]
@adellape https://trello.com/c/PaOPFm9V/845-document-node-restart-hooks seems to be broken, "Card Not Found"

**Comment by vikram-redhat** [comment]
@jtudelag you might not have access to this trello board. 

@adellape all good with this?

**Comment by jtudelag** [comment]
@adellape up ;)

**Comment by jtudelag** [comment]
@adellape this is still pending to be merged. It does not make much sense to me to have the code merged [1] , but the documentation PR still pending. This change is not big deal.

@sdodson can you help with this?

Thanks!!

[1] https://github.com/openshift/openshift-ansible/pull/6816

**Comment by jtudelag** [comment]
Also maybe @vikram-redhat you can help to get this merged.

**Comment by vikram-redhat** [comment]
@jtudelag I have a meeting with @adellape tomorrow and will bring it up.

**Comment by adellape** [comment]
@jtudelag Pulled this to https://github.com/openshift/openshift-docs/pull/10827, closing here.

**Pull request closed without merging**
