### PR TITLE
OSDOCS#6188: Version bump in mirror links

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.14

Issue:
This PR addresses [osdocs-6188](https://issues.redhat.com/browse/OSDOCS-6188).

Link to docs preview:
- [Creating the RHCOS cluster image for the GCP infrastructure](https://63326--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra#installation-gcp-user-infra-rhcos_installing-gcp-user-infra)
- [Installing RHCOS by using an ISO image](https://63326--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal#installation-user-infra-machines-iso_installing-bare-metal)
- [Installing RHCOS by using PXE or iPXE booting](https://63326--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal#installation-user-infra-machines-pxe_installing-bare-metal)
- [Installing RHCOS and starting the OpenShift Container Platform bootstrap process](https://63326--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere#installation-vsphere-machines_installing-vsphere)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mjpytlak** [comment]
@gpei It is that time of the release again. I bumped the version for the RHCOS mirror links. PTAL.

**Review by skopacz1 — APPROVED** [review]
Looks good to me! However, I'm still new to reviewing, so please wait until @adellape approves of my review before proceeding to merge. Thanks.

**Review by adellape — APPROVED** [review]
@skopacz1 @mjpytlak 👍

**Pull request merged**
