### PR TITLE
RHDEVDOCS-3910: Added a conceptual subsection for Topology usability improvements

### PR DESCRIPTION
**Pull request by smunje1**
Purpose: To resolve this issue: https://issues.redhat.com/browse/RHDEVDOCS-3910

Aligned team: DevConsole

OCP version this PR applies to: 4.11

Content for preview:

SME review needed: @divyanshiGupta @jerolimov 

QE review needed: @sanketpathak 

Peer review needed:

### CODE REVIEW

**Comment by smunje1** [comment]
This is the preview of the newly added content:
image

**Comment by smunje1** [comment]
Hello @divyanshiGupta, @jerolimov  Could you please help with the SME review of this PR and share your feedback? Thank you!

**Comment by jerolimov** [comment]
@smunje1 lgtm :+1:

**Comment by divyanshiGupta** [comment]
LGTM @smunje1!

**Comment by smunje1** [comment]
Hello @sanketpathak
Could you please help with the QE review of this PR? Thank you!

**Comment by sanketpathak** [comment]
/lgtm
Thanks @smunje1

**Comment by smunje1** [comment]
Thank you @divyanshiGupta @jerolimov @sanketpathak for your approvals. I am closing this PR and including this content in the following PR: https://github.com/openshift/openshift-docs/pull/47760. I have changed the title for this content to, "Verifying the status of your service binding from the Topology view". Please send your approval for this section.

**Comment by smunje1** [comment]
Closing this PR

**Pull request closed without merging**
