### PR TITLE
Fix typo in RunOnceDuration example

### PR DESCRIPTION
**Pull request by csrwng**
Fixes typo in example configuration

### CODE REVIEW

**Comment by csrwng** [comment]
@adellape ptal

**Comment by adellape** [comment]
:+1: 

Depends on https://github.com/openshift/openshift-docs/pull/1555.

**Comment by bfallonf** [comment]
@adellape #1555 has merged and its followup #1992 . Ok to remove the followup label here?

**Comment by adellape** [comment]
@bfallonf Yeah man. Removing. :fried_shrimp:

**Pull request merged**
