### PR TITLE
RHDEVDOCS-3629- Correct output example per QE - Branches 4.7+

### PR DESCRIPTION
**Pull request by libander**
Manual CP of a081f872849c3a39e6ab03115e13e1065ff0de99 xref:#45297   to 4.7+

### CODE REVIEW

**Comment by libander** [comment]
@anpingli - can you can confirm that this output is appropriate for 4.7+ please?

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by rolfedh — APPROVED** [review]

**Pull request merged**
