### PR TITLE
[RHACS] ROX16927 Content re-structuring 'Understanding authentication providers' section 

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
3.74, 4.0

Issue:
https://issues.redhat.com/browse/ROX-16927

Link to docs preview:
https://59596--docspreview.netlify.app/openshift-acs/latest/operating/manage-user-access/understanding-authentication-providers.html

SME review:
- [x] SME has approved this change.

Additional information:
Merge into `rhacs-docs` and cherry-pick into:
- `rhacs-docs-4.0`
- `rhacs-docs-3.74`

### CODE REVIEW

**Review by ivan-degtiarenko — APPROVED** [review]

**Review by ivan-degtiarenko — APPROVED** [review]
LGTM

**Comment by kcarmichael08** [comment]
I just learned that if you put `JIRANUMBER:` with a colon after the ticket number in the PR header, that it will automatically validate whether or not that Jira ticket is valid.

LGTM!

**Pull request merged**
