### PR TITLE
BZ-1845226: Updating the output for the etcd cluster operator's status

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1845226

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review? The output change is not live yet but is expected with 4.4.8.

Preview: https://bz-1845226--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-identify-unhealthy-etcd-member_replacing-unhealthy-etcd-member

**Comment by bergerhoffer** [comment]
IMPORTANT: Not to be merged until https://bugzilla.redhat.com/show_bug.cgi?id=1821286 is released; expected with 4.4.8.

**Comment by bmcelvee** [comment]
LGTM

**Comment by geliu2016** [comment]
LGTM, thanks

**Comment by bergerhoffer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1823608 is the 4.4.z version and was released with 4.4.8 today. Merging.

**Pull request merged**
