### PR TITLE
fix: country vs CN (BZ:1892606)

### PR DESCRIPTION
**Pull request by mikemckiernan**
Clarify that C is is for the 2 letter
country code and not the common name.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1892606

@openshift/team-documentation, please review.

**Comment by jboxman** [comment]
@mikemckiernan, OCP 4.1-4.3 is EOL, so we're only applying to >= 4.4 as applicable.

**Comment by jboxman** [comment]
@mikemckiernan, someone from QE signs off on these as well. I don't know who that might be for this, however.

**Comment by mikemckiernan** [comment]
@xltian, are you the QE contact who can sign off on this update?

**Comment by vikram-redhat** [comment]
> @xltian, are you the QE contact who can sign off on this update?

No QE required as I mentioned in the bug.

**Comment by jboxman** [comment]
Private comment, wasn't logged in in this browser.

**Comment by jboxman** [comment]
@vikram-redhat, do I merge this then?

Thanks!

**Comment by vikram-redhat** [comment]
> @vikram-redhat, do I merge this then?
> 
> Thanks!

Yes.

**Pull request merged**
