### PR TITLE
OCPBUGS#35808: RukPak does not support FIPS

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.16

Issue: [OCPBUGS-35808](https://issues.redhat.com/browse/OCPBUGS-35808)

Link to docs preview:
* https://79656--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/arch/olmv1-rukpak.html
* https://79656--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/understanding/olm-packaging-format.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@perdasilva and @kevinrizza : This is a pretty minimal admonition. I am happy to add more context and put the warning in more places. Please let me know what you think.

**Review by perdasilva — APPROVED** [review]

**Comment by michaelryanpeter** [comment]
@jianzhangbjz PTAL

**Comment by ahardin-rh** [comment]
LGTM. I don't think we need change management for this update because it's a clarifying statement, but not changing the level of supportabilty. :rocket:

**Comment by dfitzmau** [comment]
Hi @michaelryanpeter . Please squashed the commits on this PR.

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
