### PR TITLE
TELCODOCS:762 - Add new features and updates for OSC release 1.3.2

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): Only 4.12

Issue: [TELCODOCS - 762](https://issues.redhat.com/browse/TELCODOCS-762)

[Link to docs preview](https://54714--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-1.3-release-notes.html#sandboxed-containers-1-3-updates)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by cpmeadors — APPROVED** [review]
QE approval

**Review by skrthomas — COMMENTED** [review]
LGTM!

**Comment by MirzWeiss** [comment]
/label merge-review-needed

However, if it's good to go, **do not merge yet**, please! This is slated for release on January 24th. I just need the merge review done so it can be merged on the release date. I'll request the actual merge separately.

**Comment by michaelryanpeter** [comment]
/hold (to protect the PR from accidental merge until 1/24)
/albel ok-to-merge
/remove-label mergre-review-in-progress
/remove-label merge-review-needed

@MirzWeiss: Based on a conversation in the `team-docs` Slack channel, I am putting a hold on this PR to protect this PR from accidental merging and adding the `ok-to-merge` label. A formalized workflow for this sort of PR is in the works. To ensure that everything is merged in an orderly fashion, please make a Jira ticket to collect the related PRs and assign the ticket to @kalexand-rh. Please include the review status of each PR in the ticket. 

Kathryn, do you have any other comments to add?

**Comment by kalexand-rh** [comment]
@michaelryanpeter, you are correct. The Jira issue is help us make sure that all of the PRs that need to go out with a particular async release get merged on time and help coordinate additional review/merge support as necessary.

(and ok-to-merge is not (and likely will never be) on the list of /label-compatible labels.)

**Comment by MirzWeiss** [comment]
Hi @kalexand-rh . I created a JIRA issue with all of the PRs I need merged today: https://issues.redhat.com/browse/TELCODOCS-1151

**Pull request merged**
