### PR TITLE
Overcommitment resource reservation refine description

### PR DESCRIPTION
**Pull request by ingvagabund**
The description is not clear how to actually set the node server to read object specifications from node configuration directory.

### CODE REVIEW

**Comment by ncdc** [comment]
@tnguyen-rh @adellape Jan is going to rebase. Once that's done, could we please move forward with this? Thanks!

**Comment by ingvagabund** [comment]
@tnguyen-rh @adellape rebased

**Comment by tnguyen-rh** [comment]
@ingvagabund @ncdc Thanks.  If you could verify the labels (OSE 3.2, 3.1), i'll merge.

**Comment by ingvagabund** [comment]
@tnguyen-rh confirming the description is missing in both 3.1 and 3.2

**Comment by tnguyen-rh** [comment]
revhist in #2193

**Pull request merged**
