### PR TITLE
OCPBUGS-17353 [enterprise-4.13] Issue in file welcome/oke_about.adoc …

### PR DESCRIPTION
**Pull request by rolfedh**
…- Unclear support of logging in OKE

This PR continues https://github.com/openshift/openshift-docs/pull/66035

Fixes https://issues.redhat.com/browse/OCPBUGS-17353
Fixes https://issues.redhat.com/browse/OCPBUGS-11875

Version(s):
4.11, 4.12, 4.13, 4.14

Link to docs preview:

- [Table 1. Product comparison for OpenShift Kubernetes Engine and OpenShift Container Platform](https://66558--docspreview.netlify.app/openshift-enterprise/latest/welcome/oke_about#about_oke_similarities_and_differences)
- [Table 2. Features in OpenShift Kubernetes Engine and OpenShift Container Platform](https://66558--docspreview.netlify.app/openshift-enterprise/latest/welcome/oke_about#feature-summary)

Reviewers: Please use these ^^^ preview links to review and approve this PR.
- [x] QE @anpingli has approved this change.
- [x] SME @jcantrill has approved this change

### CODE REVIEW

**Comment by rolfedh** [comment]
@jcantrill @anpingli please review and approve these updates based on our conversation in https://github.com/openshift/openshift-docs/pull/66035.

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
