### PR TITLE
MIG-1551: formatting error in MTC 1.8.3 release notes

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [MIG-1551](https://issues.redhat.com/browse/MIG-1551)

* Single formatting error fixed in MTC 1.8.3 release notes

### Version(s):

* OCP 4.12 → branch/enterprise-4.12
* OCP 4.13 → branch/enterprise-4.13
* OCP 4.14 → branch/enterprise-4.14
* OCP 4.15 → branch/enterprise-4.15
* OCP 4.16 → branch/enterprise-4.16

### Link to docs preview:

* [Known issues - MTC 1.8.3](https://74935--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/mtc-release-notes.html#known-issues-1-8-3_mtc-release-notes)

### QE review:
- [ ] QE has approved this change. *No substantive change to docs, only a single formatting error that has been corrected*

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
/label peer-review-needed

**No substantive change to docs, only a single formatting error that has been corrected**

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
