### PR TITLE
Eliminate quotes not to convert wrong string data type from bool

### PR DESCRIPTION
**Pull request by bysnupy**
* Version: OCPv4.x
* Description: There are no quotes on JSON booleans. In other words, it means, such as, "key": true or false, not "true" or "false". The quotes means the value is string, not bool. Actually, the wrong type make the annotation not working.
* Example: If the quotes are configured to the "paused" value like "false" or "true", then the following error messages are shown from "openshift-controller" pod logs in "openshift-controller-manager" project.
```console
unable to extract cache data from *v1.Deployment: json: cannot unmarshal string into Go struct field ObjectFieldTrigger.paused of type bool
```

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@wzheng1, will you PTAL or help me find the right reviewer?

**Comment by bysnupy** [comment]
@wzheng1 Could you please PTAL ?

**Comment by bysnupy** [comment]
https://github.com/openshift/openshift-docs/pull/32824 , At the upstream the same file has been changed, and I'd like to create PR again for eliminating useless merge commit history. I'd apologies creating again same PR due to my bad PR commit handing ... :pensive: @kalexand-rh

**Comment by bysnupy** [comment]
My new PR is here: https://github.com/openshift/openshift-docs/pull/33146

**Pull request closed without merging**
