### PR TITLE
Bug 1290489 Not clear what "amount of cpu" means when setting a resource limit 

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1290489

### CODE REVIEW

**Comment by mburke5678** [comment]
@sferich888 PTAL
I added a link to the  section of the Compute Resources topic, where CPU measurement is explained. Does this satisfy your issue?
https://docs.openshift.com/container-platform/3.5/dev_guide/compute_resources.html#dev-compute-resources

**Comment by mburke5678** [comment]
@sferich888 BUMP ^^

**Comment by sferich888** [comment]
WFM

**Comment by mburke5678** [comment]
@mdshuai PTAL

**Comment by mdshuai** [comment]
LGTM, thanks

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. I added an xref to an existing topic.

**Comment by mburke5678** [comment]
[rev_history]
|xref:../admin_guide/limits.adoc#admin-guide-limits[Setting Limit Ranges]
|Added link to information on how CPU and memory are calculated.
%

**Pull request merged**
