### PR TITLE
Adding additional resources role to sync with main

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12 only

Issue:
No issue; fixing the mismatch between main and enterprise-4.12 so that PR #50688 can cherry pick cleanly to 4.12.

Link to docs preview:
Previews, but there are no visible changes:
* http://file.rdu.redhat.com/~ahoffer/2022/fixing-role/installing/installing_azure/manually-creating-iam-azure.html
* http://file.rdu.redhat.com/~ahoffer/2022/fixing-role/installing/installing_aws/manually-creating-iam.html
* http://file.rdu.redhat.com/~ahoffer/2022/fixing-role/installing/installing_gcp/manually-creating-iam-gcp.html

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-done
/lgtm

**Comment by bergerhoffer** [comment]
Cherry picking back further too since this is causing conflicts in earlier versions too.

**Comment by maxwelldb** [comment]
Extra peer review +1 just for completeness' sake. :)

**Comment by bergerhoffer** [comment]
Thanks @maxwelldb!

**Pull request merged**
