### PR TITLE
[SRVCOM-2455] Add a mention of disconnected support

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVCOM-2455

Link to docs preview:
https://80936--ocpdocs-pr.netlify.app/openshift-serverless/latest/install/preparing-serverless-install.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
