### PR TITLE
[MULTIARCH3411] Add support for IBM Z and IBM Power

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.16+

Issue: https://issues.redhat.com/browse/MULTIARCH-3411

Link to docs preview:
https://85374--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html

QE review:
- [x] QE has approved this change.

Additional information: Requires CM

Related PR https://github.com/openshift/openshift-docs/pull/85372

### CODE REVIEW

**Comment by holgwolf** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
This LGTM, but OSSO 1.3.1 is also on 4.16, so this should also go into 4.16 too (as long as this item still applies to 1.3.1 on 4.16).

**Comment by SNiemann15** [comment]
> This LGTM, but OSSO 1.3.1 is also on 4.16, so this should also go into 4.16 too (as long as this item still applies to 1.3.1 on 4.16).

I confirmed with @prb112 @werled that both 4.17 and 4.16 were tested.

**Comment by SNiemann15** [comment]
PTAL: @sferich888, @xltian, @kalexand-rh, @sjstout, @listey

**Review by lahinson — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@SNiemann15 I'm sorry, I actually just removed the OSSO 1.3.1 release notes from main and 4.18 today (bad timing). 1.3.1 only applies to 4.16 and 4.17. So now there's a conflict because this section doesn't exist anymore in 4.18/main.

Can you try to retarget this PR against enterprise-4.17, and then we'll merge it there and CP it to 4.16?

We have instructions in the manual on how to retarget, if you haven't done that before: https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.5s75lq4bcdl5

**Comment by bergerhoffer** [comment]
Closing in favor of #86379, which targets this update at 4.17.

**Pull request closed without merging**
