### PR TITLE
clarify the state of db replication support

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @bmcelvee 
i don't think we have this doc in 4.x, but if we do it should be fixed there also..... this can be cherry-picked back as far as we want, and the okd docs should also be updated (not branch sure what those are built off of these days?)

**Comment by bparees** [comment]
@bmcelvee open for merge?

**Comment by bmcelvee** [comment]
@bparees yes, thanks. I'll go ahead and merge. Should this also be applied to master-3 (if so, I can cherrypick from this PR)?

**Comment by bparees** [comment]
> Should this also be applied to master-3 (if so, I can cherrypick from this PR)?

is master-3 the 3.x docs?  if so then yes...  this change is applicable to all of 4.x and 3.x.

**Comment by bmcelvee** [comment]
Yeah, master-3 is the 3.x master branch. I'll go ahead and cherrypick to master-3 and assess how best to apply the changes to the rest of 3.x.

**Pull request merged**
