### PR TITLE
Document WEB_CONCURRENCY env var

### PR DESCRIPTION
**Pull request by mnagy**
For PR https://github.com/sclorg/s2i-python-container/pull/118
Trello: https://trello.com/c/o6ijZ01e/892-5-update-python-image-to-autoconfigure-based-on-available-memory-evg

Will apply for 3.3.

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but needs a rebase.  @openshift/team-documentation ptal as well.

**Comment by bparees** [comment]
@mnagy in the future, please tag me in docs PRs, or tag @openshift/team-documentation

**Comment by tpoitras** [comment]
LGTM, but as ben said, please rebase @mnagy

**Comment by mnagy** [comment]
@bparees sorry about that.

Rebased.

**Comment by bparees** [comment]
lgtm, thanks @mnagy

**Comment by tpoitras** [comment]
thanks, merging

**Comment by vikram-redhat** [comment]
Doesn't require a followup.

**Pull request merged**
