### PR TITLE
Correct docker0 network CIDR

### PR DESCRIPTION
**Pull request by sdodson**
Per the discussion in this ansible PR the value is incorrect
https://github.com/openshift/openshift-ansible/pull/3972

### CODE REVIEW

**Review by danwinship — APPROVED** [review]
lgtm

**Comment by ahardin-rh** [comment]
@sdodson Thanks! Is this for OCP 3.4 on?

**Comment by sdodson** [comment]
@ahardin-rh It's relevant to all versions, so whatever docs policies are as far as backporting would apply.

**Comment by ahardin-rh** [comment]
@sdodson Okay, thanks!

**Comment by ahardin-rh** [comment]
Minor edit. No revision history needed.

**Pull request merged**
