### PR TITLE
BZ-1680083 Replaced openshift_cockpit_deployer_prefix variable with o…

### PR DESCRIPTION
**Pull request by lbarbeevargas**
…penshift_cockpit_deployer_image in inventory file example

BZ-1680083 https://bugzilla.redhat.com/show_bug.cgi?id=1680083

@yapei PTAL for 3.11. Thank you.

### CODE REVIEW

**Comment by yanpzhan** [comment]
@lbarbeevargas  the origin variable is commented out: "#openshift_cockpit_deployer_prefix", should  the new variable "openshift_cockpit_deployer_image=" be commented, too?

**Comment by lbarbeevargas** [comment]
> @lbarbeevargas the origin variable is commented out: "#openshift_cockpit_deployer_prefix", should the new variable "openshift_cockpit_deployer_image=" be commented, too?

@yanpzhan Good question! In the customer case, the `openshift_cockpit_deployer_image` variable is not commented out in customer's example file. I'll check with the BZ Reporter to see if this is correct that the variable is not commented out.

**Comment by lbarbeevargas** [comment]
@yanpzhan I updated the PR and commented out the `openshift_cockpit_deployer_image` variable. PTAL. Thank you!

**Comment by yanpzhan** [comment]
The update LGTM now, thanks!

**Comment by lbarbeevargas** [comment]
BZ-1680083 https://bugzilla.redhat.com/show_bug.cgi?id=1680083

@openshift/team-documentation PTAL. Merge to 3.11. Add labels and milestone.

**Comment by mburke5678** [comment]
@lbarbeevargas LGTM

**Pull request merged**
