### PR TITLE
Add instructions to ensure multicast is enabled and optionally add iptables rules for VRRP

### PR DESCRIPTION
**Pull request by ramr**
@bfallonf  PTAL  Thx

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr This looks ok to me. Though I'll note that I don't make much sense of the commands. @adellape might be able to have a better eye for them.

My only question would be if the reader is expected to install anything to do with multicast? You write that node will have to be able to talk to multicast, but I think that's the only part it's mentioned. There's a link to the Keepalived docs a few paragraphs above, but would this section benefit from a link to an explanation of multicast?

**Comment by ramr** [comment]
@bfallonf  fair question - didn't want to go too much into what setup details as there's so many knobs one can tune - so just added those checks/examples in as a verification step - note, this was based on feedback from one of the customer systems (where that iptables rule was needed). 
I did have a reciprocal question for you - was working on a set of troubleshooting steps for ipfailover and router - ingress really - where should we document that? 
As part of this ```*.adoc``` or somewhere else? 

As re: adding a blurb for multicast [ability to send packets from 1 source to many destinations/hosts], I guess I could add that 1 liner but I don't see much value. Sorta on the fence on this one, how much in depth do we go - ala explain what the linux kernel is, or what RPMs are, etc.

**Comment by bfallonf** [comment]
@ramr Ok. If this is about verifying part of an installation, I see no problem with this going into the docs how it currently is. I see your point about not explaining any non-OpenShift terms. 

Although, can I ask where you are getting this info from? We have a way of tracking docs enhancements brought on from customer cases, so it'd be good to see where it's coming from. Also, without sounding ungrateful, it's probably much more our job than yours to follow up any needed docs enhancements brought on from this stuff. 

To answer your question about the Troubleshooting steps, we actually have a BZ for tracking any troubleshooting info, in the hopes that we'll have a troubleshooting guide sometime soon. It's probably best to report a BZ. This way I can make sure it's all in the same place, which will hopefully ensure it's end up in the same place too:

https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Enterprise

**Comment by ramr** [comment]
@bfallonf  Cool - I will add that info to the BZ. And will send you a pm with info.

**Comment by adellape** [comment]
@ramr Does the router section's `oadm ipfailover` cmd need `--service-account=ipfailover` as well, per recent https://lists.openshift.redhat.com/openshift-archives/users/2015-September/msg00084.html? @FranBarrera opened https://github.com/openshift/openshift-docs/pull/971 to add `--service-account=router` there but I would rather get it added in this PR since you've reworked the example SA name here to be "ipfailover" instead.

**Comment by ramr** [comment]
@adellape missed that - good catch. Will update the f5 ramp node docs as well. Stay tuned.

**Comment by ramr** [comment]
@adellape / @bfallonf  made changes as per review comments from @adellape  
PTAL

This might need some cleanup though (as the same set of instructions are repeated in 3 places - I did initially put in a link in the 2 sections where its repeated -  but on reading it, I found it was so easy to just
miss that step. So rather than just link to it, I inlined the instructions (does mean a copy of the same unfortunately).  If you have any other ideas?  Thx

**Comment by adellape** [comment]
@ramr This looks good to merge to me, with a follow-up PR from docs team for edits. @bfallonf Ack?

**Comment by adellape** [comment]
Got ack, merging.

**Pull request merged**
