### PR TITLE
add kubeletconfig management for 4.0

### PR DESCRIPTION
**Pull request by rphillips**
Initial pass of adding documentation for KubeletConfiguration with OSE 4.0.

/cc @openshift/team-documentation

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@mburke5678 - does this fall under your team?

**Comment by mburke5678** [comment]
@rphillips What current 3.x functionality does this PR replace?

**Comment by rphillips** [comment]
@mburke5678 This is targeting the 4.0 branch, and is replacing the node config map to configure nodes (kubelet configuration).

**Comment by mburke5678** [comment]
@rphillips This looks good to me. However, I think the material is too detailed for this section, which is an overview; I asked @kalexand-rh who added the topic and she agreed. Perhaps I can merge this PR and pull out what is not appropriate for the overview?

**Comment by rphillips** [comment]
sounds good to me.. thanks

**Pull request merged**
