### PR TITLE
fix typo on firewall entry for observatorium

### PR DESCRIPTION
**Pull request by laurafitzgerald**
4.12+

Small typo fix

Link to docs:
https://docs.openshift.com/rosa/rosa_planning/rosa-sts-aws-prereqs.html#osd-aws-privatelink-firewall-prerequisites_rosa-sts-aws-prereqs

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@openshift/team-documentation

**Review by jldohmann — APPROVED** [review]
lgtm

**Comment by jldohmann** [comment]
@laurafitzgerald what versions of OCP is this typo fix for? Thanks!

**Comment by laurafitzgerald** [comment]
Hi @jldohmann The fix is for ROSA so I'm not sure what OCP version that would be. I think any version of ROSA that could support privatelink and fw networking would require the change.

**Comment by kalexand-rh** [comment]
No QE's required.

**Comment by mburke5678** [comment]
This looks good to merge. Does ROSA docs get cherrypicked? If so, to where?

**Comment by bmcelvee** [comment]
Thanks @laurafitzgerald and @mburke5678! Yep, ROSA gets cherry picked to 4.12 and 4.13 :)

**Pull request merged**
