### PR TITLE
Fixing xref and a few other build issues

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12+ (or however far back issues are applicable)

Issue:
N/A

Link to docs preview:
https://75341--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_oci/installing-oci-agent-based-installer.html
https://75341--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-updating.html
https://75341--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html
https://75341--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_alerts/custom-logging-alerts.html
https://75341--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/configuring-the-monitoring-stack.html

**OSD**
https://75341--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html
https://75341--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/logging/logging_alerts/custom-logging-alerts.html
https://75341--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/monitoring/configuring-the-monitoring-stack.html

**ROSA**
https://75341--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/logging/log_collection_forwarding/configuring-log-forwarding.html
https://75341--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/logging/logging_alerts/custom-logging-alerts.html
https://75341--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/monitoring/configuring-the-monitoring-stack.html

QE review:
N/A - just build error fixes

Additional information:
This is fixing a few issues after @JoeAldinger noticed that there was an issue with the build failing.

There were some xref issues, missing emphasis/bold matchup, and some heading levels out of order

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm, I pulled this down locally and it had no errors as well.

**Review by bburt-rh — APPROVED** [review]
LGTM.

**Pull request merged**
