### PR TITLE
.kubeconfig docs

### PR DESCRIPTION
**Pull request by deads2k**
Explains how to manipulate .kubeconfig files.

### CODE REVIEW

**Comment by nhr** [comment]
@deads2k - Can you please have a look at https://github.com/openshift/openshift-docs/pull/115 and make sure that your PR and that one work make sense as complementary info?

**Comment by deads2k** [comment]
I think it does.  This doc goes into more detail about how to customize the file to suit your needs.  #115 points out that it exists and shows its format.

**Comment by nhr** [comment]
@deads2k Solid. Can you please rebase and create a link in the cli doc so that the section added by that PR has a pointer to your topic?

**Comment by CowboysFan** [comment]
@deads2k @nhr It looks like the link is there, but not in the correct syntax. The link should be to the .html version of that file, so in this case link:kubeconfig.html[]. We can easily fix this ourselves during our review process.

Is this the link in question? Please ack so that we can merge this.

**Comment by deads2k** [comment]
Yes, it was my intent to link from the cli file to the kuebconfig file.

**Comment by adellape** [comment]
Merging per last two comments. Thanks, @deads2k.

**Pull request merged**
