### PR TITLE
Add additional resource to IBM Z install section

### PR DESCRIPTION
**Pull request by SNiemann15**

### CODE REVIEW

**Comment by SNiemann15** [comment]
@bmcelvee Would you please take a look and merge and cherry pick to 4.2?

**Comment by bmcelvee** [comment]
Hi @SNiemann15, I'm happy to help! The content LGTM - adding label for peer review. I do have a few questions before merging: 
1. Is there a bug or issue related to this PR that can be linked? (If not, that is okay.)
2. Is there any reason the additional resources section shouldn't go into master and from there cherry picked to 4.2 and 4.3? That way it will be available to all relevant versions down the line.

**Comment by SNiemann15** [comment]
Hi Brandi,
no there is no bug related to that. We already do have that link in the
restricted installation:
https://docs.openshift.com/container-platform/4.3/installing/installing_ibm_z/installing-restricted-networks-ibm-z.html

I did this together with Maxim, who is training me to contribute and as far
as I remember he said it shouldn't go into the master because IBM Z is not
available for 4.4 yet.
Correct @Maxim Svistunov <msvistun@redhat.com> ?

Regards,
Silke

**Comment by rh-max** [comment]
Hi @bmcelvee and @SNiemann15. Silke's responses are correct: there's no bug, and this shouldn't go to `master`, as the IBM Z documentation release cycle is out of sync with that of OCP, so we add the docs to every `enterprise-x.y` branch "manually".
(Closed https://github.com/openshift/openshift-docs/pull/22418 in favor of this)

**Comment by bmcelvee** [comment]
Thank you both for the clarification! Since this doesn't require QE, I'll go ahead with the merge + cherry pick.

**Comment by bmcelvee** [comment]
Because of the cherry pick failure, I opened https://github.com/openshift/openshift-docs/pull/22637 directly on the 4.2 branch.

**Pull request merged**
