### PR TITLE
[OSDOCS-6223]: amending IAM service account in GCP roles, removing OWNER…

### PR DESCRIPTION
**Pull request by fmcdonal**
… role for creating a cluster on GCP

Version(s):

4.13+

Issue:

https://issues.redhat.com/browse/OSDOCS-6223

Link to docs preview:

https://61055--docspreview.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by fmcdonal** [comment]
[@Xue Li](https://redhat-internal.slack.com/team/UEEQ10T4L)
 and 
[@yuwan](https://redhat-internal.slack.com/team/UEE8X128Y)
, will you please QE review this pull request?
https://github.com/openshift/openshift-docs/pull/61055
Thanks in advance, Frances

**Review by jldohmann — APPROVED** [review]
LGTM!

**Comment by fmcdonal** [comment]
As PR has been reviewed and approved by SME and peer-reviewed, I have applied the merge request label. 
https://issues.redhat.com/browse/OSDOCS-6223?focusedId=22447540&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22447540

**Pull request merged**
