### PR TITLE
Remove misleading verify deployment from OTEL

### PR DESCRIPTION
**Pull request by pavolloffay**
The section is misleading, the verification of OTEL deployment should be done differently. The section was copied from Jaeger.

Version(s):
all supporter OCP versions 

Issue:

Link to docs preview:

QE review:
- [x] QE has approved this change.

@IshwarKanse 

Additional information:

### CODE REVIEW

**Comment by IshwarKanse** [comment]
@pavolloffay Do we want to add steps to verify the OTEL deployment or is this going to be covered in a different PR ? We also need to add the supported modes for OTEL.

**Review by iblancasa — APPROVED** [review]

**Review by bburt-rh — APPROVED** [review]

**Comment by bburt-rh** [comment]
lgtm

**Pull request merged**
