### PR TITLE
OCPBUGS#13338: Update the command for deleting the CR

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-13338

Link to docs preview: https://59983--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-quickstart.html#osdk-quickstart_osdk-helm-quickstart

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by emmajiafan** [comment]
/lgtm
but the docs link can't be open

**Comment by xenolinux** [comment]
> /lgtm but the docs link can't be open

Preview is generated now

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by sjhala-ccs** [comment]
@bergerhoffer Problems with cherry picking to 4.12 and 4.14. I have not seen the "Patch is empty" error before. Can you please help resolve this? Thanks.

**Comment by bergerhoffer** [comment]
@sjhala-ccs I issued the commands again and looks like they succeeded. Sometimes it's just a flake that causes an error like that

**Pull request merged**
