### PR TITLE
OSDOCS-12161: adds 4.15.40 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15

Issue:
[OSDOCS-12161](https://issues.redhat.com/browse/OSDOCS-12161)

Link to docs preview:
[4-15-40-dp_release-notes](https://85898--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes.html#microshift-4-15-40-dp)

QE review:
- NA. stock text updated, no other changes.

### CODE REVIEW

**Comment by aravipra** [comment]
Please do not merge until the label is added. Only Peer review is needed for now.

**Review by lahinson — COMMENTED** [review]
Assuming the links will work on 12 Dec, LGTM.

**Review by ShaunaDiaz — COMMENTED** [review]
lgtm

**Pull request merged**
