### PR TITLE
Update AWS AMIs based on recent boot image updates

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 can you verify? Thanks!

**Comment by codyhoag** [comment]
@miabbott can you verify this info?

**Comment by miabbott** [comment]
```
$ git checkout release-4.7
Already on 'release-4.7'
Your branch is up to date with 'upstream/release-4.7'.

$ jq '.amis[].hvm' < data/data/rhcos.json 
"ami-057e5df70c52dc128"
"ami-006ab68917f52bb13"
"ami-0d236f6289c700771"
"ami-040394572427a293a"
"ami-0838c978c0390dd75"
"ami-07af688c8b65de56f"
"ami-0a36faab6aa0a0dea"
"ami-01284e5815ce66a95"
"ami-0361c06cf3e935cfe"
"ami-0080eb90a48d9655e"
"ami-0a3bc89f7aadf0343"
"ami-0b4024fa5cb2588bd"
"ami-07376355104ab4106"
"ami-038f4ce9ea7ac7191"
"ami-025899013a24bb708"
"ami-089e1a3dcc5a5fe08"
"ami-0d5f9982f029fbc14"
"ami-0c84b5c5255ec4777"
"ami-0b421328859954025"
"ami-010de485a2ee23e5e"
```

LGTM

/approve

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
