### PR TITLE
OBSDOCS-1549: Create the topic maps with replacement assemblies while…

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): none for cherry-picking, just merge into the `monitoring-docs-restructure` branch

Issue: https://issues.redhat.com/browse/OBSDOCS-1549

Link to docs preview: https://85766--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/about-ocp-monitoring/about-ocp-monitoring

QE review: `n/a`

**Additional information:** 

 PR creates the topic maps with stand-in assemblies while still keeping the old topic map entries. This is not a user-facing change, just a preparation of the new table of contents.

This is part of the bigger monitoring restructuring changes.

The structure is also preliminary approved by stakeholders.

### CODE REVIEW

**Comment by eromanova97** [comment]
For reference, this is the new added structure:
image

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM for an unpublished branch. Merging.

**Pull request merged**
