### PR TITLE
[4.3] Subscribe PTP Operator from right channel

### PR DESCRIPTION
**Pull request by zenghui-shi**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@huiran0826 PTAK

**Comment by jboxman** [comment]
@zshi-redhat, do we want this for master/4.4 as well?

**Comment by jboxman** [comment]
@zhaozhanqi, can you confirm? Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, do we want this for master/4.4 as well?

@jboxman master change is https://github.com/openshift/openshift-docs/pull/20061
4.4 change will need to cherry-pick from above master change.

**Comment by zhaozhanqi** [comment]
@huiran0826 PTAL, thanks

**Pull request merged**
