### PR TITLE
BZ#2033699 Clarify restricted network statement

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=2033699

Preview: https://deploy-preview-40013--osdocs.netlify.app/openshift-enterprise/latest/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you verify? Thanks!

**Comment by gpei** [comment]
Thanks for the update, lgtm

**Comment by bobfuru** [comment]
LGTM

**Pull request merged**
