### PR TITLE
OCPBUGS-25719: Add OpenStack as supported for IPv6 clusters

### PR DESCRIPTION
**Pull request by MaysaMacedo**
OpenStack is being added as a platform that supports dual-stack network consequently IPv6 networks as well, we need to address that in the docs. Also it does not support single stack IPv6.
context https://issues.redhat.com/browse/OSASINFRA-3210

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
I hope I made the change in the correct place. My goals was to add it here https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html#nw-ovn-kubernetes-matrix_about-ovn-kubernetes

**Comment by JoeAldinger** [comment]
@MaysaMacedo this looks like it has QE LGTM; if you are ready for merge ping me.

**Comment by MaysaMacedo** [comment]
@JoeAldinger it's ready

**Pull request merged**
