### PR TITLE
[OSDOCS-4498]:Provided description of action required for step 6 of Con…

### PR DESCRIPTION
**Pull request by AedinC**
…figuring an OpenID identity provider procedure.

Version(s):

4.13+

Issue:

https://issues.redhat.com/browse/OSDOCS-4498

Link to docs preview:

https://61290--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-config-identity-providers.html#config-openid-idp_rosa-sts-config-identity-providers

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by AedinC** [comment]
> /LGTM

Hi @eldar101. Can you please apply the label `/label qe-approved` to this PR? I am going to create a new issue to research the feasibility of creating a new guide to replace the currently linked one.

**Review by sheriff-rh — APPROVED** [review]
lgtm, merging.

**Pull request merged**
