### PR TITLE
Update the link in the Additional resources section of the Understanding Helm assembly

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
[RHDEVDOCS-4517](https://issues.redhat.com/browse/RHDEVDOCS-4517): Update the link in the Additional resources section of the Understanding Helm assembly

- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.10`, enterprise-`4.11` and later
- **JIRA issues**: [RHDEVDOCS-4517](https://issues.redhat.com/browse/RHDEVDOCS-4517)
- **Preview pages**: [Additional resources in the Understanding Helm section](https://51027--docspreview.netlify.app/openshift-enterprise/latest/applications/working_with_helm_charts/understanding-helm.html#additional-resources)
- **SME Review**: Completed by @dperaza4dustbit
- **QE review**: Completed by @tisutisu 
- **Peer-review**: Completed by @gabriel-rh

### CODE REVIEW

**Review by tisutisu — COMMENTED** [review]
LGTM

**Review by gabriel-rh — APPROVED** [review]
/lgtm

**Review by dperaza4dustbit — APPROVED** [review]
lgtm

**Pull request merged**
