### PR TITLE
Add links to Kube seccomp docs in scc docs

### PR DESCRIPTION
**Pull request by pweil-**
@adellape

### CODE REVIEW

**Comment by pweil-** [comment]
cc @ahardin-rh

**Comment by ahardin-rh** [comment]
@pweil- Looks good! I'll follow up with some minor style edits. Is this targeted for 3.3?

**Comment by pweil-** [comment]
yes, please

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/additional_concepts/authorization.adoc#architecture-additional-concepts-authorization[ Additional Concepts -> Authorization]
|Added a new xref:../architecture/additional_concepts/authorization.adoc#authorization-seccomp[Seccomp] section under Security Context Constraints (SCC) Strategies.
%

**Pull request merged**
