### PR TITLE
masterClientConnectionOverrides set in node-config.yaml is ignored

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1691046

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning @rjhowe 

Which version(s) of OpenShift does this BZ apply to?
https://bugzilla.redhat.com/show_bug.cgi?id=1751952 

3.10 and 3.11, as you know, introduced the node config maps and we ask users to not edit the node-config.yaml. Is this case an exception or should the users add `kube-api-qps` and `kube-api-burst` to the node config maps?

Michael

**Comment by mburke5678** [comment]
3.9 Changes https://github.com/openshift/openshift-docs/pull/17453
3.7 Changes https://github.com/openshift/openshift-docs/pull/17454

**Comment by mburke5678** [comment]
@gpei Please take a look. Thank you!

**Comment by gpei** [comment]
The changes to 3.7&3.9 lgtm, as to 3.10 and 3.11, I noticed we have a specialized section https://docs.openshift.com/container-platform/3.11/admin_guide/manage_nodes.html#configuring-node-resources about how to add parameter to "kubeletArguments", can we add the expected `kube-api-qps` and `kube-api-burst` by following the above doc?

**Comment by mburke5678** [comment]
>  I noticed we have a specialized section https://docs.openshift.com/container-platform/3.11/admin_guide/manage_nodes.html#configuring-node-resources about how to add parameter to "kubeletArguments", can we add the expected kube-api-qps and kube-api-burst by following the above doc?

See https://github.com/openshift/openshift-docs/pull/17585

**Pull request merged**
