### PR TITLE
OSDOCS#7826: Migrate Configuring custom TLS ciphers from MOBB to ROSA

### PR DESCRIPTION
**Pull request by skopacz1**
Version(s): 4.13+

Issue:
[OSDOCS-7826](https://issues.redhat.com/browse/OSDOCS-7826)

Link to docs preview: [Configuring ROSA/OSD to use custom TLS ciphers on the ingress controllers](https://64926--docspreview.netlify.app/openshift-rosa/latest/rosa_tutorials/rosa-mobb-configure-custom-tls-ciphers)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by skopacz1** [comment]
@michaelryanmcneill could you PTAL when you have a chance? Thanks.

**Comment by laubai** [comment]
LGTM @skopacz1 !

**Review by michaelryanmcneill — APPROVED** [review]
/lgtm

**Pull request merged**
