### PR TITLE
BZ#2087235: Removed unnecessary Note and step for installing operator

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.9+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2087235

Link to docs preview: http://file.rdu.redhat.com/snarayan/BZ2087235_sriovoperator/networking/hardware_networks/installing-sriov-operator.html#install-operator-web-console_installing-sriov-operator

OR

https://48814--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/installing-sriov-operator.html#install-operator-web-console_installing-sriov-operator

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@snarayan-redhat, this is awesome, thanks!

**Comment by abhatt-rh** [comment]
LGTM!

**Pull request merged**
