### PR TITLE
bug 1673314 amended federation section

### PR DESCRIPTION
**Pull request by sheriff-rh**
Link to bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=1673314

@qinpingli PTAL
@openshift/team-documentation peer review please!

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM (We probably would have forgiven you for skipping peer review on this one.)

**Comment by vikram-redhat** [comment]
@qinpingli - PTAL.

cc: @xltian

**Comment by qinpingli** [comment]
LGTM

**Comment by vikram-redhat** [comment]
@sheriff-rh reminder to manually cherrypick this to 3.11 branch.

**Pull request merged**
