### PR TITLE
OSDOCS-8484: Fixing cron job timezone's support status

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-8484

Link to docs preview:
https://71198--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#node-technology-preview-features

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
FYI @DCChadwick, since I see that you have the "Node" jira for checking these tables assigned to you. Didn't want to duplicate effort on this one at least.

@cbippley FYI too. Also, you might want to ask about the MaxUnavailableStatefulSet row. I'm assuming that one is still TP, but would be good to double check.

**Review by mjpytlak — COMMENTED** [review]
Peer review lgtm @bergerhoffer

**Pull request merged**
