### PR TITLE
IBM Multi-arch updates

### PR DESCRIPTION
**Pull request by vikram-redhat**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@sjstout @sferich888 had some discussions around adding a note to here: https://docs.openshift.com/container-platform/4.6/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html. The accepted advice is to simply remove from the RN rather than add a note (as that becomes a maintenance issue).

Will leave this here, and merge if no issues with this.

**Comment by sjstout** [comment]
LGTM! Thanks, Vikram!

**Comment by sferich888** [comment]
/lgtm
Do we want to add a note/call out that says more explicity that OVN is not supported on Power and Z in the OVN sections? 
I know you comment talk about having a conversation to not do this, but its not clear what the reasons for this are.

**Comment by bergerhoffer** [comment]
Merging per @sjstout .

**Pull request merged**
