### PR TITLE
[OSDOCS-11363]  Updating images-configuration-allowed to correct MCO…

### PR DESCRIPTION
**Pull request by aksjadha**
…workflow

Adding/removing registries under `spec.registrySources.allowedRegistries` in `image.config.openshift.io/cluster` updates `/etc/containers/policy.json file` on each node. Changes to the `/etc/containers/policy.json` do not require node drain.

Version(s):

4.12, 4.13, 4.14, 4.15, 4.16

Issue:

[https://issues.redhat.com/browse/OSDOCS-11363](https://issues.redhat.com/browse/OSDOCS-11363
)

Link to docs preview:

- [Enterprise branch](https://81068--ocpdocs-pr.netlify.app/openshift-enterprise/latest/openshift_images/image-configuration.html)
- [ROSA](https://81068--ocpdocs-pr.netlify.app/openshift-rosa/latest/openshift_images/image-configuration.html)
- [OSD](https://81068--ocpdocs-pr.netlify.app/openshift-dedicated/latest/openshift_images/image-configuration.html)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by QiWang19 — COMMENTED** [review]
/lgtm

`allowedRegistries` updates /etc/containers/policy.json does not require the node drain.

**Comment by aksjadha** [comment]
Hi @QiWang19 @mburke5678 Thanks for reviewing this PR. Previously [PR](https://github.com/openshift/openshift-docs/pull/79335) was raised for same changes where peer-review completed but I was unable to squash commit and merge PR. So created this one. Can you please confirm if I can merge PR directly as peer-review is already completed? Let me know you thoughts on this.

**Comment by QiWang19** [comment]
@aksjadha  Thanks. I will leave it to the docs team for the final review and merging.

**Pull request merged**
