### PR TITLE
Removing a warning that no longer applies in 4.8+

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://deploy-preview-35956--osdocs.netlify.app/openshift-enterprise/latest/security/audit-log-policy-config?utm_source=github&utm_campaign=bot_dp#about-audit-log-profiles_audit-log-policy-config

### CODE REVIEW

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
@yaoli-redhat Can you please review this?

Preview: https://deploy-preview-35956--osdocs.netlify.app/openshift-enterprise/latest/security/audit-log-policy-config?utm_source=github&utm_campaign=bot_dp#about-audit-log-profiles_audit-log-policy-config

**Comment by bergerhoffer** [comment]
@yaoli-redhat Can you take a look when you get a chance?

**Comment by yaoli-redhat** [comment]
LGTM

**Pull request merged**
