### PR TITLE
OADP-5391 remove legacy-aws plugin usecase from 4.13

### PR DESCRIPTION
**Pull request by shdeshpa07**
## Jira 

* [OADP-5391](https://issues.redhat.com/browse/OADP-5391)

Removed the legacy-aws plugin use case from enterprise 4.13 as feature is not supported in OADP 1.3

##  Version

* OCP 4.13

## QE Review

* [x] QE has approved this change.

### CODE REVIEW

**Comment by shdeshpa07** [comment]
@anarnold97  - Could you please review this PR? Thanks.

**Comment by anarnold97** [comment]
@shdeshpa07 - LGTM

**Comment by shdeshpa07** [comment]
@amastbau - Could you please review? Thanks.

**Comment by amastbau** [comment]
LGTM

**Comment by michaelryanpeter** [comment]
I am going to go ahead and merge this, but I just want to point out that 4.13 is EOL and no longer supported.

While backports to 4.12 that pass over 4.13 are still being cherrypicked for consistency, but my understanding is that any issues or bugs that target 4.13-only can be closed. If you have questions or concerns, please raise them in the #team-ocp-docs or #forum-ocp-docs channels in Slack.

**Comment by anarnold97** [comment]
@michaelryanpeter - thanks for the update. Please can I ask for your advice about 4.13? 
I am just a wee bit concerned about the [OCP Operator Lifecycle page](https://access.redhat.com/support/policy/updates/openshift_operators)
image

Thanks

**Comment by anarnold97** [comment]
Just the question you want on a Friday afternoon! LOL

**Comment by michaelryanpeter** [comment]
I think it is worth raising a discussion about this in Slack. 

I don't have a final say on this, but I can raise it in my peer review channel. 

As you can see [here](https://access.redhat.com/support/policy/updates/openshift#dates), 4.13 is no longer listed in the support dates. And if you look [here](https://access.redhat.com/product-life-cycles?product=OpenShift%20Container%20Platform%204) maintenance support ended for 4.13 on Nov 17, 2024

If we are in a situation where the OADP Operator is still supported in 4.13 even though 4.13 itself is not supported, that would be something to call out in comment zero of the PR.

Also, on Jan. 17, 2025, 4.12 becomes EOL, so we'll need to come up with a plan to avoid confusion or having to do this dance with every backport.

**Comment by anarnold97** [comment]
@michaelryanpeter - thanks very much, have asked in OCP DOCS Slack channel. 

But i have to say *Great sidestep*  LOL

**Comment by michaelryanpeter** [comment]
well, it's not much of a sidestep when I don't have the authority to decide :laughing:

**Pull request merged**
