### PR TITLE
OSDOCS#8505: Removing auth dep/rem table since there are no items

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-8505

Link to docs preview:
https://69924--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-deprecated-removed-features

QE review:
No QE required

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@cbippley Let me know if this is the right approach, to remove this table if there are no items in it. Thanks!

**Comment by cbippley** [comment]
@bergerhoffer In the past we've simply commented out things that were empty but might be used later. That's probably still the way to go.

**Comment by bergerhoffer** [comment]
> @bergerhoffer In the past we've simply commented out things that were empty but might be used later. That's probably still the way to go.

Cool thanks, I'll update to just comment them out

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
