### PR TITLE
BZ2076635: Fix the parameters in example YAML

### PR DESCRIPTION
**Pull request by xenolinux**
OCP version: 4.10 only
[Preview](https://deploy-preview-44959--osdocs.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-configure-bfd-profiles.html#nw-metallb-configure-bfdprofile_configure-metallb-bfd-profiles)
QA contact: @zhaozhanqi 
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2076635)

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@asood-rh Please help take a look, and move the bug to verified if it's ok, thanks.

**Comment by pneedle-rh** [comment]
@xenolinux the specification changes in this PR look good to me from a peer review perspective.

Can you please confirm that the changes are not required for `main` and `enterprise-4.11` also? Thanks!

**Comment by xenolinux** [comment]
> @xenolinux the specification changes in this PR look good to me from a peer review perspective.
> 
> Can you please confirm that the changes are not required for `main` and `enterprise-4.11` also? Thanks!

@pneedle-rh Right now the module is only present in OCP version 4.10. 
@zhaozhanqi Can you please guide, if this change also applies to OCP version 4.11?

**Comment by asood-rh** [comment]
@xenolinux These values for the BFD profile should work functionally with 4.11, if found differently a bug will be logged. The user is at liberty to tweak the values to their needs. These are just suggested values for various parameters.

**Comment by xenolinux** [comment]
> @xenolinux These values for the BFD profile should work functionally with 4.11, if found differently a bug will be logged. The user is at liberty to tweak the values to their needs. These are just suggested values for various parameters.

@asood-rh Thanks for confirming. 
@pneedle-rh Based on this comment, IMO we can include these values in enterprise-4.11. WDYT?

**Comment by pneedle-rh** [comment]
>  @pneedle-rh Based on this comment, IMO we can include these values in enterprise-4.11. WDYT? I don't think this change will apply to `main` since the module is only present in 4.10

@xenolinux we have discussed how to best proceed, within the Peer Review Squad. The `modules/nw-metallb-configure-bfdprofle.adoc` module is present in `main` and `enterprise-4.11`. Given that the content is relevant to 4.11 and the module exists, can you please base your PR for the update on `main` instead of `enterprise-4.10`? We can then cherry pick the changes to `enteprise-4.11` and `enterprise-4.10` after the PR is merged.

I will include a link in Slack to a section of the docs manual that provides steps to rebase your feature branch off of a different base branch.

Thanks!

**Pull request closed without merging**
