### PR TITLE
MIG-1341 MTC 1.7.10 Release Notes

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
[MIG-1341](https://issues.redhat.com//browse/MIG-1341) MTC 1.7.10 Release Notes
MTC 1.7.10
OCP 4.12+
Preview: https://61122--docspreview.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/mtc-release-notes.html#migration-mtc-release-notes-1-7-10_mtc-release-notes

### CODE REVIEW

**Review by dymurray — APPROVED** [review]
LGTM! Thanks!

**Review by midays — APPROVED** [review]
LGTM

**Comment by RichardHoch** [comment]
If "munged" is a verb our users will recognize, LGTM. Maybe "changed" or "altered" would be clearer.

**Comment by sbeskin-redhat** [comment]
> If "munged" is a verb our users will recognize, LGTM. Maybe "changed" or "altered" would be clearer.

Changed to "manipulated"

**Comment by tmalove** [comment]
@sbeskin-redhat  Be sure to squash your commits before requesting merge request. Other than that, looks good.

/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Comment by sbeskin-redhat** [comment]
@jeana-redhat 
Thank you! Will it be published immediately?

**Comment by sbeskin-redhat** [comment]
@jeana-redhat 
Thank you! 
When will it be published?

**Comment by jeana-redhat** [comment]
> @jeana-redhat Thank you! When will it be published?

There's information about this in the manual, I think this heading link will work: https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.iyf01wqu3fak

If you have further questions or things aren't online as expected, please reach out to a DPM :slightly_smiling_face:

**Pull request merged**
