### PR TITLE
OSDOCS-4526: Improvement of the docs about Pod Topology Spread Contraints under Nodes

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4526

Link to docs preview:
- https://78674--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-pod-topology-spread-constraints.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoaoBraveCoding — APPROVED** [review]
/lgtm

**Comment by ingvagabund** [comment]
LGTM

**Pull request merged**
