### PR TITLE
OCPBUGS#4334: Change the url in sample LDAP CR

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OCPBUGS-4334

Link to docs preview: https://56444--docspreview.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-ldap-identity-provider.html#identity-provider-ldap-CR_configuring-ldap-identity-provider

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xingxingxia** [comment]
/cc @zhouying7780 
@zhouying7780 please help take a look, thanks!

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
