### PR TITLE
clarify how service cert annotations are defined

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k ptal

**Comment by bparees** [comment]
@deads2k not sure how far back serving certs go, please adjust labels as needed.

**Comment by deads2k** [comment]
lgtm

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bmcelvee** [comment]
LGTM

**Comment by bmcelvee** [comment]
No rev history needed.

**Pull request merged**
