### PR TITLE
Remove numbered OSP playbook prefixes

### LINKED ISSUE #21365: ShiftStack UPI Ansible playbooks no longer include numbers in names - 4.5+
### Which section(s) is the issue in?

Many ShiftStack user-provisioned infrastructure modules

### What needs fixing?

4.4: https://github.com/openshift/installer/tree/release-4.4/upi/openstack
Post-4.4: https://github.com/openshift/installer/tree/master/upi/openstack

FYI @pierreprinetti

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR resolves #21365.

Jira ticket: https://issues.redhat.com/browse/OSDOCS-1572

Any concerns with this, @pierreprinetti?

### CODE REVIEW

**Review by pierreprinetti — APPROVED** [review]
zero concerns :+1:

**Comment by maxwelldb** [comment]
Thanks!

**Comment by maxwelldb** [comment]
@wjiang or @gpei Would either of you be able to ack this?

**Comment by maxwelldb** [comment]
edit to add @wjiangjay there ^^^. I used your CoreOS Slack name rather than your GH one.

**Comment by maxwelldb** [comment]
Adding QE requests for a few more OSP folks...

**Comment by maxwelldb** [comment]
@pierreprinetti Is there anyone in particular you could recommend to QE this?

**Comment by maxwelldb** [comment]
@wjiangjay @gpei @chao007 @rlobillo Anyone able to +1 this?

**Comment by wjiangjay** [comment]
@maxwelldb Sorry for the delay, LGTM

**Comment by maxwelldb** [comment]
TODO on cherrypicks: sub in proper release branch URLs for 4.5-4.7.

**Review by bergerhoffer — COMMENTED** [review]
These changes LGTM!

But I did see one playbook reference in this assembly that still has a number in it - `cluster-scheduler-02-config.yml` - just checking if that needed updated too or not.

**Comment by maxwelldb** [comment]
@bergerhoffer That should be fine to stay--not a part of the OSP UPI playbooks.

**Comment by maxwelldb** [comment]
Thanks!

**Pull request merged**
