### PR TITLE
GH#52610 updating deprecated parameter name

### LINKED ISSUE #52610: [enterprise-4.11] Issue in file scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
### Which section(s) is the issue in?
"How to plan your environment according to application requirements" code snippet.

### What needs fixing?
service .spec.portalIP was renamed to clusterIP in 2015. We should update the documentation to remove this deprecated field.

### PR DESCRIPTION
**Pull request by skopacz1**
Versions 4.8+

Fixes #52610

Replaces portalIP, which is deprecated according to the linked issue, with clusterIP.

Preview: https://52638--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#how-to-plan-according-to-application-requirements_object-limits

### CODE REVIEW

**Comment by skopacz1** [comment]
@lenahorsley PTAL, thank you!

**Comment by lenahorsley** [comment]
@skopacz1 Did you tag the correct person?

**Comment by skopacz1** [comment]
Hi @lenahorsley , would you be an appropriate QE to tag to review a doc change in Performance and Scalability? If not, my apologies!

**Comment by lenahorsley** [comment]
@skopacz1 No problem. I'm a QE with Performance and Scalability, but I might not be the best person to review this doc. One of my team leads, @paigerube14  or @qiliRedHat , might be a better choice.

**Comment by skopacz1** [comment]
@lenahorsley sounds good, thanks for tagging alternative QEs!

@paigerube14 or @qiliRedHat would you be able to give this PR a review?

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Pull request merged**
