### PR TITLE
BZ 1493743  Added full path to s2I images for 3.5

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1493743

### CODE REVIEW

**Comment by mburke5678** [comment]
Che:
I added the paths. Can you or someone confirm the versions in the paths? Especially the images for which we did not list version numbers:
mongodb
mysql
nodejs
perl
php
postgresql
python
ruby

For docker pull jboss-amq-62 I got: There are no image results for query "jboss-amq-62"

Kevin: I added a link to [OpenShift and Atomic Platform Tested Integrations page](https://access.redhat.com/articles/2176281) for versioning policy

**Comment by mburke5678** [comment]
@travisrogers05 Updated the list of images for new and deprecated images per your comment in BZ. PTAL

**Comment by mburke5678** [comment]
[Verified by QE in BZ.](https://bugzilla.redhat.com/show_bug.cgi?id=1493743#c17)

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Added full command and path to pull S2I images from Docker for 3.5 images

**Comment by bfallonf** [comment]
@mburke5678 LGTM :star:

**Pull request merged**
