### PR TITLE
BZ 1851760: cloning between volume modes

### PR DESCRIPTION
**Pull request by ousleyp**
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1851760

Preview build: https://cloning-volume-modes--ocpdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-datavolume-block.html

enterprise-4.5, 4.6

### CODE REVIEW

**Review by aglitke — COMMENTED** [review]
lgtm

**Review by bergerhoffer — COMMENTED** [review]
One suggestion, otherwise LGTM!

**Pull request merged**
