### PR TITLE
[OSDOCS-12204][OSD-GCP] Remove outdated note and add RH Marketplace option link to docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-12204
Link to docs preview:

https://82778--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/policy-process-security.html#network-security_policy-process-security
QE review:
https://82778--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_getting_started/osd-getting-started.html#osd-getting-started-create-cluster-ccs
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by abrennan89 — COMMENTED** [review]
/lgtm

**Comment by skrthomas** [comment]
merge review /lgtm

**Pull request merged**
