### PR TITLE
BUGBZ1637616 - removed port number 8888

### PR DESCRIPTION
**Pull request by jhoyt-rh**
@ kimettog PTAL at this very minor change
@ gkimetto@redhat.com PTAL
@ chao007 PTAL
@openshift/team-documentation PTAL at this very minor change

### CODE REVIEW

**Comment by mburke5678** [comment]
@jhoyt-rh LGTM. Might add a link to the BZ (I put it as the description) for easy reference.

**Comment by vikram-redhat** [comment]
Hi @jhoyt-rh  - this should be against the master branch first and then CP'ed to 3.10 and if applicable, to the 3.11 branch as well.

**Comment by jboxman** [comment]
@jhoyt-rh, if you click **Edit** in the top right of the PR title, you can change the "commit into" base from enterprise-3.10 to master and click **Save**. That should change the PR target to master.

**Review by kimettog — COMMENTED** [review]
Looks good

**Comment by chao007** [comment]
LGTM
Thanks.

**Comment by jhoyt-rh** [comment]
Added Enterprise-3.11 for label, since I will cherrypick to that branch also.

**Pull request merged**
