### PR TITLE
Documentation indicates OpenShiftSDN is a (preferred) supported default network CNI Provider

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/okd/issues/457

### CODE REVIEW

**Comment by mburke5678** [comment]
@vrutkovs PTAL
* Added a note that OVN-Kubernetes is the default to the _About SDN_ and _Cluster Network Operator configuration_ topics.
* Updated *Optional parameters* table in _Installation configuration parameters_ topic to show default `OVNKubernetes` for `networking.networkType`.
* Changed the `networking.networkType:` to `OVNKubernetes` as appropriate in sample YAML file in the install docs

**Review by vrutkovs — APPROVED** [review]
Perfect, thanks!

**Comment by mburke5678** [comment]
@codyhoag FYI

**Comment by jboxman** [comment]
@mburke5678 yeah, I just changed `modules/installation-configuration-parameters.adoc` last night so that's going to merge fail.

**Comment by jboxman** [comment]
@mburke5678 that section is now like so:

```
|`networking.networkType`
|The default Container Network Interface (CNI) network provider plug-in to install.
ifdef::openshift-origin[]
Either `OpenShiftSDN` or `OVNKubernetes`. The default value is `OVNKubernetes`.
endif::openshift-origin[]
ifndef::openshift-origin[]
Either `OpenShiftSDN` or `OVNKubernetes`. The default value is `OpenShiftSDN`.
endif::openshift-origin[]
|String
```

**Pull request merged**
