### PR TITLE
OCPBUGS-16667#correcting typo

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-16667

Link to docs preview:
https://75131--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-baremetal-etcd-member_replacing-unhealthy-etcd-member [Update applied to the first entry in the 'ID' column of the example output in section 'e' of step 1] 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
Please add labels for 4.12, 4.13, 4.14, 4.15, and 4.16 as I don't have permissions.

**Comment by aspauldi** [comment]
Looks good to me!

**Comment by brendan-daly-red-hat** [comment]
QE review added to https://issues.redhat.com/browse/OCPBUGS-16667

**Comment by skrthomas** [comment]
merge review lgtm

**Pull request merged**
