### PR TITLE
BZ2020573: Fix typo in pipelines release notes

### PR DESCRIPTION
**Pull request by cowgirljessi**
Typo fixed per https://bugzilla.redhat.com/show_bug.cgi?id=2020573

Change applies to 4.8+

No QE required.

Preview build: https://deploy-preview-39719--osdocs.netlify.app/openshift-enterprise/latest/cicd/pipelines/op-release-notes#new-features-1-5_op-release-notes

### CODE REVIEW

**Comment by bmcelvee** [comment]
@vikram-redhat do we need to add @cowgirljessi to any teams to get Netify and the checks to run? Thanks! 

Also first PR! :tada:

**Comment by vikram-redhat** [comment]
First PR!!! Yeah @cowgirljessi!

@bmcelvee - no it should just run. Travis was just being Travis, and I did the ole open and close the PR trick to make it work.

**Comment by vikram-redhat** [comment]
FWIW, I plan to explore options to migrate away from Travis over the holidays.

**Comment by bmcelvee** [comment]
Thank you, @vikram-redhat!!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
