### PR TITLE
BZ2029511: Documentation update for Volumes with high file counts delay pod creation due to recursive SELinux file context relabeling 3.11

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=2029511

Previews:
[Use pods and claimed PVs](https://deploy-preview-41174--osdocs.netlify.app/openshift-enterprise/latest/architecture/additional_concepts/storage.html#using)
[Configuring Persistent Storage Overview](https://deploy-preview-41174--osdocs.netlify.app/openshift-enterprise/latest/install_config/persistent_storage/index.html)
 [Persistent Storage Examples Overview](https://deploy-preview-41174--osdocs.netlify.app/openshift-enterprise/latest/install_config/storage_examples/index.html)

### CODE REVIEW

**Comment by mburke5678** [comment]
@haircommander PTAL. If you can suggest a better place in the docs, or additonal places, please let me know. 

FYI: @lpettyjo

**Comment by mburke5678** [comment]
4.x PR https://github.com/openshift/openshift-docs/pull/41173

**Comment by haircommander** [comment]
We don't have a fix for 3.11. Do we still want it in the docs?

**Comment by mburke5678** [comment]
@haircommander Does the workaround not work in 3.11? The article lists OpenShift 3 and 4, I assumed that the procedure works in 3.11:
```

Environment
    Red Hat OpenShift Container Platform 3
    Red Hat OpenShift Container Platform 4
```

**Comment by haircommander** [comment]
ah it affects both, but the workaround only works in 4

**Comment by mburke5678** [comment]
Closing per [Peter's comment](https://github.com/openshift/openshift-docs/pull/41174#issuecomment-1025831617).

**Pull request closed without merging**
