### PR TITLE
Add edits to PR 8990

### PR DESCRIPTION
**Pull request by ghost**
Follow up to: https://github.com/openshift/openshift-docs/pull/8990

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@qinpingli Can you sign off on this PR for QE? I made a few additional edits on top of the merged content.

Cc: @gnufied

**Comment by tmorriso-rh** [comment]
Merge and then CP to 3.9 and 3.10.

**Comment by gnufied** [comment]
LGTM

**Pull request merged**
