### PR TITLE
Quay URL for configuring firewall

### LINKED ISSUE #22990: [enterprise-4.4] Edit suggested in file installing/install_config/configuring-firewall.adoc
### Which section(s) is the issue in?

In Whitelist the following registry URLs:
...
*.quay.io
...
### What needs fixing?
Replace quay.io instead of *.quay.io. (Because firewall think https://quay.io cannot match *.quay.io with the dot before "quay.io")

### PR DESCRIPTION
**Pull request by codyhoag**
Suggested in #22990

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you confirm this? It was reported that the asterisk was affecting the firewall's ability to match the URL.

**Comment by gpei** [comment]
yes, `quay.io` is the address provides the product images.

**Comment by bmcelvee** [comment]
LGTM

**Pull request merged**
