### PR TITLE
Add minimum resources table to all AWS/Azure/GCP IPI installation docs

### PR DESCRIPTION
**Pull request by codyhoag**
Two things done in this PR:

1. Modularize the minimum resources table, which was previously nested in a UPI module along with other UPI sub-sections.
2. Apply the new modularized table to AWS|Azure|GCP IPI assemblies.

This is in preparation for a follow-up PR, which will auto-include instance type lists.

This touches many assemblies. I have included previews for a UPI and IPI assembly for each provider, where necessary:

**IPI assemblies with new minimum resources table:** (QE needed)

* [AWS IPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-minimum-resource-requirements_installing-aws-customizations)
* [Azure IPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-minimum-resource-requirements_installing-azure-customizations)
* [GCP IPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-minimum-resource-requirements_installing-gcp-customizations)

**Modularization of existing UPI content:**

* [AWS UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-user-infra.html#installation-requirements-user-infra_installing-aws-user-infra)
* [Azure UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-requirements-user-infra_installing-azure-user-infra)
* [GCP UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-requirements-user-infra_installing-gcp-user-infra)
* [bare metal UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-requirements-user-infra_installing-bare-metal)
* [IBM Z UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z.html#installation-requirements-user-infra_installing-ibm-z)
* [IBM Power UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power.html#installation-requirements-user-infra_installing-ibm-power)
* [vSphere UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere.html#installation-requirements-user-infra_installing-vsphere)
* [VMC UPI](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-vmc-user-infra.html#installation-requirements-user-infra_installing-vmc-user-infra)

### CODE REVIEW

**Comment by codyhoag** [comment]
For a summarized QE review, I have included the [minimum resources table](https://deploy-preview-41130--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-minimum-resource-requirements_installing-aws-customizations) to all AWS, Azure, and GCP IPI assemblies. The remaining changes are docs reorg to allow that to be possible.

@yunjiang29 @MayXuQQ @jianli-wei can you confirm for AWS, Azure, and GCP, respectively? Thanks!

**Comment by yunjiang29** [comment]
@codyhoag  the section `Supported AWS machine types` will be replaced by https://github.com/openshift/installer/pull/5517 in the final version, is it right?

**Comment by MayXuQQ** [comment]
I checked Azure Minimum resource on Azure
when select the vm size, need PremiumIO==True and the vCPU is vCPUsAvailable 
(check the vm size details as "az vm list-skus -l <region> --size <vm size>" 
eg: az vm list-skus -l centralus --size Standard_D2s_v3

**Comment by codyhoag** [comment]
>@codyhoag the section Supported AWS machine types will be replaced by openshift/installer#5517 in the final version, is it right?

@yunjiang29 that's correct. This is part 1 of that effort, which is to get the mimumum resources table in for all install assemblies for AWS|Azure|GCP. Then those instance type lists will be added as a follow-up :slightly_smiling_face:

**Comment by yunjiang29** [comment]
@codyhoag get it, AWS part LGTM.

**Comment by codyhoag** [comment]
@MayXuQQ I've added the requirement for premium IO for Azure machines. Do you have any additional feedback?

**Comment by MayXuQQ** [comment]
PremiumIO,HyperVGenerations are property of the vm size, for OCP, now just support the vm size which "PremiumIO" is "true" and HyperVGenerations contains 'V1'

**Comment by codyhoag** [comment]
@MayXuQQ thank you for that clarification. I have updated the guidance. Can I get a final verification?

**Comment by MayXuQQ** [comment]
the `hyperVGeneration` property **contains** `V1`, not set . 
hyperVGeneration can be "V1,V2" or "V1", or "V2", now ocp can be used the vm size which hyperVGeneration contains 'V1". 
@codyhoag

**Comment by MayXuQQ** [comment]
You are required to use Azure virtual machines with `premiumIO` **is** `true`.  @codyhoag

**Comment by MayXuQQ** [comment]
all the vm size have "premiumIO" and "hyperVGeneration" properties, but different values, premiumIO can be "True" or "False",
hyperVGeneration can be "V1,V2", or "V1", or "V2"
we just use the vm which hyperVGeneration contains "V1" and "premiumIO" is "True". 
@codyhoag 
https://docs.microsoft.com/en-us/javascript/api/@azure/arm-machinelearningservices/virtualmachinesize?view=azure-node-latest#@azure-arm-machinelearningservices-virtualmachinesize-premiumio

**Comment by codyhoag** [comment]
@jianli-wei is this good from a GCP perspective? Thanks!

**Comment by jianli-wei** [comment]
@codyhoag There's "Supported AWS machines types" section for AWS, wonder if there's corresponding section for GCP, could you clarify? BTW, others on GCP looks good to me. Thanks!

**Comment by codyhoag** [comment]
@jianli-wei yes, the instance type lists for GCP will be added in a follow-up PR. It will reference lists from the installer repo we worked on.

**Pull request merged**
