### PR TITLE
BZ1979956: Round 2 of edits on the main branch

### PR DESCRIPTION
**Pull request by tmulquee**
Version(s):
4.7, 4.8, 4.9, 4.10, 4.11, 4.12

Link to docs preview:
http://file.emea.redhat.com/tmulquee/BZ1979956/installing/installing_bare_metal_ipi/ipi-install-overview.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tmulquee** [comment]
This is based on a PR that has already been merged: https://github.com/openshift/openshift-docs/pull/49290

A new merge is requested to implement edits that were picked up during cherry-picking: https://github.com/openshift/openshift-docs/pull/50109

**Comment by bscott-rh** [comment]
Two small nits, otherwise it LGTM.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by jboxman-rh** [comment]
@tmulquee, I've created two manual cherry picks for 4.9 and 4.8. I attempted one for 4.7, but the content is different enough I'm not sure how to handle it. If this needs to go back to 4.7 as well, can you create a manual cherry-pick for that branch?

Thanks!

**Pull request merged**
