### PR TITLE
Adding a note that you must have cluster-admin permissions to use oc …

### PR DESCRIPTION
**Pull request by bergerhoffer**
…adm commands

Preview: https://deploy-preview-38501--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by bmcelvee** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
QE ack for wording is in #38500.

**Pull request merged**
