### PR TITLE
wip: do not merge

### PR DESCRIPTION
**Pull request by gaurav-nelson**
APB CLI updates

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat?

**Comment by vikram-redhat** [comment]
@kalexand-rh one of the things we have had to drop as a result of the BNE changes.

**Comment by kalexand-rh** [comment]
That's fair, @vikram-redhat. This might be a good PR to close when you prune the list.

**Comment by vikram-redhat** [comment]
Closing this till we have resources to look at it.

**Comment by vikram-redhat** [comment]
@bergerhoffer - PTAL at this when you get a chance.

**Pull request closed without merging**
