### PR TITLE
OBSDOCS-1083:Update the Tech preview status table for Metrics Server GA

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `enterprise-4.16`  only

Issue: [OBSDOCS-909](https://issues.redhat.com/browse/OBSDOCS-909)

Link to docs preview: https://76545--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-technology-preview-tables

QE review:
- [x] QE has approved this change.

**Additional information:** This issue updates the TP feature table. The release note text will be added as part of [RN new features](https://issues.redhat.com/browse/OBSDOCS-838) issue

### CODE REVIEW

**Comment by mburke5678** [comment]
@eromanova97 LGTM Please post a preview if you need a merge review.

**Comment by eromanova97** [comment]
> @eromanova97 LGTM Please post a preview if you need a merge review.

Hello @mburke5678 sorry I forgot to update the comment with preview, I added it now :+1:

**Comment by eromanova97** [comment]
Hello @mburke5678 could you let me know if I can proceed with the review process? I will then add the `merge-review-needed` label, thank you!

**Pull request merged**
