### PR TITLE
`compute` is not an array

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/23709

### CODE REVIEW

**Comment by jboxman** [comment]
Hi @lihongan,

Can you confirm if the updated YAML is correct?

Thanks!

**Comment by lihongan** [comment]
@gpei Could you or someone from your team take a look? thanks

**Comment by gpei** [comment]
yes, it lgtm.

**Comment by jboxman** [comment]
@gpei @lihongan thank you!

**Pull request merged**
