### PR TITLE
bug 1714155 adding etcd v3 command

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1714155

@jianlinliu, will you PTAL or assign a different reviewer? @wanghaoran1988  did a lot of the verification for the etcd changes I made last year.

### CODE REVIEW

**Comment by geliu2016** [comment]
@kalexand-rh LGTM, thx

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Pull request merged**
