### PR TITLE
BZ-1845274: Updating apiVersion for SCC examples

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1845284

Preview: 
* https://bz-1845274--ocpdocs.netlify.app/openshift-enterprise/latest/authentication/managing-security-context-constraints.html#security-context-constraints-creating_configuring-internal-oauth
* https://bz-1845274--ocpdocs.netlify.app/openshift-enterprise/latest/authentication/managing-security-context-constraints.html#security-context-constraints-example_configuring-internal-oauth

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@tkashem Can you confirm that it's correct to update the apiVersion for these two SCC examples? And whether the update can be backported all the way back to 4.2, or if it needs to stay v1 in any older versions?

**Comment by bmcelvee** [comment]
LGTM

**Comment by tkashem** [comment]
LGTM

@marun can you please review?

**Comment by stlaz** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@barleyer Could you please review this update? Thanks!

**Review by cybertron — APPROVED** [review]

**Comment by barleyer** [comment]
LGTM

**Comment by vikram-redhat** [comment]
Just testing some stuff, please ignore the next few commands

**Pull request merged**
