### PR TITLE
ROX-21159: Add container name field to docs

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
4.4+

[Issue](https://issues.redhat.com/browse/ROX-21159)

[Link to docs preview
](https://77592--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/audit-listening-endpoints.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoukoVirtanen — APPROVED** [review]

**Review by agantony — COMMENTED** [review]
Added a comment for your consideration; overall lgtm!

**Pull request merged**
