### PR TITLE
GitHub 41621: adds \ to combine command that is separated on 2 lines  

### PR DESCRIPTION
**Pull request by JoeAldinger**
4.8+

GitHub issue #41621 

[Preview](https://deploy-preview-41852--osdocs.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)

Fixes a command that was broken into two lines by adding \ to combine the command into a single line.

### CODE REVIEW

**Comment by Preeticp** [comment]
Hi @rjeczkow @varshab1210 @jaideepr97 can one of you please LGTM this PR if it looks good to you.

**Comment by jaideepr97** [comment]
@Preeticp LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
