### PR TITLE
BZ#1884298 vSphere Networking version adjustments

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1884298

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma can you please confirm this for OCP 4.6?

**Comment by codyhoag** [comment]
@jinyunma bump. Can you confirm this for OCP 4.6? Thanks!

**Comment by codyhoag** [comment]
Marc Curry confirmed that this has already been certified. No QE review necessary.

**Comment by sjstout** [comment]
LGTM. Thanks, Cody!

**Review by bergerhoffer — APPROVED** [review]
LGTM!

**Comment by mcurry-rh** [comment]
LGTM

**Comment by codyhoag** [comment]
This has been given an exception to merge for master and 4.6. Merging now.

**Pull request merged**
