### PR TITLE
Pulling in new changes from autogen CLI output after code freeze

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1790

Re-ran the auto gen after code freeze to pull in any last minute changes. Just one additional example has been added.

Preview: https://deploy-preview-33493--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html#oc-adm-catalog-mirror

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@zhouying7780 Thanks for the review of the other auto-generated CLI output PR. I ran it one more time here after code freeze to get any last minute changes. There's just one more example that has been added, if you don't mind doing a quick review on it please.

Preview: https://deploy-preview-33493--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html#oc-adm-catalog-mirror

**Comment by lpettyjo** [comment]
LGTM, but needs sr peer reviewer to check.

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Pull request merged**
