### PR TITLE
metrics: reencrypte route simplified; validations

### PR DESCRIPTION
**Pull request by sosiouxme**
Use the oc create route command to make it a lot simpler to create the
reencrypt route.
Discuss deployer validations.
Make minor wording/terminology fixes.

### CODE REVIEW

**Comment by sosiouxme** [comment]
@adellape this has changes that are only correct in OSE 3.2 (`oc create route reencrypt` did not exist in 3.1 AFAIK), as we discussed. Also has some origin-only changes that I expect will percolate into 3.2 later.

**Comment by sosiouxme** [comment]
I pulled the origin-only parts out.

**Comment by adellape** [comment]
@sosiouxme Sorry, can you rebase this?

**Comment by sosiouxme** [comment]
rebased

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
[rev_history]
|link:../install_config/cluster_metrics.html[Enabling Cluster Metrics]
|Simplified the link:../install_config/cluster_metrics.html#metrics-reencrypting-route[Using a Re-encrypting Route] section.
%

**Pull request merged**
