### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by rohennes**
Minor typo
https://60435--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.html

Version: 4.13+

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]
@rohennes This is 4.13+, correct?

**Comment by rohennes** [comment]
Yes, sorry

**Comment by rohennes** [comment]
Yes ready to merge @maxwelldb

**Pull request merged**
