### PR TITLE
OSDOCS#11328: Removing unsupported versions of the descheduler operator

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-11328

Link to docs preview:
https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/index.html
https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-configuring.html
https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-release-notes.html
https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-uninstalling.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @kasturinarra Can you please review? This is just removing the unsupported descheduler operator versions and adding the same note we always do about that the operator isn't available yet right after GA. 

Previews: 
* https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/index.html
* https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-configuring.html
* https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-release-notes.html
* https://78902--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/descheduler/nodes-descheduler-uninstalling.html

**Review by lahinson — COMMENTED** [review]
Assuming this gets approved by QE, this looks good to me.

**Comment by ingvagabund** [comment]
LGTM

**Pull request merged**
