### PR TITLE
Fixing some build errors

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@lamek Can I get a quick review of this to make sure that the changes to your networking file are correct? Right now, the numbering and callouts are off a bit.

**Review by lamek — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
FYI @Preeticp - this PR removes some xrefs in two of your files. I've removed them because we currently don't allow xrefs in modules (only in assemblies). But mainly this was found because the following errors were showing up in the build:

```
ERROR (modules/odc-starting-rolling-deployment.adoc): "xref:../applications/application-life-cycle-management/odc-creating-applications-using-developer-perspective.adoc#odc-creating-applications-using-developer-perspective[Creating and deploying applications on {product-title} using the *Developer* perspective]" appears to try to reference a file not included in the "openshift-enterprise" distro

ERROR (modules/odc-starting-rolling-deployment.adoc): "xref:../applications/application-life-cycle-management/odc-viewing-application-composition-using-topology-view.adoc#odc-viewing-application-composition-using-topology-view[Viewing the applications in your project, verifying their deployment status, and interacting with them in the *Topology* view]" appears to try to reference a file not included in the "openshift-enterprise" distro

ERROR (modules/odc-starting-recreate-deployment.adoc): "xref:../applications/application-life-cycle-management/odc-creating-applications-using-developer-perspective.adoc#odc-creating-applications-using-developer-perspective[Creating and deploying applications on {product-title} using the *Developer* perspective]" appears to try to reference a file not included in the "openshift-enterprise" distro

ERROR (modules/odc-starting-recreate-deployment.adoc): "xref:../applications/application-life-cycle-management/odc-viewing-application-composition-using-topology-view.adoc#odc-viewing-application-composition-using-topology-view[Viewing the applications in your project, verifying their deployment status, and interacting with them in the *Topology* view]" appears to try to reference a file not included in the "openshift-enterprise" distro
```

Just a heads up in case you needed to include these additional resources from the assembly or anything.

**Comment by Preeticp** [comment]
@bergerhoffer thank you so much for the heads up. I had almost missed this notification. And thanks for the suggestion to add them as additional resources, doing just that!

**Pull request merged**
