### PR TITLE
BZ1892610: missing pipe (|) in a bash command dealing with pull-secret

### PR DESCRIPTION
**Pull request by jeana-redhat**
for https://bugzilla.redhat.com/show_bug.cgi?id=1892610

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@openshift/team-documentation ready for review

**Comment by jeana-redhat** [comment]
for https://bugzilla.redhat.com/show_bug.cgi?id=1892610

**Comment by jboxman** [comment]
@jeana-redhat, LGTM.

**Pull request merged**
