### PR TITLE
BZ1903980: Removing references to internal registry

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Fix for bug: https://bugzilla.redhat.com/show_bug.cgi?id=1903980
Release: 4.8, 4.9

@jianli-wei - Kindly review these changes.

### Preview links
**AWS** 
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.html#installation-aws-config-yaml_installing-restricted-networks-aws-installer-provisioned

**GCP**
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.html#installation-gcp-config-yaml_installing-restricted-networks-gcp-installer-provisioned

**VSphere**

- https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.html#installation-installer-provisioned-vsphere-config-yaml_installing-restricted-networks-installer-provisioned-vsphere
- https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere

**VMC**
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc.html#installation-installer-provisioned-vsphere-config-yaml_installing-restricted-networks-vmc

**OpenStack**
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-restricted.html#installation-osp-restricted-config-yaml_installing-openstack-installer-restricted

**Bare metal**
- https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#modify-the-install-config-yaml-file-to-use-the-disconnected-registry-optional
- https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-bare-metal-config-yaml_installing-restricted-networks-bare-metal

**IBM Power**
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-restricted-networks-ibm-power.html#installation-bare-metal-config-yaml_installing-restricted-networks-ibm-power

**IBM Z**
https://deploy-preview-35747--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.html#installation-bare-metal-config-yaml_installing-restricted-networks-ibm-z-kvm

### CODE REVIEW

**Comment by jianli-wei** [comment]
LGTM, thanks!

**Review by mikemckiernan — COMMENTED** [review]
/lgtm

**Pull request merged**
