### PR TITLE
[enterprise-4.10] change default to random

### LINKED ISSUE #54713: [enterprise-4.10] Issue in file networking/routes/route-configuration.adoc
### Which section(s) is the issue in?

- [4.8 - Route-specific annotations](https://docs.openshift.com/container-platform/4.8/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration)
- [4.9 -  Route-specific annotations](https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration)
- [4.10 - Route-specific annotations](https://docs.openshift.com/container-platform/4.10/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration)

### What needs fixing?

The documentation for the specific releases mentioned reference that currently "The default value is leastconn.", however, since 4.8 for edge and re-encrypt routes the default is actually random, as `ROUTER_LOAD_BALANCE_ALGORITHM=random` has been defined to the router deployment by default. The documentation should thus be: "The default value is random for edge and re-encrypt.". See: https://github.com/openshift/router/blob/release-4.8/images/router/haproxy/conf/haproxy-config.template#L477

The default value for pass-through routes should also be defined and the two different defaults should be distinguishable. It currently looks to be  'ROUTER_TCP_BALANCE_SCHEME=source'. https://github.com/openshift/router/blob/release-4.8/images/router/haproxy/conf/haproxy-config.template#L664

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.10, 4.9, 4.8

Issue: closes #54713

Link to docs preview: http://file.rdu.redhat.com/jdohmann/GH-54713/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@melvinjoseph86 PTAL for QE ack. This PR updates the table description for `haproxy.router.openshift.io/balance` with the default value `random` instead of `leastconn`

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
