### PR TITLE
GH#50902: Small fix to LocalVolumeSet sample

### LINKED ISSUE #50902: [enterprise-4.11] Issue in file storage/persistent_storage/persistent-storage-local.adoc
### Which section(s) is the issue in?

_Automating discovery and provisioning for local storage devices_.

### What needs fixing?

There is a yaml sample of a localvolumeset. Under `spec` there is `fstype` should be `fsType` with a capital T.
I think it is present since this section have been created for 4.6.

I noticed it because I based my LocalVolumeSet on the sample of your documentation.

### PR DESCRIPTION
**Pull request by bobfuru**
Fixes https://github.com/openshift/openshift-docs/issues/50902

PR applies to 4.6+

Preview: https://51357--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-local.html#local-storage-discovery_persistent-storage-local

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM

Just like riding a bike @bobfuru :wink:

**Comment by bergerhoffer** [comment]
@lpettyjo Can you help me with a good QE to verify this change?

**Comment by kalexand-rh** [comment]
@duanwei33, will you PTAL or suggest a different reviewer?

**Pull request merged**
