### PR TITLE
Machine health checking - OSDOCS-802

### PR DESCRIPTION
**Pull request by maxwelldb**
For https://jira.coreos.com/browse/OSDOCS-802

Machine health checking GA. 4.3+.

### CODE REVIEW

**Comment by maxwelldb** [comment]
Build w/preview materials removed: http://file.rdu.redhat.com/mbridges/111219/machine-health-osdocs-802/machine_management/deploying-machine-health-checks.html

**Comment by maxwelldb** [comment]
@enxebre @bison @spangenberg Hi! With this feature moving from preview to GA, I'd like to get the preview docs into shape. Would you be able to look at the preview in https://github.com/openshift/openshift-docs/pull/18060#issuecomment-552970069 and let me know about how close that is to covering GA doc needs for this feature?

**Comment by enxebre** [comment]
Thanks @maxwelldb 
The CRD spec needs to be updated. You can see more details here https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/machine-health-checking.md.
I'd say something in the line of "Enable automated health checking and remediation of unhealthy nodes backed by machines"

**Comment by maxwelldb** [comment]
@enxebre Are you referring to any particular part of the page, or do you just want to make sure that sentiment is included in a general sense?

**Comment by maxwelldb** [comment]
New preview: http://file.rdu.redhat.com/mbridges/111919/machine-health-osdocs-802/machine_management/deploying-machine-health-checks.html

@enxebre Is that sample more in line with what you were thinking?

**Comment by codyhoag** [comment]
@enxebre I'll be helping to bring this PR to the finish line since Max is on paternal leave.

Can you verify Max's latest edits and let me know if anything else is required?

**Comment by codyhoag** [comment]
@enxebre @bison @spangenberg can you review Max's latest iteration of the Machine Health Checking docs for 4.3? Thanks!

http://file.rdu.redhat.com/mbridges/111919/machine-health-osdocs-802/machine_management/deploying-machine-health-checks.html

**Comment by enxebre** [comment]
>To limit disruptive impact of the machine deletion, the controller drains and deletes only one node at a time.

Can we also elaborate the `maxUnhealthy` behaviour. E.g "When the number of unhealthy machines is above the maxUnhealthy threshold for a targeted pool of machines remediation is short-circuited so manual intervention can take place.

**Comment by enxebre** [comment]
in the yaml, can we use a more realistic example for the lables? these are some labels the machineSet created by the installer have by default
```
machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: clusterName-wd4n9-worker-us-east-1a
```

**Comment by codyhoag** [comment]
@enxebre thanks for the feedback! I applied your suggestions in 3fbaa75fb1b25c848cabf39dfaa3ace294075dbd. Can you confirm these changes? I'll move to QE review if this looks good.

**Comment by enxebre** [comment]
Hey @codyhoag These labels https://github.com/openshift/openshift-docs/commit/3fbaa75fb1b25c848cabf39dfaa3ace294075dbd#diff-7b7763a282f6e3d8bf58ea62e2f76d3bR34 should be at `selector.matchLabels:`

The label value clusterName-wd4n9 was just an example we probably want to follow similar token's format as in https://docs.openshift.com/container-platform/4.2/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-yaml-aws_creating-machineset-aws

I'm confused that commit is not part of the PR.

**Comment by codyhoag** [comment]
Superseded by #18578

**Pull request closed without merging**
