### PR TITLE
Fix wrong case in BuildDefaults example

### PR DESCRIPTION
**Pull request by csrwng**
Example has the wrong case for the gitHTTPSProxy setting.

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees @adellape ptal

**Comment by bparees** [comment]
lgtm

**Comment by adellape** [comment]
:+1: 

Depends on https://github.com/openshift/openshift-docs/pull/1563.

No revhistory needed.

**Comment by bfallonf** [comment]
@adellape #1766 has merged. Can the followup label be removed here?

**Comment by adellape** [comment]
@bfallonf Aw yea

**Pull request merged**
