### PR TITLE
OADP 1178 - featureFlags

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/pull/57763

Preview: [Enabling CSI in the DataProtectionApplication CR](https://59062--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#oadp-enabling-csi-dpa_installing-oadp-aws)

Current version: [Enabling CSI in the DataProtectionApplication CR](https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#oadp-enabling-csi-dpa_installing-oadp-aws)

### CODE REVIEW

**Comment by mburke5678** [comment]
@CarmiWisemon @kaovilai Is this what need to be done in order to fix https://issues.redhat.com/browse/OADP-1178?

**Comment by kaovilai** [comment]
I didn't remember this line not existing.. anyhow yes this looks right now

**Comment by mburke5678** [comment]
@kaovilai The parameter was [removed in this PR](https://github.com/openshift/openshift-docs/pull/54138) because _[featureFlags: EnableCSI is not required anymore. Remove this flag from downstream docs](https://issues.redhat.com/browse/OADP-1059). _

**Comment by kaovilai** [comment]
I see. Well it's optional because we do it for you behind the scenes.. I'll need others input on this

Do we just leave this off docs?
/cc @shubham-pampattiwar

**Comment by shubham-pampattiwar** [comment]
@kaovilai yeah if we add the flag once the `csi` plugin is specified then we should be good to just leave this.

**Comment by kaovilai** [comment]
ok then please close OADP 1178 as fixed by https://issues.redhat.com/browse/OADP-1059

**Pull request closed without merging**
