### PR TITLE
Improving etcd backup procedure for consistency

### PR DESCRIPTION
**Pull request by jruariveiro**
Added missing cp file from v2 schema procedure as well as doing some fixes for consistency between v2 and v3 procedure.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@geliu2016 can you provide QE review for this?

@kalexand-rh

**Review by kalexand-rh — COMMENTED** [review]
@jruariveiro, I have two small requests, if you're willing to make them, otherwise this change LGTM.

**Comment by jruariveiro** [comment]
@kalexand-rh It has been corrected, please let me know if this is OK now :)

**Comment by kalexand-rh** [comment]
@jruariveiro, that looks good to me! The next step is for @geliu2016 to take a look, then you can squash, and I can merge.

**Comment by geliu2016** [comment]
@kalexand-rh LGTM, thx

**Comment by kalexand-rh** [comment]
Thanks! @jruariveiro, will you please squash your commits so I can merge the change?

**Comment by kalexand-rh** [comment]
I've squashed the commits on https://github.com/openshift/openshift-docs/pull/11739 and will merge that PR. Thanks!

**Pull request closed without merging**
