### PR TITLE
BZ-1697257: Updating the location to write the snapshot to

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: http://file.rdu.redhat.com/~ahoffer/2019/BZ-1697257/day_two_guide/environment_backup.html#etcd-data-backup_environment-backup

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1697257

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@hexfusion Can you review this please?

**Comment by hexfusion** [comment]
I think this is reasonable, thanks!

/lgtm

**Comment by geliu2016** [comment]
LGTM,thx

**Pull request merged**
