### PR TITLE
OCPBUGS-15760 Issue in table describing Supported Compliance Profiles

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-14760

Link to docs preview: https://61977--docspreview.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-supported-profiles.html

QE review: QE not needed, this is addition of one version number to clarify two cells in the table.

Additional information:

### CODE REVIEW

**Comment by stevsmit** [comment]
LGTM

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Comment by GroceryBoyJr** [comment]
Merge-reviewer: I need this for 4.10+. Originally thought it was for 4.13+ but SME corrected me.

**Pull request merged**
