### PR TITLE
RHV version support update for OCP 4.6+

### LINKED ISSUE #24735: [enterprise-4.6] Issue in file installing/installing_rhv/installing-rhv-default.adoc
### Which section(s) is the issue in?

> The RHV version is 4.3.10 or later.

### What needs fixing?
We are not supporting OCP 4.6 and later on RHV 4.3, we need to update this install requirement ASAP.

should be:
The RHV version is 4.4.1 or later.

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #24735

### CODE REVIEW

**Comment by codyhoag** [comment]
@peterclauterbach can you confirm?

**Comment by Klaas-** [comment]
I think the right version is 4.4.2, see https://bugzilla.redhat.com/show_bug.cgi?id=1863615 , https://bugzilla.redhat.com/show_bug.cgi?id=1848922 - I am not an openshift customer, so I have just verified it with okd 4.5 https://github.com/openshift/openshift-docs/pull/25399

**Comment by peterclauterbach** [comment]
Yes, RHV 4.4.2 will be the minimum version required for OCP 4.6 via RHV IPI

**Comment by codyhoag** [comment]
Updated to 4.4.2. :+1: 

Since this is a trivial update that has been confirmed by SME, I'm merging now.

**Pull request merged**
