### PR TITLE
adding gluster dyn provisioning example

### PR DESCRIPTION
**Pull request by screeley44**
this example is based on CNS/gluster-kubernetes and is a basic helloworld example.

@adellape PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Thanks! Is this for 3.4?

**Comment by screeley44** [comment]
yeah, this is specific to 3.4, I will need to update for 3.5 as the params for the storageclass and some other details will have changed

**Comment by ahardin-rh** [comment]
@screeley44 Thanks! I will give this a review and follow-up as necessary.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/storage_examples/gluster_dynamic_example.adoc#install-config-storage-examples-gluster-dynamic-example[Persistent Storage Examples -> Complete Example of Dynamic Provisioning Using GlusterFS]
|New topic providing an end-to-end example of how to dynamically provision GlusterFS volumes.
%

**Pull request merged**
