### PR TITLE
Corrected the navbar error

### PR DESCRIPTION
**Pull request by rakshitsharma0402**
Version(s): 4.13+

Issue: #64749

Link to docs preview: [Rolling back to the OpenShift SDN network plugin](https://docs.openshift.com/container-platform/4.13/networking/openshift_sdn/rollback-to-ovn-kubernetes.html)

Edited docs preview: [Rolling back to the OVN-Kubernetes network plugin](https://65149--docspreview.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/rollback-to-ovn-kubernetes)

QE review:
- [ ] QE has approved this change.

Additional information: Corrected the title in the nav bar from Rolling back to the OpenShift SDN network plugin --> Rolling back to the OVN-Kubernetes network plugin

### CODE REVIEW

**Comment by RakshitKumar04** [comment]
Hey, @ShaunaDiaz please review my PR.

**Comment by RakshitKumar04** [comment]
Hey, @bergerhoffer please review my PR.

**Comment by AryanSharma9917** [comment]
LGTM!

**Comment by ShaunaDiaz** [comment]
@RakshitKumar04 I can review this, but I don't think it will count toward Hacktoberfest. If that is what you want, you may wish to close this one and open a new PR Oct. 1.

**Comment by RakshitKumar04** [comment]
Hey, @ShaunaDiaz I would like to get it reviewed and merged before Hacktoberfest.

**Comment by ShaunaDiaz** [comment]
@RakshitKumar04 LGTM!

**Review by ShaunaDiaz — APPROVED** [review]
/lgtm

**Pull request merged**
