### PR TITLE
bug 1712268 removing CSR approval from vSphere

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1712268

http://file.rdu.redhat.com/kalexand/052119/BZ1712268/installing/installing_vsphere/installing-vsphere.html#installation-installing-bare-metal_installing-vsphere

@jiajliu, I've removed the section and posted a rendered copy. PTAL?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@wking says that this change should apply to all of the UPI docs.

**Comment by kalexand-rh** [comment]
@abhinavdahiya  said to not remove the steps to approve the CSRs. The user should always check to see if there are CSRs and approve them if they aren't already approved. I've updated the steps accordingly.

**Comment by jiajliu** [comment]
@kalexand-rh LGTM

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Pull request merged**
