### PR TITLE
BZ#1595094 - added warning about overriding openshift_hostname variable

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1595094

Preview: http://bug1595094-fixes--gnelson-preview.netlify.com/openshift-enterprise/(head%20detached%20at%20fetch_head)/install_config/configuring_vsphere.html#vsphere-enabling

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@tanaka-takayoshi Please take a look

**Comment by tanaka-takayoshi** [comment]
Could you delete the sentence "* Deploy EC2 hosts in a VPC and enable both DNS host names and DNS name resolution."? This is specific to AWS and no need for vSphere.

**Comment by gaurav-nelson** [comment]
Thanks @tanaka-takayoshi I have removed the EC2 note.

**Comment by dav1x** [comment]
I think the text is better defined as such:

+The `openshift_hostname` variable should match the VM name and hostname of the virtual +machine. The value of the `nodeName` is determined via uname -n. If value of the
+`openshift_hostname` variable is set to something other than the
+metadata-provided `private-dns-name` value, the native cloud integration for
+those providers will not work.

**Comment by gaurav-nelson** [comment]
Thanks @dak1n1 

Would the following make sense?

1. The `openshift_hostname` variable must match the virtual machine name and its host name. The `openshift_hostname` defines the `nodeName`
in the *_node-config.yaml_* file. This value is compared to the `nodeName`
determined through `uname -n`. If there is a mismatch, the
native cloud integration for those providers will not work.

Other wise I am happy with:

2. The `openshift_hostname` variable must match the virtual machine name and its host name. The `openshift_hostname` defines the `nodeName`
in the *_node-config.yaml_* file. This value is compared to the `nodeName`
determined through `uname -n`. If value of the `openshift_hostname` variable is
set to something other than the metadata-provided `private-dns-name` value, the
native cloud integration for those providers will not work.


Please let me know which should we use 1 or 2 ?

**Comment by dak1n1** [comment]
@gaurav-nelson I think you meant to highlight @dav1x instead of me :)

But just in case you want my opinion, as a person who deploys OpenShift clusters, I found option 1 to be more clear, because offhand it wasn't clear to me where I would find the "metadata-provided private-dns-name".

Though, I did think about it, and realized that value comes from the cloud provider. It can either be fetched as an API query, or in the web console of my cloud provider.

**Comment by gaurav-nelson** [comment]
Thank you @dak1n1 for your insight, I was too quick to hit enter 😅 
@dav1x vouched for option 1 as well. I will go ahead and make changes.

**Comment by gaurav-nelson** [comment]
@dav1x @gnufied Can you please look at https://bugzilla.redhat.com/show_bug.cgi?id=1595094#c6 and provide some more input around this? OR point me to someone who can? Thanks.

**Comment by dav1x** [comment]
@gaurav-nelson I updated the bz. Thanks for pointing me in its direction.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - we have (yet to be merged) PR from @adellape about removing openshift hostname. I am guessing it is to be removed for 3.10. https://github.com/openshift/openshift-docs/pull/9744

**Comment by gaurav-nelson** [comment]
Thanks @vikram-redhat I have removed the 3.10 label.

**Comment by gaurav-nelson** [comment]
@tanaka-takayoshi Can you please check https://bugzilla.redhat.com/show_bug.cgi?id=1595094#c9 and https://bugzilla.redhat.com/show_bug.cgi?id=1595094#c10 and respond in the bug itself. 
Thank you.

**Comment by tanaka-takayoshi** [comment]
@gaurav-nelson I updated the BZ. Regarding this fix, it looks good for me.

**Pull request merged**
