### PR TITLE
Fix labelSelector syntax for PodAfinity docs - examples

### PR DESCRIPTION
**Pull request by StevenBarre**
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lyman9966, will you PTAL and confirm which versions this change is valid for?

**Comment by vikram-redhat** [comment]
@lyman9966 bump

@xltian ^

**Comment by lyman9966** [comment]
@zhouying7780 Can you help to confirm this?  
According to 4.4 doc, I see it's `- labelSelector`. FYI:https://docs.openshift.com/container-platform/4.4/nodes/scheduling/nodes-scheduler-pod-affinity.html#nodes-scheduler-pod-affinity-about_nodes-scheduler-pod-affinity

**Comment by lyman9966** [comment]
have tested, - labelSelector is correct.

**Comment by kalexand-rh** [comment]
Since `- labelSelector` is correct, I'm closing this PR. Thanks @sbarre-esit.

**Pull request closed without merging**
