### PR TITLE
Clarifying that the certs mentioned are the control plane certs

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Hi @geliu2016 Can you please take a look at this clarification? Thanks!

**Comment by geliu2016** [comment]
LGTM, thanks

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
Note that the 4.2 and 4.3 updates for this will be handled by: https://github.com/openshift/openshift-docs/pull/21408

**Pull request merged**
