### PR TITLE
RHDEVDOCS-6153:Correct formating for build docs

### PR DESCRIPTION
**Pull request by likhithj1996**
Version(s):
 builds-docs-1.1 and builds-docs-1.0.

Issue:
https://issues.redhat.com/browse/RHDEVDOCS-6153

Link to docs preview:
[Overview of Builds](https://85955--ocpdocs-pr.netlify.app/openshift-builds/latest/about/overview-openshift-builds.html)
[Release Notes](https://85955--ocpdocs-pr.netlify.app/openshift-builds/latest/release_notes/ob-release-notes.html)
QE review:
- [x] QE has approved this change.

QE Review:
SME Review:
Peer Review:
Internal Peer review: @Dhruv-Soni11 

Additional information:

### CODE REVIEW

**Review by avinal — APPROVED** [review]
/lgtm

**Review by avinal — COMMENTED** [review]
Based on the JIRA the changes looks good.  should Source-to-image be in backticks too?

**Comment by likhithj1996** [comment]
> Based on the JIRA the changes looks good. should Source-to-image be in backticks too?

@avinal Will be in covered in next JIRA ticket

**Review by xenolinux — COMMENTED** [review]
peer review LGTM

**Comment by xenolinux** [comment]
@likhithj1996 FYI- for the future peer and merge reviews, consider adding the `merge-review-needed` label after the `peer-review-done` label is added by the peer reviewer.

**Review by xenolinux — COMMENTED** [review]
LGTM Merging

**Comment by likhithj1996** [comment]
> @likhithj1996 FYI- for the future peer and merge reviews, consider adding the `merge-review-needed` label after the `peer-review-done` label is added by the peer reviewer. 

Understand and I will do it for the next time.

**Pull request merged**
