### PR TITLE
Erroneous sample output includes 'run-level 0' for a non control plane component

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1953936

https://deploy-preview-32347--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-project_nodes-scheduler-node-selectors

### CODE REVIEW

**Comment by mburke5678** [comment]
@dbaker-rh PTAL

**Comment by mburke5678** [comment]
@sunilcio A small review, if you would. I updated the output of the `oc edit project` command. I created a new project in 4.8 and used the output from that.

**Comment by sunilcio** [comment]
@mburke5678 thanks, LGTM!

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
