### PR TITLE
BZ2017421: Adding more info about the IPv6 address and gateway IP

### PR DESCRIPTION
**Pull request by sjhala-ccs**
https://bugzilla.redhat.com/show_bug.cgi?id=2017421

Updated the “Configuring masquerade mode with dual stack” module to include information about how to configure the VM IPv6 address and gateway IP.

Applies to 4.9, 4.10, 4.11

Preview: https://deploy-preview-44548--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.html#virt-configuring-masquerade-mode-dual-stack_virt-using-the-default-pod-network-with-virt

### CODE REVIEW

**Review by maiqueb — CHANGES_REQUESTED** [review]
I think this is actually worse off now; this is somewhat tricky to explain ... I'll try to, using an example: the `Network.pod.vmIPv6NetworkCIDR` can be passed an ipv6 - let's say `2002:1234`. 

If that is the chosen CIDR, the VM's static IP address **must be** `2002:1234::2` , while the configured gateway **must be** `2002:1234::1`. 

I.e. the gateway and VM addresses will be computed from the provisioned CIDR. 

Does it make sense ?

**Comment by sjhala-ccs** [comment]
@maiqueb Please let me know if the following text is a more accurate interpretation:

> The `Network.pod.vmIPv6NetworkCIDR` attribute in the virtual machine instance configuration determines the static IPv6  address of the VM and the gateway IP address. These are used by the virt-launcher pod to route IPv6 traffic to the virtual machine and are not used externally. The `Network.pod.vmIPv6NetworkCIDR` parameter specifies an IPv6 address block in  Classless Inter-Domain Routing (CIDR) notation. The default value is `fd10:0:2::2/120`. You can edit this value based on your  network requirements.

**Comment by maiqueb** [comment]
> @maiqueb Please let me know if the following text is a more accurate interpretation:
> 
> > The `Network.pod.vmIPv6NetworkCIDR` attribute in the virtual machine instance configuration determines the static IPv6  address of the VM and the gateway IP address. These are used by the virt-launcher pod to route IPv6 traffic to the virtual machine and are not used externally. The `Network.pod.vmIPv6NetworkCIDR` parameter specifies an IPv6 address block in  Classless Inter-Domain Routing (CIDR) notation. The default value is `fd10:0:2::2/120`. You can edit this value based on your  network requirements.

@sjhala-ccs it is indeed.

**Review by maiqueb — APPROVED** [review]
/lgtm

Thanks.

**Comment by lmandavi** [comment]
@sjhala-ccs LGTM.

**Comment by RedHatter007** [comment]
LGTM

**Pull request merged**
