### PR TITLE
BZ#1852105 No longer a short char limit for GCP cluster name

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1852105

Preview: https://deploy-preview-31213--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-initializing_installing-gcp-user-infra

### CODE REVIEW

**Comment by codyhoag** [comment]
@tsze-redhat PTAL

**Comment by tsze-redhat** [comment]
LGTM
Thanks.

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
