### PR TITLE
OSDOCS-2231: RN for hardware offloading

### PR DESCRIPTION
**Pull request by ctauchen**
Release note for hardware offloading
See also https://github.com/openshift/openshift-docs/pull/41762

**NOTE**: The build will continue to break until the feature docs are merged and the cross reference in the RN can resolve.

Applies only to `enterprise-4.10`

Preview: https://deploy-preview-42128--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes#ocp-4-10-hardware-offloading

### CODE REVIEW

**Comment by ctauchen** [comment]
@zshi-redhat @mcurry-rh

**Comment by zshi-redhat** [comment]
@ctauchen nit: since this is the first hardware offload feature introduced in openshift networking, I'm not sure if we shall have the generic name `Hardware offload` in the summary or be specific to use `OVS Hardware Offload`. wdyt?

**Comment by ctauchen** [comment]
> 

You're absolutely right. Changed here and in the feature documentation. Thanks!

**Comment by mjpytlak** [comment]
@ctauchen Outside of the broken link causing the build to fail, peer review LGTM.

**Pull request merged**
