### PR TITLE
CNV-45177: Remove ambiguity from a release note

### PR DESCRIPTION
**Pull request by jhradilek**
Version(s): 4.16

Issue: [CNV-45177](https://issues.redhat.com/browse/CNV-45177)

Link to docs preview:
* https://85112--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-16-release-notes.html#virt-4-16-web_virt-4-16-release-notes

QE review:
- [ ] QE has approved this change.

Additional information:
The original phrasing of the release note could have been misleading as it did not specify what is being hot-plugged where. This fix removes this ambiguity.

### CODE REVIEW

**Review by vsibirsk — APPROVED** [review]

**Review by aspauldi — COMMENTED** [review]
LGTM! Thanks.

**Comment by jhradilek** [comment]
Thank you, @aspauldi.

/label merge-review-needed

**Review by bergerhoffer — COMMENTED** [review]
LGTM to merge!

**Pull request merged**
