### PR TITLE
Add documentation for the new router option to select between host and container network stacks

### PR DESCRIPTION
**Pull request by ramr**
@adellape  @bfallonf   PTAL  Thx
FYI, this needs to wait for https://github.com/openshift/origin/pull/4026 to be merged.   

/cc @pweil-

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr Neat. The only major thing that I'd like to question, is: would this be better as a Note or important box? So instead of saying *Special Note About Using The Container Network Stack*, would it be better as:

[NOTE]
====
words
====

This also might apply to the *Special Note About Secured Routes* para above it.

**Comment by ramr** [comment]
@bfallonf  - that does sound better. Will do. 
Meanwhile since I have you here, have a question for you - if we need to add something for upgrading to the new behavior (you do need to re-add or edit the router deployment config to achieve that), where do we document this? @smarterclayton  had a comment in https://github.com/openshift/origin/pull/4026  -- does that go into a new file (ala ```upgrade.md```) or release notes or somewhere else? Thx

**Comment by bfallonf** [comment]
@ramr Hmm if I understand you correctly, here may be the best topic in the docs:

https://github.com/openshift/openshift-docs/blob/master/admin_guide/upgrades.adoc

Though I think you may be talking about a specific version. Say, the reader will need to perform the specific procedure to upgrade the router deployment. That may be a better job for the release notes, or even the router section. 

If you'd like, you can send me an email with the specific procedure and I can see where it'd fit the best myself.

**Comment by ramr** [comment]
@bfallonf - k I'll send you an email with the specifics (and will paste them in here as well).  Thx

**Comment by adellape** [comment]
@bfallonf @ramr We have an "Additional Instructions per Release" section the Admin Guide "Upgrading" topic:

https://docs.openshift.com/enterprise/3.0/admin_guide/upgrades.html#additional-instructions-per-release

Currently it only has a subsection for OSE 3.0.1.0, but we'll start one for OSE 3.0.2.0 as soon as we have anything (sounds like this is the first). So (unless we change up how we present these upgrade docs), whatever the steps are for modifying the router dc for 3.0.2.0 can go there.

Also notice up in the standard "Upgrading the Router" section of that topic, to make sure no one missed it for 3.0.1.0 we also added a NOTE box, calling out that there was a specific step to be performed at that point for 3.0.1.0:

https://docs.openshift.com/enterprise/3.0/admin_guide/upgrades.html#upgrading-the-router

And provided a link down to the specific steps. We could do the same for 3.0.2.0 in the appropriate spot.

**Comment by adellape** [comment]
Adding [do not merge] until the origin PR merges.

**Comment by ramr** [comment]
@adellape thx for the info. Cool, will add some info to those 2 sections.

**Comment by ramr** [comment]
@adellape @bfallonf  added the upgrade instructions - LMK if that is okay + this PR is now ready to be merged as the origin PR https://github.com/openshift/origin/pull/4026 got merged. Thx

**Comment by adellape** [comment]
@ramr @bfallonf Pulled this into https://github.com/openshift/openshift-docs/pull/877, PTAL there.

**Comment by ramr** [comment]
closing this out as #877  has all this info.

**Pull request closed without merging**
