### PR TITLE
TELCODOCS-286: BIOS update for SR-IOV prereqs

### PR DESCRIPTION
**Pull request by aireilly**
Updates for https://issues.redhat.com/browse/TELCODOCS-286

Small update based on discussion with @SchSeba and @kquinn1204. Kevin is on holidays so making this change for him. @SchSeba can you OK this and I'll get it merged.

### CODE REVIEW

**Review by SchSeba — COMMENTED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
Looks great! Just want to confirm, is this intended for 4.7 only and should not persist for 4.8? I see it's submitted against 4.7, but want to be sure that's intentional.

**Comment by aireilly** [comment]
> Looks great! Just want to confirm, is this intended for 4.7 only and should not persist for 4.8? I see it's submitted against 4.7, but want to be sure that's intentional.

yes. This is enterprise-4.7 only.

**Comment by SchSeba** [comment]
Hi @ahardin-rh the 4.8 documentation is still not in place as intel didn't declare support for the sriov-fec operator yet.

@aireilly can you please open one also for the 4.6 docs?

**Comment by aireilly** [comment]
@kquinn1204 FYI

**Pull request merged**
