### PR TITLE
Document GitOps 1.6.6 RN for OCP 4.9

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
**Aligned team**: Dev Tools

**Purpose**: To resolve the following issue:
[RHDEVDOCS-5088](https://issues.redhat.com/browse/RHDEVDOCS-5088): GitOps 1.6.6 release notes

**OCP version this PR applies to**: enterprise-`4.9`

**Link to docs preview**: 
- [Release notes for Red Hat OpenShift GitOps 1.6.6]()

**SME review**:  Completed by  @reginapizza 
**QE review**:  Completed by @varshab1210
**Peer-review**:  Completed by @themr0c

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@iam-veeramalla @harrietgrace @wtam2018 @RickJWagner @varshab1210 @pmkovar @Preeticp: Could you please help with the review of this PR and share your feedback? Thanks!

**Comment by varshab1210** [comment]
LGTM, thanks

**Comment by Srivaralakshmi** [comment]
**Quick update:** As per the discussion with the OpenShift DPM and CS, no change management process is required.

**Review by reginaelyse — APPROVED** [review]
LGTM

**Review by themr0c — APPROVED** [review]

**Pull request merged**
