### PR TITLE
[OSDOCS-6831]: Minor update to etcd recovery docs for hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14

Issue: https://issues.redhat.com/browse/OSDOCS-6831

Link to docs preview: https://64590--docspreview.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-backup-restore-dr#hosted-cluster-etcd-status_hcp-backup-restore-dr

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lahinson** [comment]
@csrwng When you can, PTAL at this small update to the etcd recovery docs. Thanks!

**Comment by csrwng** [comment]
thx!
/lgtm

**Comment by bburt-rh** [comment]
lgtm. Thanks!

**Review by skrthomas — APPROVED** [review]
/lgtm

**Pull request merged**
