### PR TITLE
CNV-23531: svg to png 4.11

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.11

Issue: [CNV-23531](https://issues.redhat.com//browse/CNV-23531)

Link to docs preview: https://54510--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-11-release-notes.html

QE review: NO QE NEEDED
- [ ] QE has approved this change. 

Additional Information: Switching SVG to PNG due to SVG rendering incorrectly on customer portal.

### CODE REVIEW

**Comment by tmalove** [comment]
@sabrinajess Although the update is changing the file type, will you include a direct preview link to this section, so the rendering can be verified. Thanks!

**Comment by sabrinajess** [comment]
@tmalove Preview added :)

**Comment by tmalove** [comment]
Thanks @sabrinajess !

/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Pull request merged**
