### PR TITLE
added more info to horizontal autoscaler docs

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://trello.com/c/7vxgSTxF/365-document-custom-metrics-extensible-metric-driven-hpa

@DirectXMan12 I'll tag you in trello, but I'm thinking that all that needs to be added to this card is objects into the table, then some rewriting to get away from the "only CPU utilization" phrase. Let me know if you disagree.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Yeah, this is a bit tricky, because anything beyond CPU utilization requires using something that's alpha in some capacity (even memory -- either autoscaling/v2alpha1 or the corresponding alpha annotations), so I'm not sure how we want to document that.

**Comment by bfallonf** [comment]
@DirectXMan12 We can attach a Technology Preview box to it. We've done this in other topics:

https://docs.openshift.com/container-platform/3.5/admin_guide/managing_networking.html#admin-guide-networking-multicast

Can just say something like what you mention "anything other than CPU utilization is in technology preview". What other objects can be added though? I can add that to the table I've added to here and see how it looks if we like.

**Comment by DirectXMan12** [comment]
did you take a look at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ and https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ ?  They describe how the new objects work.  The problem is that we don't have the adapter for non-resource-metrics, but that's how the HPA is structured.

**Comment by bfallonf** [comment]
@DirectXMan12 Thanks for the links. I can see how it works, but not too sure what other objects to that table (where, so far, I've added memory). Let me know if you have any hints.

But also, from what you're saying above, should this be documented just yet? Should this be put aside until you've worked on the adapter? Or is that for this current sprint?

**Comment by DirectXMan12** [comment]
> But also, from what you're saying above, should this be documented just yet? But also, from what you're saying above, should this be documented just yet?

Yeah, I'm not entirely certain when that work will be ready to be documented.  We might want to put it aside for the moment (plus, we haven't actually enabled a switch to make the HPA controller call out to the custom metrics APIs yet).

**Review by DirectXMan12 — CHANGES_REQUESTED** [review]
The example in the memory section uses CPU, so that needs to be fixed.  Additionally, we've disabled the HPA v2 API by default, so users will have to opt-in to use it in order to get memory-based autoscaling.

**Comment by DirectXMan12** [comment]
the API should be enablable using the `runtime-config` option under `apiServerArguments`:

```
...
apiServerArguments:
  runtime-config:
  - apis/autoscaling/v2alpha1=true
```

**Comment by bfallonf** [comment]
Thanks @DirectXMan12 . I'm not sure what you're after exactly. Which file is this being added to? And I replaced the "cpu" bits in the procedure with "memory" but should the "--cpu-percent=80" option for the command change as well?

**Comment by DirectXMan12** [comment]
> Thanks @DirectXMan12 . I'm not sure what you're after exactly. Which file is this being added to?

It's a config option in master-config.yaml.

> but should the "--cpu-percent=80" option for the command change as well?

You can't create the autoscaler through a command if you want to do just memory autoscaling.  You have to `kubectl create -f` it.

**Comment by bfallonf** [comment]
Closing this PR in favour of #4817

**Pull request closed without merging**
