### PR TITLE
CNV-45636: WASP documentation fix

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-45636

CNV 4.16+
OCP 4.16+

Preview: https://79985--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-configuring-higher-vm-workload-density.html

### CODE REVIEW

**Comment by Barakmor1** [comment]
LGTM

**Review by enp0s3 — APPROVED** [review]
/lgtm

**Comment by sbeskin-redhat** [comment]
@enp0s3 @Barakmor1 
The link in line 114 does not work. Maybe it shouldn't work without authorization? In that case, we should remove it.

**Comment by enp0s3** [comment]
@sbeskin-redhat Hi, the link provided is intended for pulling images from container registry, therefore you won't be ablr to validate the link with a browser, but with a dedicated tool such as `docker`, `podman` or `skopeo`.
I already tested the image pull URL and it indeed works.

**Comment by sbeskin-redhat** [comment]
@Barakmor1 @enp0s3  I've removed 2-b and slightly modified step 2. Please check.

**Review by adellape — APPROVED** [review]

**Pull request merged**
