### PR TITLE
OSSMDOC-589: Distributed tracing 2.6 Release Notes.

### PR DESCRIPTION
**Pull request by JStickler**
Version(s): 4.9 - 4.12

Issue: [OSSMDOC-589](https://issues.redhat.com/browse/OSSMDOC-589)

Link to docs preview: http://file.bos.redhat.com/jstickle/OSSMDOC-589/distr_tracing/distributed-tracing-release-notes.html#new-features-and-enhancements-red-hat-openshift-distributed-tracing-2-6

QE review: jkandasa
Peer Review:

### CODE REVIEW

**Comment by jkandasa** [comment]
@JStickler I will check the component version details and approve.

**Review by jkandasa — APPROVED** [review]
@JStickler LGTM!
```
$ oc get csv
NAME                               DISPLAY                                                 VERSION    REPLACES                           PHASE
jaeger-operator.v1.38.0-2          Red Hat OpenShift distributed tracing platform          1.38.0-2   jaeger-operator.v1.36.0-2          Succeeded
opentelemetry-operator.v0.60.0-2   Red Hat OpenShift distributed tracing data collection   0.60.0-2   opentelemetry-operator.v0.56.0-1   Succeeded
```

**Review by GroceryBoyJr — COMMENTED** [review]
/label LGTM

**Comment by GroceryBoyJr** [comment]
@JStickler I gave LGTM but ask you, please, to double-check the OpenShift versions needed with the developers: do the new updates belong with 4.6 and 4.7? (I cannot tell, myself). If these don't go into the earlier OpenShift release notes, you may be spared cherrypick problems.

**Comment by JStickler** [comment]
Rebased today.

**Pull request merged**
