### PR TITLE
OCPBUGS#22828: Fixup source block formatting

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.12+

Issue: OCPBUGS-22828

Link to docs preview: https://80925--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-tutorial.html#osdk-create-project_osdk-java-tutorial (step 3)

~QE review:~
~- [ ] QE has approved this change.~
Fixes formatting. No QE required.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@dfitzmau I just realized I forgot the preview link :facepalm:

**Comment by dfitzmau** [comment]
Please add the Jira link and preview link to the Description section.

**Review by dfitzmau — APPROVED** [review]

**Comment by michaelryanpeter** [comment]
Updated with a preview link. Sorry about that :)

**Comment by dfitzmau** [comment]
> @dfitzmau I just realized I forgot the preview link 🤦

All good. I just added such a comment about it.

**Pull request merged**
