### PR TITLE
OCPBUG29107: Added endif in additional resources.

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.11+

Issue: [OCPBUGS-29107](https://issues.redhat.com/browse/OCPBUGS-29107)
Related to [PR-57464](https://github.com/openshift/openshift-docs/pull/57464)

Link to docs preview:

QE review:
- [n/a] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
LGTM. Thank you!

**Comment by ShaunaDiaz** [comment]
@subhtk Bummer on the CPs! Please make the manual cherry picks for 4.12, 4.13, and 4.14. I can merge for you once completed.
Note: 4.11 is now EOL so you do not have to make a CP for that one.

**Pull request merged**
