### PR TITLE
BZ-1941940: Updated image cache name to use quay.io

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1941940

For: 4.6, 4.8, 4.9, 4.10 
(4.7 is in [PR 41098](https://github.com/openshift/openshift-docs/pull/41098))

Doc Preview: https://deploy-preview-41099--osdocs.netlify.app

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Comment by abhatt-rh** [comment]
LGTM, Katie!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
