### PR TITLE
Updated docs issue RHDEVDOCS-6084

### PR DESCRIPTION
**Pull request by Aarush-Kaswan**
Updated the docs for [RHDEVDOCS-6084](https://issues.redhat.com//browse/RHDEVDOCS-6084)

Cherry pick Version(s): GitOps 1.13 and GitOps 1.12

Issue: https://issues.redhat.com/browse/OEIIITB-17

Link to docs preview:
https://84082--ocpdocs-pr.netlify.app/openshift-gitops/latest/argocd_instance/argo-cd-cr-component-properties.html#notifications-configuration-custom-resource-properties_argo-cd-cr-component-properties

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by Srivaralakshmi — COMMENTED** [review]
@Aarush-Kaswan LGTM

These changes must be cherry-picked to the GitOps 1.13 and GitOps 1.12 branches. Verify the changes in the preview. and update the preview link in the PR description. This information must be added to the PR and visible to the merge reviewer.

**Comment by Srivaralakshmi** [comment]
@Dhruv-Soni11 Please peer review this PR and see that this PR meets all the requirements including the QE reviews (you must tag the QE person in the PR), before it goes to the peer review squad. Thank you!

**Comment by Dhruv-Soni11** [comment]
> @Aarush-Kaswan LGTM
> 
> These changes must be cherry-picked to the GitOps 1.13 and GitOps 1.12 branches. Verify the changes in the preview. and update the preview link in the PR description. This information must be added to the PR and visible to the merge reviewer.

Hi @Srivaralakshmi I don't have permission to update the preview link in the PR description. This change can only be made by @Aarush-Kaswan. Also, I don't have any other piece of feedback for @Aarush-Kaswan as he has made all the changes mentioned in the JIRA description of the ticket.

@Aarush-Kaswan please update the correct GitOps versions in the PR description. Add the details for cherry-picking to the GitOps 1.13 and GitOps 1.12 branch.

Good work on your first PR @Aarush-Kaswan.

**Review by skopacz1 — APPROVED** [review]
Seems like this was already peer reviewed and maybe the labels were misapplied. Either way LGTM

**Comment by varshab1210** [comment]
LGTM, thanks

**Pull request merged**
