### PR TITLE
Add diagrams for determining the CCO mode (4.10)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.10

Issue:
[OSDOCS-5914](https://issues.redhat.com//browse/OSDOCS-5914)

[VPN] Link to docs preview:
- [Cloud credential configuration options and update requirements by platform type](http://file.rdu.redhat.com/~jrouth/GFX334-CCO-mode-diagrams-4.10/updating/preparing-manual-creds-update.html#cco-platform-options_preparing-manual-creds-update)
- [Determining the Cloud Credential Operator mode](http://file.rdu.redhat.com/~jrouth/GFX334-CCO-mode-diagrams-4.10/authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.html#cco-determine-mode_about-cloud-credential-operator)

QE review:
- [ ] QE has approved this change.

Additional information:
4.10 does not include Nutanix

### CODE REVIEW

**Comment by abutcher** [comment]
Looks good to me!

**Comment by jeana-redhat** [comment]
@jianping-shu PTAL at this version too :)

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by jianping-shu** [comment]
LGTM

**Pull request merged**
