### PR TITLE
[OCPBUGS-15195] Apply new naming guidelines for IBM Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.13+

requires CM because name change is applied to RNs too 

Issue: 
https://issues.redhat.com/browse/OCPBUGS-15195

Link to docs preview:
https://61755--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/preparing-to-install-on-ibm-z.html
https://61755--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/preparing-to-install-on-ibm-z-kvm.html

QE review: @holgwolf
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by SNiemann15** [comment]
PTAL: @sferich888, @davemulford, @xltian, @kalexand-rh, @sjstout

**Comment by davemulford** [comment]
LGTM

**Comment by kalexand-rh** [comment]
LGTM

**Comment by mburke5678** [comment]
@SNiemann15 What about 4.12? It is the only branch remaining that shows [IBM zSystems](https://docs.openshift.com/container-platform/4.12/installing/installing_ibm_z/preparing-to-install-on-ibm-z.html)

**Comment by SNiemann15** [comment]
> @SNiemann15 What about 4.12? It is the only branch remaining that shows [IBM zSystems](https://docs.openshift.com/container-platform/4.12/installing/installing_ibm_z/preparing-to-install-on-ibm-z.html)

@mburke5678 Yes let's also cherrypick to 4.12. Thanks for bringing that up. I confirmed with PM.

**Pull request merged**
