### PR TITLE
Add GitHub organization config

### PR DESCRIPTION
**Pull request by liggitt**
Feature added in https://github.com/openshift/origin/pull/7161

### CODE REVIEW

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
**revhistory note** will appear in follow-up PR.

**Comment by liggitt** [comment]
the revhistory refers to noting which version the `organizations` attribute appeared in? if so, +1

**Comment by adellape** [comment]
@liggitt That, yes, but also about just noting what has changed in the docs themselves, specifically the downstream docs (e.g., https://docs.openshift.com/enterprise/latest/welcome/revhistory_full.html).

I should probably send a PSA to the list about our use of revhistory notes in PRs so these comments of ours are less mysterious.

**Pull request merged**
