### PR TITLE
BZ-1952805 oc login is no longer interactive

### PR DESCRIPTION
**Pull request by e-minguez**
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1952805 & https://bugzilla.redhat.com/show_bug.cgi?id=1920427

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@zhouying7780, will you please confirm the change and that it applies to only 4.7+?

**Comment by zhouying7780** [comment]
@kalexand-rh  Yes, this change only apply to 4.7+.

**Comment by kalexand-rh** [comment]
@e-minguez, there are places in the docs that use just `oc login` in procedures. What are the ramifications to those workflows?

**Comment by e-minguez** [comment]
Related to https://github.com/openshift/oc/pull/834

**Comment by kalexand-rh** [comment]
> @e-minguez, there are places in the docs that use just `oc login` in procedures. What are the ramifications to those workflows?

@e-minguez, what do you think?

**Comment by e-minguez** [comment]
> > @e-minguez, there are places in the docs that use just `oc login` in procedures. What are the ramifications to those workflows?
> 
> @e-minguez, what do you think?

Not sure the current status because of https://github.com/openshift/oc/pull/834 @sallyom wdyt? Shall the docs reflect the change or it isn't needed since the latest changes?
Thanks.

**Comment by kalexand-rh** [comment]
> > > @e-minguez, there are places in the docs that use just `oc login` in procedures. What are the ramifications to those workflows?
> > 
> > 
> > @e-minguez, what do you think?
> 
> Not sure the current status because of [openshift/oc#834](https://github.com/openshift/oc/pull/834) @sallyom wdyt? Shall the docs reflect the change or it isn't needed since the latest changes?
> Thanks.

@sallyom, will you PTAL?

**Pull request closed without merging**
