### PR TITLE
OCPBUGS#5852 specify control plane machines for the minimums

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.9+

Issue:
[OCPBUGS-5852](https://issues.redhat.com/browse/OCPBUGS-5852)

Link to docs preview:
[Preview](https://58441--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-azure-limits_installing-azure-user-infra)

QE review:
- [X] QE has approved this change.

Additional information:
Clarification to [this PR. ](https://github.com/openshift/openshift-docs/pull/55263)

### CODE REVIEW

**Comment by cbippley** [comment]
@mgahagan73 PTAL, thank you!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
