### PR TITLE
[WIP] Document on GitOps multi-tenancy support

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
**Aligned team**: Dev Tools

**Please cherry-pick to**: `gitops-docs-1.11`

**JIRA issues**: [RHDEVDOCS-5551](https://issues.redhat.com/browse/RHDEVDOCS-5551)

**Preview pages**: 

1. [Understanding multitenancy support](https://68818--docspreview.netlify.app/openshift-gitops/latest/declarative_clusterconfig/understanding-multitenancy-support)
2. [WARNING - Using an Argo CD instance to manage cluster-scoped resources](https://68818--docspreview.netlify.app/openshift-gitops/latest/declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations#configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)
3. [NOTE - 2nd bullet item in section - In-built permissions for cluster configuration](https://68818--docspreview.netlify.app/openshift-gitops/latest/declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations#gitops-inbuilt-permissions-for-cluster-config_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)
4. [WARNING - Setting up an Argo CD instance](https://68818--docspreview.netlify.app/openshift-gitops/latest/argocd_instance/setting-up-argocd-instance)
5. [Additional resources in section - Configuring an OpenShift cluster by deploying an application with cluster configurations](https://68818--docspreview.netlify.app/openshift-gitops/latest/declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations#additional-resources_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)

**SME Review**:  @harrietgrace, @jannfis, @iam-veeramalla, and @gnunn1

**QE review**: @varshab1210 

**Peer review**: 

**Additional information**: This PR creates a document on GitOps multi-tenancy support for 1.11 GitOps standalone doc, adds related admonitions to the existing  `setting-up-argocd-instance.adoc`, and `gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc` files, and updates a couple of existing assembly files to align with OCP doc guidelines for anchoring the "Additional resources" titles.

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
Hello, @harrietgrace, @jannfis, @gnunn1, and @varshab1210: The PR for multitenancy support is available. PTAL at the PR and help us with the review feedback. TIA : )

**Comment by Srivaralakshmi** [comment]
> There is a lot of technical nuance (cluster scoped versus namespace scoped, custom roles for the applicaton controller, Argo RBAC, AppProjects, etc) that I would like to see covered here but I suspect it might be a lot to include and keep up to date as things change in Argo CD (i.e. Apps in Any Namespace).

@gnunn1 Thank you very much for the response and input. We can cover the technical bits as part of core concepts and terminologies in the coming releases. Currently, I meet with @harrietgrace, @jannfis, and @iam-veeramalla to decide on the content that we plan to put in the Enterprise GitOps documentation for multitenancy support. The plan is to take it step-by-step. This PR is step 1 for this release.

It would be wonderful if you join our next meeting to decide on the content and how we can tackle the maintenance overhead. If timings do not work, then I and @Preeticp can watch the recordings and ask clarifications or doubts Async in the document. @harrietgrace WDYT?

> I'm happy to write up a version of this as I would like to see it but that's likely a 1-2 week endeavor for me and I'm not sure if there is time or if we want to defer this?

@gnunn1 I am eagerly waiting to see more content on this from you. So please go ahead and help us with your input.
About the time, it would be nice if this PR goes out with this release as a start. We can refine it in future releases. But that is just my opinion.

@harrietgrace and @jannfis: Please let us know your thoughts. As discussed in our meeting, this PR addresses the admonitions related to multitenancy permissions in the relevant sections. If you think this PR is in good shape to go with the current content, please provide your approval. If there is any improvements, please suggest. I will incorporate them.

Otherwise, we can work on this PR after we get inputs from @gnunn1. We can also send the content in Word doc and get some feedback from the field before publishing. WDYT? Eagerly awaiting your response.

Many thanks,
Sri

**Comment by aireilly** [comment]
This PR has been repointed to `gitops-docs-main` branch. `gitops-docs` is no longer in use and will be deleted presently. The gitops-docs-main branch uses the OpenShift Prow CI instead of Travis for builds.

**Pull request closed without merging**
