### PR TITLE
added true/false info and context for LabelsPresence [issue 727]

### PR DESCRIPTION
**Pull request by tpoitras**
as per issue 727: https://github.com/openshift/openshift-docs/issues/727

### CODE REVIEW

**Comment by tpoitras** [comment]
@adellape @bfallonf  is this OK to merge now, you reckon?

**Comment by bfallonf** [comment]
@tpoitras You say lines 111-120 are what you added here, and they look good to me.

**Comment by adellape** [comment]
@tpoitras Agree with @bfallonf, just looks like it needs a rebase.

**Comment by tpoitras** [comment]
rebased, @adellape :vhs:

**Comment by adellape** [comment]
@tpoitras :+1:

While I am not super surprised there's no `:betamax:`, I am pleased by the presence of :minidisc:.

**Pull request merged**
