### PR TITLE
corrected spelling of the word process in 3 places.

### LINKED ISSUE #45246: [online] Issue in file operating/manage-vulnerabilities.adoc
### Which section(s) is the issue in?
Vulnerability management proccess

### What needs fixing?
vulnerability management proccess. -

There is a typo in the spelling of <process> in section as well as heading of the section. In all, this spelling is incorrect in three places.
The URL is:

https://docs.openshift.com/acs/3.68/operating/manage-vulnerabilities.html#vulnerability-management-proccess_acs-operating-manage-vulnerabilities

### PR DESCRIPTION
**Pull request by mikesmith0414**
Corrected spelling of the word process in 3 places.

Fixes #45246

Version(s):
3.68+

https://docs.openshift.com/acs/3.68/operating/manage-vulnerabilities.html#vulnerability-management-proccess_acs-operating-manage-vulnerabilities

Preview: http://file.rdu.redhat.com/~ahoffer/2022/pr-50822/operating/manage-vulnerabilities.html#vulnerability-management-process_acs-operating-manage-vulnerabilities

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
@mikesmith0414 Great work! I very much want to get your update merged by the merge squad! Your preview link in comment 0 shows the text before your changes, not afterward. Can I help you with the preview, or can you update your preview?

**Comment by bergerhoffer** [comment]
@GroceryBoyJr Is this peer review still in progress, or does it look good and you're done? If you're done, can you switch the labels to peer-review-done?

As for the preview, since @mikesmith0414 is a contributor outside the normal OCP docs team, I'd say that we can take care of the preview for him. I've uploaded it here (http://file.rdu.redhat.com/~ahoffer/2022/pr-50822/operating/manage-vulnerabilities.html#vulnerability-management-process_acs-operating-manage-vulnerabilities) and have updated comment 0 with it.

**Comment by GroceryBoyJr** [comment]
@bergerhoffer Thank you, I appreciate the help. Labels changed and "merge-review-needed" added just now.

**Comment by bergerhoffer** [comment]
@kcarmichael08 @gaurav-nelson This PR fixes some typos, but also fixes it in the file rename. Just wanted to check that you're okay with that before we merge!

**Comment by kcarmichael08** [comment]
> @kcarmichael08 @gaurav-nelson This PR fixes some typos, but also fixes it in the file rename. Just wanted to check that you're okay with that before we merge!

This is fine! I believe as long as it's not changing the name of an assembly, it doesn't require anything else.

FWIW, 3.68 is out of support, so we generally aren't updating or fixing the docs for that version. (Actually anything before 3.70.) But some customers are on older versions so it's good to fix things if we have the bandwidth.

**Comment by bergerhoffer** [comment]
Thanks @kcarmichael08! Can you tell me which branches to cherry pick this PR to then?

**Comment by kcarmichael08** [comment]
> Thanks @kcarmichael08! Can you tell me which branches to cherry pick this PR to then?

- `rhacs-docs`
- `rhacs-docs-3.72`
- `rhacs-docs-3.71`
- `rhacs-docs-3.70`

That should do it!

**Comment by bergerhoffer** [comment]
Thanks!! Merging

**Pull request merged**
