### PR TITLE
TELCODOCS-1582: Remove incorrect note from removing a managed cluster ZTP docs

### PR DESCRIPTION
**Pull request by aireilly**
Removing a managed cluster site from the GitOps ZTP pipeline topic has a note that goes against GitOps principles. 

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/TELCODOCS-1582

Link to docs preview:
https://71743--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-deploying-far-edge-sites#ztp-site-cleanup_ztp-deploying-far-edge-sites

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Comment by aireilly** [comment]
lgtm from rlopezma@redhat.com in JIRA

**Comment by mpmaruthu** [comment]
Telco RAN QE: Looks good to me.
/Peri M

**Pull request merged**
