### PR TITLE
Followup edits to PR3377

### PR DESCRIPTION
**Pull request by bfallonf**
#3377

@ahardin-rh @bmcelvee @adellape Peer review plz?

### CODE REVIEW

**Comment by bfallonf** [comment]
@ahardin-rh @bmcelvee @adellape bump!

**Comment by ahardin-rh** [comment]
@bfallonf LGTM!

**Comment by bfallonf** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added `*ROUTER_CANONICAL_HOSTNAME*` to the list of route variables.
%
|xref:../install_config/router/default_haproxy_router.adoc#install-config-router-default-haproxy[Setting up a Router -> Using the F5 Router Plug-in]
|Added the xref:../install_config/router/default_haproxy_router.adoc#finding-router-hostname[Finding the Hostname of the Router] section
%

**Comment by bfallonf** [comment]
Thanks @ahardin-rh . Merging.

**Pull request merged**
