### PR TITLE
OSDOCS-6112: Documented the 4.12.17 z-stream release

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-6112](https://issues.redhat.com/browse/OSDOCS-6112)

Version(s):
4.12

Link to docs preview:
[4.12.17 preview](http://file.emea.redhat.com/dfitzmau/OSDOCS-6112/release_notes/ocp-4-12-release-notes.html#ocp-4-12-17)

### CODE REVIEW

**Comment by dfitzmau** [comment]
curl -H 'Content-Type: application/json' --request POST --data '{"PR_BRANCH":"OSDOCS-6011","BASE_REPO":"openshift/openshift-docs","PR_NUMBER":"60115","USER_NAME":"dfitzmau","BASE_REF":"enterprise-4.12","REPO_NAME":"dfitzmau/openshift-docs"}' https://eoa6vg2jiwjbnh6.m.pipedream.net/

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
