### PR TITLE
Clarify use of # and $ in code blocks

### PR DESCRIPTION
**Pull request by kalexand-rh**
@openshift/team-documentation, PTAL

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@kalexand-rh - do we have anything on this in our CCS guidelines? I am guessing this is via the IBM style guide?

**Comment by kalexand-rh** [comment]
@vikram-redhat, it's not in the glossary or the IBM Style guide. (IBM doesn't use either to differentiate commands and instead adds copy widgets so you can easily capture the entire command for easy pasting into your CLI. I once spent two days purging a collection of all the leading dollar signs on commands.)
I was told in our IRC channel that that was the way we were using them and couldn't think of a better place to record it.

**Comment by vikram-redhat** [comment]
@kalexand-rh - great. You should consider submitting it to the CCS Guidelines as well.

**Comment by vikram-redhat** [comment]
In the meantime @openshift/team-documentation any objections?

**Comment by tmorriso-rh** [comment]
LGTM.

**Pull request merged**
