### PR TITLE
Update ingress cidr references to new default

### PR DESCRIPTION
**Pull request by marun**
Reflects updates made in https://github.com/openshift/origin/pull/12379 to address https://github.com/openshift/origin/issues/12313

cc: @openshift/networking

### CODE REVIEW

**Comment by marun** [comment]
Added a warning of ip reassignment if ingressIPNetworkCIDR is changed.

**Comment by marun** [comment]
Added a warning of ip reassignment if ingressIPNetworkCIDR is changed.

**Review by knobunc — APPROVED** [review]
LGTM.  @openshift/team-documentation, over to you.

**Comment by knobunc** [comment]
Are there other circumstances when the assigned IP address can change?  Should the people who are using this watch for changes in general?

**Comment by vikram-redhat** [comment]
@knobunc - applies to 3.3 onwards?

**Comment by knobunc** [comment]
@vikram-redhat yes, that's right. Thanks for asking.

**Comment by vikram-redhat** [comment]
Thanks @knobunc . Can you please rebase and squash your commits into one commit?

@ahardin-rh - PTAL.

**Comment by vikram-redhat** [comment]
@ahardin-rh - I added the online and dedicated labels - pretty sure at least one file is affected which makes it applicable for these distros as well, but do confirm if these labels are correct.

**Comment by knobunc** [comment]
@marun @vikram-redhat wanted a squash above, but accidentally mentioned me.

**Comment by marun** [comment]
@vikram-redhat Why squash?  These changes are logically distinct.

**Comment by marun** [comment]
@knobunc There's a chance that more than if more than one master is running at the same time (e.g. leader election) that there could be conflicting assignments that result in reallocations.

**Comment by vikram-redhat** [comment]
@marun  - we squash all our commits into one for docs. If these commits are logically distinct, then submit separate PRs.

**Comment by marun** [comment]
@vikram-redhat Given that all I do all day long is work with version control, what you're saying makes zero sense to me.  But sure, whatever you say.

**Comment by ahardin-rh** [comment]
Thank you! I will apply some very minor style edits in a separate PR.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/tcp_ingress_external_ports.adoc#unique-external-ips-ingress-traffic-configure-cluster[Configuring the Cluster to Use Unique External IPs]
|Added a CAUTION box indicating that external IPs assigned to services of type `LoadBalancer` will always be in the range of `ingressIPNetworkCIDR` and updated Ingress CIDR references to the new default.
%
|xref:../architecture/core_concepts/pods_and_services.adoc#architecture-core-concepts-pods-and-services[Core Concepts -> Pods and Services]
|Updated Ingress CIDR references to the new default.
%

**Pull request merged**
