### PR TITLE
HCIDOCS-365: 4.16 RN for BMH firmware update

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.16

Issue: [HCIDOCS-365](https://issues.redhat.com//browse/HCIDOCS-365)

Link to docs preview: [Known issues](https://77638--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-known-issues_release-notes)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by iurygregory — COMMENTED** [review]
/lgtm

**Review by dtantsur — APPROVED** [review]

**Pull request merged**
