### PR TITLE
Trello-681 Remove Depricated ES_copy Content

### PR DESCRIPTION
**Pull request by bmcelvee**
https://trello.com/c/mNs806SG/681-document-remove-deprecated-escopy-method-of-forwarding-logs-to-external-es

https://trello.com/c/hk39Z7q0/591-2-remove-deprecated-escopy-method-of-forwarding-logs-to-external-es

### CODE REVIEW

**Comment by bmcelvee** [comment]
@jcantrill PTAL

**Review by jcantrill — APPROVED** [review]

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Removed the xref:../install_config/aggregate_logging.adoc#fluentd-log-external-elasticsearch[Having Fluentd Send Logs to Another Elasticsearch] section.
%

**Comment by bmcelvee** [comment]
@openshift/team-documentation please peer review 🍁

**Comment by vikram-redhat** [comment]
LGTM :)

**Comment by vikram-redhat** [comment]
The rev history might need changing though. If that section is removed, you can't link to it.

Removed the xref:../install_config/aggregate_logging.adoc#**fluentd-log-external-elasticsearch**[Having Fluentd Send Logs to Another Elasticsearch] section.

**Comment by bmcelvee** [comment]
Ah yes, thanks!

**Pull request merged**
