### PR TITLE
bug in vsphere config

### PR DESCRIPTION
**Pull request by bagnaram**
Should be default-datasture https://github.com/kubernetes/kubernetes/blob/release-1.11/test/e2e/storage/vsphere/config.go

### CODE REVIEW

**Comment by kalexand-rh** [comment]
/ok-to-test
@cooktheryan, will you PTAL and confirm that this change applies to 3.10 and 3.11?

**Comment by cooktheryan** [comment]
@kalexand-rh will do. Paging our vmware guy @dav1x

**Comment by mazzystr** [comment]
LGTM

**Comment by dav1x** [comment]
The vsphere cloud provider is intentionally backwards compatible from the prior to multiple vCenter configuration. 

Please see here:
https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/cloudprovider/providers/vsphere/vsphere.go#L129


https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#vsphere-cloud-config-file-for-kubernetes-version-18x-or-below

Bearing all this in mind, the documentation should be updated to include the different configurations listed here:
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#vsphere-cloud-config-file-for-kubernetes-version-19x-and-above

The current PR /lgtm ill create an addition PR with the info from above as well. This change can be applied to 3.10 and 3.11

**Comment by kalexand-rh** [comment]
Thank you all! I'll get this change into 3.10 and 3.11 and look for @dav1x's followup.

**Pull request merged**
