### PR TITLE
WCAG AA style examples for code blocks

### PR DESCRIPTION
**Pull request by jboxman**
The preview might work.

If not, fetch the PR, build, and in the preview build directory enter:

```
$ cd _preview/openshift-enterprise/wcag-aa-styles
$ python3 -m http.server
```

On `localhost:8000` it should be possible to look at the preview. It only works with an HTTP server running.

### CODE REVIEW

**Comment by jboxman** [comment]
@maxwelldb, FYI

**Comment by jboxman** [comment]
Colorful 
Screen Shot 2020-06-23 at 10 42 52 PM

**Comment by jboxman** [comment]
Fruity
Screen Shot 2020-06-23 at 10 43 32 PM

**Comment by jboxman** [comment]
monokai
Screen Shot 2020-06-23 at 10 43 54 PM

**Comment by jboxman** [comment]
perldoc
Screen Shot 2020-06-23 at 10 48 03 PM

**Comment by jboxman** [comment]
fruity
Screen Shot 2020-06-23 at 10 53 20 PM

**Comment by jboxman** [comment]
perldoc
Screen Shot 2020-06-23 at 10 53 20 PM

**Comment by jboxman** [comment]
native
Screen Shot 2020-06-23 at 10 55 02 PM

**Comment by jboxman** [comment]
solarized dark
Screen Shot 2020-06-23 at 10 55 27 PM

**Comment by jboxman** [comment]
solarized light
Screen Shot 2020-06-23 at 10 55 49 PM

**Comment by jboxman** [comment]
trac
Screen Shot 2020-06-23 at 10 55 49 PM

**Comment by jboxman** [comment]
vim
Screen Shot 2020-06-23 at 10 56 09 PM

**Comment by jboxman** [comment]
vim
Screen Shot 2020-06-23 at 10 56 27 PM

**Comment by jboxman** [comment]
@openshift/team-documentation, I've included screen shots for convenience, but it's only a YAML. This demo uses Ruby code:

https://maxchadwick.xyz/pygments-high-contrast-stylesheets/

@vikram-redhat, these are WCAG compliant at the request of @maxwelldb.

The callouts look insane with any style, unfortunately. The padding can be fixed, so the numbers don't hug the code so closely. It looks awfully loud, though.

Thoughts?

**Comment by maxwelldb** [comment]
@jboxman Thanks!

Autumn seems to be missing and trac is a duplicate of monokai-light. Those were my two frontrunners for a light-themed site, FWIW.

**Comment by maxwelldb** [comment]
Trac's in there if you build and click, but Autumn required some puttering:

image

Still probably my favorite, but the callouts are loud + heavy, yes.

**Comment by jboxman** [comment]
@maxwelldb, oops, that was my fault; I changed the include path for the sheets for the preview, then back again, and reloaded locally without remembering, so it might not have loaded the right (or any) sheet when I clicked.

**Comment by bobfuru** [comment]
> The callouts look insane with any style, unfortunately. The padding can be fixed, so the numbers don't hug the code so closely. It looks awfully loud, though.
> 
> Thoughts?

Agree, the callouts are a dealbreaker for me. They give precedence to what is arguably secondary information.

**Comment by jboxman** [comment]
@bobcallaway, but those are easy enough to fix. It's not a graphic.

Screen Shot 2020-06-24 at 1 12 02 PM

**Comment by bobcallaway** [comment]
@bobfuru ^^^

**Comment by jboxman** [comment]
@maxwelldb, I fixed the missing/broken ones.

**Comment by maxwelldb** [comment]
https://github.com/openshift/openshift-docs/pull/23243#issuecomment-648941397

Callouts are also an accessibility problem, so having to rework them at some point is probably okay.

**Comment by jboxman** [comment]
https://github.com/openshift/openshift-docs/pull/23534 implements this.

**Pull request closed without merging**
