### PR TITLE
OSDOCS-5670: Removes references of Multicluster feature from 4.10 RNs

### PR DESCRIPTION
**Pull request by opayne1**
[OSDOCS-5670](https://issues.redhat.com//browse/OSDOCS-5670): Removes references of Multicluster feature from 4.10 RNs

Relates to https://github.com/openshift/openshift-docs/pull/58093

Version(s):
4.10

Issue:
https://issues.redhat.com/browse/OSDOCS-5670

Link to docs preview:
http://file.rdu.redhat.com/opayne/OSDOCS-5670-4/release_notes/ocp-4-10-release-notes.html#ocp-4-10-web-console
http://file.rdu.redhat.com/opayne/OSDOCS-5670-4/release_notes/ocp-4-10-release-notes.html#ocp-4-10-technology-preview

QE review:
- [x] QE has approved this change.

Additional information:
This PR will need to go through CM

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM

**Comment by yapei** [comment]
look good from QE side

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by opayne1** [comment]
Putting back on peer review since I added to the dep/rem table.

**Comment by mburke5678** [comment]
@opayne1 Just curious, why comment-out the text rather than remove? In case CM doesn't approve, perhaps??

**Comment by opayne1** [comment]
We will probably need to add it back in later. The feature is only on hold for a couple releases if that afaik. @mburke5678

**Pull request merged**
