### PR TITLE
Update Kiali screen shots for TP6.

### PR DESCRIPTION
**Pull request by JStickler**
I haven't updated the Kiali screen shots for a couple of releases.  New Year's seems like a good time for a refresh.

@geekspertise , @kalexand-rh

### CODE REVIEW

**Comment by kalexand-rh** [comment]
/ok-to-test

@JStickler, will you confirm that you're finished updating the image references? It looks like you've added a few that aren't referenced in this PR and have removed a couple of images but not their references.

**Comment by JStickler** [comment]
@kalexand-rh I've added one new image, and some of the file sizes are different on the ones I'm replacing.  That may be the confusion?

**Comment by kalexand-rh** [comment]
@JStickler, thanks! I was misinterpreting the change of file size as adding and removing the binary files.

**Comment by JStickler** [comment]
@kalexand-rh , @vikram-redhat  we've released TP6, could we get this merged into the 3.11 branch please.  Thanks in advance.

**Comment by kalexand-rh** [comment]
Sure  @JStickler! I'll merge the other TP6 PR, too.

**Pull request merged**
