### PR TITLE
[SRVKS-1177] Remove module from Integrations

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.32+

Issue:
https://issues.redhat.com/browse/SRVKS-1177

Link to docs preview:
FIXME

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by skopacz1** [comment]
I'm going to wait until tests pass and a preview is built before finishing my review, just to be sure

**Comment by skopacz1** [comment]
Preview: [Improving net-istio memory usage by using secret filtering for Service Mesh](https://74196--ocpdocs-pr.netlify.app/openshift-serverless/latest/integrations/serverless-ossm-setup#serverless-ossm-secret-filtering-net-istio_serverless-ossm-setup) (Section closest to where the other one was deleted)

**Review by skopacz1 — APPROVED** [review]
LGTM! Keep in mind that this will need QE approval before it gets merged

**Comment by mgencur** [comment]
LGTM from QE

**Pull request merged**
