### PR TITLE
Remove link Ansible inv doc link

### LINKED ISSUE #27643: [enterprise-3.11] Issue in file install_config/configuring_azure.adoc
### Which section(s) is the issue in?
Configuring OpenShift Container Platform for Azure using Ansible

The above-highlighted section should either be updated or removed, as it leads to believe Azure File can be run as day-2 operation by **running the Ansible inventory file**. 

The only two ways to add Azure File storage support to a cluster would be:
- By either doing it at installation time (updating the inventory file, adding the azure variables and deploy de cluster).
- Or doing it manually, as highlighted lower in that same doc section: https://docs.openshift.com/container-platform/3.11/install_config/configuring_azure.html#manually-configuring-for-azure_configuring-for-azure

### PR DESCRIPTION
**Pull request by bobfuru**
Fix to https://github.com/openshift/openshift-docs/issues/27643
Removes xref to Ansible inventory file customization doc. As the reporter states, the wording removed in this PR "leads to believe Azure File can be run as day-2 operation by running the Ansible inventory file".

Preview link: https://deploy-preview-31243--osdocs.netlify.app/openshift-enterprise/latest/install_config/configuring_azure.html#azure-configuring-ansible_configuring-for-azure

### CODE REVIEW

**Comment by bobfuru** [comment]
@qinpingli PTAL for QE

**Comment by bobfuru** [comment]
@rhatbob PTAL and let me know if this addresses your reported issue. Thanks!

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by qinpingli** [comment]
LGTM

**Pull request merged**
