### PR TITLE
[BZ2054697] Adding BIOS settings in the SRIOV prereq section

### PR DESCRIPTION
**Pull request by mdekan1**
https://bugzilla.redhat.com/show_bug.cgi?id=2054697

### CODE REVIEW

**Comment by mdekan1** [comment]
hmm, didn't get generated as expected
https://deploy-preview-42490--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.html#prerequisites

**Comment by sjhala-ccs** [comment]
Will the changes in this PR apply to CNV version 4.9 and later? Can you please specify that in the PR description? Thanks.

**Comment by sjhala-ccs** [comment]
@mdekan1 The changes LGTM. Can you please squash your commits into one commit and also let me know which CNV versions do these changes apply to? I can merge the PR and cherry pick to the appropriate version branches.

**Pull request merged**
