### PR TITLE
OSDOCS#7762: Add vanafi in the supported issuer types section

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-7762

Link to docs preview: https://64818--docspreview.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/index.html#cert-manager-issuer-types_cert-manager-operator-about

QE review:
- [x] QE has approved this change.

SME review:
- [x] SME has approved this change.

Additional information:  This doc PR needs to be merged after the cert-manager-operator `v1.12.0` is released. (2 Oct 2023) [meanwhile I am adding peer-review-needed label for the quick merge after the release]

### CODE REVIEW

**Review by lunarwhite — COMMENTED** [review]
/lgtm

cc @thejasn

**Comment by swghosh** [comment]
/lgtm
(Reminder: we need to ensure that this doc PR is merged only when cert-manager-operator.v1.12.0 gets released :)

**Pull request merged**
