### PR TITLE
GitOps- Change default namespace to spring-petclinic namespace

### PR DESCRIPTION
**Pull request by reginaelyse**
Changed `default` namespace to `spring-petclinic`; using `default` namespace is not encouraged. 

Would fix [GITOPS-1363](https://issues.redhat.com/browse/GITOPS-1363?focusedCommentId=19032813&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19032813).

OCP Version - 4.7, 4.8, 4.9

cc @wtam2018

### CODE REVIEW

**Review by wtam2018 — COMMENTED** [review]
LGTM

**Comment by xsoldaat** [comment]
Looks great, thanks!

**Comment by reginapizza** [comment]
@Preeticp is this okay to get merged?

**Comment by wtam2018** [comment]
@Preeticp PTAL

**Pull request merged**
