### PR TITLE
Bug 1347090 : added note box to environment variables table

### PR DESCRIPTION
**Pull request by bfallonf**
As per https://bugzilla.redhat.com/show_bug.cgi?id=1347090

@bparees Would you say this more accurately represents the situation? Feel free to let me know either here on in the BZ.

### CODE REVIEW

**Comment by bparees** [comment]
lgtm 
http://stackoverflow.com/questions/19894849/error-text-search-not-enabled-in-mongodb

**Comment by bfallonf** [comment]
Sure. Thanks @bparees 

@ahardin-rh @adellape @tpoitras @tnguyen-rh Anyone have any issues?

**Comment by ahardin-rh** [comment]
@bfallonf LGTM!

**Comment by bfallonf** [comment]
[rev_history]
|link:../using_images/db_images/mongodb.html[Database Images -> MongoDB]
|Added the a note box to the Additional MongoDB Settings table in the link:../using_images/db_images/mongodb..html#environment-variables[Environment Variables] section.
%

**Comment by bfallonf** [comment]
Thanks @ahardin-rh Merging.

**Pull request merged**
