### PR TITLE
ocprhv-687 adding reference for updating credentials

### PR DESCRIPTION
**Pull request by emarcusRH**
Signed-off-by: emarcusRH <emarcus@redhat.com>

updating credentials after creating persistent volume with CSI driver on RHV

Version(s):
enterprise-4.12

Issue:

https://issues.redhat.com/browse/OCPRHV-687

Link to docs preview:

http://file.tlv.redhat.com/emarcus/ocprhv-687/storage/container_storage_interface/persistent-storage-csi-ovirt.html#persistent-storage-rhv_persistent-storage-csi-ovirt

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/remove-label peer-review-in-progress 
/label peer-review-done
/lgtm

**Comment by emarcusRH** [comment]
Approved by Dev : 

Michael Engel | Michael Engel | Mon, Dec 19, 6:56 PM (2 days ago)
"Hi Eli, 
sorry for the late reply - I was on PTO last week.
The PR looks to me"

**Pull request merged**
