### PR TITLE
[enterprise-4.14] OCPBUGS#23545: Remove the tech preview label

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.14 

Issue: https://issues.redhat.com/browse/OCPBUGS-23545

Link to docs preview: https://68318--docspreview.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-troubleshooting

QE review: Not required. The Self-Managed Hosted Control Planes is now Generally Available. Hence removing the TP label from the "Troubleshooting hosted control planes" section.

Additional information:

### CODE REVIEW

**Comment by zanetworker** [comment]
lgtm

**Review by kelbrown20 — COMMENTED** [review]
/lgtm

**Pull request merged**
