### PR TITLE
update docs for re-enabled jenkins autoprovision

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge

**Comment by vikram-redhat** [comment]
@ahardin-rh - ptal.

**Comment by ahardin-rh** [comment]
@bparees LGTM. Thank you!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/core_concepts/builds_and_image_streams.adoc#architecture-core-concepts-builds-and-image-streams[Core Concepts -> Builds and Image Streams]
|Added a link for more details on how the Jenkins server is deployed.
%
|xref:../install_config/configuring_pipeline_execution.adoc#install-config-configuring-pipeline-execution[Configuring Pipeline Execution]
|Noted that for `*jenkinsPipelineConfig*`, the `* autoProvisionEnabled*` value defaults to `true` if unspecified.
%

**Pull request merged**
