### PR TITLE
OSDOCS-4868: Add step to remove manifests for control plane machine set

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.13+

Issue:
This PR addresses [osdocs-4868](https://issues.redhat.com//browse/osdocs-4868)

Link to docs preview:
[Creating the Kubernetes manifest and Ignition config files](https://55059--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-gcp-user-infra) (step 3).

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@rna-afk and @jianli-wei Ready for SME and QE review. PTAL. Thank you.

**Review by jianli-wei — APPROVED** [review]

**Pull request merged**
