### PR TITLE
External links to migration CRs updated, few small fixes.

### PR DESCRIPTION
**Pull request by apinnick**
Updated paths where master branch changed to main. small fixes

CP to 4.5, 4.6

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@apinnick - when is this supposed to go live? I don't see the changes from master to main in the underlying repos though ( Example: https://github.com/fusor/mig-controller/blob/main/pkg/apis/migration/v1alpha1/migcluster_types.go). 

BTW - I am assuming we approved the links to GH repo? 

@bergerhoffer

**Comment by apinnick** [comment]
@vikram-redhat  @kalexand-rh @bergerhoffer 

Vikram, the github links were approved when this module was first published. Users are not downloading content from Github but they do need to see the Go code of the migration CRs.

Kathryn, I have checked all the links and updated them.

**Comment by vikram-redhat** [comment]
Thanks @apinnick - I am sorta confused now. The PR title says that you are changing master to main, but the links are now back to the master branch (on another repo?).

**Comment by apinnick** [comment]
> Thanks @apinnick - I am sorta confused now. The PR title says that you are changing master to main, but the links are now back to the master branch (on another repo?).

@vikram-redhat Some of the links changed master to main, other changed Fusor to Konveyor. I'll update the title.

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
