### PR TITLE
TELCODOCS-1516: Moving bare metal monitoring to correct assembly

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1516](https://issues.redhat.com//browse/TELCODOCS-1516): Moving bare metal monitoring from the Monitoring section to Scalability and Performance section. It's not part of the Monitoring stack, it's an optional Operator. 

FYI - the Bare Metal Event Relay Operator feature is deprecated in 4.15 and is scheduled for removal in a future release. So this assembly will go away this year.

Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/TELCODOCS-1516

Link to docs preview:
https://70406--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/using-rfhe

Additional information:
No QE review required, no content changes, just moving assembly to correct location.

### CODE REVIEW

**Comment by shipsing** [comment]
@rohennes, The changes look fine. Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

**Review by bburt-rh — APPROVED** [review]
LGTM. Thanks!

**Comment by stevsmit** [comment]
lgtm

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM as well!

**Pull request merged**
