### PR TITLE
WIP Adds whereabouts IPAM CNI and route-override usage descriptions

### PR DESCRIPTION
**Pull request by dougbtv**
@lamek here's a first pass at docs for whereabouts & route-override.

Happy to take any suggestions here for sure. I'm certain that the whereabouts portion should live in this document, but... I'm unsure about route-override. It's kind of related to IP address management, but... it's also kind of not. I'm unsure there.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@lamek can this be merged?

**Comment by jboxman** [comment]
Hi @dougbtv, is the technical content for this ready to go?

Thanks!

**Comment by jboxman** [comment]
@dougbtv, there is probably a two week window to get this in for _4.5_, FYI.

**Comment by dougbtv** [comment]
@jboxman thanks for the heads up! Technically, I'm happy with the content. What can I do to help us get this in for 4.5? My apologies it comes through late in the cycle here.

**Comment by jboxman** [comment]
@dougbtv, can your QE counterpart for this provide an ack? Thanks!

**Comment by weliang1** [comment]
Here is Jira card user story for whereabouts:
https://issues.redhat.com/browse/SDN-556

Here is the test case QE run:
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-28633

**Comment by jboxman** [comment]
@weliang1, a preview build:

http://file.bos.redhat.com/jboxman/whereabouts/dougbtv-route-override-whereabouts-docs/networking/multiple_networks/configuring-macvlan.html#nw-multus-dynamic-whereabouts-example_configuring-macvlan

**Comment by jboxman** [comment]
Closing in favor of other PR.

**Comment by leseb** [comment]
> Closing in favor of other PR.

Where is the other PR?

**Comment by jboxman** [comment]
@leseb - https://github.com/openshift/openshift-docs/pull/23057

**Pull request closed without merging**
