### PR TITLE
TELCODOCS:1103 - Update note in kataconfig file about label values

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): Main, 4.13, 4.12, 4.11, 4.10, 4.9

Issue: [TELCODOCS-1103](https://issues.redhat.com/browse/TELCODOCS-1103)

[Link to docs preview](https://55632--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads.html#sandboxed-containers-create-kataconfig-rsource-cli_deploying-sandboxed-containers)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by tbuskey** [comment]
QE ack /lgtm  1103 a-d
Sorry I didn't see it sooner

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Comment by bergerhoffer** [comment]
@MirzWeiss The cherry pick to 4.9 failed to pick cleanly. Can you please submit a manual cherry pick to 4.9 for this update? Thanks!

**Comment by MirzWeiss** [comment]
> @MirzWeiss The cherry pick to 4.9 failed to pick cleanly. Can you please submit a manual cherry pick to 4.9 for this update? Thanks!

Done, and I assigned it to you, hope that's okay. Thank you!

**Comment by bergerhoffer** [comment]
Perfect, ty!

**Pull request merged**
