### PR TITLE
Uprev sandboxed containers channel to stable

### PR DESCRIPTION
**Pull request by aireilly**
Merge to main, enterprise-4.10, enterprise-4.11

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @aireilly

**Review by cpmeadors — APPROVED** [review]

**Comment by mburke5678** [comment]
@aireilly LGTM

**Comment by aireilly** [comment]
> @aireilly Can you confirm that the changes in the current PR were made to the `enterprise-4.10` branch in [this PR](https://github.com/openshift/openshift-docs/pull/42866/files#diff-03673e02617ffe9ba913697104a75cb43b400f9ccb4358b1dc2df45a3168ba10). If so, no need to CP to 4.10.

Ah. Yes indeed. All present and correct. Thanks.

**Pull request merged**
