### PR TITLE
Follow-up edits to PR#2538

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/2538

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@bfallonf @adellape @tpoitras PTAL. Thanks!

**Comment by bfallonf** [comment]
@ahardin-rh I had a read-through and didn't see anything glaring. LGTM!

**Comment by ahardin-rh** [comment]
@bfallonf Thanks for the peer review!

**Comment by ahardin-rh** [comment]
Rev history in original PR

**Pull request merged**
