### PR TITLE
SR-IOV Network Operator does not provide a DHCP DaemonSet

### PR DESCRIPTION
**Pull request by jboxman**
This adds a new note, with a conditional for SR-IOV Network Operator, explaining how DHCP leases are renewed.

### CODE REVIEW

**Comment by jboxman** [comment]
> A DHCP DaemonSet is required to periodically renew the DHCP lease for the duration of container lifetime. However, the SR-IOV Network Operator does not deploy a DHCP DaemonSet. To trigger the deployment of a DHCP DaemonSet, you must create a shim network attachment by editing the Cluster Network Operator configuration.

@zshi-redhat, does it matter that a DaemonSet is used? Or is that an implementation detail that doesn't matter to a user? Would any reachable DHCP server work, whether it is running in a container or outside the cluster network?

What's special about the CNO DHCP server? Is it just a _basic_ or _limited_ DHCP server that renews leases for containers only or something?

I just want to be sure what we're stating is helpful. Thanks!

**Comment by zshi-redhat** [comment]
> > A DHCP DaemonSet is required to periodically renew the DHCP lease for the duration of container lifetime. However, the SR-IOV Network Operator does not deploy a DHCP DaemonSet. To trigger the deployment of a DHCP DaemonSet, you must create a shim network attachment by editing the Cluster Network Operator configuration.
> 
> @zshi-redhat, does it matter that a DaemonSet is used? Or is that an implementation detail that doesn't matter to a user? Would any reachable DHCP server work, whether it is running in a container or outside the cluster network?

It should not matter to user whether it is a DaemonSet or any other form like a deployment. What matters is the function provided in this DaemonSet to renew the leases for container interfaces (using dhcp ipam).

The reason to have such a DaemonSet is, when `dhcp` ipam is used in net-attach-def, it calls the `dhcp` CNI binary to request the dhcp address from dhcp server (outside of OpenShift cluster). Since `dhcp` CNI binary is only called once (during pod creation), it doesn't/cannot provide the function of renew the dhcp lease,  that's why we need a separate dhcp DaemonSet to provide the lease renew function. So the dhcp server would still run independently, but we have to provide the full functionality of the dhcp CNI by adding a new dhcp Daemon. Usually the dhcp server will be outside of the OpenShift cluster, it could be deployed in the cluster pod (afaik).

> 
> What's special about the CNO DHCP server? Is it just a _basic_ or _limited_ DHCP server that renews leases for containers only or something?

Yes, my understanding is it just provides the renew function of dhcp.
> 
> I just want to be sure what we're stating is helpful. Thanks!

**Comment by zshi-redhat** [comment]
@dougbtv please let me know if my statement above is not true.

**Comment by jboxman** [comment]
@zshi-redhat, I think this is also applicable in general:

https://bugzilla.redhat.com/show_bug.cgi?id=1760933

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I think this is also applicable in general:
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1760933

@jboxman yes, the statement(about dhcp daemon) is true for other types of interfaces, sriov is one of them.
I think we'd like to include a note for SR-IOV doc as the configuration of dhcp daemon is done via CNO instead of via SR-IOV Operator.

**Comment by jboxman** [comment]
@zshi-redhat, I've changed the text so that it applies both when SR-IOV is used and when it is not. I've included an example CNO configuration as well.

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I've changed the text so that it applies both when SR-IOV is used and when it is not. I've included an example CNO configuration as well.

Thanks @jboxman for the quick fix, the new update looks good to me!

**Comment by ahardin-rh** [comment]
@jboxman LGTM! My only question is whether or not DHCP should be defined at first usage in the topic. It seems like a common networking term, but I am not familiar with it. Just a suggestion/pondering for consideration.

**Comment by jboxman** [comment]
@ahardin-rh, whenever I do that for common networking terms, I've gotten push back that it's quite unnecessary to do so, so I've mostly stopped with especially common terms like DHCP, IP, DNS, and so forth. I do sneak some in, from time to time, though.

**Pull request merged**
