### PR TITLE
OSDOCS-2999: Updates to Monitoring navagation menu name in OCP docs

### PR DESCRIPTION
**Pull request by opayne1**
[OSDOCS-2999 ](https://issues.redhat.com/browse/OSDOCS-2999)

- Applies to `enterprise-4.9`+
- [Preview link](https://deploy-preview-39336--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-console_cluster-logging-deploying)

### CODE REVIEW

**Comment by bburt-rh** [comment]
lgtm

**Comment by kdoberst** [comment]
Looks good to me

**Comment by opayne1** [comment]
@schituku PTAL

**Review by jeana-redhat — COMMENTED** [review]
LGTM! Found a typo (not yours) and a few files that may or may not be in use (I didn't see them in the output or live docs). Not sure what's best to do about the latter, but if you want to get this merged I think it's fine to leave them be for the moment.

**Pull request merged**
