### PR TITLE
OSDOCS-2362: Adding release notes for the new descheduler profiles

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2362

Preview: https://deploy-preview-36066--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nodes-descheduler

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@damemi release notes for descheduler, if you can take a look.

Preview: https://deploy-preview-36066--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nodes-descheduler

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please QE review this release notes update? Note that, though the link will work and go to the descheduler section, it's expected that that won't show any of the new descheduler profiles yet. That's because it'll need #36062 to merge for that to show. 

Preview: https://deploy-preview-36066--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nodes-descheduler

**Review by damemi — COMMENTED** [review]
/lgtm

**Pull request merged**
