### PR TITLE
CNV-20483: RN for migration metrics + adding runbooks link

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): no CP (4.12 only)

Issue: [CNV-20483](https://issues.redhat.com//browse/CNV-20483)

Link to docs preview: https://54673--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-12-release-notes.html#virt-4-12-new

QE review:
- [x] QE has approved this change.

Additional information: Also adding a link to the runbooks docs now that the PR has been merged.
@sabrinajess FYI :)

### CODE REVIEW

**Comment by dshchedr** [comment]
LGTM

**Comment by tmalove** [comment]
Hi @ousleyp just checking that this update goes into 4.12 only, yes? You mentioned 'no CP'. Otherwise, looks good!

**Pull request merged**
