### PR TITLE
OCPBUGS#12285: Update the operator library version

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OCPBUGS-12285

Link to docs preview: https://59186--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-generating-csvs.html#osdk-operatorconditions_osdk-generating-csvs

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by KeenonLee — COMMENTED** [review]
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
