### PR TITLE
OSDOCS-5712

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-5712](https://issues.redhat.com//browse/OSDOCS-5712)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-5712

Link to docs preview:
N/A

QE review:
N/A

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! All set to merge, @jneczypor?

**Comment by jneczypor** [comment]
Yes! @bmcelvee! Thanks so much. /label merge-review-needed

**Pull request merged**
