### PR TITLE
BZ-1613677 Removed gitRepo from volume example and APIs

### PR DESCRIPTION
**Pull request by lbarbeevargas**

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
@qinpingli PTAL for 3.11. Thank you!

BZ-1613677 https://bugzilla.redhat.com/show_bug.cgi?id=1613677

**Note:** For all of the API updates (for example, the `rest_api/api/v1.Pod.adoc` file) I removed the `gitRepo` object from `volumes`.

**Comment by lbarbeevargas** [comment]
@sjenning  PTAL for 3.11. Thanks!

**Comment by qinpingli** [comment]
lgtm

**Comment by lbarbeevargas** [comment]
@openshift/team-documentation PTAL for 3.11. Add labels and milestone. Please merge to enterprise-3.11. Thank you! 

BZ-1613677 https://bugzilla.redhat.com/show_bug.cgi?id=1613677

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Pull request merged**
