### PR TITLE
bug 1891039 - removing boot media limitation

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1891039

@miabbott, PTAL?

### CODE REVIEW

**Comment by miabbott** [comment]
Yup, this is accurate.  Though I would go a step further and just revert the entire commit (d39a556ace3b743a93897135c5d795fb337f6d49) entirely since we are no longer imposing limitations.

**Comment by kalexand-rh** [comment]
@miabbott, thanks! I'll pull the whole note. Is this behavior changing for 4.6? I've been asked to add a release note for it, and I'd like to better understand what's different in 4.6.

**Comment by miabbott** [comment]
We are working on a KBase article that will cover steps users can use if they want to add additional nodes using boot media that is newer than the version of the original cluster.  (i.e. adding a node with 4.5 boot media on a cluster originally installed using 4.3)

Because 4.6 introduces a new Ignition spec version (spec 3, specifically), there are additional steps needed to convert Ignition configs used.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
