### PR TITLE
TRACING-3808: Add missing OTLP exporter to OTELcol config for span RED metrics

### PR DESCRIPTION
**Pull request by pavolloffay**
Version(s):

4.11, 4.12, 4.13, 4.14, 4.15

Issue:

https://issues.redhat.com/browse/TRACING-3808

Link to docs preview:

https://69673--ocpdocs-pr.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring#opentelemetry-collector-configuration

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by IshwarKanse — APPROVED** [review]

**Review by max-cx — APPROVED** [review]
LGTM for the peer review

**Comment by max-cx** [comment]
label/ peer-review-done

**Comment by max-cx** [comment]
label/ merge-review-needed

**Comment by max-cx** [comment]
label/ peer-review-done

**Comment by max-cx** [comment]
label/ merge-review-needed

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM! You just need to squash those commits before merging

**Comment by pavolloffay** [comment]
> Updates LGTM! You just need to squash those commits before merging

@kelbrown20 done

**Pull request merged**
