### PR TITLE
Fix margin and padding for definition lists

### PR DESCRIPTION
**Pull request by jboxman**
@bergerhoffer, how about this?

Screen Shot 2020-10-28 at 11 43 22 AM

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@jboxman That looks much better to me. Thank you!!

**Comment by jboxman** [comment]
FYI @vikram-redhat, a small fix to margins for our definition lists.

**Comment by vikram-redhat** [comment]
@jboxman merge away!

**Pull request merged**
