### PR TITLE
Change sysconfig.conf to syslog.conf

### PR DESCRIPTION
**Pull request by eRaid6**
Changing sysconfig.conf to syslog.conf otherwise fluentd will ignore the configuration.

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli PTAL. 
These changes appear correct based on a comment from @jcantrill that I must have missed (likely because the comment is listed as `outdated` in GitHub).
https://github.com/openshift/openshift-docs/pull/19650#discussion_r394656038

**Review by anpingli — COMMENTED** [review]
LGTM

**Pull request merged**
