### PR TITLE
BZ2004967: Remove incorrect desc

### PR DESCRIPTION
**Pull request by jldohmann**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2004967

OCP Version: 4.7+

Current 4.10 docs: https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere

Direct doc preview link: https://deploy-preview-43641--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-machines_installing-restricted-networks-vsphere (step 9d)

### CODE REVIEW

**Comment by jldohmann** [comment]
@miabbott could you PTAL for QE ack? 

The BZ has more info, but this PR removes a sentence in a procedure that tells users to specify the URL of their hosted bootstrap Ignition config file. Thank you 🙇

**Comment by jinyunma** [comment]
LGTM

**Review by miabbott — APPROVED** [review]
LGTM

**Comment by tmalove** [comment]
@jldohmann LGTM

**Pull request merged**
