### PR TITLE
BZ-2071810 fixed Azure resource group parameter name

### PR DESCRIPTION
**Pull request by bscott-rh**
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2071810
[Doc preview](https://deploy-preview-44340--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html#oadp-installing-operator_installing-oadp-azure)
CP to 4.7, 4.9, 4.10, 4.11

### CODE REVIEW

**Comment by bscott-rh** [comment]
@mgahagan73 Ready for QA review

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Merging! Skipping 4.8 because it seems to already be fixed just in that version

**Comment by bergerhoffer** [comment]
(Ignore the 4.8 failure, this wasn't supposed to go to 4.8 :roll_eyes: )

**Pull request merged**
