### PR TITLE
OSDOCS-3820: Add STS family to supported SR-IOV devices

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-3820

Version(s): 4.12

Issue:

Link to docs preview: https://50535--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

Additional information:

### CODE REVIEW

**Comment by novacain1** [comment]
lgtm

**Comment by jboxman-rh** [comment]
@Amrita42 thank you!

**Pull request merged**
