### PR TITLE
RHDEVDOCS 6125 publish Pipelines 1.16 on docs.openshift.com

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

main only

Issue:

RHDEVDOCS 6125

Link to docs preview:

n/a

QE review:
n/a

Additional information:

This PR enables publishing a new version of a standalone documentation set on docs.openshift.com. This PR does not alter any documentation content, so no documentation preview is available.

### CODE REVIEW

**Comment by smunje1** [comment]
Peer review LGTM.

**Review by sheriff-rh — APPROVED** [review]
Changes look good; merging to main only.

**Pull request merged**
