### PR TITLE
Adding the TP note back in for CLI plugins

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@openshift/team-documentation For peer review.

This TP note already exists in master, and 3.9 and earlier. Just missing from 3.11 and 3.10 branches.

**Comment by mburke5678** [comment]
@bergerhoffer LGTM Is there an issue that initiated this change?

**Comment by bergerhoffer** [comment]
Thanks @mburke5678! And no, just something I noticed when looking through the CLI content. I asked @vikram-redhat and he said not to worry about opening an issue for it.

Merging.

**Pull request merged**
