### PR TITLE
Etcd typo corrections

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.10+

Link to docs preview:

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Comment by bergerhoffer** [comment]
@adellape @sheriff-rh It looks like this wasn't CPd. Does it still need CPd to 4.10+?

**Comment by sheriff-rh** [comment]
Hey @bergerhoffer, thanks for catching this. I confirmed in 4.10+ branches that this did not get cherry picked. Would you or @adellape mind merging? Thanks!

**Pull request merged**
