### PR TITLE
CNV-14273: Live migration restriction is no longer relevant in 4.10

### PR DESCRIPTION
**Pull request by bgaydosrh**
For 4.10 only.

Jira: https://issues.redhat.com/browse/CNV-14273

Tagging @davidvossel for Code Review.
Tagging @ousleyp for QE and Peer Review (as this is a simple change. Let me know if you think Oded should assign a QE).

Direct doc preview link: https://deploy-preview-41107--osdocs.netlify.app/openshift-enterprise/latest/virt/live_migration/virt-live-migration.html

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

Thanks for noticing this! Looks great

**Comment by ousleyp** [comment]
@bgaydosrh This LGTM, but I think the change is impactful enough that it warrants a QE ack before we merge. Thanks!

**Comment by bgaydosrh** [comment]
Pinging @kbidarkar to ack for QE. Updating Jira story as well. 
cc: @ousleyp

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
