### PR TITLE
BZ1825796 - clarifying vSphere version

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1825796

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@dav1x, does this seem like a reasonable clarification to the supported vSphere versions for 4.6 and earlier?

**Review by dav1x — APPROVED** [review]
LGTM!

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
