### PR TITLE
Removing Descheduler from list as it is not available in 4.1

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@vikram-redhat Question - does this need to go through that new process you defined on changing support status for a feature in published docs?

The descheduler was incorrectly listed as tech preview in the 4.1, 4.2, and 4.3 release notes, but the feature is not available at all in those releases. It is being introduced in 4.4 (as tech preview).

Related PRs: #19778 (4.2) #19779 (4.3) #19780 (4.4)

**Comment by vikram-redhat** [comment]
@bergerhoffer Yes it does.

**Comment by lamek** [comment]
LGTM

**Comment by bergerhoffer** [comment]
The descheduler is listed in the tech preview section of the 4.1-4.3 release notes [1], but it is not even going to be available until 4.4. This PR (and #19778 for 4.2 and #19779 for 4.3) removes it.

@soltysh @sferich888 @xltian @tkatarki @reestr Can you please ack this if you're okay with the descheduler being removed from the 4.1-4.3 tech preview list?

[1] https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-technology-preview

**Comment by xltian** [comment]
@sunilcio can you please review froom QE?

**Review by soltysh — APPROVED** [review]
lgtm

**Comment by tkatarki** [comment]
LGTM

**Comment by reestr** [comment]
LGTM

**Comment by bergerhoffer** [comment]
Thanks all! Ack received from Eric via Slack. Emailing the OpenShift lists now to make sure no one else has any concerns.

**Comment by bergerhoffer** [comment]
@sunilcio @xltian Can I have an ack from QE on this? Thanks!

**Comment by sunilcio** [comment]
@bergerhoffer LGTM.

**Pull request merged**
