### PR TITLE
vSphere content from refarch

### PR DESCRIPTION
**Pull request by dav1x**
WIP. It's a PR to show those involved how it's going.

I'm making the vSphere content more modular, and adding some stuff from the ref arch.

### CODE REVIEW

**Comment by bfallonf** [comment]
Sorry, @dav1x . With all the ref archs I've been given and my usual work I haven't had a chance to get to this just yet. I can pull this PR and fix and broken things and make it hit those CCS standards. Let's leave it open for now and hopefully I'll get to it today or tomorrow.

**Comment by vikram-redhat** [comment]
@ahardin-rh - can you please drive this forward as well?

**Comment by ahardin-rh** [comment]
@vikram-redhat will do!

**Comment by ahardin-rh** [comment]
Cross-checking this content with https://github.com/openshift/openshift-docs/pull/12081 and it seems to be the same content. I pulled the content and edits into https://github.com/openshift/openshift-docs/pull/12306 and got the content cherry-picked to 3.10 and 3.11 docs. So, I am closing this in favor of the other. Please let me know if we need to reopen this. 

FYI @vikram-redhat

**Pull request closed without merging**
