### PR TITLE
BZ1698680: the guide doesn't work, and the IP doesn't match

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1698680

[Configuring Networking-> On the master](https://deploy-preview-43717--osdocs.netlify.app/openshift-enterprise/latest/dev_guide/expose_service/expose_internal_ip_service.html#manually-assign-ips-network),  changed Step 1 to `systemctl restart network`;  added example after Step 4.
[Configuring Networking-> On the node](https://deploy-preview-43717--osdocs.netlify.app/openshift-enterprise/latest/dev_guide/expose_service/expose_internal_ip_service.html#manually-assign-ips-network), changed Step 1 to `systemctl restart network`; added example after Step 3.
[Configuring Networking-> On the system that is not in the cluster](https://deploy-preview-43717--osdocs.netlify.app/openshift-enterprise/latest/dev_guide/expose_service/expose_internal_ip_service.html#manually-assign-ips-network),  changed Step 1 to `systemctl restart network`; added example after Step 3.

### CODE REVIEW

**Comment by mburke5678** [comment]
@vwalek PTAL

**Comment by vwalek** [comment]
Hey @mburke5678 - thx for the PR, I see that there is one issue, there is no systemd service `networking`, but `network`. Could you change it to the network?

Also, I see that the command still works, but it is better to use the systemd service.

Thx

**Comment by mburke5678** [comment]
@zzhao@redhat.com PTAL

**Comment by zhaozhanqi** [comment]
@mburke5678 sorry for late reply.  I did not see any ip is updated here. 
only from `service` to `systemctl`

**Comment by mburke5678** [comment]
@zhaozhanqi I added examples to the procedures that describe the IP addresses in the commands, similar to: 

`route add -net <exposed_service_ip> netmask 255.255.255.0 gw <host_ip_address>`

Does this address your concern?

**Comment by zhaozhanqi** [comment]
ok, this looks good to me, thanks

**Comment by tmalove** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
