### PR TITLE
removed the admonition on spot instances

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to **main, 4.11, 4.10,4.9 and 4.8** branches.
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2091928)
- [GCP Preview] (http://file.del.redhat.com/asakthiv/BZ2091928/machine_management/creating_machinesets/creating-machineset-gcp.html#machineset-non-guaranteed-instance_creating-machineset-gcp)
- [Azure Preview](http://file.del.redhat.com/asakthiv/BZ2091928/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-creating-non-guaranteed-instance_creating-machineset-azure)
- [AWS preview](http://file.del.redhat.com/asakthiv/BZ2091928/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-creating-non-guaranteed-instance_creating-machineset-aws)
- @miyadav ptal

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@Amrita42 LGTM

**Comment by miyadav** [comment]
/lgtm

Thanks @Amrita42

**Pull request merged**
