### PR TITLE
Promote CPU manager pinning to supported

### PR DESCRIPTION
**Pull request by mburke5678**
https://trello.com/c/CGNHORQh/831-document-promote-cpu-manager-pinning-to-supported

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning  @mdshuai 
Does this Trello elevate the entire CPU Manager feature to supported? The term "pinning" in the title makes this not clear to me.

**Comment by sjenning** [comment]
fyi @derekwaynecarr 

The feature really is "Static CPU Policy".  While the end result in CPU pinning, it also repels other pods from the "exclusive" CPUs.  We should probably shouldn't using the word "pinning" and should instead refer to "exclusive cores" vs "shared cores".

**Comment by mburke5678** [comment]
@sjenning @derekwaynecarr The topic doesn't use the term _pinning_. I just want to make sure the entire CPU Manager tool is being promoted. We can certainly work in _exclusive_ vs. _shared_ cores in a follow-up.

**Comment by sjenning** [comment]
sorry, off-topic :) LGTM

**Comment by mburke5678** [comment]
@mdshuai PTAL

**Comment by mburke5678** [comment]
@mdshuai PTAL

**Comment by mburke5678** [comment]
@mdshuai PTAL

**Comment by mdshuai** [comment]
I have missed it, LGTM! Thanks

**Pull request merged**
