### PR TITLE
OSDOCS#11002: Migrating installing the HCP CLI

### PR DESCRIPTION
**Pull request by xenolinux**
This PR is a part of HCP content migration and modularization. Installing HCP CLI has been removed from the RHACM docs and added to the OCP docs. The content has not been changed for this PR.

Version(s): 4.17+

Issue: https://issues.redhat.com/browse/OSDOCS-11002

Link to docs preview:
- [Installing the hosted control planes command-line interface](https://81080--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-prepare/hcp-cli.html)
- [Installing the hosted control planes command-line interface by using the CLI](https://81080--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-prepare/hcp-cli.html#hcp-cli-terminal_hcp-cli)
- [Installing the hosted control planes command-line interface by using the web console](https://81080--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-prepare/hcp-cli.html#hcp-cli-console_hcp-cli)
- [Installing the hosted control planes command-line interface by using the gateway](https://81080--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-prepare/hcp-cli.html#hcp-cli-gateway_hcp-cli)

QE review:

- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@xenolinux Was this content already removed from the other docset? Otherwise, it might be good to link to live docs for merge review since you do not have QE or SME ack on this.

**Comment by xenolinux** [comment]
> @xenolinux Was this content already removed from the other docset? Otherwise, it might be good to link to live docs for merge review since you do not have QE or SME ack on this.

@ShaunaDiaz This PR has a QE approval

**Pull request merged**
