### PR TITLE
Issue-6563 Release Notes Corrections

### PR DESCRIPTION
**Pull request by bmcelvee**
https://github.com/openshift/openshift-docs/issues/6563#issuecomment-348207004

### CODE REVIEW

**Comment by bmcelvee** [comment]
@openshift/team-documentation please peer review 🦄

**Comment by vikram-redhat** [comment]
@bmcelvee lgtm.

**Comment by vikram-redhat** [comment]
@bmcelvee - CP it to the 3.7 stage branch straight away. I will publish it straight away.

**Comment by bmcelvee** [comment]
Thanks, @vikram-redhat!

**Pull request merged**
