### PR TITLE
PR for SRVLOGIC-401: Added additional resources section in the kn workflow plugin installation guide. 

### PR DESCRIPTION
**Pull request by kaldesai**
**Affecting version:** 
- `serverless-docs-1.35`
- `serverless-docs-1.34`
- `serverless-docs-1.33`

**Tracking JIRAs:** https://issues.redhat.com/browse/SRVLOGIC-401

**Doc previews:** [Installing the OpenShift Serverless Logic Knative Workflow plugin](https://85570--ocpdocs-pr.netlify.app/openshift-serverless/latest/install/serverless-logic-install-kn-workflow-plugin-cli.html#serverless-logic-install-kn-workflow-binary-file-linux_serverless-logic-install-kn-workflow-plugin-cli)

### CODE REVIEW

**Review by domhanak — CHANGES_REQUESTED** [review]
This does not solve the issue, when I open the doc I start from top of it and follow it. Adding an additional resource does not help here.

The link should be for example here:
image

Sugestion:
You have installed the Knative ([kn](https://docs.openshift.com/serverless/1.30/install/installing-kn.html)) command-line interface (CLI).

I click the KN and it takes me to the guide I am supposed to do as prerequisite, without the need of scrolling to bottom.

**Comment by kaldesai** [comment]
@domhanak I have added the link wherever applicable. Can you please take a look and verify?

**Review by domhanak — APPROVED** [review]
Thanks

**Review by xenolinux — COMMENTED** [review]
LGTM

**Review by wmedvede — CHANGES_REQUESTED** [review]

**Review by ricardozanini — COMMENTED** [review]
I'm ok with this change once @wmedvede comments are incorporated.

**Comment by kaldesai** [comment]
@wmedvede @ricardozanini I have incorporated the changes. Can you please approve the PR?

**Comment by wmedvede** [comment]
@kaldesai I  think we are missing one of the suggested changes
Screenshot from 2024-11-29 08-51-27

**Comment by domhanak** [comment]
@wmedvede You latest comment does not seem right. Check the steps, in step 3 we tell them to rename to `kn-workflow` and not move. So it should stay as is imho.

**Review by domhanak — CHANGES_REQUESTED** [review]
image

Step 4a tells user to make the binary executable `chmod +x /usr/local/bin/kn-workflow`
but user never moved the binary file. That is only suggest in step 4b. So the previous `<path/to/downloaded/kn-workflow> ` seems correct to me.


Any reason for mixing multiple fixes in one PR?

**Comment by domhanak** [comment]
Also consider that I already did the review and approved, the fact I noticed there are updates here is just me being vigilant. This is not OK, if such things happen make sure you rerequest review from QE explicitly again. Thanks.

**Comment by wmedvede** [comment]
@domhanak I think the "origia

> @kaldesai I think we are missing one of the suggested changes Screenshot from 2024-11-29 08-51-27
> 
> goes both for macOs and linux

@domhanak I think the original layout was wrong, so this is why I suggested the change.

And now, after your comment, and looking at the section where we install by taking the binary from the images, to make the hole comment consistent, what we need to do is to change the order and keep all aligned to what we have for the images case.

see:

image


we first copy or move, and then, we change the access right.

**Comment by wmedvede** [comment]
@kaldesai Is this repository available for me to make PRs?

**Comment by wmedvede** [comment]
> Also consider that I already did the review and approved, the fact I noticed there are updates here is just me being vigilant. This is not OK, if such things happen make sure you rerequest review from QE explicitly again. Thanks.

Sorry, but if something is not good, we must fix, independently if you gave a +1. This is why we have many reviewers involved.

**Comment by kaldesai** [comment]
@wmedvede @domhanak 
What is the correct way now? Should I re-do my changes?

**Comment by kaldesai** [comment]
> @kaldesai Is this repository available for me to make PRs?

@wmedvede I will have to check and let you know. But if you have any suggestions we can always create a JIRA and create another PR for the same.

**Comment by domhanak** [comment]
> > Also consider that I already did the review and approved, the fact I noticed there are updates here is just me being vigilant. This is not OK, if such things happen make sure you rerequest review from QE explicitly again. Thanks.
> 
> Sorry, but if something is not good, we must fix, independently if you gave a +1. This is why we have many reviewers involved.

Sure thing, we should fix it, but scope of this PR is clear enough, https://issues.redhat.com/browse/SRVLOGIC-401 mixing extra fixes into it, just creates confusion, prolongs the solution of the original issues, requires extra unplanned work and we also can't track why we did these updates easily in the future.

@wmedvede the procedure is like this because when we tested it last time, also during test day for 1.35.0; it made the most sense. not sure changing it again is worth the time and provides value.

**Comment by domhanak** [comment]
@kaldesai Walter's changes are OK, we clarified the confusion on a quick call :) I think we can incorporate this here, I ll update the original JIRA to also include this update request.  

Current shape is good.

**Review by domhanak — APPROVED** [review]

**Comment by kaldesai** [comment]
@domhanak @wmedvede 
I have incorporated your original changes. Walter cleared the confusion and explained to me on a quick call :) For the content refinement I will create another JIRA and another PR. 

Thank you so much! :)

**Review by wmedvede — APPROVED** [review]

**Comment by xenolinux** [comment]
@kaldesai We have some conflicts that need to be resolved in order to merge. Can you PTAL? Once reoslved and build checks pass, I will go ahead and merge the PR.

**Review by xenolinux — COMMENTED** [review]
Conflicts are resolved; build passed

Merging...

**Pull request merged**
