### PR TITLE
OCPBUGS-7083: Updated Prism Central link

### PR DESCRIPTION
**Pull request by dfitzmau**
[OCPBUGS-7083](https://issues.redhat.com/browse/OCPBUGS-7083)

Version(s):
4.12 & 4.11
(mpytlak: This work also applies to 4.13. See last comment).

Issue:
(https://issues.redhat.com/browse/OCPBUGS-7083)

Link to docs preview: [Internet access for Prism Central](https://55631--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-nutanix-installer-provisioned.html#cluster-entitlements_installing-nutanix-installer-provisioned)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sgaoshang** [comment]
@dfitzmau /lgtm, thanks.

**Comment by mjpytlak** [comment]
@dfitzmau FYI. This applies to all supported versions of the Nutanix doc (4.11+).

**Pull request merged**
