### PR TITLE
BZ#1842937 Do not favor vShere storage provisioning type

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1842937

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma can you confirm? Thanks!

**Comment by jinyunma** [comment]
From function test, I installed ocp4.4 where vm's storage type is "Thick Provision Lazy Zeroed", it works well without any error.
so it looks good to me.

**Comment by jinyunma** [comment]
From function test, I installed ocp4.4 where vm's storage type is "Thick Provision Lazy Zeroed", it works well without any error.
so it looks good to me.

**Comment by jinyunma** [comment]
From function test, I installed ocp4.4 where vm's storage type is "Thick Provision Lazy Zeroed", it works well without any error.
so it looks good to me.

**Comment by jinyunma** [comment]
From function test, I installed ocp4.4 where vm's storage type is "Thick Provision Lazy Zeroed", it works well without any error.
so it looks good to me.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
