### PR TITLE
MIG-1300: fix error in MTC workflow sample use case

### PR DESCRIPTION
**Pull request by RichardHoch**
MTC 1.7.7 , OCP 4.9+

Resolves https://issues.redhat.com/browse/MIG-1300 by correcting the text in a sample user case.

Preview: https://55466--docspreview.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/about-mtc.html#migration-mtc-workflow_about-mtc  Paragraph beginning "For example..."

### CODE REVIEW

**Comment by RichardHoch** [comment]
@stillalearner please review

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by RichardHoch** [comment]
Very small change. Passed QE. GA is next Thursday; doc freeze is today. This was assigned a few hours ago, so if we can get it into the next release, that would be great. Thanks.

**Comment by RichardHoch** [comment]
/label OADP
/label peer-review-needed

Very small change. Passed QE. GA is on Thursday. This was assigned and ready two business days ago but I messed up the labels. If we can get it into the next release, that would be great. Thanks.

**Pull request merged**
