### PR TITLE
Adding `namespace: openshift-logging` to log forward CR

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-1541
https://bugzilla.redhat.com/show_bug.cgi?id=1884275
Private slack: https://coreos.slack.com/archives/CB3HXM2QK/p1601561892206500

### CODE REVIEW

**Comment by mburke5678** [comment]
@alanconway I added the namespace requirement back to the docs. The changes that concern you are the new lines in each CR example. The other changes are from bumping the call-out numbers.
```
namespace: openshift-logging <2>
```
<2> The namespace for the log forwarding CR must be `openshift-logging`
```

**Review by alanconway — APPROVED** [review]
All good.

**Comment by mburke5678** [comment]
@anping Please take a look? 
Alan is bringing back namespace scoping for Log Forwarding GA. As a result, I added back the requirement for the `namespace: openshift-logging` parameter back to the CR examples. 
Can you verify that those new lines in each CR example looks OK? The other changes are from bumping the call-out numbers.
```
namespace: openshift-logging <2>
```
```
<2> The namespace for the log forwarding CR must be `openshift-logging`
```

**Review by gkarager — COMMENTED** [review]
LGTM

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
