### PR TITLE
GH42366: Wrong command flag in Verifying node health section

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/42366

Preview: [Reviewing node status, resource usage, and configuration](https://deploy-preview-42778--osdocs.netlify.app/openshift-enterprise/latest/support/troubleshooting/verifying-node-health.html#reviewing-node-status-use-and-configuration_verifying-node-health)

### CODE REVIEW

**Comment by mburke5678** [comment]
@lmurthyrh Can you help with a QE resource for this PR? Thank you.

**Comment by lmurthyrh** [comment]
@mburke5678 - Please check with  schoudha@redhat.com for QE review

**Comment by mburke5678** [comment]
@sunilcio Can you verify [this one-character change](schoudha@redhat.com)? The other changes in the file are purely editorial.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM. Please standby for merge review.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too!

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
