### PR TITLE
BZ#1913242 Add link to compatibility matrix in the RHV install prerequisites

### PR DESCRIPTION
**Pull request by emarcusRH**
https://bugzilla.redhat.com/show_bug.cgi?id=1913242
enterprise-4.9
could also be back-ported to enterprise-4.8 or to any recent version that customers are actively using

added link for [compatibility matrix](https://access.redhat.com/articles/5485861) in the Prerequisites for chapters:
[Preparing to Install on RHV](https://deploy-preview-37288--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/preparing-to-install-on-rhv.html)
[Installing a cluster on RHV with customizations](https://docs.openshift.com/container-platform/4.7/installing/installing_rhv/installing-rhv-customizations.html) 
[Installing a Cluster quickly on RHV](https://docs.openshift.com/container-platform/4.7/installing/installing_rhv/installing-rhv-default.html#prerequisites)

### CODE REVIEW

**Comment by emarcusRH** [comment]
Michael Burman 2021-10-19 07:28:35 UTC

(In reply to Eli Marcus from comment #4)
> received ack/lgtm from Gal Z. 
> needs QE ack 
> and then final peer review from OCP peer review team

ack from QE, thanks

**Review by michaelryanpeter — COMMENTED** [review]
Thank you for your patience. Just a couple of small notes. 

-  Please add the BZ# to the title of your PR.
-  Please add the enterprise branches you need this picked to in the first comment.

**Pull request merged**
