### PR TITLE
[OSDOCS-10957]:Remove information pertaining to https://issues.redhat.com/browse/OSDOCS-10434

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10957
Link to docs preview:

https://77668--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/osd-limits-scalability.html#node-sizing-during-installation_osd-limits-scalability
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by mletalie** [comment]
Thanks @EricPonvelle!!

**Pull request merged**
