### PR TITLE
Fix wrong indention in master config to enable feature gates

### PR DESCRIPTION
**Pull request by liangxia**
https://bugzilla.redhat.com/show_bug.cgi?id=1659337

@openshift/team-documentation 

Applies to enterprise-3.9 and above.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, the proposed change is valid yaml, and @liangxia is one of the storage QEs. If no one objects, I'm going to merge this change.

**Comment by mburke5678** [comment]
@liangxia Can you comment on this PR: https://github.com/openshift/openshift-docs/pull/13104 to remove the steps on configuration of nodes for Feature Gates in the Expanding Persistent Volumes topic?

**Comment by liangxia** [comment]
Verified the change on OCP v3.9.58 and v3.9.59, it works.

```shell
[root@preserve-qe-lxia-39-master-etcd-1 ~]# openshift version ; grep -A 6 apiServer /etc/origin/master/master-config.yaml ; systemctl restart atomic-openshift-master-api ; echo $?
openshift v3.9.59
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
  apiServerArguments:
    feature-gates:
    - ExpandPersistentVolumes=true
    cloud-config:
    - /etc/origin/cloudprovider/openstack.conf
    cloud-provider:
    - openstack
0
```

**Comment by mburke5678** [comment]
The change matches what is in the [approved PR for the feature gates feature](https://github.com/openshift/openshift-docs/pull/8654/files). Merging.

**Pull request merged**
