### PR TITLE
RHDEVDOCS-3598: Temporarily comment out some sections of odo docs

### PR DESCRIPTION
**Pull request by gabriel-rh**
4.6+

[RHDEVDOCS-3598](https://issues.redhat.com/browse/RHDEVDOCS-3598)

[Netlify preview](https://deploy-preview-41412--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/odo-release-notes.html)

@kadel @Preeticp

### CODE REVIEW

**Comment by bburt-rh** [comment]
lgtm

**Comment by Preeticp** [comment]
@gabriel-rh I suggest we retain the Understanding section and the related Xrefs from the main OpenShift pages as the section has relatively few updates and it is a way for getting eyes on odo, otherwise odo will not be mentioned on the Index page at all. The only alternative to the latter that I can see is linking it to the Installation page instead.

**Comment by Preeticp** [comment]
@dharmit @kadel can one of you take a look at this PR and provide an LGTM if this looks good? We will also need to send a mail informing all the stakeholders. Details are mentioned in the related Jira.

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Review by kadel — APPROVED** [review]

**Comment by Preeticp** [comment]
Hi @gabriel-rh this looks great to me. Two things: 
1. I have one request that is not part of this PR but it is about adding two letters to correct something that is wrong, hence my ask. [The title here](https://deploy-preview-41412--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/configuring-the-odo-cli.html#developer-cli-odo-unset-config_configuring-the-odo-cli) needs to be changed from Setting...to Unsetting...

2. A question, I see the [Telemetry section](https://deploy-preview-41412--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/understanding-odo.html#odo-telemetry_understanding-odo) is quiet up to date, so can we consider[ this Jira ](https://issues.redhat.com/browse/RHDEVDOCS-3592)to be done as well?

**Pull request merged**
