### PR TITLE
BZ2033142 update for image information

### PR DESCRIPTION
**Pull request by cowgirljessi**
https://bugzilla.redhat.com/show_bug.cgi?id=2033142

Version 4.9+

@juzhao QE check please

preview link: https://deploy-preview-41074--osdocs.netlify.app/openshift-enterprise/latest/monitoring/managing-metrics.html#deploying-a-sample-service_managing-metrics

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by cowgirljessi** [comment]
@juzhao  QE check please

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
