### PR TITLE
GH#43284: Typo fix

### PR DESCRIPTION
**Pull request by bobfuru**
Fixes small typo as reported in https://github.com/openshift/openshift-docs/issues/43284

Preview: https://51359--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-identity-access-management_rosa-policy-responsibility-matrix

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@pneedle-rh @EricPonvelle Can you help me with how far back we're picking changes for ROSA? is it 4.10+?

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by EricPonvelle** [comment]
@bergerhoffer - we only build off of the current GA, so 4.11+ would work! Thanks for this.

**Comment by bergerhoffer** [comment]
Thanks @EricPonvelle!

Merging this in

**Pull request merged**
