### PR TITLE
Included reference to image configuration

### PR DESCRIPTION
**Pull request by ghost**
@ghyde Please review. This is a follow-up to https://github.com/openshift/openshift-docs/pull/5374.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by ghyde** [comment]
@tmorriso-rh LGTM

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Comment by vikram-redhat** [comment]
@tmorriso-rh - is this ready for merging into 3.5 to 3.9 branches?

**Comment by tmorriso-rh** [comment]
@vikram-redhat Yes, this needs to be merged to 3.5 - 3.9.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - cool - did you want to go ahead and do it? I expect there will be a conflict, so did you want to try doing it on the command line and we can do it in a live session?

**Pull request merged**
