### PR TITLE
resource presentation not as a List

### PR DESCRIPTION
**Pull request by duritong**
Showing single elements as a List kind is just confusing and does not bring any values.

Version(s):

Issue:

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@duritong you are requesting to merge into the individual 4.15 branch, does this change apply to other versions? if so, this PR needs to be merged into the `main` branch so we can cherrypick to the appropriate OCP docs versions this change applies to

**Review by jldohmann — COMMENTED** [review]
Content changes look good to me. @lihongan could you PTAL for QE ack? thank you!

**Comment by lihongan** [comment]
It looks good to me. Thank you!

**Review by ousleyp — COMMENTED** [review]
Your changes LGTM! I'll go ahead and merge this.

**Pull request merged**
