### PR TITLE
Bug 1296199, added comprehensive list of events

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1296199

Continues work from https://github.com/openshift/openshift-docs/pull/2235

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@pweil- PTAL. Thanks!

**Comment by ahardin-rh** [comment]
@pweil- Thoughts?

**Comment by pweil-** [comment]
@ahardin-rh the file looks fine to me.  I'm still not convinced that the cost of maintaining this list is worth it.  The descriptions don't give any more information than the event itself and since the events aren't part of the api contract I'm not sure what this would be used for by an end user.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/events.adoc#dev-guide-events[Events]
|Added a xref:../dev_guide/events.adoc#events-reference[comprehensive list of events].
%

**Pull request merged**
