### PR TITLE
Remove extra step for removing an additional network

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-872
- https://bugzilla.redhat.com/show_bug.cgi?id=1755908

### CODE REVIEW

**Comment by jboxman** [comment]
@weliang1, based on your comment in bz-1755908, can I remove the step to manually delete the `NetworkAttachmentDefinition`?

Thanks.

**Comment by weliang1** [comment]
@jboxman No manual deleting steps needed in latest code

**Comment by jboxman** [comment]
@weliang1, thanks!

**Pull request merged**
