### PR TITLE
[OSDOCS-6793] Remove 4.13-specific failure domains content for ShiftStack

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR addresses [OSDOCS-6793](https://issues.redhat.com//browse/OSDOCS-6793).

Version(s): 4.14

Issue: [OSDOCS-6793](https://issues.redhat.com//browse/OSDOCS-6793)

Link to docs preview: https://62110--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-configuration-parameters-additional-osp_installing-openstack-installer-custom

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by pierreprinetti** [comment]
LGTM

**Comment by kalexand-rh** [comment]
@rlobillo, will you PTAL?

**Comment by eurijon** [comment]
lgtm (@rlobillo is on PTO)

**Review by skopacz1 — APPROVED** [review]
LGTM! Please wait until @adellape approves my review before proceeding.

**Review by adellape — APPROVED** [review]
@skopacz1 @kalexand-rh Peer review changes LGTM 👍

**Pull request merged**
