### PR TITLE
[enterprise-4.9] Add known issue about vSphere, TANG, and OVN-Kubernetes

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=2006756

Preview: https://deploy-preview-37423--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes#ocp-4-9-known-issues

### CODE REVIEW

**Comment by jboxman** [comment]
Looks like https://github.com/openshift/openshift-docs/pull/37500 addresses this.

**Comment by jboxman** [comment]
@zhaozhanqi, does this make sense for the 4.9 known issues? Thanks!

**Review by jeana-redhat — COMMENTED** [review]
Very small suggestion for peer review. If you can get this rebased I will approve merge for 4.9.

**Comment by jboxman** [comment]
@jeana-redhat thanks!

**Comment by vikram-redhat** [comment]
After discussing this in detail with @xltian we have decided to not document this known issue. This issue has only come about for a very specific support exception and the support exception scenario is also not documented in the product docs (it's a very specific scenario).

I am closing this PR.

@jeana-redhat @jboxman @sjstout FYI

**Pull request closed without merging**
