### PR TITLE
OSDOCS-4736: Changed the language for Encrypted-at-rest

### PR DESCRIPTION
**Pull request by EricPonvelle**
Version(s):
Enterprise-4.11+

Issue:
[OSDOCS-4736](https://issues.redhat.com/browse/OSDOCS-4736)

Link to docs preview:
- [ROSA service definition change](https://54274--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-encrytpted-at-rest-storage_rosa-service-definition)
- [Data management change](https://54274--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security.html#rosa-policy-data-management_rosa-policy-process-security) 

QE review:
- [ ] QE has approved this change.

Additional information:
Changed the language around encrypted-at-rest OS storage

### CODE REVIEW

**Comment by EricPonvelle** [comment]
@bysnupy and @xueli181114 may I get a review of this PR?

**Comment by bysnupy** [comment]
@EricPonvelle I'm sorry for late response. It looks good for me.

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
