### PR TITLE
BZ2081804:Update CSI architecture diagram

### PR DESCRIPTION
**Pull request by lpettyjo**
BZ2081804:Update CSI architecture diagram

Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2081804

Link to docs preview: http://file.rdu.redhat.com/lpettyjo/BZ2081804/storage/container_storage_interface/persistent-storage-csi.html#persistent-storage-csi-architecture_persistent-storage-csi

Additional information:

PTAL: @jsafrane, @gcharot, @duanwei33

### CODE REVIEW

**Comment by gcharot** [comment]
We need a one liner for Resizer / Snapshotter like we have for other components

**Comment by lpettyjo** [comment]
@gcharot threw some verbiage in for that. PTAL.

**Pull request merged**
