### PR TITLE
OCPBUGS-31295: fixed typo

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-31295

Link to docs preview:
[Setting up Topology Manager](https://file.rdu.redhat.com/antaylor/OCPBUGS-31295/scalability_and_performance/using-cpu-manager.html#setting_up_topology_manager_using-cpu-manager-and-topology_manager)

### CODE REVIEW

**Comment by mramendi** [comment]
LGTM for peer review, looks straightforward. But as I am on peer review induction, @JoeAldinger will finish this review

**Comment by JoeAldinger** [comment]
Let

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
