### PR TITLE
Update references to registry.access.redhat.com to registry.redhat.io

### PR DESCRIPTION
**Pull request by bmcelvee**
Related to: https://github.com/openshift/openshift-docs/pull/11506

Will need to follow up on references to registry.redhat.io in Online, Dedicated, and OKD.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@openshift/team-documentation - please be aware of this change that is coming in for 3.11.

**Comment by kalexand-rh** [comment]
@bmcelvee, there will likely be conflicts with some of the install topics. Do you want me to make the swap in the files that I'm changing to reduce the number of merge conflicts?

**Comment by bmcelvee** [comment]
@kalexand-rh sure! I can make any adjustments needed to this PR too. I wanted to get an idea of how large-scale of a change this is going to be.

**Comment by bmcelvee** [comment]
@wenjing when you get a chance, please take a look at this PR as well.

Thanks!

**Comment by bmcelvee** [comment]
@openshift/team-documentation Do you know if the registry location needs to change in the servicemesh topics? 

Otherwise, if this looks okay to you all I would like to get it merged before the weekend. 

Thanks! :maple_leaf:

**Comment by kalexand-rh** [comment]
@jsticker, do you know if the registry location needs to change in the servicemesh topics?

**Review by kalexand-rh — COMMENTED** [review]
You got all the instances in the disconnected install topic, so it LGTM!

**Comment by bmcelvee** [comment]
@vikram-redhat This PR has not yet been reviewed by QE, but I would really like to get it merged today. Since it's just changing the URL, I will merge it and add the to_followup label. That way if there are any issues that pop up by Monday or Tuesday, I can revert the PR or open a follow-up. 

@JStickler If the registry location needs to change for the servicemesh topics, I will open a PR. 

Thanks! :fallen_leaf:

**Comment by bmcelvee** [comment]
Hi again @wenjing, if you get a chance PTAL.

Thanks!

**Pull request merged**
