### PR TITLE
 OCPBUGS#6790: Change the control plane machine sets

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-6790

Link to docs preview: https://57094--docspreview.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-about.html#cpmso-limitations_cpmso-about

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Putting a hold on this because I am not sure this is really the right approach to resolve this bug. Will follow up in Jira.

/remove-label peer-review-in-progress
/remove-label peer-review-needed

**Review by sheriff-rh — APPROVED** [review]
LGTM! Merging.

**Pull request merged**
