### PR TITLE
 removes word repetition

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.6 and above versions
- Does not require QE/SME
- [Issue](https://github.com/openshift/openshift-docs/issues/49431)
- [Preview](url)

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by kalexand-rh** [comment]
This looks like a duplicate of https://github.com/openshift/openshift-docs/pull/51170.

**Comment by Amrita42** [comment]
yes good catch @kalexand-rh  we can close this.

**Pull request closed without merging**
