### PR TITLE
fixing links and module locations

### PR DESCRIPTION
**Pull request by kalexand-rh**
Cleaning up links between assemblies, extra modules, and "module included in" statements for the installation content.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, will someone please scan over this change? It's mostly uncommenting xrefs and adding the "used in z assemblies" notes for modules that I neglected in the rush for freeze. (It's large but not too involved.)

**Comment by jboxman** [comment]
lgtm

**Comment by kalexand-rh** [comment]
Thanks Jason! Merging.

**Pull request merged**
