### PR TITLE
OADP-3341: quick formatting fix in oadp-installing-dpa-1-3.adoc

### PR DESCRIPTION
**Pull request by anarnold97**
### Jira

* [OADP-3341](https://issues.redhat.com/browse/OADP-3341)

### OCP version

* OCP 4.15 → branch/enterprise-4.15

### Preview

* [Verifying the installation](https://70151--ocpdocs-pr.netlify.app//openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws#verifying-oadp-installation-1-2_installing-oadp-aws)

### QE review

I do not think QE review is required as it is two small formatting errors

### CODE REVIEW

**Comment by bscott-rh** [comment]
merge review LGTM

**Comment by anarnold97** [comment]
@bscott-rh - thanks, looks like this has been fixed in another PR

I ran a diff-check and the only difference is that there is an extra blank line at the bottom of the doc

Again, thanks

**Pull request merged**
