### PR TITLE
[OCPBUGS-30752] Change conditionals to ifdef

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.15
If backporting can be done without too much effort by 🍒 should be applied to 4.13 and 4.14 

Issue: 
- https://issues.redhat.com/browse/OCPBUGS-30752

Link to docs preview:
- https://72935--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-lpar#installation-bare-metal-config-yaml_installing-ibm-z-lpar (same for z/VM and KVM) 
- https://72935--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power#installation-bare-metal-config-yaml_installing-ibm-power

QE review:
- [NA] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Comment by ShaunaDiaz** [comment]
@SNiemann15 the automated CPs to 4.13 and 4.14 failed; you are welcome to make manual picks and put them back for merge.

**Pull request merged**
