### PR TITLE
correction in doc for logging installation in OCP v4.1

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1731972

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli Please take a look

**Review by anpingli — APPROVED** [review]
Revert LGTM

**Comment by anpingli** [comment]
Asmita thought the section is output. In fact, it is not. It is a resource file. in a pure resource, there should not be status filed. Could we ark Asmita to confirm?

Example Subscription
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: "elasticsearch-"
  namespace: "openshift-operators-redhat" (1)
spec:
  channel: "preview" (2)
  installPlanApproval: "Automatic"
  source: "elasticsearch"
  sourceNamespace: "openshift-operators-redhat" (1)
  name: "elasticsearch-operator"
status:
  currentCSV: elasticsearch-operator.4.1.4-20190621212 (3)

**Comment by mburke5678** [comment]
DO NOT MERGE TO MASTER. After getting the change approved, create new PR against 4.1 and merge directly to 4.1.

**Comment by mburke5678** [comment]
Closing in favor ot https://github.com/openshift/openshift-docs/pull/16025

**Pull request closed without merging**
