### PR TITLE
Windows node failed to become ready after a while (trunk port limitation)

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OCPBUGS-4285

Adding Known Limitation in https://github.com/openshift/windows-machine-config-operator/pull/1338

Preview: WINC Release Notes -> [Known Limitations](https://53341--docspreview.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-6-x.html#windows-containers-release-notes-limitations_windows-containers-release-notes)

### CODE REVIEW

**Comment by mburke5678** [comment]
@mansikulkarni96 PTAL

**Comment by mansikulkarni96** [comment]
Thanks for adding this @mburke5678 
/lgtm

**Review by jfrancoa — COMMENTED** [review]
/lgtm

**Review by adellape — APPROVED** [review]

**Pull request merged**
