### PR TITLE
Fix OSD LoadBalancer internal-only command

### PR DESCRIPTION
**Pull request by wgordon17**
@sheriff-rh Can I get this merged please 🙏

### CODE REVIEW

**Comment by maxwelldb** [comment]
@sheriff-rh I'm merging this after discussion with Will. Could you verify that it's all good when you have a moment?

**Comment by wgordon17** [comment]
@sheriff-rh It looks like change was introduced by this issue: #18268 

The issue incorrectly used the `azure` annotation. However the implication that we should be using `"true"` instead of `0.0.0.0/0` seems valid based on [K8s docs](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer) (AWS tab). I have tested this with `0.0.0.0/0` and it seems that it still works with this value, this is likely something that is or will be deprecated by K8s at some point. Please update this to use `"true"` at some point to ensure we're inline with upstream K8s.

So it would look like 

```bash
$ oc expose dc httpd-example --type=LoadBalancer --name=internal-lb --dry-run -o yaml | awk '1;/metadata:/{ print "  annotations:\n    service.beta.kubernetes.io/aws-load-balancer-internal: \"true\"" }' | oc create -f -
service/internal-lb created
```

**Pull request merged**
