### PR TITLE
OLS-915 change customer resource file to custom resource file

### PR DESCRIPTION
**Pull request by rh-tokeefe**
This PR is part of the standalone doc set for the OpenShift Lightspeed project. Kathryn is aware that this content applies for a product that is not officially released yet.  The project is seeking feedback from early adopters. 

Versions: Tech Preview

PRs get merged to https://github.com/openshift/openshift-docs/tree/lightspeed-docs-main

And cherry picked to https://github.com/openshift/openshift-docs/tree/lightspeed-docs-1.0tp1

Version(s): Tech Preview

Issue: https://issues.redhat.com/browse/OLS-915

Link to docs preview: 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@JoaoFula please review when you have time. Thank you.

**Comment by JoaoFula** [comment]
LGTM

**Review by bhardesty — COMMENTED** [review]
LGTM!

**Pull request merged**
