### PR TITLE
Spelling and Grammar fixes

### PR DESCRIPTION
**Pull request by brian-avery**
This fixes a few instances of repeated words and spelling errors in the OpenShift docs.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@vikram-redhat Usually we do want to cherry pick all the way back to 4.4 for the typos that apply. Do you want me to take care of the conflicts here?

**Comment by vikram-redhat** [comment]
> @vikram-redhat Usually we do want to cherry pick all the way back to 4.4 for the typos that apply. Do you want me to take care of the conflicts here?

Yes - thanks @bergerhoffer!

**Comment by bergerhoffer** [comment]
@vikram-redhat done

**Pull request merged**
