### PR TITLE
Fix feature gate/set conflation

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11+

Issue:
N/A, reported via [Slack](https://redhat-internal.slack.com/archives/GE2HQ9QP4/p1687880610882739?thread_ts=1687877622.019489&cid=GE2HQ9QP4)

Link to docs preview:
:construction: [Limitations](https://61878--docspreview.netlify.app/openshift-enterprise/latest/machine_management/capi-machine-management.html#capi-tech-preview-limitations)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
lgtm

**Comment by jeana-redhat** [comment]
@sunzhaohua2 can you PTAL at this (or tag someone in your place)? :)

**Comment by stevsmit** [comment]
@jeana-redhat This LGTM, but the preview is borked (hence the caution flag I reckon?)

**Comment by jeana-redhat** [comment]
@stevsmit ty - I think this was submitted when Netlify was messed up, I'll refresh the PR to make sure the build is happy before merging :)

**Pull request merged**
