### PR TITLE
GitHub-26681: Noted new flag for JDK 11+

### LINKED ISSUE #26681: memory settings for jdk11+ on openshift
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/master/modules/nodes-cluster-resource-configure-jdk.adoc

### What needs fixing?

In java 11; they dropped the "UseCGroupMemoryLimitForHeap" and have added "UseContainerSupport"

See for more details.
https://www.eclipse.org/openj9/docs/xxusecontainersupport/

The docs page should be updated to make note of the new flag

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #26681

Preview: https://deploy-preview-30784--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-resource-configure.html#nodes-cluster-resource-configure-jdk-heap_nodes-cluster-resource-configure

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@sunilcio Can you please QE review this? Or let me know if there is someone else that I should ask? Thanks!

Preview: https://deploy-preview-30784--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-resource-configure.html#nodes-cluster-resource-configure-jdk-heap_nodes-cluster-resource-configure

**Comment by sunilcio** [comment]
@bergerhoffer missed this one earlier. It looks this would require review from OpenJDK team. @wsun1 do you know who can help review this one?

**Comment by sunilcio** [comment]
Okay, after reviewing below links, this LGTM.
https://access.redhat.com/solutions/4564491
https://www.eclipse.org/openj9/docs/xxusecontainersupport
https://bugs.openjdk.java.net/browse/JDK-8250627

**Pull request merged**
