### PR TITLE
Add ovn-k8s migration egress router section

### PR DESCRIPTION
**Pull request by jboxman**
So this was deleted somehow.

### CODE REVIEW

**Comment by jboxman** [comment]
@mikemckiernan, do we know if egress router is GA in 4.8?

**Comment by mikemckiernan** [comment]
Hi Jason, the name of the story for 4.8 is Uploaded image for project: SDN-1113 OVN Egress Router Improvements: GA.

If that isn't trustworthy...dunno what to say.  I guess I can poke the ticket for conformation that the GA part is still valid.

Regarding this update, if ER was TP for 4.7 does that still mean it is not supported?  Put another way, is it that GA means supported and anything else is unsupported?

**Comment by jboxman** [comment]
@mikemckiernan, oh, then that was an irrelevant question.

I don't think someone migrating to ovn-k8s can reasonably rely on an incomplete TP feature, so I'd consider that unsupported for < 4.8.

**Pull request merged**
