### PR TITLE
OSDOCS-8996: Add CDO deprecation note to Tutorial: Deploying the Exte…

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8996

Link to docs preview:
https://69091--docspreview.netlify.app/openshift-rosa/latest/cloud_experts_tutorials/cloud-experts-external-dns

QE review:
Adding existing note to tutorial. No new technical information. No QE review required. 

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/lgtm

**Comment by lihongan** [comment]
LGTM
thanks

**Pull request merged**
