### PR TITLE
fixed Typos in 3.11 #25828

### LINKED ISSUE #25828: Typos in 3.11
### What needs fixing?

The typos in this list of files in the `enterprise-3.11` branch:

| File  | Typo |
| ------------- | ------------- |
|release_notes/ocp_3_6_release_notes.adoc |Kublet (should be Kubelet)
|architecture/infrastructure_components/kubernetes_infrastructure.adoc |kublet (should be kubelet)
|dev_guide/topics/about_device_manager.adoc |Manger
|install_config/topics/ocp_osp_provisioning.adoc |file file
|servicemesh-install/topics/tutorial-rhoar-missions.adoc |are are
|servicemesh-release-notes/topics/rn-known-issues.adoc | it it (should be it is)
|servicemesh-release-notes/topics/rn-new-features.adoc |and and
|install_config/master_node_configuration.adoc |commmand
|dev_guide/managing_images.adoc | `importPolicy.insecure`` (extra ending backtick)
|install_config/router/customized_haproxy_router.adoc | `map\[string](ServiceAliasConfig)`` (extra ending backtick)
|install_config/router/customized_haproxy_router.adoc | ``[]Endpoint`  (extra beginning backtick)
|install_config/router/customized_haproxy_router.adoc | ``$cfg` (extra beginning backtick)
|install_config/router/customized_haproxy_router.adoc |``$balanceAlgo`   (extra beginning backtick)
|install_config/aggregate_logging.adoc | enviroment

Marking this as a good issue for Hacktoberfest!

### PR DESCRIPTION
**Pull request by amycruz97**
Fixed all typos in issues #25828

### CODE REVIEW

**Comment by vikram-redhat** [comment]
This looks good to me @amycruz97! Thanks for submitting. @bergerhoffer if you are happy with it, please confirm and merge.

**Comment by bergerhoffer** [comment]
@amycruz97 The changes look great, thank you for submitting this!

The only thing that needs done before we can merge is to squash the commits so that there is only 1 commit (there are currently 2). Feel free to reach out if you need help on how to do this.

**Comment by amycruz97** [comment]
Thanks how do i squash the commits

**Comment by bergerhoffer** [comment]
Hi @amycruz97, you can find some detailed instructions here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes

But I've outlined the steps below:

1. In your branch in your terminal, use this command to squash your 2 commits into 1:
```
$  git rebase -i HEAD~2
```

2. In the file that pops up, change the first word of the second line from "pick" to "squash", like below:
```
pick 22e337e40 fixed Typos in 3.11 #25828
squash 6b29ea568 fixed Typos in 3.11 #25828
```
3. Save and quit the file (if it's vim, enter `:wq`).

4. In the next file that pops up, you can remote the second commit message, like below

```
# This is a combination of 2 commits.
# This is the 1st commit message:

fixed Typos in 3.11 #25828

# This is the commit message #1:

fixed Typos in 3.11 #25828                                 <---- Remove this line
```

5. Save and quit the file (if it's vim, enter `:wq`).

6. Push the changes to this PR.

```
$ git push origin HEAD
```

Let me know if that works for you, or if you have any issues in squashing. Thanks!

**Comment by amycruz97** [comment]
The error i am getting

! [rejected]            HEAD -> enterprise-3.11 (non-fast-forward)
error: failed to push some refs to 'git@github.com:amycruz97/openshift-docs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by bergerhoffer** [comment]
@amycruz97 My apologies, you'll need to force the push to the PR, so the last command should be `git push -f origin HEAD`.

**Comment by amycruz97** [comment]
Done. Thanks for your assistant

**Comment by bergerhoffer** [comment]
Looks great. Thanks again! Merging.

**Pull request merged**
