### PR TITLE
OSDOCS-2190: Added note about known issue with AWS quota checker

### PR DESCRIPTION
**Pull request by jonquilwilliams**
JIRA: https://issues.redhat.com/browse/OSDOCS-2190

😎 Browse the preview: https://deploy-preview-32852--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-required-aws-service-quotas

Please merge to branch/dedicated. No milestones needed, it's iterative.

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
Minor nit. Otherwise LGTM. 

It's not completely clear from RH GS, but it looks like you should use "see" rather than "refer" when citing other content.

**Comment by mburke5678** [comment]
IBM Style Guide says to use _see_ instead of _refer to_. Otherwhise LGTM

**Pull request merged**
