### PR TITLE
Fix bz1444776. Table number change in ovs flows

### PR DESCRIPTION
**Pull request by rajatchopra**
@danwinship PTAL. Thanks.
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1444776

### CODE REVIEW

**Review by danwinship — APPROVED** [review]
ugh, we really ought to find a nicer way to do this

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
@rajatchopra @danwinship Looks like this is for OCP 3.5 docs only, correct?

**Review by knobunc — APPROVED** [review]
LGTM

**Comment by eparis** [comment]
yes only for 3.5 (and later)

**Comment by rajatchopra** [comment]
I made another PR to the 3.5 branch. But yes, only 3.5 and the tip.

**Comment by rajatchopra** [comment]
I made another PR to the 3.5 branch. But yes, only 3.5 and later.

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
