### PR TITLE
GH#44908: fix typo "usng --> using"

### PR DESCRIPTION
**Pull request by tonytheleg**
Version(s):

PR applies to versions 4.6 - 4.10

Issue:

For #44908

Link to docs preview:

QE review:
- [ ] QE has approved this change.

QE not required.

Additional information:

### CODE REVIEW

**Comment by tonytheleg** [comment]
@openshift/team-documentation please take a look when you can. Thanks!

**Review by bergerhoffer — COMMENTED** [review]
@tonytheleg Looks great, thanks again!

**Comment by bergerhoffer** [comment]
FYI @kalexand-rh I'm cherry picking from 4.10 back to 4.6. This has been fixed in main and 4.11+.

**Pull request merged**
