### PR TITLE
A tiny change in HCP release notes structure

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.17+

Issue: None

Link to docs preview: https://85317--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hosted-control-planes-release-notes.html

QE review: Not required. This is purely a structure change.

Additional information:

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
lgtm

**Review by max-cx — APPROVED** [review]
LGTM on the changes in the PR.

Global recommendations for future PRs about this page:

1.
From my personal experience with peer reviews for this repo, I was asked multiple times to include the `snippets/technology-preview.adoc` admonition on pages, preferably after the first paragraph (due to SEO) or further in the section.

2.
IBM Style guidance is to "use parentheses to identify items such as abbreviations, symbols, and measurements, but avoid using parentheses in general text." You might want to rethink use of parentheses in `(Technology Preview` in section heading.

3.
This page appears to have an inconsistent use of parentheses with TP/GA in new feature headings: TP is mentioned in parentheses, but GA is mentioned without parentheses. For example:

`Custom taints and tolerations (Technology Preview)`
versus
`Hosted control planes on OpenShift Virtualization in a disconnected environment is Generally Available`

4.
I'd recommend considering the splitting of your current "New features and enhancements" section into two sections:
`New features and enhancements`
and
`Technology Preview features`
See my example of how this can be done: https://docs.openshift.com/container-platform/4.14/observability/otel/otel-rn.html#otel_3-3_technology-preview-features_otel-rn
In this linked example, one common TP admonition is added for all of the TP features in the section:
```
:FeatureName: Each of these features
include::snippets/technology-preview.adoc[leveloffset=+1]
```

**Comment by xenolinux** [comment]
> LGTM on the changes in the PR.
> 
> Global recommendations for future PRs about this page:
> 
> 
> From my personal experience with peer reviews for this repo, I was asked multiple times to include the `snippets/technology-preview.adoc` admonition on pages, preferably after the first paragraph (due to SEO) or further in the section.
> 
> 
> IBM Style guidance is to "use parentheses to identify items such as abbreviations, symbols, and measurements, but avoid using parentheses in general text." You might want to rethink use of parentheses in `(Technology Preview` in section heading.
> 
> 
> This page appears to have an inconsistent use of parentheses with TP/GA in new feature headings: TP is mentioned in parentheses, but GA is mentioned without parentheses. For example:
> 
> `Custom taints and tolerations (Technology Preview)` versus `Hosted control planes on OpenShift Virtualization in a disconnected environment is Generally Available`
> 
> 
> I'd recommend considering the splitting of your current "New features and enhancements" section into two sections: `New features and enhancements` and `Technology Preview features` See my example of how this can be done: https://docs.openshift.com/container-platform/4.14/observability/otel/otel-rn.html#otel_3-3_technology-preview-features_otel-rn In this linked example, one common TP admonition is added for all of the TP features in the section:
> 
> ```
> :FeatureName: Each of these features
> include::snippets/technology-preview.adoc[leveloffset=+1]
> ```

Thank you. @max-cx I will consider these improvements to include in another (probably 4.18 RN) PR .

**Pull request merged**
