### PR TITLE
PR7788-Follow-up Minor Content Edits

### PR DESCRIPTION
**Pull request by bmcelvee**
https://github.com/openshift/openshift-docs/pull/7788

### CODE REVIEW

**Comment by bmcelvee** [comment]
Hi @wzheng1, would you mind taking a look at this PR? The original PR was opened by a developer from Developer Experience: https://github.com/openshift/openshift-docs/pull/7788. Thanks!

**Comment by wzheng1** [comment]
@dongboyan77 Could you please review? thanks!

**Comment by dongboyan77** [comment]
LGTM, thanks

**Comment by bmcelvee** [comment]
Thank you, @wzheng1 and @dongboyan77!

**Pull request merged**
