### PR TITLE
[enterprise-4.12] Add release note for new supported SR-IOV device

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-8954

Specifically for https://github.com/openshift/openshift-docs/pull/68971.

Version(s): 4.12 only

Issue:

Link to docs preview: https://69008--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes#ocp-4-12-networking-supported-hardware-for-sr-iov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@zhaozhanqi, this is the release note for 4.12.

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by ahardin-rh** [comment]
LGTM! Thank you!

**Pull request merged**
