### PR TITLE
correctly identify default image reference policy

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/assign @bmcelvee 
/cc @adambkaplan 

please back/forward port as needed.  I didn't see this exact text in master.

**Comment by bparees** [comment]
also chasing the history on why this was wrong:
https://bugzilla.redhat.com/show_bug.cgi?id=1664612
https://github.com/openshift/openshift-docs/pull/13340

seems like there was some confusion somewhere.....

**Comment by jboxman** [comment]
@bparees, I created a separate PR (https://github.com/openshift/openshift-docs/pull/15401) with the proposed fix. If it looks good there, I'll close this and move forward in that PR. Thanks!

**Comment by bparees** [comment]
your pr looks fine, thanks

**Pull request closed without merging**
