### PR TITLE
YAML edit as per suggestion

### PR DESCRIPTION
**Pull request by bfallonf**
Edit reported to me via email

### CODE REVIEW

**Comment by GrahamDumpleton** [comment]
Looks better now presuming is then rendered properly in browser.

**Comment by bfallonf** [comment]
@GrahamDumpleton The problem seemed to stem that there were too many spaces and indents and the like. Should be good now.

Thanks!

**Comment by bfallonf** [comment]
Just fixed a yaml eg so it worked. Probably no rev history needed here.

**Comment by adellape** [comment]
@bfallonf Label/milestone.

**Comment by adellape** [comment]
Removed this from "Next Release" as it modifies https://github.com/openshift/openshift-docs/pull/1445 which is for OSE 3.2.

**Pull request merged**
