### PR TITLE
BZ2077157: Adding HighNodeUtilization profile

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.8+
[Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2077157)

Preview: [Evicting pods using the descheduler -> Descheduler profiles ](https://51538--docspreview.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-profiles_nodes-descheduler)

- [ ] QE review

### CODE REVIEW

**Comment by kelbrown20** [comment]
@sunilcio Hey Sunil! Can you PTAL at this PR when you get the chance? Thank you!

**Comment by sunilcio** [comment]
@kelbrown20 hi, checked with @kasturinarra , she will help review. Thank you!

**Comment by kasturinarra** [comment]
@kelbrown20 I do not think  we have tested  HighNodeUtilization with respect to descheduler. @ingvagabund could you please help confirm as well ? thanks !!

**Comment by ingvagabund** [comment]
We don't currently enable HighNodeUtilization strategy in any of the available descheduler operator profiles.

**Comment by ingvagabund** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2077157 needs to be turned into an RFE first. @knelasevero can you please take a look? It's about introducing a new profile.

**Comment by kelbrown20** [comment]
PR no longer needed

**Pull request closed without merging**
