### PR TITLE
OSDOCS-468-DEVEXP-401 Add Builds - Mount trusted CA for cluster proxies warning

### PR DESCRIPTION
**Pull request by bmcelvee**
https://jira.coreos.com/browse/DEVEXP-401

Adding warning based on discussion from: https://github.com/openshift/openshift-docs/issues/16327#issuecomment-533255545

### CODE REVIEW

**Comment by bparees** [comment]
thx @bmcelvee 
/assign @gabemontero @ricardomaraschini

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by mburke5678** [comment]
@bmcelvee One nit from me.

**Comment by bmcelvee** [comment]
Thanks, all! Merging now.

This PR is adding a note and does not require QE review.

**Pull request merged**
