### PR TITLE
[OSDOCS-6940]:(phase-1) new standard, non-GPU instances for OSD on GCP

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-6940
Link to docs preview:

https://74436--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#gcp-compute-types_osd-service-definition
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Reviewers: Feature is not in production, do not merge until further notice.

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
