### PR TITLE
Connected to Diconnected post install assembly remove TP note

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=2110779

Preview: [Converting a connected cluster to a disconnected cluster ](http://file.rdu.redhat.com/mburke/connected-to-disconnected.html)

### CODE REVIEW

**Comment by mburke5678** [comment]
@sferich888 @dmesser @xltian @mrunalp PTAL

cc @sjstout

**Review by dmesser — APPROVED** [review]

**Review by tmalove — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
LGTM!

**Pull request merged**
