### PR TITLE
TELCODOCS-522 - enterprise-4.11 ClusterGroupUpgrade message is incorrect

### PR DESCRIPTION
**Pull request by aireilly**
https://issues.redhat.com/browse/TELCODOCS-522

Fixes incorrect status message for 4.11

Merge to enterprise-4.11 only.

### CODE REVIEW

**Comment by aireilly** [comment]
@jc-rh can you review/LGTM on this please. Related to https://github.com/openshift/openshift-docs/pull/53026#discussion_r1031759751

**Comment by GroceryBoyJr** [comment]
More complete preview link:
https://53181--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.html#ztp-monitoring-policy-deployment-progress_ztp-configuring-managed-clusters-policies

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
