### PR TITLE
Removed Release Notes/added README

### PR DESCRIPTION
**Pull request by vikram-redhat**
@openshift/team-documentation PTAL

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Thanks @vikram-redhat! I'll take a closer look at this tomorrow. But for right now, what I notice is that the topic map needs updating to show the 4.3 rn file instead of 4.2.

**Comment by vikram-redhat** [comment]
@bergerhoffer good point. Fixed (after a few fixups).

**Comment by bergerhoffer** [comment]
This LGTM @vikram-redhat! Let me know when you merge this so I can merge PR #18597 which is dependent on this. Thanks!

**Comment by vikram-redhat** [comment]
@codyhoag @sheriff-rh - am merging this if this has any implications for release notes updates for anything that you are working on right now.

@ahardin-rh @adellape FYI

**Pull request merged**
