### PR TITLE
Fixed incorrect statement about IPSec throughput

### PR DESCRIPTION
**Pull request by ghost**
@cjoster Please review this follow-up to https://github.com/openshift/openshift-docs/pull/5049.

@openshift/team-documentation PTAL.

### CODE REVIEW

**Review by cjoster — CHANGES_REQUESTED** [review]
The two lines I changed look good, but I do want to raise an objection to "IPSec encryptes traffic at the IP *address* level", which would be better said as the "IP payload level" if, for some reason, "the IP level" (as in the protocol level, or layer 3, isn't sufficient.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM pending cjoster comment above.

**Comment by tmorriso-rh** [comment]
@cjoster Changed "IP address level" to "IP payload level." Please review. Thanks.

**Comment by cjoster** [comment]
Looks good. Thank you!

**Pull request merged**
