### PR TITLE
OCPBUGS#11781: Update the product comparison table

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-11781 

Link to docs preview: https://59058--docspreview.netlify.app/openshift-enterprise/latest/welcome/oke_about.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by juzhao** [comment]
> @juzhao The "About OpenShift Kubernetes Engine" diagram mentions "Monitoring" only. Should we change the term from "Monitoring" to "Cluster monitoring" in the diagram to avoid confusion? I updated the table

the change is LGTM

**Comment by gaurav-nelson** [comment]
LGTM 🍔

**Pull request merged**
