### PR TITLE
OCPBUGS-36911: Update PTP docs as per the Concious Language initiative

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.14, 4.15, 4.16, 4.17, 4.18

Issue: https://issues.redhat.com/browse/OCPBUGS-36911

Link to docs preview: https://85785--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/ztp-reference-cluster-configuration-for-vdu#ztp-sno-du-configuring-ptp_sno-configure-for-vdu

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]
/lgtm

**Comment by amolnar-rh** [comment]
@tmalove That's it, I changed what I could for now, but I discussed with the developer that some of the configuration still uses master/slave and they are planning to update this in a future release.

**Review by ShaunaDiaz — COMMENTED** [review]
LGTM

**Comment by ShaunaDiaz** [comment]
@amolnar-rh Looks like 4.15 and 4.14 version are different. If those two are the same, though, you can make a PR against 4.15 and we can pick it back to 4.14. Otherwise, two CP PRs will be needed.

**Pull request merged**
