### PR TITLE
Fix a YAML line

### PR DESCRIPTION
**Pull request by rh-max**
@bmcelvee Could you please merge this and cherry-pick into `enterprise-4.3`? Thanks. It's verified by the QE.

### CODE REVIEW

**Comment by bmcelvee** [comment]
Sure thing!

**Comment by bmcelvee** [comment]
Also cherry picking to 4.4 because the file is there too. :)

**Comment by rh-max** [comment]
@bmcelvee Right, forgot to request 4.4 too. Thank you!

**Comment by rh-max** [comment]
@bmcelvee Could you please cherry-pick this into `enterprise-4.2` and `enterprise-4.1` as well? I forgot about those.

**Pull request merged**
