### PR TITLE
OSDOCS-1594: Combine the Authentication and authorization and Cluster…

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.11+

Issue:
Relates to https://issues.redhat.com/browse/OSDOCS-1594 and https://github.com/openshift/openshift-docs/pull/51026

Link to docs preview:
http://file.rdu.redhat.com/bmcelvee/OSDOCS-1594-combine-books/authentication/assuming-an-aws-iam-role-for-a-service-account.html

QE review:
Moving existing content. No QE review required. 

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
@kalexand-rh here's the PR that combines the authentication books in the ROSA topic map

**Comment by kalexand-rh** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
