### PR TITLE
Applied minimalism workshop feedback to the Secrets topic

### PR DESCRIPTION
**Pull request by ahardin-rh**
per https://mojo.redhat.com/groups/ccs/blog/2016/12/19/looking-for-a-few-guinea-p-i-mean-volunteers

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @bmcelvee @mburke5678 PTAL

**Comment by mburke5678** [comment]
Looks better! 
Did we talk about the use of "it" in the meeting and/or using the nouns like "object," so you would have for ex. Properties of Secret Objects (Properties of Secrets sounds odd). 

Comments:
Line 22: Use of "it" 
Line 22: Passive voice "can be mounted"
Line 65: Plaural? secret/s You must create secrets before the pods that depend on it
Line 65: Use of "it"
Lines 88-90: "An exception to this is when a node is rebooted and the API server must re-read the secret data." An exception to what? Instead of following the prior sentence what should the customer do?

**Comment by bfallonf** [comment]
@ahardin-rh Looks good :star:

**Comment by ahardin-rh** [comment]
@mburke5678 @bfallonf Thanks! Made some edits.

**Comment by ahardin-rh** [comment]
No revision history necessary

**Pull request merged**
