### PR TITLE
OSDOCS-2220: add random option to haproxy.router.openshift.io/balance

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-2220

Preview: https://deploy-preview-33339--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration

### CODE REVIEW

**Comment by bmcelvee** [comment]
@Miciah here's the PR adding `random` to `haproxy.router.openshift.io/balance`. I'll add the release note in a separate PR.

**Comment by bmcelvee** [comment]
@quarterpin would you mind reviewing this PR, please? Thank you!

**Comment by quarterpin** [comment]
looks good to me. Thanks!

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
