### PR TITLE
Follow-up Edits to log forwarding per email

### PR DESCRIPTION
**Pull request by mburke5678**
Follow-up to https://github.com/openshift/openshift-docs/pull/20108#discussion_r397512074

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli PTAL

**Review by anpingli — COMMENTED** [review]
> If you set disableDefaultForwarding: true you must configure a pipeline and output for all three types of logs, application, infrastructure, and audit. If you do not specify a pipeline and output for a log type, those logs are not stored and will be lost.

I don't see any difference between disableDefaultForwarding: true and disableDefaultForwarding: false.  @jcantrill Is this a bug?

**Pull request merged**
