### PR TITLE
Hyperlink for Microsoft Azure documentation "listing user-assigned managed identities" is incorrect

### PR DESCRIPTION
**Pull request by Shubhampwrredhat**
The hyperlink for Microsoft Azure documentation "listing user-assigned managed identities" is incorrect in doc[1]. In Using Azure managed identities , procedure 2.b 

[1] https://docs.openshift.com/container-platform/4.14/installing/installing_azure/installing-azure-account.html#installation-using-azure-managed-identities_installing-azure-account

Current link : 

link:https:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#list-user-assigned-managed-identities[listing user-assigned managed identities].

Actual link : 

link:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#list-user-assigned-managed-identities[listing user-assigned managed identities].

Version(s):
4.14,4.15

Issue:
https://issues.redhat.com/browse/OCPBUGS-32052

Link to docs preview:
https://docs.openshift.com/container-platform/4.15/installing/installing_azure/installing-azure-account.html#installation-using-azure-managed-identities_installing-azure-account

### CODE REVIEW

**Comment by Shubhampwrredhat** [comment]
Hi @tmalove , exactly the issue is.  It is not resolving due to an extra "https" keyword (see below) : 

Screenshot from 2024-04-11 00-50-32

**Comment by tmalove** [comment]
> Hi @tmalove , exactly the issue is. It is not resolving due to an extra "https" keyword (see below) :
> 
> Screenshot from 2024-04-11 00-50-32

@Shubhampwrredhat The updated content should resolve that issue...contacting you offline.

**Pull request merged**
