### PR TITLE
[enterprise-4.2] AWS EFS provisioner was dropped for 4.x

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@qinpingli can you confirm this again? https://github.com/openshift/openshift-docs/pull/16410#issuecomment-529660162 advised to list this as TP for 4.2, which is why we have continuously listed it as such. Once I have confirmation for this change, I'll make changes for the 4.3+ release notes. Thanks!

**Comment by qinpingli** [comment]
> @qinpingli can you confirm this again? [#16410 (comment)](https://github.com/openshift/openshift-docs/pull/16410#issuecomment-529660162) advised to list this as TP for 4.2, which is why we have continuously listed it as such. Once I have confirmation for this change, I'll make changes for the 4.3+ release notes. Thanks!

Hello Cody,
Thanks for the information, I double confirmed with QE team, we never tested efs from 4.x. And from 4.4 we didn't release efs provisioner image to the customer(https://comet.engineering.redhat.com/containers/repositories/5d96f099d70cc50ebeaadb0b#tab-images)

@huffmanca  Could you help double confirm, thanks in advance.

**Comment by huffmanca** [comment]
@qinpingli @codyhoag ,

I've spoken to our product manager, and he indicated that we should be testing this (and properly reporting it). We hope to include EFS in a CSI Driver soon; however, we need to be testing and including it until the CSI Driver is available, at least as tech preview.

In the testing sheet we include AWS EBS in both File and Block; there was an open question regarding whether this should be EFS for File?

**Comment by codyhoag** [comment]
Closing, as discussed with Bob and Christian.

**Pull request closed without merging**
