### PR TITLE
GitHub-16568: Reordering fields to match the expected order

### LINKED ISSUE #46568: [enterprise-4.9] Issue in file authentication/configuring-internal-oauth.adoc
### Which section(s) is the issue in?
Customizing the internal OAuth server URL

### What needs fixing?

I think this section is wrong 

apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: oauth-openshift
      namespace: openshift-authentication
      hostname: <custom_hostname> 
      servingCertKeyPairSecret:
        name: <secret_name> 

and should look like this instead

apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - hostname: <custom_hostname> 
      name: oauth-openshift
      namespace: openshift-authentication
      servingCertKeyPairSecret:
        name: <secret_name> 

Whats different is hostname and name. Look what you have in the document about customizing custom console URL

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.9+

Issue:
Fixes #46568

Link to docs preview:
* http://file.rdu.redhat.com/~ahoffer/2022/github-16568/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth
* http://file.rdu.redhat.com/~ahoffer/2022/github-16568/web_console/customizing-the-web-console.html#customizing-the-web-console-url_customizing-web-console

### CODE REVIEW

**Review by bortek — APPROVED** [review]
This looks correct according and how the operator reorders the fields when applied.

**Comment by bscott-rh** [comment]
LGTM!

**Review by bscott-rh — APPROVED** [review]

**Comment by bergerhoffer** [comment]
@xingxingxia can you please QE review this update?

Link to docs preview:
* http://file.rdu.redhat.com/~ahoffer/2022/github-16568/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth
* http://file.rdu.redhat.com/~ahoffer/2022/github-16568/web_console/customizing-the-web-console.html#customizing-the-web-console-url_customizing-web-console

**Comment by xingxingxia** [comment]
Right, the display of kubectl/oc's subcommands like `get -o yaml`, `edit`, `explain` et al print the fields alphabetically. So, while following our documents, if user runs `edit` to **edit existing** fields and sees the display differs from the documents, he/she may be confused.

**Comment by xingxingxia** [comment]
But by default, these customization fields are not existent in a fresh env, so user only **adds new** fields rather than edits the existing fields at the beginning. In terms of this, the documents do not have problem.

**Comment by xingxingxia** [comment]
Anyway, ordering as per the original issue's request is fine. Other problems come as below, though. Need they be updated too?
`oc edit ingress.config.openshift.io cluster` will show:
```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  domain: <...>
  componentRoutes:
  - hostname: <...>
```
It shows "domain: " but documents don't show, will other users have new confusion about this? And fields under componentRoutes show 4 space indentation:
```
  componentRoutes:
  - hostname: <custom_hostname>
    name: oauth-openshift
```
but the documents differ with 6 space indentation:
```
  componentRoutes:
    - hostname: <custom_hostname> 
      name: oauth-openshift
```
will some careful users have separate confusion about this?

**Comment by bortek** [comment]
This is an excellent explanation of what's going on. 👍

So why not, instead of modify the documentation and reordering stuff like aI previously suggested, just add as a comment to documentation your explanation? It will not only clarify it but will also teach users something new.

**Comment by bergerhoffer** [comment]
It doesn't seem like there is a right or wrong answer here: depending on how you view it, the fields are in different orders. 

Order doesn't matter for YAML, and this likely happens many other places throughout the docs. We can't specify each of those places that the order might be different than what you're seeing. For that reason, I'm going to close this PR as something we won't address.

**Pull request closed without merging**
