### PR TITLE
[enterprise-3.6] Clarifing Docker Storage choices for Graph Drivers per BZ

### PR DESCRIPTION
**Pull request by mburke5678**
Cherrypicked from https://github.com/openshift/openshift-docs/pull/8594

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@mburke5678  Why does this have a label of enterprise-3.10 when it is merged to the 3.6 branch?

**Comment by mburke5678** [comment]
@vikram-redhat Copy-paste error with the [enterprise-3.10]. Fixed.

**Comment by mburke5678** [comment]
Reverting this PR to get a correctly titled commit

**Comment by mburke5678** [comment]
Reverting this merge to get the correct commit message. Replaced changes via https://github.com/openshift/openshift-docs/pull/8815

**Pull request merged**
