### PR TITLE
BZ2185920: Fix live migration YAML

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12+

Issue: [BZ2185920](https://bugzilla.redhat.com/show_bug.cgi?id=2185920)

Link to docs preview: [Configuring live migration policy](https://58776--docspreview.netlify.app/openshift-enterprise/latest/virt/live_migration/virt-configuring-live-migration-policies.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@kbidarkar Ready for QE review.

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
