### PR TITLE
OBSDOCS-1148: Add documentation for routing connector

### PR DESCRIPTION
**Pull request by max-cx**
:warning: This PR is for https://github.com/openshift/openshift-docs/tree/dtotel-docs-3.3, not `main`

Signed-off-by: Israel Blancas <iblancasa@gmail.com>

Version(s):

:warning: No cherry-picks (cherry-picks will be done when the whole branch gets merged into main on the release date).
4.12, 4.13, 4.14, 4.15, 4.16, 4.17

Issue:

https://issues.redhat.com/browse/OBSDOCS-1148

Link to docs preview:

https://79248--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-collector/otel-collector-connectors.html#routing-connector_otel-collector-connectors

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by IshwarKanse — APPROVED** [review]

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
Excellent. Merge review lgtm!

**Pull request merged**
