### PR TITLE
Bug 1795495 update node sample policy configurations

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1795495

### CODE REVIEW

**Review by kasturinarra — COMMENTED** [review]
Changes looks good to me.

**Comment by bmcelvee** [comment]
Thanks!

@openshift/team-documentation PTAL, thanks!

**Comment by jboxman** [comment]
@bmcelvee, for consistency I'd reintroduce the space between the key and array value, but otherwise LGTM.

```
"labels": ["region, zone"]
```

**Comment by bmcelvee** [comment]
Thanks, @jboxman - easy enough! Update coming ASAP.

**Pull request merged**
