### PR TITLE
Clarifying that etcd encryption only encrypts values

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://encryption-clarification--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/backing-up-etcd.html#backing-up-etcd-data_backup-etcd

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@sttts Can you verify that this wording is okay? This will be applied for 4.3+.

And let me know if we need to make an update to either of these places that mention OAuth tokens being encrypted:

* https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-encrypt-data-stored-in-etcd
* https://docs.openshift.com/container-platform/4.3/authentication/encrypting-etcd.html#about-etcd_encrypting-etcd

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review this update?

Also FYI @jasinner in case you wanted to review.

**Comment by geliu2016** [comment]
@bergerhoffer LGTM, thanks

**Comment by bergerhoffer** [comment]
I'm going to merge in this update. @sttts or @jasinner let me know if we need to update either of the references mentioned above which say that OAuth tokens are encrypted.

**Pull request merged**
