### PR TITLE
OCPBUGS#16812: update table for tls passthrough routes default

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-16812

Link to docs preview: https://67101--docspreview.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration#nw-route-specific-annotations_route-configuration

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi PTAL for QE ack. this doc change updates the haproxy load balancing entry of the table for route annotations, it adds the default value for TLS passthrough routes

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by ShudiLi** [comment]
/lgtm
@jldohmann done.

**Pull request merged**
