### PR TITLE
BZ1980122: Add quotes arounnd annotation value

### PR DESCRIPTION
**Pull request by xenolinux**
Fixes: [1980122](https://bugzilla.redhat.com/show_bug.cgi?id=1980122)
OCP version: 4.7, 4.8, 4.9, 4.10
[Preview](https://deploy-preview-39659--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration#nw-route-specific-annotations_route-configuration)
QA contact: @quarterpin

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@lihongan ^^

**Comment by quarterpin** [comment]
Looks good to me. Thanks!

**Pull request merged**
