### PR TITLE
OCPBUGS-13195 Documentation of a haproxy annotation that doesn't exist

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): all (from 4.5 onwards)

Issue: https://issues.redhat.com/browse/OCPBUGS-13195

Link to docs preview: https://72949--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration#nw-route-specific-annotations_route-configuration

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@ShudiLi QE check please

**Comment by ShudiLi** [comment]
/lgtm
enabled by default(Scenario: OCP-30066:NetworkEdge Enable log-send-hostname in HAproxy configuration by default)

**Comment by gwynnemonahan** [comment]
Hey @jmanthei ,

LGTM!

**Pull request merged**
