### PR TITLE
OCPBUGS-9290: Not clear where to enable multipathing with kernel arguments

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s):  4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-9290

Link to docs preview: (Note to reviewers: the change was to only one module but the automation tracked where the module occurs and provided three previews)

https://75733--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html
https://75733--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html
https://75733--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
/assign @achuzhoy 
Asking for your QE LGTM please sir.

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
