### PR TITLE
Document admin console inventory variables

### PR DESCRIPTION
**Pull request by spadgett**
Initial documentation of the admin console inventory variables.

/assign @ahardin-rh

### CODE REVIEW

**Comment by spadgett** [comment]
@sdodson fyi

**Comment by ahardin-rh** [comment]
@spadgett Thanks for this!
@yapei Can you please provide a QE review? Thank you!

**Comment by yapei** [comment]
Seems we missed following parameters

`openshift_console_branding
openshift_console_documentation_base_url
openshift_console_base_path
openshift_console_image_name
openshift_console_nodeselector
openshift_console_replica_count`

**Comment by spadgett** [comment]
Yeah, I purposely left most of those out because they shouldn't really needed to be changed. There's a good chance those will be reset when we move to an operator for install.

`openshift_console_base_path` should be there, though. Will update.

**Comment by spadgett** [comment]
Updated

**Comment by ahardin-rh** [comment]
Thank you! LGTM

**Comment by adellape** [comment]
@spadgett Can you confirm the name of what we're calling this console, either "Admin Console" or "Cluster Console"? I'm looking at a latest OKD cluster and see "Cluster Console" in the top-left drop-down switcher, just wondering if that's the same for 3.11.

Also, even though we're talking about "admin" tasks, do we expect all users (with or without cluster-admin or similar permissions) to be able to access this new console?

cc @ahardin-rh

**Comment by spadgett** [comment]
> Can you confirm the name of what we're calling this console, either "Admin Console" or "Cluster Console"? I'm looking at a latest OKD cluster and see "Cluster Console" in the top-left drop-down switcher, just wondering if that's the same for 3.11.

The selector will say "Cluster Console." (I'm not a fan of that name, but that's what it will be.)

> Also, even though we're talking about "admin" tasks, do we expect all users (with or without cluster-admin or similar permissions) to be able to access this new console?

Yes, normal users will be able to access the console, and it is still useful for normal users.

**Pull request merged**
