### PR TITLE
 BZ1879712: Added a note for SMB and corrected passive voice usage

### PR DESCRIPTION
**Pull request by Amrita42**
The scope of this bz covers adding a note for SMB and also correcting 3 instances of passive voice (can be).

Applies to 4.6+ versions

[BZ1879712](https://bugzilla.redhat.com/show_bug.cgi?id=1879712)

[Preview](https://deploy-preview-37400--osdocs.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-azure-file)

@jsafrane please review and confirm that its for 4.6 and above versions.
@duanwei33 please review

### CODE REVIEW

**Review by ctauchen — COMMENTED** [review]
All good -- a few suggestions.

But first, some housekeeping:

* please make sure that the title follows the format `BZ9999999: bla bla bla". This makes it easier for us to track.

**Review by bergerhoffer — COMMENTED** [review]
One note to consider going forward, but LGTM so merging!

**Pull request merged**
