### PR TITLE
bug 1622044 corrected auditFilePath examples

### PR DESCRIPTION
**Pull request by sheriff-rh**
Link to bug, see c#8:
https://bugzilla.redhat.com/show_bug.cgi?id=1622044

@gpei PTAL 
@openshift/team-documentation peer review please!

Thanks!

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Looks good! :+1:

**Comment by sheriff-rh** [comment]
QE Ok'ed in c#13 of bug, merging.

**Pull request merged**
