### PR TITLE
OCPBUGS#4782 First known issue in OCP RN needs updated to reflect version

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OCPBUGS-4782

Link to docs preview:
https://53760--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-known-issues

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by mffiedler** [comment]
Approved for QE - LGTM

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
