### PR TITLE
Remove duplicate words

### PR DESCRIPTION
**Pull request by liangxia**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Thank you, @liangxia! 
@vikram-redhat, should we change the text of the API docs, or do we need to drive changes somewhere else to make them "stick?"

**Comment by vikram-redhat** [comment]
Wow. First there were that many duplicate words? Thank you @liangxia .

Second, the inclusion of the REST API docs makes it hard to CP this to 3.9 or other branches. The REST API guides are supposed to get auto-generated, although Jim Minter is working on updates to it. 

@kalexand-rh - you can merge it to master and then CP to 3.9 and 3.10. Other than that, I am not sure it will work without removing the REST API changes to other earlier branches. Even for 3.10 I am skeptical.

**Comment by kalexand-rh** [comment]
Yes, thanks again @liangxia!
@vikram-redhat, how far back do you want me to try? I'll brace myself for merge errors. ;)

**Comment by vikram-redhat** [comment]
This is a low hanging fruit. I am gonna say let's leave it at this. If you come across these fix them as part of other things.

cc: @aheslin

**Comment by kalexand-rh** [comment]
Sounds good to me.

**Pull request merged**
