### PR TITLE
Added details about known issue per docs issue#13345

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses https://github.com/openshift/openshift-docs/issues/13345

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@wjiangjay Can you please provide a QE review of this content?

**Comment by kalexand-rh** [comment]
LGTM!

**Comment by wjiangjay** [comment]
@ahardin-rh @kalexand-rh  will give a try tomorrow.
Since this issue is blocking https://bugzilla.redhat.com/show_bug.cgi?id=1611839 and https://bugzilla.redhat.com/show_bug.cgi?id=1503729, and seems like we already got a fix, 
and patch for version 3.9 is already merged https://github.com/openshift/openshift-ansible/pull/11014.

So I think I can give a try with the latest release-3.9 code or release rpms or images

**Comment by wjiangjay** [comment]
Checked and LGTM

**Comment by ahardin-rh** [comment]
@wjiangjay Excellent. Thank you!

**Pull request merged**
