### PR TITLE
Revert misfire commits

### PR DESCRIPTION
**Pull request by maxwelldb**
This reverts commit 819da3bacd1353ec94401be2b26a463983723c16 and
commit 0b369eba02e46cba7f3f5bde28ccced07ca3d707 from #51467

Version(s): 4.10, 4.11. Change must apply to main, too. 

Issue: 

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information: 

@bergerhoffer Any objections to:

1. Merging this to main. 
2. CPing to 4.10 and 4.11.
2. Re-applying the changes from #51467 to 4.10 and 4.11 in single-commit pull requests?

?

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
@maxwelldb That sounds like a good plan. Thanks for resolving this!

LGTM

**Comment by maxwelldb** [comment]
@bergerhoffer Thanks!

**Pull request merged**
