### PR TITLE
Updated OpenShift instances to {product-title} in Rest API book

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tnguyen-rh @tpoitras PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**Comment by tpoitras** [comment]
@ahardin-rh LGTM, too. :octocat:

**Comment by ahardin-rh** [comment]
Thanks, guys!  :star2:

**Pull request merged**
