### PR TITLE
For bug BZ1469406 - added note about ansible_ssh_user variable

### PR DESCRIPTION
**Pull request by jhoyt-rh**
@openshift/team-documentation, PTAL
@anpingli, PTAL
@sdodson, PTAL
@gkimetto@redhat.com, PTAL

### CODE REVIEW

**Comment by jhoyt-rh** [comment]
Source is install/configuring_inventory_file.adoc

**Review by sdodson — APPROVED** [review]
looks fine to me

**Comment by mburke5678** [comment]
@jhoyt-rh LGTM
Which version(s) should this change go into in addition to 3.10? @anpingli reported the issue in 3.6 according to the BZ.

**Comment by vikram-redhat** [comment]
@jhoyt-rh - the change should be made in master and then cherry picked to 3.10 (and 3.11).

**Comment by jhoyt-rh** [comment]
@anpingli, PTAL. If you approve this change I can merge the PR. Thanks!

**Comment by anpingli** [comment]
LGTM

**Review by anpingli — APPROVED** [review]

**Comment by jhoyt-rh** [comment]
All reviews complete and approved. Merging PR

**Pull request merged**
