### PR TITLE
Issue 49638: Removing duplicate text

### LINKED ISSUE #49638: [enterprise-4.11] Issue in file migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
### Which section(s) is the issue in?
State migration

### What needs fixing?
In section "State migration", the Prerequisites, Procedure and following NOTE repeated.
The later repeat should be removed.

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://github.com/openshift/openshift-docs/issues/49638
MTC 1.6, MTC 1.7
OCP 4.8+

### CODE REVIEW

**Comment by apinnick** [comment]
@sbeskin-redhat You need to request peer review and then have this merged and CPed.

**Comment by kcarmichael08** [comment]
Hi, preview is no longer available, but it looks OK in the code view. However, I think the body of the PR needs to be edited to indicate which version(s) to cherry pick to (I am not sure). Otherwise, LGTM.

**Comment by apinnick** [comment]
@sbeskin-redhat Which versions does this need to be cherrypicked to?

**Comment by anarnold97** [comment]
Thanks @apinnick for highlighting

**Pull request merged**
