### PR TITLE
Followup edits as per 4587

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://trello.com/c/n2Nznefg/565-document-allow-modification-of-haproxys-ssl-cipher-preference-ingress

and #4587 

cc: @pecameron @knobunc

### CODE REVIEW

**Review by pecameron — COMMENTED** [review]
LGTM

**Comment by bfallonf** [comment]
Thanks @pecameron . I'll move forward with this.

@openshift/team-documentation peer review please?

**Comment by bmcelvee** [comment]
LGTM 🎆

**Comment by bfallonf** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added the section xref:../architecture/core_concepts/routes.adoc#ciphers[Router Cipher Suite] and various changes about ciphers.
%
|xref:../install_config/router/default_haproxy_router.adoc#install-config-router-default-haproxy[Setting up a Router -> Using the Default HAProxy Router]
|Added the xref:../install_config/router/default_haproxy_router.adoc#bind-ciphers[TLS Cipher Suites] section and various changes about ciphers.
%

**Pull request merged**
