### PR TITLE
[SRVCOM-1950] Re-adding previously removed release notes

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.7

Issue:
https://issues.redhat.com/browse/SRVCOM-1950

Link to docs preview:
- 1.15: http://file.rdu.redhat.com/abrennan/180722/SRVCOM-1950-47/serverless/serverless-release-notes.html#serverless-rn-1-15-0_serverless-release-notes
- 1.14: http://file.rdu.redhat.com/abrennan/180722/SRVCOM-1950-47/serverless/serverless-release-notes.html#serverless-rn-1-14-0_serverless-release-notes

NOTE: Re-adding previously published but removed content (no longer supported versions requested to be returned by customer). No QE or SME reviews required since content was previously reviewed and published at the time.
See https://github.com/openshift/openshift-docs/pull/41248

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
Adding these back in may require change management or a variation of it. Content lgtm though!

**Comment by abrennan89** [comment]
Need ACKs from:

- [ ] Product Experience: @sferich888 @reestr 
- [ ] QE: @xltian 
- [ ] Engineering: @nainaz or someone designated by Naina
- [ ] The Project Manager (PM) for the Engineering team: Rajesh
- [ ] DPM (@kalexand-rh ) and a Content Strategist (@Preeticp )

**Review by kalexand-rh — COMMENTED** [review]
Based on the Slack thread, this LGTM.

**Comment by nainaz** [comment]
LGTM!

**Comment by alanfx** [comment]
This change looks good to me! QE ACK!

**Comment by Shermbo** [comment]
ACK from CPM/PLM on this PR - @abrennan89

**Comment by rrajasek** [comment]
Acknowledge the change based on the decision to reinstate older release notes and not remove them in the future.

**Pull request merged**
