### PR TITLE
OADP - 749 extract updated

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP  1.1.2 

OCP 9+ 

Resolves -   https://issues.redhat.com/browse/OADP-749

Deploy preview -  https://54336--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html

### CODE REVIEW

**Comment by CarmiWisemon** [comment]
@mperetzred please review.

**Review by mperetzred — APPROVED** [review]

**Comment by RichardHoch** [comment]
LGTM

**Comment by RichardHoch** [comment]
Carmi doesn't yet have permission to add labels, so i did it for him. He'll reply to any comments.

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
@CarmiWisemon @RichardHoch Which versions of the OCP docs should this change be included in? From the linked JIRA, I see a link to OCP 4.11 docs; 4.11 and later?

**Comment by RichardHoch** [comment]
@CarmiWisemon see Aziza's last comment the Jira -- looks like OCP 4.9 and 4.11 but that needs to be confirmed.

**Comment by CarmiWisemon** [comment]
> @CarmiWisemon @RichardHoch Which versions of the OCP docs should this change be included in? From the linked JIRA, I see a link to OCP 4.11 docs; 4.11 and later?

@adellape 
OCP 9+

**Comment by CarmiWisemon** [comment]
Please merge as soon as it clears.

**Pull request merged**
