### PR TITLE
[enterprise-4.12] OSDOCS-4799: Add release note for post-install hybrid network configuration

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-4799

Refs https://github.com/openshift/openshift-docs/pull/61108.

Version(s): 4.12

Issue: https://61985--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-configure-hybrid-networking-post-install

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by mffiedler** [comment]
@anuragthehatter PTAL.   Looks ok to me.

**Review by mffiedler — APPROVED** [review]

**Comment by jab-rh** [comment]
@anuragthehatter, can you confirm? Thanks!

**Pull request merged**
