### PR TITLE
OCPBUGS-24589: Updated Config firewall for OCP section in Install config

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.15 to 4.11

Issue:
[OCPBUGS-24589](https://issues.redhat.com/browse/OCPBUGS-24589)

Link to docs preview:
[Configuring your firewall for OpenShift Container Platform](https://69898--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall)

SME review
- [X] SME has approved this change.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by barbacbd** [comment]
/retitle OCPBUGS-24589: Updated Config firewall for OCP section in Install config

**Review by barbacbd — COMMENTED** [review]
according to the notes in the JIRA link 

/lgtm

**Review by abrennan89 — COMMENTED** [review]
lgtm, left one suggestion comment

**Comment by jinyunma** [comment]
LGTM

**Pull request merged**
