### PR TITLE
4.14.z Telco RAN RDS

### PR DESCRIPTION
**Pull request by aireilly**
Doc updates for the Telco RAN 4.14.z RDS.

Version(s):
enterprise-4.14+

Issue:
https://issues.redhat.com/browse/TELCODOCS-1774

Link to docs preview:
https://file.emea.redhat.com/aireilly/rds-4.14.z-mk2/telco_ref_design_specs/ran/telco-ran-ref-design-spec.html

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mpmaruthu** [comment]
Telco RAN QE: Looks good to me.
/Peri M

**Review by imiller0 — COMMENTED** [review]
lgtm

**Pull request merged**
