### PR TITLE
bug 1529522 backup /etc/etcd/ca/ folder

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://bugzilla.redhat.com/show_bug.cgi?id=1529522

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@geliu2016, PTAL

**Comment by geliu2016** [comment]
@kalexand-rh, this section LGTM, but how to restore ca in 'etcd restore' should be added, right? pls confirm with the dev or bug reporter for this, thx

**Comment by kalexand-rh** [comment]
On the source bug, @geliu2016 said to go ahead and merge this change. He made a new bug for the restore changes.

Merging.

**Comment by kalexand-rh** [comment]
(The PR shows that the Travis job is pending, but it really passed.)

**Pull request merged**
