### PR TITLE
Removed tech preview per Trello

### PR DESCRIPTION
**Pull request by mburke5678**
https://trello.com/c/RRkUUnKS/830-document-node-promote-hugepages-to-supported

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning  @wjiangjay  Removed the Technology Preview from the Hugepages topic. Does this cover this Trello or is more needed?

**Comment by derekwaynecarr** [comment]
LGTM, this should merge with 3.10 docs

**Comment by mburke5678** [comment]
@wjiangjay PTAL

**Comment by wjiangjay** [comment]
LGTM

**Comment by mburke5678** [comment]
@ahardin-rh Follow-up to merge to master in https://github.com/openshift/openshift-docs/pull/8706 PTAL

**Comment by mburke5678** [comment]
Closing in favor of follow-up to merge to the correct branch.

**Pull request closed without merging**
