### PR TITLE
Fix link for Enabling HTTP/2 Ingress connectivity

### PR DESCRIPTION
**Pull request by bmcelvee**
Fix per Slack request.

### CODE REVIEW

**Comment by bmcelvee** [comment]
@Miciah - apologies for the delay on this! The link points to the correct section now. (It might take a bit for the preview build to spin up.)

**Comment by bmcelvee** [comment]
Direct preview link: https://fix-ne-rn-link--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-5-release-notes.html#ocp-4-5-http-2-ingress-support

**Comment by bobfuru** [comment]
LGTM!

**Comment by bmcelvee** [comment]
Since this is a simple link fix PR, QE review is not required.

**Pull request merged**
