### PR TITLE
Fix for Issue 18529

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://github.com/openshift/openshift-docs/issues/18529

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@gpei Can you please provide a QE review or refer me to the correct contact? Thank you!

**Comment by gpei** [comment]
Hi @ahardin-rh , I'm not sure which QE team is familiar with `Telemetry` and `Insights`

**Comment by ahardin-rh** [comment]
@xltian Can you please recommend a QE contact to review this? Thank you!

**Comment by xltian** [comment]
As I forwarded in email, 
 Jan Krocil is the QE owner for Insignts.

@juzhao  Please check if you can review any part related to telemetry.

**Comment by juzhao** [comment]
@xltian based on the issue 18529
https://github.com/openshift/openshift-docs/issues/18529
This is a Insights issue, should be assigned to Insights team

**Comment by vikram-redhat** [comment]
@rh-max have you worked with Jan Krocil? If yes, could you ping him to review this?

**Review by quarckster — APPROVED** [review]

**Comment by quarckster** [comment]
CCX qe reviewed and approved the changes.

**Comment by ahardin-rh** [comment]
@quarckster Thank you!

**Pull request merged**
