### PR TITLE
add AppliedClusterResourceQuota resource

### PR DESCRIPTION
**Pull request by guangxuli**

### CODE REVIEW

**Comment by guangxuli** [comment]
@adellape PTAL, thanks!

**Comment by guangxuli** [comment]
@pweil- PTAL. Thanks!

**Comment by pweil-** [comment]
@adellape do we want to include this?  This section is an example about making the GET request and is not attempting to provide the full output.

**Comment by guangxuli** [comment]
@pweil- yeah, I know our example is not attempting to provide the full output, but it is the first output, not in the middle.

**Comment by guangxuli** [comment]
@adellape PTAL.Thanks.

**Comment by guangxuli** [comment]
@enj ptal,thanks.

**Review by pweil- — APPROVED** [review]

**Comment by enj** [comment]
I am not familiar enough with `AppliedClusterResourceQuota` to make any comments.

**Comment by guangxuli** [comment]
@enj thanks
@adellape this PR is only about show the first resources after run this：
 [root@openshift-node ~]# curl -X GET -H "Authorization: Bearer" https://192.168.1.26:8443/oapi/v1 --insecure
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
    **{
      "name": "appliedclusterresourcequotas",
      "namespaced": true,
      "kind": "AppliedClusterResourceQuota"
    },**
    {
      "name": "buildconfigs",
      "namespaced": true,
      "kind": "BuildConfig"
    },
    {
      "name": "buildconfigs/instantiate",
      "namespaced": true,
      "kind": "BuildRequest"
    },
    {
      "name": "buildconfigs/instantiatebinary",
      "namespaced": true,
      "kind": "BinaryBuildRequestOptions"
    }, 
   ...
  I mean we should add the first resource `AppliedClusterResourceQuota `in our document since it has been updated.

**Pull request closed without merging**
