### PR TITLE
OSDOCS#8237: Operator SDK Multi-platform 4.14 release note

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.14

Issue: [OSDOCS-8237](https://issues.redhat.com//browse/OSDOCS-8237)

Link to docs preview: [Configuring Operator projects with support for multiple platforms](https://66408--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-osdk-multi-platform)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@aleskandro and @jaypoulz: PTAL at this PR for the 4.14 release notes

**Review by cbippley — COMMENTED** [review]
LGTM!

**Pull request merged**
