### PR TITLE
[enterprise-4.10] OSDOCS-4024: Add MT2892 Family SR-IOV hardware

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-4024

Refs https://github.com/openshift/openshift-docs/pull/49777.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM

**Comment by CFields651** [comment]
LGTM

**Comment by CFields651** [comment]
LGTM

**Comment by mffiedler** [comment]
QE is in the process of testing this on 4.10 cc: @zhaozhanqi

**Comment by zhaozhanqi** [comment]
Tested on 
410.84.202212061416-0 with kernel 4.18.0-305.72.1.el8_4.x86_64
/lgtm

**Comment by deepakc5** [comment]
any idea when documentation is going to make it into : https://docs.openshift.com/container-platform/4.10/networking/hardware_networks/about-sriov.html ?

**Comment by arkadykanevsky** [comment]
Is there a seperate patch for OCP 4.11 documentation for it also?

**Pull request merged**
