### PR TITLE
[OCPBUGS-4561]: Small update to revised instance type proc

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OCPBUGS-4561](https://issues.redhat.com/browse/OCPBUGS-4561)

Link to docs preview:
[Changing the Amazon Web Services instance type by using the AWS console](https://55485--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#aws-console-changing-aws-instance-type_recommended-host-practices)

QE review:
- [ ] QE has approved this change.

Additional information:
Based on [feedback](https://github.com/openshift/openshift-docs/pull/55123#pullrequestreview-1281149153) for #55123, which adds this proc for OCP 4.8-4.11

### CODE REVIEW

**Comment by JoelSpeed** [comment]
LGTM thanks

**Comment by jeana-redhat** [comment]
Can one of @sunzhaohua2 @miyadav or @huali9 PTAL for QA verification? :bow:

**Review by lobziik — COMMENTED** [review]
LGTM

**Pull request merged**
