### PR TITLE
TELCODOCS-1947: Removing BMER from docs as it is EOL

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1947](https://issues.redhat.com//browse/TELCODOCS-1947): Removing BMER from docs as it is EOL

Version(s):
4.17+

Issue:
https://issues.redhat.com/browse/TELCODOCS-1947

Link to docs preview:
(Preview of remaining modified content only)
https://80109--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ptp/using-ptp-events.html#cnf-migrating-from-amqp-to-http-transport_using-ptp-hardware-fast-events-framework

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jzding — APPROVED** [review]
/lgtm

**Review by lahinson — COMMENTED** [review]
LGTM

@rohennes I believe this PR requires change management according to the OpenShift Docs Manual (https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.epes4xf06pzk).

**Comment by rohennes** [comment]
> LGTM
> 
> @rohennes I believe this PR requires change management according to the OpenShift Docs Manual (https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.epes4xf06pzk).

Thanks Laura. I think as this change is being made as part of the 4.17 release, it wouldn't also need change management. There will be a release note too highlighting the EOL status. And it's been deprecated in previous releases. So I think we're good unless I'm misunderstanding the process.

**Comment by tradej** [comment]
(Telco DPM here) Agreed with @rohennes, @lahinson. This feature has been deprecated in previous releases and is expected. As per the [bold sentence in the first paragraph](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#bookmark=id.khm4rxl210qm) of the OCP Docs Manual, I would assert CM not needed.

**Comment by michaelryanpeter** [comment]
@rohennes Would you please make a manual CP to 4.17?

The `main` branch and the release feature branches got out of sync with PR #69899. Not a huge deal, but #69899 should have been broken into two PRs, one based off of `enterprise-4.15` for the release note and another off of `main` for the documentation changes. As a result, there is a five line discrepancy between `scalability_and_performance/using-rfhe.adoc` on `main` (58 lines) and `enterprise-4.17` (63 lines), which is causing the merge conflict. 

(FWIW, this happens from time to time. I just thought I would explain the specifics, as I appreciate learning from these situations, and I get the sense that you do too. :smiley: )

**Comment by rohennes** [comment]
> @rohennes Would you please create a manual CP to 4.17?
> 
> The `main` branch and the release feature branches got out of sync with PR #69899. Not a huge deal, but #69899 should have been broken into two PRs, one based off of `enterprise-4.15` for the release note and another off of `main` for the documentation changes. As a result, there is a five line discrepancy between `scalability_and_performance/using-rfhe.adoc` on `main` (58 lines) and `enterprise-4.17` (63 lines), which is causing the merge conflict.
> 
> (FWIW, this happens from time to time. I just thought I would explain the specifics, as I appreciate learning from these situations, and I get the sense that you do too. 😃 )

You are right as usual Michael! Thanks for the extra detail, much appreciated. Yeah, I think I removed the note as an afterthought when adding the 4.15 RN. Whoops!

**Pull request merged**
