### PR TITLE
Remove ExperimentalCriticalPodAnnotation from featureflags

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/api/pull/515

### CODE REVIEW

**Comment by mburke5678** [comment]
@rphillips PTAL

**Comment by mburke5678** [comment]
@rphillips PTAL

**Comment by mburke5678** [comment]
@jhou1 You have reviewed the feature gates topic for me in the past. Is this an issue you can review? Removing `ExperimentalCriticalPodAnnotation` for 4.3.

**Comment by mburke5678** [comment]
@rphillips PTAL

**Comment by mburke5678** [comment]
@jhou1 @rphillips  Please take a look at this small change.

**Comment by jhou1** [comment]
Not an area I'm familiar with, but with https://github.com/openshift/api/pull/515 this looks good. 
@sunilcio @xingxingxia PTAL.

**Comment by xingxingxia** [comment]
LGTM. CC @zhouying7780

**Pull request merged**
