### PR TITLE
OSDOCS-1100: Removing manual restart requirement for 4.5

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1100

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@marun This is just removing any references for 4.5 that we had to needing a manual restart after upgrading to a version for the first time that supports auto rotation of the service CA. Can you confirm that there's no reason we'd need this anymore for 4.5?

**Comment by jboxman** [comment]
@bergerhoffer LGTM

**Comment by bergerhoffer** [comment]
Hi @barleyer, can you please review this? It's just removing references in 4.5 to having to do the manual restart. Thanks!

**Pull request merged**
