### PR TITLE
OBSDOCS-975 - Logging 5.8.6 Release Notes

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Logging Z-Stream Release Notes - 5.8.6
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-975

Fix Version: 4.12, 4.13, 4.14, 4.15

Doc Preview: https://75243--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-8-release-notes#logging-release-notes-5-8-6_logging-5-8-release-notes

SME Review: @periklis 
QE Review: @anpingli 
Peer Review: @mburke5678

### CODE REVIEW

**Review by periklis — CHANGES_REQUESTED** [review]
Missing bug fixes: LOG-5392, LOG-5402

**Comment by kabirbhartiRH** [comment]
Here too, [LOG-5392](https://issues.redhat.com/browse/LOG-5392) and [LOG-5402](https://issues.redhat.com/browse/LOG-5402) should be enhancements and not bugs.

**Comment by mburke5678** [comment]
@shreyasiddhartha One comment. Otherwise, [pending the issue](https://github.com/openshift/openshift-docs/pull/75243#issuecomment-2085172299) with [LOG-5402](https://issues.redhat.com//browse/LOG-5403) and LOG-5392, LGTM.

**Review by jldohmann — APPROVED** [review]
nice work! lgtm

**Comment by jldohmann** [comment]
going to test a new bot thing with this PR...we'll see if it works 🤞

**Comment by jldohmann** [comment]
/cherrypick enterprise-4.15 enterprise-4.14 enterprise-4.13 enterprise-4.12

**Comment by jldohmann** [comment]
going back to individual cherrypicks for older versions

**Pull request merged**
