### PR TITLE
OCPBUGS-37574: Updated the network multiple interface mapping example

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.14+

Issue:
* [OCPBUGS-37574](https://issues.redhat.com/browse/OCPBUGS-37574)
* [OCPBUGS-37542](https://issues.redhat.com/browse/OCPBUGS-37542)

Link to docs preview:
[Configuration for an OVN-Kubernetes additional network mapping](https://79456--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/multiple_networks/configuring-additional-network.html#configuring-additional-network_configuration-additional-network-interface)

- [x] SME has approved this change.
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
Looks good to me, thanks!

**Comment by mburke5678** [comment]
@dfitzmau LGTM, pending QE review.

**Review by Srivaralakshmi — COMMENTED** [review]
lgtm

**Pull request merged**
