### PR TITLE
OCPBUGS#14422: move greenboot set up to install

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13, 4.14

Issue:
https://issues.redhat.com/browse/OCPBUGS-14422

Link to docs preview:
https://61665--docspreview.netlify.app/microshift/latest/microshift_install/microshift-greenboot.html

QE review:
N/A, docs plumbing

### CODE REVIEW

**Review by skrthomas — APPROVED** [review]
/lgtm

**Review by kelbrown20 — COMMENTED** [review]
Updates lgtm!

**Pull request merged**
