### PR TITLE
CNV-46293 to 4.16

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves https://issues.redhat.com/browse/CNV-46293 for 4.16

https://github.com/openshift/openshift-docs/pull/80340 cherrypicked to 4.16

CNV 4.16
OCP 4.16

Preview: https://80401--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/post_installation_configuration/virt-configuring-higher-vm-workload-density.html

### CODE REVIEW

**Comment by mburke5678** [comment]
@sbeskin-redhat LGTM. We no longer need https://github.com/openshift/openshift-docs/pull/80350?

**Comment by sbeskin-redhat** [comment]
@mburke5678 No, we don't need it. I've fixed the problem in this PR.

**Pull request merged**
