### PR TITLE
BZ2006232: add cloud.redhat.com to the list

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applies to 4.8+

https://bugzilla.redhat.com/show_bug.cgi?=2006232

[Docs preview](https://deploy-preview-39204--osdocs.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall)

Requires QE ack from @JoaoFula

### CODE REVIEW

**Comment by gpei** [comment]
Sorry, I don't test `Telemetry` nor `insights-operator`, please find the proper QE for that

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
