### PR TITLE
OSDOCS-12159: adds 4.15.38 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15

Issue:
[OSDOCS-12159](https://issues.redhat.com/browse/OSDOCS-12159)

Link to docs preview:
[4-15-38-dp_release-notes](https://84673--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes.html#microshift-4-15-38-dp_release-notes)

QE review:
 - NA. stock text, no other changes.

### CODE REVIEW

**Comment by aravipra** [comment]
@adellape
Checking if the peer review is done? The peer review done label is not added yet.

**Review by adellape — APPROVED** [review]
LGTM 👍

**Pull request merged**
