### PR TITLE
adding conditionals

### PR DESCRIPTION
**Pull request by kalexand-rh**
Follow up from https://github.com/openshift/openshift-docs/pull/10418

This note won't work on online and dedicated, so I'm getting more information for those versions.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jeremyeder said on IRC that this note doesn't apply to online and should be removed. @BigN provided the limits and suggested limit for dedicated in an email.

@openshift/team-documentation, PTAL :smile_cat:

**Comment by ahardin-rh** [comment]
LGTM :+1:

**Pull request merged**
