### PR TITLE
OSDOCS-3940 Release Notes GCP VPC installation

### PR DESCRIPTION
**Pull request by bscott-rh**
https://issues.redhat.com/browse/OSDOCS-3940 Release Notes

Version(s):
4.12

Link to docs preview: https://54594--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-gcp-shared-vpc

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei please take a look at these release notes for GCP shared VPC. thank you

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by sjstout** [comment]
LGTM! In this case, QE verified almost exactly the same text in the first paragraph of this PR:[ ](https://github.com/openshift/openshift-docs/pull/51171)
This PR can be merged without additional QE acks.

**Pull request merged**
