### PR TITLE
RHDEVDOCS 5172 Adding sections from main to GitOps-docs 1.9 branch and shallow restructure

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
Version(s): gitops-docs, gitops-docs-1.9, gitops-docs-1.10

Issue:
[RHDEVDOCS-5172](https://issues.redhat.com//browse/RHDEVDOCS-5172)

Link to docs preview: https://65086--docspreview.netlify.app/openshift-gitops/latest/understanding_openshift_gitops/what-is-gitops.html

Peer review: @Preeticp, @mramendi
PM review: @harrietgrace

Additional Info: While it is a size XL there is no significant new content. Being a shallow restructure, most of the size is due to the creation of multiple directories and moving assemblies and modules into them. These files are seen in the PR as new but the content is all from the pre-existing assemblies/modules. Only necessary edits were made to the metadata and anchor IDs to rectify the legacy content errors to keep them in line with the OCP docs, mod docs, and RH SSG guidelines.

This is a restructure that is part of enabling the standalone documentation set for OpenShift GitOps. It was approved by the PM and Content Strategist. It does not affect the main at all, only gitops-docs, gitops-docs-1.9, and gitops-docs-1.10. The PR does not change documentation content, except copying modules or assemblies from the main that were already reviewed for merging to the main.

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@Preeticp and @mramendi: could you please do a peer review ack on this PR? Thank you!

**Comment by Srivaralakshmi** [comment]
Hi, @harrietgrace Can you please approve this PR so that I can go ahead and request a merge for the 1.9 branch? TY!

**Review by mramendi — APPROVED** [review]

**Comment by Preeticp** [comment]
Looks good to me, suggest Security, Observability, Troubleshooting as the top level headings on d.o.c, based on capacity, or we can take it up in the detailed restructure we plan for later.

**Pull request merged**
