### PR TITLE
Minor updates to Optimizing storage section

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses:
https://github.com/openshift/openshift-docs/issues/24918
https://github.com/openshift/openshift-docs/issues/24917
https://github.com/openshift/openshift-docs/issues/24701

Preview build: https://scale-storage--ocpdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/optimizing-storage.html#specific-application-storage-recommendations

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@lautou PTAL. Thanks!

**Review by sheriff-rh — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
