### PR TITLE
[BZ2104920]: Convert disconnected cluster to a connected cluster

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2104920

Link to docs preview:

Additional information:

QE: @jinyunma

### CODE REVIEW

**Comment by xenolinux** [comment]
@jinyunma Could you please confirm if the version (4.6+) is correct for this PR?

**Comment by jinyunma** [comment]
@xenolinux I checked that the procedures of converting disconnected cluster to a connect cluster has already been described in doc https://docs.openshift.com/container-platform/4.10/post_installation_configuration/connected-to-disconnected.html#connected-to-disconnected-restore_connected-to-disconnected,  do we still need new chapter to address it?

**Comment by xenolinux** [comment]
> @xenolinux I checked that the procedures of converting disconnected cluster to a connect cluster has already been described in doc https://docs.openshift.com/container-platform/4.10/post_installation_configuration/connected-to-disconnected.html#connected-to-disconnected-restore_connected-to-disconnected, do we still need new chapter to address it?

I checked the steps from https://access.redhat.com/solutions/6966995. The procedure is almost the same. So I think you are right we can skip adding the chapter on converting a disconnected cluster to a connected cluster.

**Comment by xenolinux** [comment]
Closing this PR and a bug as per https://github.com/openshift/openshift-docs/pull/47780#issuecomment-1188526717

**Pull request closed without merging**
