### PR TITLE
GH#49816: fixes the label namespace command

### PR DESCRIPTION
**Pull request by tonytheleg**
Version(s):

PR applies to 4.10 and 4.11 looking at the docs online. Issue was opened against 4.11

Issue:

#49816

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tonytheleg** [comment]
@openshift/team-documentation if you could please take a look. Let me know if I missed any steps. Thanks!

**Review by bergerhoffer — COMMENTED** [review]
@tonytheleg This looks great to me! Thanks for your contribution :tada:

**Comment by bergerhoffer** [comment]
@DebarghoGhosh Could you help me with who a good QE person would be to review this? Thanks!

**Comment by varshab1210** [comment]
LGTM, thanks!

**Comment by bergerhoffer** [comment]
@varshab1210 You're right, it looks after this PR was opened, someone else merged a PR that fixed this issue already. 

Thanks for letting us know - closing this PR.

**Pull request closed without merging**
