### PR TITLE
set env vars on oc new-app of template

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but merge needs to wait for the actual new-app updates.

**Comment by gabemontero** [comment]
sounds great - thanks @bparees 

fyi - the code changes are https://github.com/openshift/origin/pull/12048

I pulled in @csrwng (dividing up PR reviews, etc.)

**Comment by gabemontero** [comment]
The code changes have merged.

@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
LGTM. Thanks!

**Comment by ahardin-rh** [comment]
Adding a to_followup label, as I should make style edits to this page as a whole per our updated style guidelines.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/new_app.adoc#dev-guide-new-app[Creating New Applications]
|Noted that any `BuildConfig` objects created as part of `oc new-app` processing will not be updated with environment variables passed via the `-e|--env` argument.
%

**Comment by adellape** [comment]
@ahardin-rh Do you think https://github.com/openshift/openshift-docs/pull/3389 counts as the follow-up to this one, too?

**Comment by ahardin-rh** [comment]
@adellape I think I had some extra style edits in mind, so I will keep the to_followup label in place for now and get a PR going soon.

**Comment by ahardin-rh** [comment]
Follow-up complete. Removing that label.

**Pull request merged**
