### PR TITLE
Removed tech preview status from kuryr

### PR DESCRIPTION
**Pull request by ariordan-redhat**
[BZ 1660517](https://bugzilla.redhat.com/show_bug.cgi?id=1660517)
Removed tech preview status for Kuryr docs
Changes apply to 3.11 only.

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
@ariordan-redhat, will you put a link to the bug in comment 0? It's easier that way.

**Comment by aheslin** [comment]
@ariordan-redhat Please don't merge until OCP product management (Marc Curry) gives the ok.

**Comment by vikram-redhat** [comment]
@ariordan-redhat - I am closing this PR and removing the labels in accordance with PM's direction.

**Comment by vikram-redhat** [comment]
To be merged and CPed on Mar 12th.

@ariordan-redhat @ahardin-rh @sheriff-rh

**Comment by vikram-redhat** [comment]
@ariordan-redhat @ahardin-rh I have updated @ariordan-redhat 's commit and using squash and merge to merge this.

This is the first time I am trying to use two things: Editing someone else's branch directly and using squash and merge via the UI :)

**Pull request merged**
