### PR TITLE
BZ#2243845: typo fix

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.10+

Issue: [CNV-33916](https://issues.redhat.com//browse/CNV-33916), [BZ#2243845](https://bugzilla.redhat.com/show_bug.cgi?id=2243845)

Link to docs preview: [Configuring systemd-journald for OpenShift Logging](https://66681--docspreview.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-systemd#cluster-logging-systemd-scaling_cluster-logging-systemd)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM!

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead.

**Review by abhatt-rh — COMMENTED** [review]
@apinnick @xenolinux : Peer review LGTM!

**Pull request merged**
