### PR TITLE
Add documentation for Azure configuration

### PR DESCRIPTION
**Pull request by abn**
Relates-to: openshift/openshift-ansible#7745

### CODE REVIEW

**Comment by abn** [comment]
@bfallonf can we get this reviewed and merged? The installer changes have been merged.

**Comment by bfallonf** [comment]
Thanks @abn . I can see the origin PR, but is this related to any current OpenShift work? Asking so that I can attach this to a trello card or BZ, but also so that I can see any QA efforts and determine what needs to be done.

**Comment by abn** [comment]
@bfallonf I do not think there is a specific card/bz that tracks the work. However, this does relate to [BZ#1535391](https://bugzilla.redhat.com/show_bug.cgi?id=1535391#c45). I suspect the change would also resolve a few other issues around storage class and azure provider configuration.

**Comment by abn** [comment]
@bfallonf note that the change has not been cherry-picked onto 3.9 branch yet.

**Comment by bfallonf** [comment]
Hi @abn . This took a bit, but I've spoken to QA and this can probably be merged, and taken into the 3.10 docs.

I'll do a followup after, to set up some docs standards, but thanks, this is a good pick for the Azure topics.

**Pull request merged**
