### PR TITLE
Correct vSphere version for OCP 4.17

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.17+

Issue: Update vSphere version for OCP 4.17

Link to docs preview: https://80713--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gnufied @duanwei33 @gcharot

### CODE REVIEW

**Review by jneczypor — COMMENTED** [review]
LGTM.
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by gcharot** [comment]
lgtm

**Comment by lpettyjo** [comment]
> Should it be: In {product-title} 4.15 -> In {product-title} 4.17?

 @duanwei33 Good catch! Fixed now. Thanks!

**Pull request merged**
