### PR TITLE
ROX-18086: Clarify FIPS readiness

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to `rhacs-docs`
- Cherrypick to `rhacs-docs-4.0`

[Issue](https://issues.redhat.com/browse/ROX-18086)

[Link to docs preview
](https://61783--docspreview.netlify.app/openshift-acs/latest/release_notes/40-release-notes.html#fips-ready-rn40)

QE review: (**ACS has no QE, approved by SME**) 
- [x] QE has approved this change.

Additional information:

- ACS doesn't have a formal "change management" process like OpenShift.

### CODE REVIEW

**Comment by knewcomerRH** [comment]
approved. Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
