### PR TITLE
Fixing malformed link in WMCO docs

### PR DESCRIPTION
**Pull request by mburke5678**
Fixing malformed link added via https://github.com/openshift/openshift-docs/pull/48660/

Hat tip @bergerhoffer 

[Enabling Windows container workloads](http://file.rdu.redhat.com/~mburke/winc-cluster-proxy-fix-take-3/windows_containers/enabling-windows-container-workloads.html)
[Scheduling Windows container workloads](http://file.rdu.redhat.com/~mburke/winc-cluster-proxy-fix-take-3/windows_containers/scheduling-windows-workloads.html)

### CODE REVIEW

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by bergerhoffer** [comment]
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
