### PR TITLE
Adding description of MaxCSIVolumeCountPred

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/32174

Preview: https://deploy-preview-32714--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-default.html#default-predicates_nodes-scheduler-default

### CODE REVIEW

**Comment by mburke5678** [comment]
@kasturinarra Is this an issue you can review for QE? Thank you very much.

**Review by damemi — COMMENTED** [review]
/lgtm
but since all predicates are deprecated now, and won't be configurable soon, it might be better to backport this as well

**Comment by mburke5678** [comment]
@damemi Should we remove the predicates that were deprecated for  MaxCSIVolumeCount?

MaxEBSVolumeCount
MaxGCEPDVolumeCount
MaxAzureDiskVolumeCount
MaxCinderVolumeCount

**Comment by damemi** [comment]
@mburke5678 no they haven't been removed yet so we should still document them. I'm just pointing out that every predicate will soon be unavailable once Policy config is officially removed (not just the ones related to this change)

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
