### PR TITLE
[OSDOCS-4466, OSDOCS-4407]: Backporting CCO feature announcements into 4.10.z

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.10

Issue:
[OSDOCS-4466](https://issues.redhat.com//browse/OSDOCS-4466) and [OSDOCS-4407](https://issues.redhat.com//browse/OSDOCS-4407)

Link to docs preview:
- [4.10.40](http://file.rdu.redhat.com/~jrouth/OSDOCS-4466-4407-4.10-rn-cco-backports/release_notes/ocp-4-10-release-notes.html#ocp-4-10-40-notable-technical-changes)
- [4.10.41](http://file.rdu.redhat.com/~jrouth/OSDOCS-4466-4407-4.10-rn-cco-backports/release_notes/ocp-4-10-release-notes.html#ocp-4-10-41-notable-technical-changes)

QE review:
(see change mgmt acks below)

Additional information:
- Must follow #53487
- Must cherrypick #52348 and #52380 into 4.10 with this merge.
- Requires change management acks:
  - [x] Andrew Butcher
  - [x]  Jianping Shu
  - [x] @sferich888
  - [x] @kalexand-rh
  - [x] @julienlim

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@abutcher and @jianping-shu these are the 4.10 announcements for the CCO backports from a little while ago, PTAL

**Comment by kalexand-rh** [comment]
LGTM

**Review by abutcher — APPROVED** [review]
LGTM

**Comment by jianping-shu** [comment]
LGTM

**Comment by julienlim** [comment]
lgtm

**Pull request merged**
