### PR TITLE
OBSDOCS-992: Fix ClusterRole for Kubernetes attributes processor

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.12, 4.13, 4.14, 4.15, 4.16

Issue:

https://issues.redhat.com/browse/OBSDOCS-992

Link to docs preview: https://74820--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]

**Review by IshwarKanse — APPROVED** [review]

**Review by maxwelldb — APPROVED** [review]
Looks fine to me. Check with a CS if you're unsure about change management.

**Comment by michaelryanpeter** [comment]
@max-cx Would you please confirm the verdict from your CS in regards to change management?

The content LGTM, I just want to verify that CM is not required. Thanks!

**Comment by max-cx** [comment]
@michaelryanpeter, apologies for the delay, I had to prioritize release-related Jiras.

My CS has confirmed that no CM needed her.

**Pull request merged**
