### PR TITLE
BZ2030784: remove ipam from the host-device CNI plug-in configuration

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
For 4.9+

https://bugzilla.redhat.com/show_bug.cgi?id=2030784

[Docs preview](https://deploy-preview-40159--osdocs.netlify.app/openshift-enterprise/latest/networking/multiple_networks/configuring-additional-network.html#nw-multus-host-device-object_configuring-additional-network)

Requires ack from @weliang1

### CODE REVIEW

**Comment by weliang1** [comment]
@chinmayi-chandrasekar I still see ipam-type: DHCP in https://github.com/openshift/openshift-docs/blob/4c5fea9ec39cf71de0672f1443a9ffcaa8f1708e/modules/nw-multus-host-device-object.adoc

**Comment by chinmayi-chandrasekar** [comment]
> @chinmayi-chandrasekar I still see ipam-type: DHCP in https://github.com/openshift/openshift-docs/blob/4c5fea9ec39cf71de0672f1443a9ffcaa8f1708e/modules/nw-multus-host-device-object.adoc

Comment addressed.

**Comment by mburke5678** [comment]
/enterprise-4.9

**Pull request merged**
