### PR TITLE
BZ1973602: Update operator conditions and operator overrides

### PR DESCRIPTION
**Pull request by michaelryanpeter**
4.8+
https://bugzilla.redhat.com/show_bug.cgi?id=1973602

Docs preview:
1. [About Operator conditions and Upgradable condition](https://deploy-preview-35215--osdocs.netlify.app/openshift-enterprise/latest/operators/understanding/olm/olm-operatorconditions.html#olm-about-operatorconditions_olm-operatorconditions)
2. [Overriding Operator conditions](https://deploy-preview-35215--osdocs.netlify.app/openshift-enterprise/latest/operators/admin/olm-managing-operatorconditions.html#olm-supported-operatorconditions_olm-managing-operatorconditions)

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@vdinh@redhat.com: PTAL

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by michaelryanpeter** [comment]
@jianzhangbjz: Ready for QE review. PTAL.

**Comment by stevsmit** [comment]
LGTM.

**Pull request merged**
