### PR TITLE
Deprecation of openshift_logging_curator_run_timezone isn't documented

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1679248

### CODE REVIEW

**Comment by mburke5678** [comment]
@josefkarasek PTAL

**Review by josefkarasek — CHANGES_REQUESTED** [review]
The doc still mentions `openshift_logging_curator_run_timezone`

**Comment by mburke5678** [comment]
@josefkarasek Sorry! (Getting confused; too much going on!)
Removed `openshift_logging_curator_run_timezone`.

**Comment by josefkarasek** [comment]
@mburke5678 alright! Thank you. Can you also update 3.10 docs?

**Comment by josefkarasek** [comment]
@mburke5678 no need for porting this to 3.10. The change occurred in 3.11

**Comment by mburke5678** [comment]
@xltian PTAL for 3.11.

**Comment by xltian** [comment]
@anpingli Will work on it.

**Comment by anpingli** [comment]
Yes, it works.

**Pull request merged**
