### PR TITLE
4.15 - OADP-4941: Removing OADP 1.2 references from docs

### PR DESCRIPTION
**Pull request by anarnold97**
### CHERRY PICK for 4.15

Cherry Picked from 0725b69e5360c23a5993fb76ced0f85cfe7de275 xref: https://github.com/openshift/openshift-docs/pull/82722

### JIRA

* [OADP-4941](https://issues.redhat.com/browse/OADP-4941)

We are removing OADP 1.2 references as it is no longer supported.
Also, support are seeing people looking at the docs and asking about OADP 1.2 support
We are only removing the OADP 1.2 references and including the OADP support dates for all versions.

### Version(s):

* OCP 4.15

### Link to docs preview:

* [OpenShift API for Data Protection support](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-intro#oadp-operator-supported_oadp-api)

* Removing DPA 1.2 & changing title of DPA 1.3
    * [OADP - AWS](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws)
    * [OADP - Azure](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure)
    * [OADP - Google Cloud Platform](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp)
    * [OADP - OpenShift Data Foundation](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs)  

* Data Mover
    * [Data Mover 1.3 renamed](https://84526--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover) - renamed with Data Mover 1.2 docs removed

### QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by anarnold97** [comment]
FYI - @jeana-redhat

**Review by xenolinux — COMMENTED** [review]
LGTM

**Comment by anarnold97** [comment]
thanks

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM; merging.

**Comment by anarnold97** [comment]
Thanks

**Pull request merged**
