### PR TITLE
Use oc logs with the registry deployment config

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/openshift/openshift-docs/issues/1645

@tnguyen-rh PTAL

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@kargakis LGTM.  This is for 3.2, right?

**Comment by kargakis** [comment]
Not necessarily but I would guess every fix we can squeeze in is ok

**Comment by tnguyen-rh** [comment]
@kargakis 
I've added the label for 3.1.  How about 3.0?

**Comment by kargakis** [comment]
This was added in 3.1.1.2. So I guess it's 3.2?

**Comment by tnguyen-rh** [comment]
[rev_history]
|link:../install_config/install/deploy_registry.html[Installing -> Deploying a Docker Registry]
|Used `oc logs` in the link:../install_config/install/deploy_registry.html#access-pushing-and-pulling-images[deployment configuration example].
%

**Comment by vikram-redhat** [comment]
@tnguyen-rh @adellape - there is a reference to OSE 3.2 in this. Should this not be tagged with enterprise-3.2?

**Comment by adellape** [comment]
@vikram-redhat @tnguyen-rh According to @kargakis above it was added in 3.1.1.2, so that would warrant branch/enterprise-3.1 + Next Release.

I tried this on a 3.2 machine and it seemed to work as described (pod logs looked like they matched up with latest dc logs). On a 3.1.1.6 machine, it looks like it's showing the latest deployment logs, but since it was successful there's nothing to show (as mentioned in https://docs.openshift.com/enterprise/3.1/dev_guide/deployments.html#viewing-deployment-logs):

http://pastebin.test.redhat.com/358308

When the deployment was running (or when there's a failed deployment), the `oc logs dc/<name>` showed deployment logs. But from what this PR is suggesting, I would have expected to see the same pod logs from the `oc logs dc/docker-registry` for a successful deployment (like I'm seeing in 3.2).

If I'm misunderstanding the described new feature here, please correct me.

**Comment by vikram-redhat** [comment]
@adellape, @tnguyen-rh , @kargakis 

I was looking at this particular line:

. If your registry was initially deployed on {product-title}
ifdef::openshift-enterprise[]
3.2
endif::[]
ifdef::openshift-origin[]
1.1.2
endif::[]
or later, update the scheme used for the registry's readiness probe from HTTP to HTTPS:

If we merge it in for the next release it will be incorrect? Does this need to be fixed to say 3.1.1.6 instead?

**Comment by adellape** [comment]
@vikram-redhat That is from https://github.com/openshift/openshift-docs/pull/1728 (marked for enterprise-3.2/Future Release) and needs to stay out of the 3.1 docs.

**Comment by kargakis** [comment]
> On a 3.1.1.6 machine, it looks like it's showing the latest deployment logs, but since it was successful there's nothing to show (as mentioned in https://docs.openshift.com/enterprise/3.1/dev_guide/deployments.html#viewing-deployment-logs):

Great for digging this out, we need to update it too.:) Complete deployments should return pod logs.

**Comment by tnguyen-rh** [comment]
@adellape 
Thanks for the detective work.  To summarize, the actual funtionality will be user-visible in 3.2.  I've adjusted te labels/milestone accordingly.  Updates/correction welcome.

**Pull request merged**
