### PR TITLE
OBSDOCS-124: Added details for ES8 in the log forwarder example

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OBSDOCS-124

Link to docs preview:
https://69280--ocpdocs-pr.netlify.app/openshift-enterprise/latest/logging/log_collection_forwarding/log-forwarding#cluster-logging-collector-log-forward-es_log-forwarding

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jcantrill** [comment]
/lgtm

Side note nit: we could likely drop all the reference to internal versus external since internal is just the default storage that requires no management in CLF other then using "defaul"

**Review by cbippley — COMMENTED** [review]
LGTM!

**Pull request merged**
