### PR TITLE
[WIP] Added details for non-interactive install

### PR DESCRIPTION
**Pull request by tpoitras**
Bug 1270619
 [DOCS] [3.1] [Feature] Document the non-interactive Installer for 3.1 

Documenting how to create a config file for non-interactive install.

Just missing details on how to actually specify this file for installation. Have pinged SME in Trello card: https://trello.com/c/fHy2DzMN

:key:

### CODE REVIEW

**Comment by adellape** [comment]
@tpoitras For your consideration: https://github.com/openshift/openshift-docs/pull/1128

Pretty build (internal):

http://file.rdu.redhat.com/~adellape/103015/31_quickinstall/install_config/install/quick_install.html

Basically I pulled in your work in this PR as I was working on updates for the Quick Install method, and the info on the install cfg file and running an unattended install seemed like it would fit well inline w/ the other ways you can use the quick installer.

Let me know how you feel about this approach. If you're into it, we can close this PR (https://github.com/openshift/openshift-docs/pull/1126) and continue in https://github.com/openshift/openshift-docs/pull/1128.

**Comment by tpoitras** [comment]
@adellape :+1: 

Most excellent merger of content here. I think it makes total sense to keep these together. 

I vote yes to close this PR (#1126) and continue in #1128

**Comment by tpoitras** [comment]
Updated Bug 1270619 with info on this PR being closed in favour of #1128

**Comment by adellape** [comment]
Closed in favor of https://github.com/openshift/openshift-docs/pull/1128

**Pull request closed without merging**
