### PR TITLE
ROX-20500: Bump Scanner-DB memory requests to match new default.

### PR DESCRIPTION
**Pull request by porridge**
Version(s): ACS `master` branch

Issue: [ROX-20500](https://issues.redhat.com/browse/ROX-20500)

Link to docs preview:  https://67004--docspreview.netlify.app/openshift-acs/latest/installing/acs-default-requirements#default-requirements-central-services-scanner_acs-default-requirements

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by porridge** [comment]
Please review @openshift/team-documentation

**Comment by mburke5678** [comment]
@porridge Does this need to be cherrypicked?

**Comment by porridge** [comment]
No, this just reflects a change done in current ACS master, so I'm assuming the next time we branch for an ACS release this will be picked up automagically, @mburke5678

**Comment by kcarmichael08** [comment]
> No, this just reflects a change done in current ACS master, so I'm assuming the next time we branch for an ACS release this will be picked up automagically, @mburke5678

Hi @porridge , our docs branching works a bit differently. Is this going into all the releases currently live? (3.74, 4.0, 4.1, 4.2, and upcoming 4.3?) If so then we need to cherry pick it into those branches. The `rhacs-docs` branch doesn't actually get published, it's the main repo, then the numbered branches are what gets published.

**Comment by porridge** [comment]
@kcarmichael08 no, this change **does not** apply to any of the releases you listed. The CPU bump will only appear in the product in 4.4 (or 5.0, if that's the number we'll choose).

**Pull request merged**
