### PR TITLE
OCPBUGS#11576: Update the operator SDK version in OCP 4.13

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.13 only

Issue: https://issues.redhat.com/browse/OCPBUGS-11576

Link to docs preview: https://58971--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/osdk/cli-osdk-install.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by KeenonLee — COMMENTED** [review]
/lgtm

**Comment by adellape** [comment]
This has been addressed via the https://github.com/openshift/openshift-docs/pull/59006 cherrypick that I forgot to create from the `main` PR https://github.com/openshift/openshift-docs/pull/56753. 

@xenolinux My apologies, but this PR can be closed.

**Pull request closed without merging**
