### PR TITLE
Jira:OSDOCS-2159 Update Cluster audit logging

### PR DESCRIPTION
**Pull request by kmccarron-rh**
Jira: https://issues.redhat.com/browse/OSDOCS-2159

Direct link to Cluster audit logging section:
https://deploy-preview-32634--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-service-definition.html#rosa-sdpolicy-cluster-audit-logging_rosa-service-definition

Minor update to Logging section:
https://deploy-preview-32634--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-service-definition.html#rosa-sdpolicy-logging_rosa-service-definition

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
Hi @okashi18.  I replaced the cluster audit logging section with the updated text. Please review. thanks!

**Comment by kmccarron-rh** [comment]
Minor update to the first occurrence Amazon CloudWatch reference.

**Comment by 0kashi** [comment]
LGTM

**Comment by kmccarron-rh** [comment]
@yufchang Please QE review 
@sfortner-RH  Please Peer review

**Comment by kmccarron-rh** [comment]
This is a small one that is SME reviewed.
@yufchang Please QE review
@sfortner-RH Please Peer review

**Review by sfortner-RH — APPROVED** [review]
LGTM! No need to take up time for QE testing. These are minor doc changes and don't involve any new functionality or steps that need tested.  So we can give QE a breather to focus on more high-priority tasks. Merging card.

**Pull request merged**
