### PR TITLE
Add information about expiration to service serving certificate secrets

### PR DESCRIPTION
**Pull request by soltysh**
@ahardin-rh ptal, I doubt I can add more info than just this from https://trello.com/c/1jpkpbZZ/843-2-add-controller-to-regenerate-service-serving-certificates

@mfojtik @deads2k fyi

### CODE REVIEW

**Comment by soltysh** [comment]
[(2) Add controller to regenerate service serving certificates](https://trello.com/c/1jpkpbZZ/843-2-add-controller-to-regenerate-service-serving-certificates)

**Comment by mfojtik** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thanks! I will make some very minor follow-up edits in a separate PR.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/secrets.adoc#dev-guide-secrets[Secrets]
|Added information about expiration to the xref:../dev_guide/secrets.adoc#service-serving-certificate-secrets[Service Serving Certificate Secrets] section.
%

**Pull request merged**
