### PR TITLE
don't be so specific about the jenkins version, it keeps changing

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by ahardin-rh** [comment]
@bparees Thanks! Looks good! We are starting to substitute OpenShift with {product-title}. You can make that swap if you're up for it, or we (the docs team) can handle it. 

Can you please check my labels and milestone? I am assuming this can be pulled into our next weekly release. Please correct me if I'm wrong. Thanks!

**Comment by bparees** [comment]
i went ahead and replaced it everywhere except in "openshift pipeline plugin" because that's the formal name of that plugin, not part of the openshift product.

milestones look ok to me, weekly release should be fine.

**Comment by ahardin-rh** [comment]
@bparees Thanks!  :thumbsup:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#versions[Other Images -> Jenkins]
|Removed specific reference to Jenkins version and added a link to the LTS Changelog.
%

**Pull request merged**
