### PR TITLE
BZ#1851676 Adjust Azure UPI disk size to the same used in IPI

### PR DESCRIPTION
**Pull request by codyhoag**
Completed via https://bugzilla.redhat.com/show_bug.cgi?id=1850714

Docs BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1851676

### CODE REVIEW

**Comment by codyhoag** [comment]
@fabianofranz I just noticed the linked bug was targeted for 4.6. Should this hold for the 4.6 docs?

**Comment by fabianofranz** [comment]
@codyhoag This will be backported to previous versions. ;)

**Comment by codyhoag** [comment]
@jianlinliu can you confirm this Azure UPI update?

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
