### PR TITLE
fix errors in patch release notes

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
4.5

Issue: none

[Link to docs preview:
](https://82765--ocpdocs-pr.netlify.app/openshift-acs/latest/release_notes/45-release-notes)
QE review: **N/A**
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — APPROVED** [review]
LGTM

**Review by jldohmann — APPROVED** [review]
James beat me to it 😄 but lgtm too

**Comment by GroceryBoyJr** [comment]
Woops, sorry @jldohmann but I'm very glad your eyes are on it too.

**Comment by kcarmichael08** [comment]
Thank you both :D

**Pull request merged**
