### PR TITLE
[RHACS] Update Debian support

### PR DESCRIPTION
**Pull request by RTann**
Update Debian OSes

Cherrypick into `rhacs-docs-4.5`

Preview: https://78610--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/examine-images-for-vulnerabilities.html#supported-operating-systems_examine-images-for-vulnerabilities

### CODE REVIEW

**Review by dcaravel — APPROVED** [review]

**Comment by RTann** [comment]
Thanks @agantony 

Can you also help merge this and cherry-pick it into the 4.5 branch? I'm not sure if I have permission to do so

**Comment by agantony** [comment]
> Thanks @agantony
> 
> Can you also help merge this and cherry-pick it into the 4.5 branch? I'm not sure if I have permission to do so

Unfortunately, I do not have merge access. I will the merge review label and someone from the team is gonna pick it up.

**Comment by bscott-rh** [comment]
Merge review LGTM

**Pull request merged**
