### PR TITLE
OSDOCS-11694-RN Adding 2 missed Nutanix release notes

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-11694
https://issues.redhat.com/browse/OSDOCS-11890

Link to docs preview:
https://82876--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-installation-nutanix-gpus_release-notes
https://82876--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-installation-nutanix-disks_release-notes

QE review:
- [X] QE has approved this change.

CM Acks:
- [x] DPM
- [x] PX
- [X] PM and Eng. via slack
- [x] CS

### CODE REVIEW

**Comment by bscott-rh** [comment]
@sgaoshang PTAL when you have a moment. thank you

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by bscott-rh** [comment]
@sferich888 @kalexand-rh please take a look at this late release note announcing two Nutanix features for 4.17 from a change management perspective. Eric, if you aren't the right person to look at this please tag someone else from PX. Thank you

**Comment by sstout-rh** [comment]
LGTM

**Pull request merged**
