### PR TITLE
OSDOCS-4879: Region Addition

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-4879](https://issues.redhat.com//browse/OSDOCS-4879)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4879

Link to docs preview:
ROSA: https://56171--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html
OSD: https://56171--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#regions-availability-zones_osd-service-definition

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @xueli181114 and @yuwang-RH! Can one of you please review this PR when you have the chance? I know the region isn't available yet, but I want to get the docs review and ready for release as soon as the region is live. Thanks!

**Comment by xueli181114** [comment]
LGTM

**Comment by jneczypor** [comment]
Hi @arendej! Can I please get PM review of this availability zone? Thank you!

**Review by arendej — APPROVED** [review]
.

**Review by arendej — COMMENTED** [review]
Melbourne is an opt-in region

**Comment by jneczypor** [comment]
Hi @arendej! I have fixed the region to be "opt-in". Can I please get final approval? Thanks!

**Review by arendej — APPROVED** [review]
lgtm (please note to hold publishing until the region is available)

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by cbippley** [comment]
@opayne1 Want to take a look?
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
