### PR TITLE
Slack notifications for Travis CI build failures

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Enables Slack notifications in the `forum-docs-review` channel for build failures.

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@pneedle-rh @bergerhoffer @adellape Can you review and merge?

**Review by adellape — APPROVED** [review]

**Comment by bergerhoffer** [comment]
@gaurav-nelson Is this going to add a notification in the slack channel for every PR that is opened (like the one I see in #forum-docs-review now for this PR)? If so, I was moreso just looking for notifications on if the actual branch broke after a "bad" merge. Most importantly main, but really any of supported branches here: https://app.travis-ci.com/github/openshift/openshift-docs/branches

**Comment by gaurav-nelson** [comment]
@bergerhoffer 
By default, notification is sent on all builds that pass. I missed out on setting the `on_success` string which resulted in the Slack notification.

- I've set it to `change` - It sends a notification when the build status changes, from pass to fail or from fail to pass.
- Another option is `never` - which doesn't send any notifications for passing builds.

Should I change it to `never` to only receive failure notifications ?

The build message you see in the channel is the default message, however, I've changed it to report the following:
```
- "Build %{result} for PR <%{pull_request_url}|#%{pull_request_number}>"
- "%{message}"
- "Branch: %{branch}"
- "Author: %{author}"
```
Line 1 includes the link for the failed build and the PR.
Line 2 includes the failure message, I'm not sure if its the message from the log, Travis docs don't mention the details.
Line 3 is the branch  the PR is targeting.
Line 4 is the Name of the PR author.

**Comment by pneedle-rh** [comment]
@gaurav-nelson hi! My view is that useful reporting in the channel would be to highlight when a build failure has made its way into the mainstream channel through a merge. I don't think that there is value in the Peer Review Squad needing to see notifications of all build failures in PRs that are not yet merged. The peer review requirement to check for build failures in the PR itself I think is suffice in that regard.

If it is somehow possible only to alert when a build failure is merged into the mainstream, that would be a beneficial alert. Then we could react to it quickly to prevent any PR that is based on that branch from seeing the same build failure and to revert any potential major issues in the live documentation.

**Comment by gaurav-nelson** [comment]
Thank you @pneedle-rh Yes, that makes sense. 
Yes, we can certainly only enable notifications if the builds are failing for specific branches when PR's are merged. 

@bergerhoffer @adellape thoughts?

**Comment by bergerhoffer** [comment]
> Thank you @pneedle-rh Yes, that makes sense.
Yes, we can certainly only enable notifications if the builds are failing for specific branches when PR's are merged.
>
> @bergerhoffer @adellape thoughts?

Yes that's exactly what I was hoping for!

Thanks @pneedle-rh for explaining this better than I was able to :smile:

**Comment by gaurav-nelson** [comment]
Thank you @pneedle-rh @bergerhoffer I've updated the script to:
- Send channel notifications only if builds fail on merge events for branches `main`, `enterprise-4.9`, and `enterprise-4.10`.
- Send channel notification when build change states from pass to fail or fail to pass.

Do we need to enable it for more branches?

**Comment by bergerhoffer** [comment]
Thanks @gaurav-nelson! I say that those 3 branches are fine to start with, but maybe after we test it out a bit, we could probably add it to all supported branches. Speaking of testing - how can we test this? I assume we have to merge the PR before being able to test. And do we just need to wait until some unfortunate soul accidentally breaks one of those branches, or should we actually introduce a (temporary) broken change to try it?

**Comment by pneedle-rh** [comment]
I thought of a scenario that might not get caught by this alert. When occasionally the Travis checks are not triggered for a PR, only one green tick is seen for "This branch has no conflicts with the base branch" and no line item is featured at all relating to the checks. In such situations there is not check failure notification. I think that is the most likely scenario where a PR would get merged without having been checked.

Is it possible for us to somehow prevent a PR from being merged at all unless there is a check in the PR and it has been successful? Or, if not, is it possible to somehow provide an alert also when a PR is merged that has not been checked, in addition to the alerting that we have discussed already?

**Comment by pneedle-rh** [comment]
Another aspect is that often `asciibinder build` errors and warnings are not picked up by the Travis checks. Often, `asciibinder build` errors are introduced in the mainstream branches. The errors can sometimes impact the live content rendering.

Would it be useful also to add an alert that signifies when `asciibinder build` errors (and potentially warnings too) are seen in a mainstream branch?

**Comment by gaurav-nelson** [comment]
Thanks @pneedle-rh for thinking it through. 
> Is it possible for us to somehow prevent a PR from being merged at all unless there is a check in the PR and it has been successful?

Yes, however, I will need to look into the mechanics of how to do that. I don't think it is too difficult.

> Would it be useful also to add an alert that signifies when asciibinder build errors (and potentially warnings too) are seen in a mainstream branch?
Sounds doable to me as well. However, I'll have to look into asciibinder related warnings and errors. Do you have any PRs or past PRs that cause Asciibinder related issues? 

Also, I'll go ahead an create a Google Doc to discuss this issue and any other updates we might want to add in checks.

**Comment by pneedle-rh** [comment]
@gaurav-nelson thank you!

**Pull request closed without merging**
