### PR TITLE
OSDOCS#9645: Updating the descheduler to be not supported in OKE

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-9645

Link to docs preview:
https://71557--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/oke_about#feature-summary

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ingvagabund** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@kasturinarra for review please. 

@gauravsingh85 need a sign-off from you on this as well when you get a chance.

Preview: https://71557--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/oke_about#feature-summary

**Comment by gauravsingh85** [comment]
Descheduler will continue to support OKE

**Comment by gauravsingh85** [comment]
LGTM

**Pull request merged**
