### PR TITLE
Bug 1303341, edited project request limit plugin information

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1303341

Follow-up to https://github.com/openshift/openshift-docs/pull/1476

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape PTAL. Thanks!

**Comment by ahardin-rh** [comment]
@tnguyen-rh @bfallonf @tpoitras PTAL also. Thanks!

**Comment by tnguyen-rh** [comment]
@ahardin-rh 
LGTM, although i have a doubt about the proper title-casing of "plug-in".

**Comment by ahardin-rh** [comment]
@tnguyen-rh Thanks! Yeah, I kept going back and forth on that, but settled with what [http://www.titlecase.com/](url) spit out at me.

**Comment by adellape** [comment]
"Plug-in" is how we've titlecased previously.

**Comment by ahardin-rh** [comment]
Passed QA. Mergin'.

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../admin_guide/managing_projects.html[Managing Projects]
|Added the link:../admin_guide/managing_projects.html#limit-projects-per-user[Limiting Number of Self-Provisioned Projects Per User] section.
%
|link:../install_config/configuring_admission_control.html[Configuring Admission Control Plug-ins] 
|Added a new link:../install_config/configuring_admission_control.html[Configuring Admission Control Plug-ins] page.
%
|link:../dev_guide/projects.html[Projects] 
|Added a Note box about project creation limits.
%

**Pull request merged**
