### PR TITLE
BZ-1822897: Adding --type of json and an alternative option

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.6 and 4.7

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1822897

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2022/BZ-1822897/cli_reference/openshift_cli/developer-cli-commands.html#patch

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund Can you confirm if this update (per the above BZ) is true/okay to make? This is only for 4.6 and 4.7

http://file.rdu.redhat.com/~ahoffer/2022/BZ-1822897/cli_reference/openshift_cli/developer-cli-commands.html#patch

**Comment by ingvagabund** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review? 

http://file.rdu.redhat.com/~ahoffer/2022/BZ-1822897/cli_reference/openshift_cli/developer-cli-commands.html#patch

**Comment by bergerhoffer** [comment]
@kalexand-rh Can I get an approval to CP this to 4.7? This update is only applicable in 4.6 and 4.7.

**Comment by kalexand-rh** [comment]
Yes, it makes sense to use the bot to CP this one.

**Pull request merged**
