### PR TITLE
Adding snippets directory and all required symbolic links

### PR DESCRIPTION
**Pull request by mjpytlak**
This PR is a follow on effort to enabling the use of text snippets. While [PR 38393](https://github.com/openshift/openshift-docs/pull/38393) updated the OpenShift documentation guidelines on how to use text snippets. This PR prepares the repository for their adoption.

Material changes.

1. `technology-preview.adoc` was moved from the top-level `modules` directory to a new top-level `snippets` directory.
2. All existing topics that include `technology-preview.adoc` have been updated to reference the new location. All files where tested locally and look good.
3. A symbolic link to the top-level `snippets` directory has been added to all remaining content directories, enabling the use of text snippets.

Doc preview of topics using `technology-preview.adoc`

- [Driver Toolkit](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-driver-toolkit.html)
- [Special Resource Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html)
- [Using PTP hardware](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/networking/using-ptp.html)
- [Using a virtual function in RDMA mode with a Mellanox NIC](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/networking/hardware_networks/using-dpdk-and-rdma.html#example-vf-use-in-rdma-mode-mellanox_using-dpdk-and-rdma)
- [About the Kubernetes NMState Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html)
- [Deploying node health checks by using the Node Health Check Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/eco-node-health-check-operator.html)
- [Converting a connected cluster to a disconnected cluster](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/connected-to-disconnected.html)
- [Deploying distributed units at scale in a disconnected environment](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-deploying-disconnected.html)
- [Developing Golang functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-go-functions.html)
- [Developing Node.js functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-nodejs-functions.html)
- [Developing Python functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-python-functions.html)
- [Developing Quarkus functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-python-functions.html)
- [Developing TypeScript functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-developing-typescript-functions.html)
- [About OpenShift Serverless Functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-about.html)
- [Using functions with Knative Eventing](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-eventing.html)
- [Getting started with functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-getting-started.html)
- [Functions development reference guide](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-reference-guide.html)
- [Setting up OpenShift Serverless Functions](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-setup.html)
- [Using kn CLI in offline mode](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/serverless/knative_serving/serverless-applications.html#serverless-applications-kn-offline-mode)
- [CSI inline ephemeral volumes](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/ephemeral-storage-csi-inline.html)
- [AWS Elastic File Service CSI Driver Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-aws-efs.html)
- [Azure Disk CSI Driver Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-azure-stack-hub.html)
- [CSI automatic migration](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-migration.html)
- [VMware vSphere CSI Driver Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html)
- [Importing RHEL Simple Content Access certificates with Insights Operator](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/support/remote_health_monitoring/insights-operator-simple-access.html)
- [Configuring your cluster for OpenShift Virtualization](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/virt/install/preparing-cluster-for-virt.html)
- [Configuring automatic workload updates](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/virt/upgrading-virt.html#configuring-workload-updates_upgrading-virt)
- [Hot-plugging virtual disks](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-hot-plugging-virtual-disks.html)
- [About the web terminal in the web console](https://deploy-preview-39854--osdocs.netlify.app/openshift-enterprise/latest/web_console/odc-about-web-terminal.html)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@vikram-redhat Given the nature of this change, I am asking that you peer review this. I was thinking that it might be a good idea to begin adoption of text snippets with 4.10 to avoid any issues that might arise going as far back as 4.6. WDYT?

**Comment by vikram-redhat** [comment]
@mjpytlak this works for me.

Do you mean to say that you will merge this only for 4.10?

**Comment by mjpytlak** [comment]
Yes. I am proposing that we adopt text snippets as of 4.10. I was concerned about back porting and running into issues. Am I overthinking it?

**Comment by jboxman-rh** [comment]
@vikram-redhat, this doesn't count as _a module_ in the CCS guidelines and is thus permissible? Or are we not concerned about that any longer. For all intents in purposes, this is just structured use of an `include`. And if we were just docs.openshift.com, I'd say go for it. But because we have other concerns, I wonder about this if adopted at scale.

**Comment by mjpytlak** [comment]
Good morning, @jboxman-rh. If you have not had a chance, PTAL at https://github.com/openshift/openshift-docs/pull/38393. I had updated our guidelines around usage.

**Comment by vikram-redhat** [comment]
@jboxman I don't think there are any issues around using text snippets, in any platform. @kalexand-rh can you confirm if Jupiter has any restrictions on this?

@mjpytlak if we do merge it, I think we should backport it to avoid conflicts.

**Comment by jboxman** [comment]
@vikram-redhat, well, a _snippet_ is just an include. So this all formalizes what to Asciidoctor is just a thing, that it does. But it isn't necessarily a thing every 'platform' will do, so I don't want to keep digging if it presents an issue.

**Comment by vikram-redhat** [comment]
> well, a snippet is just an include. So this all formalizes what to Asciidoctor is just a thing, that it does. But it isn't necessarily a thing every 'platform' will do, so I don't want to keep digging if it presents an issue.

You are right. We know how it can be with other "platforms" :).

**Comment by mjpytlak** [comment]
@kalexand-rh Rebased and resolved references to `modules/technology-preview.adoc` Based on Vikram's comments, I believe he was suggesting this be back ported, but he did not say how far back. I am presuming he meant all the way back to 4.6.

**Comment by kalexand-rh** [comment]
@mjpytlak, moving this back to 4.6 will be best.

**Pull request merged**
