### PR TITLE
OSDOCS-2677: Added a link to a Knowledge base article for SRE Residency.

### PR DESCRIPTION
**Pull request by EricPonvelle**
This PR added a link to two sections that provides information about the SRE Residency.

JIRA: https://issues.redhat.com/browse/OSDOCS-2677

Previews:

1. **OSD** - https://deploy-preview-40021--osdocs.netlify.app/openshift-dedicated/latest/osd_policy/policy-process-security.html#additional-resources
2. **ROSA** - https://deploy-preview-40021--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-policy-process-security.html#additional-resources

### CODE REVIEW

**Comment by sagidlow** [comment]
LGTM. Links are working as expected.

**Review by arendej — APPROVED** [review]
lgtm!

**Pull request merged**
