### PR TITLE
OSDOCS-10105: adds 4.14.22 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.14

Issue:
[OSDOCS-10105](https://issues.redhat.com/browse/OSDOCS-10105)

Link to docs preview:
[4.14.22 async release note](https://74968--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-14-release-notes.html#microshift-4-14-22-dp)

QE review:
- N/A release notes stock text

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by ShaunaDiaz** [comment]
The 4.14.22 release for MicroShift is likely to be dropped.

**Pull request closed without merging**
