### PR TITLE
[enterprise-4.15] TELCODOCS#1889:Deleting the chunksize related info

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.15

QE review:
- [x] QE has approved this change.

Note: The doc updates that are deleted in this PR are applicable only to 4.17. Hence, deleting them. These were added for [TELCODOCS-1889](https://issues.redhat.com/browse/TELCODOCS-1889).

### CODE REVIEW

**Comment by sr1kar99** [comment]
@suleymanakbas91 
Could you please review the changes?
Thanks!

**Comment by sr1kar99** [comment]
@radeore 
Could you please review this PR?
Thanks!

**Comment by radeore** [comment]
@mmakwana30 Could you help review?

**Pull request merged**
