### PR TITLE
NE-709, update router default to random balancing algorithm

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s): 4.11

Addresses https://issues.redhat.com/browse/NE-709 / https://issues.redhat.com/browse/NE-825

https://issues.redhat.com/browse/OSDOCS-3619

Preview build: https://deploy-preview-44889--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@gcs278 @quarterpin Please review when you have a moment. Thank you!

**Comment by gcs278** [comment]
@ahardin-rh looks good to me. Quick and easy fix. I suppose we will hang on to this PR until the code is submitted to change to random?

**Comment by ahardin-rh** [comment]
@gcs278 Thanks! Yes, we will hold off on merging until the code is merged, but I will get all of the appropriate reviews in place in the meantime. :rocket:

**Comment by quarterpin** [comment]
/lgtm
Thanks!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by ahardin-rh** [comment]
Hold - waiting on code to merge

**Comment by ahardin-rh** [comment]
Code is now merged: https://github.com/openshift/cluster-ingress-operator/pull/727

**Pull request merged**
