### PR TITLE
OSDOCS-3801: Add release note for OVN-Kubernetes internal subnet

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-3801

Version(s): 4.12

Issue:

Link to docs preview: https://52321--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-ovn-kubernetes-supports-configuration-internal-subnet

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@weliang1 @pliurh

This adds a release note for the internal subnet configuration feature.

Thanks!

**Comment by pliurh** [comment]
LGTM

**Pull request merged**
