### PR TITLE
Updates article title rendering for SEO

### PR DESCRIPTION
**Pull request by luciddreamz**
@nhr Please merge

### CODE REVIEW

**Comment by nhr** [comment]
Looks good.

**Comment by adellape** [comment]
@luciddreamz @nhr Good to go?

Note to cherry-picker later: pick w/ https://github.com/openshift/openshift-docs/pull/1501 (for the fixed broken links) when it's ready for downstream.

**Comment by nhr** [comment]
Looks legit; @luciddreamz okay for me to merge?

**Comment by luciddreamz** [comment]
Merge away

On Thursday, February 18, 2016, N. Harrison Ripps <notifications@github.com>
wrote:

> Looks legit; @luciddreamz <https://github.com/luciddreamz> okay for me to
> merge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-docs/pull/1575#issuecomment-185974662>
> .
>


-- 
Jacob Lucky
jlucky@redhat.com | (919) 890-8540

**Comment by adellape** [comment]
@luciddreamz @nhr Wowzers, the h1 titles are pretty huge (here's one of our longest titles):

https://docs.openshift.com/enterprise/latest/install_config/persistent_storage/persistent_storage_aws.html

I had tried this change out in a local build and it didn't look like this then.

**Comment by adellape** [comment]
Looks like it's only like that for Enterprise. Normal in Origin:

https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_aws.html

**Comment by adellape** [comment]
And Dedicated. So, the commercial sites I guess:

https://github.com/openshift/openshift-docs/pull/1575

**Comment by nhr** [comment]
@luciddreamz - will you have an opportunity to look at this today? I don't have the CSS-fu to correct this rendering issue.

**Comment by adellape** [comment]
@nhr Would me cherry-picking https://github.com/luciddreamz/openshift-docs/commit/cd97e9ff23a97b6fb058ba73d64d5fdcf325acb8 to each of the branches help? I suppose you would need to rebuild the OSE/OSD sites after?

**Comment by nhr** [comment]
@adellape Nope. All of the styling comes from master. Glad you asked because you should know that you don't need to port style changes into other branches. This is a problem in master with a CSS collision that affects the commercial distros.

**Comment by spurtell** [comment]
@nhr are you sure about this? The docs.css file in master seems to be origin-specific.

**Comment by spurtell** [comment]
@nhr - so maybe not, but it's unclear why the docs.css file would not be updated for the commercial sites. The css change was a pretty basic one.

**Comment by nhr** [comment]
@spurtell @luciddreamz I see the error of my ways now. The template always comes from master, but not the CSS. That's a bug. I'll update docs.css on the commercial branches.

**Comment by nhr** [comment]
Branches patched, docs.openshift.com rebuilt.

**Pull request merged**
