### PR TITLE
BZ1857153: Renamed the section title in TOC and in the section itself for consistency

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applicable for 4.6+

https://bugzilla.redhat.com/show_bug.cgi?id=1857153

Doc review link: https://deploy-preview-35088--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html

Requires QA approval from @gpei

### CODE REVIEW

**Comment by gpei** [comment]
@shellyyang1989 could you help on this?

**Comment by shellyyang1989** [comment]
LGTM.

**Pull request merged**
