### PR TITLE
document the supports annotation on imagestreams

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@GrahamDumpleton @jwforres ptal

**Comment by jwforres** [comment]
lgtm

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/managing_images.adoc#dev-guide-managing-images[Managing Images]
|Added information about the `supports` annotation on image streams.
%

**Pull request merged**
