### PR TITLE
BZ2100534 added AWS route 53 to restricted installation note

### PR DESCRIPTION
**Pull request by bscott-rh**
[BZ#2100534:](https://bugzilla.redhat.com/show_bug.cgi?id=2100534) Added AWS Route 53 to the note about internet access for restricted installations.
 
Version(s):
4.6+

Doc preview:
[About installations in restricted networks](https://bscott-rh.github.io/openshift-docs/BZ2100534/installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.html#installation-about-restricted-networks_installing-restricted-networks-aws-installer-provisioned)

### CODE REVIEW

**Comment by bscott-rh** [comment]
@yunjiang29 Hello Yunfei, can you please take a look at this? I was requested to add Route 53 to the list of required services for restricted network installations on AWS. Thank you.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
