### PR TITLE
GH-47162: fix sample memoryMB

### LINKED ISSUE #47162: [enterprise-4.10] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
### Which section(s) is the issue in?
Sample install-config.yaml file for an installer-provisioned VMware vSphere cluster

### What needs fixing?
The sample memoryMB of worker nodes should be 8192 instead of 8196:
4 x 1024 = 8192

This also can be fixed in "Installing a cluster on vSphere with network customizations"

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.6+

Issue: fixes #47162 

Link to docs preview: http://file.rdu.redhat.com/jdohmann/GH-47162/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-installer-provisioned-vsphere-config-yaml_installing-vsphere-installer-provisioned-customizations

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@jinyunma could you PTAL at this docs PR for QE ack? Someone raised a GH issue about the `memoryMB` field. Thank you 🙇

**Comment by jinyunma** [comment]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
/lgtm

**Pull request merged**
