### PR TITLE
Include route-override chained CNI plug-in

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/pull/20605

@dougbtv, `route-override` fits best as a new topic. Once this is complete, it will be included in the TOC.

Will there be additional chained CNI plug-ins? Eventually this may need to morph into more expansive content if so.

### CODE REVIEW

**Comment by jboxman** [comment]
@dougbtv, do we know what CNI plug-ins route-override is compatible with?

Thanks.

**Comment by jboxman** [comment]
This overlaps with declarative configurations for creating multiple networks. It might be best to do both.

**Comment by vikram-redhat** [comment]
@jboxman is this still valid? If not, can you close it?

**Comment by jboxman** [comment]
@vikram-redhat, it's relevant to _multiple networks_, but the necessary background content does not exist. It's one of the focus areas for closing networking documentation gaps, yet to be realized.

**Pull request closed without merging**
