### PR TITLE
Fixing attributes for the bug RHDEVDOCS-5537

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
**Aligned team**: Dev Tools

**Purpose**: To resolve the following issues:
(https://issues.redhat.com/browse/RHDEVDOCS-5537)

**OCP version this PR applies to**: enterprise-`4.8`, `4.9`,  `4.10`, `4.11`, `4.12`, `4.13`, and `4.14`

**Link to docs preview**: 
- [Prerequisites](https://62714--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html)
- [1st para in Using an Argo CD instance to manage cluster-scoped resources](https://62714--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#using-argo-cd-instance-to-manage-cluster-scoped-resourcesconfiguring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations)

**SME review**: Completed by @iam-veeramalla, @reginapizza 
**QE review**: Completed by @varshab1210
**Peer-review**:  Completed by @ekristova

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@reginapizza, @iam-veeramalla, @varshab1210, and @Preeticp: PTAL at this PR and provide feedback/approval. Thanks!

**Comment by varshab1210** [comment]
LGTM, thanks

**Comment by ekristova** [comment]
LGTM

**Review by reginaelyse — APPROVED** [review]

**Comment by Srivaralakshmi** [comment]
SME+QE+Peer review completed.

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Pull request merged**
