### PR TITLE
RHDEVDOCS-3358 - update SSO configuration

### PR DESCRIPTION
**Pull request by DebarghoGhosh**
Aligned team: Dev Tools
OCP version for cherry-picking: enterprise-4.8, enterprise-4.9
JIRA issues: https://issues.redhat.com/browse/RHDEVDOCS-3358
Preview pages: https://deploy-preview-38486--osdocs.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-sso-on-argo-cd-using-dex.html
SME+QE review: @iam-veeramalla 
Peer-review: @Preeticp

### CODE REVIEW

**Comment by DebarghoGhosh** [comment]
@iam-veeramalla please review

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla please review

@DebarghoGhosh Is there a way to bring up the docs website for this PR on my local or your staging environment to review this PR ?

It is difficult at-least for a person like me(no knowledge on ) to review the files changed.

**Comment by iam-veeramalla** [comment]
> https://deploy-preview-38486--osdocs.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-sso-for-argo-cd-on-openshift.html

Hi @DebarghoGhosh , Firstly, sorry for the delayed response as I am on PTO.

-> Both Dex and Keycloak/RH-SSO are two different things. We support both the SSO's. So we need to create two different pages for Dex and Keycloak.

**Comment by DebarghoGhosh** [comment]
closing the pull request because of multiple conflicts and build error. Creating a new one https://github.com/openshift/openshift-docs/pull/39282

**Pull request closed without merging**
