### PR TITLE
[BZ2076635]: Fix the parameters in the example YAML

### PR DESCRIPTION
**Pull request by xenolinux**
OCP versions: 4.10 and 4.11
[Preview](https://deploy-preview-45401--osdocs.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-configure-bfd-profiles.html#nw-metallb-configure-bfdprofile_configure-metallb-bfd-profiles)
QA contact: @zhaozhanqi
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2076635)

### CODE REVIEW

**Comment by pneedle-rh** [comment]
LGTM

**Comment by zhaozhanqi** [comment]
@asood-rh Could you help take a look this?

**Comment by xenolinux** [comment]
@asood-rh Can you please review this PR?

**Comment by sayjadha** [comment]
LGTM

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
