### PR TITLE
OSDOCS-5872-Support cluster-wide proxy on Windows Containers

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-5872

### CODE REVIEW

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.15` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.14. And any PR going into `main` must also target the latest version branch (enterprise-4.15).

If the update in your PR does NOT apply to version 4.15 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main

**Comment by mburke5678** [comment]
Closing. Dupe of https://github.com/openshift/openshift-docs/pull/68678

**Pull request closed without merging**
