### PR TITLE
Edit securityContext in sample windows deployment

### PR DESCRIPTION
**Pull request by mburke5678**
Implementing edits in https://github.com/openshift/openshift-docs/pull/50851. See https://github.com/openshift/openshift-docs/pull/50851#discussion_r989104994

### CODE REVIEW

**Comment by mburke5678** [comment]
@aravindhp PTAL

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@jfrancoa PTAL

**Comment by jfrancoa** [comment]
/remove-lgtm

I'm trying to reproduce the execution of the deployment with:
{code}
        securityContext:
          windowsOptions:
            runAsUserName: "ContainerAdministrator"
            runAsNonRoot: false
{code}

And I'm still getting the very same error:
{code}
[jfrancoa@localhost wmco]$ oc get pods
NAME                              READY   STATUS                       RESTARTS   AGE
linux-webserver-8fc5c86b8-r9hsb   1/1     Running                      0          153m
win-webserver-585d794b5-cqxht     0/1     CreateContainerConfigError   0          8m47s
win-webserver-585d794b5-j5nd2     0/1     CreateContainerConfigError   0          8m47s
win-webserver-585d794b5-ktfqt     0/1     CreateContainerConfigError   0          8m47s
win-webserver-585d794b5-rq7jt     0/1     CreateContainerConfigError   0          8m47s
win-webserver-585d794b5-t7pvd     0/1     CreateContainerConfigError   0          8m47s

 Warning  Failed     8m25s (x12 over 10m)  kubelet            Error: container's runAsUserName (ContainerAdministrator) which will be regarded as root identity and will break non-root policy (pod: "win-webserver-585d794b5-cqxht_winc-test(9d87da7d-99ed-45a0-ada8-eec4dadca6ea)", container: windowswebserver)
{code}

It is not taking the runAsNonRoot user option into account:

{code}
[jfrancoa@localhost wmco]$ oc get deployment win-webserver -o yaml | grep -A 3  securityContext
        securityContext:
          windowsOptions:
            runAsUserName: ContainerAdministrator
        terminationMessagePath: /dev/termination-log
{code}
Also, I'm seeing in the [docs](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) that the only option allowed for runAsNonRoot is true and there is no spec.securityContext.windowsOptions.runAsNonRoot field being defined:

Running as Non-root	

Containers must be required to run as non-root users.

Restricted Fields

    spec.securityContext.runAsNonRoot
    spec.containers[*].securityContext.runAsNonRoot
    spec.initContainers[*].securityContext.runAsNonRoot
    spec.ephemeralContainers[*].securityContext.runAsNonRoot

Allowed Values

    true

**Comment by jfrancoa** [comment]
@mburke5678 the right syntax should be:

```
securityContext:
   runAsNonRoot: false
   windowsOptions:
     runAsUserName: "ContainerAdministrator"
```

**Comment by mburke5678** [comment]
Updated per https://coreos.slack.com/archives/CM4ERHBJS/p1665494964431129?thread_ts=1664987085.944479&cid=CM4ERHBJS

**Review by adellape — APPROVED** [review]

**Pull request merged**
