### PR TITLE
Replacing links that were removed in error

### PR DESCRIPTION
**Pull request by mburke5678**
I removed these links in error from 4.12+. I correctly removed them from 4.10 and 4.11.

### CODE REVIEW

**Comment by mburke5678** [comment]
Replaced the links to [match the what was added](https://github.com/openshift/openshift-docs/pull/49786/files#diff-32cc22145012670da2376aa01a3f8bfa32f4c0244fa1b44f2c323752161c73c7). 

@skrthomas @jldohmann PTAL

**Review by skrthomas — COMMENTED** [review]
LGTM!

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
