### PR TITLE
[BZ1649480]: Add a note in Image Pull Policy section

### PR DESCRIPTION
**Pull request by xenolinux**
OCP version: 4.6+
[Preview](https://deploy-preview-44320--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/managing_images/image-pull-policy.html#images-image-pull-policy-overview_image-pull-policy)
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1649480)
QE contact: @xiuwang

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
I suggest dropping "in {product-title} 4.x version." because that's the section of documentation you are working in, so it's restating what is already known.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

**Comment by xenolinux** [comment]
> I suggest dropping "in {product-title} 4.x version." because that's the section of documentation you are working in, so it's restating what is already known.

Addressed. Thanks

**Comment by xenolinux** [comment]
Closing this pull request since the change is requested at different location in the docs: https://coreos.slack.com/archives/C013VBYBJQH/p1649336240910889

**Pull request closed without merging**
