### PR TITLE
OSSM-6920 [DOC] OTEL + Tempo Merge Review Clean up

### PR DESCRIPTION
**Pull request by gwynnemonahan**
[OSSM-6920](https://issues.redhat.com//browse/OSSM-6920) [DOC] OTEL + Tempo Merge Review Clean up

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSSM-6920

Link to docs preview:
https://80255--ocpdocs-pr.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-observability.html#ossm-configuring-distr-tracing-tempo_observability

QE review:
 
QE approval is not required.

Additional information:
Small changes per Merge Review. Changes did not hold up merge; making them now so they don't get lost later.

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Comment by gwynnemonahan** [comment]
Rebased against main, 4.12, 4.13, and 4.14.

**Pull request merged**
