### PR TITLE
Bug 1774385, Port 111 not needed for NFSv4

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1774385

### CODE REVIEW

**Comment by codyhoag** [comment]
@liangxia can you confirm this change? Also, would this also apply to 3.11?

**Comment by liangxia** [comment]
@duanwei33 from QE will check.

**Comment by duanwei33** [comment]
@LGTM
I see the port 111  has been removed.

For NFSv4, configure the default port 2049 (nfs).

NFSv4
# iptables -I INPUT 1 -p tcp --dport 2049 -j ACCEPT

**Comment by codyhoag** [comment]
@duanwei33 thanks! Is this valid for OCP 3.11 too?

**Comment by liangxia** [comment]
Yes, it also apply to OCP 3.11

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
