### PR TITLE
[4.9]Removed Cluster Loader documentation

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/PERFSCALE-1037
https://issues.redhat.com/browse/OSDOCS-2141

@vikram-redhat I was asked to completely deprecate Cluster Loader docs, as it is no longer maintained or supported by our PerfScale team. The docs existed as far back as 3.x. Since this is a straight removal, we don't have any content to redirect to. What are some other special considerations for this type of removal? Thanks!

@chaitanyaenr FYI

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by vikram-redhat** [comment]
Hey @ahardin-rh - this will require full change management, including acks from PM, Eng, QE and PX and sending out the change notifications before and after. 

If it is being deprecated, why would we want to remove it? Could we just put a notice at the top and perhaps remove it at a GA? (irrespective, even if we just put the deprecation notice outside of a release, we need to follow through with the change management process)

**Comment by jtaleric** [comment]
> Hey @ahardin-rh - this will require full change management, including acks from PM, Eng, QE and PX and sending out the change notifications before and after.
> 
> If it is being deprecated, why would we want to remove it? Could we just put a notice at the top and perhaps remove it at a GA? (irrespective, even if we just put the deprecation notice outside of a release, we need to follow through with the change management process)

My only concern is if customers / partners continue to use this documentation to run clusterloader and it fails to work for whatever reason. My preference is to remove it to avoid that situation.

**Comment by chaitanyaenr** [comment]
+1, it might be better to remove the references in the docs to make sure the users/customers don't run into issues especially since it's no longer maintained like @jtaleric mentioned.

**Comment by chaitanyaenr** [comment]
@tkatarki Thoughts?

**Comment by vikram-redhat** [comment]
> +1, it might be better to remove the references in the docs to make sure the users/customers don't run into issues especially since it's no longer maintained like @jtaleric mentioned.

Thanks @chaitanyaenr for tagging @tkatarki. Yes I think we need to make sure that users/customers who may have been using it already are given enough notice. I do think we need to get an ack from PM before moving forward (and send notifications to all customer facing teams, which @ahardin-rh will do after getting Tushar's ack).

**Comment by ahardin-rh** [comment]
@tkatarki PTAL Thanks!

**Comment by tkatarki** [comment]
Have we put out a deprecation notice in a previous release. Typically we deprecate first (that, put out a notice) and then remove in a subsequent release. So I would suggest we deprecate in 4.8 and then remove in 4.9.

**Comment by ahardin-rh** [comment]
@tkatarki Thank you! Sounds good to me. I opened https://github.com/openshift/openshift-docs/pull/32702 to add a deprecation notice to the Cluster Loader docs and then https://github.com/openshift/openshift-docs/pull/32703 to update the 4.8 release notes with a notice.

@chaitanyaenr FYI

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by vikram-redhat** [comment]
@ahardin-rh so we will close this PR since the removal of these docs (and the feature) shouldn't take place till 4.9, right?

**Comment by ahardin-rh** [comment]
@vikram-redhat Yes, closing this now and I will take care of the removal in a separate PR for 4.9. Thanks!

**Pull request closed without merging**
