### PR TITLE
RHDEVDOCS-4346 - 1 character correction

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.8+

Issue: https://issues.redhat.com/browse/RHDEVDOCS-4346

Link to docs preview:

QE review: n/a - correction is a single character change to a typo'd description of a file. 
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Review by rolfedh — APPROVED** [review]

**Pull request merged**
