### PR TITLE
Distinguish between embedded/external etcd; use ETCD_DATA_DIR in example

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Fixes bug 1349226 (specifically the issue explained in [comment 3](https://bugzilla.redhat.com/show_bug.cgi?id=1349226#c3)).

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@ahardin-rh @adellape @bfallonf @tpoitras Peer review (and labels check), please?

**Comment by tnguyen-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/manual_upgrades.adoc#install-config-upgrading-manual-upgrades[Performing Manual Cluster Upgrades]
|Distinguished between embedded and external etcd in the xref:../install_config/upgrading/manual_upgrades.adoc#preparing-for-a-manual-upgrade[Preparing for a Manual Upgrade] section.
%

**Comment by ahardin-rh** [comment]
@tnguyen-rh LGTM! :star:

**Comment by tnguyen-rh** [comment]
@ahardin-rh Thanks for the review.  Merging.

**Pull request merged**
