### PR TITLE
CNV#35090_417: Release note: NEW GA Host-side USB passthrough

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.17

Issue: [CNV-35090](https://issues.redhat.com/browse/CNV-35090?filter=12439470)

Link to docs preview: See the note under the [Virtualization](https://81835--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html#virt-4-17-virtualization) heading in the 4.17 release notes.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by aspauldi** [comment]
@tiraboschi or @stu-gott, can either of you review this 4.17 release note? It corresponds to the feature doc (for [CNV-29336](https://issues.redhat.com/browse/CNV-29336)) you helped review today and yesterday.

**Comment by stu-gott** [comment]
LGTM

**Comment by aspauldi** [comment]
@jerry7z, can you please review this 4.17 release note? Thanks!

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
