### PR TITLE
BZ1867056: Remove legacy forwarding from fluentd

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applicable for 4.6+

Direct docs preview link: https://deploy-preview-35885--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-external?utm_source=github&utm_campaign=bot_dp#cluster-logging-collector-legacy-fluentd_cluster-logging-external

https://bugzilla.redhat.com/show_bug.cgi?id=1867056

Requires QE ack from @anpingli

### CODE REVIEW

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
