### PR TITLE
OBSDOCS-1009 List MS Teams as a supported receiver for monitoring alerts

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `enterprise-4.15` and later

Issue: [OBSDOCS-1009](https://issues.redhat.com/browse/OBSDOCS-1009)

Links to docs preview: 
* [Sending notifications to external systems](https://75483--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/managing-alerts.html#sending-notifications-to-external-systems_managing-alerts)
* [Configuring alert notifications](https://75483--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-alert-notifications)

QE review:
- [x] QE has approved this change.

**Additional information:**

### CODE REVIEW

**Comment by juzhao** [comment]
/lgtm

just NOTE:
OCP 4.15 and 4.16 use alertmanager 0.26.0, from below information, `summary` requires Alertmanager >= 0.27.0, other fields are since 0.26.0 
```
$ oc explain alertmanagerconfig.spec.receivers.msteamsConfigs
GROUP:      monitoring.coreos.com
KIND:       AlertmanagerConfig
VERSION:    v1beta1

FIELD: msteamsConfigs <[]Object>

DESCRIPTION:
    List of MSTeams configurations. It requires Alertmanager >= 0.26.0.
    MSTeamsConfig configures notifications via Microsoft Teams. It requires
    Alertmanager >= 0.26.0.
    
FIELDS:
  httpConfig	<Object>
    HTTP client configuration.

  sendResolved	<boolean>
    Whether to notify about resolved alerts.

  summary	<string>
    Message summary template. It requires Alertmanager >= 0.27.0.

  text	<string>
    Message body template.

  title	<string>
    Message title template.

  webhookUrl	<Object> -required-
    MSTeams webhook URL.
```
same as find from
https://prometheus.io/docs/alerting/0.26/configuration/#msteams_config
https://prometheus.io/docs/alerting/0.27/configuration/#msteams_config
`summary` field is since 0.27

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM; merging to 4.15+.

**Pull request merged**
