### PR TITLE
[GH#32958] Example is incorrect for OKD

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/32958

Added ifdefs for OKD for the _Sample Node object with a label_ output in the _Node selectors on specific pods and nodes_ section.
Preview OCP: https://deploy-preview-32970--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-about_nodes-scheduler-node-selectors
Preview OKD: http://file.rdu.redhat.com/~mburke/issue-32958/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-about_nodes-scheduler-node-selectors

### CODE REVIEW

**Comment by mburke5678** [comment]
@elmiko Did you bring this issue up at the OKD docs meeting today? Can you PTAL?

**Review by elmiko — APPROVED** [review]
this does look accurate to what we discussed in the meeting today. thanks!
/lgtm

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Comment by vrutkovs** [comment]
Looks great, thanks!

**Pull request merged**
