### PR TITLE
[OCPBUGS-25202] Add ansible-collections-openstack to be installed

### PR DESCRIPTION
**Pull request by gryf**
Version(s):

4.16, 4.15, 4.14, 4.13, 4.12

Issue: https://issues.redhat.com/browse/OCPBUGS-25202

Link to docs preview: https://69512--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user#installation-osp-downloading-modules_installing-openstack-user

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]

**Comment by eurijon** [comment]
lgtm, thanks @gryf !

**Comment by maxwelldb** [comment]
@gryf Any objections to my merging this now?

**Comment by maxwelldb** [comment]
@gryf Just create a 4.13-specific PR w/me mentioned on it and this should be all set.

**Pull request merged**
