### PR TITLE
Update managing_images.adoc

### PR DESCRIPTION
**Pull request by gburges**
There is missing wording in ARO docs, so added the openshift-aro to ifdef

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gburges, will you please squash your commits?

@vikram-redhat, will you PTAL?

**Comment by vikram-redhat** [comment]
@lamek PTAL

**Comment by lamek** [comment]
LGTM. I'll merge and cherry pick for you. Thanks for the fix.

**Pull request merged**
