### PR TITLE
Bug 1383279, Documented the new feature to bookmark page state

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1383279

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jwforres PTAL. Is there anything else we should mention about this feature? Thanks!

**Comment by jwforres** [comment]
@ahardin-rh LGTM

**Comment by ahardin-rh** [comment]
@adellape please peer review

**Comment by ahardin-rh** [comment]
Moved the content to the Dev Guide --> Projects topic per discussion with @adellape

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/projects.adoc#dev-guide-projects[Projects]
|Added a new xref:../dev_guide/projects.adoc#web-console-bookmarking-page-state[Bookmarking Page States] section, which discusses that {product-title} now bookmarks page states, which is helpful in saving label filters.
%

**Pull request merged**
