### PR TITLE
closing more ifevals

### PR DESCRIPTION
**Pull request by kalexand-rh**
@vikram-redhat, PTAL?

### CODE REVIEW

**Comment by jboxman** [comment]
@kalexand-rh, for the network modules I see you're unsetting the specific value. Why not unset the variable entirely? It's less verbose.

https://asciidoctor.org/docs/user-manual/#using-attributes-set-assign-and-reference

**Comment by kalexand-rh** [comment]
@jboxman, because checking to see **what** the variables were wasn't part of my process - I was looking for modules that defined and then didn't undefine them. I've updated them all. Thanks

**Comment by vikram-redhat** [comment]
Thanks @kalexand-rh.

**Pull request merged**
