### PR TITLE
update image location

### PR DESCRIPTION
**Pull request by apinnick**
Update hook image location to downstream

cp 4.3, 4.4, 4.5

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Looks great!

**Comment by ahardin-rh** [comment]
@apinnick I just manually tried to cherrypick to enterprise-4.3 after the bot failed, but modules/migration-understanding-migration-hooks.adoc does not exist in enterprise-4.3.

**Comment by apinnick** [comment]
> @apinnick I just manually tried to cherrypick to enterprise-4.3 after the bot failed, but modules/migration-understanding-migration-hooks.adoc does not exist in enterprise-4.3.

Sorry, you're right. CP only for 4.4 and 4.5

**Pull request merged**
