### PR TITLE
BZ-2009339: Compatibility matrix update

### PR DESCRIPTION
**Pull request by tshwartz**
BZ-2009339 - Compatability Matrix Update

Version(s):
Main, 4.11, 4.12

Issue:
(https://bugzilla.redhat.com/show_bug.cgi?id=2009339)

Link to docs preview:
(http://file.emea.redhat.com/tshwartz/BZ-2009339/installing/installing-preparing.html)

Additional information:

- Added Restricted Network support for Bare Metal (x2) in the Installer-Provisioned Infrastructure Options table.
- Added a second sentence to the note above the table.
- Replaced X with ✓across the two tables.

### CODE REVIEW

**Comment by tshwartz** [comment]
Thanks Ori.

**Comment by jboxman-rh** [comment]
@tshwartz, looks like this hit a merge conflict. Otherwise, LGTM.

**Comment by jboxman-rh** [comment]
@tshwartz, needs another rebase. Thanks!

**Comment by bergerhoffer** [comment]
@jboxman-rh Looks like this wasn't cherry picked to 4.11 or 4.12, does it still need to be?

**Pull request merged**
