### PR TITLE
Default timeout vars overrride capabilities. 

### PR DESCRIPTION
**Pull request by sferich888**
This is dependent on work in https://github.com/openshift/origin/pull/9518

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Just one comment from me. Also, will need a rebase. :bow:

**Comment by sferich888** [comment]
@ahardin-rh not sure what you mean, with your suggestion, but tell me if it looks ok, now.

**Comment by ahardin-rh** [comment]
@sferich888 oh sorry for not being clear. I just meant that "as an example" is an introductory clause, so it needs a comma:
s/As an example you can/As an example, you can

**Comment by sferich888** [comment]
@ahardin-rh PTAL now.

**Comment by ahardin-rh** [comment]
@sferich888 perfect :star2: 
Is this for for future release (3.3), or can this get merged into 3.2 now?

**Comment by sferich888** [comment]
Future, see the other pending prs from my comments.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc[Core Concepts -> Routes]
|Added router configuration parameters.
%

**Pull request merged**
