### PR TITLE
STOR#1396:Fix vSphere CSI driver version

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.15 only

Issue: https://issues.redhat.com/browse/STOR-1396

Link to docs preview: https://76847--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html

QE review:
- [ ] QE has approved this change.

Additional information:

**PTAL**: @gcharot @jsafrane @gnufied @duanwei33

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

LGTM

**Comment by gcharot** [comment]
LGTM 
@gnufied can you please review? Thanks!

**Comment by duanwei33** [comment]
Hi @gnufied 
In 4.15, I recall we reverted it to 3.0.2 due to topology bug in this PR(https://github.com/openshift/vmware-vsphere-csi-driver/pull/101), could you double check? I don't know how to check that from the code.

**Comment by gnufied** [comment]
@duanwei33 you are actually right.  I think version of vSphere CSI driver didn't change.

**Comment by lpettyjo** [comment]
Since the version didn't actually change, I'm closing this PR without merging.

**Comment by lpettyjo** [comment]
Since the version didn't actually change, I'm closing this PR without merging.

**Pull request closed without merging**
