### PR TITLE
OSDOCS-8439: CAPI install refactor

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.15+

Issue:
[OSDOCS-8439](https://issues.redhat.com//browse/OSDOCS-8439)

Link to docs preview:
[The Cluster CAPI Operator](https://69890--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/capi-machine-management#capi-arch-operator)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
LGTM

**Comment by jeana-redhat** [comment]
@huali9 PTAL when you can :)

**Comment by gwynnemonahan** [comment]
Hey @jeana-redhat ,

LGTM! Being new, @abrennan89 needs to check, too.

**Review by abrennan89 — COMMENTED** [review]
lgtm

**Pull request merged**
