### PR TITLE
OSDOCS-11884_417#updating 4.17 RN

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version: 
4.17 

Issue:
https://issues.redhat.com/browse/OSDOCS-11884

Link to docs preview:
https://83427--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-technology-preview-tables_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@makentenza, PTAL

**Review by dfitzmau — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress

/label peer-review-done

**Comment by soumyadbanik** [comment]
LGTM

**Review by makentenza — CHANGES_REQUESTED** [review]
Please check https://github.com/openshift/openshift-docs/pull/83426#pullrequestreview-2369903435 as the same change applies here

**Comment by makentenza** [comment]
LGTM

**Review by makentenza — APPROVED** [review]

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
