### PR TITLE
RHDEVDOCS-5142: Document tainting nodes

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: `enterprise-4.10` and later
• **JIRA issue**:  [RHDEVDOCS-5142](https://issues.redhat.com/browse/RHDEVDOCS-5142)
• **Preview pages**: [Configuring an OpenShift cluster by deploying an application with cluster configurations](https://58872--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html), [Running GitOps control plane workloads on infrastructure nodes](https://58872--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/run-gitops-control-plane-workload-on-infra-nodes.html)
• **SME Review**: Completed by @iam-veeramalla 
• **QE review**: Completed by @varshab1210 
• **Peer-review**: Completed by @deerskindoll

### CODE REVIEW

**Comment by ekristova** [comment]
Hello @iam-veeramalla @varshab1210 PTAL and provide feedback. Thank you!

**Review by deerskindoll — APPROVED** [review]
lgtm

**Pull request merged**
