### PR TITLE
OCPBUGS-35488_4.16:updating installation doc

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version:
4.16

Issue:
https://issues.redhat.com/browse/OCPBUGS-35488

Link to docs preview:
**AWS**
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-customizations#installation-aws-tested-machine-types_installing-aws-customizations
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-customizations#installation-aws-arm-tested-machine-types_installing-aws-customizations

**Azure**
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations#installation-azure-tested-machine-types_installing-azure-customizations
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations#installation-azure-arm-tested-machine-types_installing-azure-customizations

**GCP**
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types_installing-gcp-customizations
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types-arm_installing-gcp-customizations

**IBM Cloud**
- https://83354--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations#installation-ibm-cloud-tested-machine-types_installing-ibm-cloud-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@jinyunma, Can you review the changes for Azure?
@jianli-wei, Can you review the changes for GCP?
@yunjiang29, Can you review the changes for AWS?
@MayXuQQ, Can you review the change for IBM Cloud?

**Comment by jinyunma** [comment]
thanks for addressing this, lgtm for azure part.

**Comment by MayXuQQ** [comment]
lgtm for ibmcloud

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
