### PR TITLE
OSDOCS3464: correcting the important notes so they match

### PR DESCRIPTION
**Pull request by cowgirljessi**
Bug fix

https://issues.redhat.com/browse/OSDOCS-3464

@lihongan QE check please

Preview build: https://deploy-preview-44633--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-enforcing-hsts-per-domain_route-configuration[](https://github.com/cowgirljessi)

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Preview build: https://deploy-preview-44633--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-enforcing-hsts-per-domain_route-configuration

@cowgirljessi This update LGTM. Please ensure that you leave a preview build link in each peer review request, as well as indication of what versions the update applies to. I was able to decipher from the linked issue in this case, but including these details in the PR for reviewers helps to save time. Thank you!

**Comment by cowgirljessi** [comment]
@ahardin-rh Can you merge?

**Comment by lihongan** [comment]
@quarterpin could you please take a look? thanks.

**Comment by quarterpin** [comment]
/lgtm
Thanks!

**Pull request merged**
