### PR TITLE
[main] OSDOCS-3991: Port Operators book to OSD/ROSA

### PR DESCRIPTION
**Pull request by bhardesty**
Cherry Picked from f18533b4badf57c59e007c21a5e47e6b2bc83745 xref: https://github.com/openshift/openshift-docs/pull/61793.

Note: This was originally merged to `enterprise-4.13` to avoid applying any 4.14+ content to older releases.

### CODE REVIEW

**Comment by jeana-redhat** [comment]
We have some concerns about this approach, will pick this back up tomorrow and catch up with you about it.

Cc: @kalexand-rh

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
This LGTM, and I had reviewed the earlier 4.13-specific https://github.com/openshift/openshift-docs/pull/61793 as well.

**Comment by jeana-redhat** [comment]
Thanks for taking this on, Alex!

**Pull request merged**
