### PR TITLE
Audit components for arch/OS label usage

### PR DESCRIPTION
**Pull request by mburke5678**
https://jira.coreos.com/browse/OSDOCS-507

### CODE REVIEW

**Comment by rphillips** [comment]
/lgtm

Thanks!

**Comment by mburke5678** [comment]
@anpingli Can you take a look at these small changes?

**Comment by anpingli** [comment]
@zhaozhanqi  Could you look at these changes?

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi Could you look at these changes?

sriov part lgtm.

**Review by anpingli — APPROVED** [review]
@mburke5678  Confirmed in 4.2 ,  kubernetes.io/os=linux is used to replace beta.kubernetes.io/os=linux

**Pull request merged**
