### PR TITLE
CMA 2.11.2-322 release notes

### PR DESCRIPTION
**Pull request by mburke5678**
Preview: https://73664--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/cma/nodes-cma-autoscaling-custom-rn#nodes-pods-autoscaling-custom-rn-2112-322_nodes-cma-autoscaling-custom-removing

### CODE REVIEW

**Comment by mburke5678** [comment]
@joelsmith PTAL

**Comment by joelsmith** [comment]
LGTM, thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
