### PR TITLE
[internal-fix] Level 1 heading attributes not resolving  - move attributes include ahead of heading

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14+ , also applies to 4.14 but I assume cherry-picking won't work as several files don't exist in 4.14

Issue: common attributes don't resolve in level 1 headings common attribute include needs to be moved before the heading

Link to docs preview:

https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installation-config-parameters-ibm-power.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-restricted-networks-ibm-power.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/preparing-to-install-on-ibm-power.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/creating-ibm-power-vs-workspace.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installation-config-parameters-ibm-power-vs.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-cloud-account-power-vs.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-customizations.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-private-cluster.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-powervs-vpc.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/preparing-to-install-on-ibm-power-vs.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/uninstalling-cluster-ibm-power-vs.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installation-config-parameters-ibm-z.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-kvm.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-lpar.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z-lpar.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/preparing-to-install-on-ibm-z.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-ibm-powervs-block.html
https://76136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-ibm-vpc-block.html

QE review:
- [NA ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by maxwelldb** [comment]
@SNiemann15 This doesn't have a `peer-review-done` tag on it, yet. Has that happened elsewhere?

**Comment by SNiemann15** [comment]
> @SNiemann15 This doesn't have a `peer-review-done` tag on it, yet. Has that happened elsewhere?

@maxwelldb I don't think this requires a peer-review since it only fixes a bug with attributes that suddenly don't render anymore in level 1 headings. see discussion here: https://redhat-internal.slack.com/archives/C85JYPHL3/p1715938416585369

**Review by maxwelldb — APPROVED** [review]
/lgtm

**Pull request merged**
