### PR TITLE
[OSDOCS-10175]:Missing Permission in EFS ROSA DOC elasticfilesystem:TagResource

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10175
Link to docs preview:

 https://74291--ocpdocs-pr.netlify.app/openshift-rosa/latest/storage/container_storage_interface/osd-persistent-storage-aws-efs-csi.html#efs-sts_osd-persistent-storage-aws-efs-csi

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 , Could you please get QE to review this PR? Thanks!

**Comment by mletalie** [comment]
See approval here: https://issues.redhat.com/browse/OSDOCS-10175?focusedId=24516574&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24516574

**Comment by ropatil010** [comment]
/lgtm
Thanks..!

**Comment by aldiazRH** [comment]
LGTM!

**Pull request merged**
