### PR TITLE
RHDEVDOCS-2602 In secure forward the self_hostname the definition and…

### PR DESCRIPTION
**Pull request by rolfedh**
… value are wrong
merge to master only, not to the enterprise branches for now.

### CODE REVIEW

**Comment by rolfedh** [comment]
@r2d2rnd Oscar, please mark this as lgtm.

**Comment by r2d2rnd** [comment]
@rolfedh LGTM

**Comment by bmcelvee** [comment]
The change LGTM! 

It looks like the module is in the unused topics folder, and I couldn't find it in the preview build. Is it moving out of that folder? Thanks!

**Comment by bmcelvee** [comment]
Merging to master only.

**Pull request merged**
