### PR TITLE
Shouldn't this permission be present out of the box

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1705233

"openshift-ansible provides means to deploy cluster autoscaler since 3.8+. "
https://coreos.slack.com/archives/CBZHF4DHC/p1559936085012200?thread_ts=1559935044.010300&cid=CBZHF4DHC

### CODE REVIEW

**Comment by mburke5678** [comment]
@ingvagabund PTAL

**Comment by ingvagabund** [comment]
@mburke5678 looks good

**Comment by mburke5678** [comment]
Procedure appears in 3.11 only.

**Pull request merged**
