### PR TITLE
BZ#1977897 Updated the instance type from m5a.10xlarge to m5a.12xlarge

### PR DESCRIPTION
**Pull request by EricPonvelle**
This PR updates the value of an AWS instance type from the defunct `m5a.10xlarge` to `m5a.12xlarge`.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1977897

Preview: https://deploy-preview-35359--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-supported-aws-machine-types_installing-aws-customizations

### CODE REVIEW

**Comment by EricPonvelle** [comment]
@yunjiang29 @e-tienne PTAL at this PR to address BZ1990206.

**Review by e-tienne — CHANGES_REQUESTED** [review]
Hello,

It looks like this AWS instance is plastered across our product documentation.

```
$ grep -R 'm5a.10xlarge' * | wc -l
432
```

It looks like we will need to change it at multiple places and re-generate the docs so these 432 `m5a.10xlarge` instance types are updated to `m5a.12xlarge`

**Comment by e-tienne** [comment]
It looks like it's also in at least 2 other files:

- installation-creating-aws-worker.adoc
- installation-creating-aws-control-plane.adoc

**Comment by yunjiang29** [comment]
@EricPonvelle  this PR should be for https://bugzilla.redhat.com/show_bug.cgi?id=1977897

**Comment by yunjiang29** [comment]
`m5a.10xlarge` is still in following sections:
* https://deploy-preview-35359--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-restricted-networks-aws.html#installation-cloudformation-control-plane_installing-restricted-networks-aws
* https://deploy-preview-35359--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-restricted-networks-aws.html#installation-creating-aws-worker_installing-restricted-networks-aws

**Comment by EricPonvelle** [comment]
> @EricPonvelle this PR should be for https://bugzilla.redhat.com/show_bug.cgi?id=1977897

Hey, @yunjiang29. What's the difference between the two tickets I linked? Could I address both in this PR?

It looks like the existing references to the `m5a.10xlarge` instance type are auto-generated from the installer repo template. I've sent a PR to the installer repo here: https://github.com/openshift/installer/pull/5143

**Comment by yunjiang29** [comment]
@EricPonvelle  The component of bug 1990206  is Installer, for changing UPI template, and bug 1977897 is for documentation.

**Comment by yunjiang29** [comment]
@codyhoag LGTM

**Review by adellape — APPROVED** [review]

**Pull request merged**
