### PR TITLE
BZ-1850687: Adding step to restart the kubelet service

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1850687

Preview: https://bz-1850687--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@geliu2016 Can you review this update for adding the workaround of restarting the kubelet service?

Preview: https://bz-1850687--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Comment by geliu2016** [comment]
LGTM,thanks

**Pull request merged**
