### PR TITLE
BZ1888541: Include bonded and VLAN interfaces for Multus macvlan

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1888541

Preview: https://deploy-preview-34808--osdocs.netlify.app/openshift-enterprise/latest/networking/multiple_networks/configuring-macvlan.html#nw-multus-macvlan-object_configuring-macvlan

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, does this make sense? Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, does this make sense? Thanks!

The change looks good to me.
/cc @s1061123

**Review by jeana-redhat — APPROVED** [review]

**Comment by jboxman** [comment]
@jeana-redhat thanks!

**Pull request merged**
