### PR TITLE
s\tp\ga sm is in ga

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.jboss.org/projects/OSSMDOC/issues/OSSMDOC-3?filter=allissues

### CODE REVIEW

**Comment by neal-timpe** [comment]
@brian-avery Can you take a look? I fixed the Service Mesh in TP in the release notes issue. https://issues.jboss.org/projects/OSSMDOC/issues/OSSMDOC-3?filter=allissues

**Review by brian-avery — APPROVED** [review]

**Comment by neal-timpe** [comment]
@openshift/team-documentation Can you merge this to 4.1, 4.2, and beyond?

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@neal-timpe Can you submit a separate PR for 4.1, since the 4.1 RN file doesn't exist there? 

I'll cherry pick this for 4.2 and 4.3.

**Pull request merged**
