### PR TITLE
new required variable

### PR DESCRIPTION
**Pull request by cooktheryan**
Two new variables are required for the 3.11 installation. I copied these based off of @kalexand-rh work in RHV

### CODE REVIEW

**Comment by cooktheryan** [comment]
not sure if you have the cycles @kalexand-rh but would be appreciate :+1:

**Comment by jianlinliu** [comment]
LGTM for new required variable, but have a glance in other parts, I do not think we should expose "openshift_version" setting in example inventory, ideally openshift_version is some internal var in openshift-ansible installer.

**Comment by kalexand-rh** [comment]
@cooktheryan, will you please squash so I can merge?

**Comment by kalexand-rh** [comment]
Thanks @cooktheryan! Merging.

**Pull request merged**
