### PR TITLE
Bug 1828027, Updated Ansible version

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1828027

Creating this change per discussion in https://github.com/openshift/openshift-docs/pull/23189#discussion_r461584100

@gpei PTAL

### CODE REVIEW

**Comment by gpei** [comment]
LGTM, thanks.

**Comment by gpei** [comment]
btw, @ahardin-rh we may need to backport this to 4.4/4.5 docs since we're requiring ansible-2.9 from 4.4

**Comment by ahardin-rh** [comment]
@gpei Thank you! Yes, this change will soon be applied to 4.4, 4.5, and 4.6. Thanks again!

**Pull request merged**
