### PR TITLE
OCPBUGS#23193: Limitation for adding or removing deviceClass

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.13+

Issue: [OCPBUGS-23193](https://issues.redhat.com/browse/OCPBUGS-23193)

Link to docs preview:
https://70160--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms#lvms-creating-lvms-cluster_logical-volume-manager-storage

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@suleymanakbas91 
Can you please review this PR?
Thanks.

**Comment by sr1kar99** [comment]
@radeore 
Can you please review this PR?
Thanks.

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by jab-rh** [comment]
@sr1kar99, looks like this needs a rebase, thanks!

**Comment by sr1kar99** [comment]
> @sr1kar99, looks like this needs a rebase, thanks!

Rebase done. Thanks!

**Review by sheriff-rh — APPROVED** [review]
LGTM, merging.

**Comment by sheriff-rh** [comment]
@sr1kar99 looks like you'll need to manually cherrypick to 4.13 and .14.

**Pull request merged**
