### PR TITLE
OSDOCS-909: Adding info on OCS

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-909

Preview: https://osdocs-909-ocs--ocpdocs.netlify.com/openshift-enterprise/latest/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-storage

### CODE REVIEW

**Review by adellape — APPROVED** [review]
:+1:

**Comment by bergerhoffer** [comment]
@XinRedhat or @liangxia - I'm not sure who is best suited for this, but could one of you please review this update to the migration planning content for OCS? Thanks!

**Comment by liangxia** [comment]
@XinRedhat  will check.

**Comment by XinRedhat** [comment]
LGTM

**Pull request merged**
