### PR TITLE
Edit suggested in file

### PR DESCRIPTION
**Pull request by mburke5678**
Requested by https://github.com/openshift/openshift-docs/issues/8851

### CODE REVIEW

**Comment by mburke5678** [comment]
@ingvagabund @mdshuai 
I came across a [Trello](https://github.com/openshift/openshift-docs/issues/8851#issuecomment-386214958) where DeShuai was working with the `system-reserved` parameter. Is the change I made correct?

**Comment by ingvagabund** [comment]
Based on [1]:
```
A set of ResourceName=ResourceQuantity (e.g. cpu=200m,memory=500Mi,ephemeral-storage=1Gi) pairs that ...
```

So `memory=2Gi` seems right.

[1] https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L563

**Comment by mburke5678** [comment]
@mdshuai PTAL

**Comment by vikram-redhat** [comment]
@mdshuai - PTAL.

cc: @xltian

**Comment by mburke5678** [comment]
@mdshuai PTAL

cc: @xltian

**Comment by xltian** [comment]
@wjiangjay from QE will have a look at this doc while deshuai is PTO.

**Comment by wjiangjay** [comment]
LGTM

**Comment by mburke5678** [comment]
@ingvagabund @wjiangjay Can you comment on @kalexand-rh comment? Do we need the quotation marks?
```
system-reserved:
    - "memory=1.5Gi"
```

**Comment by ingvagabund** [comment]
@adellape PTAL

**Comment by mburke5678** [comment]
Per @adellape "i believe either should work, but might as well sync up w/ the quotes"

**Comment by mdshuai** [comment]
LGTM, thanks

**Comment by mburke5678** [comment]
Change not needed in 3.4 and 3.3.
https://docs.openshift.com/container-platform/3.3/admin_guide/out_of_resource_handling.html#out-of-resource-schedulable-resources-and-eviction-policies

kubeletArguments:
  eviction-hard: 
    - "memory.available<500Mi"
  system-reserved:
    - "memory=1.5Gi"

**Pull request merged**
