### PR TITLE
OCPBUGS-18064 -important post-configuration installation information for Ingress default certification

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-18064

Link to docs preview:
https://69269--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-private-cluster#private-clusters-about_configuring-private-cluster

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@lihongan can I get a QE  check

**Comment by lihongan** [comment]
LGTM
Thank you!

**Review by lahinson — COMMENTED** [review]
lgtm

**Comment by sheriff-rh** [comment]
Hi @jmanthei , I see this PR is against the main branch, however you have selected 4.10-4.13 as your versions. 

We are only updating 4.11-4.15 at this time, as 4.10 is [end of life](https://access.redhat.com/support/policy/updates/openshift#dates). Should this PR also be applied to 4.14 and 4.15? Please let me know which versions you would like to apply the changes to.  Reach out to me here or on Slack. Thanks!

**Comment by sheriff-rh** [comment]
Merging to 4.11+.

**Pull request merged**
