### PR TITLE
[Enterprise-4.13] OBSDOCS-845 - Logging API Reference Updates

### PR DESCRIPTION
**Pull request by libander**
[Enterprise-4.13] Manual CP of #74922 

Logging Version | Supported OCP Versions Matrix
5.9 | 4.15, 4.14, 4.13
5.8 | 4.12, 4.13, 4.14, 4.15
5.7 | 4.12, 4.13, 4.14
5.6 | 4.12, 4.13

PRs by branch: 
https://github.com/openshift/openshift-docs/pull/74925
https://github.com/openshift/openshift-docs/pull/74924
https://github.com/openshift/openshift-docs/pull/74923
https://github.com/openshift/openshift-docs/pull/74922

### CODE REVIEW

**Comment by libander** [comment]
@anpingli / @kabirbhartiRH - lgtm please.

**Comment by anpingli** [comment]
@libander  There is Logging 5.9 in Openshift 4.13.

**Review by GroceryBoyJr — COMMENTED** [review]
For information on the 5.6, 5.7 and 5.8 files, look to PR [74922](https://github.com/openshift/openshift-docs/pull/74922)

These files are all nearly identical to the ones found in that PR and will be re-created by automation once the desired corrections have been made.  Here are the search strings used to find the errors in these files:

explicitly for the
`application` logs that
logs to allow
profile based on:
Custom provides
the pods are scheduled on.
events will be
the mode
buffer plugin to
Flush operations can
(Which must be

**Pull request closed without merging**
