### PR TITLE
OSSMDOC-324

### PR DESCRIPTION
**Pull request by neal-timpe**
2.0.5 release notes
https://issues.redhat.com/browse/OSSMDOC-324

2.x release notes https://deploy-preview-32561--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/servicemesh-release-notes.html#new-features-red-hat-openshift-service-mesh-2-0-5

2.x fixed issues https://deploy-preview-32561--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/servicemesh-release-notes.html#ossm-rn-fixed-issues_ossm-release-notes

1.x release notes https://deploy-preview-32561--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/servicemesh-release-notes.html#new-features-red-hat-openshift-service-mesh-1-1-15

1.x fixed issues https://deploy-preview-32561--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/servicemesh-release-notes.html#ossm-rn-fixed-issues-1x_ossm-release-notes-v1x

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by knrc — APPROVED** [review]

**Review by tvieira — APPROVED** [review]
lgtm - thanks @neal-timpe

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
