### PR TITLE
CNV-4324: must delete objects before uninstall

### PR DESCRIPTION
**Pull request by ousleyp**
- Jira: https://issues.redhat.com/browse/CNV-4324

Preview build links: 
- http://file.bos.redhat.com/pousley/041420/uninstall-delete/cnv/cnv_install/uninstalling-container-native-virtualization.html
- http://file.bos.redhat.com/pousley/041420/uninstall-delete/cnv/cnv_virtual_machines/cnv-delete-vms.html
- http://file.bos.redhat.com/pousley/041420/uninstall-delete/cnv/cnv_virtual_machines/cnv-deleting-vmis.html
- http://file.bos.redhat.com/pousley/041420/uninstall-delete/cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-deleting-datavolumes.html

### CODE REVIEW

**Review by fabiand — COMMENTED** [review]
lgtm

**Review by sbulage — APPROVED** [review]
LGTM from my point of view :+1:

**Review by aburdenthehand — APPROVED** [review]

**Comment by ousleyp** [comment]
opened the following RFE bug to address redundancy: https://bugzilla.redhat.com/show_bug.cgi?id=1825272

**Pull request merged**
