### PR TITLE
OSDOCS-10916: adds 4.15.19 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15

Issue:
[OSDOCS-10916](https://issues.redhat.com/browse/OSDOCS-10916)

Link to docs preview:
[4.15.19 async relnote](https://77882--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes.html#microshift-4-15-19-dp)

QE review:
- N/A stock text

### CODE REVIEW

**Comment by aravipra** [comment]
work is in progress for this PR.

**Comment by aravipra** [comment]
Do not merge the PR until merge review label is added.
For now peer review is needed.

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
