### PR TITLE
OCPBUGS#23147: Fixup of the OLMv1 Operator API snippet

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.14+

Issue: [OCPBUGS-23147](https://issues.redhat.com/browse/OCPBUGS-23147)

Link to docs preview:
* [Operator Controller > [NOTE] admonition](https://71963--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/arch/olmv1-operator-controller#olmv1-operator-api)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM, good catch

**Comment by michaelryanpeter** [comment]
@KeenonLee PTAL.

**Review by KeenonLee — COMMENTED** [review]
/lgtm

**Pull request merged**
