### PR TITLE
4.11 GA

### PR DESCRIPTION
**Pull request by kalexand-rh**
For 4.11 GA. Based on #42925

### CODE REVIEW

**Review by pneedle-rh — COMMENTED** [review]
LGTM!

**Comment by pneedle-rh** [comment]
@kalexand-rh hi! We also need to move the pointer for OSD and ROSA to `enterprise-4.11` in the distro map on 4.11 GA. For 4.10, this was done through https://github.com/openshift/openshift-docs/pull/43054 by @EricPonvelle.

For 4.11, it might make sense to roll that into this 4.11 GA PR (48243). What is your view?

**Comment by kalexand-rh** [comment]
> @kalexand-rh hi! We also need to move the pointer for OSD and ROSA to `enterprise-4.11` in the distro map on 4.11 GA. For 4.10, this was done through #43054 by @EricPonvelle.
> 
> For 4.11, it might make sense to roll that into this 4.11 GA PR (48243). What is your view?

Thank you for pointing that out, @pneedle-rh! I think it's a good idea to make all of these changes on one PR, so I've added them to this one.

**Comment by pneedle-rh** [comment]
> Thank you for pointing that out, @pneedle-rh! I think it's a good idea to make all of these changes on one PR, so I've added them to this one.

Thank you!

**Review by bergerhoffer — APPROVED** [review]

**Pull request merged**
