### PR TITLE
BZ-1866844: Removed a bullet

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.5+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1866844
Preview Link: https://deploy-preview-32009--osdocs.netlify.app/openshift-enterprise/latest/installing/install_config/installing-customizing.html#installation-special-config-encrypt-disk_installing-customizing
Pending QE review: @miabbott

### CODE REVIEW

**Comment by sagidlow** [comment]
@miabbott - Could you please review the removal of the bullet from the list?

**Review by adellape — APPROVED** [review]
:+1:

**Comment by knewcomerRH** [comment]
LGTM

**Pull request merged**
