### PR TITLE
[SRVCOM-2271] Update distributed tracing prerequisites

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVCOM-2271

Link to docs preview:
https://78875--ocpdocs-pr.netlify.app/openshift-serverless/latest/observability/tracing/serverless-tracing-open-telemetry.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by maschmid** [comment]
QE approved

**Review by snarayan-redhat — COMMENTED** [review]
LGTM!

**Pull request merged**
