### PR TITLE
JIRA-OSDOCS3200: Added Autoscaling intro and hyperlink in ROSA service definition

### PR DESCRIPTION
**Pull request by sayjadha**
Versions:
PR applies to all versions after a specific version: 4.9+

Issue:
https://issues.redhat.com/browse/OSDOCS-3200

Link to docs preview:
http://file.rdu.redhat.com/sayjadha/JIRA-OSDOCS3200/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-autoscaling_rosa-service-definition

Change request:
Added introduction of autoscaling nodes and a cross-reference to the related documentation.

### CODE REVIEW

**Comment by yuwang-RH** [comment]
LGTM~

**Review by opayne1 — COMMENTED** [review]
lgtm!

**Pull request merged**
