### PR TITLE
[GH56976]: Minor grammatical change to "Responsibility assignment matrix" doc

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

Link to docs preview:

https://56976--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html
QE review:
- [ ] QE has approved this change.

Additional information:

Peer Review Team: I created this PR for a very minor change. There was no JIRA ticket or GH ticket that addressed the issue. I was advised that with an issue this small, it was not necessary, as long as pointed out the issue in the description (please see attached image). 
image

### CODE REVIEW

**Comment by mletalie** [comment]
\label peer-review-needed

**Review by adellape — APPROVED** [review]

**Pull request merged**
