### PR TITLE
OSDOCS-8328: Follow-up PR to add OCP conditionals to welcome page con…

### PR DESCRIPTION
**Pull request by bmcelvee**
Follow-up to https://github.com/openshift/openshift-docs/pull/67823

Version(s):
4.14+ 

Issue:
https://issues.redhat.com/browse/OSDOCS-8328

Link to docs preview:
**ROSA**: https://68289--docspreview.netlify.app/openshift-rosa/latest/welcome/

**OSD**: https://68289--docspreview.netlify.app/openshift-dedicated/latest/welcome/

**OCP**: https://68289--docspreview.netlify.app/openshift-enterprise/latest/welcome/

QE review:
No QE review required. 

Additional information:
@lahinson I'm adding conditionals to restrict this content to OCP. If we need to make any adjustments, please let me know!

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by lahinson** [comment]
Thanks @bmcelvee!

**Pull request merged**
