### PR TITLE
Importing VMware template

### PR DESCRIPTION
**Pull request by apinnick**

### CODE REVIEW

**Comment by jelkosz** [comment]
LGTM

**Comment by apinnick** [comment]
@kalexand-rh  Please review

**Review by bthurber — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
@aburdenthehand, are you ok with combining the template and VM content like this?

**Review by kalexand-rh — COMMENTED** [review]
This change LGTM, and if Andrew agrees, I'll merge.

**Comment by aburdenthehand** [comment]
@kalexand-rh - Indeed. LGTM. Thank you!

**Pull request merged**
