### PR TITLE
BZ2056430: Remove part of docs in STS AWS upgrade

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
For 4.9+

https://bugzilla.redhat.com/show_bug.cgi?id=2056430

Requires ack from @xingxingxia

### CODE REVIEW

**Comment by xingxingxia** [comment]
Though it is only a removal, seems still better to ask for check from STS teammate, reassigning, @lwan-wanglin could you look? Thanks

**Comment by lwan-wanglin** [comment]
@chinmayi-chandrasekar thanks for fixing it, LGTM!
/lgtm

**Pull request merged**
