### PR TITLE
OSDOCS-9448: modified the updating section for Microshift 4.16

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.16+

Issue:
[OSDOCS-9448](https://issues.redhat.com/browse/OSDOCS-9448)

Link to docs preview:
[About updates](https://75493--ocpdocs-pr.netlify.app/microshift/latest/microshift_updating/microshift-about-updates.html)
[Manual updates with RPM](https://75493--ocpdocs-pr.netlify.app/microshift/latest/microshift_updating/microshift-update-rpms-manually.html)
[Updates with RPM ostree](https://75493--ocpdocs-pr.netlify.app/microshift/latest/microshift_updating/microshift-update-rpms-ostree.html)

SME review:
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aravipra** [comment]
@copejon review and LGTM is required

**Comment by tmalove** [comment]
Hi @aravipra checking that you want this update in 4.16+? If 4.16+, I suggest updating that in comment 0 for clarity. Thanks.

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
