### PR TITLE
OSDOCS-2284: Added enabling multicast to ROSA and OSD with dedicated-admin ability…

### PR DESCRIPTION
**Pull request by jonquilwilliams**
… to do this feature

JIRA: https://issues.redhat.com/browse/OSDOCS-2284

OSD: https://deploy-preview-36079--osdocs.netlify.app/openshift-dedicated/latest/networking/openshift_sdn/enabling-multicast.html

ROSA: https://deploy-preview-36079--osdocs.netlify.app/openshift-rosa/latest/networking/openshift_sdn/enabling-multicast.html

Branch=dedicated-4   No CP and no milestones.

### CODE REVIEW

**Comment by yuwang-RH** [comment]
LGTM.

**Review by skrthomas — APPROVED** [review]
LGTM!

**Comment by EricPonvelle** [comment]
Aaren De Jong can you please take a look at this PR for SME acknowledgement?

**Comment by arendej** [comment]
for https://deploy-preview-36079--osdocs.netlify.app/openshift-dedicated/latest/networking/openshift_sdn/enabling-multicast.html
I tested this and the part in 4b where it says
> To start the multicast listener, in a new terminal window or tab, enter the following command:
It's actually more appropriate to make the #4 step happen in another terminal tab/window, because 4b relies on 4a, which won't carry over to another terminal unless it's exported.

**Pull request merged**
