### PR TITLE
BZ1759434 fix PV name in yaml

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1759434](https://bugzilla.redhat.com/show_bug.cgi?id=1759434)
@liangxia File names have been fixed, ready for QE. Thanks.

### CODE REVIEW

**Comment by huffmanca** [comment]
Looks good to me!

**Comment by liangxia** [comment]
LGTM (from QE)

**Comment by mburke5678** [comment]
@liangxia @bobfuru Should this change be rolled back to 3.11 as requested by this issue?
https://github.com/openshift/openshift-docs/issues/13065

**Comment by bobfuru** [comment]
> @liangxia @bobfuru Should this change be rolled back to 3.11 as requested by this issue?
> #13065

It does look like it should also be fixed in 3.11 in this example:
https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/persistent_storage_iscsi.html#iscsi-multipath

And in this example:
https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/persistent_storage_iscsi.html#iscsi-custom-iqn

@liangxia Can you confirm and I'll open a PR to fix?
@mburke5678

**Comment by liangxia** [comment]
@qinpingli  PTAL

**Comment by qinpingli** [comment]
@bobfuru Yes, both names are need to be fixed.

**Pull request merged**
