### PR TITLE
CNV#38977: missing single quotes in YAML

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.13+

Issue: [CNV-38977](https://issues.redhat.com//browse/CNV-38977)

Link to docs preview: https://72565--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/storage/virt-automatic-bootsource-updates#virt-disable-auto-updates-single-boot-source_virt-automatic-bootsource-updates

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by xphyr** [comment]
Looks perfect. Thanks for the quick fix.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
