### PR TITLE
Add NFD Operator to openshift docs

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

https://issues.redhat.com/browse/PSAP-355

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@ArangoGutierrez We will need to update the _topic_map.yml file to add this new topic to the site navigation under the Scalability and Performance guide. That way, we can see how the content builds. Let me know if you need my help doing that, and also if you prefer me to make my comments in this PR for you to address, or if you prefer me to fork your branch and apply the necessary style edits for you. It's just a matter of your preference. Thanks!

**Comment by ArangoGutierrez** [comment]
Today @zvonkok told me about the idea of not having this documentation under `scale and performance` but creating a new entry  , should we address that in this PR? 

cc @ashishkamra @gaurvsingh85

**Comment by nermina-redhat** [comment]
> Today @zvonkok told me about the idea of not having this documentation under `scale and performance` but creating a new entry , should we address that in this PR?
> 
> cc @ashishkamra @gauravsingh85

Hi, @ArangoGutierrez, I'm a new content strategist helping Ashley. She related that you were interested in creating a new guide. I recommend that we keep this topic in the existing docs and create a spike to assess the needs for a new guide that would include this topic and any others. For now, it doesn't make sense to have a single-topic guide. We want the docs to be just right; not too small and not too large. Let me know if you'd like to discuss further and work on docs requirements for a separate guide. There are many things to consider: naming, taxonomy, hierarchy, etc.  cc @ahardin-rh

**Comment by ArangoGutierrez** [comment]
> > Today @zvonkok told me about the idea of not having this documentation under `scale and performance` but creating a new entry , should we address that in this PR?
> > cc @ashishkamra @gauravsingh85
> 
> Hi, @ArangoGutierrez, I'm a new content strategist helping Ashley. She related that you were interested in creating a new guide. I recommend that we keep this topic in the existing docs and create a spike to assess the needs for a new guide that would include this topic and any others. For now, it doesn't make sense to have a single-topic guide. We want the docs to be just right; not too small and not too large. Let me know if you'd like to discuss further and work on docs requirements for a separate guide. There are many things to consider: naming, taxonomy, hierarchy, etc. cc @ahardin-rh

thanks @nermina-redhat , makes total sense, for now keeping NFD docs under `scale and performance` in the future we could have a separate topic

**Comment by ahardin-rh** [comment]
Closing this PR in favor of https://github.com/openshift/openshift-docs/pull/32761, where the work continues.

**Pull request closed without merging**
