### PR TITLE
Issue-4346 Added Cron Job Warning

### PR DESCRIPTION
**Pull request by bmcelvee**
Follow-up to https://github.com/openshift/openshift-docs/issues/4346#issuecomment-300680010

### CODE REVIEW

**Comment by bmcelvee** [comment]
@soltysh @juanluisvaladas PTAL

**Comment by juanluisvaladas** [comment]
@bmcelvee LGTM for OCP 3.5 but doesn't cover OCP's 3.3 and 3.4  scheduled jobs.

Since the file dosn't exist in this branch, I'd merge it and fix it in another PR

**Review by soltysh — APPROVED** [review]
lgtm

**Comment by bmcelvee** [comment]
Thanks! @ahardin-rh @adellape @mburke5678 please peer review 🎆

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
:+1:

**Comment by mburke5678** [comment]
LGTM

**Comment by bmcelvee** [comment]
[rev_history]
|xref:..dev_guide/cron_jobs.adoc#dev-guide-cron-jobs[Cron Jobs]
|Added warning to the thexref:..dev_guide/cron_jobs.adoc#dev-guide-cron-jobs[Cron Jobs] Overview section.
%

**Pull request merged**
