### PR TITLE
Edit suggested in file logging/cluster-logging.adoc

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/20111

### CODE REVIEW

**Comment by mburke5678** [comment]
@aburdenthehand @sheriff-rh FYI We got an issue to change the wording at the start of the _About cluster logging_ topic, as the sentence in the assembly is the same as the first sentence in the first module.

**Comment by sheriff-rh** [comment]
Looks fine to me, thanks @mburke5678 !

The build errors are as follows: 

asciidoctor: ERROR: includes/cluster-logging-about.adoc: line 25: unmatched macro: endif::openshift-enterprise,openshift-webscale,openshift-origin[]
asciidoctor: ERROR: includes/cluster-logging-about.adoc: line 32: unmatched macro: endif::openshift-dedicated[]
asciidoctor: ERROR: includes/cluster-logging-about.adoc: line 40: unmatched macro: endif::cnv-logging[]

Just double check the cluster-logging-about.adoc page and ensure that all ifs and endifs are in place - hard to tell from the snip shown in the `Files changed` section.

**Comment by aburdenthehand** [comment]
@mburke5678 From CNV perspective this looks good to me. Thank you

**Pull request merged**
