### PR TITLE
Change copyright from 2021 -> 2022

### PR DESCRIPTION
**Pull request by bobfuru**
These are the files where I am finding 2021 occurrences in the `openshift-docs` repo. Happy New Year! 🎉 

**Preview link (Legal page):** https://deploy-preview-40235--osdocs.netlify.app/openshift-enterprise/latest/welcome/legal-notice.html

Netlify doesn't show the footer but I built locally and it is rendering fine.

### CODE REVIEW

**Comment by bobfuru** [comment]
@vikram-redhat PTAL

**Comment by vikram-redhat** [comment]
Thank you @bobfuru! @

**Pull request merged**
