### PR TITLE
BZ1875952: Fixed vague information about cpu resource limits (number of cores and GPUs)

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
For versions 4.5+

https://bugzilla.redhat.com/show_bug.cgi?id=1875952

Direct link to doc preview: https://deploy-preview-33750--osdocs.netlify.app/openshift-enterprise/latest/machine_management/applying-autoscaling.html#configuring-clusterautoscaler

Ready for QA: @sunzhaohua2

### CODE REVIEW

**Comment by chinmayi-chandrasekar** [comment]
For versions 4.5+

https://bugzilla.redhat.com/show_bug.cgi?id=1875952

Direct link to doc preview: https://deploy-preview-33750--osdocs.netlify.app/openshift-enterprise/latest/machine_management/applying-autoscaling.html#configuring-clusterautoscaler

Ready for QA: @sunzhaohua2

**Comment by lpettyjo** [comment]
LGTM

**Comment by mburke5678** [comment]
LGTM

**Pull request merged**
