### PR TITLE
override of plugin list, jenkins config, after initial container star…

### PR DESCRIPTION
**Pull request by gabemontero**
…t with PVs

@bparees fyi

### CODE REVIEW

**Comment by bparees** [comment]
perfect, thanks @gabemontero !

@openshift/team-documentation ptal/merge.

**Comment by gabemontero** [comment]
bump @bmcelvee

**Comment by bmcelvee** [comment]
Thanks @gabemontero! LGTM

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Jenkins]
|Added `*OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG*` and `*OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS*` to the xref:../using_images/other_images/jenkins.adoc#jenkins-environment-variables[Jenkins Environment Variables] table.
%

**Pull request merged**
