### PR TITLE
[RHACS] ROX-24807: Release notes updates for 4.4.4

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.4

Issue:
https://issues.redhat.com/browse/ROX-24807

Link to docs preview:
https://78410--ocpdocs-pr.netlify.app/openshift-acs/latest/release_notes/44-release-notes#resolved-in-version-444_release-notes-44

SME review:
- [x] SME has approved this change.

### CODE REVIEW

**Review by adellape — APPROVED** [review]
LGTM

**Review by dcaravel — APPROVED** [review]

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM, merging.

**Pull request merged**
