### PR TITLE
OCPBUGS-30092-oci: Port the OCI AI and ABI docs sets to 4.14

### PR DESCRIPTION
**Pull request by dfitzmau**
PEER REVIEWER AND MERGE REVIEWER. This PR is not as monstrous as the label indicates :smile: . The PR is a porting PR in that 4.15 content needs to be applied to the enterprise-4.14. To avoid entanglement of changes between upstream branches, anything you identify as a needed change, I can address in https://github.com/openshift/openshift-docs/pull/72364

Change management notification has gone out for this change.

Version(s):
4.14

Issue:
[OCPBUGS-30092](https://issues.redhat.com/browse/OCPBUGS-30092)

Link to docs preview:
* [Using the Assisted Installer to install a cluster on OCI](https://72430--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_oci/installing-oci-assisted-installer)
* [Installing a cluster OCI by using the Agent-based Installer](https://72430--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_oci/installing-oci-agent-based-installer)

- [x] SME has approved this change.
- [x] QE has approved this change.

Additional information:
* [4.15:Using the Assisted Installer to install a cluster on OCI](https://docs.openshift.com/container-platform/4.15/installing/installing_oci/installing-oci-assisted-installer.html)
* [4.15:Installing a cluster OCI by using the Agent-based Installer](https://docs.openshift.com/container-platform/4.15/installing/installing_oci/installing-oci-agent-based-installer.html)

### CODE REVIEW

**Comment by mburke5678** [comment]
@dfitzmau I am assuming from your comments above that this PR ports the https://github.com/openshift/openshift-docs/pull/70025 and https://github.com/openshift/openshift-docs/pull/69901 PRs to 4.14. 
As such, I reviewed this PR assuming that the text has been reviewed already. As such, all LGTM. 
If I am incorrect and the text in this PR need individual reviewing, please let me know and I will revisit.

**Comment by dfitzmau** [comment]
> @dfitzmau I am assuming from your comments above that this PR ports the #70025 and #69901 PRs to 4.14. As such, I reviewed this PR assuming that the text has been reviewed already. As such, all LGTM. If I am incorrect and the text in this PR need individual reviewing, please let me know and I will revisit.

Thanks, @mburke5678 . Yes, the content will mirror 4.15, which has already been thoroughly reviewe and approved. Thanks for the LGTM!

**Comment by Srivaralakshmi** [comment]
@dfitzmau should this PR be CP-ed to only 4.14? Please confirm.

Is it not part of a continuous release that needs a CP to 4.14+?

**Pull request merged**
