### PR TITLE
OCPBUGS-2599 Added tuningOptions to Performance Opt. Section

### PR DESCRIPTION
**Pull request by Wiharris**
**OCPBUGS-2599**
Added tuningOptions to router performance optimizations section

**Version(s):**
* PR applies only to enterprise-4.11

**Issue:**
https://issues.redhat.com/browse/OCPBUGS-2599

**Link to docs preview:**

- https://52998--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/routing-optimization.html#router-performance-optimizations_routing-optimization

**QE review:  @juzhao **
- [x] QE has approved this change.

**Additional information:**
N/A

### CODE REVIEW

**Comment by juzhao** [comment]
maybe the right QE is @lihongan

**Comment by lihongan** [comment]
/lgtm
Thank you @Wiharris

**Comment by GroceryBoyJr** [comment]
@Wiharris the preview links are identical. Would you like to include the correct link for the second modified file?

**Comment by Wiharris** [comment]
> @Wiharris the docs preview links are identical. Would you like to include the correct link for the second modified file?

Thanks for the catch, James! I ended up removing the second link as both changes are on the same page and I just did not realize it before lol

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
