### PR TITLE
RHDEVDOCS-5864: Updated compatibility table to correct compatible pip…

### PR DESCRIPTION
**Pull request by shipsing**
**Purpose**: To resolve these issues: https://issues.redhat.com/browse/RHDEVDOCS-5864 and https://issues.redhat.com/browse/RHDEVDOCS-5783

**Aligned team**: DevTools

**Version for cherrypicking**: build-docs-1.0, build-docs-1.1

**Content for preview**:  

- https://70158--docspreview.netlify.app/openshift-builds/latest/about/ob-release-notes#compatibility-support-matrix_ob-release-notes
- https://70158--docspreview.netlify.app/openshift-builds/latest/about/build-strategies

**SME review**:  @ayushsatyam146 @divyansh42  

**QE review**:  @jitendar-singh 

**Peer review**:  @xenolinux

### CODE REVIEW

**Review by divyansh42 — COMMENTED** [review]
/lgtm

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by bscott-rh** [comment]
Merge review LGTM

**Pull request merged**
