### PR TITLE
Add a note on implication of oldest routes w/ a sharded setup.

### PR DESCRIPTION
**Pull request by ramr**
Docs for bugz 1357829.

@knobunc @bfallonf  @adellape  PTAL  Thx.

### CODE REVIEW

**Comment by knobunc** [comment]
LGTM

**Comment by bmeng** [comment]
@ramr @knobunc 
Hi, what blocks this to be merged?

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added a note on the implication of older routes with a sharded setup.
%

**Pull request merged**
