### PR TITLE
Follow-up Edits to PR1808 (S2I Ruby)

### PR DESCRIPTION
**Pull request by tpoitras**
https://github.com/openshift/openshift-docs/pull/1808

@bfallonf @ahardin-rh @adellape @tnguyen-rh Any issues?

### CODE REVIEW

**Comment by bfallonf** [comment]
@tpoitras LGTM :star2:

**Comment by tpoitras** [comment]
[rev_history]
|link:../using_images/s2i_images/ruby.html[Source-to-Image (S2I) -> Ruby]
|Added variables related to link:../using_images/s2i_images/ruby.html#s2i-images-ruby-config[Puma].
%

**Comment by tpoitras** [comment]
(added some xref anchors, too)

**Comment by tpoitras** [comment]
Leaving labeled as "future release" since the original PR#1808 hasn't been picked to enterprise-3.2 yet

**Pull request merged**
