### PR TITLE
Fix context variable connector

### PR DESCRIPTION
**Pull request by codyhoag**
Checked both `enterprise-4.2` and `enterprise-4.3` branches. They also only contain the four fixes in this PR, so the cherry-pick for them should suffice.

The `enterprise-4.1` branch contained a few more, so its changes were made in a separate PR: #18435

### CODE REVIEW

**Comment by mburke5678** [comment]
@codyhoag LGTM

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
