### PR TITLE
BZ#1927841: host network routers and OVN-K

### PR DESCRIPTION
**Pull request by mikemckiernan**
This is a followup request from Andrew. We
overlooked this page for the admonition.

Click and scroll for the pink box: https://deploy-preview-31358--osdocs.netlify.app/openshift-enterprise/latest/networking/network_policy/default-network-policy.html#nw-networkpolicy-project-defaults_default-network-policy

----
Applies to enterprise-4.6 through 4.8.  Milestone Next Release.

@openshift/team-documention PTAL.

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
/lgtm
FYI, @mikemckiernan this issue should be fixed on 4.8 version, So we need also update the docs when 4.8 GA.

**Review by bobfuru — COMMENTED** [review]
LGTM

**Pull request merged**
