### PR TITLE
Fixed command in osdk-golang-quickstart.adoc

### PR DESCRIPTION
**Pull request by hbelmiro**
Version(s): 4.13

Issue:

Link to docs preview: https://65561--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-quickstart.html

QE review:
- [ ] QE has approved this change.

Additional information:

The command uses a file and a namespace that don't exist. Probably a copy/paste error.

### CODE REVIEW

**Comment by hbelmiro** [comment]
cc @openshift/team-documentation

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
No QE required, merging.

**Pull request merged**
