### PR TITLE
Template example fix

### PR DESCRIPTION
**Pull request by ge0ffrey**
http://{PARAMETER_1}#{$PARAMETER_2} -> http://${PARAMETER_1}${$PARAMETER_2}

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@ahardin-rh, I think this looks ok. What do you think?

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
@xiuwang Can you please give this a QE review? Thanks!

**Comment by xiuwang** [comment]
LGTM

**Pull request merged**
