### PR TITLE
[OSDOCS-7934]: ROSA documentation is missing any reference for creating machine pool for specific AZ on a multi AZ cluster

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-7934
Link to docs preview:

https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes#creating_machine_pools_cli_rosa-managing-worker-nodes

https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about#machine-pools

QE review:
- [x] QE has approved this change.

Additional information:

image
image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 and/or @yuwang-RH,  when you get a moment can I please get a QE review for this PR? Thanks!

**Comment by mgahagan73** [comment]
https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about#machine-pools   looks fine

for:
https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes#creating_machine_pools_cli_rosa-managing-worker-nodes

Step 8 in the rosa create machine-pools command is repeated twice. See the 2 --disk-size=<disk_size>

rosa create machinepool --cluster=<cluster-name> --name=<machine_pool_id> --replicas=<replica_count> --instance-type=<instance_type> --labels=<key>=<value>,<key>=<value> --taints=<key>=<value>:<effect>,<key>=<value>:<effect> --use-spot-instances --spot-max-price=0.5 --disk-size=<disk_size> --availability-zone=<az> --disk-size=<disk_size>

**Comment by mletalie** [comment]
> https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about#machine-pools looks fine
> 
> for: https://65624--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes#creating_machine_pools_cli_rosa-managing-worker-nodes
> 
> Step 8 in the rosa create machine-pools command is repeated twice. See the 2 --disk-size=<disk_size>
> 
> rosa create machinepool --cluster= --name=<machine_pool_id> --replicas=<replica_count> --instance-type=<instance_type> --labels==,= --taints==:,=: --use-spot-instances --spot-max-price=0.5 --disk-size=<disk_size> --availability-zone= --disk-size=<disk_size>

Looks like there was a merge conflict. Fixed now. Thanks for catching!

**Comment by abhatt-rh** [comment]
> Hello @xueli181114 and/or @yuwang-RH, when you get a moment can I please get a QE review for this PR? Thanks!

Hi @mletalie Are we still awaiting QE review? Comment 0 checks the QE approved box, but I didn't see any indication of approval from the tagged folks in the PR or the Jira issue. Kindly confirm.

**Comment by abhatt-rh** [comment]
> > Hello @xueli181114 and/or @yuwang-RH, when you get a moment can I please get a QE review for this PR? Thanks!
> 
> Hi @mletalie Are we still awaiting QE review? Comment 0 checks the QE approved box, but I didn't see any indication of approval from the tagged folks in the PR or the Jira issue. Kindly confirm.

@mletalie confirmed over Slack that QE (Mike) has approved the change. Thanks!

**Pull request merged**
