### PR TITLE
BZ-1691019: Adding additional notes about concatenating files for cer…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…t chain

https://bugzilla.redhat.com/show_bug.cgi?id=1691019

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Hi @pamoedom, can you verify whether this update covers the sections where you were looking for the note to be added? Thanks!

Previews (internal): 
* http://file.rdu.redhat.com/~ahoffer/2020/BZ-1691019-update/install_config/certificate_customization.html#configuring-custom-certificates-retrofit-master
* http://file.rdu.redhat.com/~ahoffer/2020/BZ-1691019-update/install_config/certificate_customization.html#ansible-configuring-custom-certificates

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Comment by pamoedom** [comment]
@bergerhoffer LGTM also, thanks!

**Comment by gpei** [comment]
lgtm

**Pull request merged**
