### PR TITLE
bug 1692011 updating cluster config commands

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1692011

~~@jiajliu, will you PTAL?~~

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL?

**Comment by sunzhaohua2** [comment]
Line 33 should be `name: cluster`
Line 35 should be `selfLink: /apis/imageregistry.operator.openshift.io/v1/configs/cluster`

**Comment by kalexand-rh** [comment]
@sunzhaohua2, I've updated the PR. Thank you for the update! Will you please confirm?

**Comment by sunzhaohua2** [comment]
LGTM, thanks!

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
