### PR TITLE
update apiVersion in CAPI examples

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
N/A

Link to docs preview:
https://74678--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/capi-machine-management.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
can one of @sunzhaohua2 @huali9 or @miyadav PTAL for QE?

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
