### PR TITLE
Specify that F5 virtual servers must be configured by users as a pre-requisite

### PR DESCRIPTION
**Pull request by rajatchopra**
@openshift/networking PTAL

/cc @ahardin-rh

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rajatchopra Thanks! Looks good to me! Is this targeted for 3.5?

**Review by knobunc — APPROVED** [review]
LGTM.  Should the corresponding text in 'oadm router --help' also be amended?

**Comment by knobunc** [comment]
Oh, and is there a doc (either ours or F5s) that we should link to that tells people how to do so?

**Comment by rajatchopra** [comment]
@knobunc Added the section on how to configure the virtual servers. Has a detailed external link.

**Comment by rajatchopra** [comment]
@ahardin-rh Yes, this PR is intended for 3.5! Thanks.

**Comment by ahardin-rh** [comment]
Thank you! I will follow up with some minor edits in a separate PR

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/router/f5_router.adoc#install-config-router-f5[Setting up a Router -> Using the F5 Router Plug-in]
|Specified that F5 virtual servers must be configured by users as a prerequisite.
%

**Comment by vikram-redhat** [comment]
@ahardin-rh @bfallonf - this is an old PR, but @rajatchopra confirmed via email today that this should be applied to 3.4 as well.

Brice will backport this to 3.4, along with Ashley's followup and https://github.com/openshift/openshift-docs/pull/5188/.

**Pull request merged**
