### PR TITLE
 kubelet is not able to convert  TLS Security profile 1.0 to 1.1 for old, 1.3 to 1.2 for intermediate.

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OCPBUGS-1241

### CODE REVIEW

**Comment by mburke5678** [comment]
@harche PTAL

**Comment by rphillips** [comment]
I don't believe this is correct for clusters >= 4.6. TLS 1.3 is supported. Referenced here:

https://access.redhat.com/articles/5348961#ocp-4---node-13

**Comment by mburke5678** [comment]
@rphillips I removed the entire note. Is that what you expected?

**Comment by mburke5678** [comment]
@rphillips I removed the entire note. Is that what you expected?

**Comment by rphillips** [comment]
Yes. This is what I would expect.

/lgtm

**Comment by mburke5678** [comment]
@lihongan You reviewed the PR when this note was added to the docs. Is this a PR you can review? Thank you.

**Comment by lihongan** [comment]
It looks good to me. Thank you @mburke5678

**Comment by jeana-redhat** [comment]
LGTM

/remove-label peer-review-in-progress
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]

**Pull request merged**
