### PR TITLE
OSDOCS-10762:Updated regulatory compliance info for ROSA with HCP.

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.15+

Issue:
[OSDOCS-10762](https://issues.redhat.com/browse/OSDOCS-10762)

Link to docs preview:

- https://76944--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition.html
- https://76944--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html

Peer review:
- [x] Peer reviewer has approved this change.

SME review:
- [x] SME has approved this change.

Additional information:
QE approval not needed as no process verification or substantial update to docs made.

### CODE REVIEW

**Comment by AedinC** [comment]
@arendej Can you please review? Thanks.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by arendej — APPROVED** [review]
lgtm

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
