### PR TITLE
BZ2068397 Manualling copying changes from PR 55538 to 4.11

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.11 only

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2068397

Link to docs preview:
https://55539--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-yaml-aws_creating-machineset-aws

QE review:
- [ ] QE has approved this change.

Additional information:
- Original PR: https://github.com/openshift/openshift-docs/pull/55373
- Merge into `enterprise-4.11`
- Cherry-picked commit from 4.10: https://github.com/openshift/openshift-docs/pull/55538/commits

### CODE REVIEW

**Comment by agantony** [comment]
QE review needed: @lyman9966

**Review by jeana-redhat — APPROVED** [review]
LGTM, thanks!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
