### PR TITLE
CNV-9233: removing offensive language

### PR DESCRIPTION
**Pull request by ousleyp**
- [CNV-9233](https://issues.redhat.com/browse/CNV-9233)
- Deleted unused assembly/module (the module had an instance of "master" that I was going to change to "main" until I realized we weren't using it)
- delayed until 4.9

Preview build:
- [See the example output after step 3](https://deploy-preview-33707--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/advanced_vm_management/virt-configuring-pci-passthrough#virt-binding-devices-vfio-driver_virt-configuring-pci-passthrough)

### CODE REVIEW

**Comment by vladikr** [comment]
@ousleyp Thanks!
This looks good to me.
/lgtm
/cc @fabiand

**Comment by fabiand** [comment]
@vladikr I don't think that these changes are already in 4.8, are they?

/hold

**Comment by kbidarkar** [comment]
Below is the output from 4.8.0-rc.0.
So my best Guess is  OCP might no be updating this yet, as the changes are not even in `rc.0` of 4.8


[kbidarka@localhost auth]$ oc get clusterversion 
NAME      VERSION      AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.0-rc.0   True        False         5h18m   Cluster version is 4.8.0-rc.0
[kbidarka@localhost auth]$ oc get mc 
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m
00-worker                                          3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m
01-master-container-runtime                        3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m
01-master-kubelet                                  3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m
01-worker-container-runtime                        3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m
01-worker-kubelet                                  3f6db243f2d6651720daa658e8edc830f47dd184   3.2.0             6h4m

This docs update could cause confusion, so would say,
/hold

**Comment by vladikr** [comment]
@ousleyp yeah, I think @fabiand and @kbidarkar are right. I saw that this is what OCP is going to rename the nodes to (s/master/supervisor) and I was under the impression that it will happen in the 4.8 version. Looks like I'm wrong.

**Comment by vikram-redhat** [comment]
@ousleyp can this be closed?

**Comment by ousleyp** [comment]
Will reopen a new PR for 4.9.

**Pull request closed without merging**
