### PR TITLE
admin cluster metrics: minor tweaks

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@jimmidyson can you double-check the service definition I added?

**Comment by jimmidyson** [comment]
@sosiouxme I assume you're trying to add a service for the heapster REST endpoint? You'll need to add port 8082 the pod template too IIRC.

**Comment by sosiouxme** [comment]
@jimmidyson actually I'm just trying to bring consistency to the text (which says "here's a service") and the actual definition. If heapster doesn't present anything you'd usually want to access via a service, then we could just change the text instead.

**Comment by jimmidyson** [comment]
@sosiouxme Aha! For now, let's just update the text - need to figure out how to secure the REST service appropriately.

**Comment by sosiouxme** [comment]
Alright then this should be ready to merge.

**Comment by jimmidyson** [comment]
LGTM

**Comment by adellape** [comment]
:+1:

**Pull request merged**
