### PR TITLE
bugfix: rename ibm_cloud* subdirectories

### PR DESCRIPTION
**Pull request by sean-freeman**
Move all content currently under `*ibm_cloud` to `*ibm_cloud_classic`, as all this content refers to `IBM Cloud (Classic)`; see additional information. Subsequently move all content currently under `*ibm_cloud_public` to `*ibm_cloud`, as there is no distinction - as defined by Gartner, Cloud Service Providers (CSP) which operate Public Clouds and are considered Hyperscalers are AWS, MS Azure, GCP, IBM Cloud, Oracle Cloud.

Version(s):
4.14+, apply content fix to latest and future releases only

Issue:
- None (GH or Jira), this is community author contribution

Link to docs preview:
- Not described how to achieve preview, content has not changed except rename of subdirectories for correct future content additions

QE review:
- [ ] QE has approved this change.

Additional information:
- Bugfix to rename related content in subdirectory correctly titled for `IBM Cloud (Classic)`, formerly Softlayer; akin to `AWS (Classic)` and `MS Azure (Classic/ASM)` which are unsupported by OpenShift

### CODE REVIEW

**Comment by sean-freeman** [comment]
@openshift/team-documentation

**Comment by sean-freeman** [comment]
@bscott-rh Can we progress with this? The PR is just to correct the subdir names (in preparation for future append to the content)

**Comment by bscott-rh** [comment]
> @bscott-rh Can we progress with this please? The PR is just to correct the subdir names (in preparation for future append to the content)

Hi Sean, I will most likely not be able to review this until next week as this is the final week before 4.17 GA.

**Comment by sean-freeman** [comment]
Review has taken too long and other structure changes have occured.  Will repeat and force push new commit.

**Comment by sean-freeman** [comment]
@bscott-rh Please see replacement PR #82684 and close this PR accordingly. Changes made in latest PR use the latest from `main` branch for the rename of the subdirectories.

**Pull request closed without merging**
