### PR TITLE
reorder TOC

### PR DESCRIPTION
**Pull request by kalexand-rh**
Preview build here: http://file.rdu.redhat.com/kalexand/051319/reorder_toc/welcome/index.html

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, PTAL?

**Comment by ahardin-rh** [comment]
LGTM!

**Review by adellape — APPROVED** [review]
:+1:

**Comment by bergerhoffer** [comment]
Definitely looks like an improvement to me.

**Comment by kalexand-rh** [comment]
It looks like there are no objections, so I'm going to merge. Thanks!

**Pull request merged**
