### PR TITLE
Added --dry-run option for `oc adm drain` for 3.7

### PR DESCRIPTION
**Pull request by ahardin-rh**
Added per discussion in https://github.com/openshift/openshift-docs/pull/5709#issuecomment-367043544

@pravisankar PTAL

### CODE REVIEW

**Review by pravisankar — APPROVED** [review]
LGTM

**Comment by vikram-redhat** [comment]
@ahardin-rh would this not apply to 3.9 as well?

**Comment by ahardin-rh** [comment]
@vikram-redhat Not in this case. The new options for 3.9 are introduced via https://github.com/openshift/openshift-docs/pull/7881

**Comment by vikram-redhat** [comment]
@ahardin-rh - awesome. Thanks!

**Pull request merged**
