### PR TITLE
PERFSCALE-1081: Clarify that perf scale guidance applies to SDN not OVN

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/PERFSCALE-1081

Preview build: https://deploy-preview-32445--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/planning-your-environment-according-to-object-maximums.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@chaitanyaenr @mffiedler PTAL

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by mffiedler — APPROVED** [review]
LGTM

**Pull request merged**
