### PR TITLE
OADP-2167: typo in troublehsooting module

### PR DESCRIPTION
**Pull request by anarnold97**
OADP 1.1 & OADP 1.2; OCP 4.11+

[OADP-2167](https://issues.redhat.com/browse/OADP-2167)

Simple typo fix

Version(s):

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14

Issue:

https://issues.redhat.com/browse/OADP-2167

Link to docs preview:

https://62657--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/troubleshooting.html#migration-debugging-velero-admission-webhooks-ibm-appconnect_oadp-troubleshooting

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
@stillalearner - please can you review and approve? thanks

**Review by stillalearner — APPROVED** [review]
LGTM.

**Review by skrthomas — APPROVED** [review]
/lgtm

**Comment by anarnold97** [comment]
@skrthomas - please can I push this to *merge review*? thanks

**Comment by skrthomas** [comment]
@anarnold97 I added the merge review label for you. Someone on the current squad rotation should get back to this within the next few hours :)

**Pull request merged**
