### PR TITLE
Reverts changes made at OSDOCS-3625

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-4702

Link to docs preview. You probably don't have to look at every single one that has omitted content. 

Preview of added content: https://54542--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-configuration-parameters-network_installing-bare-metal-network-customizations 

Preview of omitted AWS content: https://54542--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-vpc.html#installation-configuration-parameters-network_installing-aws-vpc

Alibaba: https://54542--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_alibaba/installing-alibaba-customizations.html#installation-configuration-parameters-network_installing-alibaba-customizations 

Azure Stack Hub: https://54542--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.html#installation-configuration-parameters-network_installing-azure-stack-hub-network-customizations 

GCP: https://54542--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters-network_installing-gcp-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman** [comment]
@stevsmit, thanks for your help with this!

**Comment by jboxman-rh** [comment]
@stevsmit, thanks for your help with this!

**Pull request merged**
