### PR TITLE
WMCO 1.0.4 release notes

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: https://deploy-preview-31531--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes.html#wmco-1-0-4

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
Do we need to add `You must upgrade to WMCO 1.0.4 before upgrading to WMCO 2.x.` as we did for 1.0.3? Otherwise LGTM.

**Comment by codyhoag** [comment]
@sgaoshang can you confirm this from the QE perspective? Thanks!

**Comment by sgaoshang** [comment]
@codyhoag LGTM, thanks.

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by codyhoag** [comment]
The WMCO 1.0.4 is now live. Merging

**Pull request merged**
