### PR TITLE
Trello-793 Deprication Announcement

### PR DESCRIPTION
**Pull request by bmcelvee**
https://trello.com/c/xGqKhT4x/793-add-deprecation-announcement-for-hawkular

### CODE REVIEW

**Comment by bmcelvee** [comment]
@tkatarki PTAL. We're also tracking the announcement in the Release Notes Tracker: https://github.com/openshift/openshift-docs/issues/6458.

**Comment by bmcelvee** [comment]
@ahardin-rh PTAL :snowflake:

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bmcelvee** [comment]
Thanks! :sun_with_face:

**Pull request merged**
