### PR TITLE
Fix Machine create for replacing BM control plane

### PR DESCRIPTION
**Pull request by pmannidi**
Machine create YAML shouldn't have customDeploy in 4.8, it's introduced in 4.10

Version(s):

Issue:

#46644

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by pmannidi** [comment]
@pamoedom  FYI https://github.com/openshift/cluster-api-provider-baremetal/blob/release-4.10/pkg/apis/baremetal/v1alpha1/baremetalmachineproviderspec_types.go#L80-L85 and I also see references in https://github.com/openshift/baremetal-operator

**Comment by pamoedom** [comment]
Thanks @pmannidi, I was checking on [cluster-baremetal-operator](https://github.com/openshift/cluster-baremetal-operator) instead of [baremetal-operator](https://github.com/openshift/baremetal-operator), makes more sense now.

However, please note that `customDeploy` seems to be also present in 4.9 [here](https://github.com/openshift/baremetal-operator/blob/release-4.9/apis/metal3.io/v1alpha1/baremetalhost_types.go#L395), can you please double check? maybe it was backported?

Regards.

**Comment by pmannidi** [comment]
@pamoedom the partial code landed in 4.9 but its not supported for releases <4.10

**Comment by pamoedom** [comment]
ACK @pmannidi, thanks for the confirmation.

**Comment by mjpytlak** [comment]
@ktothill Ahead of merging this update, I wanted to check with you to see if removing ` customDeploy` from the 4.8 and 4.9 versions of the OCP doc would require any other updates on your side. Want to make sure we do not reference it or its use elsewhere. Thank you.

**Comment by mjpytlak** [comment]
@pmannidi Once the writer who owns this content confirms no other changes would be required as a result of removing the reference, I can get this merged into 4.8. I will pull a separate PR to make the change in 4.9.

**Pull request closed without merging**
