### PR TITLE
Skip Netlify and Vale checks for cherrypick bot

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Allows us to skip the Vale and Netlify stages for PRs from `openshift-cherrypick-robot`.
Saves Travis CI resources and approximately 1 minute 20 seconds.

Reference: https://docs.travis-ci.com/user/conditions-v1

Cherry-pick into:
- `enterprise-4.12`
- `enterprise-4.13`
- `enterprise-4.11`

And other branches as needed.

### CODE REVIEW

**Comment by aireilly** [comment]
Great change! LGTM

**Review by aireilly — COMMENTED** [review]
Great change! LGTM

**Comment by bergerhoffer** [comment]
@gaurav-nelson Just checking, did this need to be cherry picked to 4.11+ like it is marked?

**Comment by gaurav-nelson** [comment]
OH yes! thank you 🙌 @bergerhoffer Looks like I missed manual cherry-picks.

**Pull request merged**
