### PR TITLE
Edits of Cluster Monitoring Operator docs

### PR DESCRIPTION
**Pull request by ahardin-rh**
@sjug Applying your outlined edits

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@mrsiano @sjug PTAL

**Comment by sjug** [comment]
Generally our values for the variables are:
`PROMETHEUS_RETENTION_PERIOD=15d` (string converted to time, unit is time s/m/h/d) 

```
PROMETHEUS_STORAGE_SIZE=2000Gi
ALERTMANAGER_STORAGE_SIZE=20Gi
```
These are storage values: 
>  You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki.

**Comment by ahardin-rh** [comment]
@sjug I made the edits. Here's a pretty build: http://file.rdu.redhat.com/~ahardin/04032019/cluster-monitoring-operator-edits/scalability_and_performance/scaling-cluster-monitoring-operator.html#configuring-cluster-monitoring-cluster-monitoring-operator

@mffiedler Can you please review as well?

**Review by mffiedler — APPROVED** [review]
/lgtm

**Pull request merged**
