### PR TITLE
bug 1639080 clarifying insecure connection override

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1639080

@ericavonb, how does this sound?

@jianlinliu, will you PTAL?

This bug was filed against 3.10 - do you know how far back this change is true?

### CODE REVIEW

**Comment by ericavonb** [comment]
@kalexand-rh lgtm!

**Comment by kalexand-rh** [comment]
@stuartchuan, PTAL?

**Comment by kalexand-rh** [comment]
@stuartchuan, the bug says that it's taking effect anyway.

**Comment by kalexand-rh** [comment]
@stuartchuan,  will you PTAL?

**Comment by stuartchuan** [comment]
I still think this is not the root cause fix, just a workaround. I think the bug should be fixed in code but not doc.
@ericavonb what do you think?

**Comment by kalexand-rh** [comment]
@ericavonb, when you have a minute, will you PTAL?

**Comment by ericavonb** [comment]
@kalexand-rh @stuartchuan I think this is the correct behavior (with the docs here) in accord with the standards around ldap urls and tls.

**Comment by kalexand-rh** [comment]
Thanks @ericavonb. @stuartchuan, if this is correct, can I merge this to 3.10 and 3.11?

**Comment by stuartchuan** [comment]
@kalexand-rh it's OK to merge.

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
