### PR TITLE
BZ-1906726: Adding a note to the Getting Started with CLI about namespaces

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.6+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1906726
Preview Link: [Viewing pods](https://deploy-preview-43559--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#viewing-pods)
QE ack needed.

### CODE REVIEW

**Review by jeana-redhat — COMMENTED** [review]
LGTM

**Comment by kasturinarra** [comment]
@sagidlow should we add  something like "By default, the namespace of the pod is used when a namespace is not specified when oc is run inside a pod"

**Comment by kasturinarra** [comment]
@sagidlow s/Running/run may be ?

**Comment by sagidlow** [comment]
@kasturinarra updated :) PTAL.

**Comment by kasturinarra** [comment]
@sagidlow thanks !!

**Pull request merged**
