### PR TITLE
Documentation wrong regarding FIPS mode and FCOS

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/okd/issues/488

### CODE REVIEW

**Comment by mburke5678** [comment]
@vrutkovs I think I got all the FIPS references out of the OKD docs. 
* Most of the changes were in the install docs, in the _Sample customized install-config.yaml file_ to remove the `fils: false` parameter. 
* A few in the _Security and Compliance_ book. 
* The _Adding RHEL compute machines to an OKD cluster_ section in _Post-install_ -> _Node tasks_  has some.  This section will be removed by another PR that I need to merge.

Preview: http://file.rdu.redhat.com/~mburke/okd-remove-fips/installing/installing_aws/installing-aws-customizations.html#installation-aws-config-yaml_installing-aws-customizations

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Review by vrutkovs — APPROVED** [review]

**Pull request merged**
