### PR TITLE
Bug 1605114 Updated vmware config file

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1605114

Will verify in the BZ.

### CODE REVIEW

**Comment by dav1x** [comment]
This looks great! Thank you

**Comment by vikram-redhat** [comment]
@bfallonf this can be merged. I believe it is Origin only.

**Comment by bfallonf** [comment]
@vikram-redhat I was waiting for the BZ reporter to verify the change, which they now have. It's now on QA in the BZ.

It's for enterprise-3.9 and above (which is what QA is verifying).

**Comment by bmeng** [comment]
@jhou1 Can you help check this doc PR? As you should be familiar with vshpere setup.

**Comment by jhou1** [comment]
LGTM

**Comment by bfallonf** [comment]
Thanks @bmeng @jhou1 . No peer review needed. I'll merge.

**Pull request merged**
