### PR TITLE
fix ingress example

### PR DESCRIPTION
**Pull request by a7vicky**

### CODE REVIEW

**Comment by skrthomas** [comment]
LGTM as long as QE acks.

**Comment by a7vicky** [comment]
@bobfuru  AFAIK this is applicable for any ingress object with apiVersion `networking.k8s.io/v1`

**Comment by a7vicky** [comment]
@lihongan  thanks for the review. I have updated another ingress example.

**Comment by bobfuru** [comment]
> @bobfuru AFAIK this is applicable for any ingress object with apiVersion `networking.k8s.io/v1`

@skrthomas Can you please look at this as you are a primary Network Edge writer? A quick search of our openshift-docs repo returns 87 results for occurrences of `networking.k8s.io/v1`, so it would be good to make sure any other examples are also updated where necessary. 🙇

**Comment by skrthomas** [comment]
> > @bobfuru AFAIK this is applicable for any ingress object with apiVersion `networking.k8s.io/v1`
> 
> @skrthomas Can you please look at this as you are a primary Network Edge writer? A quick search of our openshift-docs repo returns 87 results for occurrences of `networking.k8s.io/v1`, so it would be good to make sure any other examples are also updated where necessary. 🙇

@bobfuru There are a lot of occurrences of `networking.k8s.io/v1`. I also searched for `serviceName` and `servicePort`, and those results were a lot more reasonable. There weren't any other instances of the same kind of errors. I did see the 2 that Hongan and Abhishek pointed out and that was all. There were a few other areas outside Networking but I didn't see the error there.

**Comment by bobfuru** [comment]
Hi @lihongan - once more PTAL to be sure that the additional example also looks good and then I can merge. Thanks!

**Comment by lihongan** [comment]
LGTM.
Thank you all!

**Comment by bobfuru** [comment]
Confirmed that this example exists in [4.6](https://docs.openshift.com/container-platform/4.6/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)+, so I will cherrypick back to each version starting in 4.6.

**Pull request merged**
