### PR TITLE
GH#38021:Fix ClusterResourceOverride examples

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/38021

Previews:
[Cluster-level overcommit using the Cluster Resource Override Operator](https://deploy-preview-38138--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-resource-override_nodes-cluster-overcommit)[
Configuring cluster-level overcommit](https://deploy-preview-38138--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-resource-configure_nodes-cluster-overcommit)

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio Sunil -- You reviewed this topic when we first brought it into 4.x docs. Can you PTAL at this small change?

**Comment by tkashem** [comment]
@mburke5678  i have not been involved after the first release, please ping someone from the node team to review this.

**Comment by mburke5678** [comment]
@rphillips  Should be a simple review. Can you take a look or assign to someone who can?

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
