### PR TITLE
WIP Add openshift_logging_curator_ops_default_days variable

### PR DESCRIPTION
**Pull request by jboxman**
- BZ https://bugzilla.redhat.com/show_bug.cgi?id=1633337

### CODE REVIEW

**Comment by jboxman** [comment]
@openshift/team-documentation, the feature work for this change was completed here: https://bugzilla.redhat.com/show_bug.cgi?id=1567231

Who might be someone to reach out to so I ensure the descriptions for the updated variables in this PR are accurate?

Thanks.

**Comment by kalexand-rh** [comment]
LGTM. It looks like a logging parameter.

@anpingli, will you PTAL and confirm which versions this change is valid in? The bug's filed against 3.6, but Vikram said to change 3.9 in a comment.

**Comment by mburke5678** [comment]
@jboxman @kalexand-rh According to the feature BZ, the variable was added for 3.9+: https://bugzilla.redhat.com/show_bug.cgi?id=1567231#c3

**Comment by jboxman** [comment]
Hi @anpingli @QiaolingTang,

Can you PTAL at this PR and let me know if this change makes sense? I updated the table to include the new configuration variable mentioned in this BZ[0]. Can you confirm if this applies to 3.10 and 3.11 in addition to 3.9?

Thank you.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1633337

**Comment by jboxman** [comment]
> Hi @anpingli @QiaolingTang,
> 
> Can you PTAL at this PR and let me know if this change makes sense? I updated the table to include the new configuration variable mentioned in this BZ[0]. Can you confirm if this applies to 3.10 and 3.11 in addition to 3.9?
> 
> Thank you.
> 
> [0] https://bugzilla.redhat.com/show_bug.cgi?id=1633337

Hi @anpingli @QiaolingTang

Any update on this? Or is there a different person that can look at this change?

Thank you.

**Comment by jboxman** [comment]
@vikram-redhat who might be a good choice to look at this? It's a relatively small change: Adding a new variable and a description for it.

**Comment by vikram-redhat** [comment]
Hi @jboxman - the QE team will be back next week.

**Comment by jboxman** [comment]
Based on updates to the BZ[0][1], this PR may not be the best approach for the issue.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1633337#c6
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1633337#c7

**Comment by jboxman** [comment]
This was resolved in a different PR (https://github.com/openshift/openshift-docs/pull/13980, https://github.com/openshift/openshift-docs/pull/13978). Closing.

**Pull request closed without merging**
