### PR TITLE
Fixed typos in the Configuring Node Resources example

### PR DESCRIPTION
**Pull request by ghost**
@ghyde Please review. This is a follow-up to https://github.com/openshift/openshift-docs/pull/5373.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Comment by ghyde** [comment]
@tmorriso-rh LGTM

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Pull request merged**
