### PR TITLE
RHDEVDOCS 6058 add Pipelines 1.15 to distromap

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

main only

Issue:

RHDEVDOCS 6058

Link to docs preview:

n/a

QE review:
n/a

Additional information:

This PR enables building a new version of a standalone documentation set on docs.openshift.com. This PR does not alter any documentation content, so no documentation preview is available.

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6058

**Comment by Srivaralakshmi** [comment]
LGTM

**Comment by stevsmit** [comment]
LGTM

**Pull request merged**
