### PR TITLE
TELCODOCS-1199: Removed  module from assembly.

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: [TELCODOCS-1199](https://issues.redhat.com/browse/TELCODOCS-1199)

For: Version 4.12+

Doc Preview [here](https://57430--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-deploying-far-edge-clusters-at-scale.html)

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Comment by ktothill** [comment]
Who: Chad Crum,QE
Timestamp: March 20, 2023  15:07
Summary: Requested `LGTM` from Chad.

Next Steps:
- [ ] Receive `LGTM` from Chad
- [ ] Confirm with Dan whether this requires change management.

**Comment by ktothill** [comment]
@chadcrum @trewest could I please get a QE review of this module deletion from the assembly? Thank you!!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM

**Comment by ktothill** [comment]
Change Management Email sent 3/27.

**Comment by ktothill** [comment]
**Next Steps:**
Updated Change Management email sent 4/12.

 [ ] - Receive `LGTM` from all stakeholders.

**Pull request merged**
