### PR TITLE
OSSMDOC-206: Update upstream/downstream topic for Federation

### PR DESCRIPTION
**Pull request by JStickler**
Remove the topic that states that we do not support Federation.

Eng review - brian-avery
Peer review -  bmcelvee

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! Just needs SME/QE acks, and this PR will be all set. 

Linking the Jira issue here: https://issues.redhat.com/browse/OSSMDOC-206

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
