### PR TITLE
TELCODOCS-1339: Fix linking in Installing on AWS

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.13, 4.14

Issue: https://issues.redhat.com/browse/TELCODOCS-1339

Link to docs preview: https://60497--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/preparing-to-install-on-aws.html#choosing-an-method-to-install-ocp-on-aws-single-node

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
