### PR TITLE
OSDOCS-3551: Update AMIs for 4.11 GA

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
CP to 4.11

Issue:
This PR addresses [OSDOCS-3551](https://issues.redhat.com/browse/OSDOCS-3551).

Link to docs preview:
[RHCOS AMIs for the AWS Infrastructure](http://file.rdu.redhat.com/mpytlak/osdocs-3547/installing/installing_aws/installing-restricted-networks-aws.html#installation-aws-user-infra-rhcos-ami_installing-restricted-networks-aws)

### CODE REVIEW

**Comment by miabbott** [comment]
@mjpytlak Unfortunately there is a late breaking blocking bug that we need to address that is going to require recreating all of the RHCOS bootimage artifacts, including the Amazon AMIs

https://bugzilla.redhat.com/show_bug.cgi?id=2106058

**Comment by mjpytlak** [comment]
@miabbott Looks like the content of rhcos.json [1] has been updated since my original commit. Good to update the doc at this point? 

[1] https://github.com/openshift/installer/blob/release-4.11/data/data/coreos/rhcos.json

**Comment by mike-nguyen** [comment]
@mjpytlak micah has moved onto a new role.  I just verified that the ova in https://github.com/openshift/installer/blob/release-4.11/data/data/coreos/rhcos.json has the fix for https://bugzilla.redhat.com/show_bug.cgi?id=2106058 so you should be good to update the doc

**Comment by mjpytlak** [comment]
@mike-nguyen PTAL. Thanks!

**Comment by mike-nguyen** [comment]
LGTM

**Comment by mjpytlak** [comment]
Peer reviewer: This is ready for merge after the review is complete. Thanks.

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Pull request merged**
