### PR TITLE
Fixing some typos in main

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12+

Issue:
N/A

Link to docs preview:
Not adding previews,  character typos only. 

QE review:
N/A

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
lgtm

/label peer-review-done
/remove-label peer-review-in-progress

**Review by JoeAldinger — APPROVED** [review]
/lgtm

**Comment by JoeAldinger** [comment]
Whoops sorry @michaelryanpeter didn't see you were reviewing this. Well this is extra lgtm 😄

**Comment by michaelryanpeter** [comment]
No problem, @JoeAldinger. Lately, it seems like the `/label` commands in comments can be slow to update.

**Pull request merged**
