### PR TITLE
BZ#2212847: Fix mustgather image name

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13+

Issue: [CNV-29450](https://issues.redhat.com//browse/CNV-29450), [BZ#2212847](https://bugzilla.redhat.com/show_bug.cgi?id=2212847)

Link to docs preview:

* [About the must-gather tool](https://60892--docspreview.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data.html#about-must-gather_gathering-cluster-data)
* [Gathering data about specific features](https://60892--docspreview.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data)
* [Using the must-gather tool for OpenShift Virtualization](https://60892--docspreview.netlify.app/openshift-enterprise/latest/virt/support/virt-collecting-virt-data.html#virt-using-virt-must-gather_virt-collecting-virt-data)
* [must-gather tool options](https://60892--docspreview.netlify.app/openshift-enterprise/latest/virt/support/virt-collecting-virt-data.html#virt-must-gather-options_virt-collecting-virt-data)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by dbasunag — APPROVED** [review]
I found another link with cnv-must-gather image information: https://docs.openshift.com/container-platform/4.13/service_mesh/v2x/ossm-troubleshooting-istio.html

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
