### PR TITLE
OSSM-6903: Create redirect from OCP stub page to 3.0 standalone doc

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OCP 4.14+

Issue: https://issues.redhat.com/browse/OSSM-6903

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
Rebased PR on 8/28/24

**Comment by rh-tokeefe** [comment]
Rebased on 8/28/24

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
All the cherrypicks failed, but IIRC these probably actually don't need to be picked anyway.

**Pull request merged**
