### PR TITLE
To add DCs to installer for OCP 4.16

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.16+

Issue:

Link to docs preview: https://77345--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-cloud-account-power-vs#installation-ibm-power-vs-regions_installing-ibm-cloud-account-power-vs

QE review:
- [x] QE has approved this change.

Additional information:
Review draft: https://docs.google.com/document/d/1_YXWpEgIcxaaWLEypaqxubxuF67pbeD8W8dYchcZBuA/edit

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Comment by skopacz1** [comment]
Sorry - the content looks good to merge, but just realized that it's not clear whether @mjturek is the QE reviewer for this PR or not. Does this PR have QE review? If not, please get QE review and then I can merge this PR

**Comment by alishaIBM** [comment]
> Sorry - the content looks good to merge, but just realized that it's not clear whether @mjturek is the QE reviewer for this PR or not. Does this PR have QE review? If not, please get QE review and then I can merge this PR

Yes , @mjturek is the QE reviewer for this PR. 

@skopacz1 request you to do the needful. Thanks.

**Pull request merged**
