### PR TITLE
OCPBUGS#24561: fix typo busybox yaml

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OCPBUGS-24561

Link to docs preview:
[Using manifests example](https://69121--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-applications#microshift-applying-manifests-example_applications-microshift)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
Change LGTM. 

Related Q: is line 32 (`sudo`) actually a command?

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by ShaunaDiaz** [comment]
> Change LGTM.
> 
> Related Q: is line 32 (`sudo`) actually a command?
> 
> /remove-label peer-review-in-progress /remove-label peer-review-needed /label peer-review-done

Yes, it gives the user root-access to execute whatever that command is.

**Pull request merged**
