### PR TITLE
Changed CLUSTER_IP to Mongo DB Service Name

### PR DESCRIPTION
**Pull request by mburke5678**
From Issue https://github.com/openshift/openshift-docs/issues/2626

### CODE REVIEW

**Comment by mburke5678** [comment]
@jwforres @luciddreamz PTAL

**Comment by luciddreamz** [comment]
Right above that command, you no longer need this bit from the previous section: 

2. Next, get the internal IP address and port of the newly-created MongoDB service:

`$ oc get services`

Note the CLUSTER_IP of the MongoDB service before heading to the next section.

**Comment by mburke5678** [comment]
@zhouying7780  PTAL Is this change in your area?

**Comment by mburke5678** [comment]
@mdshuai Does one of your teams handle this area?  
From Issue #2626
"In the DB provisioning step in the getting started guide we are telling people to use the CLUSTER_IP of the service, when all they need to do within the same namespace is use the name of the service..."

**Comment by mburke5678** [comment]
@mdshuai Bump!!

**Comment by mburke5678** [comment]
@mdshuai PTAL so I can close this issue.

**Comment by wzheng1** [comment]
@mburke5678 LGTM, thanks!

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by mburke5678** [comment]
[rev_history]
|xref:../getting_started/beyond_the_basics.adoc#getting-started-beyond-the-basics[Beyond the Basics]
|Changed the environment variable command to include service name instead of service IP address in the xref:../getting_started/beyond_the_basics.adoc#btb-setting-environment-variables[Setting Environment Variables] section.
%

**Pull request merged**
