### PR TITLE
OBSDOCS-876: Fix a table-rendering bug

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.12, 4.13, 4.14, 4.15

Issue:

https://issues.redhat.com/browse/OBSDOCS-876

Link to docs preview:

https://72432--ocpdocs-pr.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-configuring#distr-tracing-config-jaeger-collector_distr-tracing-jaeger-configuring

Current state, before this fix:
image

After this fix:
image

QE review:
- N/A, rendering bug

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done
/lgtm

**Review by sheriff-rh — APPROVED** [review]
LGTM, merging.

**Pull request merged**
