### PR TITLE
OLS-1190: Update official attribute for OLS doc

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Affects:
[lightspeed-main](https://github.com/openshift/openshift-docs/tree/lightspeed-docs-main)
[lightspeed-docs-1.0tp1](https://github.com/openshift/openshift-docs/tree/lightspeed-docs-1.0tp1)

This PR is part of the standalone doc set for the Lightspeed project. Kathryn is aware that this content applies for a product that is part of a Technology Preview release. The project is seeking feedback from early adopters.

PR must be CP'd back to the tp1 branch.

Version(s): Tech Preview

Issue:
https://issues.redhat.com/browse/OLS-1190

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by JoaoFula** [comment]
LGTM

**Comment by kcarmichael08** [comment]
LGTM! I'm not familiar with this repo so I assume that you searched and got all of the instances of `ols-offical` in the repo. I am also assuming it's a different attributes file than the OCP repo so it won't affect anything there.

**Comment by rh-tokeefe** [comment]
Hi @kcarmichael08! You are correct on both accounts.  

I searched to find all the instances. 

This is a standalone doc set, and it uses a different attributes file than the file that the core OCP docs uses. In fact, the file resides on a different branch. I know working on the standalone branches is a little different, and I'm happy to chat sometime if you'd like. 

If this looks good, I'd like to get it merged during normal working hours. Do you have merge rights?

**Comment by kcarmichael08** [comment]
> Hi @kcarmichael08! You are correct on both accounts.
> 
> I searched to find all the instances.
> 
> This is a standalone doc set, and it uses a different attributes file than the file that the core OCP docs uses. In fact, the file resides on a different branch. I know working on the standalone branches is a little different, and I'm happy to chat sometime if you'd like.
> 
> If this looks good, I'd like to get it merged during normal working hours. Do you have merge rights?

Sure, I'll go ahead and do the merge review and merge now. Thanks for the explanation!

**Pull request merged**
