### PR TITLE
[No Jira]: Adding registered symbol attributes for IBM Power and IBM Z

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): N/A

Issue: None

Link to docs preview: N/A

QE review: N/A...I think. Reviewers, let me know if someone from QE needs to review this. 

Additional information: According to the Supplementary Style Guide, on first use, both "IBM Power"[1] and "IBM Z"[2] must include the registered trademark symbol. This PR adds attributes for those product names that include the registered symbols so that writers can comply with the guidelines without hard-coding the product names.

[1] https://redhat-documentation.github.io/supplementary-style-guide/#ibm-power
[2] https://redhat-documentation.github.io/supplementary-style-guide/#ibm-z

### CODE REVIEW

**Comment by lahinson** [comment]
@kalexand-rh and @SNiemann15 - When you have time, I'd appreciate your thoughts on this PR. If anything should change, let me know. Thank you!

**Comment by SNiemann15** [comment]
To make clear this is on first use I would "first use" either to the comment or change the entry to `ibmpowerProductName-first` 
(same for IBM Z) 
Similar to` :op-system-first: Red Hat Enterprise Linux CoreOS (RHCOS)`

Also is there a difference in using (R) or the ascii code &#174; ? I would stay with one or the other.

**Comment by lahinson** [comment]
@SNiemann15 I updated the comments to specify that the entries are for first use only. 

Good question about `(R)` versus `&#174;`. As far as I see from the [asciidoc website](https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/), both of those are valid. I'm not sure if OCP docs prefers one or another, as I found both already being used in the attributes file. I asked about it in the team-ocp-docs channel on Slack, and `(R)` was the unanimous choice, so that's what I went with. I left one instance of `&#174;` in the file because someone else added it.

**Comment by lahinson** [comment]
Hi @SNiemann15 - If the latest changes in this PR look okay to you, let me know, and I'll move this forward to be merged. Thanks!

**Comment by SNiemann15** [comment]
@lahinson Sorry I missed this yes looks good.

**Comment by lahinson** [comment]
Closing this PR, as the changes are being covered in a separate PR: https://github.com/openshift/openshift-docs/pull/67323

**Pull request closed without merging**
