### PR TITLE
OSDOCS-5112: Add release note for ConnectX-6 Dx HWOL

### PR DESCRIPTION
**Pull request by jboxman-rh**
Version(s): 4.13

Issue:

Link to docs preview:

- https://56683--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-networking-supported-hardware-for-ovs

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by jboxman-rh** [comment]
cc @wizhaoredhat @bn222

thanks

**Pull request merged**
