### PR TITLE
Terminology style updates for security book

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Requesting reviews from @ahardin-rh and @sheriff-rh for compliance operator and file integrity docs, respectively.

**Review by sheriff-rh — APPROVED** [review]
I have reviewed the Compliance section - looks great! Thanks for all your other little corrections in syntax and formatting along the way :) 🎉

**Comment by ahardin-rh** [comment]
File Integrity Operator content updates LGTM! :rocket:

**Comment by bergerhoffer** [comment]
Merging for 4.6+ only, since these operator docs are only available in 4.6+.

**Pull request merged**
