### PR TITLE
Update versions for OCP support

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to `rhacs-docs`
- Cherry pick to `rhacs-docs-4.0`

[Issue](https://issues.redhat.com/browse/ROX-15357)

Link to docs preview:

- https://58797--docspreview.netlify.app/openshift-acs/latest/configuration/enable-offline-mode.html
- https://58797--docspreview.netlify.app/openshift-acs/latest/installing/installing_ocp/install-central-ocp.html#install-acs-operator_install-central-ocp
- https://58797--docspreview.netlify.app/openshift-acs/latest/installing/installing_ocp/install-central-ocp.html#install-central-operator_install-central-ocp
- https://58797--docspreview.netlify.app/openshift-acs/latest/installing/installing_ocp/install-secured-cluster-ocp.html#install-secured-cluster-operator_install-secured-cluster-ocp

QE review:
- [x] QE has approved this change. (*N/A* - ACS has no QE, approved by SME)

Additional information:
Also updated some OCP doc links to point to a more recent version.

### CODE REVIEW

**Review by SimonBaeumer — APPROVED** [review]

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
