### PR TITLE
Removed old release notes from 4.3+

### PR DESCRIPTION
**Pull request by abrennan89**
Serverless versions prior to 1.4.0 are not compatible on 4.3+
This PR is to remove the old release notes from these docs.

Applies for OCP 4.3 and OCP 4.4.

### CODE REVIEW

**Comment by maschmid** [comment]
QE approved

**Comment by cardil** [comment]
> QE approved

Didn't make it in time :stuck_out_tongue_closed_eyes:

**Comment by jboxman** [comment]
@abrennan89, LGTM.

**Pull request merged**
