### PR TITLE
Omitted support tier info & linked to tested intergration info

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1322352

Follow-up PR to https://github.com/openshift/openshift-docs/pull/1874

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sferich888 @adellape PTAL

**Comment by sferich888** [comment]
LGTM

**Comment by adellape** [comment]
@ahardin-rh :+1:

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../architecture/infrastructure_components/web_console.html[Infrastructure Components -> Web Console]
|Added a link to the https://access.redhat.com/articles/2176281[OpenShift and Atomic Enterprise Platform Tested Integrations] article in the link:../architecture/infrastructure_components/web_console.html#browser-requirements[Browser Requirements] section.
%

**Comment by tnguyen-rh** [comment]
Witness all the weirdness in the milestone updates.

**Pull request merged**
