### PR TITLE
search-commercial: fix endpoint typo

### PR DESCRIPTION
**Pull request by jiri-fiala**
* Fixes the search endpoint typo (comma)
* Fixes the label field name

Signed-off-by: Jiri Fiala <jfiala@redhat.com>

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@jiri-fiala ok to merge?

**Comment by jiri-fiala** [comment]
@vikram-redhat, yes, this is addressing search issues introduced with https://github.com/openshift/openshift-docs/pull/18130

**Pull request merged**
