### PR TITLE
Fix typo in descheduler introduction

### PR DESCRIPTION
**Pull request by jboxman**
Fixes issue reported in https://github.com/openshift/openshift-docs/issues/13684

### CODE REVIEW

**Comment by jboxman** [comment]
@openshift/team-documentation, typo.

**Comment by ahardin-rh** [comment]
LGTM! :+1:

**Comment by mburke5678** [comment]
FYI: Fixed in 4.0 docs. https://github.com/openshift/openshift-docs/pull/13645/commits/5095badf0479040699ececb96ca3a5b8e1dd7bd6

**Pull request merged**
