### PR TITLE
Moves a networking entry to notable technical change and adds a heading

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.16 only

Issue:
No issue raised

Link to docs preview:
https://75040--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-notable-technical-changes

QE not needed. Migration only

### CODE REVIEW

**Review by jneczypor — COMMENTED** [review]
lgtm. @michaelryanpeter will follow up with a final review since I am currently onboarding to Peer Review. Thank you for your patience!

**Comment by michaelryanpeter** [comment]
LGTM.

**Pull request merged**
