### PR TITLE
OSDOCS-4300: Adding release notes for installing plugins with Krew

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4300

Link to docs preview:
https://53375--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-cli-krew

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra @deejross Here is the release notes, can you please review?

Preview: https://53375--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-cli-krew

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Pull request merged**
