### PR TITLE
feat: accept command-line args

### PR DESCRIPTION
**Pull request by mikemckiernan**
Proposed change in usage. Rather than run interactively,
accept module names as command line arguments, such
as the following examples:

```bash
./scripts/list_assemblies_used_by_modules.sh modules/nw-sriov-runtime-config.adoc modules/nw-sriov-topology-manager.adoc
```
Or, run from any location:

```bash
cd /tmp
/var/tmp/mike/openshift-docs/scripts/list_assemblies_used_by_modules.sh nw-sriov-runtime-config.adoc nw-sriov-topology-manager.adoc
```

The script performs some limited error checking on
the arguments to confirm files in the `modules`
directory for the repository exist.

```bash
/var/tmp/mike/openshift-docs/scripts/list_assemblies_used_by_modules.sh foo.adoc nw-sriov-runtime-config.adoc
Failed to find the specified file in the modules directory: foo.adoc
```

### CODE REVIEW

**Comment by mikemckiernan** [comment]
/assign @pneedle-rh 

Hi Paul, when you have the time, please consider a change to the API.  Apologies for fiddling with one of your functions.

**Comment by pneedle-rh** [comment]
@mikemckiernan thank you for the contribution, this is great! Would you be willing to also add a `--help` menu as a command option? I think it makes sense to have one if we are going to add command line arguments to the script. If you do add a menu, could you please also default to the menu output in the event of an error, for example if "Failed to determine the top-level directory for the repository" in the `infer_repo_dir` function? Thank you!

**Comment by mikemckiernan** [comment]
> @mikemckiernan thank you for the contribution, this is great!
> 
> Would you be willing to also add a `--help` menu as a command option? I think it makes sense to have one if we are going to add command line arguments to the script. If you do add a menu, could you please also default to the menu output in the event of an error, for example if "Failed to determine the top-level directory for the repository" is invoked in the `infer_repo_dir` function?
> 
> Thank you!

Let me noodle on that for a bit. Thanks for the review and the consideration.

**Comment by mikemckiernan** [comment]
Hi Paul, let me bail on this.  I started this several weeks before the team agreed to automate updating the "module-used-by" information.

Apologies for burning your time with the review, though I appreciate it all the same.

**Pull request closed without merging**
