### PR TITLE
[OSSM-8237] Update older SMCP release notes to contain operator version info

### PR DESCRIPTION
**Pull request by mkralik3**
Version(s): 4.14+

Note: Created 2 PRs to avoid merge conflicts since the release notes were restructured in 4.14+. This PR aims to make changes to 4.14+

Issue: https://issues.redhat.com/browse/OSSM-8237

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

With the latest 2.6.2 release, [we included operator version](https://github.com/openshift/openshift-docs/pull/82442) info in release notes to make it more understandable what version of SMCP is in which Operator version (see linked JIRA ticket). This PR backports this information into the previous versions.
Table of versions:

| Operator Version|SMCP X.Y | SMCP X.Y-1 | SMCP X.Y-2 |
| ------------- | ------------- |------------- |------------- |
| 2.6.2 | 2.6.2 | 2.5.5 | 2.4.11 |
| 2.6.1 | 2.6.1 | 2.5.4 | 2.4.10 |
| 2.6.0 | 2.6.0 | 2.5.3 | 2.4.9 |
| 2.5.2 | 2.5.2 | 2.4.8 | 2.3.12 |
| 2.5.1 | 2.5.1 | 2.4.7 | 2.3.11 |
| 2.5.0 | 2.5.0 | 2.4.6 | 2.3.10 |
| 2.4.5 | 2.4.5 | 2.3.9 | 2.2.12 |

### CODE REVIEW

**Review by unsortedhashsets — APPROVED** [review]
LGTM

**Review by mayleighnmyers — APPROVED** [review]
/LGTM

**Pull request merged**
