### PR TITLE
OCPBUGS#11212: adjusted YAML (ssh key format)

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-11212

Link to docs preview:
https://73249--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/installing-with-agent-based-installer#installing-ocp-agent_installing-with-agent-based-installer

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by adellape** [comment]
Oops sorry for the noise, just realized this was only meant for "4.12" and not "4.12+". 😅 Thankfully they all failed anyway, so 🤷

**Pull request merged**
