### PR TITLE
[GH#33838]: Correct typo in security-compliance-operator module

### LINKED ISSUE #33738: [enterprise-4.6] Issue in file security/compliance_operator/compliance-operator-remediation.adoc
### Which section(s) is the issue in?
Filters for failed compliance check results --> typo in command

### What needs fixing?

The 1st command at "List all failing checks that can be remediated automatically:"  has a typo

It says: 
`$ oc get compliancecheckresults -l 'compliance.openshift.io/check-status=FAIL,compliance.openshift.io/automated-remmediation'`

But it should be 
`$ oc get compliancecheckresults -l 'compliance.openshift.io/check-status=FAIL,compliance.openshift.io/automated-remediation'`

(without double 'm' in "remediation")

### PR DESCRIPTION
**Pull request by tmalove**
Preview link: https://deploy-preview-35529--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation
Fix applies to 4.6 and later versions. 
Fixes #33738.

### CODE REVIEW

**Comment by maxwelldb** [comment]
TODO as an onboarding buddy rather than peer reviewer: practice git commit --amend on this PR.

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Comment by tmalove** [comment]
@pdhamdhe  - Please provide QE review for the typo fix in this bug. Thank you!

**Comment by pdhamdhe** [comment]
@tmalove Hi, the change looks good to me. Thanks 
/lgtm
```
$ oc get compliancecheckresults -l 'compliance.openshift.io/check-status=FAIL,compliance.openshift.io/automated-remediation' |head
NAME                                                                                                STATUS   SEVERITY
ocp4-moderate-api-server-encryption-provider-cipher                                                 FAIL     medium
ocp4-moderate-api-server-encryption-provider-config                                                 FAIL     medium
ocp4-moderate-audit-error-alert-exists                                                              FAIL     high
ocp4-moderate-oauth-or-oauthclient-inactivity-timeout                                               FAIL     medium
ocp4-moderate-oauth-or-oauthclient-token-maxage                                                     FAIL     medium
rhcos4-moderate-master-audit-rules-dac-modification-chmod                                           FAIL     medium
rhcos4-moderate-master-audit-rules-dac-modification-chown                                           FAIL     medium
rhcos4-moderate-master-audit-rules-dac-modification-fchmod                                          FAIL     medium
rhcos4-moderate-master-audit-rules-dac-modification-fchmodat                                        FAIL     medium

$ oc get compliancecheckresults ocp4-moderate-api-server-encryption-provider-cipher --show-labels
NAME                                                  STATUS   SEVERITY   LABELS
ocp4-moderate-api-server-encryption-provider-cipher   FAIL     medium     **compliance.openshift.io/automated-remediation=**,compliance.openshift.io/check-severity=medium,compliance.openshift.io/check-status=FAIL,compliance.openshift.io/scan-name=ocp4-moderate,compliance.openshift.io/suite=my-companys-compliance-requirements

```

**Pull request merged**
