### PR TITLE
OSDOCS-891: Updating one more output version

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by lamek** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@boczkowska Since this touches your Helm docs, can you check that updating this output version is okay from 1.16 for 4.3 to 1.17 for 4.4?

**Review by kasturinarra — COMMENTED** [review]
LGTM !!

**Comment by boczkowska** [comment]
@bergerhoffer hi, thanks! I'm not sure if the version of the sample app depends on OCP version. 
I've pinged the SMEs, once they clarify I'll give you an answer.

**Comment by boczkowska** [comment]
@bergerhoffer the answer from the engineer: "output should be same as before, since it's chart version." 
There are no plans to update the sample chart so for 4.4 the output will still be 1.6.

**Comment by bergerhoffer** [comment]
Thanks for checking @boczkowska! I'll go ahead and close out this PR then.

**Pull request closed without merging**
