### PR TITLE
OCPBUGS#8025: Fix tar command

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OCPBUGS-8025

Link to docs preview: https://56624--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli_cli-developer-commands

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mburke5678** [comment]
@xenolinux @zhouying7780 Do we need to change this one, too? [See Step 5](https://56624--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-web-console-macos-linux_cli-developer-commands).  If not, LGTM

**Comment by xenolinux** [comment]
> @xenolinux @zhouying7780 Do we need to change this one, too? [See Step 5](https://56624--docspreview.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-web-console-macos-linux_cli-developer-commands). If not, LGTM

Addressed the change

**Comment by abhatt-rh** [comment]
> /cherrypick enterprise-4.19

sorry, erroneous branch name

**Pull request merged**
