### PR TITLE
Update name change for CNS and CRS

### PR DESCRIPTION
**Pull request by ghost**
Per Marketing:

- CNS mode will now be referred to as converged mode.
- CRS mode will now be referred to as independent mode.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@SaravanaStorageNetwork and @netzzer PTAL to determine if the changes made due the name change make sense.

Cc: @vikram-redhat

**Comment by vikram-redhat** [comment]
@tmorriso-rh this is missing the rest of the changes to the scaling performance guide which didn't have the attribute: https://github.com/tmorriso-rh/openshift-docs/commit/771d7362a0b3c1ae113e1c9694d4cd9ee9ab6cf3#diff-f368171fd950e046a50929f2746793a4

**Comment by tmorriso-rh** [comment]
@vikram-redhat Yes, I still need to add those changes. What about the 3.7 and 3.9 release notes? They don't have the attribute. Do those need to be updated since the name change is for 3.10?

**Comment by SaravanaStorageNetwork** [comment]
I feel both converged and independent mode are misnomer.
Container Native Storage(CNS) conveys better meaning than converged, same  for independent mode.

**Comment by vikram-redhat** [comment]
@SaravanaStorageNetwork - Hey there. This change has come to us from the product marketing and content strategy teams of Gluster product. Can you please take up the issue of naming with them and just provide us the QE review?

**Comment by anjsupsri** [comment]
@SaravanaStorageNetwork, I agree with Vikram. The new rebranded terms for the deployment modes are as follows:
• CNS mode will now be referred to as 'converged mode’
• CRS mode will now be referred to as ‘independent mode'

**Comment by vikram-redhat** [comment]
@tmorriso-rh I have got the ack on this from both Anjana and Ken. Please go ahead and merge and CP.

**Pull request merged**
