### PR TITLE
cnv: Restructure and improve cluster preparations

### PR DESCRIPTION
**Pull request by fabiand**
This is a small update to the cluster preparation section related to CNV

It does two things:

1. Move some sections around
2. Add some more details to 3 of them

### CODE REVIEW

**Comment by fabiand** [comment]
@ousleyp @ctomasko FYI can you help with this?

**Comment by fabiand** [comment]
@bgaydosrh

**Comment by bgaydosrh** [comment]
@fabiand - I can take this on. We are finishing 4.10 but this should be an easier fix for later in the week.

**Comment by bgaydosrh** [comment]
Hi @fabiand - yes, a rebase is going to be needed. We made a lot of major attribute changes in the doc set that required all our branches to be rebased recently. That should be completed today.

I will create my own PR and notify you when you can close this one.

**Comment by apinnick** [comment]
Closing this PR because it has been superseded by https://github.com/openshift/openshift-docs/pull/44140

**Pull request closed without merging**
