### PR TITLE
RHDEVDOCS-3833 - Remove IMPORTANT admonition from various topics

### PR DESCRIPTION
**Pull request by bburt-rh**
**Summary**: This PR removes and outdated IMPORTANT admonitions from various monitoring-related topics.

- Aligned team: DevTools
- For branches: 4.8+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3833
- Direct link to doc previews: 
- - https://deploy-preview-43853--osdocs.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack.html#configuring-persistent-storage
- - https://deploy-preview-43853--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-within-minor.html#prerequisites
- - https://deploy-preview-43853--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-rhel-compute.html#prerequisites
- - https://deploy-preview-43853--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-restricted-network-cluster.html#prerequisites
- SME review: N/A
- QE review: @juzhao (approved)
- Peer review: @rolfedh (approved)
- <All reviews complete. Please merge now>

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]
/lgtm

**Comment by juzhao** [comment]
there is not updating/updating-cluster.adoc in OCP doc,
we only have
https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-within-minor.html
https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-cli.html

others are lgtm

**Comment by bburt-rh** [comment]
> there is not updating/updating-cluster.adoc in OCP official site, we only have https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-within-minor.html https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-cli.html
> 
> others are lgtm

Thanks @juzhao. @rolfedh and I investigated, and updating/updating-cluster.adoc seems to be an orphaned file in the repo that doesn't appear anywhere in the published docs for OCP 4.8+. We are leaving it there for now while we investigate further. If necessary, we'll remove the file in a separate PR.

**Pull request merged**
