### PR TITLE
OCPBUGS#13688: Default pids-limit and log-max-size update

### PR DESCRIPTION
**Pull request by mrVectorz**
Version(s):
4.12+

Issue:
[
](https://issues.redhat.com/browse/OCPBUGS-13688)

Link to docs preview:
[](https://github.com/mrVectorz/openshift-docs/blob/main/modules/create-a-containerruntimeconfig-crd.adoc)

### CODE REVIEW

**Comment by mrVectorz** [comment]
@sunilcio waiting on your review

**Comment by kalexand-rh** [comment]
@mrVectorz, please rebase your PR so we can get it merged. Thanks!

**Comment by kalexand-rh** [comment]
@mrVectorz, you still need to squash your commits before we can merge this.

**Pull request closed without merging**
