### PR TITLE
Make gluster endpoints and service the same name

### PR DESCRIPTION
**Pull request by eparis**
This prevents the endpoints from being automatically deleted

### CODE REVIEW

**Comment by humblec** [comment]
LGTM. Thanks!

**Comment by nak3** [comment]
May I ask you to modify the notes in the line:

> <1> The name of the endpoints is used in the PV definition below.

and

> <1> The name of the service.

to like "This name must match the {service,endpoints}". [This section](https://docs.openshift.com/container-platform/3.3/install_config/persistent_storage/persistent_storage_glusterfs.html#creating-gluster-endpoints) has the notes and it was really helpful.

**Comment by ahardin-rh** [comment]
Thanks!

@nak3 I will follow up with that edit, as well as some other edits, in a separate PR while I continue to address https://bugzilla.redhat.com/show_bug.cgi?id=1408293

**Comment by ahardin-rh** [comment]
These changes were applied to 3.3 and 3.4 via:
https://github.com/openshift/openshift-docs/pull/3545
https://github.com/openshift/openshift-docs/pull/3546

**Pull request merged**
