### PR TITLE
OSDOCS-3261: Fix title for ocp4-nerc-cip-node in the Supported Profiles table

### PR DESCRIPTION
**Pull request by kmccarron-rh**
https://issues.redhat.com/browse/OSDOCS-3261

Applies to 4.6+

https://deploy-preview-41593--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-supported-profiles.html

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
LGTM

**Comment by kmccarron-rh** [comment]
@pdhamdhe - Will you PTAL? Thanks!

**Comment by pdhamdhe** [comment]
LGTM

**Pull request merged**
