### PR TITLE
ocpbugs25624: correcting RHACM product name

### PR DESCRIPTION
**Pull request by DCChadwick**
Version(s): 4.11+

Issue: OCPBUGS-25624

Link to docs preview: https://75413--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#infrastructure-components_creating-infrastructure-machinesets

QE review:
- NA

Additional information: Changing the RHACM name to match the official product name as found here: https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1259317633

### CODE REVIEW

**Comment by DCChadwick** [comment]
@sunilcio This PR is ready for QE review

**Comment by kalexand-rh** [comment]
After one of the ACM writers confirms that this is correct, normal peer/merge review is sufficient.

**Comment by DCChadwick** [comment]
PR: [76613](https://github.com/openshift/openshift-docs/pull/76613)

**Review by swopebe — APPROVED** [review]

**Pull request merged**
