### PR TITLE
Warning for Azure Windows machine set name length restriction

### LINKED ISSUE #28774: [enterprise-4.6] Issue in file windows_containers/creating_windows_machinesets/creating-windows-machineset-azure.adoc
### Which section(s) is the issue in?

Azure Machine Set

### What needs fixing?

The MachineSet example produces an error
```
  Warning  FailedCreate  2m3s (x2 over 2m8s)  azure-controller  InvalidConfiguration: failed to reconcile machine "wrxp2-windows-worker-centralus1-8vx4c": failed to create vm wrxp2-windows-worker-centralus1-8vx4c: failure sending request for machine wrxp2-windows-worker-centralus1-8vx4c: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Windows computer name cannot be more than 15 characters long, be entirely numeric, or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \\ | ; : . ' \" , < > / ?." Target="computerName
```

We should note something like it says in the Github doc https://github.com/openshift/windows-machine-config-operator/blob/master/docs/machineset-azure.md

```
Please note that on Azure, Windows Machine names cannot be more than 15 characters long. The MachineSet name can therefore not be more than 9 characters long, due to the way Machine names are generated from it.
```

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #28774

### CODE REVIEW

**Comment by codyhoag** [comment]
@sgaoshang can you verify? Thanks!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
