### PR TITLE
OSDOCS#11960: Migrating destroying hosted clusters

### PR DESCRIPTION
**Pull request by xenolinux**
This PR is a part of HCP content migration and modularization. This content is only being moved from RHACM to OCP and not changed. This content has been SME and peer reviewed. This migration PR contains the QE approval

Version(s): 4.17 and main

Issue: https://issues.redhat.com/browse/OSDOCS-11960

Link to docs preview:

- https://81663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-destroy/hcp-destroy-ibmz.html
- https://81663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-destroy/hcp-destroy-non-bm.html
-  https://81663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-destroy/hcp-destroy-bm.html
-  https://81663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-destroy/hcp-destroy-aws.html
-  https://81663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-destroy/hcp-destroy-virt.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by agantony — COMMENTED** [review]
Added a few suggestions for your consideration; overall lgtm!

**Comment by xenolinux** [comment]
@agantony I appreciate your suggestions. I addressed them.

**Pull request merged**
