### PR TITLE
OCPBUGS-3856: Fix typo: <rout_name> → <route_name>

### PR DESCRIPTION
**Pull request by Miciah**
* `modules/nw-disabling-hsts.adoc`:
* `modules/nw-enabling-hsts-per-route.adoc`: Replace "<rout_name>" with "<route_name>".

-------

Version(s):
4.9+

Issue:

https://issues.redhat.com/browse/OCPBUGS-3856

Link to docs preview:

https://52971--docspreview.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-enabling-hsts-per-route_route-configuration

https://52971--docspreview.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration.html#nw-disabling-hsts_route-configuration

QE review:
- Since this is just a typo fix, QE is not necessary as the typo doesn't change the meaning or intent of the documentation.

Additional information:

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM. 
@quarterpin PTAL. Thanks!

**Comment by kalexand-rh** [comment]
@quarterpin PTAL?

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by skrthomas** [comment]
I do not think this PR needs QE since its a tiny typo fix that does not impact the doc in a meaningful way, other than fix the incorrect typo :) Peer review LGTM. OK to merge post merge freeze since this is 4.9+, and impacts 4.12 and 4.13.

**Pull request merged**
