### PR TITLE
OSDOCS-12215 Removing unsupported RODOO versions from 4.17 branch

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.17

Issue: [OSDOCS-12215](https://issues.redhat.com/browse/OSDOCS-12215)

Link to docs preview:

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ingvagabund** [comment]
LGTM

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
