### PR TITLE
OSDOCS-2395: Add release note for DPDK GA

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-2395

This adds a RN for DPDK GA and updates the TP table.

Previews:
- https://deploy-preview-35643--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes#ocp-4-9-sriov-dpdk-ga
- https://deploy-preview-35643--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes#ocp-4-9-technology-preview

### CODE REVIEW

**Comment by jboxman** [comment]
@EinatGlottmann, what does _containerized Data Plane Development Kit (DPDK) application_ mean exactly? Is that the application that provides DPDK? Or does a user create an application that uses DPDK? I'm relatively new to DPDK. Thanks!

**Comment by EinatGlottmann** [comment]
DPDK is a software development kit that provide libraries that improve performance of NICs
https://source.redhat.com/groups/public/gssnfv/cee_network_functions_virtualization_landing_page_wiki/dpdk
(I am relatively new to it myself)

**Comment by jboxman** [comment]
@zshi-redhat @SchSeba

This adds a release note entry for GA.

**Comment by zshi-redhat** [comment]
> @zshi-redhat @SchSeba
> 
> This adds a release note entry for GA.

The change looks good to me.
@SchSeba have we finished TE?

**Comment by sagidlow** [comment]
LGTM, just need to squash your commits :)

**Comment by jboxman** [comment]
@sagidlow, thanks!

**Pull request merged**
