### PR TITLE
CNV-24330: metrics change for 4.12.1

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): Hold until 4.12.1 releases. When merging, CP to 4.12+ 

Issue: [CNV-24330](https://issues.redhat.com//browse/CNV-24330)

Link to docs preview: https://54734--docspreview.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-prometheus-queries.html#virt-live-migration-metrics_virt-prometheus-queries

QE review:
- [x] QE has approved this change.

Additional information: @dshchedr please review when you can. Thanks!

### CODE REVIEW

**Comment by dshchedr** [comment]
LGTM

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by apinnick** [comment]
@ousleyp  This can be merged and CPed. I confirmed that 4.12.1 is GA today.

**Pull request merged**
