### PR TITLE
[OSDOCS-3360] HIPAA should not be included in compliance table

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
This PR removes HIPAA from the compliance table on OSD and ROSA until remaining legal issues are resolved. 

JIRA: https://issues.redhat.com/browse/OSDOCS-3360

PREVIEWS:
- **OSD:** https://deploy-preview-43102--osdocs.netlify.app/openshift-dedicated/latest/osd_policy/policy-process-security.html#compliance_policy-process-security
- **ROSA:** https://deploy-preview-43102--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-policy-process-security.html#rosa-policy-compliance_rosa-policy-process-security

### CODE REVIEW

**Comment by ctauchen** [comment]
Peer review -- LGTM

**Comment by ctauchen** [comment]
@michaelryanmcneill Which versions does this apply to?

**Comment by michaelryanmcneill** [comment]
@ctauchen it should apply to 4.10 and 4.11!

**Comment by ctauchen** [comment]
@michaelryanmcneill All we need now is a QE review. Do you have a QE contact for this area? I can merge once I get an ack in this PR.

**Comment by michaelryanmcneill** [comment]
Per @nermina-redhat: @yufchang and @xueli181114 are our QE contacts

**Comment by yuwang-RH** [comment]
LGTM.

**Comment by michaelryanmcneill** [comment]
@nermina-redhat can we possibly get this merged ASAP? This is an important clarification.

**Pull request merged**
