### PR TITLE
OSDOCS-7359: aggregate relevant information

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-7359

Link to docs preview: https://80182--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/configuring-ipfailover.html#nw-ipfailover-cluster-ha-ingress_configuring-ipfailover

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by melvinjoseph86** [comment]
Hi @jldohmann i am fine with the changes. but i can see there is some no page found issue in the link doc of `[Configuration for ExternalIP](https://github.com/openshift/openshift-docs/blob/fd879eee91e7501fc8ec4702a963b48187b09c1d/networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc#configuration-externalip_configuring-externalip)`

the below 3 Prerequisites files are giving 'page not found' error even in the main branch.
```
[modules/nw-externalip-about.adoc](https://github.com/openshift/openshift-docs/blob/fd879eee91e7501fc8ec4702a963b48187b09c1d/networking/configuring_ingress_cluster_traffic/modules/nw-externalip-about.adoc)

[modules/nw-externalip-object.adoc](https://github.com/openshift/openshift-docs/blob/fd879eee91e7501fc8ec4702a963b48187b09c1d/networking/configuring_ingress_cluster_traffic/modules/nw-externalip-object.adoc)

[modules/nw-externalip-configuring.adoc](https://github.com/openshift/openshift-docs/blob/fd879eee91e7501fc8ec4702a963b48187b09c1d/networking/configuring_ingress_cluster_traffic/modules/nw-externalip-configuring.adoc)
```

**Comment by jldohmann** [comment]
thanks @melvinjoseph86 ! that happens for modules for some reason when attempting to view them through their associated `include` statements in github, but their sections are included in the assembly at build time: https://docs.openshift.com/container-platform/4.16/networking/configuring_ingress_cluster_traffic/configuring-externalip.html

**Pull request merged**
