### PR TITLE
Expand explanation of SCTP capabilities

### PR DESCRIPTION
**Pull request by jboxman**
Explain a use case for SCTP.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@jboxman what is this waiting on?

**Comment by jboxman** [comment]
@vikram-redhat, Monday morning probably; it's a not entirely satisfying attempt at specifying a coherent use case. But it may be off the mark. I haven't finished my next attempt yet. And someone that knows better will then need to call my buff.

It's not urgent for 4.4, it's just a little extra.

I can change the label or push :delete it or whatever until it's complete, if necessary.

**Comment by vikram-redhat** [comment]
@jboxman that's ok if it can come post 4.4. I wanted to close up all 4.4 necessary work for l10n.

**Comment by jboxman** [comment]
Hi @danwinship, I felt the urge to expand upon the description. Is what I wrote technically sound?

Thanks!

**Comment by danwinship** [comment]
The use case for SCTP is "my OpenShift cluster needs to interoperate with my other systems which are already using SCTP". If the customer is not already using SCTP outside of OpenShift, there is no reason for them to use it inside OpenShift. None of the nominal benefits of SCTP over TCP are relevant at this point because SCTP is a dead and abandoned protocol that nobody supports (except in telecom where they're stuck with it for compatibility reasons). (Also, things like multihoming wouldn't work inside an OpenShift cluster anyway.) We should be actively discouraging customers from using SCTP. Every time a RHEL customer enables SCTP, God kills a kitten. Think of the kittens. :joy_cat:

**Comment by jboxman** [comment]
@danwinship, I'll close this PR, then. Thanks!

**Pull request closed without merging**
