### PR TITLE
BZ 1898042: disclaimers about VMs getting OOM killed

### PR DESCRIPTION
**Pull request by ousleyp**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1898042
Preview build: https://oomkill-warning--ocpdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/advanced_vm_management/virt-managing-guest-memory.html

Adding more explicit warnings about the risks of two advanced memory management procedures. Also unwrapped a few lines.

4.6, 4.7 (and maybe 4.5)

@fabiand, can you please review? Thanks!

### CODE REVIEW

**Review by fabiand — COMMENTED** [review]
/lgtm

Thanks looks great!

**Review by fabiand — APPROVED** [review]

**Review by sjhala-ccs — COMMENTED** [review]
LGTM! I'll leave the decision to unwrap the other hard-wrapped lines that are not part of this PR up to you.

**Pull request merged**
