### PR TITLE
add references to external s2i docs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
before this merges i need to double check that this blog is still accurate:
https://blog.openshift.com/create-s2i-builder-image/

**Comment by bparees** [comment]
blog has been validated/updated.  @openshift/team-documentation ptal/merge.

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by adellape** [comment]
:+1:

**Comment by adellape** [comment]
[rev_history]
|link:../creating_images/s2i.html[S2I Requirements]
|Added an link:../creating_images/s2i.html#external-references[External References] section with links to an image creation tutorial and the S2I project repository.
%

**Pull request merged**
