### PR TITLE
BZ2068397 Manualling copying changes from PR 55480 to 4.9

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.9 only

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2068397

Link to docs preview:
http://file.pnq.redhat.com/agantony/manual-cp-55373-to-4.9/machine_management/creating_machinesets/creating-machineset-aws.html#machineset-yaml-aws_creating-machineset-aws

QE review:
- [ ] QE has approved this change.

Additional information:
- Original PR: https://github.com/openshift/openshift-docs/pull/55373
- Merge into `enterprise-4.9`
- Cherry-picked commit from 4.8: https://github.com/openshift/openshift-docs/pull/55480/commits

### CODE REVIEW

**Comment by agantony** [comment]
QE review needed: @lyman9966

**Review by jeana-redhat — APPROVED** [review]
LGTM, thanks!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
