### PR TITLE
OSSMDOC-376: Fixing YAML indentation in Gateway file.

### PR DESCRIPTION
**Pull request by JStickler**
Fixing YAML indentation.

Preview is here -> https://deploy-preview-36235--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-traffic-manage.html#ossm-routing-gw_routing-traffic

QE review - yxun
Peer review

### CODE REVIEW

**Comment by JStickler** [comment]
@yxun

**Review by yxun — APPROVED** [review]

**Comment by sagidlow** [comment]
LGTM.

**Pull request merged**
