### PR TITLE
CNV-14946: Reversing redirect to allow CNV content to go live on GA

### PR DESCRIPTION
**Pull request by sjhala-ccs**
[CNV-14946](https://issues.redhat.com/browse/CNV-14946)

To be merged at CNV 4.10 GA (after merging placeholder reversal https://github.com/openshift/openshift-docs/pull/42596)

No CP

### CODE REVIEW

**Comment by sjhala-ccs** [comment]
@pneedle-rh Can you please review? This is basically commenting out (reversing) the redirect rule for CNV docs. CNV 4.10 is scheduled to release tomorrow (March 16). I will merge this PR after errata advisories are shipped. Thank you.

**Comment by pneedle-rh** [comment]
LGTM

**Pull request merged**
