### PR TITLE
OSDOCS-3613: Add STS snippet

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.10, 4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3613

Link to docs preview:
https://deploy-preview-45424--osdocs.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-understanding.html#rosa-understanding-credential-modes_rosa-understanding

Additional information:
No QE review required

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
Otherwise, LGTM!

**Comment by arendej** [comment]
Need to shift this one:
image

**Review by arendej — CHANGES_REQUESTED** [review]
see my comments

**Comment by bmcelvee** [comment]
Thanks, @arendej! Updates are in place.

**Pull request merged**
