### PR TITLE
Separating command and output for Monitoring book

### PR DESCRIPTION
**Pull request by pneedle-rh**
Applies to branch/enterprise-4.5.

My view is that we should not cherry pick this PR for branch/enterprise-4.6, because I have been working on a separate feature branch locally to extensively restructure the Monitoring book for 4.6. I will separate command and output code blocks and will include `[source,terminal]` for branch/enterprise-4.6, as part of the restructuring PR, to avoid merge conflicts.

### CODE REVIEW

**Comment by pneedle-rh** [comment]
@openshift/team-documentation for peer review please.

**Review by codyhoag — APPROVED** [review]
Changes LGTM! Separate comment below

**Comment by codyhoag** [comment]
@pneedle-rh Perhaps you should only merge this change for `enterprise-4.5`? And come back with a follow-up for `master` and `enterprise-4.6`? I think the latter two should be mostly identical, but I could be wrong.

**Comment by pneedle-rh** [comment]
Closing this PR and will submit a new one based on enterprise-4.5. Switching base branches within this PR has not worked. I will reference the new PR in a further comment here, once I have created it.

**Comment by pneedle-rh** [comment]
I have now created new PR https://github.com/openshift/openshift-docs/pull/24526 against base: enterprise-4.5.

**Pull request closed without merging**
