### PR TITLE
GitHub-39602: Putting command all on one line

### PR DESCRIPTION
**Pull request by bergerhoffer**
To address #39602

Preview: https://deploy-preview-39966--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing#ldap-auto-syncing_ldap-syncing-groups

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh @zhouying7780 Can you please review?

Preview: https://deploy-preview-39966--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing#ldap-auto-syncing_ldap-syncing-groups

**Comment by sagidlow** [comment]
lgtm!

**Comment by zeten30** [comment]
Perfect, thank you.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
