### PR TITLE
Bug 1803186, updated defaults based on 4.3 scale tests

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1803186

@chaitanyaenr PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@weinliu PTAL. Thank you!

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by weinliu** [comment]
The update LGTM, thanks.

**Pull request merged**
