### PR TITLE
OCPBUGS-35488_418#updating installation doc

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version:
4.18

Issue:
https://issues.redhat.com/browse/OCPBUGS-35488

Link to docs preview:

**AWS**
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-network-customizations#installation-aws-tested-machine-types_installing-aws-network-customizations 
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-network-customizations#installation-aws-arm-tested-machine-types_installing-aws-network-customizations

**Azure**
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/ipi/installing-azure-customizations#installation-azure-tested-machine-types_installing-azure-customizations
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/ipi/installing-azure-customizations#installation-azure-arm-tested-machine-types_installing-azure-customizations 

**GCP**
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types_installing-gcp-customizations
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-tested-machine-types-arm_installing-gcp-customizations

**IBM Cloud** 
- https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud/installing-ibm-cloud-customizations#installation-ibm-cloud-tested-machine-types_installing-ibm-cloud-customizations 

QE review:

- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@MayXuQQ, PTAL at the IBM Cloud update.

**Comment by brendan-daly-red-hat** [comment]
@yunjiang29, PTAL at the AWS update.

**Comment by brendan-daly-red-hat** [comment]
@jianli-wei, PTAL at the GCP update.

**Comment by MayXuQQ** [comment]
@brendan-daly-red-hat , how about just list the tested type in https://84228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud/installing-ibm-cloud-customizations#installation-ibm-cloud-tested-machine-types_installing-ibm-cloud-customizations ?

**Comment by jinyunma** [comment]
LGTM for azure part

**Comment by MayXuQQ** [comment]
lgtm for IBMCloud

**Review by maxwelldb — APPROVED** [review]

**Comment by maxwelldb** [comment]
All requested QE acks in. Merging.

**Pull request merged**
