### PR TITLE
OCPBUGS#28655: Removing core API group from example

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-28655

Link to docs preview:
https://83470--ocpdocs-pr.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing.html#ldap-auto-syncing_ldap-syncing-groups

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ibihim @xingxingxia Can you please review and see if it's okay to remove the core group access from this example for LDAP group syncing?

Preview: https://83470--ocpdocs-pr.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing.html#ldap-auto-syncing_ldap-syncing-groups

**Review by kcarmichael08 — COMMENTED** [review]
LGTM!

**Pull request merged**
