### PR TITLE
[OSDOCS-5388]:Remove a section from the OSD/ROSA documentation for the Logging stack

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-5388
Link to docs preview:
Please note that because the ticket scope is based on removing a topic from ROSA docs and OSD docs (topic maps), there is no Netlify preview generated, but attached image from local build shows the topic has been removed from the topic maps. 

image
image

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @yuwang-RH , could you please review me for this (QE review)? Thanks! ML

**Review by anpingli — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@mletalie Do you have access to file.rdu.redhat.com/<user-name>/? If so, you can upload your local preview.

**Comment by mletalie** [comment]
Thanks @mburke5678, 
I had never done that before, but I think I got it to work: 
image
Hope that helps, and let me know if you need any more info in order to access the needed files. Thanks!

**Comment by mburke5678** [comment]
Current: https://docs.openshift.com/container-platform/4.12/logging/config/cluster-logging-systemd.html The _Configuring systemd-journald and Fluentd _ topic is present in the topic map

Preview: http://file.rdu.redhat.com/mburke/56318/logging/config/cluster-logging-moving-nodes.html  The _Configuring systemd-journald and Fluentd _ topic is not present in the topic map

**Comment by mletalie** [comment]
http://file.rdu.redhat.com/mletalie/OSDOCS-5388/dedicated/welcome/index.html
image
@mburke5678

**Pull request merged**
