### PR TITLE
CNV-22619: Update doc HCO variable 4.12.1

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.12

Issue: [CNV-22619](https://issues.redhat.com/browse/CNV-22619)

Link to docs preview: https://56539--docspreview.netlify.app/openshift-enterprise/latest/virt/install/virt-specifying-nodes-for-virtualization-components.html#virt-example-node-placement-node-selector-olm-subscription_virt-specifying-nodes-for-virtualization-components

QE review: N/A 

Additional information: Doc review only

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by bmcelvee** [comment]
Hi @aspauldi the change looks good to me, just have a question about the branch: would it be possible to this one to push the change to main and cherrypick to 4.12, or does it need to be made directly on 4.12? Thanks!

**Comment by aspauldi** [comment]
Hi @bmcelvee! I didn't know the answer to your question, as this is the first update to the HCO variable that I've done. I sent a message to Shikha, who said that this change applies only to 4.12 and that there is no cherry picking needed. I hope that helps!

**Comment by bmcelvee** [comment]
Thank you! Going ahead with the merge. :)

**Comment by aspauldi** [comment]
Thanks, @bmcelvee!

**Pull request merged**
