### PR TITLE
OCPBUGS-22397: clarify netobserv network policy

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.11+
Issue:

https://issues.redhat.com/browse/OCPBUGS-22397
Link to docs preview:

https://69671--docspreview.netlify.app/openshift-enterprise/latest/network_observability/network-observability-network-policy
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
I need to re-open this against `main`.

**Review by jpinsonneau — APPROVED** [review]

**Comment by skrthomas** [comment]
@memodi Can you PTAL at this small update in the network policy documentation. Steven requested this a while back and I am hoping to squeeze it in 1.5. If its not possible before 1.5, no worries. I can open this up against `main` and get it in later. I actually intended to open this against `main` initially, but I opened it against `no-1.5` and now we are nearly at 1.5 so I can just go ahead and put it in there if this looks OK.

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by skopacz1 — APPROVED** [review]
LGTM! Is the Netlify preview bot not configured to generate previews for this branch?

**Comment by skrthomas** [comment]
@skopacz1 It is not unfortunately and this PR was caught in the crosshairs of the Travis->Prow switch.

**Pull request merged**
