### PR TITLE
CNV-4971: Replace kubevirt api version with v1 version

### PR DESCRIPTION
**Pull request by lmandavi**
This PR is associated with https://issues.redhat.com/browse/CNV-4971.

### CODE REVIEW

**Comment by lmandavi** [comment]
@stu-gott - Requesting SME review. Thanks!

**Comment by lmandavi** [comment]
@davidvossel - Please review this PR.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

This looks accurate and all references to `kubevirt.io/v1alpha3` are changed. To be certain, I cross checked this PR with the usage of v1alpha3 in the openshift-docs/main branch.

**Comment by lmandavi** [comment]
Requesting QE review.

**Comment by lmandavi** [comment]
Requesting Peer Review.

**Comment by ousleyp** [comment]
LGTM!

**Comment by ousleyp** [comment]
(Confirmed with Lavanya via Slack that enterprise-4.8, 4.9, and 4.10 are the correct branches.)

**Pull request merged**
