### PR TITLE
OCPBUGS#35980_35977

### PR DESCRIPTION
**Pull request by lpettyjo**
Azure File Cloning Known Issues

Version(s): 4.16 only

Issue: https://issues.redhat.com/browse/OCPBUGS-35977
https://issues.redhat.com/browse/OCPBUGS-35980

Link to docs preview: https://77967--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-known-issues_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gcharot @RomanBednar @ropatil010

### CODE REVIEW

**Comment by RomanBednar** [comment]
LGTM

**Comment by michaelryanpeter** [comment]
LGTM
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed

**Comment by gcharot** [comment]
LGTM

**Comment by ropatil010** [comment]
LGTM
Thanks.!

**Pull request merged**
