### PR TITLE
Modifications for RHDEVDOCS-2620 and 2621

### PR DESCRIPTION
**Pull request by sounix000**
Aligned team: Dev Tools
OCP version for cherry-picking: `4.7`, `4.8`
JIRA issues: [RHDEVDOCS-2620](https://issues.redhat.com/browse/RHDEVDOCS-2620), [RHDEVDOCS-2621](https://issues.redhat.com/browse/RHDEVDOCS-2621)
Preview pages: The introductory section of [Configuring the log store](https://deploy-preview-30904--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-log-store.html)
SME and QE reviewers: Oscar Casal Sanchez

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
The commits need to be squashed and then I can merge!

**Comment by sounix000** [comment]
> The commits need to be squashed and then I can merge!

@bergerhoffer - I have squashed the commits. Please merge. Thanks!

**Comment by bergerhoffer** [comment]
Thanks @sounix000,  merging!

**Pull request merged**
