### PR TITLE
Taint and Tolerations with BuildOverride not working as expected

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1837093

### CODE REVIEW

**Comment by mburke5678** [comment]
@xltian Please assign for QE review.

**Comment by xltian** [comment]
@weinliu can your team please review from QE?

**Comment by weinliu** [comment]
@mburke5678 The updates look good for QE

**Comment by ahardin-rh** [comment]
Looks good to me!

**Pull request merged**
