### PR TITLE
[RHACS] ROX-13653: Add info about policies in CM display

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
 
- merge into `rhacs-docs-3.73.0`
- cherry pick to `rhacs-docs`
- cherry pick to `rhacs-docs-3.72`
- cherry pick to `rhacs-docs-3.71`
- cherry pick to `rhacs-docs-3.70`

Issue: [ROX-13653](https://issues.redhat.com/browse/ROX-13653)

[Link to docs preview](https://openshift-docs-gcf71vw5n-kcarmichael08.vercel.app/openshift-acs/master/operating/review-cluster-configuration.html#using-the-configuration-management-view_review-cluster-configuration)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by clickboo — APPROVED** [review]

**Review by Wiharris — COMMENTED** [review]
/LGTM

**Review by jldohmann — APPROVED** [review]
LGTM!

**Pull request merged**
