### PR TITLE
RHDEVDOCS 6328 release notes for Pipelines 1.16.2

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please also cp to `pipelines-docs-main`

The current target is necessary because this change will not be visible in `pipelines-docs-main`, only in `pipelines-docs-1.16`

Issue:

RHDEVDOCS 6328

Link to docs preview:

https://86403--ocpdocs-pr.netlify.app/openshift-pipelines/latest/release_notes/op-release-notes-1-16.html#release-notes-1-16-2_op-release-notes

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by savitaashture** [comment]
LGTM

**Review by srivickynesh — APPROVED** [review]
LGTM

**Review by skrthomas — COMMENTED** [review]
Just one small comment, lgtm otherwsie

**Review by bergerhoffer — COMMENTED** [review]
I don't understand the explanation for targeting this to 1.16 if it has to go into main too. I would think it should still originate in main and then CP to whichever versions it applies to. And that if it's going into main, that it should go into the latest version branch too, which looks to be 1.17.

However, in the interest of getting this out today, I won't hold up the merge over this. I'll merge this and CP to just piplelines-docs-main. Just note that I'll be out until January, so if you do need any further help with this between now and then, reach out to the rest of the merge squad. Thanks!

**Comment by mramendi** [comment]
> I don't understand the explanation for targeting this to 1.16 if it has to go into main too. I would think it should still originate in main and then CP to whichever versions it applies to. And that if it's going into main, that it should go into the latest version branch too, which looks to be 1.17.

Here is the situation. The 1.17 version, which is also in main, does not render the release notes for previous versions. This is a decision taken for all of the layered products: to avoid massively inflate release notes, only the RNs for a given minor version are rendered in that minor version's docs.

Therefore if we originate the PR in pipelines-docs-main, the automatically generated preview will not include the changes.

This is something that is probably worthy of a separate discussion in January.

**Comment by bergerhoffer** [comment]
> > I don't understand the explanation for targeting this to 1.16 if it has to go into main too. I would think it should still originate in main and then CP to whichever versions it applies to. And that if it's going into main, that it should go into the latest version branch too, which looks to be 1.17.
> 
> Here is the situation. The 1.17 version, which is also in main, does not render the release notes for previous versions. This is a decision taken for all of the layered products: to avoid massively inflate release notes, only the RNs for a given minor version are rendered in that minor version's docs.
> 
> Therefore if we originate the PR in pipelines-docs-main, the automatically generated preview will not include the changes.
> 
> This is something that is probably worthy of a separate discussion in January.

@mramendi Thanks for the explanation! In that case, is there a reason they're put into main at all? For the main OCP enterprise branches, our release notes only go into the respective version branch, and never into main. We just keep a stub file on main for build purposes. Something to consider if you take another look at how it is done!

**Pull request merged**
