### PR TITLE
Bug 1528521, updated active subscription screenshot

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1528521

@abhgupta @tiwillia PTAL

### CODE REVIEW

**Comment by tiwillia** [comment]
Looks great 🙆‍♂️

**Comment by ahardin-rh** [comment]
@tiwillia Updated per QE comments in the BZ. PTAL.

**Review by tiwillia — APPROVED** [review]
Looks good to me. 👨‍💼 👌

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
