### PR TITLE
[RHACS] Update Ubuntu scanning support

### PR DESCRIPTION
**Pull request by RTann**
Version(s):

* rhacs-docs
* rhacs-docs-3.70.0

Labels: _RHACS_

Issue(s):

* https://issues.redhat.com/browse/ROX-10710
* https://issues.redhat.com/browse/ROX-10743

Link to docs preview:

* [Scanning Images](https://deploy-preview-45731--osdocs.netlify.app/openshift-acs/latest/operating/examine-images-for-vulnerabilities#scanning-images_examine-images-for-vulnerabilities)

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
/LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
