### PR TITLE
[OSDOCS-3753] Remove overly specific example language

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11+

Issue:
[OSDOCS-3753](https://issues.redhat.com//browse/OSDOCS-3753)

Link to docs preview:
[Machine API overview](https://67072--docspreview.netlify.app/openshift-enterprise/latest/machine_management/#machine-api-overview_overview-of-machine-management)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@jeana-redhat @elmiko 

I know this is outside of the scope of this PR, but this sound odd to me:

> a machine type ... might define a specific machine type

If that is fine, the LGTM.

**Comment by jeana-redhat** [comment]
refresh for merge

**Pull request merged**
