### PR TITLE
OCPBUGS-31272: Removing Prometheus alert creation from 4.12, 4.13 Net…

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

Issue:

https://issues.redhat.com/browse/OCPBUGS-31272
Link to docs preview:

Removed topic Creating Loki rate limit alerts: https://74100--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/network-observability-operator-monitoring.html

Removed topic Creating alerts: https://74100--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/metrics-alerts-dashboards
QE review:
- [X] QE has approved this change.

Additional information:

related PR: https://github.com/openshift/openshift-docs/pull/74099 changes PrometheusRule to AlertingRule in 4.14+

### CODE REVIEW

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by jotak — APPROVED** [review]

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Pull request merged**
