### PR TITLE
BZ1967077: Updating the nodeSelector YAML for moving the registry

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1967077

4.6+

Preview: https://deploy-preview-34712--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@wzheng1, will you PTAL?

**Comment by wzheng1** [comment]
@xiuwang Could you please review?

**Comment by xiuwang** [comment]
After configure podAntiAffinity and nodeSelector in config.images, the image registry still have chance to schedule to same node, But IMO, it used preferredDuringSchedulingIgnoredDuringExecution policy, so we can admit this behavior

$ oc get pods -n openshift-image-registry  -o wide
NAME                                               READY   STATUS    RESTARTS   AGE     IP            NODE                                            NOMINATED NODE   READINESS GATES
cluster-image-registry-operator-679db64c8c-jh9nt   1/1     Running   0          7h39m   10.130.0.63   ip-10-0-69-165.us-gov-west-1.compute.internal   <none>           <none>
image-registry-796b78fbb-4swdf                     1/1     Running   0          43s     10.131.0.34   ip-10-0-49-91.us-gov-west-1.compute.internal    <none>           <none>
image-registry-796b78fbb-6lh29                     1/1     Running   0          44s     10.131.0.35   ip-10-0-49-91.us-gov-west-1.compute.internal    <none>           <none>
$ oc get node
NAME                                            STATUS   ROLES          AGE   VERSION
ip-10-0-48-238.us-gov-west-1.compute.internal   Ready    master         8h    v1.20.0+558d959
ip-10-0-49-91.us-gov-west-1.compute.internal    Ready    infra,worker   8h    v1.20.0+558d959
ip-10-0-61-234.us-gov-west-1.compute.internal   Ready    master         8h    v1.20.0+558d959
ip-10-0-67-5.us-gov-west-1.compute.internal     Ready    infra,worker   8h    v1.20.0+558d959
ip-10-0-69-165.us-gov-west-1.compute.internal   Ready    master         8h    v1.20.0+558d959
ip-10-0-73-238.us-gov-west-1.compute.internal   Ready    worker         8h    v1.20.0+558d959

**Comment by xiuwang** [comment]
LGTM

**Comment by mburke5678** [comment]
@kalexand-rh LGTM

**Pull request merged**
