### PR TITLE
Update the OverlayFS link to the latest RHEL doc.

### PR DESCRIPTION
**Pull request by warmchang**

### CODE REVIEW

**Comment by warmchang** [comment]
@openshift/team-documentation PTAL.

**Comment by ahardin-rh** [comment]
@warmchang LGTM. I have this labeled so that the change is applied to OCP 3.5+, as the Scaling and Performance guide was introduced in 3.5. Please let me know if that labeling needs adjusted. Thanks!

**Comment by warmchang** [comment]
@ahardin-rh According the [OpenShift Container Platform Tested Integrations](https://access.redhat.com/articles/2176281), RHEL 7.4 only support the OCP-3.6 and later.
So I suggest remove the "branch/enterprise-3.5" label.

**Comment by ahardin-rh** [comment]
@warmchang Thanks so much! 

No revision history needed.

**Pull request merged**
