### PR TITLE
OSDOCS-5431: Adding new instance types to lists.

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4.13

Issue:
[OSDOCS-5431](https://issues.redhat.com/browse/OSDOCS-5431)

Link to docs preview:
[ROSA Instance Types](https://59557--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-instance-types_rosa-service-definition)
[OSD Instance Types](https://59557--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#aws-instance-types-ccs_osd-service-definition)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by stevsmit** [comment]
lgtm

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request closed without merging**
