### PR TITLE
bug 1597074 clarifying DB versions

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1597074

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation PTAL

Here's the source for the change: https://access.redhat.com/articles/2176281 (Mongo has an extra version because of a PR that Gaurav opened for 3.10.)

**Comment by bmcelvee** [comment]
LGTM :night_with_stars:

**Comment by kalexand-rh** [comment]
Thank you, @bmcelvee!

**Pull request merged**
