### PR TITLE
OCPBUGS-44418: Generalize install-config.yaml path to use variable directory

### PR DESCRIPTION
**Pull request by MrSanketkumar**
Version(s):  4.12, 4.13, 4.14, 4.15, 4.16, 4.17 
  

Issue: [Jira Ticket](https://issues.redhat.com/browse/OCPBUGS-44418)

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information: 
The installation process uses a **placeholder** for the directory name in one part, but later it is **hardcoded as "my-cluster"** in another, which can lead to mismatches if the actual directory name differs from the hardcoded value.

### CODE REVIEW

**Comment by skopacz1** [comment]
@mhanss could you PTAL? Thanks!

**Review by skopacz1 — APPROVED** [review]
Peer review looks good to me. @MrSanketkumar when you want this to get merged, please request a merge review by either commenting "/label merge-review-needed" or by tagging me. Thanks!

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Comment by xenolinux** [comment]
@MrSanketkumar Can you PTAL and create manual PRs for failed CPs -- 4.15 and 4.12?

**Comment by skopacz1** [comment]
@xenolinux in the case of the 4.15 error message, I've come across that "patch is empty" message before and I was usually able to resolve it by simply trying another CP command. If you don't mind, let me try that. (the 4.12 failure definitely sounds like a merge conflict though)

**Comment by xenolinux** [comment]
@MrSanketkumar I suggest you to create manual CPs as soon as possible as a best practice.

**Pull request merged**
