### PR TITLE
follow up edits

### PR DESCRIPTION
**Pull request by mburke5678**
Follow up to https://github.com/openshift/openshift-docs/pull/6020

### CODE REVIEW

**Comment by mburke5678** [comment]
@aheslin   @adellape Can you take a look at the additions through https://github.com/openshift/openshift-docs/pull/6020 ? 
I am not sure the link to Dedicated is appropriate in the _Adv Install_ and links to Dedicated and Online in _Planning_. At this point, the user, I assume, knows what he/she wants to install. 
Likewise with the cloud install in _Adv. Install_. Seems confusing here. 
There is a reference, too, to using the OpenStack CLI to install OpenShift on OpenStack. Should that be in the _Adv Install_? Should that be in _Planning_?

**Review by bogdando — APPROVED** [review]
Thank you for fixing this!

**Comment by aheslin** [comment]
@mburke5678 I agree that the links to Dedicated don't need to be in the Advanced Installer topic. It veers towards marketing content.

**Review by bogdando — APPROVED** [review]

**Comment by mburke5678** [comment]
Closing. This PR was a follow-up to https://github.com/openshift/openshift-docs/pull/6020 which contained suggestions to use Dedicated. The PR was accidentally merged to master (not cherry-picked to any staging branch). This PR was for a proofread pass and  edits. The references to Dedicated were rejected by aheslin and backed out via a different PR. I am closing this PR and will make proofread edits to bogdando's remaining text through https://github.com/openshift/openshift-docs/pull/6700

**Pull request closed without merging**
