### PR TITLE
OSDOCS-2623: release note for HAProxy 2.2.15 version bump

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-2623

Preview: https://deploy-preview-36192--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-notable-technical-changes

Tagging Release Notes Tracker: https://github.com/openshift/openshift-docs/issues/33497

### CODE REVIEW

**Comment by bmcelvee** [comment]
@frobware and @jechen0648 would you both mind reviewing this PR, please? It's a quick and easy release note update. Thanks!

**Comment by frobware** [comment]
This is now going to be 2.2.17 as I'm bumping to resolve some recent CVEs. That change hasn't landed yet so I don't know whether you would prefer to wait for confirmation of the bump.

**Comment by bmcelvee** [comment]
Thank you, @frobware! I'll go ahead and update the PR, but hold on merging for confirmation.

**Comment by frobware** [comment]
> Thank you, @frobware! I'll go ahead and update the PR, but hold on merging for confirmation.

This will be remain at v2.2.15.

It's only likely to change if the severity of the CVEs that we were addressing with v2.2.17 become high/urgent. We should commit at the change referencing v2.2.15. Thanks!

**Comment by bmcelvee** [comment]
Thanks, @frobware!

**Comment by bmcelvee** [comment]
@jechen0648 would you mind reviewing this release note PR please? Thank you!

**Pull request merged**
