### PR TITLE
BZ-1795670: Use full path to scripts

### PR DESCRIPTION
**Pull request by bergerhoffer**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1795670

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@retroflexer Can you review please?

**Comment by bmcelvee** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@geliu2016 Can you review please?

**Comment by geliu2016** [comment]
LGTM, thanks!

**Pull request merged**
