### PR TITLE
CNV-24754: Removing references to marking VM templates as favorites

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/CNV-24754

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:
As of OCP 4.11, you can no longer mark VM templates as favorites.

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by sjhala-ccs** [comment]
Because this PR is changing the support status of something in the already published docs, this might require change management. Tagging @apinnick to see if we need to add a release note or notify internal stakeholders about this change.

**Comment by apinnick** [comment]
> Because this PR is changing the support status of something in the already published docs, this might require change management. Tagging @apinnick to see if we need to add a release note or notify internal stakeholders about this change.

@sjhala-ccs Good catch. We should mention that in RN. I'll add a task. Thanks!

**Pull request merged**
