### PR TITLE
CNV-23201: Minor minimalism issue

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.10, 4.11

Issue:
https://issues.redhat.com/browse/CNV-23201
https://bugzilla.redhat.com/show_bug.cgi?id=2151386

Link to docs preview:
N/A

QE review: NA

Additional information:
N/A

### CODE REVIEW

**Comment by apinnick** [comment]
@danielclowers This kind of change should be merged to "main" and then cherrypicked to 4.10+.

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by skrthomas — COMMENTED** [review]
Merge review LGTM!

**Pull request merged**
