### PR TITLE
[OSDOCS-3212] Added a bullet to the Customer applications row, Red Hat responsibili…

### PR DESCRIPTION
**Pull request by eohartman**
Added a bullet to the Customer applications row, Red Hat responsibilities column.

Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-3212

Link to docs preview:
OSD: https://49604--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/policy-responsibility-matrix.html#policy-customer-responsibility_policy-responsibility-matrix

ROSA: https://49604--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-customer-responsibility_rosa-policy-responsibility-matrix

Additional information:

### CODE REVIEW

**Comment by 0kashi** [comment]
lgtm

**Review by opayne1 — COMMENTED** [review]
Great job on your first PR!! 🎉  I left a comment but it is more of just a suggestion. Let me know if you have questions. 😄

**Comment by opayne1** [comment]
Looks like Travis is still running for me. Not sure what is up there.

**Comment by eohartman** [comment]
So, this was my first ticket and it was a bit complicated to squash a bunch of commits into it. Then there were more issues, but I think I've finally got it all squared away. The resulting changes can be found here:

**OSD:** https://49604--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/policy-responsibility-matrix.html#policy-customer-responsibility_policy-responsibility-matrix

**ROSA:** https://49604--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-customer-responsibility_rosa-policy-responsibility-matrix

**Review by adellape — APPROVED** [review]

**Pull request merged**
