### PR TITLE
OSDOCS-8953: Add supported SR-IOV device

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-8953

Version(s): 4.15+

Issue:

Link to docs preview: https://69006--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov#supported-devices_about-sriov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@yingwang-0320, does this change look okay? Thanks!

**Comment by jab-rh** [comment]
@zhaozhanqi, what do you think? Thanks!

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi, what do you think? Thanks!

/lgtm

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Pull request merged**
