### PR TITLE
OBSDOCS-1119: Add missing entries to the API support Monitoring table

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `enterprise-4.12` and later

Issue: [OBSDOCS-1119](https://issues.redhat.com/browse/OBSDOCS-1119)

Link to docs preview: https://77553--ocpdocs-pr.netlify.app/openshift-enterprise/latest/rest_api/understanding-api-support-tiers.html#mapping-support-tiers-to-monitoring-api-groups_understanding-api-tiers

QE review:
- [x] QE has approved this change.

**Additional information:**

### CODE REVIEW

**Comment by juzhao** [comment]
LGTM

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
