### PR TITLE
BZ1962418: adding note about ssh key algorithms for FIPS

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1962418

Preview: https://deploy-preview-33336--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#ssh-agent-using_installing-aws-customizations

Confirming versions, but likely 4.5+

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@staebler, will you please confirm that you're happy with this note about SSH keys and FIPS?

**Review by staebler — COMMENTED** [review]
LGTM

**Comment by gpei** [comment]
LGTM

**Comment by kalexand-rh** [comment]
@gpei, will you please also confirm that this change is valid in 4.5+?

**Comment by lbarbeevargas** [comment]
LGTM!

**Comment by gpei** [comment]
@kalexand-rh Seen from https://access.redhat.com/solutions/3643252, this should be valid for all OCP versions

**Pull request merged**
