### PR TITLE
OSDOCS-3738: Update the cake diagram for OpenShift Kubernetes Engine

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.8+

Issue: https://issues.redhat.com/browse/OSDOCS-3738

Link to docs preview: https://52286--docspreview.netlify.app/openshift-enterprise/latest/welcome/oke_about.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by zanetworker — COMMENTED** [review]
I don't see any mention of OKE in the figure which should be the main contribution of this PR.

**Comment by zanetworker** [comment]
LGTM

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
