### PR TITLE
OSDOCS#1491 - Include diagram for IPsec traffic flows

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-1491

So this includes text changes, which if accurate, mean the diagram must be updated.

Preview:
- [Types of network traffic flows encrypted by IPsec](https://deploy-preview-31202--osdocs.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ipsec-ovn.html#nw-ovn-ipsec-traffic_about-ipsec-ovn)

### CODE REVIEW

**Comment by jboxman** [comment]
@markdgray, so when including the diagram, I took another look at the content and I have this suspicion that what I had before is incomplete. This seeks to clarify the omissions, but puts in sharp relief that the diagram as I read it is at odds with the content.

I think we need to refresh the digram as well?

Thanks!

**Comment by markdgray** [comment]
Yes,
* The arrow colors are back-to-front
* The diagram uses the term "Pod Network" instead of "Cluster Network"

**Comment by bobfuru** [comment]
Squash the commits and this LGTM!

**Comment by jboxman** [comment]
@markdgray thanks!

**Pull request merged**
