### PR TITLE
Bug 1419947 Removed Technology Preview Wording

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@ahardin-rh and @adellape can you take a quick look? I removed the Technology Preview wording from the Java Console section per comments from GSS and @vikram-redhat 
file:///home/mburke/Docs/openshift-docs/_preview/openshift-enterprise/mburke-BZ-1419947-2/architecture/infrastructure_components/web_console.html

**Review by adellape — APPROVED** [review]

**Comment by mburke5678** [comment]
[rev_history]
|xref:../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[Web Console]
|Removed the Technical Preview note in the xref:..infrastructure_components/web_console.html#jvm-console[JVM Console] section.
%

**Comment by ahardin-rh** [comment]
@mburke5678 Looks good! Just a heads-up that I edited your rev history note with 2 minor changes.

- changed [Web Console] to [Infrastructure Components -> Web Console] to show that parent topic.
-  update .html to .adoc in the second link

**Comment by vikram-redhat** [comment]
Hmm..  @ahardin-rh , @mburke5678  - shouldn't the link in the rev history be:

|Removed the Technical Preview note in the xref:**../architecture/infrastructure_components/**web_console.html#jvm-console[JVM Console] section.

**Pull request merged**
