### PR TITLE
Fix calculated max pod count based on node and pod limits

### PR DESCRIPTION
**Pull request by ehashman**
I saw this document linked on a development mailing list, and noticed a typo. With a maximum of 250 nodes that each can run a maximum of 250 pods, a 4.1 cluster can only support a maximum of `250 * 250 = 62500` pods.

/cc @chaitanyaenr

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
Nice catch @ehashman, thanks for the PR.

**Comment by vikram-redhat** [comment]
@mffiedler @xltian if you can approve this, I can merge it for GA.

**Comment by mffiedler** [comment]
@akrzos  @chaitanyaenr   Approving based on the math for 4.1, but should we have an external-facing sentence that explains the reason for the reduction in supported # of nodes?

**Review by mffiedler — APPROVED** [review]
/lgtm

**Comment by chaitanyaenr** [comment]
Thanks for the review @mffiedler, +1 to adding a sentence about the reduction in node count.

**Pull request merged**
