### PR TITLE
 Add rolloutStrategy -  Image Registry Configuration

### PR DESCRIPTION
**Pull request by dpateriya**
Added rolloutStrategy Parameter as this is one of the configurable parameter with OCP internal image registry. Here is the information obtained from the OpenAPI Specification. 
~~~
oc explain configs.imageregistry.operator.openshift.io.spec.rolloutStrategy
KIND:     Config
VERSION:  imageregistry.operator.openshift.io/v1

FIELD:    rolloutStrategy <string>

DESCRIPTION:
     rolloutStrategy defines rollout strategy for the image registry deployment.
~~~

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
Hi @wewang58 and @dmage! Would you mind giving this PR a review, please? Thanks!

**Comment by dmage** [comment]
LGTM

**Comment by bmcelvee** [comment]
Hi @xiuwang! Would you mind giving this PR a review, please? Thanks!

**Comment by xiuwang** [comment]
LGTM

**Pull request merged**
