### PR TITLE
bug 1781064 clarifying max nodes

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1781064

@jhou1, will you PTAL?

### CODE REVIEW

**Comment by jhou1** [comment]
@miyadav Will you PTAL?

**Comment by miyadav** [comment]
The changed text doesn't address the customer issue which is mentioned in
the link [1] as it seems it was  interpreted as the keys(maxReplicas) in
the yaml  will be used directly for scaling the machines  , whereas it is
not for scaling but rather limit it once a scaling decision has been made
based upon workload.

Can we  put description for maxReplicas/min like : "The limit to the
max/min number Machines of the specified type to be deployed in the
specified AWS zone once the cluster autoscaler has decided for scaling the
cluster.
[1] https://access.redhat.com/solutions/4457721

**Comment by kalexand-rh** [comment]
@miyadav, will you please take another look?

**Pull request merged**
