### PR TITLE
OSDOCS#12812: Remove TP, pull secret, and private catalog snippets

### PR DESCRIPTION
**Pull request by michaelryanpeter**
> :notebook: **This PR does not clean up all of the content changes required for catalogs to make the OLM v1 GA release**

* Remove the following snippets in the OLM v1 docs:
    - Tech Preview
    - Known issue with private registries
    - Pull secrets
* Rephrase the abstract for the RH catalogs module since they are now installed by default.

Version(s): 4.18

Issue: [OSDOCS-12812](https://issues.redhat.com//browse/OSDOCS-12812)

Link to docs preview:
* The only module with a change in phrasing:
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/managing-catalogs#olmv1-red-hat-catalogs_managing-catalogs
* Sections with removed content:
    -  https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/arch/catalogd.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/arch/components.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/arch/operator-controller.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/creating-catalogs.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/fbc.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/managing-catalogs.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/catalogs/rh-catalogs.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/ce/crd-upgrade-safety.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/ce/managing-ce.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/ce/upgrade-edges.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/index.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/extensions/of-terms.html
    - https://85731--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/index.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by dtfranz — APPROVED** [review]
/lgtm

**Review by LalatenduMohanty — APPROVED** [review]

**Comment by michaelryanpeter** [comment]
@jianzhangbjz PTAL

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
