### PR TITLE
OSDOCS-11377: Updated the mtu parameter for the bridge add. network p…

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.12+

Issue:
(https://issues.redhat.com/browse/OSDOCS-11377)

Link to docs preview:
* [Configuration for a bridge additional network (ent)](https://79276--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/multiple_networks/configuring-additional-network.html#nw-multus-bridge-object_configuring-additional-network)
* [Configuration for a bridge additional network (MShift)](https://79276--ocpdocs-pr.netlify.app/microshift/latest/microshift_networking/microshift_multiple_networks/microshift-cni-multus.html#nw-multus-bridge-object_microshift-cni-multus)

- [x] SME has approved this change.
- [x] QE has approved this change.

### CODE REVIEW

**Comment by jorti** [comment]
I tested that a integer is required in the mtu option of the bridge plugin.
LGTM

**Review by JoeAldinger — APPROVED** [review]
/lgtm

**Comment by JoeAldinger** [comment]
Merge request via slack.

**Pull request merged**
