### PR TITLE
OSDOCS-3150: Add flag argument to the Unapply a remediation command

### PR DESCRIPTION
**Pull request by kmccarron-rh**
https://issues.redhat.com/browse/OSDOCS-3150
Affects 4.6+

Preview [here](https://deploy-preview-40361--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-unapplying_compliance-remediation)

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
it looks good! thanks for the PR

**Comment by kmccarron-rh** [comment]
@pdhamdhe - When you get a chance, will you PTAL? Thx!

**Review by bergerhoffer — COMMENTED** [review]
LGTM! Merging

**Pull request merged**
