### PR TITLE
GH#77645: Application Interconnect is now Service Interconnect (Skupper)

### PR DESCRIPTION
**Pull request by pwright**
Version(s):
4.12 -> 4.15

Issue:

https://github.com/openshift/openshift-docs/issues/77645

Link to docs preview:

QE review:
- [x] QE review not required.

Additional information:

Upstream: skupper.io

### CODE REVIEW

**Comment by pwright** [comment]
@openshift/team-documentation could someone review?thx

**Review by aireilly — APPROVED** [review]

**Pull request merged**
