### PR TITLE
adjusted mongodb volume mount point

### LINKED ISSUE #5147: mongodb volume mount point differs between documentation and image readme
According to the image repository READMEs, the data directory is the mount point.  
Attempting to mount a physical volume claim on `/var/lib/mongodb` (according to the current origin documentation) does not seem to succeed in persisting data across re-deployments whereas mounting on `/var/lib/mongodb/data` does.

### PR DESCRIPTION
**Pull request by Larzenegger**
resolves #5147

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@gaurav-nelson - PTAL

**Comment by Larzenegger** [comment]
In case you end up accepting this pull request, please correct my typo in the commit message `moint` -> `mount` :)

**Comment by gaurav-nelson** [comment]
@bparees Can you please review this?

**Review by bparees — APPROVED** [review]

**Comment by bparees** [comment]
lgtm

**Comment by gaurav-nelson** [comment]
no revision history required

**Pull request merged**
