### PR TITLE
OKD on OpenStack docs refer to RHOSP only

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/okd/issues/511

Internal preview: 
OKD: [Preparing to install on OpenStack](http://file.rdu.redhat.com/~mburke/okd-openstack-version/installing/installing_openstack/preparing-to-install-on-openstack.html) 
OCP: [Preparing to install on OpenStack](file:///home/mburke/Docs/openshift-docs/_preview/openshift-enterprise/okd-openstack-version/installing/installing_openstack/preparing-to-install-on-openstack.html)

### CODE REVIEW

**Review by LorbusChris — APPROVED** [review]

**Comment by maxwelldb** [comment]
@EricArrakis @pierreprinetti @EmilienM Any concerns with this proposed docs change? It would change instances of "Red Hat OpenStack Platform (RHOSP)" on docs.okd.io (not docs.openshift.com or the customer portal) to "OpenStack."

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
