### PR TITLE
RHDEVDOCS-5645: Remove additional resources section from the Pipeline…

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.11 and later
• **JIRA issue**: [RHDEVDOCS-5645](https://issues.redhat.com/browse/RHDEVDOCS-5645)
• **Preview page**: [About Red Hat OpenShift Pipelines](https://65794--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/about-pipelines)
• SME  and QE Review not needed
• **Peer-review**: @mramendi

### CODE REVIEW

**Review by mramendi — APPROVED** [review]

**Review by adellape — APPROVED** [review]
@ekristova See review process comments from https://github.com/openshift/openshift-docs/pull/65801#pullrequestreview-1660479374.

**Pull request merged**
