### PR TITLE
remove extra --role param and fix -role typo

### PR DESCRIPTION
**Pull request by joelddiaz**
adding the "User Access Administrator" role is already handled by a future step, and you can only provide one '--role' param. So remove the extra param.

correct the typo of '-role'.

### CODE REVIEW

**Review by sdodson — APPROVED** [review]

**Comment by kalexand-rh** [comment]
@e-tienne, will you PTAL?

**Comment by e-tienne** [comment]
LGTM

**Review by kalexand-rh — APPROVED** [review]

**Comment by kalexand-rh** [comment]
Thanks everyone! Merging.

**Pull request merged**
