### PR TITLE
add rhel 8.8

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.13

Issue: n/a

Link to docs preview:

- Required machines for cluster installation: http://file.rdu.redhat.com/jdohmann/more-rhel-bumps/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-machine-requirements_installing-platform-agnostic
- Minimum resource requirements for cluster installation: http://file.rdu.redhat.com/jdohmann/more-rhel-bumps/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-minimum-resource-requirements_installing-platform-agnostic
- System requirement for RHEL compute nodes: http://file.rdu.redhat.com/jdohmann/more-rhel-bumps/machine_management/more-rhel-compute.html#rhel-compute-requirements_more-rhel-compute
- Updating RHEL compute machines in your cluster: http://file.rdu.redhat.com/jdohmann/more-rhel-bumps/updating/updating-cluster-rhel-compute.html#rhel-compute-updating-minor_updating-cluster-rhel-compute

QE review:
- [ ] QE has approved this change.

Additional information: per Scott Dodson with GA pushed to May, RHEL 8.8 needs to be added to the supported RHEL versions for compute nodes. Related to #58678

### CODE REVIEW

**Comment by jldohmann** [comment]
In the nearish future, 4.10-4.12 will also need to be updated to include updated RHEL 8.x version support

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by jldohmann** [comment]
@sdodson I know you ack'd through slack, but do you mind acking this PR for transparency before merge? Thank you!

**Pull request merged**
