### PR TITLE
Removing references to resources that cannot be configured and are no…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…t needed for viewing

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kalexand-rh These items I'm removing are just in a commented out section, but I wanted to give you a heads up because @deads2k mentions [here](https://github.com/openshift/openshift-docs/pull/15806/files#r302046103) that we shouldn't be documenting these resources. Just in case this section was intended to eventually make it into the docs.

**Comment by kalexand-rh** [comment]
Thanks for letting me know, @bergerhoffer! This section might eventually make it into the docs, so I'm glad that you put in the fix.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
