### PR TITLE
specify compute resources for the registry

### PR DESCRIPTION
**Pull request by pweil-**
@derekwaynecarr @kargakis ptal and let me know if you think this should be more specific.

@adellape - this should go in a 3.2 build.

ref: https://github.com/openshift/origin/issues/8329#issuecomment-204417847

### CODE REVIEW

**Comment by kargakis** [comment]
LGTM

@derekwaynecarr should we recommend a specific request/limit for average clusters?

**Comment by derekwaynecarr** [comment]
I do not have any data that can make a specific recommendation at this time.

The text is LGTM.

**Comment by pweil-** [comment]
@adellape can this get merged?

**Comment by adellape** [comment]
:+1:

**Pull request merged**
