### PR TITLE
Rename RHV to include/switch to oVirt

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/okd/issues/198

Add `ifedf`s to remove RHV from OKD.

Also, reverting `{rh-virtualization}` variable that was changed to `RHV` in https://github.com/openshift/openshift-docs/pull/28717/files#diff-d53ae3c90b8c03f6ca277c25ffe37db6ef5deb6320cd74131021c546508b14b3

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]

**Comment by mburke5678** [comment]
@codyhoag FYI

**Pull request merged**
