### PR TITLE
OSDOCS-11464 OCP 4.15.24 Release Notes

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.15

Issue: [OSDOCS-11464](https://issues.redhat.com/browse/OSDOCS-11464)

Link to [docs preview](https://79595--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes.html#ocp-4-15-24_release-notes)

QE review:
Not needed

Additional information: Advisory links will not work until July 31.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@cbippley noted that the advisory links are "404".  I checked the other links in your update and they all work fine.

**Comment by cbippley** [comment]
> @cbippley noted that the advisory links are "404". I checked the other links in your update and they all work fine.

Yep, that's expected before the release date. Thank you!

**Pull request merged**
