### PR TITLE
Update oc edit command from the "Scaling down the data plane to zero" section. 

### PR DESCRIPTION
**Pull request by Shubhampwrredhat**
Version(s):
4.14, 4.15, 4.16, 4.17, 4.18

Issue:

https://issues.redhat.com/browse/OCPBUGS-42561

Link to docs preview:

https://82681--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-troubleshooting.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by max-cx — APPROVED** [review]
LGTM

**Review by dfitzmau — APPROVED** [review]

**Comment by Shubhampwrredhat** [comment]
Hi @max-cx , Can you help me to get it approved with QE. 

Thank you in advance..!!

**Comment by michaelryanpeter** [comment]
@Shubhampwrredhat Thank you for your contribution!

I have a couple of comments that are outside of the scope of merge review.
1. PRs that use `main` as a parent branch must be cherrypicked to the latest release branches. The repo is currently locked for merge freeze for OpenShift 4.17. When the repo reopens, this PRs must also be cherrypicked to 4.17 and 4.18. If this only applies to 4.12-4.16, you need to create individual PRs for those branches. A QE team member can help you figure out what branches the change should apply to.
2. In the future, please wait until you have QE approval before adding the `merge-review-needed` label. 

If you have any questions or need help, you can reach out in the [#forum-ocp-docs](https://redhat.enterprise.slack.com/archives/C025XCRRH28) channel in Slack. 

I am going to remove the `merge-review-needed` label for now. Please feel free to add it again once the following actions are completed:
* You have verified if this PR also applies to 4.17 and 4.18
* You have received verification from a member of the QE team

Thank you, again for your contribution. We appreciate it!
/remove-label merge-review-needed

**Comment by PoornimaSingour** [comment]
@michaelryanpeter ,  Thank you for the details information its really helpful. Also these changes are applied to 4.17 and 4.18 as well. We will updated the PR version section.
@jiezhao16 Could you please help with the QE approval.

**Comment by PoornimaSingour** [comment]
@jiezhao16 Thank you so much for QE

**Comment by JoeAldinger** [comment]
@Shubhampwrredhat you'll need to create manual CP PRs for the branches that failed. Feel free to ping me on slack if you need help with this. On slack, I can provide a link to our docs manual. Thanks for your contribution.

**Comment by Shubhampwrredhat** [comment]
Hi  @JoeAldinger , I have created the  PR's for the enterprise-(4.14, 4.15 & 4.16) branch. Do let me know if anything is needed. 

enterprise-4.16  : https://github.com/openshift/openshift-docs/pull/83005
enterprise-4.15  : https://github.com/openshift/openshift-docs/pull/83004
enterprise-4.14  : https://github.com/openshift/openshift-docs/pull/83003

Thank You..!!

**Pull request merged**
