### PR TITLE
OSDOCS-7212: Machine configs are processed in order of their name

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-7212

Link to docs preview:
https://64537--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/machine-configuration-tasks#machine-config-overview-post-install-machine-configuration-tasks

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Review by QiWang19 — COMMENTED** [review]
/lgtm

**Comment by rioliu-rh** [comment]
LGTM
/cc @sergiordlr

**Pull request merged**
