### PR TITLE
Corrected project name for aggregated logging SCC

### PR DESCRIPTION
**Pull request by sabre1041**
Corrected logging project (`openshift-logging`) for SCC command

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@sabre1041, please open this PR against `master`, not `enterprise-3.11`. Will you confirm that this change is not valid in previous versions?

**Comment by sabre1041** [comment]
@kalexand-rh updated against master. the namespace change includes 3.10 and 3.11

**Comment by kalexand-rh** [comment]
Thanks @sabre1041!
@jianlinliu or @anpingli , will you please confirm?

**Comment by anpingli** [comment]
@kalexand-rh  LGTM.

**Review by anpingli — APPROVED** [review]

**Comment by jianlinliu** [comment]
@anpingli is the logging component owner from QE team.

**Comment by kalexand-rh** [comment]
Thank you!

**Pull request merged**
