### PR TITLE
OCP 4.17: IPI docs correction

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): applies to all versions 4.13+

Issue: https://jsw.ibm.com/browse/POCPQE-186

Link to docs preview:
https://80448--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs#installation-initializing_installing-restricted-networks-ibm-power-vs

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by gwynnemonahan — COMMENTED** [review]
LGTM

**Review by sheriff-rh — APPROVED** [review]
LGTM; merging to 4.13+

**Pull request merged**
