### PR TITLE
Changed securtityContext to securityContext

### PR DESCRIPTION
**Pull request by ghost**
@jamesread Please review. This is a follow-up to https://github.com/openshift/openshift-docs/pull/7351.

### CODE REVIEW

**Comment by jamesread** [comment]
LGTM :)

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL. No rev history needed.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Comment by jamesread** [comment]
Hey @tmorriso-rh , first time contributor here (if you can call a typo commit a contribution!), just curious why you created your own branch again rather than merging from mine? It is because I didn't apply the right labels to the PR or something or do you prefer not to merge from people outside the project or something? Not fussed, just curious. Thanks!

**Comment by tmorriso-rh** [comment]
Hi @jamesread This was actually a mistake on my part. I should have fetched your PR, which would have allowed me to view and approve your contribution, and then merge the PR. So, no, you did things correctly. :-) Sorry for the confusion.

**Pull request merged**
