### PR TITLE
Reorganize SR-IOV topics

### PR DESCRIPTION
**Pull request by jboxman**
- Add topics for 4.3

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, is there a reason to _not_ apply this to enterprise-4.3 as well?

Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, is there a reason to _not_ apply this to enterprise-4.3 as well?
> 
> Thanks!

@jboxman nope, this could be applied to 4.3 as well.

One note, not specific to 4.3,  is that with this reorganizing change, `modules/nw-sriov-nic-partitioning.adoc` is missing. It needs to be included in `networking/hardware_networks/configuring-sriov-device.adoc`, after below two lines:

```
include::modules/nw-sriov-device-discovery.adoc[leveloffset=+1]
include::modules/nw-sriov-configuring-device.adoc[leveloffset=+1]
( )  <== include it here
```

**Comment by jboxman** [comment]
@zshi-redhat, once we release 4.4, master will track 4.5; If it's merged into master, it will also be in 4.5 once we branch that.

**Comment by jboxman** [comment]
@zshi-redhat, I added `modules/nw-sriov-nic-partitioning.adoc` to master/4.4.

So far, I don't seem to have that file in the 4.3 branch:

```
git branch | grep \*
* enterprise-4.3
ls modules/nw-sriov-nic-partitioning.adoc
ls: modules/nw-sriov-nic-partitioning.adoc: No such file or directory
```

**Comment by zshi-redhat** [comment]
> @zshi-redhat, I added `modules/nw-sriov-nic-partitioning.adoc` to master/4.4.
> 
> So far, I don't seem to have that file in the 4.3 branch:
> 
> ```
> git branch | grep \*
> * enterprise-4.3
> ls modules/nw-sriov-nic-partitioning.adoc
> ls: modules/nw-sriov-nic-partitioning.adoc: No such file or directory
> ```

@jboxman hi, this is a feature backported to 4.3.z for customer0, how do we handle the new feature backport in document?

**Comment by jboxman** [comment]
@zshi-redhat, so I may need @vikram-redhat to check my math here, but I think what is needed for this is to use a conditional to include this content only for `webscale`, assuming that `webscale` is based on 4.3?

Because it's a feature backport, I don't know if there is additional work necessary for this.

**Comment by jboxman** [comment]
@zshi-redhat, it also may make sense to separate out the content for the feature backport from this _reorganization_ PR.

**Comment by vikram-redhat** [comment]
That is correct. If this is only backported for customer 0, that distro is available on the webscale version of the content. 

@ahardin-rh could you coordinate this with the telco team to confirm? As far as I can understand this should not appear in the usual version of docs for 4.3.

**Comment by jboxman** [comment]
I created a separate PR for the offending file; This PR can merge, with a redirect, as it changes URLs for a current release.

**Comment by jboxman** [comment]
@vikram-redhat, I updated the redirects sheet for this.

**Pull request merged**
