### PR TITLE
fix webhook secret example

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@bmcelvee minor fix, ptal.

**Comment by bmcelvee** [comment]
LGTM! Should the following examples be formatted the same way (i.e., `name: "mysecret"`)?

**Comment by bparees** [comment]
yeah, should have been. fixed. :)

**Comment by bmcelvee** [comment]
Perfect! Thanks :)

**Comment by bmcelvee** [comment]
No revision history needed.

**Pull request merged**
