### PR TITLE
[GH#48514][RHDEVDOCS#4334] fix additional resources link

### PR DESCRIPTION
**Pull request by pfeifferj**
Fixed the self-referencing link, pointing to this resource: [access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/monitoring/querying-metrics#querying-metrics-for-user-defined-projects-as-a-developer_querying-metrics](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/monitoring/querying-metrics#querying-metrics-for-user-defined-projects-as-a-developer_querying-metrics)

Version(s):

ROSA, OSD, enterprise-4.10

Issue:

[GH#48514](https://github.com/openshift/openshift-docs/issues/48514)
[RHDEVDOCS-4334](https://issues.redhat.com/browse/RHDEVDOCS-4334)

Link to docs preview:

[ROSA](https://57051--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_monitoring/rosa-managing-metrics.html#querying-metrics-for-user-defined-projects-as-a-developer_rosa-managing-metrics) 
[OSD](https://57051--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_monitoring/rosa-managing-metrics.html#querying-metrics-for-user-defined-projects-as-a-developer_rosa-managing-metrics)
[Enterprise](https://57051--docspreview.netlify.app/openshift-enterprise/latest/monitoring/querying-metrics.html#exploring-the-visualized-metrics_querying-metrics)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by abrennan89 — COMMENTED** [review]
I believe these should be fixed as xrefs rather than hardcoded links

**Comment by pfeifferj** [comment]
hi @abrennan89 the links point to access.rh.com, not docs.openshift.com

**Comment by abrennan89** [comment]
They are published from the same repository using the same source code, so xrefs work for both

**Comment by pfeifferj** [comment]
oh ok, my bad. I'll change to xrefs then. thank you for pointing this out

**Comment by bburt-rh** [comment]
Closing this PR because the self-referencing link has been fixed in https://issues.redhat.com/browse/OBSDOCS-154

**Pull request closed without merging**
