### PR TITLE
OCPBUGS-6802 - Remedy unclear topic titles for GitOps ZTP worker nodes

### PR DESCRIPTION
**Pull request by aireilly**
Fixes inaccuracies and tidies up some sections related to adding worker nodes to SNO cluster with GitOps ZTP. 

Version(s):
main, enterprise-4.12, enterprise-4.13

Issue:
https://issues.redhat.com/browse/OCPBUGS-6802

Link to docs preview:
https://55356--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-sno-additional-worker-node.html

QE review:
- [ ] QE has approved this change.

Additional information:
Related to: https://issues.redhat.com/browse/OCPBUGS-5972

### CODE REVIEW

**Comment by mburke5678** [comment]
@aireilly These two verification steps need to be bullets, not numbered steps. Otherwise LGTM. 
https://github.com/openshift/openshift-docs/pull/55356/files#diff-f8fe4fbf49c12199579755766fe463b02496b1b73cb54a941837319fb7958746R128
https://github.com/openshift/openshift-docs/pull/55356/files#diff-f8fe4fbf49c12199579755766fe463b02496b1b73cb54a941837319fb7958746R151

**Comment by aireilly** [comment]
> @aireilly These two verification steps need to be bullets, not numbered steps. Otherwise LGTM. https://github.com/openshift/openshift-docs/pull/55356/files#diff-f8fe4fbf49c12199579755766fe463b02496b1b73cb54a941837319fb7958746R128 https://github.com/openshift/openshift-docs/pull/55356/files#diff-f8fe4fbf49c12199579755766fe463b02496b1b73cb54a941837319fb7958746R151

Updated slightly. Each of these items are optional, hence the bullets and not sequential steps.

**Comment by mburke5678** [comment]
@aireilly Thanks for the fix. The spacing looks better now!

**Pull request merged**
