### PR TITLE
Update Azure UPI infra template

### PR DESCRIPTION
**Pull request by codyhoag**
Updated and verified in https://bugzilla.redhat.com/show_bug.cgi?id=1836016

### CODE REVIEW

**Comment by codyhoag** [comment]
@e-tienne PTAL?

**Comment by codyhoag** [comment]
@e-tienne I noticed the BZ related to this was verified. Is this good to merge?

**Comment by e-tienne** [comment]
Hello @codyhoag , openshift/installer#3720 has been verified and this brings that change in the product docs.

LGTM

**Comment by codyhoag** [comment]
Trivial code updates. No peer review necessary, since QE confirmed accuracy.

**Pull request merged**
