### PR TITLE
Removing TP notice from NetObserv CLI docs

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issue:

Link to docs preview:

https://84005--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/netobserv_cli/netobserv-cli-install.html
QE review:
- The CLI is GA, as a fact, I just forgot to remove this. No QE needed. See https://access.redhat.com/errata/RHEA-2024:8264 "Network Observability CLI General Availability."

Additional information:

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
