### PR TITLE
OSDOCS-5112: ConnectX-6 Dx supports HWOL

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-5112

This PR moves this device ID from the TP section to the GA list of device IDs.

Preview:
- [Supported devices](https://57126--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/configuring-hardware-offloading.html#supported_devices_configuring-hardware-offloading)

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
Hi @yingwang-0320, this PR promotes ConnectX-6 Dx from Tech Preview to GA. Can you confirm? Thanks!

**Comment by jboxman-rh** [comment]
cc @wizhaoredhat @bn222

**Review by snarayan-redhat — COMMENTED** [review]
Looks good!

**Pull request merged**
