### PR TITLE
OSDOCS-12109:Added FIPS info for creating ROSA cluster using UI

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.16+

Issue:
[OSDOCS-12109](https://issues.redhat.com/browse/OSDOCS-12109)

Link to docs preview:

- https://82357--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-quickstart-guide-ui.html

- https://82357--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html

- https://82357--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.html#rosa-sts-creating-cluster-customizations-ocm_rosa-sts-creating-a-cluster-with-customizations

SME review:
- [x] SME has approved this change.

Peer review:
- [x] Peer reviewer has approved this change.

QE review:
- [x] QE has approved this change.

Additional information:
**Reviewers: The changes to these docs includes adding a new **Enable FIPS Cryptography** field in the creation of a ROSA Classic cluster using the UI workflow, as well as adding new information that came with the design changes.

These changes are currently in stage.

The **Enable FIPS Cryptography** field also needs to be added to the create a cluster using the ROSA CLI docs. I will create a separate ticket for this as I think there are other fields that need to be updated.**

### CODE REVIEW

**Comment by AedinC** [comment]
> /lgtm this seems to be the same changes as GCP

Thanks Jason, yes this is the same change as for GCP.

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Comment by AedinC** [comment]
@arendej Can you please review this when you get a chance? Many thanks. I will create a separate PR to incorporate the CLI update.

**Review by arendej — APPROVED** [review]
looks good for classic only

**Pull request merged**
