### PR TITLE
Pulling in CLI doc updates after freeze

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2377

Follow up to #35593.

Previews:
* https://deploy-preview-36136--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/developer-cli-commands.html
* https://deploy-preview-36136--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@zhouying7780 As a follow up to #35593, I ran the CLI doc generation again after code freeze and there were just a few last minute changes to pull in. Can you please take a look? If you hide the whitespace changes in the diff, there are only a few lines actually changed.

Previews:

* https://deploy-preview-36136--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/developer-cli-commands.html
* https://deploy-preview-36136--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/administrator-cli-commands.html

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
