### PR TITLE
OSDOCS#7318: Updating multi-arch compute machines bare metal docs for GA

### PR DESCRIPTION
**Pull request by kelbrown20**
**Version(s):** 4.14+ 
**Issue:** [OSDOCS-7318](https://issues.redhat.com//browse/OSDOCS-7318)

**Description:** Removes tech preview labels for bare metal GA in 4.14

**Link to docs preview:**
[Creating a cluster with multi-architecture compute machine on bare metal ](https://64536--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-bare-metal)

**QE review:**
- [x] QE approved

### CODE REVIEW

**Comment by kelbrown20** [comment]
@Prashanth684 Hey Prashanth! Do you think you could take a look at this PR when you get the chance? Thank you!

**Comment by dfitzmau** [comment]
LGTM

/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
