### PR TITLE
scc read only root file system

### PR DESCRIPTION
**Pull request by pweil-**
Update descriptions and examples to include read only root file system settings

@adellape

### CODE REVIEW

**Comment by smarterclayton** [comment]
Volumes are merged now, roll it in here?

**Comment by adellape** [comment]
@pweil- This PR, yea? https://github.com/openshift/origin/pull/7935

LMK if this is ready to go or if you have further updates.

**Comment by pweil-** [comment]
@adellape - will have this updated for volume controls today

**Comment by pweil-** [comment]
@adellape - updated for volume controls

**Comment by ahardin-rh** [comment]
@smarterclayton @pweil- @adellape Picking this back up. Is this still current? Any new changes before we merge?

**Comment by pweil-** [comment]
no new changes from my side.  Should be good to go.  thanks!

**Pull request merged**
