### PR TITLE
Bug 1268368, added supportability note

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1268368

### CODE REVIEW

**Comment by adellape** [comment]
:+1:

**Comment by ahardin-rh** [comment]
added ifdef to note on Arch topic

**Comment by ahardin-rh** [comment]
3.0 work done in https://github.com/openshift/openshift-docs/pull/1654

**Comment by ahardin-rh** [comment]
**revhistory note:**

(for Architecture --> Kubernetes Infrastructure)

    Added a note to the link:../architecture/infrastructure_components/kubernetes_infrastructure.html#high-availability-masters[High Availability Masters] section indicating that moving from a single master cluster to multiple masters after installation is not supported.

(for Install/Config --> Advanced Installation)

Added notes indicating that moving from a single master cluster to multiple masters after installation is not supported.

**Pull request merged**
