### PR TITLE
TELCODOCS-1175-RN: Release Notes - Metal3 Support Added / Removal of remediation content from docs.openshift.com

### PR DESCRIPTION
**Pull request by ogradyp**
https://issues.redhat.com/browse/TELCODOCS-1175 Release Notes - Metal3 Support Added / Removal of remediation content from docs.openshift.com

Applies to OpenShift version : 4.13 

Preview: [Metal3 remediation support](http://file.emea.redhat.com/pogrady/TELCODOCS-1175-RN/release_notes/ocp-4-13-release-notes.html#ocp-4-13-metal3-remediation-support)

Dev review completed by @slintes 

Thank you.

### CODE REVIEW

**Comment by slintes** [comment]
lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by ogradyp** [comment]
Thank you for merging @bscott-rh

**Pull request merged**
