### PR TITLE
Fix-attributes

### PR DESCRIPTION
**Pull request by apinnick**
Cleaning up doc attributes

CP to 4.5 and 4.6

### CODE REVIEW

**Review by codyhoag — COMMENTED** [review]
@apinnick the changes look good and appear to render correctly. Two questions though (may have been discussed in a previous peer review, but figured I'd ask):
1. Can we use `{mtc-first}` instead of repetitively listing both as `{mtc-full} ({mtc-short})`? That has been the general way we've done it for others (e.g., `{op-system-first}` and `{op-system}`. Is there ever a scenario where we'd use `{mtc-full}` by itself?
2. Why was `{rh-virtualization}` and `{rh-virtualization-first}` removed in the one instance?

**Comment by apinnick** [comment]
@codyhoag 
1. Vikram told me to cut down the mtc attributes. That's why there is no `{mtc-first}`. He approved that but I forgot to clean up the attributes in the assemblies.

2. I have no idea why the attributes were removed or who did so. Someone removed them from the virt-document-attributes so I can't use them now.

**Comment by codyhoag** [comment]
Thanks @apinnick for explaining. I'll merge and CP.

**Pull request merged**
