### PR TITLE
[enterprise-4.2] OSP image version note

### PR DESCRIPTION
**Pull request by codyhoag**
Suggested in #18200.

### CODE REVIEW

**Comment by codyhoag** [comment]
Preview: http://file.rdu.redhat.com/~choag/012420/osp-image-version-4.2/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-creating-image_installing-openstack-installer-custom

**Comment by codyhoag** [comment]
@eurijon can you confirm? Thanks!

**Comment by eurijon** [comment]
> @eurijon can you confirm? Thanks!

It looks good to me!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
