### PR TITLE
SRVCOM-545 Document using defaultPodDisruptionBudget in installation docs

### PR DESCRIPTION
**Pull request by mgencur**
Fix for https://jira.coreos.com/browse/SRVCOM-545

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@knrc is this correct to merge? 

FYI: @geekspertise

**Comment by abrennan89** [comment]
@vikram-redhat it's for Serverless, I think it's just a minor change to some code block. @mgencur is QE on Serverless :)

**Comment by mgencur** [comment]
hi! could we get this integrated please?

**Comment by knrc** [comment]
@neal-timpe We should include something in our docs as well since it prevents OCP upgrade, MAISTRA-925 is our issue for this

**Comment by joaedwar** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
