### PR TITLE
[RHACS] Removed generate-central-database-provisioning-bundle module and its …

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://issues.redhat.com/browse/ROX-23930

- Removed the following modules:
   - modules/create-resource-central-db-bundle.adoc
   - modules/generate-central-database-provisioning-bundle.adoc
- Removed the includes from assemblies.

Preview: https://77530--ocpdocs-pr.netlify.app/openshift-acs/latest/upgrading/upgrade-roxctl.html

Cherry-pick in `rhacs-docs-4.5`

### CODE REVIEW

**Review by c-du — APPROVED** [review]

**Comment by smunje1** [comment]
@gaurav-nelson This changes LGTM. As I am new to the peer review squad, I request that you wait until @bscott-rh gives approval.

**Comment by gaurav-nelson** [comment]
**praise:** 👏🏼 Thank you @smunje1 for reviewing. I'll wait for @bscott-rh to check.

**Comment by bscott-rh** [comment]
LGTM, thanks :)

**Pull request merged**
