### PR TITLE
BZ 1767706: Removing PVC documentation

### PR DESCRIPTION
**Pull request by ousleyp**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1767706

(for enterprise-4.2 and 4.3)

### CODE REVIEW

**Comment by ousleyp** [comment]
@gsr-shanks Thanks for the review! I made a few changes based on your suggestions in https://github.com/openshift/openshift-docs/pull/17822/commits/90f518bd35d229b56ed677389b95f9f3d49cd7a7. There are also one or two minor changes based on issues I noticed. Please let me know how you feel about the changes. Cheers.

**Comment by ahardin-rh** [comment]
Looks good!

**Pull request merged**
