### PR TITLE
Bug 1867186: correct router.openshift.io/cookie-same-site variable name

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1867186

Preview: https://deploy-preview-34610--osdocs.netlify.app/openshift-enterprise/latest/networking/routes/route-configuration?utm_source=github&utm_campaign=bot_dp#nw-route-specific-annotations_route-configuration

### CODE REVIEW

**Comment by bmcelvee** [comment]
@Miciah would you mind reviewing this PR, please?

I'm curious if the formatting break for `router.openshift.io/cookie-same-site` (removing the `haproxy.`... prefix) is specific to only this instance. Do you know if the rest need updating?

**Comment by bmcelvee** [comment]
@quarterpin would you mind reviewing this PR, please? Thank you!

**Comment by quarterpin** [comment]
/lgtm
Thanks!

**Review by mikemckiernan — APPROVED** [review]
/lgtm

**Pull request merged**
