### PR TITLE
add azure file persistent volume

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by rootfs** [comment]
@childsb @ahardin-rh can this be merged into master as well?

**Comment by ahardin-rh** [comment]
@rootfs Resurrecting this old PR :scream_cat:  If this is still valid, I would close this and then open a new PR as you resubmit this against the master branch. We can then label that PR for OCP 3.4 and OCP 3.5, and any other relevant branches.

**Comment by rootfs** [comment]
@ahardin-rh yes still valid, thanks for helping!

**Comment by ahardin-rh** [comment]
@rootfs Happy to help! Closing this in favor of https://github.com/openshift/openshift-docs/pull/4463

**Pull request closed without merging**
