### PR TITLE
[OCPBUGS-16810] correct compliance operator uninstall procedure

### PR DESCRIPTION
**Pull request by briantward**
Version(s):

All

Issue:

https://issues.redhat.com/browse/OCPBUGS-16810
Steps to Reproduce:

1. Attempt to run commands for uninstall.  These commands are incorrect:

oc delete CSV -n openshift-compliance

oc delete project -n openshift-compliance

They should be:

oc delete csv <compliance-csv> -n openshift-compliance
(Only the compliance csv would be removed. There can be other csv's as well such as elasticsearch, that are installed in all namespaces. In my experience, the CSVs don't really need to be removed in order to destroy the namespace and uninstall the operator.  I believe OLM takes care of removing them after you remove the Subscription.)

oc delete project openshift-compliance 
(the project is a namespace and thus cannot be referenced within itself with the `-n` flag)

Actual results:

Failure to delete CSVs.
Failure to delete namespace.

Expected results:

CSV is deleted.
Namespace is deleted.

Link to docs preview:
[Uninstalling the OpenShift Compliance Operator from OpenShift Container Platform using the CLI](https://62829--docspreview.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-uninstallation#compliance-operator-uninstall-cli_compliance-operator-uninstallation)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by briantward** [comment]
If QE can confirm that the CSV deletion process is not necessary, then I'd also suggest we just remove that from the steps.  I don't recall ever deleting CSVs for any other operators when uninstalling them.

**Review by sheriff-rh — COMMENTED** [review]
These changes make sense to me. I'll ask QE to verify as well. Thank you!

**Comment by sheriff-rh** [comment]
@xiaojiey can you PTAL when you get a chance? Thanks.

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
