### PR TITLE
Issues: Wrong PV name in install_config/persistent_storage/persistent_storage_iscsi.html

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/13065

Need to make the change confirmed in https://github.com/openshift/openshift-docs/pull/17220#issuecomment-607053889

### CODE REVIEW

**Comment by mburke5678** [comment]
@qinpingli @bobfuru  PTAL

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Comment by qinpingli** [comment]
LGTM

**Pull request merged**
