### PR TITLE
OSDOCS-6317: Documented the 4.13.2 z-stream release notes

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-6317](https://issues.redhat.com/browse/OSDOCS-6317)

Version(s):
4.13

Link to docs preview:
[OCP 4.13.2 Release Notes](https://60874--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-2)

QE review:
- [X] Not required.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm ping me when this needs merged on Shipped Live status

**Review by JoeAldinger — COMMENTED** [review]
quick date change, please

**Comment by dfitzmau** [comment]
Closing this PR because of the addition of changes that did not rebase to my local branch.

New PR: https://github.com/openshift/openshift-docs/pull/60935

**Pull request closed without merging**
