### PR TITLE
 [enterprise-3.4] oc describe node shows less information

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1572985

### CODE REVIEW

**Comment by sjenning** [comment]
LGTM

**Comment by mburke5678** [comment]
@zhouying7780 PTAL

**Comment by zhouying7780** [comment]
LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. 

See also related PRs: 
3.9 https://github.com/openshift/openshift-docs/pull/10087
3.7 https://github.com/openshift/openshift-docs/pull/10086
3.6 https://github.com/openshift/openshift-docs/pull/10084

**Review by kalexand-rh — COMMENTED** [review]
The code calls out <9>, but you don't have a note for it. Otherwise, LGTM!

**Comment by mburke5678** [comment]
@kalexand-rh Thank you!!

**Pull request merged**
