### PR TITLE
[OSDOCS#9219]: Added DB volume snapshot advice upgrade cluster CLIOT

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-9219

Link to docs preview:
https://69878--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli#prerequisites

QE review:
- [x] QE has approved this change.

Additional information:
@gpei and @duanwei33 approved in Slack - waiting on the official /lgtm tag

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
