### PR TITLE
SRVCOM-2358 tidy up nav sections

### PR DESCRIPTION
**Pull request by gabriel-rh**
Version(s):
4.9+

Issue:
[SRVCOM-2358](https://issues.redhat.com//browse/SRVCOM-2358)

Link to docs preview: https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/about/about-serverless.html

==================
Moving Configuring Kafka content 

https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/serverless-kafka-admin.html

=================================
Security re-org:

https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/knative-serving/config-applications/serverless-config-tls.html#serverless-config-tls

https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/knative-serving/external-ingress-routing/cluster-local-availability.html#serverless-enabling-tls-local-services_cluster-local-availability

https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/brokers/kafka-broker.html#serverless-kafka-admin-security

https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/channels/serverless-kafka-admin-security-channels.html

================================
Global configuration
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/install-serverless-operator.html#serverless-configuration

Configuring Kafka
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/brokers/kafka-broker.html#serverless-kafka-admin

Creating serverless applications using the Administrator perspective
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/knative-serving/getting-started/serverless-applications.html#creating-serverless-apps-admin-console_serverless-applications

Creating triggers
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/triggers/create-triggers.html

Creating channels
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/channels/serverless-creating-channels.html

Creating subscriptions
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/subscriptions/serverless-subs.html

Removed [kn-event plugin](https://docs.openshift.com/container-platform/4.12/serverless/eventing/kn-event-plugin/kn-plugins-events.html)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Preeticp** [comment]
Hi Gabriel, this section seems a bit out of place in the Kafka broker section as it seems to do with generic Knative Kafka and not specifically broker: 
https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/brokers/kafka-broker.html#serverless-kafka-admin

Would it make sense to put it after: https://58116--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/installing-knative-eventing.html#serverless-install-kafka-odc_installing-knative-eventing?

**Comment by gabriel-rh** [comment]
> Apart from the one comment above, rest looks good to me, thank you!

I have moved the content into the installing section as requested

**Pull request merged**
