### PR TITLE
BZ 1520558 Add note that NFS is not supported for registry storage

### PR DESCRIPTION
**Pull request by ghost**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1520558

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by mburke5678** [comment]
@tmorriso-rh Should the _experimental_ notes go directly under the **Option A: NFS Host Group** and **Option B: External NFS Host** headers like the other _experimental_ notes?
Otherwise LGTM

**Comment by vikram-redhat** [comment]
@mburke5678 that is a good point. We should keep it consistent.

**Comment by tmorriso-rh** [comment]
@mburke5678 Changes made. PTAL. Thanks.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM!

**Pull request merged**
