### PR TITLE
Updating the TechPreviewNoUpdate list in 4.7

### PR DESCRIPTION
**Pull request by mburke5678**
Updated the list to match: https://github.com/openshift/api/blob/release-4.7/config/v1/types_feature.go#L108

Preview: [Understanding feature gates](https://deploy-preview-42124--osdocs.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html)

### CODE REVIEW

**Comment by rioliu-rh** [comment]
question, why `TechPreviewNoUpdate` is removed from 4.6/4.7 doc

**Comment by rioliu-rh** [comment]
@mburke5678 we have a test case that to verify kubelet conf changes for FG `TechPreviewNoUpdate` from 4.7 to latest releases
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-42945

following changes should be applied in kubelet.conf
```
oc rsh -n openshift-machine-config-operator -c machine-config-daemon machine-config-daemon-rnp56 cat /rootfs/etc/kubernetes/kubelet.conf | egrep 'RotateKubeletServerCertificate|SupportPodPidsLimit'
    "RotateKubeletServerCertificate": true,
    "SupportPodPidsLimit": true
```

**Comment by mburke5678** [comment]
@rioliu-rh Is modifying the kubelet.conf the preferred way to manage the `TechPreviewNoUpgrade` features in all releases (4.6+) or just in 4.6 and 4.7 where the `TechPreviewNoUpgrade` feature set is empty?

**Comment by mburke5678** [comment]
@rioliu-rh 

The `RotateKubeletServerCertificate` and `SupportPodPidsLimit` features are in kubelet.conf, but are set to `true`, which means enabled (??), by default. So, the user would not need to enable them with the `TechPreviewNoUpdate` feature set. Could this be the case?
If so, this PR is correct to remove the `TechPreviewNoUpdate` feature set from the 4.7 docs? (And, [this PR](https://github.com/openshift/openshift-docs/pull/42125) does the same for 4.6.)

**Comment by rioliu-rh** [comment]
@mburke5678 yes, I verified `RotateKubeletServerCertificate` and `SupportPodPidsLimit` state with a fresh 4.7 cluster. they're enabled by default (i.e. value=true)

```
oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.44    True        False         13m     Cluster version is 4.7.44

oc get featuregate/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-03-04T03:32:31Z"
  generation: 1
  name: cluster
  resourceVersion: "1010"
  selfLink: /apis/config.openshift.io/v1/featuregates/cluster
  uid: 2b62f0e3-8753-4e02-86e2-376150cf4b50
spec: {}

oc debug node/ip-10-0-151-96.us-east-2.compute.internal
Starting pod/ip-10-0-151-96us-east-2computeinternal-debug ...
To use host binaries, run `chroot /host`
Pod IP: 10.0.151.96
If you don't see a command prompt, try pressing enter.
sh-4.4#
sh-4.4# chroot /host
sh-4.4# cat /etc/kubernetes/kubelet.conf|egrep 'RotateKubeletServerCertificate|SupportPodPidsLimit'
  RotateKubeletServerCertificate: true
  SupportPodPidsLimit: true
```

**Comment by rioliu-rh** [comment]
@mburke5678 I verified RotateKubeletServerCertificate and SupportPodPidsLimit state with a fresh 4.6 cluster. they're enabled by default (i.e. value=true)

```
oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.55    True        False         104m    Cluster version is 4.6.55

oc get featuregate/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-03-04T04:24:50Z"
  generation: 1
  name: cluster
  resourceVersion: "1600"
  selfLink: /apis/config.openshift.io/v1/featuregates/cluster
  uid: 930cb4dc-cc8c-4e99-bc1f-11243659a05b
spec: {}

oc debug node/ip-10-0-217-170.us-east-2.compute.internal
Starting pod/ip-10-0-217-170us-east-2computeinternal-debug ...
To use host binaries, run `chroot /host`
Pod IP: 10.0.217.170
If you don't see a command prompt, try pressing enter.
sh-4.4# chroot /host
sh-4.4# cat /etc/kubernetes/kubelet.conf|egrep 'RotateKubeletServerCertificate|SupportPodPidsLimit'
  RotateKubeletServerCertificate: true
  SupportPodPidsLimit: true

```
So features in  featureSet `TechPreviewNoUpgrade` are enabled by default in 4.6 and 4.7 builds. this featureSet can be removed from docs of 2 versions.

Also I will update related test cases accordingly.

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Pull request merged**
