### PR TITLE
GH-47667: add links to butane docs

### LINKED ISSUE #47667: [enterprise-4.10] Issue in file post_installation_configuration/machine-configuration-tasks.adoc
### Which section(s) is the issue in?
Every note in this page - Creating machine configs with Butane
image

### What needs fixing?
There's no link or related page in whole document about how to use or down butane.
Please provide a page that describe how to create machine configs with Butane

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.8+

Issue: fixes #47667

Link to docs preview: 

Additional resources section added below the follow procedures:
- http://file.rdu.redhat.com/jdohmann/GH-47667/post_installation_configuration/machine-configuration-tasks.html#installation-special-config-chrony_post-install-machine-configuration-tasks
- http://file.rdu.redhat.com/jdohmann/GH-47667/post_installation_configuration/machine-configuration-tasks.html#machineconfig-modify-journald_post-install-machine-configuration-tasks
- http://file.rdu.redhat.com/jdohmann/GH-47667/post_installation_configuration/machine-configuration-tasks.html#rhcos-load-firmware-blobs_post-install-machine-configuration-tasks

Additional information:

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Comment by jldohmann** [comment]
@mike-nguyen could you PTAL for QE ack? This PR adds some links to another part of the docs about using Butane

**Comment by mike-nguyen** [comment]
LGTM

**Pull request merged**
