### PR TITLE
BZ1669050: Use oc exec instead of oc rsh in Customized HAProxy Router steps

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1669050

Use "oc exec" instead of 'ocrsh" which does not modify the content when piping out to file.

### CODE REVIEW

**Comment by mburke5678** [comment]
@xingxingxia Hello. You were [assigned the BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1668763) that resulted in [BZ:1669050](https://bugzilla.redhat.com/show_bug.cgi?id=1669050). Is this an issue you can review?

**Comment by xingxingxia** [comment]
Updated BZ with appropriate QA Contact.

**Pull request merged**
