### PR TITLE
OCPBUGS#11961: Update the project file

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): ~~4.9+~~ 4.10+ now that 4.9 is closed

Issue: https://issues.redhat.com/browse/OCPBUGS-11961

Link to docs preview: https://58972--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-project-file_osdk-golang-tutorial

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by adellape** [comment]
@xenolinux Could you also use this PR to add `sdk.x-openshift.io/v1: {}` to the list of plugins per https://issues.redhat.com/browse/OCPBUGS-11961? 🙇

**Comment by xenolinux** [comment]
> @xenolinux Could you also use this PR to add `sdk.x-openshift.io/v1: {}` to the list of plugins per https://issues.redhat.com/browse/OCPBUGS-11961? 🙇

Addressed - @adellape Can we merge this PR if it looks good?

**Pull request merged**
