### PR TITLE
Link only to the OCP mirror site for live PXE image downloads

### PR DESCRIPTION
**Pull request by bgilbert**
The customer portal page doesn't appear to have them.

cc @miabbott @bobfuru

### CODE REVIEW

**Comment by bgilbert** [comment]
Wait, no, I see what's happening here.  The customer portal page only lists PXE artifacts for the specific Z-stream releases that contain bootimage bumps.  That's not very usable.  @miabbott, what do you think is the right fix here?  I notice that the instructions for downloading the ISO image already link solely to the OCP mirror site.

**Comment by travier** [comment]
We also have a lot of "for RHEL 7" items in the list which don't really make sense (but should be harmless).

**Comment by miabbott** [comment]
> Wait, no, I see what's happening here. The customer portal page only lists PXE artifacts for the specific Z-stream releases that contain bootimage bumps. That's not very usable. @miabbott, what do you think is the right fix here? I notice that the instructions for downloading the ISO image already link solely to the OCP mirror site.

This matches how we published/listed artifacts for RHELAH, so it is not surprising.  Personally, I think it would be fine to remove the link to the portal; the canonical source of artifacts (per the documentation) is the mirror, so the inclusion of a link to the portal is just a nicety.

**Review by mikemckiernan — COMMENTED** [review]
I previewed from https://deploy-preview-37127--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-iso_installing-bare-metal-network-customizations

Ideally, there'd be a BZ or GH Issue.

An "up-to-you" on using "4.9" in the text or entertaining `{product-version}`.  I don't know enough about the area to infer if that's welcoming a calamity or not.

**Comment by bobfuru** [comment]
Thanks, @mikemckiernan!

> I previewed from https://deploy-preview-37127--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-iso_installing-bare-metal-network-customizations

Thanks, I don't know why I posted a live link. 🙄 
 
> Ideally, there'd be a BZ or GH Issue.

Agreed, though in this case it's not really a bug but more of a minor improvement, so I opted to keep it within Benjamin's PR.
 
> An "up-to-you" on using "4.9" in the text or entertaining `{product-version}`. I don't know enough about the area to infer if that's welcoming a calamity or not.

It gets a version bump with each release. I'm not certain that an attribute will resolve correctly in a link, so leaving it as is for now but will investigate.

**Pull request merged**
