### PR TITLE
OCPBUGS-19428: Issue in file scalability_and_performance/using-cpu-ma…

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
…nager.adoc

Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-19428

Link to docs preview:
https://68206--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/using-cpu-manager#setting_up_cpu_manager_using-cpu-manager-and-topology_manager
https://68206--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks#nodes-pods-plugins-about_post-install-node-tasks
https://68206--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks#setting_up_topology_manager_post-install-node-tasks

QE review: QE is not required, this is only a spelling correction. 
- [ ] QE has approved this change.

Additional information: Also corrected spelling errors in comments describing the section "scalability_and_performance"

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Comment by bmcelvee** [comment]
LGTM

**Pull request merged**
