### PR TITLE
fixing wrong commands

### LINKED ISSUE #3707: Wrong command present in multicomponent-application documentation ( odo.dev )
/kind documentation

## What mistake did you find / what is missing in the documentation?
Minor mistakes in documentation,
- [Documentation](https://odo.dev/docs/creating-a-multicomponent-application-with-odo/#deploying-the-front-end-component)
  command in bellow image need to be change with `git clone https://github.com/openshift/nodejs-ex frontend`
  image
  
- [Documentation](https://odo.dev/docs/creating-a-multicomponent-application-with-odo/#modifying-the-running-application)
  command in bellow image need to be change with `cd frontend`
 image

## What is the relevance of it?
Better user UX

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
Fixes [#3707](https://github.com/openshift/odo/issues/3707)

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@Preeticp PTAL

**Comment by boczkowska** [comment]
LGTM

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
