### PR TITLE
ARO: Add link to Azure Monitor documentation

### PR DESCRIPTION
**Pull request by olga-mir**
Microsoft already has documentation on Azure Monitor for containers including on ARO clusters. We do not wan't to duplicate it, but we need to make our customers aware that this feature is available to them and provide links to that documentation.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, who should provide a review?

**Comment by Makdaam** [comment]
/lgtm
The doc change better reflects what's going on. The first version was written when the Azure Monitor for ARO was still in development.

**Comment by kalexand-rh** [comment]
Ok! Then I'll merge it. Thanks. :)

**Pull request merged**
