### PR TITLE
Issue 44285, fixed incorrect statement

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses https://github.com/openshift/openshift-docs/issues/44285

For 4.6+

Preview build: https://deploy-preview-45342--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-raw-results.html

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
/lgtm - please stand by for further review.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too

**Pull request merged**
