### PR TITLE
[MULTIARCH-3486,3485] Remove SNO restriction IBM P/Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14+

Issue:
- https://issues.redhat.com/browse/MULTIARCH-3486
- https://issues.redhat.com/browse/MULTIARCH-3485

Link to docs preview: https://66869--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_on_prem_assisted/installing-on-prem-assisted

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by SNiemann15** [comment]
@holgwolf @manojnkumar Please QE approve

**Comment by holgwolf** [comment]
lgtm

**Comment by manojnkumar** [comment]
LGTM

**Comment by SNiemann15** [comment]
/label peer-review-needed 

Not sure if its really needed since I've only removed a note.

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
