### PR TITLE
Updated instances of OpenShift to {product-title} in Cluster Admin

### PR DESCRIPTION
**Pull request by ahardin-rh**
Skipped Admin Solution topics for now

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @tnguyen-rh @bfallonf @tpoitras PTAL. Thanks!

**Comment by tnguyen-rh** [comment]
@ahardin-rh LGTM. :flower_playing_cards:

**Comment by ahardin-rh** [comment]
No rev history needed

**Comment by adellape** [comment]
@ahardin-rh Same w/ this one wrt dropping enterprise-3.1 and doing a sweep in follow-up directly on the branch.

**Pull request merged**
