### PR TITLE
4.1 UI fix

### PR DESCRIPTION
**Pull request by apinnick**
Corrected OCP 4.1 console command: 
Catalog > OperatorHub
Catalog > Installed Operators

for 4.2+

Doc preview:

http://file.tlv.redhat.com/~apinnick/UI_fix/migration/migrating-4-4/migrating-openshift-4_1-to-4.html

### CODE REVIEW

**Comment by apinnick** [comment]
@peer-review-squad Ready for review

**Comment by bmcelvee** [comment]
@apinnick LGTM - do you need me to merge + cherrypick? Thanks!

**Comment by apinnick** [comment]
@bmcelvee Yes, please merge and cherry-pick for 4.2.

Thanks!

**Pull request merged**
