### PR TITLE
Fixed imageChange to ImageChange in type spec

### PR DESCRIPTION
**Pull request by ehvs**
- Aligned team: Dev Tools
- For branches: 3.11 - 4.5 - 4.6 - 4.7 - 4.8 
- https://issues.redhat.com/browse/RHDEVDOCS-3014
- Direct link to doc preview: https://deploy-preview-32674--osdocs.netlify.app//openshift-enterprise/latest/cicd/builds/triggering-builds-build-hooks.html
- SME review: @wking 
- QE review: Waiting for review
- Peer review: Waiting for review @rolfedh

### CODE REVIEW

**Review by wking — APPROVED** [review]

**Review by rolfedh — APPROVED** [review]
/lgtm

**Pull request merged**
