### PR TITLE
clean up build CA docs

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton @adambkaplan ptal  (Clayton to ensure he's happy w/ the cleanup since he requested it, Adam for technical accuracy).

/assign @bmcelvee 

needs backporting to at least 4.2 and i think 4.1.

**Review by adambkaplan — APPROVED** [review]
lgtm

/cc @bmcelvee 

I could have swore we had documentation similar to this leading up to 4.1. Was it somehow dropped?

**Comment by bparees** [comment]
i got what i'll consider verbal confirmation from @smarterclayton that this addresses his primary concerns.

**Comment by bmcelvee** [comment]
LGTM, thanks @bparees. 

In the email you mentioned including the example (module, maybe?) in the Configuring image settings section of the Image configuration resources assembly (https://docs.openshift.com/container-platform/4.2/openshift_images/image-configuration.html#images-configuration-file_image-configuration). Do you still want to do that or are the changes in this PR sufficient?

**Review by bmcelvee — APPROVED** [review]

**Comment by bparees** [comment]
> In the email you mentioned including the example (module, maybe?) in the Configuring image settings section of the Image configuration resources assembly (https://docs.openshift.com/container-platform/4.2/openshift_images/image-configuration.html#images-configuration-file_image-configuration). Do you still want to do that or are the changes in this PR sufficient?

yes i think something along those lines should still be done, that is a different issue

**Comment by bmcelvee** [comment]
Got it. I opened a [quick] PR to add the module, but marked it as WIP since it'll need rebasing after this one merges. 

I don't think this PR needs QE review, so I can go ahead and merge + cherrypick if you think it's set.

**Comment by bparees** [comment]
i'd say it's all set.

**Pull request merged**
