### PR TITLE
Clarify terms, rm old OCE file

### PR DESCRIPTION
**Pull request by bobfuru**
Replacing some product names with attributes (RHEL and RHCOS) in a few places. 

Also removes "About OpenShift Container Engine" ([https://github.com/openshift/openshift-docs/blob/main/welcome/oce_about.adoc](https://github.com/openshift/openshift-docs/blob/main/welcome/oce_about.adoc)) because it is no longer named as such in OCP 4.

This should not need to be added to the [redirects register](https://docs.google.com/spreadsheets/d/1KH2_p54Fr2KRFTUGzQdpqExox7iL9RM4_yiPNQpArjk/edit?usp=sharing). For OCP 4.1-4.3, the link already resolves from `oce_about` to `oke_about`. For 4.4+, `oce_about` is not found, so there should be no harm in removing this file from the repo.

Preview link: https://deploy-preview-36063--osdocs.netlify.app/openshift-enterprise/latest/welcome/oke_about.html

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]
/lgtm

Thanks!

Obligatory: Sounds like you've already done your research re: redirects, but if there are any doubts, check with Vikram.

**Comment by bobfuru** [comment]
FYI @vikram-redhat

**Pull request merged**
