### PR TITLE
OCPBUGS#29178: replacing RBAC image

### PR DESCRIPTION
**Pull request by kalexand-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-29178

Link to docs preview:
https://71298--ocpdocs-pr.netlify.app/openshift-enterprise/latest/authentication/using-rbac#default-roles_using-rbac

Compare to: https://docs.openshift.com/container-platform/4.14/authentication/using-rbac.html#default-roles_using-rbac

QE review:
- [n/a ] QE has approved this change.

Additional information:
I found the updated image in the `enterprise-3.11` branch and replaced it in `main`.

### CODE REVIEW

**Review by mjpytlak — COMMENTED** [review]
lgtm @kalexand-rh

**Comment by kalexand-rh** [comment]
The image is already present in 4.11-4.13.

**Pull request merged**
