### PR TITLE
Marking Masters as Unschedulable Nodes false needs to be False in doc

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1417232

Tiny change. No peer review needed.

### CODE REVIEW

**Comment by mburke5678** [comment]
Per @sdodson "False is definitely more correct, without testing it I couldn't tell you if false worked or not and we don't have time for anyone to go back and test this with 3.4."

**Comment by mburke5678** [comment]
@gpei Is this something you can look at?

**Comment by gpei** [comment]
LGTM

**Pull request merged**
