### PR TITLE
heading for service account/secret section

### PR DESCRIPTION
**Pull request by bparees**
@liggitt ptal.

### CODE REVIEW

**Comment by bparees** [comment]
w/o this change, the information about service account/secret whitelisting is blended into the "infrastructure service accounts" section.

**Comment by bparees** [comment]
or @deads2k

**Comment by ahardin-rh** [comment]
LGTM

**Comment by deads2k** [comment]
lgtm

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/service_accounts.adoc#admin-guide-service-accounts[Configuring Service Accounts]
|Added a xref:../admin_guide/service_accounts.adoc#service-accounts-and-secrets[Service Accounts and Secrets] heading.
%

**Pull request merged**
