### PR TITLE
Make default scanTolerations more tolerant

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.6 and above versions
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2007613)
- [Preview](https://deploy-preview-44341--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-scans.html)
- @jhrozek @pdhamdhe ptal

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by pdhamdhe** [comment]
LGTM 
@xiaojiey Hi, please help to review. Thanks

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM 
Amrita: we will hold off on merge until your last ACK, please resubmit to peer-review-squad when ready.

**Comment by Amrita42** [comment]
@GroceryBoyJr  we can merge now we have the 3rd ack

**Comment by bobfuru** [comment]
LGTM

**Comment by Amrita42** [comment]
forgot to add the PRs here :
https://github.com/openshift/openshift-docs/pull/44427>> 4.6. 
https://github.com/openshift/openshift-docs/pull/44428 >> 4.7  
https://github.com/openshift/openshift-docs/pull/44429 >> 4.8

@bergerhoffer @bobfuru

**Comment by bergerhoffer** [comment]
@Amrita42 In looking at the CPs, it doesn't look like the second YAML block change was made (where it removed `effect: NoSchedule` etc). But I do see them there in the file still. Should that change be made as well?

**Comment by Amrita42** [comment]
> @Amrita42 In looking at the CPs, it doesn't look like the second YAML block change was made (where it removed `effect: NoSchedule` etc). But I do see them there in the file still. Should that change be made as well?

You are right my mistake , let me correct that. and tag you once im done @bergerhoffer

**Comment by Amrita42** [comment]
@bergerhoffer ptal.

**Pull request merged**
