### PR TITLE
clarify that completion deadline is not supported with pipeline strategy

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/origin/issues/19481

@openshift/sig-developer-experience @bmcelvee ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
Yep, whenever we introduced completion deadline (I am fairly sure that dropped in after pipeline strategy).

**Comment by bmcelvee** [comment]
This PR does not require QE review.

**Pull request merged**
