### PR TITLE
TELCODOCS-522 - enterprise-4.12 ClusterGroupUpgrade message is incorrect

### PR DESCRIPTION
**Pull request by aireilly**
https://issues.redhat.com/browse/TELCODOCS-522

Fixes incorrect status message for 4.12

Merge to enterprise-4.12 only.

### CODE REVIEW

**Comment by aireilly** [comment]
@jc-rh can you review/LGTM on this please. Related to https://github.com/openshift/openshift-docs/pull/53026#discussion_r1031759751

**Comment by GroceryBoyJr** [comment]
https://53182--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.html#ztp-monitoring-policy-deployment-progress_ztp-configuring-managed-clusters-policies

**Review by GroceryBoyJr — COMMENTED** [review]
lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
/lgtm

**Comment by GroceryBoyJr** [comment]
@aireilly Please forgive my experimentation, github is pretty finicky, I'm trying to see how much. Answer: A lot! :-D

**Comment by aireilly** [comment]
No worries thanks @GroceryBoyJr :)

**Pull request merged**
