### PR TITLE
Issue 53512 updated example pod resource requests and limits

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.9+

Issue:
https://github.com/openshift/openshift-docs/issues/53512

Link to docs preview:
[Scheduling Pods with resource requests](http://file.rdu.redhat.com/antaylor/issue-53512/security/compliance_operator/compliance-scans.html#compliance-scheduling-pods-with-resource-requests_compliance-operator-scans)

Additional information:
None currently.

### CODE REVIEW

**Comment by rhmdnd** [comment]
/lgtm

Thanks!

**Comment by sheriff-rh** [comment]
Rebased; merging.

**Pull request merged**
