### PR TITLE
clarify onbuild behavior with s2i

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge
@ryanj fyi

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by ahardin-rh** [comment]
@bparees Thanks! Looks good!

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../creating_images/s2i.html[S2I Requirements]
|Clarified details of link:../creating_images/s2i.html#using-images-with-onbuild-instructions[onbuild behavior with S2I].
%

**Pull request merged**
