### PR TITLE
[OSDOCS-4465, OSDOCS-4406]: Backporting CCO feature announcements into 4.11.z

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11

Issue:
[OSDOCS-4465](https://issues.redhat.com//browse/OSDOCS-4465) and [OSDOCS-4406](https://issues.redhat.com//browse/OSDOCS-4406)

Link to docs preview:
- [4.11.13](https://53487--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-13-notable-technical-changes)
- [4.11.16](https://53487--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-16-notable-technical-changes)

QE review:
(see change mgmt acks below)

Additional information:
- Must cherrypick #52348 and #52380 into 4.11 with this merge.
- Requires change management acks:
  - [x] Andrew Butcher
  - [x]  Jianping Shu
  - [x] @sferich888
  - [x] @kalexand-rh
  - [x] @julienlim

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@abutcher and @jianping-shu these are the 4.11 announcements for the CCO backports from a little while ago, PTAL

**Comment by kalexand-rh** [comment]
LGTM

**Review by abutcher — APPROVED** [review]
LGTM

**Comment by jianping-shu** [comment]
LGTM

**Comment by julienlim** [comment]
lgtm

**Pull request merged**
