### PR TITLE
Updates DNS NMState Operator important note for clarity

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OCPBUGS-24361

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anuragthehatter** [comment]
@qiowang721 Can you also confirm this?

**Comment by mburke5678** [comment]
@stevsmit One comment based on my brute ignorance of the subject matter. Feel free to disregard.

**Comment by stevsmit** [comment]
@qiowang721 Please disregard. There is more information required that requires me to open a separate PR. I will ping all involved parties in a separate PR soon.

**Comment by qiowang721** [comment]
@stevsmit okay, thanks.
Actually configure DNS on ovnk cluster should be supported, just do not touch the br-ex interface, like configure a global DNS.

**Pull request closed without merging**
