### PR TITLE
OSDOCS-10660: Update SOC1 for ROSA HCP

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-10660

Link to docs preview:
https://76470--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security.html#rosa-policy-compliance_rosa-policy-process-security

QE review:
Compliance table update. No QE review required.

Additional information:

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Review by arendej — APPROVED** [review]
thank you

**Pull request merged**
