### PR TITLE
CNV#41658: adding backup assembly to rosa/osd

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.14+

Issue: [CNV-41658](https://issues.redhat.com//browse/CNV-41658)

Link to docs preview:
ROSA: https://78527--ocpdocs-pr.netlify.app/openshift-rosa/latest/virt/backup_restore/virt-backup-restore-overview
OSD: https://78527--ocpdocs-pr.netlify.app/openshift-dedicated/latest/virt/backup_restore/virt-backup-restore-overview
Enterprise: https://78527--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/backup_restore/virt-backup-restore-overview

QE review:
- [x] QE has approved this change.

Additional information:
- No new content; just adding existing content back to ROSA/OSD
- Conditionalizing links and additional resources so they don't appear in ROSA/OSD (they all 404 at this time)
- Moving the important admonition from the very bottom of the page to the top

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
Otherwise, LGTM!

**Comment by dalia-frank** [comment]
lgtm

**Comment by sjhala-ccs** [comment]
@kalexand-rh IIUC, the 4.17 CP failed again (see error message above) because with https://github.com/openshift/openshift-docs/pull/79323 being merged, the content is already in sync?

**Pull request merged**
