### PR TITLE
 add docs for single vs. multiple vcenter

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/13997

Built draft's here: http://file.rdu.redhat.com/kalexand/030619/PR13997/install_config/configuring_vsphere.html#vsphere-configuring-masters-manual_configuring-for-vsphere

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@dav1x, will you PTAL?

**Comment by dav1x** [comment]
LGTM @kalexand-rh 

Thank you!

**Comment by kalexand-rh** [comment]
Thanks! @vikram-redhat, since this is part of the ref arch content, I'm going to merge.

**Pull request merged**
