### PR TITLE
Issue 6022: Fixed broken links to CNS for OCP content

### PR DESCRIPTION
**Pull request by ghost**
@Cameronwyatt This is a Follow-up to https://github.com/openshift/openshift-docs/issues/6022. I fixed the broken links to the CNS content. Please review. Thanks!

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
No rev history needed.

**Comment by jhou1** [comment]
LGTM

**Comment by mburke5678** [comment]
@tmorriso-rh I assume this link is appropriate for all versions? The article subtitle suggests is it for 3.6? Otherwise LGTM

**Comment by tmorriso-rh** [comment]
@mburke5678 Thanks, the broken link points to GlusterFS 3.1 docs, but I guess the version of GlusterFS used would depend on the version of OCP used, correct?

Should I change the link to the GlusterFS landing page? https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/

Customer would have to select their version of GlusterFS to get the right doc.

**Comment by mburke5678** [comment]
@vikram @aheslin Any thoughts on what @tmorriso-rh can do regarding the links to the Gluster storage docs? Hard coded links in each staging branch to the appropriate Gluster version? Link to the Gluster top page?  
An Atom search shows 9 links to _https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/_ in 4 files.

**Comment by tmorriso-rh** [comment]
@aheslin @vikram-redhat Bump. Any thoughts on this? Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh sadly in this case, we will need to update the links each time rather than point the users to a generic landing page. 

As @mburke5678 has pointed out, there are 9 total links that need updating, so please do a search across the docs to find those 9 links and update them to the newer links. I suspect, this will be from 3.6 onwards.

**Comment by vikram-redhat** [comment]
I have removed the labels for 3.2 to 3.5, as the new links are from 3.6 onwards as pointed out in the original issue.

**Pull request merged**
