### PR TITLE
fix sno differences text

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13+

Issue: None

Link to docs preview: [Single-node OpenShift differences](https://61781--docspreview.netlify.app/openshift-enterprise/latest/virt/about-virt.html#virt-sno-differences_about-virt)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by akalenyu** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Good work, @apinnick: the changes you made really improve the SNO doc!

**Pull request merged**
