### PR TITLE
OSDOCS-2359 Remove admonition on outdated Azure feature requirement

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2359

Preview: https://deploy-preview-39390--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-vnet.html#installation-about-custom-azure-vnet_installing-azure-vnet

### CODE REVIEW

**Comment by codyhoag** [comment]
@mgahagan73 can you verify? Thanks!

**Comment by codyhoag** [comment]
@mgahagan73 resurfacing this. Can you verify? Thanks!

**Comment by mgahagan73** [comment]
Confirmed, private-dns has been a mainline feature in Azure for a while now and the reasons it's needed for api-int in particular have been documented elsewhere so no need for the warning. 

/lgtm

**Comment by mjpytlak** [comment]
Peer review looks good to me.

**Pull request merged**
