### PR TITLE
OSDOCS-9675: Add procedure for initial role creation and account association

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-9675

Link to docs preview:
Added link to checklist: https://74561--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-cloud-expert-prereq-checklist.html#aws-account 
Added module: https://74561--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-cloud-expert-prereq-checklist.html#rosa-sts-associating-your-aws-account_rosa-cloud-expert-prereq-checklist

QE review:
Adding existing module for additional context. No procedural changes involved. No QE review required. 

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.18` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.17. And any PR going into `main` must also target the latest version branch (enterprise-4.18).

If the update in your PR does NOT apply to version 4.18 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by bmcelvee** [comment]
Updated the PR. This is just pulling an existing module into the prerequisite steps with no additional changes to the content.

**Comment by obrown1205** [comment]
/label peer-review-done
/remove-label peer-review-in-progress
LGTM! :)

**Pull request merged**
