### PR TITLE
BZ 1538473 Updates to Recycling section

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1538473

This should apply to branch/enterprise-3.6 and above.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@weherdh Please review.

**Comment by tmorriso-rh** [comment]
No revision history needed.

**Comment by weherdh** [comment]
LGTM

**Comment by tmorriso-rh** [comment]
Update rev history files.

**Pull request merged**
