### PR TITLE
OSDOCS-5184: OSDK 1.25.4 Patch release: main docs content

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.12+

Issue: [OSDOCS-5184](https://issues.redhat.com//browse/OSDOCS-5184)

Link to docs preview:
* [About Operator SDK (note adomonition)](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-about.html)
* [Installing Operator SDK CLI](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html)
* [Scorecard config](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-config_osdk-scorecard)
* [Scorecard output](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-config_osdk-scorecard)
* [Scorecard parallel testing](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-parallel_osdk-scorecard)
* [Updating Go-based projects](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-updating-projects.html)
* [Updating Ansible-based projects](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html)
* [Updating Helm-based projects](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-updating-projects.html)
* [Updating Hybrid Helm-based projects](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.html)
* [Updating Java-based projects](https://55496--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-updating-projects.html)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Review by everettraven — APPROVED** [review]
LGTM

**Pull request merged**
