### PR TITLE
OSDOCS-5789: Understanding updates section

### PR DESCRIPTION
**Pull request by skopacz1**
[OSDOCS-5789](https://issues.redhat.com/browse/OSDOCS-5789)

Versions: 4.14+

This PR moves all conceptual pages in the update docs into the "Understanding OpenShift updates" subsection. The overview page has also been removed from standard OCP docs (the file is still kept around for OKD docs, since it seems to have some OKD-specific information in there). The scope of this PR is limited to reorganization, and no content or information has been changed.

Previews:
**Understanding OpenShift updates**

- [Introduction to OpenShift updates](https://62151--docspreview.netlify.app/openshift-enterprise/latest/updating/understanding_updates/intro-to-updates.html)
- [How cluster updates work](https://62151--docspreview.netlify.app/openshift-enterprise/latest/updating/understanding_updates/how-updates-work.html)
- [Understanding update channels and releases](https://62151--docspreview.netlify.app/openshift-enterprise/latest/updating/understanding_updates/understanding-update-channels-release.html)
- [Understanding OpenShift update duration](https://62151--docspreview.netlify.app/openshift-enterprise/latest/updating/understanding_updates/understanding-openshift-update-duration.html)

OKD: [Introduction to OpenShift updates](https://file.rdu.redhat.com/skopacz/OSDOCS-5789/updating/understanding_updates/intro-to-updates.html) (requires VPN connection)

Samples from sections with updated links:

- [Architecture overview](https://62151--docspreview.netlify.app/openshift-enterprise/latest/architecture/index.html#:~:text=Platform%20Logging.-,For%20more%20information,-on%20over%2Dthe)
- [Installer](https://62151--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#additional-resources_creating_manifest_ignition)
- [Networking](https://62151--docspreview.netlify.app/openshift-enterprise/latest/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer-allowed-source-ranges.html#additional-resources)
- [Scalability and Performance](https://62151--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.html#:~:text=disconnected%20environment.-,For%20more,-information%20about%20update)

### CODE REVIEW

**Comment by vrutkovs** [comment]
LGTM

**Comment by skopacz1** [comment]
Hey @tmalove, the site works for me when I checked it just now. Are you connected to VPN? Sorry, I should have clarified in my comment that it's a fileshare preview requiring VPN connection, I'll do that now.

**Review by jeana-redhat — COMMENTED** [review]
Noticed a couple nits while scanning for link structure

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
