### PR TITLE
Update nw-operator-cr.adoc

### PR DESCRIPTION
**Pull request by Rupesh-git-eng**
Version(s):

4.12, 4.13 

Issue:

The calculation isn't correct. 

Link to docs preview:

https://61466--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-network-customizations.html#nw-operator-cr-cno-object_installing-gcp-network-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@weliang1, will you please confirm this change?

**Comment by maxwelldb** [comment]
@ShaunaDiaz Yup. Waiting on the addition of the preview link to the PR description.

**Review by maxwelldb — APPROVED** [review]

**Comment by kcarmichael08** [comment]
Also cherry picking to 4.14 since that branch is created already.

**Pull request merged**
