### PR TITLE
Add namespace to commands

### PR DESCRIPTION
**Pull request by xenolinux**
Specified the (-n myproject) project for the commands
OCP version: 4.6, 4.7, 4.8, 4.9, 4.10
Fixes: [BZ1889406](https://bugzilla.redhat.com/show_bug.cgi?id=1889406)
QA contact: @anuragthehatter 
Preview: link

### CODE REVIEW

**Comment by sagidlow** [comment]
LGTM!

**Comment by ctauchen** [comment]
@xenolinux @anuragthehatter

Step 1 of this procedure already puts us in the `myproject` namespace, so this appears to be a redundant addition.

Is the idea here to double up and make extra sure that `oc new-app` is working in the right namespace? On the face of it, this just seems unnecessary. Just playing devil's advocate here, quite happy to be wrong.

What do you think?

**Comment by anuragthehatter** [comment]
@ctauchen heh..nw. So yea we were creating service under a project 'myproject` and exposing the same service in subsequent step under 'project1'. Just a good idea to keep same project.

**Comment by ctauchen** [comment]
> @ctauchen heh..nw. So yea we were creating service under a project 'myproject` and exposing the same service in subsequent step under 'project1'. Just a good idea to keep same project.

Ok, then it appears that the problem you pointed out in [BZ1889406](https://bugzilla.redhat.com/show_bug.cgi?id=1889406) was inadvertently fixed sometime between then and now.

I suggest we move the BZ to CLOSED --> NOTABUG without introducing extra changes to the docs.

That work for you @anuragthehatter ?

**Comment by xenolinux** [comment]
> @xenolinux @anuragthehatter
> 
> Step 1 of this procedure already puts us in the `myproject` namespace, so this appears to be a redundant addition.
> 
> Is the idea here to double up and make extra sure that `oc new-app` is working in the right namespace? On the face of it, this just seems unnecessary. Just playing devil's advocate here, quite happy to be wrong.
> 
> What do you think?

@ctauchen I totally agree. @anuragthehatter what is your call? Should I close the bug as a NOTABUG?

**Comment by anuragthehatter** [comment]
Yep sounds good to me. Looks like it was fixed midway somehow.

**Comment by xenolinux** [comment]
Closing this PR- the change seems to be the redundant information. The actual issue from the BZ has been fixed.

**Pull request closed without merging**
