### PR TITLE
OSDOCS#5365: Fixed incorrect platform parameter

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.10+

Issue:
This PR addresses [osdocs-5365](https://issues.redhat.com/browse/OSDOCS-5365).

Link to docs preview:
[Sample customized install-config.yaml file for IBM Cloud VPC](https://55978--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.html#installation-ibm-cloud-config-yaml_installing-ibm-cloud-customizations)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@MayXuQQ Pretty straight forward update. PTAL. Thank you.

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
