### PR TITLE
OSDOCS-9968: Incorporate out-of-scope comments

### PR DESCRIPTION
**Pull request by bhardesty**
This PR incorporates out-of-scope comments from https://github.com/openshift/openshift-docs/pull/72868.

Version(s):
* enterprise-4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-9968 

Link to docs preview:

QE review:
- Not required

### CODE REVIEW

**Review by jneczypor — COMMENTED** [review]
/lgtm (I'll add the "peer review done" labels, but I am still onboarding, so technically @michaelryanpeter has to give the final okay before merge). Thanks for your patience!

**Comment by michaelryanpeter** [comment]
LGTM

**Pull request merged**
