### PR TITLE
OSDOCS-5176 removing post-install encryption module from Azure assemblies

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-5176

Link to docs preview:
https://57366--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/enabling-user-managed-encryption-azure.html
No previews for the install assemblies, since it's removing a module.

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jhixson74 Hey John, are there other doc changes that need to be made for CORS-2080? I started by removing the "finalizing encryption" module from the Azure installation assemblies since I interpreted the feature as handling the storage class portion of the process. Please let me know if this is inaccurate and any other changes I need to make. Thank you

**Comment by bscott-rh** [comment]
@gpei Hello Gaoyun, can you PTAL at this PR addressing https://issues.redhat.com/browse/CORS-2080? Thank you

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
