### PR TITLE
Remove incorrect logical operator command

### PR DESCRIPTION
**Pull request by bysnupy**
Remove logical operator in the example of command because the "&&" makes errors in the command.

Version(s):

all versions

Issue:

The command example is wrong and not executed as it is. Please remove incorrect "&&" operator in it.

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@varshab1210, will you PTAL at this suggested change?

**Comment by varshab1210** [comment]
Thanks, looks good to me.

**Comment by bluengo** [comment]
That's right!
/lgtm

**Pull request merged**
