### PR TITLE
Fix namespace for SR-IOV Network Operator

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1790287

@zhaozhanqi, does this look correct?

Thanks!

### CODE REVIEW

**Comment by jboxman** [comment]
@zshi-redhat, this updates the namespace in several places. Is the change correct? Thanks!

**Comment by zshi-redhat** [comment]
> @zshi-redhat, this updates the namespace in several places. Is the change correct? Thanks!

Good catch!
I think we need the change in ` modules/nw-sriov-add-pod-runtimeconfig.adoc `
For the update in `modules/nw-sriov-installing-operator.adoc `, it may not be necessary as it's the subscription name, not actual namespace.  @zhaozhanqi do we see any issue using the `sriov-network-operator` as subscription name?

**Comment by zhaozhanqi** [comment]
> > @zshi-redhat, this updates the namespace in several places. Is the change correct? Thanks!
> 
> Good catch!
> I think we need the change in `modules/nw-sriov-add-pod-runtimeconfig.adoc`
> For the update in `modules/nw-sriov-installing-operator.adoc `, it may not be necessary as it's the subscription name, not actual namespace. @zhaozhanqi do we see any issue using the `sriov-network-operator` as subscription name?

no issue for subscription name using `sriov-network-operator`.
just update the `namespace` to `openshift-sriov-network-operator` is ok @jboxman

**Comment by jboxman** [comment]
@zshi-redhat, did I miss any? I thought I found them all.

Thanks.

**Comment by zshi-redhat** [comment]
> @zshi-redhat, did I miss any? I thought I found them all.
> 
> Thanks.

@jboxman I think we should revert the change in ` modules/nw-sriov-installing-operator.adoc ` and keep the change in `modules/nw-sriov-add-pod-runtimeconfig.adoc`

**Comment by jboxman** [comment]
@zshi-redhat, fixed!

**Pull request merged**
