### PR TITLE
document the latest changes in must gather for OpenShift Virtualization

### PR DESCRIPTION
**Pull request by nunnatsa**
Add documentation about must gather for OpenShift Virtualization, that now supports targeted gathering.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by ousleyp** [comment]
> /cc @ousleyp - clould you please review?

Hi Nahshon, thank you for providing this! I am going to check out this PR and open a new one so that I can ensure that it meets our docs standards. I'll track my progress in the doc bug. This is next on my list so I will hopefully have a PR soon. This is for the 4.8.4/4.9.1 releases, right? Or do the changes apply to 4.9.0/4.8.0?

**Comment by nunnatsa** [comment]
> This is next on my list so I will hopefully have a PR soon. This is for the 4.8.4/4.9.1 releases, right? Or do the changes apply to 4.9.0/4.8.0?

First we want it for 4.10.0, then we want to backport to 4.8.4 and 4.9.1

**Comment by ousleyp** [comment]
> > This is next on my list so I will hopefully have a PR soon. This is for the 4.8.4/4.9.1 releases, right? Or do the changes apply to 4.9.0/4.8.0?
> 
> First we want it for 4.10.0, then we want to backport to 4.8.4 and 4.9.1

@dankenigsberg Can you please clarify if we need to publish this documentation update before the 4.8.4 release? If not, please let me know when the changes will be live in the product. Thanks!

**Comment by dankenigsberg** [comment]
> > > This is next on my list so I will hopefully have a PR soon. This is for the 4.8.4/4.9.1 releases, right? Or do the changes apply to 4.9.0/4.8.0?
> > 
> > 
> > First we want it for 4.10.0, then we want to backport to 4.8.4 and 4.9.1
> 
> @dankenigsberg Can you please clarify if we need to publish this documentation update before the 4.8.4 release? If not, please let me know when the changes will be live in the product. Thanks!

I would defer this question to @nunnatsa. He knows best when his code is merged.

**Pull request closed without merging**
