### PR TITLE
OSDOCS-3181: Added the peristent storage book to OSD.

### PR DESCRIPTION
**Pull request by EricPonvelle**
Added the Persistent storage book to the the OSD topic map.

JIRA: https://issues.redhat.com/browse/OSDOCS-3181

PREVIEW: https://people.redhat.com/eponvell/020222/OSDOCS-3181_EFS_Note_OSD/storage/persistent_storage/osd-persistent-storage-aws.html

### CODE REVIEW

**Comment by 0kashi** [comment]
lgtm

**Comment by bmcelvee** [comment]
LGTM! 

One note: do you think the "Persistent storage" drop-down is needed with just the one assembly?

**Comment by 0kashi** [comment]
as it stands, no

**Pull request merged**
