### PR TITLE
Change the chroot /host step for accuracy

### PR DESCRIPTION
**Pull request by mburke5678**
Per @bscott-rh we should change the description in the `chroot /host` step for accuracy and clarity. See [comment](https://github.com/openshift/openshift-docs/pull/52548#discussion_r1015848045).

Previews
[Backing up etcd data. Step 2](https://52572--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks.html#backing-up-etcd-data_post-install-cluster-tasks)
[Enabling signature verification for Red Hat Container Registries. Step 5b](https://52572--docspreview.netlify.app/openshift-enterprise/latest/security/container_security/security-container-signature.html#containers-signature-verify-enable_security-container-signature)
[Configuring image registry repository mirroring. Step 5c](https://52572--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/preparing-for-users.html#images-configuration-registry-mirror_post-install-preparing-for-users)
[Accessing registry directly from the cluster. Step 2](https://52572--docspreview.netlify.app/openshift-enterprise/latest/registry/accessing-the-registry.html#registry-accessing-directly_accessing-the-registry)
[Rebooting a node gracefully, Step 4](https://52572--docspreview.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-gracefully_nodes-nodes-rebooting)
[Removing a local volume or local volume set, Step 3b](https://52572--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-local.html#local-removing-device_persistent-storage-local)
[Replacing an unhealthy etcd member whose etcd pod is crashlooping, Step 1b](https://52572--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member)
[Enabling feature sets at installation, Verification Step 4](https://52572--docspreview.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-install_nodes-cluster-enabling)

### CODE REVIEW

**Comment by mburke5678** [comment]
@bscott-rh Can I ask you to PTAL as you know what we are doing with this change?

**Review by bscott-rh — APPROVED** [review]
The changes and previews look good to me. Thank you very much for making this change Michael!

**Pull request merged**
