### PR TITLE
Adding an errata link to OADP 1.3.4 release notes

### PR DESCRIPTION
**Pull request by apurvabhide17**
Version(s):
OCP 4.12 → OCP 4.15

Issue:
[OADP-5269](https://issues.redhat.com/browse/OADP-5269)

Link to docs preview:

Additional information:
This PR adds an errata link to the published [OADP 1.3.4 release notes](https://docs.openshift.com/container-platform/4.15/backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.html#oadp-release-notes-1-3-4_oadp-release-notes).

### CODE REVIEW

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by apurvabhide17** [comment]
> LGTM! 👍
> 
> /remove-label peer-review-in-progress /label peer-review-done

Thanks, @kowen-rh

**Pull request merged**
