### PR TITLE
Bug 1801385, pipeline strategy is dropped in 4.3

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1801385

Preview build: http://file.rdu.redhat.com/~ahardin/Feb132020/BZ1801385-pipeline/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums_object-limits

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@mffiedler we used S2I strategy for the previous builds scale testing right?

**Comment by mffiedler** [comment]
> @mffiedler we used S2I strategy for the previous builds scale testing right?

Yes, we use S2I

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Comment by ahardin-rh** [comment]
@chaitanyaenr @mffiedler Updated. Thanks!

**Comment by mburke5678** [comment]
@ahardin-rh LGTM

**Pull request merged**
