### PR TITLE
OSDOCS-9316# 4.14 Correct vSphere in-tree migration info

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.14 only

Issue:  https://issues.redhat.com/browse/OSDOCS-9316

4.13 changes covered in this PR https://github.com/openshift/openshift-docs/pull/71083

Link to docs preview:

CSI content: https://71307--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere
In-tree content: https://71307--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-vsphere

QE review:
- [ ] QE has approved this change.

Additional information:

**PTAL**: @gcharot @gnufied

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Comment by skopacz1** [comment]
Post review comment: from a style perspective this seems fine, but I'd double check that this is a valid use case for mentioning a future version of OCP in our docs, especially if you intend to have this merged before the 4.15 GA.

**Comment by gcharot** [comment]
lgtm

**Pull request merged**
