### PR TITLE
[WIP]: DNS mgt policy

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.12 only
- [Jira](https://issues.redhat.com/browse/CFE-606)
- [Preview](url)

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@Amrita42 Here's an updated preview link - paste into comment 0 if you wish:
https://50874--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html

**Review by GroceryBoyJr — COMMENTED** [review]
/label peer-review-needed

**Comment by GroceryBoyJr** [comment]
Hey @Amrita42 LGTM. Can you get QE LGTM and please resubmit for merge review?

**Comment by Amrita42** [comment]
Closing this PR , dues to merge conflicts  https://github.com/openshift/openshift-docs/pull/51111.

**Pull request closed without merging**
