### PR TITLE
CNV-39963: Release notes: CPU hot plugging (enterprise-4.17)

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-39963

OCP 4.17
CNV 4.17

Preview:

### CODE REVIEW

**Comment by stu-gott** [comment]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by sjhala-ccs** [comment]
@sbeskin-redhat I think you are trying to link to a module that has not been merged yet, so the build will fail. I cannot merge the PR until the build passes.

**Comment by sbeskin-redhat** [comment]
@sjhala-ccs Yes, I know. I asked for a peer review of that module - https://github.com/openshift/openshift-docs/pull/83243. If you could maybe do that one first?

**Comment by sjhala-ccs** [comment]
> @sjhala-ccs Yes, I know. I've already asked for a peer review of that module - #83243. If you could maybe do that one first?

@sbeskin-redhat I am in the CNV docs meeting and Catherine suggested merging the RN PR first (without the link) because it is higher priority.

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
