### PR TITLE
removing 3.10 image references

### PR DESCRIPTION
**Pull request by kalexand-rh**

### CODE REVIEW

**Comment by bmcelvee** [comment]
@gabemontero this PR is updating the Jenkins files - PTAL

Thanks!

**Comment by gabemontero** [comment]
Hmmm ... even though the images are deprecated, they still exist ... they just are not longer supported

@bparees is my understanding correct ^^ ?

If so, I don't think we want this update

**Comment by bparees** [comment]
> @bparees is my understanding correct ^^ ?

your understanding is correct (they are deprecated, the images still exist) but i don't see a problem w/ removing the documentation from the 3.11+ version of the docs.

**Comment by kalexand-rh** [comment]
@bparees, are you ok with the proposed change, or would you like to use different language in 3.11?

**Comment by bparees** [comment]
@kalexand-rh it's fine for 3.11.

**Comment by kalexand-rh** [comment]
Thanks @bparees! Merging.

**Comment by gabemontero** [comment]
ok ... i suppose we can always add something back if we get a ton of questions, etc.

**Pull request merged**
