### PR TITLE
OSDOCS 10258: Added NCM issuer for cert-manager operator supported issuer types

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OSDOCS-10258

Link to docs preview: https://76697--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/index.html#cert-manager-issuer-types_cert-manager-operator-about

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lihongan** [comment]
@lunarwhite could you please help take a look? thanks.
cc @xingxingxia

**Review by lunarwhite — COMMENTED** [review]
LGTM. Let's also add the note under the ncm-issuer per Anjali's [comment](https://redhat-internal.slack.com/archives/C045YMPKR3M/p1719928452514689?thread_ts=1718222782.558369&cid=C045YMPKR3M) to the 1.14 RN.

**Review by Srivaralakshmi — COMMENTED** [review]
@subhtk LGTM.

The PR only has a link. But the PR title says it adds an assembly. Please clarify. TY!

**Comment by lunarwhite** [comment]
Sorry, I just notice the target version is not correct. It should be 4.14+.
@subhtk @Srivaralakshmi Could any of you help with updating? Thanks!

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
