### PR TITLE
Removed instances of virt_sandbox_use_nfs variable, not needed anymore.

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For #4746

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@pospispa Can you please check this?

**Comment by pospispa** [comment]
LGTM

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :fire:

**Comment by gaurav-nelson** [comment]
No rev history needed.

**Pull request merged**
