### PR TITLE
OSDOCS-2049: Adding note about known issue that causes intallation to…

### PR DESCRIPTION
**Pull request by skrthomas**
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-2049

Link to docs preview:
https://51373--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-nutanix-installer-provisioned.html

- [ ] QE has approved this change.

### CODE REVIEW

**Review by mjpytlak — COMMENTED** [review]
@skrthomas peer review LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by skrthomas** [comment]
@sgaoshang Can you PTAL at this for QE? Morgan Peterman gave a review in the linked Jira. If you have feedback, I will open a new PR to address it since I already merged.

**Comment by sgaoshang** [comment]
@skrthomas  lgtm, thanks.

**Pull request merged**
