### PR TITLE
Bug 2066860:  NFD Outdated spec in NFD documentation under `operand`

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by ahardin-rh — APPROVED** [review]
LGTM! Once we have QE review, we can merge. Thanks!

**Comment by ahardin-rh** [comment]
@wabouhamad PTAL. Thanks!

**Comment by ahardin-rh** [comment]
@lenahorsley Please provide QE review. Thank you!

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
