### PR TITLE
OSDOCS-4115: updates support message for 3.11

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-4115](https://issues.redhat.com//browse/OSDOCS-4115): Clarifies support message for 3.11 cluster metrics 

Version(s):
3.11

Issue:
[Jira](https://issues.redhat.com/browse/OSDOCS-4115)

Link to docs preview:
[Preview](https://joealdinger.github.io/openshift-docs/OSDOCS-4115/install_config/cluster_metrics.html)

QE review:
- [ ] QE has approved this change.

Additional information:
This PR will create a similar text block as [here](https://access.redhat.com/support/policy/updates/openshift_noncurrent) to help our customers understand the extended support on 3.11. Currently, I'm working on receiving feedback from QE and PX before making changes to the portal. 
@sferich888 @mffiedler  PTAL

### CODE REVIEW

**Comment by mffiedler** [comment]
LGTM from QE

**Comment by sferich888** [comment]
I don't think we want to document this; OCP 3.11 is in the ELP phase (meaning the whole product doesn't get software updates), and our CEE team (support) is merely providing support on existing configurations; and not providing RCA or other binary support. see [here](https://access.redhat.com/support/policy/updates/openshift_noncurrent#:~:text=continue%20receiving%20access%20to%20all%20previously%20released%20content%2C%20documentation%2C%20Kbase%20articles%2C%20as%20well%20as%20receive%20limited%20technical%20support.%20During%20this%20phase%2C%20there%20are%20no%20bug%20fixes%2C%20security%20fixes%2C%20new%20certifications%2C%20hardware%20enablement%2C%20feature%20enhancements%2C%20or%20root%20cause%20analysis%20available.).

**Comment by JoeAldinger** [comment]
@sferich888 thanks for taking a look. The request for this came in on 9.12.22. Agree with not documenting given 3.11's ELP phase plan.

**Comment by mwringe** [comment]
> I don't think we want to document this; OCP 3.11 is in the ELP phase (meaning the whole product doesn't get software updates), and our CEE team (support) is merely providing support on existing configurations; and not providing RCA or other binary support. see [here](https://access.redhat.com/support/policy/updates/openshift_noncurrent#:~:text=continue%20receiving%20access%20to%20all%20previously%20released%20content%2C%20documentation%2C%20Kbase%20articles%2C%20as%20well%20as%20receive%20limited%20technical%20support.%20During%20this%20phase%2C%20there%20are%20no%20bug%20fixes%2C%20security%20fixes%2C%20new%20certifications%2C%20hardware%20enablement%2C%20feature%20enhancements%2C%20or%20root%20cause%20analysis%20available.).

This is not entirely correct. From the top of the https://access.redhat.com/support/policy/updates/openshift_noncurrent

> Red Hat offers [OpenShift 3 to OpenShift 4 migration offerings](https://www.openshift.com/learn/topics/migration) that include the extended coverage of OpenShift 3.11 CVEs and critical bug fixes on most of the software components out to June of 2023. Please contact your local Red Hat representative for more information.

Essentially what this means is that users who are part of this migration offering essentially have maintenance support for _most_ of the components in OpenShift until June 2023.

Hawkular Metrics is not part of this extension and its support ended in June 2022.

**Comment by sferich888** [comment]
Isn't this already covered by https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-major-changes-in-40 

In short with Haukular moving to Prometheus the migration stack/tools can't migrate between components. If we update anything it should be https://docs.openshift.com/container-platform/4.11/migrating_from_ocp_3_to_4/planning-migration-3-4.html#migration-preparing-monitoring to add a consideration that says; you can't migrate Hawkular configs/metrics to Prometheus.

**Comment by JoeAldinger** [comment]
Closing this issue in favor of @sferich888's suggestions which I've made in GH #51448

**Pull request closed without merging**
