### PR TITLE
OSDOCS-5502 adding link to VMware cloud provider program doc 4.12+

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-5502

Link to docs preview:
https://58613--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned-customizations

QE review:
- [x] QE has approved this change.

Additional information:
Corresponding change with https://github.com/openshift/openshift-docs/pull/58614

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei PTAL at this change. 
CC: @julienlim

**Comment by bscott-rh** [comment]
@WenXinWei Hello, PTAL at this change

**Review by mjpytlak — COMMENTED** [review]
Hey @bscott-rh lgtm

**Pull request merged**
