### PR TITLE
OSDOCS-5540: Updating missing package in microshift

### PR DESCRIPTION
**Pull request by kelbrown20**
**For Version**: 4.12
**Issue:** [OSDOCS-5540](https://issues.redhat.com//browse/OSDOCS-5540)

**Preview:** 
[Adding MicroShift repositories to Image builder](https://59012--docspreview.netlify.app/microshift/latest/microshift_install/microshift-embed-in-rpm-ostree.html#adding-MicroShift-repos-image-builder_microshift-embed-in-rpm-ostree)

**QE review** 

- [x] QE approved

### CODE REVIEW

**Comment by kelbrown20** [comment]
@fzdarsky @dhellmann Hello! Do you guys think you could take a look at this PR when you get the chance?

**Review by dhellmann — COMMENTED** [review]
/lgtm

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by kelbrown20** [comment]
@ggiguash Hi Giga! Do you think you could take a look at this bug when you get the chance? Thank you!

**Pull request merged**
