### PR TITLE
OSDOCS-12297:Added WIF as auth type in create cluster on GCP workflow.

### PR DESCRIPTION
**Pull request by AedinC**
This PR adds information about WIF as an authentication type for GCP with CCS clusters. It also refreshes some other parts of the docs so that they are up to date with the current UI design.

Version(s):
4.17+

Issue:
[OSDOCS-12297](https://issues.redhat.com/browse/OSDOCS-12297)

Link to docs preview:
- [Creating a cluster on GCP with Red Hat Marketplace](https://83595--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-rhm-gcp-account_osd-creating-a-cluster-on-gcp)
- [Creating a cluster on GCP with CCS](https://83595--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-gcp-cluster-ccs_osd-creating-a-cluster-on-gcp)
- [Creating a cluster on GCP with Google Cloud Marketplace](https://83595--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-gcp-account_osd-creating-a-cluster-on-gcp)
- [Creating a cluster on AWS with CCS](https://83595--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-an-aws-cluster#osd-create-aws-cluster-ccs_osd-creating-a-cluster-on-aws)

Peer review:
- [x] Peer reviewer has approved this change.

SME review:
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change. 

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Comment by mletalie** [comment]
Other than suggestion about changing WIF command to match what is in UI, looks good to me!

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress

**Comment by AedinC** [comment]
@lento-sun Can you please provide a QE review for this when you get a chance? Many thanks.

**Comment by AedinC** [comment]
Hi @jloss-redhat would you be able to provide a QE review for this PR please?

**Comment by AedinC** [comment]
Thanks @jloss-redhat!

**Pull request merged**
