### PR TITLE
Removing restore cluster content from troubleshooting

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.14+

Issue:
N/A

Link to docs preview:
https://75401--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/troubleshooting_updates/gathering-data-cluster-update

Current docs are: https://docs.openshift.com/container-platform/4.14/updating/troubleshooting_updates/gathering-data-cluster-update.html

QE review:
N/A

Additional information:
PM asked to remove content for now - commented it out in the topic map

### CODE REVIEW

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

By the way, the removed content here is essentially an "additional resources" note, but written as a full assembly. I find that a little bit interesting. :slightly_smiling_face: 

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by obrown1205** [comment]
> LGTM! 👍
> 
> By the way, the removed content here is essentially an "additional resources" note, but written as a full assembly. I find that a little bit interesting. 🙂
> 
> /remove-label peer-review-in-progress /label peer-review-done

Yes! We are creating a full Troubleshooting section :)

**Pull request merged**
