### PR TITLE
BZ-2095294: Renamed IBM Cloud to IBM Cloud VPC

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
CP to 4.10 and 4.11

Issue:
This PR addresses doc bug [2095294](https://bugzilla.redhat.com/show_bug.cgi?id=2095294).

Link to docs preview:

- [Supported installation methods for different platforms](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing-preparing.html#supported-installation-methods-for-different-platforms)
- [Preparing to install on IBM Cloud VPC](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.html)
- [Configuring an IBM Cloud VPC account](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/installing-ibm-cloud-account.html)
- [Configuring IAM for IBM Cloud VPC](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/configuring-iam-ibm-cloud.html)
- [Installing a cluster on IBM Cloud VPC with customizations](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.html)
- [Installing a cluster on IBM Cloud VPC with network customizations](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.html)
- [Uninstalling a cluster on IBM Cloud VPC](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing_ibm_cloud_public/uninstalling-cluster-ibm-cloud.html)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@makentenza Should be good to go here. PTAL. Thanks!

**Comment by makentenza** [comment]
Thanks @mjpytlak, I think we need to extend the change to the text of every section you have changed. Out from the [Supported installation methods for different platforms](http://file.rdu.redhat.com/mpytlak/IBMCloudVPC/installing/installing-preparing.html#supported-installation-methods-for-different-platforms) section I still can see a lot of references for `IBM Cloud` in the text for the other sections. Can we replace `IBM Cloud` for `IBM Cloud VPC` on every reference we have to `IBM Cloud` in those sections?

**Comment by makentenza** [comment]
Thanks @mjpytlak, it LGTM!

**Review by sheriff-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
