### PR TITLE
BZ2101861: Add an example YAML file for secrets

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s):

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2101861

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/secret-yaml-example/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-stack-hub-user-infra

Additional information:

### CODE REVIEW

**Comment by mgahagan73** [comment]
Based on the work I've done in testing Azure Stack Hub installs this looks correct.

/lgtm

**Comment by abhatt-rh** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
Looks good!

**Pull request merged**
