### PR TITLE
Remove nw-creating-secured-routes

### PR DESCRIPTION
**Pull request by jboxman**
This remixes https://github.com/openshift/openshift-docs/pull/14791 as a new PR because I don't have the hang of pushing to someone else's PR yet.

@vikram-redhat, the original PR got a LGTM. About all I did here was fix the build error by flattening the TOC tree and moving a few topics around. If it's not too late, my suspicion is we can merge this.

### CODE REVIEW

**Comment by jboxman** [comment]
Looks like I spoke too soon. It doesn't build upstream.

In `networking/ingress-operator.adoc`:

```
xref:../../networking/ingress/ingress-controller-configuration.adoc#ingress-controller-configuration[Ingress
controller configuration]
```

Is broken because that file no longer exists. I don't know the history of this file, so I can't say where specifically this needs to link now.

**Comment by vikram-redhat** [comment]
@jboxman looks like you fixed the issue. OK to merge?

**Comment by jboxman** [comment]
@vikram-redhat, yes.

**Comment by vikram-redhat** [comment]
Ok this is merged. @miabbott @lihongan @bmcelvee let us know if you disagree and if anything needs changing.

**Pull request merged**
