### PR TITLE
OSDOCS-1860: Add release note entry for OpenShift SDN egress IPs

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-1860

The egress IP capability now load balances across multiple configured
egress IPs.

Preview:
- [OpenShift SDN cluster network provider egress IP feature balances across nodes](https://deploy-preview-31200--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-openshift-sdn-egress-ips-balance)

### CODE REVIEW

**Comment by jboxman** [comment]
@JacobTanenbaum, this is the release notes entry.

**Comment by jboxman** [comment]
@huiran0826 ping, thanks!

**Comment by huiran0826** [comment]
LGTM

**Comment by jboxman** [comment]
@huiran0826 thanks!

**Comment by sagidlow** [comment]
LGTM!

**Pull request merged**
