### PR TITLE
OSDOCS-11640 HCP 250 node scale

### PR DESCRIPTION
**Pull request by xJustin**
Added a new "Limits and scalability" section for ROSA HCP and made the updates for 250 nodes. 

Also added a release note for 250 and removed the release note for 180. 

Version(s):

4.16+

Issue:

https://issues.redhat.com/browse/OSDOCS-11640

Link to docs preview:

Updated note in instance types section:
https://81712--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-hcp-instance-types.html

New L&S section for ROSA HCP
https://81712--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-hcp-limits-scalability.html

New Release Note:
https://81712--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_release_notes/rosa-release-notes.html

Update in the HCP Service Definition:
https://81712--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition#rosa-sdpolicy-instance-types_rosa-hcp-service-definition

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by bhardesty — COMMENTED** [review]
LGTM!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
