### PR TITLE
Fix Jaeger log-level possible values

### PR DESCRIPTION
**Pull request by iblancasa**
Signed-off-by: Israel Blancas <iblancas@redhat.com>

Solves #36099

### CODE REVIEW

**Comment by iblancasa** [comment]
Hi! Is there anything I can do to help merging this? :)

**Comment by JStickler** [comment]
Sorry @iblancasa I don't think I noticed that you created a PR for this issue. That's my fault. =(
If I miss something like this again, ping me on Slack or pop me an e-mail, I could have had this merged ages ago.  
I just merged Tim's PR (#40730) so I'm going to close this one.

**Comment by iblancasa** [comment]
Don't worry :)

**Pull request closed without merging**
