### PR TITLE
OCPBUGS#7234: Fix links in 4.12 documentation

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-7234

Link to docs preview: https://56111--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/storage-configuration.html#post-install-deploy-OCS

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kelbrown20** [comment]
@xenolinux Before proceeding with the peer review, if this is only going into 4.12, shouldn't it be going into the 4.12 branch?

**Comment by xenolinux** [comment]
> @xenolinux Before proceeding with the peer review, if this is only going into 4.12, shouldn't it be going into the 4.12 branch?

Yeah. That makes sense. But now, is it possible to backport this PR to 4.12?

**Comment by kelbrown20** [comment]
> Yeah. That makes sense. But now, is it possible to backport this PR to 4.12?

So I spoke with som other writers and it seems like this should be going into 4.12+. Because it would be odd for 4.13 to have the 4.9 RN. So this PR can remain in main, but should be added to 4.12+

**Review by kelbrown20 — COMMENTED** [review]
Other than what I mentioned before about the 4.12+ change, this LGTM.

**Comment by xenolinux** [comment]
> > Yeah. That makes sense. But now, is it possible to backport this PR to 4.12?
> 
> So I spoke with some other writers and it seems like this should be going into 4.12+. Because it would be odd for 4.13 to have the 4.9 RN. Also close to GA, we do a 4.12 sweep so that its updated to 4.13. So for now, this PR can remain in main, but should be added to 4.12+.

Done

**Pull request merged**
