### PR TITLE
BZ2174229: RN known issue

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.11

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2174229

Link to docs preview: https://56659--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-11-release-notes.html#virt-4-11-known-issues

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sjhala-ccs** [comment]
@kbidarkar Can you please review? Thanks.

**Comment by kbidarkar** [comment]
@dshchedr From my team has reviewed this.

**Pull request merged**
