### PR TITLE
BZ1679419 change Ansible version from 2.5 to 2.6

### PR DESCRIPTION
**Pull request by jeana-redhat**
https://bugzilla.redhat.com/show_bug.cgi?id=1679419

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Hi @rlopez133 - 
I'm working on https://bugzilla.redhat.com/show_bug.cgi?id=1679419, which is asking to update the statement "Requires Ansible 2.5" to say "Requires Ansible 2.6" 
That's easy enough, but I noticed several other places on that page reference "rhel-7-server-ansible-2.5-rpms" and am thinking they should also be changed to "rhel-7-server-ansible-2.6-rpms" 
Let me know if that's right please!

**Comment by bmcelvee** [comment]
LGTM!

**Comment by rlopez133** [comment]
@jeana-redhat At the time of the publishing, that was the version we tested on. It would likely still work on Ansible 2.6 so I think that is a pretty safe change to make at this point.

**Comment by jeana-redhat** [comment]
@rlopez133 Thank you!
@bmcelvee Can you do the things I don't have permission for yet? 
- Apply labels
- Merge
- CP to 3.11

**Pull request merged**
