### PR TITLE
Document role binding restrictions

### PR DESCRIPTION
**Pull request by Miciah**
Document the RoleBindingRestriction resource and the RestrictSubjectBindings admission control plug-in.

### CODE REVIEW

**Comment by Miciah** [comment]
@ahardin-rh, sorry, I should have specified that.  This feature will be in 3.5.

**Comment by ahardin-rh** [comment]
@Miciah Thanks so much! :beers:

**Comment by php-coder** [comment]
@Miciah Is this feature only available on OpenShift Enterprise? I'm asking because I see related PRs in origin repo.

**Comment by Miciah** [comment]
@php-coder, it's in Origin since 1.4.

**Comment by php-coder** [comment]
Aha, but the docs was visible only to enterprise users because `admin_solutions/user_role_mgmt` not available to origin and other distros.

**Comment by mburke5678** [comment]
@php-coder @Miciah Is it just the RoleBindingRestriction object that is also in Origin?  Or all of the User and Role Management features?
https://docs.openshift.com/container-platform/3.6/admin_solutions/user_role_mgmt.html

**Comment by Miciah** [comment]
Scanning through it, I see nothing that is not in Origin.

**Pull request merged**
