### PR TITLE
Add an image stream authoring guide for best end user experience

### PR DESCRIPTION
**Pull request by jwforres**
Implements https://trello.com/c/LBm5DB8b

image-stream-docs-part1

continues from above...

image-stream-docs-part2

### CODE REVIEW

**Comment by jwforres** [comment]
@bparees @spadgett @sspeiche this is just the image stream half of it.  I'm not sure I love the section header.  For reference I added it to the bottom of this page: https://docs.openshift.org/latest/dev_guide/managing_images.html

**Comment by bparees** [comment]
works for me.

**Comment by ahardin-rh** [comment]
@jwforres Thanks! Is this for 3.4?

**Comment by jwforres** [comment]
The content is accurate for 3.4

**Comment by sspeiche** [comment]
fyi @luciddreamz

**Comment by jwforres** [comment]
@ahardin-rh anything holding this one up?

**Comment by ahardin-rh** [comment]
@jwforres  Whoops! Nope. I just forgot to pull the trigger. Merging now and applying minor style edits in a separate PR. Thanks for this!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/managing_images.adoc#dev-guide-managing-images[Managing Images]
|Added a new xref:../dev_guide/managing_images.adoc#writing-image-streams-for-s2i-builders[Writing Image Streams for S2I Builders] section.
%

**Pull request merged**
