### PR TITLE
RHDEVDOCS 6160 fix examples in Git SCM resolver

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.14, pipelines-docs-1.15, pipelines-docs-1.16

Issue:

RHDEVDOCS 6160

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6160

**Review by ppitonak — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Review by adellape — COMMENTED** [review]
Changes LGTM. 👍 

Technically out of scope for this PR but I'll mention since I noticed in the preview build: There is an "Example value" column in the "Supported parameters to override the Git resolver" table of the `modules/op-resolver-git-override-scm.adoc` file that has inconsistently marked-up values (some are backticked, some aren't). All the other "Example value" columns in other tables across the assembly looked good tho (all values were marked up).

**Pull request merged**
