### PR TITLE
OCPBUGS#32178: Updated the name of the YAML file

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.14+

Issue:
[OCPBUGS-32178](https://issues.redhat.com/browse/OCPBUGS-32178)

Link to docs preview:
- [Creating multiple VLANs on SR-IOV VFs](https://84796--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/multiple_networks/configuring-additional-network.html#nw-multus-create-multiple-vlans-sriov_configuring-additional-network)

Note: Fixed a typo. Name of the yaml file did not match in 4a and 4b. Updated the name of the yaml file. Not sure if this needs QE.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sr1kar99 LGTM. If the code **requires** that the YAML be named  `vlan100-additional-network-configuration.yaml`, I might get a QE review. If it is just an example name, which seems likely to me, no QE, just a typo.

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM. I'd say that in the future, it never really hurts to get a QE review on something simple like this and would recommend it just to be complete, but in this case I think it's a clear enough typo that this can merge without it. 

The next substep says to apply "the" YAML file, which clearly refers to the one users made in the previous substep.

**Pull request merged**
