### PR TITLE
Added events content to File Integrity Operator docs

### PR DESCRIPTION
**Pull request by ahardin-rh**
@mrogers950 PTAL. Thanks!

Preview build: https://deploy-preview-31768--osdocs.netlify.app/openshift-enterprise/latest/security/file_integrity_operator/file-integrity-operator-understanding.html#file-integrity-events_file-integrity-operator

### CODE REVIEW

**Review by mrogers950 — APPROVED** [review]

**Comment by ahardin-rh** [comment]
@xiaojiey PTAL. Thanks!

**Review by adellape — COMMENTED** [review]
:fire:

**Comment by ahardin-rh** [comment]
@xiaojiey PTAL. Thank you!

**Comment by xiaojiey** [comment]
@mrogers950 It doesn't work with latest build for 4.6 and 4.7. Could you help to double confirm it is merged/released or not? Thanks.
@ahardin-rh Could you please hold on until the code is released? Or our customer could not see the expected result. Thanks.

**Comment by mrogers950** [comment]
@xiaojiey @ahardin-rh  Sorry for not clarifying sooner, we should hold this for now, since we are holding the release for more fixes.

**Comment by ahardin-rh** [comment]
Just noting that we're still on hold right now and once Matt gives the approval, we can merge.

**Pull request merged**
