### PR TITLE
OSSMDOC-384: Update Product comparison table.

### PR DESCRIPTION
**Pull request by JStickler**
Correcting the components listed in the Product comparison table for OpenShift Service Mesh.

Adding a row for OpenShift distributed tracing to the comparison table.

(Per request of Product Management)

QE approval - jkandasa
Peer review - jrouth
Preview -> https://deploy-preview-35035--osdocs.netlify.app/openshift-enterprise/latest/welcome/oke_about?utm_source=github&utm_campaign=bot_dp

### CODE REVIEW

**Comment by JStickler** [comment]
@maltron

**Comment by JStickler** [comment]
@tvieira or @jkandasa  I just need a QE ack on Maltron's suggested update.

**Review by jkandasa — APPROVED** [review]

**Pull request merged**
