### PR TITLE
OCPBUGS#3812 Ingress autoscaling omit maxReplicaCount default should be 100 not 50

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-3812

Link to docs preview:
https://53683--docspreview.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-autoscaling-ingress-controller_configuring-ingress

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by cbippley** [comment]
@qiliRedHat Please take a look, thank you!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
