### PR TITLE
Moves VMW CCM TP status to the right table

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12

Issue:
N/A

Link to docs preview:
[Machine management Technology Preview features](https://55359--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#machine-management-technology-preview-features)

QE review:
IMO no QE required, docs-only update.

Additional information:
Noticed while adding 4.13 CCMs in  #55358

### CODE REVIEW

**Comment by Amrita42** [comment]
Good catch! lgtm

**Comment by jeana-redhat** [comment]
Ty @Amrita42! :rocket:

**Pull request merged**
