### PR TITLE
CNV-31199: Update HCO version to 4.12.7

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: [CNV-31199](https://issues.redhat.com/browse/CNV-31199)

Link to docs preview: [Installing - CLI](https://64359--docspreview.netlify.app/openshift-enterprise/latest/virt/install/installing-virt-cli#virt-deploying-operator-cli_installing-virt-cli)

QE review: NA
- [ ] QE has approved this change.

Additional information: To be merged on Oct. 31.

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

**Comment by abhatt-rh** [comment]
> LGTM
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

@apinnick and @xenolinux: Peer review LGTM!

**Pull request merged**
