### PR TITLE
update TSB annotation namespaces

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jim-minter ptal

**Comment by jim-minter** [comment]
lgtm

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bmcelvee** [comment]
LGTM. Is this for 3.7+?

**Comment by bparees** [comment]
yes

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Updated template service broker annotation namespaces.
%

**Pull request merged**
