### PR TITLE
Separating command and output for tkn CLI docs

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Hi @nkakkar81 - we're working on an effort to go through all our docs and do the following:

- Separate commands and output into separate code blocks (no changes were need to the tkn CLI docs for this one)
- Add `[source,terminal]` for command and output blocks

Would you mind reviewing this PR since it touches your tkn CLI docs? And just make sure the changes look okay to you. Let me know if you have any questions on this effort.

Also keep in mind going forward when you add new command/output blocks, to use `[source,terminal]`. Thanks!

**Review by jeana-redhat — COMMENTED** [review]
lgtm :)

**Comment by bergerhoffer** [comment]
FYI @Preeticp - not sure who is the right person to take a look at this. I'm going to merge as it has been reviewed by an OCP peer reviewer, but let me know if there are any updates needed if whoever is responsible for the tkn CLI docs now takes a look.

**Pull request merged**
