### PR TITLE
OSSMDOC-418 Fix OSSM federation examples

### PR DESCRIPTION
**Pull request by luksa**

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
LGTM

**Comment by JStickler** [comment]
@tsze-redhat 
@yxun

**Comment by yxun** [comment]
Hi Julie and Marko , in the modules/ossm-federation-config-smcp.adoc   I see the SMCP sample doc is using gateways labels 
`federation.maistra.io/proxy:`
Is that correct ?
In our test samples, we are using labels ` federation.maistra.io/egress-for:`   and ` federation.maistra.io/ingress-for:`

**Comment by luksa** [comment]
Looks like @rcernich changed the label name (from `proxy` to `ingress-for`/`egress-for`). However, I don't see these labels being used anywhere in the code. Anyway, I've now changed the label name in the PR.

**Pull request merged**
