### PR TITLE
Add NOTE on how to obtain the ‘htpasswd’ utility

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Fixes 1296600

@mrjoshuap
Tech-review please?

@ahardin-rh @adellape @tpoitras @bfallonf 
Peer-review please?

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
Oops, forgot to include a handy [link to the BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1296600).

**Comment by ahardin-rh** [comment]
@tnguyen-rh LGTM!  :zap:

**Comment by mrjoshuap** [comment]
Looks terrific!  👍

**Comment by tnguyen-rh** [comment]
@ahardin-rh @mrjoshuap Thanks for the quick reviews.

**Comment by tnguyen-rh** [comment]
[rev_history]
|xref:../install_config/configuring_authentication.adoc#[Configuring Authentication]
|Added a note on how to obtain the xref:../install_config/configuring_authentication.adoc#HTPasswdPasswordIdentityProvider[`htpasswd`] utility.

**Pull request merged**
