### PR TITLE
OSDOCS-8651: HAProxy version updates

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s): 4.14 and 4.15

https://github.com/openshift/openshift-docs/pull/73008 bumps the version to 2.8 for OCP 4.16.

Issue:
https://issues.redhat.com/browse/OSDOCS-8651

Link to docs preview:

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@ShudiLi Can you please verify this change for versions 4.14 and 4.15, or direct me to the correct QE contact? I'll open another PR for 4.16. Thank you!

**Review by kowen-rh — COMMENTED** [review]
The change looks good to me, but are we supposed to update each instance of an old HAProxy version number in the docs? If so, two occurrences of "HAProxy 2.2" appear in `modules/nw-ingress-converting-http-header-case.adoc` (lines 9 and 13).

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by ShudiLi** [comment]
/lgtm
@ahardin-rh done, thanks.

**Comment by bergerhoffer** [comment]
@ahardin-rh Since this PR went into main, it should have also gone to 4.16.

I see that you did a separate PR for 4.16. But the right way would be to do a PR that goes into main/4.16, and one that goes straight to 4.14/4.15 for older ones.

It looks like the changes between these files is out of sync between main and 4.16. 

Can you please open a PR to make the change on this line to 4.16? https://github.com/openshift/openshift-docs/pull/72835/files#diff-b1154f93f229feafc535c284f9662bef004a0a89ac36f5aab91e305e3b9531d0R9

This will prevent someone else from running into a conflict the next time they modify this line. Thanks!

**Comment by ahardin-rh** [comment]
@bergerhoffer Oops! Sorry about that. Yes, the fix is in https://github.com/openshift/openshift-docs/pull/72835

**Pull request merged**
