### PR TITLE
[OSDOCS#12124] Remove UPI support statement from ShiftStack compact docs

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.17

Issue: [OSDOCS-12124](https://issues.redhat.com//browse/OSDOCS-12124)

Link to docs preview: https://82453--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-three-node.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by eurijon** [comment]
Hey @maxwelldb , https://github.com/openshift/openshift-docs/blob/enterprise-4.17/modules/installation-three-node-cluster-cloud-provider.adoc has still references to UPI (step 2 and the example in the procedure section).

**Comment by maxwelldb** [comment]
@eurijon Updated. Thanks!

**Comment by eurijon** [comment]
lgtm! cc @mandre

**Review by mandre — COMMENTED** [review]
LGTM too.

**Comment by maxwelldb** [comment]
Squashed.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
