### PR TITLE
OSDOCS-5502 adding link to VMware cloud provider program doc 4.10 and 4.11

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.10, 4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-5502

Link to docs preview:
https://58614--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned-customizations

QE review:
- [X] QE has approved this change.

Additional information:
corresponding change to https://github.com/openshift/openshift-docs/pull/58613/files

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei PTAL at this change. 
CC: @julienlim

**Comment by bscott-rh** [comment]
@WenXinWei Hello, PTAL at this change

**Comment by bscott-rh** [comment]
Eng: @jcpowermac @rvanderp3 
QE: ✅ 
PM: @julienlim @racedo 
PX: @sferich888 
DPM: @kalexand-rh 

Requesting change management approval to state that OCP 4.10 and 4.11 don't support vSphere 6 or 8. Thank you

**Comment by kalexand-rh** [comment]
LGTM

**Comment by julienlim** [comment]
lgtm

**Pull request merged**
