### PR TITLE
TELCODOCS#1645: Promote workload partitioning to GA

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s): 4.14
Issue link: [TELCODOCS-1645](https://issues.redhat.com/browse/TELCODOCS-1645)

Preview link: 
https://68710--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-technology-preview

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by danmacpherson** [comment]
/lgtm

Providing Docs ACK for Change Management

**Comment by sr1kar99** [comment]
@DanielFroehlich , @brandisher 
Can you please review this PR for change management.

**Comment by DanielFroehlich** [comment]
/lgtm
Providing PM ACK for Change Management

**Comment by sr1kar99** [comment]
@CFields651 

Can you please review this PR for change management.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
