### PR TITLE
Distributed tracing and Red Hat build of OpenTelemetry 3.2 release

### PR DESCRIPTION
**Pull request by max-cx**
:warning: This PR is tied to a product release date, which is currently set to **May 29** (Wednesday).

- If the merge review gets delayed, you're welcome to ping `mleonov` on Slack.
- If you have any questions, ping `mleonov` on Slack.

:warning:  This PR aggregates cherry-picked commits from the following QE-approved and peer-reviewed PRs:

(To make it easier to merge-review this PR, I added the preview links under the corresponding commits/PRs.)

#### 1

9e91feb8f8b4bd747d0765b03ab944ae314142c1 from https://github.com/openshift/openshift-docs/pull/75505

previews:

new content (excluding some included modules that are supposed to be immutable across releases):
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_rn/distr-tracing-rn-3-2

content moved from one file to another file:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_rn/distr-tracing-rn-past-releases#distributed-tracing-rn-3-1-1

new content (excluding some included modules that are supposed to be immutable across releases):
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel_rn/otel-rn-3-2

content moved from one file to another file:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel_rn/otel-rn-past-releases#otel-rn-3-1-1

#### 2

0b95740e943f556db485dcbb50eaf13e6637a962 from https://github.com/openshift/openshift-docs/pull/75425

preview: 

new section: https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#filestorage-extension_otel-configuration-of-otel-collector

#### 3

6ab5fe6b6ea80775a84919a9197ffab5084d45ef from https://github.com/openshift/openshift-docs/pull/75761

previews:

new page intro (between the page title and the first section):
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing#installing-the-tempo-operator

two published procedures split into four:
- https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing#installing-the-tempo-operator
- https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing#installing-a-tempostack-instance

new section with two sub-sections (two procedures):
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing#installing-a-tempomonolithic-instance

#### 4

a67a539ed367e1770b7c5f5353608a6e2b2e7c2c from https://github.com/openshift/openshift-docs/pull/75067

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#otel-creating-required-RBAC-resources-automatically_otel-configuration-of-otel-collector

#### 5

61a8751a2c3d65ed40a4318b7fd68ac27d57110d from https://github.com/openshift/openshift-docs/pull/75070

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#forward-connector_otel-configuration-of-otel-collector

#### 6

afffd906767fbc144f687ab0f56dbed052c2ce13 from https://github.com/openshift/openshift-docs/pull/75487

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#oidcauth-extension_otel-configuration-of-otel-collector

#### 7

e392214b44f576b45d110b0eb5dc891f1e3f142e from https://github.com/openshift/openshift-docs/pull/75128

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#cumulativetodelta-processor_otel-configuration-of-otel-collector

#### 8

652d858e82fc4ab7dc2a877f01c9489c954150e2 from https://github.com/openshift/openshift-docs/pull/75019

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#kubernetesevents-receiver_otel-configuration-of-otel-collector

#### 9

3d79cde104abab2a0f0c6d43a9e8ab1378464ec7 from https://github.com/openshift/openshift-docs/pull/73313

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuring-metrics-for-monitoring-stack#configuration-for-receiving-metrics-from-the-monitoring-stack_otel-configuring-metrics-for-monitoring-stack

#### 10

0ab5918158c9aa3b7c9d386b87390ae3d71eda71 from https://github.com/openshift/openshift-docs/pull/75426

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#hostmetrics-receiver_otel-configuration-of-otel-collector

#### 11

e90422d585124021b72b991d0fa7698edc1566fd from https://github.com/openshift/openshift-docs/pull/75557

preview: 

new admonition:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring#distr-tracing-tempo-config-multitenancy_distr-tracing-tempo-configuring

#### 12

730681081b337c4dbd78ab7ca1acb8faebfa2d4a from https://github.com/openshift/openshift-docs/pull/76296

#### 13

e73f53729a7990698852ffbfbd9ffefec5daa237 from https://github.com/openshift/openshift-docs/pull/75335

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#k8sobjectsreceiver-receiver_otel-configuration-of-otel-collector

#### 14

007c23045a9013800611fe37c65fa67bd0add67b from https://github.com/openshift/openshift-docs/pull/75550

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#filelog-receiver_otel-configuration-of-otel-collector

#### 15

5632d673ffa9287a2e140e9b1f848f3b2a38347c from https://github.com/openshift/openshift-docs/pull/75257

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#journald-receiver_otel-configuration-of-otel-collector

#### 16

3c4a89bf6e8d4e34e7e751a775a5cfca14f83c3d from https://github.com/openshift/openshift-docs/pull/75604

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#k8scluster-receiver_otel-configuration-of-otel-collector

#### 17

f2cdfb7b2a260f523fc751aa2eb766f8250500a8 from https://github.com/openshift/openshift-docs/pull/75202

preview: 

new section:
https://76340--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-otel-collector#kubeletstats-receiver_otel-configuration-of-otel-collector

Version(s):

4.12, 4.13, 4.14, 4.15, 4.16

Issue:

https://issues.redhat.com/browse/OBSDOCS-868

Link to docs preview:

See the link(s) included under each cherry-picked commit as listed above.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by max-cx** [comment]
Adding the `peer-review-done` label because the PRs that constitute this PR have been peer-reviewed separately.

**Comment by max-cx** [comment]
Hi, team, this is the 3.2 docs release PR.

Please note that some topics were already merged as separate PRs, and other topics will be merged as separately PRs soon.

**Comment by kalexand-rh** [comment]
@max-cx, each PR that's peer reviewed needs to be merged separately. Reopen your other PRs.

**Comment by max-cx** [comment]
> @max-cx, each PR that's peer reviewed needs to be merged separately. Reopen your other PRs.

@kalexand-rh, please note that if I do it like this, then

- the merge reviewer will have to manually fix all the merge conflicts that I already resolved manually while cherry-picking these commits into a single PR (and I was the writer acquainted with all of these topics),

- the merge reviewer will have to perform 17 merges instead of one, which is a lot of extra work for the merge reviewer to repeat the work that is already completed,

- how should we handle new releases for the docs of the distributed tracing and OpenTelemetry components in the OpenShift docs repo from now on?

**Comment by max-cx** [comment]
I've reopened the individual PRs:

1. https://github.com/openshift/openshift-docs/pull/75505
2. https://github.com/openshift/openshift-docs/pull/75425
3. https://github.com/openshift/openshift-docs/pull/75761
4. https://github.com/openshift/openshift-docs/pull/75067
5. https://github.com/openshift/openshift-docs/pull/75070
6. https://github.com/openshift/openshift-docs/pull/75487
7. https://github.com/openshift/openshift-docs/pull/75128
8. https://github.com/openshift/openshift-docs/pull/75019
9. https://github.com/openshift/openshift-docs/pull/73313
10. https://github.com/openshift/openshift-docs/pull/75426
11. https://github.com/openshift/openshift-docs/pull/75557
12. https://github.com/openshift/openshift-docs/pull/76296
13. https://github.com/openshift/openshift-docs/pull/75335
14. https://github.com/openshift/openshift-docs/pull/75550
15. https://github.com/openshift/openshift-docs/pull/75257
16. https://github.com/openshift/openshift-docs/pull/75604
17. https://github.com/openshift/openshift-docs/pull/75202

**Pull request closed without merging**
