### PR TITLE
[RHACS] [4.4] ROX-23837: Removing mentions of CIS Docker v1.2.0

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.4

Issue:
https://issues.redhat.com/browse/ROX-23837

Link to docs preview:
https://81689--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/manage-compliance/managing-compliance-10.html
https://81689--ocpdocs-pr.netlify.app/openshift-acs/latest/operating/review-cluster-configuration.html

SME review:
- [ ] SME has approved this change.

Additional information:
- Merge into `rhacs-docs-4.4`

### CODE REVIEW

**Review by clickboo — APPROVED** [review]
The changes look good to me however I am not the right person to assess if these are complete. I leave that to your discretion.

**Review by xenolinux — COMMENTED** [review]
Changes LGTM

**Comment by agantony** [comment]
Closing this PR since we are ending support for 4.4 on 28 Sep, 2024.

**Pull request closed without merging**
