### PR TITLE
LDAP group sync documentation

### PR DESCRIPTION
**Pull request by tpoitras**
Bug 1268179 - [DOCS] [3.1] [Feature] Document LDAP Synchronization

initial details taken from https://github.com/openshift/openshift-docs/pull/1066

### CODE REVIEW

**Comment by tpoitras** [comment]
waiting on QE: https://bugzilla.redhat.com/show_bug.cgi?id=1268179

**Comment by tpoitras** [comment]
Updated as per feedback received by tech review: 

https://bugzilla.redhat.com/show_bug.cgi?id=1268179#c7

**Comment by tpoitras** [comment]
Updated again as per feedback received by tech review: 

https://bugzilla.redhat.com/show_bug.cgi?id=1268179#c13

**Comment by adellape** [comment]
@tpoitras Do you feel strongly about your `s/syncing/synchronizing/` (and other permutations) changes? The IBM Style Guide appears to be fine with "sync":

> sync adj
Spell as shown when used as an adjective - not “synch.”
sync v
Spell as shown when used as a verb - not “synch.”

And no specific callout in the RH Writing Style Guide on the matter. All else equal, it seems like the shorter word form would be cleaner, unless you had a particular reason for the change (plus, it aligns with the command name, tho that's just an added bonus since we usually don't use command/code spellings as a deciding factor).

Ultimately not a big deal and probably a preference thing, but thought I'd bring it up.

**Comment by tpoitras** [comment]
This was changed to long-form "synchronize" after a conversation with Bilhar, but didn't realize IBM style guide was ok with "sync", reverting my changes now. Hold on.

**Comment by tpoitras** [comment]
ok i fixed it up, checkit-checkit-checkit out, @adellape :hamster: :ok_hand:

**Comment by adellape** [comment]
:hotsprings: stuff, "sync" wording LGTM.

**Pull request merged**
