### PR TITLE
BZ1532957 - Add details about elastic and network load balancers

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1532957](https://bugzilla.redhat.com/show_bug.cgi?id=1532957)

@jhou1 PTAL

### CODE REVIEW

**Comment by jhou1** [comment]
@lihongan PTAL

**Comment by lihongan** [comment]
@sunilcio PTAL

**Comment by bobfuru** [comment]
> @bobfuru hi, I am reviewing this change as I originally opened the bug. I guess we should add below statement:
> 
> `Load balancers (Classic or Network) and listeners`
> 
> I am referring to below aws doc in which i see `Classic` & `Network` are types of `Elastic Load Balancer`.
> 
> https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html

@sunilcio Thank you for the clarification. That makes sense, especially in regards to @lihongan's comment in the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1532957#c20

I've updated the wording based on your suggestion. 

Does this look good to you?

**Comment by sunilcio** [comment]
Thanks @bobfuru , LGTM

**Comment by lihongan** [comment]
LGTM, thanks.

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL

**Comment by jboxman** [comment]
@bobfuru, LGTM.

**Comment by bobfuru** [comment]
> @bobfuru: #19072 failed to apply on top of branch "enterprise-4.1":
> 
> ```
> error: Failed to merge in the changes.
> Using index info to reconstruct a base tree...
> M	modules/installation-aws-user-infra-requirements.adoc
> M	modules/installation-cloudformation-dns.adoc
> M	modules/installation-creating-aws-dns.adoc
> Falling back to patching base and 3-way merge...
> Auto-merging modules/installation-creating-aws-dns.adoc
> Auto-merging modules/installation-cloudformation-dns.adoc
> Auto-merging modules/installation-aws-user-infra-requirements.adoc
> CONFLICT (content): Merge conflict in modules/installation-aws-user-infra-requirements.adoc
> Patch failed at 0001 BZ1532957 - Add details about classic and network load balancers
> ```

[PR 19229](https://github.com/openshift/openshift-docs/pull/19229) applies changes to `enterprise-4.1` branch since auto CP failed.

**Pull request merged**
