### PR TITLE
GH#30569 Azure private clarification

### LINKED ISSUE #30569: [enterprise-4.6] Issue in file installing/installing_azure/installing-azure-private.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_azure/installing-azure-private.html#installation-about-custom-azure-permissions_installing-azure-private

The Azure credentials that you use when you create your cluster do not need the networking permissions that are required to make VNets and core networking components within the VNet, such as subnets, routing tables, internet gateways, NAT, and VPN. You still need permission to make the application resources that the machines within the cluster require, such as ELBs, security groups, S3 buckets, and nodes.

### What needs fixing?

Change the above sentence to;

The Azure credentials that you use when you create your cluster do not need the networking permissions that are required to make VNets and core networking components within the VNet, such as subnets, routing tables, internet gateways, NAT, and VPN. You still need permission to make the application resources that the machines within the cluster require, such as Load Balancers, security groups, Storage Accounts, and nodes.

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #30569 

Preview: https://deploy-preview-30590--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-private.html#installation-about-custom-azure-permissions_installing-azure-private

### CODE REVIEW

**Comment by codyhoag** [comment]
@mgahagan73 PTAL

**Comment by mgahagan73** [comment]
I reviewed the Divsion of Permissions section paragraph and the permissions description looks good as well as the warning about clusters sharing vnets

LGTM

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
