### PR TITLE
The toleration and taint should have same  parameters in the matching example - 3x

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1756247

### CODE REVIEW

**Comment by mburke5678** [comment]
@zhouying7780
Thank you for pointing this out. Please take a look to make sure I addressed your concerns.

**Comment by mburke5678** [comment]
Change for 4.x https://github.com/openshift/openshift-docs/pull/17027

**Comment by zhouying7780** [comment]
LGTM. Thanks.

**Pull request merged**
