### PR TITLE
issue 13527 removed xPaaS image links

### LINKED ISSUE #13527: Link to outdated xpaas content
### Which section(s) is the issue in?

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/using_images/xpaas-middleware-images#using-images-xpaas-images-index 

### What needs fixing?

The docs linked in this section are not maintained and are written for OCP 3.6 or earlier. A link to this page should not be in the 3.7+ guides.

### PR DESCRIPTION
**Pull request by sheriff-rh**
fixes #13527

@jboxman would you please review? 
@vikram-redhat  I'll merge this PR from 3.7 onwards if it looks good to you.

### CODE REVIEW

**Comment by sheriff-rh** [comment]
Well, there's a lot of xrefs that need correcting. Thanks, Travis. 

I'm a little unclear on the scope of the issue; do we want to remove all mentions (and xrefs) of xPaaS?

**Comment by jboxman** [comment]
When I looked, I found these:

```
/Users/jasonb/Self/work/openshift-docs/getting_started/beyond_the_basics.adoc
  442,23: templates] as well as xref:../using_images/xpaas_images/index.adoc#using-images-xpaas-images-index[images] as

/Users/jasonb/Self/work/openshift-docs/getting_started/developers_cli.adoc
  96,23: templates] as well as xref:../using_images/xpaas_images/index.adoc#using-images-xpaas-images-index[images] as

/Users/jasonb/Self/work/openshift-docs/welcome/index.adoc
  140,3: * xref:../using_images/xpaas_images/index.adoc#using-images-xpaas-images-index[Services provided by xPaaS Middleware Images]
```

**Comment by jboxman** [comment]
My suspicion is that those references can be removed from the docs as well, but I'd also want confirmation if it was me. Based on the text, it seems reasonable that each entire line or block speaking about xPaaS images can be excised though.

**Comment by sheriff-rh** [comment]
Thanks so much @jboxman . Just wanted to make sure I wasn't crazy!

**Comment by vikram-redhat** [comment]
*sigh* This has gotten complex.  :)

@sheriff-rh just take out the links to the xPaaS sections which are causing the build to fail. While the docs haven't been updated since 3.6 because the downstream was disbanded, the upstream GitHub repo containing these images seems to be still updated as late as Dec 2018. 

cc: @aheslin

**Comment by sheriff-rh** [comment]
Squashed commits to remove xrefs. All checks have passed.

@openshift/team-documentation  peer review please!
@vikram-redhat I think this was what you were looking for.

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
