### PR TITLE
BZ1812974: Added additional prerequisite step

### PR DESCRIPTION
**Pull request by opayne1**
https://bugzilla.redhat.com/show_bug.cgi?id=1812974

4.5+

https://deploy-preview-33780--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/configuring-cli.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM! Great job, Olivia!

**Comment by opayne1** [comment]
@zhouying7780

**Comment by kalexand-rh** [comment]
merging!

**Pull request merged**
