### PR TITLE
CNV-18201: Updating version attributes for 4.12

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.12+

Issue:
[CNV-18201](https://issues.redhat.com/browse/CNV-18201)

QE review: @kbidarkar 

* [x]  QE has approved this change.

Additional information:
N/A

### CODE REVIEW

**Comment by danielclowers** [comment]
@stu-gott | @tiraboschi: Ready for review.

**Comment by bergerhoffer** [comment]
Adding the 4.13 label since this is going to main and is marked for 4.12 (can't skip 4.13 when targeting main).

**Comment by kbidarkar** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
