### PR TITLE
Updated .NET Core supported version number

### PR DESCRIPTION
**Pull request by ahardin-rh**
Updated per e-mail request from @jerboaa 

@jerboaa PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@aheslin FYI

**Comment by jerboaa** [comment]
@ahardin-rh We should also add the 1.1 image to the docker pull command:

    docker pull registry.access.redhat.com/dotnet/dotnetcore-11-rhel7

The `new-app` invocations should get updates too. For 1.0 image use:

    oc new-app registry.access.redhat.com/dotnet/dotnetcore-10-rhel7~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-1.0 --context-dir=app

and for 1.1 use:

    oc new-app registry.access.redhat.com/dotnet/dotnetcore-11-rhel7~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-1.1 --context-dir=app

**Comment by jerboaa** [comment]
cc @tmds

**Comment by ahardin-rh** [comment]
@jerboaa Thanks! Updated.

**Comment by jerboaa** [comment]
@ahardin-rh Looks good. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/s2i_images/dot_net_core.adoc#using-images-using-dot-net-core[Source-to-Image (S2I) -> .NET Core]
|Updated supported version number.
%

**Comment by omajid** [comment]
Sorry, I am very late to the conversation, but I don't think this change represents our support policy. Red Hat will ship and support both .NET Core 1.0 and 1.1 containers for the same duration. AFAIK, the both EOL on the exact same day. This matches the upstream policy adapted by Microsoft. Please see the table at https://www.microsoft.com/net/core/support. I am going to open a PR to fix this.

**Pull request merged**
