### PR TITLE
[Enterprise-4.14] OBSDOCS-845 - Logging API Reference Updates

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.14

Issue: [OBSDOCS-845](https://issues.redhat.com//browse/OBSDOCS-845)

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:
Logging Version | Supported OCP Versions Matrix
5.9 | 4.15, 4.14, 4.13
5.8 | 4.12, 4.13, 4.14, 4.15
5.7 | 4.12, 4.13, 4.14
5.6 | 4.12, 4.13

PRs by branch: 
https://github.com/openshift/openshift-docs/pull/74925
https://github.com/openshift/openshift-docs/pull/74924
https://github.com/openshift/openshift-docs/pull/74923
https://github.com/openshift/openshift-docs/pull/74922

### CODE REVIEW

**Comment by libander** [comment]
@anpingli / @kabirbhartiRH - lgtm please.

**Comment by anpingli** [comment]
Why  don't we add 5.9 Logging API reference?

**Comment by libander** [comment]
> Why don't we add 5.9 Logging API reference?

Accidentally omitted from the topic map, good catch thank you!

**Review by GroceryBoyJr — COMMENTED** [review]
For information on review for these files, look to PR https://github.com/openshift/openshift-docs/pull/74922

These files are all nearly identical to the ones found in that PR and will be re-created by automation once the desired corrections have been made. Here are the search strings used to find the errors in these files:

explicitly for the
application logs that
logs to allow
profile based on:
Custom provides
the pods are scheduled on.
events will be
the mode
buffer plugin to
Flush operations can
(Which must be

**Pull request closed without merging**
