### PR TITLE
Provided inventory parameters are not correct for Logging NFS volume config

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1780904

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli Please take a look at this small change.

**Comment by anpingli** [comment]
@mburke5678 These options won't work. I am trying to fix it.

**Comment by anpingli** [comment]
The openshift_enable_unsupported_configurations=True must be set.

**Comment by mburke5678** [comment]
@anpingli Thank you for finding the _unsupported_ parameter. That reminded me of an older issue when we added the following note. Should the note go in this PR?
````
Using NFS storage as a volume or a persistent volume, or using NAS such as Gluster, is not supported for Elasticsearch storage, as Lucene relies on file system behavior that NFS does not supply. Data corruption and other problems can occur.
````

**Comment by anpingli** [comment]
@mburke5678,  These NFS related options used by playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
It won't work when use playbook  /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml
Are all variables in this page for deploy_cluster.yml only? have we mention this?

**Comment by mburke5678** [comment]
@anpingli Which parameters are not used by ` /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml`?

**Comment by mburke5678** [comment]
@anpingli Which parameters are not used by ` /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.yml`? See:
https://github.com/openshift/openshift-docs/pull/18675/commits/6498d174ad2d928c9d9ad2b22025d084fd80ee8c

**Comment by anpingli** [comment]
@mburke5678  the parameters with prefix openshift_logging_storage_nfs_. The other should can be used /openshift-logging/config.yml

**Comment by mburke5678** [comment]
@anpingli Can you look at the [changes I made in Comment 3](6498d174ad2d928c9d9ad2b22025d084fd80ee8c) based on [your comments](https://github.com/openshift/openshift-docs/pull/18675#issuecomment-568681097) look right?

**Comment by anpingli** [comment]
@mburke5678  LGTM, Thanks

**Pull request merged**
