### PR TITLE
Adding link to forwarding logs

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1982714

Preview: https://deploy-preview-34622--osdocs.netlify.app/openshift-enterprise/latest/security/audit-log-view?utm_source=github&utm_campaign=bot_dp#viewing-audit-logs-additional-resources

### CODE REVIEW

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Comment by bergerhoffer** [comment]
@xingxingxia Can you please review?

Preview: https://deploy-preview-34622--osdocs.netlify.app/openshift-enterprise/latest/security/audit-log-view?utm_source=github&utm_campaign=bot_dp#viewing-audit-logs-additional-resources

**Comment by xingxingxia** [comment]
/lgtm
@bergerhoffer

**Pull request merged**
