### PR TITLE
explain impersonation

### PR DESCRIPTION
**Pull request by deads2k**
We added a way for users to impersonate other users.  This explains how to use it.

I'm not certain exactly where to put it.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@deads2k Thanks! Jumping in here since @adellape is on PTO this week. I think your current positioning looks fine. We can always shuffle it later if we want to. Ready to merge?

**Comment by deads2k** [comment]
@liggitt any comments on technical details?

**Comment by deads2k** [comment]
> Ready to merge?

@ahardin-rh  Got an out of band ok from @liggitt .

**Comment by ahardin-rh** [comment]
@deads2k @liggitt Thanks!

**Comment by adellape** [comment]
@deads2k Would this https://github.com/openshift/origin/pull/8824 be the beginning of this code work? The associated Trello card there mentions 3.3.

This docs PR got mislabeled I think, so we'll revert from the 3.1/3.2 docs and put it back in queue for 3.3.

**Pull request merged**
