### PR TITLE
Updates migration to OVNK docs to include Nutanix platforms

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-9477

Link to docs preview:
https://74852--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by stevsmit** [comment]
cherry-pick enterprise-4.16

**Pull request merged**
