### PR TITLE
OSDOCS-11627: Consolidate vSphere docs under existing installation section

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.12+, depending on conflicts

Issue:
https://issues.redhat.com/browse/OSDOCS-11627

Link to docs preview:
- https://80715--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/post-install-vsphere-zones-regions-configuration
- https://80715--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/vsphere-post-installation-encryption
- https://80715--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-post-installation-configuration

QE review:
- N/A, no content changes, just moving 3 topics

Additional information:
- Redirects added in request sheet

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by abrennan89** [comment]
No need to cherrypick to 4.12 since two of the sections being moved didn't exist in that version

**Pull request merged**
