### PR TITLE
RHSA-2016:24489-14 notes

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape Not sure if this is necessary or not regarding the latest async release. We can discuss when you get back. :sunglasses:

**Comment by adellape** [comment]
:+1:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../release_notes/ose_3_2_release_notes.adoc#release-notes-ose-3-2-release-notes[OpenShift Enterprise 3.2 Release Notes]
|Added release notes for xref:../release_notes/ose_3_2_release_notes.adoc#ose-3-2-1-15[RHSA-2016:1853 - OpenShift Enterprise 3.2.1.15 security and bug fix update].
%

**Comment by ahardin-rh** [comment]
Cherry-picked in https://github.com/openshift/openshift-docs/pull/2873, so dropping Next Release milestone

**Pull request merged**
