### PR TITLE
OSDOCS-3076 remove Gathering data about your cluster assembly from OSD

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-3076

Preview: https://deploy-preview-40761--osdocs.netlify.app/openshift-dedicated/latest/support/getting-support.html

### CODE REVIEW

**Comment by bmcelvee** [comment]
@okashi18 would you mind giving this PR a quick review, please? Thanks!

**Comment by bmcelvee** [comment]
Hi @yuwang-RH would you mind giving this PR a review, please? Or would you mind pointing me to someone who can review it? Thank you!

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by 0kashi** [comment]
lgtm

**Comment by bmcelvee** [comment]
Hi @yuwang-RH would you mind giving this PR a review, please? Thank you!

**Comment by bmcelvee** [comment]
@xueli181114 would you mind giving this PR a QE review, please? Thanks!

**Pull request merged**
