### PR TITLE
Changed 'CAM Operator' to 'Cluster Application Migration Operator'

### PR DESCRIPTION
**Pull request by apinnick**
For 4.2, 4.3, 4.4.

### CODE REVIEW

**Comment by apinnick** [comment]
@bergerhoffer Small PR to update the name of the Operator

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@apinnick Cherry picking to 4.3 and 4.4, but the file structure for 4.2 is too different. Can you submit a separate PR for 4.2 please? Thanks!

**Pull request merged**
