### PR TITLE
Adding ifevals for azure + gcp networking contexts

### PR DESCRIPTION
**Pull request by maxwelldb**
Somewhat experimental PR with which I hope to solve some problems with conditional statements in the installation docs. 

Relevant bugs: 

* https://bugzilla.redhat.com/show_bug.cgi?id=1771505

* https://bugzilla.redhat.com/show_bug.cgi?id=1771511

* https://bugzilla.redhat.com/show_bug.cgi?id=1771506

### CODE REVIEW

**Comment by maxwelldb** [comment]
@vikram-redhat Do you think it might be okay to merge this in and see what happens?

**Comment by codyhoag** [comment]
Another relevant bug for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1771506

**Comment by maxwelldb** [comment]
Merging this per https://bugzilla.redhat.com/show_bug.cgi?id=1771505

**Pull request merged**
