### PR TITLE
OCPBUGS#14093: Replaced broken link with correct RHEL 8 link for Netw…

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15
4.14
4.13
4.12
4.11

Issue:
[OCPBUGS-14093](https://issues.redhat.com/browse/OCPBUGS-14093)

Link to docs preview:
[Changing the MTU for the cluster network: Additional resource](https://67408--docspreview.netlify.app/openshift-enterprise/latest/networking/changing-cluster-network-mtu#changing-cluster-network-mtu-additional-resources)

QE review:
- [ ] QE approval not required.

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

**Review by abhatt-rh — APPROVED** [review]
@aravipra I see that versions listed are `4.11-4.14` but now that 4.14 is available/GA, I think this might apply to 4.15. Kindly confirm

**Comment by abhatt-rh** [comment]
> LGTM
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

LGTM!

**Pull request merged**
