### PR TITLE
CNV#34154 - Update TTO and SSP downstream Diagram

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/CNV-34154

Link to docs preview:
https://66834--docspreview.netlify.app/openshift-enterprise/latest/virt/about_virt/virt-architecture#virt-about-ssp-operator_virt-architecture

QE review:
- [x] QE has approved this change.

Additional information:
Originally part of https://github.com/openshift/openshift-docs/pull/64967 but had to be added on later in this separate PR.

### CODE REVIEW

**Review by codingben — APPROVED** [review]
LGTM

**Review by ShaunaDiaz — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
The issue is in the existing content, but this diagram should have a caption. Since it's not a regression, I think it's fine to merge but please consider adding a caption in a followup :slightly_smiling_face: 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
