### PR TITLE
Followup 4.1 Release Notes Tracker

### PR DESCRIPTION
**Pull request by sheriff-rh**
This is the Release Notes tracker for 4.1 GA. This PR will function as a WIP until we get closer to release, then will be merged. 

Build preview:
http://file.rdu.redhat.com/~antaylor/05282019/4-1-release-notes/release_notes/ocp-4-1-release-notes.html

### CODE REVIEW

**Comment by sheriff-rh** [comment]
I've included the first commit from the following bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=1708640

**Comment by huffmanca** [comment]
@sheriff-rh ,

We should include the loss of strategic merge for SCCs. This is discussed in the final comments of https://bugzilla.redhat.com/show_bug.cgi?id=1707679 .

**Comment by sheriff-rh** [comment]
Just added the following bug as well: 
https://bugzilla.redhat.com/show_bug.cgi?id=1695196

**Comment by barleyer** [comment]
Maybe add:`ServiceAccountTokenVolumeProjection` feature is not available in {product-title} 4.1. is better.This word `ServiceAccountTokenVolumeProjection` make us consistent with k8s doc.

Otherwise: /lgtm.

**Comment by sheriff-rh** [comment]
@barleyer  I have committed the changes you requested. This will be reflected in the Build Preview changes when I rebuild them later this week. Thanks!

**Comment by barleyer** [comment]
/lgtm

Thanks!

**Comment by xltian** [comment]
The following is a list of known bugs: 
> Bug 1712955 - Can't scale up ES nodes from 3 to N (N>3) in clusterlogging CRD 
Bug 1710657 - Logging limited to 1 CPU in default configuration
Bug 1712245 - User can not use shell variable in build config environment variable section when variable name includes a '.'
Bug 1685089 - User cannot remove image-registry bucket in UPI uninstallation - can delete it manually in Bucket console.
Bug 1701422 - Registry service hostname has to work with a port suffix.
Bug 1707679 - Patch/edit scc will failed, workaround is add option ‘--type=merge’ with patch command, QE has commented in the bug
Bug 1713061 - Workaround: For a machine stuck in this state, after confirming the node is actually absent from the cluster, you can add the following annotation to the machine's metadata: "machine.openshift.io/exclude-node-draining"
Bug 1713157 -AWS us-west-2 region doesn't have m4 instance type, needs to use m5 instance type
Bug 1712525 - Users can’t login console when ingress use customized certificates
Bug 1714484 - Node tuning operator creates too many secrets - must be manually
 deleted
Bug 1711402 - Cloud credential operator OOMkilled in clusters with large number of projects 
Bug 1695550 - Some opsrc can't be detected after the cluster upgrade
Bug 1707785 Horizontal Pod Autoscaler with memory metrics is not working.
Bug 1715001 oc and openshift-install version show "dirty" no matter the rc.x clients or extracted from payload
Bug 1713292 if not approve CSR in 24hous after stopping the master, need to restart the instance to recover it.
Bug 1713157 - Cannot scale default machineset us-west-2d provisioned by installer 
Bug 1710981 - m4 instances are old (2015), OpenShift should default to m5 instances for IPI and UPI installs on AWS
Bug 1711044 - The ES deployment couldn't be created if the origin one is deleted in stuck

**Comment by barleyer** [comment]
> The following is a list of known bugs:
> 
> > Bug 1712955 - Can't scale up ES nodes from 3 to N (N>3) in clusterlogging CRD
> > Bug 1710657 - Logging limited to 1 CPU in default configuration
> > Bug 1712245 - User can not use shell variable in build config environment variable section when variable name includes a '.'
> > Bug 1685089 - User cannot remove image-registry bucket in UPI uninstallation - can delete it manually in Bucket console.
> > Bug 1701422 - Registry service hostname has to work with a port suffix.
> > Bug 1707679 - Patch/edit scc will failed, workaround is add option ‘--type=merge’ with patch command, QE has commented in the bug
> > Bug 1713061 - Workaround: For a machine stuck in this state, after confirming the node is actually absent from the cluster, you can add the following annotation to the machine's metadata: "machine.openshift.io/exclude-node-draining"
> > Bug 1713157 -AWS us-west-2 region doesn't have m4 instance type, needs to use m5 instance type
> > Bug 1712525 - Users can’t login console when ingress use customized certificates
> > Bug 1714484 - Node tuning operator creates too many secrets - must be manually
> > deleted
> > Bug 1711402 - Cloud credential operator OOMkilled in clusters with large number of projects
> > Bug 1695550 - Some opsrc can't be detected after the cluster upgrade
> > Bug 1707785 Horizontal Pod Autoscaler with memory metrics is not working.
> > Bug 1715001 oc and openshift-install version show "dirty" no matter the rc.x clients or extracted from payload
> > Bug 1713292 if not approve CSR in 24hous after stopping the master, need to restart the instance to recover it.
> > Bug 1713157 - Cannot scale default machineset us-west-2d provisioned by installer
> > Bug 1710981 - m4 instances are old (2015), OpenShift should default to m5 instances for IPI and UPI installs on AWS
> > Bug 1711044 - The ES deployment couldn't be created if the origin one is deleted in stuck

All of those have something to do with  `ServiceAccountTokenVolumeProjection` feature?

**Comment by xltian** [comment]
> All of those have something to do with `ServiceAccountTokenVolumeProjection` feature?

This is just a list of outstanding known bugs, not limited to any features. This ticket is to track all issues we hope to track in release notes.

**Comment by vikram-redhat** [comment]
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1715290 needs to be noted as a known issue.

**Comment by sheriff-rh** [comment]
> Bug https://bugzilla.redhat.com/show_bug.cgi?id=1715290 needs to be noted as a known issue.

Thanks @vikram-redhat . @huffmanca mentioned earlier that https://bugzilla.redhat.com/show_bug.cgi?id=1707679 needed to be added, and I see that 1715290 is a clone. I've documented Christian's bug. Thanks!

**Comment by sheriff-rh** [comment]
@xltian  all bugs have been added to the `Known Issues` section and the build preview has been updated. PTAL: 
http://file.rdu.redhat.com/~antaylor/05282019/4-1-release-notes/release_notes/ocp-4-1-release-notes.html

**Pull request merged**
