### PR TITLE
document ansible configuration for build overrides/defaults settings

### PR DESCRIPTION
**Pull request by bparees**
documents changes introduced in https://github.com/openshift/openshift-ansible/pull/3086

### CODE REVIEW

**Comment by bparees** [comment]
@sdodson ptal

**Review by sdodson — APPROVED** [review]
Looks good

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by ganhuang** [comment]
@bparees Could we update [inventory hosts examples](https://github.com/openshift/openshift-ansible/tree/master/inventory/byo) at the same time? Thanks!

**Comment by bparees** [comment]
@ganhuang sure: https://github.com/openshift/openshift-ansible/pull/3110

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by vikram-redhat** [comment]
@bparees - why the dedicated label? This is mostly install config guide stuff, right?

**Comment by bparees** [comment]
@vikram-redhat i wasn't sure if dedicated made sense or not, i mean it's relevant to anyone who's installing/managing clusters.  In the case of dedicated(and online) that'd be the ops team, so if that makes this content inappropriate for dedicated end-users/customers, then removing the dedicated label makes sense.

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL.

**Comment by bfallonf** [comment]
I think this one is OK as is. Thanks @bparees ! I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/build_defaults_overrides.adoc#install-config-build-defaults-overrides[Configuring Global Build Defaults and Overrides]
|Added and organized information on configuring global build overrides.
%

**Comment by adellape** [comment]
> @bparees - why the dedicated label? This is mostly install config guide stuff, right?

FWIW, we do share this Install&Config topic into the Dedicated Cluster Admin guide:

https://docs.openshift.com/dedicated/admin_guide/osd_build_defaults_overrides.html

Via:

https://raw.githubusercontent.com/openshift/openshift-docs/dedicated/admin_guide/osd_build_defaults_overrides.adoc

So that customers know that this stuff _could_ be configured, and have that discussion with RH Ops if needed. But, getting into the weeds with Ansible vs direct changes in master-config.yml is probably TMI for Dedicated.

**Pull request merged**
