### PR TITLE
bug 1913821: Provide instructions for uninstalling descheduler

### PR DESCRIPTION
**Pull request by bergerhoffer**
Replaces #28508.

https://bugzilla.redhat.com/show_bug.cgi?id=1913821

Preview: https://pr-28508-update--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-uninstalling_nodes-descheduler

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra I know you reviewed @ingvagabund's other PR #28508, but this one has some additional steps and minor adjustments if you wouldn't mind doing a quick check of this one.

Preview: https://pr-28508-update--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-uninstalling_nodes-descheduler

@ingvagabund For review too please.

**Comment by ingvagabund** [comment]
LGTM
leaving the final `lgtm` flag to @kasturinarra

**Comment by kasturinarra** [comment]
Reviewed and tested the doc, looks good to me.

**Pull request merged**
