### PR TITLE
RHDEVDOCS-2755 Logging 5.6 API Ref

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.10+

Issue: [RHDEVDOCS-2755](https://issues.redhat.com//browse/RHDEVDOCS-2755)

Link to docs preview: https://56498--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging-loki.html#logging-5-6-api-ref 

QE review:
- [x] QE has approved this change.

Additional information:
Auto-generated from source: https://github.com/openshift/cluster-logging-operator/blob/release-5.6/docs/reference/operator/api.adoc 
---
Note: Current location is for preview / ease of review, this may be changed prior to merge.

### CODE REVIEW

**Review by jcantrill — APPROVED** [review]
/lgtm

**Comment by rh-tokeefe** [comment]
LGTM

**Pull request merged**
