### PR TITLE
OSDOCS-2419: clarify SRE AWS account access

### PR DESCRIPTION
**Pull request by gregsheremeta**
/cc @okashi18 @fahlmant @jonquilwilliams

### CODE REVIEW

**Comment by 0kashi** [comment]
as this was confirmed - LGTM.

**Comment by EricPonvelle** [comment]
@yuwang-RH PTAL and let me know if this is good to be merged.

**Comment by yuwang-RH** [comment]
LGTM

**Comment by mburke5678** [comment]
@gregsheremeta @EricPonvelle LGTM

**Pull request merged**
