### PR TITLE
RHDEVDOCS-3109 - [OP] Document pipelines as code

### PR DESCRIPTION
**Pull request by rishumehra**
**Purpose**:

- Adding a new assembly for Pipelines as code documentation in CI/CD Pipelines.

**PR information**:

- Aligned team: DevConsole
- For branches: OpenShift 4.9
- JIRA: [RHDEVDOCS-3109](https://issues.redhat.com/browse/RHDEVDOCS-3109)
- Direct link to doc preview: TBA
- SME and QE Review: @karthikjeeyar  
- Peer Review: @sounix000

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Instead of having the full instructions here, cant we just  have an Installation link in the section that redirects to Pipelines as code documentation https://pipelinesascode.com/docs/install ?


Note: This manual installation is only applicable in 4.9 (OSP.1.6.x) , later versions of OSP(>1.6.x) ships with the pipelines as code infrastructure.
cc: @Preeticp

**Comment by rishumehra** [comment]
> Instead of having the full instructions here, cant we just have an Installation link in the section that redirects to Pipelines as code documentation https://pipelinesascode.com/docs/install ?
> 
> Note: This manual installation is only applicable in 4.9 (OSP.1.6.x) , later versions of OSP(>1.6.x) ships with the pipelines as code infrastructure. cc: @Preeticp

@karthikjeeyar Seems like a good idea. As that will save turn-around time for all the doc fixes. Let me make some changes in the files and push a new commit soon. Thanks for sharing this idea. 👍🏼

**Comment by Preeticp** [comment]
@rishumehra this feature was DP in 4.9 and the later releases do not need these docs as per Karthik. Please see the comments in the google doc for the bootstrapping issue. cc: @TanyaShearonRH

**Comment by Preeticp** [comment]
@rishumehra we cannot link to docs like these. We need to document them in our docs. I believe @sounix000 is doing that, please check his PR and if required we can link it to those docs.

**Comment by rishumehra** [comment]
@Preeticp Sure, I'll check with @sounix000 again for his PR on PAC related docs and will try to connect the ODC side of docs in it. Thanks for the intimation on this @karthikjeeyar and @Preeticp

**Comment by rishumehra** [comment]
@Preeticp thanks for update. Yes, @shipsing can use some of this content pieces. Thanks for closing the PR.

**Pull request closed without merging**
