### PR TITLE
[SRVOCF-423]: Minor bug fix to update heading

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+
OSD 4+

Issue:
Jira: https://issues.redhat.com/browse/SRVOCF-423
Via bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2086121

Link to docs preview:
TBA

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Review by lkingland — APPROVED** [review]

**Pull request merged**
