### PR TITLE
Fix yaml indention in adding-a-custom-logo

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@dmvolod Is this change targeting both 4.3 and 4.4, or 4.4 only? As with the other PR, before we can merge, can you please squash these 2 commits down to 1 commit? Thank you!

**Comment by dmvolod** [comment]
@ahardin-rh I checked this against 4.3 and will check on 4.4 but looks like this is fix for both.
I will rebase on master when one of the gitignore adds will be merged

**Review by ahardin-rh — APPROVED** [review]
:+1:

**Pull request merged**
