### PR TITLE
[MULTIARCH2324] Add step to select product variant

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.11 and later

Issue:
- IBM Z: https://issues.redhat.com/browse/MULTIARCH-2324
- IBM Power: https://issues.redhat.com/browse/MULTIARCH-2325

Link to docs preview: http://file.str.redhat.com/~sniemann/ocp_cli_step/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli_cli-developer-commands

Additional information: The default on the customer portal is x86. Other architectures like IBM Z, IBM Power, ARM have to select the product variant first. 
QE: 
- IBM Z: Kyle Moser
- IBM Power: Julie Matthew

### CODE REVIEW

**Comment by juliemathew** [comment]
The documentation looks good for Power architecture @SNiemann15 
However, I do not see an option to choose the architecture for Z, under "Product Variant" menu. Can you please check this. thanks.

**Comment by SNiemann15** [comment]
> 

Verified with @alishaIBM that IBM Z is visible for her now too.

**Review by tmalove — COMMENTED** [review]
LGTM.

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Pull request merged**
