### PR TITLE
BZ1942951: CPMA removed (MTC 1.4.3)

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1942951

4.5+

Preview: Removed from this section: https://deploy-preview-30933--osdocs.netlify.app/openshift-enterprise/latest/migration/migrating_3_4/about-migration.html

Assembly removed from `migration/migrating_3_to_4`.

Does not require QE.

### CODE REVIEW

**Comment by apinnick** [comment]
@vikram-redhat  Can you tell me what I should do about an assembly that is being removed?

**Comment by vikram-redhat** [comment]
Hi @apinnick - is this being deprecated in a particular release or just generally? 

If it is being deprecated out of a release, then we should send change notifications and get documented acks from all stakeholders. See the manual for details.

**Comment by apinnick** [comment]
> Hi @apinnick - is this being deprecated in a particular release or just generally?
> 
> If it is being deprecated out of a release, then we should send change notifications and get documented acks from all stakeholders. See the manual for details.

Deprecated out of a release. I started the change notification process. Thanks.

**Comment by XinRedhat** [comment]
LGTM

**Pull request merged**
