### PR TITLE
add debugging ignition procedure

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.8+

Issue: part of [OSDOCS-2128](https://issues.redhat.com/browse/OSDOCS-2128)

Link to docs preview: http://file.rdu.redhat.com/jdohmann/debug-ignition/support/troubleshooting/troubleshooting-operating-system-issues.html#debugging-ignition_troubleshooting-operating-system-issues

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen could you PTAL for QE ack? This PR adds a short procedure for debugging in the case that provisioning with Ignition fails. Thanks!

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
