### PR TITLE
Fixing a few typos

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12+

Issue:
N/A

Link to docs preview:

- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image_based_upgrade/preparing_for_image_based_upgrade/cnf-image-based-upgrade-generate-seed.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image-base-install/ibi-edge-image-based-install-standalone.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/image-base-install/ibi-preparing-for-image-based-install.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-nutanix-installer-provisioned.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/prepare-pxe-assets-agent.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-adding-node-iso.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html
- https://83705--ocpdocs-pr.netlify.app/openshift-enterprise/latest/web_console/dynamic-plugin/deploy-plugin-cluster.html

QE review:
N/A

Additional information:

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Changes aren't relevant earlier than 4.14

**Pull request merged**
