### PR TITLE
Swaps Elasticsearch for Prometheus

### PR DESCRIPTION
**Pull request by stevsmit**
GH Issue: https://github.com/openshift/openshift-docs/issues/38321 and https://github.com/openshift/openshift-docs/issues/38275

For 4.6+

Preview: https://deploy-preview-38354--osdocs.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack#persistent-storage-prerequisites

Pending QE/SME: @juzhao please review :)

### CODE REVIEW

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Review by jan--f — APPROVED** [review]
/lgtm
Thanks!

**Pull request merged**
