### PR TITLE
metrics validations

### PR DESCRIPTION
**Pull request by sosiouxme**
builds on https://github.com/openshift/openshift-docs/pull/1983 adding origin-only bits; may need to rebase once that's in.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sosiouxme Is this still a work in progress? Looks like the links need to be updated to xrefs and needs rebased. Thanks!

**Comment by sosiouxme** [comment]
@ahardin-rh thanks for the bump, I forgot about this. I've rebased it. I don't think this applies to 3.2 but it does apply to both origin and OSE 3.3.

**Comment by ahardin-rh** [comment]
Thanks so much!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/cluster_metrics.adoc#install-config-cluster-metrics[Enabling Cluster Metrics]
|Added a new xref:../install_config/cluster_metrics.adoc#metrics-deployer-validations[Metrics Deployer Validations] section.
%

**Pull request merged**
