### PR TITLE
GVK incompatibility warning and workaround

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/MIG-227

CP for 4.4, 4.5

### CODE REVIEW

**Review by sergiordlr — APPROVED** [review]
Looks good to me.

Thank you.

**Comment by apinnick** [comment]
> Looks good to me.
> 
> Thank you.

@sergiordlr 

Except that we either need to make the download command more generic or to add Azure and MCG commands to the AWS command. Thanks.

**Review by sergiordlr — APPROVED** [review]
Looks good to me. Thank you!

**Review by sheriff-rh — APPROVED** [review]
This looks great! Merging.

**Pull request merged**
