### PR TITLE
Removing note that is no longer applicable

### PR DESCRIPTION
**Pull request by bergerhoffer**
Per changes in https://bugzilla.redhat.com/show_bug.cgi?id=1902059

Preview: https://deploy-preview-30005--osdocs.netlify.app/openshift-enterprise/latest/authentication/bound-service-account-tokens.html

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

**Comment by marun** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@xingxingxia Can you review the removal of this note for 4.7+? Thanks!

Preview: https://deploy-preview-30005--osdocs.netlify.app/openshift-enterprise/latest/authentication/bound-service-account-tokens.html

**Comment by xingxingxia** [comment]
LGTM

**Pull request merged**
