### PR TITLE
Updated docs with 3.9 cluster limits and metrics guidance

### PR DESCRIPTION
**Pull request by ahardin-rh**
Updated per discussion with @jeremyeder 

Preview builds:
http://file.rdu.redhat.com/~ahardin/03072018/cluster-limit-updates-3-9/scaling_performance/cluster_limits.html#scaling-performance-current-cluster-limits

http://file.rdu.redhat.com/~ahardin/03072018/cluster-limit-updates-3-9/scaling_performance/scaling_cluster_metrics.html#overview

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jeremyeder PTAL

**Comment by ahardin-rh** [comment]
@jeremyeder Also, are there any 3.9 updates needed for this page?
https://docs.openshift.com/container-platform/3.7/install_config/install/prerequisites.html#production-level-hardware-requirements
cc @adellape

**Comment by jeremyeder** [comment]
No, it does not need any updates other than adding a 3.9 column with the same numbers.

**Comment by jeremyeder** [comment]
preview build lgtm

**Comment by ahardin-rh** [comment]
@jeremyeder Excellent. Thanks!

**Pull request merged**
