### PR TITLE
Update NFS recommendation / call out

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1664034

### CODE REVIEW

**Comment by mburke5678** [comment]
@sferich888 @jcantrill 
The email thread I started on this seems to have taken on a life of its own. How do we want to proceed with this issue? 
Leave the NFS admonitions around NFS and Cassandra and Elasticsearch as they are currently and change the others?

**Comment by jcantrill** [comment]
> @sferich888 @jcantrill
> The email thread I started on this seems to have taken on a life of its own. How do we want to proceed with this issue?
> Leave the NFS admonitions around NFS and Cassandra and Elasticsearch as they are currently and change the others?
I vote leaving them in

**Comment by sferich888** [comment]
I also say leave them.

**Comment by mburke5678** [comment]
Install Config structure changed in 3.10, but the _Testing shows issues with using the NFS server_ in the 3.7 and 3.9 install files. Might need separate PR for those versions.

**Pull request merged**
