### PR TITLE
Added to logging documentation for remote syslog work

### PR DESCRIPTION
**Pull request by sqtran**
This is for the following PR.
https://github.com/openshift/origin-aggregated-logging/pull/679

### CODE REVIEW

**Comment by bfallonf** [comment]
Thanks @sqtran . This actually ties into a BZ I have for this sprint:

https://bugzilla.redhat.com/show_bug.cgi?id=1426694

So you actually answered some of the questions. I've included this information in my PR. Do you mind if I close this PR? I do have some questions that I'll ask there.

**Comment by bfallonf** [comment]
FYI, a lot of the information in this PR is from the code PR above:

https://github.com/openshift/openshift-docs/pull/5416

**Comment by bmcelvee** [comment]
Is it safe to close this PR based on https://github.com/openshift/openshift-docs/pull/5416? Thanks! 🌞

**Comment by sqtran** [comment]
Were you asking me if it was okay to close this PR?  That's cool with me.

**Comment by kalexand-rh** [comment]
Closing in favor of #5416

**Pull request closed without merging**
