### PR TITLE
CNV-20963: BitLocker recovery alternatives + Win11 TP

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.11 only (no CP)

Issue: https://issues.redhat.com/browse/CNV-20963

Link to docs preview: https://51681--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-11-release-notes.html#virt-4-11-technology-preview

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ousleyp** [comment]
Hi @djfjeff , can you please take a look at this when you get the chance? Thanks!

**Comment by djfjeff** [comment]
LGTM, the wording is clear and point the reader in the right direction.

**Comment by kbidarkar** [comment]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
