### PR TITLE
RHDEVDOCS-6119 - Adding uncommented sections in the Installing the GitOps CLI section

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.13

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6119

Link to docs preview:

https://79035--ocpdocs-pr.netlify.app/openshift-gitops/latest/installing_gitops/installing-argocd-gitops-cli.html

SME and QE review: Not applicable

Peer review: @Srivaralakshmi 

Additional information:

This PR is also related to the changes made in the following PR: https://github.com/openshift/openshift-docs/pull/78999

I'm sharing the PR link here for you to refer to.

### CODE REVIEW

**Review by Srivaralakshmi — COMMENTED** [review]
@Dhruv-Soni11 The `gitops-installing-argocd-cli-on-linux-using-rpm.adoc` file must be updated to reflect the latest updates from the file in the `gitops-docs-main` branch. See here: https://github.com/openshift/openshift-docs/blob/gitops-docs-main/modules/gitops-installing-argocd-cli-on-linux-using-rpm.adoc?plain=1


Also, please update L17 of the `common-attributes.adoc` file to `1.13` here: https://github.com/openshift/openshift-docs/blob/gitops-docs-1.13/_attributes/common-attributes.adoc

Now it is :gitops-ver: 1.1
You must change it to --> :gitops-ver: 1.13


Rest looks good. Thanks!

**Comment by Dhruv-Soni11** [comment]
> gitops-installing-argocd-cli-on-linux-using-rpm.adoc

Thanks for the detailed explanation regarding the changes @Srivaralakshmi. I have implemented the changes and added it in the PR. PTAL. Thanks.

**Review by Srivaralakshmi — COMMENTED** [review]
@Dhruv-Soni11 Thanks for the changes. LGTM.

Please add the merge review needed label.

**Pull request merged**
