### PR TITLE
PR for SRVKS-1092: Wrong code block format used in the document

### PR DESCRIPTION
**Pull request by kaldesai**
**Affected cherry-picking versions:** 

- serverless-docs 1.29
- serverless-docs 1.30
- serverless-docs 1.31
- serverless-docs 1.32

**Associated JIRA:** https://issues.redhat.com/browse/SRVKS-1092?src=confmacro

**Doc preview and description:** 

Check the following sections I have removed the unnecessary code block that was added. 

- [Configuring kube-rbac-proxy resources for Knative for Apache Kafka](https://70013--docspreview.netlify.app/openshift-serverless/latest/install/kube-rbac-proxy-kafka#serverless-configuring-kube-rbac-proxy-resources-for-kafka_kube-rbac-proxy-kafka)
- [Configuring kube-rbac-proxy resources for Serving](https://70013--docspreview.netlify.app/openshift-serverless/latest/knative-serving/kube-rbac-proxy-serving#serverless-configuring-kube-rbac-proxy-resources-for-serving_kube-rbac-proxy-serving)
- [Configuring kube-rbac-proxy resources for Eventing](https://70013--docspreview.netlify.app/openshift-serverless/latest/eventing/kube-rbac-proxy-eventing#serverless-configuring-kube-rbac-proxy-resources-for-eventing_kube-rbac-proxy-eventing)

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm

Thank you!

**Comment by mgencur** [comment]
LGTM

**Review by Srivaralakshmi — COMMENTED** [review]
@kaldesai Neat PR! LGTM. Thank you!

As I am new to the peer review squad, I would ask @bmcelvee to give my review the go-ahead. Please wait until Brandi applies the peer-review-done label.

**Comment by bmcelvee** [comment]
LGTM!

**Comment by mburke5678** [comment]
@kaldesai I got this error:  _'serverless-docs-1.32' did not match any file(s) known to git_. Is this expected?

**Comment by kaldesai** [comment]
> @kaldesai I got this error: _'serverless-docs-1.32' did not match any file(s) known to git_. Is this expected?

I think so, as I am unable to see the 'serverless-docs-1.32' branch in the repository. I will let you know about the same. Thank you so much for merging the PR for the rest all the branches. :)

**Comment by kaldesai** [comment]
@mburke5678 
The serverless-docs-1.32 branch is now created. Can you please cherry-pick this PR content for that branch? Thank you so much in advance!

**Comment by kaldesai** [comment]
@mburke5678
The serverless-docs-1.32 branch is now created. Can you please cherry-pick this PR content for that branch? Thank you!

**Pull request merged**
