### PR TITLE
Update Operator description in 3.11 release notes

### PR DESCRIPTION
**Pull request by robszumski**
- [x] update OLM description
 - [x] update SDK description
 - [x] add link to SDK readme

### CODE REVIEW

**Comment by robszumski** [comment]
@adellape I submitted a few edits to the release notes

**Review by adellape — APPROVED** [review]
:+1:

**Comment by adellape** [comment]
@robszumski Could you squash to a single commit?

**Comment by adellape** [comment]
Continuing via https://github.com/openshift/openshift-docs/pull/12286.

**Pull request closed without merging**
