### PR TITLE
[enterprise-4.7] Add Bug fix prefix on the logging release notes

### PR DESCRIPTION
**Pull request by lbscorpio**
@vikram-redhat There is one minor issue on logging release notes, minimum version that the change applies to should be 4.7 in my opinion, could you arrange someone to review them? Thanks.

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]
/lgtm

**Comment by lbscorpio** [comment]
@Preeticp Any update? Thanks.

**Comment by rolfedh** [comment]
Hi, @lbscorpio. I've asked for someone to merge this PR. Thanks.

**Comment by JStickler** [comment]
@lbscorpio If this also needs to be in the 4.8 branch, ping me and I'll cherry pick to 4.8 as well.

**Comment by lbscorpio** [comment]
@JStickler Yes, it should cherry pick to 4.8 too, thanks.

**Comment by rolfedh** [comment]
> @JStickler Yes, it should cherry pick to 4.8 too, thanks.

@JStickler There's no need to CP this to 4.8. I already have these changes in my work on the 5.1 Release Notes. I'd rather not have to perform a rebase.

**Comment by JStickler** [comment]
@rolfedh as long as the files get into 4.8, I don't care how they get there,  Thanks for the info.

**Comment by JStickler** [comment]
D'oh, I forgot that Rolf had this covered.  Not going to worry about the failed CP then.

**Comment by rolfedh** [comment]
@JStickler. Please close this PR. Thanks.

**Pull request merged**
