### PR TITLE
Playbook fails if openshift_logging_storage_volume_name is other that 'logging'.

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1858666

### CODE REVIEW

**Comment by mburke5678** [comment]
@ewolinetz PTAL

**Comment by mburke5678** [comment]
@anpingli Very small change. PTAL

**Review by anpingli — COMMENTED** [review]
LGTM

**Review by adellape — APPROVED** [review]
:+1:

**Comment by ewolinetz** [comment]
lgtm, thanks!

**Pull request merged**
