### PR TITLE
Bug 1579762 Updated docker insecure registry value for IP

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1579762

Should be straight-forward. @openshift/team-documentation PTAL.

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
A pick and a suggestion, otherwise LGTM!

**Comment by bfallonf** [comment]
This was painful because of the new install/

3.9: https://github.com/openshift/openshift-docs/pull/10797
3.7: https://github.com/openshift/openshift-docs/pull/10558
3.6: https://github.com/openshift/openshift-docs/pull/10803

**Pull request merged**
