### PR TITLE
OSDOCS#10117: Doc sweep for updating to Kubernetes 1.29

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10117

Link to docs preview:
https://75041--ocpdocs-pr.netlify.app/openshift-dedicated/latest/nodes/pods/nodes-pods-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-dedicated/latest/nodes/scheduling/nodes-scheduler-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-dedicated/latest/openshift_images/image-configuration.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/upi/installing-aws-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/upi/installing-restricted-networks-aws.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-restricted-networks-azure-user-provisioned.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-restricted-networks-ibm-power.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-kvm.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-lpar.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z-lpar.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-restricted-networks-vsphere.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-vsphere.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/installing-vsphere-network-customizations.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/adding-rhel-compute.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/more-rhel-compute.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-aws-compute-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-bare-metal-compute-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/user_infra/adding-vsphere-compute-user-infra.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-cgroups-2.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-managing.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-sno-worker-nodes.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/pods/nodes-pods-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/openshift_images/image-configuration.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-bare-metal.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-ibm-power.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-ibm-z.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/configuring-multi-arch-compute-machines/creating-multi-arch-compute-nodes-ibm-z-kvm.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/preparing-for-users.html
https://75041--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-hardware-on-nodes-running-on-vsphere.html
https://75041--ocpdocs-pr.netlify.app/openshift-rosa/latest/nodes/pods/nodes-pods-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-rosa/latest/nodes/scheduling/nodes-scheduler-node-selectors.html
https://75041--ocpdocs-pr.netlify.app/openshift-rosa/latest/openshift_images/image-configuration.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please QE review this kube bump PR in our example outputs?

Preview links are in the PR description if you need them.

**Comment by stevsmit** [comment]
This PR LGTM. I wonder why we don't use an attribute? :thinking: I feel like we've talked about that before, and that there's probably a reason I'm not remembering.

**Comment by bergerhoffer** [comment]
> This PR LGTM. I wonder why we don't use an attribute? 🤔 I feel like we've talked about that before, and that there's probably a reason I'm not remembering.

It's mostly because it's usually copy pasted from people's actual CLI terminals and added as is. I'm sure we could, and that might help with some of them, but we'd always have to do this check and make updates for new additions anyway. So honestly seemed like more work to me than just doing this quick sweep :shrug: :smile:

**Pull request merged**
