### PR TITLE
Bug 1387712 Added note recommending moving off NFS for production

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1387712

### CODE REVIEW

**Comment by bmcelvee** [comment]
@rjhowe @jhou1 PTAL

**Comment by jhou1** [comment]
@bmcelvee LGTM, thank you.

**Comment by bmcelvee** [comment]
@ahardin @adellape @mburke5678 peer review please 😺

**Comment by mburke5678** [comment]
LGTM!!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/registry/registry_known_issues.adoc#install-config-registry-known-issues[Known Issues]
|Added note recommending moving off NFS for production in the xref:../install_config/registry/registry_known_issues.adoc#known-issue-nfs-image-push-fails[Image Push Errors with Scaled Registry Using Shared NFS Volume] section.
%

**Pull request merged**
