### PR TITLE
Added the Persistent Storage Using Azure File topic

### PR DESCRIPTION
**Pull request by ahardin-rh**
This continues the work in https://github.com/openshift/openshift-docs/pull/3707

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rootfs @childsb PTAL

**Comment by rootfs** [comment]
lgtm, thanks!

**Comment by ahardin-rh** [comment]
@adellape @bmcelvee Can you please peer review? Thanks!

**Comment by ahardin-rh** [comment]
Updated the list in another file per discussion with @adellape

**Comment by bmcelvee** [comment]
LGTM! 🎆

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/persistent_storage/persistent_storage_azure_file.adoc#[install-config-persistent-storage-persistent-storage-azure-file[Configuring Persistent Storage -> Persistent Storage Using Azure File]
|New topic on provisioning your {product-title} cluster with persistent storage using Azure File.
%

**Pull request merged**
