### PR TITLE
removing content from the backup_restore topic

### PR DESCRIPTION
**Pull request by kalexand-rh**
I didn't want to delete the topic but forgot to remove all the content.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@ahardin-rh, after you merge  https://github.com/openshift/openshift-docs/pull/11156, do you want me to remove the content from that file from 3.7 on?

**Comment by vikram-redhat** [comment]
@ahardin-rh - bump

**Comment by kalexand-rh** [comment]
@ahardin-rh and I had a chat. She's still waiting for SME review on hers but is willing to reopen it against 3.6 instead of master. I'll go ahead and merge this one.

**Comment by ahardin-rh** [comment]
Discussed this with @kalexand-rh and she is going to move this forward, since my related PR is still awaiting guidance and I don't want to block this! :star2:

**Comment by kalexand-rh** [comment]
sigh

**Pull request merged**
