### PR TITLE
OCP 4.10 Netobserv updates RN

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

OCP 4.10 release notes
Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

This PR creates a small announcement of Network Observability in the big OpenShift Container Platform documentation release notes. It doesn't include specifics, but rather points to the Operator release notes.

### CODE REVIEW

**Comment by skrthomas** [comment]
@mcurry-rh Can you PTAL at this release notes addendum to the OCP release notes. Basically just creating a link to the Network Observability release notes, so customers can know that the Operator releases on a different cadence and where to find the updates.

**Review by nathan-weinberg — COMMENTED** [review]
/label qe-approved

**Comment by skrthomas** [comment]
Dude...wth. I have no idea how all these files got pulled in. I was getting some strange git errors...Gotta roll something back

**Comment by skrthomas** [comment]
Closing because somehow I pulled in like 23 other commits. I tried a hard reset but it didn't do the trick. This is the new PR: https://github.com/openshift/openshift-docs/pull/59586

**Pull request closed without merging**
