### PR TITLE
CNV-21228: new content

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.13+

Issue: [CNV-21228](https://issues.redhat.com//browse/CNV-21228)

Link to docs preview: https://58385--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-create-vms.html#virt-creating-vm-instancetype_virt-create-vms

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by RoniKishner** [comment]
QA approved

**Comment by apinnick** [comment]
@abhatt-rh 
@kalexand-rh gave me the go-ahead to merge this PR.

**Comment by abhatt-rh** [comment]
> @abhatt-rh 
> @kalexand-rh gave me the go-ahead to merge this PR.

@apinnick Thank you for letting me know.

**Pull request merged**
