### PR TITLE
OBSDOCS-1500 - Logging 5.6.26 RN - OCP 4.12 & 4.13

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.12 & 4.13

Issue: [OBSDOCS-1500](https://issues.redhat.com//browse/OBSDOCS-1500)

Link to docs preview: https://85217--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-6-release-notes.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by libander** [comment]
@anpingli - Review, please.

**Comment by anpingli** [comment]
LGTM

**Review by xperimental — APPROVED** [review]

**Review by adellape — COMMENTED** [review]
Technically should go through `peer-review-needed` first, but LGTM.

I'll try to cherrypick this `enterprise-4.13` PR to `enterprise-4.12`, though normally should be a separate PR.

**Pull request merged**
