### PR TITLE
Adding information on whitelisting and blacklisting APBs

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/yuLBrRdC/297-13-ability-to-whitelist-blacklist-apbs

### CODE REVIEW

**Comment by mdshuai** [comment]
@ahardin-rh you can ref https://github.com/openshift/ansible-service-broker/blob/master/docs/filtering_apbs.md#apb-filtering

**Comment by ahardin-rh** [comment]
@mdshuai Thanks! This is updated.

@jwmatthews @eriknelson Please tech review.

@openshift/team-documentation Please peer review

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/service_catalog/ansible_service_broker.adoc#arch-ansible-service-broker[Service Catalog Components -> Ansible Service Broker]
|Added information on xref:../architecture/service_catalog/ansible_service_broker.adoc#service-catalog-actions[whitelisting and blacklisting] Ansible Playbook Bundles (APBs).
%

**Comment by eriknelson** [comment]
@ahardin-rh Hi Ashley, the APB `white_list` and `black_list` are actually part of the broker's configuration and are not playbooks themselves. See: https://github.com/openshift/ansible-service-broker/blob/master/docs/config.md#registry-configuration

Let me know if you have any questions.

**Comment by ahardin-rh** [comment]
@eriknelson Okay, thanks! The more you know! 🌠 Given this information, do you think I should move the content out of this Actions section and, if so, where do you think it would be most appropriate? Perhaps to a new section called Filtering?

**Comment by ahardin-rh** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/7057/files

**Pull request closed without merging**
