### PR TITLE
OSDOCS-5979: Fix Broken Link to download the ROSA CLI

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-5979](https://issues.redhat.com//browse/OSDOCS-5979): Fix the broken link to download the ROSA CLI

Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-5979

Link to docs preview:
ROSA:https://65623--docspreview.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-setting-up-environment

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @0kashi - Can you please give me a quick "LGTM" for this PR? Thank you!

**Comment by 0kashi** [comment]
lgtm.

**Comment by tsze-redhat** [comment]
LGTM

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
