### PR TITLE
BZ2011514: Disconnected installation improvement

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=2011514

Clarifications for disconnected installation procedures

4.6+

Previews:
https://deploy-preview-37174--osdocs.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/installing-restricted-3-4.html

https://deploy-preview-37174--osdocs.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/installing-restricted-3-4.html#migration-installing-legacy-operator_installing-restricted-3-4

QE Approved. Ready for peer review.

### CODE REVIEW

**Review by eriknelson — CHANGES_REQUESTED** [review]
LGTM apart from the one comment, thank you @apinnick

**Review by eriknelson — APPROVED** [review]
LGTM!

**Review by bobfuru — COMMENTED** [review]
Let me know if my comments about the intro procedure descriptions need clarification. Basically, trying to think about whether it is clear enough that A) They all are required or not required, and B) They are covered in detail later in the assembly. Thanks!

**Pull request merged**
