### PR TITLE
OCPBUGS-34048:clarifies multi network NAD creation for localnet

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OCPBUGS-34048

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anuragthehatter** [comment]
LGTM

confirm with @weliang1 as well

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
