### PR TITLE
OSDOCS-1809: Add release note entry for OVN-Kubernetes migration

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-1809

Preview: https://deploy-preview-31201--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-networking

### CODE REVIEW

**Comment by jboxman** [comment]
@pliurh, I've created a release note entry for this.

**Comment by jboxman** [comment]
@huiran0826, PTAL? Thanks!

**Comment by huiran0826** [comment]
LGTM

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Pull request merged**
