### PR TITLE
CNV-20149-16809: RN Guest agent probe and virtctl ssh access

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.12

Issue: [CNV-20149](https://issues.redhat.com//browse/CNV-20149)
[CNV-16809](https://issues.redhat.com//browse/CNV-16809)

Link to docs preview:https://54202--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-12-release-notes.html#virt-4-12-technology-preview

https://54202--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-12-release-notes.html#virt-4-12-new

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by dominikholler — APPROVED** [review]
/lgtm

**Comment by geetikakay** [comment]
Lgtm

**Review by mjpytlak — COMMENTED** [review]
@sjhala-ccs peer review LGTM.

**Pull request merged**
