### PR TITLE
[OSDOCS-7765]: Remove note about default machine pools. 

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-7765
Link to docs preview:

OSD: https://64850--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition#instance-types_osd-service-definition
ROSA: https://64850--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition#rosa-sdpolicy-instance-types_rosa-service-definition
QE review: 
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Reviewers: This PR was in response to https://issues.redhat.com/browse/OSDOCS-7645. It was pointed out after that ticket was closed that there was another section in the docs that mentioned "default machine pools (And the ability to delete them).

**Review by bergerhoffer — COMMENTED** [review]
This LGTM, but per our slack convo, I think it should be run by QE before merging, since it is removing some technical information. Am happy to merge once that is gotten, thanks!

**Pull request merged**
