### PR TITLE
GH #64763 : added the missing urls for PatternFly new version

### PR DESCRIPTION
**Pull request by volantxs**
Version(s): uncertain

Issue:
https://github.com/openshift/openshift-docs/issues/64763
https://issues.redhat.com/browse/OCPBUGS-17838

Link to docs preview:
https://github.com/volantxs/openshift-docs/blob/missing_url/web_console/dynamic-plugin/overview-dynamic-plugin.adoc

QE review:
- [ ] QE has approved this change.

Additional information:

updated all the suggested changes regarding missing/old links for PatternFly in the required file

### CODE REVIEW

**Comment by volantxs** [comment]
@kalexand-rh

**Comment by kalexand-rh** [comment]
@volantxs, if you squash your commits, I'll get this merged.

**Comment by volantxs** [comment]
@kalexand-rh squashed the commits

**Review by JoeAldinger — APPROVED** [review]

**Pull request merged**
