### PR TITLE
Tweaking Vale template to add links

### PR DESCRIPTION
**Pull request by aireilly**
Updates the Vale template to suggest links for RedHat rules only. 

Uses the Vale rule filename to generate the links.

### CODE REVIEW

**Review by rohennes — COMMENTED** [review]
This is how it looks locally to me:

````
[
  {
    "body": "🤖 **[error] RedHat.TermsErrors**: [Use 'before' rather than 'prior to'.](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termserrors)",
    "path": "modules/ztp-preparing-for-the-gitops-ztp-upgrade.adoc",
    "line": 36
  }
]
````

This is the test [PR](https://github.com/openshift/openshift-docs/pull/73832).

So looks good, however, personally, I would prefer if the link was outside of the message text somehow. Often these error messages say, use X instead of Y. If that message is contained in a hyperlink it makes it harder to copy/paste the correct suggestion, and I found it harder to read when it's all hyperlink text. 

Other than that, LGTM.

**Comment by aireilly** [comment]
> This is how it looks locally to me:
> 
> ```
> [
>   {
>     "body": "🤖 **[error] RedHat.TermsErrors**: [Use 'before' rather than 'prior to'.](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termserrors)",
>     "path": "modules/ztp-preparing-for-the-gitops-ztp-upgrade.adoc",
>     "line": 36
>   }
> ]
> ```
> 
> This is the test [PR](https://github.com/openshift/openshift-docs/pull/73832).
> 
> So looks good, however, personally, I would prefer if the link was outside of the message text somehow. Often these error messages say, use X instead of Y. If that message is contained in a hyperlink it makes it harder to copy/paste the correct suggestion, and I found it harder to read when it's all hyperlink text.
> 
> Other than that, LGTM.

Fair comment. I've updated as suggested.

**Review by rohennes — APPROVED** [review]
/lgtm - great stuff, thanks Aidan!

**Pull request merged**
