### PR TITLE
Bug 1634172 fix edit router service command

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1634172

### CODE REVIEW

**Comment by bmcelvee** [comment]
@bmeng PTAL 

Thanks!

**Comment by bmeng** [comment]
LGTM. Thanks.

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL (super tiny change) :fallen_leaf:

**Comment by mburke5678** [comment]
@bmcelvee I tested this in a 3.11 deployment. I am seeing that the command should be `oc edit service <router-name>`. My set up might be wrong, I am not sure.

```oc get service
NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
logging-es              ClusterIP   172.30.150.135   <none>        9200/TCP                  6d
logging-es-cluster      ClusterIP   None             <none>        9300/TCP                  6d
logging-es-prometheus   ClusterIP   172.30.36.242    <none>        443/TCP                   6d
logging-kibana          ClusterIP   172.30.167.230   <none>        443/TCP                   6d
router-1                ClusterIP   172.30.241.180   <none>        80/TCP,443/TCP,1936/TCP   51s
[root@kvm-04-guest23 ~]# oc edit service router router-1
Error from server (NotFound): services "router" not found```

However, `oc edit service router-1` opens the YAML in a text editor.

**Comment by bmcelvee** [comment]
@mburke5678 @bmeng should it be s/oc edit service router <router-service-name>/oc edit service  <router-name>?

**Comment by mburke5678** [comment]
@bmcelvee I found that `oc edit service <router-name>` works in 3.11

**Comment by bmeng** [comment]
Oh, sorry, I did not check it clearly. It is my bad.

Yes, the command in the PR is incorrect.

It should be `oc edit service <router-name>`

**Comment by bmcelvee** [comment]
Thanks! I'm going to go ahead and merge/CP since we have consensus. :sun_with_face:

**Pull request merged**
