### PR TITLE
[OSDOCS-10000]: [addition] include FedRAMP high in security docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10000
Link to docs preview:

https://73417--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security#rosa-policy-compliance_rosa-policy-process-security

QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by stharris-rh** [comment]
lgtm

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
