### PR TITLE
MON-1841 4.9 Monitoring Release Notes

### PR DESCRIPTION
**Pull request by bburt-rh**
- Purpose: OpenShift 4.9 Release Notes for Monitoring stack
- Aligned team: Dev Tools
- For branches: 4.9 ONLY
- Jira: https://issues.redhat.com/browse/MON-1841
- Direct link to doc previews: 
- - New and enhanced features: https://deploy-preview-37264--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-monitoring.
- - Known issues: https://deploy-preview-37264--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-9-known-issues
- SME review: @simonpasquier (approved)
- QE review: @juzhao (approved) and @lihongyan1
- Peer review: @missmesss and @jc-berger (approved)
- All reviews complete. Please merge now

### CODE REVIEW

**Review by jc-berger — APPROVED** [review]
Approving all the changes I've seen in this commit. 

Please see further suggestions I have!

**Review by jc-berger — APPROVED** [review]
/lgtm

**Review by jc-berger — APPROVED** [review]
/lgtm

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
