### PR TITLE
RHDEVDOCS-5095: Adding 4.13 version to GitOps v1.8.1 RN after OCP 4.1…

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.10 and later
• **JIRA issue**: [RHDEVDOCS-5095](https://issues.redhat.com/browse/RHDEVDOCS-5095)
• **Preview page**: [Release notes for Red Hat OpenShift GitOps 1.8.1](https://58114--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/gitops-release-notes.html#gitops-release-notes-1-8-1_gitops-release-notes)
• **SME Review**: Completed by @jaideepr97
• **QE review**: Completed by @varshab1210
• **Peer-review**: Completed by @abrennan89

### CODE REVIEW

**Comment by ekristova** [comment]
Hello @jaideepr97 @varshab1210 , please review this PR. Thank you!

**Comment by varshab1210** [comment]
/lgtm 
thanks

**Review by jaideepr97 — APPROVED** [review]
LGTM thanks @ekristova

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
