### PR TITLE
[OSDOCS-9306]:spec.backupLocations.bucket.prefix in DPA is required

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-9306
Link to docs preview:

https://70081--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_backing_up_and_restoring_applications/backing-up-applications#oadp-installing-oadp-rosa-sts_rosa-backing-up-applications
image

https://70081--ocpdocs-pr.netlify.app/openshift-rosa/latest/cloud_experts_tutorials/cloud-experts-deploy-api-data-protection
image

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
SME approved.

**Comment by PrasadJoshi12** [comment]
@mletalie can we add a point under the DPA spec something like this so that users will be aware that they can change this value. 
https://docs.openshift.com/container-platform/4.14/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html#oadp-installing-dpa-1-3_installing-oadp-azure

Screenshot from 2024-01-15 17-07-40

**Comment by PrasadJoshi12** [comment]
Specify a prefix for Velero backups, for example, velero, it's required for internal image backups if you want to set it empty then set backupImages to false

**Comment by mletalie** [comment]
Hello @PrasadJoshi12,
    Just looking at your request, I believe that can be do done, but is outside the scope of this ticket. I need to get this merged as the current doc is incorrect and will return an error to the user. Are the current changes (not including your suggestion)  correct in that the user can complete the task without an error? Once determined, I can create an additional ticket to get that info added. Please let me know, thanks.

**Comment by PrasadJoshi12** [comment]
@mletalie ack, I will open a separate ticket for the above.

**Comment by PrasadJoshi12** [comment]
PR looks good to me, approved

**Review by PrasadJoshi12 — APPROVED** [review]

**Comment by mletalie** [comment]
> @mletalie ack, I will open a separate ticket for the above.

Thank you!!! I really appreciate it.

**Pull request merged**
