### PR TITLE
Remove offending style to fix spacing issue. 

### PR DESCRIPTION
**Pull request by sg00dwin**
fix for https://github.com/openshift/openshift-docs/issues/786

### CODE REVIEW

**Comment by adellape** [comment]
@sg00dwin Tried it out locally, looks beautiful! Thanks. Spot checked around other topics too and didn't see any issues with the bulleted/unordered lists.

cc @nhr for ack/merge.

**Comment by nhr** [comment]
Much obliged, @sg00dwin - thank you!

**Comment by CowboysFan** [comment]
@sg00dwin @nhr I'm not sure if this is a result of this fix, but I'm noticing excessing spacing in bulleted lists now. If you compare the following topics on the nightly versus the Enterprise builds:

https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/admin_guide/service_accounts.html#infrastructure-service-accounts

versus:

https://docs.openshift.com/enterprise/3.0/admin_guide/service_accounts.html#infrastructure-service-accounts

The Enterprise branch is correct because I think this fix hasn't made it to the OSE branch I assume? But regardless I think the current spacing is not good because it's too much, and should probably be fixed. Thanks.

**Comment by CowboysFan** [comment]
@sg00dwin @nhr I'm sorry for being late to chime in on this, but personally I think the spacing is a bit excessive now. But maybe it's just me. :)

https://docs.openshift.com/enterprise/3.0/admin_guide/service_accounts.html#infrastructure-service-accounts

versus:

https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/admin_guide/service_accounts.html#infrastructure-service-accounts

**Pull request merged**
