### PR TITLE
OSDOCS#10265: Updated the command for adding tab completion

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.14+

Issue:
[OSDOCS-10265](https://issues.redhat.com/browse/OSDOCS-10265)

Link to docs preview:
[Enabling tab completion for Zsh](https://75853--ocpdocs-pr.netlify.app/openshift-enterprise/latest/cli_reference/openshift_cli/configuring-cli.html)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@dpateriya 
Could you please review this PR?
Thanks!

**Comment by dpateriya** [comment]
@sr1kar99 
LGTM

**Comment by sr1kar99** [comment]
@aleskandro 
Could you please review this PR?
Thanks!

**Comment by aleskandro** [comment]
Hi @sr1kar99 , it looks good to me, but maybe the best QE contact here is @kasturinarra @zhouying7780

**Review by Srivaralakshmi — COMMENTED** [review]
@sr1kar99 Good work! LGTM, thank you!

**Pull request merged**
