### PR TITLE
Revert "Undo changes to daemonset RBAC docs"

### PR DESCRIPTION
**Pull request by kalexand-rh**
This reverts commit ea979387b6c874dd99a2e5442b327edf15e20fa6 per @enj on https://github.com/openshift/openshift-docs/pull/8126.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@xltian, PTAL.

**Comment by xltian** [comment]
@stuartchuan  Please review from QE side.

**Comment by stuartchuan** [comment]
LGTM.

**Pull request merged**
