### PR TITLE
OSDOCS-10726: Updating kafka replicas and cacheMaxSize in the resource considerations table

### PR DESCRIPTION
**Pull request by mpandya15**
OSDOCS#10726: Updating kafka replicas and cacheMaxSize in the resource considerations table. 

Version(s): 4.17

Issue:
[JIRA](https://issues.redhat.com/browse/OSDOCS-10726)
https://issues.redhat.com/browse/OSDOCS-10726

Link to docs preview: https://78332--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/configuring-operator.html

QE review: QE approved

### CODE REVIEW

**Review by jotak — APPROVED** [review]
thanks, LGTM!

**Review by memodi — APPROVED** [review]
/label qe-approved

we'll update our perf tests to run with these recommendations of kafkaConsumerReplicas

**Review by stleerh — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM!

**Pull request merged**
