### PR TITLE
OSDOCS-3554: Updating migration content for 4.11

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3554

Link to docs preview:
(single page) http://file.rdu.redhat.com/~ahoffer/2022/OSDOCS-3554/migrating_from_ocp_3_to_4/planning-migration-3-4.html#migration-preparing-storage

Additional information:

### CODE REVIEW

**Comment by gnufied** [comment]
lgtm

**Comment by lpettyjo** [comment]
LGTM. However, please note that the list of migrated CSI drivers will expand.

**Comment by bergerhoffer** [comment]
@ropatil010 Can you please QE review this update to the content for migrating from 3.11 -> 4.11? Thanks!

Link to docs preview:
(single page) http://file.rdu.redhat.com/~ahoffer/2022/OSDOCS-3554/migrating_from_ocp_3_to_4/planning-migration-3-4.html#migration-preparing-storage

**Comment by ropatil010** [comment]
LGTM, 
Note: Yeah from 3.11 -> 4.11 only Azure Disk, Cinder types got migrated. 
Going ahead 4.12+ other types AWS EBS, GCP etc comes in picture.

**Pull request merged**
