### PR TITLE
[RHACS] fix date for 4.3.7 release notes

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

4.3

Issue:

Link to docs preview:
[75919--ocpdocs-pr.netlify.app/openshift-acs/latest/release_notes/43-release-notes.html](https://75919--ocpdocs-pr.netlify.app/openshift-acs/latest/release_notes/43-release-notes.html)

QE review: **N/A**
- [ ] QE has approved this change.

Additional information:

Release was delayed but I forgot to update the date before merging.

### CODE REVIEW

**Review by bhardesty — COMMENTED** [review]
LGTM! Just note that the PR needs to be rebased.

**Comment by kcarmichael08** [comment]
Hi, the preview is still showing the `{mce}` variable, instead of the product?

**Pull request merged**
