### PR TITLE
Add diagrams for determining the CCO mode (4.11+)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.11+

Issue:
[OSDOCS-5914](https://issues.redhat.com//browse/OSDOCS-5914)

Link to docs preview:
- [Cloud credential configuration options and update requirements by platform type](https://60355--docspreview.netlify.app/openshift-enterprise/latest/updating/preparing-manual-creds-update.html#cco-platform-options_preparing-manual-creds-update)
- [Modes (_Table 1. CCO mode support matrix_)](https://60355--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.html#about-cloud-credential-operator-modes_about-cloud-credential-operator)
- [Determining the Cloud Credential Operator mode](https://60355--docspreview.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.html#cco-determine-mode_about-cloud-credential-operator)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by abutcher** [comment]
Looks good to me!

**Comment by jeana-redhat** [comment]
@jianping-shu PTAL

**Review by kcarmichael08 — COMMENTED** [review]
lgtm!

**Comment by kcarmichael08** [comment]
Looks like QE review still needed but peer review looks good!

**Comment by jianping-shu** [comment]
LGTM

**Pull request merged**
