### PR TITLE
Bug 1722922 - Add running entitled builds to topic map

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1722922

Added the content in https://github.com/openshift/openshift-docs/pull/13988, just didn't get it into the topic map.

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by bmcelvee** [comment]
Thanks, @adambkaplan! Since this has your approval, and it's just adding the previously reviewed content to the topic map I don't think it requires QE and peer review. 

I will open a follow-up PR to address the removal of, "Layers are always squashed in OpenShift Container Platform Branch Build.", in 4.2.

**Pull request merged**
