### PR TITLE
OCPBUGS-23427-revert: Reverted original change but placed new content in api-server part

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.15 to 4.12

Issue:
[OCPBUGS-23427](https://issues.redhat.com/browse/OCPBUGS-23427)

Link to docs preview:
* [Example load balancer configuration for user-provisioned clusters - Bare metal](https://71287--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal#installation-load-balancing-user-infra-example_installing-bare-metal)
* [Example load balancer configuration for user-provisioned clusters - Agnostic](https://71287--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic#installation-load-balancing-user-infra_installing-platform-agnostic)
* [Example load balancer configuration for user-provisioned clusters - IBM Z](https://71287--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z#installation-load-balancing-user-infra_installing-ibm-z)
* [Example load balancer configuration for user-provisioned clusters - IBM Power](https://71287--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power#installation-load-balancing-user-infra_installing-ibm-power)
* [Example load balancer configuration for user-provisioned clusters - OpenStack](https://71287--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom#installation-load-balancing-user-infra-example_installing-openstack-installer-custom)

SME review
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Timdawson264** [comment]
Thanks so much for redoing this one, Looks great.

**Review by skopacz1 — APPROVED** [review]
Looks good from my perspective! Thanks for the comprehensive preview links. 

I just want to ask, since I'm not familiar with the content: the callout descriptions below the text appear to still be accurate in light of your changes, but do they look accurate to you? I was originally a little confused about label 2 repeating in the config after 3 was introduced, but it seems like that was already the case before this PR.

**Comment by dfitzmau** [comment]
> Looks good from my perspective! Thanks for the comprehensive preview links.
> 
> I just want to ask, since I'm not familiar with the content: the callout descriptions below the text appear to still be accurate in light of your changes, but do they look accurate to you? I was originally a little confused about label 2 repeating in the config after 3 was introduced, but it seems like that was already the case before this PR.

Thanks for the review, Seb. Yes, label 2 applies to the bootstrap line entries, to which they're are now two.

**Comment by kalexand-rh** [comment]
4.11 is now [EOL](https://access.redhat.com/support/policy/updates/openshift), and we are no longer updating it. Please set the versions to 4.12+.

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM. Merging.

**Comment by sheriff-rh** [comment]
Looks like cherrypick issues from 4.12-4.14 @dfitzmau

**Pull request merged**
