### PR TITLE
Added a new Choose a Plan topic for Online

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/N4K26dAS/801-3-create-a-new-topic-on-selecting-a-plan-and-adding-resources

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jawnsy @luciddreamz PTAL

**Comment by ahardin-rh** [comment]
@jawnsy Updated.
@jlucky Any thoughts?

**Comment by ahardin-rh** [comment]
@jawnsy Updated
@luciddreamz Any thoughts?

**Comment by ahardin-rh** [comment]
@bmcelvee @adellape @mburke5678 Please peer review

**Comment by bmcelvee** [comment]
LGTM 🌟

**Comment by ahardin-rh** [comment]
@luciddreamz Any thoughts on this?

**Comment by mburke5678** [comment]
LGTM

**Comment by ahardin-rh** [comment]
No revision history needed, as this is an Online-only topic.

**Pull request merged**
