### PR TITLE
update kubelet label selector for new upstream GA label

### PR DESCRIPTION
**Pull request by rphillips**
ref: https://jira.coreos.com/browse/POD-114

/cc @mburke5678

### CODE REVIEW

**Comment by mburke5678** [comment]
@rphillips Thanks. Let me know what version to apply this PR against.

**Comment by rphillips** [comment]
@sjenning 4.2?

**Comment by sjenning** [comment]
yes, 4.2

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by vikram-redhat** [comment]
@mburke5678 can this be merged or moved along?

**Comment by mburke5678** [comment]
Closing. Changes made via https://github.com/openshift/openshift-docs/pull/15982

**Pull request closed without merging**
