### PR TITLE
BUG 1805100: Fix sriov field in documentation.

### PR DESCRIPTION
**Pull request by SchSeba**
This PR replace the "pfName" with "PfNames"

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by zshi-redhat** [comment]
There was BZ created for this issue, maybe link PR to the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1805100).

**Comment by kalexand-rh** [comment]
@huiran0826, will you PTAL?

**Comment by huiran0826** [comment]
@zhaozhanqi  PTAL, thanks!

**Pull request merged**
