### PR TITLE
OCPBUGS-45211: Image tag is updated

### PR DESCRIPTION
**Pull request by MrSanketkumar**
Version(s): 4.12, 4.13, 4.14, 4.15, 4.16, 4.17

Issue: [Jira Ticket](https://issues.redhat.com/browse/OCPBUGS-45211)

Link to docs preview: https://85623--ocpdocs-pr.netlify.app/openshift-enterprise/latest/getting_started/openshift-cli.html#getting-started-cli-connecting-database_openshift-cli

QE review:
- [x] QE has approved this change.

Additional information:

LINK : [image registry](https://quay.io/repository/centos7/mongodb-36-centos7?tab=info)

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

**Review by xenolinux — COMMENTED** [review]
Changes LGTM

Before merging; I would recommend getting QE approval on this PR. 
If you already have it on slack or ticket; please mark the box as such in the comment 0.

**Comment by skopacz1** [comment]
@zhouying7780 could you PTAL when you have a chance? Thanks!

**Review by adellape — APPROVED** [review]

**Pull request merged**
