### PR TITLE
update OpenShift cluster maximums data

### PR DESCRIPTION
**Pull request by amitsagtani97**

### CODE REVIEW

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Comment by nermina-redhat** [comment]
Adding @sjstout to review this PR. Thanks!

**Comment by paigerube14** [comment]
LGTM

**Comment by mburke5678** [comment]
@sjstout PR to [remove the cluster maximums for minor releases module](https://github.com/openshift/openshift-docs/pull/36588/files).

**Pull request merged**
