### PR TITLE
bug 1638854 adding registry variables to inventory samples

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1638854

@xltian,  will you PTAL?

### CODE REVIEW

**Comment by xltian** [comment]
@gpei will review

**Comment by jeremyeder** [comment]
Which credentials are we expected to use here?

**Comment by kalexand-rh** [comment]
Great question @jeremyeder.  @sdodson, is there anything special about the user that you specify in 
`oreg_auth_user` for `oreg_url`?

If there is, I'll update the [inventory file](https://github.com/openshift/openshift-docs/blame/master/install/configuring_inventory_file.adoc#L901 ) topic, too.

**Comment by sdodson** [comment]
I don't see the question but oreg_auth_user and oreg_auth_password supply credentials used to pull from your registry. Which by default is registry.redhat.io in 3.11 and newer. This registry requires authentication.

**Comment by kalexand-rh** [comment]
I added a description to the inventory file to describe what parameters to use for the default registry.

@gpei, will you PTAL?

**Comment by gpei** [comment]
LGTM, thanks

**Comment by kalexand-rh** [comment]
Thank you, @gpei! Merging. :)

**Pull request merged**
