### PR TITLE
Resolves bz#1734100 by adding ignition configs via vApp

### PR DESCRIPTION
**Pull request by dav1x**
This method is based on documentation via:
https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-14A25C25-A6F8-4818-9D0C-C0247C0672FA.html#GUID-14A25C25-A6F8-4818-9D0C-C0247C0672FA

Both methods have been tested. This doc change should be applied to 4.1 and 4.2.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jiajliu, ptal?

**Comment by jiajliu** [comment]
lgtm

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
