### PR TITLE
CNV-18461: Replace v1alpha1 API calls

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.13 only

**Issue:**
https://issues.redhat.com/browse/CNV-18461

**Link to docs preview:**
https://56123--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#oadp-installing-dpa_installing-oadp-aws

**QE review:**
- [x] QE has approved this change.

**Additional information:**
Same changes as https://github.com/openshift/openshift-docs/pull/52793 after it being closed and push to 4.13.

### CODE REVIEW

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Comment by GroceryBoyJr** [comment]
@danielclowers For ease of review, this preview links to your COMMENT 0 above:

https://56123--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#oadp-installing-dpa_installing-oadp-aws

It'll get reviewers to the right section of the docs, backup and restore.

**Review by GroceryBoyJr — COMMENTED** [review]
@danielclowers Only one tiny nit (the preview). Otherwise LGTM!

**Comment by danielclowers** [comment]
@GroceryBoyJr thank you! still learning the ropes, and have added the preview link to c#0

**Pull request merged**
