### PR TITLE
OSDOCS-8617: adds 4.13.21 z-stream release note MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-8617

Link to docs preview:
https://67437--docspreview.netlify.app/microshift/latest/microshift_release_notes/microshift-4-13-release-notes#microshift-4-13-21-dp

QE review:
- N/A asynch release note

### CODE REVIEW

**Comment by abhatt-rh** [comment]
Confirmed with @ShaunaDiaz that the advisories that are linked in the PR are not yet shipped; and therefore this is not ready for a merge yet. I'm removing the merge related labels for now. Kindly add them label back when you are ready for a merge. Thanks!

**Comment by ShaunaDiaz** [comment]
Advisory status is Shipped Live.

**Review by mjpytlak — APPROVED** [review]

**Pull request merged**
