### PR TITLE
[OSDOCS-4684]: Update links in the OPP user guide for Quay 3.8

### PR DESCRIPTION
**Pull request by tmalove**
**NOTE: This PR is replaced by [#53848](https://github.com/openshift/openshift-docs/pull/53848). **

[OSDOCS-4684](https://issues.redhat.com/browse/OSDOCS-4684)

Epic: [OSDOCS-4676](https://issues.redhat.com/browse/OSDOCS-4676)

Version(s):
This PR is based on the ‘opp-docs’ repo and when merged, it should be in that branch only. The OPP doc is not versioned. Add the ‘Continuous Release’ milestone to this PR.

Links to docs preview:
[relnote](https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/red_hat_quay_release_notes/index)
[installing](https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index)
[compatibility matrix](http://file.rdu.redhat.com/tlove/opp-osdocs-4684-tlove/architecture/opp-architecture.html#opp-architecture-compatibility-matrix_opp-architecture)

QE review:
- [ ] Doc release link change only. No QE is required.

### CODE REVIEW

**Comment by tmalove** [comment]
@stevsmit Will you Ack the updated links in the OPP doc for Quay 3.8? Thanks!

**Review by snarayan-redhat — COMMENTED** [review]
LGTM! FYA: There are merge conflicts to be resolved.

**Comment by GroceryBoyJr** [comment]
@tmalove squash  your commits right quick!

**Pull request closed without merging**
