### PR TITLE
[virt] DPDK cluster config: Reduce HugePages allocation

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, the example configures the DPDK-enabled nodes to have 32 1Gi huge pages in NUMA 0.

Define a minimum number of HugePages, so a single instance of the DPDK checkup could run.

A single instance of the DPDK checkup requires eight 1Gi huge pages.

Version(s):

4.14+

Issue:

Link to docs preview:

https://63246--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network#virt-configuring-cluster-dpdk_virt-attaching-vm-to-sriov-network

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by RamLavi** [comment]
> The current config allocate too much memory as huge pages, thus making the cluster sluggish.
> 
> Define a minimum number of HugePages, so a single instance of the DPDK checkup could run.

I would avoid mentioning that the cluster can become sluggish - that totally depends on the specific cluster strength.
I would focus on that fact that the dpdk-checkup now requires only 8 hugepages, and so the example should reflect that requirement.

**Comment by orelmisan** [comment]
[Change](https://github.com/openshift/openshift-docs/compare/8665016def5b09aef6ef294c69029639e24091c8..3781645482d247acabc13bc93c08ad6f433a5a24): Updated commit message in order to answer a review [comment](https://github.com/openshift/openshift-docs/pull/63246#issuecomment-1666842725).

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
