### PR TITLE
OADP-4236 updated oadp version attribute to 1.4.1

### PR DESCRIPTION
**Pull request by shdeshpa07**
## Jira 

* [OADP-4236](https://issues.redhat.com/browse/OADP-4236)

Updated oadp version attribute to 1.4.1

##  Version

* OCP 4.13 → OCP 4.17

## Preview

* [OADP-Velero-OpenShift Container Platform version relationship](https://78767--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/oadp-installing-operator#velero-oadp-version-relationship_installing-oadp-operator)

## QE Review

* [x] QE has approved this change.

### CODE REVIEW

**Comment by shdeshpa07** [comment]
@tareqalayan - Please review and approve the PR. Thanks.

**Review by lahinson — COMMENTED** [review]
LGTM

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Comment by opayne1** [comment]
@shdeshpa07 You will need to do manual cherrypicks for 4.13-4.15.

**Comment by shdeshpa07** [comment]
> @shdeshpa07 You will need to do manual cherrypicks for 4.13-4.15.

Okay. Thank you.

**Pull request merged**
