### PR TITLE
Fix userSecretName in ceph-storageclass.yaml

### PR DESCRIPTION
**Pull request by steveteuber**
Fix parameter `userSecretName` in  `ceph-storageclass.yaml`

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@tmorriso-rh?

**Comment by tmorriso-rh** [comment]
Thanks @kalexand-rh.

**Comment by tmorriso-rh** [comment]
@jhou1  @liangxia Please provide the QE review for this PR.

**Comment by jhou1** [comment]
LG

**Comment by liangxia** [comment]
LGTM

**Comment by tmorriso-rh** [comment]
@steveteuber Does this change only apply to 3.5 - 3.9 docs?

**Comment by steveteuber** [comment]
@tmorriso-rh Yes.

**Comment by tmorriso-rh** [comment]
Follow-up PRs in progress:

3.5: https://github.com/openshift/openshift-docs/pull/8806

3.6: https://github.com/openshift/openshift-docs/pull/8808

3.7 - 3.10: https://github.com/openshift/openshift-docs/pull/8809

**Comment by vikram-redhat** [comment]
@tmorriso-rh - why does this require a followup? Further, the followups do the exact same thing? 

You could just merge this change in the master and then cherrypick to the right branches?

**Comment by tmorriso-rh** [comment]
@vikram-redhat Thanks, Vikram. Good point; because this change is so small, I should have just merged this PR and used the commit ID to cherry-pick to the appropriate branches. I will continue with merging and/or cherry-picking the PRs I created, but remember this rule for future PRs.

**Comment by tmorriso-rh** [comment]
Cherry-pick PRs:

3.7: https://github.com/openshift/openshift-docs/pull/8839

3.9: https://github.com/openshift/openshift-docs/pull/8840

3.10: https://github.com/openshift/openshift-docs/pull/8841

**Comment by tmorriso-rh** [comment]
Work completed in these PRs:

https://github.com/openshift/openshift-docs/pull/8806
https://github.com/openshift/openshift-docs/pull/8808
https://github.com/openshift/openshift-docs/pull/8809
https://github.com/openshift/openshift-docs/pull/8839
https://github.com/openshift/openshift-docs/pull/8840
https://github.com/openshift/openshift-docs/pull/8841

**Pull request closed without merging**
