### PR TITLE
Fixed inconsistent header

### PR DESCRIPTION
**Pull request by apinnick**
Fixed an inconsistent header.

4.5+

Does not need QE.

Preview: https://deploy-preview-34313--osdocs.netlify.app/openshift-enterprise/latest/migration-toolkit-for-containers/premigration-checklists-mtc?utm_source=github&utm_campaign=bot_dp

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM, but if you want it in master/4.8, you'll need to get an exception.

**Comment by apinnick** [comment]
> LGTM, but if you want it in master/4.8, you'll need to get an exception.

@kalexand-rh  Not urgent. It can wait until after 4.8 release. Thanks.

**Pull request merged**
