### PR TITLE
OSDOCS-11521: removed caveat for 4.17+

### PR DESCRIPTION
**Pull request by ahardin-rh**
Version(s):
4.17+

Issue:
https://issues.redhat.com/browse/OSDOCS-11521

Link to docs preview:

QE review:
- [ x ] QE has approved this change. Change confirmed by @mffiedler

### CODE REVIEW

**Review by dfitzmau — COMMENTED** [review]
Note is removed from the following docs: 

Screenshot from 2024-07-31 16-18-39

/remove-label peer-review-in-progress

/label peer-review-done

**Review by dfitzmau — APPROVED** [review]

**Comment by ahardin-rh** [comment]
Thank you!

**Pull request merged**
