### PR TITLE
RHDEVDOCS-3202 Tracker for issue#35108 logging/cluster-logging-deploy…

### PR DESCRIPTION
**Pull request by rolfedh**
…ing.adoc

- Purpose: Fix bug to allow traffic between projects when network isolation is enabled
- Aligned team: Dev Tools
- For branches: 4.6+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3202
- Direct link to doc preview: https://deploy-preview-35429--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-deploying?utm_source=github&utm_campaign=bot_dp#cluster-logging-deploy-multitenant_cluster-logging-deploying
- SME review: @eranra 
- QE review: @anpingli 
- Peer review: @JStickler 
- All reviews complete. Please merge now.

### CODE REVIEW

**Review by eranra — APPROVED** [review]

**Review by JStickler — APPROVED** [review]
LGTM

**Comment by anpingli** [comment]
By default, the namespaces is not isolated. It is better to add condition to apply the NetworkPolicy.

For OpenShift SDN in network policy mode or OVN-Kubernetes. If namespaces isolation had been enabled.You have to perform the following actions to dis-isolated the Logging:

**Comment by anpingli** [comment]
Ignore, the  titile is 'Allowing traffic between projects when network isolation is enabled'

**Comment by anpingli** [comment]
> By default, the namespaces is not isolated. It is better to add condition to apply the NetworkPolicy.
> 
> To --->
> For OpenShift SDN in network policy mode or OVN-Kubernetes, you may need to allows ingress from the openshift-operators-redhat project to the openshift-logging project. you have to perform the following actions to dis-isolated the Logging:

Ignore my comment above.  LGTM

**Review by anpingli — APPROVED** [review]

**Comment by rolfedh** [comment]
Okay - Thanks, Anping.

On Mon, Aug 16, 2021 at 6:16 AM Anping Li ***@***.***> wrote:
>
> By default, the namespaces is not isolated. It is better to add condition to apply the NetworkPolicy.
>
> To --->
> For OpenShift SDN in network policy mode or OVN-Kubernetes, you may need to allows ingress from the openshift-operators-redhat project to the openshift-logging project. you have to perform the following actions to dis-isolated the Logging:
>
> Ignore my comment above. LGTM
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 

Rolfe Dlugy-Hegwer

Senior Technical Writer, US ENG Content Services

Red Hat North Carolina

***@***.***

M: 910-409-8007     IM: rdlugyhe

To book a meeting with me, click here.

**Pull request merged**
