### PR TITLE
BZ2109446: Remove guest overcommit section

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.6+

Issue: [BZ2109446](https://bugzilla.redhat.com/show_bug.cgi?id=2109446)

Link to docs preview: [Welcome](http://file.tlv.redhat.com/apinnick/bz2109446-remove-guest-overcommit/welcome/index.html) (Section removed from Virtualization > Virtual machines > Advanced virtual machine management)

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@fabiand @mtessun 
Please review this PR.

**Comment by fabiand** [comment]
lgtm

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
