### PR TITLE
OSDOCS-3367: Removing the customer scheduler docs in favor of the sec…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ondary scheduler docs

https://issues.redhat.com/browse/OSDOCS-3367

Preview:
* https://deploy-preview-44665--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/index.html 
(The section was removed, so no real place to link to. Just verify that the "Running a custom scheduler" assembly is no longer in the TOC).
* https://deploy-preview-44665--osdocs.netlify.app/openshift-enterprise/latest/nodes/index.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @kasturinarra This PR removes the old method for configuring a custom scheduler for the 4.11 docs. Let me know if you're okay with this.

Not much to link to in terms of a preview since it's just removing docs, but there is this section where we linked to those old docs that I updated to link to the SSO docs: https://deploy-preview-44665--osdocs.netlify.app/openshift-enterprise/latest/nodes/index.html

To verify the removal, you can look at the descheduler docs (https://deploy-preview-44665--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html) and make sure that there isn't a "Running a custom scheduler" section right above it in the table of contents.

**Comment by ingvagabund** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
