### PR TITLE
OCPBUGS#30185: Fix OSDK Operator conditions `go.mod` file

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.14+

Issue: [OCPBUGS-30185](https://issues.redhat.com/browse/OCPBUGS-30185)

Link to docs preview: [Enabling Operator conditions](https://72631--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-generating-csvs#osdk-operatorconditions_osdk-generating-csvs)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @michaelryanpeter . Changes LGTM. SME and QE reviews will be required in the event that versions are no compatible with OCP.

/remove-label merge-review-in-progress

/label peer-review-done

The peer-review checklist is not clear on the rule, but at least an SME review should be required before a peer review (just to validate the changes so that a loopback to peer review does not occur)

Screenshot from 2024-03-05 16-09-45

**Comment by michaelryanpeter** [comment]
For feature work where there would be discussion with SMEs, I agree that this is the best practice. In the case of minor bug fixes like this one, where QE has the solution in the ticket, I didn't think it would be an issue. 

Anyhow, if the team is concerned about churn, I will wait in the future. It seemed like an easy review. Sorry.

**Comment by michaelryanpeter** [comment]
@emmajiafan PTAL

**Comment by michaelryanpeter** [comment]
@dfitzmau I have thought about your comment the past couple of days and looked over the peer review checklist. 

Respectfully, I disagree with your reading of the rule. It is not my intent to be confrontational, but this isn't how I was trained for doing reviews, and it isn't something that I enforce. When I was onboarded and throughout my tenure on peer review, it has been very clear to me that QE is required before a merge (except for the typo/URL-fix type of exceptions), but writers can put work up for peer review at any time in the process.

I would be happy to discuss in greater detail with you and the rest of the team at a Monday meeting. If you want to discuss this more, feel free to put something on the agenda, and we can clear things up. Thanks!

**Comment by dfitzmau** [comment]
> @dfitzmau I have thought about your comment the past couple of days and looked over the peer review checklist.
> 
> Respectfully, I disagree with your reading of the rule. It is not my intent to be confrontational, but this isn't how I was trained for doing reviews, and it isn't something that I enforce. When I was onboarded and throughout my tenure on peer review, it has been very clear to me that QE is required before a merge (except for the typo/URL-fix type of exceptions), but writers can put work up for peer review at any time in the process.
> 
> I would be happy to discuss in greater detail with you and the rest of the team at a Monday meeting. If you want to discuss this more, feel free to put something on the agenda, and we can clear things up. Thanks!

I'm only portraying what was issued to me on a few occasions when I first joined the team. I was also asked on a few occasions to get SME approval before requesting a peer review (I will not be looking back to find these comments :smile: ). I see the logic in getting either an SME or QE review first as sometimes what is asked on a Jira might not translate to the support level of OCP or surrounding components.

I disagree on your approach for this reason as it could lead to a duplicate peer reviews should the SME review reveal some limitation. I do want to clarify that QE testing can reveal a lot as well so for really technical content I strive to get a QE review before a peer review (unless pressed for time). What harm is getting the SME ack before a peer review; at least a peer reviewer can rest assured that a technical accuracy review has been conducted. Nothing worse when a peer reviewer has invested a lot of their time to review content and SMEs chime in to request the content be overhauled. I've been at RH for 4.5 years and I've seen this happen on a few occasions.

Yes, feel free to add the item to Monday's call. I'll leave this to you as you really want this clarified.

**Pull request merged**
