### PR TITLE
[SRVCOM-2444] Remove IBM P/Z restriction

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.10 and later

Issue: https://issues.redhat.com/browse/SRVCOM-2444

Link to docs preview: https://59598--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/serverless-kafka-admin.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by nbziouec** [comment]
LGTM

**Comment by alanfx** [comment]
This change looks good to me, @SNiemann15 ! QE approvedx2!

**Review by gwynnemonahan — APPROVED** [review]
lgtm

**Pull request merged**
