### PR TITLE
OSDOCS-11825: Add worker node disk size to ROSA HCP

### PR DESCRIPTION
**Pull request by bhardesty**
This applies the changes from PR #82207 to the new ROSA HCP distro.

Version(s):
* enterprise-4.17+

Issue:
(https://issues.redhat.com/browse/OSDOCS-11825)

Link to docs preview:
Cluster administration book in ROSA HCP: https://file.rdu.redhat.com/~bhardest/osdocs-11825/rosa_cluster_admin/rosa-cluster-notifications.html

QE review:
- N/A

### CODE REVIEW

**Comment by bmcelvee** [comment]
Overall it LGTM! There's one link in the first Additional resources section, `[Customer responsibilities: Review and action cluster notifications](https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.adoc#notifications_rosa-policy-responsibility-matrix)`, that appears to be broken. Would you mind checking that? It could just be a funky preview problem.

**Comment by bhardesty** [comment]
@bmcelvee I fixed the link. It was originally conditioned out from ROSA HCP since the target doesn't (yet) exist in the ROSA HCP, but it ended up back in. I just restored the correct conditionalization.

**Comment by bmcelvee** [comment]
All set for merge @JoeAldinger:)

**Pull request merged**
