### PR TITLE
Remove WINC info that is now covered in new prereqs module

### PR DESCRIPTION
**Pull request by codyhoag**
Follow-up to #33599

Content is now covered in new [prereqs](https://github.com/openshift/openshift-docs/blob/main/modules/wmco-prerequisites.adoc) module.

Preview: https://deploy-preview-37058--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/understanding-windows-container-workloads?utm_source=github&utm_campaign=bot_dp

### CODE REVIEW

**Comment by codyhoag** [comment]
@rrasouli can you verify? Just some repeated content that is no longer necessary (and is stale for WMCO 3.1.0). Thanks!

**Comment by rrasouli** [comment]
I was wondering perhaps adding [prereqs](https://github.com/openshift/openshift-docs/blob/main/modules/wmco-prerequisites.adoc) link for supported workloads

**Comment by codyhoag** [comment]
@rrasouli the prereqs module is included just a few lines after the text removal on line 17 [here](https://github.com/openshift/openshift-docs/pull/37058/files#diff-16e1685ec7f8338086de81871522248b6a9ee95166e545a94c94a2afdd075f8cR17). It is the first section listed after the intro ([preview](https://deploy-preview-37058--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/understanding-windows-container-workloads#wmco-prerequisites_understanding-windows-container-workloads)). Do you think that will suffice?

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
