### PR TITLE
RHDEVDOCS-6266 - Replacing with a workable link to install the GitOps CLI

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
Jira issue: [RHDEVDOCS-6266](https://issues.redhat.com/browse/RHDEVDOCS-6266) 

Aligned team: DevTools 
Cherry-pick to versions: `enterprise-4.12` and later

Docs preview:

- [Installing the GitOps CLI](https://85541--ocpdocs-pr.netlify.app/openshift-enterprise/latest/cli_reference/gitops-argocd-cli-tools.html)

SME review: Completed by @anandf

QE review: @varshab1210

Peer review:  Completed by @xenolinux 

Additional information: N/A

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
@anandf Please review this PR and provide feedback. Thanks!

**Review by anandf — APPROVED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
@varshab1210 Please review this PR and provide feedback. Thanks!

**Comment by varshab1210** [comment]
LGTM, thanks

**Pull request merged**
