### PR TITLE
Logging deployment guide errors with nodeselector

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1776902

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli Please take a look at this small change.

**Comment by mburke5678** [comment]
Asked BZ reporter:
_What if we remove the "Optionally specify an empty node selector in order for the logging pods to spread evenly across your cluster. If you want the logging pods to run on specific nodes, you can specify a node selector value such as openshift.io/node-selector: node-role.kubernetes.io/infra= here." paragraph and just have users install using `openshift.io/node-selector: "_
https://bugzilla.redhat.com/show_bug.cgi?id=1776902#c1

**Comment by anpingli** [comment]
The openshift.io/node-selector must be provided.  If you define openshift_node_groups yourself.  you must  know the labels.   If not, you can use the default labels.

**Comment by anpingli** [comment]
That is not a bug.  the fluentd  have to spread all over the nodes. That is why we use emptry values  for openshift.io/node-selector. If he want to deploy ES to infra nodes,  He need to specified in CRD.

**Comment by anpingli** [comment]
LGTM.

**Pull request merged**
