### PR TITLE
OCPBUGS-16180 Values incorrect in recommended control plane practices

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.14 only

Issue: https://issues.redhat.com/browse/OCPBUGS-16180

Link to docs preview: https://62599--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices.html

QE review:
- [*] QE has approved this change.

Additional information: Hello reviewer - this change is ONLY for 4.14. Please add labels as needed for milestone and "branch/enterprise 4.14" only. I have SME and QE approval.

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
Description from the issue:

The second note in [https://docs.openshift.com/container-platform/4.13/scalability_and_performance/recomme[...]ce-scale-practices/recommended-control-plane-practices.html](https://docs.openshift.com/container-platform/4.13/scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices.html) speaks to 5/10 default values and those were changed to 50/100 per https://github.com/kubernetes/kubernetes/pull/116121

**Comment by smalleni** [comment]
@afcollins @mffiedler Can you please review this, thanks!

**Review by afcollins — APPROVED** [review]
I see the changes in [release-4.14](https://github.com/openshift/kubernetes/blame/release-4.14/pkg/kubelet/apis/config/v1beta1/defaults.go#L99) but not release-4.13. (Only mention because the PR description says 4.13+)

I wouldn't expect it in 4.13 docs unless we back port it.

LGTM!

**Review by mffiedler — APPROVED** [review]

**Pull request merged**
