### PR TITLE
OSDOC#9453: Adding a known issue for Ebdsv5 and Ebsv5 machine type in…

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.15

Issue:

This issue addresses [osdocs-9453](https://issues.redhat.com/browse/OSDOCS-9453).

Link to docs preview:

[Known issues](https://70761--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-known-issues) (second bullet)

QE review:
[yes] QE has approved this change.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by jinyunma** [comment]
LGTM

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/lgtm

**Pull request merged**
