### PR TITLE
GH#52922: Add documentation for HAProxy option persist

### PR DESCRIPTION
**Pull request by thomaswoeckinger**
Issue:
Documentation for new HAProxy configuration option https://github.com/openshift/router/issues/419

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@skrthomas, will you send this change out for reviews and get it merged?

**Comment by skrthomas** [comment]
This docs issue depends on <https://github.com/openshift/router/pull/420>, which is now an RFE pending Engineer review

**Comment by skrthomas** [comment]
@thomaswoeckinger is there a new update on this PR? I see you recently re-pinged the engineering team asking for reviews of https://github.com/openshift/router/pull/420

**Comment by thomaswoeckinger** [comment]
sorry but there is still no response

**Comment by skrthomas** [comment]
Looks like this dependent code PR is still open and needs an RFE opened with the Network Edge component. Since there's not yet a `persist` HAProxy option, this documentation is still not viable for reviews.

**Comment by thomaswoeckinger** [comment]
> Looks like this dependent code PR is still open and needs an RFE opened with the Network Edge component. Since there's not yet a `persist` HAProxy option, this documentation is still not viable for reviews.

I am still waiting because I am not allowed to open an RFE on Network Edge componen

**Pull request closed without merging**
