### PR TITLE
some small cleanup to the MachineAutoscaler resource definition

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.6+

Issue:
Relates to effort in [OSDOCS-2876](https://issues.redhat.com//browse/OSDOCS-2876)

Link to docs preview:
[MachineAutoscaler resource definition](http://file.rdu.redhat.com/jrouth/typo-compute-plane/machine_management/applying-autoscaling.html#machine-autoscaler-cr_applying-autoscaling)

Additional information:
Just a few things that I noticed in this topic while planning some reorganization. This applies in part to 4.6+ but will need manual CP lower than at least 4.8 due to some other differences.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by kalexand-rh — COMMENTED** [review]
LGTM. This doesn't need QE.

**Pull request merged**
