### PR TITLE
[enterprise-4.13] reverse PR#59169

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.13

Issue:

Link to docs preview: http://file.rdu.redhat.com/jdohmann/reverse-regions/release_notes/ocp-4-13-release-notes.html#ocp-4-13-installation-and-update (removal)

QE review:
- [ ] QE has approved this change.

Additional information: xref: #59169

### CODE REVIEW

**Comment by jldohmann** [comment]
bf8f90ac59..6c613cb069 rebase

**Review by snarayan-redhat — COMMENTED** [review]
LGTM.

**Comment by jldohmann** [comment]
@jianli-wei PTAL for QE ack, thank you!

**Comment by JoeAldinger** [comment]
> @jianli-wei PTAL for QE ack, thank you!

Going to merge this due to freeze. We will create a new PR if need be to incorporate @jianli-wei suggestions if need be.

**Comment by kalexand-rh** [comment]
@jianli-wei, because today's the RN deadline and we want this to be correct to the best of our understanding in the translated collections at GA, we're merging this PR. Please review it anyway. If additional corrections are required, we will open a follow-up PR.

**Pull request merged**
