### PR TITLE
[enterprise-4.14] CNV-30838: RN - DV GC is now disabled by default

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.14

**Issue:**
https://issues.redhat.com/browse/CNV-30838

**Link to docs preview:**
https://63270--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-new

**QE review:**
- [x] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

@danielclowers be sure to get QE approval, if needed, before a merge request. Thanks!

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Pull request merged**
