### PR TITLE
OLS-931: Document OLS configuration for RHELAI as the provider

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Affects:
[lightspeed-main](https://github.com/openshift/openshift-docs/tree/lightspeed-docs-main)
[lightspeed-docs-1.0tp1](https://github.com/openshift/openshift-docs/tree/lightspeed-docs-1.0tp1)

This PR is part of the standalone doc set for the Lightspeed project. Kathryn is aware that this content applies for a product that is part of a Developer Preview release. The project is seeking feedback from early adopters.

PR must be CP'd back to the tp1 branch.

Version(s): Tech Preview

Issue:
https://issues.redhat.com/browse/OLS-931

Issue:

Link to docs preview for conceptual topic:
https://83104--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/about/ols-about-openshift-lightspeed.html#ols-about-rhelai_ols-about-openai

Link to docs preview for CLI task with code example:
https://83104--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/configure/ols-configuring-openshift-lightspeed.html#ols-creating-lightspeed-custom-resource-file-using-cli_ols-configuring-openshift-lightspeed

Link to docs preview for web console task with code example:
https://83104--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/configure/ols-configuring-openshift-lightspeed.html#ols-creating-lightspeed-custom-resource-file-using-web-console_ols-configuring-openshift-lightspeed

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]

**Comment by JoaoFula** [comment]
LGTM

**Review by lahinson — COMMENTED** [review]
@rh-tokeefe Before I can merge this one, you need to squash the PR down to 1 commit. If you're not familiar with how to do that, you can see the instructions here: https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#bookmark=id.9bn6glcn7tle

Otherwise, this looks good. Let me know when you've squashed, and I will merge.

**Review by lahinson — COMMENTED** [review]
lgtm

**Pull request merged**
