### PR TITLE
OSDOCS-9752 fixed openshit-dedicated typo

### PR DESCRIPTION
**Pull request by xJustin**
Typo fix in conditional statement 

Version(s):

4.13+ 

Issue:

https://issues.redhat.com/browse/OSDOCS-9752
Link to docs preview:

Enterprise: 
https://72004--ocpdocs-pr.netlify.app/openshift-enterprise/latest/openshift_images/image-configuration#images-configuration-blocked-payload 

Dedicated:
https://72004--ocpdocs-pr.netlify.app/openshift-dedicated/latest/openshift_images/image-configuration#images-configuration-blocked_image-configuration

ROSA: 
https://72004--ocpdocs-pr.netlify.app/openshift-rosa/latest/openshift_images/image-configuration#images-configuration-blocked_image-configuration

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xueli181114** [comment]
LGTM

**Review by mletalie — COMMENTED** [review]
/label remove-peer-review-in-progress
/label peer-review-done
/lgtm

**Review by mletalie — COMMENTED** [review]
/remove-label peer-review-in-progress

**Pull request merged**
