### PR TITLE
RHDEVDOCS-6122: Content creation for GitOps 1.11.7 Release Notes

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.11, GitOps 1.12, GitOps 1.13, GitOps 1.14

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6122

Link to docs preview:

[Release Notes for Red Hat OpenShift GitOps 1.11.7](https://79752--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-11-7_gitops-release-notes)

QE review:
- [x] QE has approved this change.

SME review: Completed by anjoseph@redhat.com
QE review: Completed by @varshab1210 
Peer review: Completed by @Srivaralakshmi 

Additional information:

### CODE REVIEW

**Comment by varshab1210** [comment]
LGTM, thanks

**Review by anandf — APPROVED** [review]
LGTM

**Review by Srivaralakshmi — COMMENTED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
The accidental merge with unqsuashed commits warranted a revert of this PR.

**Pull request merged**
