### PR TITLE
[enterprise-3.10] Update name change for CNS and CRS

### PR DESCRIPTION
**Pull request by ghost**
This is a CP of https://github.com/openshift/openshift-docs/pull/10980.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@vikram-redhat Due to the [release notes merge](https://travis-ci.org/openshift/openshift-docs/builds/407227268#L586), the CI check never started for this PR. Should I go ahead and merge this PR?

**Comment by vikram-redhat** [comment]
@tmorriso-rh - Hey. No please rebase your local enterprise-3.10 which contains the release notes fixes and then push against this PR. That should trigger the rebuild and pass it:

https://travis-ci.org/openshift/openshift-docs/builds/407324715

**Comment by tmorriso-rh** [comment]
@vikram-redhat Please contact me about this PR. Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh  Closing this in favor of: https://github.com/openshift/openshift-docs/pull/11065

**Pull request closed without merging**
