### PR TITLE
Add instruction on making projects global after move to ovs-multitenant

### PR DESCRIPTION
**Pull request by rh-max**
@bostrt , does this change look good?

### CODE REVIEW

**Comment by bostrt** [comment]
lgtm!

**Comment by rh-max** [comment]
@bostrt Thanks!
@bobfuru Could you please review and merge? Thank you.

**Comment by bobfuru** [comment]
LGTM

**Comment by bobfuru** [comment]
> @bostrt Thanks!
> @bobfuru Could you please review and merge? Thank you.

@rh-max Added labels and merged.

**Comment by rh-max** [comment]
@bobfuru Thanks!

**Pull request merged**
