### PR TITLE
[enterprise-4.15] OCPBUGS-34846: add optional paramter and admonition

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.14, 4.15

Issue: https://issues.redhat.com/browse/OCPBUGS-34846

Link to docs preview:

- https://78607--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-autoscaling-ingress-controller_configuring-ingress
- https://78607--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/cma/nodes-cma-autoscaling-custom-trigger.html#nodes-cma-autoscaling-custom-prometheus-config_nodes-cma-autoscaling-custom-trigger

QE review:
- [x] QE has approved this change.

Additional information: followup to #78467

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi PTAL at this docs PR for QE ack. Thank you 🙇

**Review by skopacz1 — APPROVED** [review]
Peer review LGTM

**Comment by ShudiLi** [comment]
/lgtm
@jldohmann done, thanks.

**Pull request merged**
