### PR TITLE
CNV-25105: Create dummy 4.14 release notes file

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14

Issue: [CNV-25105](https://issues.redhat.com/browse/CNV-25105)

Link to docs preview: N/A

QE review: N/A

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
Looks good to me! I'm still new to peer review, so please wait until @adellape has approved of my review before proceeding to merge review.

**Review by adellape — COMMENTED** [review]
@skopacz1 @aspauldi Peer review looks good to me 👍

**Comment by jeana-redhat** [comment]
@aspauldi does this get CPed to 4.14 or do you already have/plan to have a "real" 4.14 RN file in that spot?

**Pull request merged**
