### PR TITLE
Update installation type table

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@vikram-redhat let me know if this is a pre or post GA update.

**Comment by vikram-redhat** [comment]
Definitely pre :D

**Review by vikram-redhat — APPROVED** [review]

**Comment by codyhoag** [comment]
Preview: https://install-table-updates--ocpdocs.netlify.app/openshift-enterprise/latest/installing/install_config/installation-types.html

**Review by jeana-redhat — APPROVED** [review]
LGTM!

**Pull request merged**
