### PR TITLE
Deprecation and EOL statements for RNs

### PR DESCRIPTION
**Pull request by codyhoag**
This includes new deprecation and EOL statements acked by Eric Rich and Tim Rees (via email). With the validation of all current removed/deprecated features in the current TP table, along with Eric Rich's recommendation to point to a Deprecation table from our deprecation statement, I've also extracted the deprecated/removed features into its own unique table.

Preview: http://file.rdu.redhat.com/~choag/042720/dep-eol-notices/release_notes/ocp-4-4-release-notes.html

FYI @vikram-redhat

### CODE REVIEW

**Comment by mbearer** [comment]
Looks good Cody!

**Comment by bergerhoffer** [comment]
This layout LGTM. The only thing that struck me as odd was that the TP table has rows in it that are GA across the board, but I feel like we discussed that at a previous meeting and decided to leave them in their for historical purposes.

**Comment by codyhoag** [comment]
@bergerhoffer yeah, you're right (and I 100% agree on it seeming odd). We decided to keep those in for 4.4 and get the appropriate acks in 4.5 to remove them. I also have the same feeling for the removed features in the Deprecation table. We're playing it safe since we are unsure of the scope the table was intended to cover when it was requested by Engineering.

**Comment by vikram-redhat** [comment]
> We're playing it safe since we are unsure of the scope the table was intended to cover when it was requested by Engineering.

_By the PM/BU._

**Comment by codyhoag** [comment]
With no objections from the team and already having stakeholder acks for the statements, I'll merge this in. Thanks!

**Pull request merged**
