### PR TITLE
OSDOCS#8967: Doc set sweep to change 1.27 to 1.28

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-8967

Link to docs preview:
Too many to list all exact spots, since most are just example output. But adding links for places that were changed more significantly:
* https://69920--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-viewing#nodes-nodes-viewing-listing_nodes-nodes-viewing
* https://69920--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/understanding/olm/olm-understanding-olm#olm-catalogsource-image-template_olm-understanding-olm
* https://69920--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli#prerequisites

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by adellape — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
LGTM

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
