### PR TITLE
BZ2010287: Doc how to use shared directories w/local volumes

### PR DESCRIPTION
**Pull request by lpettyjo**
4.10+

[BZ2010287](https://bugzilla.redhat.com/show_bug.cgi?id=2010287)
Documents how to use shared directories with local volumes

**Preview**: https://deploy-preview-41435--osdocs.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent-storage-local.html#local-create-cr-manual_persistent-storage-local

**PTAL**: @gnufied @duanwei33

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

**Comment by gnufied** [comment]
lgtm

**Comment by lpettyjo** [comment]
@kalexand-rh agrees that this should be back ported to 4.8 and 4.9.

**Pull request merged**
