### PR TITLE
Telcodocs 1016 411 RN Adding Release note for bug 2050824

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-1016](https://issues.redhat.com//browse/TELCODOCS-1016): Deleting a BFDProfile object does not delete the corresponding running-conf from the MetalLB speakers

See also https://bugzilla.redhat.com/show_bug.cgi?id=2050824

Version(s):
4.11

Preview: https://52492--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-known-issues

### CODE REVIEW

**Comment by cgoncalves** [comment]
OCP 4.12 also needs such a release note. Are you going to submit a 4.12 PR?

**Comment by kquinn1204** [comment]
I will have to create a separate PR for that. I think RN for 4.12 being centrally managed so will do that with this same content. @cgoncalves @sabinaaledort can you LGTM this desc to get through peer review squad please.

**Comment by bscott-rh** [comment]
LGTM.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
