### PR TITLE
Adding additional feedback to netobserv release note

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.10+
Issue:

https://issues.redhat.com/browse/OSDOCS-5366
Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

There was a [comment](https://github.com/openshift/openshift-docs/pull/55951#issuecomment-1433601429) from @stleerh that came in right at time of merge that had some minor yet important details that need addressing. His Slack message to me with context about his comment:
- Previously, HOST was doing only host authentication and not user authentication.
- "allowing any user" to "allowing anyone" because you don't even have to be logged in as a user.  It may still not be that obvious when we speak of a "user".
- "Now, regardless of the Loki authToken mode," -> There's a third choice which is DISABLED (default value) that will prevent even a cluster admin from getting flows because it's not providing a token.

### CODE REVIEW

**Review by stleerh — COMMENTED** [review]
/lgtm

**Comment by jotak** [comment]
As said on slack, I think this is not correct, we must stick to the current published version (bc admins privileges are required *regardless* of the lokiAtuh mode)

**Comment by skrthomas** [comment]
ACK, thanks for your reviews both. These details man, they are so devilish!

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by skrthomas** [comment]
The changes in this PR were determined not necessary. Closing this PR.

**Pull request closed without merging**
