### PR TITLE
Update nw-ingress-sharding-namespace-labels.adoc

### PR DESCRIPTION
**Pull request by s-dharma**
Replace "#" with "$"

Update nw-ingress-sharding-namespace-labels.adoc

Replace "#" with "$"

Version(s):

RHOCP 4.16

Issue:

Added "#" instead of "$"

Link to docs preview:

https://docs.openshift.com/container-platform/4.16/networking/ingress-sharding.html#nw-ingress-sharding-namespace-labels_ingress-sharding

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by JoeAldinger** [comment]
@anuragthehatter could help with the QE review of this PR please?

**Comment by lihongan** [comment]
LGTM. 
Thank you!

**Pull request merged**
