### PR TITLE
OCPBUGS-16287: Fix yaml formatting

### PR DESCRIPTION
**Pull request by yuumasato**
The environment variable PLATFORM was not being correctly set.

Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-16287

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

- https://github.com/ComplianceAsCode/compliance-operator/blob/master/doc/usage.md#how-to-use-compliance-operator-with-hypershift-hosted-cluster
- https://github.com/ComplianceAsCode/compliance-operator/blob/master/config/catalog/subscription-hypershift.yaml

### CODE REVIEW

**Comment by yuumasato** [comment]
Follow up from https://github.com/openshift/openshift-docs/pull/62435
CC: @xiaojiey @sheriff-rh

**Review by sheriff-rh — APPROVED** [review]
LGTM! Thanks Yuuma!

**Comment by sheriff-rh** [comment]
Merging! :rocket:

**Pull request merged**
