### PR TITLE
RHDEVDOCS-3594: Update odo config docs

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/RHDEVDOCS-3594

Applies for OCP 4.6+ (confirmed with @gabriel-rh)

Direct preview link: https://deploy-preview-42439--osdocs.netlify.app/openshift-enterprise/latest/cli_reference/developer_cli_odo/configuring-the-odo-cli.html

Peer review: @gabriel-rh ✅

### CODE REVIEW

**Comment by gabriel-rh** [comment]
@abrennan89 the content looks good to me. The only issue I spotted is in the example command:

$ odo preference unset updatednotification

this should be "update" not "updated"

Otherwise, good to merge imo.

**Comment by abrennan89** [comment]
>this should be "update" not "updated"
@gabriel-rh this probably needs to be updated upstream then as well, just FYI 🙂 will update and merge this today, thanks!

**Pull request merged**
