### PR TITLE
OSDOCS-8384: Migrate "Getting Started with Rosa - Delete the Cluster"

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-8384](https://issues.redhat.com//browse/OSDOCS-8384): Migrate "Getting Started with Rosa - Delete the Cluster" from rosaworkshop.io

Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8384

Link to docs preview:
https://70152--ocpdocs-pr.netlify.app/openshift-rosa/latest/cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-deleting

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can you please provide a QE review for this PR? Thanks!

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
