### PR TITLE
BZ1859396: Fixed out-of-date oc expose command

### PR DESCRIPTION
**Pull request by ctauchen**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1859396

Applies to 4.6+

Preview link: https://deploy-preview-38343--osdocs.netlify.app/openshift-enterprise/latest/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-nodeport#nw-exposing-service_configuring-ingress-cluster-traffic-nodeport

### CODE REVIEW

**Comment by ctauchen** [comment]
@zhaozhanqi Can you take a look?

**Review by atheurer — APPROVED** [review]

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi Can you take a look?
Hi, need @lihongan help take a look this.

**Comment by lihongan** [comment]
LGTM
Thank you @ctauchen

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
