### PR TITLE
OSDOCS-4354: Added cloud-network-config-controller-cloud description to table.

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4,11+

Issue:
https://issues.redhat.com/browse/OSDOCS-4354

Link to docs preview:
https://52759--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources.html#rosa-sts-operator-roles_rosa-sts-about-iam-resources

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by opayne1** [comment]
I see you have an ack in JIRA from an engineer 👍 

Just FYI your commit message doesn't match the title of this PR it is just missing the OSDOCS piece.

**Comment by yuwang-RH** [comment]
LGTM.

**Pull request merged**
