### PR TITLE
Added new Scheduled Jobs topic

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1374031

### CODE REVIEW

**Comment by soltysh** [comment]
@ahardin-rh just fyi, the #3083 was submitted against 3.3, since it contains additional known issues section that should not be present against 3.4 release. And we need the docs in both versions.

**Comment by soltysh** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/scheduled_jobs.adoc#dev-guide-scheduled-jobs[Scheduled Jobs]
|New topic on the Scheduled Jobs feature, which allows you to specifically schedule how the job should be run.
%

**Pull request merged**
