### PR TITLE
OSDOCS-12654:Replace Accessing service logs link with Rosa cluster notifications link

### PR DESCRIPTION
**Pull request by fmcdonal**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-12654

Link to docs preview:
https://84835--ocpdocs-pr.netlify.app/openshift-rosa/latest/support/approved-access.html

### CODE REVIEW

**Comment by fmcdonal** [comment]
no Reviews needed as just a link change

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
