### PR TITLE
BZ1919425: networking: Document which ports applications can not connect to

### PR DESCRIPTION
**Pull request by russellb**
bug 1919425

### CODE REVIEW

**Review by knobunc — APPROVED** [review]
LGTM.

**Comment by russellb** [comment]
> @russellb, I've updated the formatting on this; What do you think? Thanks!

Changes look good to me.  Thanks!

**Comment by russellb** [comment]
/hold

This is actually a bit more complicated.  I'd like to hold this while we sort it out further.

**Comment by jboxman** [comment]
@russellb, sounds good, let me know when anything changes, thanks!

**Comment by jboxman** [comment]
@russellb is there any movement on this? Thanks!

**Comment by russellb** [comment]
@dougbtv picked up the work related to this.  Doug, can you share a link to a bugzilla tracker for what you were working on?  Then we can probably close this PR.

**Comment by dougbtv** [comment]
Tracking the CNO change which also has the code for which ports will be involved @ https://bugzilla.redhat.com/show_bug.cgi?id=1960751 and related PR and especially relevant lines here @ https://github.com/openshift/cluster-network-operator/pull/986/files#diff-cf5a3f70cfbed6100989a28c557544abce4bae0637b4a43c277cb9189e25e78aR211-R214

**Comment by jboxman** [comment]
@dougbtv forgot what this was about; We'll have a few ports that are basically not usable for users?

**Pull request closed without merging**
