### PR TITLE
BZ-1905797: Add guidance on using cloud-provided DNS server when deploying to an existing VNet/VPC

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
CP to 4.6+

Issue:
This PR addresses BZ [1905797](https://bugzilla.redhat.com/show_bug.cgi?id=1905797).

Link to docs preview:

- (Azure) [Requirements for using your VNet](http://file.rdu.redhat.com/mpytlak/bz1905797/installing/installing_azure/installing-azure-vnet.html#installation-about-custom-azure-vnet-requirements_installing-azure-vnet)
- (AWS) [Requirements for using your VPC](http://file.rdu.redhat.com/mpytlak/bz1905797/installing/installing_aws/installing-aws-vpc.html#installation-custom-aws-vpc-requirements_installing-aws-vpc)
- (GCP) [Requirements for using your VPC](http://file.rdu.redhat.com/mpytlak/bz1905797/installing/installing_gcp/installing-gcp-vpc.html#installation-custom-gcp-vpc-requirements_installing-gcp-vpc)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@MichaelWasher PTAL. I believe this covers it. @MayXuQQ Ready for QE review, as well.

@yunjiang29 and @jianli-wei Based on this [KCS](https://access.redhat.com/solutions/5636061), is it OK to make the proposed change to the respective AWS and GCP content?

**Comment by yunjiang29** [comment]
@mjpytlak 
> The installation program requires that you use the cloud-provided DNS server. Using a custom DNS server is not supported and causes the installation to fail.

This description looks good to me,  it is applicable for Azure/AWS/GCP.

> ETCD DNS records
Installer doesn't not create individual etcd DNS records in DNS zone.

**Comment by yunjiang29** [comment]
@mjpytlak thanks for the update,  /lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
