### PR TITLE
document new non-string parameter syntax

### PR DESCRIPTION
**Pull request by bparees**
This doc is for https://github.com/openshift/origin/pull/11421

please do not merge until that PR merges.

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation pre-req PR has merged, ptal/merge.

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by vikram-redhat** [comment]
@bfallonf - ptal.

**Comment by bfallonf** [comment]
@bparees Sure, thanks for this. I'll merge.

**Comment by adellape** [comment]
@bfallonf Adding milestone.

**Pull request merged**
