### PR TITLE
OSDOCS-12406:Amended ROSA Classic private/public arch image.

### PR DESCRIPTION
**Pull request by AedinC**
This PR amends the ROSA Classic private and public architecture model image as the previous one was incorrect. No QE review needed.

Version(s):
4.17+

Issue:
https://issues.redhat.com/browse/OSDOCS-12406

Link to docs preview:
https://85903--ocpdocs-pr.netlify.app/openshift-rosa/latest/architecture/rosa-architecture-models#rosa-classic-architecture-networks_rosa-architecture-models

SME review:
- [x] SME has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
lgtm

**Comment by AedinC** [comment]
> lgtm

Thanks @arendej

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
