### PR TITLE
Rename dry-run to confirm for pruning.

### PR DESCRIPTION
**Pull request by ncdc**
Rename dry-run to confirm for pruning operations. Also move image
pruning from the Docker Registry page to the resource pruning page.

### CODE REVIEW

**Comment by ncdc** [comment]
Wait until https://github.com/openshift/origin/pull/2768 merges before merging this PR

**Comment by ncdc** [comment]
Ok to review & merge

**Comment by ncdc** [comment]
@tnguyen-rh @adellape

**Comment by adellape** [comment]
@ncdc Thanks, merging.

**Pull request merged**
