### PR TITLE
OSDOCS-4924: Verify max MTU value acceptance

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4924

Link to docs preview:
https://72472--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/changing-cluster-network-mtu#mtu-value-selection_changing-cluster-network-mtu

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by huiran0826** [comment]
@yingwang-0320 Can you help check this one ? Thanks!

**Comment by yingwang-0320** [comment]
It looks good, but people who is not familar with the hardware environment may not know which network interface is used.
I suppose it would be better to add the command about how to get the network interface name.

**Comment by yingwang-0320** [comment]
Hi @obrown1205 Just find that the command is covered in [other section](https://docs.openshift.com/container-platform/4.15/networking/changing-cluster-network-mtu.html#nw-cluster-mtu-change_changing-cluster-network-mtu).
So I put /lgtm here.

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
