### PR TITLE
OSDOCS-3490: add supported AWS instance types for OSD

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-3490

Preview: https://deploy-preview-44281--osdocs.netlify.app/openshift-dedicated/latest/osd_policy/osd-service-definition#aws-compute-types_osd-service-definition

### CODE REVIEW

**Comment by bmcelvee** [comment]
@yuwang-RH would you mind reviewing this PR, please? Thanks! It's the OSD-specific updates related to the ROSA updates made in https://github.com/openshift/openshift-docs/pull/44154.

**Comment by bmcelvee** [comment]
@yuwang-RH would you mind reviewing this PR, please? Thanks!

**Comment by yuwang-RH** [comment]
LGTM~

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

However, should we collapse this list too? https://deploy-preview-44281--osdocs.netlify.app/openshift-dedicated/latest/osd_policy/osd-service-definition#regions-availability-zones_osd-service-definition

**Review by arendej — APPROVED** [review]
lgtm

**Pull request merged**
