### PR TITLE
Append SR-IOV specific must-gather

### PR DESCRIPTION
**Pull request by Scotchman0**
Resolves Issue: https://github.com/openshift/openshift-docs/issues/54365

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Scotchman0** [comment]
https://54416--docspreview.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data

**Comment by kalexand-rh** [comment]
@zhaozhanqi, will you PTAL?

**Comment by kalexand-rh** [comment]
@zhaozhanqi, will you PTAL?

**Comment by zhaozhanqi** [comment]
> @zhaozhanqi, will you PTAL?

sriov must-gather image should be deprecated, see https://github.com/openshift/sriov-network-operator/pull/682

**Comment by Scotchman0** [comment]
Ah! Fantastic - I will mark this closed/resolved. Thank you for the PR link, this solves the issue for me!

**Pull request closed without merging**
