### PR TITLE
Bug 1463852 Updating list of images for 3.5 disconnected install

### PR DESCRIPTION
**Pull request by mburke5678**
Related to https://github.com/openshift/openshift-docs/pull/5082

### CODE REVIEW

**Comment by mburke5678** [comment]
@jianlinliu @miheer PTAL. Updated the list of images for 3.5 Disconnected Install based on Jianlin's list in [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1463852#c7).

**Comment by mburke5678** [comment]
@jianlinliu @miheer PTAL. Updated the list of images for 3.5 Disconnected Install based on Jianlin's list in [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1463852#c7).

**Comment by jianlinliu** [comment]
LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL

**Comment by tmorriso-rh** [comment]
LGTM.

**Pull request merged**
