### PR TITLE
Introduces the "CLI by Example" section

### PR DESCRIPTION
**Pull request by fabianofranz**
This document is automatically generated by the `hack/run-gendocs.sh` script.

Related: https://github.com/openshift/origin/pull/3325

### CODE REVIEW

**Comment by adellape** [comment]
@fabianofranz Would this be OK to go ahead and merge so we could try to start figuring out how to present it (e.g., what to do w/ the TOC)?

**Comment by adellape** [comment]
BTW, this is cool. :pizza:

**Comment by fabianofranz** [comment]
@adellape Yes, good to merge. Just notice that I need to know if you change anything in the structure of `cli_by_example_content.adoc` - it's generated automatically by a script so I may need to update the base template.

**Comment by adellape** [comment]
@fabianofranz Got it, thanks!

**Pull request merged**
