### PR TITLE
Follow up to 43323 regarding ipsec note

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OCPBUGS-43323

Link to docs preview:
https://83462--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/network_security/configuring-ipsec-ovn.html

QE review:
- [x] QE has approved this change.

Additional information:
PTAL: @zshi-redhat

### CODE REVIEW

**Comment by anuragthehatter** [comment]
/lgtm

@pperiyasamy ptal as well if we need to add something more

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by pperiyasamy** [comment]
@stevsmit @anuragthehatter is this change for 4.15 and later versions ? The ipsec daemonsets are removed automatically in >=4.15 versions. only in 4.14 and previous versions it has to be removed explicitly after ipsec is disabled.

**Comment by stevsmit** [comment]
@pperiyasamy I'll get this branch targeted for 4.12-4.14 soon.

**Comment by anuragthehatter** [comment]
Agree. The target branch is main which doesn;t see right. Thanks for catching that @pperiyasamy

**Pull request closed without merging**
