### PR TITLE
Bug 1921281: remove --export flag from oc

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1921281

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh @zhouying7780 Can you please review?

Preview: https://deploy-preview-28943--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/using-templates.html#templates-create-from-existing-object_using-templates

**Review by jeana-redhat — APPROVED** [review]
Great!

**Comment by jboxman** [comment]
@bergerhoffer is this also related to this https://github.com/openshift/openshift-docs/issues/28623?

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
> @bergerhoffer is this also related to this #28623?

Yes it is, thanks @jboxman! I'll close that issue.

**Pull request merged**
