### PR TITLE
BZ1860721: adding certificate customizations

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1860721

4.6+

Preview: https://deploy-preview-34976--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-initializing_installing-restricted-networks-gcp

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@tsze-redhat, will you PTAL? It's easier to track the important part of this change by checking out the [preview](https://deploy-preview-34976--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-initializing_installing-restricted-networks-gcp).

**Comment by tsze-redhat** [comment]
Sorry I didn't notice this before.

Looking at https://deploy-preview-34976--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-initializing_installing-restricted-networks-gcp, 

step 2 c has
Edit the install-config.yaml file to provide the additional information that is required for an installation in a restricted network.

Do you know where that comes from? It isn't a necessary step, I think. @wking Correct me here please.

Other than the above, LGTM.

Thanks.

**Comment by kalexand-rh** [comment]
> Sorry I didn't notice this before.
> 
> Looking at https://deploy-preview-34976--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-restricted-networks-gcp.html#installation-initializing_installing-restricted-networks-gcp,
> 
> step 2 c has
> Edit the install-config.yaml file to provide the additional information that is required for an installation in a restricted network.
> 
> Do you know where that comes from? It isn't a necessary step, I think. @wking Correct me here please.
> 
> Other than the above, LGTM.
> 
> Thanks.

@tsze-redhat, it's applying the same GCP + restricted customizations that you approved [here](https://github.com/openshift/openshift-docs/pull/32482#issuecomment-839983489).

**Comment by tsze-redhat** [comment]
and I asked the same questions there too. :)

Sorry.

LGTM

Thanks.

**Comment by kalexand-rh** [comment]
> and I asked the same questions there too. :)
> 
> Sorry.
> 
> LGTM
> 
> Thanks.

Thank you for taking a look! I am glad that you didn't have a new concern about this specific implementation and that it looks good. :)

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
