### PR TITLE
OSDOCS-3744: Removing conditional for SRE mandatory service

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Version(s): PR applies to all active versions of ROSA documentation. 
Issue: [OSDOCS-3744](https://issues.redhat.com/browse/OSDOCS-3744): Missing nosnch.in endpoint in firewall prereqs

Link to docs preview: pending

### CODE REVIEW

**Comment by michaelryanmcneill** [comment]
cc: @bmcelvee @okashi18

**Review by tmalove — COMMENTED** [review]
LGTM

**Pull request merged**
