### PR TITLE
OCPBUGS#755 Added missing GCP supported regions

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
CP to 4.10+

Issue:
[This PR addresses OCPBUGS-775](https://issues.redhat.com/browse/OCPBUGS-755)

Link to docs preview:
[Supported GCP regions](http://file.rdu.redhat.com/mpytlak/ocpbugs-755/installing/installing_gcp/installing-gcp-account.html#installation-gcp-regions_installing-gcp-account)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@jianli-wei Ready for QE review. I updated Supported GCP regions to include all QE tested regions. Used this doc [1] to identify missing entries.

[1] https://docs.google.com/spreadsheets/d/15BHZt0CTBDKQiYlHNTabSdwMSKV_xUiQMaqhJhH57hs/edit#gid=0

**Comment by jianli-wei** [comment]
> @jianli-wei Ready for QE review. I updated Supported GCP regions to include all QE tested regions. Used this doc [1] to identify missing entries.
> 
> [1] https://docs.google.com/spreadsheets/d/15BHZt0CTBDKQiYlHNTabSdwMSKV_xUiQMaqhJhH57hs/edit#gid=0

hello @mjpytlak 
1. It seems I cannot open the doc preview [Supported GCP regions](https://github.com/openshift/openshift-docs/pull/modules/installation-gcp-regions.adoc), any idea? Thanks! 
2. In your [1], the GCP sheet, 
- Line 31 and line 12 seem duplicate.
- Please provide also the long name for regions in line 29 - 37.

**Comment by mjpytlak** [comment]
> 1. It seems I cannot open the doc preview [Supported GCP regions](https://github.com/openshift/openshift-docs/pull/modules/installation-gcp-regions.adoc), any idea? Thanks

@jianli-wei For the time being Tech Pubs has to publish to a RH file share. I suspect you are not on the VPN. You need to be on the VPN to access it.

**Comment by mjpytlak** [comment]
> 2\. In your [1], the GCP sheet,
> 
> * Line 31 and line 12 seem duplicate.
> * Please provide also the long name for regions in line 29 - 37.
> * Suggest to sort the regions alpha-numerically

@jianli-wei This is not my spreadsheet. I am not sure who owns it, but it was forward to me by Mak to use as a resource.

I did, however, make sure to add the long snames to the regions in the doc. :)

**Comment by jianli-wei** [comment]
@mjpytlak The bug [2102362](https://bugzilla.redhat.com/show_bug.cgi?id=2102362) _- Valid regions should be allowed in GCP install config_ was only tested with 4.11, so 4.10 won't allow the 8 new regions (see below list). Shall we remove the label `branch-enterprise-4.10` from the PR? 

- asia-south2 (Delhi, India)
- australia-southeast2 (Melbourne, Australia)
- europe-southwest1 (Madrid, Spain)
- europe-west8 (Milan, Italy)
- europe-west9 (Paris, France)
- southamerica-west1 (Santiago, Chile)
- us-east5 (Columbus, Ohio, USA)
- us-south1 (Dallas, Texas, USA)

```
$ openshift-install version
openshift-install 4.10.31
built from commit abcc78b6c7c20d6f5363c794a7e72326d24f7093
release image quay.io/openshift-release-dev/ocp-release@sha256:86f3b85645c613dc4a79d04c28b9bbd3519745f0862e30275acceadcbc409b42
release architecture amd64
$ yq-3.3.0 r test1/install-config.yaml platform
gcp:
  projectID: openshift-qe
  region: asia-south2
$ openshift-install create cluster --dir test1
FATAL failed to fetch Metadata: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.gcp.region: Unsupported value: "asia-south2": supported values: "asia-east1", "asia-east2", "asia-northeast1", "asia-northeast2", "asia-northeast3", "asia-south1", "asia-southeast1", "asia-southeast2", "australia-southeast1", "europe-central2", "europe-north1", "europe-west1", "europe-west2", "europe-west3", "europe-west4", "europe-west6", "northamerica-northeast1", "northamerica-northeast2", "southamerica-east1", "us-central1", "us-east1", "us-east4", "us-west1", "us-west2", "us-west3", "us-west4" 
$

**Comment by jianli-wei** [comment]
/hold
The bug https://bugzilla.redhat.com/show_bug.cgi?id=2102363 for release-4.10 is to be verified. Will update then, thanks!

**Comment by jianli-wei** [comment]
/unhold
/label branch/enterprise-4.10
[Bug 2102363 - Valid regions should be allowed in GCP install config](https://bugzilla.redhat.com/show_bug.cgi?id=2102363) had been verified for 4.10.z.

**Comment by jianli-wei** [comment]
@mjpytlak Sorry, could you re-add the label branch-enterprise-4.10? Thanks!

**Comment by mjpytlak** [comment]
@jianli-wei Re-added 4.10. Good to publish this content to 4,.10+ now?

**Review by bscott-rh — APPROVED** [review]
LGTM.

**Pull request merged**
