### PR TITLE
Include IBM Z/Power for supported UPI platforms

### LINKED ISSUE #26643: [enterprise-4.5] Issue in file architecture/architecture-installation.adoc
### Which section(s) is the issue in?

Supported Platforms

### What needs fixing?
Is there a reason IBM Cloud is missing from this list of supported platforms?

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #26643

### CODE REVIEW

**Comment by codyhoag** [comment]
@SNiemann15 this is a straightforward update, but wanted to get a QE ack. Do you know who could provide that?

**Comment by SNiemann15** [comment]
@holgwolf @lsmcfadden Can one of you ack?

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
