### PR TITLE
Changed destinationCaCertificate to destinationCACertificate - #1739

### PR DESCRIPTION
**Pull request by shubheksha**
I've made the changes as specified in #1739. Please review.

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@vikram-redhat 
Small but important typo.  Do you think a revhistory note is necessary?

**Comment by adellape** [comment]
@tnguyen-rh +1 to revhistory for this.

**Comment by vikram-redhat** [comment]
Yeah, as @adellape  says.

**Comment by adellape** [comment]
@shubheksha LGTM, thanks!

Fixes https://github.com/openshift/openshift-docs/issues/1739

[rev_history]
|link:../architecture/core_concepts/routes.html[Core Concepts -> Routes]
|Fixed typo of the `*destinationCACertificate*` parameter name.
%
|link:../install_config/cluster_metrics.html[Enabling Cluster Metrics]
|Fixed typo of the `*destinationCACertificate*` parameter name.
%

**Pull request merged**
