### PR TITLE
UPI is now supported for select platforms on WINC

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: https://deploy-preview-37548--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-3-x.html#wmco-prerequisites_windows-containers-release-notes

### CODE REVIEW

**Comment by codyhoag** [comment]
@sgaoshang @rrasouli can you verify? Thanks!

**Comment by codyhoag** [comment]
@sgaoshang @rrasouli bump. Can you confirm? Thanks!

**Comment by sgaoshang** [comment]
@codyhoag lgtm, thanks.

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
