### PR TITLE
Adding rel note for CNV 2.1 - BZ1754920

### PR DESCRIPTION
**Pull request by bgaydosrh**
Testing Build

### CODE REVIEW

**Comment by bgaydosrh** [comment]
This PR adds one release note to the 4.2 notes.

Here is a test build. The note is the last one, bottom of file.

Peer review needed. Merge and pick to enterprise-4.2 only. Another PR adds the note for 4.3  release notes.

**Comment by ousleyp** [comment]
LGTM.

**Comment by bgaydosrh** [comment]
> Bob, can you reopen this against master? Then I can cherrypick it to 4.2. Thanks!

@ousleyp Sure, I will close. I need to open a second PR as well to add info to the upgrading note for 4.3.....

**Comment by bgaydosrh** [comment]
After talking with @ousleyp reopening

**Comment by bgaydosrh** [comment]
Restoring branch and reopening

**Review by ousleyp — APPROVED** [review]
LGTM

**Pull request merged**
