### PR TITLE
[enterprise-4.12] TELCODOCS-1358: Clarification in Enabling the assisted service ZTP section

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.12

Issue: https://issues.redhat.com/browse/TELCODOCS-1358

Link to docs preview: https://65084--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster#enabling-assisted-installer-service-on-bare-metal_ztp-preparing-the-hub-cluster

QE review:
- [X] QE has approved this change.

Additional information: Cherry Picked from d3715a5e4a74dd404eeb9eaa1af7ea9e04da9d25 xref: https://github.com/openshift/openshift-docs/pull/64883 . Acks in original PR

### CODE REVIEW

**Comment by amolnar-rh** [comment]
@michaelryanpeter Even if it's a manual cherrypick of the original PR (https://github.com/openshift/openshift-docs/pull/64883)? I included a link to it in my description and all the review acks are in there

**Comment by michaelryanpeter** [comment]
@amolnar-rh Sorry, I missed that. 

[The OpenShift docs manual](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.x2d4tdt5adta) specifies how your pull requests and comment zero need to be formatted for manual cherrypicks. For example: `[enterprise-4.12] TELCODOCS-1358`. You have the cross reference to the PR, but you also need to specify the commit: “Cherry Picked from <commit-id> xref: <original-main-PR-link>”.

I can change the labels back, and pick up the merge review. Would you please update the PR's heading and comment zero?

**Comment by amolnar-rh** [comment]
@michaelryanpeter Thanks for the link, updated the title and the description!

**Comment by michaelryanpeter** [comment]
Since you are out of office for the day, I will change the heading for you. Please update comment zero with an xref to the commit when you return. Thanks!

**Comment by michaelryanpeter** [comment]
Thank you! I know it seems like a small thing, but it does help a lot when you are doing lots of reviews in a day.

**Pull request merged**
