### PR TITLE
OSDOCS-10012: 4.15.5 RN

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-10012

Link to docs preview:
https://73745--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-5

QE review:
N/A

Additional information:

### CODE REVIEW

**Review by mramendi — APPROVED** [review]
One style suggestion and one minor nit about attributes, otherwise looks great!

As I am in peer review induction, @JoeAldinger will finish this review.

**Review by JoeAldinger — COMMENTED** [review]
small suggestion, nice work on RNs.

**Pull request merged**
