### PR TITLE
Update cluster maximums for OpenShift 4.6

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit updates the cluster tested maximums based on the Performance
and Scale testing done for OpenShift 4.6 including number of nodes and
number of pods per cluster.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@ahardin-rh PTAL. We also have a PR open against enterprise-4.6 branch which updates the limits and adds information around the environment on which the cluster maximums were tested: https://github.com/openshift/openshift-docs/pull/27917.

**Comment by chaitanyaenr** [comment]
cc: @jtaleric @mffiedler

**Comment by ahardin-rh** [comment]
LGTM! @mffiedler Once we get your ack, we should be good to go. Thanks!

**Review by mffiedler — APPROVED** [review]
LGTM

**Pull request merged**
