### PR TITLE
Bug 1763876, Pull secret can be downloaded as a file or copied to clipboard

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1763876

@maxwelldb can you confirm this change?

### CODE REVIEW

**Comment by maxwelldb** [comment]
Looks copacetic. :+1:

**Comment by codyhoag** [comment]
@maxwelldb thanks for the speedy review! Do you mind merging/cherry-picking? I don't have permissions for that yet.

**Comment by maxwelldb** [comment]
@codyhoag Oof. Options:

1. Update your master from this one, force push here, and see if that fixes the problem. 
2. Cherrypick this change onto updated enterprise-4.2 and enterprise-4.3 branches in separate PRs.

**Comment by maxwelldb** [comment]
Seems good in spite of the bot's errors. Verify, but probably NM.

**Comment by codyhoag** [comment]
Thanks, @maxwelldb. I think it's a false alarm, but I'll check into it. As you said, it appears the commits were OK. I'll check my workflow and see what the bot is having issues with.

**Comment by vikram-redhat** [comment]
Weird errors

**Comment by codyhoag** [comment]
@vikram-redhat agreed! I rebased before I pushed, so I was a little dumbfounded by the errors. All seems to be working OK on my PRs today, so I guess I can chalk it up to a one-time glitch. :thinking:

**Pull request merged**
