### PR TITLE
Adding --incremental and --no-cache flags to start-build

### PR DESCRIPTION
**Pull request by coreydaley**
Trello Card: [link](https://trello.com/c/QDZ4fSCo/1011-5-allow-incremental-and-nocache-to-be-specified-on-build-request-builds)

Depends on: https://github.com/openshift/origin/pull/16014

### CODE REVIEW

**Comment by coreydaley** [comment]
@openshift/team-documentation ptal

**Comment by coreydaley** [comment]
[(5) Allow incremental and nocache to be specified on build request [builds]](https://trello.com/c/QDZ4fSCo/1011-5-allow-incremental-and-nocache-to-be-specified-on-build-request-builds)

**Comment by bmcelvee** [comment]
@coreydaley Is this waiting on openshift/origin#15994 before it can be merged?

**Comment by coreydaley** [comment]
@bmcelvee doh, sorry, it's waiting on https://github.com/openshift/origin/pull/16014, I updated the comment with the correct pull request (not sure how that other one got in there)

**Comment by bmcelvee** [comment]
@coreydaley Ah ok, cool! It looks fine to me. :) When it's ready to merge, I'll open a follow-up PR with some very minor style edits.

**Comment by coreydaley** [comment]
@bmcelvee https://github.com/openshift/origin/pull/16014 has merged, so you should be good to go with this PR now.

Thanks!

**Comment by bmcelvee** [comment]
Thanks, @coreydaley!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../cli_reference/basic_cli_operations.adoc#cli-reference-basic-cli-operations[Developer CLI Operations]
|Added `--incremental` and `--no-cache` flags to the xref:../cli_reference/basic_cli_operations.adoc#start-build[start-build] section.
%

**Comment by vikram-redhat** [comment]
@bmcelvee - I am guessing this is for Future Release, not Next Release, since it is for 3.7.

**Pull request merged**
