### PR TITLE
[WIP] OSDOCS-876: Adding release notes for bound service account tokens

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-876

Preview: http://file.rdu.redhat.com/~ahoffer/2020/OSDOCS-876-rn/release_notes/ocp-4-4-release-notes.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
The link in this PR won't work until #21118 is merged.

**Comment by sheriff-rh** [comment]
LGTM!

**Comment by marun** [comment]
LGTM

**Comment by xingxingxia** [comment]
LGTM, thanks.

**Pull request merged**
