### PR TITLE
CNV#46303: [enterprise-4.16] Issue in file virt/virtual_machines/creating_vms_custom/virt-creating-vms-from-container-disks.adoc

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14+

Issue: [CNV-46303](https://issues.redhat.com/browse/CNV-46303)

Link to docs preview: [Building and uploading a container disk](https://82082--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/virtual_machines/creating_vms_custom/virt-creating-vms-from-container-disks.html)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
Hi @matthewsecaur, Can you please take a look at this fix for the bug you reported? The fix will be applied to the docs for 4.14 and later. (The information isn't included in versions before 4.14.) Thanks.

**Comment by matthewsecaur** [comment]
Hi, @aspauldi I ran through the docs and the steps worked fine this time. Thanks!

**Comment by aspauldi** [comment]
Hi @dshchedr, Can you take a look and this bug fix and provide approval if it looks okay? Thanks!

**Pull request merged**
