### PR TITLE
[enterprise-4.13] OCPBUGS-36911: Update PTP docs as per the Concious Language initiative

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OCPBUGS-36911

Link to docs preview:
https://85786--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.html#ztp-sno-du-configuring-ptp_sno-configure-for-vdu 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]
/lgtm

**Comment by tmalove** [comment]
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

Direct preview link: https://85786--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.html#ztp-sno-du-configuring-ptp_sno-configure-for-vdu

**Pull request merged**
