### PR TITLE
CNV#36931: Updating machine type section for 4.14+

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.14+

Issue: [CNV-36931](https://issues.redhat.com//browse/CNV-36931)

Link to docs preview: https://69791--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/updating/upgrading-virt#virt-rhel-9_upgrading-virt

QE review:
- [x] QE has approved this change.

Additional information: This section was written for 4.13 and needs to be updated to make sense in 4.14+.

### CODE REVIEW

**Comment by ousleyp** [comment]
Hi @dshchedr, can you please review this PR? Thanks!

**Review by dshchedr — COMMENTED** [review]
_

**Pull request merged**
