### PR TITLE
CNV-18452-migration-policies-ui

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: [CNV-18452](https://issues.redhat.com//browse/CNV-18452)

Link to docs preview: [Configuring live migration policies](https://54238--docspreview.netlify.app/openshift-enterprise/latest/virt/live_migration/virt-configuring-live-migration-policies.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by avivtur** [comment]
Hi @apinnick 
LGTM from my side :)

**Review by lkladnit — APPROVED** [review]

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM

**Pull request merged**
