### PR TITLE
Update running-compliance-scans.adoc

### PR DESCRIPTION
**Pull request by StevenBarre**
Add namespace to ScanSettingBinding

### CODE REVIEW

**Comment by StevenBarre** [comment]
Happy birthday to this super simple PR! 🍰 📆 🎉 I guess improvements to the docs are not welcome from customers?

Going to tag a bunch of people that have merged PRs recently hoping that someone notices me. /cc @jboxman-rh @ahardin-rh @EricPonvelle @kalexand-rh @apinnick @maxwelldb @miabbott

**Comment by jboxman-rh** [comment]
Asking on Slack if someone knows who can QE this so it can get merged.

**Comment by StevenBarre** [comment]
> Asking on Slack if someone knows who can QE this so it can get merged.

Which Slack is this?

**Comment by jboxman-rh** [comment]
@StevenBarre the CoreOS Slack with all the OCP channels; Not sure it's open to the public.

**Pull request merged**
