### PR TITLE
Two smol fixes for the Asciidoctor validate script

### PR DESCRIPTION
**Pull request by aireilly**
1. Add `_unused_topics` folder to list of excluded files
2. Don't validate an assembly if it is not in a topic_map

Example build: https://app.travis-ci.com/github/openshift/openshift-docs/jobs/603203701

### CODE REVIEW

**Comment by aireilly** [comment]
@gaurav-nelson @kowen-rh PTAL - two smol fixes to the asciidoctor validate script

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
