### PR TITLE
RHDEVDOCS-4511 Pipelines 1.6.4 Release Notes

### PR DESCRIPTION
**Pull request by sounix000**
- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: `enterprise-4.9`, `enterprise-4.10`, `enterprise-4.11`, `enterprise-4.12`
- **JIRA issues**: [RHDEVDOCS-4511 Pipelines 1.6.4 RN](https://issues.redhat.com/browse/RHDEVDOCS-4511)
- **Preview pages**: [Pipelines 1.6.4 Release Notes](http://file.pnq.redhat.com/sosarkar/Pipelines-1-6-4-RN/cicd/pipelines/op-release-notes.html#release-notes-1-6-4_op-release-notes)
- **SME review**: @rupalibehera           
- **Peer-review**: @gabriel-rh

### CODE REVIEW

**Comment by rupalibehera** [comment]
@sounix000 LGTM

**Review by gabriel-rh — APPROVED** [review]
/lgtm

**Pull request merged**
