### PR TITLE
TELCODOCS:766 - update variables for new OSC version

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): Only 4.12

Issue:
[TELCODOCS-766](https://issues.redhat.com/browse/TELCODOCS-766)

Link to docs preview: N/A—this change was only to the attributes file.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
Merge review looks good.

**Comment by MirzWeiss** [comment]
@skrthomas—here to request a merge, now that merge freeze is over :)

**Comment by MirzWeiss** [comment]
@skrthomas or @kalexand-rh could I get a merge on this PR please?

**Pull request merged**
