### PR TITLE
remove meaningless "{" empty file

### PR DESCRIPTION
**Pull request by jeffrey4l**
This file must be added by a accident by commit
be4ad40e866c425d1b36067017943cc219240578

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@soltysh, do you object to removing this file?

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, any objection to pulling this file?

**Comment by mburke5678** [comment]
@kalexand-rh I have no objections. Be interesting to see how it got there.

**Comment by kalexand-rh** [comment]
My theory is that because it was at the very bottom of the PR, no one noticed that it was included.

**Pull request merged**
