### PR TITLE
TELCODOCS-420: Adding new metrics for MetalLB

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-420](https://issues.redhat.com//browse/TELCODOCS-420): Adds some new metrics to MetalLB

Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/TELCODOCS-420

Link to docs preview:
https://69136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-troubleshoot-support.html#nw-metallb-metrics_metallb-troubleshoot-support

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by liornoy** [comment]
Hi @rohennes thanks for the PR, I think's it's good that you didn't include the "FRR only", it makes perfect sense.
My only comment is that maybe on the BGP section, every place we have "to a BGP peer" we should instead write: "...each BGP peer" so that we will be consistent with the BFD section.

**Review by kononovn — APPROVED** [review]
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
