### PR TITLE
Bug 1490806 Changed vmware vsphere info to be more accurate

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1490806

Might need to be more specific with the information. Will verify in the BZ.

### CODE REVIEW

**Review by knobunc — APPROVED** [review]
LGTM.  Thanks Brice

**Comment by bfallonf** [comment]
Thanks @knobunc 

@openshift/team-documentation peer review please?

**Comment by gaurav-nelson** [comment]
@bfallonf LGTM

**Comment by gaurav-nelson** [comment]
The link on 947 [https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network-policy.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network-policy.md) is failing!

**Comment by bfallonf** [comment]
Thanks @gaurav-nelson . I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../admin_guide/managing_networking.adoc#admin-guide-manage-networking[Managing Networking]
|Added more information to the xref:../admin_guide/managing_networking.adoc#admin-guide-limit-pod-access-important-deployment-considerations[VMWare vSphere] section.
%

**Pull request merged**
