### PR TITLE
Rewrite vague phrase: "at a point in time"

### PR DESCRIPTION
**Pull request by Miciah**
I don't know what information this phrase might have been intended to convey. It did make me LOL, but I don't think that is what we're going for here.

### CODE REVIEW

**Comment by adellape** [comment]
The LOLs were merely a fun side-effect.

I believe it was supposed to suggest that the example generated config file represents defaults at the time of writing, which may include new or deprecated parameters if a newer version was released and the config file example wasn't updated just so.

We've been trying to keep it up to date and adjusted as we go, though. I agree the phrase doesn't really help or add anything useful, and the sentence that follows it conveys what's important anyway.

**Comment by Miciah** [comment]
How about if we rewrite the sentences to say something like "generated with the default values as of the most recent release" or "as of writing"?

**Comment by adellape** [comment]
"As of writing" worksforme.

**Comment by Miciah** [comment]
Thanks! Updated.

**Comment by adellape** [comment]
:+1:

**Comment by Miciah** [comment]
Danke sehr!

**Pull request merged**
