### PR TITLE
Fix non existing image in Serverless eventing

### LINKED ISSUE #23465: gcr.io/hello-minikube-zero-install/hello-node image does not exist
# Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/serverless/knative_eventing/serverless-apiserversource.html

### What needs fixing?

- The image `gcr.io/hello-minikube-zero-install/hello-node` does not exist in [Using ApiServerSource](https://docs.openshift.com/container-platform/4.4/serverless/knative_eventing/serverless-apiserversource.html). 
- It is not a big problem as it could produce event log, but very confusable. It should use the existing image in `quay.io`.

/cc @abrennan89 @matzew @maschmid

### PR DESCRIPTION
**Pull request by nak3**
Fixes https://github.com/openshift/openshift-docs/issues/23465

This patch fixes non existing image.
Ideally we should use an official image, but we don't have it yet. So use an image in quay.io.

/cc @abrennan89 @matzew

### CODE REVIEW

**Review by abrennan89 — APPROVED** [review]
looks good to me, thanks Kenjiro!

**Review by bergerhoffer — COMMENTED** [review]
LGTM! Just need to know which versions this is for.

**Pull request merged**
