### PR TITLE
[OCPBUGS-14619]: Update order of etcd restore docs

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-14619

Link to docs preview: https://61924--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lahinson** [comment]
@palonsoro @geliu2016 PTAL when you can and let me know if these changes resolve the issue described in https://issues.redhat.com/browse/OCPBUGS-14619. Thank you!

**Comment by palonsoro** [comment]
Sorry, I was out. It looks perfect to me.

/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
