### PR TITLE
Fixing var names

### PR DESCRIPTION
**Pull request by sferich888**
@ahardin-rh can you review based on my changes in https://github.com/openshift/origin/pull/9619

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sferich888 LGTM! Is this for 3.3?

**Comment by sferich888** [comment]
3.3 provided, that https://github.com/openshift/origin/pull/9619 gets merged.

**Comment by adellape** [comment]
Added [DO NOT MERGE] til https://github.com/openshift/origin/pull/9619 is in.

**Comment by ahardin-rh** [comment]
@sferich888 looks like this is ready to merge. Correct? :steam_locomotive:

**Comment by sferich888** [comment]
Should be

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Updated the xref:../architecture/core_concepts/routes.adoc#haproxy-template-router[Router Configuration Parameters] table.
%

**Pull request merged**
