### PR TITLE
OSDOCS-2129: Add upstream gateway API documentation - revert

### PR DESCRIPTION
**Pull request by bmcelvee**
Reverts additions made in: https://github.com/openshift/openshift-docs/pull/33631. 

This is the content being removed: https://docs.okd.io/latest/networking/about-contour-operator.html

No QE review needed.

### CODE REVIEW

**Comment by bmcelvee** [comment]
@mcurry-rh and @Miciah here's the PR to remove the OKD Contour content.

**Comment by mjpytlak** [comment]
@bmcelvee All of you removed content LGTM. :)

**Comment by bmcelvee** [comment]
@mjpytlak Thank you! Yep, going ahead with the merge.

**Pull request merged**
