### PR TITLE
OSDOCS-10984 OSDOCS-11291 Minor fix to section title and firewall

### PR DESCRIPTION
**Pull request by laubai**
Version(s): 4.15+

Issue:
- https://issues.redhat.com/browse/OSDOCS-10984
- https://issues.redhat.com/browse/OSDOCS-11291

Link to docs preview:
https://78762--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-aws-private-creating-cluster.html
https://78762--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html

QE review: Minor enough to not need review IMO - api.openshift.com is a well-established requirement
- [x] QE has approved this change.

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Review by EricPonvelle — COMMENTED** [review]
One small clarification item.

**Review by jneczypor — COMMENTED** [review]
LGTM. 
If you want to make an enhancement while you are already in the docs, feel free to change the "This document..." lines at the top of the [page](https://78762--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-aws-private-creating-cluster.html), since I know we try to avoid that type of prescriptive writing.
Screenshot 2024-07-16 at 12 13 06 PM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by jeana-redhat** [comment]
@laubai noticed the QE box/your comment after review - this PR should still get an ack from QA engg please. I'll mark it as "ok to merge" though because otherwise looks ready. If you relabel for merge review once you have an ack someone should get it in w/o furhter churn :)

**Comment by laubai** [comment]
Noting that merge review has already happened so should be good to merge now QE has approved based on Jeana's comment above :)

**Comment by jeana-redhat** [comment]
> Noting that merge review has already happened so should be good to merge now QE has approved based on Jeana's comment above :)

thank you for getting the ack! :clinking_glasses:

**Pull request merged**
