### PR TITLE
install_config/registry/registry_known_issues: use oc patch

### PR DESCRIPTION
**Pull request by php-coder**
This PR replaces usage of `oc get`/`sed`/`oc replace` by single `oc patch` command.

PTAL @openshift/team-documentation

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@php-coder Thanks! Is this targeted for 3.6?

**Comment by php-coder** [comment]
I don't remember exactly when `oc patch` was introduced by it definitely was here in 3.5 too.

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
Simplified command. No revision history needed.

**Pull request merged**
