### PR TITLE
CFE 1136: Removed ExternalRouteCertificate from the understanding feature gates section

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/CFE-1136 and https://issues.redhat.com/browse/OCPBUGS-36479

Link to docs preview: https://82464--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-about_nodes-cluster-enabling

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by chiragkyal** [comment]
/lgtm
Thank you!

**Comment by lihongan** [comment]
LGTM
Thank you!

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
