### PR TITLE
OSDOCS-3339 - Adding network verfication content for OSD and ROSA

### PR DESCRIPTION
**Pull request by pneedle-rh**
**Please do not merge this PR.**

This applies to `main`, `enterprise-4.11` and `enterprise-4.10`.

The PR relates to https://issues.redhat.com/browse/OSDOCS-3339. The PR adds network verification content to the OSD and ROSA libraries.

The previews are as follows:

### **OSD**

* **Introduction to OpenShift Dedicated** -> **Policies and service definition** -> **OpenShift Dedicated service definition** -> **Networking** -> [**Network verification**](http://file.fab.redhat.com/pneedle/pr46772/osd/osd_architecture/osd_policy/osd-service-definition.html#osd-network-verification_osd-service-definition)
* **Networking** -> [**Network verification**](http://file.fab.redhat.com/pneedle/pr46772/osd/networking/network-verification.html)

### **ROSA**

* **Introduction to ROSA** -> **Policies and service definition** -> **ROSA service definition** -> **Networking** -> [**Network verification**](http://file.fab.redhat.com/pneedle/pr46772/rosa/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-network-verification_rosa-service-definition)
* **Networking** -> [**Network verification**](http://file.fab.redhat.com/pneedle/pr46772/rosa/networking/network-verification.html)

### CODE REVIEW

**Comment by pneedle-rh** [comment]
@wgordon17, @jharrington22, @xueli181114 and @yuwang-RH hi! Can you please review this doc PR? Thanks!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request closed without merging**
