### PR TITLE
OSSMDOC-636: fix typo in diagram

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.6-4.11

Issue: https://issues.redhat.com/browse/OSSMDOC-636

Link to docs preview: http://file.bos.redhat.com/tokeefe/OSSMDOC-636/service_mesh/v2x/ossm-architecture.html

Additional information:
Peer Review: jstickler

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@JStickler this is ready for peer review, and if it looks good, it can be merged.

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
