### PR TITLE
BZ1770271: Add local volume to PV types

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ1770271](https://bugzilla.redhat.com/show_bug.cgi?id=1770271)

### CODE REVIEW

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL - merge to master, CP to 4.2 and 4.3 only. Thanks!

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bobfuru** [comment]
Manual CP to 4.2 in [PR 18026](https://github.com/openshift/openshift-docs/pull/18026)

**Pull request merged**
