### PR TITLE
GH#49479, updated ACM doc link for 4.11+

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses https://github.com/openshift/openshift-docs/issues/49479 for 4.11+

Version(s):
For 4.11+

Link to docs preview:
https://51181--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-deploying-disconnected.html#ztp-pgt-config-best-practices_ztp-deploying-disconnected

### CODE REVIEW

**Review by aireilly — COMMENTED** [review]
LGTM

**Comment by ahardin-rh** [comment]
No QE or SME review needed. Thanks!

**Pull request merged**
