### PR TITLE
GlusterFS: modifying installation verbiage to deploy clusters

### PR DESCRIPTION
**Pull request by netzzer**
Modify verbiage to deploy GlusterFS clusters with OpenShift deployment.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@jhou1 can you PTAL?

@gaurav-nelson - can you do a peer review?

**Comment by gaurav-nelson** [comment]
Thanks for the PR @netzzer 

I went through the suggested change and recommend following modifications:
```
// Module included in the following assemblies:
//
// install_config/persistent_storage/persistent_storage_glusterfs.adoc
// - #install-example-basic
// - #install-example-basic-external
// - #install-example-registry
// - #install-example-infra
// - #install-example-full
// - #install-example-full-external

+
[NOTE]
====
The preceding steps only provide some of the options that must be added to the
inventory file. Use the complete inventory file to deploy {gluster}.
====

. Run the installation playbook and provide the relative path for the inventory
file as an option.
+
** For a new {product-title} installation:
```

This does include some extra bits which we might have missed in previous iteration.

Please rebase and squash to one commit when you do update. 👍

**Comment by jhou1** [comment]
@wkshi PTAL

**Comment by wkshi** [comment]
Looks good.

**Review by gaurav-nelson — CHANGES_REQUESTED** [review]
https://github.com/openshift/openshift-docs/pull/11234#issuecomment-409407536

**Comment by gaurav-nelson** [comment]
@netzzer I can merge this one after the changes. Please rebase and squash to one commit when you do update.

**Comment by gaurav-nelson** [comment]
@netzzer Can you please check https://github.com/openshift/openshift-docs/pull/11234#issuecomment-409407536 and update. I can go ahead and merge it one you do.

**Comment by vikram-redhat** [comment]
@netzzer can you please take a look?

**Comment by gaurav-nelson** [comment]
Closing this in favor of #11720

**Pull request closed without merging**
