### PR TITLE
[OCPBUGS-8100]: Update the OPP user guide for the latest product versions

### PR DESCRIPTION
**Pull request by tmalove**
[OCPBUGS-8100](https://issues.redhat.com/browse/OCPBUGS-8100)

Version: This PR is based on the ‘opp-docs’ repo and when merged, it should be in that branch only. The OPP doc is not versioned. Add this PR to the ‘Continuous Release’ milestone.

Link to docs preview (3/27): http://file.rdu.redhat.com/tlove/opp-ocpbugs-8100-tlove/architecture/opp-architecture.html#opp-architecture-support_opp-architecture

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
@lmaynard88 Will you review for ACS? Thanks!
@ascerra  Will you review the updated versions? Thanks!

**Comment by lmaynard88** [comment]
@tmalove LGTM. thx!

**Comment by tmalove** [comment]
Hi @ascerra @BillDett Just a friendly reminder to ack these version updates at your earliest convenience. Thanks!

**Comment by BillDett** [comment]
@tmalove LGTM!

**Comment by tmalove** [comment]
Hi @ascerra  will you ack the version updates at your earliest? Thanks!

**Comment by oramraz** [comment]
@tmalove LGTM!

**Comment by tmalove** [comment]
@kalexand-rh  I will add attributes for the version numbers in the common attributes file. This will make for 'cleaner' version updates. Thx!

**Pull request merged**
