### PR TITLE
Update master/worker subnet CIDR examples

### PR DESCRIPTION
**Pull request by codyhoag**
Followup to #32061; the examples for GCP were missed, so updating them here.

Preview: https://deploy-preview-35462--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-creating-gcp-vpc_installing-gcp-user-infra-vpc

### CODE REVIEW

**Comment by codyhoag** [comment]
@tsze-redhat can you verify? This is following the updates introduced in 4.8 for the GCP machine CIDRs. Thanks!

**Comment by tsze-redhat** [comment]
LGTM!
Thanks.

**Review by adellape — APPROVED** [review]
:+1:

**Pull request merged**
