### PR TITLE
Remove unsupportedConfigOverrides from documentation

### PR DESCRIPTION
**Pull request by soltysh**
/assign @bergerhoffer 
/cc @deads2k

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Hi @sferich888 @xltian @vikram-redhat @tkatarki 

We're removing this section, "Configuring quota synchronization period", from the 4.2-4.5 docs because it uses the `unsupportedconfigOverrides` field, which is not supported.

Can each of you please ack this removal, or let me know if there are any concerns with removing this? 

Thanks!

**Comment by vikram-redhat** [comment]
Ack

**Comment by xltian** [comment]
ACK

**Comment by sferich888** [comment]
ACK

**Comment by vikram-redhat** [comment]
@bergerhoffer we received ack from Mike B on email so we should be good to go with this, as long as you have already sent out notifications emails to the lists.

**Comment by bergerhoffer** [comment]
Related PRs for specific versions:

* 4.5: https://github.com/openshift/openshift-docs/pull/22452
* 4.4: https://github.com/openshift/openshift-docs/pull/22453
* 4.3: https://github.com/openshift/openshift-docs/pull/22454
* 4.2: https://github.com/openshift/openshift-docs/pull/22455

**Pull request merged**
