### PR TITLE
BZ-1496982 Removed experimental support wording as this is a supported feature

### PR DESCRIPTION
**Pull request by mrobson**

### CODE REVIEW

**Comment by mrobson** [comment]
@openshift/team-documentation another one @ https://bugzilla.redhat.com/show_bug.cgi?id=1496982

**Comment by mburke5678** [comment]
@mrobson LGTM. This change is for 3.6 only?

**Comment by mrobson** [comment]
@mburke5678 yes, 3.6+.

**Comment by mburke5678** [comment]
[rev_history]
|xref:../admin_guide/encrypting_data.adoc#admin-guide-encrypting-data-at-datastore[Encrypting Data at Datastore Layer]
|Removed the "experimental support" language for the data encryption feature, as the feature is fully supported as of v3.6.
%

**Pull request merged**
