### PR TITLE
osdocs-631 installing default cluster on Azure

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://jira.coreos.com/browse/OSDOCS-631

I'm waiting for some feedback from engineering on the related issues, but here's a WIP draft.

Built draft's here: https://osdocs631--ocpdocs.netlify.com/openshift-enterprise/latest/installing/installing_azure/installing-azure-default.html

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@abhinavdahiya, @jhixson74, does this information about the default Azure installation sound right to you? (I have a separate PR to describe the account configuration, but I want to see the change for CORS-1172 before I finish it.)

**Comment by kalexand-rh** [comment]
@abhinavdahiya, @jhixson74, will you PTAL?

**Review by jhixson74 — APPROVED** [review]

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, PTAL

**Comment by ahardin-rh** [comment]
LGTM :rocket:

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Pull request merged**
