### PR TITLE
[OSDOCS-4165]: Enabling Azure boot diagnostics on compute machines

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-4165](https://issues.redhat.com//browse/OSDOCS-4165)

Link to docs preview:
- [Enabling Azure boot diagnostics on compute machines](http://file.rdu.redhat.com/~jrouth/OSDOCS-4165-azure-worker-boot-diagnostics/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-azure-boot-diagnostics_creating-machineset-azure) (for global Azure)
- [Enabling Azure boot diagnostics on compute machines](http://file.rdu.redhat.com/~jrouth/OSDOCS-4165-azure-worker-boot-diagnostics/machine_management/creating_machinesets/creating-machineset-azure-stack-hub.html#machineset-azure-boot-diagnostics_creating-machineset-azure-stack-hub) (for Azure Stack Hub)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Changes look god, Azure docs for this feature only talk about blob as well so I think that's accurate.

Do we need an equivalent for control plane machine sets as well?

**Comment by jeana-redhat** [comment]
> Do we need an equivalent for control plane machine sets as well?

Is the process the same? The card said "workers" so I assumed this was for compute specifically, but if it also works for the control plane machine set I could add it as part of that work

**Comment by JoelSpeed** [comment]
Exactly the same process, just substitute control plane machineset for compute machine set

**Comment by jeana-redhat** [comment]
@sunzhaohua2 this is the docs PR for enabling Azure boot diagnostics that I messaged you about. PTAL for QA verification, and also let me know if this works for ASH in addition to global Azure.

**Comment by sunzhaohua2** [comment]
@jeana-redhat I checked this works on Azure Stack Hub. For "Procedure" it seems that we only need the second step `Add the diagnostics configuration`, like [Creating Spot VMs by using compute machine sets](https://52725--docspreview.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-creating-non-guaranteed-instance_creating-machineset-azure). If we take three steps and the first step is edit, the second step is add, the third step should be to save and delete the original machines, then the new machine will take effect, or if the third step is create, the first step should be clone a machineset and update machineset name, wdyt?

**Comment by jeana-redhat** [comment]
> If we take three steps and the first step is edit, the second step is add, the third step should be to save and delete the original machines, then the new machine will take effect, or if the third step is create, the first step should be clone a machineset and update machineset name, wdyt?

@sunzhaohua2 this is a really good point, and I appreciate you putting it so clearly. I think (in general) that the machine set docs are not consistent about if we expect a user to create a new machine set (based on copying one) or edit an existing one. In some cases that leads to a situation like this, where I have started one way and then finished the other (because I was looking at different topics for formatting).

I think the content needs a complete overhaul to become consistent, and I hope to do that in the near future. For now, I will rewrite this feature to be consistent with the "edit existing" workflow.

**Comment by sunzhaohua2** [comment]
/lgtm 
Thank you @jeana-redhat

**Review by sheriff-rh — APPROVED** [review]
Great work! :rocket:

**Pull request merged**
