### PR TITLE
BZ#1943587 WINC minor updates and typos

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1943587

Preview: https://deploy-preview-31538--osdocs.netlify.app/openshift-enterprise/latest/support/troubleshooting/troubleshooting-windows-container-workload-issues.html#collecting-kube-node-logs-windows_troubleshooting-windows-container-workload-issues

### CODE REVIEW

**Comment by codyhoag** [comment]
@sgaoshang PTAL

**Comment by sgaoshang** [comment]
@codyhoag LGTM, thanks.

**Review by rbo — CHANGES_REQUESTED** [review]
Please remove the space in `am d64` modules/creating-the-vsphere-windows-vm-golden-image.adoc:86 

Current version:
```
<component ....... processorArchitecture="am d64" ....versionScope="nonSxS">
```
Should be:
```
 <component ...... processorArchitecture="amd64" .....versionScope="nonSxS">
```
Thanks.

This typo is mention in BZ#1943587 too.

**Comment by codyhoag** [comment]
@rbo sorry about that; just updated :+1:

**Comment by mburke5678** [comment]
LGTM

**Pull request merged**
