### PR TITLE
Added syntax fix and new connect_to field for non-interactive install

### PR DESCRIPTION
**Pull request by tpoitras**
Bug 1270619 - https://bugzilla.redhat.com/show_bug.cgi?id=1270619

Added update to this user story as per feedback received during tech review with QE team.

### CODE REVIEW

**Comment by tpoitras** [comment]
waiting on final tech review before merging

**Comment by tpoitras** [comment]
tech review passed, bug complete, checking for rebase before merging

**Comment by tpoitras** [comment]
rebased, should be good to merge now

**Comment by adellape** [comment]
:+1:

**Pull request merged**
