### PR TITLE
BZ-1635251: Add auto rotation info and point to section with proper c…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ommand

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@rjhowe Can you review this update please and let me know if this is what you were thinking?

Preview: http://file.rdu.redhat.com/~ahoffer/2019/BZ-1635251/install_config/redeploying_certificates.html#redeploying-node-certificates

**Comment by bmcelvee** [comment]
LGTM!

**Comment by rjhowe** [comment]
LGTM

**Comment by bergerhoffer** [comment]
Hi @gpei - would you be the right person to QE review this update? Thanks!

For BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1635251

**Comment by gpei** [comment]
LGTM, thanks for the update!

**Pull request merged**
