### PR TITLE
Update tech prev featureset 412

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/api/blob/release-4.12/config/v1/types_feature.go#L111

### CODE REVIEW

**Comment by mwerner2113** [comment]
@nee1esh @tkatarki can you review that this list is accurate and tag a potential QE management contact to review as well? Thank you!

**Comment by mwerner2113** [comment]
@sunilcio can you provide QE review for this PR by EOD today for 4.12? Thank you and sorry for the short notice!

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
