### PR TITLE
adding missing components allowed for infrastructure nodes

### LINKED ISSUE #25472: [enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc
### Which section(s) is the issue in?
The components identified to be scheduled on infra nodes should also contain the accessory product that the customer could already have a subscription on. 
Or else RH is selling double subscriptions on components which normally  shouldn't happen.

### What needs fixing?
The list should (IMHO) comprehend 

- Quay (that maybe nominating it in the docs could spark some attention)
- 3Scale (the ctrl plane part)
- OCS
- Kafka (doubt on this as is not infrastructural per se)
- istio (the ctrl plane part)
- ACM (when will be released)
- etc.

### PR DESCRIPTION
**Pull request by vagnerfarias**
OpenShift Container Storage and Red Hat Quay may also be installed on infrastructure nodes. I'm also trying to clarify that OpenShift built-in container registry is allowed in infrastructure nodes, as "the container image registry" could be misinterpreted.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vagnerfarias Thank you for this!
@enxebre @jhou1 Can you please confirm this change or point me to the correct contacts? Thank you!

**Comment by ahardin-rh** [comment]
@enxebre @jhou1 PTAL. Thanks!

**Comment by ahardin-rh** [comment]
@ingvagabund Can you please review? Thanks!

**Comment by ingvagabund** [comment]
@ahardin-rh I am not familiar with the image registry. @smarterclayton or @sallyom might know better.

**Comment by dmage** [comment]
`Red Hat Quay` and `OpenShift Image Registry` are different registries. `OpenShift built-in container registry` aka `OpenShift Image Registry` and we have documented how to install it on infrastructure nodes.

Not sure about `Red Hat Quay` though. Why do we want to run it on infra nodes?

**Comment by bmcelvee** [comment]
+1 to @dmage's comment. OpenShift Container Platform Image Registry refers to the integrated registry. I'm not sure if Quay ships in the OCP payload or if it is technically an infrastructure component since it can be installed. 

@thomasmckay would you mind clarifying this for us, please? Thanks!

As Oleg mentioned in chat, we have a documented method for moving the default registry (e.g., if you choose to switch to using Quay): https://docs.openshift.com/container-platform/4.6/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets.

**Comment by thomasmckay** [comment]
@dmesser Please review

**Comment by dmesser** [comment]
@bmcelvee @dmage Red Hat Quay qualifies as an infrastructure workload suitable for running on OpenShift Infrastructure nodes, therefore not incurring subscriptions for OCP nodes. Red Hat Quay is an OpenShift Add-On like OpenShift Container Storage and does not ship with the payload.

**Comment by vagnerfarias** [comment]
Going through the comments here I realize that this change might be trickier than I thought initially. My goal wasn't to state that these components are included in OCP, but that they can be used in infrastructure nodes without consuming OCP subscriptions.

If you believe this information deserves to be in this section including any clarification that these components are "add-ons", I'd be happy to provide an updated text to be reviewed. Otherwise, it'd be better to close this PR.

**Comment by ahardin-rh** [comment]
@vagnerfarias Thank you!
@dmage @dmesser What are your thoughts? Should this be updated or closed?

**Comment by dmesser** [comment]
@ahardin-rh I think we could update it to say "this is the list of eligible infrastructure workloads that do not incur OpenShift Worker Subscriptions".

**Comment by ahardin-rh** [comment]
@vagnerfarias Please see the suggestion above. Are you able to make that change?

**Comment by dmesser** [comment]
Is it possible to get this resolved? The lack of this information is creating confusion among users.

**Comment by vagnerfarias** [comment]
> @vagnerfarias Please see the suggestion above. Are you able to make that change?

Looks like I have to rebase and I've never done it. Will do it over the weekend.

**Comment by ahardin-rh** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/29625

**Pull request closed without merging**
