### PR TITLE
BZ-2083251 fixed version requirements for UPI compute nodes

### PR DESCRIPTION
**Pull request by bscott-rh**
[BZ-2083251](https://bugzilla.redhat.com/show_bug.cgi?id=2083251)
CP to 4.10 and 4.11
[Doc preview](https://deploy-preview-45462--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-minimum-resource-requirements_installing-bare-metal)

### CODE REVIEW

**Comment by bscott-rh** [comment]
@xltian Please review at your convenience

**Comment by sdodson** [comment]
/lgtm
Thanks!

**Comment by bmcelvee** [comment]
LGTM

**Comment by bscott-rh** [comment]
@gpei please review at your convenience

**Comment by gpei** [comment]
LGTM

**Pull request merged**
