### PR TITLE
OSDOCS-3560: Updated Support coverage

### PR DESCRIPTION
**Pull request by EricPonvelle**
Version(s):
Enterprise-4.11+

Issue:
[OSDOCS-3560](https://issues.redhat.com/browse/OSDOCS-3560)

Link to docs preview:
[Responsibility assignment matrix in ROSA](https://51072--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-change-management_rosa-policy-responsibility-matrix)

QE review:
NEEDED

Additional information:
Removed an incorrect responsibility from SRE and added a new responsibility for the customer. I also added a link to "About machine pools" in a new additional resources section.

### CODE REVIEW

**Comment by xueli181114** [comment]
LGTM

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
