### PR TITLE
Multiple odo fixes.

### LINKED ISSUE #32435: [enterprise-4.7] Issue in file cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-java-application-with-a-database.adoc
### Which section(s) is the issue in?
CLI tools / Creating a Java application with a database

### What needs fixing?
The order of creation of database and app needs to be swapped as you can not create a service unless you are in a valid component folder:

step 1  Creating a Java MicroServices JPA application
step 2 Creating a database with odo

### LINKED ISSUE #32436: [enterprise-4.7] Issue in file cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-java-application-with-a-database.adoc
### Which section(s) is the issue in?
CLI tools / Creating a Java application with a database
Creating a Java MicroServices JPA application
Clone the sample application:

### What needs fixing?
First issue:
The following git clone will not work as the application is not at the master level
git clone https://github.com/redhat-developer/application-stack-samples
you need to clone the correct branch 
git clone -b jpa-sample https://github.com/redhat-developer/application-stack-samples.git

Second issue:
the following command did not show the same output as documentation   
         odo exec -- bash -c 'export | grep DATABASE'
but using the "env" would show the result:
        odo exec -- bash -c 'env | grep DATABASE'

### LINKED ISSUE #32439: [enterprise-4.7] Issue in file cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/using-devfiles-in-odo.adoc
### Which section(s) is the issue in?
Deploying a Java application using a devfile
Step 2.

### What needs fixing?
There is no java-spring-boot component
       odo create java-spring-boot myspring --starter
Should be as follow(no dash between spring and boot):
       odo create java-springboot myspring --starter

### PR DESCRIPTION
**Pull request by yhontyk**
Fixes https://github.com/openshift/openshift-docs/issues/32436 
Fixes https://github.com/openshift/openshift-docs/issues/32439
Fixes https://github.com/openshift/openshift-docs/issues/32435

Branch 4.7 and 4.8

### CODE REVIEW

**Review by jc-berger — APPROVED** [review]
LGTM from docs point of view.

**Review by neal-timpe — APPROVED** [review]

**Pull request merged**
