### PR TITLE
[enterprise-4.7] BZ2049266 Added note on configuring MTU during installation

### PR DESCRIPTION
**Pull request by Wiharris**
**This has the same work done for PR:** https://github.com/openshift/openshift-docs/pull/42239

Only for versions 4.7 and 4.8

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2049266#c4

Direct link to doc preview: https://deploy-preview-44066--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-government-region.html#installation-aws-about-government-region_installing-aws-government-region

QA: @yunjiang29

### CODE REVIEW

**Comment by sagidlow** [comment]
LGTM.

**Comment by Wiharris** [comment]
> /lgtm

Hi Yunfei, 

I wanted to confirm that the note for configuring MTU during installation, the same that was added in PR https://github.com/openshift/openshift-docs/pull/42239 for 4.10 and 4.11, applies for previous versions such as 4.7, 4.8, and 4.9?

**Comment by yunjiang29** [comment]
> > /lgtm
> 
> Hi Yunfei,
> 
> I wanted to confirm that the note for configuring MTU during installation, the same that was added in PR #42239 for 4.10 and 4.11, applies for previous versions such as 4.7, 4.8, and 4.9?



> > /lgtm
> 
> Hi Yunfei,
> 
> I wanted to confirm that the note for configuring MTU during installation, the same that was added in PR #42239 for 4.10 and 4.11, applies for previous versions such as 4.7, 4.8, and 4.9?

Yes.

**Pull request merged**
