### PR TITLE
OCPBUGS#13638: Important section under discovery for local storage de…

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.11, 4.12, 4.13, 4.14, 4.15

Issue:
[OCPBUGS-13638](https://issues.redhat.com/browse/OCPBUGS-13638)

Link to docs preview:
[important section is modified for Automating discovery and provisioning for local storage devices](https://69894--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-local#local-storage-discovery_persistent-storage-local)

QE review:
- [x] QE approval required.

### CODE REVIEW

**Comment by bkunal** [comment]
@aravipra LGTM

**Comment by duanwei33** [comment]
LGTM

**Pull request merged**
