### PR TITLE
Remove duplicate content

### PR DESCRIPTION
**Pull request by lrx0014**
Typo fixed: 
Remove the duplicate content: master.example.com

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@adellape, will you PTAL?

**Review by adellape — APPROVED** [review]
LGTM

**Comment by vikram-redhat** [comment]
@jianlinliu bump.

@xltian

**Comment by jianlinliu** [comment]
LGTM. When I was reviewing the PR for https://bugzilla.redhat.com/show_bug.cgi?id=1589952, I missed the duplicate content.

**Comment by kalexand-rh** [comment]
Thanks @jianlinliu! I'll apply it back to 3.9.

**Pull request merged**
