### PR TITLE
[GH#53021]: Fixed typos in the "Installing distributed tracing" section

### LINKED ISSUE #53021: [enterprise-4.9] Issue in file distr_tracing/distr_tracing_install/distr-tracing-installing.adoc
### Which section(s) is the issue in?
* [distributing tracing platform](https://docs.openshift.com/container-platform/4.9/distr_tracing/distr_tracing_install/distr-tracing-installing.html#distr-tracing-jaeger-operator-install_install-distributed-tracing)
* [Installing the Red Hat OpenShift distributed tracing data collection Operator] https://docs.openshift.com/container-platform/4.9/distr_tracing/distr_tracing_install/distr-tracing-installing.html#distr-tracing-install-otel-operator_install-distributed-tracing)

### What needs fixing?
* Replace "Type distributing tracing platform into the filter to locate the Red Hat OpenShift distributed tracing platform Operator." with "Type distributed tracing platform into the filter to locate the Red Hat OpenShift distributed tracing platform Operator."
* Replace "Type distributing tracing data collection into the filter to locate the Red Hat OpenShift distributed tracing data collection Operator." with "Type distributed tracing data collection into the filter to locate the Red Hat OpenShift distributed tracing data collection Operator."

### PR DESCRIPTION
**Pull request by dearrudam**
Version(s):
4.9+

Issue:
fixes #53021

Link to docs preview:
[Installing the Red Hat OpenShift distributed tracing platform Operator](https://53862--docspreview.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_install/distr-tracing-installing.html#distr-tracing-jaeger-operator-install_install-distributed-tracing)
[Installing the Red Hat OpenShift distributed tracing data collection Operator](https://53862--docspreview.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_install/distr-tracing-installing.html#distr-tracing-install-otel-operator_install-distributed-tracing)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by dearrudam** [comment]
@openshift/team-documentation 
@kalexand-rh 
Could someone review my PR, please?

**Review by hbelmiro — APPROVED** [review]
LGTM. 
Thank you @dearrudam.

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
@iblancasa, will you PTAL?

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
