### PR TITLE
[enterprise-4.8] OSDOCS-2711 Add known issue and info for projected volumes and Windows pods

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2711

This will be manually backported for OCP 4.7.

Previews:
- [Known issue](https://deploy-preview-37811--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-3-x.html#wmco-3-1-0-known-issues)
- [Admonition](https://deploy-preview-37811--osdocs.netlify.app/openshift-enterprise/latest/nodes/containers/nodes-containers-projected-volumes.html#nodes-containers-projected-volumes-about_nodes-containers-projected-volumes)

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by codyhoag** [comment]
@rrasouli can you re-review this slight modification of what you verified in #37587?

**Comment by codyhoag** [comment]
@rrasouli bump. Can you verify this? Thanks!

**Comment by codyhoag** [comment]
@sgaoshang @rrasouli resurfacing this. Can you give a QE ack? Thanks!

**Comment by lpettyjo** [comment]
Line 74 in 2nd file: "like someone with the `ContainerAdministrator` role" should be "such as someone with..." as per ISG.

**Comment by lpettyjo** [comment]
Line 81 in the 2nd file: " the pod gets stuck in the": I'd recommend "the pod remains in the...". No ISG reference, but it is less wordy and slangy sounding.

**Comment by codyhoag** [comment]
Follow-up PR for additional peer review comments: #39488

**Pull request merged**
