### PR TITLE
OSSM: Add instructions to remove CNI cluster resources

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
AFAICT this applies to all 4.x branches, since this is OSSM 1.0
cc @neal-timpe @rcernich

**Review by rcernich — APPROVED** [review]

**Comment by neal-timpe** [comment]
@tvieira Does this look right to you?

**Review by tvieira — APPROVED** [review]
LGTM

**Comment by neal-timpe** [comment]
@JStickler Tiago from QE and Rob from engineering have signed off. Do you want to merge this to master and cherry pick it to 4.3 and 44 and I'll make separate prs to 41 and 42?

**Review by JStickler — APPROVED** [review]

**Pull request merged**
