### PR TITLE
adjust declarative sample to match recommendation

### PR DESCRIPTION
**Pull request by gabemontero**
More pivoting out of https://github.com/openshift/jenkins/issues/498

@openshift/sig-developer-experience @bmcelvee ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by bmcelvee** [comment]
LGTM 🌞

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/dev_tutorials/openshift_pipeline.adoc#dev-guide-openshift-pipeline-builds[OpenShift Pipeline Builds]
|Updated the declarative sample in xref:../dev_guide/dev_tutorials/openshift_pipeline.adoc#the-jenkinsfile[The Jenkinsfile] section.
%

**Comment by vikram-redhat** [comment]
@bmcelvee  this doesn't apply to Dedicated docs?

**Comment by bmcelvee** [comment]
@vikram-redhat the OpenShift Pipeline Builds topic is not in the Dedicated docs. We can add the topic if it belongs in Dedicated.

**Comment by vikram-redhat** [comment]
@bmcelvee  - Ah I see the issue. If I understand correctly, openshift_pipelines wasn't introduced till 3.7, and the docs for dedicated are at 3.6 atm. 

Unless @gabemontero says otherwise, I will add this the enterprise 3.7 and 3.9 branches (from which dedicated docs will be built.)

**Comment by gabemontero** [comment]
On Wed, Feb 21, 2018 at 5:42 AM, Vikram Goyal <notifications@github.com>
wrote:

> @bmcelvee <https://github.com/bmcelvee> - Ah I see the issue. If I
> understand correctly, openshift_pipelines wasn't introduced till 3.7, and
> the docs for dedicated are at 3.6 atm.
>
> Unless @gabemontero <https://github.com/gabemontero> says otherwise, I
> will add this the enterprise 3.7 and 3.9 branches (from which dedicated
> docs will be built.)
>
Assuming the original content is in the 3.7 branch, I'm good.

**Pull request merged**
