### PR TITLE
OSSM-4528: Update topic map to match assembly title

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OSSM-4528

Link to docs preview: https://63705--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-create-mesh

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mayleighnmyers — APPROVED** [review]
/lgtm

**Review by pbajjuri20 — APPROVED** [review]

**Comment by rh-tokeefe** [comment]
PR was rebased on 8/23/23. 

/label merge-review-needed

**Review by gwynnemonahan — APPROVED** [review]
LGTM

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
