### PR TITLE
CNV-21591: Fixed oc get vmis command syntax

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.10+

Issue: [CNV-21591](https://issues.redhat.com//browse/CNV-21591)

Link to docs preview: http://file.rdu.redhat.com/sjhala/cnv-21591/virt/virtual_machines/virt-manage-vmis.html#virt-listing-vmis-cli_virt-manage-vmis

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by djfjeff** [comment]
LGTM

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Review by jldohmann — APPROVED** [review]
/lgtm

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
