### PR TITLE
Fix how to create new alertmanager.yaml secret

### PR DESCRIPTION
**Pull request by duritong**
The way how it was described didn't work. A) There is no file config.yaml in the game here
and B) if you do create secret --from-file it will automatically add the base64 encoded content
of the file to data with the filename it read from.

This is broken in 4.2 configs as well, should be backported there.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm

**Comment by vikram-redhat** [comment]
@rh-max - can you please take a look?

**Comment by rh-max** [comment]
@duritong Thank you for the fix!
@vikram-redhat I'll rely on @brancz 's ACK of the changes, so lgtm. Could you please merge this to master and cherry-pick to enterprise-4.2 and enterprise-4.3? Thanks.

**Comment by vikram-redhat** [comment]
@rh-max  Waiting on QE ack.

**Comment by juzhao** [comment]
LGTM

**Pull request merged**
