### PR TITLE
[OSDOCS-6601]: Updating DR docs to reflect specificity to non-STS clusters

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-6601
Link to docs preview:

https://61620--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-backup-policy_rosa-service-definition
image

https://61620--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-disaster-recovery_rosa-policy-responsibility-matrix

image

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 and/or @yuwang-RH,
   Could you please provide QE review for this PR when you get a moment? Please and thank you! ML

**Comment by 0kashi** [comment]
lgtm

**Comment by xueli181114** [comment]
LGTM

**Comment by stevsmit** [comment]
lgtm!

**Pull request merged**
