### PR TITLE
Clarifying the behavior of the etcd operator

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://clarify-etcd-behavior--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-determine-state-etcd-member_replacing-unhealthy-etcd-member

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review this clarification?

Preview: https://clarify-etcd-behavior--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/replacing-unhealthy-etcd-member.html

**Comment by retroflexer** [comment]
Looks good to me.

**Comment by geliu2016** [comment]
There is minor err in section: "2.Review the output:"
The original output is not exact in my opinion: _ip-10-0-164-97.ec2.internal,ip-10-0-154-204.ec2.internal members are available,  have not started, ip-10-0-131-183.ec2.internal are unhealthy,  are unknown_
there is a bug for above output msg: https://bugzilla.redhat.com/show_bug.cgi?id=1821286#c5

I tried in my env, and got below output:
# oc get etcd -o=jsonpath='{range .items[0].status.conditions[?(@.type=="EtcdMembersAvailable")]}{.message}{"\n"}'

2 of 3 members are available, ip-10-0-150-139.us-east-2.compute.internal is unhealthy

Other parts LGTM, thanks Andrea

**Comment by bergerhoffer** [comment]
Great thanks @geliu2016! I actually was aware of this output change coming, and have prepared a section (which is currently commented out) here: https://github.com/openshift/openshift-docs/pull/20890/files#diff-0d35d43f3fe03f6932e37a0f76746439R30-R38

But it seems that I missed the PR actually getting merged, so I appreciate you catching it!

So I'll go ahead and merge in this PR and will submit a separate PR to switch to using the new output.

@retroflexer Can you confirm whether or not this output change went out in a 4.4 z-stream yet?

**Pull request merged**
