### PR TITLE
[INTERNAL-FIX] fixed-kbase-link

### PR DESCRIPTION
**Pull request by dfitzmau**
INTERNAL FIXES:

* Asciidoc character subs does not render on CP
* Link had "draft" in URL

Version:
4.14

Preview link:
https://67320--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-oci

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Comment by bergerhoffer** [comment]
Sorry ignore the cherry picks!

**Pull request merged**
