### PR TITLE
fixed indentation and API/Ingress specification to new format (apiVIPs…

### PR DESCRIPTION
**Pull request by frankfnord**
…/ingressVIPs)

fixed identation and API/Ingress specification to new format (apiVIPs/ingressVIPs)

Version(s):

4.13.10
Issue:

apiVIP/ingressVIP is deprecated and not working in recent OpenShift Releases
Link to docs preview:

[Sample customized install-config.yaml file for Nutanix](https://64954--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-nutanix-installer-provisioned#installation-nutanix-config-yaml_installing-nutanix-installer-provisioned)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mjpytlak — COMMENTED** [review]
Peer review LGTM.

@sgaoshang PTAL. Thank you.

**Comment by sgaoshang** [comment]
@mjpytlak Just noticed that shall we also update API/Ingress here: https://64954--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned#installation-nutanix-config-yaml_installing-restricted-networks-nutanix-installer-provisioned

**Comment by mjpytlak** [comment]
@sgaoshang The file that was updated is shared across all of the Nutanix installation use cases, so we are good to go.

**Pull request merged**
