### PR TITLE
BZ1807524: Adds a warning about disabling SELiux

### PR DESCRIPTION
**Pull request by xenolinux**
Adds a warning about disabling SELiux

Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=1807524

Link to docs preview:
http://file.rdu.redhat.com/sdudhgao/selinux/nodes/nodes/nodes-nodes-working.html#nodes-nodes-kernel-arguments_nodes-nodes-working

http://file.rdu.redhat.com/sdudhgao/selinux/installing/install_config/installing-customizing.html#installation-special-config-kargs_installing-customizing

Additional information:

### CODE REVIEW

**Comment by mike-nguyen** [comment]
I noticed the BZ had a reference to https://github.com/openshift/openshift-docs/blob/main/modules/nodes-nodes-kernel-arguments.adoc.  Can we change `While not recommended for production systems, permissive mode can be helpful for debugging.` to `While not supported for production systems, permissive mode can be helpful for debugging.` in that doc also in this PR?  We need consistent messaging across the docs.

If you want to do that in a separate PR, then this PR LGTM.

**Comment by xenolinux** [comment]
> 

@mike-nguyen I addressed the changes in this PR. Could you please take a look?

**Comment by mike-nguyen** [comment]
LGTM

**Review by jldohmann — APPROVED** [review]
/lgtm

**Review by jeana-redhat — COMMENTED** [review]
Please remove hard wraps in the sections you're editing while you are in there. Otherwise LGTM.

**Comment by xenolinux** [comment]
> Please remove hard wraps in the sections you're editing while you are in there. Otherwise LGTM.

Addressed

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Comment by bergerhoffer** [comment]
@xenolinux The CPs to 4.6-4.9 failed. Can you please submit the manual CPs for these versions tomorrow? Thanks!

**Pull request merged**
