### PR TITLE
Documenting secrets in environment variables

### PR DESCRIPTION
**Pull request by jupierce**
@bparees

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, @openshift/team-documentation ptal

**Comment by vikram-redhat** [comment]
@bparees  - are there any parts here which are 3.4 or 3.5 specific only?

**Comment by bparees** [comment]
@vikram-redhat no, 3.3+

**Comment by vikram-redhat** [comment]
@gaurav-nelson - PTAL.

**Comment by gaurav-nelson** [comment]
Looks good to me. :seedling:

**Comment by ahardin-rh** [comment]
LGTM too. Mergin'!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/secrets.adoc#dev-guide-secrets[Secrets]
|Added information about xref:../dev_guide/secrets.adoc#secrets-in-env-vars[secrets in environment variables].
%

**Pull request merged**
