### PR TITLE
OSDOCS-3607: Added OpenShift Cluster Manager doc to Architecture title in OCP

### PR DESCRIPTION
**Pull request by dayleparker**
[OSDOCS-3607](https://issues.redhat.com//browse/OSDOCS-3607): added OpenShift Cluster Manager title to Architecture topic map

Version(s):
4.9 to current. Prior versions were not requested originally.

Issue:
https://issues.redhat.com/browse/OSDOCS-3607

Link to docs preview: http://file.bne.redhat.com/~dayparke/OSDOCS-3607-ocm-ocp/architecture/ocm-overview-ocp.html

Additional information:
This was added to the ROSA and OSD topic map already in https://issues.redhat.com/browse/OSSDOCS-30 - this Jira is just to add the doc to the OCP docs so OpenShift Cluster Manager content is easier to find in the OCP docs.

Note: This addition was originally done with a symlink, but now I have created a new assembly with different IDs to not run into conflicts in the different docs sites/builds.

For background - Stephanie Stout determined that the best place to add this doc to the OCP docs repo is in the Architecture guide - CC @sjstout

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Hi, Dayle! We've had some team discussion around this. I have not seen an assembly reused like this and there are some concerns around the usage and whether it would work okay on both docs.openshift.com and on the Customer Portal. Assemblies must have unique contexts, so if the same context is used for both places, there will likely be ID conflicts. The team's suggestion is to make a separate assembly or move the assembly to a new book. Sorry for any headache! We should probably update our guidelines to address this use case.

**Comment by dayleparker** [comment]
No worries @ahardin-rh! I definitely don't want to break the builds :) I will try the solution(s) you mention here and let you and the review team know when it's ready to look at again. I'm not sure how often this use case will happen....Thanks so much for the explanation of the potential conflicts too.

**Comment by dayleparker** [comment]
Hi @ahardin-rh and the review squad,
I've now updated this PR so the OCM guide is a new assembly instead of the previous method (A symlink). I had a bit of trial and error with squashing (I'm new to the OpenShift docs processes) but all looks as it should now. Please let me know if this will work and can be merged. I've updated the docs preview link in the original description.
Thanks so much!

**Comment by ahardin-rh** [comment]
Looks great! Thank you!

**Comment by ahardin-rh** [comment]
Per Dayle and Stephanie's discussion, removing 4.6-4.8 labels.

**Comment by dayleparker** [comment]
I've spoken with Stephanie Stout about whether we actually need this doc all the way back to 4.6 (to determine if it is needed to manually cherry-pick) and we agreed it will be fine to have this update in the versions 4.9 and newer. I will cancel the backports to versions 4.6, 4.7 and 4.8.

**Pull request merged**
