### PR TITLE
osdocs-911 updating AWS AMIs

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://issues.redhat.com/browse/OSDOCS-911

Per https://github.com/openshift/installer/blob/release-4.4/data/data/rhcos.json

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by jianlinliu** [comment]
@yunjiang29 pls help review this PR.

**Comment by yunjiang29** [comment]
@kalexand-rh The file rhcos.json has been changed on Apr. 25, could you please update AMIs info according to the latest changes? 

btw, there is an extra double quote followed by ami-02b1b5a5fd4c8e49a in section ap-south-1, it should be removed.

**Comment by vikram-redhat** [comment]
@yunjiang29 - is this ok now?

**Comment by jianlinliu** [comment]
LGTM now.

**Pull request merged**
