### PR TITLE
Bug 1489319 Added port 8444 to list of required ports

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1489319

Will verify in the BZ or over email once I find an SME.

### CODE REVIEW

**Comment by zhouying7780** [comment]
LGTM

**Comment by bfallonf** [comment]
Thanks @zhouying7780 ! I'll put to review.

@openshift/team-documentation PTAL

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bfallonf** [comment]
Thanks @kalexand-rh :horse:

**Pull request merged**
