### PR TITLE
Fix for https://github.com/openshift/openshift-docs/issues/23529

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/23531

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gpei, will you PTAL or help me find a better reviewer?

**Comment by kalexand-rh** [comment]
@wzheng1, will you PTAL?

**Comment by kalexand-rh** [comment]
@gpei, will you PTAL or help me find a better reviewer?

**Comment by gpei** [comment]
LGTM. Sorry for missing this somehow.

**Comment by kalexand-rh** [comment]
@gpei, thank you for looking now!

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
