### PR TITLE
OSDOCS-2250: Removed metering book

### PR DESCRIPTION
**Pull request by vikram-redhat**
Issue: https://issues.redhat.com/browse/OSDOCS-2250

Applies to enterprise-4.9 branch only.

Preview: https://deploy-preview-36779--osdocs.netlify.app/openshift-enterprise/latest/welcome/index.html

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@pruan-rht - can you give your ack for this?

**Comment by bobfuru** [comment]
LGTM

**Pull request merged**
