### PR TITLE
OSDOCS-11274:changing uppercase to lowercase for Greenboot

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.14+

Issue:
[OSDOCS-11274](https://issues.redhat.com/browse/OSDOCS-11274)

Link to docs preview:
Configuring section:
[Checking greenboot scripts status](https://83377--ocpdocs-pr.netlify.app/microshift/latest/microshift_configuring/microshift-greenboot-checking-status.html)

Running applications section:
[Greenboot workload health check scripts](https://83377--ocpdocs-pr.netlify.app/microshift/latest/microshift_running_apps/microshift-greenboot-workload-scripts.html)

Troubleshooting (troubleshooting) section:
[Checking the status of greenboot health checks](https://83377--ocpdocs-pr.netlify.app/microshift/latest/microshift_troubleshooting/microshift-troubleshoot-updates.html#microshift-greenboot-check-status_microshift-troubleshoot-updates)

Installing:
[The greenboot health check framework](https://83377--ocpdocs-pr.netlify.app/microshift/latest/microshift_install_get_ready/microshift-greenboot.html)

QE review:
- NA as only "Greenboot" is changed to "greenboot" as per style guide https://redhat-documentation.github.io/supplementary-style-guide/#greenboot . No other technical change.

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Comment by ShaunaDiaz** [comment]
@aravipra Looks like you'll have to pick these back one at a time for 4.14-4.16; or just do them individually.

**Comment by aravipra** [comment]
https://github.com/openshift/openshift-docs/pull/83593 - cp for 4.14 branch

**Pull request merged**
