### PR TITLE
STOR-794: 4.12: Update required vSphere ver to 7.0.2

### PR DESCRIPTION
**Pull request by jsafrane**
And document upstream vSphere CSI driver removal.

cc @openshift/storage @lpettyjo

### CODE REVIEW

**Comment by lpettyjo** [comment]
@bscott-rh for install area content.

**Comment by jcpowermac** [comment]
cc: @rvanderp3 @bostrt @jcpowermac

**Comment by jsafrane** [comment]
/close
in favor of https://github.com/openshift/openshift-docs/pull/50431

**Pull request closed without merging**
