### PR TITLE
Bug 1475371, Added valid units of measurement for --keep-younger-than

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1475371

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@derekwaynecarr Please confirm that this information is correct.

**Comment by ahardin-rh** [comment]
@soltysh Can you please help verify this information?

**Review by soltysh — APPROVED** [review]
That's correct, it's based off https://golang.org/pkg/time/#ParseDuration

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/pruning_resources.adoc#admin-guide-pruning-resources[Pruning Objects]
|Added valid units of measurement for `--keep-younger-than`.
%

**Pull request merged**
