### PR TITLE
Document warnings returned by generic buildhook

### PR DESCRIPTION
**Pull request by jim-minter**
bug https://bugzilla.redhat.com/show_bug.cgi?id=1373330
https://github.com/openshift/origin/issues/11736

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jim-minter Thanks! Is this for 3.3, or for a future release? Please check my labels before I merge. Thanks!

**Comment by jim-minter** [comment]
@ahardin-rh this should be going into origin 1.4 and ocp 3.4 (so different labels I guess)

**Comment by ahardin-rh** [comment]
@jim-minter Labels updated. Thanks for confirming!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/builds.adoc#dev-guide-builds[Builds]
|Added a NOTE to the xref:../dev_guide/builds.adoc#webhook-triggers[Generic Webhooks] section explaining that {product-title} permits builds to be triggered via the generic webhook even if an invalid request payload is presented.
%

**Pull request merged**
