### PR TITLE
Bug 1589879 Add oreg_url to example inventory files

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1589879

### CODE REVIEW

**Comment by bmcelvee** [comment]
Because of rearranging of our files, this is for 3.10+. For previous versions I will need to open PRs on those branches.

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL :rocket:

**Review by kalexand-rh — COMMENTED** [review]
It passed QE, so LGTM. :smile_cat:

**Comment by bmcelvee** [comment]
Thank you!

**Pull request merged**
