### PR TITLE
[OSDOCS-4684]: Update the OPP product guide's Quay links for 3.8

### PR DESCRIPTION
**Pull request by tmalove**
[OSDOCS-4684](https://issues.redhat.com/browse/OSDOCS-4684)

Version(s):
This PR is based on the ‘opp-docs’ repo and when merged, it should be in that branch only. The OPP doc is not versioned. Add the ‘Continuous Release’ milestone to this PR.

Epic: [OSDOCS-4676](https://issues.redhat.com/browse/OSDOCS-4676)

Link to docs previews:
[Release notes](https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/red_hat_quay_release_notes/index)
[Installing](https://access.redhat.com/documentation/en-us/red_hat_quay/3.8/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/index)
[Compatibility matrix](http://file.rdu.redhat.com/tlove/opp-osdocs-4684-new-tlove/architecture/opp-architecture.html#opp-architecture-compatibility-matrix_opp-architecture)

QE review:
- [ ] QE is not required. Doc change only.

### CODE REVIEW

**Comment by tmalove** [comment]
@stevsmit  WIll you verify the Quay links for 3.9? Thanks!

**Review by kelbrown20 — COMMENTED** [review]
Looks great!
/lgtm

**Pull request merged**
