### PR TITLE
ROX-22475: update roxctl image scan `--fail` argument

### PR DESCRIPTION
**Pull request by stehessel**
Version(s): 4.5

Issue: https://issues.redhat.com/browse/ROX-22475

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kcarmichael08** [comment]
Hi @stehessel , can you please change parent branch to `rhacs-docs-main`? Thank you!

**Comment by kcarmichael08** [comment]
Hi @stehessel , this needed a rebase, so I did it using the GUI, but unfortunately now there are 2 commits that need to be squashed into one. (repo requirement) Can you please squash? Thank you!

**Comment by stehessel** [comment]
@kcarmichael08 this happened because you updated the branch via a merge commit instead of using the rebase option. I rebased the branch again, so it should be a single commit now.

**Comment by kcarmichael08** [comment]
Thank you @stehessel , sorry for the churn. I'll do a retest since the build is having issues.

**Pull request merged**
