### PR TITLE
OCPBUGS#31537: Amend ODF must-gather image name

### PR DESCRIPTION
**Pull request by kowen-rh**
Version(s):
4.14+

Issue:
[OCPBUGS-31537](https://issues.redhat.com/browse/OCPBUGS-31537)

Link to docs preview:
[Gathering data about specific features](https://80473--ocpdocs-pr.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data)

QE review:
- [x] QE has approved this change.

Additional information:
N/A

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
LGTM

**Comment by ShaunaDiaz** [comment]
@kowen-rh Please make a manual CP for 4.14, resolve the conflict, and either ping me or put it back in queue! https://github.com/openshift/openshift-docs/pull/80473#issuecomment-2291758094

**Pull request merged**
