### PR TITLE
OCPBUGS#10586: Removed TP reference for installing on OCI

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OSDOCS-10586

Link to docs preview: https://76853--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes.html#ocp-4-15-oci

Review:
- [x] QE has approved this change.
- [x]  PM has approved this change.
- [x]  SME has approved this change.

### CODE REVIEW

**Review by makentenza — APPROVED** [review]
LGTM

**Comment by mhanss** [comment]
LGTM

**Comment by dfitzmau** [comment]
Hi @snarayan-redhat . The TP table will also need to be updated for VMs:

Screenshot from 2024-06-07 09-31-44

**Comment by dfitzmau** [comment]
LGTM

/label peer-review-done

**Pull request merged**
