### PR TITLE
OSDOCS-3926: removes depricated extension point and replaces with correct console-extensions.json

### PR DESCRIPTION
**Pull request by opayne1**
[OSDOCS-3926](https://issues.redhat.com//browse/OSDOCS-3926): removes depricated extension point and replaces with correct console-extensions.json

Applies to enterprise-4.10+

Issue:
[OSDOCS-3926](https://issues.redhat.com/browse/OSDOCS-3926)

Link to docs preview:
http://file.rdu.redhat.com/opayne/OSDOCS-3926/web_console/dynamic-plug-ins.html#adding-tab-to-pods-page_dynamic-plugins

### CODE REVIEW

**Comment by opayne1** [comment]
@spadgett Can you verify these are the correct changes to be made? I double checked the extension docs that were merged with 4.11 and the deprecated notice is on the [`console.page/resource/tab` extension](https://docs.openshift.com/container-platform/4.11/web_console/dynamic-plug-ins.html#consolepageresourcetab) in our docs. Thank you!

**Review by spadgett — APPROVED** [review]
LGTM

**Comment by Amrita42** [comment]
lgtm

**Comment by yapei** [comment]
LGTM

**Pull request merged**
