### PR TITLE
Manual CP of RHDEVDOCS-4102 to main

### PR DESCRIPTION
**Pull request by libander**
Post-merge reversion manual CP of https://github.com/openshift/openshift-docs/pull/50781 to main.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@bburt-rh @libander I'm pretty sure that you've done these CPs, but would you mind linking those PRs to this one for tracking purposes?

**Comment by bergerhoffer** [comment]
@libander since that one was reverted before it was CPd around, it would be better to attach them to this one if you wouldn't mind!

**Comment by libander** [comment]
https://github.com/openshift/openshift-docs/pull/51972
https://github.com/openshift/openshift-docs/pull/52099
https://github.com/openshift/openshift-docs/pull/52111
https://github.com/openshift/openshift-docs/pull/52112
https://github.com/openshift/openshift-docs/pull/52113

**Pull request merged**
