### PR TITLE
removed tp language from 3scale

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.jboss.org/projects/OSSMDOC/issues/OSSMDOC-12?filter=allissues

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Review by tvieira — APPROVED** [review]
LGTM

**Comment by neal-timpe** [comment]
@openshift/team-documentation Can you review and merge?

**Review by adellape — APPROVED** [review]
:+1:

**Comment by adellape** [comment]
xref: https://github.com/openshift/openshift-docs/pull/18009

**Pull request merged**
