### PR TITLE
OCPBUG#9850- Corrected control plane node sizing values

### PR DESCRIPTION
**Pull request by subhtk**
Version(s): 4.10+

Issue: [OCPBUG9850](https://issues.redhat.com/browse/OCPBUGS-9850)

Docs Preview:
[Preview](https://57332--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-host-practices.html#master-node-sizing_recommended-host-practices)

@sunilcio ptal

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
lgtm pending QE review

**Review by kelbrown20 — COMMENTED** [review]
LGTM

**Pull request merged**
