### PR TITLE
install/bare_metal: Remove tech preview text from three-node cluster

### PR DESCRIPTION
**Pull request by sdodson**
This has always worked but now it's tested and fully supported in 4.5+

/cc @kalexand-rh

### CODE REVIEW

**Comment by sdodson** [comment]
This was done as part of https://issues.redhat.com/browse/CORS-1369

**Review by kalexand-rh — COMMENTED** [review]
@sdodson, I pushed a small edit, but this LGTM.

**Comment by kalexand-rh** [comment]
@qinpingli, will you please +1 this change?

**Comment by qinpingli** [comment]
@gpei Could you help take a look at this? Thx.

**Comment by gpei** [comment]
LGTM, thanks.

**Pull request merged**
