### PR TITLE
bug BZ1716427 note about patch failing

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1716427

### CODE REVIEW

**Comment by staebler** [comment]
Do we care to add any context for why the patch may fail? I don't know what the general approach is to giving information such as that in installation instructions.

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL?

**Comment by jianlinliu** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
