### PR TITLE
OSDOCS-11984#removing trailing quotation

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-11984

Link to docs preview:
https://83381--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/validation_and_troubleshooting/installing-troubleshooting.html#installation-bootstrap-gather_installing-troubleshooting

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by brendan-daly-red-hat** [comment]
@yunjiang29, PTAL

**Pull request merged**
