### PR TITLE
[OSDOCS-5257] Additional support statements in ROSA docs

### PR DESCRIPTION
**Pull request by mletalie**
[OSDOCS-5257] Additional support statements in ROSA docs

Version(s):

4.12 +
Issue:

https://issues.redhat.com/browse/OSDOCS-5257
Link to docs preview:
* [ROSA Support](https://55775--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-getting-support.html)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by codymant** [comment]
@mletalie There are a few procedural steps involved in enabling AWS Support, and part of the customer feedback was related to not knowing what the steps were to enable AWS Support, or where to find this information. 

What do you think if we add the the following sentence that links out to the AWS Knowledge Center solution page with steps for enabling AWS Support? This could look something like the following: 

"You can also get support from [AWS Support](https://aws.amazon.com/premiumsupport/) as long as you have a valid AWS support contract and have enabled AWS Business, Enterprise On-Ramp, or Enterprise support plans.

For steps to enable an AWS Support plan, see [How do I sign up for an AWS Support plan?](http://aws.amazon.com/premiumsupport/knowledge-center/sign-up-support/)

For information about creating an AWS support case, see the [AWS support case](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html) documentation."

**Comment by codymant** [comment]
There's a similar example in the AWS ROSA guide topic "Support for ROSA":[ ](https://docs.aws.amazon.com/ROSA/latest/userguide/troubleshooting-rosa.html#rosa-support)

**Comment by codymant** [comment]
I'd also suggest capitalizing "AWS Support" whenever the term is used, as seen in the [AWS support docs](https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html).

**Comment by mletalie** [comment]
Looks good, thanks @codymant!
Will make the changes and commit on Monday. Appreciate it! ML

**Comment by mletalie** [comment]
/label merge-review-needed

FYI: This ticket was reviewed by both PM (@0kashi) and Cody @codymant. Do not believe it needs another peer review but not sure. If not, please review for merge; otherwise let me know and I will add a peer review needed label. Thanks!

**Comment by maxwelldb** [comment]
@mletalie lgtm. ROSA doesn't require a QE check, does it?

**Review by maxwelldb — APPROVED** [review]

**Comment by codymant** [comment]
@mletalie Looks good to me, thanks for the update!

**Comment by mletalie** [comment]
> @mletalie lgtm. ROSA doesn't require a QE check, does it?

Hi @maxwelldb,
   Thanks for handling this; in regards to your question, in many cases it does, but per my mgr that role was handled via an AWS tech writer and was also approved by RH PM. Thanks!

**Pull request merged**
