### PR TITLE
OSDOCS Graphic Update: updated an diagram in both ROSA classic and HCP

### PR DESCRIPTION
**Pull request by EricPonvelle**
Version(s):
`enterprise-4.14+`

Link to docs preview:
- [ROSA architecture on public and private networks](http://file.rdu.redhat.com/eponvell/OSDOCS-Graphic-Update/rosa_architecture/rosa_architecture_sub/rosa-architecture-models.html#rosa-architecture_rosa-architecture-models)
    image

- [Comparing ROSA with hosted control planes and ROSA Classic](http://file.rdu.redhat.com/eponvell/OSDOCS-Graphic-Update/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html#rosa-hcp-classic-comparison_rosa-hcp-sts-creating-a-cluster-quickly)
    image

QE review:
- [ ] QE has approved this change.

Additional information:
Updated a diagram. I need to delete the old version before this PR merges.

### CODE REVIEW

**Review by wgordon17 — APPROVED** [review]
LGTM 👍 Thanks

**Comment by jneczypor** [comment]
label /lgtm

**Pull request merged**
