### PR TITLE
added openshift_gcp_multizone variable in Configuring GCE section

### PR DESCRIPTION
**Pull request by gaurav-nelson**
for #8745

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
[Missing Ansible variables for GCE](https://trello.com/c/k2XV3oUT/20-missing-ansible-variables-for-gce)

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM

**Comment by gaurav-nelson** [comment]
minor change verified from https://bugzilla.redhat.com/show_bug.cgi?id=1542843 and https://github.com/openshift/openshift-ansible/pull/7122
no QE required

**Pull request merged**
