### PR TITLE
bug 1395447. Advise sizing of storage

### PR DESCRIPTION
**Pull request by jcantrill**

### CODE REVIEW

**Comment by jcantrill** [comment]
@ahardin-rh  upon final approval should also be cherry-picked into 3.4

**Review by lukas-vlcek — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
@jcantrill Thanks! This should be submitted against the master branch, so that we get it to show up in our Origin docs, then we can cherry-pick it to 3.3 and 3.4 from there.

**Comment by jcantrill** [comment]
Added PR https://github.com/bmcelvee/openshift-docs/pull/1 since the docs PR for master hast not been merged yet.

**Comment by ahardin-rh** [comment]
Closing this, as it was addressed via https://github.com/openshift/openshift-docs/pull/3918/files by @bmcelvee 

Thanks!

**Pull request closed without merging**
