### PR TITLE
BZ#2071560: Adding link to openjdk documentation for Java S2I reference in OCP docs

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):
4.6+

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2071560

Link to docs preview:
https://deploy-preview-44950--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/using_images/using-s21-images.html

### CODE REVIEW

**Comment by xiuwang** [comment]
LGTM

**Review by maxwelldb — APPROVED** [review]
Could turn that paragraph into a UL, if you like. lgtm, though!

**Pull request merged**
