### PR TITLE
registry option acceptschema2: true

### PR DESCRIPTION
**Pull request by aweiteka**
See default config change: https://github.com/openshift/origin/pull/13428

Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@aweiteka Looks like we need a rebase. This is targeting 3.6, correct? Thanks!

**Comment by aweiteka** [comment]
> Looks like we need a rebase.

Done

> This is targeting 3.6, correct?

Yes

**Comment by ahardin-rh** [comment]
@aweiteka Thanks! Once the Origin PR is merged, this is ready to go :star2:

**Comment by ahardin-rh** [comment]
Looks like the Origin PR is merged. Merging this now.

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
