### PR TITLE
[enterprise-4.1] Multi-stage Dockerfile Builds GA

### PR DESCRIPTION
**Pull request by adambkaplan**
Add a note (in addition to GA table entry) indicating multi-stage
Dockerfiles are supported in all `Docker` strategy builds.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bmcelvee 

Motivated by [@fatherlinux tweet](https://twitter.com/fatherlinux/status/1131557672447369216)

**Comment by vikram-redhat** [comment]
@ahardin-rh @sheriff-rh for release notes.

**Comment by bmcelvee** [comment]
LGTM. @adambkaplan would you mind rebasing? Then, @sheriff-rh has no objections, I can go ahead and merge. Thanks!

**Comment by adambkaplan** [comment]
@bmcelvee rebased

**Comment by bmcelvee** [comment]
Thanks! Merging.

**Comment by bmcelvee** [comment]
Minor update to release notes, no QE review necessary.

**Pull request merged**
