### PR TITLE
OSDOCS#10737: Changed note for clarity reg IPI parameter

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-10737
 
Link to docs preview: https://83853--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installation-config-parameters-vsphere#installation-configuration-parameters-additional-vsphere_installation-config-parameters-vsphere

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sgaoshang** [comment]
From 4.13, apiVIPs and ingressVIPs is not needed for IPI install if configured an external load balancer, see [here](https://docs.openshift.com/container-platform/4.13/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-launching-installer_installing-vsphere-installer-provisioned ) , and this 2 parameters should not be set for UPI install

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
