### PR TITLE
OSDOCS-2893: Updating RNs for Kubernetes 1.23

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2893

Preview: https://deploy-preview-38447--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes#ocp-4-10-about-this-release

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Probably should wait to merge this until 1.23 is released (December 7)

**Comment by bergerhoffer** [comment]
Kube 1.23 has been released, can move forward with this

**Comment by bergerhoffer** [comment]
@zhouying7780 Would you mind reviewing this bump of the kube version in the release notes? Thanks!

Preview: https://deploy-preview-38447--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes#ocp-4-10-about-this-release

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
