### PR TITLE
GitHub-43667: Updating procedure to edit a namespace

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.6+

Issue:
#43667

Link to docs preview: http://file.rdu.redhat.com/~ahoffer/2022/github-43667/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-project_nodes-scheduler-node-selectors

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@sunilcio Can you please QE review this change? Thanks!

Preview: http://file.rdu.redhat.com/~ahoffer/2022/github-43667/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-project_nodes-scheduler-node-selectors

**Pull request merged**
