### PR TITLE
CNV-28960: docs enabling preview features

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.14

**Issue:**
https://issues.redhat.com/browse/CNV-28960

**Link to docs preview:**
https://62736--docspreview.netlify.app/openshift-enterprise/latest/virt/getting_started/virt-web-console-overview.html#overview-settings-cluster_virt-web-console-overview

**QE review:**
- [x] QE has approved this change.

**Additional information:**

### CODE REVIEW

**Comment by apinnick** [comment]
@lkladnit Please review this PR.

**Review by lkladnit — APPROVED** [review]

**Comment by ousleyp** [comment]
LGTM!

**Pull request merged**
