### PR TITLE
[SRVCOM-2060] Fix minor bug in functions docs

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+

Issue:
https://issues.redhat.com/browse/SRVCOM-2060

Link to docs preview:
https://50740--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-setup.html#serverless-functions-podman_serverless-functions-setup

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Review by lkingland — APPROVED** [review]
Looks good to me.  The command help text mentions that they have the option of using the `--path` flag to build a function in a different directory should that be needed.  👍🏻

**Review by lance — COMMENTED** [review]
/lgtm

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
