### PR TITLE
OSDOCS-1788: Removing TP from scheduler profiles

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1788

Preview: https://deploy-preview-35448--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-profiles.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund Can you please review? All I'm doing here is just removing any references to scheduler profiles being tech preview. 

Preview: https://deploy-preview-35448--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-profiles.html

There is no change to scheduler policies in 4.9, correct?

**Comment by bergerhoffer** [comment]
@kasturinarra for review please:

Preview: https://deploy-preview-35448--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-scheduler-profiles.html

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Comment by ingvagabund** [comment]
> There is no change to scheduler policies in 4.9, correct?

No change. They will get removed in 4.10.

**Pull request merged**
