### PR TITLE
RHACS: Fix typo in scanner v4 docs

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
4.4+

Issue: none, reported via Slack

[Link to docs preview
](https://73980--docspreview.netlify.app/openshift-acs/latest/installing/installing_ocp/install-central-ocp.html#central-services-private-configuration-file-scanner_install-central-ocp)

QE review: (**N/A**)
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kcarmichael08** [comment]
Hi @jmanthei , any update? This is a really small change but I would like to get it in ASAP, since the docs are already published. Thank you!

**Comment by jmanthei** [comment]
LGTM - I know it was a small change but since I'm new to peer review, I just wanted to be thorough!

**Pull request merged**
