### PR TITLE
OSDOCS#10236: Rename "Configuring hosted control planes"

### PR DESCRIPTION
**Pull request by xenolinux**
This PR renames the title of the "Configuring hosted control planes" topic. This topic contains sections related to getting started such as sizing guidance, infrastructure/port/firewall requirements, distributing workloads and lastly configuring HCP on a particular platform. Hence, the title is renamed to indicate that user can find out "getting started" related information here.

Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OSDOCS-10236

Link to docs preview: https://74573--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-getting-started.html

QE review:
- [x] QE has approved this change.

PM review:
- [x] PM has approved this change.

Additional information:

### CODE REVIEW

**Review by zanetworker — APPROVED** [review]
/lgtm

**Comment by kcarmichael08** [comment]
Hi @xenolinux , looks like the 4.14 cherry pick needs to be done manually, but everything else is good! I'll keep this one on my radar and you can tag me on the manual cherry pick to merge it.

**Pull request merged**
