### PR TITLE
ROX-26886: Update scanner v4 options in docs

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s): 4.5+

[Issue](https://issues.redhat.com/browse/ROX-26886)

Link to docs preview:

- https://85545--ocpdocs-pr.netlify.app/openshift-acs/latest/installing/installing_ocp/install-secured-cluster-config-options-ocp.html#scanner-configuration-settings_install-secured-cluster-config-options-ocp

QE review: **ACS has no QE, approved by SME**
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by vladbologa — APPROVED** [review]
LGTM

**Review by cbippley — COMMENTED** [review]
One nit. Remember to get QE review before asking for merge review. Otherwise, LGTM!

**Comment by kcarmichael08** [comment]
> One nit. Remember to get QE review before asking for merge review. Otherwise, LGTM!

Oh, ACS doesn't have QE. I usually note that in the PR body - will fix that.

**Pull request merged**
