### PR TITLE
Improve a command invocation

### PR DESCRIPTION
**Pull request by rh-max**
(Passed QE. To be cherry-picked to enterprise-4.2 too.)
@aburdenthehand , could you please review, merge, and cherrypick? Thank you.

### CODE REVIEW

**Comment by rh-max** [comment]
@ahardin-rh Could you please take over this one from Andrew? Thanks.

**Comment by rh-max** [comment]
Oh, and we should cherry-pick it to enterprise-4.1 too.

**Comment by rh-max** [comment]
@sheriff-rh Hey, could you please review, merge and cherry-pick? Thank you.

**Comment by sheriff-rh** [comment]
Will merge and pick to 4.1 and 2! Thanks @rh-max !

**Pull request merged**
