### PR TITLE
OSDOCS-3417: move out of ingress operator assembly

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OSDOCS-3417

Link to docs preview: http://file.rdu.redhat.com/jdohmann/OSDOCS-3417/networking/ingress-operator.html (it's a removal)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@lihongan could you PTAL for QE ack? this PR removes ingress sharding from the operator docs, because sharding now lives [here](https://docs.openshift.com/container-platform/4.12/networking/ingress-sharding.html) in its own assembly. Thank you!

**Comment by lihongan** [comment]
@jldohmann it looks good. 
Thank you!

**Review by adellape — APPROVED** [review]

**Pull request merged**
