### PR TITLE
OCPBUGS-31096#removing VPC wizard text

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.15+

Issue:
https://issues.redhat.com/browse/OCPBUGS-31096

Link to docs preview:
https://79531--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-private.html#installation-custom-aws-vpc-requirements_installing-aws-private

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@ehvs, PTAL at this draft update.

**Comment by gpei** [comment]
@brendan-daly-red-hat I think we just need to update the link in this section, but not remove it.

**Comment by gpei** [comment]
@brendan-daly-red-hat we can update the link to `https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html` , which is the redirected one when visiting `https://docs.aws.amazon.com/vpc/latest/userguide/VPC_wizard.html`

**Comment by brendan-daly-red-hat** [comment]
> @brendan-daly-red-hat we can update the link to `https://docs.aws.amazon.com/vpc/latest/userguide/working-with-vpcs.html` , which is the redirected one when visiting `https://docs.aws.amazon.com/vpc/latest/userguide/VPC_wizard.html`

@gpei, Thanks, can you review the revised draft: https://79531--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-private.html#installation-custom-aws-vpc-requirements_installing-aws-private?

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
