### PR TITLE
SRVCOM-2931 - adds 1.32 to list of versions

### PR DESCRIPTION
**Pull request by briandooley**
Version(s):

Issue:
[SRVCOM-2931](https://issues.redhat.com/browse/SRVCOM-2931)

Link to docs preview:
N/A

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by briandooley** [comment]
@gabriel-rh @kalexand-rh @gaurav-nelson @Srivaralakshmi @mramendi @aireilly Can one of you give this a review in advance of the serverless docs 1.32 release?

**Comment by tmalove** [comment]
Per @briandooley, a preview is not required because this change is transparent to the user.
/remove-label peer-review-in-progress
/label peer-review-done

**Review by aireilly — APPROVED** [review]
/lgtm

**Pull request merged**
