### PR TITLE
Bug 1387371, added clarification to the Exposing a Non-Secure Registry section

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1387371

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf Please peer review. 

Preview Build: http://file.rdu.redhat.com/~ahardin/10242016/exposing-route/install_config/registry/securing_and_exposing_registry.html#access-insecure-registry-by-exposing-route

**Comment by bfallonf** [comment]
@ahardin-rh Looks good!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/registry/securing_and_exposing_registry.adoc#install-config-registry-securing-exposing[Setting up the Registry -> Securing and Exposing the Registry]
|Added clarification to the xref:../install_config/registry/securing_and_exposing_registry.adoc#access-insecure-registry-by-exposing-route[Exposing a Non-Secure Registry] section.
%

**Comment by vikram-redhat** [comment]
@ahardin-rh - Hey Ashley - the links for the access-logging-in-to-the-registry anchor were not in this file. When publishing today, I changed those links to point to the accessing_registry.adoc file.

**Pull request merged**
