### PR TITLE
Update the admonition for the supported backup storage providers

### PR DESCRIPTION
**Pull request by apurvabhide17**
Version(s):
OCP 4.13 → OCP 4.16

Issue:
[OADP-4012](https://issues.redhat.com/browse/OADP-4012)

Link to docs preview:

QE review:
- [x] QE has approved this change.

The changes were peer reviewed in the previous [PR](https://github.com/openshift/openshift-docs/pull/83479), which was closed.

### CODE REVIEW

**Comment by mail2nadeem92** [comment]
+LGTM

**Review by mail2nadeem92 — APPROVED** [review]
Looks good to me.

**Comment by apurvabhide17** [comment]
Thanks @mail2nadeem92

**Comment by stevsmit** [comment]
@apurvabhide17 Be sure to use the /peer-review-needed label first. This content lgtm to me though, so I can go ahead and merge it.

**Comment by apurvabhide17** [comment]
> @apurvabhide17 Be sure to use the /peer-review-needed label first. This content lgtm to me though, so I can go ahead and merge it.

@stevsmit, the changes were peer reviewed in the previous [PR](https://github.com/openshift/openshift-docs/pull/83479), which was closed. I've now updated the description of this PR with it.
Thanks!

**Pull request merged**
