### PR TITLE
Additional clarification around docker and persistent storage

### PR DESCRIPTION
**Pull request by sdodson**
Builds upon #674 
- Clarifies differences between docker storage and persistent storage
- Re-orders docker-storage-setup options such that adding an additional block device is first
- Updated example output

### CODE REVIEW

**Comment by sdodson** [comment]
@brenton @adellape PTAL 

Rendered preview http://file.rdu.redhat.com/sdodson/dss/admin_guide/install/prerequisites.html

I can squash my commits after review. I wasn't sure if the third level section would be ok or not.

**Comment by brenton** [comment]
I like where this is going.  I'd definitely recommend rewording the original "There are three methods available based on your storage configuration:" part.  You're now clarifying that above and labeling them A, B and C.  I would change the part where the actual details are given to simply have titles like, "Option A: Using an additional block device".

Also, it doesn't look like you changed this section but I'll be honest, it doesn't make much sense to me so we should probably fix it too:

> Before using Docker or OpenShift please verify that the docker-pool logical volume is approximately 60% of the space you’ve allocated. This thin pool will automatically grow to fill the remaining space as needed.

It's the "space you've allocated" part that seems really vague in this context.

**Comment by sdodson** [comment]
So, when i redid the examples I noticed that they'd changed the defaults to only allocate 60% of the volume group space and allow lvm monitoring to grow both the data and metadata subvolumes as needed. This is mainly to allow the metadata volume to grow based on usage. I had a hard time coming up with how to express that because I didn't want people to be confused when it didn't reflect the amount of space they're expecting.

I've updated it, is that better?
Also cleaned up the OptionA,B,C per your suggestions.

Also, some of the feedback on the lists is that we need to clarify docker storage versus persistent storage. Thus far I added Persistent Storage to the table of system requirements but I wonder if we should make storage a section of its own and then elaborate on the difference between docker storage and volumes.

**Comment by brenton** [comment]
Cool. I like the updates.

**Comment by sdodson** [comment]
Alex is going to pull my changes into his original PR and polish things there. Closing this in favor of #674

**Pull request closed without merging**
