### PR TITLE
OSDOCS-5119-RN GCP shared VPC installation RN

### PR DESCRIPTION
**Pull request by bscott-rh**
Release notes for https://issues.redhat.com/browse/OSDOCS-5119

Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-5119

Link to docs preview:
https://56804--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-gcp-shared-vpc

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei PTAL at these release notes for GCP XPN GA. Thank you

**Comment by bscott-rh** [comment]
@jianli-wei can you please take a look at these GCP XPN release notes? thank you

**Review by snarayan-redhat — COMMENTED** [review]
Looks good!

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
