### PR TITLE
Clarify Configure your firewall section

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/OSDOCS-1375

### CODE REVIEW

**Comment by cuppett** [comment]
lgtm

**Review by cuppett — APPROVED** [review]

**Comment by ahardin-rh** [comment]
@lihongan Can you please provide QE review or point me to the best contact? Thank you!

**Comment by bobfuru** [comment]
LGTM

**Comment by lihongan** [comment]
> @lihongan Can you please provide QE review or point me to the best contact? Thank you!

This is the [part](https://docs.openshift.com/container-platform/4.5/installing/install_config/configuring-firewall.html) of installation configuration, @gpei could you please help take a look? thank.

**Comment by gpei** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thank you!

**Pull request merged**
