### PR TITLE
OSDOCS#11576: Moving the memory ballooning note out of a snippet to f…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ix build

Version(s):
4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-11576

Link to docs preview:
* https://80529--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/upi/upi-vsphere-installation-reqs.html#installation-minimum-resource-requirements_upi-vsphere-installation-reqs

Also, here is an example of another assembly that uses this module, to show that this note only appears for vSphere: 
https://80529--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites#installation-minimum-resource-requirements_ipi-install-prerequisites

QE review:
QE not required since no text is changing

Additional information:
This PR doesn't change any text, just moves the text out of a snippet and into the module directly. Because snippets inside conditionals can cause errors for the portal.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Note to peer reviewer - this PR only moves text, doesn't change any of it

**Review by lahinson — COMMENTED** [review]
LGTM

**Pull request merged**
