### PR TITLE
Remove 3.10 specific items from downgrade and restore documentation

### PR DESCRIPTION
**Pull request by sdodson**
This updates the downgrade and restore documentation service restoration steps to be accurate for 3.11.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Thank you @sdodson!

**Review by kalexand-rh — APPROVED** [review]

**Comment by kalexand-rh** [comment]
@jiajliu, PTAL

**Comment by jiajliu** [comment]
This pr LGTM. But it need some changes in upgrade&downgrade section for a new config file's backup.
> /etc/origin/master/master.env
@kalexand-rh 
Need add this file to backup and ensure backup lists for both upgrade and downgrade.

**Comment by kalexand-rh** [comment]
Thank you! I made a new PR to add that config file to the upgrade and downgrade steps.

**Pull request merged**
