### PR TITLE
BZ1905543: Corrected language to rectify an inaccurate CRI-O availability statement

### PR DESCRIPTION
**Pull request by skrthomas**
https://bugzilla.redhat.com/show_bug.cgi?id=1905543

Direct link to doc preview: https://deploy-preview-31461--osdocs.netlify.app/openshift-enterprise/latest/architecture/architecture-rhcos.html#rhcos-key-features_architecture-rhcos

for 4.5+

Confirmed that CRI-O is indeed available on other operating systems than OpenShift [1], which contradicts the doc statement in the doc: "At the moment, CRI-O is only available as a container engine within OpenShift Container Platform clusters".

[1] https://github.com/cri-o/cri-o/blob/master/install.md

### CODE REVIEW

**Comment by mburke5678** [comment]
@skrthomas LGTM

**Comment by skrthomas** [comment]
@sunilcio ready for QA

**Comment by sunilcio** [comment]
@skrthomas thanks for the edit, LGTM.

**Pull request merged**
