### PR TITLE
OCPBUGS-15797: Removing single deviceClass limitation in LVMCluster CR

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OCPBUGS-15797

Link to docs preview: https://62339--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html#lvms-preface-sno-ran_logical-volume-manager-storage

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by amolnar-rh** [comment]
@kelbrown20 Could you please also merge it to main, 4.13, and 4.14? :)

**Review by bergerhoffer — COMMENTED** [review]
@amolnar-rh just a reminder to post the preview link, even for simple ones.

https://62339--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html#lvms-preface-sno-ran_logical-volume-manager-storage

LGTM for merging!

**Pull request merged**
