### PR TITLE
[OSDOCS-12502]:Create a separate link for the GCP supported regions for OSD

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-12502
Link to docs preview:

https://84268--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#gcp-regions-availability-zones_osd-service-definition
QE review: QE REVIEW N/A: Content meaning has not changed. 
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Reviewers: Please see https://issues.redhat.com/browse/RFE-6517 for reference. The ask was for docs to have a link directly to GCP-specific regions and AZs for a better user experience. I have sent over to the individual who requested the  doc updater and they have signed off on changes. https://issues.redhat.com/browse/RFE-6517?focusedId=25980246&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25980246

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
