### PR TITLE
[OSDOCS-9738]: Fix Typo in https://docs.openshift.com/dedicated/authentication/index.html

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-9738
Link to docs preview:

https://72108--ocpdocs-pr.netlify.app/openshift-dedicated/latest/authentication/
QE review:
- [ ] QE has approved this change.

QE approval N/A as change does not impact meaning of the docs.
Additional information:

image

### CODE REVIEW

**Comment by shipsing** [comment]
LGTM @mletalie

**Review by sheriff-rh — APPROVED** [review]
LGTM, merging to 4.15+.

**Pull request merged**
