### PR TITLE
Add additional monitoring details for OSD

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
Hey @sheriff-rh, would you be able to build a staging site of this so I can float it around for comments?

**Comment by sheriff-rh** [comment]
@wgordon17 build preview link:
http://file.rdu.redhat.com/~antaylor/091619/additional-osd-notification-docs/additional-osd-notification-docs/getting_started/access_your_services.html#access-your-cluster-monitoring-tools

If further squashes/commits are performed and you need an updated preview, I'll have to rebuild (doesn't take but a few minutes). Just let me know!

**Comment by vikram-redhat** [comment]
@wgordon17 ok for this to be merged?

**Comment by wgordon17** [comment]
Yeah, this is ready...thanks for checking, I had forgot about this 🤦🏻‍♂️

**Pull request merged**
