### PR TITLE
Bug 1446824, Added clarification: nodes/masters are forward and backward compatible across one minor version

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1446824

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sdodson @adellape PTAL

**Review by sdodson — APPROVED** [review]
lgtm

**Comment by ahardin-rh** [comment]
After discussion with @adellape, I updated the link to point to the Preparing for an Automated Upgrade section instead of the Preparing for a Manual Upgrade section.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/index.adoc#install-config-upgrading-index[Upgrading a Cluster -> Overview]
|Added clarification that nodes and masters are forward and backward compatible across one minor version.
%

**Pull request merged**
