### PR TITLE
OSDOCS-1736 Provide clarity that UPI docs are example only

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1736

### CODE REVIEW

**Comment by codyhoag** [comment]
@staebler With our current discussions regarding UPI doc improvements, this PR addresses the need to very clearly state for UPI docs (AWS, Azure, GCP, and vSphere) that the provided instructions are example only. Jeremiah and I had this discussion a few months ago, and came up with a similar statement that I've added here. Let me know if you have any suggestions on the "example only" clarification. Thanks!

**Comment by staebler** [comment]
Looks good to me.

**Comment by codyhoag** [comment]
@jianlinliu can you provide a QE review? Thanks!

**Comment by jianlinliu** [comment]
LGTM.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
