### PR TITLE
Adding values for bypassing admission control

### PR DESCRIPTION
**Pull request by lbac-redhat**
Version(s):
RHACS 3.65+ 

Issue:
https://github.com/openshift/openshift-docs/issues/47037

Link to docs preview:
No preview available

Additional information:

This PR adds missing valid values for admissionControl.bypass, including default value.

Slightly out of scope, but the PR also adds the default value to admissionControl.contactImageScanners.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
Hello Luka!  James Brigman here, I'm a member of this week's Peer Review Team.  Your updates look to be important, since you are providing information missing from the documentation. We need a local "asciibinder build", a preview and to have all commits squashed. I'll work on that now, and also pull the docs link into this PR from PR 47037.  Please stand by.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM - please stand by

**Review by bergerhoffer — COMMENTED** [review]
This LGTM too!

Per Kerry, this update should go into the following branches:
rhacs-docs (main)
rhacs-docs-3.71.0 (next release)
rhacs-docs-3.70 (current)
rhacs-docs-3.69
rhacs-docs-3.68

**Pull request merged**
