### PR TITLE
BZ 1713508 Apply feedback to Cluster Monitoring

### PR DESCRIPTION
**Pull request by bobfuru**
@maximsvistunov Please take a look and let me know if these updates look good to you before QE. Thanks!

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1713508

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@rh-max can you please take a look today?

**Comment by rh-max** [comment]
Hey @bobfuru, all your changes look good. I only suggest that when you request a review from Junqi, emphasize that the command invocation in modules/monitoring-applying-custom-alertmanager-configuration.adoc should yield the same results (as opposed to as if we realised that we needed for the command to do something different). Thanks for improving these docs!

**Comment by bobfuru** [comment]
@juzhao QE required only for modules/monitoring-applying-custom-alertmanager-configuration.adoc 

Please note that the command invocation should yield the same results (as opposed to expecting the command to do something different).

**Comment by bobfuru** [comment]
Peer review and QE verification completed
@openshift/team-documentation need peer review, merge request

**Comment by huffmanca** [comment]
This looks good to me!

**Comment by bobfuru** [comment]
Updates verified on 4.1 and [BZ 1713508](https://bugzilla.redhat.com/show_bug.cgi?id=1713508) closed.

**Pull request merged**
