### PR TITLE
Bug 1842431: backup_and_restore: clarify backup process

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1842431

Replaces #22668.

Preview: https://bz-1842431--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/backing-up-etcd.html

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
Two small style picks, then it LGTM

**Comment by bergerhoffer** [comment]
@geliu2016 Can you review this update please? Thanks!

Preview: https://bz-1842431--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/backing-up-etcd.html

**Comment by geliu2016** [comment]
LGTM, thx

**Pull request merged**
