### PR TITLE
OADP-72: Configuration

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/OADP-72

Configuration modules for OADP

4.6+

Preview: https://deploy-preview-38248--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/configuring-oadp.html

QE approved. Ready for peer review.
Update: There might be more comments from QE but peer review should still go ahead because this PR is so big.

### CODE REVIEW

**Comment by apinnick** [comment]
@XinRedhat Ready for QE.

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

Small change with `tls` but that's all I can see

**Pull request merged**
