### PR TITLE
Fix bug 1642832

### PR DESCRIPTION
**Pull request by liangxia**
https://bugzilla.redhat.com/show_bug.cgi?id=1642832

### CODE REVIEW

**Comment by liangxia** [comment]
Applies to enterprise-3.10 and above.

**Comment by liangxia** [comment]
@jhou1 @qinpingli @weherdh  Please take a look.

**Comment by jhou1** [comment]
LGTM

**Comment by kalexand-rh** [comment]
Thank you all! Merging.

**Pull request merged**
