### PR TITLE
OSDOCS-5595:updates install and uninstall for NW observability Operator

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-5595](https://issues.redhat.com//browse/OSDOCS-5595): updates install and uninstall for Network Observability Operator

Version(s):
4.10+

Issue:
https://issues.redhat.com/browse/OSDOCS-5595

Link to docs preview:
https://57748--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/installing-operators.html#network-observability-operator-installation_network_observability

QE review:
- [x] QE has approved this change.

Additional information:
PTAL @memodi and @OlivierCazade

### CODE REVIEW

**Review by memodi — APPROVED** [review]
/label qe-approved

**Review by OlivierCazade — APPROVED** [review]
/lgtm, thanks!

**Pull request merged**
