### PR TITLE
Moved json-file note from 3.7 to 3.9 per BZ

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1596012

### CODE REVIEW

**Comment by mburke5678** [comment]
@vikram-redhat PTAL

**Comment by mburke5678** [comment]
Per Anping Li 

json-file is the default logging driver in v3.9 and later.  For more detail. refer to [1]
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1513409

**Review by jcantrill — APPROVED** [review]
@tkatarki Is this erroneous in 3.7?  we flopped back and forth between journal and json. @ewolinetz Maybe you know what the 3.7 default is?

**Comment by ewolinetz** [comment]
It looks like the default docker log driver (via Ansible) was empty... so I believe it would have been the default driver that that version of Docker configured OOTB

**Comment by mburke5678** [comment]
@ewolinetz @jcantrill @anpingli It seems that we can merge this PR to move the release note on the default docker driver from 3.7 to 3.9 release notes, as the default was added to OpenShift in 3.9, not 3.7. Please let me know if there are any objections.

**Pull request merged**
