### PR TITLE
admission_controllers.html: don't show link in non-enterprise docs

### LINKED ISSUE #5240: 404 link from admission control
https://docs.openshift.org/latest/architecture/additional_concepts/admission_controllers.html#admission-controllers-customizable-admission-plug-ins

Restricting Role Bindings link

### PR DESCRIPTION
**Pull request by php-coder**
Fixes #5240

PTAL @openshift/team-documentation @pweil- 
CC @simo5

### CODE REVIEW

**Comment by mburke5678** [comment]
@php-coder LGTM Am I correct that this change only goes into 3.5/1.5 and 3.6/1.6? The link does not appear in Origin 1.4 and earlier.

**Comment by php-coder** [comment]
Perhaps, yes, because it was added in this year (see 9a4a48238b80771ba4d92f3dd7e9de62e86fae39)

**Comment by php-coder** [comment]
Yes, it's was a new feature in 3.5: https://github.com/openshift/openshift-docs/pull/3990#issuecomment-288170482

**Comment by php-coder** [comment]
Hold on, looks like not a link placed wrong but the documentation itself.

**Comment by php-coder** [comment]
Based on this comment https://github.com/openshift/openshift-docs/pull/3990#issuecomment-329822962 we should fix the docs.

**Pull request closed without merging**
