### PR TITLE
OSDOCS#10119: Release note for new interactive flag for deleting reso…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…urces

Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10119

Link to docs preview:
https://76896--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-interactive-flag

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ardaguclu** [comment]
> @ardaguclu @gauravsingh85 
> 
> I'm looking at this[ comment in the Jira](https://issues.redhat.com/browse/OCPSTRAT-917?focusedId=23787499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23787499).
> 
> > new --interactive flag in delete command was added in 4.15(1.28) as an alpha(can only be used after enabling some environment variable). In 4.16, this flag can be used without enabling anything and it is in beta; oc delete --all --interactive 
> >
> > That said, customers can use this flag in 4.16. But this will be completely done when it is promoted to GA in 4.17(1.31) https://github.com/kubernetes/enhancements/pull/4396
> 
> Does this mean that this --interactive flag should be announced as tech preview for 4.16?
> 
> CC @ingvagabund

That is correct. This feature is in stable in 4.17(1.30) and in tech preview in 4.16

**Comment by bergerhoffer** [comment]
Thanks @ardaguclu! I've updated this release note to mention its TP status. Can you please review the wording in this PR when you get a chance?

Preview: https://76896--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-interactive-flag

**Comment by ardaguclu** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please QE review?

Preview: https://76896--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-interactive-flag

**Pull request merged**
