### PR TITLE
BZ1959400: Break out OCP 3 to 4 migration into top level doc

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1959400

Move the MTC section for 3>4 to a top level folder.
4.x sections will remain in MTC.

4.5+

Preview: https://deploy-preview-32411--osdocs.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/about-migrating-from-3-to-4.html

Ready for QE.

### CODE REVIEW

**Review by sergiordlr — APPROVED** [review]
Looks good to me.

Thank you very much!

**Comment by apinnick** [comment]
I will create separate PRs for the branches with merge conflicts.

**Comment by apinnick** [comment]
Merged too soon.

**Pull request merged**
