### PR TITLE
OSDOCS-1786: Adding a link to common parameters to all IDP assemblies

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1786

Preview: https://deploy-preview-29750--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-ldap-identity-provider.html#additional-resources

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
@rhpmali Can you please review this? It's just a simple link back to the common IDP parameters, from each IDP provider's doc. Thanks!

Preview: https://deploy-preview-29750--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-ldap-identity-provider.html#additional-resources

**Comment by rhpmali** [comment]
lgtm

**Pull request merged**
