### PR TITLE
fix indentation for pod creation steps

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to rhacs-docs
- Cherry pick to `rhacs-docs-4.0`
- Cherry pick to `rhacs-docs-3.74`
- Cherry pick to `rhacs-docs-3.73`

Issue: Updates to #57249 

[Link to docs preview
](https://58511--docspreview.netlify.app/openshift-acs/latest/upgrading/upgrade-operator.html#rollback-operator-upgrades-console_upgrade-operator)

QE review:
- [x] QE has approved this change. (**N/A - ACS has no QE, approved by SME**)

Additional information:

- Add in change to all versions
- Cherry pick to 4.0 docs in progress (forgot to include in original PR) - OK to merge to 4.0 since 4.0 docs won't go "live" until the page that controls them being visible is published at GA.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Nice improvements, @kcarmichael08 !

**Comment by kcarmichael08** [comment]
Will do a manual cp for 4.0

**Pull request merged**
