### PR TITLE
OSDOCS-6566: Add IPsec support for IBM Cloud

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-6566

Version(s):  4.14

Issue:

Link to docs preview:

- [Specifying advanced network configuration](https://62429--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.html#modifying-nwoperator-config-startup_installing-ibm-cloud-network-customizations)
- [Cluster Network Operator configuration object](https://62429--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.html#nw-operator-cr-cno-object_installing-ibm-cloud-network-customizations)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@mccv1r0, I've removed the conditionals that hide IPsec information for IBM Cloud. Is this what you had in mind? Thanks!

**Comment by jab-rh** [comment]
@rbbratta, this exposes IBM Cloud as supported for IPsec; Does this look reasonable? Thanks!

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Comment by zshi-redhat** [comment]
> @zshi-redhat, does this look okay? Thanks!

yes, looks good.

**Pull request merged**
