### PR TITLE
GH#42369: fixes command by adding node_name

### PR DESCRIPTION
**Pull request by JoeAldinger**
4.7+ I need labels and merge please.

Github issue #42369 

[Preview](https://deploy-preview-42421--osdocs.netlify.app/openshift-enterprise/latest/support/troubleshooting/troubleshooting-network-issues.html)

Adds <node name> in command to prevent error message

@memodi PTAL

### CODE REVIEW

**Comment by memodi** [comment]
Verified command with `node_name` passes successfully; tested with below versions:
`$ oc version
Client Version: 4.10.0-0.nightly-2022-01-13-061145
Server Version: 4.10.0-0.nightly-2022-02-26-230022
Kubernetes Version: v1.23.3+e419edf`

/label qe-approved

**Comment by sagidlow** [comment]
LGTM

**Pull request merged**
