### PR TITLE
[BZ2106817] Add ShiftStack restricted IPI ifeval to cluster deploy module

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.6-4.12

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2106817

Link to docs preview: http://file.rdu.redhat.com/~mbridges/ifeval-fix/installing/installing_openstack/installing-openstack-installer-restricted.html#installation-launching-installer_installing-openstack-installer-restricted

Additional information: This PR only addresses the restricted ShiftStack IPI assembly. More are coming to fix additional ifeval problems for other platforms that I've found in the module.

### CODE REVIEW

**Comment by maxwelldb** [comment]
No QE needed on this--just making sure the conditional statements are correct.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
