### PR TITLE
bug 1905290 - Fixing incorrect output for cmd "oc get MachineConfig" (2 instances)

### PR DESCRIPTION
**Pull request by lpettyjo**
Fixes for Buzilla 1905290 (https://bugzilla.redhat.com/show_bug.cgi?id=1905290)

@mnguyen PTAL

### CODE REVIEW

**Comment by lpettyjo** [comment]
@gpei PTAL.

**Comment by gpei** [comment]
Here's the machineconfig output from the 4.7 and 4.6 cluster

4.7 
```
 oc get machineconfig
 NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
 00-master                                          ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 00-worker                                          ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 01-master-container-runtime                        ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 01-master-kubelet                                  ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 01-worker-container-runtime                        ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 01-worker-kubelet                                  ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 99-master-generated-registries                     ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 99-master-ssh                                                                                 3.1.0             31m
 99-worker-generated-registries                     ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 99-worker-ssh                                                                                 3.1.0             31m
 rendered-master-d28423a871e5f028bf95b1830553cd8e   ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
 rendered-worker-4b90f2f9ab42c1aef4d939982860d1db   ff9431921ef6c22f602da46c07980622f2809546   3.2.0             24m
```

4.6
```
 oc get machineconfig
 NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
 00-master                                          5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 00-worker                                          5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 01-master-container-runtime                        5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 01-master-kubelet                                  5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 01-worker-container-runtime                        5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 01-worker-kubelet                                  5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 99-master-generated-registries                     5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 99-master-ssh                                                                                 3.1.0             77m
 99-worker-generated-registries                     5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
 99-worker-ssh                                                                                 3.1.0             77m
 rendered-master-0f314bb55448c47e6776e16e608c5912   5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             42m
 rendered-master-c7761e6162e6c9538b0cdd7eef567d38   5ce9351ceb24e721e28cd82de3a44fc7cc27137c   3.1.0             65m
```

So the change is ok for 4.7, but for 4.6 we need to keep the IGNITIONVERSION as 3.1.0 based on above result.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
