### PR TITLE
Updated URL

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses https://github.com/openshift/openshift-docs/issues/4454

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@tiwillia PTAL

**Comment by tiwillia** [comment]
@ahardin-rh We might just not want to include a link here. There are several free-tier clusters, meaning there are several internal registries. The one linked is just one of those.

**Comment by ahardin-rh** [comment]
@tiwillia Thanks! Updated with a replaceable instead.

**Comment by tiwillia** [comment]
@ahardin-rh help me out here, whats a replaceable? Do we have a way to replace it with the right URL depending on which cluster the user is a part of?

**Comment by ahardin-rh** [comment]
@tiwillia The example is just updated to not be specific (<registry_URL>), since the path can change. Would the user already know the URL, or would they have to look it up somewhere? If they have to look it up, we can provide guidance here as to how they can do that.

**Comment by siamaksade** [comment]
@ahardin-rh  I don't know of any other way to retrieve the registry URL. Users don't have access to list routes in the _default_ namespace. It might actually make sense to have it somewhere within the web console on e.g. About page.

Alternatively if registry URLs follow a pattern across online clusters, we could specify the pattern: `registry.<plan>-<region>.openshift.com`

We can document then that the `<plan>-<region>` is the same as the one they see in the master URL.

**Comment by tiwillia** [comment]
@abhgupta and I yesterday discussed the possibility of adding this URL into the console `About` page, as mentioned above. The current plan is to add the URL there: https://trello.com/c/zztJk7Lk/787-2-add-registry-url-in-about-cli-page-in-console

Perhaps we can hold off on setting the URL in the docs and instead document the existence of the URL in the console, once its ready?

**Comment by abhgupta** [comment]
@ahardin-rh @timothyh @siamaksade Here are my thoughts.

1. Add a link to the registry URL on the console "About" or "Command Line Tools" page
2. Add documentation to provide the URL format for the registry (with a replaceable for cluster ID) --> `registry.<clusterID>.openshift.com`
3. Perhaps, in the docs, provide a list of cluster region names to cluster ID mappings (eg: Starter US East 1 --> starter-us-east-1)

**Comment by tiwillia** [comment]
@abhgupta that sounds great. We can probably move this PR to complete # 2 in your list for now.

**Comment by ahardin-rh** [comment]
@tiwillia @abhgupta @siamaksade Thanks! I updated the PR, satisfying #2 on @abhgupta's list. 

#3 Is something worth discussing with @aheslin

**Comment by tiwillia** [comment]
LGTM 👍

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
