### PR TITLE
improve documentation about autogenerated SA tokens

### PR DESCRIPTION
**Pull request by stlaz**
Version(s):
4.11+

Issue: none

Link to docs preview: 
https://56715--docspreview.netlify.app/openshift-enterprise/latest/authentication/using-service-accounts-in-applications.html#auto-generated-sa-token-secrets_using-service-accounts

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@xingxingxia Can you please QE review this?

Preview: https://56715--docspreview.netlify.app/openshift-enterprise/latest/authentication/using-service-accounts-in-applications.html#auto-generated-sa-token-secrets_using-service-accounts

**Comment by xingxingxia** [comment]
/lgtm
Good catch, thanks

**Pull request merged**
