### PR TITLE
[OSDOCS#6098]: Add egress IP support on Nutanix 

### PR DESCRIPTION
**Pull request by tmalove**
[OSDOCS-6098](https://issues.redhat.com//browse/OSDOCS-6098)

Version(s): 4.14+

Link to docs preview: https://60574--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.html#nw-egress-ips-platform-support_configuring-egress-ips-ovn

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
@racedo @makentenza Will you review this update? Thanks!

**Comment by anuragthehatter** [comment]
@huiran0826 PTAL. thanks

**Comment by makentenza** [comment]
LGTM

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
