### PR TITLE
OCPBUGS#16054: Adding DHCP as a supported network protocol

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.14+

Issue:
This issues addresses [ocpbugs-16054](https://issues.redhat.com/browse/OCPBUGS-16054).

Link to docs preview:

[Networking requirements](https://65005--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_nutanix/preparing-to-install-on-nutanix#installation-nutanix-installer-infra-requirements-networking_preparing-to-install-on-nutanix)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@sgaoshang Ready for QE review. PTAL. Thank you.

**Comment by yannickstruyf3** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
