### PR TITLE
GA Vertical Pod Autoscaling

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-1845

No new functionality per https://issues.redhat.com/browse/OCPNODE-437?focusedCommentId=15964418&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15964418

### CODE REVIEW

**Comment by mburke5678** [comment]
@weinliu Can you please take a look? This issue is to promote this feature from TP to GA. No new functionality.

**Review by jeana-redhat — APPROVED** [review]
lgtm

**Pull request merged**
