### PR TITLE
GH#82954: remove duplicate PIDPressure node condition

### PR DESCRIPTION
**Pull request by peterroth**
Version(s):
4.17 back to 4.10.

Issue:
GitHub #82954

Link to docs preview:
https://82955--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-viewing.html

QE review:
N/A

### CODE REVIEW

**Comment by peterroth** [comment]
Hello @bergerhoffer,
Could you please help me with this PR? :)

**Comment by bergerhoffer** [comment]
@peterroth Thanks for submitting! I'll work on getting this in. Just note that we only support back to OCP 4.12, so that's the farthest I can backport this change.

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
