### PR TITLE
Remove -1 as unlimited for MaxScheduledImageImportsPerMinute

### PR DESCRIPTION
**Pull request by mfojtik**
@pweil- PTAL

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1388319

### CODE REVIEW

**Review by pweil- — APPROVED** [review]
LGTM 

FYI to others - removes a bit of misleading doc while the bug is being fixed as a non-blocker

**Comment by pweil-** [comment]
fix for -1 is merged in origin now.  https://github.com/openshift/origin/pull/13315

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
