### PR TITLE
OCPBUGS-18062: Removing runtimeclass section

### PR DESCRIPTION
**Pull request by rohennes**
OCPBUGS-18062: You cannot assign a container runtime class to controller and speaker pods. Removing this section.

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-18062

Link to docs preview:
_Configuring a container runtime class in a MetalLB deployment_ removed from this section: 
https://70345--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/metallb/metallb-operator-install.html#nw-metallb-operator-deployment-specifications-for-metallb_metallb-operator-install

QE review:
- [x] QE has approved this change.

Additional information:
Removing content only.

### CODE REVIEW

**Comment by gkopels** [comment]
lgtm

**Review by gkopels — APPROVED** [review]

**Comment by dfitzmau** [comment]
Module removed and this module is not xref dependent.

/remove-label peer-review-in-progress

/label peer-review-done

**Review by dfitzmau — APPROVED** [review]

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
