### PR TITLE
can't update from 4.1.z to 4.2

### PR DESCRIPTION
**Pull request by kalexand-rh**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, @cooktheryan  +1'd this change in Slack.  Please let me know how you want to proceed.

**Comment by bergerhoffer** [comment]
@kalexand-rh does this need to be added to the known issues of the release notes too?

**Comment by kalexand-rh** [comment]
@bergerhoffer, I'm discussing that with Vikram.

**Comment by vikram-redhat** [comment]
Normally, we don't update the list of known issues after GA unless there is a z stream release. Let's leave this at a warning till it is fixed.

**Pull request merged**
