### PR TITLE
CNV-9305 - RN - Template wizard auto-fills details when selecting OS

### PR DESCRIPTION
**Pull request by aburdenthehand**
Release Note for VM Templates in the UI: When you select OS, the default Flavor and Workload Profile is automatically filled

CNV-9305

### CODE REVIEW

**Comment by jelkosz** [comment]
lgtm

**Comment by yaacov** [comment]
@gouyang hi, please review

**Comment by gouyang** [comment]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Review by jeana-redhat — APPROVED** [review]
approving exception

**Pull request merged**
