### PR TITLE
Fixed links to templates

### PR DESCRIPTION
**Pull request by vikram-redhat**

### CODE REVIEW

**Comment by adellape** [comment]
@vikram-redhat I'm not sure what this is fixing, because the links still don't work. So I've put the `to_followup` label back on for now.

**Comment by vikram-redhat** [comment]
@adellape - the links to the templates were broken. It fixes those.

**Comment by vikram-redhat** [comment]
@adellape - Ah you're saying they still don't work? Strange. Let me check.

**Comment by vikram-redhat** [comment]
@adellape - Reverted, removed milestones and labels and submitted a new one (https://github.com/openshift/openshift-docs/pull/3105). Thanks Alex.

**Pull request merged**
