### PR TITLE
The OpenShift-Ansible deployed loadbalancer is not recommended for production use

### PR DESCRIPTION
**Pull request by mburke5678**
Requested via https://github.com/openshift/openshift-docs/issues/2159

### CODE REVIEW

**Comment by mburke5678** [comment]
@sdodson 
Do I have this right? I used the phrase "not recommended for production environments" to be more in line with other parts of the doc. Am I confusing the issue? Is the HAProxy load balancer a problem in cloud-based clusters only?

"This HAProxy load balancer is intended to illustrate the API server's HA mode and is not recommended for production environments. If you are deploying to a cloud provider we recommend that you deploy a cloud-native TCP-based load balancer or take other steps to provide a highly available load balancer."

**Review by sdodson — APPROVED** [review]
Yeah that's fine

**Comment by mburke5678** [comment]
@jianlinliu Is your group the proper team to review this PR?

**Comment by jianlinliu** [comment]
LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Small paragraph added

**Comment by bmcelvee** [comment]
LGTM 🍂

**Comment by mburke5678** [comment]
[rev_history]
|xref: ../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Advanced Installation]
|Added a note that the default HAProxy load balancer is intended for non-production environments.
%

**Comment by vikram-redhat** [comment]
@mburke5678 - there is a small space between xref and the link.

**Pull request merged**
