### PR TITLE
Bug - 1537851 Added value for provider: local for cluster loader topic

### PR DESCRIPTION
**Pull request by bfallonf**
For : https://bugzilla.redhat.com/show_bug.cgi?id=1537851

Will followup for review via email.

### CODE REVIEW

**Comment by bfallonf** [comment]
Changed to better indicate the relevance of the `provider` value.

**Comment by bfallonf** [comment]
Verified the information is best and accurate. @openshift/team-documentation PTAL

**Comment by mburke5678** [comment]
@bfallonf LGTM

**Comment by bfallonf** [comment]
Thanks @mburke5678 . I'll merge.

**Pull request merged**
