### PR TITLE
OSDOCS-1857 Empty RG for Azure

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1857

Preview: https://deploy-preview-31113--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-configuration-parameters_installing-azure-customizations

### CODE REVIEW

**Comment by codyhoag** [comment]
@e-tienne can you review and let me know if any other info should be added? Thanks!

**Comment by codyhoag** [comment]
@e-tienne bump. Let me know if you have any feedback for this. Thanks!

**Comment by codyhoag** [comment]
@mgahagan73 PTAL

**Comment by mgahagan73** [comment]
I reviewed the doc change as well as successfully installed a cluster to an empty resource group using 4.8.0-0.nightly-2021-04-05-174735 so the doc change looks good to me!

**Review by jboxman — APPROVED** [review]
Lots of conditionals; LGTM.

**Pull request merged**
