### PR TITLE
CNV-30815: Update OpenShift doc for GC disabled by default

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.14+

**Issue:**
https://issues.redhat.com/browse/CNV-30815

**Link to docs preview:**
https://62701--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-creating-data-volumes.html#virt-about-datavolumes_virt-creating-data-volumes

**QE review:**
- [x] QE has approved this change.

### CODE REVIEW

**Review by skrthomas — APPROVED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging!

**Pull request merged**
