### PR TITLE
[OSDOCS-3938]: Updating MCE version in hosted control planes overview

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.11, 4.12

Issue: https://issues.redhat.com/browse/OSDOCS-3938

Link to docs preview (VPN required): http://file.rdu.redhat.com/lahinson/osdocs-3938/architecture/control-plane.html#hosted-control-planes-overview_control-plane

Additional information:

### CODE REVIEW

**Comment by jiezhao16** [comment]
lgtm

**Comment by enxebre** [comment]
thanks!
/lgtm

**Comment by Amrita42** [comment]
lgtm

**Comment by lahinson** [comment]
Thank you, @mburke5678!

**Pull request merged**
