### PR TITLE
[OSDOCS-6455] Azure AD Workload ID for OLM Operators (CCO reference)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.15+

Issue:
[OSDOCS-6455](https://issues.redhat.com//browse/OSDOCS-6455)

Link to docs preview:
[OLM-managed Operator support for authentication with Azure AD Workload Identity](https://69663--ocpdocs-pr.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-short-term-creds#cco-short-term-creds-azure-olm_cco-short-term-creds)

QE review:
- [x] QE has approved this change.

Additional information:
Possible 4.14.z backport later

### CODE REVIEW

**Comment by dlom** [comment]
LGTM :shipit:

**Comment by jeana-redhat** [comment]
@jianping-shu this is ready for QA but no rush at all :)

**Comment by jianping-shu** [comment]
LGTM
@jeana-redhat In OLM part doc, all the Azure credentials(azureClientID, azureRegion, azureSubscriptionID, azureTenantID) needs to configured in the CredentialsRequest file, pls. help notify me when OLM part doc is in review.

**Comment by jeana-redhat** [comment]
> LGTM @jeana-redhat In OLM part doc, all the Azure credentials(azureClientID, azureRegion, azureSubscriptionID, azureTenantID) need to be configured in the CredentialsRequest file, pls. help notify me when OLM part doc is in review.

Thanks! I will be sure to let the OLM writing team know to include you in reviews when they are ready.

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by jeana-redhat** [comment]
force push to refresh pre-merge

**Pull request merged**
