### PR TITLE
[OSDOCS-8407]:Wrong placement of STS related documentation

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8407
Link to docs preview:

https://67800--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-getting-started-workflow
QE review:
- [ ] QE has approved this change.

Additional information:

**Reviewers: The original JIRA ticket which prompted this PR stated that there was wrong placement of STS related documentation. Reference to STS deployment was removed from this doc b/c it was included in a section that describes deploying a cluster WITHOUT AWS STS. The snippet (TIP) was left in the doc to inform readers that using STS is the preferred method.** 

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello 
[@Xue Li](https://redhat-internal.slack.com/team/UEEQ10T4L)
/
[@yuwan](https://redhat-internal.slack.com/team/UEE8X128Y)
, can I get a QE review for this PR? Thank you!

**Review by ShaunaDiaz — APPROVED** [review]
/remove-label peer-review-needed

**Pull request merged**
