### PR TITLE
BZ1978334: Clarifying port definition in private installs

### PR DESCRIPTION
**Pull request by skrthomas**
https://bugzilla.redhat.com/show_bug.cgi?id=1978334

For 4.7+

Preview: https://deploy-preview-35213--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-vnet.html#installation-about-custom-azure-vnet-requirements_installing-azure-vnet (Table: Required ports under Network security group requirements)

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
LGTM, yes.

I think anyone who wants more information would be best off with an architecture/flow diagram of the installation process.

**Comment by skrthomas** [comment]
For transparency, I'm pasting in email follow-up of Colin's review:

Sara: Are you saying that this table shouldn't be included in other areas of the doc? Or are you saying that anyone installing on another platform would be best served with an architecture diagram, and not this table of port reqs?

Colin:I think it'd be good to extend the port requirement across all platforms. 

I don't think an architecture diagram would be a substitute for the port requirement list.  I am sure many system administrators will come at it from the point of view of "how do I need to configure my network" and that's what the port requirement list helps with.

The architecture diagram is more *why* they need to configure their network in this way, which would also be potentially useful but not the same as "how".
I wasn't suggesting you or anyone else should do a diagram for this now, just an aside for a potential future improvement/addition if that makes sense.

**Comment by skrthomas** [comment]
@lmurthyrh can you assign QA for this BZ please? To Hung says he is no longer QA for this product area.

**Comment by codyhoag** [comment]
@skrthomas I was told recently that @MayXuQQ would be covering some QE duties for Azure. Perhaps they can verify?

**Comment by skrthomas** [comment]
@xingxingxia ready for QA please 🙏

**Comment by tsze-redhat** [comment]
I looked at the preview page.
The line about the port is there but when I scroll, the top bar that contains the drop down box for version stay on same position overlapping the text.
Is that intended?

**Comment by skrthomas** [comment]
@gpei ready for QA

**Comment by skrthomas** [comment]
@tsze-redhat I think something wonky is happening in the preview build. I don't think this will actually be the way the doc looks. Only the port definition will change, not any of the version bar area.

**Comment by gpei** [comment]
@skrthomas lgtm

**Comment by sagidlow** [comment]
LGTM!

**Pull request merged**
