### PR TITLE
Improve OS upgrade instructions for hosts running GlusterFS

### PR DESCRIPTION
**Pull request by yrro**
The existing instructions were unclear and the commands given were incomplete.

I have fleshed the description of the process out in a way that makes sense to me...

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@xltian could I get someone to review these changes?

**Comment by vikram-redhat** [comment]
@yrro it will require submitting this to master-3 branch first and then CPing to the 3.11 branch. @bobfuru - once @yrro has made this change and @xltian's team has given QE ack, can you please take it forward?

**Comment by xltian** [comment]
@liangxia  Can you check if this something your team can review?

**Comment by liangxia** [comment]
LGTM.
Perhaps we need the PR to point to the correct branch first?

**Comment by yrro** [comment]
Thanks for the review.

I've rebased against `master-3` and squashed into one commit for good measure.

**Comment by liangxia** [comment]
LGTM

**Comment by bobfuru** [comment]
@yrro @vikram-redhat I merged to master-3, all good. Then I cherry-picked to 3.11 using the UI before seeing a note in the OpenShift Docs Manual that that method can only be done from master. The UI cherry pick failed but then opened a new PR 17891 (see above), which I closed.

Then I attempted a command-line cherry-pick to 3.11 but that failed because the commit has two parents. Finally, I cherry-picked to each of these commits. This was successful, I think. But I'd like someone to check and make sure the content displays as intended.

**Comment by codyhoag** [comment]
@bobfuru @vikram-redhat FYI: I also had similar issues in #17880 and #17889 today.

**Comment by vikram-redhat** [comment]
@bobfuru which is the 3.11 PR for this?

**Comment by bobfuru** [comment]
> @bobfuru which is the 3.11 PR for this?
Looks like I never created one before, so I created [PR 18065](https://github.com/openshift/openshift-docs/pull/18065)

**Pull request merged**
