### PR TITLE
oadp-932: removed if statements

### PR DESCRIPTION
**Pull request by HagayVider1**
HG# : 61904
OCPBUGS# : [OADP-932](https://issues.redhat.com//browse/OADP-932)

Version(s): OADP  1.2.0

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14

Issue: https://issues.redhat.com/browse/OADP-932

Link to docs preview: https://61904--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html#migration-configuring-azure_installing-oadp-azure

QE review:
- [X] QE has approved this change.

Amos Mastbaum has approved. See Jira ticket [OADP-932](https://issues.redhat.com//browse/OADP-932).

Additional information:

### CODE REVIEW

**Review by snarayan-redhat — COMMENTED** [review]
lgtm

**Comment by kalexand-rh** [comment]
I've opened the `enterprise-4.15` branch. Please review your PR and update the applicable versions to also cover 4.15 if you expect that the changes in this PR will be valid in that branch.

**Comment by kalexand-rh** [comment]
4.11 is now [EOL](https://access.redhat.com/support/policy/updates/openshift), and we are no longer updating it. Please set the versions to 4.12+.

**Pull request closed without merging**
