### PR TITLE
Bug 1290487 Added section on overlayfs

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1290487

Will confirm with SMEs the right information is there.

### CODE REVIEW

**Comment by mburke5678** [comment]
@bfallonf Is overlayFS required/optional? Does the user install it (I assume) or does the installer? Otherwise LGTM.

**Comment by bfallonf** [comment]
@mburke5678 @openshift/team-documentation I reworded it. WDYT?

**Comment by mburke5678** [comment]
@bfallonf LGTM!!

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/install/prerequisites.adoc#install-config-install-prerequisites[Installing a Cluster -> Prerequisites]
|Added the xref:../install_config/install/prerequisites.adoc#install-prerequisites-overlayfs[Using OverlayFS] section.
%

**Pull request merged**
