### PR TITLE
Remove containerd changes during WMCO 6.0.0 update

### PR DESCRIPTION
**Pull request by mburke5678**
Remove section of the upgrade that is specific to WMCO 5.x to 6.x updates.

[Windows Machine Config Operator upgrades](http://file.rdu.redhat.com/mburke/winc-remove-containerd-chages/windows_containers/windows-node-upgrades.html#wmco-upgrades_windows-node-upgrades). Removed second paragraph and two bullet lists that followed.
[
Current version](https://docs.openshift.com/container-platform/4.12/windows_containers/windows-node-upgrades.html#wmco-upgrades_windows-node-upgrades)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mburke5678** [comment]
@aravindhp Is this the correct thing to do for the WMCO 7.0.0 and 8.0.0+ docs?

**Review by aravindhp — COMMENTED** [review]
Yes, this can be removed. But lets get feedback from @openshift/openshift-team-windows-containers also.

**Comment by sebsoto** [comment]
Removing this makes sense to me, it should not be relevant in the 7.0.0 or 8.0.0 docs.

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
