### PR TITLE
Removes TP banner

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10 and 4.11

Issue: None

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/remove-tp-baner/networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.html

Additional information:

QE ack is not required

### CODE REVIEW

**Comment by bscott-rh** [comment]
LGTM.

**Comment by ahardin-rh** [comment]
@xenolinux Thanks for this update! Did this feature GA with 4.11? If so, we will need to update the [release notes tech preview table](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview) to reflect that the feature moved from TP to GA and send a change management email per the OpenShift Docs Manual instructions. Thanks!

**Comment by xenolinux** [comment]
> @xenolinux Thanks for this update! Did this feature GA with 4.11? If so, we will need to update the [release notes tech preview table](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview) to reflect that the feature moved from TP to GA and send a change management email per the OpenShift Docs Manual instructions. Thanks!

Okay. I created the [PR](https://github.com/openshift/openshift-docs/pull/49430) to track the [release notes tech preview table](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview) related changes.

**Comment by ahardin-rh** [comment]
Sounds great. Thank you!

**Pull request merged**
