### PR TITLE
[INTERNAL-FIX] OCPBUGS-30254-fix: Added file metadata toinstallation-vsphere-infrast…

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.14 +

A merge review requests that stemmed from [OCPBUGS-30254](https://issues.redhat.com/browse/OCPBUGS-30254)

Preview link: [VMware vSphere infrastructure requirements](https://72914--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs)

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM!

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
