### PR TITLE
RHDEVDOCS-5645-pipelines: Remove additional resources section from th…

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **Version for cherry-picking**: pipelines-docs-1.10 and later
• **JIRA issue**: [RHDEVDOCS-5645](https://issues.redhat.com/browse/RHDEVDOCS-5645)
• **Preview page**: [About Red Hat OpenShift Pipelines](https://65801--docspreview.netlify.app/openshift-pipelines/latest/about/about-pipelines)
• SME  and QE Review not needed
• **Peer-review**: @mramendi

### CODE REVIEW

**Review by mramendi — APPROVED** [review]

**Review by adellape — APPROVED** [review]
@ekristova Please use the `peer-review-needed` label so that the openshift-docs repo review squad can provide review, before adding to the `merge-review-needed` queue. 🙇

**Comment by adellape** [comment]
> Version for cherry-picking: pipelines-docs-1.10 and later

Please also note each individual branch that you're interested in getting a PR picked to, as merge-reviewers may not know what all are the latest relevant branches for some of the layered products. From checking the available branches right now, I'm assuming it's: `pipelines-docs-1.10`, `pipelines-docs-1.11`, and `pipelines-docs-1.12`.

**Pull request merged**
