### PR TITLE
Update REST API to match Origin 1.0.7

### PR DESCRIPTION
**Pull request by smarterclayton**
Regenerated from latest

### CODE REVIEW

**Comment by adellape** [comment]
FYI @vikram-redhat @bfallonf We'll need to touch up the few spots that usually give the Customer Portal build grief.

**Comment by smarterclayton** [comment]
Are there concrete changes we can make to generation?

**Comment by tnguyen-rh** [comment]
@adellape @smarterclayton
Aside from Portal-related concerns, generation needs to able to output stuff like https://github.com/openshift/openshift-docs/pull/926/files (the "subfield `name`" hack).
Related BZs:

- https://bugzilla.redhat.com/show_bug.cgi?id=1244889
- https://bugzilla.redhat.com/show_bug.cgi?id=1258235

**Comment by tnguyen-rh** [comment]
@smarterclayton 
See also: https://trello.com/c/N6MzKDjN/58-rewrite-the-rest-api-doc-generation-program

**Comment by vikram-redhat** [comment]
Doesn't require a followup.

**Pull request merged**
