### PR TITLE
Remove prompt with hostname

### PR DESCRIPTION
**Pull request by jboxman**
This is superfluous.

### CODE REVIEW

**Comment by jboxman** [comment]
Must confirm what happens with note blocks: file:///Users/jasonb/Self/work/openshift-docs/_preview/openshift-enterprise/refresh-adv-net-install/installing/installing_aws/installing-aws-network-customizations.html#installation-aws-config-yaml_installing-aws-network-customizations

**Review by mffiedler — APPROVED** [review]
LGTM

**Comment by jboxman** [comment]
@mffiedler thanks!

**Pull request merged**
