### PR TITLE
OCPBUGS-181 updated vmware URL

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-181

Link to docs preview:
[Updating the virtual hardware for control plane nodes on vSphere](http://file.rdu.redhat.com/antaylor/OCPBUGS-181/updating/updating-hardware-on-nodes-running-on-vsphere.html#update-vsphere-virtual-hardware-on-control-plane-nodes_updating-hardware-on-nodes-running-in-vsphere) Step 4

Additional information:
Corrected the link in two other places as well.

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by sheriff-rh** [comment]
Peer review complete, dev ack in JIRA. 

/label merge-review-needed

**Pull request merged**
