### PR TITLE
OCPBUGS#32048: Remove tech preview banner

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OCPBUGS-32048

Link to docs preview: https://74480--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-troubleshooting.html

QE review: Approved

Additional information:

### CODE REVIEW

**Comment by smunje1** [comment]
@xenolinux This changes LGTM. As I am new to the peer review squad, I request that you wait until @bscott-rh gives approval.

**Comment by xenolinux** [comment]
@bscott-rh Can you please merge the PR after your review?

**Comment by bscott-rh** [comment]
@smunje1 Peer review LGTM
@xenolinux It looks like this PR should get QE's approval because it's changing the supported status of a feature in the product.

**Comment by bscott-rh** [comment]
Merge review LGTM

**Pull request merged**
