### PR TITLE
OSDOCS-8835

### PR DESCRIPTION
**Pull request by smunje1**
[OSDOCS-8835](https://issues.redhat.com/browse/OSDOCS-8835): [rosa-] Issue in file rosa_architecture/rosa-sts-about-iam-resources.adoc

Aligned team: Service Delivery
OCP version for cherry-picking: enterprise-4.14+
JIRA issues: [OSDOCS-8835](https://issues.redhat.com/browse/OSDOCS-8835)
Preview pages: [ROSA build preview](https://70097--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources#rosa-sts-account-wide-roles-and-policies-creation-methods_rosa-sts-about-iam-resources)
SME review **completed**: @dupliaka
QE review **completed**:  @yuwang-RH
Peer review **completed**: @shipsing and @bburt-rh

### CODE REVIEW

**Review by dupliaka — APPROVED** [review]
LGTM

**Comment by shipsing** [comment]
@smunje1, The PR changes look okay. Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

**Review by bburt-rh — APPROVED** [review]
LGTM. Sorry for the delay.

**Pull request merged**
