### PR TITLE
OSDOCS-11135: adds 4.15.23 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15

Issue:
[OSDOCS-11135](https://issues.redhat.com/browse/OSDOCS-11135)

Link to docs preview:
[4.15.23 async relnote](https://79260--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes.html#microshift-4-15-23-dp_release-notes)

QE review:
- NA stock text

### CODE REVIEW

**Comment by aravipra** [comment]
do not merge until the merge label is added. Now, only review is needed

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
