### PR TITLE
[AWS Installation] Fixes typo in the permissions for the IAM user

### PR DESCRIPTION
**Pull request by aleskandro**
/cc @yunjiang29 @LorbusChris

### CODE REVIEW

**Comment by aleskandro** [comment]
Hi @mburke5678 could you help to check-in this PR?

**Comment by mburke5678** [comment]
@yunjiang29 PTAL

**Comment by mburke5678** [comment]
@mjpytlak FYI

**Comment by yunjiang29** [comment]
/lgtm 

Thanks @aleskandro

**Pull request merged**
