### PR TITLE
OADP and FIPS

### PR DESCRIPTION
**Pull request by RichardHoch**
OADP 1.3; OCP 4.11+

Resolves: https://issues.redhat.com/browse/OADP-2692 by adding a short note describe OADP compliance with FIPS.

Preview: https://65310--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-features-plugins#oadp-fips_oadp-features-plugins

OADP QE approved this PR.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by weshayutin** [comment]
LGTM, holding for QE

**Comment by RichardHoch** [comment]
@akarol Please review.

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by RichardHoch** [comment]
@stillalearner  @weshayutin put a hold on this PR until Aziza verified the functionality was tested. Now that it has been tested, can you remove the hold or should I ask only Wes to do that?

**Comment by RichardHoch** [comment]
@weshayutin Please remove the hold from this PR.

**Comment by GroceryBoyJr** [comment]
Hey @RichardHoch squash your commits pleez.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by RichardHoch** [comment]
GA is Tuesday, November 28.

**Comment by RichardHoch** [comment]
Please merge today; release has gone GA. Thanks.

**Comment by michaelryanpeter** [comment]
Cherrypicks for this PR were missed when the PR was merged. I am correcting that now.

/cherrypick enterprise-4.20

**Comment by michaelryanpeter** [comment]
@anarnold97 ^

**Comment by michaelryanpeter** [comment]
@anarnold97 Everything picked clean except for `enterprise-4.12`. Would you please assign someone to do that manual cherrypick? Feel free to DM when you are ready for a merge.

**Pull request merged**
