### PR TITLE
[RHACS] ROX-13717 add note for PKI user not supported

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
- `rhacs-docs-3.73`

[Issue](https://issues.redhat.com/browse/ROX-13717)

[Link to docs preview](https://openshift-docs-qqonztlss-kcarmichael08.vercel.app/openshift-acs/master/release_notes/373-release-notes.html#known-issues-373)

QE review:
- [x] QE has approved this change.

Additional information:
- Also fixed Release Notes to use variable for abbreviated product name

### CODE REVIEW

**Review by rukletsov — APPROVED** [review]

**Comment by kcarmichael08** [comment]
Rebased & request a merge.

**Pull request merged**
