### PR TITLE
CNV-30686 - new rn for RHEL subscription

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.14 RN

Issue: [CNV-30686](https://issues.redhat.com//browse/CNV-30686)

Link to docs preview: https://63493--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-web-new

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@gouyang Please review. Thanks

**Comment by stevsmit** [comment]
LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Pull request merged**
