### PR TITLE
Update REST APIs

### PR DESCRIPTION
**Pull request by jboxman**
This would have the latest APIs.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@jboxman can this be merged?

**Comment by jboxman** [comment]
@vikram-redhat, it's lacking any of the improvements made subsequently. I may be able to finalize those fixes this weekend, and then update this PR. I need to confirm that the fix for the Prometheus spec produces somewhat useable output; could also release with the huge 200 attribute table if necessary.

At times, there isn't enough water for all the fires.

**Comment by vikram-redhat** [comment]
> At times, there isn't enough water for all the fires.

:D

**Comment by jboxman** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/22214.

**Pull request closed without merging**
