### PR TITLE
NTO: document MCO quirk about nodes with master/worker roles.

### PR DESCRIPTION
**Pull request by jmencak**

### CODE REVIEW

**Comment by jmencak** [comment]
@liqcui  could you please review this from QE perspective?  Thank you!

**Review by liqcui — APPROVED** [review]
/LGTM

**Comment by kmccarron-rh** [comment]
Link to section containing this change:  https://deploy-preview-35978--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/using-node-tuning-operator.html#custom-tuning-specification_node-tuning-operator

**Review by kmccarron-rh — COMMENTED** [review]
lgtm

**Review by codyhoag — APPROVED** [review]

**Pull request merged**
