### PR TITLE
[OSDOCS 7108] Restructure IBM Z toc to one entry point

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14 +

Issue: https://issues.redhat.com/browse/OSDOCS-7108

The installation config parm changes are related to this PR https://github.com/openshift/openshift-docs/pull/62676

Link to docs preview: https://64691--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/preparing-to-install-on-ibm-z

QE review: Doesn't require QE, but @holgwolf approved
- [x] QE has approved this change.

Additional information:
Content reduction: 
Refactoring IBM Z content has saved/removed ~6 pages of redundant documentation.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@SNiemann15 I love to see simplifications like this. Great work here.
@kalexand-rh I was not sure, so I thought it best to ask. Does the consolidation of the topic map require anything of you from the perspective of the Portal?

**Comment by SNiemann15** [comment]
@sjstout PTAL

Does this rework require CM? Will be for 4.14 +  not in between releases.

**Comment by sjstout** [comment]
@SNiemann15 , this change looks great! It really cleans up the TOC. :) I don't think this needs CM since you didn't change anything technical content, and now things are easier to find. 
LGTM

**Review by sheriff-rh — COMMENTED** [review]
This looks great, Silke! Nice work :slightly_smiling_face:

**Comment by kalexand-rh** [comment]
> @SNiemann15 I love to see simplifications like this. Great work here. @kalexand-rh I was not sure, so I thought it best to ask. Does the consolidation of the topic map require anything of you from the perspective of the Portal?

No, only changes to the top-most directories or their entries in the topic-map need attention on the portal.

> @sjstout PTAL
> 
> Does this rework require CM? Will be for 4.14 + not in between releases.

Since it's not being backported, it doesn't need CM.

**Comment by kalexand-rh** [comment]
I'm backporting this simplification to 4.13 and 4.12 as part of some improvements to the installation docs on docs.redhat.com.

**Pull request merged**
