### PR TITLE
[OSDOCS-11556]Document Support A2 (NVIDIA A100 80 GB) GCP nodes

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-11556
Link to docs preview:

https://79782--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#gcp-compute-types_osd-service-definition
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by svmrh** [comment]
@mletalie: Can we align the A2 instances in the order of their capacity, similar to how it is listed in the OCMUI. 

image

**Comment by svmrh** [comment]
Think about it.. the above suggestion is not inline with other instance type categories (General-purpose, compute-optimized, memory-optimized) in OSD as well as in ROSA docs. So, may be we can keep it as is. Sorry for the confusion.

**Comment by mletalie** [comment]
@lento-sun, Could I get a QE review for this PR? Thanks!

**Pull request merged**
