### PR TITLE
Add Configuring and Tuning Cluster Logging

### PR DESCRIPTION
**Pull request by mburke5678**
For integrating @jcantrill 's [Configuring and Tuning Cluster Logging](https://github.com/jcantrill/cluster-logging-operator/blob/3aec81cd16484432ecb12dcc474e173dc54b7432/docs/configuration.md)

### CODE REVIEW

**Comment by mburke5678** [comment]
@jcantrill PTAL. This is based on your [Configuring and Tuning Cluster Logging](https://github.com/jcantrill/cluster-logging-operator/blob/3aec81cd16484432ecb12dcc474e173dc54b7432/docs/configuration.md) document. It is thin on details, such as why you might make different configurations. 
I am working on other PRs (as noted in the files) that add more 4.0 functionality, based on Jiras and test cases. 
Other changes that you have suggested, such as EFK Stack --> cluster logging are also in another PR and can be disregarded here.

**Comment by mburke5678** [comment]
Commit https://github.com/openshift/openshift-docs/pull/13344/commits/3486e49c253426494460029865cbd7383ce918a9 is based on https://jira.coreos.com/browse/OSDOCS-229

**Review by josefkarasek — APPROVED** [review]
:+1:

**Comment by jcantrill** [comment]
> @jcantrill I am not sure where the information in this commit is from: [8121be3](https://github.com/openshift/openshift-docs/commit/8121be33ed081d664655a9fc97320daed7530fe7)
> Is there a Jira that I cannot find?

I don't know we have a specific JIRA card which addresses storage here but a cursory glance tells me we can most likely remove this content.  The intention is that all storage configuration is through PVC; hostPath will not be supported in favor of localvolumes (need to confirm that is an option).

**Comment by mburke5678** [comment]
Passed Travis:
https://travis-ci.org/openshift/openshift-docs/builds/494023608

**Comment by mburke5678** [comment]
Merging at the request of Jeff Cantrill to facilitate logging docs review.

**Pull request merged**
