### PR TITLE
GitHub issue-28150/issue-29904 update PVC command for registry

### LINKED ISSUE #28150: [enterprise-4.6] Issue in file registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc
### Which section(s) is the issue in?
Creating registry storage \ Configuring block registry storage for VMware vSphere
Creating registry storage \ Configuring registry storage for VMware vSphere

### What needs fixing?
Need to change to openshift-image-registry project before running configuration commands
oc project openshift-image-registry

### PR DESCRIPTION
**Pull request by bmcelvee**
Resolves https://github.com/openshift/openshift-docs/issues/28150 and https://github.com/openshift/openshift-docs/issues/29904.

Preview: https://deploy-preview-30776--osdocs.netlify.app/openshift-enterprise/latest/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#installation-registry-storage-block-recreate-rollout_configuring-registry-storage-vsphere

### CODE REVIEW

**Comment by bmcelvee** [comment]
Hi @duanwei33, would you mind reviewing this PR, please? It's an amendment to a PVC creation command. Thank you!

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL, thanks!

**Review by bergerhoffer — COMMENTED** [review]
Change LGTM, but just checking whether this needs to be made back to 4.5 as well

**Comment by bmcelvee** [comment]
Just a bump on this because it likely got lost in requests: Hi @duanwei33, would you mind reviewing this PR, please? It's an amendment to a PVC creation command. Thank you!

**Comment by duanwei33** [comment]
/LGTM
Sorry I missed the first mention @bmcelvee

**Pull request merged**
