### PR TITLE
Fix Red Hat Enterprise Linux CoreOS spelling

### PR DESCRIPTION
**Pull request by koep**
Minor change, but it makes the documentation more consistent (e. g. see [here](https://docs.openshift.com/container-platform/4.6/security/file_integrity_operator/file-integrity-operator-understanding.html)).

### CODE REVIEW

**Comment by jboxman** [comment]
@koep, thanks for this. We're actually using these in `common.adoc`:

```
:op-system-first: Red Hat Enterprise Linux CoreOS (RHCOS)
:op-system: RHCOS
```

So it would be `{op-system-first}` in text.

**Comment by koep** [comment]
Thanks Jason, I should have read the contribution guidelines more carefully. 

Please have a look at the updated commit (I even found another file where this change could be applicable).

**Review by sandrobonazzola — APPROVED** [review]
/lgtm

**Comment by sandrobonazzola** [comment]
Anyone can review / approve / merge?

**Comment by sandrobonazzola** [comment]
@koep looks like this patch needs a rebase (modules/installation-special-config-encrypt-disk.adoc conflicts)

**Comment by koep** [comment]
@sandrobonazzola

**Review by sandrobonazzola — APPROVED** [review]
/lgtm

**Comment by sandrobonazzola** [comment]
@jboxman can you please review / merge?

**Comment by jboxman** [comment]
@sandrobonazzola fixing in a new PR.

**Pull request closed without merging**
