### PR TITLE
NE743: document upstream resolvers

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
**Note: This PR is a rework of https://github.com/openshift/openshift-docs/pull/39661 . The original PR was inadvertently cherrypicked to 4.9, so raising a new PR for 4.10+ only.** 

For 4.10+

https://issues.redhat.com/browse/NE-743

Requires ack from @sherine-k @ShudiLi

### CODE REVIEW

**Comment by sherine-k** [comment]
Merci @chinmayi-chandrasekar !

**Comment by ctauchen** [comment]
/lgtm

Let me know when you're ready for a merge.

**Comment by chinmayi-chandrasekar** [comment]
> /lgtm
> 
> Let me know when you're ready for a merge.



> /lgtm
> 
> Let me know when you're ready for a merge.

@ctauchen The PR can be merged now. Thanks.

**Pull request merged**
