### PR TITLE
OSSMDOC-725: Assist with dev update to doc

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.9+

Issue: https://issues.redhat.com/browse/OSSMDOC-725

Link to docs preview: http://file.bos.redhat.com/tokeefe/servicemesh/service_mesh/v2x/ossm-threescale-webassembly-module.html#openid-connect-use-case_ossm-threescale-webassembly-module

QE review:
- [x] QE has approved this change.

Additional information:

Dev Review: Jacek
QA Review: Filip

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@jewertow and @mattmahoneyrh I'm trying to help usher Jacek's PR through the doc process. I copied his branch and created this PR so I can provide a preview build according to our process. Please provide a quick review when you can. Thanks!

**Review by jewertow — APPROVED** [review]

**Comment by FilipB** [comment]
LGTM

**Comment by mattmahoneyrh** [comment]
LGTM

**Comment by bburt-rh** [comment]
lgtm (but please squash 2 commits to 1)

**Pull request merged**
