### PR TITLE
OCPBUG#10418: Update oc label command for MCP

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-10418

Link to docs preview: https://75567--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-create-performance-profiles.html#gathering-data-about-your-cluster-using-must-gather_cnf-create-performance-profiles --- Step 2.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by MarSik — APPROVED** [review]
/lgtm

**Review by bhardesty — COMMENTED** [review]
LGTM!

**Pull request merged**
