### PR TITLE
OSDOCS#11574: Updating for no Kubernetes API removals in OCP 4.17

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-11574

Link to docs preview:
* https://80514--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/preparing_for_updates/updating-cluster-prepare.html#kube-api-removals_updating-cluster-prepare
* https://80514--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli.html#prerequisites

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@wangke19 Can you please QE review?

This is just temporarily removing the docs on the API removals/admin-ack because there aren't any in 4.17.

Preview:
* https://80514--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/preparing_for_updates/updating-cluster-prepare.html#kube-api-removals_updating-cluster-prepare
* https://80514--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/updating_a_cluster/updating-cluster-cli.html#prerequisites

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Pull request merged**
