### PR TITLE
added kiali command and separated commands in different codeblocks

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSM-136
https://issues.redhat.com/browse/OSSMDOC-117

### CODE REVIEW

**Comment by neal-timpe** [comment]
@jshaughn I can't add you as a reviewer, but you can leave a review if you like. I've also separated the commands to align with OpenShift's style guidelines.

**Review by gbaufake — APPROVED** [review]

**Comment by jshaughn** [comment]
@neal-timpe Fine for me.

**Review by JStickler — APPROVED** [review]
I fired up a cluster-bot and tested the CLI delete commands.  LGTM.

**Review by FilipB — APPROVED** [review]
LGTM

**Pull request merged**
