### PR TITLE
BM three-node clusters now supported for production

### LINKED ISSUE #24211: [enterprise-4.5] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc
### Which section(s) is the issue in?
Installing a cluster on bare metal --> Configuring a three-node cluster

### What needs fixing?
This statement "This provides smaller, more resource efficient clusters for cluster administrators and developers to use for deployment, development, and testing." needs to be updated to include the word "Production" since this feature is GAd with 4.5 release.

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #24211

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you confirm this makes sense? Perhaps "deployments" should be removed too (not sure if it's necessary)? Let me know. Thanks!

**Comment by gpei** [comment]
It's ok for me to add `production` in this section, but looks like we got duplicate "development" there.
`to use for deployment, development, production, and testing`

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
