### PR TITLE
BZ2013756: correct machine config metrics in 4.9

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
For 4.9+
https://bugzilla.redhat.com/show_bug.cgi?id=2013756

[Docs preview](https://deploy-preview-39553--osdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-machine-config-daemon-metrics)

Requires ack from @sergiordlr

### CODE REVIEW

**Review by sergiordlr — APPROVED** [review]
/lgtm 
Thank you very much!

**Comment by mjpytlak** [comment]
@chinmayi-chandrasekar I am curious. Did you intend for this to be a 4.9 fix only?

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
