### PR TITLE
Restricted network clusters not supported for WINC

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: https://deploy-preview-30667--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-2-x.html#wmco-2-0-0

### CODE REVIEW

**Comment by codyhoag** [comment]
Approved in Slack by PM/SME

**Comment by bmcelvee** [comment]
LGTM!

**Comment by Anandnatraj** [comment]
Do want to call out disconnected? Some users may not understand what restricted means

**Comment by Anandnatraj** [comment]
Some thing to the effect of 

Running Windows container workloads is not supported for clusters in a restricted network and disconnected environments
--

**Comment by codyhoag** [comment]
@Anandnatraj how about this instead?
>Running Windows container workloads is not supported for clusters in a restricted network, also known as disconnected clusters.

**Pull request merged**
