### PR TITLE
[enterprise 3-2] Fix Bad Link per PR-8985

### PR DESCRIPTION
**Pull request by mburke5678**
See: #8985 (review)

### CODE REVIEW

**Comment by mburke5678** [comment]
@sdodson Did the `openshift_portal_net` parameter I am referencing in https://github.com/openshift/openshift-docs/pull/8985#pullrequestreview-123511597 change in 3.3? In 3.2 the parameter is `openshift_master_portal_net`?

**Comment by sdodson** [comment]
It looks like at least in 3.2 and newer openshift_portal_net defaults to openshift_master_portal_net so therefore we should document `openshift_portal_net`

**Comment by mburke5678** [comment]
@sdodson PTAL. I changed openshift_master_portal_net to openshift_portal_net in 3.2.

**Review by sdodson — APPROVED** [review]
/lgtm

**Pull request merged**
