### PR TITLE
cnv: Point to the KCS for object maximums

### PR DESCRIPTION
**Pull request by fabiand**
Relates to https://bugzilla.redhat.com/show_bug.cgi?id=1997540

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by fabiand** [comment]
@ctomasko @ousleyp @bgaydosrh please help to review this.

As agreed with @mtessun the goal is to replace the in-docs scale and limits section with a pointer to the KCS https://access.redhat.com/articles/6571671.
Similar to how it is done in the RHV Planning guide section 2.2. See https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/pdf/planning_and_prerequisites_guide/red_hat_virtualization-4.4-planning_and_prerequisites_guide-en-us.pdf

**Comment by ousleyp** [comment]
@fabiand I'll take this PR over. Thanks! :)

**Comment by fabiand** [comment]
Thanks!

**Comment by ousleyp** [comment]
Closing this PR now that https://github.com/openshift/openshift-docs/pull/40294 is merged. Thanks, Fabian.

**Pull request closed without merging**
