### PR TITLE
Add a description about "ansible_service_broker_node_selector" for v3.11

### PR DESCRIPTION
**Pull request by bysnupy**
Fix a [[DOCS] Add to describe about ansible_service_broker_node_selector](https://bugzilla.redhat.com/show_bug.cgi?id=1638184).

This PR for v3.11.

### CODE REVIEW

**Comment by bysnupy** [comment]
This fix can do backport to v3.10 and v3.9. But in v3.9 the label is different with v3.11 and v3.10 ({"node-role.kubernetes.io/infra":"true"}). If you can, I wish to do backport at v3.9 with {"region": "infra"} label. (Additionally I think add notice about the variable can be enable as of `v3.9.40` in `v3.9`.).

**Comment by kalexand-rh** [comment]
@bysnupy, please open a separate PR against 3.9.

@jianlinliu, PTAL

**Comment by bysnupy** [comment]
@kalexand-rh Thank you for your kind guide, I've opened here: https://github.com/openshift/openshift-docs/pull/12464

**Comment by kalexand-rh** [comment]
Thank you @bysnupy! As soon as QE agrees, I'll merge in these PRs.

**Comment by kalexand-rh** [comment]
@jianlinliu, PTAL

**Comment by jianlinliu** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Comment by kalexand-rh** [comment]
Oh! It needs to go against master since this was opened against 3.11.

**Comment by kalexand-rh** [comment]
@bysnupy, when a change applies to multiple branches, please open the PR against master and say where else you know it's valid. Our process says to start from master and cherry-pick from it instead of the other way round, and I apologize for not seeing it earlier.

**Pull request merged**
