### PR TITLE
Cluster Admins can now create daemon sets

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape per our recent discussion. Can you please take a look at my first pass?

**Comment by adellape** [comment]
:rainbow: LGTM

**Comment by ahardin-rh** [comment]
@abhgupta PTAL. Thanks!

**Comment by abhgupta** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[/rev_history/]
|xref:../admin_guide/index.adoc#admin-guide-index[Overview]
|Added that an administrator of an OpenShift Dedicated cluster now has the privilege to create daemon sets.
%

**Comment by ahardin-rh** [comment]
Marked as Future Release, as the feature is merged, but still needs tested per @abhgupta

**Comment by adellape** [comment]
Cherry-picking to `dedicated` via https://github.com/openshift/openshift-docs/pull/5073.

**Comment by abhgupta** [comment]
retroactive lgtm since @adellape reached out to me earlier today

**Pull request merged**
