### PR TITLE
OSP 16 now available as GA

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@racedo @luis5tb I just saw the OSP 16 GA release email go out. Can you confirm this update?

**Comment by vikram-redhat** [comment]
We need @sferich888 and/or @reestr  AND @xltian to ack this change as well.

**Comment by sferich888** [comment]
Ack

**Comment by xltian** [comment]
ack from QE.

**Comment by codyhoag** [comment]
@racedo @luis5tb can you ack this update so we are certain all teams are OK with this update?

**Comment by racedo** [comment]
Ack

**Comment by mandre** [comment]
Ack

**Pull request merged**
