### PR TITLE
Remove the outdated compatibility section

### PR DESCRIPTION
**Pull request by rh-max**
@bmcelvee Could you take a look please? If it looks fine, we should also cherrypick it into master-3.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bmcelvee bump

**Comment by vikram-redhat** [comment]
@rh-max should this first go into master-3?

**Comment by rh-max** [comment]
@vikram-redhat Hmm, I didn't think it matters with cherry-picking, as long as the change does end up in both branches? But I'll default to master-3 for my new PRs (I also just tried to change base of this PR, and it's not worth the trouble).

**Comment by vikram-redhat** [comment]
@rh-max yes that is correct, you can CP to and from any branch :)

**Pull request merged**
