### PR TITLE
Updated link to kubeletconfig options

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/24726

New link per Seth J: https://coreos.slack.com/archives/GK6BJJ1J5/p1598472010048200

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio Do you know who might be able to QE this change?

**Comment by mburke5678** [comment]
@sunilcio Can you help with this one line change?

**Comment by sunilcio** [comment]
Hi @mburke5678 , I missed this one. LGTM

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
