### PR TITLE
TELCODOCS-1174: Update the TALM versions

### PR DESCRIPTION
**Pull request by tshwartz**
Summary of Changes:
- Copied the 4.12 table into main
- Updated the KALM versions

Version(s):
main

Issue:
(https://issues.redhat.com/browse/TELCODOCS-1174?filter=-1)

Link to docs preview:
https://55735--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by imiller0 — COMMENTED** [review]
/lgtm

**Review by snarayan-redhat — COMMENTED** [review]
lgtm

**Comment by sjhala-ccs** [comment]
@tshwartz Looks like there is a merge conflict in the `modules/ztp-telco-ran-software-versions.adoc` file. You will need to manually cherry pick using the CLI to both 4.12 and 4.13. Please let me know if you have any questions about the process.

**Comment by bergerhoffer** [comment]
@sjhala-ccs Thanks a lot for checking on this! I found the problem PR (#53229) which went into 4.12 but not main. So you can go ahead and move forward with the manual CPs for this PR for 4.12 and 4.13.  And then I'll have @aireilly update main with his changes so that no one else runs into conflicts again in the future. Thanks!

**Pull request merged**
