### PR TITLE
How to clear cache after pruning images 4.3

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1730148

Per Slack https://coreos.slack.com/archives/CEKNRGF25/p1573081039096000?thread_ts=1573079169.094900&cid=CEKNRGF25

### CODE REVIEW

**Comment by mburke5678** [comment]
@adambkaplan @wking PTAL

**Comment by mburke5678** [comment]
Depends on https://github.com/openshift/oc/pull/169

**Comment by mburke5678** [comment]
@tnozicka @adambkaplan 
I believe the PR to add `oc rolling restart` has merged. Can you confirm if this PR will now work?

@wzheng1 PTAL

**Comment by mburke5678** [comment]
@wzheng1 PTAL

**Comment by wzheng1** [comment]
LGTM

**Comment by mburke5678** [comment]
@wzheng1 Thank you very much for your quick review!

**Pull request merged**
