### PR TITLE
OSDOCS-3586: Wording Update for Support Period

### PR DESCRIPTION
**Pull request by jneczypor**
OSDOCS- 3586

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-3586

Link to docs preview:
OSD: https://56955--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-life-cycle.html
ROSA: https://56955--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
LGTM, thanks

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by michaelryanpeter** [comment]
The content here LGTM, but I think this needs to go through change management and get PX approval before a merge. Please reapply the `merge-review-needed` label when you are ready. 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by jneczypor** [comment]
Hi @davemulford! Can I please get a PX review on this for change management? Thanks!

**Comment by davemulford** [comment]
LGTM
/label px-approved

**Comment by jneczypor** [comment]
Hi @xueli181114 or @yuwang-RH! Can one of you please review this PR? Thanks so much!

**Pull request merged**
