### PR TITLE
OADP-2130: Restructure of Backup, OADP Installation, Features, Plugins, and Configuring Restructure

### PR DESCRIPTION
**Pull request by anarnold97**
[OADP-2130](https://issues.redhat.com/browse/OADP-2130)

Version(s):

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14
Enterprise 4.15 → branch/enterprise-4.15

## Issue:

https://issues.redhat.com/browse/OADP-2130

This PR is predominantly related to a restructure of existing OADP documentation

## Link to docs preview:

* [OADP Backing up](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications)
* [OADP Restoring](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications)
* [OADP Data Mover](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/data-mover-intro)
* [Advanced OADP features and functionalities](https://64811--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-advanced-topics)

QE review:
- [x ] QE has approved this change.

Please see this [PR] which is an earlier duplicate

Additional information:

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@anarnold97 don't forget to squash your commits pleez sir.

**Comment by anarnold97** [comment]
@GroceryBoyJr - Yes sir... will do sir! Can I have my dinner first, sir LOL

**Comment by GroceryBoyJr** [comment]
@anarnold97 Darn impressive work for first-pass sir! I have suggestions, but the scale of this work is most impressive.

**Comment by GroceryBoyJr** [comment]
@anarnold97 (I checked all the links too, and they work great. I almost always catch a broken one...great job!)

**Comment by anarnold97** [comment]
@GroceryBoyJr - thanks very much
Enjoy your weekend

**Comment by jab-rh** [comment]
@anarnold97, this needs manual cherry-picking to account for changes in the TOC in earlier releases of OCP. Thanks!

**Comment by sheriff-rh** [comment]
I have performed the manual cherrypicks to account for asciidoctor build errors and linked the PR to this one.

**Comment by kalexand-rh** [comment]
@anarnold97, @sheriff-rh, I don't see a CP to 4.11. Is this an intentional change, or do you need to open one?

**Comment by sheriff-rh** [comment]
@kalexand-rh yes - I must have missed 4.11 in my previous corrections. Please let me know if I can help!

**Comment by kalexand-rh** [comment]
@anarnold97, please open a CP PR against `enterprise-4.11` as well.

**Comment by anarnold97** [comment]
@kalexand-rh - please see [4.11 PR](https://github.com/openshift/openshift-docs/pull/66114)

**Pull request merged**
