### PR TITLE
BZ-1717554: Added a step to remove the etcd directory

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: http://file.rdu.redhat.com/~ahoffer/2019/BZ-1717554/admin_guide/assembly_replace-etcd-member.html#remove-failed-etcd-node_replace-etcd-member

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@hexfusion Could you take a look at this update to the 3.11 docs for this BZ [1] to make sure it looks okay? Thanks!

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1717554

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
Merging as BZ was verified.

**Pull request merged**
