### PR TITLE
TELCODOCS-961 release note: Configuring PGT CRs with compliance duration settings

### PR DESCRIPTION
**Pull request by aireilly**
[TELCODOCS-961](https://issues.redhat.com//browse/TELCODOCS-961) release note for configuring PGT CRs with compliance duration settings feature.

Version(s):
enterprise-4.11

Issue:
https://issues.redhat.com/browse/TELCODOCS-961

Link to docs preview:
https://54147--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-pgt-compliance-duration-settings

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by aireilly** [comment]
Closing this as it is not required. the feature will be release noted in 4.12.

**Pull request closed without merging**
