### PR TITLE
Good practice to access CR using api-group FQDN

### LINKED ISSUE #24129: [enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets

### What needs fixing?

it seems that the object to get/edit is not:

oc get config/cluster -o yaml
oc edit config/cluster

But instead

oc get configs.imageregistry.operator.openshift.io cluster -o yaml
oc edit configs.imageregistry.operator.openshift.io cluster

### LINKED ISSUE #24574: [enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc
### Which section(s) is the issue in?

#infrastructure-moving-registry_creating-infrastructure-machinesets

### What needs fixing?

registry config object is config.imageregistry/cluster and not just config/cluster

### PR DESCRIPTION
**Pull request by a7vicky**
for [24129](https://github.com/openshift/openshift-docs/issues/24129)

### CODE REVIEW

**Comment by garbagego** [comment]
@ahardin-rh

**Comment by mmckinst** [comment]
I'm also running in to this issue, patching `cluster/config` doesn't work at all.

Also, FWIW it would be a lot easier to just do `oc patch config.imageregistry.operator.openshift.io/cluster --type=merge -p '{"spec": {"nodeSelector": {"node-role.kubernetes.io/infra": ""}}}'` see https://github.com/openshift/openshift-docs/pull/22620

**Comment by vikram-redhat** [comment]
@ahardin-rh can you confirm with QE on this?

**Comment by sheriff-rh** [comment]
@vikram-redhat  @ahardin-rh  this is associated with a bug assigned to me :) 
@jiajliu PTAL regarding [bug 1859007](https://bugzilla.redhat.com/show_bug.cgi?id=1859007). Thanks!

**Comment by jiajliu** [comment]
@sunzhaohua2 ^^

**Comment by ctauchen** [comment]
Closes BZ 1860063: https://bugzilla.redhat.com/show_bug.cgi?id=1860063

**Pull request merged**
