### PR TITLE
CNV#33978-1: ROSA support and general storage update

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.14+

Issue: [CNV-33978](https://issues.redhat.com//browse/CNV-33978)

Link to docs preview: https://67365--docspreview.netlify.app/openshift-enterprise/latest/virt/install/preparing-cluster-for-virt#virt-aws-bm_preparing-cluster-for-virt

QE review:
- [x] QE has approved this change.
- [x] seeking additional approval from @orenc1  before merge

Additional information: 
- Removing information about specific storage vendors per @ronensdeor - FYI @aglitke @dankenigsberg @kmajcher-rh 
- Planning to open a second PR to add a release note (for CNV) re: ROSA support (Update: opened https://github.com/openshift/openshift-docs/pull/67398)
- Also planning to follow up with the ROSA team to add a release note there

### CODE REVIEW

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by orenc1** [comment]
lgtm in general, but I would like to comment about:
> * You can install the cluster by using installer-provisioned infrastructure, ensuring that you specify bare-metal node instance types in the `install-config.yaml` file. For example, you can use the `c5n.metal` type value for a machine based on x86_64 architecture.

I think we can mention that at least the **worker** nodes should be bare metal instances (e.g. `c5n.metal`), since they are running the VirtualMachines. At least two of them in order to support live migration.
There is no hard requirements for the master/control-plane nodes to be also bare metals.
This distinction has a considerable influence on the running costs of the AWS/ROSA cluster. Metal instance is 10x more expensive than a virtual EC2 that can serve as a master node.

**Comment by ousleyp** [comment]
> lgtm in general, but I would like to comment about:
> 
> > * You can install the cluster by using installer-provisioned infrastructure, ensuring that you specify bare-metal node instance types in the `install-config.yaml` file. For example, you can use the `c5n.metal` type value for a machine based on x86_64 architecture.
> 
> I think we can mention that at least the **worker** nodes should be bare metal instances (e.g. `c5n.metal`), since they are running the VirtualMachines. At least two of them in order to support live migration. There is no hard requirements for the master/control-plane nodes to be also bare metals. This distinction has a considerable influence on the running costs of the AWS/ROSA cluster. Metal instance is 10x more expensive than a virtual EC2 that can serve as a master node.

Changed to:

```
* You can install the cluster by using installer-provisioned infrastructure, ensuring that you specify bare-metal instance types for the worker nodes by editing the `install-config.yaml` file. For example, you can use the `c5n.metal` type value for a machine based on x86_64 architecture.
```

**Pull request merged**
