### PR TITLE
Modify the heading

### PR DESCRIPTION
**Pull request by xenolinux**
This PR changes the heading for common terms added in each book.

Version(s): 4.8+

Issue: None

Link to docs preview:

https://53160--docspreview.netlify.app/openshift-enterprise/latest/getting_started/openshift-overview.html#getting-started-openshift-common-terms_openshift-overview

https://53160--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging.html#openshift-logging-common-terms_cluster-logging

https://53160--docspreview.netlify.app/openshift-enterprise/latest/registry/index.html#openshift-registry-common-terms_registry-overview

https://53160--docspreview.netlify.app/openshift-enterprise/latest/storage/index.html#openshift-storage-common-terms_storage-overview

https://53160--docspreview.netlify.app/openshift-enterprise/latest/monitoring/monitoring-overview.html#openshift-monitoring-common-terms_monitoring-overview

https://53160--docspreview.netlify.app/openshift-enterprise/latest/nodes/index.html#commonterms-node

https://53160--docspreview.netlify.app/openshift-enterprise/latest/networking/understanding-networking.html#nw-networking-glossary-terms_understanding-networking

https://53160--docspreview.netlify.app/openshift-enterprise/latest/installing/index.html#install-openshift-common-terms_ocp-installation-overview

https://53160--docspreview.netlify.app/openshift-enterprise/latest/architecture/index.html#openshift-architecture-common-terms_architecture-overview

QE review:  Not required
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Amrita42** [comment]
lgtm

**Comment by snarayan-redhat** [comment]
@xenolinux - Need to create manual CPs for 4.8, 4.9 and 4.10

**Pull request merged**
