### PR TITLE
[SRVKS-1061] Update readiness/liveness default availability

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.32+

Issue:
https://issues.redhat.com/browse/SRVKS-1061

Link to docs preview:
https://84727--ocpdocs-pr.netlify.app/openshift-serverless/latest/eventing/tuning/overriding-config-eventing.html 
(first NOTE)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
