### PR TITLE
CNV#41545: Add link to Supported Limits KCS to the about virt page

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.12+

Issue: [CNV-41545](https://issues.redhat.com/browse/CNV-41545)

Link to docs preview: [Additional resources>Supported limits for OpenShift Virtualization 4.x](https://77782--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/about_virt/about-virt.html#additional-resources_about-virt)

(Review openshift-enterprise preview only)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
Bonjour @djfjeff, can you please review this doc update? The new link will appear in each version of our CNV docs from 4.12+. And do you know who the appropriate QE reviewer is? Thanks!

**Comment by djfjeff** [comment]
LGTM

**Comment by aspauldi** [comment]
Hi @dshchedr, Debarati suggested that you might be able to do the QE review for this doc update. Jean-Francois has already approved. Thanks!

**Review by Srivaralakshmi — COMMENTED** [review]
@aspauldi Good work! LGTM

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
