### PR TITLE
TELCODOCS-1249: URGENT: Updating OSC variables

### PR DESCRIPTION
**Pull request by MirzWeiss**
Updating OSC variable in common attributes file. This will update the must-gather image in [this table](https://docs.openshift.com/container-platform/latest/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data).

Version(s):
Only 4.13

Issue: https://issues.redhat.com/browse/TELCODOCS-1249

Link to docs preview: Change is to common attributes file.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
Changes lgtm. I do not see the QE review on here though.

**Comment by tbuskey** [comment]
/lgtm
QE approves

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
