### PR TITLE
Add release note for expanded SDN migration platforms

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/SDN-1172

### CODE REVIEW

**Comment by jboxman** [comment]
@pliurh, can you confirm this release note?

Thanks!

**Comment by pliurh** [comment]
LGTM

**Review by codyhoag — APPROVED** [review]
Other than the needed rebase, LGTM! :slightly_smiling_face:

**Comment by jboxman** [comment]
@codyhoag thanks!

**Pull request merged**
