### PR TITLE
OSDOCS-3591: Migrating API version that is being removed

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-3591

Link to docs preview:
No preview other than GitHub, since the file isn't in use

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
/label peer-review-needed

No preview other than GitHub, since the file isn't in use

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Review by sanchezl — APPROVED** [review]

**Pull request merged**
