### PR TITLE
Help validate customer portal title

### PR DESCRIPTION
**Pull request by mburke5678**
Per vikram email Help validate customer portal title 3/4/19

### CODE REVIEW

**Comment by mburke5678** [comment]
@bergerhoffer PTAL

**Comment by bergerhoffer** [comment]
As long as we're allowed to use double brackets for anchors (and don't always have to use the [id=''] approach, then this looks good to me.

**Comment by mburke5678** [comment]
@bergerhoffer @vikram-redhat The double-brackets are in the 4.0 doc guidelines. If the preferred method is to use the `id=` string, please let me know and I will make the change. 
https://github.com/openshift/openshift-docs/blob/enterprise-4.0/contributing_to_docs/doc_guidelines.adoc#unique-ids

**Comment by vikram-redhat** [comment]
@bergerhoffer and @mburke5678 the guideline is to use 'id=' format for anchor ids for module headings, not for all anchor ids (within modules). At least that is how I read it from the modular docs guidelines here: https://redhat-documentation.github.io/modular-docs/.

I have made this a little bit more explicit as part of this update to the guidelines: https://github.com/openshift/openshift-docs/pull/13976. Can you PTAL?

**Comment by bergerhoffer** [comment]
Thanks for clarifying @vikram-redhat. The guidance update looked good, just added a few other comments to the PR.

**Pull request merged**
