### PR TITLE
TELCODOCS-1433 updating description based on slack chat

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-1433]: 

Version(s): 4.14 and main

Issue: https://issues.redhat.com/browse/TELCODOCS-1433

Link to docs preview: 

*  https://64816--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-numa-aware-scheduling.html#cnf-about-collecting-nro-data_numa-aware

QE review:
- [x] QE has approved this change.

Additional information: All appproved in https://github.com/openshift/openshift-docs/pull/63481 however follow up via slack asked to update part of a line for clarity. This is the PR for that update.

### CODE REVIEW

**Comment by shajmakh** [comment]
Thanks for the PR.
/lgtm

**Comment by JoeAldinger** [comment]
Hi @kquinn1204 this needs to go through `peer-review` before it can be placed into the `merge-review` queue. I've updated the labels accordingly and left you feedback. Once the feedback is addressed, please relabel it for `merge-review`. Feel free to ping me and I'll have another look, thanks.

**Comment by kquinn1204** [comment]
@JoeAldinger I thought going straight to merge would be OK as all addressed in https://github.com/openshift/openshift-docs/pull/63481. I hope this is OK to merge now. Thanks.

**Pull request merged**
