### PR TITLE
OADP - 3354 fixed remove-Tech Preview-1-3 

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP 1.3.1

OCP 4.13+

GA April 16, 2024

Resolves - https://issues.redhat.com/browse/OADP-3354

Deploy preview - https://73312--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/about-oadp-1-3-data-mover

### CODE REVIEW

**Comment by CarmiWisemon** [comment]
/label OADP 
/label peer-review-needed

This PR was already approved once. Later on in the Jira the text was changed by QE & DEV. The text in this PR reflects that change.

**Comment by DCChadwick** [comment]
/remove-label peer-review-in-progress

/label peer-review-done

LGTM

**Pull request merged**
