### PR TITLE
YAML formatting fix

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12+

Issue:
None

Link to docs preview:
[Configuring Operator resource constraints](https://83245--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/compliance_operator/co-scans/compliance-operator-troubleshooting.html#operator-resource-constraints_compliance-troubleshooting)

Additional information:
Fixes a YAML formatting error.

### CODE REVIEW

**Review by rhmdnd — APPROVED** [review]
/lgtm

Thanks!

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
