### PR TITLE
OSDOCS-3562: SRE and service account access for ROSA and OSD

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-3562

Link to docs preview:
ROSA: https://64510--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-sre-access
OSD: https://64510--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-sre-access 

QE review:
No QE review required. 

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
Note for Friday morning: add Identity and access management module to the OSD SRE and service account access assembly

**Comment by bmcelvee** [comment]
@davemulford would you mind giving this PR an ack for change management, please? We're moving the _Identity and access management_ section from ROSA's _Overview of responsibilities for Red Hat OpenShift Service on AWS_ page and OSD's _Understanding process and security for OpenShift Dedicated_ page to the _SRE and service account access_ page. Thank you!

**Comment by davemulford** [comment]
LGTM!
/label px-approved

**Comment by iamkirkbater** [comment]
LGTM

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by bmcelvee** [comment]
All acks received. Merging now!

**Pull request merged**
