### PR TITLE
OSDOCS-OSDOCS-10656:Updating Network Observability arch Loki-less option

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-10656
Link to docs preview:

https://80379--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/understanding-network-observability-operator.html#network-observability-architecture_nw-network-observability-operator
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@jotak Can you PTAL at these graphics updates? I wonder if the line to Loki should be dotted, or if we leave it as bold and just mention that its optional in the context. Since Loki is still the only storage solution that we fully support, even though it is optional.

**Review by jotak — APPROVED** [review]
thanks @skrthomas , lgtm
I agree with the loki lines, they could be dotted, if it's a quick/easy change it would be better .. else I'm fine with the current graphics and we can change that later

**Comment by skrthomas** [comment]
This dropped off my radar totally as I was prepping 1.7 stuff, but the loki dotted line graphics have been added.

**Comment by skrthomas** [comment]
Hey @memodi this one has been in progress for a while, basically its an update to the architecture graphics post 1.6 Lokiless improvements. Can you PTAL for QE approvals?

**Review by memodi — APPROVED** [review]
/label qe-approved

**Comment by memodi** [comment]
thanks @skrthomas

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
