### PR TITLE
Bumped Node.js version numbers

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1487015

Follow-up to https://github.com/openshift/openshift-docs/pull/5228

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
From what I see in NodeJS imagestream, the image for 0.10 is still there. However, it is marked as deprecated and it is hidden from view. That's why users can't see it. So we do need to address it in the doc. I would prefer to still have 0.10 and notice that it is deprecated and no longer available to use.

**Comment by ahardin-rh** [comment]
@dinhxuanvu Thanks! I updated the language to reflect that.

**Review by dinhxuanvu — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
