### PR TITLE
[enterprise-4.13] Replacing defaultVolumesToRestic with defaultVolumesToFsBackup

### PR DESCRIPTION
**Pull request by RichardHoch**
Enterprise 4-13: Cherry-pick of https://github.com/openshift/openshift-docs/pull/66083

xref: f66edc5db8675a22e03c2701d7a573b356ebf17b

### CODE REVIEW

**Comment by stevsmit** [comment]
@RichardHoch I removed the merge-review-needed label because it still has the do-not-merge label. Would you mind resubmitting and removing that label?

**Comment by RichardHoch** [comment]
@stevsmit how do i remove it?

**Pull request merged**
