### PR TITLE
ISSUE-43384: Removing ConfigMap handling from restricted network cluster doc

### LINKED ISSUE #43384: [enterprise-4.9] Issue in file updating/updating-restricted-network-cluster.adoc
### Which section(s) is the issue in?
Creating the image signature config map

### What needs fixing?
The docs say:
`If you are upgrading from version 4.4.8 or later, you can use the oc CLI to create the config map.`

But not actually tell you how to do it with the `oc`-CLI.

### PR DESCRIPTION
**Pull request by sagidlow**
GH Issue Link: https://github.com/openshift/openshift-docs/issues/43384
Applies to 4.8+
QE/SME ack required.
Preview Link: https://deploy-preview-43897--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-restricted-network-cluster

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
