### PR TITLE
Fix typos and copy and paste errors

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/13585

@mrogers950, @stuartchuan, @barleyer, will you PTAL and confirm which 3.x versions this change should apply to?

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@mrogers950 can you please take a look?

@stuartchuan can you confirm which versions it should apply to?

**Comment by barleyer** [comment]
@lihongan could you take a look?

**Comment by lihongan** [comment]
LGTM, thank you. 
I think the change should be applied to all 3.x versions, but seems the chapter has less content in old version so not all changes can be applied to 3.6 and before.

**Comment by kalexand-rh** [comment]
Thank you, @lihongan! I'll make sure that the change is applied back to 3.6 and try to put it on earlier branches.

**Comment by kalexand-rh** [comment]
I checked, and this change isn't valid before 3.6.

**Pull request merged**
