### PR TITLE
Issue 4431 Added supported integrations Q to planning

### PR DESCRIPTION
**Pull request by bfallonf**
As per #4431 

@adellape @ahardin-rh @bmcelvee @mburke5678 @gaurav-nelson Peer review plz?

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM :star2:

**Comment by mburke5678** [comment]
LGTM

**Comment by etsauer** [comment]
LGTM

**Comment by bfallonf** [comment]
Thanks all! I'll merge.

**Comment by adellape** [comment]
@bfallonf Wondering if this whole line should be ifdef'd for just OCP?

**Comment by bfallonf** [comment]
@adellape I guess it depends on if there's a difference between what would work on OCP and what would work on Origin? Or are you asking if this should be in the Origin docs, considering it's upstream?

**Comment by adellape** [comment]
@bfallonf Mainly just that the KBase talks about OCP and its version numbers (3.x) and doesn't mention Origin by name or its versions. Also that the KBase talks about tested/supported things (suggesting GSS), when they don't support Origin.

**Comment by bfallonf** [comment]
@adellape Hmm true. OK, I'll do a followup PR.

**Pull request merged**
