### PR TITLE
ROX-20438: update path for deploy-central-db.sh

### PR DESCRIPTION
**Pull request by RTann**
Version(s):

4.0+

Issue:

https://issues.redhat.com/browse/ROX-20438

Link to docs preview:

QE review:
- [ ] QE has approved this change. (**N/A**: approved by SME)

Additional information:

### CODE REVIEW

**Comment by RTann** [comment]
See https://github.com/stackrox/stackrox/blob/4.2.2/pkg/renderer/render_new.go#L29 and https://github.com/stackrox/stackrox/blob/4.2.2/pkg/renderer/readme.go#L56

**Comment by kcarmichael08** [comment]
LGTM!

**Pull request merged**
