### PR TITLE
GH#36703 Diagram refers to RHCOS instead of FCOS

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/36703 https://github.com/openshift/openshift-docs/issues/34109

Add version of **Figure 2. Creating the bootstrap, control plane, and compute machines** with FCOS not RHCOS for OKD.

Previews:
[Installation Process Figure 2](http://file.rdu.redhat.com/~mburke/GH36703/installing/#installation-process_ocp-installation-overview) 
[Installing quickly on oVirt](http://file.rdu.redhat.com/~mburke/GH36703/installing/installing_rhv/installing-rhv-default.html)
[Installing a cluster on oVirt with customizations](http://file.rdu.redhat.com/~mburke/GH36703/installing/installing_rhv/installing-rhv-customizations.html)[
Installing a cluster on oVirt with user-provisioned infrastructure](http://file.rdu.redhat.com/~mburke/GH36703/installing/installing_rhv/installing-rhv-user-infra.html)

### CODE REVIEW

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Review by vrutkovs — APPROVED** [review]

**Review by kalexand-rh — COMMENTED** [review]
I see FCOS or OKD in each of these files. LGTM

**Pull request merged**
