### PR TITLE
RHDEVDOCS-4821 - fixed {featureName}

### PR DESCRIPTION
**Pull request by DebarghoGhosh**
Aligned team: Dev Tools
OCP version for cherry-picking: enterprise- 4.11-4.12

JIRA issue:
https://issues.redhat.com/browse/RHDEVDOCS-4821

Preview pages: https://54096--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/gitops-release-notes.html

SME+QE review: @varshab1210 
Peer-review: @sounix000

### CODE REVIEW

**Comment by varshab1210** [comment]
lgtm

**Review by sounix000 — APPROVED** [review]
/lgtm

**Pull request merged**
