### PR TITLE
Bug 1537882, added information about enabling block volume feature gates

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1537882

@screeley44 PTAL. Thanks!

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@qinpingli Thank you. Are you saying that this change should only be applied to 3.9 docs and not 3.10, or is it that only the part stating "For more information, see Configuring for Local Volume should be removed in the 3.10 doc set? Thanks!

**Comment by qinpingli** [comment]
@ahardin-rh 

For "BlockVolume" feature gate, it should be enabled both in 3.9 and 3.10.  
In `For more information` session, how to enable feature gates in the xref `../../install_config/configuring_local.adoc#install-config-configuring-local[Configuring for Local Volume]` will be removed from 3.10.

**Comment by ahardin-rh** [comment]
@qinpingli Thank you! I created https://github.com/openshift/openshift-docs/pull/9002 to add the link to 3.9 only.

**Pull request merged**
