### PR TITLE
Log forwarding assembly called wrong module

### PR DESCRIPTION
**Pull request by mburke5678**
While checking if a recent PR was live, I noticed that the Forward logs to third party systems topic was calling an incorrect module and the correct module was not being called. This PR fixes that and removes the incorrect module

### CODE REVIEW

**Comment by mburke5678** [comment]
CP to 4.3 and 4.4 only. Changes to 4.5 made in https://github.com/openshift/openshift-docs/pull/20269/files#diff-a75af9361f4180b78389366568d5d682R31

**Comment by lamek** [comment]
LGTM

**Pull request merged**
