### PR TITLE
Svc and pkg rename

### PR DESCRIPTION
**Pull request by sdodson**
Handle service and package renames
- openshift-{master,node} -> origin-{master,node} and atomic-openshift-{master,node} for origin and enterprise respectively
- /etc/openshift -> /etc/origin
- /var/lib/openshift -> /var/lib/origin
- /etc/sysconfig/openshift-{master,node} -> /etc/sysconfig/origin-{master,node} and /etc/sysconfig/atomic-openshift-{master,node}  for origin and enterprise respectively

### CODE REVIEW

**Comment by adellape** [comment]
@sdodson Bout to merge https://github.com/openshift/openshift-docs/pull/1170 which has some of these changes for the install topics, FYI.

**Comment by sdodson** [comment]
Ok, will review after that's merged and see what if anything needs to be done.

**Comment by adellape** [comment]
https://github.com/openshift/openshift-docs/pull/1170 merged.

**Comment by sdodson** [comment]
Ok, rebased

**Comment by adellape** [comment]
:bow:

**Pull request merged**
