### PR TITLE
BZ 1440961 Wrong image tag/version used when grabbing router configuration template

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1440961

### CODE REVIEW

**Comment by mburke5678** [comment]
@adellape Am I using the product-version correctly here?
Replace `$version` with `{product-version}` for the latest version.

**Comment by mburke5678** [comment]
@rjhowe Added "Replace `$version` with `{product-version}` for the latest version." This should replace `{product-version}` with `3.4`, `3.5`, or `3.6`, as appropriate.

**Comment by mburke5678** [comment]
@rjhowe Bump!

**Comment by mburke5678** [comment]
@openshift/team-documentation Am I using the product-version correctly here?
_Replace $version with {product-version} for the latest version._

**Comment by bfallonf** [comment]
@mburke5678 is the reader doing the replacing here? I think that when this is published, this will replace the specific version of the branch the reader is reading and not get what they have to do. Should it be replaced with <product_version>?

Let me know if I'm not making sense.

**Comment by mburke5678** [comment]
@bfallonf {product-version} does not replace with the OpenShift version? `v3.4`, `v3.5`, `v3.6`? 
The user needs to enter that with the command:
`ose-haproxy-router:v3.6 haproxy-config.template`

**Comment by bfallonf** [comment]
@mburke5678 Then yes, this should work as you want it to. LGTM.

**Comment by mburke5678** [comment]
@zhaozhanqi PTAL

**Comment by vikram-redhat** [comment]
@xltian  - request you to take a look. 

Thanks!

**Comment by zhaozhanqi** [comment]
@mburke5678 
LGTM , sorry to miss this since in vacation

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Minor change. Added `{product-version}` to a code block.

Should I expect to see the version in the asciibinder build preview? I am seeing `Branch Build` in place of the `{product-version}`.
`Replace $version with Branch Build for the latest version.`

**Comment by adellape** [comment]
@mburke5678 `{product-version}` would get replaced with `3.4`, `3.5`, `3.6`, etc, depending on the branch. There would not be a `v` before it. It's taken from the `_distro_map.yml` file, then `name:` field for each branch. `3.6`, for example, might be a valid tag for latest OCP 3.6, but I can't search the Container Catalog right now to verify.

**Comment by mburke5678** [comment]
@adellape  All the following seem to work:
docker run --rm --interactive=true --tty --entrypoint=cat     registry.access.redhat.com/openshift3/ose-haproxy-router:v3.6 haproxy-config.template
docker run --rm --interactive=true --tty --entrypoint=cat     registry.access.redhat.com/openshift3/ose-haproxy-router:v3.5 haproxy-config.template
docker run --rm --interactive=true --tty --entrypoint=cat     registry.access.redhat.com/openshift3/ose-haproxy-router:v3.4 haproxy-config.template

**Comment by mburke5678** [comment]
No rev history needed.

**Comment by mburke5678** [comment]
Merged via https://github.com/openshift/openshift-docs/pull/6021

**Pull request merged**
