### PR TITLE
OCPBUGS 13378: Updating non-preempting priority classes to GA

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11 only

Issue:
https://issues.redhat.com/browse/OCPBUGS-13378

Link to docs preview:
http://file.rdu.redhat.com/~ahoffer/2023/OCPBUGS-13378-411/release_notes/ocp-4-11-release-notes.html#ocp-4-11-technology-preview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @gauravsingh85 @xltian @kalexand-rh @sferich888 Please review for change management approval

One more PR now if you can please approve if you're okay with it, since it actually needs to be GA as of 4.11

**Review by JoeAldinger — COMMENTED** [review]
/lgtm
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by kalexand-rh** [comment]
LGTM

**Pull request merged**
