### PR TITLE
OSDOCS-9742: add view a NP to MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
[OSDOCS-9742](https://issues.redhat.com/browse/OSDOCS-9742)

Link to docs preview:
[Viewing a network policy](https://72311--ocpdocs-pr.netlify.app/microshift/latest/microshift_networking/microshift-network-policy/microshift-viewing-network-policy)

QE review:
- [ ] QE has approved this change.

Additional information:
Content port from OCP with conditionals

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
