### PR TITLE
OSDOCS-9783 Retry for Docs supporting NE-1441

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): only 4.16

Issue: https://issues.redhat.com/browse/OSDOCS-9783

Link to docs preview: https://74467--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-networking 

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
IBM style guide doesn't allow future tense, FYI

**Review by obrown1205 — COMMENTED** [review]
@jmanthei can you add a specific doc preview link for the changes?

**Comment by obrown1205** [comment]
Looks good for now - will add the LGTM tag once I preview the rendering :)

**Comment by jmanthei** [comment]
@obrown1205 check it out :)

**Comment by obrown1205** [comment]
LGTM!

/label peer-review-done
/remove-label peer-review-in-progress

**Pull request merged**
