### PR TITLE
Registry catalog API call

### PR DESCRIPTION
**Pull request by miminar**
Task: https://trello.com/c/AZINw5qI/1313-5-registry-implement-catalog-api-call

Blocked on PRs: 
- https://github.com/openshift/image-registry/pull/87
- https://github.com/openshift/origin/pull/19879

### CODE REVIEW

**Comment by miminar** [comment]
@bmcelvee PTAL. No rush, waits for the blocked PRs.

**Comment by miminar** [comment]
No longer blocked.

**Comment by bparees** [comment]
lgtm

**Comment by bmcelvee** [comment]
LGTM :fireworks: 

@dongboyan77 PTAL

**Comment by dongboyan77** [comment]
LGTM, thanks

**Comment by vikram-redhat** [comment]
@bmcelvee - can this be merged? Or does it require peer review yet? Also - I don't think it should have the online label, but not sure.

**Pull request merged**
