### PR TITLE
BZ1989538: Remove trust bundle steps from ShiftStack clouds.yaml definition procedure

### PR DESCRIPTION
**Pull request by maxwelldb**
Context: https://bugzilla.redhat.com/show_bug.cgi?id=1989538

Preview: https://deploy-preview-35150--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-describing-cloud-parameters_installing-openstack-installer-custom

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
LGTM, thanks @maxwelldb for the quick fix.

**Comment by maxwelldb** [comment]
@itzikb-redhat Is this something that you could QE? Just asking as I recall seeing you on a relevant Slack thread. :)

**Comment by itzikb-redhat** [comment]
LGTM

**Comment by maxwelldb** [comment]
@itzikb-redhat Thanks! Can you confirm that this is appropriate for 4.7, too?

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Pull request merged**
