### PR TITLE
bug 1589129 updating etcdclt commands

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1589129

@geliu2016, PTAL. (I'm assuming that this change is valid in all versions. Please correct me if that's not right.)

### CODE REVIEW

**Comment by geliu2016** [comment]
LGTM, thx

**Comment by kalexand-rh** [comment]
Thank you!

@openshift/team-documentation PTAL

**Comment by bmcelvee** [comment]
LGTM :rabbit2:

**Comment by kalexand-rh** [comment]
Thanks! Merging. :smile_cat:

**Pull request merged**
