### PR TITLE
[OSDOCS-10626]: Update ROSA/OSD lifecycle pages for 4.12

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10626
https://issues.redhat.com/browse/OSDOCS-10628
Link to docs preview:

https://76319--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-life-cycle.html#sd-life-cycle-dates_osd-life-cycle
https://76319--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.html#sd-life-cycle-dates_rosa-life-cycle
**NOTE: HCP Docs Not Affected**
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
LGTM

**Comment by abhgupta** [comment]
LGTM

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
