### PR TITLE
Include SR-IOV device discovery in only one assembly

### PR DESCRIPTION
**Pull request by jboxman**
This module is included in two places. This one makes the least sense.

- https://docs.openshift.com/container-platform/4.4/networking/hardware_networks/about-sriov.html#discover-sr-iov-devices_about-sriov (deleted)
- https://docs.openshift.com/container-platform/4.4/networking/hardware_networks/configuring-sriov-device.html#discover-sr-iov-devices_configuring-sriov-device

cc @zshi-redhat

### CODE REVIEW

**Comment by jboxman** [comment]
@vikram-redhat, this module was included in 2 places. Does this need a change control email?

**Comment by vikram-redhat** [comment]
> @vikram-redhat, this module was included in 2 places. Does this need a change control email?

No.

**Pull request merged**
