### PR TITLE
How to clear cache after pruning images 2

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1730148#c7

### CODE REVIEW

**Comment by mburke5678** [comment]
@adambkaplan 
Masaki Hatada suggested in the BZ [1] that the `oc patch deployment` command you suggested we add to the docs via https://github.com/openshift/openshift-docs/pull/17959#issuecomment-551816368 _is not good since it can work just once_ and suggested the command I added in this PR. 
Can you verify Masaki's concerns and solution?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1730148#c7

**Comment by mburke5678** [comment]
@adambkaplan 
Masaki Hatada suggested in the BZ [1] that the `oc patch deployment` command you suggested we add to the docs via https://github.com/openshift/openshift-docs/pull/17959#issuecomment-551816368 _is not good since it can work just once_ and suggested the command I added in this PR. 
Can you verify Masaki's concerns and solution?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1730148#c7

**Comment by mburke5678** [comment]
@wzheng1 Please take a look. I updated the command to clear the cache after pruning based on ] https://bugzilla.redhat.com/show_bug.cgi?id=1730148#c7

**Comment by wzheng1** [comment]
I have verified, yes to https://bugzilla.redhat.com/show_bug.cgi?id=1730148#c7.

**Comment by mburke5678** [comment]
@wzheng1 Thank you for your review. Sorry that the BZ got confusing with multiple PRs.

**Pull request merged**
