### PR TITLE
OCPBUGS-15814 Updated step 5 in the Running the Installation section

### PR DESCRIPTION
**Pull request by wgabor0427**
Version(s):
4.14+

Issue::
https://issues.redhat.com/browse/OCPBUGS-15814

Link to docs preview:
https://80835--ocpdocs-pr.netlify.app/

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jianping-shu** [comment]
I didn't see the update take effect in the following preview. Maybe it is because the chapters reworked in 4.14+. Pls. have a check
AWS
https://80835--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/ipi/installing-aws-customizations#installing-aws-with-short-term-creds_installing-aws-customizations
GCP
https://80835--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installing-gcp-with-short-term-creds_installing-gcp-customizations
In addition, 4.14+ support Azure Microsoft Entra Id which has the same issue as below:
https://80835--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/ipi/installing-azure-customizations#installing-azure-with-short-term-creds_installing-azure-customizations

**Comment by dfitzmau** [comment]
Hi @wgabor0427 . Jianping is correct. The file is added as an include in the following assemblies:

- cco-mode-gcp-workload-identity.adoc
- cco-mode-sts.adoc

But, it the include is not found:

Screenshot from 2024-08-29 14-51-51

Meaning: That these files are no longer in use:

Screenshot from 2024-08-29 14-54-35

**Comment by dfitzmau** [comment]
This PR can be closed as it looks like to me the 4.14+ doc doe snot exist.

Screenshot from 2024-08-29 14-57-13

**Comment by wgabor0427** [comment]
This work is no longer relevant for 4.14+

**Comment by jianping-shu** [comment]
In my understanding, it doesn't mean that this work won't be applicable for 4.14+, instead you may need to modify a different source file to update the links I pasted above.

**Comment by wgabor0427** [comment]
/label merge-review-needed

Updated step #4 in the "Incorporating the Cloud Credential Operator utility manifests" section to match what was in PRs https://github.com/openshift/openshift-docs/pull/80833 and https://github.com/openshift/openshift-docs/pull/80830. Modified the cco-ccoctl-install-creating-manifests.adoc file.

**Comment by bscott-rh** [comment]
@jianping-shu Bill has updated the PR and it looks like the changes are showing up in the installation assemblies correctly. Can you please verify? Thank you

**Review by bscott-rh — APPROVED** [review]
Updated changes LGTM from peer review perspective.

**Comment by jianping-shu** [comment]
LGTM

**Review by adellape — APPROVED** [review]

**Pull request merged**
