### PR TITLE
HCIDOCS-376: Fix indents in networkConfig stanza, install-config.yml (IPI)

### PR DESCRIPTION
**Pull request by johnwilkins**
Fixed indents.

Fixes: [HCIDOCS-376](https://issues.redhat.com//browse/HCIDOCS-376)

See https://issues.redhat.com/browse/HCIDOCS-376 for additional details.

Preview URL:https://80609--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-configuring-host-network-interfaces-for-subnets_ipi-install-installation-workflow

For release(s): 4.12-4.17
QE Review: 

- [x] QE has approved this change. 

Signed-off-by:  <jowilkin@redhat.com>

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @johnwilkins . The http://jowilkin.com:8080/HCIDOCS-376/welcome/index.html link does not work for me; maybe this is a link held on a private server (based on port 8080)?

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Comment by ShaunaDiaz** [comment]
@johnwilkins You can do manual CPs for each off the main branch; or if it is the same conflict(s) in all the branches 4.12-4.15, you can make a PR based on 4.15 and we can pick it back.

**Pull request merged**
