### PR TITLE
OCP documentation - RHV restricted network support - fix tables upi ipi

### PR DESCRIPTION
**Pull request by emarcusRH**
Version(s):
enterprise-4.11
enterprise-4.10
enterprise-4.12 

Issue:

 - options matrix for OCP on RHV in restricted networks is not rendering correctly in v 4.11 docs
 - matrix not correct regarding IPI and UPI support for RHV

Link to docs preview:

http://file.tlv.redhat.com/emarcus/upi_ipi/installing/installing-preparing.html#supported-installation-methods-for-different-platforms

Additional information:

### CODE REVIEW

**Comment by emarcusRH** [comment]
@engelmi , @janosdebugs
I need someone to double check that the support for UPI on restricted networks exists in both 4.10 and 4.11. 
In the installation instructions in the guide, it implies that both are supported - callout description #4 in this sample YAML file indicates that IPI is supported - https://docs.openshift.com/container-platform/4.11/installing/installing_rhv/installing-rhv-restricted-network.html#installation-bare-metal-config-yaml_installing-rhv-restricted-network

**Comment by engelmi** [comment]
Based on the documentation for [4.10](https://docs.openshift.com/container-platform/4.10/installing/installing_rhv/installing-rhv-restricted-network.html#installation-bare-metal-config-yaml_installing-rhv-restricted-network) and [4.11](https://docs.openshift.com/container-platform/4.11/installing/installing_rhv/installing-rhv-restricted-network.html#installation-bare-metal-config-yaml_installing-rhv-restricted-network), I'd say yes - not sure how to verify this correctly. Can you help? @janosdebugs

**Comment by peterclauterbach** [comment]
I'm not sure I understand the question. Once we support a deployment option, we continue to support it, unless it is explicitly deprecated.
Since it was it was supported in OCP 4.9, it is correct that support continues in OCP 4.10 and OCP 4.11.

**Comment by emarcusRH** [comment]
> I'm not sure I understand the question. Once we support a deployment option, we continue to support it, unless it is explicitly deprecated. Since it was it was supported in OCP 4.9, it is correct that support continues in OCP 4.10 and OCP 4.11.

@peterclauterbach the instructions for OCP on RHV/restricted networks provides the procdure for UPI installations - https://docs.openshift.com/container-platform/4.11/installing/installing_rhv/installing-rhv-restricted-network.html#installation-network-user-infra_installing-rhv-restricted-network
But the support matrix in the general Installation chapter is missing an "X" under UPI/Restricted Networks > RHV
https://docs.openshift.com/container-platform/4.11/installing/installing-preparing.html#supported-installation-methods-for-different-platforms
- is this simply an oversight that it was not updated?

**Comment by peterclauterbach** [comment]
Yes, it's an oversight. We support UPI installations on restricted networks. The bulk of UPI installations are direconnected.

**Comment by emarcusRH** [comment]
too many commit errors - restarting this PR

**Pull request closed without merging**
