### PR TITLE
[WIP] Add Hawkular, Heapster, and Prometheus deprecation notes

### PR DESCRIPTION
**Pull request by rh-max**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, can we merge and CP this?

**Comment by rh-max** [comment]
Oh ok @kalexand-rh. Will use "[WIP]" next time.

**Comment by kalexand-rh** [comment]
No worries @rh-max! Vikram prefers that we try to keep the open PR count low, so I sometimes check for ones that we'll need to merge and try to push them along. The WIP labeling is a good way to signal that we should leave them alone.

**Comment by vikram-redhat** [comment]
@rh-max - can this be closed now?

**Comment by rh-max** [comment]
@vikram-redhat Yes, it can be. Closing.

**Pull request closed without merging**
