### PR TITLE
Deprecated nodeIP config in favor of kubeletArguments["node-ip"]

### PR DESCRIPTION
**Pull request by pravisankar**
Origin PR: https://github.com/openshift/origin/pull/17719 (pending review/merge)

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/networking @openshift/team-documentation PTAL

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL.

**Comment by bfallonf** [comment]
Thanks @pravisankar . Is this for 3.9? Or 3.7?

**Comment by danwinship** [comment]
Does
/hold
work here? Anyway, this shouldn't land until the corresponding code change does.

**Comment by vikram-redhat** [comment]
The corresponding Origin PR has gone stale. I am closing this PR. Please reopen when the Origin PR is merged.

**Pull request closed without merging**
