### PR TITLE
OSDOCS-10987 Updating supported on section of OCP 4.16 RNs

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.16

Issue: [OSDOCS-10987](https://issues.redhat.com/browse/OSDOCS-10987)

Link to docs preview: [Preview](https://77872--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-about-this-release_release-notes)

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by cbippley** [comment]
LGTM from @mffiedler via Slack for the first two changes.

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by julienlim** [comment]
lgtm

**Comment by holgwolf** [comment]
lgtm

**Pull request merged**
