### PR TITLE
Update site nav with openshift.com redesign

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
Staging site: https://commercial-docs-wgordon.6923.rh-us-east-1.openshiftapps.com/

**Comment by nhr** [comment]
@wgordon17 - I don't think Vikram or I are the best people to review these changes; they are all layout changes to match the new OpenShift.com design. I would suggest that you ask if @luciddreamz can do the review or point you in the direction of someone else who can do that style comparison.

**Comment by nhr** [comment]
Ack, thanks for the review @luciddreamz !
@wgordon17 I think you are good to go. I'll let @vikram-redhat have a shot and he can merge it if he's good with the content.

**Comment by vikram-redhat** [comment]
@wgordon17 @luciddreamz @nhr - all looks good to me, but just wondering if we can increase the space between the black header at the top and the breadcrumbs that follow immediately?

For example: https://commercial-docs-wgordon.6923.rh-us-east-1.openshiftapps.com/online/welcome/index.html

**Comment by wgordon17** [comment]
@vikram-redhat I had some margin included (https://github.com/openshift/openshift-docs/pull/9032/files#diff-e93b21cedf1f2b7dfd23be811beadf80), but maybe it has to do with the way I packaged it, that it didn't get applied.

Since I'm only updating master, I would _assume_ that once this is cherry picked to all of the branches, it would work as expected, right?

**Comment by vikram-redhat** [comment]
@wgordon17 - ah yes, it should get applied as the stylesheets are picked from the master branch if you build from the master branch. @nhr can correct me if I am wrong.

Other than that it looks good to me.

I am technically on PTO this week and Monday is a public holiday in Brisbane. If this needs to be merged before the summit, and if I am not around or can't get access to my computer, just ping anyone in the team openshift docs to merge.

cc: @aheslin FYI.

**Comment by nhr** [comment]
@wgordon17 yes, css changes need to be cherry-picked to the branches.

**Comment by nhr** [comment]
I've hand-merged the docs.css change to all non-master branches; merging this now.

**Pull request merged**
