### PR TITLE
SRVKS-805: Add emptyDir config

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVKS-805

Applies for OCP 4.6+

Direct preview link: https://deploy-preview-35989--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/knative-serving-cr-config#serverless-config-emptydir_knative-serving-CR-config

### CODE REVIEW

**Comment by skonto** [comment]
Unless we want to point to some more docs about emptyDir it lgtm.

**Comment by maschmid** [comment]
QE approved

**Comment by bmcelvee** [comment]
LGTM! Don't forget to squash your commits :)

A note: the modules in this assembly _could be_ stretched into the procedure module format, though I don't know that it's necessary.

**Pull request merged**
