### PR TITLE
OSSMDOC-597: Document support for ROSA.

### PR DESCRIPTION
**Pull request by JStickler**
Version(s): 4.6 - 4.11

Issue:[OSSMDOC-597](https://issues.redhat.com/browse/OSSMDOC-597)

Update the docs to document ROSA as a fully supported platform.

Link to docs preview:
http://file.bos.redhat.com/jstickle/OSSMDOC-597/service_mesh/v2x/preparing-ossm-installation.html#ossm-supported-configurations_preparing-ossm-installation
http://file.bos.redhat.com/jstickle/OSSMDOC-597/service_mesh/v2x/ossm-federation.html#ossm-federation-limitations_federation

QE review -  pbajjuri20
Peer review - jc-berger

### CODE REVIEW

**Comment by pbajjuri20** [comment]
It looks perfect..!

**Review by pbajjuri20 — APPROVED** [review]

**Review by jc-berger — APPROVED** [review]

**Pull request merged**
