### PR TITLE
OCPBUGS-35361-12: Updated the wait-ip note for bm only

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.12

Issue:
[OCPBUGS-35361](https://issues.redhat.com/browse/OCPBUGS-35361)

Link to docs preview:
[Optional: Deploying with dual-stack networking](https://77430--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#modifying-install-config-for-dual-stack-network_ipi-install-installation-workflow)

- [x] SME has approved this change.
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by cybertron — COMMENTED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
