### PR TITLE
Document new multicast and NetworkPolicy stuff

### PR DESCRIPTION
**Pull request by danwinship**
This documents the new multicast and NetworkPolicy stuff. I wasn't quite sure how to refer to their "Tech Preview" status, so maybe that needs to be tweaked.

Also, there didn't seem to be any good place to put them, and I realized that we were kind of abusing managing_pods.adoc for a lot of not-especially-pod-related stuff, so I split all the networking stuff out of there into a new "managing_networking" file. It seems to work fine?

~~Built on top of #3572; only the last three commits are new here~~

### CODE REVIEW

**Comment by danwinship** [comment]
rebased around the egress doc updates.
poke poke, this is supposed to be in 3.5

**Comment by bfallonf** [comment]
@danwinship Thanks! I think this looks good overall.

Is this ok to merge? I might do that and do some followups for CCS style, etc.

**Comment by bfallonf** [comment]
Actually, @danwinship this may have to be squashed before I can merge it.

**Comment by danwinship** [comment]
yes, it's ready. squashed and repushed

**Comment by bfallonf** [comment]
Thanks @danwinship . I'll merge this and do a quick followup.

**Comment by vikram-redhat** [comment]
@bfallonf - when this got split, the anchors were duplicated. Please be sure to check for that when doing a follow up.

**Pull request merged**
