### PR TITLE
Removing links added in error

### PR DESCRIPTION
**Pull request by mburke5678**
These  links were [added in error to this file](https://github.com/openshift/openshift-docs/pull/58186/files#diff-32cc22145012670da2376aa01a3f8bfa32f4c0244fa1b44f2c323752161c73c7) somehow. This PR removes them. 
I noticed as I was cherry-picking that PR. I will remove the includes in the 4.10+ branches.

### CODE REVIEW

**Comment by mburke5678** [comment]
@skrthomas PTAL

**Comment by skrthomas** [comment]
@mburke5678 I think the removal is OK but one thing is that there was an additional resources list under Autoscaling an Ingress Controller in your original PR (screen-captured below), and those additional resources look like they were replaced by the resources you're removing now. But I think that the old resources need to be added back. I think that Ingress Autoscaling is new in 4.12+ though, so any adding back of those resources wouldn't need to be cherrypicked all the way to 4.10
image

cc @jldohmann since Jesse added the Autoscaling while I was out on mat leave.

**Comment by mburke5678** [comment]
@skrthomas 

> Ingress Autoscaling is new in 4.12+

That must be what confused me. I will fix the links.

**Comment by mburke5678** [comment]
Replaced the links to [match the what was added](https://github.com/openshift/openshift-docs/pull/49786/files#diff-32cc22145012670da2376aa01a3f8bfa32f4c0244fa1b44f2c323752161c73c7). 

@skrthomas @jldohmann PTAL

**Pull request closed without merging**
