### PR TITLE
OLS-880: Create redirect from OCP stub page to OLS standalone content

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OCP 4.15+

Issue: https://issues.redhat.com/browse/OLS-880

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@gaurav-nelson the team is planning for a July 29 code release. 

I have informed the team that the content will likely be published on the portal on the following day. The team is fine with this.

**Comment by rh-tokeefe** [comment]
According to [these instructions](https://docs.google.com/document/d/1RW7p5cFQ_hHlCLRSeEhFXeaymPPBm_6JV6C4wIr7aUs/edit), the _templates/_page_openshift.html.erb should be updated to include an entry for Lightspeed and the main/.s2i/httpd-cfg/01-commercial.conf file to include a redirect for lightspeed.

Looks like the instructions advise both changes be made on the same PR, so I updated this PR to contain both changes.

**Comment by rh-tokeefe** [comment]
@kalexand-rh the instructions emphasize that changes to the _templates/_page_openshift.html.erb file can crash the doc server. Who do you think would be a good candidate to help review this PR?

**Review by bscott-rh — COMMENTED** [review]
Redirects LGTM.

**Review by gaurav-nelson — APPROVED** [review]
Changes LGTM

**Pull request merged**
