### PR TITLE
Removing old DR procedure landing page

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: http://file.rdu.redhat.com/~ahoffer/2020/removing-old-procedure/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@hexfusion @retroflexer Any objections to removing this landing page for the procedure we used to have in 4.1-4.3 (which now just points to the other restoring cluster state procedure)?

It's this one here: https://docs.openshift.com/container-platform/4.6/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by hexfusion** [comment]
LGTM

**Comment by bergerhoffer** [comment]
Just a removal so no QE needed, merging.

**Pull request merged**
