### PR TITLE
Added process topic for using AsciiDoctor diagram extension

### PR DESCRIPTION
**Pull request by Bilhar-rh**
@nhr @adellape Sanity check please. I'm wondering if GitHub is going to be able to process the AsciiDoctor diagram content. Actually, I don't think it can so that might be an issue because I'm trying to show a rendered example.

### CODE REVIEW

**Comment by adellape** [comment]
No, it doesn't. asciidoctor-diagram's own doc source deals with the same thing:

https://github.com/asciidoctor/asciidoctor-diagram/blob/master/examples/features.adoc

If you want to show a rendered example, I'd just link to their actual docs, since GH's rendered AsciiDoc doesn't display embedded images of any sort either:

http://asciidoctor.org/docs/asciidoctor-diagram/

Do we need this dedicated topic of our own to duplicate the above info when we could just link to it instead from one of the existing contributing docs? It looks like there's not much OpenShift-specific info added.

**Comment by CowboysFan** [comment]
@adellape Yeah, I thought about that myself, but still went ahead and created just for convenience really.  I actually started thinking about possibly turning this into a template people can use easily, and point to the AsciiDoctor docs for installation and all that. 

The rendering issue can be solved by just using the generated PNG.

**Comment by CowboysFan** [comment]
@adellape I've went ahead and updated everything to just simple instructions, and using the AsciiDoctor doc for installation. Let me know if you think we need any more changes.

**Comment by adellape** [comment]
LGTM.

**Pull request merged**
