### PR TITLE
RHDEVDOCS-3513 - Update OpenShift Logging Compatibility Table

### PR DESCRIPTION
**Pull request by libander**
Aligned team: Dev Tools
For branches: enterprise-4.9
https://issues.redhat.com/browse/RHDEVDOCS-3513
Direct link to doc preview: https://deploy-preview-39399--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-upgrading.html
SME review: @alanconway
QE review: @anpingli
Peer review:

### CODE REVIEW

**Comment by Preeticp** [comment]
@anpingli @alanconway can one of you provide a LGTM, please?

**Comment by Preeticp** [comment]
@libander please provide the direct doc preview link so that it is easier for reviewers. Currently I have added it: https://deploy-preview-39399--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-upgrading.html

**Comment by libander** [comment]
> @libander please provide the direct doc preview link so that it is easier for reviewers. Currently I have added it: https://deploy-preview-39399--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-upgrading.html

I did -- the link it generates for me isn't what it gave you. Any ideas on why that might be?

**Comment by anpingli** [comment]
Hold on. The logging 5.3 is planning to support OCP 4.8

**Comment by libander** [comment]
> Hold on. The logging 5.3 is planning to support OCP 4.8

Added!

**Comment by bburt-rh** [comment]
lgtm

**Pull request merged**
