### PR TITLE
Added information about StatefulSets, a Technology Preview feature in OCP 3.5

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/RrilYNmb/434-document-statefulsets-petsets-list-and-detail-views-kubernetes

Preview build: http://file.rdu.redhat.com/~ahardin/03082017/StatefulSets/architecture/infrastructure_components/web_console.html#web-console-statefulsets

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@benjaminapetersen @adellape This is my first pass at documenting StatefulSets. PTAL and let me know if anything should be added. Thanks!

**Comment by benjaminapetersen** [comment]
LGTM, pinging @jwforres if she wants to comment as well.

**Comment by jwforres** [comment]
@derekwaynecarr guessing someone from your team should help review this

**Comment by ahardin-rh** [comment]
@derekwaynecarr bump

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
[rev_history]
ifdef::openshift-enterprise[]
|xref:../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[Infrastructure Components -> Web Console]
|Added information about xref:../architecture/infrastructure_components/web_console.adoc#web-console-statefulsets[`StatefulSet`], currently a Technology Preview feature.
endif::openshift-enterprise[]
%

**Pull request merged**
