### PR TITLE
Bug 1408327, provided guidance for preconfigured loadbalancers for HA OpenShift

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1408327

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sjwalter2 PTAL

**Comment by ahardin-rh** [comment]
@sjwalter2 Any thoughts? Thanks!

**Comment by sjwalter2** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
@bmcelvee @mburke5678 @adellape peer review please :smiley_cat:

**Comment by mburke5678** [comment]
LGTM

**Comment by bmcelvee** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing a Cluster -> Advanced_ Installation]
|Provided guidance for preconfigured loadbalancers for {product-title} with high availability.
%

**Pull request merged**
