### PR TITLE
OSDOCS-9861 updating dep/rem tables

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-9861

Link to docs preview:

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei PTAL at this update to the deprecated/removed tables for 4.16 RN. Thank you

**Comment by bscott-rh** [comment]
QE will not be able to respond before merge freeze, so we will look for post-merge LGTM.

**Comment by obrown1205** [comment]
/label peer-review-done
/remove-label peer-review-in-progress
LGTM!

**Pull request merged**
