### PR TITLE
OSDOCS-1846: Adding known issue for docs for kubeletconfig TLS securi…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…ty profiles

https://issues.redhat.com/browse/OSDOCS-1846

Preview: https://deploy-preview-33829--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-8-known-issues

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sunilcio can you please QE review this known issue?

Preview: https://deploy-preview-33829--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes?utm_source=github&utm_campaign=bot_dp#ocp-4-8-known-issues

**Comment by sunilcio** [comment]
@weinliu hi, could you help review this. I guess we might not need to add this known issues section as I see bug https://bugzilla.redhat.com/show_bug.cgi?id=1971899 is now ON_QA. If you verify the bug, then we do not need to add this doc section. Thanks!

**Comment by weinliu** [comment]
> @weinliu hi, could you help review this. I guess we might not need to add this known issues section as I see bug https://bugzilla.redhat.com/show_bug.cgi?id=1971899 is now ON_QA. If you verify the bug, then we do not need to add this doc section. Thanks!

@sunilcio checking

**Comment by weinliu** [comment]
> @weinliu hi, could you help review this. I guess we might not need to add this known issues section as I see bug https://bugzilla.redhat.com/show_bug.cgi?id=1971899 is now ON_QA. If you verify the bug, then we do not need to add this doc section. Thanks!

@sunilcio , BZ#1971899 is targeting to 4.9, and not fixed on 4.8.0-0.nightly-2021-06-23-232238, I think we still need it on known issue list. It LGTM as-is

**Comment by mburke5678** [comment]
@rphillips Can you PTAL?

**Comment by sunilcio** [comment]
@weinliu ahh, my bad. I missed to check the target release. @mburke5678 @bergerhoffer LGTM.

**Comment by rphillips** [comment]
lgtm

**Pull request merged**
