### PR TITLE
OSDOCS-10456: Clarify CPMS AWS and Azure specs for ext LB

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-10456](https://issues.redhat.com//browse/OSDOCS-10456)

Link to docs preview:
- [Sample AWS provider specification](https://75491--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-configuration#cpmso-yaml-provider-spec-aws_cpmso-configuration)
- [Sample Azure provider specification](https://75491--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-configuration#cpmso-yaml-provider-spec-azure_cpmso-configuration)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Review by damdo — COMMENTED** [review]
LGTM

**Pull request merged**
