### PR TITLE
bug 1888462 missing tags added for 4.6 and prior

### PR DESCRIPTION
**Pull request by sheriff-rh**
Fixes [bug 1888462](https://bugzilla.redhat.com/show_bug.cgi?id=1888462)

Closing #26714 in favor of this pull request for 4.6 and prior releases. Future releases will require different tags due to a code change in progress. These changes were previously acknowledged by peer review and QE.

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM!

**Comment by gpei** [comment]
lgtm 👍

**Pull request merged**
