### PR TITLE
Correct wrong path to config.env. Fixes #1524.

### LINKED ISSUE #1524: Incorrect path: /etc/openshift-sdn/config.env should be /run/openshift-sdn/config.env
The ["ramp node" setup doc](https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html#establishing-a-tunnel-using-a-ramp-node) in the "SNAT the tunnel IP with an unused IP from the SDN subnet:" section says to run:

```
# source /etc/openshift-sdn/config.env
```

That file does not exist at that path, but appears to exist at `/run/openshift-sdn/config.env` when installed with the 'advanced installation' at these versions:

```
tuned-profiles-origin-node-1.1.1-0.git.0.54a57ff.el7.centos.x86_64
origin-node-1.1.1-0.git.0.54a57ff.el7.centos.x86_64
origin-1.1.1-0.git.0.54a57ff.el7.centos.x86_64
origin-clients-1.1.1-0.git.0.54a57ff.el7.centos.x86_64
origin-sdn-ovs-1.1.1-0.git.0.54a57ff.el7.centos.x86_64
```

I think the line should read:

```
# source /run/openshift-sdn/config.env
```

### PR DESCRIPTION
**Pull request by rwehner**
I believe this this the right fix for https://github.com/openshift/openshift-docs/issues/1524.

### CODE REVIEW

**Comment by adellape** [comment]
This seems right to me, looking at a OSE 3.1 node of my own.

@ramr Can you ack?

**Comment by ramr** [comment]
@adellape - am OOO + no access to OSE and so will let @rajatchopra / @pravisankar / @brenton   comment.

**Comment by brenton** [comment]
@adellape :+1:

**Comment by adellape** [comment]
**revhistory note:**

(Install & Config -> Routing from Edge Load Balancers)

```
Corrected the *_/run/openshift-sdn/config.env_* path in the link:../install_config/routing_from_edge_lb.html#establishing-a-tunnel-using-a-ramp-node[Establishing a Tunnel Using a Ramp Node] section.
```

**Pull request merged**
