### PR TITLE
fix typo in odo CLI reference

### PR DESCRIPTION
**Pull request by BethGriggs**
:wave: I spotted this typo so thought i'd open a quick PR. Please let me know if there is anything further I need to do.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@BethGriggs, thanks for the submission! Please also change the name of the `developer-cli-odo-deploying-a-java-application-using-a-devile.adoc` file by using the `git mv` command.

**Comment by BethGriggs** [comment]
ah! thanks, updated

**Comment by kalexand-rh** [comment]
@vikram-redhat, I don't see any links to this module in the collection, so I haven't added it to the redirects register.

**Pull request merged**
