### PR TITLE
TELCODOCS-419-RN creating first draft of network level safe sysctl

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-419]: Creating RN entry for setting network level safe sysctls

Version(s): 4.11 RN

Issue: https://issues.redhat.com/browse/TELCODOCS-419 and https://issues.redhat.com/browse/TELCODOCS-418

Link to docs preview: http://file.emea.redhat.com/kquinn/TELCODOCS-419-RN/release_notes/ocp-4-11-release-notes.html#ocp-4-11-configuring-interface-level-safe-network-sysclts

Additional information:

### CODE REVIEW

**Comment by kquinn1204** [comment]
@mmirecki @kononovn can you review this PR for new features section of the 4.11 RN

**Review by darshan-nagaraj — COMMENTED** [review]
few nits online. Otherwise LGTM.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Pull request merged**
