### PR TITLE
Clarify NTP server requirement

### LINKED ISSUE #27490: [enterprise-4.6] Issue in file installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
### Which section(s) is the issue in?
Network requirements

### What needs fixing?

In the section that discusses the NTP server it says the following:

**_"Network Time Protocol (NTP)
Each OpenShift Container Platform node in the cluster must have access to an NTP server."_**

What's unclear about this is that the NTP server must be **discoverable via DHCP**. If this is not the case, the installation will fail.
If there could be a line of text in the "Network Time Protocol (NTP)" section stating this, it would allow customers to avoid long debugging sessions due to this misunderstanding.

### PR DESCRIPTION
**Pull request by jeana-redhat**
Fixes https://github.com/openshift/openshift-docs/issues/27490
Preview: https://deploy-preview-30928--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#network-requirements_ipi-install-prerequisites

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@ryandevlin-redhat Saw your additional commentary on Sara's PR for the vSphere version of this content, and updated my PR to carry a similar message. I did leave it as a section rather than a note in this topic, which I think works in this context. LMK if this works for you.

**Comment by ryandevlin-redhat** [comment]
@jeana-redhat Looks great, thanks!

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
