### PR TITLE
Persistent Volumes docs -- 1st draft

### PR DESCRIPTION
**Pull request by markturansky**

### CODE REVIEW

**Comment by danmcp** [comment]
@markturansky Have all the corresponding code changes related to these docs merged into origin yet?

**Comment by markturansky** [comment]
Yes, the docs will not change when the newer version of PVClaimBinder drops into OpenShift.

**Comment by danmcp** [comment]
@markturansky But do these docs at least match what's currently in origin?

**Comment by markturansky** [comment]
Yes, the docs in this PR are compatible with both the current version of PVClaimBinder and the one modified upstream.  

This PR and its docs will not change when the new PVCBinder drops.

**Comment by danmcp** [comment]
@markturansky Okay I would like to see this merge then.

@adellape @CowboysFan Ready to review/merge.

**Comment by adellape** [comment]
Thanks, @markturansky. LGTM, merging.

Will follow up with any edits per docs card https://trello.com/c/u8Zdytwa.

**Pull request merged**
