### PR TITLE
CNV-18202: Updating repo names for 4.12

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
CP to 4.12 only

Issue:
[CNV-18202](https://issues.redhat.com//browse/CNV-18202)

Link to docs preview:
[Enabling OpenShift Virtualization repositories](https://54421--docspreview.netlify.app/openshift-enterprise/latest/virt/install/virt-installing-virtctl.html#virt-enabling-virt-repos_virt-installing-virtctl)

QE review: @orenc1 

* [x]  QE has approved this change.

Additional information:
N/A

### CODE REVIEW

**Review by orenc1 — APPROVED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Pull request merged**
