### PR TITLE
[OCP 4.10] up rev ACM docs version in ZTP docs

### PR DESCRIPTION
**Pull request by aireilly**
Updating the linked version of ACM docs from 2.3 to 2.4. Merge to main, enterprise-4.10

Preview: https://deploy-preview-42443--osdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-deploying-disconnected.html#installing-disconnected-rhacm_ztp-deploying-disconnected

### CODE REVIEW

**Review by imiller0 — COMMENTED** [review]
/lgtm

**Comment by yliu127** [comment]
LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
