### PR TITLE
CNV-44887: Issue in file virt/virtual_machines/virt-managing-vms-openshift-pipelines.ado

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-44887

CNV 4.16+
OCP 4.16+

Preview: https://80758--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-managing-vms-openshift-pipelines.html#virt-running-tto-pipeline-cli_virt-managing-vms-openshift-pipelines

### CODE REVIEW

**Review by InfoSec812 — APPROVED** [review]
Thank you, this is exactly what I was expecting!

**Review by InfoSec812 — APPROVED** [review]
This is accurate and updated now. Thank you!

**Review by jeana-redhat — APPROVED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by RoniKishner** [comment]
/lgtm
looks good from QE side

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Comment by geetikakay** [comment]
There are some minor issues with this writeup:

1. the pipelineref that we gave that pipeline don't exist anymore in 4.16+

2. create-base-dv doesn't exist now.

**Pull request merged**
