### PR TITLE
OSDOCS-4813 Pt2: Corrected some typos and added a link

### PR DESCRIPTION
**Pull request by EricPonvelle**
Version(s):
`enterprise-4.12+`

Issue:
[OSDOCS-4813](https://issues.redhat.com/browse/OSDOCS-4813)

Link to docs preview:
* [STS](https://55549--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources.html#rosa-minimum-scp_rosa-sts-about-iam-resources)
* [Non-STS](https://55549--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html#rosa-minimum-scp_prerequisites)

Additional information:
Cleaned up some typos and added a new link to AWS.

### CODE REVIEW

**Review by jldohmann — APPROVED** [review]
LGTM!

**Comment by codymant** [comment]
LGTM also! Thanks Eric!

**Pull request merged**
