### PR TITLE
BZ1926013: added an admonition for subscriptions

### PR DESCRIPTION
**Pull request by Amrita42**
- Applies to 4.6+ versions.
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1926013)
- [Prevew](https://deploy-preview-39442--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html)

- @sunilcio @bysnupy  Please review and provide your feedback.

### CODE REVIEW

**Comment by lpettyjo** [comment]
Peer review: LGTM

**Review by lpettyjo — COMMENTED** [review]
/LGTM

**Comment by Amrita42** [comment]
Please undo the Cherry pick as there is a mistake , will create a fresh PR , close this PR and link it.

**Pull request merged**
