### PR TITLE
Fix for OCPBUGS-17449

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OCPBUGS-17449

Link to docs preview: 
https://64008--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installation-config-parameters-ibm-power-vs
https://64008--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-customizations#installation-configuration-parameters-optional_installing-ibm-power-vs-customizations

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by cbippley — COMMENTED** [review]
LGTM, pending QE approval.

**Comment by cbippley** [comment]
/label peer-review-done
/remove-label peer-review-in-progress
@opayne1 PTAL

**Review by opayne1 — COMMENTED** [review]
looks good to me!

**Comment by dfitzmau** [comment]
Hi @alishaIBM .

I added a comment to the following PR: https://github.com/openshift/openshift-docs/pull/64103#issuecomment-1701281202 . Would you be OK to reach out to IBM engineers and confirm if the {e980,s922} parameter values are correct or have these not rendered correctly?

You can find these values in the recently merged "Additional IBM Power Virtual Server configuration parameters" section in the 4.14 OCP docs.

**Comment by opayne1** [comment]
Taking off merge review needed for @dfitzmau comment just to make sure everything is good to go first.

**Comment by alishaIBM** [comment]
> Hi @alishaIBM .
> 
> I added a comment to the following PR: [#64103 (comment)](https://github.com/openshift/openshift-docs/pull/64103#issuecomment-1701281202) . Would you be OK to reach out to IBM engineers and confirm if the {e980,s922} parameter values are correct or have these not rendered correctly?
> 
> You can find these values in the recently merged "Additional IBM Power Virtual Server configuration parameters" section in the 4.14 OCP docs.

@mjturek could you please confirm here if we can reframe the sentence as shown below ?
```
|`platform.powervs.sysType`
|The SysType defines the system type for the instance.
|The system type must be one either e980 or s922.
```

At present it is rendered as shown below: 
image

**Comment by mjturek** [comment]
> > Hi @alishaIBM .
> > I added a comment to the following PR: [#64103 (comment)](https://github.com/openshift/openshift-docs/pull/64103#issuecomment-1701281202) . Would you be OK to reach out to IBM engineers and confirm if the {e980,s922} parameter values are correct or have these not rendered correctly?
> > You can find these values in the recently merged "Additional IBM Power Virtual Server configuration parameters" section in the 4.14 OCP docs.
> 
> @mjturek could you please confirm here if we can reframe the sentence as shown below ?
> 
> ```
> |`platform.powervs.sysType`
> |The SysType defines the system type for the instance.
> |The system type must be either e980 or s922.
> ```
> 
> At present it is rendered as shown below: image

confirmed

**Comment by alishaIBM** [comment]
> Hi @alishaIBM .
> 
> I added a comment to the following PR: [#64103 (comment)](https://github.com/openshift/openshift-docs/pull/64103#issuecomment-1701281202) . Would you be OK to reach out to IBM engineers and confirm if the {e980,s922} parameter values are correct or have these not rendered correctly?
> 
> You can find these values in the recently merged "Additional IBM Power Virtual Server configuration parameters" section in the 4.14 OCP docs.

@dfitzmau I have updated the PR as discussed above. Request you to check. Thanks.

**Comment by dfitzmau** [comment]
> > Hi @alishaIBM .
> > I added a comment to the following PR: [#64103 (comment)](https://github.com/openshift/openshift-docs/pull/64103#issuecomment-1701281202) . Would you be OK to reach out to IBM engineers and confirm if the {e980,s922} parameter values are correct or have these not rendered correctly?
> > You can find these values in the recently merged "Additional IBM Power Virtual Server configuration parameters" section in the 4.14 OCP docs.
> 
> @dfitzmau I have updated the PR as discussed above. Request you to check. Thanks.

Thanks, @alishaIBM . I checked your preview link and the values now render correctly. Thank you. LGTM!

**Review by sheriff-rh — APPROVED** [review]
LGTM! Merging.

**Comment by sheriff-rh** [comment]
Looks like two conflicts in the file for 4.13, @alishaIBM. Can you create a manual cherry pick PR to resolve the issue? I have attached screenshots with line numbers if it helps. 

image
image

**Comment by alishaIBM** [comment]
> Looks like two conflicts in the file for 4.13, @alishaIBM. Can you create a manual cherry pick PR to resolve the issue? I have attached screenshots with line numbers if it helps.
> 
> image image

Have raised a PR: [[enterprise-4.13] Fix for OCPBUGS-17449 #65498](https://github.com/openshift/openshift-docs/pull/65498)
fyi: @sheriff-rh

**Pull request merged**
