### PR TITLE
RHDEVDOCS-3193 Remove 5.0 "Supported log data output types" topic fro…

### PR DESCRIPTION
**Pull request by rolfedh**
Purpose: To remove the Logging 5.0 "Supported log data output types" topic from the OCP 4.8+ docs.
This way, the OCP 4.7 docs have Logging 5.0 and 5.1 information, and the OCP 4.8+ docs have only OpenShift Logging 5.1 information. This is a continuation of https://github.com/openshift/openshift-docs/pull/34820
- Aligned team: Dev Tools
- For branches: 4.8+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3193
- Direct link to doc preview: https://deploy-preview-34920--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-external?utm_source=github&utm_campaign=bot_dp#cluster-logging-collector-log-forwarding-supported-plugins-5-1_cluster-logging-external
- SME review: @vimalk78 
- QE review: @anpingli 
- Peer review: @ tbd
- <All reviews complete. Please merge now>

### CODE REVIEW

**Review by vimalk78 — APPROVED** [review]
/lgtm

**Review by anpingli — APPROVED** [review]
/lgtm

**Review by JStickler — APPROVED** [review]
Deletions are the easiest reviews!   =D
LGTM.

**Pull request merged**
