### PR TITLE
Mhess fix rhacs docs

### PR DESCRIPTION
**Pull request by GrimmiMeloni**
Fixed an ascii doc formatting issue due to a misspelled keyword.
Fixed a sentence by adding a missing word.

Version(s):

- Merge to rhacs-docs
- Cherry pick to rhacs-docs-3.73
- Cherry pick to rhacs-docs-3.74
- Cherry pick to rhacs-docs-4.0

Issue:
N/A

Link to docs preview:
N/A - see changes in PR...?

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
Hi, I had a couple of items and commits need to be squashed into one commit but otherwise lgtm! Thank you so much for directly contributing this!

**Comment by kcarmichael08** [comment]
Hi @GrimmiMeloni It just needs the 3 commits squashed into one commit before it can be merge reviewed & merged.

**Comment by GrimmiMeloni** [comment]
> Hi @GrimmiMeloni It just needs the 3 commits squashed into one commit before it can be merge reviewed & merged.

Done.

**Pull request merged**
