### PR TITLE
OSDOCS#7000:Non-graceful node shutdown TP -> GA

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OSDOCS-7000

Link to docs preview: https://68340--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vol-detach-non-graceful-shutdown

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gcharot, @jsafrane, @wsun1

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by jsafrane** [comment]
lgtm

**Comment by duanwei33** [comment]
@radeore Could you help take a look?

**Pull request merged**
