### PR TITLE
Liveliness probe does not log a failure

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1625227

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning PTAL

**Comment by mburke5678** [comment]
This change should be applied all the way back to 3.0?

**Comment by mburke5678** [comment]
@xltian PTAL

**Comment by mdshuai** [comment]
This change lgtm, as this https://bugzilla.redhat.com/show_bug.cgi?id=1625227#c3 it should only effect effect on docker env.

**Comment by mburke5678** [comment]
@openshift/team-documentation One sentence I added. Can someone PTAL? I changed it just now as it didn't sound right the way I had first written it. Does this sound OK?

**Review by kalexand-rh — COMMENTED** [review]
As long as it makes sense in context, LGTM

**Comment by mburke5678** [comment]
@kalexand-rh Thanks!!

**Pull request merged**
