### PR TITLE
OSDOCS-11406 External DNS Rebase Release Notes

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.17

Issue: https://issues.redhat.com/browse/OSDOCS-11406

Link to docs preview: https://81811--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/external_dns_operator/external-dns-operator-release-notes.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@alebedev87 and @ShudiLi for review and QE check please

**Review by jldohmann — APPROVED** [review]
LGTM! thanks Jessi 😄

**Comment by ShudiLi** [comment]
/lgtm
cc: @melvinjoseph86, thanks

**Pull request merged**
