### PR TITLE
OBSDOCS-882: Tweak the DT 3.1 RN

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.16, 4.15, 4.14, 4.13, 4.12

Issue:

https://issues.redhat.com/browse/OBSDOCS-882

Link to docs preview:

https://72501--ocpdocs-pr.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_rn/distr-tracing-rn-3-1#distributed-tracing-rn_3-1_jaeger-release-notes_deprecated-functionality

QE review:
- N/A

Additional information:

### CODE REVIEW

**Review by jgomezselles — APPROVED** [review]
Thanks!

**Review by Srivaralakshmi — COMMENTED** [review]
@max-cx Neat PR, good job! LGTM. Thank you!

**Pull request merged**
