### PR TITLE
Remove all instances of Starter EOL from the docs.

### PR DESCRIPTION
**Pull request by sfortner-RH**
Remove all instances of Starter EOL docs per [OSDOCS-1495](https://issues.redhat.com/browse/OSDOCS-1495).

CP to 4.5,4.4, and 4.3

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Hey @sfortner-RH - just need to remove it from the distro_map. The online docs are still needed for Pro version as if I understand right, that is not going away.

**Comment by sfortner-RH** [comment]
@vikram-redhat that is correct, but all the Pro docs are in enterprise-3.11. They aren't in 4.x. Only starter was in 4.x per all my digging.  I was going to ping you to review this, because I needed the sanity check :)

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
