### PR TITLE
CMP-2752: Compliance Operator 1.5.1 Release Note Update

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/CMP-2752

Link to docs preview: https://81197--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-release-notes.html

QE review:
- [ ] QE has approved this change.

Additional information: There are no public bug fixes or enhancements listed in the associated errata.

### CODE REVIEW

**Comment by xiaojiey** [comment]
lgtm

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Review by rhmdnd — COMMENTED** [review]
/lgtm

**Review by sheriff-rh — APPROVED** [review]
Changes look good, ready for merge.

**Pull request merged**
