### PR TITLE
Bug 1312237 : Switched values in the edge termination example

### PR DESCRIPTION
**Pull request by bfallonf**
Simple BZ fix. Probably OK to merge away. 

@tpoitras @adellape @tnguyen-rh @ahardin-rh

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@bfallonf Needs labels/milestone.

**Comment by bfallonf** [comment]
[rev_history]
|link:../architecture/core_concepts/routes.html[Core Concepts -> Routes]
|Corrected footnote placement in the link:../architecture/core_concepts/routes.html#secured-routes[Secured Routes] section.
%

**Comment by bfallonf** [comment]
@tnguyen-rh Fixed

**Comment by tnguyen-rh** [comment]
@bfallonf 
I dropped some superfluous labels and was about to hit the merge button, but now i see there are conflicts.  How about a rebase?

**Comment by bfallonf** [comment]
@tnguyen-rh Cool. Rebased. I'll merge this.

**Pull request merged**
