### PR TITLE
[OSDOCS-6557]:Docs refers wrongly to on-premise storage

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-6557
Link to docs preview:

https://61674--docspreview.netlify.app/openshift-rosa/latest/storage/index.html
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @Xue Li and/or @yuwan,
   Could you please provide QE review for this PR https://github.com/openshift/openshift-docs/pull/61674 when you get a moment? Please and thank you! ML

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging!

**Pull request merged**
