### PR TITLE
OSSMDOC-572: Update 1.0 to 1.1 in service mesh doc

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.6 - 4.11

Issue: https://issues.redhat.com/browse/OSSMDOC-572

Link to docs preview: https://deploy-preview-45576--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v1x/installing-ossm

Additional information:

### CODE REVIEW

**Comment by rh-tokeefe** [comment]
@JStickler this is ready for peer review.

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
