### PR TITLE
issue 16693 bumping ansible version

### LINKED ISSUE #16693: [enterprise-4.2] Edit suggested in file machine_management/adding-rhel-compute.adoc
### Which section(s) is the issue in?
Repositories needed

### What needs fixing?
ansible-2.7 needs to change to ansible-2.8
also, the ocp repository needs to change from 4.1 to 4.2

### PR DESCRIPTION
**Pull request by kalexand-rh**
Fixes #16693

@mtnbikenc, do you agree?

### CODE REVIEW

**Comment by mtnbikenc** [comment]
LGTM

**Comment by kalexand-rh** [comment]
@wmengRH, do you agree with this change?

**Comment by wmengRH** [comment]
Yes. I agree. 
This change is good.
Thanks.

**Pull request merged**
