### PR TITLE
RHDEVDOCS-3915 relocating Jenkins assemblies to CICD

### PR DESCRIPTION
**Pull request by rolfedh**
- Purpose: Move these two topics from [the **Images > Using images** node](https://rolfedh.github.io/previews/RHDEVDOCS-3915/openshift_images/using_images/using-images-overview.html) in the TOC to the **CICD > Jenkins** node:
  - Configuring Jenkins images
  - Jenkins agent

- Aligned team: Dev Tools
- For branches: 4.11
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3915
- Direct link to doc preview: https://rolfedh.github.io/previews/RHDEVDOCS-3915/cicd/jenkins/images-other-jenkins.html
- SME review: @coreydaley   
- QE review: @jitendar-singh 
- Peer review: @jc-berger 
- All reviews complete. Please merge now.

### CODE REVIEW

**Comment by gabemontero** [comment]
no @akram or @coreydaley needs to be the SME reviewer here

**Review by jc-berger — APPROVED** [review]
/lgtm

**Pull request merged**
