### PR TITLE
GH#31328 - Added subjectAltName to the registry certificate

### LINKED ISSUE #31328: Baremetal container mirror certificate missing flag
### Which section(s) is the issue in?
 Installing / Deploying installer-provisioned clusters on bare metal / Setting up the environment for an OpenShift installation / Generating the self-signed certificate (optional)

### What needs fixing?

The certificate instructions miss an important flag `-addext "subjectAltName = DNS:${host_fqdn}"`

See https://openshift-kni.github.io/baremetal-deploy/4.7/Deployment.html#_generating_the_self_signed_certificate_optional

### PR DESCRIPTION
**Pull request by e-minguez**
Fix #31328

### CODE REVIEW

**Comment by e-minguez** [comment]
@jboxman do you mind to take a look at this? Thanks!

**Comment by gpei** [comment]
LGTM

**Comment by jboxman** [comment]
@gpei thanks!

**Pull request merged**
