### PR TITLE
HCIDOCS-300: Incorrect example for dual port NIC in day 1 metal IPI

### PR DESCRIPTION
**Pull request by johnwilkins**
Updated configuration from feedback.

Fixes: [HCIDOCS-300](https://issues.redhat.com//browse/HCIDOCS-300)

See https://issues.redhat.com/browse/HCIDOCS-300 for additional details.

Preview URL: http://184.23.213.161:8080/HCIDOCS-300/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configuring-host-dual-network-interfaces-in-the-install-config-yaml-file_ipi-install-installation-workflow

For release(s): 4.13-4.16
QE Review: 

- [x] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]
Seems fine as far as peer review goes. Still needs QE approval. lgtm. 

Note that this is an opportunity to fix the module title--we aren't supposed to use "Optional:" in module titles.

**Comment by johnwilkins** [comment]
Note: There is no corresponding module entry for openshift-4.12. The module was introduced in openshift-4.13 as a Technology Preview.

**Comment by kcarmichael08** [comment]
Consider an update to the title at some point to address @maxwelldb 's comment, but I'll merge this one now.

**Pull request merged**
