### PR TITLE
Improve product docs for custom machine config pool nuances

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-4586

New module on custom machine config pools, based on internal 

Added module to:
Architecture -> Control plane architecture -> Node configuration management with machine config pools -> [Configuring a node by using custom machine config pools](https://53072--docspreview.netlify.app/openshift-enterprise/latest/architecture/control-plane.html#architecture-machine-config-pools-custom_control-plane)
Post-installation -> Post-installation machine configuration tasks -> [Configuring a node by using custom machine config pools](https://53072--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/machine-configuration-tasks.html#architecture-machine-config-pools-custom_post-install-machine-configuration-tasks)
Post-installation -> Post-installation node tasks -> [Configuring a node by using custom machine config pools
](https://53072--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/node-tasks.html#architecture-machine-config-pools-custom_post-install-node-tasks)

Source material for new modue:
* https://access.redhat.com/solutions/5688941
* Moved a couple paragraphs from:  Architecture -> Control plane architecture -> Node configuration management with machine config pools

### CODE REVIEW

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by kalexand-rh** [comment]
Only versions 4.11+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Comment by mburke5678** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/82611

**Pull request closed without merging**
