### PR TITLE
Fix formatting issue

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: None. Fixes formatting issue in https://github.com/openshift/openshift-docs/pull/54337

Link to docs preview: [Reviewing resource usage by virtual machines ](https://54357--docspreview.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-reviewing-vm-dashboard.html)

QE review: NA
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by tmalove** [comment]
@apinnick  Just a nit, but do you mean '4.12+' for the version instead of '4.12'? Otherwise, it looks good.

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by apinnick** [comment]
> @apinnick Just a nit, but do you mean '4.12+' for the version instead of '4.12'? Otherwise, it looks good.
> 
> /remove-label peer-review-in-progress /label peer-review-done

@tmalove  Yes, that's what I meant. I'll fix that. Thanks!

**Pull request merged**
