### PR TITLE
SRVOCF-361: Updates to the func.yaml reference documentation

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+
Jira: https://issues.redhat.com/browse/SRVOCF-361
Docs preview: https://deploy-preview-38798--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-yaml.html

### CODE REVIEW

**Comment by rh-max** [comment]
@lance Could you PTAL? Note that in addition to the changes you suggested in SRVOCF-361, I've also documented `buildEnvs` . Please let me know if I should delete them.

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by rh-max** [comment]
@jrangelramos You are the right person to QE-review functions stuff, right? If so, could you PTAL?
@lance Thanks Lance!

**Comment by jrangelramos** [comment]
Hello @rh-max 
LGTM
QE Approved

**Comment by sagidlow** [comment]
LGTM!

**Pull request merged**
