### PR TITLE
CNV-26234: replace cluster tasks with tasks

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.14

**Issue:**
https://issues.redhat.com/browse/CNV-26234

**Link to docs preview:**
https://60800--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-managing-vms-openshift-pipelines.html

**QE review:**
- [ ] QE has approved this change.

**Additional information:**
NA

### CODE REVIEW

**Comment by ksimon1** [comment]
A small note, this change should only go to 4.14, not 4.12+.

**Comment by geetikakay** [comment]
lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
