### PR TITLE
TELCODOCS:1103d - Update to kataconfig file in 4.9

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s): 4.9

Issue: [TELCODOCS-1103](https://issues.redhat.com/browse/TELCODOCS-1103)

[Link to docs preview](https://55842--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads.html#sandboxed-containers-create-kataconfig-resource-web-console_deploying-sandboxed-containers)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by tbuskey** [comment]
QE ack /lgtm

**Comment by eohartman** [comment]
Looks great!

**Pull request merged**
