### PR TITLE
SRVCOM-2431 fix page-loader.js for serverless

### PR DESCRIPTION
**Pull request by gabriel-rh**
Version(s):
main and  4.1

Issue:
[SRVCOM-2431](https://issues.redhat.com//browse/SRVCOM-2431)

Link to docs preview:

Additional Info:

I have copied the changes from the direct commit to 4.1 and added in new serverless stuff on top. 

This needs to be then cherry-picked to 4.1 to take effect

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gaurav-nelson, will you PTAL?

**Review by gaurav-nelson — CHANGES_REQUESTED** [review]
@gabriel-rh Thank you for the PR. Can you please redo this and target the `enterprise-4.1` branch? Because the doc site uses the file from that branch. I see some of the changes are already in the `_javascripts/page-loader.js` file in the `enterprise-4.1` branch.

**Comment by gabriel-rh** [comment]
@gaurav-nelson 

My plan is to merge to main and then cherry-pick to 4.1. Just to be clear, I started with the js file that is currently on the 4.1 branch to pick up the acs stuff, and then added in the serverless changes on top and PR'd against main.

I think we need to be consistent with the js/css files - either merge to main and then CP to 4.1, or merge directly to 4.1 but at the moment we seem to have a mix. From talking to Aidan yesterday, his workflow for CSS is merge to main, CP to 4.1.

I guess either way works ok, but we need to just choose one - for this PR, I chose to merge to main and then CP to 4.1

@kalexand-rh @aireilly

**Comment by gabriel-rh** [comment]
Gaurav Nelson
 [12:25 PM](https://redhat-internal.slack.com/archives/D04TDC4UAUB/p1685013928600999)
Cool. As long as 4.1 changes are in there it is fine with me. I’ll pick that PR again tomorrow

**Comment by gabriel-rh** [comment]
Here are the actual changes on 4.1: https://github.com/openshift/openshift-docs/pull/60553/files

**Pull request merged**
