### PR TITLE
Fixed encryption types wording

### PR DESCRIPTION
**Pull request by bfallonf**
@adellape @ahardin-rh @tnguyen-rh @tpoitras

Peer review please.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@bfallonf LGTM!

**Comment by adellape** [comment]
:+1:

**Comment by bfallonf** [comment]
Cool. Merging. Thanks, all.

**Comment by bfallonf** [comment]
[rev_history]
|link:../install_config/configuring_authentication.html[Configuring Authentication]
|Corrected wording in the link:../install_config/configuring_authentication.html#HTPasswdPasswordIdentityProvider[HTPasswd section].
%

**Pull request merged**
