### PR TITLE
OSDOCS-6796: Adding final deprecation notice for 1.0 channel

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.10+
Issue:

https://issues.redhat.com/browse/OSDOCS-6796
Link to docs preview:

https://62486--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/network-observability-operator-release-notes.html#network-observability-channel-deprecation
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@nathan-weinberg @jotak can you PTAL at this PR.

**Review by nathan-weinberg — COMMENTED** [review]
/label qe-approved

**Review by jotak — APPROVED** [review]

**Comment by ShaunaDiaz** [comment]
@skrthomas Do you need to check the QE box?

**Comment by ShaunaDiaz** [comment]
@maxwelldb Will you please verify my review? Thx!

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
