### PR TITLE
Bug 1305552, added step: switch to your new project after creating it

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1305552

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape PTAL. Thanks!

**Comment by ahardin-rh** [comment]
Approved by the reporter, Alexander Koksharov.

@adellape any edits?

**Comment by bfallonf** [comment]
@ahardin-rh What you have here seems to be a double-up of one of the issues from my #1641. Not sure which way we want to go. If we want to merge this one I can get rid of that little bit in mine. No biggie.

**Comment by ahardin-rh** [comment]
@bfallonf I will go ahead and merge this and we can cobble the 2 changes together. Thanks!

**Comment by ahardin-rh** [comment]
**revhistory note:**

(for Install/Config --> Aggregating Container Logs)

    Added a step within the link:../install_config/aggregate_logging.html#pre-deployment-configuration[Pre-deployment Configuration] section indicating that you must switch to your new project after creating it.

**Pull request merged**
