### PR TITLE
MULTIARCH-168: Release note additions for IBM Power and Z

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/MULTIARCH-168

Additional IBM Z restrictions: https://docs.google.com/document/d/1WvBhHVcTrXM54--qd2CHpdKtAD7RlY90Mb8vAlUdJyc/edit?ts=5ea84486

### CODE REVIEW

**Review by manojnkumar — APPROVED** [review]
Looks good to me.

**Comment by mburke5678** [comment]
@manojnkumar I also added an entry for IBM Z. Can you comment if this entry looks good?
I was asked to [add more restrictions for IBM Z](https://docs.google.com/document/d/1WvBhHVcTrXM54--qd2CHpdKtAD7RlY90Mb8vAlUdJyc/edit?ts=5ea84486). Do you know if the restrictions for IBM Power are the same as IBM Z?

**Comment by mburke5678** [comment]
Waiting on the following to add links to IBM Power and IBM Z install:
https://issues.redhat.com/browse/MULTIARCH-169
https://issues.redhat.com/browse/MULTIARCH-110

**Comment by mburke5678** [comment]
Format of Features section from:
https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-10

**Comment by bpradipt** [comment]
@mburke5678 a minor nit. There is one more reference to PowerPC "Architecture support has been expanded to IBM Z and PowerPC platforms, providing binaries that are available for installation." under "OpenShift Do enhancements".  It would be good to replace that with `Power`

**Comment by mburke5678** [comment]
@bpradipt Made the change.  Does this conflict with our statement that odo is not supported for IBM Power and Z?
```
OpenShift Do enhancements
OpenShift Do (odo) has a few enhancements that focus on the user experience of
application deployment:
* Architecture support has been expanded to IBM Z and Power platforms,
providing binaries that are available for installation.

```

**Comment by bpradipt** [comment]
> @bpradipt Made the change. Does this conflict with our statement that odo is not supported for IBM Power and Z?
> 
> ```
> OpenShift Do enhancements
> OpenShift Do (odo) has a few enhancements that focus on the user experience of
> application deployment:
> * Architecture support has been expanded to IBM Z and Power platforms,
> providing binaries that are available for installation.
> ```

Sorry missed this.. I think the support statement still holds good. One the binaries are available for use as-is. 
@manojnkumar can you please check this ?

**Pull request merged**
