### PR TITLE
[WIP] Bug 1756253 Add link to CloudFront configuration

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1756253

### CODE REVIEW

**Comment by xiuwang** [comment]
@bmcelvee IMO, [bug 1756253](https://bugzilla.redhat.com/show_bug.cgi?id=1756253) is intented to add introduction for those parameters https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/apis/imageregistry/v1/types.go#L180-L189

**Comment by wzheng1** [comment]
@bmcelvee Image registry config has great change comparing to v3.x, so please refer to my test case for doc: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-22753 .

**Comment by bmcelvee** [comment]
This PR needs substantial reworking and will land post GA.

**Comment by vikram-redhat** [comment]
@bmcelvee when you are back, can you update this PR?

**Pull request closed without merging**
