### PR TITLE
BZ#2083421: Remove not existing FluentdQueueLengthBurst alert

### PR DESCRIPTION
**Pull request by bysnupy**
FluentdQueueLengthBurst alert has been removed as of Cluster Logging v5.1. Remove not existing alert for suppressing confusion.

Version(s):

OCP v4.7+

Issue:

https://bugzilla.redhat.com/show_bug.cgi?id=2083421

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@anpingli, will you PTAL?

**Comment by bysnupy** [comment]
@anpingli could you PTAL ? Thanks.

**Comment by bysnupy** [comment]
@anpingli could you please take a look at this ? If you are busy, please suggest another member who can review this matter. Thanks.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
