### PR TITLE
Followup edits to PR 2226

### PR DESCRIPTION
**Pull request by bfallonf**
#2226

Rev history in original PR.

@tpoitras @tnguyen-rh @ahardin-rh @adellape Any problems?

### CODE REVIEW

**Comment by bfallonf** [comment]
@tnguyen-rh Aaand now I just realised you assigned self-assigned to the original PR. Hope I didn't step on your toes...

**Comment by tpoitras** [comment]
@bfallonf LGTM! :star2: :star: :stars:

**Comment by bfallonf** [comment]
Thanks @tpoitras I'll merge.

**Comment by tnguyen-rh** [comment]
@bfallonf No worries.  I've unassigned myself from #2226.

**Pull request merged**
