### PR TITLE
ossmdoc-277 and ossmdoc-262

### PR DESCRIPTION
**Pull request by neal-timpe**
https://issues.redhat.com/browse/OSSMDOC-262
Update productversion variable for 2.0.2 and 1.1.12 release. 

https://issues.redhat.com/browse/OSSMDOC-277
Update table items and typos in custom resources.

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]

**Comment by neal-timpe** [comment]
@luksa can you take a look and approve or give feedback? I made a couple of changes based on the docs issue you filed.

**Review by luksa — APPROVED** [review]

**Comment by neal-timpe** [comment]
@yxun or @gbaufake This should be a really quick check.

**Review by yxun — APPROVED** [review]

**Review by JStickler — APPROVED** [review]

**Pull request merged**
