### PR TITLE
Rebrand openshift.org and OpenShift Origin as okd.io and OKD

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@wgordon17 besides the one comment, the only other thing is to change OpenShift Origin in the _distro_map.yml .

**Comment by vikram-redhat** [comment]
@wgordon17 - Ah nvm my comment about _distro_map.yml. I see you had included it.

Would we need to do anything different with the existing redirects?

**Comment by wgordon17** [comment]
@vikram-redhat Fixed the 3.10. Redirects don't need to be touched, I've already added the new route, so this should be ready to go whenever you are! 👍

**Comment by vikram-redhat** [comment]
Great @wgordon17. I will merge.

**Pull request merged**
