### PR TITLE
BZ1852900 Added a GCP link to proc

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.5+
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=1852900
Doc Link: https://deploy-preview-30272--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-install-cli_installing-gcp-user-infra

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM.

The only feedback I have is that the manual recently changed to require an appropriate link to the rendered change in comment 0, so please include a link in future PRs.

**Comment by sagidlow** [comment]
@shellyyang1989

**Comment by shellyyang1989** [comment]
LGTM.

**Pull request merged**
