### PR TITLE
Missing type in visualization for install via GUI

### PR DESCRIPTION
**Pull request by ssonigra**
Version(s):
4.13 to 4.16

Issue:
https://issues.redhat.com/browse/OBSDOCS-1336

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by maxwelldb** [comment]
@shreyasiddhartha Does this apply beyond 4.16, too? If not, the PR should not target `main`.

**Review by jeana-redhat — COMMENTED** [review]
This LGTM but waiting to get version applicability confirmation (with #82328)

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by libander** [comment]
@jeana-redhat  - 4.13+ 
@ssonigra - thank you! 
/lgtm

**Comment by jeana-redhat** [comment]
@ssonigra this will need a manual cherrypick into the 4.13 branch of the docs.

**Comment by ssonigra** [comment]
Hello @jeana-redhat , is there any action needed from my side

**Comment by jeana-redhat** [comment]
> Hello @jeana-redhat , is there any action needed from my side

See comment on the related PR #82328 :)

**Pull request merged**
