### PR TITLE
[OCPBUGS#23731] Fix unmatched attributes set by conditional expressions 

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OCPBUGS-23731

Link to docs preview: https://68362--docspreview.netlify.app/

QE review: n/a
- [ ] QE has approved this change.

Additional information: Requires careful comparisons and teamwide notice.

I will open release-specific PRs for 4.12-4.14. All of these changes require review beyond what is typically needed for openshift-docs PRs. Ideally, a reviewer would compare master.xml files in proposed branches against target branches.

### CODE REVIEW

**Comment by maxwelldb** [comment]
Comparing master.xmls, I see changes in:
- installing
- operators
- post-installation-configuration

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.18` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.17. And any PR going into `main` must also target the latest version branch (enterprise-4.18).

If the update in your PR does NOT apply to version 4.18 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request closed without merging**
