### PR TITLE
BZ#1996994 Add prereq that MCPs must be running during update

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1996994

Added prereq to following assemblies:
- [Updating a cluster between minor versions](https://deploy-preview-35760--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-between-minor.html)
- [Updating a cluster within a minor version from the web console](https://deploy-preview-35760--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster.html)
- [Updating a cluster within a minor version by using the CLI
](https://deploy-preview-35760--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-cli.html)
- [Updating a restricted network cluster](https://deploy-preview-35760--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-restricted-network-cluster.html)

### CODE REVIEW

**Comment by codyhoag** [comment]
@yuqi-zhang can you confirm? Thanks!

**Comment by codyhoag** [comment]
@jiajliu can you verify from QE perspective? Thanks!

**Comment by jiajliu** [comment]
@codyhoag I noticed @jianlinliu had already reviewed it in https://bugzilla.redhat.com/show_bug.cgi?id=1996994#c3. So from QE side, it's ok to get it merged.

**Comment by mburke5678** [comment]
@codyhoag LGTM

**Pull request merged**
