### PR TITLE
OSDOCS-6435: Updated Gathering data about specific features module

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-6435](https://issues.redhat.com/browse/OSDOCS-6435)

Version(s):
4.14 through 4.10

Link to docs preview:
[Gathering data about specific features](https://61310--docspreview.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by sferich888 — COMMENTED** [review]
How does one determine the correct versions for these components?

**Comment by dfitzmau** [comment]
> How does one determine the correct versions for these components?

Thanks for the reply, @sferich888 . I do not know. I would need a software engineer to inform me on how a user could determine the version. Maintaining version numbered causes outdated documents, more maintenance with up versioning for every release, and incorrect component versions transferring to later OCP releases.

Would you know of a software engineer that could chime in on how the versions could be sought?

**Review by soltysh — APPROVED** [review]
The proposed changes look good to me

**Comment by soltysh** [comment]
> How does one determine the correct versions for these components?

Maybe it would be reasonable to either point to https://docs.openshift.com/container-platform/4.13/storage/persistent_storage/persistent-storage-ocs.html which leads to [Red Hat OpenShift Data Foundation Supportability and Interoperability Guide](https://access.redhat.com/articles/4731161) to inform users about where and how to match the correct version. That should be sufficient and generic enough.

**Comment by soltysh** [comment]
Also, we'd need similar docs for each of the components, most likely.

**Comment by dfitzmau** [comment]
> How does one determine the correct versions for these components?

Hi @sferich888 . I've included a link to the OCP Support Policy page to give a user a place where they can determine the version of an OCP component or even get acquainted with support-related info to do with that component.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by jab-rh** [comment]
@dfitzmau, LGTM, thanks!

**Comment by jab-rh** [comment]
@dfitzmau, it looks like this doesn't merge cleanly for 4.10, 4.11, and 4.12. Might need adjustments?

**Pull request merged**
