### PR TITLE
OCPBUGS43801: CMA fix spacing in secret example

### PR DESCRIPTION
**Pull request by mburke5678**
Per [Slack conversation](https://redhat-internal.slack.com/archives/C02F1J9UJJD/p1729760931747139).

https://issues.redhat.com/browse/OCPBUGS-43801

Preview: [Configuring the custom metrics autoscaler to use OpenShift Container Platform monitoring](https://84099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/cma/nodes-cma-autoscaling-custom-trigger.html#nodes-cma-autoscaling-custom-prometheus-config_nodes-cma-autoscaling-custom-trigger) -> Fixed formatting in Step 2b code example. [Current docs](https://docs.openshift.com/container-platform/4.17/nodes/cma/nodes-cma-autoscaling-custom-trigger.html#nodes-cma-autoscaling-custom-prometheus-config_nodes-cma-autoscaling-custom-trigger).

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@ShudiLi Is this an issue you can review? You [reviewed this material previously](https://github.com/openshift/openshift-docs/pull/78467/files#diff-5b0981a1b66b58b9f7f05e5c821abb40dd2c10a4c2d48e83ddf5e09db34224ac).

**Comment by ShudiLi** [comment]
/lgtm
thanks

**Review by max-cx — APPROVED** [review]
LGTM

**Pull request merged**
