### PR TITLE
Issue 63319: fixed unsubstituted variable

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12+

Issue:
https://github.com/openshift/openshift-docs/issues/63319

Link to docs preview:
[About specialized hardware and driver enablement](https://63475--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/about-hardware-enablement.html)

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM! Please wait until @adellape approves my review before proceeding, thanks.

**Review by adellape — APPROVED** [review]
@skopacz1 @sheriff-rh 👍

**Comment by sheriff-rh** [comment]
Thanks all! Merging.

**Comment by skopacz1** [comment]
I'm a little late to the party with the label updates, but oh well lol

**Pull request merged**
