### PR TITLE
New collapsible js functionality and collapsing UPI templates

### PR DESCRIPTION
**Pull request by lbarbeevargas**
New `collapsible.js` file that allows writers to collapse content by adding `[%collapsible]` in asciidoctor.

The initial feature is applied to the ARM templates in the `installing/installing_azure/installing-azure-user-infra.adoc` assembly.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
Collapsed ALL UPI templates.
Preview available here - http://file.bos.redhat.com/lbarbeev/10202020/welcome
Preview example - http://file.bos.redhat.com/lbarbeev/10202020/collapsible-js-and-azure-upi-template/installing/installing_azure/installing-azure-user-infra.html#installation-arm-vnet_installing-azure-user-infra

**Comment by codyhoag** [comment]
Looks like the collapsible logic works as expected with the auto-included templates. :tada:

These look good from my perspective!

**Comment by vikram-redhat** [comment]
As discussed - update the guidelines to show example of using this and a separate PR to CP to 4.1 branch the javascript changes.

**Comment by vikram-redhat** [comment]
> Looks like the collapsible logic works as expected with the auto-included templates. 🎉
> 
> These look good from my perspective!

I wanted to comment that this brings together 3 improvements to docs.openshift.com in one place :D 

Copy code, collapsible code blocks, and auto-included templates.

**Comment by codyhoag** [comment]
>I wanted to comment that this brings together 3 improvements to docs.openshift.com in one place :D
>
>Copy code, collapsible code blocks, and auto-included templates.

All my OCP dreams are coming true! :tada: :smile:

**Pull request merged**
