### PR TITLE
[OSDOCS-5327]: Release note for updating hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-5327

Link to docs preview: https://58554--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-hosted-control-planes-updates

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jiezhao47** [comment]
lgtm

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
Looks great!

**Pull request merged**
