### PR TITLE
(WIP) RN CNV-5439 Auto renew SSL certs

### PR DESCRIPTION
**Pull request by lmandavi**
Initial draft for release note write-up on auto renewal of SSL certificates for CNV.

### CODE REVIEW

**Comment by lmandavi** [comment]
@stu-gott - Please advise any additional info we should be mentioning in the rel notes.

**Review by stu-gott — COMMENTED** [review]
looks good!

**Comment by lmandavi** [comment]
@stu-gott @rmohr -  This PR is for the write-up that will go into the 2.4 release notes. It is short because write-ups that go into the release notes are short  Please review the content and add your comments. If the write-up looks good and you don't have any changes, please add LGTM label to the PR. Then, I will move the PR into peer review stage. Thanks!

**Comment by lmandavi** [comment]
Requesting peer review and merge.

**Comment by ousleyp** [comment]
The text lgtm, but you need to resolve the merge conflict and squash your commits before we can merge this.

**Comment by lmandavi** [comment]
@ousleyp I will be deleting this PR. It is outdated and you can ignore this PR. There is currently a new PR in place in lieu of this PR: https://github.com/openshift/openshift-docs/pull/23417 - that PR is the active PR.

**Pull request closed without merging**
