### PR TITLE
BZ-2008984: Clarifying that 0 priority is the highest

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=2008984

Preview: https://deploy-preview-39177--osdocs.netlify.app/openshift-enterprise/latest/authentication/managing-security-context-constraints#scc-prioritization_configuring-internal-oauth

### CODE REVIEW

**Review by skrthomas — APPROVED** [review]
Looks great :) LGTM!

**Comment by bergerhoffer** [comment]
@stlaz @xingxingxia can you please review these clarifications to make sure that they're accurate? Thanks!

Preview: https://deploy-preview-39177--osdocs.netlify.app/openshift-enterprise/latest/authentication/managing-security-context-constraints#scc-prioritization_configuring-internal-oauth

**Comment by xingxingxia** [comment]
No, nil and 0 are lowest, see proof:
```
Prepare too same YAML SCCs:
$ oc get scc restricted -o yaml > exported-restricted-scc.yaml
$ cp exported-restricted-scc.yaml restricted-scc-copy-1.yaml
$ cp exported-restricted-scc.yaml restricted-scc-copy-2.yaml
$ sed -i "s/name: restricted/name: restricted-copy-1/" restricted-scc-copy-1.yaml
$ sed -i "s/name: restricted/name: restricted-copy-2/" restricted-scc-copy-2.yaml
$ oc create -f restricted-scc-copy-1.yaml -f restricted-scc-copy-2.yaml

Make restricted-copy-1 with p 0 and restricted-copy-2 of p 10:
$ oc patch scc restricted-copy-1 --type=merge -p='{"priority": 0}'
$ oc patch scc restricted-copy-2 --type=merge -p='{"priority": 10}'
$ oc get scc -o=custom-columns='NAME:.metadata.name,PRIORITY:.priority' | grep -e NAME -e restricted 
NAME                              PRIORITY
restricted                        <nil>
restricted-copy-1                 0
restricted-copy-2                 10

Above 3 SCCs are the determined set of SCCs that can be all used by normal user's normal pod.
Login with normal user creating pod:
$ oc login -u testuser-18 -p ...
$ oc new-project xxia-test
$ oc run testpod --image=quay.io/openshifttest/hello-openshift:openshift

Check which SCC is chosen:
$ oc run testpod --image=quay.io/openshifttest/hello-openshift:openshift
pod/testpod created
$ oc get po -o yaml | grep scc
      openshift.io/scc: restricted-copy-2
^^ It selects "restricted-copy-2" of p 10, instead of 'restricted' of nil p and "restricted-copy-1" with p 0.
```
CC @y4sht (you can give a read ack after getting the feature about SCC 'priority' and how above test steps are crafted)

**Comment by xingxingxia** [comment]
Moving bug back to ASSIGNED.

**Comment by y4sht** [comment]
@bergerhoffer As the admission control section already mentions
```The set of SCCs that admission uses to authorize a pod are determined by the user identity and groups that the user belongs to. Additionally, if the pod specifies a service account, the set of allowable SCCs includes any constraints accessible to the service account.```

If we create a resource using a `kind: Pod` manifest, then we can either use <username> or <serviceaccount> to grant the scc
But if we use any other resource eg: `kind: Deployment` we need to grant the scc to the serviceaccount, granting it to the username will not work.

Can we integrate this into the current PR?

**Comment by stlaz** [comment]
/hold
it's the other way around

**Comment by bergerhoffer** [comment]
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request closed without merging**
