### PR TITLE
OSDOCS-11484: Fix CMPS YAML for capacity res

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.16+

Issue:
[OSDOCS-11484](https://issues.redhat.com//browse/OSDOCS-11484)

Link to docs preview:

- [Compute](https://79638--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-azure-capacity-reservation_creating-machineset-azure)
- [Control plane](https://79638--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure.html#machineset-azure-capacity-reservation_cpmso-config-options-azure)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@sunzhaohua2 PTAL at this fix

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
