### PR TITLE
OSSM-6969: Update path for YAML examples

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Affects:

[service-mesh-docs-main](https://github.com/openshift/openshift-docs/tree/service-mesh-docs-main)
[service-mesh-docs-3.0.0tp1](https://github.com/openshift/openshift-docs/tree/service-mesh-docs-3.0.0tp1)

This PR is part of the standalone doc set for the Service Mesh 3.0 project. Kathryn is aware that this content applies for a product that is part of a Technology Preview release. The project is seeking feedback from early adopters.

PR must be CP'd back to the tp1 branch.

Issue: https://issues.redhat.com/browse/OSSM-6969

Link to docs preview:
https://80646--ocpdocs-pr.netlify.app/openshift-service-mesh/latest/install/ossm-installing-openshift-service-mesh.html#deploying-book-info

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Review by FilipB — APPROVED** [review]

**Review by jneczypor — COMMENTED** [review]
LGTM.
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Pull request merged**
