### PR TITLE
Restructured v3 content as per discussion with the team

### PR DESCRIPTION
**Pull request by Bilhar-rh**
@nhr @adellape Here's the content restructure as per the whole discussion. I finished it pretty fast so probably a good idea to do a sanity check, but there will be further tweaks so we can address any issues at that time as well. If all looks good please merge.

@nhr For some reason the system seems to have reverted back to not using the topic title in the topic itself. It's instead still using the title from the _build_cfg.yml file. I know we fixed this, but it's not working now for some reason. Can you please verify?

### CODE REVIEW

**Comment by nhr** [comment]
The master branch contains the correct article title logic:

https://github.com/openshift/openshift-docs/blob/master/_builder_lib/docsitebuilder/helpers.rb#L622-L626

and

https://github.com/openshift/openshift-docs/blob/master/_templates/page.html.erb#L62

So as long as you start the build from the master branch, article titles will be generated correctly.

**Comment by nhr** [comment]
This is where I eat my hat because https://github.com/openshift/openshift-docs/blob/master/_builder_lib/docsitebuilder/helpers.rb#L624 is exactly wrong. Fix forthcoming.

**Comment by nhr** [comment]
PR to fix title detection: https://github.com/openshift/openshift-docs/pull/303

**Comment by adellape** [comment]
Overall the PR looks good to me.

**Comment by CowboysFan** [comment]
@adellape Thanks, merged it!

**Comment by ryanj** [comment]
This change broke a lot of URLs: https://github.com/openshift/openshift-docs/issues/309

is the plan to fix documentation urls later? I keep hitting an ugly 404 page

**Comment by CowboysFan** [comment]
@ryanj Yes, we will definitely fix the links. We'll fix the links as the writers work on their respective topics, and that will also be one of the tasks for the final pass through all the content. Apologies for any inconvenience.

**Pull request merged**
