### PR TITLE
BZ-1770132: Fixing URL

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@cuppett Can you make sure that this change (requested by this BZ [1]) is appropriate? Preview here [2] in step 5. Thanks!

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1770132
[2] https://bz-1770132--ocpdocs.netlify.com/openshift-enterprise/latest/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

**Comment by cuppett** [comment]
> @cuppett Can you make sure that this change (requested by this BZ [1]) is appropriate? Preview here [2] in step 5. Thanks!
> 
> [1] https://bugzilla.redhat.com/show_bug.cgi?id=1770132
> [2] https://bz-1770132--ocpdocs.netlify.com/openshift-enterprise/latest/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

LGTM!

**Comment by bergerhoffer** [comment]
HI @jianlinliu - are you the right person to verify this update?

If so, the BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1770132. Thanks!

**Comment by jianlinliu** [comment]
LGTM.

**Pull request merged**
