### PR TITLE
FIX:1646038 and 1649701:Change the htpasswd file path under /etc/origin/master

### PR DESCRIPTION
**Pull request by bysnupy**
* Fix:
   - [htpasswd can not be placed at /etc/origin/ but only /etc/origin/master](https://bugzilla.redhat.com/show_bug.cgi?id=1646038)
   - [Configure Identity provider htpasswd](https://bugzilla.redhat.com/show_bug.cgi?id=1649701) 

* Version: `v3.10` and `v3.11+`

* Description:
  Refer the BZ summary first.

Change the `htpasswd` file path under `/etc/origin/master` directory for accessing by `master api/controllers` pods
And I would change the `/etc/origin/master/htpasswd` instead of `openshift-passwd` because the htpasswd file path is static in the playbooks as follows, [https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_control_plane/tasks/htpass_provider.yml#L13-L16]
~~~
- name: Create the htpasswd file if needed
  template:
    dest: "/etc/origin/master/htpasswd"
    src: htpasswd.j2
~~~

### CODE REVIEW

**Comment by bysnupy** [comment]
@kalexand-rh this PR has not assigned a reviewer, is there some reason ?

**Comment by kalexand-rh** [comment]
@bysnupy, because I wasn't sure who should take it.

@stuartchuan, will you PTAL?

**Comment by stuartchuan** [comment]
@kalexand-rh the changes are lgtm.

**Pull request merged**
