### PR TITLE
An egress router pod macvlan is created by cluster

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/36979

Preview: [Egress router pod specification for redirect mode](https://deploy-preview-37407--osdocs.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/deploying-egress-router-layer3-redirection.html#nw-egress-router-pod_deploying-egress-router-layer3-redirection)
Preview: [Egress router pod specification for HTTP mode](https://deploy-preview-37407--osdocs.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/deploying-egress-router-http-redirection.html#nw-egress-router-pod_deploying-egress-router-http-redirection)

### CODE REVIEW

**Comment by jboxman** [comment]
@danwinship, I've updated the description, with apologies for expanding the _NIC_ acronym. It's a convention we generally follow in OCP docs, even if it's superfluous for most users.

**Review by ctauchen — COMMENTED** [review]
This is clearer -- thanks. A few comments, otherwise 
/lgtm

**Comment by jboxman** [comment]
@ctauchen, thanks!

@danwinship, lol

**Pull request merged**
