### PR TITLE
Bug 2026192, noted new limitation of OVN environment

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=2026192

Preview build: http://file.rdu.redhat.com/~ahardin/Mar-11-2022/BZ-2026192/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html#nw-ovn-kubernetes-limitations_about-ovn-kubernetes

### CODE REVIEW

**Comment by bpickard22** [comment]
@ahardin-rh this is correct, session affinity timeout seconds are not supported in ovn

**Comment by anuragthehatter** [comment]
nu surprises. Thanks

/lgtm

**Pull request merged**
