### PR TITLE
Added Cluster Loader deprecation notice

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview build: https://deploy-preview-32703--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-deprecated-features

https://issues.redhat.com/browse/PERFSCALE-1037
https://issues.redhat.com/browse/OSDOCS-2141

Related to https://github.com/openshift/openshift-docs/pull/32034

This will be released in 4,8 and backported to earlier versions

### CODE REVIEW

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
@mffiedler PTAL

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Review by mffiedler — APPROVED** [review]
LGTM

**Pull request merged**
