### PR TITLE
Updating versions to 4.10 instead of 4.9

### PR DESCRIPTION
**Pull request by bergerhoffer**
Followup to #44319, to fix 4.9 versions to 4.10.

Version(s):
4.9, 4.10, 4.11

Issue:

Link to docs preview:
https://deploy-preview-45260--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-user-infra-machines-iso_installing-platform-agnostic

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@pamoedom @hector-vido Just like the 4.8 one (comment here https://github.com/openshift/openshift-docs/pull/45259#issuecomment-1115313160)

I'm attempting to fix the versions so that 4.9-specific output is changed to 4.10. Please let me know if these changes are sufficient, or if we need to generate new/better output for 4.10.

**Comment by hector-vido** [comment]
> This is the same comment that I wrote in the other PR

Hi guys, is this a problem? I though it was just an example and not the real address, trying to inform the readers about the openshift-install coreos print-stream-json.
Because if we change, we need to change for 4.8, 4.9, 4.10, 4.11 ... and so son.
Another option is remove the versions and use a "template like" output... something like:

```
./openshift-install coreos print-stream-json | grep '\.iso[^.]'
    "location": "https://<url>/rhcos-4.8-aarch64/<file>-live.aarch64.iso",
```

Best,

**Comment by bergerhoffer** [comment]
@pamoedom I took @hector-vido's suggestion to make the output more generic, if we can't just replace the version numbers. Because going forward in the future, that's all we will do (bump versions) - writers won't come back and run commands to get the correct output.

I used <url> and <release> as replacement/placeholder values. Can you please take a look and see if this works for you?

I've adjusted the 4.8 PR to do the same: https://github.com/openshift/openshift-docs/pull/45259/files

**Comment by pamoedom** [comment]
Thanks @bergerhoffer , LGTM
/label qe-approved

**Comment by bergerhoffer** [comment]
Will CP this back to 4.9 as well, since we are using the generic example outputs.

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
