### PR TITLE
Add cluster metrics docs

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by adellape** [comment]
@jimmidyson Would you say this is the closest related dev card for this? https://trello.com/c/ByONdF8m Or is there another one(s)?

Also, it looks like this might be something that should only show up in the Origin docs for now (at least in the current instructions' state), and not Enterprise yet?

**Comment by jimmidyson** [comment]
@adellape Yeah that card is the closest. This is the first step in documenting & enhancing heapster although it is usable in its current state.

This is fine to include only for origin for now, but I would like to see it in enterprise as it improves. You mention the current instructions state - what's necessary to improve thus to enterprise docs standards?

**Comment by adellape** [comment]
@jimmidyson I meant more from the product itself's side, not docs standards. Will follow up, thanks!

**Comment by jimmidyson** [comment]
Ah OK! I'm not sure tbh.

**Comment by adellape** [comment]
Merging, and will follow up to conditionalize it out of the OSE build for now.

**Pull request merged**
