### PR TITLE
Added openshift_hosted_router details

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1620117

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@knobunc @sdodson PTAL

**Review by sdodson — CHANGES_REQUESTED** [review]
This looks like it'd provision two routers into the same namespace running on the same ports. wouldn't we need to do something to insure that they're running in different namespaces and on different hosts if they're using the same ports?

Needs review from @openshift/sig-network-edge

**Comment by Miciah** [comment]
The routers should be fine running in the same namespace, and the example specifies two distinct node selectors (`'selector': 'type=router1'` and `'selector': 'type=router2'`), so the routers should be scheduled on different hosts.

**Review by sdodson — APPROVED** [review]
Based upon Miciah's feedback, lgtm

**Comment by ahardin-rh** [comment]
QE approval received in the BZ. Fixed minor formatting issue in the in the parameter example.

**Pull request merged**
