### PR TITLE
OSDOCS-2617: clarify credentials rotation for Azure

### PR DESCRIPTION
**Pull request by jeana-redhat**
Addressing https://issues.redhat.com/browse/OSDOCS-2617 for 4.7+

Preview: https://deploy-preview-36093--osdocs.netlify.app/openshift-enterprise/latest/authentication/managing_cloud_provider_credentials/cco-mode-mint.html#manually-rotating-cloud-creds_cco-mode-mint

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
:+1:

**Comment by jeana-redhat** [comment]
Hi @lwan-wanglin - can you PTAL at this addition to address the Azure service principal issue?

**Comment by lwan-wanglin** [comment]
@jeana-redhat LGTM! :+1:

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
