### PR TITLE
ocpbugs#22215: Updated AMI to match us-west-2 region

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.14+

Issue:
This PR addresses [ocpbugs-22215](https://issues.redhat.com/browse/OCPBUGS-22215).

Link to docs preview:

Installing a private cluster on AWS > [Sample customized install-config.yaml file for AWS](https://67412--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-private#installation-aws-config-yaml_installing-aws-private)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
Closing/reopening to kick start Travis.

**Comment by mjpytlak** [comment]
@yunjiang29 Ready for QE review. PTAL.

**Review by abrennan89 — APPROVED** [review]
/lgtm

**Pull request merged**
