### PR TITLE
Removed old upgrade guide

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Removed the page at https://docs.openshift.com/acs/upgrading/upgrading_roxctl/upgrade-from-40-43.html

- This topic is for older versions which no ones uses.

### CODE REVIEW

**Comment by mburke5678** [comment]
@gaurav-nelson LGTM Does this change need to go through [change management](https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#heading=h.nckpao8upx1u)?

**Comment by IAmATeaPot418** [comment]
No it does not. This is the removal of an upgrade from a version that hasn't been supported for over 3 months. This version is no longer supported.

**Comment by mburke5678** [comment]
@vikram-redhat Is change management required, given the info provided by @IAmATeaPot418 information? Just wanted to make sure.

**Comment by vikram-redhat** [comment]
At the moment, we are not doing change management for ACS docs. However, once things settle, we will.

**Pull request merged**
