### PR TITLE
Github-47714 adding setup steps for Zsh completion 

### PR DESCRIPTION
**Pull request by waljaber**
Expanded the oc completion page to include the steps to setup shell completion for both Bash, and Zsh.

Version(s):

Issue:
#47714 

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@bergerhoffer @opayne1, will one of you PTAL?

**Comment by bergerhoffer** [comment]
@waljaber Thanks a lot for submitting this! Since these are separate procedure for the different shells, we have to break them out into different module files. I took your commit and made the necessary adjustments, and opened #48289 with the new changes. Can you please take a look at that PR and see if it looks okay to you?

Closing this PR in favor of #48289

**Comment by waljaber** [comment]
@bergerhoffer thank you so much for taking the time to review this PR. I agree with you that it would be better if it was split into a different page, one for each shell type. 
I took a look at the new pull request, and it looks great!

**Comment by bergerhoffer** [comment]
@waljaber Glad to hear it, thanks for reviewing it! Once it passes QE review, we will get it merged in :slightly_smiling_face:

**Pull request closed without merging**
