### PR TITLE
[WIP] RHDEVDOCS-5553: Document removal of deprecated .spec.resourceCustomiz…

### PR DESCRIPTION
**Pull request by eromanova97**
**For GitOps version 1.10**
Please **DO NOT** merge this issue. The intention is to keep the **PRs merge ready with all approvals**. The PR merging can happen only on the GA date (September 26th). So please hold off merging until I let you know. thank you!

• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.12 and later
• **JIRA issue**: [RHDEVDOCS-5553](https://issues.redhat.com/browse/RHDEVDOCS-5553)
• **Preview page**:  [Argo CD custom resource properties](https://63663--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/argo-cd-custom-resource-properties#argo-cd-properties_argo-cd-custom-resource-properties)
• **SME Review**: Completed by @svghadi 
• **QE review**: Completed by @varshab1210
• **Peer-review**: Completed by @abrennan89

### CODE REVIEW

**Comment by ekristova** [comment]
Hello @varshab1210 PTAL at this PR and provide feedback. Thank you!

**Review by svghadi — APPROVED** [review]
/lgtm
Thank You @ekristova

**Comment by varshab1210** [comment]
LGTM, thanks

**Review by abrennan89 — APPROVED** [review]
lgtm!

**Comment by ekristova** [comment]
Please **DO NOT** merge this issue. The intention is to keep the **PRs merge ready with all approvals**. The PR merging can happen only on the GA date (September 26th). So please hold off merging until I let you know. thank you!

**Comment by mburke5678** [comment]
merge review LGTM

**Pull request merged**
