### PR TITLE
[RHDEVDOCS-5161]: Move Kafka sink docs and create new section

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/RHDEVDOCS-5161

Link to docs preview:
- https://58532--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/event-sinks/serverless-creating-sinks.html
- https://58532--docspreview.netlify.app/openshift-enterprise/latest/serverless/eventing/event-sinks/serverless-kafka-developer-sink.html

QE review:
- [x] QE approved

### CODE REVIEW

**Review by gabriel-rh — APPROVED** [review]
/LGTM

**Comment by mgencur** [comment]
LGTM from QE

**Pull request merged**
