### PR TITLE
OSDOCS-7506 updated TechPreviewNoUpgrade feature sets for 4.14

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-7506

Link to docs preview (VPN required):
[Understanding feature gates](https://file.rdu.redhat.com/antaylor/OSDOCS-7506/nodes/clusters/nodes-cluster-enabling-features.html#nodes-cluster-enabling-features-about_nodes-cluster-enabling)

QE review:
- [ ] QE has approved this change.

Additional information:
None

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@nee1esh @tkatarki @sunilcio  Please review when you have a chance, thanks!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
