### PR TITLE
OCPBUGS2294: Add HPA and VPA to the unsupported list in WINC release notes

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OCPBUGS-2294

### CODE REVIEW

**Comment by mburke5678** [comment]
@aravindhp PTAL

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
@rrasouli @jfrancoa PTAL

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Comment by tmalove** [comment]
@mburke5678 Because this is a release note entry, this should be in the 'enterprise-412' branch instead of 'main', yes? Also, the Build preview shows the stub in the Release note section, because this was updated in 'main'.

**Comment by mburke5678** [comment]
@tmalove That is a good thought about the base branch. However, this module is used in multiple OCP versions and needs to be in `main`. 
Sorry about the preview. This should work:
http://file.rdu.redhat.com/~mburke/winc-add-hpa-vpa-limitation/windows_containers/windows-containers-release-notes-6-x.html#windows-containers-release-notes-limitations_windows-containers-release-notes

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Pull request merged**
