### PR TITLE
Adding entries for the new OOTB default policy for drop all caps

### PR DESCRIPTION
**Pull request by kcarmichael08**
Taken over from https://github.com/openshift/openshift-docs/pull/63501
Version(s):

- Merge to `rhacs-docs`
- Cherry pick to `rhacs-docs-4.2`

[Issue](https://issues.redhat.com/browse/ROX-18083)

Link to docs preview:
- https://63553--docspreview.netlify.app/openshift-acs/latest/operating/default-security-policies#low-sev-security-policies_default-security-policies

QE review:
- [x] QE has approved this change. (SME approved, ACS has no QE)

Additional information:

- Removed unused, outdated module that was discovered when working on this PR.
- Will go out in patch release 4.1.3 also, probably week of 8/21, so will do a manual CP at that time to `rhacs-docs-4.1`.

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@kcarmichael08 This LGTM, but I wonder if the source PR needs to be closed?

**Comment by ousleyp** [comment]
LGTM!

**Pull request merged**
