### PR TITLE
Remove items that are already GA

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.17+

Issue: No Jira

Link to docs preview: https://84674--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hosted-control-planes-release-notes.html#hcp-4-17-new-features-and-enhancements_hosted-control-planes-release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jparrill — COMMENTED** [review]
/lgtm

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM.

**Pull request merged**
