### PR TITLE
Bug 1291594, added warning admonition

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1291594

New PR after closing https://github.com/openshift/openshift-docs/pull/1460 

@nak3 , @adellape I made a small edit since last review. Please let me know if this is okay.

### CODE REVIEW

**Comment by nak3** [comment]
LGTM

**Comment by adellape** [comment]
@ahardin-rh LGTM. You may consider adding a short line explaining why, like "Otherwise, containers managed by OpenShift may fail to resolve host names properly."

**Comment by ahardin-rh** [comment]
@adellape good idea. I added that line in.

**Comment by adellape** [comment]
:+1:

**Pull request merged**
