### PR TITLE
Bug 1376923,cpu and requests.cpu are the same value;memory and requests.memory are the same value

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1376923

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@erjones PTAL

@adellape please peer review. Thanks!

**Comment by TheDiemer** [comment]
@ahardin-rh LGTM, Pretty simple change, thanks!

**Comment by adellape** [comment]
:+1:

**Review by adellape — APPROVED** [review]

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/quota.adoc#admin-guide-quota[Setting Quotas]
|Added that `*cpu*` and `*requests.cpu*` are the same value and can be used interchangeably, as with `*memory*` and `*requests.memory*`.
%

**Pull request merged**
