### PR TITLE
RHDEVDOCS-5371: Correct the namespace in Pipelines as Code chapter

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.11 and later
• **JIRA issue**: [RHDEVDOCS-5371](https://issues.redhat.com/browse/RHDEVDOCS-5371)
• **Preview page**: [Using Pipelines as Code](https://61080--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-pipelines-as-code.html)
• **SME Review**: Completed by @vdemeester 
• **QE review**: Completed by @VeereshAradhya 
• **Peer-review**: Completed by @Srivaralakshmi

### CODE REVIEW

**Review by VeereshAradhya — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Review by Srivaralakshmi — APPROVED** [review]
@ekristova Nice work! Approved!

**Pull request merged**
