### PR TITLE
Mention SDN cluster networking config variables

### PR DESCRIPTION
**Pull request by sdodson**
My attempt at documenting advanced configuration for cluster network. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1259737

### CODE REVIEW

**Comment by adellape** [comment]
@sdodson Looks like some accidental double-pasting in both of the `link:`s, but other than that LGTM.

**Comment by adellape** [comment]
Also, current assumption is that this can apply for the OSE 3.0 docs as well.

**Comment by sdodson** [comment]
Thanks, should be fixed.

**Comment by adellape** [comment]
:+1:

**Pull request merged**
