### PR TITLE
[OSDOCS-6083]-Remove reference to "AWS site reliability engineering (SRE)" in ROSA Docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-6083
Link to docs preview:

http://file.rdu.redhat.com/mletalie/OSDOCS-6083/rosa_architecture/rosa-understanding.html
QE review:
- [ ] QE has approved this change.

**Note: QE review not needed IMO**
Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
image

**Comment by mletalie** [comment]
Hello @arendej,
   When you get a chance, could you please review this doc change? Thanks, ML

**Comment by bchandra-ocp** [comment]
Perhaps is it OK to say "AWS and Red Hat Site reliability engineering (SRE) experts manage the underlying platform so you do not have to worry about the complexity of infrastructure management. "
instead of 
"Red Hat and AWS Site reliability engineering (SRE) experts manage the underlying platform so you do not have to worry about the complexity of infrastructure management." ? 

I'm thinking the underlying platform and infrastructure management can span physical things too which are managed by AWS.

**Comment by mletalie** [comment]
> Perhaps is it OK to say "AWS and Red Hat Site reliability engineering (SRE) experts manage the underlying platform so you do not have to worry about the complexity of infrastructure management. " instead of "Red Hat and AWS Site reliability engineering (SRE) experts manage the underlying platform so you do not have to worry about the complexity of infrastructure management." ?
> 
> I'm thinking the underlying platform and infrastructure management can span physical things too which are managed by AWS.

Good point, @bchandra-ocp. I will re-write and get feedback from AWS as well. Thanks.

**Comment by mletalie** [comment]
Hello @bchandra-ocp, I did reach out to our contact at AWS and sent him your suggestion. He stated "This still makes it seem like AWS has personnel managing the ROSA platform, which is not the case. Removing AWS from that sentence would be the most accurate. " I then showed him what I had originally suggested and he was good with that. Are you okay with moving forward with the original suggestion? Please let me know, thx!

**Comment by bchandra-ocp** [comment]
Thanks @mletalie for giving it a consideration. 

I'm fine with removing AWS from that sentence however I'm bit concerned with the reference to 'underlying platform'. What are you thoughts on that w.r.t the responsibility matrix laid out here - https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html? 

My understanding is:

1. We want to mention that RH SREs manage the openshift platform
2. We want to highlight the value of managing complex infrastructure. 
3. However, there are pieces of underlying platform that are managed by AWS and that are responsibility of customer.  
4. per AWS, we must not indicate that AWS personnel are managing the OpenShift platform or its architecture. 

Would it be easier if we reference to above matrix or paraphrase this comprehensive table?

**Comment by mletalie** [comment]
Hello @bchandra-ocp,
  Funny that you should mention that; I have been working on this ticket which is updating the responsibility matrix in a big way: https://issues.redhat.com/browse/OSDOCS-5467; here is the  updated matrix so far: http://file.rdu.redhat.com/mletalie/OSDOCS-5467/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-security-regulation-compliance_rosa-policy-responsibility-matrix. This is being driven by AWS, although we will need to get approval on our side.

**Pull request merged**
