### PR TITLE
[GH#41971] include syslog inputs

### LINKED ISSUE #41971: [enterprise-4.8] Issue in file logging/cluster-logging-external.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-syslog_cluster-logging-external
Syslog section doesn't have `inputs` reference, therefore it's not obvious if it can be used with Syslog forwarder. 
image

### What needs fixing?
Add input and number reference to YAML example for syslog forwarder.
image

### PR DESCRIPTION
**Pull request by pfeifferj**
Version(s):

`enterprise-{4.8, 4.9, 4.10, 4.11, 4.12, 4.13}`

Issue:

fixes #41971 

Link to docs preview:

[Forwarding logs using the syslog protocol](https://57043--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-syslog_cluster-logging-external)

QE review:
- [ ] QE has approved this change.

Additional information:

Followed same convention as [Sample log forwarding outputs and pipelines](https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#cluster-logging-collector-log-forwarding-about_cluster-logging-external)

### CODE REVIEW

**Comment by pfeifferj** [comment]
cf. https://github.com/openshift/openshift-docs/pull/56292

**Comment by libander** [comment]
@pfeifferj - Please squash your commits to merge.

**Comment by pfeifferj** [comment]
squashing broke the PR again. fixed here: https://github.com/openshift/openshift-docs/pull/57131

**Pull request closed without merging**
