### PR TITLE
NSX-T SDN Documentation update

### PR DESCRIPTION
**Pull request by mburke5678**
Backstory:
https://github.com/openshift/openshift-docs/pull/14695 seems to be a duplicate of  https://github.com/openshift/openshift-docs/pull/14649 which was added to OpenShift docs via PR https://github.com/openshift/openshift-docs/pull/14709.

However, I see two changes in https://github.com/openshift/openshift-docs/pull/14695 that need to be applied to the OpenShift docs.

### CODE REVIEW

**Comment by mburke5678** [comment]
@RobbieJVMW PTAL

**Comment by mburke5678** [comment]
@RobbieJVMW is this link to the Release Notes the correct document for _additional configuration and options_?

_For additional configuration and options please refer to the link:https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.4/rn/NSX-Container-Plugin-Release-Notes.html[VMware NSX-T v2.4 OpenShift Plug-In] documentation._

**Comment by kalexand-rh** [comment]
@dav1x, will you PTAL?

**Comment by dav1x** [comment]
@mburke5678 @kalexand-rh 

The link is correct:

https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.4/rn/NSX-Container-Plugin-Release-Notes.html

**Comment by kalexand-rh** [comment]
Thank you @dav1x! @mburke5678, thank you for catching this! I'm going to merge and force a 3.11 build.

**Pull request merged**
