### PR TITLE
add additional cluster egress IPs to ROSA identity based policy

### PR DESCRIPTION
**Pull request by maorfr**
part of https://issues.redhat.com/browse/SDE-3707

this PR adds the egress IPs of 2 clusters on which we are going to run Red Hat workloads that reach out to customer infrastructure. each 3 additional lines are placed under the 3 lines that are the egress IPs of where these services are running today.

a matching PR is submitted here as well: https://gitlab.cee.redhat.com/service/sre-platform-rhcontrol-terraform/-/merge_requests/11

docs preview: https://71018--ocpdocs-pr.netlify.app/openshift-rosa/latest/security/rosa-adding-additional-constraints-for-ip-based-aws-role-assumption

### CODE REVIEW

**Comment by nalhadef** [comment]
Hi, @maorfr .

The review link goes to the top level of the documentation. Please as a link directly to the new content. Thanks!

I'm putting the peer review needed label back on so the PR goes to the list.

**Comment by maorfr** [comment]
added the link to the description. here it is as well: https://71018--ocpdocs-pr.netlify.app/openshift-rosa/latest/security/rosa-adding-additional-constraints-for-ip-based-aws-role-assumption

**Comment by nalhadef** [comment]
Thanks, Maor. I've grabbed the PR.

**Pull request closed without merging**
