### PR TITLE
replace EAP_HOME with JBOSS_HOME

### PR DESCRIPTION
**Pull request by bdecoste**

### CODE REVIEW

**Comment by adellape** [comment]
@bdecoste :+1: on the S2I fixes. For the s/EAP_HOME/JBOSS_HOME/, is that fixing a bug in the docs for the existing images, or is the change only applicable for an upcoming/newer EAP image?

**Comment by bdecoste** [comment]
EAP_HOME is a bug in the docs. It's not EAP_HOME in the current and isn't in the new. It's always been JBOSS_HOME.

**Comment by adellape** [comment]
@bdecoste Cool, I see that now. Thanks! Merging.

**Comment by bdecoste** [comment]
Thanks. My first doc commit :-)

**Comment by adellape** [comment]
:tada:

**Comment by lucascosti** [comment]
Hey guys,

I can't speak for AMQ, but the term EAP_HOME is used in the EAP docs to refer to the EAP installation directory. I think that using a different term for the xPaaS docs will create confusion for users switching between the different docs sets.

(Note that EAP_HOME in the docs is *not* an environment variable, and is just a reference that users would replace with the path to their EAP installation).

**Comment by adellape** [comment]
@lucascosti I was looking earlier in the EAP docs to see how things compared, and noticed that. The way the sentence is worded in this topic though made it sound like it is an environment variable "inside a JBoss EAP xPaaS image", so I checked:

```
# docker run -i -t registry.access.redhat.com/jboss-eap-6/eap-openshift /bin/bash
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[jboss@2ac4dae8dce4 ~]$ env | grep HOME
JBOSS_HOME=/opt/eap
JAVA_HOME=/usr/lib/jvm/java-1.8.0
HOME=/home/jboss
```

Similarly, A-MQ has `AMQ_HOME` and Web Server has `JWS_HOME`.

> (Note that EAP_HOME in the docs is not an environment variable, and is just a reference that users would replace with the path to their EAP installation).

When you say "in the docs" there, are you referring to the general EAP docs, or this xPaaS image topic, or both? I can understand not wanting to introduce confusion, so I guess the question is, is this sentence here and the EAP docs in general trying to refer to the same thing? If so, some added context here may be good, and we could revert this change.

**Comment by lucascosti** [comment]
>When you say "in the docs" there, are you referring to the general EAP docs, or this xPaaS image topic, or both?

Both. And yes, both are referring to the same thing, which which is that EAP_HOME is the path to the EAP installation directory. 

JBOSS_HOME is the environment variable, but is/was used in multiple JBoss products, so in the docs we decided to use EAP_HOME for referring the EAP installation directory.

**Comment by bdecoste** [comment]
The doc was incorrect but has been corrected. EAP_HOME isn’t an ENV like AMQ_HOME and JWS_HOME are. The analogy for EAP is JBOSS_HOME. This is where AMQ, JWS, and EAP are installed.

**Comment by lucascosti** [comment]
Imo, I think we should keep the usage consistent with the EAP documentation. As the EAP documentation has the EAP installation path as EAP_HOME, I think it should also be the case here (but, of course I am bias in working on that docs team :)).

When referring to the environment variable, it should of course be JBOSS_HOME. However, all EAP_HOME mentions in this doc weren't as an environment variable.

There's a distinction between the EAP_HOME documentation replaceable vs. $JBOSS_HOME an environment variable. The former should be replaced by the user with their installation path. The latter can be included literally as an environment variable.

**Comment by adellape** [comment]
@lucascosti If it's kept EAP_HOME here, can we add some language to this topic to make the distinction that you've just described clear?

**Comment by lucascosti** [comment]
Yep, sure!

Something like "EAP_HOME in this documentation is used refer to the JBoss EAP installation directory. The location of EAP_HOME inside a JBoss EAP xPaaS image is: /opt/eap/."

**Comment by adellape** [comment]
:+1:

**Pull request merged**
