### PR TITLE
OSDOCS-8023: adds short attribute for MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13, 4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-8023

Link to docs preview:
https://65751--docspreview.netlify.app/microshift/latest/microshift_getting_started/microshift-understanding
https://65751--docspreview.netlify.app/microshift/latest/microshift_getting_started/microshift-architecture

QE review:
- N/A docs plumbing

Additional information;
Example sections updated to ensure attribute works as expected prior to global use.

### CODE REVIEW

**Comment by xenolinux** [comment]
looks good!

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead. Thanks!

**Comment by abhatt-rh** [comment]
> looks good!
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead. Thanks!

@ShaunaDiaz and @xenolinux LGTM!

**Pull request merged**
