### PR TITLE
Added information about Collaboration in Online

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/XI3EBYhK/803-3-document-collaboration-for-free-and-paid-tiers

@abhgupta @luciddreamz PTAL

### CODE REVIEW

**Comment by abhgupta** [comment]
LGTM

**Comment by ahardin-rh** [comment]
@alexd @bmcelvee @bfallonf Can one of you please peer review? Thanks!

**Comment by bmcelvee** [comment]
LGTM 🎆

**Comment by bfallonf** [comment]
LGTM :fireworks:

**Comment by ahardin-rh** [comment]
No revision history needed, as this is appearing in Online only (where no revision history is preserved).

**Pull request merged**
