### PR TITLE
ceph end-to-end example.

### PR DESCRIPTION
**Pull request by jeffvance**
[WIP] Ceph-rbd example.
Console screens to be added later (if deemed necessary).
There is a fair amount of duplication between this PR and #1732 . I'd like to reduce this redundancy in the near future.

### CODE REVIEW

**Comment by erinboyd** [comment]
@jeffvance shouldn't this go into openshift-docs? Also you will need to edit the index page to link to the example in openshift-docs/install_config/storage_examples/index.adoc

**Comment by jeffvance** [comment]
@erinboyd this is openshift-docs :)  I'll update index.adoc.

**Comment by jeffvance** [comment]
@adellape  @erinboyd  @screeley44  PTAL, thanks

**Comment by erinboyd** [comment]
@jeffvance why did you create an additional directory for ceph examples?
I think it's sufficient to just have them all in the storage_examples directory

**Comment by erinboyd** [comment]
@jeffvance one more thing, sorry it's a bit nit picky. But can you look at the formatting of the numbers in the code to match this example https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/persistent_storage_nfs.html

**Comment by erinboyd** [comment]
LGTM. You will likely have to rebase with the conflicting changes on the _build_cfg :(

**Comment by adellape** [comment]
@jeffvance For consistency with other references, can this use "Ceph RBD" instead of "Ceph-RBD" in relevant spots?

Also the `build_cfg` title and the topic title can probably match closer. Sometimes we shorten the left nav (`build_cfg`) title for space reasons or to consider redundancy w/ the subdirectory name, and let the topic title have more room to spell things out further, but in this case they're both fairly short, just different.

Most of the other stuff I noticed in this I think would be easier addressed by a docs member in a follow-up PR for style/formatting. So after my above comments are addressed, I'm OK to merge to move it along if @erinboyd and @screeley44 are happy.

**Comment by jeffvance** [comment]
@adellape Thanks for the review. I've pushed the latest changes.

**Comment by adellape** [comment]
:+1:

**Comment by adellape** [comment]
No revhistory (will add in follow-up PR), should be picked with https://github.com/openshift/openshift-docs/pull/1849.

**Pull request merged**
