### PR TITLE
shorten manually `delete` StorageClass on nodes

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lpettyjo, will you PTAL?

**Comment by kalexand-rh** [comment]
@lpettyjo, PTAL.

**Comment by kalexand-rh** [comment]
@duanwei33, will you PTAL?

**Comment by duanwei33** [comment]
LGTM 
(cc @Phaow @chao007 )

**Comment by Phaow** [comment]
LGTM

**Review by lpettyjo — COMMENTED** [review]
I see that there are two commits. Other that that LGTM!

**Comment by xerc** [comment]
@lpettyjo the second commit is merge-only caused change of mount-path

**Comment by kalexand-rh** [comment]
The change I pushed fixed a [nesting issue](https://36798--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-local#local-removing-device_persistent-storage-local) and squashed the commits.

**Pull request merged**
