### PR TITLE
RHDEVDOCS 5959 Release Notes for Pipelines 1.14.1

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.14

Issue:

RHDEVDOCS 5959

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by ppitonak — APPROVED** [review]

**Review by rupalibehera — APPROVED** [review]

**Comment by skopacz1** [comment]
Link to doc preview: [Release notes for Red Hat OpenShift Pipelines General Availability 1.14.1](https://73059--ocpdocs-pr.netlify.app/openshift-pipelines/latest/about/op-release-notes#release-notes-1-14-1_op-release-notes)

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by rupalibehera** [comment]
@mramendi we can go ahead to merge this one.

**Pull request merged**
