### PR TITLE
OADP2256:  Incorrect apiVersion in DPA CR yaml

### PR DESCRIPTION
**Pull request by anarnold97**
OADP 1.2; OCP 4.12+

[OADP-2256](https://issues.redhat.com//browse/OADP-2256)

Version(s):

/branch/enterprise-4.12
/branch/enterprise-4.13
/branch/enterprise-4.14

Issue:

https://issues.redhat.com/browse/OADP-2256

Link to docs preview:

[Installing and configuring the OpenShift API for Data Protection with Amazon Web Services](https://62366--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html)

[Installing and configuring the OpenShift API for Data Protection with Microsoft Azure](https://62366--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html)

[Installing and configuring the OpenShift API for Data Protection with Google Cloud Platform](https://62366--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.html)

[Installing and configuring the OpenShift API for Data Protection with Multicloud Object Gateway](https://62366--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.html)

[Installing and configuring the OpenShift API for Data Protection with OpenShift Data Foundation](https://62366--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
@stillalearner @weshayutin - please can i ask for a review so i can get this merged as soon as possible
Thanks

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by weshayutin** [comment]
[whayutin@thinkdoe OADP]$ oc explain dataprotectionapplications.oadp.openshift.io
KIND:     DataProtectionApplication
VERSION:  oadp.openshift.io/v1alpha1

**Review by skrthomas — APPROVED** [review]
/lgtm

**Comment by anarnold97** [comment]
@skrthomas - am I ok to push to *merge review*, please?
Thanks

**Comment by skrthomas** [comment]
@anarnold97 Yep, once you've incorporated peer review suggestions, you're good to move to merge review :) I just added the label for you.

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
