### PR TITLE
Change target platforms assembly language to indicate support rather than possibility

### PR DESCRIPTION
**Pull request by maxwelldb**
Context: https://bugzilla.redhat.com/show_bug.cgi?id=1801980#c11

### CODE REVIEW

**Comment by maxwelldb** [comment]
@sferich888 Any objections to this wording change on [this page](https://docs.openshift.com/container-platform/4.6/installing/install_config/installation-types.html)?

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by maxwelldb** [comment]
@bergerhoffer TY!

**Pull request merged**
