### PR TITLE
CNV-13223: Updated HCO variable for 4.8.1

### PR DESCRIPTION
**Pull request by sjhala-ccs**
- [CNV-13223](https://issues.redhat.com/browse/CNV-13223)
- enterprise-4.8 and 4.9

### CODE REVIEW

**Comment by sjhala-ccs** [comment]
@tiraboschi Can you please review/approve this HCO version bump PR for the 4.8.1 release scheduled to go out on August 24? Thanks!

**Comment by ousleyp** [comment]
LGTM

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
