### PR TITLE
CNV-20962: follow-up PR for SELinux in 4.12

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.12+

Issue: [CNV-20962](https://issues.redhat.com//browse/CNV-20962)

Link to docs preview: https://54696--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-additional-security-privileges-controller-and-launcher.html#virt-extended-selinux-policies-for-virt-launcher_virt-additional-security-privileges-controller-and-launcher

QE review:
- [x] QE has approved this change.

@jean-edouard and @kbidarkar Please review! Thanks!

### CODE REVIEW

**Review by jean-edouard — APPROVED** [review]

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Review by skrthomas — COMMENTED** [review]
LGTM :)

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
