### PR TITLE
OLS-919: Update Lightspeed docs for OpenShift AI vLLM

### PR DESCRIPTION
**Pull request by rh-tokeefe**
This PR is part of the standalone doc set for the OpenShift Lightspeed project. Kathryn is aware that this content applies for a product that is not officially released yet.  The project is seeking feedback from early adopters. 

Versions: Tech Preview

PRs get merged to https://github.com/openshift/openshift-docs/tree/lightspeed-docs-main

And cherry picked to https://github.com/openshift/openshift-docs/tree/lightspeed-docs-1.0tp1

Issue: https://issues.redhat.com/browse/OLS-919

Linkto About OpenShift AI vLLM
https://80312--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/about/ols-about-openshift-lightspeed#ols-about-openshift-ai-vllm_ols-large-language-model-requirements

Link to docs preview of note in the task:
https://80312--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/configure/ols-configuring-openshift-lightspeed.html#ols-creating-lightspeed-custom-resource-file-using-web-console_ols-configuring-openshift-lightspeed

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by thoraxe** [comment]
LGTM

**Comment by JoaoFula** [comment]
@rh-tokeefe since you're tackling changing from **customer** to **custom** example files, in the [Filtering and redacting information](https://80312--ocpdocs-pr.netlify.app/openshift-lightspeed/latest/configure/ols-configuring-openshift-lightspeed#ols-filtering-and-redacting-information_ols-configuring-openshift-lightspeed), there's another instance of this

**Comment by rh-tokeefe** [comment]
@JoaoFula I believe your comment refers to the work that was done for OLS-819. That change was made as part of the PR: https://github.com/openshift/openshift-docs/pull/80269

Does this PR for OLS-919 look good?

**Comment by JoaoFula** [comment]
@rh-tokeefe ah, gotcha, my bad!
Yes, LGTM for this one

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Pull request merged**
