### PR TITLE
OSDOCS-8124: update pod auth behavior

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-8124

Link to docs preview:
https://66082--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-authentication

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@kelbrown20 Could you PTAL since you did this work originally?

**Review by kelbrown20 — COMMENTED** [review]
Hey @ShaunaDiaz! These updates LGTM!

**Comment by ShaunaDiaz** [comment]
@pacevedom and @dhensel-rh Could you both PTAL?

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by pacevedom — APPROVED** [review]
/lgtm

**Pull request merged**
