### PR TITLE
BZ#1840891 Azure region updates

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1840891

### CODE REVIEW

**Comment by codyhoag** [comment]
@e-tienne as discussed. Can you confirm? I'll wait for the `norwayeast` confirmation for 4.4 before merging. Thanks!

**Comment by e-tienne** [comment]
Hello Cody,

Unfortunately, I can't test `norwayeast` right now as we are having issues with creating clusters in our Subscription today. We'll have to test it later and update the docs it's confirmed.

Also, is there a reason why we are not ordering the regions alphabetically? 

Thanks!

**Comment by codyhoag** [comment]
@e-tienne I'll remove `norwayeast` in OCP 4.4 for now. We can add it once it has been verified. I'll send that PR separately. I'll also alphabetize; I see it's done like that for AWS, and it's much easier to read that way, I agree. :+1:

**Comment by e-tienne** [comment]
LGTM

**Comment by lamek** [comment]
LGTM.

**Pull request merged**
