### PR TITLE
[WIP] OSSM-5548: comment in source code appears in output

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSSM-5548

Link to docs preview: https://69098--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-create-smcp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jwendell — APPROVED** [review]

**Review by pbajjuri20 — APPROVED** [review]
LGTM

**Review by jeana-redhat — APPROVED** [review]
What a weird issue! not sure why it was doing that. Good fix :)

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
