### PR TITLE
Fix typo in CAS docs

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
Reported via [Slack](https://redhat-internal.slack.com/archives/CBZHF4DHC/p1714994639165639)

Link to docs preview:
[Cluster autoscaler resource definition](https://75542--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling)

QE review:
N/A

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@elmiko PTAL :bow:

**Review by elmiko — COMMENTED** [review]
/lgtm

**Pull request merged**
