### PR TITLE
note gogs support for github webhook

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bfallonf** [comment]
@bparees Looks OK. Travis problems though. Would a re-push fix this?

**Comment by bparees** [comment]
```
Gem::InstallError: listen requires Ruby version ~> 2.2.

An error occurred while installing listen (3.1.1), and Bundler cannot continue.

Make sure that `gem install listen -v '3.1.1'` succeeds before bundling.

The command "eval bundle install --jobs=3 --retry=3" failed 3 times.

The command "bundle install --jobs=3 --retry=3" failed and exited with 5 during .
```

so no, i don't think so.  i poked travis to rerun the test.

**Comment by bparees** [comment]
@openshift/team-documentation looks like you need to version lock the listen gem, or update to ruby 2.2 in your travis file.

**Comment by bparees** [comment]
@bfallonf passed travis

**Comment by bfallonf** [comment]
@bparees Neato. Thanks!

**Comment by ahardin-rh** [comment]
rev history in follow-up PR: https://github.com/openshift/openshift-docs/issues/2024

**Pull request merged**
