### PR TITLE
OCPBUGS#2928: Remove idle=poll from the reference DU performance profile

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.11, 4.12

Issue: https://issues.redhat.com/browse/OCPBUGS-2928

Link to docs preview: https://52402--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-configuring-single-node-cluster-deployment-during-installation.html#sno-du-configuring-performance-addons_sno-du-deploying-distributed-units-manually-on-single-node-openshift

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by imiller0 — COMMENTED** [review]
Looks good to me, however note that the backport of this fix to 4.10 has not yet landed (it has been backported to 4.11). It may make sense to hold this docs update until the last backport completes?

**Comment by amolnar-rh** [comment]
@imiller0 We can do that! Let me know when the backport is finished and we'll merge it then.

**Review by sheriff-rh — APPROVED** [review]
Looks good! No suggestions.

**Review by imiller0 — COMMENTED** [review]
lgtm

**Comment by amolnar-rh** [comment]
At the moment, this change is for 4.11 and 4.12. Please only cherrypick for 4.11 and 4.12

**Pull request merged**
