### PR TITLE
Bug 1436834 Clarifying title of Configuring Highly-available Services section

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1436834

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@pecameron  Hey Phil, can you help us in figuring out what needs to happen for fixing this bug for the high availability and geo-cache? https://bugzilla.redhat.com/show_bug.cgi?id=1436834

**Comment by pecameron** [comment]
@vikram-redhat @bmcelvee I will look into this and get back to you soon.

**Comment by pecameron** [comment]
@vikram-redhat @bmcelvee  I have been looking through referenced page in 3.4 docs.

In reading through the bug, Thom Carlin developed and expectation that is not supported in the documents. I think he read them expecting to find a particular answer and not just trying to understand the feature and how to apply it. I am not sure what to do about that. Maybe you could reach out to him for more context on his thinking. There may be some simple phrasing changes that would get him and others  on track.



23.2.5. Configuring a Highly-available Service
"The following steps describe how to..."
This might be rephrased as something like: "The following example illustrates how to ..."

"Deploy IP Failover Pod"
at the end of 23.2.5 is another example. Maybe it should get a section number and a better introduction.

------
In looking at the bug, Thom Carlin is looking for something beyond the scope of the examples. I don't think he realizes that these are just examples of how the software could be used. I think improving the introduction to the examples might help here.

The geo-cache example was in the early version of the docs that I worked on. I really didn't do anything with it since it set out the approach. I don't know what geo-caching does or why it was originally included. When I was working on HA the thrust was with using a VIP with routers.

From the bug:
" I was expecting this section to be a copy-paste-tweak for setting up wildcard DNS for OCP HA."
I am not sure how the documents lead him to expect this. I don't think of any of our docs as providing cut and paste examples. DNS in general is not a consideration beyond you need to get the traffic to the specified VIP. HA just deals in VIPS. Maybe an earlier discussion could expand on the note that you have to externally make arrangements to get the traffic to any of the nodes that can host the VIP. It might point to other discussions on wildcard DNS.

What do you think?

**Comment by bmcelvee** [comment]
@pecameron Thank you for the clarification! I think changing our phrasing and providing better introductions would certainly help. @vikram-redhat What do you think?

**Comment by vikram-redhat** [comment]
Thanks @pecameron. 

@thom-at-redhat - hey Thom, would a better wording of the docs help alleviate the issue?

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../admin_guide/high_availability.adoc#admin-guide-high-availability[High Availability]
|Added verbiage clarifying the example outlined in the xref:../admin_guide/high_availability.adoc#configuring-a-highly-available-service[Configuring a Highly-available Service] section.
%

**Pull request merged**
