### PR TITLE
BZ-1747616: Added local PV definition with node affinity

### PR DESCRIPTION
**Pull request by lbarbeevargas**
BZ-1747616 https://bugzilla.redhat.com/show_bug.cgi?id=1747616

@liangxia PTAL for 3.11.

### CODE REVIEW

**Comment by liangxia** [comment]
@qinpingli  PTAL

**Comment by qinpingli** [comment]
LGTM

**Comment by lbarbeevargas** [comment]
BZ-1747616 https://bugzilla.redhat.com/show_bug.cgi?id=1747616
@openshift/team-documentation PTAL. Merge to enterprise-3.11. Add labels and milestone.

**Comment by mburke5678** [comment]
@lbarbeevargas LGTM

**Pull request merged**
