### PR TITLE
Bug 1432594 corrected `openshift_metrics_cassandra_cpvc_size` variable

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@ahardin-rh PTAL.

**Comment by ahardin-rh** [comment]
LGTM! :star:

**Comment by mburke5678** [comment]
[rev_history]
|xref:../ install_config/cluster_metrics.adoc#install-config-cluster-metrics[Enabling Cluster Metrics]|Changed the `openshift_metrics_cassandra_cpvc_size` to `openshift_metrics_cassandra_pvc_size` variable in the Ansible Variables table in the xref:/install_config/cluster_metrics.adoc#metrics-ansible-role[Metrics Ansible Variables] section.
%

**Comment by vikram-redhat** [comment]
@mburke5678 @ahardin-rh - this one had no labels or milestones and therefore didn't get picked into any release.

**Pull request merged**
