### PR TITLE
RHDEVDOCS-2911 - Uninstall GitOps operator

### PR DESCRIPTION
**Pull request by DebarghoGhosh**
- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: `enterprise-4.8`, `enterprise-4.9`
- **JIRA issues**: [RHDEVDOCS-2911 Uninstall-GitOps-Operator](https://issues.redhat.com/browse/RHDEVDOCS-2911)
- **Preview pages**: https://deploy-preview-37012--osdocs.netlify.app/openshift-enterprise/latest/cicd/gitops/uninstalling-openshift-gitops?utm_source=github&utm_campaign=bot_dp
- **SME+QE review**: Regina Scott
- **Peer-review**: Preeti

### CODE REVIEW

**Comment by DebarghoGhosh** [comment]
@reginapizza please verify and provide review comments

**Review by reginaelyse — CHANGES_REQUESTED** [review]
Looks almost good to me but please see review comments for just a couple things! I would also suggest squashing commits (I think you would be asked to do that anyway).

**Comment by reginapizza** [comment]
cc @iam-veeramalla please review to make sure I didn't miss anything!

**Comment by iam-veeramalla** [comment]
> cc @iam-veeramalla please review to make sure I didn't miss anything, thanks!

Apart from your review comments, PR looks good to me :)

**Comment by reginapizza** [comment]
Okay content-wise LGTM! You may still have to squash the commits, but that's up to your team :)

**Review by Preeticp — COMMENTED** [review]
@DebarghoGhosh I have left a few suggestions, PTAL.

**Pull request merged**
