### PR TITLE
Use consistent --cert and --key values for Securing the Registry

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Fixes 1249155

@rjhowe Thanks for including the detailed session log in the BZ.  These changes are based on them.  WDYT?  In particular, starting on line 605, the previous text and example was for **one** (the `default`) service account, and now there are **two**.  Is that correct?

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@xiama 
Although i have [responded in the BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1249155#c8), please feel free to continue the review here.

**Comment by tnguyen-rh** [comment]
@bfallonf @tpoitras @ahardin-rh @adellape 
Hopefully will be out of tech-review soon.  Peer-review please?

**Comment by ahardin-rh** [comment]
@tnguyen-rh LGTM!  :star2:

**Comment by bfallonf** [comment]
@tnguyen-rh LGTM as well. Have another :star2:

**Comment by tnguyen-rh** [comment]
[tech-review OK](https://bugzilla.redhat.com/show_bug.cgi?id=1249155#c9)

**Comment by tnguyen-rh** [comment]
Rats, forgot to squash.  :-/  Sorry @openshift/team-documentation ...

[rev_history]
|xref:../install_config/install/docker_registry.adoc#[Installing -> Deploying a Docker Registry]
|Fixed examples in the xref:../install_config/install/docker_registry.adoc#securing-the-registry[Securing the Registry] section to use consistent `--cert` and `--key` values.  Also, clarify the origin of the *_ca.crt_* file that must be installed per-node.

**Pull request merged**
