### PR TITLE
BZ2079092: Add SELinux warnings and fix hard returns

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2079092

Link to docs preview: 
- Choosing how to harden RHCOS: http://file.rdu.redhat.com/jdohmann/BZ2079092/security/container_security/security-hardening.html#security-hardening-how_security-hardening
- Securing containers on RHCOS: http://file.rdu.redhat.com/jdohmann/BZ2079092/security/container_security/security-hosts-vms.html#security-hosts-vms-rhcos_security-hosts-vms

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen could you PTAL for QE feedback/ack? Thank you

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by jldohmann** [comment]
afec7ca..66a5fd6 remove link to Solution article

**Pull request merged**
