### PR TITLE
Updated Backup and Restore docs for Dedicated

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview Build: http://file.rdu.redhat.com/~ahardin/01082018/dedicated-backup/admin_guide/backup_restore.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vikram-redhat @aheslin Sorting through this

**Comment by ahardin-rh** [comment]
@spurtell @sspeiche @jgouldin PTAL. I removed some sections per Steve's guidance and added in a new callout regarding user responsibility. Please let me know if further guidance needs added.

Preview build:
 http://file.rdu.redhat.com/%7Eahardin/01082018/dedicated-backup/admin_guide/backup_restore.html

**Comment by ahardin-rh** [comment]
@sferich888 PTAL as well. Thanks!

**Comment by ahardin-rh** [comment]
@sferich888  @spurtell @jgouldin @sspeiche bump

**Comment by spurtell** [comment]
I recommend also removing the Bringing OpenShift Dedicated Services Back Online section entirely, as that is not something the customer can manage on OSD.

**Comment by ahardin-rh** [comment]
@spurtell Thanks! This is updated.

**Comment by ahardin-rh** [comment]
@vikram-redhat I cherry-picked this to all stage branches, then to the dedicated prod branch via https://github.com/openshift/openshift-docs/pull/7102, so I am removing the dedicated label, as the other branches can get taken care of during the weekly release.

**Comment by ahardin-rh** [comment]
@spurtell @sferich888 @jgouldin @sspeiche The updates are live. I wanted to get the inaccurate sections pulled down quickly, but let me know if any follow-up is necessary. Thanks!

**Pull request merged**
