### PR TITLE
Adds release note entry for OVNK migration support on Nutanix platforms

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.16 only

Issue:
No issue. RN follow up. 

Link to docs preview:
https://75035--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-sdn-ovnk-migration-nutanix-support

Follow up release note for https://github.com/openshift/openshift-docs/pull/74852

### CODE REVIEW

**Review by jneczypor — COMMENTED** [review]
lgtm. @michaelryanpeter will follow along after with his final review because I am currently onboarding to the Peer Review team. Thanks for your patience!

**Comment by michaelryanpeter** [comment]
LGTM.

**Pull request merged**
