### PR TITLE
[continuation of #58238] Move and include the Serverless upgrades section

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
4.9+

Issue:
https://github.com/openshift/openshift-docs/pull/58238

Link to docs preview:
https://58455--docspreview.netlify.app/openshift-enterprise/latest/serverless/install/serverless-upgrades.html

QE review:
not needed.

Additional information:
The section introduced in https://github.com/openshift/openshift-docs/pull/58238 should have been included in the respective topic maps as usual. However, restructuring of the Serverless docs happened, and I've missed the need to include this section correctly. This PR fixes that. The text itself already went through all necessary reviews.

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Updates look great! 
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
