### PR TITLE
Add documentation on how to dynamically update VIPs for an IP failover config.

### PR DESCRIPTION
**Pull request by ramr**
Updating as per email exchange with PMs re: how to dynamically update the VIPs.

@adellape / @bfallonf  PTAL thx

### CODE REVIEW

**Comment by ramr** [comment]
@bfallonf / @adellape   /bump - this is for OSE 3.2 docs

**Comment by adellape** [comment]
@ramr I've pulled this into a follow-up PR: https://github.com/openshift/openshift-docs/pull/2028

**Comment by ramr** [comment]
@adellape cool thx.

**Pull request closed without merging**
