### PR TITLE
Documentation wrong openshift_hosted_router_certificate

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1579348

### CODE REVIEW

**Comment by mburke5678** [comment]
@ikke-t @sdodson  I got code from an issue that you worked on that included a bracket with the `openshift_hosted_router_certificate=[{"certfile": "/path/on/host/to/app-crt-file", "keyfile": "/path/on/host/to/app-key-file", "cafile": "/path/on/host/to/app-ca-file"}]` command. 
A customer says that the brackets are not needed, based on upstream: https://github.com/openshift/openshift-ansible/blob/master/inventory/hosts.example#L395
Can you verify which is correct in OpenShift?

**Comment by mburke5678** [comment]
@jianlinliu @ikke-t @sdodson
PTAL

**Review by sdodson — APPROVED** [review]
It's fine to remove the brackets. I wouldn't have expected them to cause a problem though.

**Comment by mburke5678** [comment]
@jianlinliu PTAL

**Comment by jianlinliu** [comment]
LGTM.

**Comment by ikke-t** [comment]
The brackets would be needed if it was a list. If it accepts non-lists, then it's fine to remove them, as there is only one item {} there.

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL tiny change. Just wanted to make sure I didn't miss something

**Comment by kalexand-rh** [comment]
LGTM :+1:

**Pull request merged**
