### PR TITLE
bug 1640600 updating Apache HTTPD REMOTE_USER definition

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://bugzilla.redhat.com/show_bug.cgi?id=1640600

@stuartchuan, PTAL?

### CODE REVIEW

**Comment by stuartchuan** [comment]
The changes are OK, I have verified the changes with OCP 3.9.

**Comment by kalexand-rh** [comment]
@enj, can I merge this one?

@stuartchuan, if Mo agrees to merge, are you ok with me applying the changes to 3.9-3.11?

**Comment by stuartchuan** [comment]
@kalexand-rh it's OK for me.

**Pull request merged**
