### PR TITLE
BZ2190236: Update SCC for DPDK checkup

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13

Issue: [BZ2190236](https://bugzilla.redhat.com/show_bug.cgi?id=2190236)

Link to docs preview: [DPDK checkup](https://59372--docspreview.netlify.app/openshift-enterprise/latest/virt/support/monitoring/virt-running-cluster-checkups.html#virt-checking-cluster-dpdk-readiness_virt-running-cluster-checkups)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by orelmisan — APPROVED** [review]
@apinnick Thank you very much for the quick fix.

**Comment by apinnick** [comment]
@yossisegev Ready for QE review.

**Review by yossisegev — COMMENTED** [review]
/lgtm

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
