### PR TITLE
Update UPI TP support statements for WMCO 3.1+ to GA

### PR DESCRIPTION
**Pull request by codyhoag**
After additional testing post-release, the UPI related Tech Preview statements for WINC have been requested for upgrade to GA.

Preview: https://deploy-preview-39754--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-4-x.html#supported-platforms-based-on-openshift-container-platform-and-wmco-versions

### CODE REVIEW

**Comment by codyhoag** [comment]
Because this PR updates support statements for an already released component of OCP, this will require change management ACKs/approvals.

@aravindhp (Eng) @sgaoshang (QE) @davemulford (Support) @TanyaShearonRH (Docs) @Anandnatraj (PM) can you ACK? Thanks!

**Comment by aravindhp** [comment]
/cc @selansen 
Please ack

**Comment by Anandnatraj** [comment]
ACK

**Comment by selansen** [comment]
ACK

**Comment by TanyaShearonRH** [comment]
ACK

**Comment by sgaoshang** [comment]
ACK, thanks.

**Comment by mjpytlak** [comment]
@codyhoag peer review LGTM.

**Pull request merged**
