### PR TITLE
GitHub-43205: Fixing example callback URL

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.6+

Issue:
#43205

Link to docs preview:
* OCP (single page): http://file.rdu.redhat.com/~ahoffer/2022/configuring-github-identity-provider.html#identity-provider-registering-github_configuring-github-identity-provider
* ROSA: (single page): http://file.rdu.redhat.com/~ahoffer/2022/rosa-sts-config-identity-providers.html
* Dedicated (single page): http://file.rdu.redhat.com/~ahoffer/2022/config-identity-providers.html

Additional information:

### CODE REVIEW

**Review by aireilly — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@stlaz or @ibihim Can you please review these updates to make sure that the changes I made to the example OAuth callback URL are okay?

@xingxingxia Can you please verify as well?

Previews:

- OCP (single page): http://file.rdu.redhat.com/~ahoffer/2022/configuring-github-identity-provider.html#identity-provider-registering-github_configuring-github-identity-provider
- ROSA: (single page): http://file.rdu.redhat.com/~ahoffer/2022/rosa-sts-config-identity-providers.html
- Dedicated (single page): http://file.rdu.redhat.com/~ahoffer/2022/config-identity-providers.html

**Pull request merged**
