### PR TITLE
Add Intel X710 Base T as supported SR-IOV device

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-8954

This PR backports support for an SR-IOV device. Applies to 4.13 and 4.12 only. PR against 4.13.

Version(s): 4.12, 4.13

Issue:

Link to docs preview: https://68971--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by mffiedler — APPROVED** [review]
/lgtm

**Pull request merged**
