### PR TITLE
OSDOCS#39020: Expanding command for hot-plugging bridge interface

### PR DESCRIPTION
**Pull request by jherrman**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/CNV-39020

Link to docs preview:
https://78711--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/vm_networking/virt-hot-plugging-network-interfaces.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by yossisegev — APPROVED** [review]
/lgtm (CNV network QE)

**Review by lahinson — COMMENTED** [review]
LGTM

**Review by jldohmann — APPROVED** [review]
LGTM! nice work 😄

**Pull request merged**
