### PR TITLE
CNV-34643-01: RN for Downward Metrics and CPU Hotplug

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.16

Issue:
* https://issues.redhat.com/browse/CNV-41655
* https://issues.redhat.com/browse/CNV-34687

Link to docs preview:
https://77327--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-16-release-notes.html#virt-4-16-web

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
Small suggestion, thanks.

**Comment by JoeAldinger** [comment]
I don't see QE acks on this PR. Please be sure to get them.

**Comment by danielclowers** [comment]
Hi @JoeAldinger. The QEs were done in the actual Jiras. We were doing something different this release cycle, but admittedly it's not as seamless. Thanks for the recommendations.

**Pull request merged**
