### PR TITLE
RHDEVDOCS-4495: Added the UI customization feature in enterprise-4.12 RN

### PR DESCRIPTION
**Pull request by shipsing**
Purpose: To resolve https://issues.redhat.com/browse/RHDEVDOCS-4495
Version(s): enterprise-4.12 only

Link to docs preview: https://52342--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-web-console

SME review: @debsmita1 @jerolimov 
QE review: @sanketpathak 
Peer review: @jc-berger

### CODE REVIEW

**Comment by shipsing** [comment]
@debsmita1 @jerolimov, Could you please help with SME review of this PR created for enterprise-4.12 release notes? Thanks

**Review by christoph-jerolimov — APPROVED** [review]
Lgtm! :+1:

**Comment by jerolimov** [comment]
Updated version still LGTM. :+1:

**Comment by shipsing** [comment]
@sanketpathak, could you please help with QE review of this PR? Thanks

**Comment by sanketpathak** [comment]
LGTM

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by shipsing** [comment]
This PR covers this issue: https://issues.redhat.com/browse/RHDEVDOCS-4494 as well

**Pull request merged**
