### PR TITLE
bug 1538391 fixing router version image number

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1538391

@vikram-redhat, are you ok with this change?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Interesting. The file's in all these other branches, but this section's only in master and 3.5. I think it's fair to only correct the change in those two branches.

**Comment by vikram-redhat** [comment]
@kalexand-rh yeah. As this is the release notes for 3.5, the ones in other sections are out of sync or not relevant.

**Comment by kalexand-rh** [comment]
@vikram-redhat, that does make sense. Next time we discuss whether or not we should remove the old release notes from branches, I am fully in favor of ripping old versions out of newer branches. (And I'll put together the PRs to pull them, if you want.)

**Pull request merged**
