### PR TITLE
CAM: Self-signed CA certs

### PR DESCRIPTION
**Pull request by apinnick**
[BZ#1768497](https://bugzilla.redhat.com/show_bug.cgi?id=1768497)

[Doc preview](http://file.tlv.redhat.com/~apinnick/CAM_unsigned_CA_certs/migration/migrating-openshift-3-to-4.html#migration-launching-cam_migrating-openshift-3-to-4)

### CODE REVIEW

**Comment by apinnick** [comment]
@bergerhoffer 

This is a very small fix. Can you review, please? Thanks

**Comment by bergerhoffer** [comment]
This LGTM.

@apinnick Is this for 4.2/4.3? Is this QE reviewed and ready to be merged?

**Comment by apinnick** [comment]
> This LGTM.
> 
>  Is this for 4.2/4.3? Is this QE reviewed and ready to be merged?

This is for 4.2. It has been QE reviewed and is ready to be merged. Thanks!

**Pull request merged**
