### PR TITLE
OSSM-4529: added "the" to sentence to fix typo/dropped word

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OSSM-4529

Link to docs preview: https://62864--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/installing-ossm.html#ossm-install-ossm-operator_installing-ossm

QE review:
- [x] QE has approved this change.

- Aligned team: Dev Tools
- SME review: NA for typo
- QE review: provided by pburi20ajj
- Peer review: NA for typo
- All reviews complete. Please merge now

### CODE REVIEW

**Review by pbajjuri20 — APPROVED** [review]

**Comment by rh-tokeefe** [comment]
Obtained Github access, and now attempting to add label again: 

/label merge-review-needed

**Pull request merged**
