### PR TITLE
Bug#1490336 Fixes - Easier way to restore etcd in OpenShift 

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1490336
- Updated steps for restoring etcd in multiple node external etcd context

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@tnguyen-rh Can you please review?

**Comment by gaurav-nelson** [comment]
@jhou1 PTAL

**Comment by jhou1** [comment]
@jiajliu @jianlinliu PTAL.

**Comment by gaurav-nelson** [comment]
@jiajliu @jianlinliu bump

**Comment by gaurav-nelson** [comment]
Closing this as the updated steps were not successful in QE testing

**Pull request closed without merging**
