### PR TITLE
OCPBUGS-10288: Update Domain Names

### PR DESCRIPTION
**Pull request by jneczypor**
OCPBUGS-10288

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-10288 

Link to docs preview:
OSD: https://57887--docspreview.netlify.app/openshift-dedicated/latest/applications/deployments/osd-config-custom-domains-applications.html
ROSA: https://57887--docspreview.netlify.app/openshift-rosa/latest/applications/deployments/osd-config-custom-domains-applications.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xueli181114** [comment]
LGTM

**Review by arendej — APPROVED** [review]
lgtm, thanks

**Review by lahinson — COMMENTED** [review]
LGTM. I didn't see a direct link to the doc preview, but I think I found it here: https://57887--docspreview.netlify.app/openshift-dedicated/latest/applications/deployments/osd-config-custom-domains-applications.html

**Pull request merged**
