### PR TITLE
BZ#1936541 Add missing AWS permission

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1936541

Preview: https://deploy-preview-30220--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 can you verify this update? If valid, please let me know if this applies to all supported 4.y versions (4.5-4.8). Thanks!

**Comment by codyhoag** [comment]
Confirmed with Matthew that this affects OCP 4.6+. This is related to openshift/installer#4126

**Comment by yunjiang29** [comment]
LGTM.

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
