### PR TITLE
Updating versions and fixing attribute

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
main only (contrib docs)

GitHub preview here: https://github.com/openshift/openshift-docs/blob/ed9c44e2359a0e0951d60b9aae97dac686572cea/contributing_to_docs/doc_guidelines.adoc#product-name-and-version

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
LGTM

**Review by adellape — APPROVED** [review]

**Comment by GroceryBoyJr** [comment]
Well, I found the problem and was able to correct it, I got an asciibinder build to run fine. But it made me nutso trying to understand the why that problem was not rendered correctly in a web page. Drove me nutso, but then again, I'm not a "web rendering expert". I expect, however, that I need to develop some expertise about that.

**Comment by GroceryBoyJr** [comment]
What you see above was me trying to get useful error output. I tried the "git am --show-current-patch=diff" and it didn't work. Got:
fatal: Resolve operation not in progress, we are not resuming.

**Comment by GroceryBoyJr** [comment]
I found two ways to get useful information about the problem:
1) "git diff" was useful to get me a general look at the area of the file with the problem. That way, I didn't waste any more time looking at pie-in-the-sky stuff.
2) vscodium showed me some rendering errors in the same area, which further directed me to the area of the problem. So both  git diff and vscodium were sending me in closer to see what was happening. vscodium even gave me some nice colors. It showed too many errors (81 total) to help me because vale was scanning the file and calling it's findings "errors" also. So while vscodium directed me closer, it also obfuscated because of vale. Good argument against integrating vale into vscodium.
(more in a bit)

**Comment by GroceryBoyJr** [comment]
Pulled the pr local and renamed it:
jbrigman@jbrigman:~/git/openshift-docs (main)$ git fetch upstream pull/49244/head:cherrypicktest
From github.com:openshift/openshift-docs
 * [new ref]               refs/pull/49244/head -> cherrypicktest
jbrigman@jbrigman:~/git/openshift-docs (main)$ git checkout cherrypicktest
Switched to branch 'cherrypicktest'
jbrigman@jbrigman:~/git/openshift-docs (cherrypicktest)$

**Pull request merged**
