### PR TITLE
issue 20323: correcting subnet parameter value

### LINKED ISSUE #20323: [enterprise-4.3] Edit suggested in file installing/installing_aws/installing-aws-vpc.adoc
### Which section(s) is the issue in?

Installation configuration parameters,  table 3. Optional AWS parameters

### What needs fixing?
The parameter platform.aws.subnets should contain a subnet id, not a valid subnet range

### PR DESCRIPTION
**Pull request by kalexand-rh**
Fixes #20323

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by jianlinliu** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
