### PR TITLE
RHDEVDOCS-6130: Fixed gitops title typo

### PR DESCRIPTION
**Pull request by likhithj1996**
Version(s):
 
Gitops docs 1.13

Issue:
[RHDEVDOCS-6130](https://issues.redhat.com/browse/RHDEVDOCS-6130)

Link to docs preview:
[Using Argo Rollouts for progressive deployment delivery](https://85602--ocpdocs-pr.netlify.app/openshift-gitops/latest/argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.html)
QE review:
- [x] QE has approved this change.

SME review: Done by  @svghadi 
QE review: Done by @varshab1210 
Peer review: 
Internal Peer review: @Dhruv-Soni11 

Additional information:

### CODE REVIEW

**Comment by Dhruv-Soni11** [comment]
lgtm, thanks @likhithj1996

**Review by svghadi — APPROVED** [review]
/lgtm

Thanks @likhithj1996

**Comment by varshab1210** [comment]
LGTM, thanks

**Comment by likhithj1996** [comment]
peer-review-needed

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
