### PR TITLE
Fixed syntax error for link with spaces

### LINKED ISSUE #29052: [enterprise-4.6] Issue in file updating/updating-cluster-between-minor.adoc
### Which section(s) is the issue in?

The EUS channel documentation shows a link for which the asciidoc syntax is not correct.

### What needs fixing?

This:
```
Extended Update Support[https://access.redhat.com/support/policy/updates/openshift#ocp4_phases] (EUS)
```
Should become this:
[Extended Update Support](https://access.redhat.com/support/policy/updates/openshift#ocp4_phases) (EUS)

### PR DESCRIPTION
**Pull request by palonsoro**
Fixes #29052

### CODE REVIEW

**Comment by jboxman** [comment]
@palonsoro LGTM

**Comment by palonsoro** [comment]
Thx

**Pull request merged**
