### PR TITLE
Add network customization for vSphere installer-provisioned

### PR DESCRIPTION
**Pull request by jboxman**
- Related to OSDOCS-988

Refs https://github.com/openshift/openshift-docs/pull/22485.

### CODE REVIEW

**Comment by jboxman** [comment]
@kalexand-rh, FYI.

**Comment by jboxman** [comment]
@jinyunma

This adds the requested network customizations; What do you think? Thanks!

**Comment by jinyunma** [comment]
@==

> @jinyunma
> 
> This adds the requested network customizations; What do you think? Thanks!
Since in section of ["Network configuration parameters'](https://vsphere-ipi-network-customization--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html#network-customization-config-yaml_installing-vsphere-installer-provisioned-network-customizations), it describes each parameters under "networking", but in sample install-config.yaml does not describe this part. It's better to add them. Below is the install-config.yaml generated after running "openshift-install create install-config".
==================================
apiVersion: v1
baseDomain: qe.devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    vsphere: 
      cpus: 2
        coresPerSocket: 2
        memoryMB: 8196
        osDisk:
            diskSizeGB: 120
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere: 
      cpus: 4
        coresPerSocket: 2
        memoryMB: 16384
        osDisk:
            diskSizeGB: 120
  replicas: 3
metadata:
  creationTimestamp: null
  name: ipitest
**networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16**
platform:
  vsphere:
    apiVIP: 10.0.0.2
    cluster: devel
    datacenter: dc1
    defaultDatastore: nvme-ds1
    ingressVIP: 10.0.0.3
    network: VM Network
    password: '%Ahv72nXQzJP'
    username: aosqe@e2e.local
    vCenter: vcsa-qe.vmware.devcluster.openshift.com
publish: External
pullSecret: xxxx
sshKey:  xxxxx

**Comment by jboxman** [comment]
@jinyunma, I've updated the sample configuration.

Thanks!

**Comment by jboxman** [comment]
@kalexand-rh, did I miss any conditionals for this? I'm less familiar with the installation modules.

Thanks!

**Comment by jinyunma** [comment]
thanks to update,  lgtm.

**Comment by kalexand-rh** [comment]
@jboxman, the conditionals look ok to me - I'm not seeing any omissions.

**Pull request merged**
