### PR TITLE
Correct endpoints example in External MySQL Database 

### PR DESCRIPTION
**Pull request by zhudongmei**
"IP: 10.0.0.0" should be" ip: 10.0.0.0"
in the endpoints example of External MySQL Database section.

### CODE REVIEW

**Comment by zhudongmei** [comment]
@adellape Review please.

**Comment by zhudongmei** [comment]
@ahardin-rh PTAL,thanks

**Comment by ahardin-rh** [comment]
@zhudongmei Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/integrating_external_services.adoc#dev-guide-integrating-external-services[Integrating External Services]
|Corrected the endpoints example within the xref:../dev_guide/integrating_external_services.adoc#external-mysql-database[External MySQL Database] section.
%

**Pull request merged**
