### PR TITLE
Changed the ambiguous wording for ellipses

### PR DESCRIPTION
**Pull request by rakshitsharma0402**
Version(s):

Issue: #63286

Link to docs preview: https://github.com/openshift/openshift-docs/blob/d56b81c763e80ad3730e355279876b4b1e3d18d9/contributing_to_docs/doc_guidelines.adoc

QE review:
- [ ] QE has approved this change.

Additional information: Corrected the ambiguous wording

Hey, @rolfedh please review my PR.

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]
LGTM. Nice work, @RakshitKumar04.
I'll wait to hear your decision on whether to close this PR or merge it before the Hacktoberfest start date. (Please see my previous message to you from earlier today.)

**Comment by RakshitKumar04** [comment]
Thank you @rolfedh for the review, I would like to get it merged before Hacktoberfest.

**Comment by rolfedh** [comment]
Please disregard the two preceding "failed to apply on top of branch..." messages. In this case, because we only refer to the `contributing_to_docs/doc_guidelines.adoc` content in the `main` branch, we do not need to update the `enterprise-4.1*` release branches.

**Pull request merged**
