### PR TITLE
Add information about launch config template uploads for bug 1720147

### PR DESCRIPTION
**Pull request by maxwelldb**
https://bugzilla.redhat.com/show_bug.cgi?id=1720147

3.11.

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
LGTM, thanks!

**Comment by maxwelldb** [comment]
Tweaked wording a hair, but instructions are intact.

**Comment by maxwelldb** [comment]
@mburke5678 @huffmanca Are one of you able to merge this? Just realized it's been hanging in limbo for a bit. :)

**Comment by mburke5678** [comment]
@maxwelldb I can merge. Then cherrypick to 3.11?

**Comment by maxwelldb** [comment]
@mburke5678 That is right. :+1:

**Pull request merged**
