### PR TITLE
Changed recycle policies to reclaim policies, fixed issue 4672

### PR DESCRIPTION
**Pull request by gaurav-nelson**
#4672

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@wongma7 Can you please check this one?

**Comment by wongma7** [comment]
thanks lgtm, I would use 'reclaim policy' everywhere instead of 'reclaiming policy' though

**Comment by gaurav-nelson** [comment]
Thanks @wongma7 :+1: I have updated this.

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :sunflower:

**Comment by gaurav-nelson** [comment]
minor fixes, no revision history needed.

**Pull request merged**
