### PR TITLE
CNV-17038: Default storage class - auto update

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.10+

Issue: [CNV-17038](https://issues.redhat.com/browse/CNV-17038)

Link to docs preview: [Automatic importing and updating of pre-defined boot sources ](https://51353--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/advanced_vm_management/virt-automatic-bootsource-updates.html)

QE review: Not required

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@dominikholler 
Can you please review this XS PR?

**Comment by dominikholler** [comment]
> @dominikholler Can you please review this XS PR?

Thanks, looks good.

CC: @arnongilboa

**Comment by arnongilboa** [comment]
looks ok

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@apinnick It doesn't look like this PR got CPd to 4.12, can you please do that?

**Pull request merged**
