### PR TITLE
Insights Operator bug batching/enhancements

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.17

Issue:
N/A

Link to docs preview:
https://82548--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html

QE review:
N/A

Additional information:

### CODE REVIEW

**Comment by obrown1205** [comment]
cc @dfitzmau

**Review by sheriff-rh — APPROVED** [review]
LGTM; merging.

**Pull request merged**
