### PR TITLE
Bug 1400887, Added clarifying details around kubeletArguments in the Example Scenario section

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1400887

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@derekwaynecarr PTAL

@adellape Please peer review :mag_right:

**Review by derekwaynecarr — COMMENTED** [review]
generally lgtm, we can take another pass at this in the future when we have the % based thresholds so we can avoid the math.

**Comment by ahardin-rh** [comment]
This is now updated per comments in the BZ.

**Comment by ahardin-rh** [comment]
@bfallonf @adellape please peer review. Thanks!

**Comment by bfallonf** [comment]
@ahardin-rh LGTM

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/out_of_resource_handling.adoc#admin-guide-handling-out-of-resource-errors[Handling Out of Resource Errors]
|Added clarifying details around `kubeletArguments` in the xref:../admin_guide/out_of_resource_handling.adoc#out-of-resource-schedulable-resources-and-eviction-policies[Example Scenario] section.
%

**Pull request merged**
