### PR TITLE
OSDOCS-6646: remove CIDR from clusterNetwork parameter

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-6646

Link to docs preview:
https://63273--docspreview.netlify.app/microshift/latest/microshift_configuring/microshift-using-config-tools#microshift-yaml-default_microshift-configuring

QE review:
- [x] QE has approved this change.

Additional information:
Release note is here: https://github.com/openshift/openshift-docs/pull/63275

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@zshi-redhat PTAL and let me know if LGTM?

**Comment by dhensel-rh** [comment]
Should a suggestion be made in the docs to copy the /etc/microshift/config.yaml.default file to config.yaml ?

**Pull request merged**
