### PR TITLE
Add documentation for 'build.openshift.io/source-secret-match-uri-' annotation

### PR DESCRIPTION
**Pull request by jim-minter**
Documentation for https://trello.com/c/NoVpS2OS/1059-5-use-build-source-secret-based-on-annotation-on-secret-builds.  1.5 / 3.5.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Overall, LGTM. Thanks! I will apply some minor follow-up edits in a separate PR.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/builds.adoc#dev-guide-builds[Builds]
|Added details about the `build.openshift.io/source-secret-match-uri-` annotation.
%

**Comment by jim-minter** [comment]
> Overall, LGTM. Thanks! I will apply some minor follow-up edits in a separate PR.

Thanks @ahardin-rh.  If there are things I'm getting consistently wrong style-wise or there's a style guide, please let me know (perhaps by e-mail?)

**Comment by ahardin-rh** [comment]
@jim-minter You're doing great. All of my edits are just minor nits. Our doc guidelines live here:
https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc

**Comment by bparees** [comment]
@ahardin-rh it looks like these docs found there way into the 3.3 OCP docs?
https://access.redhat.com/documentation/en/openshift-container-platform/3.3/single/developer-guide/#source-code

it should only be in 3.5+ (as labeled).

**Comment by adellape** [comment]
Looks like a bad merge conflict resolution via https://github.com/openshift/openshift-docs/pull/3503. I'll remove today.

**Comment by adellape** [comment]
It also got into 3.4 via https://github.com/openshift/openshift-docs/pull/3498.

**Comment by ahardin-rh** [comment]
@adellape Thanks! :scream_cat:

**Pull request merged**
