### PR TITLE
BZ#1852120 Update RHCOS image upload steps for GCP

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1852120

Preview: https://deploy-preview-31212--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-gcp-user-infra-rhcos_installing-gcp-user-infra

### CODE REVIEW

**Comment by codyhoag** [comment]
@tsze-redhat PTAL

**Comment by tsze-redhat** [comment]
That looks good.

One minor suggestion:
The file name contains the OpenShift Container Platform version number in the format rhcos-<version>-gcp.tar.
could be
The file name contains the OpenShift Container Platform version number in the format rhcos-<version>-gcp.tar**.gz**.

I overlooked it when I wrote the BZ. My apology.

While we are at it, the link to RHCOS image mirror:
https://mirror.openshift.com/pub/openshift-v4/dependencies/%3Copsystem/latest/

is wrong.

It should be 
https://mirror.openshift.com/pub/openshift-v4/dependencies//rhcos/

An example:
https://mirror.openshift.com/pub/openshift-v4/dependencies//rhcos/4.7/
This is in production page too.

Thanks.

**Comment by codyhoag** [comment]
@tsze-redhat good catch on the link and file name tweaks! I've updated them. :+1: 

Can you confirm the latest changes?

**Comment by tsze-redhat** [comment]
LGTM. Thanks.

I assume the change will be picked up in 4.5/4.6 pages too, right?

**Comment by codyhoag** [comment]
@tsze-redhat Thanks! That's correct; this will apply for current 4.5-4.7 pages and the future 4.8 docs.

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Pull request merged**
