### PR TITLE
bug 1590940 fixing playbook paths

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1590940

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by jatanmalde** [comment]
+1 Kalexand Thanks for putting this.

**Comment by kalexand-rh** [comment]
Happy to help, @jatanmalde! I'll get this change live as soon as possible.

**Comment by kalexand-rh** [comment]
@gpei approved this PR in the source bug.

@openshift/team-documentation will you PTAL?

**Comment by bfallonf** [comment]
@kalexand-rh Seems good to me :taxi:

**Comment by kalexand-rh** [comment]
Thanks @bfallonf! Merging.

**Pull request merged**
