### PR TITLE
OSSM-6424: Incorrect procedure for installing the ossmconsole CR

### PR DESCRIPTION
**Pull request by gwynnemonahan**
[OSSM-6424](https://issues.redhat.com//browse/OSSM-6424): Incorrect procedure for installing the ossmconsole CR

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSSM-6424

Link to docs preview:
https://75738--ocpdocs-pr.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-kiali-ossmc-plugin.html#ossm-kiali-ossmc-plugin-install-web-console_ossm-kiali-ossmc-plugin 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Review by jeana-redhat — APPROVED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
