### PR TITLE
Osdocs 3228

### LINKED ISSUE #34745: [enterprise-4.7] Issue in file support/troubleshooting/troubleshooting-crio-issues.adoc
### Which section(s) is the issue in?

[Verifying CRI-O runtime engine status](https://docs.openshift.com/container-platform/4.7/support/troubleshooting/troubleshooting-crio-issues.html#verifying-crio-status_troubleshooting-crio-issues)

### What needs fixing?

Step _d_ is described as _Output a more detailed kubelet.service status summary:_ but then the command given is `systemctl status crio`

So the description probably just needs to change to something like _Output a more detailed crio.service status summary:_

### PR DESCRIPTION
**Pull request by JoeAldinger**
4.6+

[OSDOCS-3228](https://issues.redhat.com/browse/OSDOCS-3228)

**Preview:** https://deploy-preview-41162--osdocs.netlify.app/openshift-enterprise/latest/support/troubleshooting/troubleshooting-crio-issues.html

PTAL: @sunilcio can you make sure the change in command is correct, please? Thank you.

Fixes [issue](https://github.com/openshift/openshift-docs/issues/34745)

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
Looks like this fix should also be applied to 4.6, so adding that label as well. @JoeAldinger Let me know if this is okay with you, before I merge!

**Pull request merged**
