### PR TITLE
OCPGUBS-31937 HAProxy load interval limit

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.14, 4.15

Issue: https://issues.redhat.com/browse/OCPBUGS-31937

Link to docs preview: https://76775--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/network-configuration.html
https://76775--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/optimization/routing-optimization.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@ShudiLi please QE check

**Comment by ShudiLi** [comment]
/lgtm
@jmanthei done, thanks

**Comment by bscott-rh** [comment]
@jmanthei which versions should this apply to? I don't see it in the description.

**Comment by jmanthei** [comment]
@bscott-rh versions updated

**Pull request merged**
