### PR TITLE
SRVCOM-1451: Adding functions, install, CLI, and HA docs for OSD

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVCOM-1451

Applies for OCP 4.9, 4.10+

Direct preview links:
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/discover/serverless-functions-about.html
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/install/install-serverless-operator.html
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/admin_guide/serverless-ha.html#serverless-ha
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/install/installing-knative-serving.html
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/install/installing-knative-eventing.html#installing-knative-eventing
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/functions/serverless-functions-setup.html
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/functions/serverless-functions-getting-started.html#serverless-functions-getting-started
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/install/removing-openshift-serverless.html
- https://deploy-preview-42212--osdocs.netlify.app/openshift-dedicated/latest/serverless/cli_tools/installing-kn.html

### CODE REVIEW

**Comment by abrennan89** [comment]
Currently blocked awaiting https://github.com/openshift/openshift-docs/pull/42074 to merge, so that I can rebase and the links won't fail

**Comment by abrennan89** [comment]
NOTE: topicmap must be commented out before merge (until 1.21.0 release)

**Comment by jrangelramos** [comment]
lgtm
QE Approved

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
