### PR TITLE
Added statement about Visual Studio

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jerboaa FYI

**Comment by jerboaa** [comment]
LGTM. @tmds thoughts?

**Comment by tmds** [comment]
@ahardin-rh @jerboaa LGTM, the procedure for installing the SDK is the same for 1.0 and 1.1. So linking to a single one (e.g. 1.1) is enough.

**Comment by ahardin-rh** [comment]
@jerboaa @tmds Thanks! Updated.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/s2i_images/dot_net_core.adoc#using-images-using-dot-net-core[ S2I (Source-to-Image) -> .NET Core]
|Added a xref:../using_images/s2i_images/dot_net_core.adoc#dot-net-core-supported-versions[support statement] about Visual Studio 2017.
%

**Pull request merged**
