### PR TITLE
BZ:1902044 - Changing apiVersion in yaml for ClusterResourceQuota

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.6+
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1902044

Preview: https://deploy-preview-38212--osdocs.netlify.app/openshift-enterprise/latest/applications/quotas/quotas-setting-across-multiple-projects

Ready for QA: @wangke19 

For Peer Reviewers: Can you please add the labels 'enterprise-4.6', 'enterprise-4.7', 'enterprise-4.8' enterprise-4.9', enterprise-4.10' and 'Peer Review needed', Thank you!!

### CODE REVIEW

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Comment by wangke19** [comment]
@kelbrown20 For step 2 `Similarly, to select projects based on labels, run this command:` in page https://deploy-preview-38212--osdocs.netlify.app/openshift-enterprise/latest/applications/quotas/quotas-setting-across-multiple-projects, you also need to apply the change to section `
To select projects by label, provide a key-value pair by using the format --project-label-selector=key=value.`.

**Comment by kelbrown20** [comment]
@wangke19 Should be fixed and updated, thank you!

**Pull request merged**
