### PR TITLE
[enterprise-4.1] Hide elements from print

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Manual commit because of git conflict https://github.com/openshift/openshift-docs/pull/40242#issuecomment-1012664067

Reason for conflict: 
`_templates/_page_openshift.html.erb` is different in the `main` branch and the `enterprise-4.1` branch.

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@aireilly Can you please check and merge this one?

**Comment by aireilly** [comment]
@gaurav-nelson Unfortunately I don't have merge rights for the repo. You'll have to get someone on the core team to do this.

**Review by aireilly — APPROVED** [review]
LGTM

**Comment by gaurav-nelson** [comment]
@aireilly Do we still need this one? Or should I close it?

**Comment by aireilly** [comment]
Honestly, not sure. Looks like the original PR didn't get merged to 4.1 either: https://github.com/openshift/openshift-docs/pull/40242#issuecomment-1012664067

**Pull request closed without merging**
