### PR TITLE
Added information on a known issue with cluster loader

### PR DESCRIPTION
**Pull request by ahardin-rh**
@sjug As discussed earlier, PTAL.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Discussed with @sjug and got a :+1:

**Comment by ahardin-rh** [comment]
Received a QE :+1: in the BZ. 
@openshift/team-documentation Please peer review :heart_decoration:

**Review by kalexand-rh — COMMENTED** [review]
I'd change "are deploying" to "deploy" in two places, but otherwise LGTM

**Pull request merged**
