### PR TITLE
storage/persistent-storage-nfs: Link to RHEL 9 docs

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/openshift/openshift-docs/issues/66588

Version(s):
4.13+

Issue:
https://github.com/openshift/openshift-docs/issues/66588

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
N/A

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lpettyjo, will you PTAL at this PR?

**Review by jldohmann — APPROVED** [review]
LGTM! thanks 👍

**Pull request merged**
