### PR TITLE
[SRVOCF-569] Fix pipeline tasks links

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.30

Issue:
https://issues.redhat.com/browse/SRVOCF-569

Link to docs preview:
https://79927--ocpdocs-pr.netlify.app/openshift-serverless/latest/functions/serverless-functions-creating.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Review by skopacz1 — APPROVED** [review]
LGTM

**Review by skopacz1 — APPROVED** [review]
merge review LGTM

**Pull request merged**
