### PR TITLE
ocs 310 additions

### PR DESCRIPTION
**Pull request by cooktheryan**
Addition of links for ocs deployment for the openshift providers that would benefit from having OCS deployed.

@netzzer

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@cooktheryan, on a quick scan, this looks a lot like https://github.com/openshift/openshift-docs/pull/12906 . You could do one pr against master, and we could cherrypick it to both 3.10 and 3.11. Will you PTAL at my comments on that PR?

**Comment by kalexand-rh** [comment]
Gotcha. Our if statement usage doesn't cover that use case, and this is small enough usage that I don't think adding a variable makes sense. (Even if we used a variable, we'd still need different PRs to set it up.)

**Comment by cooktheryan** [comment]
@kalexand-rh I just realized I'm not sure my current plan of merging this to master may not work unless we cherry-pick immediately after as both PRs will be modifying the same file on master

**Comment by kalexand-rh** [comment]
@cooktheryan, close this one. I'll CP the other to 3.11 and then manually CP it to 3.10. I'll fix the link before I merge the 3.10 one.

**Comment by cooktheryan** [comment]
@kalexand-rh++

**Pull request closed without merging**
