### PR TITLE
4.5 RNs - oc commands and flags removed

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
@soltysh can you confirm? Thanks!

**Review by soltysh — APPROVED** [review]
/lgtm
Although I'm missing this comment https://github.com/openshift/openshift-docs/issues/19847#issuecomment-606540724 being mentioned in the release notes

**Comment by codyhoag** [comment]
@soltysh I went ahead and added a [commit](https://github.com/openshift/openshift-docs/pull/22390/commits/96ee602cc14601076dda947c930dee6793979718) for https://github.com/openshift/openshift-docs/issues/19847#issuecomment-606540724 too in this PR. Can you sign off on that one too? Thanks!

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Pull request merged**
