### PR TITLE
BZ1786998 Add master-restart api command

### PR DESCRIPTION
**Pull request by bobfuru**
Added `#master-restart api` command per [BZ1786998](https://bugzilla.redhat.com/show_bug.cgi?id=1786998) (master-3, enterprise-3.11).

@jianlinliu and @openshift/team-documentation PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
@bobfuru Looks like it's against the 3.11 branch, but labeled for master, 4.2, and 4.3

**Comment by bobfuru** [comment]
> @bobfuru Looks like it's against the 3.11 branch, but labeled for master, 4.2, and 4.3

Thanks, that's correct! I fixed the labels.

**Comment by bobfuru** [comment]
@jianlinliu BUMP - PTAL, thanks!

**Comment by jianlinliu** [comment]
@xingxingxia ^^

**Comment by xingxingxia** [comment]
The PR LGTM.

**Pull request merged**
