### PR TITLE
Issue #28046, udpated instances of console.operator.openshift.io

### PR DESCRIPTION
**Pull request by ahardin-rh**
Addresses https://github.com/openshift/openshift-docs/issues/28046

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@spadgett PTAL. This issue was filed for 4.6, but can you please confirm that it should be backported to earlier versions too? Thanks!

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by ahardin-rh** [comment]
@yapei Please provide QE review. Thanks!

**Comment by ahardin-rh** [comment]
@spadgett PTAL

**Comment by yapei** [comment]
@ahardin-rh May I know why we updated to `consoles.operator.openshift.io` ?

**Comment by ahardin-rh** [comment]
@yapei The usage of console.operator.openshift.io was reported as incorrect in https://github.com/openshift/openshift-docs/issues/28046

**Comment by yapei** [comment]
thank you @ahardin-rh  the changes look good to me

**Review by yapei — APPROVED** [review]
/lgtm

**Pull request merged**
