### PR TITLE
GH53271: Remove Ansible automation section

### LINKED ISSUE #53271: [enterprise-4.11] Issue in file virt/virtual_machines/advanced_vm_management/virt-automating-management-tasks.adoc
### Which section(s) is the issue in?

Documentation[ OpenShift Container Platform ](https://docs.openshift.com/container-platform/4.11/welcome/index.html)[Virtualization](https://docs.openshift.com/container-platform/4.11/virt/virtual_machines/virt/about-virt.html) Automating management tasks

### What needs fixing?

This whole section "Automating management tasks" is not supported and should be either removed, or alternativly, marked as community supported.

CC: @fabiand @geetikakay @0xFelix

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.11+

Issue: [GH53271](https://github.com/openshift/openshift-docs/issues/53271)

Link to docs preview: NA

QE review: NA

### CODE REVIEW

**Comment by apinnick** [comment]
@dominikholler @fabiand @geetikakay @0xFelix
PR for issue 53271

**Comment by apinnick** [comment]
Ready for peer review by ALIGNED peer review squad.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
