### PR TITLE
Document Operator Management state for NTO.

### PR DESCRIPTION
**Pull request by jmencak**
Document the Operator Management state and fix Tuned daemon/profile capitalization.

### CODE REVIEW

**Comment by jmencak** [comment]
/cc @ahardin-rh 
The management state is a 4.6 feature only.  The capitalization of Tuned (discussed by Tuned devels) could be picked to older branches.  As for capitalization, I believe a full review is needed wrt. Pod/Node.  See https://kubernetes.io/docs/contribute/style/style-guide/

Unfortunately, neither k8s nor OpenShift docs seem to follow there guidelines strictly.

**Comment by jmencak** [comment]
/cc @skordas 
for QE review.

**Comment by ahardin-rh** [comment]
@jmencak These changes LGTM. I will work in separate PRs to do some style cleanup for Tuned instances, as well as Pod/pod usage. Thanks for this!

**Comment by ahardin-rh** [comment]
@skordas Can you please provide QE review? Thanks!

**Review by skordas — APPROVED** [review]
LGTM

**Comment by jmencak** [comment]
@ahardin-rh thanks!  Could you please /cc me on the future [Pp]od/[Nn]ode PR for review?  Thanks!

**Pull request merged**
