### PR TITLE
Bug 1512781, updated the Scenario math

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1512781

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@derekwaynecarr PTAL

**Comment by derekwaynecarr** [comment]
LGTM

Apologies for delay.

**Comment by ahardin-rh** [comment]
@derekwaynecarr No worries. Thanks so much!

**Comment by ahardin-rh** [comment]
Moved to QE for review. @openshift/team-documentation Please peer review.

**Comment by mburke5678** [comment]
@ahardin-rh LGTM

**Comment by ahardin-rh** [comment]
QE approved in the BZ

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/out_of_resource_handling.adoc#admin-guide-handling-out-of-resource-errors[Handling Out of Resource Errors]
|Adjusted the math in the xref:../admin_guide/out_of_resource_handling.adoc#out-of-resource-schedulable-resources-and-eviction-policies[Example Scenario].
%

**Pull request merged**
