### PR TITLE
[enterprise-4.11]  Replace 'id_rsa' with 'ssh-privatekey'

### PR DESCRIPTION
**Pull request by mahmut-Abi**
when create the secret type of 'kubernetes.io/ssh-auth' is required the 'ssh-privatekey' value.
--type=kubernetes.io/ssh-auth requires the 'ssh-privatekey' value in secret.

Version(s):

[enterprise-4.11] 

Issue:

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by mahmut-Abi** [comment]
how to merge？

**Comment by rolfedh** [comment]
Thanks @mahmut-Abi. I'll ask for this to be reviewed and approved.
/assign @jitendar-singh

**Comment by coreydaley** [comment]
approved

**Pull request merged**
