### PR TITLE
OSDOCS-2370 Set mirror/download links to point to updated version

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2370

Previews (subset):
- https://deploy-preview-36297--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#creating-machines-platform-agnostic
- https://deploy-preview-36297--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-user-infra-machines-pxe_installing-platform-agnostic
- https://deploy-preview-36297--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli
- https://deploy-preview-36297--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster.html#update-upgrading-web_updating-cluster

### CODE REVIEW

**Comment by codyhoag** [comment]
@gpei can you confirm? Thanks!

**Comment by gpei** [comment]
@codyhoag hi, one concern for change is:
If we use `latest` in 4.9 doc, when 4.10 was released, we still need to change it back to `4.9`, right?

**Comment by codyhoag** [comment]
@gpei that's a really great point. I have reintroduced the explicit `4.9` version number in the mirror links. Can you verify this change?

I will manually backport this change for 4.6-4.8 as well, since a subset of the mirror links were updated with `latest` recently. We'll need to switch them back.

**Comment by gpei** [comment]
LGTM

**Comment by sagidlow** [comment]
LGTM

**Pull request merged**
