### PR TITLE
Update configuring_authentication.adoc

### PR DESCRIPTION
**Pull request by csheremeta**
Fixed typo caused by strange parsing of underscores

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@csheremeta Weird! It should be displaying this correctly. 
@openshift/team-documentation any idea why this is not rendering correctly?

**Comment by mburke5678** [comment]
@vikram-redhat For some reason, it is interpreting the underscore in `_<identity_provider_type>` as a closing mark: </em>. Not sure what to do about it yet. 
```copied to the <strong><em>/etc/origin/master/&lt;identity_provider_name&gt;</em>&lt;identity_provider_type&gt;_ca.crt_</strong> file. The```

**Comment by mburke5678** [comment]
@vikram-redhat @csheremeta See: https://github.com/openshift/openshift-docs/pull/15080/

**__/etc/origin/master/<identity_provider_name>_<identity_provider_type>_ca.crt__**

**Comment by csheremeta** [comment]
lgtm

**Comment by vikram-redhat** [comment]
Closing as Michael has the fix in #15080

**Pull request closed without merging**
