### PR TITLE
OADP-3083 Removing redundant note

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/OADP-3083

OADP 1.3

OCP 4.14+

Preview: https://67911--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/data-mover-intro

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by JoeAldinger** [comment]
@sbeskin-redhat it looks like there are merge conflicts. Feel free to ping me when you get them sorted.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request closed without merging**
