### PR TITLE
OSDOCS#6653: Adding notice of future Kubernetes API removal in 4.16

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-6653

Link to docs preview:
https://67990--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-future-removals

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@sanchezl @wangke19 Can you please review? This PR adds a warning to the 4.15 release notes about the Kubernetes API removals that will be coming in 4.16.

https://67990--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-future-removals

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by sanchezl — APPROVED** [review]

**Pull request merged**
