### PR TITLE
Add instructions on custom router service ports and update usage on how to force routes to a custom routing subdomain

### PR DESCRIPTION
**Pull request by ramr**
As per bugz: https://bugzilla.redhat.com/show_bug.cgi?id=1268904 and cleanup usage on how to force routes to a specific subdomain.

@bfallonf / @adellape  PTAL  thx.

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr This OK, but will probably require a followup from us on the docs team.

Having Travis issues though. Would a re-push fix them?

**Comment by ramr** [comment]
@bfallonf  I tried earlier but the error seems to be with the bundler/ruby version. Trying once again ...

**Comment by ramr** [comment]
pushed once again to get travis checks to run.

**Comment by bfallonf** [comment]
@ramr Cool. Thanks!

**Comment by adellape** [comment]
@ramr This is for https://github.com/openshift/origin/pull/7704, correct? Those commits only appear to be in the OSE 3.2 build, so I'm adjusting the branch labels and milestone here. Please correct me if I'm wrong.

cc @bfallonf

**Comment by ramr** [comment]
@adellape correct. It is for changes in OSE 3.2

**Pull request merged**
