### PR TITLE
OSSM-5604: resolve link to modular doc

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s):

Issue: https://issues.redhat.com/browse/OSSM-5604

Link to docs preview:
https://69841--ocpdocs-pr.netlify.app/openshift-service-mesh/latest/install/ossm-installing-openshift-service-mesh.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by aireilly** [comment]
This pull request has been repointed to target service-mesh-docs-main. service-mesh-docs is no longer in use.

**Comment by rh-tokeefe** [comment]
retest

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
