### PR TITLE
OCPBUGS#13339: Update 'config' to 'config/'

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-13339

Link to docs preview: https://59982--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-project-layout.html#osdk-helm-project-layout_osdk-helm-project-layout

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
> /lgtm but the docs link can't be open

The preview is generated now

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Pull request merged**
