### PR TITLE
Drain master node doesn't succeed without --force option

### PR DESCRIPTION
**Pull request by mburke5678**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-10424

Link to docs preview:

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mburke5678** [comment]
@lyman9966 You reviewed the [PR that added the command in question](https://github.com/openshift/openshift-docs/pull/65094/files#diff-88abd258477ab17c0d07dc30ebcd51d875f8346620fd47aac64a5f56765f5845R65) for @nalhadef last September. Would you be the appropriate QE resource to review this requested change? Thank you in advance.

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
