### PR TITLE
ibm-sync-main: Synced the main Welcome page with 4.15

### PR DESCRIPTION
**Pull request by dfitzmau**
[INTERNAL FIX]

Version(s):
main, 4.15

Link to docs preview:
https://69410--ocpdocs-pr.netlify.app/openshift-enterprise/latest/welcome/

QE review:
- [x] QE not required

Additional information:

### CODE REVIEW

**Comment by dfitzmau** [comment]
Issues with diff of `main` to `enterprise-4.14`. 

Screenshot from 2023-12-15 15-32-42

**Comment by dfitzmau** [comment]
> Issues with diff of `main` to `enterprise-4.14`.
> 
> Screenshot from 2023-12-15 15-32-42

Tagged Silke about the KVM entry
Tagged Mike about BM
Tagged Max about the RHCOS entry

**Comment by jeana-redhat** [comment]
@kalexand-rh FYI I put this in continuous release instead of 4.15 milestone because it's fixing an issue with the 4.14 version being out of sync (rather than an actual 4.15 specific effort). If that's using the milestones wrong, obvs feel free to swap :)

**Pull request merged**
