### PR TITLE
change private to public word

### PR DESCRIPTION
**Pull request by Amrita42**
- Change of word private to public in the following:
- https://docs.openshift.com/rosa/rosa_install_access_delete_clusters/rosa-aws-privatelink-creating-cluster.html
- QE not required
- [Issue](https://github.com/openshift/openshift-docs/issues/51347)
- [Preview](https://51365--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-aws-privatelink-creating-cluster.html)

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
This looks good! No changes recommended. I think the preview link is incorrect in the original comment on the PR - should be https://51365--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-aws-privatelink-creating-cluster.html (current one gives a 404)

**Comment by JStickler** [comment]
@Amrita42 which branches do you want this to go into?

**Comment by Amrita42** [comment]
@JStickler my first working on ROSA docs, I dont see any version mentioned in docs.openshift . @pneedle-rh can you please help?

**Comment by mjpytlak** [comment]
I picked up the merge request, but will hold off until we clarify which branches this should go into.

**Comment by mjpytlak** [comment]
I picked up the merge request, but will hold off until we clarify which branches this should go into.

**Comment by Amrita42** [comment]
@bmcelvee can you help with the version , as its my firs PR for ROSA and I dont see any version on docs.openshift.

**Comment by bmcelvee** [comment]
Hi @Amrita42, certainly! The versions for ROSA and OSD are 4.11 and 4.12. I'm adding the labels now.

**Pull request merged**
