### PR TITLE
OCPBUGS#13804: Removed support of standardSSD_LRS disk type from Azure Stack Hub

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.10+

Issue:
This issue addresses [ocpbugs-13804](https://issues.redhat.com/browse/OCPBUGS-13804).

Link to docs preview:

Installation configuration parameters > [Additional Azure Stack Hub configuration parameters](https://62526--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-default.html#installation-configuration-parameters-additional-azure-stack-hub_installing-azure-stack-hub-default)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mjpytlak** [comment]
@r4f4 Removed `standard_LRS` disk type from ASH content. When you have a moment, PTAL.

**Comment by mjpytlak** [comment]
@r4f4 Removed support for the `tandardSSD_LR` disk type from the ASH docs.

I noticed that https://github.com/openshift/openshift-docs/pull/62526/files#diff-14ebe576efb84b2f58b32a0de2996fced237204ae9b091e3cafbd40b65c1ef31L1911 never listed `standard_LRS` Should it be added?

**Comment by r4f4** [comment]
> I noticed that https://github.com/openshift/openshift-docs/pull/62526/files#diff-14ebe576efb84b2f58b32a0de2996fced237204ae9b091e3cafbd40b65c1ef31L1911 never listed `standard_LRS` Should it be added?

@patrickdillon Mike raises a good point: do we want to add `standard_LRS` as a supported type for controlPlane nodes in AzureStack? In theory it is supported but maybe it was not in the docs because it's not recommended?

**Review by r4f4 — COMMENTED** [review]
The changes regarding `standardSSD_LRS` lgtm.

**Comment by mjpytlak** [comment]
@jinyunma Docs are ready for QE review. PTAL.

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
lgtm

**Comment by mjpytlak** [comment]
> Mike raises a good point: do we want to add `standard_LRS` as a supported type for controlPlane nodes in AzureStack? In theory it is supported but maybe it was not in the docs because it's not recommended?

@r4f4 @patrickdillon If we believe that `standard_LRS` should be added as a supported type for controlPlane nodes, I will open up a new ticket. Given that this was beyond the scope of the original PR, I am going to merge this fix so the current docs are technically accurate.

**Pull request merged**
