### PR TITLE
BZ-1662448: Fixing typo in anchor

### PR DESCRIPTION
**Pull request by bergerhoffer**
@openshift/team-documentation for peer review

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bergerhoffer** [comment]
Merging as peer review was completed and no QE is required.

**Comment by vikram-redhat** [comment]
@bergerhoffer - thanks. Great work. Just missing the milestone, which will be next release for this PR.

**Comment by bergerhoffer** [comment]
Sorry @vikram-redhat, forgot about that. Do you think you could go over what the milestones are used for? When I asked a few weeks ago, people didn't seem to be sure if they were still used. I thought the label of the branch/enterprise-<version> indicated the release.

And if milestones are still used, can you explain the difference between "future" and "next"? Thanks!

**Comment by kalexand-rh** [comment]
@bergerhoffer, Vikram will have more details, but he uses them to help track what's going into releases. He confirmed in last week's meeting that he still wants us to use them.

"future" is for something that's not in an active collection, and "next" is for anything released that'll go live in the next build.

**Comment by bergerhoffer** [comment]
Thanks @kalexand-rh, so right now, next is anything 3.x, and future is 4.0+?

**Comment by kalexand-rh** [comment]
@bergerhoffer, yup!

**Comment by vikram-redhat** [comment]
Thanks @kalexand-rh :)

To add some more detail, we use a combination of milestones and labels at release time to make sure we have merged everything that was part of a release, and then move all PRs for a release into an archived milestone. For example, here is the milestone for the 3.11 release that contains all the PRs we merged for the release as it happened on the release day: https://github.com/openshift/openshift-docs/milestone/187?closed=1. 

All older closed milestones are here: https://github.com/openshift/openshift-docs/milestones?state=closed. 

So in case we ever had to roll back a release because stuff happened, we had a list of PRs to roll back. 

We used to use milestones and labels more extensively when we used to have scheduled weekly releases, but they are still handy.

Hope this helps. @bergerhoffer let me know if you want more details.

**Comment by bergerhoffer** [comment]
Great, thanks a lot for the explanation @vikram-redhat! That makes sense.

**Pull request merged**
