### PR TITLE
OSDOCS-4339: Added gcp to platform parameter

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.8+

Issue:
This PR addresses [osdocs-4339.](https://issues.redhat.com/browse/OSDOCS-4339) I added `gcp` as a supported value of the `platform` parameter.

Link to docs preview:
Installation configuration parameters > [Required configuration parameters](https://51756--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters-required_installing-gcp-customizations)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@jianli-wei Ready for QE review. PTAL. Thank you.

**Comment by mjpytlak** [comment]
@jianli-wei Following up on this request for review. PTAL. I believe we are good to go. Thank you for pointing out the gap in the doc.

**Comment by kalexand-rh** [comment]
@jianli-wei will you PTAL?

**Comment by kalexand-rh** [comment]
Only versions 4.8+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Pull request merged**
