### PR TITLE
log aggregation created pvcs start with name logging-es-0 and not logging-es-1 

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1585762

### CODE REVIEW

**Comment by mburke5678** [comment]
@sosiouxme 
Luke, it appears you added some info to the Aggregated Logging topic that included: 
"each PVC name will have a sequence number added to it, so `logging-es-1`, `logging-es-2`, etc."[1]

A BZ [2] suggests that the naming starts at `logging-es-0` not `logging-es-1`. Can you comment on whether the BZ is correct?

[4] https://github.com/openshift/openshift-docs/pull/2538/files#diff-0bd2e2c1a5da6f157682d4e95ecea473R454
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1585762

cc. @ahardin-rh

**Comment by mburke5678** [comment]
@sosiouxme PTAL

**Comment by mburke5678** [comment]
Closing in favor ot https://github.com/openshift/openshift-docs/pull/10540

**Comment by mburke5678** [comment]
@sosiouxme 
Luke, it appears you added some info to the Aggregated Logging topic that included: 
"each PVC name will have a sequence number added to it, so `logging-es-1`, `logging-es-2`, etc."[1]

A BZ [2] suggests that the naming starts at `logging-es-0` not `logging-es-1`. Can you comment on whether the BZ is correct?

[4] https://github.com/openshift/openshift-docs/pull/2538/files#diff-0bd2e2c1a5da6f157682d4e95ecea473R454
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1585762

cc. @ahardin-rh

**Comment by sosiouxme** [comment]
@mburke5678 yeah, that was a long time ago and things changed with the ansible deployer! Which I think was with 3.7. The bug report looks correct to me. Thanks for checking.

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Tiny change

**Review by kalexand-rh — COMMENTED** [review]
Should it be `logging-es`? Otherwise, LGTM

**Comment by kalexand-rh** [comment]
@mburke5678, that's it! Thanks!

**Pull request merged**
