### PR TITLE
cgroupv2: update the test conditions for cgroup version

### PR DESCRIPTION
**Pull request by haircommander**
Version(s):

Issue:
https://issues.redhat.com/browse/OSDOCS-8443

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@sunilcio, will you please confirm this change?

**Comment by mburke5678** [comment]
@haircommander Thanks for catching this. However, as we dragged our heels on this, someone else came along and made the fix. 
Closing as duplicate: https://github.com/openshift/openshift-docs/pull/68089

**Pull request closed without merging**
