### PR TITLE
[OSDOCS-8730]: Release note about hosted control planes on OpenShift Virtualization

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.14z

Issue: https://issues.redhat.com/browse/OSDOCS-8730

Link to docs preview: https://67835--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-known-issues (Ctrl+F for OCPBUGS-23208)

QE review:
- [x] QE has approved this change.

Additional information: This PR has been reviewed and approved by all stakeholders per the OCP docs change management process.

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by xltian** [comment]
lgtm

**Comment by zanetworker** [comment]
lgtm

**Comment by sjstout** [comment]
lgtm

**Comment by kalexand-rh** [comment]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
