### PR TITLE
Bug 1498147 Changed serviceaccounts to serviceaccount

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1498147

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL. Also, can someone help me understand why there are 3 commits? "Changed serviceaccounts to serviceaccount" should be the only commit message. The other 2 are from a different PR. Thanks.

**Comment by bfallonf** [comment]
@tmorriso-rh Hmm hard to tell. Is there stuff in the PR that shouldn't be there? Maybe when you squashed the commits, you squashed two too far? (I've done that before)

Maybe ping @adellape when you're both around tomorrow. He's the smart one :nerd_face:

**Comment by tmorriso-rh** [comment]
Thanks @bfallonf. Yes, the install_config/install/host_preparation.adoc section should not be included in this PR. 

@adellape Can you take a look at this when you have a free moment? Thanks!

**Comment by vikram-redhat** [comment]
Hey @tmorriso-rh - I think you have squashed too many commits in this one. There are two things you can do here:

1. Do another interactive rebase and remove the first two commits (the ones that you don't want) and then do a force push to your repo.

This should help: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2. Just close this PR and start a new one with just the changes you want.

PS: Please add a description to the title of the PR other than just the BZ number.

**Comment by tmorriso-rh** [comment]
Thanks @vikram-redhat. I made those changes.

**Comment by vikram-redhat** [comment]
Thanks @tmorriso-rh - lgtm.

**Comment by tmorriso-rh** [comment]
[rev_history]
|xref:../dev_guide/service_accounts.adoc#dev-sa-user-names-and-groups[Service Accounts -> User Names and Groups]
| Changed `serviceaccounts` to `serviceaccount` in the xref:../service_accounts.adoc#dev-sa-user-names-and-groups[User Names and Groups] section.
%
|xref:../dev_guide/service_accounts.adoc#dev-sa-user-names-and-groups[Service Accounts -> User Names and Groups]
| Changed `serviceaccounts` to `serviceaccount` in the xref:../service_accounts.adoc#dev-sa-user-names-and-groups[User Names and Groups] section.
%

**Comment by tmorriso-rh** [comment]
@ahardin-rh Ashley, can you please review the revision history for this PR? Thanks!

**Comment by ahardin-rh** [comment]
LGTM! Well done! 🎈

**Comment by tmorriso-rh** [comment]
https://github.com/openshift/openshift-docs/pull/6014

**Comment by vikram-redhat** [comment]
Hey @tmorriso-rh , the revision history for this contained an invalid link in the second rev history (for the admin guide). I think it copied the same content from the dev guide revision history. dev-sa-user-names-and-groups only exists in the dev guide, not in the admin guide. I have fixed it manually in the release today across the branches. But can you fix it here? (You should just be able to edit it in the GUI here).

**Comment by tmorriso-rh** [comment]
@vikram-redhat I corrected the revision history in the GUI. Thanks.

**Pull request merged**
