### PR TITLE
Catalog changed to Operators in console

### PR DESCRIPTION
**Pull request by apinnick**
Was: Catalog > Installed Operators. Changed to Operators > Installed Operators

[BZ1769290](https://bugzilla.redhat.com/show_bug.cgi?id=1769290)

### CODE REVIEW

**Comment by apinnick** [comment]
@peer-review-squad Ready for review. This is for 4.2 only. It's a UI update for 4.2 web console.

**Review by adellape — APPROVED** [review]
:+1:

**Pull request merged**
