### PR TITLE
Conditionally set remote user header

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by bfallonf** [comment]
@liggitt I saw the email that led to this. I don't mind merging, but do you know which releases this impacted? 3.2 and later, right?

**Comment by liggitt** [comment]
Applies to whatever versions included `RequestHeader set` instructions, not sure which did

**Comment by bfallonf** [comment]
Looks like 3.2. Thanks @liggitt . I'll merge this.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/advanced_ldap_configuration/sssd_for_ldap_failover.adoc#setting-up-for-ldap-failover[Advance LDAP Configuration -> Setting up SSSD for LDAP Failover]
|Fixed error in xref:../install_config/advanced_ldap_configuration/sssd_for_ldap_failover.adoc#phase-2-step-3-apache-configuration[Step 3: Apache Configuration] section.
%

**Pull request merged**
