### PR TITLE
SRVCOM-1667: Fix the mTLS entry in the feature matrix

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+

https://issues.redhat.com/browse/SRVCOM-1667

Preview: https://deploy-preview-41735--osdocs.netlify.app/openshift-enterprise/latest/serverless/serverless-release-notes.html#serverless-deprecated-removed-features_serverless-release-notes

### CODE REVIEW

**Comment by rh-max** [comment]
@nainaz @abrennan89 Could you PTAL?

**Comment by abrennan89** [comment]
I'd probably say "Service Mesh mTLS" per https://docs.openshift.com/container-platform/4.9/serverless/admin_guide/serverless-ossm-setup.html#serverlesss-ossm-external-certs_serverless-ossm-setup but I'm not an SME. Please ask @nak3 or QE what they think on how to word this.

**Comment by nak3** [comment]
Both "Service Mesh mTLS" and "mTLS with Service Mesh" are sound good to me. So it is better to use "Service Mesh mTLS" for consistency?

**Comment by alanfx** [comment]
Looks fine to me, @rh-max QE approved

**Comment by rh-max** [comment]
Thanks everybody! @ctauchen , could you please merge & CP? Thanks.

**Pull request merged**
