### PR TITLE
updating cloud.redhat.com links

### PR DESCRIPTION
**Pull request by kalexand-rh**
Per https://github.com/openshift/openshift-docs/pull/16894#discussion_r342632143

@wking, @reestr, FYI

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, PTAL?

**Comment by ahardin-rh** [comment]
Looks good!

**Comment by vikram-redhat** [comment]
@kalexand-rh I am guessing the conflicts here were due to the release notes modules?

**Comment by kalexand-rh** [comment]
@vikram-redhat, for 4.3, yes. For 4.1, there were also some modules that didn't exist. (And this did make it in 4.3 - I accidentally linked it to the wrong PR. My apologies!)

**Pull request merged**
