### PR TITLE
Bug 1556810 Updates to Curator

### PR DESCRIPTION
**Pull request by bmcelvee**
Follow-up to: https://github.com/openshift/openshift-docs/pull/8164

### CODE REVIEW

**Comment by bmcelvee** [comment]
@josefkarasek PTAL :snowflake:

**Comment by josefkarasek** [comment]
@bmcelvee please also explain the regex part of the mentioned example configuration file as I outlined in https://github.com/openshift/openshift-docs/pull/8164#discussion_r175398927

**Comment by bmcelvee** [comment]
@josefkarasek PR updated. Is this along the lines of what you had in mind? Thanks!

**Comment by vikram-redhat** [comment]
@josefkarasek - can you please have another look at this PR?

**Comment by bmcelvee** [comment]
@josefkarasek, these changes may not still be relevant with the updates to Curator. If a separate PR needs to be opened to add these to 3.9 please let me know. Thanks!

**Pull request closed without merging**
