### PR TITLE
added control plan in C and removed k8s control plane

### PR DESCRIPTION
**Pull request by Amrita42**
Added **control plane** term in the C section and removed **k8s control plane** term.

### CODE REVIEW

**Comment by Amrita42** [comment]
@bobfuru @bergerhoffer ptal

**Review by bergerhoffer — COMMENTED** [review]
LGTM! Thanks for the update!

@bobfuru want to confirm as well?

**Comment by bobfuru** [comment]
LGTM, thank you!

**Comment by Amrita42** [comment]
Thank you both :) please merge.

**Pull request merged**
