### PR TITLE
Removed NoVolumeNodeConflict from scheduler docs

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1549748

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm from tech side

**Comment by mburke5678** [comment]
@wmengRH Can you assign someone to look at these very minor changes?

**Comment by wmengRH** [comment]
@wjiangjay  help review. Thanks.

**Comment by wjiangjay** [comment]
For scheduler part, LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation XXXXS change. PTAL

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
