### PR TITLE
added ec2:DeleteSecurityGroup to aws permissions

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1577239

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
minor change no peer reviews required.

**Comment by gaurav-nelson** [comment]
@chao007 @bostrt PTAL 
Preview: https://bug1577239-fixes--gnelson-preview.netlify.com/openshift-enterprise/(head%20detached%20at%20fetch_head)/install_config/configuring_aws.html#configuring-aws-permissions

**Comment by cooktheryan** [comment]
:+1:

**Comment by chao007** [comment]
LGTM

**Comment by bostrt** [comment]
:+1:

**Pull request merged**
