### PR TITLE
Add warning when using NetworkPolicy with hostNetwork

### PR DESCRIPTION
**Pull request by sfowl**
This warning applies to all OpenShift versions, I'll make a separate PR for 3.x.

### CODE REVIEW

**Comment by sfowl** [comment]
@juanluisvaladas @danwinship

**Comment by danwinship** [comment]
lgtm

**Comment by xltian** [comment]
@zhaozhanqi  can your team review this one?

**Comment by vikram-redhat** [comment]
@jboxman note if a followup needs to be done.

**Pull request merged**
