### PR TITLE
TRACING-2643, fixing typo, addressing late review comment.

### PR DESCRIPTION
**Pull request by JStickler**
This PR fixes a copy/paste error in a variable and addresses some review comments on #45350

Version(s): 4.6 - 4.11

Issue: [TRACING-2635](https://issues.redhat.com/browse/TRACING-2635) 

Link to docs preview:  http://file.bos.redhat.com/jstickle/TRACING-2635/distr_tracing/distributed-tracing-release-notes.html

QE review - jkandasa
Peer review - jc-berger

### CODE REVIEW

**Review by jkandasa — APPROVED** [review]
Thanks @JStickler, LGTM :+1:

**Review by jc-berger — APPROVED** [review]
/lgtm 

consulted openshift checklist when conducting this peer review: https://docs.google.com/document/d/1WN7k72PKxcPA__erp5TK-CefmS_sVwE3r40PvpmNk3E/edit#heading=h.mgz8v4w1kg86

**Pull request merged**
