### PR TITLE
Updates manifest listed images on image streams from TP to GA

### PR DESCRIPTION
**Pull request by stevsmit**
Requires change management

Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-6379

Link to docs preview:
https://stevsmit.github.io/openshift-docs/note-change/ocp-4-13-release-notes.html#ocp-4-13-images

Change management acks: 
* Engineering (Flavian Missi)
* Project Manager (Daniel Messer)
* Content Strategist (Ashley Hardin)
* QE (Xiujuan Wang)
* Product Experience (Eric Rich)

Additional information:

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM from the strategy side :rocket:

**Comment by xiuwang** [comment]
LGTM

**Review by opayne1 — COMMENTED** [review]
@stevsmit I didn't see a preview, but it looks good to me without looking at one!

**Comment by stevsmit** [comment]
Included a preview for merge review.

**Comment by mburke5678** [comment]
@stevsmit Do we have, or need, acks from Engineering and PM before merging?

**Comment by stevsmit** [comment]
@mburke5678

Hi,

Engineering = Flavian Missi
PM = Daniel Messer

Apologies. They ack'd the PR in Slack. It's written in the PR description above.

**Comment by mburke5678** [comment]
@stevsmit My apologies, actually. I assumed the list of names was asking folks to ack.

**Pull request merged**
