### PR TITLE
Fix the documentation of \w expression modifier

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
This is related to https://github.com/openshift/origin/pull/3477

**Comment by adellape** [comment]
@mfojtik This can use a rebase.

**Comment by mfojtik** [comment]
@adellape thanks! fixed

**Comment by adellape** [comment]
@mfojtik Oh sorry, https://github.com/openshift/openshift-docs/pull/636 (which prompted the rebase) moved the deeper parameters discussion into the `architecture/core_concepts/templates` topic. You could add just the `\w` bits into that topic.

**Comment by mfojtik** [comment]
@adellape oh I see it now, will do :)

**Comment by adellape** [comment]
@mfojtik The typo in the mongodb topic was fixed in https://github.com/openshift/openshift-docs/pull/659 (merged), BTW, so it doesn't need to be addressed here anymore.

**Pull request closed without merging**
