### PR TITLE
OCPBUGS-8831: Add back in note about egress policy types

### PR DESCRIPTION
**Pull request by jab-rh**
This seems to have gone missing at some point, so adding it back in.

- https://issues.redhat.com/browse/OCPBUGS-8831

Version(s): 4.10+

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@anuragthehatter, this note went missing at some point; this adds it back in. Does OpenShift SDN still not support egress?

Thanks!

**Comment by kalexand-rh** [comment]
Only versions 4.11+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Comment by jab-rh** [comment]
@weliang1, what do you think? Thanks!

**Comment by zhaozhanqi** [comment]
https://issues.redhat.com/browse/OCPBUGS-8831 this only need to fix in previous version < 4.10 for openshift-sdn
from 4.10 and later, egress type in networkpolicy should be supported on openshift-sdn

**Pull request closed without merging**
