### PR TITLE
OBSDOCS-1386: Logging Z-Stream Release Notes - 5.6.25

### PR DESCRIPTION
**Pull request by eromanova97**
Version for cherry-picking`enterprise-4.12`

Issue: https://issues.redhat.com/browse/OBSDOCS-1386

Link to docs preview: https://83933--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-6-release-notes.html#cluster-logging-release-notes-5-6-25_logging-5-6-release-notes

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kabirbhartiRH** [comment]
LGTM

**Review by JoaoBraveCoding — APPROVED** [review]
/lgtm

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
