### PR TITLE
Updated the wording in the section "About Red Hat OpenShift GitOps".

### PR DESCRIPTION
**Pull request by LunguTheEngineer**
- Jira issue: [OCPBUGS-12803](https://issues.redhat.com/browse/OCPBUGS-12803)
- CherryPick versions: gitops-docs-1.9, gitops-docs-1.0 and gitops-docs-1.11 branches
- Doc preview: [About GitOps](https://70716--docspreview.netlify.app/openshift-gitops/latest/understanding_openshift_gitops/about-redhat-openshift-gitops)
- OCP team: DevTools
- SME reviews by: @reginapizza 
- QE reviews by: @varshab1210 
- Peer reviews by:

### CODE REVIEW

**Review by reginaelyse — APPROVED** [review]

**Comment by varshab1210** [comment]
LGTM, thanks

**Pull request merged**
