### PR TITLE
Fix scheduler predicate/priority examples

### LINKED ISSUE #12715: [enterprise-3.10] Edit suggested in file admin_guide/scheduling/scheduler.adoc
### Which section(s) is the issue in?
Configurable Predicates & Priorities

### What needs fixing?

ServiceAffinity example should have closing structures?
```
         "name":"ZoneAffinity",
         "argument":{
            "serviceAffinity":{
               "labels":[
                  "rack"
```
Should be...
```
        "name":"ZoneAffinity",
        "argument":{
            "serviceAffinity":{
                "labels":[
                    "rack"
                ]
            }
        }
```

The LabelsPresence example is not valid json
```
         "name":"RackPreferred",
         "argument":{
            "labelsPresence":{
               "labels":[
                  "rack"
            "labelsPresence:"{
                "labels:"[
                  "region"
                 ],
                "presence": true
            }
         }
      }
   ],
```
Should be... (assuming the desire is to show off multiple labels)
```
        "name":"RackPreferred",
        "argument":{
            "labelsPresence":{
                "labels":[
                    "rack",
                    "region"
                ],
                "presence": true
            }
        }
```

The ServiceAntiAffinity priority does not accept a list of labels (only a single label). Also the weight needs to be an integer not a string. Also the example has 'serviceAffinity' instead of 'serviceAntiAffinity'.
The definition...
```
"priorities":[
      {
         "name":"<name>", 
         "weight" : "1" 
         "argument":{
            "serviceAntiAffinity":{
               "label":[
                  "<label>" 
               ]
            }
         }
      }
   ]
```
Should be...
```
"priorities":[
    {
        "name":"<name>", 
        "weight" : 1
        "argument":{
            "serviceAntiAffinity":{
                "label":[
                    "<label>" 
                ]
            }
        }
    }
]
```

The example...
```
         "name":"RackSpread", 
         "weight" : "1"     
         "argument":{
            "serviceAffinity":{
               "label":[    
                  "rack"
```
Should be...
```
        "name":"RackSpread", 
        "weight" : 1     
        "argument":{
            "serviceAntiAffinity":{
                "label": "rack"
            }
        }
```

The labelPreference priority also only supports a single label, not a list of labels. Also weight needs to be an integer instead of a string
```
"priorities":[
      {
         "name":"<name>", 
         "weight" : "1"  
          "argument":{
            "labelPreference":{
               "label":[
                  "<label>"  
               ]
            }
         }
      }
   ],
```
Should be...
```
"priorities":[
    {
        "name":"<name>", 
        "weight" : 1
        "argument":{
            "labelPreference":{
                "label": "<label>"  
            }
        }
    }
]
```
Reference: https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/scheduler/api/types.go

### PR DESCRIPTION
**Pull request by DenverJ**
Fixes #12715 - Should have just raised a PR to begin with :)

Numerous syntax issues, typos and config issues.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, @jiajliu, can one of you suggest a reviewer for this change?

**Comment by xltian** [comment]
@wjiangjay will review from QE.

**Comment by wjiangjay** [comment]
@DenverJ @kalexand-rh  checked and LGTM

**Pull request merged**
