### PR TITLE
PR for SRVCOM-3238: Add release notes entries about "SRVCOM-3200" and "SRVCOM-3203" in Serverless version 1.33.2

### PR DESCRIPTION
**Pull request by kaldesai**
**Affecting version:** 
- `serverless-docs-1.33`
- `serverless-docs-1.34`

**Tracking JIRAs:** 
- https://issues.redhat.com/browse/SRVCOM-3235
- sub-task: https://issues.redhat.com/browse/SRVCOM-3238

**Doc previews:** [Red Hat OpenShift Serverless 1.33.2](https://80282--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/serverless-release-notes.html#serverless-rn-1-33-2_serverless-release-notes)

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by jab-rh** [comment]
@kaldesai, this didn't merge cleanly. Can you resolve and supply a new PR? Thanks!

**Pull request merged**
