### PR TITLE
OSDOCS-2909: Removing admin ack docs for 4.10

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2909

Preview: https://deploy-preview-38446--osdocs.netlify.app/openshift-enterprise/latest/updating/understanding-the-update-service.html
^ (Just preview that the docs are no longer there)

### CODE REVIEW

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
@wangke19 or @jianlinliu, can one of you please review this PR? It is just removing the admin ack docs from 4.10, since the ack won't be required when upgrading from 4.9->4.10. Thanks!

**Comment by jianlinliu** [comment]
lgtm

**Pull request merged**
