### PR TITLE
Do not use deprecated asciidoctor footnote syntax

### PR DESCRIPTION
**Pull request by jboxman**
Resolves deprecation warning for footnote syntax when using asciidoctor 2.0.0 and greater.

- https://github.com/asciidoctor/asciidoctor/issues/3114
- https://asciidoctor.org/docs/user-manual/#user-footnotes

cc @vikram-redhat

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Thanks. Can't merge it till we move to asciidoctor > 2.0

**Comment by jboxman** [comment]
@vikram-redhat, it's been deprecated for awhile; Although it looks like hilariously ascii_binder uses the last version where it was _not_ deprecated, so maybe it will break `1.5.6`.

I'll wait until we upgrade to `~> 2.0.10`.

**Comment by vikram-redhat** [comment]
@jboxman ok to merge this.

**Comment by vikram-redhat** [comment]
@jboxman thanks! Also needs doing for 3.11 branch :)

**Comment by vikram-redhat** [comment]
Building OpenShift Container Platform for branch 'enterprise-4.4'

asciidoctor: WARNING: found deprecated footnoteref macro: footnoteref:[versionpolicyn,Where <strong>N</strong> is a number greater than 1.]; use footnote macro with target instead
asciidoctor: WARNING: found deprecated footnoteref macro: footnoteref:[versionpolicyn]; use footnote macro with target instead
asciidoctor: WARNING: found deprecated footnoteref macro: footnoteref:[versionpolicyn,Where <strong>N</strong> is a number greater than 1.]; use footnote macro with target instead
asciidoctor: WARNING: found deprecated footnoteref macro: footnoteref:[versionpolicyn]; use footnote macro with target instead

I suspect in the versioning-policy.adoc.

**Pull request merged**
