### PR TITLE
Bug 1571794, added missing repo

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1571794

@sdodson Is this valid? PTAL. Thanks!

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
yeah, this is fine to add

**Comment by ahardin-rh** [comment]
QE verified in the BZ

**Comment by ahardin-rh** [comment]
Content applied to 3.9 and 3.10 via https://github.com/openshift/openshift-docs/pull/9607

**Pull request merged**
