### PR TITLE
Adds a module that shows how to replace CLB with NLB

### PR DESCRIPTION
**Pull request by stevsmit**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1890627

Preview: https://deploy-preview-37993--osdocs.netlify.app/openshift-enterprise/latest/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws-network-load-balancer

Pending QE ack. 

@zhaozhanqi please review :) 

For 4.6+

### CODE REVIEW

**Review by michaelryanpeter — COMMENTED** [review]
I made couple of small corrections and a nit/suggestion.

**Review by codyhoag — COMMENTED** [review]
Just a few additional nits. Looks good otherwise!

**Comment by zhaozhanqi** [comment]
Hi, @stevsmit  @lihongan is the leader of network-edge QE team ( ingress and dns).  I'm focus on network part(openshift-sdn/ovn/sriov/multus). Hope this can help you understanding the difference between network-edge and network sub team. :)

**Comment by stevsmit** [comment]
@lihongan would you mind reviewing? Thanks.

**Comment by lihongan** [comment]
LGTM
Thank you @stevsmit

**Pull request merged**
