### PR TITLE
OSDOCS-1297 vSphere 7 support updates

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1297

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma PTAL? Thanks!

**Comment by codyhoag** [comment]
Preview: https://vsphere-7-support--ocpdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned

**Comment by codyhoag** [comment]
@jinyunma bump. Can you review this? Thanks!

**Comment by jinyunma** [comment]
The update is LGTM.

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
