### PR TITLE
Follow-up edits to PR#3116

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/3116

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**Comment by ahardin-rh** [comment]
@bfallonf Thanks!

**Comment by ahardin-rh** [comment]
Rev history in original PR

**Pull request merged**
