### PR TITLE
OCPBUGS-36146: Updating CLI install link

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OCPBUGS-36146
Link to docs preview:

https://84128--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/network_observability/netobserv_cli/netobserv-cli-install.html
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mffiedler** [comment]
Verified the link works well

**Review by jpinsonneau — APPROVED** [review]

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@skrthomas I was impressed to see that there's EIGHT arm64 downloads! NICE!

**Comment by skrthomas** [comment]
@GroceryBoyJr thanks for the expedient review!!! <3

**Pull request merged**
