### PR TITLE
Bug#1558237 - moved cloud specific sections to the individual cloud docs

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1558237 and https://bugzilla.redhat.com/show_bug.cgi?id=1558244

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf  PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson If it builds, and looks good, then LGTM!

**Comment by gaurav-nelson** [comment]
Thanks @bfallonf yes, I build locally and checked the xrefs and includes, works fine.

**Pull request merged**
