### PR TITLE
docs: removed Duplicate oc-edit in YAML code block

### PR DESCRIPTION
**Pull request by YashasviChaurasia**
Modified .adoc file to remove extra  `$ oc edit ClusterLogging instance` in 'enterprise-4.12' branch

Resolves: #51946 

Signed-off-by: Yashasvi Chaurasia <yashasvi12977@gmail.com>

### CODE REVIEW

**Comment by YashasviChaurasia** [comment]
@gnufied @ncdc @brenton 
Can this PR be merged or do I need to still work on it?
Thank you

**Comment by kalexand-rh** [comment]
@libander PTAL

**Comment by YashasviChaurasia** [comment]
@libander @bergerhoffer Can this PR be merged?

**Review by bergerhoffer — COMMENTED** [review]
@YashasviChaurasia this looks good to me! Thanks a lot for your contribution!

**Comment by bergerhoffer** [comment]
This problem doesn't exist in main - it only exists in enterprise branches 4.6-4.12, so I'm cherry picking from here back to those versions.

**Pull request merged**
