### PR TITLE
CNV-36131: Incorrect statement: VM must be stopped before snapshotting

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-36131

OCP 4.16+
CNV 4.16+

Preview: https://78412--ocpdocs-pr.netlify.app/openshift-dedicated/latest/virt/backup_restore/virt-backup-restore-snapshots.html#virt-creating-vm-snapshot-web_virt-backup-restore-snapshots

### CODE REVIEW

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Comment by sbeskin-redhat** [comment]
@mhenriks Please check this PR.

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
