### PR TITLE
BZ2083373: Changes the registry port from 5000 to 8443

### PR DESCRIPTION
**Pull request by xenolinux**
Changes the registry port from 5000 to 8443

Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2083373

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/registry-8443/installing/disconnected_install/installing-mirroring-disconnected.html#installation-adding-registry-pull-secret_installing-mirroring-disconnected

Preview screenshot: https://github.com/openshift/openshift-docs/pull/48440#issuecomment-1197955565 

Additional information:

QE: @gpei

### CODE REVIEW

**Comment by gpei** [comment]
LGTM

**Comment by xenolinux** [comment]
Screenshot 2022-07-28 at 3 53 01 PM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
