### PR TITLE
Developer CLI getting started WIP

### PR DESCRIPTION
**Pull request by tpoitras**
https://bugzilla.redhat.com/show_bug.cgi?id=1285109

not added to _build_cfg yet so I can collaborate with @ahardin-rh on this one

### CODE REVIEW

**Comment by adellape** [comment]
@tpoitras Probably no revhistory needed for this, eh?

**Comment by vikram-redhat** [comment]
@tpoitras @ahardin-rh - a nice breakup of the topics is available here: https://mojo.redhat.com/docs/DOC-1063211

**Comment by tpoitras** [comment]
@adellape yeah i reckon we wait til it's done for revhistory

**Comment by tnguyen-rh** [comment]
@tpoitras @ahardin-rh 
I've added label `to_followup`.  This inhibits today's (2015-02-08) cherry-pick.

**Comment by vikram-redhat** [comment]
@tpoitras what is the ose label?

**Comment by tpoitras** [comment]
@vikram-redhat just to show it's enterprise-related

**Comment by tpoitras** [comment]
@tnguyen-rh How does it inhibit the cherry pick?

**Pull request merged**
