### PR TITLE
Updating support information about masquerade subnets in documentation.

### PR DESCRIPTION
**Pull request by smiglani-r**
Updating information about changing the OVN-Kubernetes network plugin internal IP address ranges.

https://issues.redhat.com/browse/OCPBUGS-37352

Version(s):

4.16

Issue:

https://issues.redhat.com/browse/OCPBUGS-37352

Link to docs preview:

https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-networking-changing-ovn-kubernetes-network-plugin-internal-range_release-notes

QE review:
- [x] QE has approved this change.
- [x] SME approved
- [x] PX approved

Additional information:

As per the Internal article [1], we have procedure to modify the internalMasqueradeSubnet but in the release notes [2] updated that the masquerade subnet must be configured during installation only. We have also verifed during the hackathon that the masquerade subnet can be modified after the cluster installation.

[1]  https://access.redhat.com/articles/7076125
[2] https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-networking-changing-ovn-kubernetes-network-plugin-internal-range_release-notes

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@JoeAldinger PTAL.

**Comment by ShaunaDiaz** [comment]
@smiglani-r We require both engineering SME and QE approval, plus potentially change management from Docs for anything in the release notes. @JoeAldinger is a good contact to help you with this, as this is his Doc area.

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Comment by JoeAldinger** [comment]
PTAL @anuragthehatter @jechen0648

**Comment by CFields651** [comment]
FYI the links to the docs preview isn't right.  It links to the current release notes.  If this change is okay w/QE it is okay we me.  /lgtm.

**Comment by jab-rh** [comment]
@bpickard22, wouldn't this apply to 4.17 as well here? Thanks!

**Pull request merged**
