### PR TITLE
#CNV-31114: new rn for update to ssh secret use

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.15 release notes

Issue: [CNV-31114](https://issues.redhat.com//browse/CNV-31114)

Link to docs preview: https://71034--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-web

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Review by ousleyp — COMMENTED** [review]
One weird nit - otherwise LGTM. Ping me when you're ready and I'll merge. Thanks, Sabrina!

**Pull request merged**
