### PR TITLE
Issue 3429 fixed context path

### PR DESCRIPTION
**Pull request by bfallonf**
As per #3429 

@siamaksade can I get an ack this is fixes what was intended for the issue?

@oatmealraisin you wrote the initial topic, can I get an ack this is correct?

Thanks, all!

### CODE REVIEW

**Comment by siamaksade** [comment]
I confirm that it fixes the issue. However there is one more place that the URL needs to be updated under "Confirming Success".

**Comment by oatmealraisin** [comment]
@bfallonf lgtm, save what @siamaksade pointed out.

**Comment by bfallonf** [comment]
Sure thing. Last one fixed. I'll merge away.

Thanks!

**Comment by bfallonf** [comment]
[rev_history]
|xref:../dev_guide/app_tutorials/maven_tutorial.adoc[Application Tutorials -> Setting Up a Nexus Mirror for Maven]
|Corrected context path for Nexus.
%

**Pull request merged**
