### PR TITLE
BZ 1970927: Cronjobs will be GA from OCP 4.8, so they no longer need batch/v1beta but can be batch/v1

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1970927

https://issues.redhat.com/browse/WRKLDS-229

Release note for this change: https://github.com/openshift/openshift-docs/pull/33697

Sample preview: https://deploy-preview-33441--osdocs.netlify.app/openshift-enterprise/latest/nodes/jobs/nodes-nodes-jobs.html#nodes-nodes-jobs-creating-cron_nodes-nodes-jobs
Release Note preview: https://deploy-preview-33697--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-8-release-notes.html#ocp-4-8-nodes-cronjob-qa_release-notes

### CODE REVIEW

**Comment by mburke5678** [comment]
@soltysh PTAL

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by mburke5678** [comment]
@sunilcio  Can you please take a look. This is a late change for 4.8. Would like to get it done soon. Thank you in advance!

**Comment by sunilcio** [comment]
LGTM, thanks!

**Review by adellape — APPROVED** [review]
:fire:

**Pull request merged**
