### PR TITLE
CNV-20106: Release note: Remove known issue 2092412/PREVIEW

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14

Issue: [CNV-20106](https://issues.redhat.com//browse/CNV-20106)

Link to docs preview: [Bug fix](https://66054--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-bug-fix)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
@dshchedr, Can you please review this PR for a release note that was moved from Known issues to Bug fix for 4.14? 
@stu-gott gave a "Works for me" in the JIra.

Thank you!

**Comment by skrthomas** [comment]
Peer review LGTM. Only thing is looks like you need a rebase, which you probably are already aware of 🙃

**Pull request merged**
