### PR TITLE
Add egress-router-cni to the docs

### PR DESCRIPTION
**Pull request by danielmellado**

### CODE REVIEW

**Comment by jboxman** [comment]
@danielmellado, thanks! I'll try to look through this by the end of next week. Ultimately I'll probably need to restructure this into several different modules.

And is it likely that in the future it will include support for all of the egress router types in OpenShift SDN? If so, I'll need to try to plan for that future work as well.

**Comment by jboxman** [comment]
Hi @danielmellado,

@mikemckiernan has joined me on the docs team working on SDN-related content; He'll be working through this PR with you.

Thanks!

**Comment by jboxman** [comment]
@mikemckiernan, also `NetworkAttachmentDefinition` is what [_Multiple networks_](https://docs.openshift.com/container-platform/4.6/networking/multiple_networks/understanding-multiple-networks.html) is based on. Unfortunately I never expanded upon what that means, and a generic overview is somewhat of a blindspot I'd like to address someday. But that doesn't really impact this PR specifically.

**Comment by mikemckiernan** [comment]
@danielmellado , I copied your commit to my fork. I plan to take credit for your great ideas.

I've initiated a follow up [PR](https://github.com/openshift/openshift-docs/pull/28609) with the required wordsmithing and structural reorganization.

@jboxman, can you remove the branch label from this PR please? And maybe add it to mine?  The absence of git superpowers sometimes has its benefits.

**Pull request closed without merging**
