### PR TITLE
SRVOCF-303: Update the envVars section name to env

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+

https://issues.redhat.com/browse/SRVOCF-303

Docs preview:
https://deploy-preview-34412--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-getting-started.html#serverless-create-func-kn_serverless-functions-getting-started (the first YAML listing in this section)
https://deploy-preview-34412--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-getting-started.html#serverless-build-func-kn_serverless-functions-getting-started (also the first YAML listing in this section)

### CODE REVIEW

**Comment by rh-max** [comment]
@lance Not strictly "your" Jira, but it's tiny, so can you please take a peek? https://github.com/openshift/openshift-docs/pull/34412#issue-685824614

**Review by lance — APPROVED** [review]

**Comment by jrangelramos** [comment]
QE Approved

**Comment by mburke5678** [comment]
@rh-max LGTM

**Review by lance — APPROVED** [review]

**Review by abrennan89 — APPROVED** [review]
@rh-max if you can squash the commits I can merge and CP this for you?

**Comment by abrennan89** [comment]
@rh-max @lance this is labelled as 4.8+ but I think that's incorrect, shouldn't it be 4.6+ if it's for 1.16.0?

**Comment by rh-max** [comment]
@lance @jrangelramos @mburke5678 Thanks for reviews! @abrennan89 Could you please merge?

**Review by abrennan89 — APPROVED** [review]

**Pull request merged**
