### PR TITLE
RHDEVDOCS 5668 fix OCP product name in the about file of the pipelines standalone branch

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.10, pipelines-docs-1.11, pipelines-docs-1.12

Issue:

RHDEVDOCS 5668

Link to docs preview:

https://66409--docspreview.netlify.app/openshift-pipelines/latest/about/about-pipelines

QE review:
- [ ] QE has approved this change.

Additional information:

The note about the new standalone documentation, as used in the standalone documentation itself, has a wrong use of {product-title}, which means Pipelines and not OCP for the standalone doc bild, The result is "Red Hat OpenShift Pipelines releases on a different cadence from Red Hat OpenShift Pipelines" at https://docs.openshift.com/pipelines/1.12/about/about-pipelines.html . This PR fixes the issue bu using the attribute {OCP}, which was introduced in the pipelines-docs branch (and is not present in the main branch).

Technical documentation content is not altered, so Dev/QE review is not necessary.

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
@mramendi I was able to find it, but just a reminder to put the preview link in the PR description to make it easier for reviewers.

Update LGTM!

**Comment by mramendi** [comment]
@bergerhoffer thanks!!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Pull request merged**
