### PR TITLE
OSDOCS-1788: Adding release notes for scheduler profiles GA

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1788

Preview: https://deploy-preview-35449--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nodes-scheduler-profiles

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @kasturinarra for review please!

Preview: https://deploy-preview-35449--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nodes-scheduler-profiles

**Review by jeana-redhat — APPROVED** [review]
LGTM

**Pull request merged**
