### PR TITLE
add multinamespace instructions to pipeline tutorial

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi / ptal

@openshift/team-documentation or @bmcelvee fyi / ptal 

This content should be valid for 3.7, 3.9, and 3.10

Also, I wrapped some of the links with ifdef's because I saw that employed with other links in the file

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by vikram-redhat** [comment]
@bmcelvee - this still needs QE review?

**Comment by bmcelvee** [comment]
@vikram-redhat Yep. @dongboyan77 PTAL

**Comment by dongboyan77** [comment]
LGTM, thanks

**Pull request merged**
