### PR TITLE
OSDOCS-7118 GCP confidential VMs moving to GA

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-7118

Link to docs preview:
https://64086--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-customizations#installation-gcp-enabling-confidential-vms_installing-gcp-customizations

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@duanwei33 hello Duan - please take a look at this docs PR. It looks like https://issues.redhat.com/browse/OCPBUGS-7582 has been resolved, so am I correct in removing the known issue from the 4.14 docs? Thank you

**Comment by duanwei33** [comment]
@bscott-rh Hi Scott, yes it could be removed from 4.14 doc.

**Comment by duanwei33** [comment]
LGTM from QE‘s perspective.

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1:

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
