### PR TITLE
TELCODOCS-1029: First instance of namespace: openshift-operators removed from example

### PR DESCRIPTION
**Pull request by ogradyp**
https://issues.redhat.com/browse/TELCODOCS-1029 NodeHealthCheck example has namespace

Applies to OpenShift version : 4.9, 4.10, 4.11, 4.12 +

Preview: [About the Node Health Check Operator](http://file.emea.redhat.com/pogrady/TELCODOCS-1029/nodes/nodes/eco-node-health-check-operator.html#about-node-health-check-operator_node-health-check-operator)

Dev review complete/approved by @slintes
QE review complete/approved by @anna-savina
Peer review complete/approved by @mburke5678 

Thank you.

### CODE REVIEW

**Comment by slintes** [comment]
lgtm

**Comment by EricPonvelle** [comment]
@ogradyp I cherrypicked `enterprise-4.10+` but I'll need you to create a manual cherry-pick for `entprise-4.9` and resolve the merge conflicts.

**Comment by ogradyp** [comment]
Thank you Eric. Much appreciated.

**Pull request merged**
