### PR TITLE
OSDOCS-10919: adds 4.16.3 relnote to MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.16

Issue:
[OSDOCS-10919](https://issues.redhat.com/browse/OSDOCS-10919)

Link to docs preview:
[4.16.3 release note](https://78844--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-16-release-notes.html#microshift-4-16-3-dp_release-notes)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
