### PR TITLE
Red Hat image name updates in release notes

### PR DESCRIPTION
**Pull request by codyhoag**
@ahardin-rh @sheriff-rh can either of you confirm this change? This was reported in #18041

This was documented as a change in the 3.11 release notes ([here](https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-accessing-and-configuring-red-hat-registry)). Let me know if this was intentional, since the change was made in the same release. Thanks!

### CODE REVIEW

**Comment by sheriff-rh** [comment]
I'm unclear what the issue is. Typically, we put the image list in the bug advisories in 3.x releases, like [this](https://access.redhat.com/errata/RHBA-2019:2824). For this particular release, we put the image list in the release notes.  It's just a list of images available for 3.11.153, it does not conflict with the disconnected installation docs referenced in the issue. 

I suppose we could make it less confusing by moving the image list to a KCS like we do with [4.x](https://access.redhat.com/solutions/4562241)? Then we change the [release notes](https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-23) to point to the KCS.

**Comment by codyhoag** [comment]
@sheriff-rh from what I gathered on first pass, the registry URL changed from `registry.access.redhat.com` &rarr; `registry.redhat.io` in 3.11, and the request is to update the registry URL for accessing those images as such. But perhaps this goes deeper than I initially realized.

**Comment by codyhoag** [comment]
I'll confirm with reporter

**Comment by codyhoag** [comment]
The reporter has informed me that the first few images in the release notes do not exist. I have confirmed by attempting a `docker pull` that they aren't reachable. I'll investigate further.

**Comment by codyhoag** [comment]
Confirmed **Build Name** &rarr; **Image Name** change with RCM team. Acquired image names from Thiago.

@sheriff-rh can you review and, if all looks good, merge too? Thanks!

**Comment by sheriff-rh** [comment]
Looks good! Merging.

**Pull request merged**
