### PR TITLE
removing ref to ISO file for PXE/iPXE boot

### LINKED ISSUE #24874: [enterprise-4.5] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc
### Which section(s) is the issue in?

Creating Red Hat Enterprise Linux CoreOS (RHCOS) machines by PXE or iPXE booting

### What needs fixing?
1/ Replace this line:
Obtain the RHCOS ISO image, compressed metal RAW image, kernel and initramfs files from the Product Downloads page on the Red Hat customer portal or the RHCOS image mirror page.

by this:
Obtain the compressed metal RAW image, kernel and initramfs files from the Product Downloads page on the Red Hat customer portal or the RHCOS image mirror page.

2/ Remove this line:
- ISO: rhcos-<version>-installer.<architecture>.iso

(because we don't use ISO file for PXE/iPXE boot)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Fixes #24874

### CODE REVIEW

**Comment by jeana-redhat** [comment]
Fixes #24874

**Comment by jeana-redhat** [comment]
Pending answer to: https://github.com/openshift/openshift-docs/issues/24874#issuecomment-701455921

**Comment by jeana-redhat** [comment]
@morenod I think this is also one for you - PTAL :)

**Review by morenod — APPROVED** [review]
lgtm

**Review by sheriff-rh — APPROVED** [review]
LGTM! 🌮 🎉 🥇 🦕 🐈

**Pull request merged**
