### PR TITLE
[SRVOCF-508] Update Tekton task links for 1.27

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
4.9+

Issue:
https://issues.redhat.com/browse/SRVOCF-508

Link to docs preview:
https://55595--docspreview.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-on-cluster-builds.html

QE review:
- [ x] QE has approved this change.

### CODE REVIEW

**Comment by jrangelramos** [comment]
QE Approved

**Review by opayne1 — COMMENTED** [review]
Updates look good. Just 2 notes:
1. Your commit message is different than the title of your PR. It is recommended that they match.
2. We are no longer backporting to 4.8 since it is EOM. Your changes will go into 4.9+

**Comment by rh-max** [comment]
@opayne1 Hi,
1. They are both "Update Tekton task links for 1.27"
2. Sure, 4.9+ then, I missed the EOL.
Thank you.

**Pull request merged**
