### PR TITLE
CNV#33125: new tp rn

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.15 RN

Issue: [CNV-33125](https://issues.redhat.com//browse/CNV-33125)

Link to docs preview: https://71908--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-technology-preview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by sabrinajess** [comment]
@lkladnit Please provide QE review.

**Pull request merged**
