### PR TITLE
OCS/RHGS link fixes

### PR DESCRIPTION
**Pull request by maxwelldb**
Updates to RHGS links as discussed between Vikram and Ken Hartsoe. 

Does this all seem copacetic, @vikram-redhat ?

FYI: @aheslin

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@maxwelldb this can be merged when ready.

**Comment by maxwelldb** [comment]
@vikram-redhat I don't have merge rights. :(

**Comment by kalexand-rh** [comment]
Merging.

**Pull request merged**
