### PR TITLE
Added 4.7 tested cluster maximums

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://issues.redhat.com/browse/OSDOCS-1633

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Preview build: https://4-7-scale-metrics--ocpdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums_object-limits

**Comment by ahardin-rh** [comment]
@chaitanyaenr PTAL. This stubs out the spot for 4.7 metrics. We can submit a separate PR to update/ build on top of this work, if necessary, as we get closer to 4.7. Thanks!

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Pull request merged**
