### PR TITLE
OSDOCS-4720: OSDK bump SDK to v1.26.0 and add Ansible migration step

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.12

Issue: [OSDOCS-4720](https://issues.redhat.com//browse/OSDOCS-4720)

Link to docs preview:
**OSDK installation docs**

- [Installing the OSDK CLI (Note admonition)](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html)
- [Installing OSDK CLI on Linux and MacOS](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-installing-cli.html#osdk-installing-cli-linux-macos_osdk-installing-cli)

**OSDK project migration docs**

- [Updating Go-based Operator projects](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-updating-projects.html)
- [Updating Ansible-based Operator projects](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-updating-projects.html)
- [Updating Helm-based Operator projects](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-updating-projects.html)
- [Updating Hybrid Helm-based Operator projects](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.html)
- [Updating Java-based Operator projects](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-updating-projects.html)

**Scorecard docs**
This changes the tag on the quay hosted image to 1.26.0.

- [Scorecard config](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-config_osdk-scorecard)
- [Scorecard output](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-output_osdk-scorecard)
- [Scorecard parallel](https://54066--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/osdk-scorecard.html#osdk-scorecard-parallel_osdk-scorecard)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@emmajiafan PTAL

**Comment by michaelryanpeter** [comment]
@everettraven PTAL

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by KeenonLee — COMMENTED** [review]
/lgtm

**Comment by michaelryanpeter** [comment]
OSDK 1.25.1 and/or 1.26.0 did not make the cut off for cutting the last release of OCP 4.12. Closing this PR in favor of #54064

**Pull request closed without merging**
