### PR TITLE
Bug 1372466 example for master and etcd on same host

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://bugzilla.redhat.com/show_bug.cgi?id=1372466

I will ask for an ack in the BZ

### CODE REVIEW

**Comment by bfallonf** [comment]
Ack given.

@tpoitras @ahardin-rh @adellape peer review plz?

**Comment by bfallonf** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Installing -> Advanced Installation]
|Added example for a multi-master install with etcd on the same hosts.
%

**Comment by ahardin-rh** [comment]
Looks good! Just needs a squash. :rainbow:

**Comment by bfallonf** [comment]
Thanks @ahardin-rh ! I'll squash and merge now.

**Pull request merged**
