### PR TITLE
[OSDOCS-2720]: Remove backup safety net message from previous release

### PR DESCRIPTION
**Pull request by tmalove**
Fixes: [OSDOCS-2720](https://issues.redhat.com/browse/OSDOCS-2720)
Urgency: Medium
Applies to: 4.10

Preview link: https://deploy-preview-41135--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-within-minor.html

### CODE REVIEW

**Comment by tmalove** [comment]
@hasbro17  I removed the statement about the backup safety net. It had been changed slightly since I added it for 4.9. It now appears like it did in 4.8. Let me know your thoughts. Thanks!

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Comment by tmalove** [comment]
@geliu2016 Will you review this PR? Thanks!

**Comment by tmalove** [comment]
> /label qe-approved

Thank you @schituku!

**Pull request merged**
