### PR TITLE
Remove Windows Server 2004 support

### PR DESCRIPTION
**Pull request by codyhoag**
Previews:
- https://deploy-preview-40968--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes-4-x.html#supported-windows-server-versions
- https://deploy-preview-40968--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.html#creating-the-vsphere-windows-vm-golden-image_creating-windows-machineset-vsphere

### CODE REVIEW

**Comment by codyhoag** [comment]
@selansen can you confirm?

**Review by selansen — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/hold 

for https://github.com/openshift/windows-machine-config-operator/pull/879

**Comment by codyhoag** [comment]
@sgaoshang can you verify? Thanks!

**Comment by sgaoshang** [comment]
@codyhoag /lgtm, thanks.

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
