### PR TITLE
OCPBUGS-33937#correcting bootstrap permission

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.13+

Issue:
https://issues.redhat.com/browse/OCPBUGS-33937

Link to docs preview:
https://78152--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account.html#minimum-required-permissions-ipi-azure_installing-azure-account

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@jinyunma, PTAL

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Pull request merged**
