### PR TITLE
BZ1771675 Typo

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by codyhoag** [comment]
Thanks @kalexand-rh ! Do you mind merging/cherrypicking too? I'm not allowed to do it yet.

**Comment by kalexand-rh** [comment]
Not at all! I thought that you could since you dropped the labels on. :)

**Comment by codyhoag** [comment]
@kalexand-rh Thanks! I technically can, but Vikram wants me to hold off for now. :blush:

**Comment by kalexand-rh** [comment]
Sure thing, @codyhoag! Just let us know when Vikram says that you're good to merge.

**Pull request merged**
