### PR TITLE
GIT25663: Added information about startup probe.

### LINKED ISSUE #25663: [enterprise-4.5] Add "startupProbe" description to "Monitoring application health" section
### Which section(s) is the issue in?

* Section name: [Monitoring application health](https://docs.openshift.com/container-platform/4.5/applications/application-health.html)

### What needs fixing?

As of Kubernetes 1.18, `startupProbe` feature has been Beta and it's available by default. Even the feature already introduced on upstream documentation here: [Configure Liveness, Readiness and Startup Probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), it's not mentioned at all on OpenShift 4.5 related section on the documentation. OpenShift 4.5 are integrated with Kubernetes 1.18 and it's also available the same feature either. So OpenShift 4.5 docs also provides related information.

### PR DESCRIPTION
**Pull request by jonquilwilliams**
Fixes #25663 

The new section "Startup Probe" was added to the Monitoring Application Health page.

QE and peer review needed. Merge and CP to 4.5 and 4.6. Thanks.

**Note to peer reviewer:** Ran asciibinder build locally. Formatting is correct.

### CODE REVIEW

**Review by sheriff-rh — APPROVED** [review]
LGTM! 🌮 🐈 🥇 🦖

**Comment by jonquilwilliams** [comment]
@juzhao Please do a QE review of this issue. Thank you!

**Comment by juzhao** [comment]
@jonquilwilliams sorry, liveness/healthy check is beyond my knowledge. @zhouying7780 are you the owner?

**Comment by xingxingxia** [comment]
> @zhouying7780 @xingxingxia are you the owner?

This seems to relate to applications or containers, and is being communicated with application owner yinzhou and container owner Sunil involved in #forum-qe thread https://url.corp.redhat.com/6ffbe75 (RH internal).

**Comment by sunilcio** [comment]
I reviewed it, LGTM

**Comment by jonquilwilliams** [comment]
@sheriff-rh Looks like this is approved by QE. Can you merge and CP please? Thanks :)

**Pull request merged**
