### PR TITLE
Fix some of asciibinder warnings

### PR DESCRIPTION
**Pull request by php-coder**
I tried to fix annoying warnings from `asciibnder build`. I created a separate commit for each warning and also put the warning into the commit message. Later I can squash commits if you need.

### CODE REVIEW

**Comment by php-coder** [comment]
PTAL @openshift/team-documentation

**Comment by vikram-redhat** [comment]
@bfallonf - can you take a look?

**Comment by bfallonf** [comment]
@php-coder @vikram-redhat LGTM

**Comment by vikram-redhat** [comment]
@php-coder - were you working on the 3.2 enterprise branch or Origin?

**Comment by php-coder** [comment]
@vikram-redhat Most of the fixes relate to Origin but there is at least one for Enterprise and one of Dedicated.

**Comment by adellape** [comment]
@php-coder LGTM. Can you rebase?

**Comment by php-coder** [comment]
@adellape rebased!

**Comment by adellape** [comment]
@vikram-redhat Do you know if the Customer Portal build script is equipped to handle the `_topic_map.yml` file name change? Can you check w/ Lee? Will want to confirm that before merging here for that change.

@php-coder Also, sorry for the delay; needs rebase again. :[

**Comment by php-coder** [comment]
@adellape Rebased and ready for merge.

**Comment by php-coder** [comment]
@openshift/team-documentation Rebased. PTAL.

**Comment by ahardin-rh** [comment]
@php-coder LGTM. Please squash and I'll merge :bow:

**Comment by php-coder** [comment]
@ahardin-rh Squashed.

**Comment by ahardin-rh** [comment]
@php-coder Thanks!

**Comment by ahardin-rh** [comment]
No rev history needed

**Pull request merged**
