### PR TITLE
SRVCOM-2705: Showcase image leftovers

### PR DESCRIPTION
**Pull request by cardil**
Version(s): Serverless 1.29+

Issue: https://issues.redhat.com/browse/SRVCOM-2705

Link to docs preview: https://64976--docspreview.netlify.app

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by stevsmit** [comment]
serverless-docs-1.28

**Comment by stevsmit** [comment]
serverless-docs-1.29

**Comment by cardil** [comment]
@stevsmit It turns out the Serverless 1.28 didn't have those docs yet. So, this change should be 1.29+, not 1.28+.

**Pull request merged**
