### PR TITLE
Added routing optimization content to 4.0

### PR DESCRIPTION
**Pull request by ahardin-rh**
Preview build: http://file.rdu.redhat.com/~ahardin/01072019/routing-optimization-4-0/scalability_and_performance/routing-optimization.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jmencak We got https://github.com/openshift/openshift-docs/pull/13142 in for 3.11, but this PR adds the content in for 4.0. PTAL. Thanks!

**Comment by jmencak** [comment]
I've already checked the content for 4.0 when we did the 3.11 PR, however, looking at the way router is set up in okd by default, performance numbers will likely need to be revisited.

**Comment by ahardin-rh** [comment]
@jmencak Any updates here? Our team is looking to get all 4.0 docs completed for a total QE review by February 22.

**Comment by jmencak** [comment]
@ahardin-rh, I'm afraid I don't have a stable 4.0 cluster to update the numbers at the moment.

**Comment by ahardin-rh** [comment]
@jmencak Any updates? Thank you!

**Comment by jmencak** [comment]
I'll try to get some numbers by the middle of next week.  Failing that, I suggest to drop the numbers section if you're aiming at the Feb 22 target and add them once they're available.

**Comment by ahardin-rh** [comment]
@jmencak Thank you!

**Comment by ahardin-rh** [comment]
@jmencak  As discussed earlier, I commented out the metrics for now. We can create a follow-up PR with correct numbers when they are ready.

**Pull request merged**
