### PR TITLE
fixed the versions info

### PR DESCRIPTION
**Pull request by BabbarPB08**
fixed the version info

Version(s):
4.14.z

Issue:
changed the ocp version from 4.12 to 4.14 and updated the nodes version form 1.18.2 to 1.27.6

Link to docs preview:
https://docs.openshift.com/container-platform/4.14/installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.html#replacing-a-bare-metal-control-plane-node_ipi-install-expanding

QE review:
- [ ] QE has approved this change.

 /label peer-review-needed

### CODE REVIEW

**Comment by abrennan89** [comment]
Hi @BabbarPB08 - any PRs opened against the `main` branch should be also be cherrypicked to 4.15, which is the next upcoming OCP version. If this change is intended only for 4.14, please open a PR against the `enterprise-4.14` branch instead.

Assuming this is for 4.14+ it LGTM.

**Comment by kowen-rh** [comment]
Docs preview is available here: https://67461--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster#replacing-a-bare-metal-control-plane-node_ipi-install-expanding

**Comment by kowen-rh** [comment]
Apologies, it seems that Firefox didn't update the state of this tab for me. Looks like peer review is already done. :slightly_smiling_face:

**Comment by kowen-rh** [comment]
Just cleaning up after that misunderstanding earlier!

/remove-label peer-review-in-progress
/label peer-review-done

**Comment by BabbarPB08** [comment]
updated: https://github.com/openshift/openshift-docs/pull/67596

**Comment by BabbarPB08** [comment]
Hello @kowen-rh , will it be merged?

**Comment by skrthomas** [comment]
@BabbarPB08 Just wanting to confirm that this is supposed to go to 4.15 too? Your comment still says 4.14z, so if it only needs to go to 4.14, then like Ashleigh advises, this PR should be opened against enterprise-4.14.

**Review by maxwelldb — COMMENTED** [review]
> Just wanting to confirm that this is supposed to go to 4.15 too? Your comment still says 4.14z, so if it only needs to go to 4.14, then like Ashleigh advises, this PR should be opened against enterprise-4.14.

I don't see an answer to this here at the moment. Please re-label when ready.

Also, there's a merge conflict that needs resolution.

**Comment by BabbarPB08** [comment]
Hello @maxwelldb , I have updated the commit and resolved the merge conflict, please have a look and let me know.

**Comment by kcarmichael08** [comment]
Hi @BabbarPB08 , there are some issues with the PR:

1. It looks like the PR is now showing 2 commits, and no file changes. You may want to undo the previous rebase that you did to resolve the merge conflicts, and try rebasing following the instructions [here](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.xhceijadkbh8). We need to have only [one commit per PR](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.epes4xf06pzk), please see guidance here.
3. As previous reviewers have asked, will this change also apply to 4.15? Or is it for 4.14z only?

**Comment by BabbarPB08** [comment]
Hello @kcarmichael08 

you can skip this and consider this: https://github.com/openshift/openshift-docs/pull/68180

**Pull request closed without merging**
