### PR TITLE
[OSDOCS-11745]Namespace needs to be indented per SME

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-11745
Link to docs preview:

https://80727--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/logging/cluster-logging-deploying.html#logging-loki-cli-install_cluster-logging-deploying

https://80727--ocpdocs-pr.netlify.app/openshift-dedicated/latest/observability/logging/log_storage/installing-log-storage.html#logging-loki-cli-install_installing-log-storage

https://80727--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/cluster-logging-deploying.html#logging-loki-cli-install_cluster-logging-deploying

https://80727--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/log_storage/installing-log-storage.html#logging-loki-cli-install_installing-log-storage

https://80727--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/logging/cluster-logging-deploying.html#logging-loki-cli-install_cluster-logging-deploying

https://80727--ocpdocs-pr.netlify.app/openshift-rosa/latest/observability/logging/log_storage/installing-log-storage.html

QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114, may I get a review for this PR, please? Thanks!

**Comment by mletalie** [comment]
> /lgtm

thanks!

**Review by mletalie — COMMENTED** [review]
/label peer-review-needed

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by michaelryanpeter** [comment]
lgtm

**Pull request merged**
