### PR TITLE
Bug 1754521: Fixing example yaml typo for crontab clusterrole

### PR DESCRIPTION
**Pull request by ravitri**
Fixing small typo error example yaml in doc link [1]

[1] - https://docs.openshift.com/container-platform/3.11/admin_guide/custom_resource_definitions.html#creating-aggregated-cluster-role-crd_admin-guide-custom-resources

### CODE REVIEW

**Comment by stuartchuan** [comment]
The changes lgtm.

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Comment by kalexand-rh** [comment]
@ravitri, will you please change this PR to be against the `master-3` branch?

**Comment by kalexand-rh** [comment]
@ravitri, please change it back to `master-3` and rebase.

@vikram-redhat, can we turn off the bug validation checker? It clashes with our workflow.

**Comment by ravitri** [comment]
@kalexand-rh - I did the following so far:
1. Delete the branch 'fix-crd-type-3.11' that was sourced from enterprise-3.11 branch earlier on.
2. This closed the PR as expected.
3. I deleted local branch and fetch latest of master-3 branch and force pushed the change with same branch name 'fix-crd-type-3.11'.
4. Yet, am not able to re-open the PR.

Is this expected? If yes, what about opening a separate PR for now?

**Comment by kalexand-rh** [comment]
@ravitri, I am sad that Git is not cooperating with you. Opening a new PR is completely acceptable. Please tag me in the new one.

**Pull request closed without merging**
