### PR TITLE
Updating docs per Kube Descheduler Operator name change

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-894

Preview: https://osdocs-894-name-update--ocpdocs.netlify.com/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-installing_nodes-descheduler

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@openshift/team-documentation For peer review please

**Comment by bergerhoffer** [comment]
@ingvagabund Can you review please? Thanks!

https://osdocs-894-name-update--ocpdocs.netlify.com/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-installing_nodes-descheduler

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Comment by ingvagabund** [comment]
/hold
feel free to unhold anytime

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please review this update for the operator name change? Thanks!

**Review by kasturinarra — COMMENTED** [review]
Why is the name change ? can you please help me understand ?

**Comment by ingvagabund** [comment]
> Why is the name change ? can you please help me understand ?

For naming consistency with other operators we own

**Comment by kasturinarra** [comment]
> > Why is the name change ? can you please help me understand ?
> 
> For naming consistency with other operators we own

okay, thanks !!

**Review by kasturinarra — COMMENTED** [review]
/lgtm

**Pull request merged**
