### PR TITLE
CNV#15028: RN nested virt in virt hosts

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.15

Issue: [CNV-15028](https://issues.redhat.com//browse/CNV-15028)

Link to docs preview: https://71812--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-15-release-notes#virt-4-15-technology-preview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by stu-gott** [comment]
LGTM

If this is a tech-preview only note, then I agree.

**Comment by sjhala-ccs** [comment]
> LGTM
> 
> If this is a tech-preview only note, then I agree.

Thanks! Yes, this is a tech preview note.

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
