### PR TITLE
OCPBUGS#16708: greenboot RPM name correction

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13, 4.14+

Issue:
https://issues.redhat.com/browse/OCPBUGS-16708

Link to docs preview:
https://63057--docspreview.netlify.app/microshift/latest/microshift_install/microshift-greenboot

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by ggiguash** [comment]
This PR is LGTM for me.

**Comment by dfitzmau** [comment]
LGTM . @mburke5678 , would you be OK to verify my review?

**Pull request merged**
