### PR TITLE
Removed assetConfig.publicURL per Gaoyun comment in BZ

### PR DESCRIPTION
**Pull request by mburke5678**
Removed `assetConfig.publicURL` per Gaoyun comment in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1557166

### CODE REVIEW

**Comment by mburke5678** [comment]
@gpei PTAL.

**Comment by gpei** [comment]
The change lgtm

**Comment by vikram-redhat** [comment]
@mburke5678 - would this apply to 3.10 as well?

**Comment by mburke5678** [comment]
@gpei Can you confirm if `assetConfig.publicURL` is not in the default master config for 3.10 (3.9 going forward)?

**Pull request merged**
