### PR TITLE
Monitoring term style updates for 4.6 and 4.7

### PR DESCRIPTION
**Pull request by lbarbeevargas**
Style updates to terminology in the Monitoring book for 4.6 and 4.7. 

Updates to 4.4 and 4.5 will be handled in separate PRs as there was a major overhaul of the Monitoring book in 4.6.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
@openshift/team-documentation PTAL

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
