### PR TITLE
OSDOCS-2014 Installing VMC IPI into restricted network

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2014

Previews: 
- New article: https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc.html
- Support table: https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing-preparing.html#supported-installation-methods-for-different-platforms

### CODE REVIEW

**Comment by codyhoag** [comment]
@jinyunma PTAL

**Comment by jinyunma** [comment]
In section [About installations in restricted networks](https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc.html#installation-about-restricted-networks_installing-restricted-networks-vmc), the IMPORTANT part mainly describes the UPI installation while this is IPI installation doc, it's better to be removed here, WDYT?

**Comment by jinyunma** [comment]
I found that in [Installing a cluster on VMC in a restricted network with user-provisioned infrastructure](https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc-user-infra.html), it also describes [Configuring the cluster-wide proxy during installation](https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc-user-infra.html#installation-configure-proxy_installing-restricted-networks-vmc-user-infra), which also supports in IPI installation in a restricted network. It's better to be added in this doc.

**Comment by codyhoag** [comment]
@jinyunma I have addressed your feedback. Can you take a second look? Thanks!

**Comment by jinyunma** [comment]
@codyhoag, LGTM for update. I have one more question, when reviewing doc [Installing a cluster on vSphere in a restricted network](https://deploy-preview-31268--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.html), I didn't notice this part, sorry for this. Could you also help to update that doc if possible?

**Comment by codyhoag** [comment]
@jinyunma sure thing! Just added that proxy config section to vSphere IPI restricted networks sections to make them uniform. Thanks!

**Comment by ahardin-rh** [comment]
@codyhoag LGTM! Nicely done. :rocket:

**Pull request merged**
