### PR TITLE
OCPBUGS#5899: Bootstrap CA renewal

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OCPBUGS-5899

Link to docs preview: https://58173--docspreview.netlify.app/openshift-enterprise/latest/security/certificate_types_descriptions/bootstrap-certificates.html#expiration

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xiaojiey** [comment]
@jianzhangbjz Maybe you are the right person for this PR. Could you please take a look? Thanks.

**Review by snarayan-redhat — COMMENTED** [review]
Looks good.

**Review by kelbrown20 — COMMENTED** [review]
Updates lgtm!

**Pull request merged**
