### PR TITLE
add clarification about jsonpath escaping

### PR DESCRIPTION
**Pull request by jim-minter**
Bug 1463503
For 3.6.

### CODE REVIEW

**Comment by jim-minter** [comment]
@bparees fyi

**Comment by bparees** [comment]
lgtm. @openshift/team-documentation ptal/merge

**Comment by jim-minter** [comment]
@ahardin-rh ptal?

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Clarified that Kubernetes' JSONPath implementation interprets some characters as metacharacters, regardless of their position in the expression, unless they are escaped with a backslash.
%

**Pull request merged**
