### PR TITLE
OCPBUGS-42243#updating firewall list

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.14+ 

Issue:
https://issues.redhat.com/browse/OCPBUGS-42243

Link to docs preview:
- https://84416--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall
- https://84416--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_oci/installing-oci-agent-based-installer.html#configuring-firewall_installing-oci-agent-based-installer 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@yunjiang29, PTAL

**Review by adellape — APPROVED** [review]

**Pull request merged**
