### PR TITLE
Sizing guideline calculus is incorrect

### PR DESCRIPTION
**Pull request by akram**
Sizing guideline calculus is incorrect: We compute the rate in KB per min but then we make the computation for a whole day in seconds.
So the old sizing was 60 times bigger than the required one.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jeremyeder @jmencak PTAL

**Comment by jmencak** [comment]
Seems to makes sense.  "per minute -> 15KB" should also be adjusted to something like "per minute ~15KB" and count with that.  A bit messy and imprecise to my taste overall and should probably be rewritten.  @mffiedler should probably look at this for sanity since he took over after the original author.

**Comment by ahardin-rh** [comment]
@mffiedler PTAL

**Comment by mffiedler** [comment]
I think the author's original intent was not 256 bytes/min but 256 bytes/sec which is more realistic for logging.   That would make the 15KB/min correct and the original numbers more realistic.     I suggest reverting the calculations and having the change for this PR be:

Baseline (256 characters per second → 15KB/min)

**Comment by akram** [comment]
@mffiedler 
256 bytes/s was already the original assumption, which makes 256x60~=15KB/min
15KB/min is already correct.
What it not correct is 15KB/min x number of seconds of a day 
It should be: 15KB/min x number of minutes of a day

**Comment by akram** [comment]
@mffiedler I just amended my commit and fixed the Baseline unit also

**Comment by mffiedler** [comment]
@akram Thanks!

**Pull request merged**
