### PR TITLE
Update console screenshots

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@adellape do you happen to know what was used to get the numbers on the old screenshots?

also the note I added at the end of new_app.adoc isn't indented underneath step 4 like I would like, any thoughts on how to fix?

**Comment by adellape** [comment]
@jwforres Thanks for this.

> do you happen to know what was used to get the numbers on the old screenshots?

I was just manually putting them on there in GIMP, pretty un-fancy.

> also the note I added at the end of new_app.adoc isn't indented underneath step 4 like I would like, any thoughts on how to fix?

You can put a `+` on the blank line between the end of the `<8>` description and the start of the `[NOTE`].

**Comment by adellape** [comment]
@jwforres For `console_navigation.png`, can you chop the header out that shows Origin? Was trying to keep them variant-agnostic to keep it simple. Unless you feel strongly about keeping them in, in which case I suppose we'd want an OSE alternate.

**Comment by jwforres** [comment]
@adellape updated with the numbers, fixed indentation, cropped the header

**Comment by adellape** [comment]
:+1:

**Pull request merged**
