### PR TITLE
BZ-1907905: Adding a note about waiting if login fails

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1907905

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@retroflexer @hexfusion Let me know if this is what you were looking for, or if we need to change what this says. Also, if there's a particular error we'd expect them to see if the controllers haven't come up yet, that might be helpful to display.

**Comment by hexfusion** [comment]
I think this looks good I believe the error is 

```
Unable to connect to the server: EOF
```

**Comment by bergerhoffer** [comment]
Thanks @hexfusion, I see that now in the BZ, not sure how I missed it. I updated to include the error.

@geliu2016 Can you please review?

Preview: https://bz-1907905--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Comment by bobfuru** [comment]
LGTM. The note text floats between a couple of command code blocks, which looks a little odd in this case, although I'm not sure there's anything you should do about that.

**Comment by bergerhoffer** [comment]
@geliu2016 Can you review this update when you get a chance?

Preview: https://bz-1907905--ocpdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Comment by geliu2016** [comment]
LGTM，thanks

**Pull request merged**
