### PR TITLE
OSDOCS#8233: Operator SDK 1.31 Release note

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.14 only

Issue: [OSDOCS-8233](https://issues.redhat.com//browse/OSDOCS-8233)

Link to docs preview: https://66401--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-operator-sdk-1-31

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@aleskandro and @jaypoulz PTAL for the 4.14 release notes.

**Comment by michaelryanpeter** [comment]
@emmajiafan or @KeenonLee: PTAL

**Review by KeenonLee — COMMENTED** [review]
/lgtm
/label qe-approved

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Review by theishshah — APPROVED** [review]
/lgtm

**Pull request merged**
