### PR TITLE
OSDOCS-8833: Fixing backup lifecycle info for Kubernetes.

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4.14

Issue:
[OSDOCS-8833](https://issues.redhat.com/browse/OSDOCS-8833)

Link to docs preview:
[Virtual Storage management row in the Disaster Recovery table](https://71661--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix#rosa-policy-disaster-recovery_rosa-policy-responsibility-matrix)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by eohartman** [comment]
@xueli181114 Can you please QE this pull request? Thank you!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
