### PR TITLE
[OSDOCS-8685]:Correction required for 'autoscaling availability only on clusters purchased through Red Hat Marketplace'

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8685
Link to docs preview:

https://67644--docspreview.netlify.app/openshift-dedicated/latest/osd_cluster_admin/osd_nodes/osd-nodes-about-autoscaling-nodes
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @xueli181114 and/or @yingzhanredhat ,
    Could you please provide QE Review for this PR. Thanks! ML

**Comment by jab-rh** [comment]
@mletalie, LGTM.

**Comment by mletalie** [comment]
> @mletalie, LGTM.

**Pull request merged**
