### PR TITLE
Bug 1947248, added note to Compliance Operator installation instructions

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1947248

Preview build: https://deploy-preview-31746--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]
LGTM. Thanks for the update!

**Comment by ahardin-rh** [comment]
@pdhamdhe PTAL. Thank you!

**Review by adellape — APPROVED** [review]
:+1:

**Comment by ahardin-rh** [comment]
@pdhamdhe PTAL. Thank you!

**Comment by xiaojiey** [comment]
@ahardin-rh Could you move the bug to document component? Thanks. All other looks good to me.

**Pull request merged**
