### PR TITLE
[4.3] Subscribe SR-IOV Operator from right channel

### PR DESCRIPTION
**Pull request by zenghui-shi**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
In 4.3 environment:
```
# oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.3.0-0.nightly-2020-01-30-173504   True        False         18d     Cluster version is 4.3.0-0.nightly-2020-01-30-173504
```

`defaultChannel` returns 4.3
```
# oc get packagemanifest sriov-network-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'
4.3```

`.channels[].name` returns 4.2
```
# oc get packagemanifest sriov-network-operator -n openshift-marketplace -o jsonpath='{.status.channels[].name}'
4.2```

**Comment by jboxman** [comment]
@zhaozhanqi, can you confirm this change? Thank you!

**Comment by zshi-redhat** [comment]
@jboxman thanks for adding the branch labels for 4.3 and 4.4!  
One minor note is that when applying the change to 4.4, we will need to update the channel number in the doc from 4.3 to 4.4. Do you think we shall create a separate PR for 4.4 or just use this one ?

**Comment by jboxman** [comment]
@zshi-redhat, it will be easier to have separate PRs, I think.

Actually, can you rebase the 4.4 change against _master_ (and I can cherry-pick to _enterprise-4.4_), and the 4.3 change against _enterprise-4.3_?

Thanks!

**Comment by zshi-redhat** [comment]
> Actually, can you rebase the 4.4 change against _master_ (and I can cherry-pick to _enterprise-4.4_), and the 4.3 change against _enterprise-4.3_?

Here is the PR against master: https://github.com/openshift/openshift-docs/pull/20060
We can use this PR for 4.3 as it's created against 4.3 branch (I updated the title with 4.3 prefix).

**Comment by jboxman** [comment]
@zshi-redhat, perfect, thank you!

**Comment by jboxman** [comment]
@zhaozhanqi thanks!

**Comment by zshi-redhat** [comment]
@jboxman this one needs cherry-pick to 4.2 branch.

**Pull request merged**
