### PR TITLE
OBSDOCS-1069/TRACING-4282: OTEL document empty objects

### PR DESCRIPTION
**Pull request by max-cx**
:warning: This PR is tied to a product release date, which is currently set to **June 5** (Wednesday).

- If the merge review gets delayed, you're welcome to ping `mleonov` on Slack.
- If you have any questions, ping `mleonov` on Slack.

Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

Picking up https://github.com/openshift/openshift-docs/pull/75505 for managing the reviews and cherry-pick.

Version(s):

4.12, 4.13, 4.14, 4.15, 4.16

Issue:

https://issues.redhat.com/browse/OBSDOCS-1069
https://issues.redhat.com/browse/TRACING-4282

Link to docs preview:

QE review:
- [x] QE has approved this change in https://github.com/openshift/openshift-docs/pull/75505/files#r1608285397.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
This all looks good, but the PR linked to for QE approval doesn't appear to be related. Please be sure to get QE review.

**Comment by max-cx** [comment]
Closing this PR because I cherry-picked its commit into https://github.com/openshift/openshift-docs/pull/76340.

**Comment by kcarmichael08** [comment]
looks ok to merge when product ships

**Pull request merged**
