### PR TITLE
Add information about TZ for CronJobs

### PR DESCRIPTION
**Pull request by bergerhoffer**
Taking over #28488.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh Just some minor wording adjustments if you don't mind checking that this is still okay. Thanks!

@zhouying7780 Can you please review this as well? Thanks!

Preview: https://pr-28488-update--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/jobs/nodes-nodes-jobs.html#nodes-nodes-jobs-about_nodes-nodes-jobs

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
