### PR TITLE
Updated OpenShift to {product-title} in Architecture

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
So far, addressed Additional Concepts pages. Moving along through the Architecture book.

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tnguyen-rh @tpoitras  PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**Comment by ahardin-rh** [comment]
No rev history needed  :zap:

**Pull request merged**
