### PR TITLE
OCPBUGS#7068: Filestore CSI driver does not support clone

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-7068

Link to docs preview: https://58470--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gcharot, @duanwei33, @bertinatto, @sferich888, @mawerner

### CODE REVIEW

**Comment by mwerner2113** [comment]
LGTM

**Comment by duanwei33** [comment]
@chao007 Hi, please help take a look, thanks!

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Comment by gcharot** [comment]
lgtm

**Comment by sferich888** [comment]
lgtm

**Review by bertinatto — COMMENTED** [review]
LGTM

**Pull request merged**
