### PR TITLE
Bug 1338513 : ipfailover not working on cloud infra

### PR DESCRIPTION
**Pull request by bfallonf**
As per:

https://bugzilla.redhat.com/show_bug.cgi?id=1338513

I'll check in the BZ to see if anything else is needed.

### CODE REVIEW

**Comment by bfallonf** [comment]
[rev_history]
|link:../admin_guide/high_availability.html[High Availability]
|Added important box to link:../admin_guide/high_availability.html#configuring-ip-failover[Configuring IP Failover] section about using HA with AWS.
%

**Comment by bfallonf** [comment]
@adellape @ahaile-redhat @tpoitras @tnguyen-rh Peer review plz.

**Comment by ahardin-rh** [comment]
@bfallonf LGTM!

**Comment by bfallonf** [comment]
Cool. Merging. thanks @ahardin-rh

**Pull request merged**
