### PR TITLE
Added a note about NetworkPolicy storage migration

### PR DESCRIPTION
**Pull request by knobunc**
This should go into release 3.7 and 3.9.

Fixes bug 1570777 (https://bugzilla.redhat.com/show_bug.cgi?id=1570777)

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
/lgtm
thanks!

**Comment by bfallonf** [comment]
@knobunc PR looks good. But for some reason this file isn't live. It's live in other branches, and indeed in the repo. Not sure of the deal, but I've sent an email to the team to try figure out what the deal is. Will merge when I can.

**Comment by bfallonf** [comment]
@knobunc It turns out that the file was removed from the 3.7 spec because the issues in the file were no longer issues. I've put the file back in and removed the issues, but this created a conflict here.

To move this along, and to prevent you from going back to this, I'll close this PR and create a new one putting the info into 3.7 and 3.9.

Let me know if there's anything more needed.

**Comment by bfallonf** [comment]
Created #9054

**Pull request closed without merging**
