### PR TITLE
Go client documentation

### PR DESCRIPTION
**Pull request by jim-minter**
Add documentation for the OpenShift Go client

### CODE REVIEW

**Comment by jim-minter** [comment]
@bmcelvee ptal
@bparees fyi

**Comment by bparees** [comment]
(I reviewed this elsewhere, lgtm)

**Comment by bmcelvee** [comment]
Thanks, @jim-minter! I'll start reviewing this this afternoon or tomorrow. A couple of questions, is this tied to a Trello card (I did a quick search but didn't see one) and is this targeted for 3.9?

**Comment by jim-minter** [comment]
Hi @bmcelvee no trello card; it'd be good to get this into 3.9.  It's a bit of a stake in the ground for now - we can improve the details in subsequent PRs.

**Review by soltysh — APPROVED** [review]
lgtm

**Comment by jim-minter** [comment]
@bmcelvee is this going to be merged?

**Comment by bparees** [comment]
@openshift/team-documentation bump

**Comment by mburke5678** [comment]
@jim-minter @bparees Quick pass, LGTM. Why don't we merge to 3.9 and I can go back and clean up some editorial stuff.

**Comment by bparees** [comment]
> @jim-minter @bparees Quick pass, LGTM. Why don't we merge to 3.9 and I can go back and clean up some editorial stuff.

+1

**Comment by bmcelvee** [comment]
Thanks, @mburke5678!

**Comment by vikram-redhat** [comment]
@jim-minter @bparees - this has been merged to master which will make it available for the origin docs. For 3.9, Chris Negus and @bmcelvee will create a followup.

**Pull request merged**
