### PR TITLE
BZ-1946678: Adding details for ROPC grant flow

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1946678

Preview: https://deploy-preview-32014--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-oidc-identity-provider.html#add-identity-provider_configuring-oidc-identity-provider

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Looks good!

**Comment by stlaz** [comment]
/lgtm
:+1:

**Comment by bergerhoffer** [comment]
@rhpmali Can you please QE review this? Thanks!

Preview: https://deploy-preview-32014--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-oidc-identity-provider.html#add-identity-provider_configuring-oidc-identity-provider

**Pull request merged**
