### PR TITLE
RHDEVDOCS-4934 - Logging 5.5.10 release notes

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.9-4.12

Issue: [RHDEVDOCS-4934](https://issues.redhat.com//browse/RHDEVDOCS-4934)

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mramendi — APPROVED** [review]

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
