### PR TITLE
Unify the similar 'Moving monitoring stack components' modules into one

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-440

Currently there are two different modules on moving the Monitoring components, in the [Machine Management](https://docs.openshift.com/container-platform/4.8/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-monitoring_creating-infrastructure-machinesets) and [Monitoring](https://docs.openshift.com/container-platform/4.8/monitoring/configuring-the-monitoring-stack.html#moving-monitoring-components-to-different-nodes_configuring-the-monitoring-stack) books.

This PR replaces the module in the Machine Management assembly with the Monitoring module, as it was recently updated. 
 
Preview of _Machine Management_ -> _Creating infrastructure machine sets_ with the new module:
 https://deploy-preview-35386--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets?utm_source=github&utm_campaign=bot_dp#moving-monitoring-components-to-different-nodes_creating-infrastructure-machinesets

### CODE REVIEW

**Comment by mburke5678** [comment]
@thoraxe Some time back, [you asked that a topic be added to the 4.x docs about moving the Monitoring components](https://bugzilla.redhat.com/show_bug.cgi?id=1688487). Somewhere [another topic on moving the Monitoring components was added](https://github.com/openshift/openshift-docs/pull/14149) to the Monitoring docs.  
[OCDOCS-440](https://issues.redhat.com/browse/OSDOCS-440) asked that we _unify_ these two topics. In response, I replaced the topic in Machine Management with the topic from Monitoring (as the latter was more recently updated and more detailed. So, the same file is used in both places. 
Do you see any reason not to make this change? Or perhaps you could refer someone if you are not appropriate to comment? 
Thank you in advance!

**Comment by thoraxe** [comment]
@mburke5678 I'm all for standardization/consolidation.

IMO: Every "component" should have a supported and documented ability to specify targeted nodes, and the organization of the docs for doing so should likely be the same for every component.

:)

**Comment by mburke5678** [comment]
@juzhao Would you be the appropriate person to review this PR for QE?

**Comment by juzhao** [comment]
@mburke5678  LGTM, the same modules on moving the Monitoring components in the Machine Management and Monitoring books, just have one question:
we have the same "Moving monitoring components to different nodes" section under Monitoring, see:
https://deploy-preview-35386--osdocs.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack.html#moving-monitoring-components-to-different-nodes_configuring-the-monitoring-stack
do you think we should remove the section from Monitoring?

**Comment by mburke5678** [comment]
@lihongan @thoraxe @pneedle-rh 

I beleive @juzhao is [right](https://github.com/openshift/openshift-docs/pull/35386#issuecomment-897324197). The moving monitoring concept is in the docs 4 times, 3 of which specifically to infrastructure nodes. The topic in the monitoring docs describes how to move the components to any node. 

Post install -> Cluster tasks -> Moving resources to infrastructure machine sets
https://docs.openshift.com/container-platform/4.8/post_installation_configuration/cluster-tasks.html#infrastructure-moving-monitoring_post-install-cluster-tasks

Scalability and Performance -> OpenShift Container Platform infrastructure components
https://docs.openshift.com/container-platform/4.8/scalability_and_performance/recommended-host-practices.html#infrastructure-moving-monitoring_

Machine management -> Moving resources to infrastructure machine sets
https://docs.openshift.com/container-platform/4.8/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-monitoring_creating-infrastructure-machinesets

Monitoring -> Configuring the monitoring stack
https://docs.openshift.com/container-platform/4.8/monitoring/configuring-the-monitoring-stack.html#moving-monitoring-components-to-different-nodes_configuring-the-monitoring-stack

What if we add an example config map showing how to move the monitoring components to the infra nodes in the `monitoring-moving-monitoring-components-to-different-nodes.adoc` module and use that in all 4 places? Is this too much?
https://deploy-preview-35386--osdocs.netlify.app/openshift-enterprise/latest/machine_management/creating-infrastructure-machinesets?utm_source=github&utm_campaign=bot_dp#moving-monitoring-components-to-different-nodes_creating-infrastructure-machinesets

**Comment by mburke5678** [comment]
@lihongan @thoraxe Any thoughts?

**Comment by thoraxe** [comment]
@mburke5678 I think this is still a bit "all over the place", but using the same example in all four places is probably good.

**Comment by lihongan** [comment]
> @lihongan @thoraxe Any thoughts?

@mburke5678  I think you want to at @lihongyan1 not me, right :)

**Comment by lihongyan1** [comment]
> @lihongyan1 Any thoughts?

According to #issuecomment-897664803,  the moving monitoring concept is in the docs 4 times, it would be better to doc in one place and refer it from other place.

**Pull request closed without merging**
