### PR TITLE
RHDEVDOCS-6098: Correct OCP version fix

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.13

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6098

Link to docs preview:

[Compatibility and support matrix](https://78702--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#GitOps-compatibility-support-matrix_gitops-release-notes)

QE review:
- [ ] QE has approved this change.

SME review: [anjoseph@redhat.com](mailto:anjoseph@redhat.com)
QE review: @varshab1210 
Peer review:

Additional information:

### CODE REVIEW

**Comment by varshab1210** [comment]
LGTM

**Review by anandf — APPROVED** [review]
LGTM

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by sheriff-rh — APPROVED** [review]
Changes LGTM; merging to gitops-docs-1.13.

**Pull request merged**
