### PR TITLE
RHDEVDOCS-3164 Build release notes, Known Issues and Bug Fixes for 4.9

### PR DESCRIPTION
**Pull request by rolfedh**
- Aligned team: Dev Tools
- For branches: enterprise-4.9 release notes
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3164
- Direct link to doc preview: https://deploy-preview-37160--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-builds
- SME review: @adambkaplan 
- QE review: @gabemontero
- Peer review: @bburt-rh 
- All reviews complete. Ready to merge.

### CODE REVIEW

**Comment by rolfedh** [comment]
@adambkaplan   Can you tell me more this request to create a release note for "Automatic RHEL Entitlement Management for Builds, 4.9 Tech Preview" here:
https://github.com/openshift/openshift-docs/issues/33497#issuecomment-937329122
Where can I get more info?

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by bburt-rh** [comment]
lgtm

**Review by gabemontero — CHANGES_REQUESTED** [review]
@rolfedh I've made suggested changes

**Pull request merged**
