### PR TITLE
OSDOCS#3994: ROSA - port 'Scalability and performance' content from OCP

### PR DESCRIPTION
**Pull request by tmalove**
This PR is to port the "Scalability and performance" OCP content to ROSA. Reference that section only for comments, reviews, etc.
[OSDOCS-3994](https://issues.redhat.com/browse/OSDOCS-3994)

Version(s):

Link to docs preview: https://file.rdu.redhat.com/tlove/sd-port-scale-tlove-main-branch/scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices.html#recommended-scale-practices_recommended-control-plane-practices  (Updated 03/21)

QE review: 

- [ ] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @xiaojiey is your team able to verify this PR for porting the `Scalability and performance` section? Thanks!

**Comment by xiaojiey** [comment]
> Hi @xiaojiey is your team able to verify this PR for porting the `Scalability and performance` section? Thanks!

@sunzhaohua2 will help to review to it.

**Comment by sunzhaohua2** [comment]
1. `Backing up etcd` link was not added to `Additional resources`
2. The command like `$ oc --namespace openshift-machine-api edit controlplanemachineset.machine.openshift.io cluster` only take affect for classic clusters, for host clusters this couldn't be run as host cluster is cluster api. not sure if we need to point this out.

**Comment by tmalove** [comment]
This PR is ready for review.
@arendej @bchandra-ocp 

cc: @karanthshashank @AndrewJones-RH

**Comment by tmalove** [comment]
Review request: @arendej @bchandra-ocp @sunzhaohua2 
cc: @AndrewJones-RH @karanthshashank 

Thanks!

**Comment by sunzhaohua2** [comment]
I still have concern about the command like `$ oc --namespace openshift-machine-api edit controlplanemachineset.machine.openshift.io cluster` this only take affect for classic clusters, on host clusters this cant be ran, maybe we need to add a note.

**Comment by tmalove** [comment]
> I still have concern about the command like `$ oc --namespace openshift-machine-api edit controlplanemachineset.machine.openshift.io cluster` this only take affect for classic clusters, on host clusters this cant be ran, maybe we need to add a note.

Thanks @sunzhaohua2 Is there a version of this command that is valid for host clusters? If so, let me know what it is and I will add a note. Otherwise, I will add a note per your suggestion.

**Comment by tmalove** [comment]
Hi @sunzhaohua2  Direct all comments to this PR: https://github.com/openshift/openshift-docs/pull/73423
This newer PR for the Performance and scalability porting is based on the 'main' branch and is required before we can merge this information. I will close this older version and refer to it in the new PR. Thanks.
cc: @AndrewJones-RH @karanthshashank @arendej @bchandra-ocp

**Comment by tmalove** [comment]
See new [PR](https://github.com/openshift/openshift-docs/pull/73423).

**Pull request closed without merging**
