### PR TITLE
RHDEVDOCS-5366: Remove embedded-status field and TP for resolvers in …

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.12 and later
• **JIRA issue**: [RHDEVDOCS-5366](https://issues.redhat.com/browse/RHDEVDOCS-5366)
• **Preview page**: [Configuring pipeline resolvers](https://60767--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/customizing-configurations-in-the-tektonconfig-cr.html#op-configuring-pipeline-resolvers_customizing-configurations-in-the-tektonconfig-cr), [Modifiable fields with default values](https://60767--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/customizing-configurations-in-the-tektonconfig-cr.html#op-modifiable-fields-with-default-values_customizing-configurations-in-the-tektonconfig-cr)
• **SME Review**: Completed by @vdemeester 
• **QE review**: Completed by @ppitonak 
• **Peer-review**: Completed by @Srivaralakshmi 
**These changes are for Pipelines version 1.11.**

### CODE REVIEW

**Comment by ppitonak** [comment]
@vdemeester I'm quite confused - TektonConfig doesn't contain `embedded-status` field in 1.11 but when I set it, it is accepted. Is that correct?

**Comment by vdemeester** [comment]
> @vdemeester I'm quite confused - TektonConfig doesn't contain `embedded-status` field in 1.11 but when I set it, it is accepted. Is that correct?

Yes, it is gone in 1.11 🙃

**Review by ppitonak — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Review by Srivaralakshmi — APPROVED** [review]
Clean PR - excellent work! Approved!

**Comment by shipsing** [comment]
cherry-pick the content to enterprise 4.12, 4.13, and 4.14

**Pull request merged**
