### PR TITLE
Adding note about FlexVolume plug-in location change

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@gnufied Can you please make sure this information is still correct for 4.2/4.3? I've added it in now that we have the FlexVolume section in the docs.

**Comment by ahardin-rh** [comment]
Looks great!

**Comment by bergerhoffer** [comment]
SME approved, and this text was QE reviewed before it was commented out. Merging!

**Pull request merged**
