### PR TITLE
remove atomic-registry docs

### PR DESCRIPTION
**Pull request by aweiteka**
Atomic Registry has been deprecated

Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@vikram-redhat, thoughts?

**Comment by aweiteka** [comment]
Specifically, these docs are no longer hosted on http://docs.projectatomic.io/registry/
There are no builds of the atomic-registry distribution being hosted.

**Comment by vikram-redhat** [comment]
@aweiteka - do we need to leave a message or redirects setup? Anything in release notes?

cc: @aheslin

**Comment by aweiteka** [comment]
> do we need to leave a message or redirects setup? Anything in release notes?

@vikram-redhat No redirects necessary. External validation includes [this thread to remove the atomic registry installer](https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2017-November/msg00068.html) and [this PR that removes the atomic registry documentation](https://github.com/projectatomic/atomic-site/pull/515).

**Comment by kalexand-rh** [comment]
All the ifdef/endif statements look good. I checked out the PR, and all references to atomic-registry are removed, but there are a couple of files that reference "Atomic Registry." Finishing up on https://github.com/openshift/openshift-docs/pull/9234.

**Pull request closed without merging**
