### PR TITLE
MIG-1419: updating attributes for MTC 1.8.0

### PR DESCRIPTION
**Pull request by anarnold97**
[MIG-1419](https://issues.redhat.com/browse/MIG-1419)

Attributes update for MTC 1.8.0:

Changed:

* **:mtc-version: 1.7** to **:mtc-version: 1.8**
* **:mtc-version-z: 1.7.10** to **:mtc-version-z: 1.8.0** 

Version(s):

Enterprise 4.11 → branch/enterprise-4.11
Enterprise 4.12 → branch/enterprise-4.12
Enterprise 4.13 → branch/enterprise-4.13
Enterprise 4.14 → branch/enterprise-4.14

Issue:

https://issues.redhat.com/browse/MIG-1419

Link to docs preview:

* No doc preview required

QE review:
- [ ] QE has approved this change.

Does this need QE approval as we are simply moving the release version forward?

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
/label peer-review-needed

* Does this need QE approval as we are simply moving the release version forward?

**Review by skopacz1 — APPROVED** [review]
LGTM! 

I would get QE ack on this, even if it's a small version bump. It technically changes the meaning of content that uses these variables, so I think that qualifies for QE review.

**Comment by anarnold97** [comment]
@skopacz1 - please can I check if this needs QE review... it is only an attribute update afterall?

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by anarnold97** [comment]
@stillalearner - thanks so much, Sachin. appreciate it

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by jeana-redhat** [comment]
Testing rate limit issue with cherrypick commands

/cherrypick enterprise-4.14
/cherrypick enterprise-4.13
/cherrypick enterprise-4.12
/cherrypick enterprise-4.11

**Pull request merged**
