### PR TITLE
BZ#1950174 Remove unnecessary GCP UPI step

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1950174

Based on openshift/installer#4849

Previews:
- https://deploy-preview-31587--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra.html#installation-creating-gcp-control-plane_installing-gcp-user-infra
- https://deploy-preview-31587--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-user-infra-vpc.html#installation-creating-gcp-control-plane_installing-gcp-user-infra-vpc

### CODE REVIEW

**Comment by codyhoag** [comment]
@tsze-redhat PTAL

**Comment by tsze-redhat** [comment]
LGTM. Thanks!

**Review by adellape — COMMENTED** [review]
:+1:

**Pull request merged**
