### PR TITLE
Update instructions specific to multi-tenant plugin.

### PR DESCRIPTION
**Pull request by ramr**
@zhaozhanqi FYI, updates for using the ramp node w/ a multi-tenant sdn plugin. Thx

Thanks @dcbw for the ovs-ocftl commands. 

@adellape / @bfallonf   PTAL - this is adding instructions for QE for using the multi-tenant sdn plugin. 
Please don't merge until  @zhaozhanqi  confirms. Thx

### CODE REVIEW

**Comment by ramr** [comment]
@zhaozhanqi  can you please confirm this is good now and can be merged.  Thx

**Comment by zhaozhanqi** [comment]
@ramr 
I restalled one env and following the configuration, this works well, thanks

**Comment by dcbw** [comment]
LGTM

**Comment by adellape** [comment]
@ramr Content LGTM, though the PR has conflicts because I moved some topics (including this one) from the admin_guide into the install_config book last night.

**Comment by adellape** [comment]
Closed in favor of https://github.com/openshift/openshift-docs/pull/1205

**Comment by bfallonf** [comment]
@adellape As this is closed, can we remove the followup label to this PR?

**Comment by adellape** [comment]
@bfallonf Totes.

/me removes

**Pull request closed without merging**
