### PR TITLE
CNV-37381: Remove "not supported" statement for EBS and EF

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-37381

OCP 4.14+

Preview:
https://72526--ocpdocs-pr.netlify.app/openshift-dedicated/latest/virt/install/preparing-cluster-for-virt.html

### CODE REVIEW

**Comment by sbeskin-redhat** [comment]
@jpeimer 
Hi, 
Your name appears in the Jira ticket (https://issues.redhat.com/browse/CNV-37381) as 'QA contact'. Could you check this PR?
Thank you

**Comment by sbeskin-redhat** [comment]
Approved by the SME  in Jira

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Comment by bmcelvee** [comment]
LGTM

**Pull request merged**
