### PR TITLE
Add Thanos to the component list

### PR DESCRIPTION
**Pull request by rh-max**

### CODE REVIEW

**Review by sichvoge — CHANGES_REQUESTED** [review]

**Comment by rh-max** [comment]
@bmcelvee Brandi, could you PTAL, merge and cherry-pick to `enterprise-4.3` and `enterprise-4.4`? Thanks.

**Comment by rh-max** [comment]
@bmcelvee The BZ is https://bugzilla.redhat.com/show_bug.cgi?id=1813211.

**Comment by rh-max** [comment]
@bmcelvee This received a technical review, and no further (QE) review needed.

**Comment by bmcelvee** [comment]
LGTM - please squash the commits and I'll go ahead with the merge and cherry pick. :)

**Comment by rh-max** [comment]
@bmcelvee Squashed. Thanks!

**Pull request merged**
