### PR TITLE
remove scheduler.alpha.kubernetes.io/affinity

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@aveshagarwal PTAL. is this all that is needed to remove `scheduler.alpha.kubernetes.io/affinity`?

**Comment by aveshagarwal** [comment]
@mburke5678 lgtm.

**Comment by mburke5678** [comment]
Removing this text from 3.9+ based on @aveshagarwal email:
"So i think we should remove references to them from our docs for releases after than 1.7 i think."

**Pull request merged**
