### PR TITLE
Clarified details in CloudFront configuration references

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up edits per discussion with @miminar

### CODE REVIEW

**Comment by adellape** [comment]
:+1: LGTM.

**Comment by ahardin-rh** [comment]
@miminar PTAL when you get a moment. Thanks!

**Comment by miminar** [comment]
@ahardin-rh LGTM, thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/docker_registry.adoc#install-config-install-docker-registry[Deploying a Docker Registry]
|Clarified details in CloudFront configuration references.
%

**Pull request merged**
