### PR TITLE
Updated version numbers of MySQL, PHP, Python, Ruby

### PR DESCRIPTION
**Pull request by ahardin-rh**
Per discussion with @luciddreamz

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@luciddreamz @adellape PTAL. Thanks!

**Comment by luciddreamz** [comment]
Looks good. There is another set of updates coming shortly. I'll try to remember to send a reminder your way upon release, but I think Alex was already working on something for that one.

**Comment by adellape** [comment]
@ahardin-rh Can you compare this against the changes made this week in https://github.com/openshift/openshift-docs/pull/2468?

See revhistory here in OSE guide:

https://docs.openshift.com/enterprise/latest/using_images/revhistory_using_images.html#tue-jul-05-2016

It looks like this PR is undoing some of that, but also adding others. Does it need to be ifdef'd between what's available for Online vs OSE?

**Comment by ahardin-rh** [comment]
@adellape thanks! I will take a look. According to @luciddreamz, these changes are valid for online, enterprise, and dedicated.

**Comment by ahardin-rh** [comment]
@adellape updated after discussion with @luciddreamz. This work adds additional version numbers to Python and Ruby.
Reference: https://www.openshift.com/features/cartridges.html

**Comment by adellape** [comment]
LGTM. :sweet_potato:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/db_images/mysql.adoc#using-images-db-images-mysql[Database Images -> MySQL]
|Updated MySQL version numbers supported by {product-title}.
%
|xref:../using_images/s2i_images/php.adoc#using-images-s2i-images-php[Source-to-Image (S2I) -> PHP]
|Updated PHP version numbers supported by {product-title}.
%
|xref:../using_images/s2i_images/python.adoc#using-images-s2i-images-python[Source-to-Image (S2I) -> Python]
|Updated Python version numbers supported by {product-title}.
%
|xref:../ using_images/s2i_images/ruby.adoc#using-images-s2i-images-ruby[Source-to-Image (S2I) -> Ruby]
|Updated Ruby version numbers supported by {product-title}.
%

**Pull request merged**
