### PR TITLE
bugfix: rename ibm_cloud* subdirectories rebase

### PR DESCRIPTION
**Pull request by sean-freeman**
Too many changes in main and in PR to perform normal rebase, this is replacement of PR #81593. Move all content currently under `*ibm_cloud` to `*ibm_cloud_classic`, as all this content refers to `IBM Cloud (Classic)`; see additional information. Subsequently move all content currently under `*ibm_cloud_public` to `*ibm_cloud`, as there is no distinction - as defined by Gartner, Cloud Service Providers (CSP) which operate Public Clouds and are considered Hyperscalers are AWS, MS Azure, GCP, IBM Cloud, Oracle Cloud.

Version(s):
4.14+, apply content fix to latest and future releases only

Issue:
- None (GH or Jira), this is community author contribution

Link to docs preview:
The following previews show that the IBM cloud and IBM cloud classic directories are named and laid out correctly.
- [Preparing to install on IBM cloud](https://82684--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud)
- [IBM Cloud bare metal prerequisites](https://82684--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_classic/install-ibm-cloud-prerequisites)

QE review:
- [ ] QE has approved this change.

Additional information:
- Bugfix to rename related content in subdirectory correctly titled for `IBM Cloud (Classic)`, formerly Softlayer; akin to `AWS (Classic)` and `MS Azure (Classic/ASM)` which are unsupported by OpenShift

### CODE REVIEW

**Comment by sean-freeman** [comment]
8x matches for:

`OpenShiftAsciiDoc.SuggestAttribute: Use the AsciiDoc attribute '{ibm-cloud-title}' rather than the plain text product term 'IBM Cloud', unless your use case is an exception.`


1x matches for:

`OpenShiftAsciiDoc.XrefContainsAnchorID: The xref is missing an anchor ID.`

**Comment by kalexand-rh** [comment]
@SNiemann15, will you PTAL?

**Comment by bscott-rh** [comment]
PR LGTM from an Asciidoc perspective, however this should wait for @SNiemann15 as she is the primary IBM writer in this area.

**Comment by sean-freeman** [comment]
@bscott-rh For awareness, she is OOO for the next 10 days. I would hesitate to block this PR, as other changes in `main` branch may cause conflicts like before - all the changes are just to fix the subdirectory paths (and fixing the vale-bot complaints when the files were re-scanned, so the PR would not be blocked).

N.B. I would seek other writers for each subset infrastructure platform, as her responsibility/focus is IBM Z.  See business structure summary below which does align to the different subdirectories in the OCP documentation.

- IBM Infrastructure  _(top-line unit, others are IBM Consulting, IBM Software, IBM Research)_
    - IBM Cloud
    - IBM Power
    - IBM Z
    - IBM Storage

**Comment by sstout-rh** [comment]
@sean-freeman , @bscott-rh is reaching out to the IBM Power writer, and taking a look at the IBM Cloud component, which was covered by an OCP core team member, not an IBM writer. 
I am late to the conversation, but can you explain why these changes are needed now? Apologies if I am missing something, but it looks like you had previous merge conflicts that you are trying to avoid. Can you provide a bit more background?

**Comment by sean-freeman** [comment]
@sstout-rh Changes are required for 2 reasons:
- correction to naming with alignment to all other Hyperscaler Public Cloud Service Providers (as defined by Gartner - AWS, MS AZ, GCP, IBM Cloud, OCI, Alibaba) within the OCP Docs; and to avoid end-user confusion with inaccurate naming
- future content updates, I am from IBM Cloud product team so I'll leave it at that and let between the lines work it's magic

Merge conflicts are just because someone elses commit edited many files at once and happened to edit some of the files where IBM Cloud is mentioned :)  This PR itself would have been 2 commits simple subdir renames, had it not been for vale-bot complaints

> N.B. An IBM Power writer is equally inappropriate to make decisions about IBM Cloud content

**Comment by bscott-rh** [comment]
@sean-freeman The changes look good to me. Please squash your commits to 1 commit and I will forward for merge review.

what do you mean by " 4.14+, apply content fix to latest and future releases only"? This seems contradictory. should this be applied to 4.14+, or only to 4.17 (which is latest) and main (which will carry into future releases)?

**Comment by sean-freeman** [comment]
@bscott-rh 

For the 2 main commits, I cannot squash without causing git to believe I am adding new files and deleting others - thereby losing all of the file's history. I already attempted this and it is much more important to keep the file history.

The 3x vale-bot commits, I can squash those. I would have done it all in 1 commit if vale-bot had been clearer / added all complaints at the same time.

---

I was meaning, it has to be retroactive only to a point:
- OpenShift 4.14 is the latest version for Managed Service deployment (IBM Cloud ROKS in this case, but I think all like ROSA and ARO are on this version)
- OpenShift 4.17 is the latest and I assume there is already something for 4.18 in one of the branches

So, change should apply to 4.14, 4.15, 4.16, 4.17 branches.

**Comment by sean-freeman** [comment]
@bscott-rh I believe this is ready to merge, as mentioned previously I squashed the 3 commits for vale-bot into 1 commit. The others I left intact.

**Comment by bscott-rh** [comment]
@sean-freeman I am not sure what you mean about losing file history, but per the [openshift docs manual](https://docs.google.com/document/u/2/d/e/2PACX-1vRLKWEMHQ3DZroxZKfTu3XcrSdREr6D3oSSayBanEprXhkA2Ciyr2SQuDTYI4aIKUiOPPIQMHgjHeh8/pub#h.rgukz7k78tb5) you need to squash down to 1 commit before the PR is ready to merge.

**Comment by sean-freeman** [comment]
@bscott-rh As described, when renaming many files with small (<5%) changes it is common for `git` to not recognise the changes as renamed files. When a file is renamed, the git file history is retained. When a file is deleted and added, all git file history is lost.

Please do not make me squash to 1 commit. I am exceedingly sure it will cause the outcome I describe, and make it much harder for tracking of file history / maintenance of the files going forward.

If you insist then I will do as requested, but I will not be held responsible or feel guilty for any repercussions.

**Comment by bscott-rh** [comment]
@sean-freeman, our program manager @kalexand-rh has tested this locally and we're confident that squashing these commits will not cause an issue for the repo. going forward, please take care to observe the [contribution guidelines](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/contributing.adoc) and direction from repo maintainers.

Note that there may be a delay before these changes are present on docs.redhat.com due to the extra work that renaming directories creates in the publishing backend. Thank you

**Comment by sean-freeman** [comment]
@bscott-rh Squashed as requested.

File history has been lost for `installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.adoc` when renamed to `installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.adoc`

**Review by sheriff-rh — APPROVED** [review]
Changes look good, very thorough work! Merging.

**Comment by sean-freeman** [comment]
@sheriff-rh That is far too many conflicts to resolve, looks like the commit attempts to update the content of each file at the same time. Which just means the 4.14 content would become 4.17 content - we're not going to do that.

This will have to apply from 4.17 onwards and not be backported. Will have to manually keep an eye on branches [enterprise-4.14](https://github.com/openshift/openshift-docs/tree/enterprise-4.14), [enterprise-4.15](https://github.com/openshift/openshift-docs/tree/enterprise-4.15), [enterprise-4.16](https://github.com/openshift/openshift-docs/tree/enterprise-4.16) if there are any content updates for IBM Cloud.

Although I hope there will be very few changes to older versions, and we can just continue onwards from 4.17

**Pull request merged**
