### PR TITLE
OSDOCS-2951: Clarify Language for Multicast Process

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-2951

Preview for ROSA: https://deploy-preview-38640--osdocs.netlify.app/openshift-rosa/latest/networking/openshift_sdn/enabling-multicast.html
Preview for OSD: https://deploy-preview-38640--osdocs.netlify.app/openshift-dedicated/latest/networking/openshift_sdn/enabling-multicast.html

### CODE REVIEW

**Comment by bmcelvee** [comment]
@arendej would you mind reviewing this PR, please? Thanks!

**Comment by bmcelvee** [comment]
@weliang1 would you mind giving this PR a review, please? Thanks!

**Review by arendej — APPROVED** [review]
/lgtm

**Pull request merged**
