### PR TITLE
Card origin_devexp_538 - Added information about sti build loglevels

### PR DESCRIPTION
**Pull request by soltysh**
/fyi @bparees @mfojtik

### CODE REVIEW

**Comment by bparees** [comment]
lgtm.

**Comment by mfojtik** [comment]
lgtm

**Comment by adellape** [comment]
@soltysh Thanks, merging.

Related docs card for follow up: https://trello.com/c/y7AKqptv

**Comment by tnguyen-rh** [comment]
@mfojtik @bparees @soltysh 
If there is both BUILD_LOGLEVEL (in the build config) and "openshift start --loglevel" (command-line option), which one wins?

**Comment by bparees** [comment]
build_loglevel would win.

**Comment by tnguyen-rh** [comment]
@bparees Thanks.
PR: https://github.com/openshift/openshift-docs/pull/457

**Pull request merged**
