### PR TITLE
updated ceph to remove directory

### PR DESCRIPTION
**Pull request by erinboyd**
removed sub-directory for ceph

### CODE REVIEW

**Comment by erinboyd** [comment]
@adellape this is currently broke, can you please merge ASAP

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
No revhistory, should be picked with https://github.com/openshift/openshift-docs/pull/1772.

**Comment by erinboyd** [comment]
thanks @adellape

**Pull request merged**
