### PR TITLE
Update CO version for oc get clusteroperator/network command

### PR DESCRIPTION
**Pull request by dpateriya**
Update CO version for oc get co/network command

Version(s):
OCP 4.16

Issue:
Update CO version for oc get co/network command

Link to docs preview:

https://79472--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/cluster-network-operator.html#nw-cluster-network-operator_cluster-network-operator

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by dpateriya** [comment]
@mburke5678 I am not sure who is going to do QE approval for this.

**Review by jeana-redhat — APPROVED** [review]
Oh wow htat was really old! Thanks for updating :) LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
