### PR TITLE
Update host_preparation.adoc

### PR DESCRIPTION
**Pull request by Klaas-**
from my understanding the parts about --insecure-registry are not needed here anymore. It's changed automatically during install.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL?

**Comment by jianlinliu** [comment]
LGTM

**Comment by kalexand-rh** [comment]
Thank you! This file moved in 3.10, so I'll be making some manual PRs to apply the change to earlier versions.

**Pull request merged**
