### PR TITLE
GitHub-30414: Adding note for GitHub Enterprise only

### LINKED ISSUE #30414: [enterprise-4.7] Issue in file authentication/identity_providers/configuring-github-identity-provider.adoc
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider

### What needs fixing?

It should be noted that this section should say "This step only needs to be done if you're using an on-prem installation of GitHub"

### PR DESCRIPTION
**Pull request by bergerhoffer**
Fixes #30414

Preview: https://deploy-preview-30434--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@christianh814 If you can make sure that this looks good to you. Thanks!

Preview: https://deploy-preview-30434--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider

**Comment by bergerhoffer** [comment]
@rhpmali Can you please review this? 

Preview: https://deploy-preview-30434--osdocs.netlify.app/openshift-enterprise/latest/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
