### PR TITLE
CNV#20240: RN vTPM persistent state

### PR DESCRIPTION
**Pull request by sjhala-ccs**
Version(s): 4.14

Issue: [CNV-20240](https://issues.redhat.com//browse/CNV-20240)

Link to docs preview: https://65983--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-new

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by stu-gott** [comment]
Looks good from my PoV, but enlisting Jed for a second glance.

**Comment by jean-edouard** [comment]
Thanks for the heads-up @stu-gott !
Not sure what qualifies as a CHANGE vs NEW, but to me this is a new feature, nothing "changed" for existing vTPM users.
Also, to use persistence, specifying a storage class in the HCO CR is not enough, you also need to set "persistent: true" on the vTPM device in the VM spec.
Other than that, looks good to me!

**Comment by vsibirsk** [comment]
Looks good to me.

> Thanks for the heads-up @stu-gott ! Not sure what qualifies as a CHANGE vs NEW, but to me this is a new feature, nothing "changed" for existing vTPM users. Also, to use persistence, specifying a storage class in the HCO CR is not enough, you also need to set "persistent: true" on the vTPM device in the VM spec. Other than that, looks good to me!

Don't know if it's relevant info for release notes. It already points to a page where all config is detailed (both for storage and for vm)

**Review by maxwelldb — APPROVED** [review]

**Pull request merged**
