### PR TITLE
BZ2022593: Removed limitation of RWNs being only supported on UPI bare metal clusters

### PR DESCRIPTION
**Pull request by amolnar-gh**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2022593

Preview: https://deploy-preview-39235--osdocs.netlify.app/openshift-enterprise/latest/nodes/edge/nodes-edge-remote-workers.html

For releases: 4.9, 4.10

### CODE REVIEW

**Comment by amolnar-rh** [comment]
Hi @reihl! Could you please take a look at let me know if it looks good from QE side as well? Thank you!

**Comment by reihl** [comment]
@amolnar-rh /LGTM
We tested this on 4.8 UPI is no longer one of the requirements

**Comment by imain** [comment]
LGTM

**Comment by ctauchen** [comment]
@amoldar-rh Hi! This looks good, but it needs change management. If/When that's done, let me know and we can get this merged.

**Comment by amolnar-rh** [comment]
@ctauchen Thanks for the quick review! Let me get back to you!

**Pull request merged**
