### PR TITLE
To remove TP statements from IPI and CSI Driver documentation

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/MULTIARCH-4115

Link to docs preview:
https://74134--ocpdocs-pr.netlify.app/
https://74134--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-customizations.html
https://74134--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-private-cluster.html
https://74134--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-powervs-vpc.html
https://74134--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-ibm-powervs-block.html

QE review:
- [x] QE has approved this change.

- [x] CM ack

Additional information:

- An indentation of a parameter (`vpcRegion`) is fixed here : https://74134--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_ibm_powervs/installing-ibm-power-vs-customizations.html#installation-ibm-power-vs-config-yaml_installing-ibm-power-vs-customizations

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
looks good to me. This would still need a QE review before merging if you have not obtained that yet.

**Comment by alishaIBM** [comment]
> looks good to me. This would still need a QE review before merging if you have not obtained that yet.

We have the QE approval above for this change.

**Comment by alishaIBM** [comment]
PTAL: @sferich888, @davemulford, @xltian, @kalexand-rh, @sjstout

**Pull request merged**
