### PR TITLE
Minor content fixes

### PR DESCRIPTION
**Pull request by jboxman**
@openshift/team-documentation, PTAL. Thanks.

### CODE REVIEW

**Review by jhoyt-rh — COMMENTED** [review]
A couple of nits:

Needs release label


|Display label for component (e.g., "critical", "important", "moderate", "low" or "health")

|Display label for component (for example, "critical", "important", "moderate",
	"low" or "health")

s/"critical", "important", "moderate","low" or "health")/ sb/"critical," "important," "moderate," "low," or "health")

Since these are not programming elements, I would put the commas inside the quotes -- and also use the comma before "or health."
From IBM Style Guide:

Commas with quotation marks
In most cases, place commas inside closing quotation marks. For details about using commas
with quotation marks, see “Quotation marks with other punctuation” on page 66.

Quotation marks with other punctuation
In most cases, place commas and periods inside closing quotation marks, and place other punctu-
ation marks outside.
Examples
For more information, see the chapter named “Semantic tagging,” which provides examples
and a tutorial.
She said, “You meet all the requirements for promotion.”
Unless a punctuation mark is part of the syntax, do not place a punctuation mark inside the quota-
tion marks of these items:
• Coding statements
• Symbolic names
• Hexadecimal, binary, or octal values
• Other programming elements that use quotation marks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+The following example call using `curl` will overwrite the value of the

suggest not using future tense "will overwrite" 

suggest /overwrites the value

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
is the format tagging correct for '<token>'  etc.???

**Comment by jboxman** [comment]
@jhoyt-rh, which format tagging?

> is the format tagging correct for '<token>'  etc.???

Thanks.

**Pull request merged**
