### PR TITLE
[BZ2056621] An attempt to add the description for cluster-reader

### PR DESCRIPTION
**Pull request by mdekan1**
https://bugzilla.redhat.com/show_bug.cgi?id=2056621

### CODE REVIEW

**Comment by mdekan1** [comment]
@jboxman-rh could you review this?

**Review by mffiedler — APPROVED** [review]
LGTM

**Comment by jboxman-rh** [comment]
@mffiedler thanks!

**Comment by jboxman-rh** [comment]
@mdekan1 to what versions of OCP does this apply? Thanks!

**Comment by mdekan1** [comment]
@jboxman-rh all supported 4.x versions.

**Comment by jboxman-rh** [comment]
@xingxingxia thank you!

**Pull request merged**
