### PR TITLE
Bug 1522746: Fixed link to Migrating Embedded etcd to External etcd section

### PR DESCRIPTION
**Pull request by ghost**
@openshift/team-documentation Please peer review.

Link to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1522746

### CODE REVIEW

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM. Should the same changes be made in Master?

**Comment by vikram-redhat** [comment]
@mburke5678 - it is a merge request for master? Is that right?

**Comment by vikram-redhat** [comment]
@tmorriso-rh - is this for a BZ? Could you please put the BZ number in front of the PR Desc?

**Comment by tmorriso-rh** [comment]
No revision history needed.

**Pull request merged**
