### PR TITLE
Try docinfo

### PR DESCRIPTION
**Pull request by iranzo**
Waiting to check on the preview...

### CODE REVIEW

**Comment by iranzo** [comment]
@ahardin-rh how do I get the bot previewer to run on this? THX

**Comment by ahardin-rh** [comment]
@iranzo If you have asciibinder installed per https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc#install-asciibinder-and-dependencies, then you should be able to run `asciibinder build` to preview locally. 

If you plan to contribute to the doc set on a regular basis and would like the preview bot as a tool, please coordinate with @vikram-redhat Thank you! Please let me know if you have any other questions.

**Comment by iranzo** [comment]
Locally ir works but wanted to check netlify oneEl 21 dic. 2020 20:35, Ashley Hardin <notifications@github.com> escribió:
@iranzo If you have asciibinder installed per https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc#install-asciibinder-and-dependencies, then you should be able to run asciibinder build to preview locally.
If you plan to contribute to the doc set on a regular basis and would like the preview bot as a tool, please coordinate with @vikram-redhat Thank you! Please let me know if you have any other questions.

**Comment by vikram-redhat** [comment]
Hi @iranzo

I have added you to the preview bot. Not 100% sure if this will preview and pull in the docinfo, but it is worth a try. I have rebuilt the build so the preview should appear shortly.

**Comment by vikram-redhat** [comment]
The preview is available here: https://docinfo--ocpdocs.netlify.app/openshift-enterprise/latest/welcome/index.html

**Comment by iranzo** [comment]
Seems it doesn't work the way it's built here, closing PR

**Pull request closed without merging**
