### PR TITLE
In CNV-v2.0 we no longer need to recreate the route

### PR DESCRIPTION
**Pull request by aglitke**
CDI now creates the correct type of route (re-encrypt) automatically so we don't need to instruct the user to complete this workaround.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Comment by aglitke** [comment]
@ousleyp Can you take a look please?

**Comment by ousleyp** [comment]
Hey @aglitke! Thanks for submitting this PR. I appreciate the effort to pitch in and help docs. :) However, I need to discuss this with @vikram-redhat because I'm not sure what guidelines we have for devs/SMEs submitting PRs to the docs repo. I should be able to get back to you next week with further details.

There is one issue with this PR, though. You filed this PR against master, which is the branch for OCP 3.11/CNV 1.4 work that is currently published. CNV 2.0 work is actually going into upstream/enterprise-4.0 to align with the OCP 4.1 docs. However, there is currently no CNV doc work merged into that branch because we're starting from scratch and moving files over as we work on them. You would have to move the `cnv_upload_virtctl.adoc` file into the "modules" folder in the upstream/enterprise-4.0 branch in order for us to merge it into CNV 2.0 docs.

I'm not sure if you can just change the base branch or if you have to open a new PR, but let me know if you have any questions.

**Comment by aglitke** [comment]
Thanks. I'll create a new PR against the proper branch.

**Pull request closed without merging**
