### PR TITLE
Fix indentation per bug

### PR DESCRIPTION
**Pull request by sfortner-RH**
Fix indentation per [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1846643).

NO QE required.

CP to 4.4 and 4.5

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! There's an unrelated issue causing the build to fail. Once that's resolved, I'll get the PR merged and cherry picked.

**Comment by sfortner-RH** [comment]
Great, thanks!

**Comment by bmcelvee** [comment]
The build issue is fixed. Please rebase whenever you get a chance, then I'll go ahead with the merge. :)

**Comment by sfortner-RH** [comment]
@bmcelvee I have rebased :) Please merge.

**Pull request merged**
