### PR TITLE
OCPBUGS#8926: Update the recommended configurable storage technology table

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-8926

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/logging-nfs/scalability_and_performance/optimizing-storage.html#recommended-configurable-storage-technology_persistent-storage

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by IshwarKanse** [comment]
In the Loki column block storage should be configurable. LokiStack uses block storage for the components and object store to store the log data in chunks. cc @kabirbhartiRH

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Review by maxwelldb — APPROVED** [review]
Meets review guidelines AFAIK, but @xenolinux have you exhausted attempts to make the table fit in the preview? The live page does not have the awkward horizontal scrolling issue that this PR introduces:

https://docs.openshift.com/container-platform/4.12/scalability_and_performance/optimizing-storage.html#recommended-configurable-storage-technology_persistent-storage

Okay to merge if there's no alternative, but it's not ideal. :(

**Comment by xenolinux** [comment]
> Meets review guidelines AFAIK, but @xenolinux have you exhausted attempts to make the table fit in the preview? The live page does not have the awkward horizontal scrolling issue that this PR introduces:
> 
> https://docs.openshift.com/container-platform/4.12/scalability_and_performance/optimizing-storage.html#recommended-configurable-storage-technology_persistent-storage
> 
> Okay to merge if there's no alternative, but it's not ideal. :(

Hi, @maxwelldb I included two different columns to simplify [the ask](https://bugzilla.redhat.com/show_bug.cgi?id=1986055#c14). However, if there are other ideas to remove the horizontal scrolling issue, I would be happy to apply them.

**Comment by opayne1** [comment]
> However, if there are other ideas to remove the horizontal scrolling issue, I would be happy to apply them.

@xenolinux there is some guidance on setting table widths in the [Asciidoc guide](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#tables). I will take off merge review for now so you can look over those and see if it is a good solution for this PR.

**Comment by xenolinux** [comment]
> > However, if there are other ideas to remove the horizontal scrolling issue, I would be happy to apply them.
> 
> @xenolinux there is some guidance on setting table widths in the [Asciidoc guide](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#tables). I will take off merge review for now so you can look over those and see if it is a good solution for this PR.

As a workaround - I changed the structure of the table from "column to row" to "row to column". Now IMO the table looks neat and the horizontal scrolling line is gone! 
Adding the merge-review-needed label

**Comment by xenolinux** [comment]
checks are stuck --- reopening/closing PR

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by maxwelldb** [comment]
@xenolinux I wrote up some thoughts on table accessibility and how this table should probably have [two headers](https://www.w3.org/WAI/tutorials/tables/two-headers/), but I'm at a loss for how to do that in AsciiDoc. 

The table on prod has a similar issue, too, so it's not as if you're introducing an a11y regression. 

If you have time and want to see if there's a way to improve this, go for it! Nevertheless, merging. :)

**Pull request merged**
