### PR TITLE
make libc note availabe across all enterprise/dedicated/origin/etc.

### PR DESCRIPTION
**Pull request by gabemontero**
See https://github.com/openshift/openshift-docs/pull/9681#issuecomment-394402805

@kalexand-rh ptal

@juanvallejo fyi

### CODE REVIEW

**Comment by kalexand-rh** [comment]
I think that's fair. I'll merge it in. Thanks!

**Comment by gabemontero** [comment]
thanks @kalexand-rh !

**Comment by kalexand-rh** [comment]
Happy to help!

**Pull request merged**
