### PR TITLE
GH#30325 Update disk-container file path param for custom RHCOS AMI imports

### LINKED ISSUE #30325: [enterprise-4.7] Issue in file installing/installing_aws/installing-aws-government-region.adoc
### Which section(s) is the issue in?
Uploading a custom RHCOS AMI in AWS

### What needs fixing?
step 6. 
aws ec2 import-snapshot --region ${AWS_DEFAULT_REGION} \
     --description "<description>" \ 
     --disk-container <file_path>/containers.json 

should be 
aws ec2 import-snapshot --region ${AWS_DEFAULT_REGION} \
     --description "<description>" \ 
     --disk-container "file://<file_path>/containers.json "

### LINKED ISSUE #31504: [enterprise-4.7] Issue in file installing/installing_aws/installing-aws-government-region.adoc
### Which section(s) is the issue in?
Uploading a custom RHCOS AMI in AWS, step 6.

### What needs fixing?
It's unclear in the docs that --disk-container requires a URL, so file://<path/to>/containers.json is the correct argument.
```
[root@xxx user]# aws ec2 import-snapshot --region us-gov-xxx --description "rhcos-aws.x86_64-4.6.vmdk" --disk-container ./containers-aws-vmdk.json

Error parsing parameter '--disk-container': Expected: '=', received: 'EOF' for input:
./containers-aws-vmdk.json
                          ^

[root@03876210cbc5 user]# aws ec2 import-snapshot --region us-gov-west-1 --description "rhcos-aws.x86_64-4.6.vmdk" --disk-container file://containers-aws-vmdk.json
{
    "Description": "rhcos-aws.x86_64-4.6.vmdk",
...
```

Reference: https://github.com/aws/aws-cli/issues/3878#issuecomment-457079963

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #30325

Preview: https://deploy-preview-30339--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-government-region.html#installation-aws-upload-custom-rhcos-ami_installing-aws-government-region

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 PTAL

**Comment by codyhoag** [comment]
@yunjiang29 bump. Can you confirm this update? Thanks!

**Comment by codyhoag** [comment]
@yunjiang29 can you verify? Or suggest someone else that can review? Thanks!

**Comment by yunjiang29** [comment]
@codyhoag LGTM.

**Comment by mburke5678** [comment]
LGTM

**Pull request merged**
