### PR TITLE
GitHub Issue #29523: Removed -$VERSION from code for getting the oc binary.

### LINKED ISSUE #29523: URL for downloading OC client is incorrect
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#retrieving-the-openshift-installer_ipi-install-installation-workflow

### What needs fixing?

Sync with US module which has the right url:  https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html#retrieving-the-openshift-installer_ipi-install-installation-workflow

### PR DESCRIPTION
**Pull request by skrthomas**
Git Hub Issue burndown: Issue #29523 

For version 4.5+
Direct link to doc preview: https://deploy-preview-30956--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#extracting-the-openshift-installer_ipi-install-installation-workflow

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM!

**Comment by skrthomas** [comment]
QE ACK'd via Slack

**Comment by jboxman** [comment]
Refs https://github.com/openshift/openshift-docs/pull/28255.

**Pull request merged**
