### PR TITLE
BZ#1874098: image reg, cdn, and firewalls

### PR DESCRIPTION
**Pull request by mikemckiernan**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1874098

/hold

When ready, please add labels for nextrelease, [enterprise-4](https://issues.redhat.com/browse/enterprise-4).4, [enterprise-4](https://issues.redhat.com/browse/enterprise-4).5, [enterprise-4](https://issues.redhat.com/browse/enterprise-4).6, and [enterprise-4](https://issues.redhat.com/browse/enterprise-4).7.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
QE approved.
@openshift/team-documentation, please review.

/hold cancel

**Comment by bmcelvee** [comment]
LGTM

**Comment by bmcelvee** [comment]
@mikemckiernan a brief explanation for the merge conflicts for 4.4 and 4.5 is that the following table entry only exists in 4.6+:

|`registry.access.redhat.com`
|Required for `odo` CLI. 

I did a manual CP for 4.4 and 4.5 and made sure the entry was not added accidentally.

**Pull request merged**
