### PR TITLE
OSDOCS#7463: Adds notes for MS 4.12.29 release

### PR DESCRIPTION
**Pull request by opayne1**
OSDOCS#7463: Adds notes for MS 4.12.29 release

Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-7463

Link to docs preview:
https://63606--docspreview.netlify.app/microshift/latest/microshift_release_notes/microshift-4-12-release-notes#microshift-4-12-29-dp

QE review:
- [ ] QE has approved this change.

Additional information:
Fixes backticks based on peer review comment in #63274

### CODE REVIEW

**Comment by sabrinajess** [comment]
LGTM. Tagging @ousleyp to confirm review.

**Review by ousleyp — COMMENTED** [review]
LGTM!

**Pull request merged**
