### PR TITLE
Use patch instead of sed

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by adellape** [comment]
@liggitt In OSE 3.1.1.6, I have a readiness + liveness probe in the router dc but only a liveness in the registry dc (created new in 3.1.1):

http://pastebin.test.redhat.com/350234

But I see PRs/Issues in origin talking about readiness probes in the registry so I'm confused.

**Comment by liggitt** [comment]
readiness probe was added in https://github.com/openshift/origin/pull/6439, exists in 1.1.2+

**Comment by liggitt** [comment]
you could separate the command into two commands, one to patch liveness and one to patch readiness, so they could be run independently if they have an older registry config

**Comment by adellape** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/1727 for the liveness probe and https://github.com/openshift/openshift-docs/pull/1728 for adding an additional step for the readiness probe (separated so we can get it into OSE docs starting with 3.2).

**Pull request closed without merging**
