### PR TITLE
remove-openshift_logging_curator_run_timezone

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1677454

### CODE REVIEW

**Comment by mburke5678** [comment]
@josefkarasek Can you PTAL?

**Comment by jboxman** [comment]
Hi @mburke5678, this is somewhat related in that this bug[0] may be partially satisfied by the merging of this PR, after which I can cherry pick the callouts from the example into the 3.9 and 3.10 docs. Mostly a FYI.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1633337

**Comment by josefkarasek** [comment]
@mburke5678 how do we deal with deprecating config options? Should we mention changes between releases too?

**Comment by mburke5678** [comment]
@josefkarasek Yes, a list of deprecated config options would be great. We were talking the other day about how to best communicate 4.0 changes. Not sure we have a solution, but we should gather as much information as we can. 
Can you or someone generate a list of deprecated options?

**Comment by josefkarasek** [comment]
> @josefkarasek Yes, a list of deprecated config options would be great. We were talking the other day about how to best communicate 4.0 changes. Not sure we have a solution, but we should gather as much information as we can.
> Can you or someone generate a list of deprecated options?

Sorry, I don't have such list.

**Comment by jboxman** [comment]
@mburke5678, I want to borrow lines 1,640+ for 1633337[0]. Is this also destined for 3.11? If so I'll only partially apply to 3.9 and 3.10.

Thanks!

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1633337

**Pull request merged**
