### PR TITLE
IBM Cloud release note for OCP 4.10

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: https://deploy-preview-40404--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes.html#ocp-4-10-ibm-cloud-installation

### CODE REVIEW

**Comment by codyhoag** [comment]
@pamoedom can you verify this brief release note for IBM Cloud support in OCP 4.10?

**Comment by pamoedom** [comment]
Hi @codyhoag, LGTM with just one suggestion, could be possible to put some link in that section of the release notes that point to the ongoing `Deploying installer-provisioned clusters on IBM Cloud` documentation (https://github.com/openshift/openshift-docs/pull/39767)? I think it would be better on this way, right?

**Comment by codyhoag** [comment]
@pamoedom absolutely; I plan to add the link once the IBM Cloud docs are merged and ready to link to :+1:

**Comment by pamoedom** [comment]
ACK @codyhoag, thanks.
/lgtm

**Pull request merged**
