### PR TITLE
OSDOCS-5732: adds 4.11.36 to RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-5732](https://issues.redhat.com//browse/OSDOCS-5732): adds 4.11.36 to RNs

Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-5732

Link to docs preview:
https://58589--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-36

QE review:
- [ ] QE has approved this change.

Additional information:
This is a hot fix so stock text is not being followed.

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
