### PR TITLE
OSDOCS-4884: Add notes for the 4.8.57 release

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-4884](https://issues.redhat.com//browse/OSDOCS-4884) : Add notes for 4.8.57 release

Version(s):
4.8

Issue:
Jira [OSDOCS-4884](https://issues.redhat.com//browse/OSDOCS-4884)](https://issues.redhat.com/browse/OSDOCS-4884)

Links to docs preview: [Share drive](http://file.emea.redhat.com/dfitzmau/OSDOCS-4884/release_notes/)

QE review:
- [ ] QE has approved this change.

* QE not required for this change

### CODE REVIEW

**Comment by dfitzmau** [comment]
Message to reviewer: I do not have merge rights, so I cannot add a branch/enterprise-4.8 label. Please add this label if you have the rights to do so.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@dfitzmau Your link to "Updating a cluster using the CLI" does not work, but I expect that's merely an artifact of your preview method (share drive)?

**Comment by dfitzmau** [comment]
> @dfitzmau Your xref to "Updating a cluster using the CLI" does not work, but I expect that's merely an artifact of your preview method (share drive)? The other two links do work, but they are complete and refer to the production advisories. I looked at the section you refer to in the xref and your xref appears correct.

Elegant username @GroceryBoyJr :smile: . Thanks for the review. Yes, the link in the new section I created is a direct copy of the link supplied in merged section. :100: on the review!

**Comment by dfitzmau** [comment]
Message to merger I do not have merge rights, so I cannot add a `branch/enterprise-4.8` label. Please add this label if you have the rights to do so.

**Review by bergerhoffer — COMMENTED** [review]
LGTM, merging!

**Pull request merged**
