### PR TITLE
[OCPSTRAT-1516]: Add known issue for hosted clusters

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/OCPSTRAT-1516

Link to docs preview: https://78880--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-known-issues_release-notes

QE review:
- [x] QE has approved this change.

Additional information: Change management has been completed for this PR.

### CODE REVIEW

**Review by zanetworker — APPROVED** [review]

**Comment by bburt-rh** [comment]
Text lgtm.

I'm not sure about your PR, but according to the OpenShift Docs Manual, if a PR is "Adding or removing known or fixed issues in between releases (including z stream releases) to the release notes", it needs to undergo change management: https://docs.google.com/document/d/1fLMpK4bqthtFlCwA36yeo2cI-pExFpX76VMnSi_In6Q/edit#bookmark=id.khm4rxl210qm

**Comment by lahinson** [comment]
Good catch, @bburt-rh! I'll send this through change management.

**Comment by 8bitdad** [comment]
LGTM

**Comment by xltian** [comment]
LGTM

**Comment by sunayna15** [comment]
LGTM

**Pull request merged**
