### PR TITLE
SRVOCF-365: Document the -r <repository> option of the `kn func create` command

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+
Jira: https://issues.redhat.com/browse/SRVOCF-365
Docs preview: https://deploy-preview-37675--osdocs.netlify.app/openshift-enterprise/latest/serverless/cli_tools/kn-func-ref.html#serverless-create-func-kn_kn-func-ref

### CODE REVIEW

**Review by lance — APPROVED** [review]
/lgtm

**Review by jrangelramos — COMMENTED** [review]
Just one minor nit.

**Review by EricPonvelle — APPROVED** [review]
/lgtm

**Pull request merged**
