### PR TITLE
Add web console to upgrade topic

### PR DESCRIPTION
**Pull request by spadgett**
Follow-on to #8009 for 3.9

/assign @ahardin-rh 
@jwforres @sdodson FYI

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
looks great, thanks

**Comment by vikram-redhat** [comment]
@spadgett needs a rebase. 

@ahardin-rh PTAL after the rebase to make sure the conflicts are correctly resolved.

**Comment by spadgett** [comment]
It looks like the same topic for service catalog upgrade was removed in #8107. Do we still want the console topic? cc @adellape 

I want to call out somewhere that extensions have changed since there's a manual upgrade step to host them as URLs if you use them. I'm not sure the best place.

**Comment by adellape** [comment]
This was pulled into https://github.com/openshift/openshift-docs/pull/8074. Closing this PR in favor of that one.

**Pull request closed without merging**
