### PR TITLE
RHDEVDOCS-6080: Replace v1alpha1 in RolloutManager sections

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.10, GitOps 1.11, GitOps 1.12, GitOps 1.13

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6080

Link to docs preview:

Replaced apiVersion: argoproj.io/v1beta1 with apiVersion: argoproj.io/v1alpha1 in the following sections:

- [About RolloutManager custom resources and specification](https://77730--ocpdocs-pr.netlify.app/openshift-gitops/latest/argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.html#gitops-about-argo-rollout-manager-custom-resources-and-spec_using-argo-rollouts-for-progressive-deployment-delivery)
- [Creating a RolloutManager custom resource](https://77730--ocpdocs-pr.netlify.app/openshift-gitops/latest/argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.html#gitops-creating-rolloutmanager-custom-resource_using-argo-rollouts-for-progressive-deployment-delivery)

QE review:
- [ ] QE has approved this change.

SME review: @jgwest 
QE review: @varshab1210 
Internal peer review: @eromanova97 
Peer review:

Additional information:

### CODE REVIEW

**Comment by varshab1210** [comment]
LGTM, thanks

**Review by jgwest — APPROVED** [review]
LGTM too

**Comment by smunje1** [comment]
@Dhruv-Soni11 Peer review, LGTM!

**Comment by ShaunaDiaz** [comment]
@Dhruv-Soni11 This PR looks OK to merge, but it can't be until rebased against the `gitops-docs-main` branch.

**Comment by Dhruv-Soni11** [comment]
> @Dhruv-Soni11 This PR looks OK to merge, but it can't be until rebased against the `gitops-docs-main` branch.

Hello @ShaunaDiaz - I have fixed the rebase issue against the gitops-docs-main branch. PTAL. Thanks.

**Pull request merged**
