### PR TITLE
update refs in Telco related modules for 411 to 412 or product-version

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-890]: Update variables version 4.11 to 4.12 or {product-version} where appropriate for Telco docs

Version(s):
4.12 and main
Issue:
https://issues.redhat.com/browse/TELCODOCS-890
Link to docs preview:

An update of variable denoting versions relevant to Telco core docvs in OCP.

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Looks great! 
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
