### PR TITLE
[SRVCOM-2663] Verifying app deployment moved to Creating Serverless apps

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.32+

Issue:
https://issues.redhat.com/browse/SRVCOM-2663

Link to docs preview:
https://74391--ocpdocs-pr.netlify.app/openshift-serverless/latest/knative-serving/getting-started/serverless-applications

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
