### PR TITLE
bz1744543 amended etcd restoration steps

### PR DESCRIPTION
**Pull request by sheriff-rh**
Removed all etcd v2 references to avoid confusion. Clarified several steps per BZ below. 

Bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=1744543

Build preview: 
http://file.rdu.redhat.com/~antaylor/bz1744543/day_two_guide/host_level_tasks.html#day-two-guide-etcd-backup

### CODE REVIEW

**Comment by geliu2016** [comment]
LGTM, thanks

**Comment by sburke1967** [comment]
Hi Andrew,
Step 6 of Restoring etcd data should be removed as you do not repeat this process on all the etc nodes, this is only performed on the first one to re-create a single mode cluster: http://file.rdu.redhat.com/~antaylor/bz1744543/day_two_guide/host_level_tasks.html#restoring-etcd_deprecating-etcd

Step 10 - After the first instance is running, you can add the remaining peers back into the cluster.
This should be the process for re-adding the remaining nodes back into the cluster, not just stating that it can now be done, as per https://docs.openshift.com/container-platform/3.11/admin_guide/assembly_restore-etcd-quorum.html#adding-etcd-after-restoring_restore-etcd-quorum

Cheers

Sean

**Comment by sheriff-rh** [comment]
The build preview has been updated to reflect the latest changes. Thanks @sburke1967 !

**Pull request merged**
