### PR TITLE
changed link to gluster storage doc

### PR DESCRIPTION
**Pull request by vikram-redhat**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vikram-redhat This is a pretty old PR. Should it be closed?

**Comment by vikram-redhat** [comment]
@ahardin-rh - Hmm. I wonder why it didn't make it in to the release? I might need to check with the Storage DPM first.

**Comment by vikram-redhat** [comment]
@ahardin-rh - I had a look at this today. Do you know why it wouldn't have merged? I can't see any reason tbh. If there doesn't seem to be a reason, go ahead and merge it so it can make the next release.

**Comment by ahardin-rh** [comment]
@vikram-redhat Closing in favor of https://github.com/openshift/openshift-docs/pull/3400. 
I went to fetch your branch to give this a squash, but that branch could not be located (probably deleted since this work was submitted), so I opened PR#3400 to apply the change.

The Ifdef in MongoDB  was introduced in https://github.com/openshift/openshift-docs/pull/2780, so no need to apply that change now.

**Pull request closed without merging**
