### PR TITLE
RNs-TP-table:fixes a typo and error

### PR DESCRIPTION
**Pull request by JoeAldinger**
RNs-TP-Table: hot fix for a typo and an error in 4.12's RNs

Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4340

Link to docs preview:
https://54952--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-technology-preview

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by opayne1 — COMMENTED** [review]
I would wait for the feedback from Laura's contact to merge, but otherwise 
/lgtm

**Review by lahinson — APPROVED** [review]
/lgtm

**Review by opayne1 — APPROVED** [review]

**Pull request merged**
