### PR TITLE
Node Tuning Operator chapter review wrt k8s guidelines.

### PR DESCRIPTION
**Pull request by jmencak**
Review of the Node Tuning Operato based on k8s Documentation Style Guide.
https://kubernetes.io/docs/contribute/style/style-guide/

Also changing `s|tuned|Tuned|` where appropriate based on discussion with the BaseOS/tuned developers.

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jmencak Thanks for this! Right now, our style guidelines call for capitalizing Pod because it's an API object, but node is lowercase. This actually falls in line with the k8s Documentation Style Guide, though it always looks strange to me when Pod and node are discussed together in the docs.

**Comment by jmencak** [comment]
@ahardin-rh , the problem with [Nn]odes is that you're often talking *not* about the k8s objects (Nodes), *but* computers/machines that are part of the k8s cluster.  In my opinion, when talking about Pod/Node labels, it is correct to use capitals in both cases, because you're talking about k8s objects.  The computer/machine does not have k8s labels!  It is the k8s object that does.  However, searching through the OpenShift docs, I see only references to 'node label(s)' in lowercase.  This is probably OK, because there's a 1:1 mapping between the k8s Node (object) and the machine/computer/node.  Using the lowercase for the node labels then to be consistent with the rest of the OpenShift docs, but I believe it is perfectly valid to use the term "Node label" especially when used together when talking with other k8s objects such as Pods.  Unfortunately, now this really looks strange where we talk about node/Pod labels together in one sentence.

**Comment by ahardin-rh** [comment]
@jmencak Thanks! I am going to merge this to get the changes in, and then raise this style discussion in the next OpenShift docs meeting. Adding it to our team's agenda now.

**Pull request merged**
