### PR TITLE
GH#47482 - Removing master node language

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.10+
Issue: #47482

Description: Removing some instances of `master` in this document to use inclusive language 

Preview: 

- [Deploying installer-provisioned clusters on bare metal -> Prerequisites -> Reserving IP addresses for nodes with the DHCP](https://kelbrown20.github.io/bug-fix-previews/GH474882-fixing-master-wording/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#network-requirements-reserving-ip-addresses_ipi-install-prerequisites)
- [Deploying installer-provisioned clusters on bare metal -> Prerequisites -> Dynamic Host Configuration Protocol (DHCP) requirements](https://kelbrown20.github.io/bug-fix-previews/GH474882-fixing-master-wording/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#network-requirements-dhcp-reqs_ipi-install-prerequisites)
- [Deploying installer-provisioned clusters on bare metal -> Prerequisites -> Validation checklist for nodes](https://kelbrown20.github.io/bug-fix-previews/GH474882-fixing-master-wording/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#validation-checklist-for-nodes_ipi-install-prerequisites)

**Question for QE:** The text says that the host names can use any hosting naming convention the user prefers and looks to not be hard coded, which is why I changed the language in the table. Please let me know if that is not the case and the Usage/Host name has to use `master`. Thank you!

### CODE REVIEW

**Comment by zaneb** [comment]
/lgtm
I would try @jadhaj for QE

**Comment by kelbrown20** [comment]
Thank you!
/label peer-review-needed

**Comment by Amrita42** [comment]
@kelbrown20 I suspect its not hard coded and can be changed imo. Let's see what QE says.

**Comment by kelbrown20** [comment]
Thank you Amrita!
/label merge-review-needed

**Pull request merged**
