### PR TITLE
OSDOCS2295: Source file for BYOK feature

### PR DESCRIPTION
**Pull request by sayjadha**
This PR contains the source file for ARO feature - BYOK (https://issues.redhat.com/browse/OSDOCS-2295)

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
I tried my best without being familiar with Microsoft's guidelines, but added some questions and suggestions!

**Comment by sayjadha** [comment]
Incorporated peer feedback and uploaded the modified file (git squash).

**Comment by sayjadha** [comment]
The SME + QE acks have been done through a Google doc, and these files have already been published as is. Following are the links:
- JIRA issue: https://issues.redhat.com/browse/OSDOCS-2295
- Published document: https://docs.microsoft.com/en-us/azure/openshift/howto-byok

@bergerhoffer: Could you please help in merging the issue to the _openshift:aro-work_ repo? Thank you.

**Comment by bergerhoffer** [comment]
Merging! Note that it is expected that a build didn't run and that a preview is not generated, for PRs against the `aro-work` branch.

**Pull request merged**
