### PR TITLE
CNV-25540: Added headless mode to web console overview

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.13+

**Issue:**
https://issues.redhat.com/browse/CNV-25540

**Link to docs preview:**
https://58673--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-web-console-overview.html#ui-virtualmachine-details-details_virt-web-console-overview

**QE review:**
- [x] QE has approved this change.

**Additional information:**
NA

### CODE REVIEW

**Review by lkladnit — APPROVED** [review]

**Review by mjpytlak — COMMENTED** [review]
@danielclowers Peer review LGTM.

**Pull request merged**
