### PR TITLE
OSDOCS-3367: Removing support for custom scheduler

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3367

Link to docs preview:
* https://deploy-preview-44790--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-custom-scheduler

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@kasturinarra @ingvagabund this is the release note for removing the custom scheduler docs. PTAL when you get a chance. I wasn't positive on how to refer to the old method of adding a scheduler vs doing it through the SSO, so I called it doing it "manually". But let me know if you have a better way of wording.

Preview: https://deploy-preview-44790--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-custom-scheduler

**Comment by tmalove** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
Looks good!

**Comment by kasturinarra** [comment]
> @kasturinarra @ingvagabund this is the release note for removing the custom scheduler docs. PTAL when you get a chance. I wasn't positive on how to refer to the old method of adding a scheduler vs doing it through the SSO, so I called it doing it "manually". But let me know if you have a better way of wording.
> 
> Preview: https://deploy-preview-44790--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-custom-scheduler

@bergerhoffer manually looks okay to me.

**Comment by ingvagabund** [comment]
Removing the support is the most important piece of information. The wording is great!!! Thank You
LGTM

**Pull request merged**
