### PR TITLE
Troubleshooting: recommend diagnostics

### PR DESCRIPTION
**Pull request by sosiouxme**
Recommend diagnostics in the context of troubleshooting with a bit of actual description.

I looked for a better place to put this, but the troubleshooting section seemed best at the moment. It didn't seem to warrant a separate topic. But feel free to pull this out somewhere else if you think it best.

BTW, I think this troubleshooting doc has already moved well beyond just SDN troubleshooting and might be better named more generically as "Troubleshooting" or "Troubleshooting the cluster".

### CODE REVIEW

**Comment by adellape** [comment]
@sosiouxme I think there's enough here to warrant a stand-alone "Running Diagnostics" topic near the end of the Cluster Administration book. The "Running Diagnostics First" section in this "Troubleshooting OpenShift SDN" topic could then just be some brief explanation + a link to a "Running Diagnostics" topic.

And eventually when we have a separate Troubleshooting book, we could move both of these topics there.

WDYT?

**Comment by sosiouxme** [comment]
@adellape I guess this is long enough to justify its own page; just seemed like there were already an awful lot of admin topics, maybe it's time for another sublevel...

**Comment by adellape** [comment]
@sosiouxme Definitely; the Cluster Admin guide should be getting grouped into better subcategories in the coming weeks.

**Comment by ahardin-rh** [comment]
@sosiouxme @adellape Is this still relevant/correct? Raising this PR from the dead. :ghost:  Thanks.

**Comment by sosiouxme** [comment]
@ahardin-rh I think it's still relevant, but would need a little jiggering as "openshift ex diagnostics" became "oadm diagnostics" and then "oc adm diagnostics". Also @adellape 's suggestion for having it be a separate page would be good.

**Comment by ahardin-rh** [comment]
Closing this and continuing work in https://github.com/openshift/openshift-docs/pull/3302

**Pull request closed without merging**
