### PR TITLE
Updates for BZ1688784

### PR DESCRIPTION
**Pull request by lamek**
Clarified the specific resources that can be encrypted.

https://bugzilla.redhat.com/show_bug.cgi?id=1688784

### CODE REVIEW

**Comment by lamek** [comment]
@openshift/team-documentation ready for peer review.

**Comment by lamek** [comment]
@soltysh can you help confirm that only secrets and configmaps can be encrypted. Thanks.
@vikram-redhat how many versions back should I port this?

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by vikram-redhat** [comment]
@lamek - till 3.9.

**Comment by soltysh** [comment]
> @soltysh can you help confirm that only secrets and configmaps can be encrypted. Thanks.

@enj you'll know better, I guess.

**Comment by enj** [comment]
/hold

Any resource can be encrypted.

**Comment by lamek** [comment]
Thanks @enj. The attached bug says custom resources created from a CRD cannot be encrypted. (https://bugzilla.redhat.com/show_bug.cgi?id=1686452)
Would the following be a fair distinction:
> While the examples use the `secrets` resource, any built-in resources can be encrypted. Custom resources created from CRDs can not be encrypted.

**Comment by enj** [comment]
> Thanks @enj. The attached bug says custom resources created from a CRD cannot be encrypted. (https://bugzilla.redhat.com/show_bug.cgi?id=1686452)
> Would the following be a fair distinction:
> 
> > While the examples use the `secrets` resource, any built-in resources can be encrypted. Custom resources created from CRDs can not be encrypted.

Custom resources created from CRDs **can** be encrypted.  Reading through the code, I see no reason for CRDs to not support encryption.  @stts can confirm.

**Comment by sttts** [comment]
@enj CRDs use the same etcd storage layer as native resources. I see no reason why it should not work for CRDs.

**Comment by lamek** [comment]
@hexfusion can you PTAL? Per your comments in the related BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1686452) CustomResources created from CRDs **can not** be encrypted.

**Comment by hexfusion** [comment]
I was going by documentation, my bad for not digging further. defer to @sttts @enj.

**Comment by sttts** [comment]
I verified: it does not work with CRDs.

Reason: the encryption is not wired into the kube-apiserver storage factory, which is not used in the apiextensions-apiserver.

**Comment by enj** [comment]
> I verified: it does not work with CRDs.
> 
> Reason: the encryption is not wired into the kube-apiserver storage factory, which is not used in the apiextensions-apiserver.

Not sure exactly what you mean, but this sounds like a bug to me.

**Comment by sttts** [comment]
@enj One "not" too much. The encryption is ~~not~~ wired into the kube-apiserver storage factory. apiextensions-apiserver uses the "normal" RESTOptions getter without all the crazyness in the kube-apiserver one (for historic reasons).

Yes, we can call that a bug.

**Comment by enj** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1726347 to track.

**Pull request closed without merging**
