### PR TITLE
[enterprise-3.5] Logging and metrics version example uses v3.6 in 3.7 doc 

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1527274

### CODE REVIEW

**Comment by mburke5678** [comment]
Related to https://github.com/openshift/openshift-docs/pull/10196

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by nekop** [comment]
All changes are inside `ifdef::openshift-origin` so I don't think this is needed for enterprise branch.

FYI origin 1.5 uses v1.5.0, there is no version tags "v3.5" nor "v1.5" at this time.

**Comment by mburke5678** [comment]
@nekop Thank you for catching that. I merged this PR in error and reverted. There was one change in this PR that is needed for Enterprise 3.5, fix the definition for `openshift_metrics_image_prefix`. I made that change through https://github.com/openshift/openshift-docs/pull/10272/files.

**Pull request merged**
