### PR TITLE
OSDOCS-3675: CSI resize TP->GA

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.11+

Issue: [OSDOCS-3675](https://issues.redhat.com/browse/OSDOCS-3675)

Link to docs preview: http://file.rdu.redhat.com/lpettyjo/OSDOCS-3675/storage/expanding-persistent-volumes.html#expanding-csi-volumes_expanding-persistent-volumes

Additional information:

PTAL: @gnufied @chao007 @gcharot

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]

**Comment by chao007** [comment]
@gnufied `Recovering from failure when expanding volumes` is not GA now, do you think we need to add this part to doc now?

**Comment by gcharot** [comment]
LGTM, let's have it reviewed by @gnufied to confirm

**Comment by lpettyjo** [comment]
@chao007 

> @gnufied `Recovering from failure when expanding volumes` is not GA now, do you think we need to add this part to doc now?

This has been added.

**Comment by duanwei33** [comment]
LGTM from QE side.

**Pull request merged**
