### PR TITLE
OBSDOCS#644: Add attributes for Cluster Observability Operator

### PR DESCRIPTION
**Pull request by bburt-rh**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OBSDOCS-644

Link to docs previews:
- https://69521--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/cluster_observability_operator/cluster-observability-operator-release-notes
- https://69521--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/cluster_observability_operator/cluster-observability-operator-overview
- https://69521--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/cluster_observability_operator/installing-the-cluster-observability-operator
- https://69521--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/cluster_observability_operator/configuring-the-cluster-observability-operator-to-monitor-a-service

QE review:
- [x] No QE review required. This PR only adds attributes, and no technical content has changed.

Additional information: This PR adds attributes for the Cluster Observability Operator content.

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Comment by bburt-rh** [comment]
This also needs to be CP'ed to enterprise-4.11, enterprise-4.12, and enterprise-4.13 branches. I added the necessary labels.

**Pull request merged**
