### PR TITLE
Clarify resource limits in Dev Preview FAQ

### PR DESCRIPTION
**Pull request by ahardin-rh**
Edits per a customer case discussed via email with @abhgupta and @sferich888

### CODE REVIEW

**Comment by abhgupta** [comment]
lgtm

**Comment by sferich888** [comment]
Lgtm

**Review by adellape — APPROVED** [review]
:+1:

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../getting_started/devpreview_faq.adoc#getting-started-devpreview-faq[Developer Preview FAQ]
|Added clarifying details about resource limits.
%

**Pull request merged**
