### PR TITLE
RHDEVDOCS-5615: Updating the installing build strategies section

### PR DESCRIPTION
**Pull request by shipsing**
Manual CP from #64609 to build-docs-1.0

### CODE REVIEW

**Comment by shipsing** [comment]
@jeana-redhat, I have manually cherry-picked the content from https://github.com/openshift/openshift-docs/pull/64609 to this PR. Please help with merge.

**Comment by jeana-redhat** [comment]
> @gabriel-rh @aireilly, will you please confirm the change to the Travis builds?

Thanks Kathryn! 

Adding one that the only other difference I see here vs the original PR is changes to [requirements.txt](https://github.com/openshift/openshift-docs/pull/65855/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552), which I also don't know anything about and am wary of :bow:

**Comment by gabriel-rh** [comment]
I think it would be better to split out the travis.yml change into its own PR - this makes it a lot easier to figure out what is going on, and allows us to revert that specific change, if something goes wrong

@shipsing @kalexand-rh

**Comment by gabriel-rh** [comment]
and I am also unsure about the requirements.txt change - again, it is better to keep infra changes separate from content changes

**Comment by shipsing** [comment]
@jeana-redhat @gabriel-rh, If you look at the travis.yaml and requirement.txt files in the build-docs branch: https://github.com/openshift/openshift-docs/tree/build-docs, the content varies from what is available in the build-docs-1.0 branch. I tried to copy the same content into the build-docs-1.0 branch. 
I agree with Gabriel that we can tackle infra changes in a separate PR. I have only changed the name of the product in the travis file in my original PR. The same change you can see in this PR. Since build-docs has a separate branch, we do not need the openshift-enterprise, rosa, microshift, and openshift-dedicated distros. I accepted the incoming change while resolving conflicts. I think the updated travis.yaml file was not cherrypicked to this build-docs-1.0 branch earlier because of which we saw conflicts. 
I can move the changes made to travis.yaml and requirement.txt files in a separate PR.

**Comment by jeana-redhat** [comment]
> @jeana-redhat @gabriel-rh, If you look at the travis.yaml and requirement.txt files in the build-docs branch: https://github.com/openshift/openshift-docs/tree/build-docs, the content varies from what is available in the build-docs-1.0 branch. I tried to copy the same content into the build-docs-1.0 branch. I agree with Gabriel that we can tackle infra changes in a separate PR. I have only changed the name of the product in the travis file in my original PR. The same change you can see in this PR. Since build-docs has a separate branch, we do not need the openshift-enterprise, rosa, microshift, and openshift-dedicated distros. I accepted the incoming change while resolving conflicts. I think the updated travis.yaml file was not cherrypicked to this build-docs-1.0 branch earlier because of which we saw conflicts. I can move the changes made to travis.yaml and requirement.txt files in a separate PR.

Thanks for writing that out! This explanation makes sense to me, but it is enough out of my understanding that I would like to get an ack from @gabriel-rh or @aireilly on the PR in its current state before merging :slightly_smiling_face:

**Review by gabriel-rh — APPROVED** [review]
/LGTM

**Pull request merged**
