### PR TITLE
Swaps google identity provider example from github to google.

### PR DESCRIPTION
**Pull request by mikesmith0414**
Swaps google identity provider example from github to google.

Versions: ROSA. 4.11+

Issue: https://github.com/openshift/openshift-docs/issues/48138

https://50532--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-config-identity-providers.html#config-google-idp_rosa-sts-config-identity-providers

QE needed

### CODE REVIEW

**Comment by stevsmit** [comment]
@xueli181114 PTAL. Thanks!

**Comment by xueli181114** [comment]
LGTM

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Pull request merged**
