### PR TITLE
ocpdocs9673: unhiding sigstore pages

### PR DESCRIPTION
**Pull request by DCChadwick**
Version(s): 4.17+

Issue: [OSDOCS-9673](https://issues.redhat.com//browse/OSDOCS-9673)

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by DCChadwick** [comment]
/label peer-review-needed

This PR is simply intended to unhide documentation that has already been through the review process.

**Review by skopacz1 — APPROVED** [review]
Peer review LGTM since you say that all the content being added to the docs has already been reviewed

**Review by jeana-redhat — APPROVED** [review]
FYI it's still helpful to include a preview in this case (to make sure the TOC rendered as it ought to :slightly_smiling_face:). I found it and it LGTM :rocket: 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
