### PR TITLE
OCPBUGS-11651 fixing content for IBM-Z and IBM power

### PR DESCRIPTION
**Pull request by kquinn1204**
[OCPBUGS-11651]: SR-IOV section included in IBM zSystems install docs in error

Version(s): 4.13 and main

Issue:
https://issues.redhat.com/browse/OCPBUGS-11651

Link to docs preview:
https://58568--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/preparing-to-install-on-bare-metal.html#nw-sriov-dual-nic-con_preparing-to-install-on-bare-metal

https://58568--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#bonding-multiple-sriov-network-interfaces-to-dual-port_installing-bare-metal

for Z:
https://58568--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z.html#installation-user-infra-machines-routing-bonding_installing-ibm-z

KVM-Link https://58568--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_z/installing-ibm-z-kvm.html

for Power:

https://58568--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_power/installing-ibm-power.html#installation-user-infra-machines-routing-bonding_installing-ibm-power

QE review:
- [x] QE has approved this change.

Additional information:
Updating documentation where a section accidentally leaked into Z docs due to my misunderstanding.

### CODE REVIEW

**Comment by SNiemann15** [comment]
@holgwolf @manojnkumar Can you please QE review the IBM Z and Power sections and sign-off. Thanks!

**Comment by holgwolf** [comment]
lgtm

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Pull request merged**
