### PR TITLE
OCPBUGS#9916: Fix the typo

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-9916

Link to docs preview: https://deploy-preview-57090--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by aireilly — COMMENTED** [review]
LGTM

**Review by opayne1 — COMMENTED** [review]
For some reason the preview linked in comment 0 didn't work for me so I checked https://57090--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks.html#dr-scenario-2-restoring-cluster-state_post-install-cluster-tasks (step 18) 
/lgtm

**Pull request merged**
