### PR TITLE
OSDOCS-1810: Add release note for cluster network MTU migration

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-1810

This adds a release note entry for cluster network MTU migration.

- Preview: [Change cluster network MTU after cluster installation](https://deploy-preview-39485--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes.html#ocp-4-10-change-cluster-network-mtu-after-cluster-installation)

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@jcaamano, can you review this release note entry? What other information might I include? Is this considered a _migration_ or a do we have a different way to describe this process?

Thanks!

**Comment by jcaamano** [comment]
@jboxman-rh The process is a bit more involved. It requires to reboot each node at least twice and it's between those two reboots when the user can change the underlying physical network MTU (including, but not exclusively, the physical host interface MTU). Reach out if you need more information for this release note.

**Comment by jboxman-rh** [comment]
@jcaamano, I see the merged enhancement discusses the procedure in depth. I'll review that further and surface any questions that arise. Thank you!

**Comment by jboxman-rh** [comment]
@jcaamano, I simplified as most of the information is in the product documentation. Can you confirm? Thanks!

The link will be fixed once the other PR is merged.

**Review by bergerhoffer — COMMENTED** [review]
Content looks good to me, but the xref fails (might be expected), and there is a conflict in the PR that needs to be resolved

**Pull request merged**
