### PR TITLE
Noted the consequences of violating the Online Starter Terms of Service

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/SjG9CzQG/978-8-ban-block-abusive-users-from-the-starter-tier

@abhgupta @damemi PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@abhgupta @damemi PTAL

**Comment by damemi** [comment]
Might want to be more clear that their account (and eventually, any non-starter subscriptions) will be terminated and banned from creating any more subscriptions. To me "disruption" doesn't sound as serious

**Comment by ahardin-rh** [comment]
@damemi Thanks! Updated! 
@abhgupta Any thoughts?

**Comment by ahardin-rh** [comment]
@damemi @abhgupta bump

**Review by damemi — APPROVED** [review]
lgtm

**Comment by yasun1** [comment]
lgtm

**Comment by adellape** [comment]
@ahardin-rh FYI, this came up while trying to robo-pick https://github.com/openshift/openshift-docs/pull/7606 for 3.9 and 3.10. Looks like 7604 was picked to 3.7 only so far, so I've picked it along with 7606 in my 3.9 and 3.10 PRs.

**Comment by ahardin-rh** [comment]
@adellape Thanks for addressing that. Those branches were not on my radar when the content was created. I appreciate your help while I was out!

**Pull request merged**
