### PR TITLE
Code highlighting in image-tag section fixed

### LINKED ISSUE #50309: [enterprise-4.11] Issue in file openshift_images/index.adoc (GOOD FIRST ISSUE)
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/openshift_images/index.html#images-tag_overview-of-images

### What needs fixing?

The code highlighting is different in the _Image tags_ section. Text there is blue. I'd say the code block is missing a source declaration like in other sections.

### PR DESCRIPTION
**Pull request by aswin2108**
# Code highlighting in image tag section has been fixed
Fixes #50309 
Link to docs preview:
https://51104--docspreview.netlify.app/openshift-enterprise/latest/openshift_images/index.html

### CODE REVIEW

**Comment by aireilly** [comment]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Pull request merged**
