### PR TITLE
[OCPBUGS-22184] Add single stack restriction for IBM Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.14 + (will backport to 4.12, 4.13 in separate PRs) 

Issue: https://issues.redhat.com/browse/OCPBUGS-22184

Link to docs preview: https://66587--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes#nw-ovn-kubernetes-matrix_about-ovn-kubernetes

QE review: @holgwolf @manojnkumar 
- [x] QE has approved this change.

Additional information:
PR for the backport to 4.13, 4.12 https://github.com/openshift/openshift-docs/pull/66700

### CODE REVIEW

**Comment by SNiemann15** [comment]
@manojnkumar Does this also apply to Power? If yes I can pick that up in this PR.

**Comment by manojnkumar** [comment]
> @manojnkumar Does this also apply to Power? If yes I can pick that up in this PR.

Yes, it applies to Power also.

**Comment by manojnkumar** [comment]
LGTM

**Comment by kcarmichael08** [comment]
Is there a separate PR for 4.12? I did see the separate PR for 4.13. This one lgtm.

**Pull request merged**
