### PR TITLE
Add genevePort for OVN-Kubernetes

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-944

### CODE REVIEW

**Comment by jboxman** [comment]
@pecameron, does this look correct? Which versions of OCP is it applicable to?

Thanks!

**Review by pecameron — COMMENTED** [review]
/lgtm

**Comment by jboxman** [comment]
@zhaozhanqi, can you confirm that this works?

Thanks!

**Comment by zhaozhanqi** [comment]
/lgtm
@huiran0826 please also have a check

**Comment by jboxman** [comment]
@zhaozhanqi @huiran0826 

Thank you!

**Comment by ahardin-rh** [comment]
Looks good!

**Comment by jboxman** [comment]
@ahardin-rh, thanks!

**Pull request merged**
