### PR TITLE
BZ-1921831: Excluding etcd quorum guard pods from output

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1921831

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@retroflexer @geliu2016 I updated all `oc get pods` commands that grepped `etcd` to exclude quorum guard pods. Let me know if this looks okay.

Preview: https://deploy-preview-28946--osdocs.netlify.app/openshift-enterprise/latest/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

FYI @yprokule

**Review by jeana-redhat — APPROVED** [review]
lgtm

**Comment by geliu2016** [comment]
LGTM, thanks

**Pull request merged**
