### PR TITLE
Pull Request for Bug 1755222 - VMware capitalization changes

### PR DESCRIPTION
**Pull request by lmandavi**
This pull request is for Bug 1755222. Two .adoc files were updated by correcting "VMWare" to "VMware". The changes were reviewed and approved by Vikram.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lmandavi, which versions does this change apply to? 4.1 and 4.2, or just 4.2?

**Comment by lmandavi** [comment]
The changes were made to the 4.2 content, to my best recollection and
understanding, this applies to 4.2.
Thanks! - Lavanya


Lavanya Mandavilli

Senior Technical Writer, Cloud Platform

Red Hat <https://www.redhat.com/>
<https://www.redhat.com/>

**Comment by kalexand-rh** [comment]
I checked, and it's showing up in 4.1 as well: https://docs.openshift.com/container-platform/4.1/storage/understanding-persistent-storage.html#types-of-persistent-volumes_understanding-persistent-storage

**Comment by lmandavi** [comment]
Thanks for cherry picking the PR to 4.2, Kathryn.

**Pull request merged**
