### PR TITLE
[OSDOCS-3951]: adding relnote for sr-iov operator on hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
[OSDOCS-3951]: Adding release note about deploying the SR-IOV Operator on hosted control planes

Version(s): 4.12

Issue: https://issues.redhat.com/browse/OSDOCS-3951

Link to docs preview: https://54261--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-hcp-sr-iov-operator

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by lahinson** [comment]
Hi @bn222 and @zhaozhanqi - PTAL at this release note entry about deploying the SR-IOV Operator on a hosted cluster. I need SME and QE approval before I can move this forward to peer review. Thank you!

**Comment by lahinson** [comment]
Hi @zhaozhanqi - When you can, PTAL at this release note text. I need your approval before I can move this along in the publishing process for OCP 4.12. Thanks!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
