### PR TITLE
s\4.1\{product-version}

### PR DESCRIPTION
**Pull request by neal-timpe**
Refactoring this pull request https://github.com/openshift/openshift-docs/pull/17501. @vikram-redhat Can you confirm this is correct?

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@neal-timpe LGTM.

**Comment by neal-timpe** [comment]
@openshift/team-documentation Can you review and merge this to 4.1, 4.2, and 4.3?

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Pull request merged**
