### PR TITLE
BZ1557935: Updating apb tool commands

### PR DESCRIPTION
**Pull request by kcarmichael08**
- [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1557935)
- [Doc Preview](https://deploy-preview-42595--osdocs.netlify.app/openshift-enterprise/latest/apb_devel/cli_tooling.html)

### CODE REVIEW

**Comment by djzager** [comment]
I don't see any mention of installing `ansible` or `ansible-galaxy`.

I remember beginning to support APBs that were created, and published to, Ansible galaxy but I don't recall it being this seamless. Is the bug reporter able to verify this behavior?

**Comment by kcarmichael08** [comment]
I did verify that the commands have been deprecated and the CLI gives those commands as the ones to use instead - but I don't know enough about the product to understand how ansible is replacing apb. I was hoping to get some Eng help to better understand, but should I go back to the submitter? Here is the output from my commands showing the new commands:

```
[quicklab@master-0 ~]$ apb help
WARN Didn't find config file /home/quicklab/.apb/registries.json, creating.
WARN Didn't find config file /home/quicklab/.apb/defaults.json, creating.
Tool for working with Ansible Playbook Bundles

Usage:
  apb [command]

Available Commands:
  binding     Manage bindings
  broker      Interact with Automation Broker
  bundle      Interact with APBs
  catalog     Interact with OpenShift Service Catalog
  completion  Generates shell completion scripts
  config      Set tool defaults
  help        Help about any command
  registry    Configure registry adapters
  version     Get version

Flags:
      --config string       configuration directory (default is $HOME/.apb)
  -h, --help                help for apb
  -k, --kubeconfig string   Path to kubeconfig to use (default is $HOME/.kube/config)
  -v, --verbose             verbose output

Use "apb [command] --help" for more information about a command.


[quicklab@master-0 ~]$ apb init my-new-apb
Command "init" is deprecated, use 'ansible-galaxy init --type=apb <bundle-name>'
[quicklab@master-0 ~]$


[quicklab@master-0 ~]$ apb build
Command "build" is deprecated, the OpenShift build system can be used instead.

Create buildconfig: 'oc new-build --binary=true --name <bundle-name>'
Start build:        'oc start-build --follow --from-dir . <bundle-name>'


[quicklab@master-0 ~]$ apb push
Command "push" is deprecated, the OpenShift build system can be used instead.

Create buildconfig: 'oc new-build --binary=true --name <bundle-name>'
Start build:        'oc start-build --follow --from-dir . <bundle-name>'

[quicklab@master-0 ~]$ apb list
Command "list" is deprecated, running 'apb bundle list'. To list APBs known to a broker, run 'apb broker catalog'
 APB     IMAGE     REGISTRY
 --- -+- ----- -+- --------
[quicklab@master-0 ~]$

```

**Comment by djzager** [comment]
Based on what you are showing @kcarmichael08 , I would think that the `apb` command itself has been decorated and we should be pointing people to the ansible documentation for creating APBs?

https://galaxy.ansible.com/docs/contributing/creating_apb.html

**Comment by djzager** [comment]
My understanding was the service catalog and ansible service broker are also deprecated. That would make the remaining commands `binding` `broker` and `bundle` less meaningful.

I'm not attached enough to what is going on to be able to answer you definitively. If you had asked me directly, I would have pointed at @jmrodri :grin: 

I personally doubt the usefulness of the APB Development guide.

**Comment by kcarmichael08** [comment]
Added a link to the APB documentation but left in the commands that are showing as still available in the software.

**Pull request closed without merging**
