### PR TITLE
OSDOCS-6331: Add ROSA Interactive Walkthrough link to documentation

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4.13+

Issue:
[OSDOCS-6331](https://issues.redhat.com/browse/OSDOCS-6331)

Link to docs preview:
[About ROSA](https://61004--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-understanding.html#rosa-understanding-about_rosa-understanding)
[ROSA quickstart guide](https://61004--docspreview.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-quickstart-guide-ui.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
Looks good to me! The interactive walkthrough is seriously cool.

I am still new to peer review, so please wait until @adellape approves of my review before proceeding to merge review. Thanks!

**Review by adellape — COMMENTED** [review]
@skopacz1 @eohartman Peer review looks good to me 👍

**Pull request merged**
