### PR TITLE
OSDOCS-8491: Specialized hardware and driver enablement

### PR DESCRIPTION
**Pull request by GroceryBoyJr**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OSDOCS-8491

Link to docs preview: https://file.rdu.redhat.com/jbrigman/415-releasenote/release_notes/ocp-4-15-release-notes.html

QE review:
- [ ] QE has approved this change.

Additional information:
image

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
@bthurber PTAL

**Comment by GroceryBoyJr** [comment]
@cdvultur @bthurber PTAL, seeking your review

**Comment by bthurber** [comment]
> @bthurber PTAL

@GroceryBoyJr Do we need a call out for "Specialized hardware and driver enablement Technology Preview features" when we don't have anything to mention there?  Hub and spoke and DTK have been GA for several releases now.

**Review by bthurber — COMMENTED** [review]
See previous comment.

**Comment by GroceryBoyJr** [comment]
> > @bthurber PTAL
> 
> @GroceryBoyJr Do we need a call out for "Specialized hardware and driver enablement Technology Preview features" when we don't have anything to mention there? Hub and spoke and DTK have been GA for several releases now.

@bthurber Good question! There is one feature that went GA from TP after 4.12 and I needed to indicate that. It's useful, particularly for support, to call out the GA status of the features across the three releases and to indicate nothing has been deprecated/removed. (I did indeed delete the blank "deprecated and removed" section.)

**Comment by bthurber** [comment]
> > > @bthurber PTAL
> > 
> > 
> > @GroceryBoyJr Do we need a call out for "Specialized hardware and driver enablement Technology Preview features" when we don't have anything to mention there? Hub and spoke and DTK have been GA for several releases now.
> 
> @bthurber Good question! Hub and spoke cluster support went GA from TP after 4.12 and I needed to indicate that. It's useful, particularly for support, to call out the GA status of the features across the three releases and to indicate nothing has been deprecated/removed. (I did, however, delete the blank "deprecated and removed" section.)

Ack.  Good with the proposed changes.  :)

/lgtm

**Pull request merged**
