### PR TITLE
[SRVKE-1467] Add the KafkaSource deletion note

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
Serverless 1.29

Issue:
https://issues.redhat.com/browse/SRVKE-1467

Link to docs preview:

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by mgencur** [comment]
LGTM from QE

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
