### PR TITLE
Update OpenShift instances across Creating Images Book

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @bfallonf @tnguyen-rh @tpoitras PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**Comment by tpoitras** [comment]
@ahardin-rh LGTM, too! :ice_cream: :palm_tree:

**Comment by ahardin-rh** [comment]
@bfallonf @tpoitras Thanks!  :dizzy:

**Comment by ahardin-rh** [comment]
No rev history needed

**Pull request merged**
