### PR TITLE
OSDOCS-7963: Update egress URLS

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.16+ 

Issue:
https://issues.redhat.com/browse/OSDOCS-7963

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.18` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.17. And any PR going into `main` must also target the latest version branch (enterprise-4.18).

If the update in your PR does NOT apply to version 4.18 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by bmcelvee** [comment]
@abyrne55 and @aaraj7 would you mind giving this PR a review, please?

**Review by abyrne55 — APPROVED** [review]
Created an OSD staging cluster in us-east-1 with servicequotas.us-east-1.amazonaws.com blocked and confirmed that cluster comes up healthily. I'll open a PR to remove this URL from the network verifier's egress list. Thanks @bmcelvee!

/lgtm

**Comment by aaraj7** [comment]
LGTM

**Comment by michaelryanpeter** [comment]
lgtm
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress

**Comment by bmcelvee** [comment]
Thank you! Squashed commits and will merge when the tests clear.

**Pull request merged**
