### PR TITLE
OSDOCS-4303: adds zstream update

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-4303](https://issues.redhat.com//browse/OSDOCS-4303): adds zstream update

Version(s):
4.10

Issue:
[Jira](https://issues.redhat.com/browse/OSDOCS-4303)

Link to docs preview:
[Preview](https://joealdinger.github.io/openshift-docs/OSDOCS-4303/release_notes/ocp-4-10-release-notes.html#ocp-4-10-36)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by nalhadef — COMMENTED** [review]
Hi, @JoeAldinger. Just one comment.

**Comment by JoeAldinger** [comment]
/label merge-review 
4.10.36 `Shipped_Live`

**Pull request merged**
