### PR TITLE
Bug#1489497 Persistent Storage Using Fibre Channel Documentation should elaborate on the specification of the targetWWNs

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1489497

Also includes fixes for 
- https://bugzilla.redhat.com/show_bug.cgi?id=1474839
- https://bugzilla.redhat.com/show_bug.cgi?id=1489483

- Added information about fibre channel path
- fixed a broken link
- Removed incorrect example text

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@TheDiemer Can you please check?

**Comment by gaurav-nelson** [comment]
@TheDiemer bump

**Comment by liangxia** [comment]
LG from QE's perspective.

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM

**Comment by gaurav-nelson** [comment]
minor bug fixes no revision history needed

**Pull request merged**
