### PR TITLE
OSDOCS-3713 adding ultra SSD capability to Azure install doc

### PR DESCRIPTION
**Pull request by bscott-rh**
https://issues.redhat.com/browse/OSDOCS-3713

Applies to 4.11

[Doc preview](https://bscott-rh.github.io/openshift-docs/OSDOCS-3713/installing/installing_azure/installing-azure-network-customizations.html#installation-configuration-parameters_installing-azure-network-customizations)

### CODE REVIEW

**Comment by mgahagan73** [comment]
This looks good, the only thing I think is missing is some clarification about what the ultraSSD option does. What the option actually does is allow one to add an UltraSSD as a data disk post-install, It doesn't actually install the nodes with UltraSSD as Azure supports them for data disks only (they are not usable for the os disk) I feel like this may cause some customer confusion.

**Comment by bscott-rh** [comment]
> This looks good, the only thing I think is missing is some clarification about what the ultraSSD option does. What the option actually does is allow one to add an UltraSSD as a data disk post-install, It doesn't actually install the nodes with UltraSSD as Azure supports them for data disks only (they are not usable for the os disk) I feel like this may cause some customer confusion.

Thanks for the information Mike. Is the process of adding a data disk an Azure procedure or an OpenShift procedure? IE do we need to include/link to OpenShift documentation about that process? or is it sufficient to state that this allows for the disk to be added as a data disk post-install.

**Comment by mgahagan73** [comment]
I think we could just reference the 4.11 version of this doc:

https://docs.openshift.com/container-platform/4.10/storage/persistent_storage/persistent-storage-azure.html

**Comment by bscott-rh** [comment]
> > This looks good, the only thing I think is missing is some clarification about what the ultraSSD option does. What the option actually does is allow one to add an UltraSSD as a data disk post-install, It doesn't actually install the nodes with UltraSSD as Azure supports them for data disks only (they are not usable for the os disk) I feel like this may cause some customer confusion.
> 
> Thanks for the information Mike. Is the process of adding a data disk an Azure procedure or an OpenShift procedure? IE do we need to include/link to OpenShift documentation about that process? or is it sufficient to state that this allows for the disk to be added as a data disk post-install.

I've updated the configuration parameters table to read:

"Enables the use of Azure ultra disks **for persistent storage** on control plane and compute machines."

Does this add enough clarity?

**Comment by Amoghrd** [comment]
For the sample install-config file `modules/installation-azure-config-yaml.adoc` `ultraSSDCapability: Enabled` has to be present for platform;azure in controlPlane and compute part too

**Comment by bscott-rh** [comment]
> For the sample install-config file `modules/installation-azure-config-yaml.adoc` `ultraSSDCapability: Enabled` has to be present for platform;azure in controlPlane and compute part too

I have added this variable to the compute and controlplane sections of the sample yaml file. Thank you

**Comment by Amoghrd** [comment]
Looks good!

**Comment by mgahagan73** [comment]
looks good to me

**Pull request merged**
