### PR TITLE
[enterprise-4.15] OSDOCS-9689: update from dep to rem

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OSDOCS-9689

Link to docs preview: https://73712--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-deprecated-removed-features scroll to 'Installation deprecated and removed features' table

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by gwynnemonahan** [comment]
Hey @jldohmann ,

LGTM.

**Comment by jldohmann** [comment]
@melvinjoseph86 could you PTAL at this docs PR for QE ack? This PR amends the deprecated and removed features table in the OCP 4.15 release notes to reflect the removal of CoreDNS supporting wildcard queries. thank you!

**Pull request merged**
