### PR TITLE
Removing References to 'Click Here'

### PR DESCRIPTION
**Pull request by bmcelvee**

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
@bmcelvee, can this one be rebased and merged/cherrypicked?

**Comment by vikram-redhat** [comment]
@bmcelvee this should be an easy fix once you rebase it. Are you able to do this sometime this week?

**Comment by bmcelvee** [comment]
Closing. Replaced by https://github.com/openshift/openshift-docs/pull/10909.

**Pull request closed without merging**
