### PR TITLE
TELCODOCS-1567 - RN - Check ZTP procedure links to the correct version of ACM

### PR DESCRIPTION
**Pull request by slovern**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/TELCODOCS-1567

Link to docs preview: https://71990--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Comment by slovern** [comment]
Thanks or the review @skopacz1

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by slovern** [comment]
thanks for the merge @jldohmann

**Pull request merged**
