### PR TITLE
[enterprise-4.13] OCPBUGS#27951: Updated a req to install LVM Storage

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.13

Issue:
[OCPBUGS-27951](https://issues.redhat.com/browse/OCPBUGS-27951)

Link to docs preview:
[Preview
](https://74105--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms#lvms-deployment-requirements-for-sno-ran_logical-volume-manager-storage)

QE review:
- [x] QE has approved this change.

xref: https://github.com/openshift/openshift-docs/pull/73358

Additional information:

### CODE REVIEW

**Comment by sr1kar99** [comment]
@jakobmoellerdev 
Can you please review this PR?
Thanks.

**Comment by sr1kar99** [comment]
@radeore 
Can you please review this PR?
Thanks.

**Review by jakobmoellerdev — COMMENTED** [review]
lgtm

**Pull request merged**
