### PR TITLE
OSDOCS-9206-RN Encryption azure storage accounts release notes

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.15

Issue:
https://issues.redhat.com/browse/OSDOCS-9206

Link to docs preview:
https://71409--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-azure-storage-account-encryption

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jinyunma PTAL at this RN for azure encryption docs. Thank you

**Comment by jinyunma** [comment]
LGTM

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
