### PR TITLE
OSDOCS-4461 - Removing ControllerAvailable

### PR DESCRIPTION
**Pull request by eohartman**
Version(s):
4.12+

Issue:
[OSDOCS-4461](https://issues.redhat.com/browse/OSDOCS-4461)

Link to docs preview:

[OCP: Installing the AWS EFS CSI Driver](https://58954--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-aws-efs.html#persistent-storage-csi-efs-driver-install_persistent-storage-csi-aws-efs)
[ROSA: Installing the AWS EFS CSI Driver](https://58954--docspreview.netlify.app/openshift-rosa/latest/storage/container_storage_interface/osd-persistent-storage-aws-efs-csi.html#persistent-storage-csi-efs-driver-install_osd-persistent-storage-aws-efs-csi)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! Question: does this also apply to 4.12?

**Comment by eohartman** [comment]
@bmcelvee  Yes! Good point. I'll edit the original comment.

**Pull request merged**
