### PR TITLE
bug 1782039 adding vCenter to noProxy

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1782039

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by gpei** [comment]
@kalexand-rh The change lgtm. And QE also filed a bug https://bugzilla.redhat.com/show_bug.cgi?id=1779578 about the default noProxy list on vSphere, could you fix that issue together?

**Comment by kalexand-rh** [comment]
@gpei, I've added the requirement for the machine IP address range. Will you please check again?

**Comment by gpei** [comment]
lgtm now.

**Comment by kalexand-rh** [comment]
@openshift/team-documentation, will you PTAL?

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
