### PR TITLE
RHDEVDOCS-6123: Content creation for GitOps 1.12.5 RN

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.12, GitOps 1.13, GitOps 1.14

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6123

Link to docs preview:

[Release Notes for Red Hat OpenShift GitOps 1.12.5](https://79804--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-12-5_gitops-release-notes)

QE review:
- [x] QE has approved this change.

SME review: Completed by anjoseph@redhat.com
QE review: Completed by @varshab1210 
Peer review: Completed by @Srivaralakshmi 

Additional information:

### CODE REVIEW

**Comment by varshab1210** [comment]
LGTM, thanks

**Review by anandf — APPROVED** [review]
LGTM

**Review by Srivaralakshmi — COMMENTED** [review]
LGTM

**Comment by Srivaralakshmi** [comment]
@Dhruv-Soni11 I am ignoring 1.11 CP and CPing into 1.12 and later.

**Comment by Srivaralakshmi** [comment]
The accidental merge with unqsuashed commits warrants a revert of this PR.

**Pull request merged**
