### PR TITLE
Updating nesting levels of heading parameter.  BZ_1850487

### PR DESCRIPTION
**Pull request by JStickler**
Second attempt to fix the nesting levels in the YAML example.

### CODE REVIEW

**Comment by JStickler** [comment]
@gbaufake , would you mind taking a look at this (and testing the YAML file) since Tiago is in training this week?

**Comment by gbaufake** [comment]
I am on it.

**Comment by gbaufake** [comment]
@JStickler 

```
oc apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v3
EOF
```

> virtualservice.networking.istio.io/reviews created

it seems the yaml is correct.

**Review by gbaufake — APPROVED** [review]

**Review by neal-timpe — APPROVED** [review]

**Pull request merged**
