### PR TITLE
[OSDOCS-9570]Asia-south-2 Delhi: Enable priority-0 GCP regions for OSD

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-9570
Link to docs preview:

https://73448--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition#regions-availability-zones_osd-service-definition
QE review:
- [x] QE has approved this change.

Additional information:

image

**FYI tied to https://issues.redhat.com/browse/XCMSTRAT-68**

### CODE REVIEW

**Comment by lentosun** [comment]
@mletalie Hi, I saw in the gcp doc https://cloud.google.com/compute/docs/regions-zones, it used "Delhi, India, APAC", and  here we only  use "Delhi" in our doc. Should we change it to "Delhi, India"?

**Comment by mletalie** [comment]
> @mletalie Hi, I saw in the gcp doc https://cloud.google.com/compute/docs/regions-zones, it used "Delhi, India, APAC", and here we only use "Delhi" in our doc. Should we change it to "Delhi, India"?

Hello @lentosun, 
    Good catch and absolutely. I should have caught that :( Will update and send back to you, thx!

**Pull request merged**
