### PR TITLE
document imageimport pem file argument

### PR DESCRIPTION
**Pull request by bparees**
provides doc for the fix to https://bugzilla.redhat.com/show_bug.cgi?id=1592936

### CODE REVIEW

**Comment by bparees** [comment]
@bmcelvee ptal.  3.11 and above only.

**Comment by bmcelvee** [comment]
Thanks, @bparees! LGTM

**Comment by bmcelvee** [comment]
Thanks, @bparees! I'm sorry about that, I'll get it merged today.

**Comment by bmcelvee** [comment]
Minor change. Does not require QE.

**Comment by xingxingxia** [comment]
Now I read this but seems didn't see this doc in [3.11 doc](https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-config-image-policy-config) ? Anything wrong? (I come here pointed to by [1592936#c29](https://bugzilla.redhat.com/show_bug.cgi?id=1592936#c29))

**Comment by bparees** [comment]
@xingxingxia good question.. @bmcelvee ?   

it is in the origin docs:
https://docs.okd.io/latest/install_config/master_node_configuration.html#master-config-image-policy-config

Note that we've actually addressed this a different way anyway, the api server is going to start mounting the /etc/pki from the host node, so you should not need to use this setting.

**Comment by bmcelvee** [comment]
Looks like this one [somehow] didn't get pulled into the 3.11 branch when it was created. I'm sorry about that.

@bparees Even though it's addressed in a different way, I can still cherry-pick the parameter + description into 3.11. Is that okay with you?

**Comment by bparees** [comment]
@bmcelvee that's fine.

**Comment by bmcelvee** [comment]
Thanks! All set.

**Pull request merged**
