### PR TITLE
Migration of SDN multitenant mode content

### PR DESCRIPTION
**Pull request by jboxman**
Remix of https://github.com/openshift/openshift-docs/pull/14082.

### CODE REVIEW

**Comment by jboxman** [comment]
Background --

This content pertains to OpenShift SDN multitenant mode, the default in OCP 3.11. In OCP 4.1, the default is NetworkPolicy mode. The former mode must be chosen explicitly at cluster installation, it cannot currently be changed thereafter.

**Comment by jboxman** [comment]
@openshift/team-documentation, PTAL? Thanks.

**Comment by ahardin-rh** [comment]
@jboxman LGTM!

**Comment by jboxman** [comment]
@bmeng @zhaozhanqi 

Can you PTAL at this? I'd like to get it merged for 4.1 GA.

Thank you!

**Comment by bmeng** [comment]
LGTM. Thanks.

**Pull request merged**
