### PR TITLE
[SD-DOCS] Typos corrected

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

Enterprise 
4.12+
Issue:

https://github.com/openshift/openshift-docs/issues/54443
Link to docs preview:

https://54737--docspreview.netlify.app/openshift-enterprise/latest/cicd/pipelines/using-tekton-chains-for-openshift-pipelines-supply-chain-security.html#installing-tekton-chains-using-pipelines-operator_using-tekton-chains-for-openshift-pipelines-supply-chain-security
QE review:
- [ ] QE has approved this change.

Additional information:

Typos corrected

### CODE REVIEW

**Review by skrthomas — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.13` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.12. And any PR going into `main` must also target the latest version branch (enterprise-4.13).

If the update in your PR does NOT apply to version 4.13 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
