### PR TITLE
Update dev guide for ephemeral storage

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up to https://github.com/openshift/openshift-docs/pull/10828.

@aheslin 
http://file.rdu.redhat.com/~tmorriso/071718/devguid/dev_guide/application_ephemeral_storage_sizing.html
http://file.rdu.redhat.com/~tmorriso/071718/devguid/dev_guide/compute_resources.html#dev-compute-resources
http://file.rdu.redhat.com/~tmorriso/071718/devguid/dev_guide/deployments/basic_deployment_operations.html#deployment-resources

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@jhou1 @liangxia Please provide QE review.

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Review by kalexand-rh — COMMENTED** [review]
Is dev_guide/application_ephemeral_storage_sizing.adoc actually enough to help users size storage? It has a lot of good conceptual info, but IDK if they could do anything with it.

**Pull request merged**
