### PR TITLE
CNV-13679: RN SR-IOV live migration feature gate enabled by default

### PR DESCRIPTION
**Pull request by sjhala-ccs**
[CNV-13679](https://issues.redhat.com/browse/CNV-13679)

RN to document that live migration is now supported by default for VMs connected to SR-IOV network interfaces

Preview: https://deploy-preview-42300--osdocs.netlify.app/openshift-enterprise/latest/virt/virt-4-10-release-notes#virt-4-10-networking-new

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
LGTM, thanks.

**Review by ormergi — APPROVED** [review]
Looks good to me, thank you!

**Comment by yossisegev** [comment]
LGTM

**Comment by ousleyp** [comment]
LGTM!

**Pull request merged**
