### PR TITLE
OSDOCS-7630: Documented the 4.13.11 z-stream release notes

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-7630](https://issues.redhat.com/browse/OSDOCS-7630)

Version(s):
4.13

Link to docs preview:
* [4.13.11 z-stream notes](https://64262--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes#ocp-4-13-11)

QE review:
- [x] QE approval is not required for z-stream release notes. 

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM! 

I am new to the squad, please wait until @abhatt-rh give my review the go-ahead! Thanks

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by abhatt-rh** [comment]
> LGTM!
> 
> I am new to the squad, please wait until @abhatt-rh give my review the go-ahead! Thanks
> 
> /remove-label peer-review-needed /remove-label peer-review-in-progress /label peer-review-done

Hi @dfitzmau and @xenolinux: Peer review LGTM!

**Review by jeana-redhat — COMMENTED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
