### PR TITLE
Document --param-file and --env-file oc arguments

### PR DESCRIPTION
**Pull request by mmilata**
Documentation for openshift/origin#12164.
Trello card: https://trello.com/c/BMuLvOny/968-5-supply-oc-new-app-and-oc-process-parameter-list-env-vars-via-a-file-app-creation

### CODE REVIEW

**Comment by mmilata** [comment]
@openshift/team-documentation @bparees PTAL

**Comment by bparees** [comment]
lgtm

**Comment by ahardin-rh** [comment]
LGTM. I applied the to_followup label and will follow up with minor style edits in a separate PR. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/application_lifecycle/new_app.adoc#dev-guide-new-app[Application Life Cycle Management -> Creating New Applications]
|Added information about `--param-file` and `--env-file` `oc` command arguments to the xref:../dev_guide/application_lifecycle/new_app.adoc#template-parameters[Template Parameters] section.
%
|xref:../dev_guide/templates.adoc#dev-guide-templates[Templates]
|Added information about `--param-file` and working with a large number of parameters to the xref:../dev_guide/application_lifecycle/new_app.adoc#template-parameters[Parameters] section.
%

**Pull request merged**
