### PR TITLE
AUTH-133: Pod security admission

### PR DESCRIPTION
**Pull request by bergerhoffer**
Will replace PR #47647 from @maxwelldb.

Version(s):
4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3535

Link to docs preview: http://file.rdu.redhat.com/~ahoffer/2022/pr-47647/authentication/understanding-and-managing-pod-security-admission.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Opened PR with initial content from #47647.

Updates (compared to original PR) after peer review: https://github.com/openshift/openshift-docs/compare/68fb49674f047ddeacf60d32e190365bbc45c692..ceb9a44db34b232beaf1ef87b6ba251a982880b1

**Comment by kalexand-rh** [comment]
@y4sht, will you PTAL? This is one of the very few docs issues that we haven't gotten through QE, and we need to get them all reviewed before we can claim that docs are ready for GA.

**Comment by y4sht** [comment]
> @y4sht, will you PTAL? This is one of the very few docs issues that we haven't gotten through QE, and we need to get them all reviewed before we can claim that docs are ready for GA.

Only one concern, Can `All namespaces that are prefixed with openshift-, except for openshift-operators` this line be incorporated with `Namespaces that have an openshift- name prefix and were not created by the system during the installation are not synchronized by default.` otherwise LGTM

**Comment by y4sht** [comment]
LGTM

**Comment by bergerhoffer** [comment]
This PR is technically the peer review of the original PR, so marking peer review done.

**Pull request merged**
