### PR TITLE
OSDOCS#8870: Add BYOK support for IBM VPC

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OSDOCS-8870

Link to docs preview: https://68762--docspreview.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-ibm-vpc-block#byok_persistent-storage-csi-ibm-vpc-block

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gcharot, @dobsonj, @Phaow

### CODE REVIEW

**Comment by nalhadef** [comment]
label peer-review-in-progress
/remove-label peer-review-needed

**Comment by gcharot** [comment]
LGTM

**Comment by jeffnowicki** [comment]
_"The user-managed encryption feature allows you to provide keys during installation that encrypt OpenShift Container Platform node root volumes, and enables **all managed storage classes** to use these keys to encrypt provisioned storage volumes. You must specify the custom key in the platform.<cloud_type>.defaultMachinePlatform field in the install-config YAML file."_

For IBM Cloud VPC Block Storage, the key specified in `defaultMachinePlatform` spec will only be injected into the `default` storage class (not all managed storage classes).

@dobsonj - do you agree?

**Comment by Phaow** [comment]
Hello @jeffnowicki , generally from storage scope, we impled with inject the key to all managed storage classes, ibmcloud is the same logic with aws. Is there any customer requirement that only inject the default storageclass?
```console
 wangpenghao@MacBook-Pro  ~  oc version
Client Version: 4.14.0-rc.0
Kustomize Version: v5.0.1
Server Version: 4.15.0-0.nightly-2023-12-11-033133
Kubernetes Version: v1.28.4+7aa0a74
 wangpenghao@MacBook-Pro  ~  oc get sc
NAME                                   PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ibmc-vpc-block-10iops-tier (default)   vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   97m
ibmc-vpc-block-5iops-tier              vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   97m
ibmc-vpc-block-custom                  vpc.block.csi.ibm.io   Delete          WaitForFirstConsumer   true                   97m
 wangpenghao@MacBook-Pro  ~  oc get sc -ojsonpath='{.items[*].parameters}'| jq .
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "true",
  "encryptionKey": "crn:v1:bluemix:public:kms:eu-gb:a/fdc2e14cf8bc4d53a67f972dc2e2c861:70691649-8640-41c5-9af8-68ebbdd8c660:key:43685f21-4509-43ef-90ac-xxxxxx",
  "profile": "10iops-tier",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "true",
  "encryptionKey": "crn:v1:bluemix:public:kms:eu-gb:a/fdc2e14cf8bc4d53a67f972dc2e2c861:70691649-8640-41c5-9af8-68ebbdd8c660:key:43685f21-4509-43ef-90ac-xxxxxx",
  "profile": "5iops-tier",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
{
  "csi.storage.k8s.io/fstype": "ext4",
  "encrypted": "true",
  "encryptionKey": "crn:v1:bluemix:public:kms:eu-gb:a/fdc2e14cf8bc4d53a67f972dc2e2c861:70691649-8640-41c5-9af8-68ebbdd8c660:key:43685f21-4509-43ef-xxxxxx",
  "iops": "400",
  "profile": "custom",
  "region": "",
  "resourceGroup": "",
  "tags": "",
  "zone": ""
}
```

**Comment by dobsonj** [comment]
@Phaow is correct, the key is injected into all managed storageclasses.

**Comment by Phaow** [comment]
LGTM

**Pull request merged**
