### PR TITLE
BZ#1879380 Compute machine creation not required in all cases

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1879380

### CODE REVIEW

**Comment by codyhoag** [comment]
@mike-nguyen can you review? Thanks!

**Comment by codyhoag** [comment]
@morenod do you mind verifying this info? Thanks!

**Review by morenod — APPROVED** [review]
LGTM

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
