### PR TITLE
MIG-1539: incorrect command in modules/migration-migrating-applications-api.adoc

### PR DESCRIPTION
**Pull request by anarnold97**
### JIRA

* [MIG-1539](https://issues.redhat.com/browse/MIG-1539)

### VERSION

*  OCP 4.12 → branch/enterprise-4.12
*  OCP 4.13 → branch/enterprise-4.13
*  OCP 4.14 → branch/enterprise-4.14
*  OCP 4.15 → branch/enterprise-4.15
*  OCP 4.16 → branch/enterprise-4.16

### Link to docs preview:

* [Migrating an application by using the MTC API 3->4](https://75472--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/advanced-migration-options-3-4.html#migration-migrating-applications-api_advanced-migration-options-3-4)

* [Migrating an application by using the MTC API](https://75472--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migration_toolkit_for_containers/advanced-migration-options-mtc.html#migration-migrating-applications-api_advanced-migration-options-mtc)

### QE review:
- [X ] [QE has approved this change](https://github.com/openshift/openshift-docs/pull/75472#issuecomment-2091297666).

### CODE REVIEW

**Review by stillalearner — APPROVED** [review]
lgtm

**Comment by anarnold97** [comment]
@mburke5678 - ta very much

**Review by opayne1 — APPROVED** [review]

**Pull request merged**
