### PR TITLE
From BZ1689796: correcting oreg url for Satellite

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/14237

@bysnupy, I fixed a typo and updated the format a little.

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by bysnupy** [comment]
@kalexand-rh Thank you for your correction ! 
Maybe this change is required to apply after fixing  ["oreg_url" does not work on disconnected installation using Satellite](https://bugzilla.redhat.com/show_bug.cgi?id=1689796).

**Comment by kalexand-rh** [comment]
Ok, @bysnupy, I'll follow that bug and wait for it to be resolved before I merge this one.

**Comment by bysnupy** [comment]
@kalexand-rh 

`osm_etcd_image` is required if `oreg_url` is different with it.
So I think it had better to modify the example as follows, could you get your thought about it ?

~~~
---
oreg_url=satellite.example.com/oreg-prod-openshift3_ose-${component}:${version}
openshift_examples_modify_imagestreams=true
# If etcd image url's prefix is different with oreg_url, osm_etcd_image should be set to its specific one.
# osm_etcd_image=satellite.example.com/oreg-prod-rhel7_etcd:3.2.22
---
~~~

**Comment by jianlinliu** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
Thank you @jianlinliu!

@bysnupy, I added a note for the  `osm_etcd_image` parameter. Does it look right to you?

**Comment by bysnupy** [comment]
Perfect! Thank you @kalexand-rh !

**Pull request merged**
