### PR TITLE
OSDOCS-1519 document SameSite route annotation

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-1519

### CODE REVIEW

**Comment by bmcelvee** [comment]
@miheer and @quarterpin would you mind reviewing this PR, please?

**Comment by quarterpin** [comment]
In addition, we can mention `(applicable to re-encrypt and edge routes only)` beside the  SameSite annotation line in the doc to be more clear for the reader. It looks fine otherwise. Thanks!

**Comment by miheer** [comment]
@bmcelvee can we point to external reference like https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite ?

**Comment by miheer** [comment]
Also the value explanation shall be like the one mentioned under "Value" section of  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by bmcelvee** [comment]
Thank you @quarterpin and @miheer! The PR is up to date.

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL :snowflake:

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
