### PR TITLE
Review installation

### PR DESCRIPTION
**Pull request by rhcarvalho**
A casual review as I went through the installation docs.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@openshift/team-documentation PTAL

**Comment by rhcarvalho** [comment]
@openshift/team-documentation PTAL

**Comment by vikram-redhat** [comment]
@danmacpherson - please incorporate in your install guide work.

**Comment by rhcarvalho** [comment]
@danmacpherson do you have an open PR where you're including this? How could I best help moving this forward? Thanks.

**Comment by ahardin-rh** [comment]
@danmacpherson @vikram-redhat Have these edits been addressed? Can this be closed?

**Comment by danmacpherson** [comment]
Due to the branch conflicts, I felt it would be easier to create a new MR and cherry-pick commits from this MR. See MR #4530.

@ahardin-rh @vikram-redhat please feel free to close this MR.

**Comment by danmacpherson** [comment]
Also my apologies for the delay on this @rhcarvalho. I had your commits included with my installation guide revamp, but the project got put on hold.

**Comment by ahardin-rh** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/4530

**Pull request closed without merging**
