### PR TITLE
[OSDOCS-5684]:Update link for ROSA service definition

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-5684
Link to docs preview:

https://58310--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_architecture_sub/rosa-architecture-models.html
image

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Apologies to the peer review squad. I added a "peer review needed" label before realizing I had to squash a commit. Hence the ongoing build. Thanks. ML

**Review by ousleyp — COMMENTED** [review]
Just one nit; otherwise, this looks good.

**Pull request merged**
