### PR TITLE
OSDOCS#10721: Disaster recovery - add a step to wait for redeployment to complete

### PR DESCRIPTION
**Pull request by tmalove**
Version(s):
4.16+

[Link](https://79802--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state) to docs preview: (updated 8/1)
Changes on Steps 18 and 19.

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
@dusk125 will you take a look at the change on steps 18 and 19 (new step). Thanks!

**Comment by dusk125** [comment]
We could replace the `oc get pods` command with `oc adm wait-for-stable-cluster`.

**Comment by tmalove** [comment]
> We could replace the `oc get pods` command with `oc adm wait-for-stable-cluster`. This will block the terminal until the all the etcd instances have stabilized on the same revision.

@dusk125 Due to this command, I also removed the sentence that instructs the user to wait before going to the next step.

**Comment by tmalove** [comment]
@geliu2016 Will you review this change in Steps 18 and 19? Thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
