### PR TITLE
BZ2029403: Replace duplicated paragraph

### PR DESCRIPTION
**Pull request by gabriel-rh**
4.6+

[BZ2029403](https://bugzilla.redhat.com/show_bug.cgi?id=2029403)

[Preview](https://deploy-preview-40300--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-restricted-network-cluster#update-oc-configmap-signature-verification_updating-restricted-network-cluster)

@evakhoni

### CODE REVIEW

**Review by ctauchen — COMMENTED** [review]
This sentence is LGTM, but:

Have you considered removing the lead-in sentence altogether?

This sentence mostly rearranging the title, and SSG guidance suggests we shouldn't bother unless there's particularly useful information:

"Do not use a lead-in sentence in the Prerequisites or Procedure sections of a module unless it is necessary to aid navigation or add clarity."

What do you think?

**Comment by gabriel-rh** [comment]
https://redhat-documentation.github.io/supplementary-style-guide/#lead-in-sentences

> Lead-in sentences for Prerequisites and Procedure sections
>A lead-in sentence in this context is the text that directly follows a Prerequisites or Procedure heading in a task-based module. It is distinct from the module abstract, which describes the goals of the user for the module.

>Do not use a lead-in sentence in the Prerequisites or Procedure sections of a module unless it is necessary to aid navigation or add clarity.


I think this is an "introduction" as per the https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules

In general, I think there is a recommendation against having two headings back-to-back, without intervening text. I'm not sure I agree with that everywhere, but in this instance, I think the intro explains why to use this method instead of the manual one, so it isn't completely superfluous.

**Comment by ctauchen** [comment]
@gabriel-rh Thanks for that. I hadn't seen that in the mod docs guidelines. Seems we have conflicting guidance.

This one remains LGTM. Let me know if you need a merge.

**Comment by gabriel-rh** [comment]
@ctauchen  QE acked - https://bugzilla.redhat.com/show_bug.cgi?id=2029403

Can you go ahead and merge? Thanks

**Pull request merged**
