### PR TITLE
[OCPBUGS-22184] 4.13 backport - Add single stack restriction IBM Power and IBM Z

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.12, 4.13

Backport of this PR: https://github.com/openshift/openshift-docs/pull/66587

Issue: https://issues.redhat.com/browse/OCPBUGS-22184

Link to docs preview: https://66700--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes#nw-ovn-kubernetes-matrix_about-ovn-kubernetes

QE review: @holgwolf 
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by holgwolf** [comment]
lgtm

**Review by kcarmichael08 — COMMENTED** [review]
lgtm!

**Comment by kcarmichael08** [comment]
Is there a PR for 4.12 that could be linked also?

**Comment by kalexand-rh** [comment]
This PR looks like it will be safe to use the bot to CP to 4.12.

**Pull request merged**
