### PR TITLE
Updates a command because there are no pods labeled fluentd in OCP

### PR DESCRIPTION
**Pull request by stevsmit**
Updating a command slightly. 

For 4.6+ 

Preview: Troubleshooting log forwarding

image

Preview: Forwarding JSON logs: 

image

Issue: https://github.com/openshift/openshift-docs/issues/46089

Pending QE.

### CODE REVIEW

**Comment by mjpytlak** [comment]
Thanks @stevsmit peer review LGTM.

**Review by anpingli — COMMENTED** [review]
/lgtm

**Pull request merged**
