### PR TITLE
Fixes typo of inital to initial

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-31028

Link to docs preview:

QE not needed. Typo fix.

### CODE REVIEW

**Comment by jab-rh** [comment]
@stevsmit, isn't that going to break including this file: `modules/preparing-an-inital-cluster-deployment-for-mce-connected.adoc`

I think these need to be renamed as well?

**Comment by stevsmit** [comment]
> @stevsmit, isn't that going to break including this file: `modules/preparing-an-inital-cluster-deployment-for-mce-connected.adoc`
> 
> I think these need to be renamed as well?

@jab-rh I think I'm confused. I did rename modules/preparing-an-inital-cluster-deployment-for-mce-connected.adoc (the ID was fixed and the module was renamed). Prowl flagged that. Here it is in the repo: 

image

**Comment by jab-rh** [comment]
@stevsmit, looks like the icons show up as rename now. GitHub was showing a different symbol oddly.

**Comment by jab-rh** [comment]
@stevsmit, LGTM

**Pull request merged**
