### PR TITLE
GH#30718: Modify code block options in RHV playbooks module

### LINKED ISSUE #30718: [enterprise-4.7] Improperly rendered {product-version} in RHV docs
### Which section(s) is the issue in?
"Downloading the Ansible playbooks"

https://docs.openshift.com/container-platform/4.7/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-downloading-ansible-playbooks_installing-rhv-user-infra

### What needs fixing?
{product-version} is shown in the command rather than the actual product version.

### PR DESCRIPTION
**Pull request by maxwelldb**
This change adds "subs=attributes+" to code block options.
As a result, attributes within the code block should render correctly.
Commit resolves #30718. 

@rolfedh Could you verify this and +1/-1 after the preview? Not sure if you'd also want QE to take a look.

### CODE REVIEW

**Comment by rolfedh** [comment]
Hi, @maxwelldb. Thanks for working on this. Vikram is removing {product-version} from the attributes file. I've forwarded the relevant email to you. When his PR clears, it will break this attribute. Better to replace it with a hard-coded value, such as 4.7.

**Comment by maxwelldb** [comment]
@rolfedh Given that product-version should still be available, do you want QE to check this out? If so, any recommendations on who? 

I tried to run this command exactly, but it just errored back:

```
curl -L -X GET https://api.github.com/repos/openshift/installer/contents/upi/ovirt\?ref\=$release-4.7
```

No idea if that's expected without context.

**Comment by rolfedh** [comment]
FYI - here's the preview for this topic: https://deploy-preview-30719--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-downloading-ansible-playbooks_installing-rhv-user-infra

**Comment by maxwelldb** [comment]
@jan-zmeskal Would you be able to help us fix this URL issue? In the preview in Rolfe's comment, you'll see the troublesome commands. 

The preview build doesn't provide the command exactly as it would appear in the docs--it should look like this:
```
$ mkdir playbooks
$ cd playbooks
$ curl -L -X GET https://api.github.com/repos/openshift/installer/contents/upi/ovirt\?ref\=$release-4.7 |
grep 'download_url.*\.yml' |
awk '{ print $2 }' | sed -r 's/("|",)//g' |
xargs -n 1 curl -O
```

**Comment by jan-zmeskal** [comment]
Hi, first I've got to say that I'm missing a lot of context there as it's been quite some time since I last worked on RHV/OCP integration. So I just took a look at the `curl` command and found out that it works when executed like this:
```shell
curl -L -X GET https://api.github.com/repos/openshift/installer/contents/upi/ovirt?ref=release-4.7
```
There were some extra escape backslashes that made the command fail. If you want the whole thing to work, this did the trick for me:
```shell
curl -s -L -X GET https://api.github.com/repos/openshift/installer/contents/upi/ovirt?ref=release-4.7 | grep 'download_url.*\.yml' | awk '{ print $2 }' | sed -r 's/("|",)//g' | xargs -n 1 curl -O
```
Notice that I added `-s` parameter to the first `curl` invocation. If you don't do that, `curl`'s output might get mixed with the pulled data.

**Comment by rolfedh** [comment]
Thanks, Jan. It works now. I'm not sure, but I vaguely remember someone
adding the escapes to make this more cross-platform. Not sure if it
matters. When I added the escapes back on my command line, it worked fine.

**Comment by jan-zmeskal** [comment]
This is possible. I tested this on Fedora workstation and I definitely can't vouch for this working across platforms. But I assume that in our docs we mostly care about RHEL-like systems and we should be good there.

**Comment by maxwelldb** [comment]
@jan-zmeskal Thanks for the help! I also lack context on this, but your suggestion looks good to me. 

I was just trying to fix a rendering error in the docs, and now it's looking like this might be something that needs proper investigation. 

I'm going to rope in RHV writers here.

**Comment by maxwelldb** [comment]
@stoobie @emarcusRH Hi! Would either of you be able to take a look at this?

**Comment by jboxman** [comment]
I notice this is still an issue and any customer trying to run this will blow up.

**Comment by jboxman** [comment]
@vikram-redhat, I haven't been successful in determining what QE team is correct to acknowledge this small change. I'm no longer sure how to proceed, although the change is small enough that a customer can probably stumble past this even if we never get it fixed. That seems suboptimal though.

**Comment by ctomasko** [comment]
@jboxman The RHV QE manager, Lucie Leistnerova confirmed that the the review by @jan-zmeskal satisfies the RHV - QE review requirement. Jan was formerly on RHV QE. Let us know if you need anything else before merging this PR. Thanks for your help.

**Comment by leistnerova** [comment]
Hi, thank you Catherine. Yes this fix is approved.

**Pull request merged**
