### PR TITLE
OSDOCS-3145: 4.10 RN for iso/pxe customize

### PR DESCRIPTION
**Pull request by bobfuru**
https://issues.redhat.com/browse/OSDOCS-3145

Release Note tracker note: https://github.com/openshift/openshift-docs/issues/37586#issuecomment-1024996962

**Preview link:** https://deploy-preview-41442--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes#ocp-4-10-coreos-installer-customize

### CODE REVIEW

**Comment by bobfuru** [comment]
@bgilbert and @jlebon PTAL for SME review
@miabbott for QE
Cc: @jldohmann

**Review by miabbott — APPROVED** [review]
LGTM

**Review by bgilbert — APPROVED** [review]
LGTM

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
LGTM too :)

**Pull request merged**
