### PR TITLE
Enterprise-4.17 - CNV#35150: removing OADP from Virt docs

### PR DESCRIPTION
**Pull request by anarnold97**
### Cherry pick

Cherry Picked from 18916350443e66e194fedf150a20570dba961d45 xref:https://github.com/openshift/openshift-docs/pull/75004 

### Jira: 

* [CNV-35150](https://issues.redhat.com//browse/CNV-35150)

### OCP version

* 4.17

### Link to docs preview:

* https://79323--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/backup_restore/virt-backup-restore-overview

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
@sjhala-ccs - FYI

**Comment by anarnold97** [comment]
@kalexand-rh - FYI 

There are also these errors coming up when we validate locally using Prow:

```
>>> Working on nodes book in openshift-enterprise <<<
Transforming the AsciiDoc content to DocBook XML...
asciidoctor: WARNING: includes/olm-overriding-operator-pod-affinity.adoc: line 214: callout list item index: expected 2, got 1
asciidoctor: WARNING: includes/olm-overriding-operator-pod-affinity.adoc: line 214: no callout found for <2>

...

>>> Working on release_notes book in openshift-enterprise <<<
Transforming the AsciiDoc content to DocBook XML...
asciidoctor: WARNING: tables must have at least one body row
asciidoctor: WARNING: tables must have at least one body row
asciidoctor: WARNING: tables must have at least one body row 
````

Do you want us to fix these tomorrow?

**Comment by sjhala-ccs** [comment]
@anarnold97 Can you match the OSD and ROSA topic map files to main? As in include the commented out lines as well: https://github.com/openshift/openshift-docs/pull/75004/files#diff-54b6c45a07b510755a4b365a48b7130a0369666209fd2e835b543de5e909e2f6L1658-R1659

**Comment by kalexand-rh** [comment]
> @kalexand-rh - FYI
> 
> There are also these errors coming up when we validate locally using Prow:
> 
> ```
> >>> Working on nodes book in openshift-enterprise <<<
> Transforming the AsciiDoc content to DocBook XML...
> asciidoctor: WARNING: includes/olm-overriding-operator-pod-affinity.adoc: line 214: callout list item index: expected 2, got 1
> asciidoctor: WARNING: includes/olm-overriding-operator-pod-affinity.adoc: line 214: no callout found for <2>
> 
> ...
> 
> >>> Working on release_notes book in openshift-enterprise <<<
> Transforming the AsciiDoc content to DocBook XML...
> asciidoctor: WARNING: tables must have at least one body row
> asciidoctor: WARNING: tables must have at least one body row
> asciidoctor: WARNING: tables must have at least one body row 
> ```
> 
> Do you want us to fix these tomorrow?

If you have time, please.

**Comment by anarnold97** [comment]
@sjhala-ccs - I had have to include some of your changes from this [PR -  CNV#41658: adding backup assembly to rosa/osd #78527 ](https://github.com/openshift/openshift-docs/pull/78527/files#diff-b445f85a73087a4a7b261d20dc3b64b8f4d255356a2297853788e9c759bcd1d7) to get this to work

As without it, you cannot continue without these changes.

Also, I am not sure removing 

```
[IMPORTANT]
====
Red Hat supports using {VirtProductName} 4.14 or later with {oadp-short} 1.3.x or later.
{oadp-short} versions before 1.3.0 are not supported for back up and restore of {VirtProductName}.
====
```
is correct as the OADP QE and Devs were very explicit about including this in the Virt backup and restore. Potentially, you could have users trying to this with OADP 1.2 to backup, which will not work. But I would rather stay out of this.

**Comment by sjhala-ccs** [comment]
> @sjhala-ccs - I had have to include some of your changes from this [PR - CNV#41658: adding backup assembly to rosa/osd #78527 ](https://github.com/openshift/openshift-docs/pull/78527/files#diff-b445f85a73087a4a7b261d20dc3b64b8f4d255356a2297853788e9c759bcd1d7) to get this to work
> 
> As without it, you cannot continue without these changes.

Okay. So, is this ready to be merged now?

**Comment by sjhala-ccs** [comment]
> Also, I am not sure removing
> 
> ```
> [IMPORTANT]
> ====
> Red Hat supports using {VirtProductName} 4.14 or later with {oadp-short} 1.3.x or later.
> {oadp-short} versions before 1.3.0 are not supported for back up and restore of {VirtProductName}.
> ====
> ```
> 
> is correct as the OADP QE and Devs were very explicit about including this in the Virt backup and restore. Potentially, you could have users trying to this with OADP 1.2 to backup, which will not work. But I would rather stay out of this.

I did not work on that PR, so I am not sure about why that change was made

**Comment by anarnold97** [comment]
@sjhala-ccs Thanks. It is ok to merge from the OADP docs point. 

I do not know what to suggest about that admonition.

**Comment by sjhala-ccs** [comment]
@anarnold97 I just noticed that the admonition was not removed, it was moved to the top of the module.

**Comment by anarnold97** [comment]
@sjhala-ccs - that is great, thanks

**Pull request merged**
