### PR TITLE
Remove outdated ShiftStack support note

### LINKED ISSUE #21465: [enterprise-4.3] Edit suggested in file scalability_and_performance/scaling-cluster-monitoring-operator.adoc
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/modules/prometheus-database-storage-requirements.adoc
Section: Lab environment

### What needs fixing?
"Currently, OpenStack environments are not supported for OpenShift Container Platform 4.3."
OCP 4.3 (and previous version too) is supported on OpenStack. This warning should be removed

### PR DESCRIPTION
**Pull request by maxwelldb**
Resolves GH-21465

### CODE REVIEW

**Comment by maxwelldb** [comment]
@morenod Can you think of any reason that this note should remain? Prometheus is fully supported for ShiftStack, right?

**Comment by maxwelldb** [comment]
Going by the review comment that generated this note a couple of years ago, I'd assume not: 
image

Removing review request. Sorry to bother you!

**Comment by maxwelldb** [comment]
https://osp-support-note-gh-21465--ocpdocs.netlify.app/openshift-enterprise/latest/scalability_and_performance/scaling-cluster-monitoring-operator.html

**Comment by maxwelldb** [comment]
I do not believe that this PR requires QE. Reasons:
1. https://access.redhat.com/articles/4679401
2. I've been writing the ShiftStack documentation since 4.2. If OpenStack isn't a supported platform, I've wasted the last 1.5 years. :smile:

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
