### PR TITLE
Bug 1487360, Clarified that Support needs added for those services to be available

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1487360

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@sferich888 PTAL
@abhgupta FYI

**Comment by ahardin-rh** [comment]
@sferich888 Please review

**Comment by sferich888** [comment]
Is there a way we can make this, look more like the quick start, guides and supply screenshots?

**Comment by ahardin-rh** [comment]
@sferich888 I don't think screenshots are necessary for this. The UI is pretty straight forward for this workflow. I vote for simplicity and less screenshots to maintain.

**Pull request merged**
