### PR TITLE
fixed broken internal links

### PR DESCRIPTION
**Pull request by gaurav-nelson**
- link fixes

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL 
- Can you add labels as well?

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :squid:

**Comment by adellape** [comment]
@gaurav-nelson @bfallonf Shouldn't these have the full ID in the anchors, instead of hanging `#`s? Per [Links, Hyperlinks, and Cross References](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-hyperlinks-and-cross-references) guidelines.

**Comment by gaurav-nelson** [comment]
Thank you @adellape. I'll do a followup to fix these.

**Comment by gaurav-nelson** [comment]
No revision history required.

**Pull request merged**
