### PR TITLE
cnv: Clarify that descheduling of VMs will lead to live migration

### PR DESCRIPTION
**Pull request by fabiand**
A small clarification that in the CNV case, pod evictions will trigger VM live migrations.

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

Version(s):

Issue:

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by fabiand** [comment]
@bgaydosrh @ctomasko is this something you can help with?

**Comment by bgaydosrh** [comment]
Hi @fabiand - @ctomasko will be in touch and will coordinate how we'll get this done for you, Thanks. Bob

**Comment by ctomasko** [comment]
@fabiand I created jira task https://issues.redhat.com/browse/CNV-18183 for a technical writer to review/edit your contribution and update the documentation.

**Comment by fabiand** [comment]
4.10 is sufficient. Thanks Bob.

I'm closing this PR in favor of #45946

**Pull request closed without merging**
