### PR TITLE
Separating command and output for the helm CLI docs

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@boczkowska In case you haven't heard yet, we're doing an effort to separate commands and output into separate code blocks. And also to add `[source,terminal]` to commands and output. 

I've updated the helm CLI docs here if you could please review. I'll look at the odo docs in a separate PR in a bit. Though that one is a bit more substantial, so I'll let you know if I need any help with it. Let me know if you have any questions on all of this.

Also keep in mind going forward to separate command and output, and add [source,terminal].

**Review by jeana-redhat — COMMENTED** [review]
lgtm :)

**Pull request merged**
