### PR TITLE
allow 'allow-lists' per container repo

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OSDOCS-1850

Preview: https://deploy-preview-31263--osdocs.netlify.app/openshift-enterprise/latest/openshift_images/image-configuration.html#images-configuration-allowed_image-configuration

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio Please take a look. Thank you!!

**Comment by sunilcio** [comment]
@mburke5678 thanks, reviewed and tested. LGTM

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
