### PR TITLE
[56255]: Corrected the apiversion for runtimeclass resource

### LINKED ISSUE #56255: wrong apiVersion for runtimeclass
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/main/modules/creating-runtimeclass.adoc

### What needs fixing?
apiVersion

### PR DESCRIPTION
**Pull request by rprakashg-rh**
Fixes #56255

Fixed apiversion for runtimeclass

Version(s):
OpenShift 4.12

### CODE REVIEW

**Comment by rprakashg-redhat** [comment]
Please review @openshift/team-documentation

**Comment by mburke5678** [comment]
@rprakashg-redhat Thanks for catching this. Can I ask you to change the instance in `modules/sandboxed-containers-preparing-openshift-cluster.adoc` also? If not let me know and I can take care of it. 
I believe this change can go back to OCP 4.9 (Kubernetes 1.22), as `node.k8s.io/v1` seems to have been introduced in Kubernetes 1.20.

**Comment by rprakashg-redhat** [comment]
Yep I can do that

**Comment by rprakashg-redhat** [comment]
Just checked the file modules/sandboxed-containers-preparing-openshift-cluster.adoc and the published docs and it seems to be correct there.

**Comment by rprakashg-redhat** [comment]
I did find some other places. Let me just go through and fix all

**Comment by rprakashg-redhat** [comment]
Sorry I was doing a search in github looks like it pulled up some files in different branch. Main looks all good to me now

**Comment by mburke5678** [comment]
I believe this change can go back to OCP 4.9 (Kubernetes 1.22), as node.k8s.io/v1 seems to have been [introduced in Kubernetes 1.20](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#runtimeclass-v125). Can you confirm?

**Comment by mburke5678** [comment]
@jfrancoa @rrasouli Can you PTAL? Thanks!

**Comment by kalexand-rh** [comment]
Only versions 4.10+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.14` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.13. And any PR going into `main` must also target the latest version branch (enterprise-4.14).

If the update in your PR does NOT apply to version 4.14 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by mburke5678** [comment]
@rprakashg-redhat Can you squash the two commits?

**Comment by kalexand-rh** [comment]
@rprakashg-redhat Can you squash the two commits?

**Comment by kalexand-rh** [comment]
Only versions 4.11+ are still in maintenance. I am removing labels from earlier versions from this PR.

**Review by mburke5678 — APPROVED** [review]

**Pull request closed without merging**
