### PR TITLE
Updates to domain names in egress network policy are based on domain TTL

### PR DESCRIPTION
**Pull request by pravisankar**
trello card: https://trello.com/c/yH9l0ouV

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/team-documentation PTAL

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL as this is networking related.

**Comment by bfallonf** [comment]
@pravisankar Looks like I broke this by merging #3575 . Can I ask you rebase this, then I can merge? Thanks.

**Comment by pravisankar** [comment]
@bfallonf rebased, ptal
This feature is targeted for 3.6 release

**Comment by bfallonf** [comment]
Thanks @pravisankar . I'll merge.

**Pull request merged**
