### PR TITLE
Kibana console isn't accessible when enabled https_proxy in the cluster

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1818651

### CODE REVIEW

**Comment by mburke5678** [comment]
@anpingli @ewolinetz Please take a look. Do I have this right? It seems to work for me.

**Comment by ewolinetz** [comment]
@mburke5678 looks like what I had tested...

**Comment by ewolinetz** [comment]
@mburke5678 maybe remove the `noproxy.com` setting as that may be misleading

**Review by ewolinetz — APPROVED** [review]

**Comment by mburke5678** [comment]
@anpingli Please take a look

**Comment by anpingli** [comment]
@QiaolingTang Could you help on this?

**Comment by QiaolingTang** [comment]
@ewolinetz will you have some fix for the issue that the CLO doesn't update the deploy/kibana after the cluster proxy is updated ?

**Comment by ewolinetz** [comment]
@QiaolingTang I hadn't seen that issue on my local cluster... let me see if I can recreate what you're seeing.

Do you have any errors in the CLO/EO logs?

**Comment by QiaolingTang** [comment]
@ewolinetz No errors related to the EnvVar changes, details are in https://bugzilla.redhat.com/show_bug.cgi?id=1813209#c22

**Comment by ewolinetz** [comment]
@QiaolingTang thanks, i'll look into this!

**Comment by ewolinetz** [comment]
@QiaolingTang 

* https://github.com/openshift/elasticsearch-operator/pull/315
* https://github.com/openshift/cluster-logging-operator/pull/480

**Comment by mburke5678** [comment]
Is this PR waiting on https://bugzilla.redhat.com/show_bug.cgi?id=1823606 and https://bugzilla.redhat.com/show_bug.cgi?id=1813209?

**Comment by QiaolingTang** [comment]
LGTM

**Pull request merged**
