### PR TITLE
two known issues

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: No docs issue.

Link to docs preview: [RN Known issues](https://54700--docspreview.netlify.app/openshift-enterprise/latest/virt/virt-4-12-release-notes.html#virt-4-12-known-issues)

QE review: @jpeimer 
- [x] QE has approved this change.

Additional information: Known issues for [BZ#2158521](https://bugzilla.redhat.com/show_bug.cgi?id=2158521) and [BZ#2149654
](https://bugzilla.redhat.com/show_bug.cgi?id=2149654)

### CODE REVIEW

**Comment by apinnick** [comment]
Tagging @sabrinajess for awareness

**Comment by jpeimer** [comment]
/lgtm
Thanks, Avital!

**Review by JoeAldinger — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Review by JoeAldinger — COMMENTED** [review]
/lgtm
@apinnick let me know if this bug is going to require some coordination for asynchronous release. I work on release notes and cant help coordinate the effort.

**Comment by apinnick** [comment]
> /lgtm @apinnick let me know if this bug is going to require some coordination for asynchronous release. I work on release notes and cant help coordinate the effort.

@JoeAldinger Thanks for the offer but not necessary. CNV already has the asynch release process started. :-)

**Pull request merged**
