### PR TITLE
Add Idea to gitignore

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by dmvolod** [comment]
@ahardin-rh , I will rebase PR's #19851, #19848 #19845 and #19844 after merging this one on top on it

**Review by ahardin-rh — APPROVED** [review]
LGTM. Thanks!

**Comment by ahardin-rh** [comment]
@dmvolod I cherrypicked this to the 4.3 and 4.4 branches, but please let me know if it needs backported further. Thanks again!

**Pull request merged**
