### PR TITLE
Added graph driver content to 4.0

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://jira.coreos.com/browse/OSDOCS-44

Preview Build: http://file.rdu.redhat.com/~ahardin/11272018/graph-drivers-4-0/storage/choosing-a-graph-driver.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jeremyeder @rhatdan @rhvgoyal Can you please review this content and let me know if it is still accurate for 4.0? Thank you!

**Comment by ahardin-rh** [comment]
@sjug I think you are now the assigned review for this section. I broke the graph driver content out into its own section.

**Comment by ahardin-rh** [comment]
Closing this PR after discussion with @jeremyeder and @sjug 
We're moving away from graph drivers. With CRI-O, there will be no choices in graph driver, it will only be overlay(2) and there will be no storage configuration.

**Comment by rhatdan** [comment]
I am not sure I would make that statement,  We might want to support multiple graphdrivers in the future for using Kata Containers since they work much better on devicemapper/lvm images then on overlay.  And for rootless containers we are using vfs storage.

**Comment by jeremyeder** [comment]
@rhatdan The content as-is addresses concerns that are 3+ years old, and largely irrelevant since defaulting to overlay.  Do you still prefer we keep it, and extend it to include your points above?  Thinking about it from a customer PoV, it strikes me that the existing content might be considered a distraction in the 4.0+ world (these docs would remain present in 3.11 and earlier branches).

**Comment by rhatdan** [comment]
No I don't mind removing it, I just want people to understand that the other graphdrivers are still important.

**Pull request closed without merging**
