### PR TITLE
CNV-31195_1: Doc: "View YAML & CLI" button

### PR DESCRIPTION
**Pull request by aspauldi**
Version(s): 4.14

Issue: [CNV-31195](https://issues.redhat.com/browse/CNV-31195)

Link to docs preview: [Creating a VM from an instance type](https://64708--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virt-creating-vms#virt-creating-vm-instancetype_virt-creating-vms)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by aspauldi** [comment]
@yfrimanm, can you please review the doc updates, specifically Steps 5 and 6? In Step 5, I changed Advanced Settings to Authorized SSH key, as that was what I saw in the UI. For Step 6, I added details about the new button. Let me know if you want me to embellish the viewing aspect that is new. Thanks.

**Comment by aspauldi** [comment]
From the Jira:

Audrey Spaulding added a comment - [Yesterday](https://issues.redhat.com/browse/CNV-31195?focusedId=23014425&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23014425) - edited

[yfrimanm](https://issues.redhat.com/secure/ViewProfile.jspa?name=yfrimanm), can you please review the [doc updates](https://github.com/openshift/openshift-docs/pull/64708), specifically Steps 5 and 6? In Step 5, I changed Advanced Settings to Authorized SSH key, as that was what I saw in the UI. For Step 6, I added details about the new button. Let me know if you want me to embellish the viewing aspect that is new. Thanks.
yfrimanm[ Yifat Menchik](https://issues.redhat.com/secure/ViewProfile.jspa?name=yfrimanm) added a comment - [43 minutes ago](https://issues.redhat.com/browse/CNV-31195?focusedId=23023706&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23023706)

Thanks [aspauldi](https://issues.redhat.com/secure/ViewProfile.jspa?name=aspauldi) LGTM

**Comment by aspauldi** [comment]
@lkladnit, Can you please review this doc update? Yifat has added a LGTM to the Jira issue. Thanks.

**Review by lkladnit — APPROVED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM, and I see the QE review from @lkladnit. Thank you!

**Pull request merged**
