### PR TITLE
Upgrading CAM (4.4)

### PR DESCRIPTION
**Pull request by apinnick**
https://bugzilla.redhat.com/show_bug.cgi?id=1844627

CP for 4.4 only

### CODE REVIEW

**Comment by XinRedhat** [comment]
this doc is missing Upgrading CAM on 3.x .

**Comment by apinnick** [comment]
@XinRedhat  The CAM on 3.x upgrade is here: https://cam-upgrade--ocpdocs.netlify.app/openshift-enterprise/latest/migration/migrating_3_4/deploying-cam-3-4.html#upgrading-cam-ocp-3_migrating-3-4

**Comment by XinRedhat** [comment]
For the CAM on 3.x upgrade 1.1.1 ->1.2.0, it misses manually restart the restic pods by deleting the restic pods. you can double confirm with @sseago

**Comment by XinRedhat** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@apinnick Before we review, can you confirm whether this is supposed to go to 4.5, or just 4.4?

If it's just 4.4, then this PR needs to be opened directly against the enterprise-4.4 branch and not master.

**Pull request closed without merging**
