### PR TITLE
Add atomic-registry distro

### PR DESCRIPTION
**Pull request by aweiteka**
This defines a new docs set (AsciiBinder distro) for
the Atomic Registry project. Another commit will provide
the necessary conditional topic building with an update
to _build_cfg.yml

### CODE REVIEW

**Comment by aweiteka** [comment]
@nhr this one's first

**Comment by nhr** [comment]
@adellape heads up on this. Want to make sure you know this is coming in; please ack.

**Comment by adellape** [comment]
:+1:

**Comment by nhr** [comment]
Solid; merging.

**Pull request merged**
