### PR TITLE
[OSDOCS-7362]: Document the EC2 Metadata HTTP Tokens Config

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-7362
Link to docs preview:

https://63857--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations#rosa-sts-creating-cluster-customizations-cli_rosa-sts-creating-a-cluster-with-customizations

image

QE review:
- [X ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @bchandra-ocp,
     Please review this PR when you get a chance.  As mentioned in this comment https://issues.redhat.com/browse/OSDOCS-7362?focusedId=22850822&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22850822, I upgraded to latest ROSA CLI and now able to see the desired output for the "EC2 Metadata HTTP Tokens" status. If you feel there is anywhere else this should be displayed/discussed in the docs besides where I have added it, please let me know. Don't think there is, but could have missed something. Thanks.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by bchandra-ocp** [comment]
lgtm

thanks!

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
