### PR TITLE
Fix navigation path in defining-template-for-external-log-link

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Review by ahardin-rh — APPROVED** [review]
Looks good to me. Thank you!

**Comment by ahardin-rh** [comment]
@vikram-redhat I was able to verify this with a 4.4 cluster. I don't think we need a formal QE review, but let me know if you think I should request one.

**Comment by ahardin-rh** [comment]
@dmvolod The only thing is that we will have to squash the 2 commits down to 1 commit per our workflow before we can merge this. Thanks again!

**Comment by dmvolod** [comment]
Thanks, @ahardin-rh. Please merge this PR with two commits, I will rebase another on top the first commit.

**Comment by dmvolod** [comment]
@dmvolod , done. Thanks.

**Pull request merged**
