### PR TITLE
OSDOCS-10749#preserveBootstrapIgnition update

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Version:
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10749

Link to docs preview:
https://77627--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-deprecated-removed-features_release-notes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@yunjiang29, Please review this release note.

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Pull request merged**
