### PR TITLE
OSDOCS-4490: Correct wrong bool type to string one in EFS static PV yaml example

### PR DESCRIPTION
**Pull request by bysnupy**
spec.csi.volumeAttributes are not allowed to configure the value with bool type, so correct it as string type in the yaml.

Version(s):

All versions supported the AWS EFS CSI operator.

Issue:

The sample happen unmarshal error and not created the PV.

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

* Reference: https://issues.redhat.com/browse/OSDOCS-4490

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@Phaow will you PTAL or suggest a different reviewer?

**Comment by Phaow** [comment]
LGTM
```
$ oc explain persistentvolume.spec.csi.volumeAttributes.encryptInTransit
KIND:     PersistentVolume
VERSION:  v1

FIELD:    encryptInTransit <string>

DESCRIPTION:
     <empty>
```
@ropatil010 @chao007  As EFS feature owner, could you please help take a look when you get a chance? Thanks!

**Comment by ropatil010** [comment]
/lgtm
Thanks @kalexand-rh @Phaow @chao007

**Comment by kalexand-rh** [comment]
@bysnupy, will you confirm which versions this change applies to?

**Pull request merged**
