### PR TITLE
Add the jenkinspipeline role

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by bfallonf** [comment]
@liggitt (repeating the same question from #3183 ) To which versions would this apply?

But big thanks for the PR!

**Comment by liggitt** [comment]
3.3/3.4

**Comment by bfallonf** [comment]
Thanks @liggitt . I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../admin_guide/securing_builds.adoc#admin-guide-securing-builds[Securing Builds by Strategy]
|Added `jenkinspipeline` build strategy role information.
%

**Pull request merged**
