### PR TITLE
Rename Fuse Integration Services to Fuse on OpenShift and update link to

### PR DESCRIPTION
**Pull request by apupier**
fuse doc #14050

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
it would be nice to report this change to 3.11 branch too

**Comment by kalexand-rh** [comment]
I don't see any other references to "Fuse Integration Services" that are included in the collection, so this LGTM. @vikram-redhat, will you PTAL?

**Comment by vikram-redhat** [comment]
Looks good. Merging.

**Pull request merged**
