### PR TITLE
[4.x] Rename OpenStack -> common attributes across docs

### LINKED ISSUE #22975: Verify RHOSP branding compliance across docs
### Which section(s) is the issue in?

All over the docs, including the Welcome page. 

### What needs fixing?

Where possible*, replace occurrences of "OpenStack" with {rh-openstack-first} or {rh-openstack}. 

* Excludes linked external pages, scripts, CLI output, etc. where replacements could result in confusion or breakage.

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR resolves #22975.

### CODE REVIEW

**Comment by maxwelldb** [comment]
Holding off on `modules/apis.adoc`, as I have no idea how it works. :)

**Comment by maxwelldb** [comment]
@openshift/team-documentation PTAL. Easy if tedious review. :)

**Review by bobfuru — COMMENTED** [review]
LGTM! OCP 4.1 is no longer supported so unless you had a specific reason in mind, you shouldn't need to CP there.

**Comment by maxwelldb** [comment]
@bobfuru Thanks!

**Comment by maxwelldb** [comment]
Just went on autopilot for 4.*. Won't bother CPing there.

**Comment by maxwelldb** [comment]
Quite manual, it is.

**Pull request merged**
