### PR TITLE
Add OSP to zero min autoscale clause - OSDOCS-1660

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR adds OSP to the list of platforms that support autoscaling from zero.

Docs ticket: https://issues.redhat.com/browse/OSDOCS-1660
Dev ticket: https://issues.redhat.com/browse/OSASINFRA-2141

FYI @adduarte

### CODE REVIEW

**Comment by maxwelldb** [comment]
Preview link: https://zero-scaling-osp-osdocs1660--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/applying-autoscaling.html#machine-autoscaler-cr_applying-autoscaling

**Comment by wjiangjay** [comment]
sorry for the delay, lgtm

**Comment by maxwelldb** [comment]
@openshift/team-documentation PTAL when you have a moment. TY!

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by maxwelldb** [comment]
@bergerhoffer Thanks!

**Pull request merged**
