### PR TITLE
OSDOCS-10612 Code error for customers

### PR DESCRIPTION
**Pull request by jmanthei**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-10612

Link to docs preview: https://76779--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/aws_load_balancer_operator/install-aws-load-balancer-operator.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jmanthei** [comment]
@alebedev87 and @ShudiLi for a qe check and to make sure I replaced the erroneous code properly. Thanks!

**Review by alebedev87 — APPROVED** [review]

**Comment by ShaunaDiaz** [comment]
@jmanthei Please confirm which version branches need the fix so it can be merged.

**Comment by jmanthei** [comment]
@ShaunaDiaz thank you so much

**Review by skopacz1 — APPROVED** [review]
merge review LGTM

**Pull request merged**
