### PR TITLE
[WIP] Removing Serverless docs for OCP 4.1

### PR DESCRIPTION
**Pull request by abrennan89**
Serverless no longer supports OCP 4.1 from 1.3.0 onwards. Removing all Serverless sections in docs.

### CODE REVIEW

**Comment by abrennan89** [comment]
@sheriff-rh do you know if we need to remove Serverless from the release notes for 4.1 if support for it is being removed?

**Review by kalexand-rh — COMMENTED** [review]
Vikram might argue that it's only necessary to remove the assemblies and to let the "unused modules" script prune the modules, but this LGTM.

**Comment by sheriff-rh** [comment]
> @sheriff-rh do you know if we need to remove Serverless from the release notes for 4.1 if support for it is being removed?

I think that's a good idea @abrennan89 ! Let me know if I can help!

**Comment by abrennan89** [comment]
@sheriff-rh this release is planned for 12/17 so it doesn't need to be removed until then :slightly_smiling_face: I can put in a PR for it or you can remove it if you're making changes to the release notes around then, whichever is easiest for you.

**Comment by abrennan89** [comment]
I've removed Serverless from the relnotes I think now: https://github.com/openshift/openshift-docs/pull/18310/files#diff-8eb40e5404d0c6ad14085893c9c2f789L776-L779

**Comment by abrennan89** [comment]
No longer required. Closing PR.
CC @sheriff-rh :)

**Pull request closed without merging**
