### PR TITLE
OSDOCS#8234: Docs for OSSO 1.0.2

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11 only

Issue:
https://issues.redhat.com/browse/OSDOCS-8234

Link to docs preview:
* 1.0.2 release: https://66403--docspreview.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes#secondary-scheduler-operator-release-notes-1.0.2
* Note added to 1.1.0: https://66403--docspreview.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes#secondary-scheduler-operator-release-notes-1.1.0

QE review:
- [ ] QE has approved this change.

Additional information:

**Advisory link will be live on 10/26**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @kasturinarra This is ready for review. What really needs reviewed closely is the warning that has been added to 1.1.0. This is what I need worked out asap so that I can send this through change management approvals before we can merge.

(The warning in 1.0.2 is similar wording, but not exactly).

Preview:
* 1.0.2 release: https://66403--docspreview.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes#secondary-scheduler-operator-release-notes-1.0.2
* Note added to 1.1.0: https://66403--docspreview.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes#secondary-scheduler-operator-release-notes-1.1.0

**Comment by kasturinarra** [comment]
@bergerhoffer looks good to me.

**Comment by ingvagabund** [comment]
Let's wait here until I get confirmation 4.11 does not have osso 1.0.1 release :( In which case we can drop 1.0.2 release completely.

**Comment by bergerhoffer** [comment]
Closing - this release was canceled

**Pull request closed without merging**
