### PR TITLE
OSDOCS-9798: adds GitOps release note 4.16

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.16

Issue:
[GitOps release note](https://issues.redhat.com/browse/OSDOCS-9798)

Link to docs preview:
[GitOps release note](https://73800--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-16-release-notes#microshift-4-16-gitops)

QE review:
- [x] QE has approved this change.

Additional information:
https://github.com/openshift/openshift-docs/pull/73201
https://github.com/openshift/openshift-docs/pull/72974

### CODE REVIEW

**Comment by ggiguash** [comment]
The wording is LGTM to me.

**Comment by ShaunaDiaz** [comment]
(QE will be next week.)

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by agullon — APPROVED** [review]
/lgtm

**Pull request merged**
