### PR TITLE
[enterprise-4.14] fix typo in registry url

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.12-4.14

Issue: n/a

Link to docs preview:

- https://85303--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/configuring-ipfailover.html#nw-ipfailover-configuration_configuring-ipfailover
- https://85303--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/configuring-ipfailover.html#nw-ipfailover-remove_configuring-ipfailover

QE review: n/a

Additional information:

### CODE REVIEW

**Comment by candita** [comment]
Thanks @jldohmann, and sorry for my initial typo.
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
