### PR TITLE
1893182 Removing line that doesn't appear in installer asking for DNS IP address.

### PR DESCRIPTION
**Pull request by stoobie**
https://bugzilla.redhat.com/show_bug.cgi?id=1893182
Applies to: 
enterprise-4.6
enterprise-4.7
enterprise-4.8

### CODE REVIEW

**Comment by bmcelvee** [comment]
The removal looks good on the PR, but the line is still showing up on the preview build (both Netify and local). I'm not clear on the modules for this content, but the section in this PR is _Deploying the cluster_ and the one in the build where this content is located is _Creating the installation configuration file_.

**Comment by stoobie** [comment]
@bmcelvee This change now targets two locations. You noticed one that I have now addressed (i.e. removed the step), and there's also one more location.
Here are the two locations:
1. https://deploy-preview-32189--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-default.html#installation-launching-installer_installing-rhv-default
(The line _was_ step "L").

2. https://deploy-preview-32189--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-customizations.html#installation-initializing_installing-rhv-customizations The line was step 1.b.vii.

**Comment by stoobie** [comment]
@bmcelvee  This has now been verified by QE and is ready to merge.

**Comment by stoobie** [comment]
The last push was to rebase the branch with latest changes to master.

**Comment by stoobie** [comment]
@bmcelvee Since this applies to 4.6 and 4.7 can this already be merged to those branches?

**Pull request merged**
