### PR TITLE
OSDOCS#10489: Move the Deleting a hosted cluster section

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OSDOCS-10489

Link to docs preview:

https://75621--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-getting-started.html

QE review:
- [x] QE has approved this change.

PM review:
- [x] PM has approved this change.

Additional information:

### CODE REVIEW

**Comment by zanetworker** [comment]
lgtm :)

**Comment by tmalove** [comment]
Hi @xenolinux your second preview link is not working. Will you correct this?

**Comment by xenolinux** [comment]
> Hi @xenolinux your second preview link is not working. Will you correct this?

Hi @tmalove The link will not work. As a part of this PR, I deleted that topic's entry from topic.yml file. But the preview can be verified by using the first link from comment 0
https://75621--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-getting-started.html

-- Removing second preview link as it won't work

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by jeana-redhat** [comment]
@xenolinux I will merge 4.16+, but it looks like you'll need to pick to 4.14 manually

**Pull request merged**
