### PR TITLE
OSDOCS-4878 Availability Zones Hyderabad

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-4878](https://issues.redhat.com//browse/OSDOCS-4878)

Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-4878

Link to docs preview:
OSD: https://56175--docspreview.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#regions-availability-zones_osd-service-definition
ROSA: https://56175--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-regions-az_rosa-service-definition

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @xueli181114 and @yuwang-RH! Can one of you please review this PR when you have the chance? I know the region isn't available yet, but I want to get the docs review and ready for release as soon as the region is live. Thanks!

**Comment by xueli181114** [comment]
This region is not enabled in CMS. [Aaren de Jong](https://issues.redhat.com/secure/ViewProfile.jspa?name=rh-ee-adejong) would you please double confirm if the doc update is expected for now?

ID                NAME                        MULTI-AZ SUPPORT    HOSTED-CP SUPPORT

af-south-1        Africa (Cape Town)          true                false

ap-east-1         Asia Pacific (Hong Kong)    true                false

ap-northeast-1    Asia Pacific, Tokyo         true                false

ap-northeast-2    Asia Pacific, Seoul         true                false

ap-northeast-3    Asia Pacific (Osaka)        true                false

ap-south-1        Asia Pacific, Mumbai        true                false

ap-southeast-1    Asia Pacific, Singapore     true                false

ap-southeast-2    Asia Pacific, Sydney        true                false

ap-southeast-3    Asia Pacific, Jakarta       true                false

ap-southeast-4    Asia Pacific, Melbourne     true                false

ca-central-1      Canada, Central             true                false

eu-central-1      EU, Frankfurt               true                false

eu-north-1        EU, Stockholm               true                false

eu-south-1        Europe (Milan)              true                false

eu-west-1         EU, Ireland                 true                true

eu-west-2         EU, London                  true                false

eu-west-3         EU, Paris                   true                false

me-south-1        Middle East, Bahrain        true                false

sa-east-1         South America, São Paulo    true                false

us-east-1         US East, N. Virginia        true                false

us-east-2         US East, Ohio               true                true

us-west-1         US West, N. California      false               false

us-west-2         US West, Oregon             true                true

**Comment by arendej** [comment]
This region will be available later

**Comment by jneczypor** [comment]
Hi @arendej! Can I get a quick PM review of this availability zone? I will then get it to QE and hold it until it is available. Thanks so much!

**Review by arendej — COMMENTED** [review]
Hyderabad is an opt-in region

**Comment by jneczypor** [comment]
Hi @arendej! I have fixed the region to "opt-in". Can I please have your stamp of approval? Thanks!

**Review by arendej — APPROVED** [review]
lgtm (please note to hold publishing until the region is available)

**Comment by jneczypor** [comment]
Hi @xueli181114 and @yuwang-RH. Can I please get QE review so this can be published? Thanks so much!

**Review by eldar101 — APPROVED** [review]
/LGTM

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by jab-rh** [comment]
@arendej, is the region available? If not, is there a timeline? Thanks!

**Comment by jneczypor** [comment]
Hi @jab-rh - Would the comment that Aaren published on the JIRA ticket three days ago (https://issues.redhat.com/browse/OSDOCS-4878) work for confirmation? Thanks so much!

**Comment by arendej** [comment]
There should be no further hold-ups on this. The region is live and usable. I built a cluster in the region last Friday.

**Pull request merged**
