### PR TITLE
OSDOCS-6293: Added overriding default IP section for SDN migration

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.14

Issue: [OSDOCS-6293](https://issues.redhat.com/browse/OSDOCS-6293)

Link to docs preview: https://61208--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#considerations-migrating-ovn-kubernetes-network-provider_migrate-from-openshift-sdn

QE review:
- [ ] QE has approved this change. @weliang1 can you please review this?
- [x] SME has approved this change.  @pliurh

### CODE REVIEW

**Comment by pliurh** [comment]
LGTM

**Comment by weliang1** [comment]
@pliurh For https://issues.redhat.com/browse/NP-687:  Multiple NICs support with OVN plugin in the UPI environment, the migration script will automatically overriding default IP section, and users do not need manually edit /etc/default/nodeip-configuration. Please confirm my understanding is correct.

**Comment by pliurh** [comment]
@weliang1 manually editing /etc/default/nodeip-configuration is for overriding the default NodeIP selection logic. A user shall only use this process when the default logic cannot pick the right NodeIP. For example, he wants to use the IP which is not to the default route of the host; or there is no default route in the host.

**Comment by weliang1** [comment]
Steps 1 to 5 in this docs should be done before deploying the cluster. And https://issues.redhat.com/browse/OCPBUGS-4963 is opened for the compent of 
Machine Config Operator / platform-vsphere, I do not think those procedures are related to SDN migration process. 
@rioliu-rh @jianzhangbjz , could you help to review this PR as you verified OCPBUGS-4963?

For SDN2OVN migration testing itself, it passed in vshper cluster with Multiple NICs (https://issues.redhat.com/browse/OSDOCS-6293)

**Comment by pliurh** [comment]
@weliang1 Yes, I think you're right. The `nodeip-configuration-vsphere-upi.service` shall be able to ensure we have the same node IP for the node before and after the migration.

**Comment by snarayan-redhat** [comment]
Changes not required anymore. Hence closing the PR.

**Pull request closed without merging**
