### PR TITLE
Add new sys req for hypervisors: do not overcommit

### PR DESCRIPTION
**Pull request by DanielFroehlich**
Proposed fix for #13046

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@sdodson, thoughts?

**Comment by kalexand-rh** [comment]
@sdodson, will you PTAL?

**Comment by sdodson** [comment]
/cc @openshift/sig-pod 

I mean, it's all correct, but I wonder if we really need to state this? Pod team is probably best team to provide any additional feedback.

**Review by sdodson — APPROVED** [review]

**Comment by sjenning** [comment]
Yeah, I would think this was understood.

Anyone overcommitting their hypervisors in terms of memory is asking for it.  Overcommitting on CPU would have roughly the same effect as... running on a slower processor (increased scheduling latency and whatnot).

Moreover most people creating virtual machines don't have control off the overcommit policies on the hypervisor.  I'm not sure we need to document this.

**Comment by DanielFroehlich** [comment]
I agree that this is kind of obvious if you think about it. But I had the
discussion with a customer, needed to explain the topic several times and
was then asked "ok, but where is this stated in the documentation?"  Hence
this pull request.

---
Sent from mobile, please excuse typos. Daniel.Froehlich@redhat.com, +49 176
10 24 84 33

Am Do., 24. Jan. 2019, 20:53 hat Seth Jennings <notifications@github.com>
geschrieben:

**Comment by kalexand-rh** [comment]
Scott and I had a chat about this one, and we think that it makes more sense to change https://docs.openshift.com/container-platform/3.11/scaling_performance/optimizing_compute_resources.html to say:
> You can use overcommit procedures so that resources such as CPU and memory are more accessible to the parts of your cluster that need them.
>**IMPORTANT**
>To avoid erratic cluster behavior due to scheduling collisions between the hypervisor and Kubernetes, do not overcommit at the hypervisor level.

**Comment by kalexand-rh** [comment]
Great! I made a new PR with that change: https://github.com/openshift/openshift-docs/pull/13427 Since everyone's in agreement, I'll close this PR and merge it and cherry-pick the new one back to 3.6.

**Pull request closed without merging**
