### PR TITLE
bz 1799055: cnv namespace is automatically created

### PR DESCRIPTION
**Pull request by ousleyp**
- bug: https://bugzilla.redhat.com/show_bug.cgi?id=1799055 (not a doc bug)
- for enterprise-4.4/cnv-2.3 only
- preview: https://auto-namespace--ocpdocs.netlify.com/openshift-enterprise/latest/cnv/cnv_install/installing-container-native-virtualization.html

@alexxa and @aburdenthehand PTAL?

### CODE REVIEW

**Review by alexxa — CHANGES_REQUESTED** [review]
image

@ousleyp A user doesn't need to do actions 5a and 5b. Those are already selected when "Create Operator Subscription" window is opened. Also remove the warning "All namespaces on the cluster (default) ... <..>" Thanks!

**Comment by alexxa** [comment]
to clear: "All namespaces" option is grayed out. One can't click it at all.

**Comment by ousleyp** [comment]
> image
> 
> @ousleyp A user doesn't need to do actions 5a and 5b. Those are already selected when "Create Operator Subscription" window is opened. Also remove the warning "All namespaces on the cluster (default) ... <..>" Thanks!

Thanks @alexxa, I didn't realize that. I made the change and updated the preview build: http://file.bos.redhat.com/pousley/022820/auto-namespace/cnv/cnv_install/installing-container-native-virtualization.html

For 5b, I changed it to "Ensure that.." because it looks like the other option is not greyed out for that step. Let me know what you think. Thanks!

**Comment by aburdenthehand** [comment]
lgtm

**Review by alexxa — CHANGES_REQUESTED** [review]
@ousleyp Keep it open please. There will be a couple of code PRs for a line "Pick an exisiting namespace" in that window. I will update you when I know more, thanks.

**Comment by alexxa** [comment]
@ousleyp please see jira cnv-4259, there is a warning line to add.
Also, update the tab name: "KubeVirt HyperConverged Cluster Operator Deployment" to "CNV Operator Deployment", in install and uninstall sections. 
Then, it all should be ready for merge. Thanks.

**Comment by ousleyp** [comment]
> @ousleyp please see jira cnv-4259, there is a warning line to add.

I responded on the Jira; I don't think it makes sense to add this to this PR.

> Also, update the tab name: "KubeVirt HyperConverged Cluster Operator Deployment" to "CNV Operator Deployment", in install and uninstall sections.
> Then, it all should be ready for merge. Thanks.

I will make this change - thanks for letting me know!

**Comment by ousleyp** [comment]
@alexxa Can you please check my latest commit (https://github.com/openshift/openshift-docs/pull/20118/commits/90475bdc4110b4d963486f2c0b1354e5dbc71024) to make sure I changed the right instances of KubeVirt HyperConverged Cluster Operator Deployment? I changed the custom resource name as well as the tab name, so let me know if that wasn't right. Thanks!

**Comment by alexxa** [comment]
@ousleyp yes, looks good, thanks

**Review by alexxa — APPROVED** [review]

**Pull request merged**
