### PR TITLE
OSDOCS-6824: Adds notes for 4.12.24 MS release

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-6824

Link to docs preview:
https://62178--docspreview.netlify.app/microshift/latest/microshift_release_notes/microshift-4-12-release-notes.html#microshift-4-12-24-dp

QE review:
N/A

NOTE: DO NOT MERGE until after 7/12/23 z-stream release.

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @ShaunaDiaz ...looks good. As a reminder, squash the commits before you merge on the 12th...thanks!

/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Comment by ShaunaDiaz** [comment]
@JoeAldinger MicroS relnote ready when the release is.

**Comment by JoeAldinger** [comment]
Requested merge via slack.

**Pull request merged**
