### PR TITLE
cnv, relocate higher workload density to post-installation

### PR DESCRIPTION
**Pull request by fabiand**
Today configuring a higher workload density is located under adavanced vm management, however configuring a higher workload density is a cluster post-installation task.

This chane is moving higher density from Adv. VM section to the post-installation section.

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by fabiand** [comment]
@ctomasko @sbeskin-redhat please review.

**Comment by fabiand** [comment]
cc @enp0s3

**Comment by ctomasko** [comment]
@fabiand @sbeskin-redhat lgtm. Sasha, please confirm. Thank you

**Comment by sbeskin-redhat** [comment]
lgtm
Replaced by another [PR](https://github.com/openshift/openshift-docs/pull/80340) for further handling

**Pull request merged**
