### PR TITLE
OSDOCS-6773: Bug fix oc v kubectl

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13, 4.14

Issue:
https://issues.redhat.com/browse/OCPBUGS-15903

Link to docs preview:
https://62206--docspreview.netlify.app/microshift/latest/microshift_getting_started/microshift-architecture.html#microshift-k8s-apis_microshift-architecture

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
Hi @ShaunaDiaz Just a reminder to get QE ack before the merge review request, otherwise looks good!
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Comment by bscott-rh** [comment]
Merged and cherrypicked to 4.13 and 4.14

**Pull request merged**
