### PR TITLE
Extract doc_site_builder into a gem.

### PR DESCRIPTION
**Pull request by Fryguy**
@nhr This PR extracts the guts into a gem.  Note that, for now, I just created a repo in my personal Github account, and reference it via the Gemfile with `:git =>`.  However, before merging, we should make it a real published gem with it's own dedicated repo.  So, we need to decide where this gem lives, what to name it, and I'll need your email address associated with rubygems.org to make you an owner of the gem (you can PM me with it)

Some possible options:
- http://github.com/docsitebuilder/doc_site_builder
- http://github.com/doc-site-builder/doc_site_builder
- http://github.com/openshift/doc_site_builder

It's too bad Red Hat doesn't have their own organization on GitHub. :confused:

### CODE REVIEW

**Comment by Fryguy** [comment]
@nhr I've published the [doc_site_builder gem](), including the changes you did since I opened my PR, and I've updated this PR, so it should be good to go.

As an aside, I've been trying to create basic templates for the manageiq_docs projects, but a LOT of the css is in https://assets.openshift.net/content/subdomain.css , which I'd rather not reference.  Unfortunately that guy has both css for the top nav bar (which we don't want), but also the nav and font-awesome stuff (which we DO want).  Is there any way that stuff can be split up or partially put into the doc_site_builder repo?

**Comment by Fryguy** [comment]
@nhr Also, in order to make you an owner of the gem so you can push new versions, you'll have to sign up for rubygems.org and send me the email address that you sign up with.

**Comment by nhr** [comment]
@Fryguy I think the best option for dealing with `subdomains.css` is probably to just pull the whole thing into `openshift_docs` under the `_templates` and to deploy it locally. That way you can have a same-named file in your docs repo that gets picked up by the builder.

**Comment by Fryguy** [comment]
Yeah that's basically what I did with manageiq_docs, but there's also some content files that are referenced via url...was hard to undo.

Who "owns" the subdomain.css?  Is that part of this project specifically, or is that shared amongst other openshift sites?

**Comment by nhr** [comment]
@spurtell or @Nick-Harvey can you comment on this? I think that one or both of you was involved in making subdomains.css?

**Comment by spurtell** [comment]
subdomains.css is hosted on our assets server and is meant to standardize certain style elements across openshift.com subdomains (and make them easier to change).

**Comment by nhr** [comment]
Okay - is there any way to rebuild subdomains.css without the top nav bar for @Fryguy 's use? We would not need to host it; he and I would figure out a way to serve it alongside the docs content for his projects.

**Comment by spurtell** [comment]
@Fryguy can break it up/use it in whatever way makes sense

**Comment by Fryguy** [comment]
@nhr Updated...I did not handle the subdomains.css thing yet, but I think I can do that in a separate PR on the doc_site_builder gem side

**Comment by nhr** [comment]
Looks good. Jenkins is prepped, so we'll cut over.

**Pull request merged**
