### PR TITLE
[OSDOCS-10073]Update documentation: Expose cluster delete protection feature (ROSA CLI)

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10073
Link to docs preview:

Managing objects with the ROSA CLI
https://73962--ocpdocs-pr.netlify.app/openshift-rosa/latest/cli_reference/rosa_cli/rosa-manage-objects-cli#rosa-edit-cluster_rosa-managing-objects-cli

https://73962--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-deleting-cluster#additional-resources_rosa-sts-deleting-cluster
QE review:
- [x] QE has approved this change.

Additional information:

image
image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @yuwang-RH, Can I get a QE review on this PR? Thanks!

**Comment by jfrazierRH** [comment]
Doc changes LGTM

**Comment by aldiazRH** [comment]
LGTM!

**Comment by mletalie** [comment]
Waiting on feature to go live. Scheduled for last week in April.

**Pull request merged**
