### PR TITLE
Update eventing structure for OCP 4.4 to sync with master

### PR DESCRIPTION
**Pull request by abrennan89**

### CODE REVIEW

**Comment by abrennan89** [comment]
Added request for link redirects in sheet.

**Comment by jboxman** [comment]
@abrennan89, LGTM.

**Comment by abrennan89** [comment]
Thanks @jboxman ! Could you merge this please when you have a chance? Thanks :slightly_smiling_face:

**Comment by jboxman** [comment]
@abrennan89, done!

**Pull request merged**
