### PR TITLE
OSDOCS-3160: NFD Update version in examples for next release

### PR DESCRIPTION
**Pull request by kmccarron-rh**
https://issues.redhat.com/browse/OSDOCS-3160
Applies to 4.10+

Preview is [here](https://deploy-preview-40513--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-node-feature-discovery-operator.html#install-operator-cli_node-feature-discovery-operator).

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
PTAL please:
@ArangoGutierrez 
@lenahorsley and/or @wabouhamad

**Comment by kmccarron-rh** [comment]
Carlos agreed with the change in a Slack thread.

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM merging!

**Pull request merged**
