### PR TITLE
BZ2021367: Change 'than' to 'that'

### PR DESCRIPTION
**Pull request by jldohmann**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2021367

OCP version: 4.9

Current 4.9 doc: https://docs.openshift.com/container-platform/4.9/networking/ingress-operator.html#nw-customize-ingress-error-pages_configuring-ingress

Direct doc preview link: https://deploy-preview-39372--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator#nw-customize-ingress-error-pages_configuring-ingress

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
lgtm!
Minor nit on the PR title. The format per the docs manual:
BZ<BZ ID>: <Short description of your PR>

**Comment by lpettyjo** [comment]
Peer review: LGTM. Changed title format.

**Comment by jldohmann** [comment]
While cherrypicking, I realize I made a mistake: this is just a change for 4.9. Apologies for the confusion!

**Comment by kmccarron-rh** [comment]
@lpettyjo - Will you remove the 4.6-4.8 labels please? Turns out this is a 4.9+ change

**Comment by lpettyjo** [comment]
Removed 4.6-4.8 labels. Looks like CPing is OK, since only 4.9 and 4.10 succeeded.

**Pull request merged**
