### PR TITLE
Syncing file with main, to resolve mismatched conditionals

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.13

Issue:

Link to docs preview:

* OCP: https://57153--docspreview.netlify.app/openshift-enterprise/latest/welcome/index.html
* ROSA: https://57153--docspreview.netlify.app/openshift-rosa/latest/welcome/index.html
* Dedicated: https://57153--docspreview.netlify.app/openshift-dedicated/latest/welcome/index.html
* Microshift: https://57153--docspreview.netlify.app/microshift/latest/welcome/index.html

QE review:
No QE required

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
I believe this is needed to close the ifndef:openshift-rosa on line 24:

https://github.com/openshift/openshift-docs/pull/57153/files#diff-40d72ccc658b0f56a1a01387cffdf2a793c5cd21234a0fcbfcc25cf880d318c5R24

**Comment by bergerhoffer** [comment]
@ShaunaDiaz @bmcelvee Can you both please peer review to make sure that this is the right solution for the difference in this line between main and enterprise-4.13?

Preview links are in the first comment

**Comment by bmcelvee** [comment]
LGTM! Thank you, @bergerhoffer!

**Comment by ShaunaDiaz** [comment]
LGTM also. Thanks, @bergerhoffer!

**Pull request merged**
