### PR TITLE
Fix typos for variables where OpenShift is used (fix case to be consi…

### PR DESCRIPTION
**Pull request by novacain1**
…stent with rest of documentation), enhance readability for ansible hosts file.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@qinpingli, will you PTAL or suggest a different reviewer for this 3.x SDN config change? I'm also curious which versions this change applies to.

**Comment by qinpingli** [comment]
@gpei @zhaozhanqi Could you help review this PR, thank you!

**Comment by zhaozhanqi** [comment]
this changes LGTM

**Comment by gpei** [comment]
LGTM

**Pull request merged**
