### PR TITLE
Revert "OADP-4439: Release Notes for 1.3.3 and Version updates"

### PR DESCRIPTION
**Pull request by anarnold97**
This PR needs to be reverted from `main`

It was included in `main` by mistake

The changes should be backed out of `main`

See for reference - https://access.redhat.com/support/policy/updates/openshift_operators
|Version | Tier | OpenShift Version |  General availability | Full support ends | Maintenance ends | EUS ends |
| ---------- | ---------- | ---------- |  ---------- | ---------- | ---------- | ---------- |  
| 1.3 |  Platform Agnostic  | 4.12, 4.13, 4.14, 4.15 | 29 Nov 2023 | 10 Jul 2024 |Release of 1.5 | N/A |

### CODE REVIEW

**Comment by anarnold97** [comment]
/label merge-review-needed as per Andrea Hoffer: "great. could you please submit a revert for that PR then against main?
you can use the "Revert" button and it will open a new PR that you can submit for merge review (and just add a comment on why it needs to be reverted, just from main"
:+1:
1

**Comment by bergerhoffer** [comment]
Reverts #78942 just from main (since the PR only applies up to 4.15.

**Comment by anarnold97** [comment]
@bergerhoffer -thanks

**Review by bergerhoffer — COMMENTED** [review]
LGTM to revert from main only.

**Pull request merged**
