### PR TITLE
BZ1978291: Updating QoS language to pod-centric vs container-centric.

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.8+

Issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1978291

Link to docs preview:

https://51716--docspreview.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-overcommit-qos-about_nodes-cluster-overcommit
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by djuran** [comment]
lgtm

**Comment by skrthomas** [comment]
@sunilcio can  you PTAL at this PR and let me know if you have any feedback. Thank you :) 🙏

**Comment by jboxman-rh** [comment]
@skrthomas, LGTM, thanks!

**Pull request merged**
