### PR TITLE
bug 1755358 fixing hyperthreading instance types

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://bugzilla.redhat.com/show_bug.cgi?id=1755358

@wmengRH, @e-tienne, will you PTAL?

@abhinavdahiya, @wking, are the instance types that I've picked fair for hyperthreading?

### CODE REVIEW

**Comment by wmengRH** [comment]
LGTM for GCP part

**Comment by e-tienne** [comment]
LGTM

**Comment by kalexand-rh** [comment]
Thanks! I'm going to merge.

**Pull request merged**
