### PR TITLE
CNV-3458: Removing various redundant virt template modules and references to them

### PR DESCRIPTION
**Pull request by danielclowers**
**Version(s):**
4.9+

**Issue:**
https://issues.redhat.com/browse/CNV-3458

**Link to docs preview:**
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-expanding-virtual-storage-with-blank-disk-images.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/logging_events_monitoring/virt-monitoring-vm-health.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/advanced_vm_management/virt-configuring-pxe-booting.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-datavolume.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/cloning_vms/virt-cloning-vm-using-datavolumetemplate.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.html
* https://56028--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-expanding-virtual-storage-with-blank-disk-images.html

**QE review:**
- [x] QE has approved this change.

**Additional information:**
N/A

### CODE REVIEW

**Review by kgoldbla — COMMENTED** [review]
lgtm

**Review by sjhala-ccs — COMMENTED** [review]
@danielclowers LGTM. No need to back port changes to 4.8. Let me know if you need help resolving the merge conflict.

**Pull request merged**
