### PR TITLE
Update configuring-firewall.adoc

### PR DESCRIPTION
**Pull request by Rupesh-git-eng**
The domain cdn03.quay.io doesn't exist in dns, if so, we should remove it. I tried a couple of DNS servers from different geo's.

Version(s):
Openshift 4.7 onwards. 

Issue:
We have a domain name link that doesn't really exist. 

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@gpei, will you PTAL or suggest another reviewer?

**Comment by gpei** [comment]
LGTM, thanks for the update.

**Comment by kalexand-rh** [comment]
@Rupesh-git-eng, the note is different in version 4.10 and earlier. Please confirm that this entire change is valid in 4.7 - 4.10.

**Comment by Rupesh-git-eng** [comment]
> @Rupesh-git-eng, the note is different in version 4.10 and earlier. Please confirm that this entire change is valid in 4.7 - 4.10.

@kalexand-rh in both cases, I believe it still applies as the specific record 'cdn03.quay.io' doesn't exist. Both versions have the same sub domain that is not configured yet.

**Comment by bergerhoffer** [comment]
@kalexand-rh If this still needs to be CPd to 4.8+, can you please look into it when you get a chance?

**Pull request merged**
