### PR TITLE
Fixing etcd backup steps

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://bugzilla.redhat.com/show_bug.cgi?id=1835196

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@geliu2016 Here is the update for the 3.11 etcd backup procedure that we talked about last week. Would you be able to run through this to be sure that we only need those 3 steps now?

And just a question in there on whether we need to note to save the snapshot.db file `/var/lib/etcd`? There was a note from a previous step that said it did, but I wasn't sure if it was also the case for these second set of steps.

Preview: http://file.rdu.redhat.com/~ahoffer/2020/BZ-1835196-2/day_two_guide/environment_backup.html#etcd-data-backup_environment-backup

@hexfusion @retroflexer In case either of you can review this as well.

**Review by bobfuru — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@geliu2016 Can you please review?

**Comment by geliu2016** [comment]
@bergerhoffer Tried it with latest 3.11(openshift v3.11.250 kubernetes v1.11.0+d4cacc0),

on master node execute below command:

[root@qe-rhoar-master-etcd-nfs-1 ~]# etcdctl3 --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt  --endpoints master-api-qe-rhoar-master-etcd-nfs-1  snapshot save /var/lib/etcd/snapshot.db
Snapshot saved at /var/lib/etcd/snapshot.db

[root@qe-rhoar-master-etcd-nfs-1 ~]# ls  /var/lib/etcd/
member  snapshot.db

and etcdctl command is not exist on master node:

[root@qe-rhoar-master-etcd-nfs-1 ~]#  ETCDCTL_API=3 etcdctl 
bash: etcdctl: command not found
[root@qe-rhoar-master-etcd-nfs-1 ~]# etcdctl
bash: etcdctl: command not found

and regarding etcd pod, there is not etcdctl command on etcd pod, so below command can't work in etcd pod:

$ oc project kube-system
$ oc exec ${ETCD_POD} -c etcd -- /bin/bash -c "ETCDCTL_API=3 etcdctl \   ==> will fail for etcdctl is not exist.

**Comment by bergerhoffer** [comment]
Hi @geliu2016. I just ran the exact steps listed in my PR here on a 3.11 cluster from quicklab, and it seems to have succeeded. So I'm not sure what issues you're seeing. Here is my output:

```
[root@master-0 etcd]# export ETCD_POD_MANIFEST="/etc/origin/node/pods/etcd.yaml"
[root@master-0 etcd]# export ETCD_EP=$(grep https ${ETCD_POD_MANIFEST} | cut -d '/' -f3)
[root@master-0 etcd]# oc login -u system:admin
Logged into "https://openshift.internal.ahofferjuly29.lab.upshift.rdu2.redhat.com:443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-service-catalog
    kube-system
    management-infra
    openshift
    openshift-ansible-service-broker
    openshift-console
    openshift-infra
    openshift-logging
    openshift-monitoring
    openshift-node
    openshift-sdn
    openshift-template-service-broker
    openshift-web-console

Using project "default".
[root@master-0 etcd]# export ETCD_POD=$(oc get pods -n kube-system | grep -o -m 1 '\S*etcd\S*')
[root@master-0 etcd]# echo $ETCD_POD
master-etcd-master-0.ahofferjuly29.lab.upshift.rdu2.redhat.com
[root@master-0 etcd]# oc project kube-system
Now using project "kube-system" on server "https://openshift.internal.ahofferjuly29.lab.upshift.rdu2.redhat.com:443".
[root@master-0 etcd]# oc exec ${ETCD_POD} -c etcd -- /bin/bash -c "ETCDCTL_API=3 etcdctl \
>     --cert /etc/etcd/peer.crt \
>     --key /etc/etcd/peer.key \
>     --cacert /etc/etcd/ca.crt \
>     --endpoints $ETCD_EP \
>     snapshot save /var/lib/etcd/snapshot.db"
Snapshot saved at /var/lib/etcd/snapshot.db
[root@master-0 etcd]# ls /var/lib/etcd/
member  snapshot.db
[root@master-0 etcd]# ls -la /var/lib/etcd/
total 47476
drwx------.  3 root root       64 Jul 29 12:06 .
drwxr-xr-x. 43 root root     4096 Jul 29 09:12 ..
drwx------.  4 root root       29 Jul 29 11:15 member
-rw-r--r--.  1 root root 24301600 Jul 29 12:06 snapshot.db
[root@master-0 etcd]# oc version
oc v3.11.248
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift.internal.ahofferjuly29.lab.upshift.rdu2.redhat.com:443
openshift v3.11.248
kubernetes v1.11.0+d4cacc0
[root@master-0 etcd]# 
```

I don't see just `etcdctl` on the master node, but I do see etcdctl2 and etcdctl3. Though it doesn't look like we run these etcdctl commands at all on the master node. It's executing the command in the etcd pod. I'm not 100% sure on how to check that etcdctl is on the pod, but I did `oc rsh` into the pod name (from $ETCD_POD) and it looks like it is there:

```
[root@master-0 etcd]# oc rsh master-etcd-master-0.ahofferjuly29.lab.upshift.rdu2.redhat.com
sh-4.2# etcd // Pressed tab here
etcd         etcd-env.sh  etcdctl 
```

So can you take another look? Or let me know if there's something that I'm misunderstanding or doing incorrectly? Thanks!

**Comment by geliu2016** [comment]
Yes, I'm not notice the prequisite: _etcdctl binaries must be available or, in containerized installations, the rhel7/etcd container must be available._
LGTM,thanks

**Comment by retroflexer** [comment]
The change here looks alright, although, it appears the restore expects the path to be different. The entire backup procedure appears to have steps mushed together from two different procedures. But that overhaul can happen in a different PR. 

As far as the original intent of this PR, it appears good to me. LGTM.

**Pull request merged**
