### PR TITLE
Adding note about future removal of custom scheduler docs

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-3367

Preview: https://deploy-preview-44667--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@gauravsingh85 @ingvagabund @kasturinarra We talked in https://issues.redhat.com/browse/OSDOCS-3367 about adding a note in the SSO docs for 4.10 mentioning that we'll be removing the docs for deploying a custom scheduler using the old method in 4.11. 

Can you please review this wording and let me know what you think?

Preview: https://deploy-preview-44667--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ingvagabund** [comment]
LGTM

**Comment by kasturinarra** [comment]
@ingvagabund does this mean QE does not need to perform any validation in 4.11 for custom scheduler ? could you please help confirm ? thanks!!

**Comment by ingvagabund** [comment]
Is there anything to validate?

**Comment by kasturinarra** [comment]
> Is there anything to validate?

We have been validating custom scheduler till 4.10 and i plan to continue validating the same for 4.11 as well but if we are removing the customscheduler doc content from here then and dropping the support then it simply implies we do not need to validate it going forward right ?

**Comment by ingvagabund** [comment]
Yes, we no longer need to do the validation since the secondary-scheduler-operator itself validates the procedure still works.

**Pull request merged**
