### PR TITLE
Follow-up to PR#1800, Unit for ES_RAM not specified and default is incorrect

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/1800

### CODE REVIEW

**Comment by adellape** [comment]
@ahardin-rh LGTM per https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/README.md#run-the-deployer

**Comment by ahardin-rh** [comment]
@sosiouxme PTAL Thanks!

**Comment by sosiouxme** [comment]
LGTM

**Comment by ahardin-rh** [comment]
@sosiouxme @adellape Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#deploying-the-efk-stack[Aggregating Container Logs]
|Specified the correct units for `*ES_INSTANCE_RAM*` and `*ES_OPS_INSTANCE_RAM*`.
%

**Pull request merged**
