### PR TITLE
OBSDOCS-1472: Prepare Enabling monitoring for user-defined projects f…

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s) for cherry-picking: none

Issue: [OBSDOCS-1472](https://issues.redhat.com/browse/OBSDOCS-1472)

Link to docs preview:  no preview necessary

QE review:
- [x] QE has approved this change.

**Additional information:**

### CODE REVIEW

**Comment by juzhao** [comment]
https://84580--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/enabling-monitoring-for-user-defined-projects.html
there are two same headers `Enabling monitoring for user-defined projects`, I think we could remove the second one, WDYT?

found it's the same for 4.17 released doc: https://docs.openshift.com/container-platform/4.17/observability/monitoring/enabling-monitoring-for-user-defined-projects.html

**Comment by eromanova97** [comment]
> https://84580--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/enabling-monitoring-for-user-defined-projects.html there are two same headers `Enabling monitoring for user-defined projects`, I think we could remove the second one, WDYT?
> 
> found it's the same for 4.17 released doc: https://docs.openshift.com/container-platform/4.17/observability/monitoring/enabling-monitoring-for-user-defined-projects.html

@juzhao Oh yes, I actually don't like it either. The problem here is that the first one is the name of the whole file while the second one is the name of the actual procedure involved. Both titles must be there due to our doc rules and the way they are structured.  

So the only thing that can be done here is to rename them. The procedure being called "Enabling monitoring for user-defined projects" makes sense.  However, the whole chapter being called the same makes sense as well. 
Honestly, I could not come up with the possible replacement title :sweat: 

It is not wrong to have it as it is currently, but if you have any ideas, let me know

**Comment by juzhao** [comment]
> > https://84580--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/enabling-monitoring-for-user-defined-projects.html there are two same headers `Enabling monitoring for user-defined projects`, I think we could remove the second one, WDYT?
> > found it's the same for 4.17 released doc: https://docs.openshift.com/container-platform/4.17/observability/monitoring/enabling-monitoring-for-user-defined-projects.html
> 
> @juzhao Oh yes, I actually don't like it either. The problem here is that the first one is the name of the whole file while the second one is the name of the actual procedure involved. Both titles must be there due to our doc rules and the way they are structured.
> 
> So the only thing that can be done here is to rename them. The procedure being called "Enabling monitoring for user-defined projects" makes sense. However, the whole chapter being called the same makes sense as well. Honestly, I could not come up with the possible replacement title 😓
> 
> It is not wrong to have it as it is currently, but if you have any ideas, let me know

keep it is fine, maybe others have an idea for it.
/lgtm

**Review by skopacz1 — APPROVED** [review]
LGTM

**Review by maxwelldb — APPROVED** [review]
Seems fine to me. @eromanova97 Can you confirm the merge target for this?

**Comment by eromanova97** [comment]
Hello @maxwelldb it only goes to the branch against which it is raised (`monitoring-docs-restructure`) so it needs no chery-picking, just merging. Thank you!

**Pull request merged**
