### PR TITLE
Change info for options field

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up to https://github.com/openshift/openshift-docs/issues/9921.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@liangxia Please provide QE review. Thanks.

**Comment by liangxia** [comment]
LG

**Comment by tmorriso-rh** [comment]
@vikram-redhat There are 2 commits here. The correct commit is "Change info for options field".

**Comment by vikram-redhat** [comment]
@tmorriso-rh - this is in master. Only if it were to be CP'ed to 3.9 would it appear in 3.9 docs. But, as you mention, you have reverted it with 10657, so it won't appear in master/origin docs either.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Thanks. So, do I need to open a new PR to get these changes made?

**Comment by vikram-redhat** [comment]
@tmorriso-rh no - just need to CP it to enterprise 3.9 and 3.10 branches as normal to get it into the 3.9 and 3.10 docs. To get it into the master branch revert the revert commit 10657.

**Comment by tmorriso-rh** [comment]
@vikram-redhat CP using which commit ID? The "Change info for options field" commit did not pass the build.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Bump.

**Comment by vikram-redhat** [comment]
This has been followed up in: https://github.com/openshift/openshift-docs/pull/10805

**Pull request merged**
