### PR TITLE
Added step to configure htpasswd to inventory file.

### PR DESCRIPTION
**Pull request by whitingjr**
This PR solves issue #11815 .

### CODE REVIEW

**Comment by whitingjr** [comment]
It is possible this PR is ditched. It depends on what the committers consider the best move.

**Comment by vikram-redhat** [comment]
@kalexand-rh - does this still require a followup/merging? I am not sure I follow what is going on in the attached issue.

**Comment by kalexand-rh** [comment]
@vikram-redhat, ok. I'll take a look when I get through bugs and to issues/PRs.

**Comment by kalexand-rh** [comment]
@whitingjr, my apologies for the delay. I've opened a [new PR](https://github.com/openshift/openshift-docs/pull/13439) to add the clarification about the different HTPasswd scenarios. You said in the issue that the original problem didn't need a doc fix, and the next page in the getting started guide contains good steps on configuring HTPasswd, so the new PR contains only an edited version of your change to `install_config/master_node_configuration.adoc`. Thank you!

**Pull request closed without merging**
