### PR TITLE
Adding Back Storage Classes file and Fix Links to Dynamic Provisioning

### PR DESCRIPTION
**Pull request by pospispa**
@screeley44 @ahardin-rh PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@pospispa Thank you. Can you please squash these commits?

**Comment by pospispa** [comment]
@ahardin-rh I would personally prefer to keep the commits as they are so that it is clear that there was a revert and a fix afterwards. I don't want to mix these two things together.

**Comment by ahardin-rh** [comment]
@pospispa Just curious: Is there a specific reason why you want to change the file name to storage_classes since the name of the file is Dynamic Provisioning and Creating Storage Classes, which still references dynamic provisioning?

**Comment by pospispa** [comment]
I'm restoring previous state. "The rename" happened in [commit 5e9d99de9cf2c16c2796ef69420533c24a3c6d79](https://github.com/openshift/openshift-docs/commit/5e9d99de9cf2c16c2796ef69420533c24a3c6d79) and was done by @screeley44
I think @screeley44 might have had a reason.

**Comment by screeley44** [comment]
no good reason really, I was doing a complete overwrite, so wasn't sure if it was better to create a new file or edit the existing, I chose to create a new file (maybe with a poor name)

**Comment by pospispa** [comment]
@ahardin-rh please, is there anything that blocks merge of this PR? Would you like me to modify it?

**Comment by pospispa** [comment]
This PR is for OpenShift 3.4 and above only. Please, remove the branch/enterprise-3.3 tag.
Reason: the original [PR](https://github.com/openshift/openshift-docs/pull/2972) was also for OpenShift 3.4 and above only too.

**Comment by adellape** [comment]
@pospispa @ahardin-rh I also would rather we just leave the file name as is. If that's OK, can we then just close this 3316 PR, and then @pospispa you can rebase https://github.com/openshift/openshift-docs/pull/3330 and we'll merge that?

**Comment by pospispa** [comment]
@ahardin-rh @adellape @screeley44 It seems that keeping the original file name is more preferable. So I reworked this PR in such a way that the original filename is kept and links to this file are fixed.

Unfortunately, problems in the Dynamic Provisioning documentation part are piling up so I had to do more reverts.

**Comment by pospispa** [comment]
@adellape I prefer to split the work into two logical steps:
Firstly, fix problems in current master branch, i.e. this PR.
Secondly, do any follow-up changes. Currently #3330 and #3318

**Comment by adellape** [comment]
@pospispa OK, after reviewing all these reverts and changes, it looks like overall the changes are good, though there are some revert casualties for some content. @ahardin-rh and I will worry about that afterward, so in the interest of moving things along I'll merge this and look at the follow-ups (https://github.com/openshift/openshift-docs/pull/3330 and https://github.com/openshift/openshift-docs/pull/3318). Normally we'd want this squashed down, but given how wacky it's gotten, we'll just go with it. Thanks for your work here.

**Comment by pospispa** [comment]
@adellape thanks!

**Comment by vikram-redhat** [comment]
As discussed in https://github.com/openshift/openshift-docs/pull/2972#issuecomment-274186725, removing the to_followup and the release milestones.

**Comment by gnufied** [comment]
@pospispa why did we revert multizone commits altogether? I am bit confused - the bug still exists in 3.4 and we need the workaround specified in these docs.

**Comment by gnufied** [comment]
Specifically I don't know why we reverted https://github.com/openshift/openshift-docs/pull/3316/commits/e005a267daa9756249c1cd5fc4bfa653dd436b95 commit.  Those docs changes are still needed.

**Comment by pospispa** [comment]
@gnufied I'm sorry, I misunderstood you. My understanding was that your changes are needed only temporarily.
Anyway, shall I create a PR to revert [the revert](https://github.com/openshift/openshift-docs/pull/3316/commits/e005a267daa9756249c1cd5fc4bfa653dd436b95) or will you?

**Comment by pospispa** [comment]
@gnufied I created the #3639 to add back the multizone information.

**Pull request merged**
