### PR TITLE
CNV-41664: Wording improvement to monitoring alerts

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s):
Main, 4.15, 4.16, 4.17

Issue:
[CNV-41664](https://issues.redhat.com/browse/CNV-41664)

[Link to docs preview](https://79965--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/monitoring/managing-alerts.html)

No QE needed.

Additional information:

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
