### PR TITLE
OCPBUGS#35942: Remove OLMv1 dependency resolution topics

### PR DESCRIPTION
**Pull request by michaelryanpeter**
In OpenShift 4.16, OLM 1.0, a tech preview feature, changed its architecture so that dependency resolution is now out-of-scope for the project. I was not able to remove this in time to make 4.16 GA, so this PR removes the chapter in the docs on dependency resolution. In a future PR, I will add a section on the current scope of OLM v1 and the design constraints. That work is targeted for 4.17 GA, but some of the relevant content might be backported to 4.16 if other priorities allow. https://issues.redhat.com/browse/OSDOCS-11097

Version(s): 4.16+

Issue: [OCPBUGS-35942](https://issues.redhat.com/browse/OCPBUGS-35942)

Link to docs preview: 
https://79883--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html 
https://79883--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html#olmv1-installing-an-operator_olmv1-installing-operator

QE review:
- [x] QE @Xia-Zhao-rh has approved this change.

Change management acks:
- [x] @kevinrizza (engineering)
- [x] @tlwu2013 (PM)
- [x] @kalexand-rh (DPM)
- [x] @ahardin-rh (CS)
- [x] @xltian (QE)
- [x] @sferich888 (PX)

### CODE REVIEW

**Comment by Xia-Zhao-rh** [comment]
LGTM

**Comment by kevinrizza** [comment]
In the preview page, I still see a warning that says:

```
Dependency resolution in Operator Lifecycle Manager (OLM) 1.0 requires that all of the Operators and extensions that are available to install on a cluster use a unique name for their bundles and packages.
```

Should we remove that as well? Otherwise this looks good to me.

**Comment by kevinrizza** [comment]
lgtm

**Comment by tlwu2013** [comment]
great to see the doc clearly points out "If an extension declares dependencies for other APIs or packages, the dependencies must be present on the cluster before you attempt to install the extension." + providing jq command for checking bundle dependencies

lgtm!

**Comment by ahardin-rh** [comment]
LGTM! Thank you!

**Comment by xltian** [comment]
LGTM

**Comment by kalexand-rh** [comment]
LGTM

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
