### PR TITLE
RHDEVDOCS-4940-secondPR: Added a CVE update for 1.5.9 and 1.6.4 releases

### PR DESCRIPTION
**Pull request by shipsing**
**Aligned team**: Dev Tools

**Purpose**: To resolve this issue: https://issues.redhat.com/browse/RHDEVDOCS-4940

**OCP version this PR applies to**:  enterprise 4.8 and later 

**Link to docs preview**: 
For 1.6.4: https://55529--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/gitops-release-notes.html#gitops-release-notes-1-6-4_gitops-release-notes
For 1.5.9: https://55529--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/gitops-release-notes.html#gitops-release-notes-1-5-9_gitops-release-notes

**Change Management**
Need an ACK from Eng: @iam-veeramalla 
Need an ACK from PM: @harrietgrace @wtam2018 
Need an ACK from Product experience: @RickJWagner 
Need an ACK from QE: @varshab1210 
Need an ACK from DPM: @pmkovar 
Need an ACK from CS: @Preeticp 

Peer review:

### CODE REVIEW

**Comment by shipsing** [comment]
@iam-veeramalla @harrietgrace @wtam2018 @RickJWagner @varshab1210 @pmkovar @Preeticp, Could you please help with review of this PR and share your feedback? Thanks

**Comment by RickJWagner** [comment]
Looks good.  Adding 'px-approved' label.  Thank you.

**Comment by shipsing** [comment]
Closing this PR as the content is now copied in this PR: https://github.com/openshift/openshift-docs/pull/55464

**Pull request closed without merging**
