### PR TITLE
GH#27131 - The `openshift` namespace is a namespace

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/27131

This replaces _OpenShift_ with `openshift` as necessary.

### CODE REVIEW

**Comment by bobfuru** [comment]
I found a couple more:

- https://github.com/openshift/openshift-docs/blob/7cda870e32d0545983ce2bc8c60217fffc68abf9/builds/running-entitled-builds.adoc#L16
- https://github.com/openshift/openshift-docs/blob/79ae4b80cb779e04c498a5648b9d08bc93dbdddb/openshift_images/configuring-samples-operator.adoc#L7

In a case like this, let me know if it's preferred that I add a commit with the additional changes to your PR.

The rest LGTM, thanks!

**Comment by jboxman** [comment]
@bobfuru, updated, thanks for having my six!

**Comment by bobfuru** [comment]
LGTM

**Pull request merged**
