### PR TITLE
TELCODOCS-999 adding RN description

### PR DESCRIPTION
**Pull request by kquinn1204**
[TELCODOCS-999]: Support MultiNetworkPolicies in IPv6 networks

Version(s): 4.15, main

Issue:https://issues.redhat.com/browse/TELCODOCS-999

Link to docs preview: https://70819--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-multi-network-policy-ipv6

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Review by kelbrown20 — COMMENTED** [review]
LGTM

**Pull request merged**
