### PR TITLE
[OSDOCS-11922]:Update "SRE and service account access" page to include GCP Private Service Connect-based access

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-11922
Link to docs preview:

https://85814--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-sre-access.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
QE review: For more context see https://redhat-internal.slack.com/archives/C065J9YCB34/p1733339764329899

**Review by adellape — APPROVED** [review]

**Pull request merged**
