### PR TITLE
Update APIs

### PR DESCRIPTION
**Pull request by jboxman**
APIs. I think.

### CODE REVIEW

**Comment by jboxman** [comment]
@vikram-redhat, this is the beginning of what's possible. And from the `diff` it looks like I'm not a complete fail at this.

We've moved beyond technology; now it's about what's useful to users. Such as; Should we publish alpha APIs? Which beta APIs should be published? Not to mention change logs and so forth.

This includes every API that has content. And alpha APIs seem not to have descriptions, so I've excluded them. This is an accurate reflection of what is available in 4.5.0. It's possible to confirm with `oc api-resources`.

Once 4.6 has risen, baked, and proofed, another can do the same. I'll make sure of it.

cc @lbarbeevargas @bobfuru

**Comment by vikram-redhat** [comment]
Excellent. Thank you Jason! This is indeed, what is possible.

**Comment by lbarbeevargas** [comment]
Looks great, @jboxman! Congratulations. I'm excited to learn how it all works under the hood!

**Pull request merged**
