### PR TITLE
OSDOCS-4296: Adding information on user-defined alerting

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
[OSDOCS-4296](https://issues.redhat.com//browse/OSDOCS-4296): Adding information on user-defined alerting now that the feature is enabled.

Version(s): PR applies to `main`, `enterprise-4.11` and `enterprise-4.12`.

Issue: https://issues.redhat.com/browse/OSDOCS-4296

Link to docs preview: 
[OpenShift Dedicated - Enabling alert routing for user-defined projects](https://51335--docspreview.netlify.app/openshift-dedicated/latest/osd_cluster_admin/osd_monitoring/osd-enabling-alert-routing-for-user-defined-projects.html)
[OpenShift Dedicated - Managing alerts](https://51335--docspreview.netlify.app/openshift-dedicated/latest/osd_cluster_admin/osd_monitoring/osd-managing-alerts.html)
[ROSA - Enabling alert routing for user-defined projects](https://51335--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_monitoring/rosa-enabling-alert-routing-for-user-defined-projects.html)
[ROSA - Managing alerts](https://51335--docspreview.netlify.app/openshift-rosa/latest/rosa_cluster_admin/rosa_monitoring/rosa-managing-alerts.html)
[OpenShift Enterprise - Enabling alert routing for user-defined projects](https://51335--docspreview.netlify.app/openshift-enterprise/latest/monitoring/enabling-alert-routing-for-user-defined-projects.html#understanding-alert-routing-for-user-defined-projects_enabling-alert-routing-for-user-defined-projects)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by michaelryanmcneill** [comment]
cc: @EricPonvelle since he's been helping me!

**Review by EricPonvelle — COMMENTED** [review]
@michaelryanmcneill, I think I captured all of the links that were missing their IDs. These changes should help make the build pass the checks.

**Review by nalhadef — COMMENTED** [review]
Hi, @michaelryanmcneill. Just a few comments.

**Comment by nalhadef** [comment]
is:pr is:open label:peer-review-needed -label:peer-review-in-progress -label:dev-tools -label:CNV sort:updated-asc

**Comment by michaelryanmcneill** [comment]
Thank you @nalhadef! I have fixed those issues and also corrected them in the source. I'm asking for eyes again just because I made changes in the other upstream docs to fix it. Preview should be updated shortly. 

/remove-label peer-review-done
/label peer-review-needed

**Comment by nalhadef** [comment]
Sure, Mike. I'll grab it. Thanks!

**Comment by nalhadef** [comment]
Second review looks good to me, Michael!

**Pull request merged**
