### PR TITLE
Incorrect information about using custom certificates with ingress router

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1759326

### CODE REVIEW

**Comment by mburke5678** [comment]
@xltian Please assign a resource to QE this change.

**Comment by xltian** [comment]
@lihongan will take a look at it.

**Comment by lihongan** [comment]
LGTM, thank you.

**Comment by mburke5678** [comment]
@xltian @lihongan Thank you for your quick response and review. I greatly appreciate it.

**Pull request merged**
