### PR TITLE
[OSDOCS-7887]:ROSA Classic - New CLI Command ROSA Describe Machineepool

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-7887
Link to docs preview:

https://66125--docspreview.netlify.app/openshift-rosa/latest/cli_reference/rosa_cli/rosa-manage-objects-cli#rosa-describe-machinepool_rosa-managing-objects-cli
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello 
@xueli181114 and @yuwang-RH, could I get a PR review for this when you get a moment? Thanks!

**Review by skrthomas — COMMENTED** [review]
Global comment, wondering if `machinepool` needs backticks in the text, not the title. I see `mymachinepool` is in backticks so just wondering why that one is and not `machinepool`

**Comment by mletalie** [comment]
Please note that a new PR has been created that unmerges this PR, as the original JIRA stated this was slated for 1.2.27 release. https://github.com/openshift/openshift-docs/pull/66228

**Pull request merged**
