### PR TITLE
Bug 1493562 Removed the "Disable dnsmsq" section

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1493562

### CODE REVIEW

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Small change, removing a paragraph

**Comment by bmcelvee** [comment]
LGTM 🍂

**Comment by vikram-redhat** [comment]
@mburke5678 - Hey Michael - can you please check the links. There is a tiny bit of space in the first link.

**Comment by vikram-redhat** [comment]
@mburke5678 - the second link wasn't correct as well. There is no 'dns' section header. The correct header is 'prereq-dns'. Can you please edit it?

**Comment by mburke5678** [comment]
[rev_history]
|xref:../install_config/install/prerequisites.adoc#install-config-install-prerequisites[Installation and Configuration -> Prerequisites]
|Removed information on disabling DNSMSQ from the xref:../install_config/install/prerequisites.adoc#prereq-dns[DNS section]. DNSMSQ must be enabled starting in version 3.6.
%

**Pull request merged**
