### PR TITLE
Groupify OAuth and User objects

### PR DESCRIPTION
**Pull request by liggitt**
Sweeping docs that reference ungrouped API types

### CODE REVIEW

**Comment by liggitt** [comment]
cc @openshift/sig-security

**Review by enj — APPROVED** [review]

**Comment by ahardin-rh** [comment]
@liggitt Thanks! is this for 3.9?

**Comment by liggitt** [comment]
Yes

**Comment by ahardin-rh** [comment]
Thanks! 
No revision history needed.

**Pull request merged**
