### PR TITLE
Bug 1939230 - "Custom image builds with Buildah" instructions incorrect

### PR DESCRIPTION
**Pull request by rolfedh**
- For versions 4.5+
- https://bugzilla.redhat.com/show_bug.cgi?id=1939230
- Direct link to doc preview: https://deploy-preview-30499--osdocs.netlify.app/openshift-enterprise/latest/cicd/builds/custom-builds-buildah.html#builds-create-custom-build-artifacts_custom-builds-buildah
- Ready for Peer Review and Merge.

### CODE REVIEW

**Comment by rolfedh** [comment]
Hi, @gabemontero. Please review and approve with `/lgtm`. thanks.

**Comment by gabemontero** [comment]
/lgtm

thanks @rolfedh

**Pull request merged**
