### PR TITLE
[OCPBUGS-17590] Remove IBM Z mention

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.12 + 

Issue:
https://issues.redhat.com/browse/OCPBUGS-17590

Link to docs preview: https://64836--docspreview.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-local#local-volume-cr_persistent-storage-local

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by duanwei33** [comment]
lgtm 
(Discussing from the Jira)

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
