### PR TITLE
[peer review] Edits to rolling strategy section

### PR DESCRIPTION
**Pull request by bfallonf**
Minor edits to #820 . Nothing major. Tried to make the footnote as small as possible.

@adellape @tpoitras @tnguyen-rh any issues?

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@bfallonf Looks good, but there's a very minor improvement suggestion: I would change the example numbers to 50 total, resulting in 5 at a time, just to avoid confusion between "10 percent" and "10 at a time".

**Comment by bfallonf** [comment]
@tnguyen-rh I see what you mean. I've done as suggested. If that's all, this might be ready to merge.

**Comment by adellape** [comment]
@bfallonf This has been deprecated by https://github.com/openshift/openshift-docs/pull/951 now (and also makes this PR have conflicts). Take a look, but I think we can close this 956 PR.

**Comment by bfallonf** [comment]
@adellape Agree (phew).

**Pull request closed without merging**
