### PR TITLE
Fixed broken xrefs throughout docs

### PR DESCRIPTION
**Pull request by tpoitras**
Man, there were heaps! :weary: 

Tagging @adellape & @aweiteka - Tons of these broken links were in the "registry_quickstart", which it seems is only related to atomic-registry. Going forward, please be sure to verify xref links using the script authored by @vikram-redhat [1] so that broken links in the atomic registry quickstart do not affect the OpenShift docs team. Thank you.

[1] https://gitlab.cee.redhat.com/vigoyal/openshift-release-script/blob/master/check-links.sh

### CODE REVIEW

**Comment by aweiteka** [comment]
@tpoitras thanks for the fixes!

**Comment by tpoitras** [comment]
@aweiteka You're welcome! :dancers:

**Comment by tpoitras** [comment]
no revision history note required

**Comment by adellape** [comment]
:+1:

**Pull request merged**
