### PR TITLE
OSDOCS-3820: Add release note for Silicom STS Family SR-IOV devices

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-3820

Version(s): 4.12

Link to docs preview: https://51108--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-networking-supported-hardware-for-sr-iov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@novacain1, can you confirm this release note entry? Thanks!

**Comment by novacain1** [comment]
So when looking at https://51108--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html, this looks fine to me.  

Navigating to https://51108--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov however does not list the 1591 PF.  Should it @jboxman-rh ?

It is listed here: https://access.redhat.com/articles/6954499.

**Comment by jboxman-rh** [comment]
@novacain1, ah, yes, it wouldn't be in the preview. It is merged into the 4.12 docs though: https://docs.openshift.com/container-platform/4.12/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

Although the login & password for that are in the Slack channel #forum-docs.

But it's there.

**Comment by novacain1** [comment]
LGTM @jboxman-rh

**Review by abhatt-rh — COMMENTED** [review]
Hi @jboxman-rh I left a suggestion, else LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
