### PR TITLE
Update release notes for 3.73.4 patch

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to `rhacs-docs-3.73`

[Issue](https://issues.redhat.com/browse/ROX-16172)

[Link to docs preview](https://58286--docspreview.netlify.app/openshift-acs/latest/release_notes/373-release-notes.html)

QE review:
- [x] QE has approved this change. (**N/A - ACS has no QE, reviewed/approved by SME**)

Additional information:

### CODE REVIEW

**Review by tommartensen — APPROVED** [review]

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Comment by kelbrown20** [comment]
@kcarmichael08 Hey Kerry! The updates lgtm, but I wanted to confirm that this has gone through QE review before merging? Thank you!

**Comment by kelbrown20** [comment]
Ah gotcha! Thank you for updating!

**Pull request merged**
