### PR TITLE
documenting --source-secret flag for new-app and new-build

### PR DESCRIPTION
**Pull request by coreydaley**
Trello: [link](https://trello.com/c/rEa5fQMO/1077-2-improve-new-app-experience-with-private-source-repositories-appcreation)
Depends on: https://github.com/openshift/origin/pull/16113

### CODE REVIEW

**Comment by coreydaley** [comment]
[(2) Improve new-app experience with private source repositories [app_creation]](https://trello.com/c/rEa5fQMO/1077-2-improve-new-app-experience-with-private-source-repositories-appcreation)

**Comment by coreydaley** [comment]
@openshift/team-documentation ptal
The dependent PR has already merged

**Comment by bmcelvee** [comment]
Thanks, @coreydaley! I'll get this merged.

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../cli_reference/basic_cli_operations.adoc#cli-reference-basic-cli-operations[Developer CLI Operations]
|Added `--source-secret` flag to the xref:../cli_reference/basic_cli_operations.adoc#new-app[`new-app`] and xref:../cli_reference/basic_cli_operations.adoc#new-build[`new-build`] sections.
%
|xref:../dev_guide/application_lifecycle/new_app.adoc#dev-guide-new-app[Creating New Applications]
|Added `--source-secret` flag to the xref:../dev_guide/application_lifecycle/new_app.adoc#specifying-source-code[Creating an Application From Source Code] section.
%

**Comment by vikram-redhat** [comment]
@coreydaley Can this apply to online docs as well? Dedicated?

**Comment by vikram-redhat** [comment]
@coreydaley - thanks!

**Pull request merged**
