### PR TITLE
CNV-23466: change to networks tab in UI

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.13+

Issue: [CNV-23466](https://issues.redhat.com//browse/CNV-23466)

Link to docs preview: http://file.rdu.redhat.com/sjess/CNV23466/virt/virt-web-console-overview.html#ui-virtualmachine-details-metrics_virt-web-console-overview

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Review by lkladnit — APPROVED** [review]

**Pull request merged**
