### PR TITLE
OADP-2948: OADP 1.1.7 release notes

### PR DESCRIPTION
**Pull request by anarnold97**
### To be published

* GA - **26th October**

### JIRA

* [OADP-2948 - release notes for 1.1.7](https://issues.redhat.com/browse/OADP-2948)

### Version(s):

* Enterprise 4.11 → branch/enterprise-4.11
* Enterprise 4.12 → branch/enterprise-4.12
* Enterprise 4.13 → branch/enterprise-4.13
* Enterprise 4.14 → branch/enterprise-4.14

### Link to docs preview:

[OADP 1.1.7 release notes](https://66677--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/oadp-release-notes#migration-oadp-release-notes-1-1-7_oadp-release-notes)

QE review:
- [x] QE has approved this change. [Approval](https://github.com/openshift/openshift-docs/pull/66677#pullrequestreview-1692788570)

Additional information:

### CODE REVIEW

**Comment by anarnold97** [comment]
@akarol && @weshayutin - please can you review. thanks

**Review by weshayutin — APPROVED** [review]
thanks Andy!

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
