### PR TITLE
Upgrade documentation

### PR DESCRIPTION
**Pull request by sdodson**
Currently only covers RPM based installs

TODO:
- [x] Router upgrade sanity checks @pweil- 
- [x] Registry upgrade sanity checks @ncdc 
- [x] S2I / DB image upgrade sanity checks @bparees
- [x] kube proxy / node evacuation impact on service / container availability @sdodson
- [x] evaluate adding updated nodes and evacuating old nodes @sdodson
- [x] Which parts make sense to automate via ansible -- follow up card to address this https://trello.com/c/yax9q1HG/53-upgrade-automation

### CODE REVIEW

**Comment by sdodson** [comment]
I think things are mostly done. I need to verify the router rolling upgrade bits after the deployments work lands.

**Comment by deads2k** [comment]
@sdodson Our bootstrap roles have changed between 3 and 3.0.1.  We're creating a new command to patch up this condition in https://github.com/openshift/origin/pull/3810.  By default, the command will display what has changed.  If you pass a --confirm, it will replace the old role with the new one.

**Comment by sdodson** [comment]
@pweil- Do you mind sanity checking the router upgrade steps now that the sa/scc stuff is in?

http://file.rdu.redhat.com/sdodson/upgrades/admin_guide/upgrades.html

**Comment by sdodson** [comment]
@adellape probably ready to start review

**Comment by sdodson** [comment]
@pweil- I should've mentioned to check both the general router steps that we'd have people perform on all upgrades and the 3.0.1 specific steps to add the SA and SCC

**Comment by pweil-** [comment]
@sdodson - SA items look good.   Deployment config should also be updated so that it uses the new service account (since they won't be re-running oadm router --service-account=router ....) along with the new parameters you discussed in https://github.com/openshift/origin/issues/3861#issuecomment-124725768

**Comment by sdodson** [comment]
Squashed everything down as we're converging on done

**Comment by adellape** [comment]
:+1:

**Pull request merged**
