### PR TITLE
Update openshift_pipeline.adoc

### PR DESCRIPTION
**Pull request by gabemontero**
See https://github.com/openshift/jenkins-sync-plugin/issues/251

@openshift/sig-developer-experience @bmcelvee ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by bmcelvee** [comment]
LTGM 

@gabemontero to which versions of OCP does this apply?

**Comment by gabemontero** [comment]
as far back as the file in question exists @bmcelvee 

we added the tutorial a release or two after we added the actual support

**Comment by bmcelvee** [comment]
Minor change, no QE required.

**Pull request merged**
