### PR TITLE
OCPBUGS#4080 explanation about VMWare licenses

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.8+ 

Issue:
https://issues.redhat.com/browse/OCPBUGS-4080

Link to docs preview:
https://54025--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/preparing-to-install-on-vsphere.html#preparing-to-install-on-vsphere-prerequisites

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@WenXinWei please take a look at this addition to the vSphere installation prerequisites. Thank you

**Comment by WenXinWei** [comment]
That looks good to me.

**Comment by bscott-rh** [comment]
@racedo Hello Ramon, can you please look over the language I've added around VMWare licensing? Thank you

**Pull request merged**
