### PR TITLE
Removing vsphere from dynamic provisioning

### PR DESCRIPTION
**Pull request by pospispa**
This PR depends on the [PR](https://github.com/openshift/openshift-docs/pull/3316) that must be merged before this one.

@childsb @screeley44  @openshift/team-documentation PTAL

Target versions: OpenShift 3.4 and above.

### CODE REVIEW

**Comment by adellape** [comment]
@pospispa This can be rebased.

**Comment by pospispa** [comment]
@adellape rebase done.

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by gaurav-nelson** [comment]
@pospispa Should we add vsphere for dynamic provisioning again now that it is supported in 3.6?

**Comment by pospispa** [comment]
Well, I don't know.

@childsb please, should be vsphere dynamic provisioning added into OpenShift 3.6 documentation?

**Pull request merged**
