### PR TITLE
OSDOCS-12978 Adding a note about Krew in CLI Manager docs

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.17 +

Issue: [OSDOCS-12978](https://issues.redhat.com/browse/OSDOCS-12978)

Link to docs preview: https://86515--ocpdocs-pr.netlify.app/openshift-enterprise/latest/cli_reference/cli_manager/cli-manager-install.html

QE review:
- [X] QE has approved this change.

Additional information: Related to [this slack thread.](https://redhat-internal.slack.com/archives/CKJR6200N/p1734544262187209)

### CODE REVIEW

**Comment by ardaguclu** [comment]
Thank you
LGTM

**Review by skrthomas — COMMENTED** [review]
/lgtm

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
