### PR TITLE
OSDCOS-2608: Added clarification that STS only supports public and AWS PrivateLink…

### PR DESCRIPTION
**Pull request by jonquilwilliams**
… clusters.

**JIRA:** https://issues.redhat.com/browse/OSDOCS-2608

**Previews:** 

https://deploy-preview-35929--osdocs.netlify.app/openshift-rosa/latest/cloud_infrastructure_access/rosa-private-cluster?utm_source=github&utm_campaign=bot_dp

https://deploy-preview-35929--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started_sts/rosa-sts-creating-cluster.html

**Branch:** dedicated-4. No CP, no milestones.

### CODE REVIEW

**Review by EricPonvelle — CHANGES_REQUESTED** [review]
There's a rendering error with the notes not being configured correctly in the private cluster assembly file. Can you take a look at it?

**Comment by 0kashi** [comment]
Looks good to me.

**Comment by xueli181114** [comment]
Looks good to me

**Comment by jonquilwilliams** [comment]
Change request addressed. Rendering correctly now. Merging and closing this PR.

**Pull request merged**
