### PR TITLE
bug 1668381 Modified GlusterFS upgrade instructions

### PR DESCRIPTION
**Pull request by sheriff-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1668381

@kalexand-rh  peer reviewed in person. 

@liangxia  Please take a look, thanks.

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@vikram-redhat  , I looked at 3.9 docs on this, and it makes sense to me the way it's written. Step 4b indicates that the pod terminates, then 4d (the line we have been changing in this bug) references that: 

https://docs.openshift.com/container-platform/3.9/upgrading/automated_upgrades.html#special-considerations-for-glusterfs

Let me know if you want me to re-work this or if it's okay for 3.9. Thanks!

**Comment by vikram-redhat** [comment]
@sheriff-rh - yes that makes sense to me to leave it as is for 3.9 docs. Just take the label off. Thanks!

**Pull request merged**
