### PR TITLE
OBSDOCS-138 - Child PR of RHDEVDOCS-4781 - Loki CLI install

### PR DESCRIPTION
**Pull request by libander**
Branches: OCP 4.11+

Child PR of https://github.com/openshift/openshift-docs/pull/59285 for merge review ease. 
All approvals completed on parent PR. 

Preview: https://64610--docspreview.netlify.app/openshift-enterprise/latest/logging/cluster-logging-loki#logging-loki-cli-install_cluster-logging-loki

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@libander, you need to open manual cherry-pick PRs for 4.11, 4.12, 4.14, and 4.15.

**Comment by abrennan89** [comment]
@kalexand-rh @libander the formatting on this one seems very off:
image
image

I've noticed it when I went to move this module as part of restructuring work I'm doing (https://67049--docspreview.netlify.app/openshift-enterprise/latest/logging/log_storage/installing-log-storage#logging-loki-cli-install_installing-log-storage)

This probably needs a follow up PR to fix. Also, in the manual cherrypicks, it looks like `:_mod-docs-content-type: ASSEMBLY` is being reverted back to `:_content-type: ASSEMBLY` - is that intentional?

Thanks.

**Pull request merged**
