### PR TITLE
security guide: monitoring events and logs

### PR DESCRIPTION
**Pull request by sosiouxme**
This adds a new topic in the existing Security Guide, focusing on
system events and logs from main platform components.

Trello card: https://trello.com/c/uI7tGkmM

### CODE REVIEW

**Comment by sosiouxme** [comment]
@brenton first pass -- anyone in particular that should be looking at this?

**Comment by brenton** [comment]
@tmorriso-rh, @vikram-redhat, This is the resurrection of https://github.com/openshift/openshift-docs/pull/5174.  Luke has a bit more to touch up but we're curious who he could work with from docs to have this reviewed and merged.

**Comment by vikram-redhat** [comment]
@brenton - @tmorriso-rh can work with Luke to get it reviewed and merged.

**Comment by sosiouxme** [comment]
I added a final paragraph to mention advanced logging. This refers to the content being provided with https://github.com/openshift/openshift-docs/pull/5722

**Comment by vikram-redhat** [comment]
@tmorriso-rh - is there anything holding this up?

**Comment by tmorriso-rh** [comment]
The new PR is https://github.com/openshift/openshift-docs/pull/6003

**Comment by vikram-redhat** [comment]
Hey @tmorriso-rh - do you need a follow up tag here?

**Comment by nengard** [comment]
#6003 has been peer-reviewed, so marking this as peer review done.

**Comment by sosiouxme** [comment]
Guessing there is no reason to keep this open as the work is proceeding in https://github.com/openshift/openshift-docs/pull/6003

**Comment by vikram-redhat** [comment]
Keeping the to_followup label on till it gets picked to the 3.7 stage branch. @tmorriso-rh

**Comment by adellape** [comment]
> Keeping the to_followup label on till it gets picked to the 3.7 stage branch. @tmorriso-rh

@vikram-redhat Did this get addressed?

**Comment by vikram-redhat** [comment]
@adellape - yeah this was merged with: https://github.com/openshift/openshift-docs/pull/6003. I will remove the to_followup.

**Pull request closed without merging**
