### PR TITLE
OSDOCS#10164:Adjusted ROSA HCP max worker nodes from 51 to 90

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.15+

Issue:
[OSDOCS-10164](https://issues.redhat.com/browse/OSDOCS-10164)

Link to docs preview:
[Instance types](https://74218--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition.html)

Peer reviewer:
- [x] Peer reviewer has approved this change.

SME review:
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by arendej — APPROVED** [review]
ship it!

**Comment by AedinC** [comment]
@arendej Can you review please?

**Comment by AedinC** [comment]
> ship it!

lol, you approved before I even requested!

**Comment by AedinC** [comment]
@tsze-redhat  Could you please approve from QE?

**Pull request merged**
