### PR TITLE
Removing Opaque Integer Resources

### PR DESCRIPTION
**Pull request by mburke5678**
Per https://github.com/openshift/openshift-docs/issues/19347

I see that Opaque Integer Resources are removed from 1.9 version as per the link here kubernetes/enhancements#76 (comment) so documentation related to Opaque Integer Resources should be removed.

Verified by @rphillips in Slack: https://coreos.slack.com/archives/CK1AE4ZCK/p1581020513181400

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunilcio Is this a PR you can review?

**Comment by mburke5678** [comment]
Files removed from 3.x via https://github.com/openshift/openshift-docs/pull/19593

**Comment by vikram-redhat** [comment]
Anytime we remove or change a previously documented (and supported) feature we need to follow the steps outlined recently to help support these changes and help make the transition. 

We need acks from Product Experience, Docs, PM, Eng and QE. We also need to send out information about this change to openshift-sme and aos-devel, before we make this change, and once the change is done.

@sferich888 and/or @reestr do you ack this change from both 3.11 and 4.x docs?
@xltian is this ok from QE?

@mburke5678 - Since eng raised this issue, happy to consider this as an ack. Not sure which PM can ack this change though. Can you confirm with eng?

**Comment by sferich888** [comment]
Based on https://github.com/kubernetes/enhancements/issues/76#issuecomment-343274099 removing this from 3.10 and 3.11 docs should be OK, given that upstream kube dropped support for this resource in 1.9 (3.9)

**Comment by vikram-redhat** [comment]
@tkatarki are you ok with us removing this from the docs for both 3.x and 4.x?

**Comment by xltian** [comment]
@sunilcio Can you please review from QE? Thanks

**Comment by jhou1** [comment]
@weinliu PTAL

**Comment by weinliu** [comment]
> Anytime we remove or change a previously documented (and supported) feature we need to follow the steps outlined recently to help support these changes and help make the transition.
> 
> We need acks from Product Experience, Docs, PM, Eng and QE. We also need to send out information about this change to openshift-sme and aos-devel, before we make this change, and once the change is done.
> 
> @sferich888 and/or @reestr do you ack this change from both 3.11 and 4.x docs?
> @xltian is this ok from QE?
> 
> @mburke5678 - Since eng raised this issue, happy to consider this as an ack. Not sure which PM can ack this change though. Can you confirm with eng?

Removing this is ok for QE as per:
> Removed opaque integer resources (deprecated in v1.8) #55103
> https://github.com/kubernetes/kubernetes/pull/55103

**Comment by mburke5678** [comment]
@tkatarki @rphillips do you ack this change from both 3.11 and 4.x docs?

**Comment by mburke5678** [comment]
@tkatarki @rphillips do you ack this change from both 3.11 and 4.x docs?

**Comment by mburke5678** [comment]
@tkatarki Approved via Slack.

**Comment by rphillips** [comment]
/lgtm
Thanks!

**Pull request merged**
