### PR TITLE
Added tags example for Azure MachineSet yaml

### PR DESCRIPTION
**Pull request by fmartingr**
I've added the `tags` key to the yaml example for the document "[Creating a MachineSet in Azure](https://docs.openshift.com/container-platform/4.3/machine_management/creating_machinesets/creating-machineset-azure.html#machineset-yaml-azure_creating-machineset-azure)", since it was supported and missing.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@jianlinliu is this ok?

@kalexand-rh

**Comment by jianlinliu** [comment]
@jhou1 @sunzhaohua2 ^^

**Comment by kalexand-rh** [comment]
Adding the example is fine, but please also provide context about how these tags are meant to be used.

**Comment by jhou1** [comment]
@miyadav PTAL

**Comment by miyadav** [comment]
@fmartingr , would suggest to add more info about the field values value1 and value2 , so that it would help users to make use of those values in future and give better idea of its usefulness .
May be similar to what is mentioned in example of [AWS](https://docs.openshift.com/container-platform/4.3/machine_management/creating_machinesets/creating-machineset-aws.html) - 
 tags:
            - name: kubernetes.io/cluster/<infrastructureID> 
              value: owned

**Comment by fmartingr** [comment]
@miyadav I've updated the example to match the one in the AWS procedure, sorry about the delay.

**Pull request closed without merging**
