### PR TITLE
BZ2093811: Remove obsolete Custom boot source module and links

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.11+

Issue: [BZ2093811](https://bugzilla.redhat.com/show_bug.cgi?id=2093811)

Link to docs preview: [Creating and using boot sources](https://52145--docspreview.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-creating-and-using-boot-sources.html)

QE review: Not required. SME approval is sufficient. Approved by Yaacov Zamir.

Additional information:

### CODE REVIEW

**Comment by apinnick** [comment]
@dominikholler 
Could you review this PR?

**Comment by dominikholler** [comment]
This PR reflect what is in the UI, but I am not sure if the chance in the UI was intended.
@yaacov can you please confirm that https://bugzilla.redhat.com/show_bug.cgi?id=2093811#c7 is intended?

**Comment by apinnick** [comment]
Approved by Yaacov Zamir. Ready for peer review.

**Review by yaacov — APPROVED** [review]

**Comment by ousleyp** [comment]
LGTM

**Pull request merged**
