### PR TITLE
OCPBUGS-3313: Change the label name

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12

Issue: https://issues.redhat.com/browse/OCPBUGS-3313

Link to docs preview: https://52528--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-nw-metrics-telemetry

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by mjpytlak** [comment]
@xenolinux Just a heads up. To prevent the openshift-ci bot from kicking in on your doc bugs use a `#` instead of a `-` in your title. For example `OCPBUGS#3313`

**Pull request merged**
