### PR TITLE
admin_guide/manage_scc: mention about preserving of labels and annotations

### PR DESCRIPTION
**Pull request by php-coder**
Related to https://github.com/openshift/origin/issues/5717 and https://github.com/openshift/origin/pull/6714

PTAL @pweil- @openshift/team-documentation

### CODE REVIEW

**Review by pweil- — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
LGTM! Is this for 3.5?

**Comment by php-coder** [comment]
It was merged on Feb 4, **2016** so I guess that it applies to all the branches.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/manage_scc.adoc#admin-guide-manage-scc[Managing Security Context Constraints]
|Added information about preserving labels and annotations, in addition to groups.
%

**Pull request merged**
