### PR TITLE
Edit suggested in file machine_management/creating_machinesets/creating-machineset-gcp.adoc

### PR DESCRIPTION
**Pull request by mburke5678**
`oc get machine` command should be `oc describe machine`.

https://github.com/openshift/openshift-docs/issues/18475

### CODE REVIEW

**Comment by mburke5678** [comment]
@sunzhaohua2 You reviewed the initial PR for this section. Can you take a look to make sure this change is OK? I think we need an `oc describe machine` command in order to get the status of a new machine. 
@kalexand-rh FYI

**Comment by sunzhaohua2** [comment]
@mburke5678 `oc describe machine <name>  -n openshift-machine-api` or `oc get machine <name> -o yaml -n openshift-machine-api` all is ok. As long as our output matches the command. If we use `oc describe machine <name>  -n openshift-machine-api` then the output should like:
```
Status:
  Addresses:
    Address:     10.0.32.4
    Type:        InternalIP
    Address:     wewang-5fn4l-w-c-lkctf.us-central1-c.c.openshift-qe.internal
    Type:        InternalDNS
    Address:     wewang-5fn4l-w-c-lkctf.c.openshift-qe.internal
    Type:        InternalDNS
  Last Updated:  2020-04-01T02:17:49Z
  Node Ref:
    Kind:  Node
    Name:  wewang-5fn4l-w-c-lkctf.c.openshift-qe.internal
    UID:   24f5aef2-6fbe-4dc3-b3ce-eaecf7ac2a8b
  Phase:   Running
  Provider Status:
    Conditions:
      Last Probe Time:       2020-04-01T01:40:31Z
      Last Transition Time:  2020-04-01T01:40:31Z
      Message:               machine successfully created
      Reason:                MachineCreationSucceeded
      Status:                True
      Type:                  MachineCreated
    Instance Id:             wewang-5fn4l-w-c-lkctf
    Instance State:          RUNNING
    Metadata:
```
If we use  `oc get machine <name> -o yaml -n openshift-machine-api` then the output should like:
```
status:
  addresses:
  - address: 10.0.32.4
    type: InternalIP
  - address: wewang-5fn4l-w-c-lkctf.us-central1-c.c.openshift-qe.internal
    type: InternalDNS
  - address: wewang-5fn4l-w-c-lkctf.c.openshift-qe.internal
    type: InternalDNS
  lastUpdated: "2020-04-01T02:17:49Z"
  nodeRef:
    kind: Node
    name: wewang-5fn4l-w-c-lkctf.c.openshift-qe.internal
    uid: 24f5aef2-6fbe-4dc3-b3ce-eaecf7ac2a8b
  phase: Running
  providerStatus:
    conditions:
    - lastProbeTime: "2020-04-01T01:40:31Z"
      lastTransitionTime: "2020-04-01T01:40:31Z"
      message: machine successfully created
      reason: MachineCreationSucceeded
      status: "True"
      type: MachineCreated
    instanceId: wewang-5fn4l-w-c-lkctf
    instanceState: RUNNING
    metadata: {}
```
And from the title I found this is a gcp env, so all the output should match gcp result. For example `oc get machinesets -n openshift-machine-api` should be :
```
$ oc get machineset
NAME               DESIRED   CURRENT   READY   AVAILABLE   AGE
wewang-5fn4l-w-a   1         1         1       1           24h
wewang-5fn4l-w-b   1         1         1       1           24h
wewang-5fn4l-w-c   1         1         1       1           24h
wewang-5fn4l-w-f   0         0                             24h
```
I will file a bug for these problems.

**Comment by mburke5678** [comment]
@sunzhaohua2 This file is used in several places, AWS, Azure, GCP, and the general machineset topic. I am not sure that customizing the output for each format is worth the effort. @kalexand-rh ?

```
// * machine_management/creating-infrastructure-machinesets.adoc
// * machine_management/creating_machinesets/creating-machineset-aws.adoc
// * machine_management/creating_machinesets/creating-machineset-azure.adoc
// * machine_management/creating_machinesets/creating-machineset-gcp.adoc
```

**Comment by sunzhaohua2** [comment]
@mburke5678 I think we must do that, otherwise we create a topic is ok instead of creating a machineset on AWS, GCP, Azure.

**Comment by mburke5678** [comment]
@sunzhaohua2 we could use conditionals for each cloud type if you can provide output for each.
AWS, Azure, GCP, OSP
See https://raw.githubusercontent.com/openshift/openshift-docs/master/modules/installation-initializing.adoc

**Pull request merged**
