### PR TITLE
[SRVOCF-439]: Minor functions fixes

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+

Issue:
https://issues.redhat.com/browse/SRVOCF-439

Link to docs preview:
http://file.rdu.redhat.com/abrennan/110822/SRVOCF-439/serverless/functions/serverless-functions-yaml.html

### CODE REVIEW

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by jrangelramos** [comment]
QE approved

**Review by bscott-rh — APPROVED** [review]
LGTM.

**Pull request merged**
