### PR TITLE
Fix IPI supported methods table

### LINKED ISSUE #29037: [enterprise-4.4, enterprise-4.5] Issue in file installing/install_config/installation-types.adoc
### Which section(s) is the issue in?

[IPI ](https://docs.openshift.com/container-platform/4.5/installing/install_config/installation-types.html)

### What needs fixing?

There is an extra row for one platform in the markup for this page in 4.4 + 4.5. As a result, the table does not render correctly.

### PR DESCRIPTION
**Pull request by maxwelldb**
This PR resolves #29037.

Bug in 4.4: https://docs.openshift.com/container-platform/4.4/installing/install_config/installation-types.html

Bug in 4.5: https://docs.openshift.com/container-platform/4.5/installing/install_config/installation-types.html

### CODE REVIEW

**Comment by maxwelldb** [comment]
Preview: https://sharp-hopper-548956.netlify.app/installation-types.html

**Comment by maxwelldb** [comment]
@openshift/team-documentation PTAL. Thanks!

**Comment by lbarbeevargas** [comment]
The table LGTM with the alignment fix.

**Comment by maxwelldb** [comment]
@lbarbeevargas TY!

**Pull request merged**
