### PR TITLE
Replace advanced install log options with openshift_docker_options.

### PR DESCRIPTION
**Pull request by abutcher**
@sdodson ptal

### CODE REVIEW

**Comment by sdodson** [comment]
LGTM

**Comment by abutcher** [comment]
@adellape ptal

**Comment by adellape** [comment]
@abutcher LGTM. Change is valid in both OSE 3.1 and 3.2?

@ahardin-rh Since you worked on the part being replaced and the section it links to, any other impact you can think of?

**Comment by ahardin-rh** [comment]
@adellape No other areas that I am aware of. Thanks for checking!

**Comment by abutcher** [comment]
@adellape yes change will be valid with the latest public openshift-ansible packages which cover 3.0->3.2 installs.

**Comment by adellape** [comment]
:green_heart:

**Comment by adellape** [comment]
[rev_history]
|link:../install_config/install/advanced_install.html[Installing -> Advanced Installation]
|Replaced the `*openshift_docker_log_options*` Ansible variable with `*openshift_docker_options*` in the link:../install_config/install/advanced_install.html#configuring-host-variables[Configuring Host Variables] section.
%

**Pull request merged**
