### PR TITLE
Added capacity planning guidance for openshift metrics (#2763 continued)

### PR DESCRIPTION
**Pull request by ahardin-rh**
Continuation of https://github.com/openshift/openshift-docs/pull/2763

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@jeremyeder @timothysc PTAL

**Comment by jeremyeder** [comment]
@ekuric

**Comment by jeremyeder** [comment]
@ahardin-rh this looks good to me.  I think you will need a follow-on PR to incorporate the new metrics installer playbook into the docs as it was not ready for us to use/document.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/cluster_metrics.adoc#install-config-cluster-metrics[Enabling Cluster Metrics]
|Added capacity planning guidance for {product-title} metrics.
%

**Pull request merged**
