### PR TITLE
Graphic Update: Changing images from SVG to PNG to address PDF rendering errors.

### PR DESCRIPTION
**Pull request by johnwilkins**
SVGs render in PDF files improperly according to the graphics department. I've updated two graphics from SVG to PNG to address this issue. 

Version(s): 4.13, 4.12, 4.11, 4.10

Issue: Request from graphics department

Link to docs preview: https://59852--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configuring-ntp-for-disconnected-clusters_ipi-install-installation-workflow and https://59852--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configure-network-components-to-run-on-the-control-plane_ipi-install-installation-workflow

QE review:
- This change doesn't require QE.

### CODE REVIEW

**Review by sheriff-rh — COMMENTED** [review]
LGTM!

**Comment by kalexand-rh** [comment]
Because you're just swapping the type of an approved image, this change doesn't require QE. Peer review is sufficient.

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM as well

**Comment by kelbrown20** [comment]
@johnwilkins it looks like some of the manual CP failed for 4.12, 4.11, and 4.10 :(. It might have something to do with those ifdefs not exiting in the other branches. I can merge the manual CPs whenever you're ready 🙂

**Pull request merged**
