### PR TITLE
OLS-714: update distro map for OLS product

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OLS 1.0

Issue: https://issues.redhat.com/browse/OLS-714

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by aireilly — APPROVED** [review]

**Comment by rh-tokeefe** [comment]
Thanks @aireilly, appreciate your help!

**Review by aireilly — CHANGES_REQUESTED** [review]
~Undo the changes to _previewpage in this PR. Make those on main and CP separately to lightspeed-docs-main and the tp branch.~

**Review by aireilly — APPROVED** [review]
Ignore last comment. This /lgtm

**Pull request merged**
