### PR TITLE
Added even number of CPUs to the podman command for oslat test - issues 58468

### LINKED ISSUE #58468: oslat - Skip the test, the requested number of CPUs should be even to avoid noisy neighbor situation
### Which section(s) is the issue in?
In the following documentation, the  `podman run`  test case for `oslat` uses  7 CPUs with the parameter `LATENCY_TEST_CPUS=7`. 

https://docs.openshift.com/container-platform/4.12/scalability_and_performance/cnf-performing-platform-verification-latency-tests.html#Running%20oslat

```bash
podman run -v $(pwd)/:/kubeconfig:Z -e KUBECONFIG=/kubeconfig/kubeconfig -e LATENCY_TEST_RUN=true -e DISCOVERY_MODE=true -e FEATURES=performance -e ROLE_WORKER_CNF=worker-cnf -e LATENCY_TEST_CPUS=7 -e LATENCY_TEST_RUNTIME=600 -e MAXIMUM_LATENCY=20 registry.redhat.io/openshift4/cnf-tests-rhel8:v4.12 /usr/bin/test-run.sh -ginkgo.v -ginkgo.focus="oslat"
```

However with 7 CPU's the test fails with the following error:
```bash
Skip the test, the requested number of CPUs should be even to avoid noisy neighbor situation
```

### Complete error output 

```bash
# podman run -v $(pwd)/:/kubeconfig:Z -e KUBECONFIG=/kubeconfig/kubeconfig -e LATENCY_TEST_RUN=true -e DISCOVERY_MODE=true -e FEATURES=performance -e ROLE_WORKER_CNF=worker-cnf -e LATENCY_TEST_CPUS=7 -e LATENCY_TEST_RUNTIME=600 -e MAXIMUM_LATENCY=20 -e ACK_GINKGO_DEPRECATIONS=1.16.5 registry.redhat.io/openshift4/cnf-tests-rhel8:v4.12 /usr/bin/test-run.sh -ginkgo.v -ginkgo.focus="oslat"
running /usr/bin/validationsuite -ginkgo.v -ginkgo.focus=oslat
I0410 15:58:00.690783       7 request.go:601] Waited for 1.038310842s due to client-side throttling, not priority and fairness, request: GET:https://api.ocp4.oshift.rl:6443/apis/node.k8s.io/v1?timeout=32s
Running Suite: CNF Features e2e validation
==========================================
Random Seed: 1681142279
Will run 0 of 47 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 0 of 47 Specs in 0.000 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 47 Skipped
PASS
Discovery mode enabled, skipping setup
running /usr/bin/cnftests -ginkgo.v -ginkgo.focus=oslat
I0410 15:58:03.242609      17 request.go:601] Waited for 1.039514736s due to client-side throttling, not priority and fairness, request: GET:https://api.ocp4.oshift.rl:6443/apis/security.internal.openshift.io/v1?timeout=32s
time="2023-04-10T15:58:07Z" level=info msg="MAX_OFFSET_IN_NS not set, assuming 100 ns"
time="2023-04-10T15:58:07Z" level=info msg="MIN_OFFSET_IN_NS not set, assuming -100 ns"
Running Suite: CNF Features e2e integration tests
=================================================
Random Seed: 1681142282
Will run 1 of 223 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[performance] Latency Test with the oslat image 
  should succeed
  /remote-source/app/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go:153
Apr 10 15:58:07.478: [ERROR]: expected pointer, but got nil

S [SKIPPING] in Spec Setup (BeforeEach) [0.049 seconds]
[performance] Latency Test
/remote-source/app/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go:62
  with the oslat image [BeforeEach]
  /remote-source/app/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go:128
    should succeed
    /remote-source/app/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go:153

    Skip the test, the requested number of CPUs should be even to avoid noisy neighbor situation

    /remote-source/app/vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go:93
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
JUnit report was created: /junit.xml/cnftests-junit.xml

Ran 0 of 223 Specs in 8.261 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 223 Skipped
PASS
time="2023-04-10T15:58:15Z" level=info msg="There's no extra TC information to add to the xml file."
```

### What needs fixing?

The resolution is pass even number of CPU's e.g. `LATENCY_TEST_CPUS=10` through `podman`.

```bash
# podman run -v $(pwd)/:/kubeconfig:Z -e KUBECONFIG=/kubeconfig/kubeconfig -e LATENCY_TEST_RUN=true -e DISCOVERY_MODE=true -e FEATURES=performance -e ROLE_WORKER_CNF=worker-cnf -e LATENCY_TEST_CPUS=10 -e LATENCY_TEST_RUNTIME=600 -e MAXIMUM_LATENCY=20 registry.redhat.io/openshift4/cnf-tests-rhel8:v4.12 /usr/bin/test-run.sh -ginkgo.v -ginkgo.focus="oslat"
```

Working on the PR now, will send it ASAP.

### PR DESCRIPTION
**Pull request by rameshsahoo11**
…es/58468

Version(s):

PR applies to the in-development version (e.g. 4.12) and future versions: 4.12+

Issue: 58468

fixes https://github.com/openshift/openshift-docs/issues/58468

Link to docs preview:

https://github.com/rameshsahoo111/openshift-docs/blob/oslat-even-cpus-58468/scalability_and_performance/modules/cnf-performing-end-to-end-tests-running-oslat.adoc

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@aireilly, do you know who could provide QE for this one? (You added this line [here](https://github.com/openshift/openshift-docs/pull/44823).)

**Comment by aireilly** [comment]
@shajmakh PTAL at this small docs update. @ffromani gave LGTM.

**Comment by ffromani** [comment]
> @shajmakh PTAL at this small docs update. @ffromani gave LGTM.

Indeed I am. LGTM

**Comment by shajmakh** [comment]
Thanks for the update.
LGTM.

**Comment by nalhadef** [comment]
@ rameshsahoo111 The preview link is giving me a 404 error.

**Comment by rameshsahoo111** [comment]
@nalhadef preview link always shows 404, I believe it's github issue. Please review the details here. 
  https://github.com/openshift/openshift-docs/pull/58471/files

**Comment by rameshsahoo111** [comment]
@nalhadef the preview link shows 404 because no file listing available @ https://github.com/rameshsahoo111/openshift-docs/blob/oslat-even-cpus-58468/scalability_and_performance/modules

but if you checkout the branch, you will see the details in the code directory. I believe this is a GitHub issue.

**Comment by rameshsahoo111** [comment]
@nalhadef please find the preview link and let me know if there is anything. 
 https://github.com/rameshsahoo111/openshift-docs/blob/oslat-even-cpus-58468/modules/cnf-performing-end-to-end-tests-running-oslat.adoc

**Comment by kalexand-rh** [comment]
@nalhadef, the preview's here: https://58471--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-performing-platform-verification-latency-tests.html#cnf-performing-end-to-end-tests-running-oslat_cnf-latency-tests

**Comment by nalhadef** [comment]
Thanks, Kathryn. Ramesh got that for me earlier this morning. He is fixing
a typo and merging it. I just updated the labels, which I'd forgotten to do.

Neal

**Pull request merged**
