### PR TITLE
fixing wrong indentation in ClusterLogging Resource

### PR DESCRIPTION
**Pull request by tjungbauer**
Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by aireilly** [comment]
@obrown1205 made this change in https://github.com/openshift/openshift-docs/pull/52041 can you PTAL at this PR

**Comment by obrown1205** [comment]
> @obrown1205 made this change in #52041 can you PTAL at this PR

@aireilly @tjungbauer Hello! My change for the YAML was suggested by QE Anping Li. It wasn't my PR's original intent, but I updated it while I was in there. Looks like the nesting and order are changed. Could be needing that change - QE can confirm when approving. :)

**Comment by obrown1205** [comment]
@tjungbauer can you confirm once QE approves?

**Comment by tjungbauer** [comment]
the order does not matter, but the nesting is wrong. "collection" is not a child of logstore :)

**Comment by obrown1205** [comment]
> the order does not matter, but the nesting is wrong. "collection" is not a child of logstore :)

Sounds good! :)

**Comment by kalexand-rh** [comment]
@obrown1205, has this issue been resolved? Can we close this PR?

**Pull request closed without merging**
