### PR TITLE
OSDOCS-12642 RODOO 1.0.2 Release Notes OCP 4.14

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.14

Issue: [OSDOCS-12642](https://issues.redhat.com/browse/OSDOCS-12642)

[Link to docs preview:](https://85162--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/pods/run_once_duration_override/run-once-duration-override-release-notes.html#run-once-duration-override-operator-release-notes-1-0-2)

QE review:
- [X] QE has approved this change.

Additional information: Advisory link will not work until November 26th.

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
lgtm
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed

**Review by jldohmann — APPROVED** [review]
lgtm!

**Pull request merged**
