### PR TITLE
BZ1829650 - Adding RWO to recommended storage technology table.

### PR DESCRIPTION
**Pull request by pneedle-rh**
Applies to branch/enterprise-3.11.

Relates to https://bugzilla.redhat.com/show_bug.cgi?id=1829650.

Preview available at http://file.fab.redhat.com/~pneedle/optimizing_storage.html.

### CODE REVIEW

**Comment by pneedle-rh** [comment]
@openshift/team-documentation for peer review please. Please can someone also add 'Peer Review Needed', 'branch/enterprise-3.11' labels and 'Next Release' milestone? Thanks!

**Comment by pneedle-rh** [comment]
@qinpingli or @juzhao can you please review this from a QE perspective? Thanks!

**Comment by pneedle-rh** [comment]
@listey can you please review this from an SME perspective? Thanks!

**Comment by lamek** [comment]
LGTM.

**Comment by listey** [comment]
LGTM

**Comment by pneedle-rh** [comment]
@listey can you please review the further changes I have made to this PR, following conversations with @qinpingli? Namely, I have added Cinder to footnote 7 as well as removing reference to Cinder being adept in ROX access mode use cases. Thanks!

**Comment by pneedle-rh** [comment]
@qinpingli please let me know if you approve the document now that we have made those further changes. Thanks!

**Comment by qinpingli** [comment]
LGTM

**Comment by juzhao** [comment]
LGTM

**Comment by listey** [comment]
Looks good, LGTM

**Pull request merged**
