### PR TITLE
Update versions in Doc Guidelines

### PR DESCRIPTION
**Pull request by codyhoag**
@vikram-redhat can you confirm these versions, and merge if correct? I updated based on the [_distro_map.yml](https://github.com/openshift/openshift-docs/blob/master/_distro_map.yml) file. Thanks!

### CODE REVIEW

**Comment by vikram-redhat** [comment]
LGTM

**Comment by vikram-redhat** [comment]
Doesn't require any CP.

**Comment by codyhoag** [comment]
@vikram-redhat do we ignore the contributing guides on legacy branches (e.g., [here](https://github.com/openshift/openshift-docs/blob/enterprise-4.1/contributing_to_docs/doc_guidelines.adoc#product-name--version))? I had marked for legacy branches because the versions were off in those too. I see where it makes sense to only maintain the `master` version; just wanted to confirm for future reference.

**Comment by vikram-redhat** [comment]
@codyhoag correct. Those legacy guidelines shouldn't be linked from anywhere else. If you find them linked, go ahead and delete. Just the master is correct (we could probably delete them from the branches).

**Comment by codyhoag** [comment]
@vikram-redhat got it; yep, makes sense.

**Pull request merged**
