### PR TITLE
Bug 1283792: in ipfailover example, add callout explaining ‘$KUBECONFIG’

### PR DESCRIPTION
**Pull request by tnguyen-rh**
@rjhowe 
PTAL (re https://bugzilla.redhat.com/show_bug.cgi?id=1283792)

### CODE REVIEW

**Comment by rjhowe** [comment]
Instead of asking customers to replace $KUBECONFIG I recommend the following:

Replace the text to show the following instead of $KUBECONFIG
'/etc/origin/master/openshift-router.kubeconfig'
This follows the examples we give when deploying other objects like registry and router

Example:
 $ oadm router ha-router-us-west --replicas=3  \
      --service-account=ipfailover \
      --selector="ha-router=geo-us-west" \
      --labels="ha-router=geo-us-west" \
      --credentials="/etc/origin/master/openshift-router.kubeconfig'
      --service-account=ipfailover

ALSO this will need to be changed for the 2  other `oadm ipfailover` commands that are below this step in the doc.  
Question: When creating the ipfailover can it use the router cert with out issue? Or does the user need to create certs,keys,and kubeconfig for use by the ipfailover. 


2,  I really don't like this alternative buy you could add a line that defines the $KUBECONFIG variable. 

# KUBERCONFIG=<kubeconfiglocation>

@tnguyen-rh

**Comment by adellape** [comment]
> Replace the text to show the following instead of $KUBECONFIG
'/etc/origin/master/openshift-router.kubeconfig'
This follows the examples we give when deploying other objects like registry and router

+1

We should consider conditionalizing between OSE and Origin (as we do in the other mentioned topics). We know the file's location in OSE but can't be certain of it in Origin, depending on their installation method (though we could add a note saying we assume an advanced install method or something).

**Comment by tnguyen-rh** [comment]
@rjhowe @adellape PTAL
Thanks for the review and feedback.  I've updated the text as suggested.  Current state (overall difference) reflects:
- reformat examples for consistency
- add conditionals to use `$KUBECONFIG` in `openshift-origin` block
- replicate conditional block to use full filename in `openshift-enterprise` block
The conditional blocks are ordered `openshift-enterprise` followed by `openshift-origin`, inspired by the same ordering in [the admin guide router.adoc](https://github.com/openshift/openshift-docs/blob/master/admin_guide/router.adoc).

**Comment by adellape** [comment]
:+1: Looks good.

**Comment by adellape** [comment]
@tnguyen-rh Could use a squash. :boot:

**Comment by tnguyen-rh** [comment]
@adellape 
Rebased, squashed.
I note that https://github.com/openshift/openshift-docs/pull/1257 also deals w/ kubeconfig.  We should probably unify these approaches; adding followup label.

**Comment by adellape** [comment]
@tnguyen-rh Removing the `branch/enterprise-3.0` label from this because it references `/etc/origin`, which did not exist in OSE until 3.1 (it was `/etc/openshift/` previously).

**Comment by tnguyen-rh** [comment]
@adellape Thanks for catching that.

**Comment by bfallonf** [comment]
Removing the followup label from this PR. The edits here are to command labels, and don't really require anything to followup with.

**Pull request merged**
