### PR TITLE
Bug#1557164 - single-zone/multizone fixes and removed GCP

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1557164

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL
NOTE: This partly resolves https://bugzilla.redhat.com/show_bug.cgi?id=1557164, I will create another PR specific for 3.9 once this merges.

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :dog2:

**Pull request merged**
