### PR TITLE
Updating to OperatorHub to match web console

### PR DESCRIPTION
**Pull request by bergerhoffer**
@chrisnegus / @openshift/team-documentation For peer review please.

### CODE REVIEW

**Comment by chrisnegus** [comment]
LGTM. Thanks for cleaning that up!

**Comment by ahardin-rh** [comment]
Yes, thank you for doing this! :+1:

**Comment by mburke5678** [comment]
@bergerhoffer Where does OperatorHub appear? is this a forthcoming change? I see a space.`Operator Hub`

**Comment by bergerhoffer** [comment]
@mburke5678 I built a new version of the installer this morning and it had been updated, so it's a recent change.

**Pull request merged**
