### PR TITLE
OSSM-4795: Variable appears in code block

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OSSM-4795

Link to docs preview: https://64301--docspreview.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-create-smcp#ossm-deploy-cluster-wide-control-plane-console_ossm-create-smcp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by pbajjuri20 — APPROVED** [review]

**Comment by mayleighnmyers** [comment]
LGTM

**Review by mramendi — APPROVED** [review]

**Comment by rh-tokeefe** [comment]
Rebased on Sept 8

**Review by jeana-redhat — APPROVED** [review]
/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
