### PR TITLE
OCPBUGS28861 Remove CMA log validation statements

### PR DESCRIPTION
**Pull request by mburke5678**
https://issues.redhat.com/browse/OCPBUGS-28861

Removing CMA log validation statements per the research of @jkyros. 

Preview: [Custom Metrics Autoscaler Operator overview](https://71778--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/cma/nodes-cma-autoscaling-custom)  [Current docs to complete the before and after](https://docs.openshift.com/container-platform/4.14/nodes/cma/nodes-cma-autoscaling-custom.html)

### CODE REVIEW

**Comment by mburke5678** [comment]
@jkyros Please let me know if I understand your [comments in Slack](https://redhat-internal.slack.com/archives/C02F1J9UJJD/p1708031914101919?thread_ts=1708014390.847579&cid=C02F1J9UJJD) correctly.

**Comment by jkyros** [comment]
> @jkyros Please let me know if I understand your [comments in Slack](https://redhat-internal.slack.com/archives/C02F1J9UJJD/p1708031914101919?thread_ts=1708014390.847579&cid=C02F1J9UJJD) correctly.

@mburke5678 Yep, you do. We're not very consistent at all about what emits a log and what doesn't, so short of doing a pass to make all of those possible actions generate a log message, I think you're right that we should take this out so users aren't confused into thinking it's not working or scaling because they didn't get the log message when it otherwise is working just fine. 

 Ideally I feel like the customer shouldn't ever have to look in the logs during normal operation -- if they have to check the logs I feel like we screwed up filling in status somewhere or making it clear that we performed an action :( 

I notice you also took out the section about pausing -- I assume because we doc it other places (e.g. https://docs.openshift.com/container-platform/4.14/nodes/cma/nodes-cma-autoscaling-custom-pausing.html) and it was weird where it was?

**Comment by mburke5678** [comment]
> I notice you also took out the section about pausing -- I assume because it was weird where it was?

Absolutely!

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Pull request merged**
