### PR TITLE
cnv-docs: request users to set monitoring ns label

### PR DESCRIPTION
**Pull request by danielBelenky**
In CNV, we deploy a set of PrometheusRules wich supposed to be picked by
openshift's monitoring-operator. For that process to work properly, the
user has to label the namespace in which he deploys CNV.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

### CODE REVIEW

**Comment by danielBelenky** [comment]
setting hold because there might be an automated solution

**Comment by fabiand** [comment]
Yes, let's investigate the automated solution.

**Comment by vikram-redhat** [comment]
@danielBelenky is this still needed? If not can we close it?

@aburdenthehand

**Pull request closed without merging**
