### PR TITLE
TELCODOCS#1645: Removed tech preview notice

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s): 4.14+

Issue: [TELCODOCS-1645](https://issues.redhat.com/browse/TELCODOCS-1645)

Preview link: 
https://68705--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/enabling-workload-partitioning

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by danmacpherson** [comment]
/lgtm

Providing Docs ACK for Change Management

**Comment by sr1kar99** [comment]
@DanielFroehlich , @brandisher 
Can you please review this PR for change management.

**Comment by sr1kar99** [comment]
@CFields651 

Can you please review this PR for change management.

**Review by lahinson — COMMENTED** [review]
lgtm

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Review by skrthomas — COMMENTED** [review]
Merge review lgtm

**Pull request merged**
