### PR TITLE
Fix example how to disable registry cache

### PR DESCRIPTION
**Pull request by dmage**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662027, https://bugzilla.redhat.com/show_bug.cgi?id=1843002

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM - @dmage once @xltian signs off on it I'll go ahead and merge. Thanks! 

@xltian PTAL

**Comment by xltian** [comment]
@wzheng1  Can you review for QE?

Thanks

**Comment by wzheng1** [comment]
Acked by QE.

**Comment by bmcelvee** [comment]
Thank you @xltian and @wzheng1!

**Pull request merged**
