### PR TITLE
Bug 1913970 - Remove outdated content [enterprise-4.7]

### PR DESCRIPTION
**Pull request by rolfedh**
https://bugzilla.redhat.com/show_bug.cgi?id=1913970

### CODE REVIEW

**Comment by mburke5678** [comment]
LGTM

**Review by alanconway — COMMENTED** [review]
LGTM

**Comment by rolfedh** [comment]
@alexissolanas @linuxstudio @ptrknvk Please take a look. Thanks.

**Comment by rolfedh** [comment]
@alexissolanas @linuxstudio @ptrknvk Please take a look. Thanks.

**Comment by bobfuru** [comment]
LGTM

**Pull request merged**
