### PR TITLE
Fixing oc-mirror download file name

### PR DESCRIPTION
**Pull request by bergerhoffer**
Preview: https://deploy-preview-43347--osdocs.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#installation-oc-mirror-installing-plugin_installing-mirroring-disconnected

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@afflom @zhouying7780 can you please review this update?

Preview: https://deploy-preview-43347--osdocs.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected.html#installation-oc-mirror-installing-plugin_installing-mirroring-disconnected

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Pull request merged**
