### PR TITLE
OSDOCS-2603: ROSA doc pre-req update: CreateServiceLinkedRole

### PR DESCRIPTION
**Pull request by nermina-redhat**
for dedicated-4

https://issues.redhat.com/browse/OSDOCS-2603

Preview: https://deploy-preview-38688--osdocs.netlify.app

### CODE REVIEW

**Comment by nermina-redhat** [comment]
@okashi18 @arendej please review

**Comment by arendej** [comment]
The previous doesn't seem to be showing the right location.

**Comment by nermina-redhat** [comment]
The preview?

**Comment by nermina-redhat** [comment]
https://deploy-preview-38688--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started_sts/rosa-sts-aws-prereqs.html

**Review by arendej — APPROVED** [review]
excellent

**Comment by bmcelvee** [comment]
LGTM!

**Comment by yuwang-RH** [comment]
LGTM~

**Pull request merged**
