### PR TITLE
Bug 1871802: customer feedback to make yaml filename consistent

### PR DESCRIPTION
**Pull request by skrthomas**
https://bugzilla.redhat.com/show_bug.cgi?id=1871802
 For 4.5+

Doc preview URL: https://deploy-preview-31206--osdocs.netlify.app/openshift-enterprise/latest/installing/install_config/installing-customizing.html#installation-special-config-chrony_installing-customizing

Ready for QE: @jiajliu

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM! 
Added labels for 4.5+ per BZ description. And removed bug labels from bot as they seem unnecessary.

**Comment by jiajliu** [comment]
LGTM, seems a small update of name, may @jianlinliu can give a confirm about this part.

**Comment by jianlinliu** [comment]
LGTM.

**Pull request merged**
