### PR TITLE
OSDOCS-4394:updates compute node support in 4.9 RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-4394](https://issues.redhat.com//browse/OSDOCS-4394): updates the compute node support in 4.9 RNs 

Version(s):
4.9

Issue:
[Jira](https://issues.redhat.com/browse/OSDOCS-4394)

Link to docs preview:
[Preview](https://joealdinger.github.io/openshift-docs/OSDOCS-4394/release_notes/ocp-4-9-release-notes.html)

QE review:
- [ ] QE has approved this change.

Additional information:
#52593

### CODE REVIEW

**Review by Wiharris — COMMENTED** [review]
/LGTM

**Comment by sdodson** [comment]
LGTM, thanks

**Pull request merged**
