### PR TITLE
Bug 1403385 added from section to custom builds

### PR DESCRIPTION
**Pull request by bfallonf**
As per: https://bugzilla.redhat.com/show_bug.cgi?id=1403385

@tiwillia can I get an ack this was all you were hoping for for this BZ? Thanks!

### CODE REVIEW

**Comment by tiwillia** [comment]
Looks great, thanks @bfallonf :tada:

**Comment by bfallonf** [comment]
Thanks, @tiwillia 

@ahardin-rh @adellape @gaurav-nelson @bmcelvee any thoughts before I merge?

**Comment by gaurav-nelson** [comment]
@bfallonf :ballot_box_with_check: LGTM

**Comment by bfallonf** [comment]
Thanks. I'll merge.

**Comment by bfallonf** [comment]
[rev_history]
|xref:../dev_guide/builds.adoc#dev-guide-builds[Builds]
|Added the xref:../dev_guide/builds.adoc#custom-strategy-from[FROM Image] section.
%

**Pull request merged**
