### PR TITLE
[enterprise-4.10] Fixing Azure Marketplace manifest directory

### PR DESCRIPTION
**Pull request by bscott-rh**
Fixing an incorrect URL in the Azure Marketplace installation procedure on editing manifests.

Merge to 4.10 and CP to 4.8 and 4.9.

Doc preview: https://bscott-rh.github.io/openshift-docs/azure-manifest-fix/installing/installing_azure/installing-azure-customizations.html#installation-azure-marketplace-manifests_installing-azure-customizations

### CODE REVIEW

**Comment by bscott-rh** [comment]
@MayXuQQ Hello May, can you take a look at this change? @mjpytlak found that the [KCS article ](https://access.redhat.com/articles/6484031) has an incorrect URL in step 2 of the manifest editing procedure. Please let me know if my update in this PR is accurate. Thank you

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-needed
/label peer-review-in-progress

**Comment by mjpytlak** [comment]
@tmalove Looks like we might have picked this up at the same time. Sorry about the labels.

**Comment by tmalove** [comment]
No worries @mjpytlak , this happens. I will go ahead and continue.

**Review by tmalove — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/LGTM

**Pull request merged**
