### PR TITLE
Jira: OSDOCS-1950 - Remove the --watch argument from create cluster

### PR DESCRIPTION
**Pull request by kmccarron-rh**
Jira: https://issues.redhat.com/browse/OSDOCS-1950

Removed the --watch argument from the create cluster command CLI, ROSA Quickstart topic and Using a Bash script.

Links to updated content:
https://deploy-preview-30578--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-quickstart.html
https://deploy-preview-30578--osdocs.netlify.app/openshift-rosa/latest/rosa_cli/rosa-manage-objects-cli.html#rosa-create-cluster_rosa-managing-objects-cli
https://deploy-preview-30578--osdocs.netlify.app/openshift-rosa/latest/rosa_cli/rosa-get-started-cli.html#rosa-using-bash-script_rosa-getting-started-cli

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
@vkareh will you please review?

**Comment by sfortner-RH** [comment]
LGTM!

**Comment by kmccarron-rh** [comment]
@sfortner-RH - QE ack received in the card. Looks like we are good to merge!

**Pull request merged**
