### PR TITLE
SRVCOM-1288 + SRVCOM-1664: Clean up attributes, prereqs

### PR DESCRIPTION
**Pull request by abrennan89**
Jiras: https://issues.redhat.com/browse/SRVCOM-1288 + https://issues.redhat.com/browse/SRVCOM-1664

Applies for OCP 4.6+

Direct preview links:
- https://deploy-preview-41712--osdocs.netlify.app/openshift-enterprise/latest/serverless/discover/serverless-channels.html
- https://deploy-preview-41712--osdocs.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-creating-channels.html
- https://deploy-preview-41712--osdocs.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-subs.html
- https://deploy-preview-41712--osdocs.netlify.app/openshift-enterprise/latest/serverless/develop/serverless-custom-event-sources.html

### CODE REVIEW

**Comment by jrangelramos** [comment]
LGTM

**Comment by stevsmit** [comment]
/lgtm

That said, there are instances I've noticed where you say "Topology view" and "Topology page", (yesterday I noticed you said "Topology View"). I'm not sure if there's a difference, just raising a small point, I guess!

**Pull request merged**
