### PR TITLE
OCPBUGS#25247: External gateway is on default network

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OCPBUGS-25247

Changing of words.

Version(s): 4.14+

Issue:

Link to docs preview: https://71228--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-secondary-external-gateway

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@jordigilh, I've updated this to omit any mention of secondary networks.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by jab-rh** [comment]
@trozet, can you confirm as well? Thanks!

**Comment by jab-rh** [comment]
@tshefi, can you confirm that this makes sense? Thanks!

**Comment by tshefi** [comment]
@jab-rh Yeah makes sense, good from my point of view.

**Review by kowen-rh — APPROVED** [review]
LGTM! :+1: 

/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
