### PR TITLE
TELCODOCS#1759: Added must gather images for LVM Operator

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.12

Issue:
[TELCODOCS-1759](https://issues.redhat.com/browse/TELCODOCS-1759)

Link to docs preview:
https://71116--ocpdocs-pr.netlify.app/openshift-enterprise/latest/support/gathering-cluster-data#gathering-data-specific-features_gathering-cluster-data

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
@jakobmoellerdev 
Can you please review this PR?
Thanks.

**Review by jakobmoellerdev — APPROVED** [review]
/lgtm

**Comment by sr1kar99** [comment]
@radeore 
Can you please review this PR?
Thanks.

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging!

**Pull request merged**
