### PR TITLE
WIP Update command to verify Network Operator config

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1707239

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
please also update the following part in the above docs:
```
   proxyArguments:
   - "iptables-min-sync-period": ["30s"]
```
to
```
    proxyArguments:
       iptables-min-sync-period: ["30s"]
```

and you can also add `iptables-min-sync-period` parameters in the `oc get networks.operator.openshift.io -o yaml` :
```
    kubeProxyConfig:
      bindAddress: 0.0.0.0
      iptablesSyncPeriod: 30s
      proxyArguments:
        iptables-min-sync-period:
        - 30s
```

**Comment by jboxman** [comment]
Hi @zhaozhanqi,

I've rewritten this and created a new PR (https://github.com/openshift/openshift-docs/pull/14705). I'll apply this change there.

**Comment by jboxman** [comment]
@zhaozhanqi, I've applied the change in https://github.com/openshift/openshift-docs/pull/14705/commits/7dc72de2997a128a42b517387911747a8de5659b.

**Comment by zhaozhanqi** [comment]
@jboxman 
 according to PR 14705 comments , we just keep the parameter 'iptablesSyncPeriod: 30s' in the docs. the others should not be supported until now.

**Comment by jboxman** [comment]
Sounds good -- I'm going to close this in favor of #14705.

**Pull request closed without merging**
