### PR TITLE
Bug 1413729 Added a note clarifying the use of `<service.name>.<service.namespace>.svc`

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1413729

### CODE REVIEW

**Comment by bmcelvee** [comment]
I added a note note clarifying the use of `<service.name>.<service.namespace>.svc` in the Service Serving Certificates section. 

@duyanyan @sferich888 PTAL

**Comment by bmcelvee** [comment]
According to the Bug 1413729, this note is only necessary until Bug 1393486 is complete. Is there a procedure or are there follow up steps required for these circumstances?

@adellape @vikram-redhat @aheslin @ahardin-rh

**Comment by adellape** [comment]
> According to the Bug 1413729, this note is only necessary until Bug 1393486 is complete. Is there a procedure or are there follow up steps required for these circumstances?

I suggested to @bmcelvee via IRC to just make a cross-reference note in BZ 1393486 after this PR is done that these docs may need to be updated if/when it's implemented.

**Comment by bmcelvee** [comment]
Would you be willing to give this one last sanity check? Thanks! @ahardin-rh

**Comment by ahardin-rh** [comment]
LGTM :+1:

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/secrets.adoc#service-serving-certificate-secrets[Service Serving Certificate Secrets]
|Added a note to the xref:../dev_guide/secrets.adoc#service-serving-certificate-secrets[Service Serving Certificate Secrets] section clarifying the use of the service DNS name.
%

**Pull request merged**
