### PR TITLE
[enterprise-4.15] OCPBUGS-31413: Remove mention of PtpConfigSlaveCvl.yaml from docs

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.15

Issue: https://issues.redhat.com/browse/OCPBUGS-31413

Link to docs preview:

- https://85630--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/ztp-advanced-policy-config.html#ztp-configuring-ptp-fast-events_ztp-advanced-policy-config
- https://85630--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/ztp-advanced-policy-config.html#ztp-configuring-ptp-fast-events-amqp_ztp-advanced-policy-config

QE review:
- [x] QE has approved this change.

Additional information:
PR for main: https://github.com/openshift/openshift-docs/pull/85629

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]
/lgtm

**Review by bscott-rh — APPROVED** [review]
Peer review LGTM.

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Pull request merged**
