### PR TITLE
[enterprise-4.12] OSDOCS-6652 AWS shared private hosted zones

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-6577

Link to docs preview:
https://72445--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-vpc#installation-custom-aws-vpc-requirements_installing-aws-vpc

QE review:
- [ ] QE has approved this change.

4.12 backport of https://github.com/openshift/openshift-docs/pull/64114

### CODE REVIEW

**Comment by bscott-rh** [comment]
@yunjiang29 PTAL at this docs PR backporting AWS shared private zones to 4.12 documentation. Thank you

**Comment by kalexand-rh** [comment]
@yunjiang29, PTAL?

**Comment by yunjiang29** [comment]
@kalexand-rh please see comments at https://issues.redhat.com/browse/OSDOCS-6577

**Comment by bscott-rh** [comment]
Closing PR as Shared VPC is not supported in 4.12.

**Pull request closed without merging**
