### PR TITLE
PR5007-Follow-up Edits to Waiting for Template Readiness Section

### PR DESCRIPTION
**Pull request by bmcelvee**
https://trello.com/c/crYjd3zB/593-document-template-completion-detection-templatebroker

Follow-up edits to https://github.com/openshift/openshift-docs/pull/5007/.

### CODE REVIEW

**Comment by bmcelvee** [comment]
@jim-minter PTAL

**Comment by jim-minter** [comment]
@bmcelvee lgtm, thanks for the improvements.

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
@bmcelvee LGTM 🎆

**Comment by mburke5678** [comment]
@bmcelvee +1

**Pull request merged**
