### PR TITLE
[BZ2079656]:Correct the storage space value for the compute and control nodes

### PR DESCRIPTION
**Pull request by xenolinux**
This PR fixes the recommended storage space value for both compute and control nodes.

Version(s): 4.6+

QE contact:

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2079656

Link to docs preview: 

-  https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-control-compute-machines_installing-openstack-installer-custom
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-kuryr.html#installation-osp-control-compute-machines_installing-openstack-installer-kuryr
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-sr-iov.html#installation-osp-control-compute-machines_installing-openstack-installer-sr-iov
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-ovs-dpdk.html#installation-osp-control-compute-machines_installing-openstack-installer-ovs-dpdk
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user.html#installation-osp-control-compute-machines_installing-openstack-user
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user-kuryr.html#installation-osp-control-compute-machines_installing-openstack-user-kuryr
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-user-sr-iov.html#installation-osp-control-compute-machines_installing-openstack-user-sr-iov
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-restricted.html#installation-osp-control-compute-machines_installing-openstack-installer-restricted
- https://deploy-preview-45916--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-bootstrap-machine_installing-openstack-installer-custom 

Additional information:

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
We should update [modules/installation-osp-bootstrap-machine.adoc](https://github.com/openshift/openshift-docs/blame/bc18d884b0529228c773209d526ec87a2ea82a65/modules/installation-osp-bootstrap-machine.adoc#L17) as well, since the bootstrap machine uses the same flavor as the master nodes.

**Review by mandre — COMMENTED** [review]
LGTM from engineering.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Pull request merged**
