### PR TITLE
structure: sequence as generic then vendor specific cloud and onprem

### PR DESCRIPTION
**Pull request by sean-freeman**
Address GH Issue #81621 for inconsistent documentation navigation structure. The commit is nonintrusive and does not alter the structure of any topic object.

Version(s):
4.17, do not cherry pick as this file is likely to have changed between each version

Issue:
- None (GH or Jira), this is community author contribution

QE review:
- [ ] QE has approved this change.

Additional information:
- n/a

#### The structure from this PR will reflect:

```yaml
# generic
- Name: Installation overview
- Name: Installing on any platform
- Name: Installing on-premise with the Assisted Installer
- Name: Installing on-premise with the Agent-based Installer
- Name: Installing on a single node
- Name: Installing on bare metal with the UPI Installer
- Name: Installing on bare metal with the IPI Installer
- Name: Installation configuration
# vendor-specific, type Cloud IaaS
- Name: Installing on Alibaba Cloud
- Name: Installing on AWS
- Name: Installing on Azure
- Name: Installing on GCP
- Name: Installing on IBM Cloud
- Name: Installing on IBM Power Virtual Server
- Name: Installing on IBM Cloud (Classic)
- Name: Installing on OCI
# vendor-specific, type On-Premise 
- Name: Installing on Azure Stack Hub
- Name: Installing on IBM Power
- Name: Installing on IBM Z and IBM LinuxONE
- Name: Installing on Nutanix
- Name: Installing on OpenStack
- Name: Installing on VMware vSphere
- Name: Validation and troubleshooting
```

#### The following renames occured for fixing bad descriptions

```
Installing on bare metal
>>>
Installing on bare metal with the UPI Installer
```

```
Deploying installer-provisioned clusters on bare metal
>>>
Installing on bare metal with the IPI Installer
```

#### The following renames occured for consistency

```
Installing on-premise with Assisted Installer
>>>
Installing on-premise with the Assisted Installer
```

```
Installing an on-premise cluster with the Agent-based Installer
>>>
Installing on-premise with the Agent-based Installer
```

```
Installing IBM Cloud Bare Metal (Classic)
>>>
Installing on IBM Cloud (Classic)
```

```
Installing on vSphere
>>>
Installing on VMware vSphere
```

### CODE REVIEW

**Comment by sean-freeman** [comment]
@kalexand-rh @bscott-rh @sheriff-rh Mentioning you all, as GH Issue template requests @openshift/team-documentation [which does not work] is mentioned after PR is raised.

**Comment by kalexand-rh** [comment]
@sean-freeman Major topic map changes are very disruptive to both other changes that are in process in the repo and the publication pipeline between [docs.openshift.com](http://docs.openshift.com/) and [docs.redhat.com](http://docs.redhat.com/). Additionally, rearranging the order of the platforms is more likely to confuse customers and support staff who are accustomed to the current layout.

**Comment by sean-freeman** [comment]
@kalexand-rh

Two points to counteract that I hope you re-consider.

1. As described in relation to the nonintrusive approach of this PR, the changes are top-level with a combination alphabetical + logical technical order. I cannot agree that customers or support staff would struggle to adapt to an improvement like this; to be a bit flippant, to use Kubernetes an IQ has to be pretty high as-is and a 10 year old would be able to adapt to a navigation menu minor re-ordering.

    1. there are no changes in the below structures and no changes to any existing URLs, nothing will be altered for support staff bookmarks etc.

    1. the only title changes are fixes to incorrectly labelled topic areas that, in their current form, would be confusing to customers and support staff

2. "Keeping the way it has always been" is not an appropriate response to a sensible suggestion that aids the future usability of documentation.


As stated, I hope you consider re-opening this until others (@bscott-rh , @sheriff-rh) have the opportunity to weigh-in.

It is open-source etiquette not to immediately close a PR that is of community benefit, has taken due care and time to prepare.

**Comment by bscott-rh** [comment]
@sean-freeman I am in agreement with Kathryn. While I am appreciative of the effort you put into these PRs, I do not see a benefit to the community that justifies the rearrangement of the topic map. Are there customer cases or feedback from OpenShift TAMs or support staff that led to the structure that you came up with? I'm happy to work with you on content improvements for community benefit, but rearranging the topic map in the middle of migrating to docs.redhat.com is not beneficial.

**Comment by sean-freeman** [comment]
@bscott-rh I did not have the context that migration to Red Hat KB is occuring - the documentation sites look like permenant mirrors as there is no notification banner on `docs.openshift.com` of ongoing relocation for the documents.

> I don't think any TAM will specifically flag problems against the documentation, they have to respond to the customer much faster than that and end-user gripes about poor documentation flow / labelling are immediately forgotten when someone provides the URL they are looking for (so they can get on with what they were doing).
>
> You'd be better off analysing the count of "can't find" or "where is" + "documentation" / "guide" across all Red Hat Support Cases in the past 12 months. Or a survey to all TAM's with a question `'How often do you ask for help finding documentation for your customer?'`.

I would actually argue the re-order is even more critical given the unstructured tile style of Red Hat KB, as opposed to the structure list style of `docs.openshift.com`. At the moment the topic map really follows no logical or alphabetical structure at all; throw into that mix, 2x poorly described titles and 4x inconsistent titles titles as corrected above. But at least it is visible in 1 condensed line, the tiles push content hidden by scroll from end-user's eyesight.

End-users will find it hard to see the generic documentation for installing (and therein their available options), when it is buried amongst vendor-specific Infrastructure Platform documentation:

image

**Pull request closed without merging**
