### PR TITLE
OBSDOCS-683: fix small bug in module ID and formatting

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OBSDOCS-683

Link to docs preview:
https://69022--docspreview.netlify.app/openshift-enterprise/latest/logging/log_collection_forwarding/log-forwarding#logging-http-forward_log-forwarding

QE review:
N/A

### CODE REVIEW

**Review by libander — APPROVED** [review]
/lgtm

**Review by skopacz1 — APPROVED** [review]
LGTM!

**Pull request merged**
