### PR TITLE
OSSM-5786: Extend cleanup commands about ossm-cni resources

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): OCP 4.12+

Issue: https://issues.redhat.com/browse/OSSM-5786

Link to docs preview: https://70583--ocpdocs-pr.netlify.app/openshift-enterprise/latest/service_mesh/v2x/removing-ossm#ossm-remove-cleanup_removing-ossm

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mkralik3** [comment]
LGTM

**Review by pbajjuri20 — APPROVED** [review]

**Review by mramendi — COMMENTED** [review]
lgtm, but as I am in peer review squad induction, @JoeAldinger will finish the review

**Comment by rh-tokeefe** [comment]
I just realized that in the description I initially mentioned this PR as part of the upcoming Service Mesh 2.5 release. It is not. This is an update to previously published content and, if approved, can be merged prior to the 2.5 release.

**Pull request merged**
