### PR TITLE
OSDOCS#5597: Added regionalized AWS STS URLs to the allow list for PrivateLink (DRAFT)

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
4.12, 4.13

Issue:
https://issues.redhat.com/browse/OSDOCS-5597

Link to docs preview:
https://58175--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html#osd-aws-privatelink-firewall-prerequisites_prerequisites
https://58175--docspreview.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-sts-about-iam-resources.html#rosa-sts-oidc-provider-for-operators-aws-cli_rosa-sts-about-iam-resources

QE review:
- [x] QE has approved this change.

Additional information: None

### CODE REVIEW

**Comment by vkareh** [comment]
LGTM

/cc @jharrington22 can you confirm that the OIDC sts.amazonaws.com endpoint can/should be regionalized as well?

**Comment by yuwang-RH** [comment]
LGTM~

**Review by adellape — APPROVED** [review]

**Comment by adellape** [comment]
@laubai I wasn't sure if the merge-review request was meant to be a peer-review request, because I didn't see the peer review done on here yet (also noticed the "DRAFT" in PR title still), so I didn't want to assume merge-ability. But I've done peer review instead on it for now; please just re-queue for merge-review at this point.

**Comment by laubai** [comment]
Thanks @adellape, I must have gotten my wires crossed. Re-queuing now!

**Comment by stevsmit** [comment]
LGTM!

**Pull request merged**
