### PR TITLE
OCPBUGS#16643: Updated storage class name in YAML configurations

### PR DESCRIPTION
**Pull request by sr1kar99**
Version(s):
4.12+

Issue:
[OCPBUGS-16643](https://issues.redhat.com/browse/OCPBUGS-16643)

Link to docs preview:
[Preview](https://75123--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-local.html)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by sr1kar99** [comment]
Hi @jsafrane 
Could you please review this PR?
Thanks!

**Comment by jsafrane** [comment]
lgtm from storage engineering point of view.

**Comment by sr1kar99** [comment]
@duanwei33 
Could you please review this PR?
Thanks!

**Comment by duanwei33** [comment]
Hi @sr1kar99, thanks for the fix! 
I think we need to update the following two places when verifying persistent volumes with `Example output`, the pv's storageclass name should be the same one defined in LSO CR (currently they are all `local-sc`)

https://github.com/openshift/openshift-docs/pull/75123/files#diff-82096208e0c1757b8d751aed72124301f6df289a29f72e243a8dda6cd3c2503cL109
-> is using `local-storage`
https://github.com/openshift/openshift-docs/pull/75123/files#diff-903db9d256758dca30cd6acced08966e4fc9ab4f44e57e9d045f137217d5b658L143
-> is using `example-storageclass`

**Comment by dfitzmau** [comment]
Hi @sr1kar99 . Jira will need story points, version labels for 4.13+.

**Comment by dfitzmau** [comment]
/remove-label peer-review-in-progress

/label peer-review-done

Nice work, @sr1kar99 . Just added some Jira-related comments. LGTM!

**Comment by lpettyjo** [comment]
LGTM

**Comment by sr1kar99** [comment]
> /remove-label peer-review-in-progress
> 
> /label peer-review-done
> 
> Nice work, @sr1kar99 . Just added some Jira-related comments. LGTM!

Hi @dfitzmau 
Thanks for the review! Updated JIRA as per the suggestions.

**Comment by sr1kar99** [comment]
Hi @mburke5678 
Cherry-picked to 4.12, 4.13, and 4.14.
Could you please merge these PRs?
Thanks!

**Pull request merged**
