### PR TITLE
Change link to origin template

### PR DESCRIPTION
**Pull request by ghost**
@jsafrane PTAL. This is a follow-up to https://github.com/openshift/openshift-docs/pull/7901. In addition to fixing the link, I made some additional changes to ensure consistency with our writing style guide.

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm

**Comment by ahardin-rh** [comment]
LGTM :star2:

**Comment by tmorriso-rh** [comment]
@vikram-redhat This pull request has been reviewed (QE/SME/peer) and merged. This needs to be cherry picked to 3.7 and 3.9.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - this is still pending. Did you want to have a go at this one yourself and then tag me before merging into 3.7 and 3.9?

**Comment by tmorriso-rh** [comment]
@vikram-redhat I scheduled a review session for Monday.

**Pull request merged**
