### PR TITLE
[BZ2091564] Change Prometheus version to 0.4.1

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.9 and later

Issue:

- https://bugzilla.redhat.com/show_bug.cgi?id=2091564
- https://issues.redhat.com/browse/MULTIARCH-2398

Link to docs preview: Netlify is currently not working. I'm working on shared folder request. Will add a preview once that's working. 

Additional information:

Changing the Prometheus version to 0.4.1, which works for x86, s390x, ppc64le. 

QE review: 
IBM Z: Nishant Chauhan
x86: juzhao@redhat.com

### CODE REVIEW

**Comment by n-chauhan** [comment]
LGTM.

**Review by Chandan-Abhyankar — COMMENTED** [review]
Changes are fine

**Pull request merged**
