### PR TITLE
Added para as per #8213

### PR DESCRIPTION
**Pull request by bfallonf**
For #8213 
@JacobTanenbaum not sure what happened, but the sdn.adoc file should not be there. I've moved the note box to the right file (the same info but made more modular) and some rewording. Please let me know if you have any suggestions for changes.

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
lgtm 
thanks @bfallonf

**Comment by vikram-redhat** [comment]
@bfallonf - looks like the sdn.adoc file wasn't deleted, but the contents were migrated to the topics. That file still existed in the core_concepts folder and therefore, an easy mistake for @JacobTanenbaum or anyone else to make. 

Can you double check now that the other files that were moved via https://github.com/openshift/openshift-docs/pull/5000/files were actually moved (that is, the original file was deleted).

**Comment by bfallonf** [comment]
@vikram-redhat Rest of it all looks fine. Should be solved by this PR.

**Comment by gaurav-nelson** [comment]
@bfallonf LGTM 👍

**Comment by bfallonf** [comment]
Thanks @gaurav-nelson . I'll merge.

**Pull request merged**
