### PR TITLE
Add ose-recycler to the required images

### PR DESCRIPTION
**Pull request by juanluisvaladas**
ose-recycler is needed to recycle released PV when
its reclaimpolicy is recycle. 
Fixes issue #4013

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
Bump

**Comment by ahardin-rh** [comment]
@juanluisvaladas Thanks! Sorry for the delay. To help with our publishing process, this needs squashed into one commit please.  Also, I have this labeled for the OCP 3.3 and later docs. Please let me know if this needs updated. Thanks again!

**Comment by ahardin-rh** [comment]
@juanluisvaladas Oh nice! I just noticed that as an option. That works! Disregard my comment on squashing then. :star2:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/disconnected_install.adoc#install-config-install-disconnected-install[Disconnected Installation]
|Added `ose-recycler` to the required images in the xref:../install_config/install/disconnected_install.adoc#disconnected-syncing-images[Syncing Images] section.
%

**Comment by vikram-redhat** [comment]
The squash commit doesn't seem to have worked. The PR still contains the original 3 commits instead of the new one.

I will take this out of the weekly release and manually apply the new commit. 

@juanluisvaladas @ahardin-rh - till we can figure out why, don't use the GitHub's Web UI to squash commits.

**Comment by juanluisvaladas** [comment]
@vikram-redhat the PR indeed has all the 3 commits but it should have them, it's a different branch which nobody cares about it anymore.

The master branch,  only has one commit. https://github.com/openshift/openshift-docs/commit/2cc8208b7c14532cc5cefe71cde7f51757f5e016 and it's the one you should care about having a clean history.

This is git expected behaviour.

**Comment by vikram-redhat** [comment]
@juanluisvaladas yup that is correct. However, our workflow script relies on the original PR containing the squashed commit (it can work on multiple commits, but we prefer a single commit).

**Pull request merged**
