### PR TITLE
add a section to the route docsfor the setting of server side timeouts using annotations

### PR DESCRIPTION
**Pull request by ahardin-rh**
Continues https://github.com/openshift/openshift-docs/pull/2619

### CODE REVIEW

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added a new xref:../architecture/core_concepts/routes.adoc#route-specific-timeouts[Route-specific Timeouts] section.
%

**Comment by knobunc** [comment]
Aah.  I missed that this was committed to 3.2.  It is a 3.3 feature and will not work with 3.2.

Bug 1383731 mentions this.

**Comment by ahardin-rh** [comment]
Thanks @knobunc and sorry that I mislabeled this. 

This is reverted for enterprise-3.2 and dedicated-3.2 via

- https://github.com/openshift/openshift-docs/pull/3041
- https://github.com/openshift/openshift-docs/pull/3042

**Comment by knobunc** [comment]
@ahardin-rh no worries.  I'm sorry I missed that earlier.  Thanks for the prompt reversion.

**Pull request merged**
