### PR TITLE
OSDOCS-7596: correct space in attribute code block notation

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13, 4.14+

Issue:
https://issues.redhat.com/browse/OSDOCS-7596

Link to docs preview:
https://64373--docspreview.netlify.app/microshift/latest/microshift_troubleshooting/microshift-troubleshoot-backup-restore#troubleshoot-backup-restore-microshift-backup-logs
https://64373--docspreview.netlify.app/microshift/latest/microshift_running_apps/microshift-greenboot-workload-scripts#microshift-greenboot-test-workload-health-check-script_microshift-greenboot-workload-scripts
https://64373--docspreview.netlify.app/microshift/latest/microshift_backup_and_restore/microshift-backup-and-restore#stopping-microshift-service_microshift-backup-and-restore
https://64373--docspreview.netlify.app/microshift/latest/microshift_backup_and_restore/microshift-backup-and-restore#microshift-backing-up-manually_microshift-backup-and-restore
https://64373--docspreview.netlify.app/microshift/latest/microshift_install/microshift-greenboot

QE review:
- N/A, docs plumbing

Additional information: This PR addresses a peer review comment on MicroShift, but applies repo-wide. Adding all the previews was too much, so please check the Files Changed for other sections.

### CODE REVIEW

**Comment by aldiazRH** [comment]
ROSA parts LGTM!

**Comment by stevsmit** [comment]
Would you mind fixing this one: 

. Create the machine config by running the following command:
+
[source,yaml]
----
$ oc create -f <file-name>.yaml
----

Should be [source,terminal]

**Comment by stevsmit** [comment]
Just the one request above. LGTM.

**Review by jeana-redhat — APPROVED** [review]
/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
