### PR TITLE
Follow-up edits to PR#2291

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/2291

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@tnguyen-rh @bfallonf @tpoitras PTAL :rocket:

**Comment by tnguyen-rh** [comment]
@ahardin-rh LGTM

**Comment by bfallonf** [comment]
@ahardin-rh LGTM!

**Comment by ahardin-rh** [comment]
@tnguyen-rh @bfallonf Thanks! Mergin' :balloon:

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Added the xref:../install_config/aggregate_logging.adoc#aggregate-logging-performing-elasticsearch-maintenance-operations[Performing Elasticsearch Maintenance Operations] section.
%

**Pull request merged**
