### PR TITLE
Fixed typo related to API port referenced in oc login

### PR DESCRIPTION
**Pull request by rvanderp3**
This PR applies to version 4.2 and later.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@neal-timpe, do you have a suggestion for a QE reviewer?

**Comment by kalexand-rh** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1822267

**Comment by neal-timpe** [comment]
@tvieira This looks correct to me when I test it. Can you confirm?

**Comment by tvieira** [comment]
@neal-timpe this is correct

**Review by tvieira — APPROVED** [review]

**Review by neal-timpe — APPROVED** [review]

**Pull request merged**
