### PR TITLE
[Serverless] Synced Travis CI changes from main

### PR DESCRIPTION
**Pull request by gaurav-nelson**
There were changes in scripts and Travis CI files which were not cherry-picked into new distro branches. This PR includes all the changes.

Cherry-pick into:
- `serverless-docs-1.28`
- `serverless-docs-1.29`
- `serverless-docs-1.30`

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@gabriel-rh Please merge and cherrypick this one.

**Comment by gabriel-rh** [comment]
serverless-docs-1.29

**Comment by gabriel-rh** [comment]
serverless-docs-1.30

**Pull request merged**
