### PR TITLE
Remove duplicate paragraph about logging

### PR DESCRIPTION
**Pull request by bmillemathias**
Fix issue #17472

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@mburke5678 @aburdenthehand - is this just an error due to forgetting to conditionalize the preceding text? Or that text does need removing?

We should also move this to master once we know.

**Comment by jboxman** [comment]
I couldn't make heads nor tails of it. The duplicate text is deep within the second conditional, so it should _not_ appear stacked like it does. The only conclusion I can come to is that _Asciidoctor_ is injecting the first conditional with that para after the conditional with the second instance of the para; otherwise, the ordering in the rendered document is impossible to achieve.

So this may be a bug in _Asciidoctor_ itself.

I made no attempts to render it to confirm this hypothesis, however.

**Comment by aburdenthehand** [comment]
@jboxman I'm inclined to agree. 
It's not an unresolved tag from an earlier module (tested by removing all prior content).
It seems to be the way asciibinder parses the conditionals. I thought it might be because there are two ifndef::cnv-logging[] in a single ifdef::openshift*[] conditional but I ruled that out by closing the idef::openshift conditional and opening a second one for this particular para - and the problem persisted. 

The best I've been able to get so far is to change the second ifndef::cnv-logging[] (the one surrounding the problem para) into an ifdef::!cnv-logging[] conditional. This stops the para repeating in the openshift logging assembly, but does not stop this para being built in the cnv assembly. 
Will come back to this in the afternoon.

**Comment by aburdenthehand** [comment]
Thanks for the fix @bmillemathias!
Jason and I went off on a tangent not realising that this para was duplicated during a cherrypick to the 4.2 branch, to which you had already provided the answer. There is no weirdness here, just a bad CP from master.

**Pull request merged**
