### PR TITLE
Document hot deployment for sti-perl

### PR DESCRIPTION
**Pull request by mnagy**
This will be implemented in https://github.com/openshift/sti-perl/pull/49

### CODE REVIEW

**Comment by adellape** [comment]
@mnagy Thanks. If you wrap this new, Origin-only (for now) content in `ifdef::openshift-origin` / `endif::[]`, I can merge this once the code is merged for Origin. I've labeled this for inclusion in OSE 3.1 so we can get it into OSE when appropriate.

https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/contributing.adoc#conditional-text-between-products

**Comment by mnagy** [comment]
Will do tomorrow, thanks.

**Comment by mnagy** [comment]
Changed a little bit. Added `""` to the list of options that disable the reloading.

**Comment by mnagy** [comment]
One more change. We decided that only "true" will enable the feature.

**Pull request merged**
