### PR TITLE
OCPBUGS#11605 updating credentialsMode to allow Manual

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OCPBUGS-11605

Link to docs preview:
[Sample yaml file (annotations)](https://58596--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-shared-vpc.html#installation-gcp-shared-vpc-config_installing-gcp-shared-vpc)
[Parameters table](https://58596--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-shared-vpc.html#installation-configuration-parameters-optional_installing-gcp-shared-vpc)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jianli-wei @patrickdillon PTAL at this bug fix for 4.13 GCP XPN. Thank you

**Comment by jianli-wei** [comment]
> @jianli-wei: No Jira issue is referenced in the title of this pull request. To reference a jira issue, add 'XYZ-NNN:' to the title of this pull request and request another refresh with `/jira refresh`.
> 
> In response to [this](https://github.com/openshift/openshift-docs/pull/58596#issuecomment-1562486143):
> 
> > /jira refresh
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

@bscott-rh I guess you need to correct the title. Besides, as the PR is not yet merged, I think the bug https://issues.redhat.com/browse/OCPBUGS-11605 should not be ON_QA, right?

**Comment by jianli-wei** [comment]
@bscott-rh Any updates? Thanks!

**Comment by bscott-rh** [comment]
> @bscott-rh Any updates? Thanks!

@jianli-wei sorry for the delay. I moved OCPBUGS-11605 off of ON_QA status. It looks like my docs PR is waiting on https://issues.redhat.com/browse/OCPBUGS-11921 and https://issues.redhat.com/browse/OCPBUGS-11605 to merge before I can publish this to the documentation. is that correct? Thank you

**Comment by patrickdillon** [comment]
LGTM

**Review by jianli-wei — APPROVED** [review]
/label qe-approved

**Review by skrthomas — COMMENTED** [review]
LGTM!

**Pull request merged**
