### PR TITLE
OSDOCS-4744: 4.10 changes

### PR DESCRIPTION
**Pull request by skopacz1**
[OSDOCS-4744](https://issues.redhat.com/browse/OSDOCS-4744)

This is the **4.10 PR** of #55448 

**Current/live documentation**:
https://docs.openshift.com/container-platform/4.10/updating/updating-restricted-network-cluster/restricted-network-update-osus.html#update-service-mirror-release_updating-restricted-network-cluster-osus
and
https://docs.openshift.com/container-platform/4.10/updating/updating-restricted-network-cluster/restricted-network-update.html#updating-restricted-network-mirror-host

**Preview**: http://file.bos.redhat.com/skopacz/4744_4.10/updating/updating-restricted-network-cluster/mirroring-image-repository.html

### CODE REVIEW

**Comment by skopacz1** [comment]
@shellyyang1989 PTAL

**Comment by shellyyang1989** [comment]
@skopacz1 generally looks good to me. Just wonder why we don't recommend oc-mirror to 4.10 users?

**Comment by shellyyang1989** [comment]
> @skopacz1 generally looks good to me. Just wonder why we don't recommend oc-mirror to 4.10 users?

ah, 4.10 introduces the oc-mirror OpenShift CLI (oc) plugin as a Technology Preview.

/lgtm

**Pull request merged**
