### PR TITLE
OCPBUGS-33407 - Adding missing PTP features to TP table

### PR DESCRIPTION
**Pull request by aireilly**
Some PTP features are missing from the TP table in the release notes. These features were missed when the TP table was split into smaller tables for 4.15. 

Preview:
https://75658--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes.html#ocp-4-15-technology-preview-tables

Version(s):
enterprise-4.15

Issue:
https://issues.redhat.com/browse/OCPBUGS-33407

Link to docs preview:

QE review:
- [x] QE review not required.

### CODE REVIEW

**Comment by kenyis** [comment]
lgtm

**Comment by tmalove** [comment]
Hi @aireilly will you add the preview link in comment 0? Thanks!

**Review by aneeshkp — COMMENTED** [review]
/lgtm

**Comment by aireilly** [comment]
@adellape Any idea why this PR didn't make it into 4.15 release notes source? https://github.com/aireilly/openshift-docs/blob/enterprise-4.15/release_notes/ocp-4-15-release-notes.adoc?plain=1

It did get published though :shrug:  

https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html

**Pull request merged**
