### PR TITLE
[docs-rhacs-4.0] manual CP: fix indentation for pod creation steps

### PR DESCRIPTION
**Pull request by kcarmichael08**
Cherry picked from #58511 

Version(s):
`rhacs-docs-4.0`

Issue: n/a

Link to docs preview:

QE review: **N/A**
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
Manual CP lgtm!

**Comment by kalexand-rh** [comment]
It looks like GitHub had a communication error. I see the commits for this PR on `[rhacs-docs-4.0](https://github.com/openshift/openshift-docs/tree/rhacs-docs-4.0)` both online and locally even though it's displaying as closed instead of merged. Since putting the commits from this PR onto that branch was the desired end result, I think that we can proceed with no further action.

@kcarmichael08, let me know if you run into issues with this branch because of this so we can try to remediate it.

**Comment by kcarmichael08** [comment]
> It looks like GitHub had a communication error. I see the commits for this PR on `rhacs-docs-4.0` both online and locally even though it's displaying as closed instead of merged. Since putting the commits from this PR onto that branch was the desired end result, I think that we can proceed with no further action.
> 
> @kcarmichael08, let me know if you run into issues with this branch because of this so we can try to remediate it.

Thank you Kathryn and Kelly!

**Pull request closed without merging**
