### PR TITLE
Add --virtual-ip-groups option

### PR DESCRIPTION
**Pull request by imcsk8**
Added grouping option to VRRP configuration.

### CODE REVIEW

**Comment by pravisankar** [comment]
Origin PR: https://github.com/openshift/origin/pull/14740/ (yet to be merged)

**Review by pravisankar — APPROVED** [review]
LGTM

**Review by knobunc — APPROVED** [review]
LGTM too... but we need to wait to merge until the feature PR lands.

**Comment by bfallonf** [comment]
@imcsk8 @pravisankar @knobunc Thanks for this. This card was in my backlog since aiming for 3.7. Is this now for 3.10?

**Comment by pravisankar** [comment]
On Thu, Apr 5, 2018 at 8:36 PM, Brice Fallon-Freeman <
notifications@github.com> wrote:

> @imcsk8 <https://github.com/imcsk8> @pravisankar
> <https://github.com/pravisankar> @knobunc <https://github.com/knobunc>
> Thanks for this. This card was in my backlog since aiming for 3.7. Is this
> now for 3.10?
>
Yes, this will be available in 3.10

**Comment by bfallonf** [comment]
Thanks @pravisankar . Instead of asking @imcsk8 to make some markup changes, I copied this over into #8659 . All, please let me know if you have any thoughts.

cc @knobunc

**Pull request closed without merging**
