### PR TITLE
[enterprise-3.7] Logging and metrics version example uses v3.6 in 3.7 doc

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1527274

### CODE REVIEW

**Comment by mburke5678** [comment]
@jcantrill 
We got a request to change a v3.6 to v3.7 for a path name in the 3.7 docs. Fixing that I noticed the origin version of the path has v1.5: _`openshift/origin-` creates `openshift/origin-logging-fluentd:v1.5`_
Should this be _`openshift/origin-` creates `openshift/origin-logging-fluentd:v1.7`_?

**Comment by jcantrill** [comment]
All versions in ocp/origin switched to 3.x after v1.5 was released.  I would expect any tag references to be 3.6, 3.7, 3.9, etc

**Comment by mburke5678** [comment]
@jcantrill Can you PTAL? It looks like I need to update these values in other versions so I want to make sure I have it right .

**Review by jcantrill — APPROVED** [review]

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by anpingli** [comment]
LGTM

**Comment by mburke5678** [comment]
@anpingli 
I apologize.  I accidentally asked you to review this PR before I saw Takayoshi's concern in the BZ with the `openshift_metrics_image_prefix` description. I used the wording from the 3.9 version of the document, which seem correct. Can you please take another look at this PR and the PRs for 3.6 and 3.5?
3.6 https://github.com/openshift/openshift-docs/pull/10227
3.5 https://github.com/openshift/openshift-docs/pull/10228

**Comment by nekop** [comment]
LGTM

**Pull request merged**
