### PR TITLE
[OSDOCS-6301]:ROSA HCP Documentation Improvements

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-6301
Link to docs preview:

https://63999--docspreview.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly#rosa-hcp-classic-comparison_rosa-hcp-sts-creating-a-cluster-quickly
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello 
[@Xue Li](https://redhat-internal.slack.com/team/UEEQ10T4L)
 
[@yuwan](https://redhat-internal.slack.com/team/UEE8X128Y)
,
When you get a moment could you please review this PR: https://github.com/openshift/openshift-docs/pull/63999? Thank you!

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by cbippley** [comment]
As I am still in training, please wait for a second reviewer before requesting a merge review. Thank you! @opayne1 
/label peer-review-done
/remove-label peer-review-in-progress

**Comment by opayne1** [comment]
Looks good to me!

**Comment by mletalie** [comment]
Thanks @opayne1 and @cbippley!

**Pull request merged**
