### PR TITLE
Removing IBM Power/Z support from release notes 4.6-49

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.6 -4.9

Issue:
[OSDOCS-4801](https://issues.redhat.com/browse/OSDOCS-4801)

Link to docs preview:
[Compliance Operator release notes](http://file.rdu.redhat.com/antaylor/ibmpz/security/compliance_operator/compliance-operator-release-notes.html#compliance-operator-release-notes-0-1-49)
[File Integrity Operator release notes](http://file.rdu.redhat.com/antaylor/ibmpz/security/file_integrity_operator/file-integrity-operator-release-notes.html#file-integrity-operator-release-notes-0-1-30)

Additional information:
This PR removes text from release notes and will be required for inactive branches 4.6 and 4.7 as well.

### CODE REVIEW

**Comment by sheriff-rh** [comment]
/hold 

Verifying with QE.

**Comment by sheriff-rh** [comment]
@kalexand-rh can you take a look at this? We need to backport these changes to 4.6 and 4.7. Thanks!

**Comment by kalexand-rh** [comment]
I'm ok with the change itself and using the bot to (try to) cherry-pick this back to 4.6.

Let me know when the change has merged to all branches so I can manually update the 4.6 and 4.7 docs on the portal.

**Comment by skrthomas** [comment]
merge review lgtm

**Comment by kalexand-rh** [comment]
I've pushed and published this change in 4.6 and 4.7 on the portal. Please confirm that it's come through correctly this afternoon. (It can take up to two hours for changes to roll out.)

**Comment by sheriff-rh** [comment]
All set in the portal. Thank you!

**Pull request merged**
