### PR TITLE
Fixed default limit/requests for fluentd

### PR DESCRIPTION
**Pull request by mburke5678**
From Slack conversation: https://coreos.slack.com/archives/CB3HXM2QK/p1598267663059300?thread_ts=1597919166.003000&cid=CB3HXM2QK

### CODE REVIEW

**Review by jcantrill — APPROVED** [review]
/approve

**Comment by mburke5678** [comment]
@anpingli Is this change something you can review?

**Review by anpingli — COMMENTED** [review]
LGTM

**Comment by bobfuru** [comment]
You'll probably want to squash commits but otherwise, LGTM.

**Pull request merged**
