### PR TITLE
Bug 1657326, Added Setting the Registry Host Name section to Deploying a Registry topic

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1657326

Preview Build: http://file.rdu.redhat.com/~ahardin/03262019/deploying-registry-variable/install_config/registry/deploy_registry_existing_clusters.html#setting-the-registry-hostname

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@rjhowe PTAL

**Comment by ahardin-rh** [comment]
@yapei PTAL

**Comment by ahardin-rh** [comment]
Received approval from @rjhowe over IRC

**Comment by ahardin-rh** [comment]
@yapei Please provide QE review

**Comment by wzheng1** [comment]
LGTM from QE side.

**Comment by ahardin-rh** [comment]
@wzheng1 Thank you!

**Pull request merged**
