### PR TITLE
Bug 1880238: [DOCS] Eliminate unclear descriptions on the "Setting Deployment Resources" section

### PR DESCRIPTION
**Pull request by bysnupy**
* Version: v3.11
* Reference: [[DOCS] Eliminate unclear descriptions on the "Setting Deployment Resources" section](https://bugzilla.redhat.com/show_bug.cgi?id=1880238)
* Description: Some explanations are not clear and it leads misunderstanding for deployment resources setting.

### CODE REVIEW

**Comment by bysnupy** [comment]
@vikram-redhat Could you PTAL ?

**Comment by vikram-redhat** [comment]
@mburke5678 - can you take this forward?

**Comment by bysnupy** [comment]
@mburke5678 Would you PTAL on this matter ? I think we should express more clear terms, such as deploy pod instead of unclear "Deployment Resources" word.

**Comment by mburke5678** [comment]
@bysnupy I am sorry that I lost track of this issue. I will merge this PR and make some editorial changes in a separate PR. I will also apply your changes to 4.x docs as appropriate.

**Pull request merged**
