### PR TITLE
Typos: Fix incorrect hyphenation per ISG

### PR DESCRIPTION
**Pull request by aireilly**
Typo fixes. 

Version(s): 
enterprise-4.11+

Per the ISG, the following incorrect terms are used throughout the openshift-docs repo: 

* pre-install
* post-install
* pre-configure

This PR corrects each instance of the above with the correct non-hyphenated form.

None of these terms take a hyphen. See https://www.ibm.com/docs/en/ibm-style?topic=grammar-prefixes for details. 

QE review:
- [x] QE review not required

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@aireilly would you consider cherrypicking this back to 4.11 (and manual CPing as necessary)? That's what I usually do when I a typo sweep through the repo. That way it prevents a lot of potential future conflicts on people making updates to these lines

**Comment by aireilly** [comment]
@bergerhoffer Will do.

**Comment by bergerhoffer** [comment]
Thanks @aireilly!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!

**Comment by kelbrown20** [comment]
@aireilly Some failed cherrypicks on 4.11, 4.12, and 4.13 :,( I can merge the manual CPs when they're all set!

**Comment by aireilly** [comment]
Updated Vale rules to match ISG: https://github.com/redhat-documentation/vale-at-red-hat/pull/686

**Pull request merged**
