### PR TITLE
BZ-1823977: Updating command to approval all pending CSRs

### PR DESCRIPTION
**Pull request by bergerhoffer**
Apply change from https://bugzilla.redhat.com/show_bug.cgi?id=1823977 to 4.x. Command accomplishes the same thing, but this one doesn't require the jq package to be installed.

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@barleyer Can you check this as well? This applies the change from #21170 to 4.x. I tested it on 4.4 and the command works well there as well.

**Pull request merged**
