### PR TITLE
Known issue for loading VMIs with Redfish Virtual Media

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1872787

### CODE REVIEW

**Comment by codyhoag** [comment]
@tomassedovic can you confirm? Thanks!

**Comment by codyhoag** [comment]
@tomassedovic bump. Can you review this known issue text? Thanks!

**Comment by tomassedovic** [comment]
@codyhoag I'm so sorry, didn't see the original mention for some reason.

The text looks good to me, but since I'm not an engineer on this, I'd like @dtantsur or @derekhiggins to take a look as well. Dmitry & Derek, is the proposed release note accurate?

**Review by derekhiggins — APPROVED** [review]
looks good to me

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Pull request merged**
