### PR TITLE
ospbugs#1858: Removed vSphere-specific note from module

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.10+

Issue:
This PR addresses [ocpbugs1858](https://issues.redhat.com/browse/OCPBUGS-1858).

Link to docs preview:
[Required machines for cluster installation](https://51092--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere.html#installation-machine-requirements_installing-vsphere)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@jinyunma This is ready for QE review. PTAL. Thank you.

**Comment by jinyunma** [comment]
@sgaoshang PTAL, thanks.

**Review by pneedle-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
