### PR TITLE
BZ2036297: Updated storage class name object and added callout

### PR DESCRIPTION
**Pull request by darshan-nagaraj**
Updated storage class `name` object and added callout to RHSOP, Azure, AWS, GCP, and vsphere object definitions.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2036297

OCP version: 4.6+

Direct Doc Preview Link:
https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#openstack-cinder-storage-class_dynamic-provisioning

https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#aws-definition_dynamic-provisioning

https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#azure-disk-definition_dynamic-provisioning

https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#gce-persistentdisk-storage-class_dynamic-provisioning

https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#vsphere-definition_dynamic-provisioning

https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#basic-storage-class-definition_dynamic-provisioning
 
@duanwei33 Please review and let me know your feedback

### CODE REVIEW

**Comment by duanwei33** [comment]
@darshan-nagaraj Hi, thanks for the update.
In the AWS part:
https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#aws-definition_dynamic-provisioning
I suggest add the "(required)" to align with the AWS other part, Or remove all the "required" or "Optional" to align with the other platform.

Other look good to me.

**Comment by darshan-nagaraj** [comment]
> @darshan-nagaraj Hi, thanks for the update. In the AWS part: https://deploy-preview-40990--osdocs.netlify.app/openshift-enterprise/latest/storage/dynamic-provisioning.html#aws-definition_dynamic-provisioning I suggest add the "(required)" to align with the AWS other part, Or remove all the "required" or "Optional" to align with the other platform.
> 
> Other look good to me.

I have added (required) to align with the AWS other part. Thanks.

**Pull request merged**
