### PR TITLE
OCPBUGS#13670: Added poland central zone to Azure docs

### PR DESCRIPTION
**Pull request by dfitzmau**
[OCPBUGS-13670](https://issues.redhat.com/browse/OCPBUGS-13670)

Version(s):
4.15 to 4.11

Link to docs preview:
[Supported Azure public regions](https://68328--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account#installation-azure-marketplace_installing-azure-account)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jinyunma** [comment]
LGTM

**Review by r4f4 — COMMENTED** [review]
/approve

**Review by agantony — COMMENTED** [review]
LGTM!

**Pull request merged**
