### PR TITLE
BZ#1904957 - OVNKube egress - ports field update

### PR DESCRIPTION
**Pull request by ktania46**
@SNiemann15   @jboxman 

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1904957

### CODE REVIEW

**Comment by jboxman** [comment]
@ktania46, I'll take a look, thanks!

**Review by ssinha20 — COMMENTED** [review]
LGTM.

**Comment by jboxman** [comment]
Hi @huiran0826,

Can you confirm? Thanks!

**Comment by jboxman** [comment]
@huiran0826, ping.

**Comment by huiran0826** [comment]
LGTM, but it is better for @JacobTanenbaum to check.  Thanks!

**Pull request merged**
