### PR TITLE
TELCODOCS-1868: Remove TP notes

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1868](https://issues.redhat.com//browse/TELCODOCS-1868): Remove TP notes associated with this feature because it is GA for 4.17. 

Version(s):
4.17+

Issue:
https://issues.redhat.com/browse/TELCODOCS-1868

QE review:
- [x] QE has approved this change.

Link to docs preview:
- https://81406--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/preparing-to-install-on-bare-metal.html#nw-sriov-dual-nic-con_preparing-to-install-on-bare-metal 
- https://81406--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.html#agent-install-sample-config-bond-sriov_preparing-to-install-with-agent-based-installer 
- https://81406--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configuring-host-dual-network-interfaces-in-the-install-config-yaml-file_ipi-install-installation-workflow 
- https://81406--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#bonding-multiple-sriov-network-interfaces-to-dual-port_installing-bare-metal 

Additional information:
Missed removing these TP notes the in original PR #80046

### CODE REVIEW

**Comment by rohennes** [comment]
@cgoncalves - thanks for spotting this, please review when you have a chance.

**Comment by rohennes** [comment]
@ShaunaDiaz  - just checking if the peer review is done for this or still in progress? Thanks!

**Comment by ShaunaDiaz** [comment]
> @ShaunaDiaz - just checking if the peer review is done for this or still in progress? Thanks!

It was done, sorry about that!

**Pull request merged**
