### PR TITLE
OCPBUGS-26932 unify cgroups docs for okd 4.14 and ocp 4.14

### PR DESCRIPTION
**Pull request by mburke5678**
Jira: https://issues.redhat.com/browse/OCPBUGS-26932
GH: https://github.com/openshift/openshift-docs/issues/67953

Previous to 4.14, in OKD cgroup v2 was default and in OCP cgroup v1 was default. We created separate modules for OCP and OKD. For 4.14+, OCP and OKD are both v2 by default. This PR removes the OKD-specific modules and adds `ifdef`s to the other modules.

**Previews:**
**OCP:**
* Nodes -> Clusters -> [Configuring the Linux cgroup version on your nodes](https://70086--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-cgroups-2)
* Post-install -> Cluster tasks -> [Configuring Linux cgroup](https://70086--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks#nodes-clusters-cgroups-2_post-install-cluster-tasks)
**OKD**
* Nodes -> Clusters -> [Configuring the Linux cgroup version on your nodes](https://file.rdu.redhat.com/~mburke/okd-unify-cgroups/nodes/clusters/nodes-cluster-cgroups-2.html)
* Post-install -> Cluster tasks -> [Configuring Linux cgroup](https://file.rdu.redhat.com/~mburke/okd-unify-cgroups/post_installation_configuration/cluster-tasks.html#nodes-clusters-cgroups-2_post-install-cluster-tasks)

### CODE REVIEW

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Review by vrutkovs — APPROVED** [review]
Looks good, thanks

**Pull request merged**
