### PR TITLE
bug 1682971 direct installer links

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://bugzilla.redhat.com/show_bug.cgi?id=1682971

@jianlinliu, @mburke5678, PTAL?

### CODE REVIEW

**Comment by mburke5678** [comment]
@kalexand-rh LGTM All of the links go to the page I expect. The `#pull-secret` anchor doesn't seem to affect the link as it lands at the top of the page. But, not problematic.

**Comment by kalexand-rh** [comment]
Thanks @mburke5678! I noticed that, too - it's a valid anchor, so I'm not sure why it's not loading properly. I tagged Vikram on the bug to see if he knows what's going on.

**Comment by jianlinliu** [comment]
@gpei PTAL

**Comment by gpei** [comment]
The #pull-secret anchor seems also didn't work for me, other changes LGTM, thanks.

**Comment by kalexand-rh** [comment]
Since that link only works for me, I've edited those sections to remove the anchor and am going to merge. Thanks!

**Pull request merged**
