### PR TITLE
Clarify that installer-provisioned bare metal installation is required for dual stack

### PR DESCRIPTION
**Pull request by jboxman**
Last minute addition of link, because it makes sense.

### CODE REVIEW

**Comment by jboxman** [comment]
@zhaozhanqi, I updated this to specify that only installer-provisioned bare metal is supported; Can you confirm? Thank you!

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by jboxman** [comment]
@kalexand-rh thanks!

**Pull request merged**
