### PR TITLE
BZ1725985 Clarify label rules and fix example to be compliant

### PR DESCRIPTION
**Pull request by jeana-redhat**
Addressing https://bugzilla.redhat.com/show_bug.cgi?id=1725985

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@wewang58 please review these changes made for BZ1725985

**Comment by wewang58** [comment]
/lgtm
Thanks

**Comment by jeana-redhat** [comment]
@wewang58 Thank you!
@openshift/team-documentation peer review please :)

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
