### PR TITLE
[OSDOCS-4535]: Enabling Azure boot diagnostics (4.12 RN)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12

Issue:
[OSDOCS-4535](https://issues.redhat.com//browse/OSDOCS-4535)

Link to docs preview:
[Enabling Azure boot diagnostics](https://52833--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-azure-boot-diagnostics)

QE review:
- [x] QE has approved this change.

Additional information:
:heavy_check_mark: ~~Bulid will fail until #52831 merges~~

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@sunzhaohua2 this PR is currently broken due to a dependency, but wanted to give you a heads up for rel note feature tracking :slightly_smiling_face:

**Review by elmiko — COMMENTED** [review]
lgtm

**Comment by sunzhaohua2** [comment]
thanks @jeana-redhat 
/lgtm

**Comment by tmalove** [comment]
Hi @jeana-redhat just checking that this update is due to only go in 4.12 or 4.12+? Otherwise, this looks good!

**Comment by jeana-redhat** [comment]
> Hi @jeana-redhat just checking that this update is due to only go in 4.12 or 4.12+? Otherwise, this looks good!

Rel notes = 4.12 only, thanks!

**Pull request merged**
