### PR TITLE
Document how to change passwords

### PR DESCRIPTION
**Pull request by rhcarvalho**
Part of https://trello.com/c/CgbBR2Sj
Implemented in https://github.com/openshift/postgresql/pull/50

@bparees @adellape PTAL

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@mfojtik PTAL

**Comment by mfojtik** [comment]
LGTM

@adellape PTAL

**Comment by rhcarvalho** [comment]
@adellape @bfallonf @CowboysFan PTAL

**Comment by rhcarvalho** [comment]
@mfojtik FYI, I removed the sentence "When you use a persistent volume to store your data, you may want to update passwords of an existing database" from the very beginning, since the instructions equally apply to ephemeral storage.

**Comment by bparees** [comment]
lgtm, nice work @rhcarvalho

**Comment by adellape** [comment]
LGTM, thanks. Targeting inclusion in OSE docs for 3.0.2.

**Pull request merged**
