### PR TITLE
BZ2049854: Correct GCP CSI Driver in table to GA

### PR DESCRIPTION
**Pull request by lpettyjo**
4.8+

[BZ2049854](https://bugzilla.redhat.com/show_bug.cgi?id=2049854) Corrects GCP CSI Driver in table to GA.

**Preview**: https://deploy-preview-41315--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

**PTAL**: @jsafrane @duanwei33

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM!

One question, is this just a lingering TP reference? If so (this has already gone through the TP to GA process and this table update was missed), then it likely won't need to go through change management. Otherwise, that might be something to look in to more closely.

**Comment by lpettyjo** [comment]
@bmcelvee it is a lingering TP mention. I'm checking with Andrew to see how he wants me to handle this.

**Comment by jsafrane** [comment]
lgtm

**Pull request merged**
