### PR TITLE
OSDOCS-10899: Remove Alibaba Cloud preupdate references

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-10899](https://issues.redhat.com//browse/OSDOCS-10899)

Link to docs preview:
[Preparing to update a cluster with manually maintained credentials](https://77509--ocpdocs-pr.netlify.app/openshift-enterprise/latest/updating/preparing_for_updates/preparing-manual-creds-update.html)

QE review:
- [x] QE has approved this change.

Additional information:
Temp image until official diagram is provided

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@jcpowermac and @jianli-wei PTAL

Heads-up: @dlom @huangmingxia @jianping-shu @jstuever

**Comment by jeana-redhat** [comment]
rebased for peer review and merge, no change

**Comment by kcarmichael08** [comment]
Peer review: lgtm!

**Comment by jeana-redhat** [comment]
premerge rebase

**Pull request merged**
