### PR TITLE
[SRVCOM-2111, SRVOCF-455, SRVOCF-454] Functions section restructuring

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
Serverless 1.28+

Issue:
https://issues.redhat.com/browse/SRVCOM-2111
https://issues.redhat.com/browse/SRVOCF-455
https://issues.redhat.com/browse/SRVOCF-454

Link to docs preview:
https://61508--docspreview.netlify.app/openshift-serverless/latest/functions/serverless-functions-getting-started.html

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by rh-max** [comment]
@gabriel-rh Hi Gabriel. Can you please review this?

**Comment by gabriel-rh** [comment]
https://61508--docspreview.netlify.app/openshift-serverless/latest/functions/serverless-functions-getting-started.html

This page probably needs a bit more refactoring - the mapping shows 4 pages:

Screenshot from 2023-06-22 14-33-18

**Comment by gabriel-rh** [comment]
https://61508--docspreview.netlify.app/openshift-serverless/latest/functions/reference/serverless-developing-nodejs-functions.html

This looks good!

**Review by gabriel-rh — APPROVED** [review]
LGTM

Maybe add toc to some pages, but that can happen in a subsequent PR

**Pull request merged**
