### PR TITLE
updates vale packages + correct id rule error

### PR DESCRIPTION
**Pull request by aireilly**
Since https://github.com/errata-ai/packages/pull/15 was merged, we don't need to specify the full URL for packages.

Merge to main, CP to enterprise-4.10+

### CODE REVIEW

**Comment by aireilly** [comment]
@rohennes @jeana-redhat PTAL

**Comment by rohennes** [comment]
\lgtm

Should update the VRH docs too for any instance of the zip

**Comment by aireilly** [comment]
@rohennes Yes indeed. I'll create a PR presently.

**Comment by aireilly** [comment]
@jeana-redhat this should be ready to merge when you have a minute.

**Comment by aireilly** [comment]
@rohennes also updated the assemblies .vale.ini to disable the OpenShiftAsciiDoc.IdHasContextVariable rule.

**Comment by rohennes** [comment]
Looks good! Getting that _{context} erro ron assemblies is annoying

**Pull request merged**
