### PR TITLE
OSDOCS-5196-4-12: Updated vSphere versioning format for 4.12 docs

### PR DESCRIPTION
**Pull request by dfitzmau**
Issue:
[OSDOCS-5196](https://issues.redhat.com/browse/OSDOCS-5197)

Version(s):
4.12

Link to docs preview:
* [VMware vSphere infrastructure requirements](http://file.emea.redhat.com/dfitzmau/OCDOCS-5196-4-12/installing/installing_vsphere/preparing-to-install-on-vsphere.html#installation-vsphere-infrastructure_preparing-to-install-on-vsphere)
* [VMware vSphere CSI Driver Operator requirements](http://file.emea.redhat.com/dfitzmau/OCDOCS-5196-4-12/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#vsphere-csi-driver-reqs_installing-vsphere-installer-provisioned)
* [Post-installation configuration](http://file.emea.redhat.com/dfitzmau/OCDOCS-5196-4-12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-post-installation)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by rvanderp3** [comment]
LGTM
cc: @jcpowermac

**Comment by duanwei33** [comment]
/lgtm
cc @sgaoshang

**Review by kcarmichael08 — COMMENTED** [review]
Looks like QE reviewed and approved so please check the box for that on the PR body. Otherwise, LGTM!

**Pull request merged**
