### PR TITLE
Rel Notes doc text for 4.6.6 release

### PR DESCRIPTION
**Pull request by jeana-redhat**
For ~~23~~ **30** Nov 2020

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@openshift/team-documentation ready for review

**Comment by jeana-redhat** [comment]
Caught a typo, changed Moderate -> Low in the RHSA title

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by codyhoag** [comment]
Force pushed for version update to 4.6.6.

**Comment by codyhoag** [comment]
@jeana-redhat 4.6.6 has been pushed back to next week due to packaging issues.

**Pull request merged**
