### PR TITLE
disambiguate upstream mirroring from openshift registry mirroring

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@legionus ptal.

**Comment by bparees** [comment]
@legionus bump

**Comment by bparees** [comment]
@miminar or @dmage can you confirm this doc change?

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge.

**Comment by bparees** [comment]
(this is applicable to all branches that discuss mirroring)

**Comment by bmcelvee** [comment]
LGTM

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/registry/extended_registry_configuration.adoc#install-config-registry-extended-configuration[Setting up the Registry -> Extended Registry Configuration]
|Added note clarifying that the mirroring feature is different from the upstream feature in the  xref:../install_config/registry/extended_registry_configuration.adoc#middleware-repository-pullthrough[Image Pullthrough] section.
%

**Pull request merged**
