### PR TITLE
Remove Tech Preview designation for SDN Multicast

### PR DESCRIPTION
**Pull request by dcbw**
@mcurry-rh @knobunc @openshift/networking

### CODE REVIEW

**Review by rajatchopra — APPROVED** [review]
LGTM

**Comment by ahardin-rh** [comment]
@dcbw Is this targeting 3.6?

**Review by pravisankar — APPROVED** [review]
lgtm

**Comment by ahardin-rh** [comment]
@dcbw Is this for OCP 3.6?

**Comment by dcbw** [comment]
@ahardin-rh yes, not sure how to tag it as such though.  Thanks!

**Comment by ahardin-rh** [comment]
@dcbw Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/managing_networking.adoc#admin-guide-manage-networking[Managing Networking]
|Removed the Technology Preview designation for SDN Multicast.
%

**Pull request merged**
