### PR TITLE
Added release notes for Online 3.9 upgrade

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/wANJAijb/1079-3-pro-create-release-notes-for-online-pro

**Target date: Tuesday, April 17**

Preview Build: http://file.rdu.redhat.com/~ahardin/04132018/online-release-notes-3-9/release_notes/online_release_notes.html

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@agupta @tiwillia Please review.

cc @aheslin @vikram-redhat @adellape

**Comment by ahardin-rh** [comment]
@sspeiche Feel free to weigh in as well. It's a review party. :clinking_glasses:

**Review by tiwillia — APPROVED** [review]

**Comment by yasun1** [comment]
LGTM

**Pull request merged**
