### PR TITLE
[OCPBUGS#33312]: Add important note when manually adding a device for IPI installation

### PR DESCRIPTION
**Pull request by tmalove**
Version(s):
4.13+

Issue: [OCPBUGS-33312](https://issues.redhat.com/browse/OCPBUGS-33312)

Link to docs preview:
[Moving etcd to a different disk](https://75751--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.html#move-etcd-different-disk_recommended-etcd-practices) (Updated 5/20/2024)

QE review:
- [x ] QE has approved this change.

### CODE REVIEW

**Comment by tmalove** [comment]
@oarribas we should link to the manual installation steps as an additional resource.

**Comment by tmalove** [comment]
Hi @oarribas   Take a look at the updated Important note. Thanks!

**Comment by tmalove** [comment]
@geliu2016 Will you review this update? Thanks!

**Review by JoeAldinger — COMMENTED** [review]
My only question is wether or not this needs to go through modified CM or have PX look at it because of the support statement.

**Pull request merged**
