### PR TITLE
OCPBUGS-18279: updated TailoredProfile example

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.10+

Issue:
https://issues.redhat.com/browse/OCPBUGS-18279

Link to docs preview (VPN required):
[Creating a new tailored profile](https://file.rdu.redhat.com/antaylor/OCPBUGS-18279/security/compliance_operator/compliance-operator-tailor.html#compliance-new-tailored-profiles_compliance-tailor)

QE review:
- [x] QE has approved this change.

Additional information:
This PR addresses the concerns in the jira and also includes a few quality of life changes while I was in the file.

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
Just one suggestion. Nice work!

**Comment by sheriff-rh** [comment]
Merging.

**Pull request merged**
