### PR TITLE
fix BZ 1450224: document RWO access mode enforcement limitation and workaround instructions

### PR DESCRIPTION
**Pull request by rootfs**
@childsb

### CODE REVIEW

**Comment by childsb** [comment]
lgtm

**Comment by rootfs** [comment]
@ahardin-rh can you merge it? thanks

**Comment by ahardin-rh** [comment]
@rootfs I see you want this applied to earlier versions too. Can the content be published now, or are we targeting this content for the launch of 3.6? Just making sure I get the timing correct. Thanks!

**Comment by rootfs** [comment]
@ahardin-rh The patch is needed for 3.6 as well as early releases. Thanks!

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/additional_concepts/storage.adoc#architecture-additional-concepts-storage[Additional Concepts -> Persistent Storage]
|Added details about the *ReadWriteOnce* access mode enforcement limitation and workaround instructions.
%

**Pull request merged**
