### PR TITLE
Optimize the commands to enable root group access in the Dockerfile

### PR DESCRIPTION
**Pull request by tstjep**
Reduce the number of instructions to set the desired permissions (gid 0, g+rx for files, g+x for directories) in the Dockerfile:

- Use only one RUN statement
- Remove find command and replace it with a +X in the chmod command (X as +x for directories only)

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@tstjep Thank you!
@bparees PTAL

**Comment by bparees** [comment]
lgtm

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../creating_images/guidelines.adoc#creating-images-guidelines[Guidelines]
|Updated the commands in the xref:../creating_images/guidelines.adoc#use-uid[Support Arbitrary User IDs] section to enable root group access in the Dockerfile.
%

**Pull request merged**
