### PR TITLE
Adding ROSA getting started next steps

### PR DESCRIPTION
**Pull request by pneedle-rh**
This applies to `main`, `enterprise-4.9` and `enterprise-4.10`.

This PR adds a "Next steps" section to the recently added "Getting started with Red Hat OpenShift Service on AWS" page.

The preview is [here](https://deploy-preview-41139--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-getting-started#next-steps_rosa-getting-started).

### CODE REVIEW

**Comment by mjpytlak** [comment]
@pneedle-rh peer review LGTM.

**Comment by 0kashi** [comment]
lgtm

**Pull request merged**
