### PR TITLE
Bug 1771512, Hide AWS note for OSP articles

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1771512

Preview: http://file.rdu.redhat.com/~choag/111519/add-conditional-osp/installing/installing_openstack/installing-openstack-installer-custom.html#ssh-agent-using_installing-openstack-installer-custom.

@maxwelldb can you confirm and merge/CP if it looks good? Thanks!

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]
Looks fine in linked preview + a local one.

**Comment by maxwelldb** [comment]
Be sure to verify on the portal later on--who knows, at this point. @codyhoag

**Comment by codyhoag** [comment]
@maxwelldb will do! Thanks!

**Pull request merged**
