### PR TITLE
Release notes for WMCO 1.0.3 release

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
Preview: https://deploy-preview-29154--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/windows-containers-release-notes.html#wmco-1-0-3

**Comment by codyhoag** [comment]
@aravindhp here's a generic statement for the WMCO 1.0.3 release. Let me know if there are any other details I should add.

Can you also confirm this is for OCP 4.6 and 4.7?

Thanks!

**Comment by aravindhp** [comment]
Looks good for 4.6. For 4.7 we should call out vSphere support,
/cc @Anandnatraj @gmarkley-VI

**Comment by codyhoag** [comment]
@aravindhp I thought vSphere support was coming in 2.0.0? Is that really coming in 1.0.3?

**Comment by aravindhp** [comment]
Yes vSphere is with 2.0.0 and OpenShift 4.7. We will not be adding vSphere support in 1.x/OpenShift 4.6. Sorry if I confused you.

**Comment by codyhoag** [comment]
@aravindhp thanks for confirming. This leads to a bigger question:

Will each major release of the WMCO be targeted for the y-release for OCP? For example, `1.x` -> `4.6`, `2.x` -> `4.7`, `3.x -> 4.8` etc...?

I'm trying to figure out the RNs for each release... if the features of the 2.x WMCO are not applying to OCP 4.6, then perhaps the release notes for 4.6 should not include the 2.x releases, which would also mean 4.7 would not include the 1.x releases.

**Comment by aravindhp** [comment]
> Will each major release of the WMCO be targeted for the y-release for OCP? For example, `1.x` -> `4.6`, `2.x` -> `4.7`, `3.x -> 4.8` etc...?

That is correct. 4.6 will only map to 1.y.z release and 4.7 will only map to 2.y.z releases.

> I'm trying to figure out the RNs for each release... 

What is RN?

>if the features of the 2.x WMCO are not applying to OCP 4.6, then perhaps the release notes for 4.6 should not include the 2.x releases, which would also mean 4.7 would not include the 1.x releases.

I am confused by this. I thought there would separate release notes for 1.x and 2.x.

**Comment by codyhoag** [comment]
Since WMCO 1.0.3 is only targeting OCP 4.6, I'm closing this PR and will resend for 4.6 inclusion only.

**Pull request closed without merging**
