### PR TITLE
Fixes pod autoscaling

### PR DESCRIPTION
**Pull request by atkrad**
There is an error on "HorizontalPodAutoscaler" config, "cpuUtilization" must be deleted.

### CODE REVIEW

**Comment by mburke5678** [comment]
@sjenning PTAL

**Comment by sjenning** [comment]
LGTM

Keep in mind that for `autoscaling/v2alpha1`, this has been replaced with a `metrics` array that contains the thresholds for autoscaling and supports custom metrics.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by mburke5678** [comment]
@atkrad This change appears to affect OpenShift 3.9 and higher. if this is correct, I can merge.

@sjenning The docs include the configuration for both autoscaling/v1` and `autoscaling/v2beta1`.

**Comment by vikram-redhat** [comment]
@mburke5678 - can you please move this one along?

**Comment by mburke5678** [comment]
@sunzhaohua2 Please take a look at this change. 
Can you confirm if this change should roll back to 3.9+?

**Comment by mburke5678** [comment]
@sunzhaohua2 Is this an issue you can review?

**Comment by mburke5678** [comment]
@sunzhaohua2 Is this an issue you can review?

**Pull request closed without merging**
