### PR TITLE
OSDOCS-8198: updates OVN-K diagrams with i/c

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-8198

Link to docs preview:
https://66494--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/ovn-kubernetes-architecture-assembly

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by tssurya — APPROVED** [review]
/lgtm

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
