### PR TITLE
OCPBUGS#24593: Specify nodejs version for cgroup v2

### PR DESCRIPTION
**Pull request by harche**
Version(s):

4.14+ 

Issue:

Link to docs preview:
[Configuring the Linux cgroup version on your nodes](https://68696--docspreview.netlify.app/openshift-enterprise/latest/nodes/clusters/nodes-cluster-cgroups-2)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mburke5678** [comment]
@harche It would be helpful to include a link to the issue that brought about this change. And don't forget about the QE review. Otherwise LGTM

**Review by jeana-redhat — APPROVED** [review]
LGTM
/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
