### PR TITLE
Update ramp node doc for openshift-sdn cluster network changes

### PR DESCRIPTION
**Pull request by ramr**
Match the new openshift-sdn cluster network network  (10.128.0.0/16) and add openflow rules to get the ramp node working.

@adellape / @bfallonf  PTAL Thx 

@rajatchopra  FYI

### CODE REVIEW

**Comment by bfallonf** [comment]
@ramr LGTM @adellape ?

**Comment by adellape** [comment]
:+1: Thanks @ramr, merging. For OSE, I'm marking this for inclusion starting in 3.2. Please lmk if that's incorrect.

**Comment by ramr** [comment]
@adellape thx confirming that inclusion for 3.2 is correct.

**Comment by adellape** [comment]
[rev_history]
|link:../install_config/routing_from_edge_lb.html[Routing from Edge Load Balancers]
|Updated to match the new OpenShift SDN cluster network network (10.128.0.0/16) and add OpenFlow rules to get the ramp node working.
%

**Pull request merged**
