### PR TITLE
Descheduler: mention openshift-* and kube-system namespaces are exclu

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/assign @bergerhoffer

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
@kasturinarra Can you please QE review this addition? This is just for 4.7+. Thanks!

Preview: https://deploy-preview-31505--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html#nodes-descheduler-about_nodes-descheduler

**Comment by kasturinarra** [comment]
@bergerhoffer one question though, any specific reason we are including this now ? I mean is this feedback from a customer or some where else ?

**Comment by ingvagabund** [comment]
During taking notes for customers about what Descheduler is and what it can do we discovered this information is missing in the docs. We consider it as an important piece of information to share.

**Comment by kasturinarra** [comment]
> During taking notes for customers about what Descheduler is and what it can do we discovered this information is missing in the docs. We consider it as an important piece of information to share.

Thanks @ingvagabund , that helps !!

**Comment by bergerhoffer** [comment]
Thanks all! Merging this in.

**Pull request merged**
