### PR TITLE
CNV-13214: Revising cloning checkbox step for users without supporting storage

### PR DESCRIPTION
**Pull request by bgaydosrh**
For 4.7, 4.8, 4.9, and 4.10.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1986556
Jira: https://issues.redhat.com/browse/CNV-13214

Tagging Rafal Szmigiel for Code Review in Jira.
Tagging Israel Pinto for QE Review in Jira.

Direct doc preview link: https://deploy-preview-38452--osdocs.netlify.app/openshift-enterprise/latest/virt/virtual_machines/virtual_disks/virt-creating-and-using-boot-sources#virt-creating-a-vm-from-a-template-with-an-attached-boot-source_virt-creating-and-using-boot-sources

### CODE REVIEW

**Comment by yaacov** [comment]
AFAIK the option was removed completely and we now always clone when possible, the option to not clone was removed.
IMHO we can just remove the section (AFAIK it's now always possible to clone, and the image will be cloned)

@phoracek hi, the UI is using common templates with DataVolumes and source image for the OperatingSystem main disk.
please keep me honest here:
- when using common templates we always clone the OS image 
- I think it's ok to just remove the section about the optional cloning from the UI docs, once the Common templates started using DataVolumes we always clone (it's a setting that is copied from the template, no need to have a section in the UI docs about it)

**Comment by phoracek** [comment]
@yaacov hello. I don't have an answer to that. Perhaps @aglitke from storage of @dominikholler from SSP.

**Comment by yaacov** [comment]
LGTM

@gouyang please review

**Comment by gouyang** [comment]
LGTM

**Comment by dominikholler** [comment]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
