### PR TITLE
Update console extensions examples

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/openshift-docs/issues/1526

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett the doc updates for the extensions

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
@adellape

**Comment by adellape** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/1731 which pulls in the commit here.

**Pull request closed without merging**
