### PR TITLE
BZ#1846520 Deleting nodes on bare metal

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1846520

### CODE REVIEW

**Comment by codyhoag** [comment]
@sunilcio @rphillips can you review? Thanks!

Preview: https://bare-metal-delete-nodes--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-deleting-bare-metal_nodes-nodes-working

**Comment by sunilcio** [comment]
LGTM

**Comment by codyhoag** [comment]
@sunilcio can you take another look at this? I've added a statement about decommisioning nodes, as was discussed in [BZ#1846520](https://bugzilla.redhat.com/show_bug.cgi?id=1846520). Thanks!

Preview: https://bare-metal-delete-nodes--ocpdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-deleting-bare-metal_nodes-nodes-working

**Comment by sunilcio** [comment]
@codyhoag lgtm now, thanks!

**Comment by lamek** [comment]
LGTM.

**Pull request merged**
