### PR TITLE
OCPBUGS-16236 - remove invalid step selecting the Installation mode

### PR DESCRIPTION
**Pull request by slovern**
OCPBUGS-16236 - remove invalid step selecting the Installation mode

Version(s): 
- 4.14 
- 4.13

Issue: https://issues.redhat.com/browse/OCPBUGS-16236

Link to docs preview: https://63848--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/kmm-kernel-module-management#kmm-install-using-web-console_kernel-module-management-operator

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by slovern** [comment]
Hi @qbarrand , @cdvultur 
Can you approve here for merge?
Thanks

**Comment by stevsmit** [comment]
LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM as well!

**Pull request merged**
