### PR TITLE
moving two assemblies in postinstall to a more logical order

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.15+

Issue:
N/A

Link to docs preview:
https://72309--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/adding-nutanix-failure-domains
image

QE review:
N/A just docs

Additional information:
Just FYI @dfitzmau @mjpytlak

### CODE REVIEW

**Comment by mjpytlak** [comment]
Was something else moving @jeana-redhat? I only see one update to the TOC.

**Comment by jeana-redhat** [comment]
> Was something else moving @jeana-redhat? I only see one update to the TOC.

I guess a matter of perspective - I swapped Nutanix FD with AWS LZ/WLZ, which i suppose you could call one _or_ two moves :sweat_smile:

**Comment by dfitzmau** [comment]
LGTM. Thanks!

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
