### PR TITLE
Bug 1332818 : Fixed incorrect image names

### PR DESCRIPTION
**Pull request by bfallonf**
Updating some image names as per https://bugzilla.redhat.com/show_bug.cgi?id=1332818

This also has to do with a disconnected install I'm trying to help with. There might be more to come. Keeping this as WIP for now.

### CODE REVIEW

**Comment by bfallonf** [comment]
I've been given the go ahead to merge this, and we can work on any outstanding issues after.

@tpoitras @tnguyen-rh @adellape @ahardin-rh Anybody have any issues/want to merge this?

**Comment by bfallonf** [comment]
[rev_history]
|link:../install_config/install/disconnected_install.html[Installing -> Disconnected Installation]
|Fixed some outdated image names.
%

**Comment by ahardin-rh** [comment]
LGTM

**Comment by adellape** [comment]
LGTM checking against registry.access and the [advisory](https://access.redhat.com/errata/RHEA-2016:0693).

**Comment by bfallonf** [comment]
Cool. I'll merge. Thanks, all.

**Pull request merged**
