### PR TITLE
CNV -29981: Add 'getting started' link

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12+

Issue: [CNV-29981](https://issues.redhat.com//browse/CNV-29981)

Link to docs preview: [Planning BM cluster for OCP virt](https://61288--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/preparing-to-install-on-bare-metal.html#virt-planning-bare-metal-cluster-for-ocp-virt_preparing-to-install-on-bare-metal)

QE review: NA
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — APPROVED** [review]
Looks good to me! Although I am new to peer review, so please wait until @adellape approves of my review before proceeding to merge review. Thanks

**Review by adellape — COMMENTED** [review]
@skopacz1 @apinnick Peer review looks good 👍

**Pull request merged**
