### PR TITLE
[enterprise-3.5] Weekly Release: 02/16/18

### PR DESCRIPTION
**Pull request by vikram-redhat**

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@gaurav-nelson - check the install_config/advanced_install.adoc changes.

**Comment by vikram-redhat** [comment]
Travis is still very slow. I am merging this as local builds work ok.

**Comment by gaurav-nelson** [comment]
Thanks @vikram-redhat 

I had a look at it, but sorry I am confused. 😕 
I do not understand what went wrong. It will be helpful if you can walk me through this.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - sure. Let's talk Monday.

**Pull request merged**
