### PR TITLE
[OSDOCS-10864]: Update GCP OSD DOCS to reflect updated CSS and Non-CSS Instance Types

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10864
Link to docs preview:

https://77331--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-service-definition.html#gcp-compute-types_osd-service-definition
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
