### PR TITLE
Add new coreos layering example

### PR DESCRIPTION
**Pull request by mburke5678**
Adding a  [new coreos layering example](https://github.com/openshift/rhcos-image-layering-examples/blob/master/fish/Containerfile) to the layering docs. 

**No QE Required** The code example is QE reviewed and approved. This PR adds a link to pull in that example.

Preview: [RHCOS image layering ](https://58156--docspreview.netlify.app/openshift-enterprise/latest/post_installation_configuration/coreos-layering.html), a few screens down on the page:
Reworded: _Example Containerfile to apply the firewalld utility_
Added: _Example Containerfile to apply the libreswan utility_
Added: _Example Containerfile to apply a third-party package that has RHEL dependencies_

### CODE REVIEW

**Comment by mburke5678** [comment]
@sinnykumari PTAL

**Comment by sinnykumari** [comment]
Looks good, thanks Michael.
/lgtm

**Comment by sinnykumari** [comment]
This example was not reviewed by QE. So, we may want to get QE review.
/cc @rioliu-rh

**Comment by sergiordlr** [comment]
/lgtm 

Thank you very much!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
