### PR TITLE
[enterprise-4.17] CNV#40187-02: Misc RN Fix

### PR DESCRIPTION
**Pull request by danielclowers**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/CNV-40187

Link to docs preview:
https://82066--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-17-release-notes.html

QE review:
- [x] QE has approved this change.

Additional information:
* [CNV-43195](https://issues.redhat.com//browse/CNV-43195) removed per Kedar Bidarka
* [CNV-31997](https://issues.redhat.com//browse/CNV-31997) removed as Regional DR is GA when using GitOps workflow [(KCS)](https://access.redhat.com/articles/7053115)
* [CNV-31997](https://issues.redhat.com//browse/CNV-31997) removed from web console TP

### CODE REVIEW

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging

**Pull request merged**
