### PR TITLE
BZ2102230: change rhcos redirector url

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2102230

Link to docs preview: http://file.rdu.redhat.com/jdohmann/BZ2102230/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@travier @mike-nguyen can y'all PTAL to make sure URLs are correct? Also, the BZ ticket says to backport to 4.8, should this PR apply to 4.8-4.10 as well? Just wanna check. Thanks!

**Comment by mike-nguyen** [comment]
I think this applies all the way back to 4.6.  Possibly 4.5 depending on whether it breaks customers.

Here is the PR for 4.6 and 4.7
https://github.com/openshift/installer/pull/6138
https://github.com/openshift/installer/pull/6139

The RHCOS team is planning on doing a boot image bump for 4.9 and 4.8 where the URL will be updated in the installer

**Comment by jldohmann** [comment]
@mike-nguyen thanks for the info, I'm thinking maybe separate PRs for those would be best if they're not merged yet. If we cherrypicked this PR to 4.6-4.10 before the installer PRs are merged, customers won't have the correct information. Wdyt?

**Comment by GroceryBoyJr** [comment]
@jldohmann @mike-nguyen I recommend different PR's for each release. If the cherrypick fails (likely), you have to do individual PR's for each failing release anyway.

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM!

**Comment by mike-nguyen** [comment]
Agreed with separate PRs.  We'll just need to keep them in mind when the boot image bumps merge since they don't have a BZ directly tied to them.

**Comment by travier** [comment]
For 4.11, the installer will be release with this URL only, but for backports, we should include both URLs in the docs as older installers will keep using the previous one.

+1 for separate PRs that land when the installer changes land.

**Review by travier — APPROVED** [review]

**Pull request merged**
