### PR TITLE
OSDOCS-4396: remove restricted channel group option

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.11, 4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4396

Link to docs preview:
**Create objects**: https://52152--docspreview.netlify.app/openshift-rosa/latest/rosa_cli/rosa-manage-objects-cli.html#rosa-create-objects_rosa-managing-objects-cli
**List and describe objects**: https://52152--docspreview.netlify.app/openshift-rosa/latest/rosa_cli/rosa-manage-objects-cli.html#rosa-list-objects_rosa-managing-objects-cli

No QE review required.

### CODE REVIEW

**Review by arendej — APPROVED** [review]
Thanks for the removal

**Review by kelbrown20 — COMMENTED** [review]
Looks great! 
/lgtm

**Pull request merged**
