### PR TITLE
OSSMDOC-408: Delete trace verbosity level from Configuration Options

### PR DESCRIPTION
**Pull request by rh-tokeefe**
- Aligned team: Dev Tools
- For branches: 
- Jira: https://issues.redhat.com/browse/OSSMDO-408
- Direct link to doc preview: https://deploy-preview-40730--osdocs.netlify.app/openshift-enterprise/latest/distr_tracing/distr_tracing_install/distr-tracing-deploying.html#distr-tracing-config-jaeger-collector_deploying-distributed-tracing
- SME review: @ tbd
- QE review: @@iblancasa
- Peer review: @JStickler 
- Cherry pick to 4.6, 4.7, 4.8, 4.9, 4.10

### CODE REVIEW

**Comment by iblancasa** [comment]
Why did you create a new PR instead of working on the PR I created? #36100

**Review by iblancasa — CHANGES_REQUESTED** [review]
The same change is needed for `Table 15. Configuration parameters passed to Query` and `Table 16. Jaeger parameters passed to the Ingester` (#36100 for refrence).

Also, the table is not the same in the 3 cases. Some of them contains `Possible values` and the others not. The same for the final `.`.

**Comment by rh-tokeefe** [comment]
@iblancasa, thanks for providing the details in your review. Good catches, these are helpful changes, and I've submitted updates to this PR.

The reason I created this PR is that I simply did not know that you previously created one.

**Review by JStickler — APPROVED** [review]
LGTM

**Pull request merged**
