### PR TITLE
RHDEVDOCS-4817 - Logging 5.4.3 release notes errata link fix.

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.9+

Issue: [RHDEVDOCS-4817](https://issues.redhat.com//browse/RHDEVDOCS-4817)

Link to docs preview: https://access.redhat.com/errata/RHSA-2022:5556

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Review by gabriel-rh — APPROVED** [review]
/LGTM

**Pull request merged**
