### PR TITLE
Convert VFIO binding instructions to Butane

### PR DESCRIPTION
**Pull request by bgilbert**
Avoid separately applying base64 to input files.  Reorder instructions for a more natural flow.  Remove footnotes on some routine configuration fields to help center the more relevant ones.

cc @bobfuru

### CODE REVIEW

**Comment by bobfuru** [comment]
LGTM!

**Comment by bobfuru** [comment]
@miabbott for QE review, please

**Review by miabbott — APPROVED** [review]
LGTM

**Pull request merged**
