### PR TITLE
bug 1533347 clarifying time zone format

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1533347

@anpingli, will you PTAL or suggest a different reviewer for this change? Will you please also confirm that this change is valid back to 3.5? (I assume it will be.)

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@anpingli, will you PTAL or suggest a different reviewer for this change?

**Comment by kalexand-rh** [comment]
@openshift/team-documentation  PTAL

**Comment by mburke5678** [comment]
@kalexand-rh LGTM

**Pull request merged**
