### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@codyhoag, we just removed the requirement to wrap text at 80 characters, so you don't have to fix the line wrapping.

**Comment by codyhoag** [comment]
@kalexand-rh good to know! I just updated it. Thanks!

**Comment by kalexand-rh** [comment]
@codyhoag, it looks good to me. If you squash your commits, I'll merge it.

**Comment by codyhoag** [comment]
@kalexand-rh squashed 😊

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
Thanks, @codyhoag! Merging.

**Comment by mbearer** [comment]
nice work @codyhoag and @kalexand-rh !

**Pull request merged**
