### PR TITLE
Update name change for CNS and CRS

### PR DESCRIPTION
**Pull request by ghost**
Per Marketing:

- CNS mode will now be referred to as converged mode. 
- CRS mode will now be referred to as independent mode.

### CODE REVIEW

**Comment by jarrpa** [comment]
As I disagree with these changes, I will not be participating in their review. Please proceed without me.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - why not change the value of the attributes gluster-native and gluster-external in the attributes file, instead of everywhere that attribute is used? That is why they are there to help with these name changes?

**Comment by vikram-redhat** [comment]
@netzzer  - hey there. Please let us know if the changes made due the name change make sense.

**Comment by tmorriso-rh** [comment]
@vikram-redhat I didn't realize editing the attribute file was an option. How do I access that file? I will update that file and then "undo" the changes made in these files. Thanks.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Should I open a new PR to fix _snippets/glusterfs.adoc and then close this PR?

**Comment by vikram-redhat** [comment]
@tmorriso-rh - up to you but you can just update this PR.

**Comment by tmorriso-rh** [comment]
Closing in favor of new PR. Will add link to new PR.

**Comment by vikram-redhat** [comment]
@tmorriso-rh when closing PRs without merging, please remember to remove the labels.

**Pull request closed without merging**
