### PR TITLE
3scale Adapter Prerequisites Update (Mixer Behavior Change)

### PR DESCRIPTION
**Pull request by geekspertise**
The 3scale team requested this update to their Prerequisites for the Istio Adapter as a result of the change in Mixer behavior. I worked with @dfennessy on this update. Can @vramosp take a look at this for the 3scale team? And can @JStickler and @brian-avery just take a quick look?

### CODE REVIEW

**Comment by JStickler** [comment]
LGTM.

**Review by brian-avery — APPROVED** [review]
LGTM

**Comment by kalexand-rh** [comment]
The build finally passed and the change looks ok, so I'm merging.

**Pull request merged**
