### PR TITLE
note about colons in docker login usernames

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bmcelvee** [comment]
@bparees LGTM :four_leaf_clover: 

To which versions of OCP does this apply?

**Comment by bparees** [comment]
@bmcelvee all of them

**Comment by bmcelvee** [comment]
Thanks!

**Comment by bmcelvee** [comment]
@wzheng1 PTAL

**Comment by dongboyan77** [comment]
LGTM

**Pull request merged**
