### PR TITLE
BZ-2060950 fixing incorrect apiVersion in HTTP2 code sample

### PR DESCRIPTION
**Pull request by bscott-rh**
[Bugzilla link](https://bugzilla.redhat.com/show_bug.cgi?id=2060950)
Applies to 4.8+ 
[Preview link](https://deploy-preview-43959--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-http2-haproxy_configuring-ingress)

### CODE REVIEW

**Comment by bscott-rh** [comment]
@difloresv @zhaozhanqi Change is in, PTAL

**Comment by zhaozhanqi** [comment]
@lihongan ^^

**Comment by ShudiLi** [comment]
Failed to verify it with 4.8.0-0.nightly-2022-03-29-081438, the apiVersion is changed to config.openshift.io/v1 in PR43959, but oc apply the changed yaml file is failed. The kind IngressController should be changed to Ingress, and the name cluster should be added, too.

% oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.0-0.nightly-2022-03-29-081438   True        False         87m     Cluster version is 4.8.0-0.nightly-2022-03-29-081438
% 

2. fail to apply the changed yaml file
% oc apply -f test9.yaml
E0331 11:10:03.087391   17508 request.go:1085] Unexpected error when reading response body: net/http: request canceled (Client.Timeout or context cancellation while reading body)
error: unable to recognize "test9.yaml": no matches for kind "IngressController" in version "config.openshift.io/v1" 
% cat test9.yaml
apiVersion: config.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    ingress.operator.openshift.io/default-enable-http2: "true"
%

**Comment by ShudiLi** [comment]
The example yaml file is as below:
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
  annotations:
    ingress.operator.openshift.io/default-enable-http2: "true"
spec:
  domain: apps.shudi-48-gcpmn09.qe.devcluster.openshift.com
  
  
  We also can edit ingresses.config/cluster, and add the annotation directly.

**Comment by bscott-rh** [comment]
> The example yaml file is as below: apiVersion: config.openshift.io/v1 kind: Ingress metadata: name: cluster annotations: ingress.operator.openshift.io/default-enable-http2: "true" spec: domain: apps.shudi-48-gcpmn09.qe.devcluster.openshift.com
> 
> We also can edit ingresses.config/cluster, and add the annotation directly.

I've updated the PR with these changes. Can you take a look? Thank you

**Comment by ShudiLi** [comment]
The changes look good to me, I have marked bug 2060950 verified, thanks.

**Pull request merged**
