### PR TITLE
updating pv types for ARO and OSD

### PR DESCRIPTION
**Pull request by lamek**
https://issues.redhat.com/browse/OSDOCS-1061

### CODE REVIEW

**Comment by lamek** [comment]
Manual preview for ARO:
http://file.bos.redhat.com/klamenzo/2020-05-19/osd-update-storage-pv-types/_preview/openshift-aro/osd-update-storage-pv-types/storage/understanding-persistent-storage.html#types-of-persistent-volumes_understanding-persistent-storage

**Comment by jboxman** [comment]
@lamek, I notice this is labeled for 4.3, but against master. Is this only for enterprise-4.3?

**Comment by lamek** [comment]
I have to confirm with @vikram-redhat but I think we're gonna do 4.3 for the current live distros, and master for future upgrades.

I'll update the labels once I know.

**Comment by jboxman** [comment]
@lamek, cool, LGTM.

**Comment by lamek** [comment]
Thanks again Jason. Just an FYI - I updated the endif's to close with the matching string they open on, for clarity. Also, we are going ahead with pushing to master and upstream branches.

**Pull request merged**
