### PR TITLE
CNV#28731: hosted control planes on OCP Virt RN

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.14 only (RN)

Issue: [CNV-28731](https://issues.redhat.com//browse/CNV-28731)

Link to docs preview: https://67602--docspreview.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-14-release-notes#virt-4-14-new

QE review:
- [x] QE has approved this change. Satheesaran Sundaramoorthi acked this PR.

Additional information: To be merged when RHACM 2.9 releases. I ~will change the link to point to the 2.9 docs before merging~ changed the link to point to the 2.9 docs, but it currently 404s (2.9 docs are not live yet. Per @lahinson the release date moved). I will confirm that the link works before I merge this PR on the new ACM 2.9 release date.

### CODE REVIEW

**Comment by ousleyp** [comment]
@davidvossel and @lahinson - I'd appreciate your reviews, if possible :) thanks!

**Review by lahinson — COMMENTED** [review]
@ousleyp The wording here looks good to me. Although CNV is GA today (I think) and MCE is GA tomorrow, the RHACM docs won't be live until November 15, so I would wait to publish this release note until the link can point to the 2.9 docs. Otherwise, if people visit the link, it'll still say Technology Preview.

**Comment by lahinson** [comment]
@ousleyp FYI, the GA for the ACM docs slipped, so it won't be today. I don't know the new date yet. I will keep you posted!

**Comment by ousleyp** [comment]
> @ousleyp FYI, the GA for the ACM docs slipped, so it won't be today. I don't know the new date yet. I will keep you posted!

Thank you for the heads up. I really appreciate it!

**Comment by lahinson** [comment]
@ousleyp The new date for the ACM 2.9 GA is Nov. 20. I will be on PTO then, but you can check with Chris Dawson from the ACM team to confirm that GA has really happened on Monday.

**Comment by sjhala-ccs** [comment]
ACM 2.9 has shipped. Merging the PR.

**Comment by lahinson** [comment]
Hi @sjhala-ccs - Please note that although ACM 2.9 is supposed to ship today, the ACM docs are not yet live, so the link in this release note won't work yet.

**Comment by sjhala-ccs** [comment]
@lahinson Thanks for letting me know. Will the docs go live at some point today?

**Comment by lahinson** [comment]
@sjhala-ccs Yes, the are expected to go live today. I can post in this PR when they are live.

**Comment by lahinson** [comment]
@sjhala-ccs The RHACM docs are now live.

**Pull request merged**
