### PR TITLE
OCPBUGS#11688: Explained that adding new users is not supported -- Follow Up

### PR DESCRIPTION
**Pull request by mburke5678**
Follow up of https://github.com/openshift/openshift-docs/pull/58569 to rework the wording. Also split the two sentences into bullets, as they are not truly related.

### CODE REVIEW

**Comment by mburke5678** [comment]
@palonsoro 
Can you take a quick look to make sure I didn't change the meaning of the sentence you added? Thank you!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
very nice work @mburke5678! Wonderful clarification there.

**Pull request merged**
