### PR TITLE
BZ2013929 - Corrected rekey directory

### PR DESCRIPTION
**Pull request by StephenJamesSmith**
For OCP 4.9 

See https://bugzilla.redhat.com/show_bug.cgi?id=2013929 for additional details.

Preview: https://deploy-preview-37601--osdocs.netlify.app/openshift-enterprise/latest/security/network_bound_disk_encryption/nbde-managing-encryption-keys

Signed off by Stephen Smith stesmith@redhat.com

### CODE REVIEW

**Comment by StephenJamesSmith** [comment]
@vikram-redhat Can this be merged for GA? Has been QA Acked.

**Comment by vikram-redhat** [comment]
@StephenJamesSmith needs peer review?

**Comment by StephenJamesSmith** [comment]
@vikram-redhat QE Acked, Dev Acked, peer reviewed.

**Pull request merged**
