### PR TITLE
fix broken slave template url

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by ahardin-rh** [comment]
Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../using_images/other_images/jenkins.adoc#using-images-other-images-jenkins[Other Images -> Jenkins]
|Updated the Jenkins slave template URL within the xref:../using_images/other_images/jenkins.adoc#using-the-jenkins-kubernetes-plug-in-to-run-jobs[Using the Jenkins Kubernetes Plug-in to Run Jobs] section.
%

**Comment by vikram-redhat** [comment]
Cleaning up some of the labels for branches we don't use any more.

**Pull request merged**
