### PR TITLE
BZ1783183: Update the command

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 3.11

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=1783183

Link to docs preview: https://github.com/openshift/openshift-docs/pull/48817#issuecomment-1211534159

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
Screenshot 2022-08-11 at 9 41 11 AM

**Comment by Amrita42** [comment]
lgtm

**Comment by ahardin-rh** [comment]
LGTM

**Pull request merged**
