### PR TITLE
CNV-11468: Single VM import from RHV/VMware deprecated (RN)

### PR DESCRIPTION
**Pull request by apinnick**
https://issues.redhat.com/browse/CNV-11468

For CNV 4.8 release notes

Preview: https://deploy-preview-33200--osdocs.netlify.app/openshift-enterprise/latest/virt/virt-4-8-release-notes.html#virt-4-8-new

### CODE REVIEW

**Comment by apinnick** [comment]
@mgarrellRH  For CNV 4.8 release notes.

**Review by bergerhoffer — COMMENTED** [review]
LGTM other than just wondering whether it would be worthwhile for the CNV RN to have a separate deprecated features section?

**Comment by apinnick** [comment]
> LGTM other than just wondering whether it would be worthwhile for the CNV RN to have a separate deprecated features section?

@mgarrellRH  What do you think?

**Comment by mgarrellRH** [comment]
> > LGTM other than just wondering whether it would be worthwhile for the CNV RN to have a separate deprecated features section?
> 
> @mgarrellRH What do you think?

@apinnick @bergerhoffer I don't know if such a format change is in my power to decide. I do like the idea, but all I did was create the file based on the previous release's file because the CNV writers take turns in each different release with creating the notes. That said, I can bring it up in the CNV weekly team meeting in a bit over an hour and see what is said.

**Pull request merged**
