### PR TITLE
OSSM-4843: Update conditional tagging

### PR DESCRIPTION
**Pull request by rh-tokeefe**
Version(s): 4.10+

Issue: https://issues.redhat.com/browse/OSSM-4843

Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by fjglira — APPROVED** [review]
lgtm

**Comment by rh-tokeefe** [comment]
Posted in team channel asking if dev review is required. Andrea Hoffer replied and said this type of back-end change does not require dev  review.

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
