### PR TITLE
replaced NFS warning to logging docs per jcantrill

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1820678

### CODE REVIEW

**Review by jcantrill — APPROVED** [review]

**Comment by mburke5678** [comment]
@anpingli At Jeff's request, I put a note from 3.x docs into the 4.x docs regarding NFS. The note got dropped when  we removed all references to NFS for 4.x. 
Do you have any concerns with adding this note back to the docs?

**Review by anpingli — COMMENTED** [review]
LGTM

**Pull request merged**
