### PR TITLE
update the xref in release-3.7

### PR DESCRIPTION
**Pull request by warmchang**
the branch enterprise-3.7 should be update too.

### CODE REVIEW

**Comment by warmchang** [comment]
branch/enterprise-3.7 and above

**Comment by warmchang** [comment]
@ahardin-rh can you help to check this PR? Thanks!

**Comment by ahardin-rh** [comment]
@warmchang LGTM. Can you please squash this into 1 commit, however? That is required per our publishing process. Thanks!

**Comment by warmchang** [comment]
@ahardin-rh I have squashed them into 1 commit, Please check it. Thanks!

**Comment by ahardin-rh** [comment]
LGTM! Thanks!

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
