### PR TITLE
Update installation methods table and storage size [enterprise-4.4][enterprise-4.5]

### PR DESCRIPTION
**Pull request by rolfedh**
This PR fixes issue #21764 in master, enterprise-4.4, and enterprise-4.5

### CODE REVIEW

**Comment by peterclauterbach** [comment]
LGTM

**Comment by peterclauterbach** [comment]
LGTM

**Comment by lamek** [comment]
LGTM. I did a local build to preview.

**Comment by rolfedh** [comment]
@vikram-redhat  Can you merge this now?

**Comment by vikram-redhat** [comment]
@lamek PTAL

**Comment by lamek** [comment]
Manual CP for 4.4 https://github.com/openshift/openshift-docs/pull/21821
Manual CP for 4.5 https://github.com/openshift/openshift-docs/pull/21822

**Review by emarcusRH — CHANGES_REQUESTED** [review]
@rolfedh The use of the memory units GiB is not consistent with the IBM Style Guide - it should be GB, and there should be a single space between the number and the units of measure

All the rest of the changes look good.

**Pull request merged**
