### PR TITLE
OCPBUGS#26213: Graphic image file is changed in default clusters roles

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.15,4.14,4.13,4.12

Issue:
[OCPBUGS-26213](https://issues.redhat.com/browse/OCPBUGS-26213)

Link to docs preview:
https://71533--ocpdocs-pr.netlify.app/openshift-enterprise/latest/authentication/using-rbac#default-roles_using-rbac

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by johnsimcall** [comment]
Thank you for changing "binging" to "binding" in the image! Looks good to me!

**Comment by mramendi** [comment]
LGTM for peer review, but as I am in peer review induction. @JoeAldinger will finish the review

**Review by JoeAldinger — COMMENTED** [review]
/lgtm, I think this still needs QE.

**Pull request merged**
