### PR TITLE
[SRVKS-1081] Add net-kourier-controller liveness probe error known issue to 1.29

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
Serverless 1.29+

Issue:
https://issues.redhat.com/browse/SRVKS-1081

Link to docs preview:
https://61374--docspreview.netlify.app/openshift-serverless/latest/about/serverless-release-notes.html#known-issues-1-29-0_serverless-release-notes

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by rh-max** [comment]
@gabriel-rh Hi Gabriel, could you PTAL? Thank you.

**Review by gabriel-rh — APPROVED** [review]
LGTM

**Pull request merged**
