### PR TITLE
Bug 1679130, clarified that the CRI-O packages are automatically installed

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1679130

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@chrisnegus Please take a look. Thanks!

**Comment by ahardin-rh** [comment]
@gpei  Can you please provide QE review? Thank you!

**Comment by gpei** [comment]
LGTM

**Comment by ahardin-rh** [comment]
Thank you!

**Pull request merged**
