### PR TITLE
Edits to DNS path info

### PR DESCRIPTION
**Pull request by bfallonf**
@thoraxe @smarterclayton As discussed over email, this PR is in regards to these changes:

https://lists.openshift.redhat.com/openshift-archives/dev/2015-May/msg00037.html

I converted the examples into a table, but not sure if I'm on the right track. Thoughts?

Also, @mfojtik I'm not too sure what to do with the SRV examples and how it fits in. Thoughts?

Thanks, guys.

### CODE REVIEW

**Comment by thoraxe** [comment]
This still isn't *usage* documentation.

* How do I find the "cluster"/endpoints with DNS?
* What information is stored in the SRV records? How do I access them?

We need more examples.

**Comment by bfallonf** [comment]
@thoraxe @smarterclayton  OK. Maybe we need clearer objectives here. Because this PR came from an email conversation and not a card I didn't expect it to be great first try. So then, a few questions:

1. Firstly, is the information I have already put in here correct? It's really just the table of DNS example names that I added.

2. How _do_ I find the "cluster"/endpoints? I can't seem to understand any of this from some googling, so I'm not even sure of the right question to ask, really.

3. I can find what SRV is and what the info means when it's found, but finding it is the hard part. Is there an OpenShift specific method for accessing SRV records? @mfojtik did Clayton mention you were the go-to-guy for this?

4. Erik, you mentioned in the initial email that there's no info on SkyDNS. Is there something to do with that you'd like to see in the docs?

I think that's all. Again, if I'm on the wrong track let me know. Also, if I'm asking the wrong questions, or if there's someone else I should be asking, let me know. 

Thanks.

**Comment by thoraxe** [comment]
1. I think so?

2. I think when you dig the service you're supposed to be returned a list of all the endpoints as a list of A records. EG:

dig servicename.namespace.svc.cluster.local

servicename.namespace.svc.cluster.local IN A 10.x.x.x
servicename.namespace.svc.cluster.local IN A 10.x.x.x
servicename.namespace.svc.cluster.local IN A 10.x.x.x
...

3. No, again, I think this is a dig "-t srv" against the service name. But showing an example is the thing.

4. I'm not sure that I mentioned that. I think this doc is somewhat sufficient to describe what SkyDNS is all about, it's just not complete enough (missing detail regarding what the stored info looks like).

**Comment by smarterclayton** [comment]
Only for headless services.  Regular services return the portalIp as an A record.  The "endpoints" path type will always return A records

**Comment by thoraxe** [comment]
* Only for headless services
    What defines a headless service?

* Regular services return the portalip as an A record
    What's a "regular" service?

* The "endpoints" path type will always return A records
    I assume you mean "<name>.<namespace>.endpoints.cluster.local" from the PR, but if that's the case, shouldn't <name> be <servicename> ?

**Comment by adellape** [comment]
I was noticing this example log message earlier up in the topic:

```
0308 19:51:03.118430    4484 node.go:197] Started Kubelet for node
openshiftdev.local, server at 0.0.0.0:10250
I0308 19:51:03.118459    4484 node.go:199]   Kubelet is setting 10.0.2.15 as a
DNS nameserver for domain "local"
```

Which I figured would also need to be updated to show `cluster.local` instead of `local`, but I couldn't find this message in actual start-up logs anymore (on both an all-in-one and a 2 node cluster, latest build via Vagrant). It seems like it was removed per https://github.com/openshift/origin/pull/2323/files#diff-5009334e857b25f4efb55d2d21f157e1L240.

I do see the following messages from the master:

```
2015/06/03 16:50:23 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/06/03 16:50:23 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
I0603 16:50:23.883794   20990 master.go:840] OpenShift DNS listening at 0.0.0.0:53
```

@smarterclayton Are there any similarly relevant Kubelet messages anymore to show from nodes that I'm missing?

**Comment by adellape** [comment]
Gonna merge this so we can at least get the table in there, and @bfallonf can follow-up with more.

**Pull request merged**
