### PR TITLE
GH#36147 BM IPI support missed in intro text

### LINKED ISSUE #36147: [enterprise-4.8] Issue in file installing/index.adoc
### Which section(s) is the issue in?
The "Supported Platforms for OpenShift Clusters for IPI"
https://docs.openshift.com/container-platform/4.8/installing/index.html#supported-platforms-for-openshift-clusters_ocp-installation-overview

### What needs fixing?
I'm pretty sure we support IPI on Bare Metal now. We're doing this with partners. But "Bare Metal" is missing from this list.

However Bare Metal does appear in the next list in the doc for UPI targets. So it appears to be missing from the IPI list. Unless I am mistaken and it's still in TP.

This may also be present in the 4.7 docs.

### PR DESCRIPTION
**Pull request by codyhoag**
Resolves #36147

Preview: https://deploy-preview-36158--osdocs.netlify.app/openshift-enterprise/latest/installing/index.html#supported-platforms-for-openshift-clusters_ocp-installation-overview

BM IPI support was introduced in OCP 4.6

### CODE REVIEW

**Comment by codyhoag** [comment]
@pamoedom can you confirm? This change is adding bare metal to the list of supported IPI installation options. Thanks!

**Comment by pamoedom** [comment]
Hi @codyhoag, AFAIK, IPI BM should be on the supported IPI list since OCP 4.6.
I was able to find this [release note](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-bare-metal-ipi) that confirms it.
Regards.

**Review by skrthomas — APPROVED** [review]
LGTM :)

**Pull request merged**
