### PR TITLE
OSDOCS-10525: ROSA integrations with Databases etc... is either unclear or erroneous

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-10525](https://issues.redhat.com//browse/OSDOCS-10525): ROSA integrations with Databases etc... is either unclear or erroneous

Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-10525

Link to docs preview:
https://76387--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_architecture/rosa-understanding.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @bchandra-ocp! Can you please take a look and review this PR? Thanks!

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can you please review this PR? Thanks so much!

**Pull request merged**
