### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by yigitpolat**
This section is about GCP however the command output is from AWS screen. Fixed and created PR.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@mjpytlak, will you PTAL?

**Comment by mjpytlak** [comment]
@yigitpolat Thank you for taking the time to comment on the OpenShift doc. This was addressed in https://github.com/openshift/openshift-docs/pull/45796. The writing team actually decided to remove the example. Not only did it affect the GCP installation material, but many other installation topics. Given that the example was only a step response to running a command, it offered little value in the doc.

**Comment by yigitpolat** [comment]
okay, thanks for the information. ✌️

**Comment by mjpytlak** [comment]
Would you mind closing the PR? Thank you.

**Pull request closed without merging**
