### PR TITLE
OSDOCS-9085: Adding attributes and IDs to custom domain tutorial

### PR DESCRIPTION
**Pull request by bmcelvee**
Combines the rebase of @laubai's PR https://github.com/openshift/openshift-docs/pull/69451 and this PR https://github.com/openshift/openshift-docs/pull/69440. Reviews were conducted on original PRs.

Version(s):
4.14+

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by laubai** [comment]
LGTM @bmcelvee - can we merge?

**Comment by bmcelvee** [comment]
Thank you, @laubai! Merging now :)

**Pull request merged**
