### PR TITLE
CNV-18431: Monitoring live migrations UI

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.12

Issue: [CNV-18431](https://issues.redhat.com//browse/CNV-18431), [CNV-18454](https://issues.redhat.com//browse/CNV-18454)

Link to docs preview: [Monitoring live migration](https://54337--docspreview.netlify.app/openshift-enterprise/latest/virt/live_migration/virt-monitor-vmi-migration.html)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by avivtur** [comment]
Hi @apinnick 
looks great :) LGTM from my side

**Review by lkladnit — APPROVED** [review]

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
