### PR TITLE
OSDOCS#12011: Fix syntax

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.17 and main

Issue: https://issues.redhat.com/browse/OSDOCS-12011

Link to docs preview:
- https://81828--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.html#hcp-ibmz-lpar-agents_hcp-deploy-ibmz
- https://81828--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-manage/hcp-manage-bm.html#hcp-bm-access_hcp-manage-bm
- https://81828--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-manage/hcp-manage-bm.html#hcp-bm-add-np_hcp-manage-bm
- https://81828--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-manage/hcp-manage-bm.html#hcp-bm-scale-np_hcp-manage-bm
- https://81828--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-manage/hcp-manage-bm.html#hcp-bm-autoscale_hcp-manage-bm

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
/label peer-review-needed

Adding this to peer review before the QE approval because the changes are minor and mostly non-technical.

**Review by lahinson — COMMENTED** [review]
Great changes. Thank you!

**Pull request merged**
