### PR TITLE
The fields in this module are duplicated elsewhere

### PR DESCRIPTION
**Pull request by jboxman**
Eventually these fields were added into the following module:
modules/installation-configuration-parameters.adoc

It is easier to drop the older module than excise it from the
aforementioned module.

Preview:
- [Installation configuration parameters](https://deploy-preview-31186--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-configuration-parameters_installing-aws-customizations)

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM

**Comment by jboxman** [comment]
@bergerhoffer thanks!

**Pull request merged**
