### PR TITLE
OSDOCS-1789: Updating apiVersion to v1

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1789

Preview: https://deploy-preview-31740--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html

### CODE REVIEW

**Comment by mburke5678** [comment]
@bergerhoffer LGTM

**Comment by bergerhoffer** [comment]
@damemi @kasturinarra Can you review this update to change the descheduler version from v1beta1 to v1?

Preview: https://deploy-preview-31740--osdocs.netlify.app/openshift-enterprise/latest/nodes/scheduling/nodes-descheduler.html

@damemi @soltysh We also need to add something to the release notes for this change, but I'm struggling with what to say about it. Because technically the descheduler as a whole was marked as GA for 4.7: https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-descheduler-ga

So do you have any thoughts for what we'd say about this change?

**Review by damemi — COMMENTED** [review]
LGTM

**Comment by soltysh** [comment]
> @damemi @soltysh We also need to add something to the release notes for this change, but I'm struggling with what to say about it. Because technically the descheduler as a whole was marked as GA for 4.7: https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-descheduler-ga
> 
> So do you have any thoughts for what we'd say about this change?

Maybe just put in the release notes the fact that we switched from v1beta1 to v1, and that's sufficient.

**Pull request merged**
