### PR TITLE
[enterprise-3.6]  oc describe node shows less information

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1572985

### CODE REVIEW

**Comment by sjenning** [comment]
LGTM

**Comment by mburke5678** [comment]
@zhouying7780 PTAL

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
