### PR TITLE
Backup and restore updates

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1445014

Related work:
https://github.com/openshift/openshift-docs/pull/10105
https://github.com/openshift/openshift-docs/pull/11157

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@deads2k @bparees PTAL

**Comment by bparees** [comment]
lgtm

**Comment by ahardin-rh** [comment]
@soltysh I am told in the BZ that more is needed here to resolve the BZ, but it's not clear to me what that is. Are you able to help?

**Comment by ahardin-rh** [comment]
Closing this, as the information is now outdated. Whatever changes need to be applied need to be applied to 3.5 and 3.6 and not master. Still waiting on guidance in the BZ. Looks like `oc export` is deprecated in 3.11, but not before then.

**Pull request closed without merging**
