### PR TITLE
Adds Broadcom_bnxt_en_BCM57504_NetXtreme support to SRIOV docs table

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-7790

Link to docs preview:
https://65068--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov#supported-devices_about-sriov

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by SalDaniele** [comment]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM!
/lgtm

**Pull request merged**
