### PR TITLE
BZ2022560: Adds m6i AWS EC2 instance

### PR DESCRIPTION
**Pull request by opayne1**
[BZ link](https://bugzilla.redhat.com/show_bug.cgi?id=2022560)

- Applies to versions `enterprise-4.6`+
- [Preview link](https://deploy-preview-38872--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-customizations.html#installation-supported-aws-machine-types_installing-aws-customizations)

### CODE REVIEW

**Comment by yunjiang29** [comment]
@opayne1 
`c4.large` and `c4.xlarge` should not be in the list, the minimum requirements for worker node is 2 vCPU and  8 GB memory.

**Comment by opayne1** [comment]
@yunjiang29 Thank you for clarifying I think I was a little confused there. I have updated.

**Comment by yunjiang29** [comment]
@opayne1 LGTM, thanks for the updates.

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
