### PR TITLE
OCPBUGS-10550 removing erroneous line as per PR 54754

### PR DESCRIPTION
**Pull request by kquinn1204**
[OCPBUGS-10550]: Removing line "The only allowed values for Mellanox cards are 1015, 1017."

Version(s):
main, 4.13, 4.12, 4.11

Issue:
https://issues.redhat.com/browse/OCPBUGS-10550

Link to docs preview:
https://57399--docspreview.netlify.app/openshift-enterprise/latest/networking/hardware_networks/using-dpdk-and-rdma.html#example-vf-use-in-rdma-mode-mellanox_using-dpdk-and-rdma

When I got this https://github.com/openshift/openshift-docs/pull/54754 merged, I should have followed through on the other instance in the docs. This PR addresses that oversight. 

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Fixmetal** [comment]
thanks, @kquinn1204 
/lgtm my side

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM! Good work sir!

**Review by kelbrown20 — COMMENTED** [review]
This LGTM as well!

**Pull request merged**
