### PR TITLE
Bug 1525557: Changed Downward API configuration example

### PR DESCRIPTION
**Pull request by ghost**
Link to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1525557

### CODE REVIEW

**Comment by wkulhanek** [comment]
@tmorriso-rh I think this needs a bit more changes. E.g. further down there is a reference to the "metadata" line which no longer seems to exist. Also the example further down would need updating as well I think. I would also recommend getting engineering involved to make sure we are documenting what is actually implemented in 3.7+. Things seem to have changed a bit here.

**Comment by tmorriso-rh** [comment]
Thanks @wkulhanek. I have forwarded your comment to the QA team for review.

**Comment by jhou1** [comment]
LGTM

**Comment by tmorriso-rh** [comment]
@wkulhanek or @jhou1 Can you please specify the other example that needs to be updated? Also, what specific changes need to be made to this example?

**Comment by wkulhanek** [comment]
@tmorriso-rh The Kubernetes Documentation seems to have it correct:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by tmorriso-rh** [comment]
Additional changes made on 01/08/18. Back to QA for review.

**Comment by jhou1** [comment]
LGTM

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Pull request merged**
