### PR TITLE
bug 1724028 remove startingCSV line in section 2f

### PR DESCRIPTION
**Pull request by bobfuru**
Removed line 178 (step 2f): startingCSV: "elasticsearch-operator.v4.1.0"
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1724028
@openshift/team-documentation

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
The bug says no QE, so LTGM.

**Comment by vikram-redhat** [comment]
@bobfuru the callout marker and line have been removed, but you also need to remove the callout listing for the marker that you removed: https://github.com/openshift/openshift-docs/pull/15932/files#diff-ed2514a91149983674ad7ff3485f7499R181.

So <3> was removed, but the <3> explanation remains which is not right.

Please submit a new PR to remove the <3> explanation as well.

**Comment by vikram-redhat** [comment]
And now we also have a bug for it: https://bugzilla.redhat.com/show_bug.cgi?id=1731588 :)

**Comment by bobfuru** [comment]
@vikram I have submitted a new PR per your note and bug 1731588 to remove the callout listing for the callout #3 marker.

**Comment by vikram-redhat** [comment]
New PR is: https://github.com/openshift/openshift-docs/pull/15959

**Pull request merged**
