### PR TITLE
BZ1958300: Update supported GCP installer regions 4.6+

### PR DESCRIPTION
**Pull request by michaelryanpeter**
4.6+

https://bugzilla.redhat.com/show_bug.cgi?id=1958300

Should be merged before #32803

Fixes #32649 

Direct link to docs preview: https://deploy-preview-32802--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#installation-gcp-regions_installing-gcp-account

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
Verified by QE.

**Comment by bobfuru** [comment]
LGTM!

**Pull request merged**
