### PR TITLE
Correct login command for accessing internal registry

### LINKED ISSUE #19712: [enterprise-4.2] Edit suggested in file registry/accessing-the-registry.adoc
### Which section(s) is the issue in?
Registry/Accessing the registry/Accessing registry directly from the cluster

### What needs fixing?
`oc login` command is missing the api URL.

### PR DESCRIPTION
**Pull request by janehojy**
Fixes #19712 

`oc login` command needs api url.

### CODE REVIEW

**Comment by janehojy** [comment]
Bump. 4.3 docs needs the fix too

https://docs.openshift.com/container-platform/4.3/registry/accessing-the-registry.html#registry-accessing-directly_accessing-the-registry

**Comment by jboxman** [comment]
@bmcelvee @sheriff-rh 

You've both touched this file; Any ideas on who can take a look?

Thanks!

**Comment by bmcelvee** [comment]
I can take a look this afternoon, thanks.

**Comment by bmcelvee** [comment]
LGTM. @wzheng1 would you mind giving this a quick review, please? Thanks!

**Comment by wzheng1** [comment]
Acked by QE.

**Comment by bmcelvee** [comment]
Merging and cherrypicking now - thank you @janehojy and @wzheng1!

**Pull request merged**
