### PR TITLE
Elasticsearch Logging Performance Edits

### PR DESCRIPTION
**Pull request by mburke5678**
https://docs.google.com/document/d/1h3vSpJWkhlQmvG5wHWXIQedx_TAgIoCX1Pc1rZuZjhM/edit#heading=h.ma7s939l68g9

### CODE REVIEW

**Comment by mburke5678** [comment]
Jeff -- Please let me know if this meets your expectations. If I took too much out or not enough.

**Review by jcantrill — APPROVED** [review]

**Pull request merged**
