### PR TITLE
Adds 4.6.46 release notes

### PR DESCRIPTION
**Pull request by darshan-nagaraj**
No BZ.

Preview: https://deploy-preview-36783--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-6-release-notes.html#ocp-4-6-46

Not to be merged until 9-29.

### CODE REVIEW

**Comment by darshan-nagaraj** [comment]
> This LGTM too. However, a travis check wasn't run on this PR (which happens randomly sometimes unfortunately).
> 
> @darshan-nagaraj One way that you can force travis to build is to fetch and rebase (if there are new changes) and push them to this PR. Can you try that please and hopefully that will kick off the travis build? We don't want to merge unless there is a successful travis build.

@bergerhoffer Done! Now looks like LGTM label has been removed. Should I ask @ctauchen to add the LGTM label?

**Comment by bergerhoffer** [comment]
> @bergerhoffer Done! Now looks like LGTM label has been removed. Should I ask @ctauchen to add the LGTM label?

We don't actually rely on the "lgtm" label or anything like that. we just check that the "peer review done" label is set and that someone from the OCP docs peer reviewing team said it looked good (in a comment). So it should be good to go for tomorrow when you're ready for this to be merged!

**Pull request merged**
