### PR TITLE
RHDEVDOCS 4015 - CP to 4.7 - Corrected case of value 'SystemMaxUse=8g' to 'SystemMaxUse=8G'

### PR DESCRIPTION
**Pull request by libander**
Manual CP of https://github.com/openshift/openshift-docs/pull/44984 

Branches: 4.7

### CODE REVIEW

**Comment by maxwelldb** [comment]
> Branches: 4.7, 4.6

Should this just say 4.7? 4.6 should be a separate PR.

**Comment by libander** [comment]
> > Branches: 4.7, 4.6
> 
> Should this just say 4.7? 4.6 should be a separate PR.
Yes, I'll create a 4.6. Can this be merged?

**Comment by maxwelldb** [comment]
@libander I'd check in with the current peer review squad rotation to merge this and the other PR.

**Pull request merged**
