### PR TITLE
[logging-5.3]RHDEVDOCS-2681 Document "Remove legacy configuration mechanism for lo…

### PR DESCRIPTION
**Pull request by rolfedh**
…g forwarding from RHOL"

Purpose: Removed the "Forwarding logs using the legacy Fluentd method" and "Forwarding logs using the legacy syslog method" topics from our documentation.

- Aligned team: Dev Tools
- For branches: 4.9+ (Logging 5.3+)
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-2681
- Direct link to doc preview: https://deploy-preview-36302--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-external.html
- SME review: @jcantrill 
- QE review: @kabirbhartiRH 
- Peer review: @Eva-Lotte
- All reviews complete. Please merge when Logging 5.3 GA goes live.

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by Eva-Lotte** [comment]
looks good to me too!

**Pull request merged**
