### PR TITLE
Remove CMS configuration for Fujitsu iRMC

### PR DESCRIPTION
**Pull request by zhouhao3**
At present, Fujitsu iRMC no longer needs to configure CSM, delete related configuration content.

Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@johnwilkins, will you PTAL?

**Comment by zhouhao3** [comment]
Hi, PTAL.

**Review by johnwilkins — APPROVED** [review]
LGTM.

**Comment by kalexand-rh** [comment]
We need to make sure that this goes through QE before it's merged.

**Comment by johnwilkins** [comment]
> We need to make sure that this goes through QE before it's merged.

@zhouhao3 Can you verify that this was tested? @kalexand-rh Fujitsu does the testing on this, because QE does not have Fujitsu hardware.

**Comment by jeana-redhat** [comment]
Reading back over the history here, I am removing the merge review labels until @zhouhao3 lets us know that this is validated. 

@zhouhao3 - I think you might be able to add the request label back yourself if you want, and then it will go in our queue. Just comment with `/label merge-review-needed` if this has been validated. Thanks!

**Comment by zhouhao3** [comment]
/label merge-review-needed

@johnwilkins @jeana-redhat Thanks, we have verified on Fujitsu's server, it is ok.

**Comment by zhouhao3** [comment]
> @zhouhao3: Can not set label merge-review-needed: Must be member in one of these teams: [team-red-hat]

@jeana-redhat It looks like I can't add labels, can you help me?

**Comment by johnwilkins** [comment]
@zhouhao3 Is this strictly for 4.12+, or did this get done in a z-stream release too?

**Comment by zhouhao3** [comment]
> @zhouhao3 Is this strictly for 4.12+, or did this get done in a z-stream release too?

This get done in a z-stream release, no restrictions on versions.

**Pull request merged**
