### PR TITLE
Fix instance of "the the" per BZ

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1557217

### CODE REVIEW

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. So simple a change I want to make sure i didn't make an error from not paying attention!

**Comment by mburke5678** [comment]
This issue also appears in all versions back to 3.3. Will change those versions as needed in separate PRs

**Comment by bmcelvee** [comment]
LGTM :four_leaf_clover:

**Comment by mburke5678** [comment]
3.5 PR https://github.com/openshift/openshift-docs/pull/8173
3.4 https://github.com/openshift/openshift-docs/pull/8175
3.3 https://github.com/openshift/openshift-docs/pull/8178

**Pull request merged**
