### PR TITLE
[OSP] Document PV limit workaround 

### PR DESCRIPTION
**Pull request by maxwelldb**
Context: https://issues.redhat.com/browse/OSDOCS-1278

### CODE REVIEW

**Comment by maxwelldb** [comment]
@mandre Are there other properties that might be documented here, or is it just the two for now?

**Comment by mandre** [comment]
> @mandre Are there other properties that might be documented here, or is it just the two for now?

There's also `"hw_qemu_guest_agent": "yes"` to enable QEMU guest agent. See OSASINFRA-1508.

**Comment by maxwelldb** [comment]
Added.

**Comment by maxwelldb** [comment]
@mandre Any other requirements, here?

**Review by mandre — APPROVED** [review]
LGTM :+1:

**Comment by maxwelldb** [comment]
Thanks!

**Comment by maxwelldb** [comment]
@duanwei33 Ready for QE.

**Comment by duanwei33** [comment]
@wjiangjay 
Could you take a look from installation-qe side?

**Comment by maxwelldb** [comment]
@duanwei33 @wjiangjay Any updates on this one?

**Comment by maxwelldb** [comment]
@duanwei33 Thanks!

**Comment by maxwelldb** [comment]
@openshift/team-documentation Ready for review. Thanks!

**Comment by ahardin-rh** [comment]
LGTM! Just need to squash the commits and you're set. :rocket:

**Pull request merged**
