### PR TITLE
Bug 1813277, added clarification about 3.11 maximum

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1813277

Preview builds of footnote and footnote placement:
http://file.rdu.redhat.com/~ahardin/April-7-2020/3-11-tested-maximums-note/scaling_performance/cluster_maximums.html#_footnotedef_2

http://file.rdu.redhat.com/~ahardin/April-7-2020/3-11-tested-maximums-note/scaling_performance/cluster_maximums.html#scaling-performance-current-cluster-maximums

@RobertKrawitz PTAL

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@mffiedler Can you please provide QE review?

**Review by kalexand-rh — COMMENTED** [review]
The change LGTM, but it seems a little weird that we're documenting a functional limit on a table about tested values. I'm curious if there are other hard stops to present.

**Comment by ahardin-rh** [comment]
Closing per comments in the BZ

**Pull request closed without merging**
