### PR TITLE
OSDOCS-3910-4.12:adds networking metrics to RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
[OSDOCS-3910](https://issues.redhat.com//browse/OSDOCS-3910): adds networking metrics to RNS

Version(s):
4.12

Issue:
[Jira](https://issues.redhat.com/browse/OSDOCS-3910?filter=-1) 

Link to docs preview:
[Preview](https://53105--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-networking)

QE review:
- [x] QE has approved this change.

Additional information:
@qiowang721 PTAL for QE review

### CODE REVIEW

**Comment by qiowang721** [comment]
Hi @JoeAldinger , seems there is only one new metrics i tested for https://issues.redhat.com/browse/SDN-3127
`ovn_controller_southbound_database_connected`
The metrics you listed was released in 4.10. @martinkennelly Could you please help to double check this, please correct me if i'm wrong. Thanks a lot!

**Comment by martinkennelly** [comment]
@qiowang721 yes, you are right.

**Comment by qiowang721** [comment]
> @qiowang721 yes, you are right.

Thanks for confirming~

**Pull request merged**
