### PR TITLE
OSDOCS-12708 Updating a cli plugin with cli-manager

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.17 +

Issue: [OSDOCS-12708](https://issues.redhat.com/browse/OSDOCS-12708)

Link to docs preview:

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by ardaguclu** [comment]
LGTM
Thank you

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM, with a couple suggestions. Excellent work!

**Pull request merged**
