### PR TITLE
Adding disk and cd-rom modules for 4.3

### PR DESCRIPTION
**Pull request by bgaydosrh**
Checking Build

### CODE REVIEW

**Comment by bgaydosrh** [comment]
This PR adds missing module refs for disk and CD-ROM in 4.3
@aburdenthehand will peer review and then this can be merged and picked to 4.3 only.

Test Build: http://file.bos.redhat.com/bgaydos/011320_2/cnv/cnv_users_guide/

Thanks
Bob

**Comment by ousleyp** [comment]
This PR LGTM. 

However, the following modules are missing introductions: 

- Editing a virtual machine YAML configuration using the CLI
- Adding a virtual disk to a virtual machine
- Adding a network interface to a virtual machine

Can you please make note of that (if you haven't already) and fix it in a different PR? Thanks!

**Comment by bgaydosrh** [comment]
> This PR LGTM.
> 
> However, the following modules are missing introductions:
> 
>     * Editing a virtual machine YAML configuration using the CLI
> 
>     * Adding a virtual disk to a virtual machine
> 
>     * Adding a network interface to a virtual machine
> 
> 
> Can you please make note of that (if you haven't already) and fix it in a different PR? Thanks!

Will do. Thanks Pan.

**Review by sheriff-rh — APPROVED** [review]

**Pull request merged**
