### PR TITLE
OCPBUGS-13395: adds known issue to 4.13 RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
OCPBUGS-13395: adds known issue to 4.13 RNs

Version(s):
4.13

Issue:
https://issues.redhat.com/browse/OCPBUGS-13395
https://issues.redhat.com/browse/OSDOCS-5573

Link to docs preview:
[working on it
](http://file.rdu.redhat.com/jaldinge/OCPBUGS-13395/release_notes/ocp-4-13-release-notes.html#ocp-4-13-known-issues)

QE review:
- [ ] QE has approved this change.

Additional information:
Combines a TP table update and a known issue

### CODE REVIEW

**Comment by maxwelldb** [comment]
@JoeAldinger We typically avoid that sort of language, but I'm less concerned about it in a case like this. Seems like those changes really are in the pipeline.

**Comment by JoeAldinger** [comment]
> @JoeAldinger We typically avoid that sort of language, but I'm less concerned about it in a case like this. Seems like those changes really are in the pipeline.

That's what I thought. I just wanted to make sure we were good to include it.

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
