### PR TITLE
IBM-power-typo:fixes a typo

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OCPBUGS-25360

Link to docs preview:
https://69338--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing-preparing#:~:text=You%20can%20also%20complete,you%20can%20also%20customize

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by lahinson — COMMENTED** [review]
lgtm

**Comment by JoeAldinger** [comment]
typo found [here](https://github.com/openshift/openshift-docs/pull/69170/files#diff-7a06762359d4d38228c7c8d974a10016f2e10f4230a3ff910b1b5b6818514c07R70)

**Comment by bergerhoffer** [comment]
This should have been cherry picked to 4.15 too, so doing that now.

**Comment by bergerhoffer** [comment]
Nvmd I see you just kicked it off :)

**Pull request merged**
