### PR TITLE
Ext Auth Release Note

### PR DESCRIPTION
**Pull request by EricPonvelle**
Version(s):
`enterprise-4.15+`

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:
Added a release note about the new Ext Auth support

### CODE REVIEW

**Comment by zanetworker** [comment]
lgtm

**Review by jneczypor — COMMENTED** [review]
/lgtm

**Comment by EricPonvelle** [comment]
/enterprise-4.15

**Comment by EricPonvelle** [comment]
/enterprise-4.16

**Comment by anjaltelang** [comment]
lgtm

**Pull request merged**
