### PR TITLE
OSDOCS-2194: Azure Auto Migration (TP)

### PR DESCRIPTION
**Pull request by lpettyjo**
4.9+

[OSDOCS-2194:](https://issues.redhat.com/browse/OSDOCS-2194) Azure Disk added to auto migration feature (Tech Preview).

**Preview**: https://deploy-preview-34444--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-migration.html

PTAL: @Elbehery, @duanwei33

### CODE REVIEW

**Comment by duanwei33** [comment]
Hi @lpettyjo, this is not added by this PR but could you help replace "The following drivers" with "The following CSI drivers"?

The following drivers are supported:
* Amazon Web Services (AWS) Elastic Block Storage (EBS)
* OpenStack Cinder
* Azure Disk

**Comment by lpettyjo** [comment]
> Hi @lpettyjo, this is not added by this PR but could you help replace "The following drivers" with "The following CSI drivers"?
> 
> The following drivers are supported:
> 
> * Amazon Web Services (AWS) Elastic Block Storage (EBS)
> * OpenStack Cinder
> * Azure Disk
> 
> Others are lgtm.

HI @duanwei33, I'm not really referring to the CSI drivers, as such. I'm actually referring to what storage services allow for the auto migration of in-tree to CSI driver. Would changing it to "The following storage services are supported" make sense to you?

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by duanwei33** [comment]
@lpettyjo Sorry looks like I missed the notification from github. Hmm I don't have a better word, I think we can leave it there.

**Pull request merged**
