### PR TITLE
[MULTIARCH-3396] Add IBM SE support to RNs

### PR DESCRIPTION
**Pull request by SNiemann15**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/MULTIARCH-3396

Link to docs preview: https://57843--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-rhcos

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by holgwolf** [comment]
lgtm

**Comment by SNiemann15** [comment]
> @SNiemann15 IBM Secure Execution on IBM zSystems and LinuxONE still appeatrs listed as Technology Preview in Table 16 under Technology Preview features. Otherwise LGTM

@mburke5678 That's covered in another PR https://github.com/openshift/openshift-docs/pull/57256

**Pull request merged**
