### PR TITLE
Bug 1443235 Add more information on dynamic provisioning

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1443235

### CODE REVIEW

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL :fireworks: 

Something is wonky with my links, but I can't quite place what it is. Do you see something obviously wrong with them? 

Thanks!

**Comment by ahardin-rh** [comment]
@bmcelvee In master and 3.10+, the Installation and Configuration guide will be broken into up into 2 distinct guides, so it looks like any install_config paths are tripping it up.

**Comment by vikram-redhat** [comment]
@bmcelvee - I think the issue might be that because this PR is quite old, it might need a proper rebase since the install config has been broken up. You may need to close this and open up a new one.

**Comment by bmcelvee** [comment]
Thanks @ahardin-rh and @vikram-redhat! I'll go ahead and close/open a new PR for this one.

**Pull request closed without merging**
