### PR TITLE
Fix persistent volume reclaim policy, bug 1652782

### PR DESCRIPTION
**Pull request by liangxia**
https://bugzilla.redhat.com/show_bug.cgi?id=1652782

### CODE REVIEW

**Comment by vikram-redhat** [comment]
Thanks @liangxia - For 3.5 and below can you submit a new PR just for the enterprise-3.5 branch? We can then cherry pick that to older branches.

I will merge and CP this to 3.6 and above.

**Comment by liangxia** [comment]
> Thanks @liangxia - For 3.5 and below can you submit a new PR just for the enterprise-3.5 branch? We can then cherry pick that to older branches.

PR for 3.5, https://github.com/openshift/openshift-docs/pull/12940

**Pull request merged**
