### PR TITLE
More OSSM attribute fixes in Serverless docs

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+

https://issues.redhat.com/browse/SRVCOM-1727

Preview:
https://deploy-preview-44732--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-ossm-setup.html
https://deploy-preview-44732--osdocs.netlify.app/openshift-enterprise/latest/serverless/security/serverless-ossm-with-kourier-jwt.html

### CODE REVIEW

**Comment by tmalove** [comment]
LGTM!

**Comment by kalexand-rh** [comment]
@rh-max, some of the bot's cherry-picks failed. Will you please open manual ones and let me know when they're ready to merge?

**Pull request merged**
