### PR TITLE
Follow-up to Document support of upstream registry config (PR#1917)

### PR DESCRIPTION
**Pull request by ahardin-rh**
Follow-up to https://github.com/openshift/openshift-docs/pull/1917

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape @tnguyen-rh @tpoitras @bfallonf PTAL

**Comment by bfallonf** [comment]
@ahardin-rh LGTM

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../install_config/install/docker_registry.html[Installing -> Deploying a Docker Registry]
|Added support information for upstream link:../install_config/install/docker_registry.html#advanced-overriding-the-registry-configuration[registry configuration].
%

**Comment by adellape** [comment]
Turns out this and the original PR https://github.com/openshift/openshift-docs/pull/1917 should have been labeled enterprise-3.2 (they were previously labeled enterprise-3.1), but were already picked to the enterprise-3.1 branch and published Mar 30. I have now reverted the commits on the enterprise-3.1 branch via https://github.com/openshift/openshift-docs/pull/2218, and have reassigned this (and will reassign https://github.com/openshift/openshift-docs/pull/1917) to the enterprise-3.2 label, and am adding the `to_followup` back to both as well.

In 2nd follow-up PR, we can probably make the "Registry Configuration Reference" section ifdef'd for only Origin, and then re-vet the full changes for OSE-support/relevant with Eng. Once that 2nd follow-up is merged, we can remove `to_followup` from all 3 PRs and let them all roll into enterprise-3.2 together via the Next Release milestone/weekly publish.

I'll crippled the revhistory in the above comment also for now.

**Comment by vikram-redhat** [comment]
@adellape - should this have the to_followup label still? Because it has the label, it hasn't got picked for the release. I am not sure. There are 7 others that have the to_followup labels that were in this week's PR's but didn't get picked.

**Comment by adellape** [comment]
@vikram-redhat Sorry, I'll pin this to look into tomorrow.

**Comment by adellape** [comment]
@vikram-redhat I'm not sure why this and the original PR (https://github.com/openshift/openshift-docs/pull/1917) got moved out of Next Release last week, since they were both labeled `to_followup`. I've moved them back to Next Release and synced up with @ahardin-rh since she worked on these originally. She said she can take these the rest of the way.

**Comment by vikram-redhat** [comment]
Thanks @adellape and @ahardin-rh . I think the issue might just have been that the to_followup label wasn't removed?

**Pull request merged**
