### PR TITLE
OCPBUGS#31296: Update the OCP architecture and lifecycle diagrams

### PR DESCRIPTION
**Pull request by xenolinux**
The PR updates "OpenShift Lifecycle Manager" to "Operator Lifecycle Manager" in the OCP architecture diagram and adds the polished OCP lifecycle diagram (No technical changes in the lifecycle diagram)

Version(s): 4.13+

Issue: https://issues.redhat.com/browse/OCPBUGS-31296

Link to docs preview: 
- OCP architecutre diagram: https://73978--ocpdocs-pr.netlify.app/openshift-enterprise/latest/architecture/architecture#architecture-platform-introduction_architecture
- OCP lifecycle: https://73978--ocpdocs-pr.netlify.app/openshift-enterprise/latest/architecture/architecture#architecture-overview-image_architecture

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Thanks! 
/lgtm

**Review by lahinson — COMMENTED** [review]
LGTM

**Pull request merged**
