### PR TITLE
Updated master node sizing for 4.4

### PR DESCRIPTION
**Pull request by aakarshg**
- Updated recommended memory for master node to 96GB based on 4.4
  perfscale data

### CODE REVIEW

**Comment by aakarshg** [comment]
cc: @jtaleric @ahardin-rh

**Comment by ahardin-rh** [comment]
@aakarshg Thanks for this bump! 
@mffiedler Can you please provide a QE ack?

Once QE approved, I will merge. I will also open a separate PR to apply the change to the master branch and cherrypick it to the 4.5 branch so that the change carries over. :+1:

**Review by chaitanyaenr — APPROVED** [review]
/lgtm

**Review by mffiedler — APPROVED** [review]
/lgtm

**Pull request merged**
