### PR TITLE
 OSDOCS-2527: Post-installation configuration overview

### PR DESCRIPTION
**Pull request by xenolinux**
- The overview page for Post-installation configuration
-  OCP version: 4.6+
-  The post-installation book consists of many components as mentioned below
- [Jirra issue](https://issues.redhat.com/browse/OSDOCS-2527)
- Preview link : https://deploy-preview-37237--osdocs.netlify.app/openshift-enterprise/latest/post_installation_configuration/index.html
- QE contacts: Looking forward to the suggestions!
**Network**: @lihongan @zhaozhanqi @anuragthehatter  Kindly review the `Configuring cluster components to private` and `Configuring network` bullet points. 
**Authentication**: @yaoli-redhat Kindly review the `Configuring users` bullet point.
**Monitoring**: @lihongyan1 Kindly review the `Managing alerts and notifications` bullet point.
**MCO**: @rioliu-rh , @sergiordlr Kindly review the `Configuring operating system features` and `Performing machine operations` bullet points.
**Storage**: @duanwei33 Kindly review the `Configuring storage` bullet point.

### CODE REVIEW

**Review by rioliu-rh — CHANGES_REQUESTED** [review]

**Review by bobfuru — COMMENTED** [review]
This is a fantastic new addition overall! I've made some suggestions for clarity and readability, some of which you might not agree with...which is of course totally fine. Please let me know if I can provide additional details or clarifications on my suggestions. Thanks so much for this effort! It will be great to have an Overview page for Day 2 docs!!

**Review by jboxman — COMMENTED** [review]
I left a few comments on networking as I understand it.

**Comment by lihongan** [comment]
The ingress and DNS part looks good. Thank you!

**Review by bobfuru — COMMENTED** [review]
A few more suggestions here. Thank you!

**Pull request merged**
