### PR TITLE
[OCPBUGS-16665]: Added info about --machine-cidr flag to Create HCP clus…

### PR DESCRIPTION
**Pull request by AedinC**
…ter guide

Version(s):
4.13+

Issue:
[OCPBUGS-16665](https://issues.redhat.com/browse/OCPBUGS-16665)

Link to docs preview:
https://64882--docspreview.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly

image

Peer review:
- [x] Peer reviewer has approved this change.

SME review:
- [x] SME has approved this change.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by AedinC** [comment]
Hi @wgordon17. Could I get a review for this please whenever you get a chance? As noted in the JIRA issue, I can peel off a story to further investigate if there is anywhere better for this information to go once the MOBB docs migration is no longer a priority. However, I think we want to put the information about the `--machine -cidr` argument as close as possible to the commands the user is entering.

**Review by wgordon17 — APPROVED** [review]
Excellent! Thanks @AedinC

**Comment by mgahagan73** [comment]
looks good from the QE side
/lgtm

**Pull request merged**
