### PR TITLE
add a sample dockerfile for consuming input secrets

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bmcelvee** [comment]
LGTM. To which version(s) does this apply?

**Comment by bparees** [comment]
any version that has the input secrets section.

**Comment by bmcelvee** [comment]
Thanks!

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/builds/build_inputs.adoc#dev-guide-build-inputs[Build Inputs]
|Added an example of a Dockerfile referencing secret data in the xref:../dev_guide/builds/build_inputs.adoc#using-secrets-docker-strategy[Docker Strategy] section.
%

**Comment by bmcelvee** [comment]
I can't seem to open PRs for 3.9. Will investigate more in the morning.

**Pull request merged**
