### PR TITLE
introduce embedded etcd migration doc

### PR DESCRIPTION
**Pull request by ahardin-rh**
Continues the work in https://github.com/openshift/openshift-docs/pull/5723

Preview Builds:
http://file.rdu.redhat.com/~ahardin/11032017/ingvagabund-fork/install_config/upgrading/migrating_embedded_etcd.html

http://file.rdu.redhat.com/~ahardin/11032017/ingvagabund-fork/install_config/upgrading/migrating_etcd.html

Addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=1509195
https://bugzilla.redhat.com/show_bug.cgi?id=1508698
https://trello.com/c/XmEEJ8Ut/707-document-migrate-embedded-etcd-hosts-to-external-process

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@ingvagabund @sdodson PTAL

**Comment by sdodson** [comment]
Looks good, thanks @ahardin-rh

**Review by sdodson — APPROVED** [review]

**Comment by ahardin-rh** [comment]
@sdodson @ingvagabund This could be combined into one topic. Let me know if you prefer that. 

🗒 Note to self: If we keep this as 2 topics, this new topic should technically be before the existing topic. Also, we will need a new PR for 3.6 since the existing v2->v3 migration script in 3.6 also requires AH 7.4.x, so I need to add that to the migrating_etcd topic for 3.6. Thanks to @adellape for talking this through with me.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/migrating_embedded_etcd.adoc#install-config-upgrading-etcd-data-migration[Upgrading a Cluster -> Migrating Embedded etcd to External etcd]
|New topic on migrating embedded etcd to external etcd.
%

**Pull request merged**
