### PR TITLE
include HomeBrew @ cli-installing

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@bergerhoffer, will you PTAL?

**Comment by bergerhoffer** [comment]
@soltysh @zhouying7780 Just checking, do we support installing the CLI via homebrew as is requested to add in via this PR? I don't see anywhere else in our docs that we talk about using homebrew to install anything.

**Comment by bergerhoffer** [comment]
Closing this PR in favor of #45528, which moved this step into it's own procedure for installing via Homebrew.

**Pull request closed without merging**
