### PR TITLE
TELCODOCS-860: MGMT-10404 Use boot-artifacts API to fetch rootfs in minimal-iso (assisted-image-service)

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: [TELCODOCS-860](https://issues.redhat.com/browse/TELCODOCS-860)

For: Version 4.11+

Doc Preview: https://49123--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/ztp-deploying-disconnected.html#enabling-assisted-installer-service-on-bare-metal_ztp-deploying-disconnected

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Comment by ktothill** [comment]
Date and Time: August 15, 2022  16:33

Summary: Created [content](https://github.com/openshift/openshift-docs/pull/49123) and [RN](https://github.com/openshift/openshift-docs/pull/49125) PRs.

 

Next Steps: Requesting review from SME.

**Comment by ktothill** [comment]
@danielerez, could you please review the content and RN PRs? Any comments can be made directly in the PRs. If no changes are needed, please add an `lgtm` to each PR in Github. Thank you!

**Comment by ktothill** [comment]
@trewest, could you please review the content and RN PRs? Any comments can be made directly in the PRs. If no changes are needed, please add an `lgtm` to each PR in Github. Thank you!

**Comment by ktothill** [comment]
Date and Time: August 16, 2022  14:10
Summary: Received /lgtm from Daniel and Kerry. Requested Peer Review from Telco team. 

Next Steps: Implement feedback from Telco Peer Reviews and submit for OCP Review Squad feedback.

**Comment by ktothill** [comment]
Contact Method: Slack, [#forum-doc-review](https://coreos.slack.com/archives/C025XCRRH28/p1661446287635699)
Date and Time: August 25, 2022  12:51
Summary: Requested review from Peer Review Squad. 

Next Steps: Implement feedback from peer reviews and request merge.

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#forum-doc-review](https://coreos.slack.com/archives/C025XCRRH28/p1661531624731009)
**Date and Time:** August 26, 2022  12:33
**Summary:** Requested merge in #forum-docs-review

**Next Steps:** Once merged, Jira can be closed.

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#forum-docs-review](https://coreos.slack.com/archives/C025XCRRH28/p1661534211883339?thread_ts=1661531624.731009&cid=C025XCRRH28)
**Date and Time:** August 26, 2022  13:23
**Summary:** Holding off on merging content PR, until RN PR is discussed with Emily next Monday.

**Next Steps:** Need to confirm with Emily when she's back on Monday regarding the corresponding .z the content and RN were supposed to be in.

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#forum-docs-review](https://coreos.slack.com/archives/C025XCRRH28/p1662992488128169)
**Date and Time:** September 12, 2022  10:22
**Summary:** Requested merge for content and RN.

**Next Steps:** Once PRs are merged, Jira can be closed.

**Pull request merged**
