### PR TITLE
RHDEVDOCS-6117: Fixing incorrect link

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.13

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6117

Link to docs preview:

argocd command reference link in the following section: 

[GitOps argocd CLI reference](https://78999--ocpdocs-pr.netlify.app/openshift-gitops/latest/gitops_cli_argocd/argocd-gitops-cli-reference.html)

QE review:
Not applicable

SME review: anjoseph@redhat.com
QE review: @varshab1210 
Peer review:

Additional information:

This PR is also related to the changes made in the following PR: https://github.com/openshift/openshift-docs/pull/79035

I'm sharing the PR link here for you to refer to.

### CODE REVIEW

**Review by anandf — APPROVED** [review]
LGTM

**Review by Srivaralakshmi — COMMENTED** [review]
@Dhruv-Soni11 LGTM.

Please add the 1.13 PR link in the Additional information: section of this PR description and the JIRA issue [RHDEVDOCS-6117](https://issues.redhat.com/browse/RHDEVDOCS-6117). I will review that as well and approve it. Thanks!

**Comment by Srivaralakshmi** [comment]
@Dhruv-Soni11 Please add the merge review needed label.

**Comment by Srivaralakshmi** [comment]
@Dhruv-Soni11 Missed noticing a change, so reverted the merge. PTAL at this PR - https://github.com/openshift/openshift-docs/pull/79065. I have mentioned the required change you need to make there. thanks!

**Pull request merged**
