### PR TITLE
visual cleanup `router-internal.yaml`

### PR DESCRIPTION
**Pull request by xerc**
btw/ there a many different variants ; this one and ..
1. FILE ; https://docs.openshift.com/container-platform/4.13/networking/ingress-operator.html
2. PIPE ; https://docs.openshift.com/container-platform/4.13/networking/network_policy/multitenant-network-policy.html

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

**Comment by xerc** [comment]
@openshift-ci why do you list it then ?!

**Pull request closed without merging**
