### PR TITLE
OSDOCS-3776:Environment check for VMWare enhancements

### PR DESCRIPTION
**Pull request by lpettyjo**
This PR covers VMware environment checking (vCenter, ESXi, and hw). For 3rd-party CSI driver checking, see https://github.com/openshift/openshift-docs/pull/47535.

Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-3776

Link to docs preview: http://file.rdu.redhat.com/lpettyjo/OSDOCS-3776/storage/container_storage_interface/persistent-storage-csi-vsphere.html#vsphere-csi-driver-reqs_persistent-storage-csi-vsphere

Additional information:

**PTAL**: @jsafrane, @duanwei33, @gcharot, @bscott-rh

### CODE REVIEW

**Review by tmalove — COMMENTED** [review]
LGTM

**Comment by jsafrane** [comment]
lgtm

**Comment by gcharot** [comment]
Optional: I think we could reiterate the fact that 4.12 zstream / minor updates will still work.
Otherwise LGTM

**Comment by gcharot** [comment]
LGTM

**Comment by duanwei33** [comment]
LGTM

**Comment by lpettyjo** [comment]
/cherrypick-enterprise-4.12

**Pull request merged**
