### PR TITLE
RHDEVDOCS-3547: fluentd to collector change 

### PR DESCRIPTION
**Pull request by libander**
- Aligned team: Dev Tools
- For branches: 4.8, 4.9, main
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3547
- Direct link to doc preview: https://deploy-preview-40067--osdocs.netlify.app/openshift-enterprise/latest/logging/cluster-logging-release-notes.html#openshift-logging-5-3-0-known-issues
- SME review: @alanconway 
- QE review: @anpingli 
- Peer review: @missmesss

### CODE REVIEW

**Review by otikhomi — APPROVED** [review]

**Comment by anpingli** [comment]
only for logging 5.3 and after use the component name collector. it is fluentd in Logging 5.2

**Pull request merged**
