### PR TITLE
Document PV & PVC pre-binding scenarios

### PR DESCRIPTION
**Pull request by wongma7**
Properly document `volumeName` and `claimRef`.

edit: nvm. leaving the volumename part and focusing on claimref

### CODE REVIEW

**Comment by gnufied** [comment]
lgtm

**Comment by gnufied** [comment]
@wongma7 was there a bugzilla link for this?

**Comment by wongma7** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1406771

**Comment by ahardin-rh** [comment]
Closing this and continuing work in https://github.com/openshift/openshift-docs/pull/3693 (just applying minor edits there)

**Pull request closed without merging**
