### PR TITLE
bug 1567530 backing up more master files

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1567530

@jianlinliu, PTAL.

### CODE REVIEW

**Comment by jianlinliu** [comment]
@jiajliu PTAL.

**Comment by kalexand-rh** [comment]
Jianlin approved this PR in the source bug.

@openshift/team-documentation, PTAL

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by kalexand-rh** [comment]
Thanks @ahardin-rh! Merging.

**Comment by kalexand-rh** [comment]
3.7: https://github.com/openshift/openshift-docs/pull/10273
3.6: https://github.com/openshift/openshift-docs/pull/10274
3.5: https://github.com/openshift/openshift-docs/pull/10275
3.4: https://github.com/openshift/openshift-docs/pull/10276
3.3:  https://github.com/openshift/openshift-docs/pull/10277

**Pull request merged**
