### PR TITLE
OSDOCS-11778# Azure File snapshot (TP)

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.17+

Issue: https://issues.redhat.com/browse/OSDOCS-11778

Link to docs preview: https://80961--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

QE review:
- [x] QE has approved this change.

Additional information:

PTAL: @gcharot @RomanBednar @radeore

### CODE REVIEW

**Comment by RomanBednar** [comment]
@lpettyjo lgtm

**Comment by gcharot** [comment]
LGTM

**Pull request merged**
