### PR TITLE
OSDOCS#9312: Catalogd doesn't support global pull secrets admonition

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.15

Issue: [OSDOCS-9312](https://issues.redhat.com//browse/OSDOCS-9312)

Link to docs preview:
* [Creating a pull secret for catalogs hosted on a secure registry](https://70147--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog#olmv1-creating-a-pull-secret-for-catalogs-secure-registry_olmv1-installing-operator) (the NOTE is present here)
* [Red Hat-provided Operator catalogs in OLM 1.0](https://70147--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog#olmv1-red-hat-catalogs_olmv1-installing-operator) (the NOTE is intentionally not present here)
* [Installing an Operator from a catalog](https://70147--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog#olmv1-adding-a-catalog-to-a-cluster_olmv1-installing-operator) (NOTE is intentionally not present here)

QE review:
- [ ] QE has approved this change.

Additional information:
Adds a NOTE admonition to the tech preview OLM 1.0 docs in the procedure for adding a pull secret to the catalogd namespace. This admonition is part of a snippet that will likely be removed in the next release or before GA. As a result, the admonition uses conditionals to only render the admonition in the appropriate place.

### CODE REVIEW

**Review by everettraven — APPROVED** [review]

**Comment by michaelryanpeter** [comment]
@Xia-Zhao-rh PTAL :)

**Comment by rh-tokeefe** [comment]
LGTM. @bburt-rh as my review process onboarding buddy please review.

**Review by bburt-rh — APPROVED** [review]
LGTM. Thanks @michaelryanpeter and @rh-tokeefe.

@michaelryanpeter - I'm assuming that you will get a QE approval before merging, correct? I only see a SME approval.

**Comment by michaelryanpeter** [comment]
Correct, @bburt-rh  I am still waiting on QE before merging. Since the content of the admonition only clarifies existing content, I thought it safe to change the usual order of operations.

**Pull request merged**
