### PR TITLE
HCIDOCS- 262: Remove OSC

### PR DESCRIPTION
**Pull request by apinnick**
This PR replaces OSC docs with a link to standalone OSC docs for 4.12.

Version(s): 4.12

Issue: [HCIDOCS-262](https://issues.redhat.com//browse/HCIDOCS-262)

Link to docs preview: [Sandboxed containers](https://73775--ocpdocs-pr.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-moved)

QE review: NA
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
Hey @apinnick - I have reviewed your PR and wanted to start a conversation with you about this process of moving the OSC docs. Three points I wanted to communicate to you:
1) You appear to be moving your OSC documentation completely off docs.openshift.com and onto the customer portal, but only for the OSC docs within the 4.12 OCP doc set. Is that what you truly want to do, and if so, does that mean you are declaring the OSC docs on the portal to be static and only as relates to the 4.12 version of OCP?
2) What you are doing has also been done by the Serverless and Pipelines folks. Here's links to how they did it, which gives them their own version dropdown and segregates their documentation releases from OCP releases, but still keeps their documentation on docs.openshift.com (providing to them all the benefits of being on docs. openshift.com, which you will lose if you go to portal-only).  Here are example links to those sections are:
https://docs.openshift.com/serverless/1.32/about/about-serverless.html
https://docs.openshift.com/pipelines/1.14/about/about-pipelines.html
3) I looked over your docs on the portal and  one of the pages, https://access.redhat.com/documentation/en-us/openshift_sandboxed_containers/1.5/html/openshift_sandboxed_containers_release_notes/introduction appears to be not rendering correctly and is missing all introductory text - it is only a Chapter 1 heading. 
4) I read through your notes and in those notes, you draw correlation between OSC 1.5 and OCP 4.15. but the link takes the customer there from the 4.12 docs. Is this what you intended?
5) Do you need review of all the documentation you moved to the portal? I can provide very limited review there. (for example, the csrc.nis.gov link "Cryptographic Module Validation Program" does not work, but all your links to other internal Red Hat resources work OK.)

**Comment by GroceryBoyJr** [comment]
@apinnick I've edited my comments to you above, I see that this move has already happened once before. Will close out my peer review now.

**Comment by bergerhoffer** [comment]
Just adding my 2 cents that I think it would be better if the content matched exactly like how 4.13+ does it: https://docs.openshift.com/container-platform/4.15/sandboxed_containers/sandboxed-containers-moved.html

It looks like the names of the assembly and content are a bit different

**Pull request merged**
