### PR TITLE
OADP -1639 Roles

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP 1.2.0

OCP - 4.10+

Resolves - https://issues.redhat.com/browse/OADP-1639

Deploy preview - https://59515--docspreview.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.html   Step 8.

### CODE REVIEW

**Review by kaovilai — COMMENTED** [review]
What happened to the indent?

**Comment by CarmiWisemon** [comment]
> What happened to the indent?

@kaovilai sorry for that mistake. I corrected it. Is this OK?

**Review by kaovilai — APPROVED** [review]

**Comment by sbahar619** [comment]
lgtm.

**Comment by RichardHoch** [comment]
LGTM!

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Comment by stevsmit** [comment]
lgtm.

**Pull request merged**
