### PR TITLE
OSDOCS-1654: Release notes for non-preempting priority class option

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1654

Preview: https://osdocs-1654-rn--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-non-preempting-priority-classes

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Note that PR #27727 needs to be merged before the anchor in the xref will go to the right location.

**Comment by bergerhoffer** [comment]
@ingvagabund Here is a release notes entry for this. Can you take a look and see if the wording is okay? Note that the link won't go to the right place yet since #27727 hasn't been merged yet.

Preview: https://osdocs-1654-rn--ocpdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-non-preempting-priority-classes

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by ingvagabund** [comment]
lgtm

**Pull request merged**
