### PR TITLE
update reference from crd to cr for Web Terminal Operator Uninstall

### PR DESCRIPTION
**Pull request by strangiato**
Version(s):

4.9+

Issue:

Docs provide instructions for removing devworkspaces objects.  The objects being deleted are Custom Resources or an instance of a CRD but not a Custom Resource Definition.

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@Preeticp, who would be best to provide QE for this change?

**Comment by Preeticp** [comment]
@amisevsk can you review this PR or suggest someone from your team, please?

**Review by amisevsk — APPROVED** [review]
Good catch, thanks! These are indeed custom resources, not definitions.

**Comment by kalexand-rh** [comment]
Thank you!

**Pull request merged**
