### PR TITLE
OSDOCS-1224: Adding OAuth token format to migration planning doc

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1224

Preview: https://osdocs-1224-oauth--ocpdocs.netlify.app/openshift-enterprise/latest/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-security

### CODE REVIEW

**Comment by lamek** [comment]
LGTM.

**Comment by bergerhoffer** [comment]
@sttts Here's the migration planning doc update for the OAuth token changes. Can you please review?

Preview: https://osdocs-1224-oauth--ocpdocs.netlify.app/openshift-enterprise/latest/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-security

**Comment by sttts** [comment]
@bergerhoffer maybe little better:

Newly created OAuth HTTP bearer tokens no longer match directly the names of their OAuth access tokens objects. Instead, the objects use a hash of the bearer tokens as name and are hence not sensitive anymore, reducing the risk of leaking sensitive information e.g. through log or audit files.

**Comment by bergerhoffer** [comment]
@sttts Updated.

Preview: https://osdocs-1224-oauth--ocpdocs.netlify.app/openshift-enterprise/latest/migration/migrating_3_4/planning-migration-3-to-4.html#migration-preparing-security

**Pull request merged**
