### PR TITLE
[GH#43494] OSP external load balancing module typo fix

### LINKED ISSUE #43494: [enterprise-4.8+] Typo in file networking/load-balancing-openstack.adoc
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/networking/load-balancing-openstack.html#nw-osp-configuring-external-load-balancer_load-balancing-openstack

### What needs fixing?
In this example:
~~~
...
listen my-cluster-api-6443
    bind 0.0.0.0:6443
    mode tcp
    balance roundrobin
    server my-cluster-master-2 192.0.2.2:6443 check
    server my-cluster-master-0 192.0.2.3:6443 check
    server my-cluster-master-1 192.0.2.1:6443 check
listenmy-cluster-apps-443
        bind 0.0.0.0:443
        mode tcp
        balance roundrobin
        server my-cluster-worker-0 192.0.2.6:443 check
        server my-cluster-worker-1 192.0.2.5:443 check
        server my-cluster-worker-2 192.0.2.4:443 check
listenmy-cluster-apps-80
        bind 0.0.0.0:80
        mode tcp
        balance roundrobin
        server my-cluster-worker-0 192.0.2.7:80 check
        server my-cluster-worker-1 192.0.2.9:80 check
~~~

Two lines are wrong, then

- `listenmy-cluster-apps-443` should be `listen my-cluster-apps-443`
- `listenmy-cluster-apps-80` should be  `listen my-cluster-apps-80`

The example should be like:

~~~
...
listen my-cluster-api-6443
    bind 0.0.0.0:6443
    mode tcp
    balance roundrobin
    server my-cluster-master-2 192.0.2.2:6443 check
    server my-cluster-master-0 192.0.2.3:6443 check
    server my-cluster-master-1 192.0.2.1:6443 check
listen my-cluster-apps-443
        bind 0.0.0.0:443
        mode tcp
        balance roundrobin
        server my-cluster-worker-0 192.0.2.6:443 check
        server my-cluster-worker-1 192.0.2.5:443 check
        server my-cluster-worker-2 192.0.2.4:443 check
listen my-cluster-apps-80
        bind 0.0.0.0:80
        mode tcp
        balance roundrobin
        server my-cluster-worker-0 192.0.2.7:80 check
        server my-cluster-worker-1 192.0.2.9:80 check
~~~

### PR DESCRIPTION
**Pull request by maxwelldb**
Commit to fix typo per openshift/openshift-docs#43494

Version(s): 4.8+

Issue: Fixes openshift/openshift-docs#43494

Link to docs preview: https://51162--docspreview.netlify.app/openshift-enterprise/latest/networking/load-balancing-openstack.html#nw-osp-configuring-external-load-balancer_load-balancing-openstack

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by maxwelldb** [comment]
@eurijon Small typo fix seeks QE ack. 👍

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by eurijon** [comment]
lgtm

**Comment by maxwelldb** [comment]
@eurijon TY!

**Pull request merged**
