### PR TITLE
OBSDOCS-1501 - Logging 5.9.9 RN - OCP 4.13 thru 4.16

### PR DESCRIPTION
**Pull request by libander**
Version(s): 4.13, 4.14, 4.15, 4.16

Issue: https://issues.redhat.com/browse/OBSDOCS-1501

Link to docs preview: https://85214--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-9-release-notes.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by libander** [comment]
@anpingli - Review please.

**Comment by anpingli** [comment]
LGTM

**Review by xperimental — APPROVED** [review]

**Review by aspauldi — COMMENTED** [review]
Hi! The only thing I noticed was in the preview, in which there is one NOTE followed without intervening content by another NOTE. I don't think that you updated this section, but I wanted to mention that the Red Hat Supplementary Style Guide advises to avoid placing multiple admonitions close together (https://redhat-documentation.github.io/supplementary-style-guide/#admonitions).

**Comment by libander** [comment]
> Hi! The only thing I noticed was in the preview, in which there is one NOTE followed without intervening content by another NOTE. I don't think that you updated this section, but I wanted to mention that the Red Hat Supplementary Style Guide advises to avoid placing multiple admonitions close together (https://redhat-documentation.github.io/supplementary-style-guide/#admonitions).

Solid feedback, thank you so much! Fixed. :)

**Pull request merged**
