### PR TITLE
Add release note for OVN-Kubernetes secondary network GA

### PR DESCRIPTION
**Pull request by jab-rh**
- https://issues.redhat.com/browse/OSDOCS-6264

Adds release note, touches TP table.

(TP notice in content is removed in a separate feature PR: https://github.com/openshift/openshift-docs/pull/61110)

Version(s): 4.14+

Issue:

Link to docs preview: https://61113--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-networking-ovn-kubernetes-secondary-network

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jab-rh** [comment]
@maiqueb, this restates the release note that we used in the previous release, and bumps the feature to GA from TP. For the release notes, I think this is sufficient? Thanks!

**Review by maiqueb — APPROVED** [review]
Thank you !

**Comment by weliang1** [comment]
@jab-rh @maiqueb Do we need some configuration and verification steps in this doc? 

The configuration and verification steps can be found in QE test cases: 
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67618
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67616

**Comment by maiqueb** [comment]
> @jab-rh @maiqueb Do we need some configuration and verification steps in this doc?
> 
> The configuration and verification steps can be found in QE test cases: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67618 https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67616

I'm unsure. Let's ask OVN-Kubernetes maintainers: @trozet / @jcaamano

**Comment by jab-rh** [comment]
@weliang1, does this release note look okay?

Thanks!

**Pull request merged**
