### PR TITLE
[SRVCOM-3149] Change sidecar injection from annotations to labels

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
`serverless-docs-1.34`+

Issue:
https://issues.redhat.com/browse/SRVCOM-3149

Link to docs preview:
https://79344--ocpdocs-pr.netlify.app/openshift-serverless/latest/integrations/serverless-ossm-setup.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by rh-max** [comment]
@ReToCode Hi Reto, could you PTAL? Thanks.

**Review by ReToCode — COMMENTED** [review]
LGTM.

**Comment by mgencur** [comment]
LGTM from QE

**Review by opayne1 — COMMENTED** [review]
Don't forget about the preview link: https://79344--ocpdocs-pr.netlify.app/openshift-serverless/latest/integrations/serverless-ossm-setup.html 

Otherwise lgtm!

**Pull request merged**
