### PR TITLE
OCPBUGS-17393 Issue in file welcome/oke_about.adoc

### PR DESCRIPTION
**Pull request by rolfedh**
Version(s):
4.9 - 4.13 [from the Jira task](https://issues.redhat.com/browse/OCPBUGS-17393)
* It looks like this change should apply to enterprise-4.14, too. 

Issue:
[OCPBUGS-17393](https://issues.redhat.com/browse/OCPBUGS-17393)

Link to docs preview:
https://65348--docspreview.netlify.app/openshift-enterprise/latest/welcome/oke_about

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by rolfedh** [comment]
@zanetworker and @jianlinliu, please review and approve this PR. Thank you.

**Comment by juzhao** [comment]
@pruan-rht please help to review, it's for `Metering`

**Comment by kalexand-rh** [comment]
@pruan-rht, will you please confirm this change?

**Pull request merged**
