### PR TITLE
vSphere driver version update for 4.16

### PR DESCRIPTION
**Pull request by lpettyjo**
Version(s): 4.16+

Issue: Update vSphere driver version and correct a link

Link to docs preview: https://76408--ocpdocs-pr.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi-vsphere.html

QE review:
- [x] QE has approved this change.

Additional information:

**PTAL**: @gnufied @duanwei33 @gcharot

### CODE REVIEW

**Review by aspauldi — APPROVED** [review]
LGTM! Thanks.

**Comment by gcharot** [comment]
LGTM

**Pull request merged**
