### PR TITLE
BZ-1903699 3.11 Note for prometheus storage capacity planning for CMO

### PR DESCRIPTION
**Pull request by lbarbeevargas**
https://bugzilla.redhat.com/show_bug.cgi?id=1903699

This PR handles a new note in the 3.11 _Capacity Planning for Cluster Monitoring Operator_ section. A separate PR will be opened against 4.x branches.

Preview - https://deploy-preview-29502--osdocs.netlify.app/openshift-enterprise/latest/scaling_performance/scaling_cluster_monitoring.html#cluster-monitoring-capacity-planning

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
@simonpasquier PTAL (for 3.11). Thank you.

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by lbarbeevargas** [comment]
@juzhao @openshift/team-documentation PTAL, thank you.

**Pull request merged**
