### PR TITLE
BZ2036156 - Fixing command in customizing HAProxy procedure

### PR DESCRIPTION
**Pull request by kelbrown20**
For versions 4.9+
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2036156

Ready for QE: @lihongan 

Preview: https://deploy-preview-42902--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-customize-ingress-error-pages_configuring-ingress

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
/LGTM!

**Review by bergerhoffer — COMMENTED** [review]
LGTM too

**Comment by zhaozhanqi** [comment]
@kelbrown20 will assign this to @lihongan who is the QE leader of network-edge(ingress and dns). Thanks

**Comment by bergerhoffer** [comment]
The `branch/enterprise-4.11` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.10. And any PR going into `main` must also target the latest version branch (enterprise-4.11).

If the update in your PR does NOT apply to version 4.11 onward, please retarget this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by ShudiLi** [comment]
/qe-approved
thanks

**Pull request merged**
