### PR TITLE
OSDOCS-5196-4-11: Updated vSphere versioning format for 4.11 docs

### PR DESCRIPTION
**Pull request by dfitzmau**
Issue:
[OSDOCS-5196](https://issues.redhat.com/browse/OSDOCS-5197)

Version(s):
4.11

Link to docs preview:
* [VMware vSphere infrastructure requirements](http://file.emea.redhat.com/dfitzmau/OSDOCS-5196-4-11/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned)
* [VMware vSphere CSI Driver Operator requirements](http://file.emea.redhat.com/dfitzmau/OSDOCS-5196-4-11/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#vsphere-csi-driver-reqs_installing-vsphere-installer-provisioned-customizations)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by rvanderp3** [comment]
LGTM
cc: @jcpowermac

**Comment by duanwei33** [comment]
/lgtm
cc @sgaoshang

**Review by kcarmichael08 — COMMENTED** [review]
Since QE has approved, please check the box in the body of the PR; otherwise, LGTM!

**Pull request merged**
