### PR TITLE
OSDOCS-2809: Remove hardened SRE support pod info

### PR DESCRIPTION
**Pull request by lpettyjo**
Fixes the following issue: https://issues.redhat.com/browse/OSDOCS-2809

**Preview**:
**ROSA**: https://deploy-preview-38388--osdocs.netlify.app/openshift-rosa/latest/rosa_policy/rosa-policy-process-security.html#rosa-policy-sre-access_rosa-policy-process-security

**OSD**: https://deploy-preview-38388--osdocs.netlify.app/openshift-dedicated/latest/osd_policy/policy-process-security.html#sre-access-all_policy-process-security

PTAL: @xueli181114, @yuwang-RH, @okashi18

### CODE REVIEW

**Review by codyhoag — COMMENTED** [review]
One nit; looks good otherwise!

**Comment by 0kashi** [comment]
lgtm

**Comment by lpettyjo** [comment]
Closing this PR and covering this change in this PR: https://github.com/openshift/openshift-docs/pull/39950.

The new PR points to the "main" rather than "dedicated-4" branch.

**Pull request closed without merging**
