### PR TITLE
OCPBUGS#3628 Adding access.redhat.com to allowlist.

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/OCPBUGS-3628

Link to docs preview:
https://54877--docspreview.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by Amrita42** [comment]
lgtm

**Review by skrthomas — COMMENTED** [review]
merge review lgtm!

**Pull request merged**
