### PR TITLE
OSDOCS-11614: SPO 0.8.5 release notes

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-11614

Link to docs preview:
In progress

QE review:
- [x] QE has approved this change.

Additional information:
None

### CODE REVIEW

**Comment by sheriff-rh** [comment]
Build test failed when I linked to the internal bug https://issues.redhat.com/browse/OCPBUGS-37747. I removed the link but kept the bug text as I think it's still important. 

Retesting the build (it should pass now).

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by sheriff-rh** [comment]
Merging to 4.12+.

**Pull request merged**
