### PR TITLE
Fixing configmap doc typo

### PR DESCRIPTION
**Pull request by jupierce**

### CODE REVIEW

**Comment by jupierce** [comment]
@bparees

**Comment by bparees** [comment]
@pmorie you're the expert here.

**Comment by pmorie** [comment]
LGTM, thanks

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge.

**Comment by ahardin-rh** [comment]
Thanks! LGTM! Assuming this is not waiting for 3.3? Please check my labeling. Thanks again!

**Comment by bparees** [comment]
yeah it can go in now.

**Pull request merged**
