### PR TITLE
[DOCS] OBSDOCS-832 Power Monitoring- Warning for Bare Metal shifted on top

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Power Monitoring- Warning for Bare Metal shifted on top
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-832

Fix Version: 4.14+

Doc Preview: https://71941--ocpdocs-pr.netlify.app/openshift-enterprise/latest/power_monitoring/power-monitoring-overview#power-monitoring-about-power-monitoring_power-monitoring-overview

SME Review: @ssonigra
QE Review: @vprashar2929
Peer Review: @smunje1 @bscott-rh

### CODE REVIEW

**Comment by ssonigra** [comment]
Updated warning at the top looks good to be published

**Review by vprashar2929 — APPROVED** [review]
/lgtm

**Comment by smunje1** [comment]
@shreyasiddhartha This changes LGTM.  As I am new to the peer review squad, I request that you wait until  @bscott-rh   gives approval.

**Comment by bscott-rh** [comment]
Peer review LGTM.

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
