### PR TITLE
Bug 1987341: NFD Operator shows different namespace

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
NFD Docs are showing a namespace different from the recomended

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

https://bugzilla.redhat.com/show_bug.cgi?id=1987341

### CODE REVIEW

**Review by ahardin-rh — APPROVED** [review]
LGTM! Thank you!

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
