### PR TITLE
osdocs-908 updating 4.4 ami links

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://issues.redhat.com/browse/OSDOCS-912

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@xltian can we get someone to ack this?

**Comment by xltian** [comment]
@jiajliu  Can you review and ack this one? Thanks

**Comment by jiajliu** [comment]
@kalexand-rh 
The changes in the pr lgtm. But i want to confirm if following version number needed to be updated too.
1) the version column in all other platforms except gcp also needed to be updated too, such as https://docs.openshift.com/container-platform/4.3/installing/installing_vsphere/installing-vsphere.html#installation-complete-user-infra_installing-vsphere
2) the operators list should be updated since there are 30 operators in v4.4.
```
# ./oc get co
NAME                                       VERSION                             AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.4.0-0.nightly-2020-04-27-013217   True        False         False      40m
cloud-credential                           4.4.0-0.nightly-2020-04-27-013217   True        False         False      59m
cluster-autoscaler                         4.4.0-0.nightly-2020-04-27-013217   True        False         False      50m
console                                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      41m
csi-snapshot-controller                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      48m
dns                                        4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
etcd                                       4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
image-registry                             4.4.0-0.nightly-2020-04-27-013217   True        False         False      48m
ingress                                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      48m
insights                                   4.4.0-0.nightly-2020-04-27-013217   True        False         False      50m
kube-apiserver                             4.4.0-0.nightly-2020-04-27-013217   True        False         False      52m
kube-controller-manager                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      52m
kube-scheduler                             4.4.0-0.nightly-2020-04-27-013217   True        False         False      52m
kube-storage-version-migrator              4.4.0-0.nightly-2020-04-27-013217   True        False         False      48m
machine-api                                4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
machine-config                             4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
marketplace                                4.4.0-0.nightly-2020-04-27-013217   True        False         False      50m
monitoring                                 4.4.0-0.nightly-2020-04-27-013217   True        False         False      43m
network                                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      54m
node-tuning                                4.4.0-0.nightly-2020-04-27-013217   True        False         False      54m
openshift-apiserver                        4.4.0-0.nightly-2020-04-27-013217   True        False         False      48m
openshift-controller-manager               4.4.0-0.nightly-2020-04-27-013217   True        False         False      47m
openshift-samples                          4.4.0-0.nightly-2020-04-27-013217   True        False         False      47m
operator-lifecycle-manager                 4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
operator-lifecycle-manager-catalog         4.4.0-0.nightly-2020-04-27-013217   True        False         False      53m
operator-lifecycle-manager-packageserver   4.4.0-0.nightly-2020-04-27-013217   True        False         False      49m
service-ca                                 4.4.0-0.nightly-2020-04-27-013217   True        False         False      54m
service-catalog-apiserver                  4.4.0-0.nightly-2020-04-27-013217   True        False         False      54m
service-catalog-controller-manager         4.4.0-0.nightly-2020-04-27-013217   True        False         False      54m
storage                                    4.4.0-0.nightly-2020-04-27-013217   True        False         False      50m
```
I'm not sure if above update have been changed in other prs, if yes, please feel free to just merge this pr.

**Comment by vikram-redhat** [comment]
Thanks @jiajliu - I will merge this and @kalexand-rh if you can update the rest later today/tomorrow.

**Pull request merged**
