### PR TITLE
OSDOCS-3052: Fix submitting a support case doc for OSD

### PR DESCRIPTION
**Pull request by bmcelvee**
4.11, 4.12 

https://issues.redhat.com/browse/OSDOCS-3052

Preview: http://file.rdu.redhat.com/bmcelvee/OSDOCS-3052/osd_architecture/osd-support.html#support-submitting-a-case_osd-getting-support

No QE review required.

### CODE REVIEW

**Comment by bobfuru** [comment]
Because this is marked as 4.9+ and WIP, I'm changing the milestone from `Future Release` to `Next Release`.

**Comment by bergerhoffer** [comment]
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by jboxman-rh** [comment]
@bmcelvee, if it renders conditionals for OCP correctly as well it LGTM. Thanks!

**Pull request merged**
