### PR TITLE
[OSDOCS-8963]: Repair a broken link in ROSA docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.14+
Issue:

https://issues.redhat.com/browse/OSDOCS-8963
Link to docs preview:

https://69021--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-deleting-cluster

https://69021--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-deleting-cluster#rosa-deleting-cluster_rosa-deleting-cluster

QE review:
- [ ] QE has approved this change.

QE not required for reviewing a broken link fix. 
Additional information:

### CODE REVIEW

**Review by jeana-redhat — COMMENTED** [review]
I know ROSA docs are sometimes different, but want to verify: should this not just be an xref outside the module (in Additional resources)?

**Comment by mletalie** [comment]
Hello @jeana-redhat,
   So just so I am clear with what you are asking; are you saying that section (Additional resources) along with any links included should be pulled out of the module and then placed in the assembly so an xref can be used and not a direct link (as modules cannot have xrefs)?

**Pull request closed without merging**
