### PR TITLE
Bug 1908514: additional supported AWS regions

### PR DESCRIPTION
**Pull request by miabbott**
As part of a 4.6.z release, we included support for three new regions:

- `af-south-1`
- `ap-east-1`
- `eu-south-1`

This updates the docs accordingly.

### CODE REVIEW

**Comment by miabbott** [comment]
This should be backported to the 4.6 branch too

**Comment by codyhoag** [comment]
@yunjiang29 can you confirm? Thanks!

**Comment by codyhoag** [comment]
@yunjiang29 bump -  can you confirm these additional AWS regions for 4.6?

Can you also confirm this list is accurate for the 4.7 release too?

**Comment by yunjiang29** [comment]
@codyhoag LGTM.

**Review by codyhoag — APPROVED** [review]

**Pull request merged**
