### PR TITLE
PR10283 Follow-up Documentation for regionendpoint config parameter

### PR DESCRIPTION
**Pull request by bmcelvee**
https://github.com/openshift/openshift-docs/pull/10283

### CODE REVIEW

**Comment by bmcelvee** [comment]
I'm looking into why the checks failed. It seems to have something to do with the re-org of the install guides. Will fix as soon as I can figure it out.

**Comment by vikram-redhat** [comment]
@bmcelvee - this can now be moved along?

**Comment by bmcelvee** [comment]
@legionus When you get a chance, PTAL. I linked the sections per the IRC discusssion, and made a few minor edits to the text.

**Comment by legionus** [comment]
Why do not make section `Use Amazon S3 as a Storage Back-end` a link to [section about S3 driver](https://github.com/openshift/openshift-docs/pull/11040/files#diff-fa84991e4fe6c525769a3e8c3f7ad75bR434) ?

**Comment by vikram-redhat** [comment]
@legionus - hey there. Did you have any more feedback besides the one about the link?

If not, @bmcelvee can you please move this along? @jiajliu - can you please do a QE review?

**Comment by bmcelvee** [comment]
There was a QE review on the original PR, so this should be good to go. I'll go ahead and merge.

**Pull request merged**
