### PR TITLE
TELCODOCS-657: Update headings under the IPI book 

### PR DESCRIPTION
**Pull request by johnwilkins**
Replaces https://github.com/openshift/openshift-docs/pull/46219. Replaces (Optional) to Optional: in ipi bare metal titles.

Fixes: [TELCODOCS-657](https://issues.redhat.com//browse/TELCODOCS-657)

See https://issues.redhat.com/browse/TELCODOCS-657 for additional details.

Preview URL: http://jowilkin.com:8080/TELCODOCS-657-2/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html

For release(s): 4.12, 4.11
Signed-off-by: John Wilkins <jowilkin@redhat.com>

### CODE REVIEW

**Comment by bscott-rh** [comment]
LGTM

**Review by bscott-rh — APPROVED** [review]

**Comment by bergerhoffer** [comment]
The 4.12 CP failed because https://github.com/openshift/openshift-docs/pull/48745 needed to get CPd to 4.12 first. Now that that PR is CPd, issuing the 4.12 CP command again and hopefully 4.12 will pick cleanly this time.

/cherrypick enterprise-4.12

**Pull request merged**
