### PR TITLE
Fix the definition for disableDefaultForwarding

### PR DESCRIPTION
**Pull request by mburke5678**
Fixed the definition of the `disableDefaultForwarding` parameter
https://coreos.slack.com/archives/CB3HXM2QK/p1600348857023200

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by mburke5678** [comment]
Cherrypicking to 4.5 and 4.6. In 4.6 (and possibly 4.5.z), the parameter will be removed by Log Forward GA feature

**Pull request merged**
