### PR TITLE
Fix mysql links

### PR DESCRIPTION
**Pull request by liangxia**
This should apply to branch/enterprise-3.3 and above.

### CODE REVIEW

**Comment by liangxia** [comment]
@openshift/team-documentation  PTAL.

**Comment by gaurav-nelson** [comment]
Thanks for the PR @liangxia LGTM

minor fixes no peer review needed.

**Comment by gaurav-nelson** [comment]
@vikram-redhat Do we need to include this in v3.3 as well?

**Comment by vikram-redhat** [comment]
@gaurav-nelson - if @liangxia says so. But we don't have a stage branch for 3.3, so put this directly in the prod branch for 3.3.

**Pull request merged**
