### PR TITLE
OCPBUGS-37822: Add new permission required for forwarding rules labels

### PR DESCRIPTION
**Pull request by barbacbd**
CAPG additions require the addition of compute.globalForwardingRules.setLabels by default.

Version(s):

4.17

Issue:

https://issues.redhat.com/browse/OCPBUGS-37822
https://issues.redhat.com/browse/OCPBUGS-33947
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1276
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1274

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by bscott-rh — APPROVED** [review]
LGTM from docs perspective

**Comment by gpei** [comment]
cc @jianli-wei

**Comment by bfournie** [comment]
/lgtm
Thanks Brent!

**Pull request merged**
