### PR TITLE
OSDOCS#24488: Changed example values for cert-manager

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OCPBUGS-24488

Link to docs preview: https://69897--ocpdocs-pr.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/cert-manager-customizing-api-fields#cert-manager-configure-cpu-memory_cert-manager-customizing-api-fields

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by lunarwhite — COMMENTED** [review]
/lgtm

Thanks!

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
