### PR TITLE
simplify snippet for querying effective_affinity

### PR DESCRIPTION
**Pull request by makelinux**
to more short and fast

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@kquinn1204, will you please send this PR through QE review and get it merged?

**Comment by kquinn1204** [comment]
I did a quick look up on this replacement and this is what I got "The command provided will not work as expected because grep is designed to search for patterns within files, and it won't work well with special files like those in /proc/irq/. Additionally, using grep with the --include option is not the correct way to filter files in the /proc/irq/ directory." I will reach out to QE/dev for a comment @kalexand-rh

**Comment by kquinn1204** [comment]
Hi @naggety Is this replacement valid for shortening the string in question replacing find `/proc/irq/ -name effective_affinity -exec sh -c 'i="$1"; mask=$(cat $i); file=$(echo $i); echo $file: $mask' _ {} \`; with grep '' -r /proc/irq/ --include effective_affinity. I have done some research and it seems to indicate "The main issue is that grep is designed to search for patterns within files, and it's not the best tool to filter files based on their names or contents. Moreover, the --include option is not the correct way to filter files in the /proc/irq/ directory, as it will include all files in the search results, regardless of their names or contents."  WDYT?

**Comment by naggety** [comment]
Hi. Sorry for the long delay, I missed the notification in my email.

I don't have a strong opinion vs using `grep` here. It might fail with many files under `/proc`, but I don't think it will fail with the effective_affinity files.

Anyway, if you want a more reliable solution, here there are 3:
```
# find /proc/irq -name effective_affinity -exec echo -n {}: \; -exec cat {} \;
/proc/irq/0/effective_affinity:01
/proc/irq/1/effective_affinity:20
/proc/irq/2/effective_affinity:00
/proc/irq/3/effective_affinity:01
...

$ find /proc/irq -name effective_affinity | xargs awk '{printf FILENAME ":" ;print}'
/proc/irq/0/effective_affinity:01
/proc/irq/1/effective_affinity:20
/proc/irq/2/effective_affinity:00
/proc/irq/3/effective_affinity:01
...

# find /proc/irq -name effective_affinity | xargs head
==> /proc/irq/0/effective_affinity <==
01

==> /proc/irq/1/effective_affinity <==
20

==> /proc/irq/2/effective_affinity <==
00

...
```

**Comment by naggety** [comment]
More readable alternatives:

```
$ find /proc/irq -name effective_affinity -printf "%p:" -exec cat {} \;
/proc/irq/0/effective_affinity:01
/proc/irq/1/effective_affinity:20
/proc/irq/2/effective_affinity:00
/proc/irq/3/effective_affinity:01
...

$ find /proc/irq -name effective_affinity -printf "%p: " -exec cat {} \;
/proc/irq/0/effective_affinity: 01
/proc/irq/1/effective_affinity: 20
/proc/irq/2/effective_affinity: 00
/proc/irq/3/effective_affinity: 01
...

$ find /proc/irq -name effective_affinity -printf "%h:" -exec cat {} \;
/proc/irq/0:01
/proc/irq/1:20
/proc/irq/2:00
/proc/irq/3:01
...
```

**Comment by kquinn1204** [comment]
@makelinux are you happy to make the update as suggested by @naggety

**Comment by kquinn1204** [comment]
Yes @makelinux are you taking the best of both ?

**Comment by makelinux** [comment]
@kquinn1204, yes

**Comment by kquinn1204** [comment]
@makelinux what doe that update now look like ?

**Comment by makelinux** [comment]
@kquinn1204 , 
`find /proc/irq -name effective_affinity -printf "%p: " -exec cat {} \;`

**Review by kquinn1204 — COMMENTED** [review]
/LGTM cleaner

**Comment by kquinn1204** [comment]
Preview: https://64186--docspreview.netlify.app/openshift-enterprise/latest/scalability_and_performance/cnf-low-latency-tuning.html#about_irq_affinity_setting_cnf-master

**Comment by kquinn1204** [comment]
@mrniranjan Can you give this a LGTM looks straightforward update to a command I over complicated in https://github.com/openshift/openshift-docs/pull/60123

**Comment by makelinux** [comment]
@mramendi , would you like to rewiew please?

**Comment by kquinn1204** [comment]
got LGTM from QE

**Comment by bburt-rh** [comment]
@kquinn1204 - Can you please indicate what enterprise branches this PR applies to? Thanks!

**Comment by kquinn1204** [comment]
4.12 and greater

**Pull request merged**
