### PR TITLE
BYO RHEL docs need to be updated to include RHEL 7.9 support

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1918082

Updates to match supported versions shown here: https://access.redhat.com/articles/4763741

### CODE REVIEW

**Comment by mburke5678** [comment]
@sdodson PTAL

**Comment by sdodson** [comment]
/lgtm
Did a quick search and couldn't find any other references to these version ranges so this seems to be good. Thanks.

**Comment by sdodson** [comment]
/lgtm cancel
@katherinedube pointed out other references to 7.6 where as the linked [solution](https://access.redhat.com/articles/4763741) mentions 7.7 and later in 4.5+, lets update that.
https://github.com/openshift/openshift-docs/blame/master/modules/installation-requirements-user-infra.adoc#L135

**Comment by mburke5678** [comment]
@sdodson @katherinedube 
Updated the doc referenced in the BZ to _RHEL 7.7 and later_.

**Comment by mburke5678** [comment]
@sdodson @katherinedube Updated the supported versions for 4.6 and 4.7 (impending) to RHEL 7.8-7.9.  PTAL

cc. @sferich888 @codyhoag 

[1] https://github.com/openshift/openshift-docs/pull/28703/files#diff-2f3534bfedc94d5ef24b4845354ac2e1cf0ad53bf4bab0f5764acb82bfa9fb17R19

**Comment by mburke5678** [comment]
Changes to 4.5 breanch: https://github.com/openshift/openshift-docs/pull/28853

**Comment by mburke5678** [comment]
@gpei Can you please take a look at this PR and my PR for 4.5: https://github.com/openshift/openshift-docs/pull/28853

**Comment by gpei** [comment]
LGTM, RHEL-7.8 and RHEL-7.9 are covered in QE's testing in OCP-4.6 and OCP-4.7

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Pull request merged**
