### PR TITLE
[OSDOCS-9697]:Document GA and EOL dates for 4.16

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-9697
Link to docs preview:

https://78330--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_architecture/osd_policy/osd-life-cycle.html
QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
image

**Comment by bmcelvee** [comment]
LGTM! No QE review required.

**Comment by mletalie** [comment]
https://github.com/openshift/openshift-docs/pull/78330

**Pull request merged**
