### PR TITLE
hiding update topics

### PR DESCRIPTION
**Pull request by kalexand-rh**
@vikram-redhat \

Preview here: http://file.rdu.redhat.com/kalexand/060319/update/updating/updating-cluster.html

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@bergerhoffer, @sheriff-rh, FYI

**Comment by kalexand-rh** [comment]
Vikram said to merge this as soon as Travis passes.

**Comment by kalexand-rh** [comment]
Mike Barrett says to keep the web console info.

**Review by mffiedler — APPROVED** [review]
/lgtm

**Pull request merged**
