### PR TITLE
SRVCOM-1580: Move install into own section

### PR DESCRIPTION
**Pull request by abrennan89**
Jira: https://issues.redhat.com/browse/SRVCOM-1580

Applies for OCP 4.6+

Direct preview link: https://deploy-preview-39365--osdocs.netlify.app/openshift-enterprise/latest/serverless/install/install-serverless-operator.html (new **Install** section)

### CODE REVIEW

**Comment by mjpytlak** [comment]
@abrennan89 LGTM.
Ready for merge?

**Comment by abrennan89** [comment]
Note: decided not to apply the changes for 4.6, 4.7 since the structure is too different. Failed CPs can be ignored.

**Pull request merged**
