### PR TITLE
[OSDOCS-10120]: Update Roles for the osd-ccs-admin service account within OSD docs

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.15+
Issue:

https://issues.redhat.com/browse/OSDOCS-10120
Link to docs preview:

https://74062--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs#gcp-policy-instances_gcp-ccs
QE review:
- [x] QE has approved this change.

Additional information:

**Reviewers: The scope of this ticket mainly focuses on making sure the lists shown in the attached image match what is presented in tables #1 and #2 here**: https://docs.openshift.com/dedicated/osd_planning/gcp-ccs.html#ccs-gcp-customer-procedure_gcp-ccs

image

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @lento-sun,
   Could I please get a QE review for this PR? Per the PR description, I just had confirm and then copy some duplicate info to another section in the topic. The roles were already established and approved here: https://github.com/openshift/openshift-docs/pull/72303. There were  two additional locations within the docs that should have been updated with that info but were missed. Thanks!

**Comment by tsze-redhat** [comment]
Sorry for forgetting to let you know, Mark, @valeriiashapoval will be looking at this today.

**Comment by mletalie** [comment]
> @mletalie Just took another look, the change looks good to me! Thanks.

Thanks @valeriiashapoval!

**Comment by aldiazRH** [comment]
LGTM!

**Pull request merged**
