### PR TITLE
Use Optional: instead

### PR DESCRIPTION
**Pull request by jboxman**
Always use _Optional:_.

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
Actual changes look good, but have two additional pieces of feedback:

1. I don't see in our guidelines that "Optional:" is preferred, though I remember talking about this, so I'm surprised that it's not. If we're asking people to use that over other ways, we should add it as a guideline. Would you mind doing that in a separate PR?
2. I would backport this as far as possible, just to avoid future merge conflicts for others.

**Comment by jboxman** [comment]
@bergerhoffer, from what I gather, this came from ISG and in the new edition appears on page 185.

**Comment by bergerhoffer** [comment]
> @bergerhoffer, from what I gather, this came from ISG and in the new edition appears on page 185.

Awesome, I hadn't caught that in the update. That's good enough for me then, thanks!

**Pull request merged**
