### PR TITLE
[GH55362] Change m5.x2large to m5.2xlarge per GH55362

### PR DESCRIPTION
**Pull request by mletalie**
[GH55362] Change m5.x2large to m5.2xlarge per GH55362

Version(s):

4.12+
Issue:

https://github.com/openshift/openshift-docs/issues/55362
Link to docs preview:

https://55722--docspreview.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html
image

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @yuwang-RH , could you please review me for this (QE review)? Thanks! ML

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by yuwang-RH** [comment]
LGTM~

**Pull request merged**
