### PR TITLE
Comment out NodeStatusMaxImagesExceeded

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.13

Issue: None

Link to docs preview: [CNV runbooks](https://58183--docspreview.netlify.app/openshift-enterprise/latest/virt/support/virt-runbooks.html)

QE review: NA
- [ ] QE has approved this change.

Additional information: Change requested by @sradco

### CODE REVIEW

**Comment by apinnick** [comment]
@sradco Ready for review

**Review by lahinson — COMMENTED** [review]
lgtm

**Pull request merged**
