### PR TITLE
[OSDOCS-12141]: Add additional role to OSD on GCP shared VPC note

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-12141
Link to docs preview:

**With CCS**: https://82543--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-gcp-cluster-ccs_osd-creating-a-cluster-on-gcp

**With GC Marketplace**: https://82543--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-gcp-account_osd-creating-a-cluster-on-gcp

**With RH Marketplace**
https://82543--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster.html#osd-create-cluster-rhm-gcp-account_osd-creating-a-cluster-on-gcp

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @lento-sun , may I get a QE review on this PR when you get a moment? Thx!

**Review by max-cx — APPROVED** [review]
LGTM

**Review by dfitzmau — APPROVED** [review]

**Pull request merged**
