### PR TITLE
OCPBUGS 7544: Replacing instances of k8s.gcr.io with registry.k8s.io

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-7544

Link to docs preview:
https://55928--docspreview.netlify.app/openshift-enterprise/latest/applications/application-health.html#application-health-about_application-health

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh PTAL

Preview: https://55928--docspreview.netlify.app/openshift-enterprise/latest/applications/application-health.html#application-health-about_application-health

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Review by mffiedler — APPROVED** [review]
LGTM

**Pull request merged**
