### PR TITLE
OSDOCS-2363: Updating 1.21 to 1.22 in example output

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-2363

Preview: https://deploy-preview-35409--osdocs.netlify.app/openshift-enterprise/latest/welcome/index.html (throughout doc set)

### CODE REVIEW

**Comment by bergerhoffer** [comment]
Hold this until the rebase lands, so we can confirm it is 1.22.0.

**Comment by bergerhoffer** [comment]
Rebase has landed, good to go.

**Comment by jboxman** [comment]
@bergerhoffer LGTM

**Review by codyhoag — APPROVED** [review]
LGTM!

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bobfuru** [comment]
LGTM

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review these updates to v1.22 throughout our doc set? Thanks!

**Pull request merged**
