### PR TITLE
BZ1703529 corrected command to capture the hawkular certificate

### PR DESCRIPTION
**Pull request by jeana-redhat**
Addressing https://bugzilla.redhat.com/show_bug.cgi?id=1703529

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@juzhao Please review this change in response to https://bugzilla.redhat.com/show_bug.cgi?id=1703529

**Comment by jeana-redhat** [comment]
QE gave approval on bug :+1:

**Comment by mburke5678** [comment]
@jeana-redhat LGTM

**Pull request merged**
