### PR TITLE
OSDOCS-7741: Documented the 4.13.13 z-stream release notes

### PR DESCRIPTION
**Pull request by dfitzmau**
[OSDOCS-7741](https://issues.redhat.com/browse/OSDOCS-7741)

Version(s):
4.13

Link to docs preview:
[4.13.13 z-stream release notes](https://64817--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes#ocp-4-13-13)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
Updates LGTM as well!

**Pull request merged**
