### PR TITLE
Replacing example CR to About Cluster Logging

### PR DESCRIPTION
**Pull request by mburke5678**
Replacing CR in _About the Cluster Logging Custom Resource Definition_.
https://docs.openshift.com/container-platform/4.2/logging/cluster-logging.html#cluster-logging-configuring-crd_cluster-logging

### CODE REVIEW

**Comment by mburke5678** [comment]
@sheriff-rh Do you recall why you added a `ifdef::openshift-dedicated[]` tag here?

https://github.com/openshift/openshift-docs/commit/f5a93ffd72a828762dd16c4d9d377bbb89c00a12#diff-2e73b7f1b268e41025eec8ac0ed41fcdR18

**Comment by jboxman** [comment]
Relatedly, this is a CRD: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

So it's an example CR, rather than a CRD, in this PR. Somewhat confusingly, a CRD appears to be implemented using a CR, but it's through the `apiVersion: apiextensions.k8s.io/v1` API in k8s.

**Comment by mburke5678** [comment]
@jboxman You are correct. As I recall, we wanted to put the CRDs in the docs until we realized that the user edits the CRs (and the CRDs can be huge), and it seemed better to use the CR (I could be remembering this).

**Comment by jboxman** [comment]
@mburke5678, what passes as the CRD will actually be in the API docs, as a table of parameters and values.

**Comment by sheriff-rh** [comment]
> @sheriff-rh Do you recall why you added a `ifdef::openshift-dedicated[]` tag here?
> 
> [f5a93ff#diff-2e73b7f1b268e41025eec8ac0ed41fcdR18](https://github.com/openshift/openshift-docs/commit/f5a93ffd72a828762dd16c4d9d377bbb89c00a12#diff-2e73b7f1b268e41025eec8ac0ed41fcdR18)

Hey @mburke5678 ! There is a separate yaml for dedicated vs enterprise, since dedicated is a very tightly controlled configuration. Hope this helps!

**Comment by mburke5678** [comment]
@sheriff-rh I see it now. The Enterprise YAML isn't in Master (in cluster-logging-configuring-crd.adoc), likely because of the file name change (??).  I copied the two CRs from the 4.1 version and added them to the version in master. Can you take a quick look?
https://raw.githubusercontent.com/openshift/openshift-docs/afb4f5f82b324da4ee89493b5f11edd703149f3f/modules/cluster-logging-about-crd.adoc

**Comment by sheriff-rh** [comment]
> @sheriff-rh I see it now. The Enterprise YAML isn't in Master (in cluster-logging-configuring-crd.adoc), likely because of the file name change (??). I copied the two CRs from the 4.1 version and added them to the version in master. Can you take a quick look?
> https://raw.githubusercontent.com/openshift/openshift-docs/afb4f5f82b324da4ee89493b5f11edd703149f3f/modules/cluster-logging-about-crd.adoc

Looks great @mburke5678 , thanks for checking!

**Pull request merged**
