### PR TITLE
OSDOCS-11416_2#prereq reorg

### PR DESCRIPTION
**Pull request by brendan-daly-red-hat**
Versions:
4.17+

Issue:
https://issues.redhat.com/browse/OSDOCS-11423

Link to docs preview:

**Azure:**
- [Creating the Azure resource group](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/upi/installing-azure-user-infra#installation-azure-create-resource-group-and-identity_installing-azure-user-infra)
- [Creating the bootstrap machine in Azure](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/upi/installing-azure-user-infra#installation-creating-azure-bootstrap_installing-azure-user-infra) 
- [Uploading the RHCOS cluster image and bootstrap Ignition config file](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure/upi/installing-azure-user-infra#installation-azure-user-infra-uploading-rhcos_installing-azure-user-infra)

**Azure Stack Hub:** 
- [Creating the Azure resource group](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-azure-create-resource-group-and-identity_installing-azure-stack-hub-user-infra)
- [Creating the bootstrap machine in Azure Stack Hub ](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra)
- [Uploading the RHCOS cluster image and bootstrap Ignition config file](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra.html#installation-azure-user-infra-uploading-rhcos_installing-azure-stack-hub-user-infra)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by brendan-daly-red-hat** [comment]
@jinyunma, PTAL at the draft update.

**Comment by jinyunma** [comment]
@brendan-daly-red-hat  Thanks for addressing this, the update looks good to me except following one.

For step [Creating the bootstrap machine in Azure Stack Hub](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra) in azure stack hub UPI installation doc,  below precondition should be removed because no identity is created in ASH.
```
Create the Azure Stack Hub identity and grant the appropriate roles.
```

**Comment by brendan-daly-red-hat** [comment]
/label peer-review-needed

> @brendan-daly-red-hat Thanks for addressing this, the update looks good to me except following one.
> 
> For step [Creating the bootstrap machine in Azure Stack Hub](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra) in azure stack hub UPI installation doc, below precondition should be removed because no identity is created in ASH.
> 
> ```
> Create the Azure Stack Hub identity and grant the appropriate roles.
> ```

@jinyunma Thanks for reviewing this. I applied the change to [Creating the bootstrap machine in Azure Stack Hub](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra).

**Comment by brendan-daly-red-hat** [comment]
> @brendan-daly-red-hat Thanks for addressing this, the update looks good to me except following one.
> 
> For step [Creating the bootstrap machine in Azure Stack Hub](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra) in azure stack hub UPI installation doc, below precondition should be removed because no identity is created in ASH.
> 
> ```
> Create the Azure Stack Hub identity and grant the appropriate roles.
> ```

@jinyunma Thanks for reviewing this. I applied the change to [Creating the bootstrap machine in Azure Stack Hub](https://84954--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra#installation-creating-azure-bootstrap_installing-azure-stack-hub-user-infra).

**Review by xenolinux — COMMENTED** [review]
LGTM

**Pull request merged**
