### PR TITLE
Support projectatomic.io page template for Atomic Registry

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by aweiteka** [comment]
@nhr @adellape new PR. This should be good to go now.

**Comment by aweiteka** [comment]
@Fryguy I closed #1698; please take a look at this.

**Comment by adellape** [comment]
@aweiteka Took this for a spin and it seemed good to me. The atomic-registry build locally looked as expected, and the openshift-* builds all looked normal as well.

Would like to get an ack from @nhr on implementation before merging.

**Comment by aweiteka** [comment]
@nhr @Fryguy could one of you take a peek?

**Comment by nhr** [comment]
LGTM - @Fryguy, speak now or forever hold your peace :-) I will merge this by EOB unless you have any comments / concerns.

**Comment by adellape** [comment]
@nhr Should this get picked to the other branches for some of the non-atomic page changes? Or does it not matter?

**Comment by nhr** [comment]
Thanks for picking this up. All of the changes were to _templates/ and the new index page, so it should not be necessary to patch this to the branches.

**Pull request merged**
