### PR TITLE
Fixes spacing/indentation in yaml construct for prometheusK8s config.

### LINKED ISSUE #43227: [enterprise-4.9] Issue in file monitoring/configuring-the-monitoring-stack.adoc
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#configuring-the-monitoring-stack_configuring-the-monitoring-stack

### What needs fixing?

yaml for the prometheus volume needs to be corrected. Incorrect spacing starting at "spec"...

```
data:
  config.yaml: |
    prometheusK8s: 
      volumeClaimTemplate:
       spec:
         storageClassName: fast
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
```

### PR DESCRIPTION
**Pull request by briantward**
fixes https://github.com/openshift/openshift-docs/issues/43227

### CODE REVIEW

**Comment by bburt-rh** [comment]
QE needs to approve this change before it can be merged.

@briantward Can you confirm what versions of the docs this affects? Looks like 4.6+ in my cursory look through the existing docs.

@juzhao - PTAL and approve if everything looks good.

**Comment by juzhao** [comment]
/lgtm
we also need to back port to 4.10
https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html
no such issue with version before 4.10

**Pull request merged**
