### PR TITLE
[enterprise-4.6] OSDOCS-3853: add new redirector URL

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.6

Issue: https://issues.redhat.com/browse/OSDOCS-3857

Link to docs preview: http://file.rdu.redhat.com/jdohmann/OSDOCS-3853-4.6/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

Additional information: Manual cherrypick of #48134

### CODE REVIEW

**Comment by jldohmann** [comment]
@mike-nguyen PTAL for QE ack. This is a manual cherrypick of https://github.com/openshift/openshift-docs/pull/48134 to 4.6

**Comment by mike-nguyen** [comment]
This looks good to me, but we haven't made the the changes to 4.6 yet.  We've worked our way back from 4.12 to 4.9.  4.8, 4.7, and 4.6 have not been done yet.

**Review by kelbrown20 — COMMENTED** [review]
From the peer review end, this LGTM!

**Comment by jldohmann** [comment]
@mike-nguyen has the installer PR for this landed?

**Comment by mike-nguyen** [comment]
@jldohmann looks like the PRs got closed because 4.6 and 4.7 are EOL.

**Comment by jldohmann** [comment]
Thanks @mike-nguyen, I am going to go ahead and close this PR. I can reopen again if needed

**Pull request closed without merging**
