### PR TITLE
RAN consolidated release notes for 4.11

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.11

Issue: 
Known issues: https://issues.redhat.com/browse/TELCODOCS-674
New features: https://issues.redhat.com/browse/TELCODOCS-672

Link to docs preview: 
New features: https://50930--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-ran-features
Known issues: https://50930--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-ran-known-issues

QE review:
- [x] QE has approved this change.

Additional information:
This PR is consolidated from the following reviewed PRs:
* 628 RN: https://github.com/openshift/openshift-docs/pull/48933
* 339 RN: https://github.com/openshift/openshift-docs/pull/49640
* KIs: https://github.com/openshift/openshift-docs/pull/49433

### CODE REVIEW

**Comment by opayne1** [comment]
Note to peer review squad that this will be added in after 4.11.6 but will go in the 4.11.6 entry. Please reach out if you have questions.

**Comment by opayne1** [comment]
Removed the peer-review-needed label because Kelly Reviewed #49433

**Comment by amolnar-rh** [comment]
@opayne1 Implemented the peer review comments from https://github.com/openshift/openshift-docs/pull/49433 (responses are in the other PR for easier tracking). I didn't squash the commits yet so you can check the diff if needed.

**Comment by opayne1** [comment]
Closing this PR since we merged #50945

**Pull request closed without merging**
