### PR TITLE
Import updated API documentation from origin

### PR DESCRIPTION
**Pull request by jim-minter**
Merge after https://github.com/openshift/origin/pull/15788.  @bparees PTAL.

### CODE REVIEW

**Comment by bparees** [comment]
here too separate commits for the tooling changes and the content changes would be helpful.

**Comment by jim-minter** [comment]
@bparees done (here)

**Comment by bparees** [comment]
lgtm, @openshift/team-documentation ptal

**Comment by bparees** [comment]
@jim-minter needs a rebase
@openshift/team-documentation any questions/concerns on this?

**Comment by bmcelvee** [comment]
http://file.rdu.redhat.com/~bmcelvee/083017/jim-minter-rest_api_work/rest_api/index.html

**Comment by jim-minter** [comment]
@bparees it's tedious keeping this rebased; I mentioned this to @bmcelvee.  As soon as there's a green light from docs, I'll rebase and then it can be merged.

**Comment by ahardin-rh** [comment]
@jim-minter I think this looks good and we can get this merged once you rebase. @bmcelvee is OOO, but feel free to ping me and @vikram-redhat  to merge this when it's ready and we will get it in. Thanks so much!

**Comment by jim-minter** [comment]
@ahardin-rh great! rebased!

**Comment by jim-minter** [comment]
@ahardin-rh I don't think this should be going to enterprise-3.6 -- I think it should be origin plus anything that is branched in the future

**Comment by ahardin-rh** [comment]
@jim-minter Also, (sorry!) forgot to mention that this need to be squashed into 1 commit for our publishing process.

**Comment by jim-minter** [comment]
@ahardin-rh squashed

**Pull request merged**
