### PR TITLE
Adding version variable to single file.

### PR DESCRIPTION
**Pull request by JStickler**
Replacing a hard coded version number with a variable.
Preview is here -> https://deploy-preview-41718--osdocs.netlify.app/openshift-enterprise/latest/service_mesh/v2x/ossm-security.html#ossm-cert-manage_ossm-security  
Variable updates the two links to the Maistra repository

Peer review - rh-tokeefe, GroceryBoyJr. bergerhoffer

### CODE REVIEW

**Comment by JStickler** [comment]
FYI @rh-tokeefe

**Comment by rh-tokeefe** [comment]
LGTM

**Review by GroceryBoyJr — APPROVED** [review]
Julie - LGTM, but pause for someone to check behind me and do the merge.....I'm training.

**Review by bergerhoffer — COMMENTED** [review]
LGTM too!

**Pull request merged**
