### PR TITLE
OSDOCS-2907 New GCP region

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2907

Preview: https://deploy-preview-41595--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#installation-gcp-regions_installing-gcp-account

### CODE REVIEW

**Comment by codyhoag** [comment]
@jianli-wei can you verify? Thanks!

**Comment by jianli-wei** [comment]
LGTM, thanks

**Pull request merged**
