### PR TITLE
Updated health checks for 4.0

### PR DESCRIPTION
**Pull request by mburke5678**
https://jira.coreos.com/browse/OSDOCS-202

### CODE REVIEW

**Comment by mburke5678** [comment]
Mereging for HTB. Any changes can be tracked through a follow-up PR.

**Comment by vikram-redhat** [comment]
@mburke5678 this still needs to go through QA and peer review.

**Comment by mburke5678** [comment]
@jhou1 Can you take a look at this PR or assign to another QE person?

**Comment by jhou1** [comment]
@weinliu PTAL

**Comment by weinliu** [comment]
@mburke5678 , sunilc and I forgot to leave a comment here.  We replied with LGTM on Mar 11 at https://jira.coreos.com/browse/OSDOCS-202. 
Thanks!

**Pull request merged**
