### PR TITLE
Replace LabelsPreference with LabelPreference

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by adellape** [comment]
Was trying to verify in https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go. Seems like it follows the same structure as `ServiceAffinity` but couldn't tell for sure...

@abhgupta Can you verify this change?

**Comment by nak3** [comment]
Sorry. I wanted to change `LabelsPreference` to `LabelPreference`. `LabelsPresence` should be `LabelPresence`. 

I think we should follow api tyes.

https://github.com/openshift/origin/blob/v1.0.4/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/api/types.go#L60

**Comment by adellape** [comment]
Ah OK, thanks for clarifying. I'll wait for an update to this PR?

**Comment by adellape** [comment]
Thanks, LGTM

**Pull request merged**
