### PR TITLE
OSDOCS-11401: update with correct current path

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.16+

Issue: https://issues.redhat.com/browse/OSDOCS-11401

Link to docs preview: https://79308--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-configure-ingress-access-logging_configuring-ingress

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@ShudiLi can you PTAL at this docs PR? it updates the Ingress syslog destination location. thank you 🙇

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Comment by mletalie** [comment]
Requested preview link for review purposes.

**Comment by ShudiLi** [comment]
/lgtm
@jldohmann done, thanks

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress
/lgtm

**Pull request merged**
