### PR TITLE
BUG1383703 - Corrected the path for routes.json,certs and cacerts  for Monitoring Routers section

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Changed from _**/var/lib/containers/router/**_ to _**/var/lib/haproxy/router/**_

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM!

**Comment by weliang1** [comment]
@adellape PTAL

@gaurav-nelson what versions of the docs should be updated?

**Comment by vikram-redhat** [comment]
Hey @weliang1 - If I understand correctly, this should apply to Enterprise 3.3 docs and Origin. I am merging it now, and it should come up in the Origin docs overnight and in the Enterprise 3.3 docs next week.

Let me know if you have any questions.

**Pull request merged**
