### PR TITLE
Corrected logTypes from FLOW to FLOWS

### PR DESCRIPTION
**Pull request by dhgautam99**
The configurable options for logTypes are FLOWS CONVERSATIONS, ENDED_CONVERSATIONS, or ALL. In this config, logTypes is defined as FLOW instead of FLOWS and it needs to be corrected.

Version(s): 4.10, 4.11, 4.12 and 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-6604

Link to docs preview:

https://docs.openshift.com/container-platform/4.13/networking/network_observability/configuring-operator.html#network-observability-flowcollector-view_network_observability

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jotak** [comment]
Good catch again! thanks
lgtm
cc @skrthomas

**Review by skrthomas — COMMENTED** [review]
Good catch! Thank you :) Looks good to me!

**Review by skrthomas — APPROVED** [review]

**Pull request merged**
