### PR TITLE
ROX-13700-central-endpoint-note

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):
- Merge to `rhacs-docs`
- Cherry pick to `rhacs-docs-3.73`

[Issue](https://issues.redhat.com/browse/ROX-13700)

[Link to docs preview](https://openshift-docs-en5oswtc9-kcarmichael08.vercel.app/openshift-acs/master/cli/getting-started-cli.html#using-cli_cli-getting-started) (third bullet in note)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by kcarmichael08** [comment]
@rukletsov and @porridge would you mind taking a look to see if the language I used here is OK? I see that the URL appears on the Cloud Console page now and it's marked as the UI/roxctl Central instance. I think from the example in the JIRA ticket that the `https` part isn't used with `roxctl` so I guess just lmk if my language is correct here.

**Comment by rukletsov** [comment]
@kcarmichael08 I think we miss a mention of ACS cloud service. Is this what `product-title-managed` resolves to?

**Comment by kcarmichael08** [comment]
> 

Hi Alex, yes, that variable is for cloud service. If you look at the "link to doc preview" in the body of the pull request it should be resolved correctly.

**Review by rukletsov — APPROVED** [review]

**Review by JoeAldinger — COMMENTED** [review]
/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Pull request merged**
