### PR TITLE
OSDOCS-5405: revise install to remove local copy

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.13+

Issue:
https://issues.redhat.com/browse/OSDOCS-5405

Link to docs preview:
https://56957--docspreview.netlify.app/microshift/latest/microshift_install/microshift-embed-in-rpm-ostree.html#adding-MicroShift-repos-image-builder_microshift-embed-in-rpm-ostree (main change)

https://56957--docspreview.netlify.app/microshift/latest/microshift_install/microshift-install-rpm.html (revising additional resources to make formattting parallel)

QE review:
- [x] QE has approved this change.
Note: SME is approving in lieu of QE (see lgtm before rebase).

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@jogeo and @fzdarsky I realize the now-second step says 1. also, but I think it's not needed anyway. Or do we have a different step to add? PTAL, thank you!

**Comment by ShaunaDiaz** [comment]
@fzdarsky Does this look good to you?
@jogeo Can QE affirm this shorter procedure?

**Comment by fzdarsky** [comment]
This LGTM, thanks. I've just noticed a bug in Step 1, though, which is that instead of `--enable rhocp-{product-version}-for-rhel...` it has to be `--enable rhocp-{ocp-version}-for-rhel...`. Shall we include a fix in this PR?

**Comment by dhellmann** [comment]
This looks correct.

/lgtm

**Review by snarayan-redhat — COMMENTED** [review]
LGTM

**Comment by stevsmit** [comment]
LGTM

**Pull request merged**
