### PR TITLE
OCP 4.13 - IBM Power Virtual Server using installer-provisioned infra…

### PR DESCRIPTION
**Pull request by alishaIBM**
…structure follow up PR

Follow up to https://github.com/openshift/openshift-docs/pull/47558

openshift-4.13+

### CODE REVIEW

**Comment by alishaIBM** [comment]
fyi : @kalexand-rh @mburke5678

**Review by kalexand-rh — APPROVED** [review]
The new links match the change in https://github.com/openshift/openshift-docs/pull/60058, and uncommenting the `<4>` should correct the build error. LGTM! Thank you for making these updates.

**Pull request merged**
