### PR TITLE
OBSDOCS-119: Tiny bug fix for command

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OBSDOCS-119

Link to docs preview:
https://67609--docspreview.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-log-store#cluster-logging-manual-rollout-rolling_cluster-logging-log-store

QE review:
Not required, very minor typo fix

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead

**Comment by abhatt-rh** [comment]
> LGTM
> 
> I am new on the peer review squad. Please wait until @abhatt-rh gives my review the go-ahead 

LGTM

**Pull request merged**
