### PR TITLE
OSDOCS-9551: Further clarify CPMS non-IPI incompatibility

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-9551](https://issues.redhat.com//browse/OSDOCS-9551)

Link to docs preview:
[Limitations](https://71212--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso-about.html#cpmso-limitations_cpmso-about)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@damdo PTAL when you can :)

**Review by damdo — COMMENTED** [review]
Thanks @jeana-redhat 
LGTM!

**Review by bburt-rh — APPROVED** [review]
LGTM. No comments or suggestions. Excellent PR, Jeana! Thank you so much.

**Comment by jeana-redhat** [comment]
Thanks @bburt-rh! rebased and refreshed pre-merge

**Pull request merged**
