### PR TITLE
[enterprise-4.13]OCPBUGS#16845: allocateLoadBalancerNodePorts support release notes

### PR DESCRIPTION
**Pull request by snarayan-redhat**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OCPBUGS-16845

Link to docs preview: https://63651--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes#ocp-4-13-networking-networkapi

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by andreaskaris** [comment]
Looks good to me but I'll let others comment, too

**Comment by snarayan-redhat** [comment]
Closing this PR, as Release Notes team will be creating one after the advisory update.

**Comment by aravipra** [comment]
testing comment

**Comment by aravipra** [comment]
testing comment

**Comment by aravipra** [comment]
commenting again

**Pull request closed without merging**
