### PR TITLE
OBSDOCS-772: Fix containerLimit docs bug

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OBSDOCS-772

Link to docs preview:
https://73314--ocpdocs-pr.netlify.app/openshift-enterprise/latest/logging/performance_reliability/logging-flow-control-mechanisms#logging-set-input-rate-limit_logging-flow-control-mechanisms

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by kcarmichael08** [comment]
LGTM!

**Pull request merged**
