### PR TITLE
OCPBUGS-9944: Updating User-Replaced Values to Use Underscores

### PR DESCRIPTION
**Pull request by kdrake20**
**Fixes:** [OCPBUGS-9944](https://issues.redhat.com/browse/OCPBUGS-9944)

**For:** Version 4.11+
[Version 4.10](https://github.com/openshift/openshift-docs/pull/59264)

**Doc Preview** [here](https://57889--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-troubleshooting.html)

**Signed-off-by:** Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
Nice fix!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by jeana-redhat** [comment]
Don't forget to squash your commits, and I suspect this [bit](https://github.com/openshift/openshift-docs/pull/57889/files#diff-9334faadf96539f60825900554c3bb2b290ecbbb29edfb9ebcb2d620373053faR34) merits QE validation :slightly_smiling_face:

**Comment by ktothill** [comment]
**Who:**
Chad Crum, QE
Oved Ourfali, SME

**Summary:** Requested QE, SME and Peer Reviews.

**Next Steps:**
 - [ ] Receive LGTM from QE, SME, and Peer Review

**Comment by ktothill** [comment]
> Don't forget to squash your commits, and I suspect this [bit](https://github.com/openshift/openshift-docs/pull/57889/files#diff-9334faadf96539f60825900554c3bb2b290ecbbb29edfb9ebcb2d620373053faR34) merits QE validation 🙂

Thanks so much! I've fixed the commit issue and this is ready for another round of peer reviews.

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-needed
/label peer-review-done

**Comment by ktothill** [comment]
@oourfali, could I please get a review of this PR? Thank you!

**Comment by jboxman-rh** [comment]
@ktothill, this might need a manual CP to 4.9 and 4.10.

**Pull request merged**
