### PR TITLE
[dedicated-3.6] Documenting how to prevent PVC deletion if the PVC is…

### PR DESCRIPTION
**Pull request by ghost**
… in use by a pod

(cherry picked from commit 20bddcfcf02ae402b24eea6a558541cdf7d3ec9e) xref:

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@vikram-redhat Hi Vikram, can you review this PR? How do I troubleshoot build failures?Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - run asciibinder locally on your branch (asciibinder build). That should replicate the same error.

**Comment by tmorriso-rh** [comment]
@vikram-redhat I did the build locally and got this result:

-----------------------------------------------------------------------
The build will proceed but these branches will not be generated.
Error: The topic map file at '_topic_map.yml' contains the following errors:
- Topic entity at 'Installation and Configuration -> Persistent Storage Examples -> Installing a Cluster -> Planning' exceeds the maximum nested depth.
-----------------------------------------------------------------------------------------------
There are about 30 topic entities listed. What is the best fix? Is there a way to swap the corrupt topic_map file in my local branch with a clean version?

**Comment by vikram-redhat** [comment]
@tmorriso-rh - that would be hard to say. Were there any merge conflicts? I will try and replicate your branch locally to see what the issue is.

**Comment by tmorriso-rh** [comment]
@vikram-redhat Yes, I resolved all of the merge conflicts. There were many <<<<<<< HEAD pulled into the file.

**Comment by tmorriso-rh** [comment]
Cross ref: https://github.com/openshift/openshift-docs/pull/7867

**Pull request closed without merging**
