### PR TITLE
WIP: OSDOCS-2173: [4.9] Added Intel E810 NICs for SRIOV

### PR DESCRIPTION
**Pull request by ctauchen**
This PR adds support for the Intel E810 NICs.

For information, see
https://issues.redhat.com/browse/OSDOCS-2173
https://bugzilla.redhat.com/show_bug.cgi?id=2019844

Applies only to `enterprise-4.9`

Device list: https://deploy-preview-41332--osdocs.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

RN: https://deploy-preview-41332--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-9-release-notes.html#ocp-4-9-supported-hardware-sriov

### CODE REVIEW

**Comment by ctauchen** [comment]
@zshi-redhat Can you take a look? Thanks!

**Comment by ctauchen** [comment]
@zhaozhanqi Can you do a QE review? Thanks!

**Review by mffiedler — APPROVED** [review]
LGTM

**Comment by mcurry-rh** [comment]
LGTM

**Pull request closed without merging**
