### PR TITLE
Refresh API reference docs

### PR DESCRIPTION
**Pull request by jboxman**
Initial pass at this.

Preview: http://file.bos.redhat.com/jboxman/apis-refresh-311/rest_api/

Need to manually add the following, but it isn't likely this will ever need to be published again.

```
ifdef::product-title[]
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:
endif::[]
```

~OCP 3.11 OpenAPI likes to omit type `object`, so the build tool might require a few changes to deal with that.~

### CODE REVIEW

**Comment by jboxman** [comment]
@vikram-redhat FYI

This can supersede the existing API reference docs for 3.11.

**Comment by jboxman** [comment]
@vikram-redhat, added preview build.

**Comment by jboxman** [comment]
@vikram-redhat if this seems legit, I can close out 3 old BZs with it.

**Comment by vikram-redhat** [comment]
Nice! I need to understand how you did the refresh. I will ping you offline.

**Pull request merged**
