### PR TITLE
OBSDOCS-715: remove deprecated dedicated service monitor topics

### PR DESCRIPTION
**Pull request by bburt-rh**
Version(s): 4.15 only

Issue: https://issues.redhat.com/browse/OBSDOCS-715

Link to docs preview: Preview should show that the dedicated service monitor feature docs [present in the OCP 4.14 docs](https://docs.openshift.com/container-platform/4.14/monitoring/configuring-the-monitoring-stack.html#configuring-a-dedicated-service-monitor_configuring-the-monitoring-stack) are no longer present:
https://70515--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack

QE review:
- [x] QE has approved this change.

Additional information:
This PR removes content for the deprecated dedicated service monitor feature from the in-cluster monitoring content for the OCP 4.15 docs.

### CODE REVIEW

**Comment by juzhao** [comment]
@Tai-RedHat please help to review the doc, epic is [MON-3452](https://issues.redhat.com/browse/MON-3452) , see from the doc task [OBSDOCS-715](https://issues.redhat.com/browse/OBSDOCS-715)

**Comment by Tai-RedHat** [comment]
https://github.com/openshift/openshift-docs/blob/main/modules/telco-core-monitoring.adoc

Since the `DedicatedServiceMonitors` setting is deprecated, It looks like the description here might need to be revised.

**Comment by bburt-rh** [comment]
> https://github.com/openshift/openshift-docs/blob/main/modules/telco-core-monitoring.adoc
> 
> https://github.com/openshift/openshift-docs/blob/46df16c618d8213561bf9944523a5b5e76bfa320/modules/telco-core-monitoring.adoc#L31
> 
> Since the `DedicatedServiceMonitors` setting is deprecated, It looks like the description here might need to be revised.

@Tai-RedHat - You are correct. However, the content you linked to is in the OpenShift Telco docs, which are not publicly available and not part of the core OCP docs published at docs.openshift.com. The Telco docs are managed by a separate docs team,and I've contacted them to create a new issue to get this content revised in the Telco docs set. When this issue is created by @aireilly, I will tag you in it.

So the upshot is that this revision will get made, but as part of a Telco docs PR. The Telco docs changes are out of scope for this PR, which is for the core in-cluster monitoring docs. 

Therefore, if no further changes are necessary for this PR, can you please give it an LGTM? Thanks!

**Comment by bburt-rh** [comment]
@Tai-RedHat - The related Telco docs issue related to this PR is: https://issues.redhat.com/browse/TELCODOCS-1725

**Comment by michaelryanpeter** [comment]
LGTM
/label peer-review-done
/remove-label peer-review-needed
/remove-label peer-review-in-progress

**Pull request merged**
