### PR TITLE
OCPBUGS#24441 Removing port 80 from firewall docs

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OCPBUGS-24441

Link to docs preview:https://68960--docspreview.netlify.app/openshift-enterprise/latest/installing/install_config/configuring-firewall

QE review:
- [x] QE has approved this change.

Confirmed by Patrick Dillon in Slack chat that this can be removed from the docs with QE's approval.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@gpei Hello, can you review this PR removing port 80 from the firewall docs or refer me to the right QE resource to do so? Thank you!

**Comment by gpei** [comment]
It looks good to me. When checking into the access log of a proxy server which is used for the cluster installation, all websites are visited with 443 port. 

```
[root@ip-10-0-8-227 ~]# awk -F " " '{print $7}' /srv/squid/log/access.log |sort -n |uniq 

api.openshift.com:443
canary-openshift-ingress-canary.apps.gpei-aws06.qe.devcluster.openshift.com:443
cdn02.quay.io:443
console-openshift-console.apps.gpei-aws06.qe.devcluster.openshift.com:443
console.redhat.com:443
d1wgmlmph9kt2c.cloudfront.net:443
ec2.us-east-2.amazonaws.com:443
elasticloadbalancing.us-east-2.amazonaws.com:443
google.com:443
gpei-aws06-sbs6p-bootstrap.s3.us-east-2.amazonaws.com:443
gpei-aws06-sbs6p-image-registry-us-east-2-endkvrcwvaffhlvdpuqo.s3.dualstack.us-east-2.amazonaws.com:443
iam.amazonaws.com:443
infogw.api.openshift.com:443
oauth-openshift.apps.gpei-aws06.qe.devcluster.openshift.com:443
quay.io:443
registry.access.redhat.com:443
registry.ci.openshift.org:443
registry.redhat.io:443
route53.amazonaws.com:443
tagging.us-east-1.amazonaws.com:443
us-east-2-replica-of-ci-dv2np-image-registry-us-east-1.s3.amazonaws.com:443
www.shadowserver.org:443
```

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
