### PR TITLE
[enterprise-4.13] OSDOCS-7126: Added vCenter requirements section to vSphere UPI docs

### PR DESCRIPTION
**Pull request by dfitzmau**
Cherry-picked from commit [#60436](https://github.com/openshift/openshift-docs/pull/60436)

[OSDOCS-7126](https://issues.redhat.com/browse/OSDOCS-7126)

Version(s):
4.13

Previews:
* [Installing a cluster on vSphere with user-provisioned infrastructure](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-installer-infra-requirements_installing-vsphere)
* [Installing a cluster on vSphere with network customizations](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-network-customizations.html#installation-vsphere-installer-infra-requirements_installing-vsphere-network-customizations)
* [Installing a cluster on vSphere in a restricted network with user-provisioned infrastructure](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-installer-infra-requirements_installing-restricted-networks-vsphere)
* [Installing a cluster on VMC with user-provisioned infrastructure](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-vmc-user-infra.html#installation-vsphere-installer-infra-requirements_installing-vmc-user-infra)
* [Installing a cluster on VMC with user-provisioned infrastructure and network customizations](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-vmc-network-customizations-user-infra.html#installation-vsphere-installer-infra-requirements_installing-vmc-network-customizations-user-infra)
* [Installing a cluster on VMC in a restricted network with user-provisioned infrastructure](https://62863--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc-user-infra.html#installation-vsphere-installer-infra-requirements_installing-restricted-networks-vmc-user-infra)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by JoeAldinger** [comment]
@dfitzmau has this gone through peer-review? I'm going to remove it from the merge queue till I hear back to avoid confusion.

**Comment by JoeAldinger** [comment]
Cherry-picked from 94ad17f7fdec741b2b983da8f73641e73d4e9d59 xref https://github.com/openshift/openshift-docs/pull/60436

**Comment by dfitzmau** [comment]
@JoeAldinger . Ready for merging.

**Pull request merged**
