### PR TITLE
bug 1798921 BYO VPC proxy

### PR DESCRIPTION
**Pull request by kalexand-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1798921

@gpei, I've updated the note and added the option to set the proxy to AWS, Azure, and GPC BYO VPC/Vnet and private docs. Does this seem reasonable to you?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
This change was approved on the bug.

@openshift/team-documentation, will you PTAL?

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
