### PR TITLE
[SRVKE-1173]: Update dashboard name

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+

Issue:
https://issues.redhat.com/browse/SRVKE-1173

Link to docs preview:
- https://deploy-preview-45383--osdocs.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-admin-monitoring.html#serverless-admin-monitoring-eventing-broker-trigger_serverless-admin-monitoring

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by jrangelramos** [comment]
QE Approved

**Pull request merged**
