### PR TITLE
[OSDOCS-4456]: Update documentation to reflect ROSA Route Sharding for Custom Domain

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.12+
Issue:

https://issues.redhat.com/browse/OSDOCS-4456
Link to docs preview:

https://56945--docspreview.netlify.app/openshift-rosa/latest/applications/deployments/osd-config-custom-domains-applications.html
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Hello @yuwang-RH , could you please review me for this (QE review)? Thanks! ML

**Comment by mletalie** [comment]
QE reviewer: As an FWIW, I have already received guidance/acceptance for the changes from two members of the SRE team as well as the Jira ticket reporter, but as I am still learning the workflow processes, assumed that someone from the QE team needed to review as well. Thanks!!

**Comment by lihongan** [comment]
@mletalie it looks good.
Thank you!

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
