### PR TITLE
OSDOCS-10559: adds assembly for router docs MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.16+

Issue:
[OSDOCS-10559](https://issues.redhat.com/browse/OSDOCS-10559)

Link to docs preview:
[MicroShift router assembly](https://75899--ocpdocs-pr.netlify.app/microshift/latest/microshift_networking/microshift-nw-router.html)

SME review:
Done

QE review:
N/A docs structural addition

### CODE REVIEW

**Review by pacevedom — APPROVED** [review]
/lgtm

**Comment by aldiazRH** [comment]
LGTM!

**Pull request merged**
