### PR TITLE
[OSDOCS-6138]: Azure AD Workload ID installation RNs

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.14

Issue:
[OSDOCS-6138](https://issues.redhat.com//browse/OSDOCS-6138)

Link to docs preview:
[Installing a cluster with Azure AD Workload Identity](https://64960--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-azure-ad-workload-id)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by cbippley — COMMENTED** [review]
LGTM!

**Comment by dlom** [comment]
LGTM :shipit:

**Comment by jianping-shu** [comment]
LGTM

**Comment by jeana-redhat** [comment]
resolved merge conflict

**Pull request merged**
