### PR TITLE
TELCODOCS-1107 - remove TP label from DTK

### PR DESCRIPTION
**Pull request by slovern**
[TELCODOCS-1107](https://issues.redhat.com//browse/TELCODOCS-1107) - remove TP label from DTK

Version(s): 4.12

Issue: https://issues.redhat.com/browse/TELCODOCS-1107

Link to docs preview: https://54603--docspreview.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-driver-toolkit.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by slovern** [comment]
@cdvultur @bthurber 
This PR removes the TP label from DTK. Can you add /lgtm?

**Comment by Amrita42** [comment]
lgtm

**Pull request merged**
