### PR TITLE
GH32085: Add note to etcd encryption section

### PR DESCRIPTION
**Pull request by hmaclean73**
https://github.com/openshift/openshift-docs/issues/32085

For versions 4.6+

Direct link to doc preview: https://deploy-preview-35025--osdocs.netlify.app/openshift-enterprise/latest/security/encrypting-etcd.html

Ready for QA: @geliu2016 
@sttts Can you please review this PR?

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by hexfusion** [comment]
LGTM

**Comment by geliu2016** [comment]
/lgtm
@wangke19 please help to double confirm, thanks

**Pull request merged**
