### PR TITLE
Updated versions for maistra-0.4.0 release: MAISTRA-107

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Comment by knrc** [comment]
@geekspertise Can you take a quick look at this?  There shouldn't be anything controversial as it's just updating versions to align with the 0.4.0 release.  Thanks very much.

**Comment by geekspertise** [comment]
@knrc I looked through the changes and I see no problems.

**Comment by JStickler** [comment]
@knrc @geekspertise , We probably should also rev the version in the attributes files (one for each manual) to read ":ProductVersion: 0.4.TechPreview".  It doesn't show externally, but I've been doing it just to help track the TP versions internally.

**Comment by JStickler** [comment]
@knrc  is there an updated version/link to the operator templates for TP4?

**Comment by geekspertise** [comment]
@JStickler @knrc That will be part of my PR

> @knrc @geekspertise , We probably should also rev the version in the attributes files (one for each manual) to read ":ProductVersion: 0.4.TechPreview". It doesn't show externally, but I've been doing it just to help track the TP versions internally.

That will be part of my PR as it was in the last release.

**Comment by JStickler** [comment]
@geekspertise , OK, cool I was thinking that the Release Notes PR might just be updates to the Release Notes, but sounds like you've got things covered.

**Comment by knrc** [comment]
@JStickler Sorry about that, I was searching for 0.3.0 and didn't find the 0.3 ones.

@geekspertise Thanks for picking these up

**Comment by kalexand-rh** [comment]
@geekspertise, @JStickler, does this need to be merged and CP'd to 3.11?

**Comment by geekspertise** [comment]
> @geekspertise, @JStickler, does this need to be merged and CP'd to 3.11?

@knrc Is this ready to be merged? I don't have any additional changes.

**Comment by knrc** [comment]
@geekspertise @JStickler @kalexand-rh Yes please, this needs to be merged as we are now pushing live

**Comment by kalexand-rh** [comment]
Ok. Merging!

**Pull request merged**
