### PR TITLE
[OSDOCS-8450] Clarify note about MHC machine set requirement

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.12+

Issue:
[OSDOCS-8450](https://issues.redhat.com//browse/OSDOCS-8450)

Link to docs preview:
* [About machine health checks](https://67427--docspreview.netlify.app/openshift-enterprise/latest/machine_management/deploying-machine-health-checks#machine-health-checks-about_deploying-machine-health-checks)
* [Creating a machine health check resource](https://67427--docspreview.netlify.app/openshift-enterprise/latest/machine_management/deploying-machine-health-checks#machine-health-checks-creating_deploying-machine-health-checks)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by jeana-redhat** [comment]
Can one of @zhouhao3 @huali9 or @miyadav PTLA for QE?

**Comment by huali9** [comment]
> Can one of @zhouhao3 @huali9 or @miyadav PTAL for QE?

Should be @sunzhaohua2

**Comment by miyadav** [comment]
thanks @jeana-redhat , LGTM

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by jeana-redhat** [comment]
/label merge-review-needed

Needs an approval, please

**Review by bscott-rh — APPROVED** [review]

**Pull request merged**
