### PR TITLE
[RHACS] ROX-21300: Correcting operator values

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.1+

Issue:
https://issues.redhat.com/browse/ROX-21300

Link to docs preview:
Screenshot from 2023-12-13 13-38-22

SME review:
- [x] SME has approved this change.

Additional information:
- Merge into `rhacs-docs` and cherry-pick to:
    - `rhacs-docs-4.4`
    - `rhacs-docs-4.3`
    - `rhacs-docs-4.2`
    - `rhacs-docs-4.1`

### CODE REVIEW

**Review by dhaus67 — APPROVED** [review]

**Review by jeana-redhat — APPROVED** [review]
No preview but LGTM based on file view :+1: 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by sheriff-rh — APPROVED** [review]
LGTM, merging.

**Comment by agantony** [comment]
Hi @sheriff-rh Please also cherry-pick to the `rhacs-docs-4.4` branch.

**Comment by sheriff-rh** [comment]
Thanks @agantony !

**Pull request merged**
