### PR TITLE
ROSA remove temporary test directory without symlinks for WFM

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
Main only 

Issue:
No issue. Removing test directory added in https://github.com/openshift/openshift-docs/pull/60287

Link to docs preview:
No preview. Not included in topic map. 

QE review:
- [ ] QE has approved this change.
No QE review required. 

Additional information:
 This was a temporary directory to test tooling. This directory was not building in any live documentation.

### CODE REVIEW

**Comment by aldiazRH** [comment]
LGTM!

**Comment by laujohns89** [comment]
LGTM 2!

**Pull request merged**
