### PR TITLE
Updates Ruby on Rails example to include setting required env var

### PR DESCRIPTION
**Pull request by coreydaley**
Updates example to include setting required environment
variable DATABASE_SERVICE_NAME

Fixes https://github.com/openshift/rails-ex/issues/108

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees @openshift/team-documentation ptal

**Comment by bparees** [comment]
lgtm

**Comment by bmcelvee** [comment]
LGTM 🌟 

@coreydaley does this fix need to go in OCP 3.1-3.9?

**Comment by bmcelvee** [comment]
No revision history needed.

**Comment by coreydaley** [comment]
@bmcelvee I believe so, @bparees ?

**Comment by bparees** [comment]
yeah for what it's worth, might as well backport it all the way.

**Comment by bmcelvee** [comment]
Sounds good. Thanks, @coreydaley and @bparees!

**Pull request merged**
