### PR TITLE
OSDOCS-8696: adds 4.12.43 to RNs

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-8696

Link to docs preview:
https://68099--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes#ocp-4-12-43

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by shipsing** [comment]
@JoeAldinger, the changes look fine.
 
Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

**Comment by bburt-rh** [comment]
LGTM. Thanks @shipsing!

**Pull request merged**
