### PR TITLE
Bug 1376585 Followup to 3916

### PR DESCRIPTION
**Pull request by bfallonf**
As per #3916 

Essentially moved the section to a different location, but also some minor rewording.

cc @sjenning @derekwaynecarr Let me know if there's any disagreements.

@ahardin-rh @adellape @bmcelvee @mburke5678 Peer review please?

### CODE REVIEW

**Comment by bfallonf** [comment]
[rev_history]
|xref:../admin_guide/manage_nodes.adoc#admin-guide-manage-nodes[Managing Nodes]
|Added the xref:../admin_guide/manage_nodes.adoc#admin-guide-max-pods-per-node[Setting Maximum Pods Per Node] section.
%

**Review by adellape — APPROVED** [review]
You could drop the `====`s around the two code blocks since we don't use those anymore, but otherwise LGTM!

**Comment by mburke5678** [comment]
LGTM

**Comment by bfallonf** [comment]
Also, as per this: https://bugzilla.redhat.com/show_bug.cgi?id=1376585

**Comment by bfallonf** [comment]
And thanks all, I'll merge.

**Pull request merged**
