### PR TITLE
OSDOCS-1857 Add note for empty RG permissions info

### PR DESCRIPTION
**Pull request by codyhoag**
Add-on to original docs feature work

https://issues.redhat.com/browse/OSDOCS-1857

Preview: https://deploy-preview-32032--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account.html#installation-azure-service-principal_installing-azure-account

### CODE REVIEW

**Comment by codyhoag** [comment]
@e-tienne PTAL. Thanks!

**Review by e-tienne — COMMENTED** [review]
LGTM

**Comment by codyhoag** [comment]
@mgahagan73 can you confirm from a QE perspective? Thanks!

**Comment by codyhoag** [comment]
@mgahagan73 bump. Can you verify? Thanks!

**Comment by mgahagan73** [comment]
@codyhoag  LGTM

**Pull request merged**
