### PR TITLE
Pr11368

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/11368

@jiajliu PTAL

### CODE REVIEW

**Review by sdodson — APPROVED** [review]
lgtm

**Comment by kalexand-rh** [comment]
@jianlinliu, PTAL? 

This is a follow up to #11368 to fix the docs side of https://bugzilla.redhat.com/show_bug.cgi?id=1458018

**Comment by jianlinliu** [comment]
LGTM.

**Comment by kalexand-rh** [comment]
Thank you! Merging.

**Pull request merged**
