### PR TITLE
Do not use emphasis with code font even with dash or underscore

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/pull/22592

### CODE REVIEW

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

Thanks for doing these updates! It looks like there are a lot of file paths, etc. still using the `*_/file/path_*` syntax that we should clean up as well at some point.

**Comment by jboxman** [comment]
@bergerhoffer, I've noticed that as well.

**Pull request merged**
