### PR TITLE
Adding missing modules for GitOps 1.13

### PR DESCRIPTION
**Pull request by Dhruv-Soni11**
Version(s):

GitOps 1.13

Issue:

https://issues.redhat.com/browse/RHDEVDOCS-6110

Link to docs preview:

[1.11.5](https://78870--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-11-5_gitops-release-notes)

[1.11.4](https://78870--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-11-4_gitops-release-notes)

[1.10.6](https://78870--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-10-6_gitops-release-notes)

[1.10.5](https://78870--ocpdocs-pr.netlify.app/openshift-gitops/latest/release_notes/gitops-release-notes.html#release-notes-for-gitops-1-10-5_gitops-release-notes)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by Dhruv-Soni11** [comment]
@Srivaralakshmi - As discussed on Slack, kindly take a look at the missing modules in GitOps 1.13 release and merge it if everything looks fine. Thank you :)

**Review by Srivaralakshmi — COMMENTED** [review]
@Dhruv-Soni11 LGTM. Thanks!

**Comment by Srivaralakshmi** [comment]
@Dhruv-Soni11 Please update the version field in the PR description field. Also, request for the merge and ping me. Thanks!

**Pull request merged**
