### PR TITLE
Added Build Run Policy section

### PR DESCRIPTION
**Pull request by ahardin-rh**
Continuation of work from https://github.com/openshift/openshift-docs/pull/1956

### CODE REVIEW

**Comment by ahardin-rh** [comment]
cc @bparees @mfojtik @php-coder

**Comment by bparees** [comment]
thanks @ahardin-rh!

**Comment by ahardin-rh** [comment]
@bparees you're very welcome!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/builds.adoc#dev-guide-builds[Builds]
|Added a xref:../dev_guide/builds.adoc#build-run-policy[Build Run Policy] section.
%

**Pull request merged**
