### PR TITLE
[SRVCOM-1874] Update pingsource API version and data spec

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.6+
OSD

Issue:
https://issues.redhat.com/browse/SRVCOM-1874

Link to docs preview:
http://file.rdu.redhat.com/abrennan/010622/SRVCOM-1874/serverless/develop/serverless-pingsource.html#serverless-pingsource-yaml_serverless-pingsource

### CODE REVIEW

**Comment by lberk** [comment]
LGTM
Thanks @abrennan89!!

**Comment by mgencur** [comment]
LGTM

**Pull request merged**
