### PR TITLE
[OCPBUGS-32109]: Clarify availability of virtualization platform in HCP overview

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OCPBUGS-32109

Link to docs preview: https://77070--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/index.html#hosted-control-planes-overview_hcp-overview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by zanetworker** [comment]
lgtm!

**Review by zanetworker — APPROVED** [review]

**Review by gwynnemonahan — COMMENTED** [review]
LGTM

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
