### PR TITLE
Always include `name` in CNI configuration

### PR DESCRIPTION
**Pull request by jboxman**
- https://bugzilla.redhat.com/show_bug.cgi?id=1793418

@dougbtv, I think this addresses the problem of the missing `name` value.

### CODE REVIEW

**Comment by jboxman** [comment]
Hi @weliang1,

Do the changes in this PR address this issue?

Thanks!

**Comment by zhaozhanqi** [comment]
@weliang1 please help check this, thanks

**Comment by weliang1** [comment]
@jboxman 
Not see any updating in macvlan section, not sure if we need include the "name" for macvlan

**Comment by jboxman** [comment]
@weliang1, when configuring a macvlan attachment by using the CNO, the configuration is in YAML and includes the `name` field. The `name` field was missing for all the CNI plug-ins that are configured by using `rawCNIConfig` JSON.

```yaml
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  additionalNetworks: 
  - name: test-network-1
    namespace: test-1
    type: SimpleMacvlan
    simpleMacvlanConfig:
      ipamConfig:
        type: static
        staticIPAMConfig:
          addresses:
          - address: 10.1.1.0/24
```

https://docs.openshift.com/container-platform/4.4/networking/multiple_networks/configuring-macvlan.html#nw-multus-macvlan-object_configuring-macvlan

**Pull request merged**
