### PR TITLE
BZ2110339: Default inheritable capabilities for linux container should not be empty

### PR DESCRIPTION
**Pull request by tmulquee**
Version(s):
  * PR applies only to a specific single version (e.g. 4.10): 4.10

Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=2110339

Link to docs preview:
Link to docs preview: http://file.emea.redhat.com/tmulquee/BZ2110339/release_notes/ocp-4-10-release-notes.html#ocp-4-10-bug-fixes - at end of Nodes section, search for 2076265.

QE review:
- [ ] QE has approved this change.

Additional information:
The original PR this content was developed with was https://github.com/openshift/openshift-docs/pull/49995

### CODE REVIEW

**Comment by haircommander** [comment]
as a note, this does apply to all currently supported versions. we'll change the behavior in 4.12

/lgtm

**Comment by tmulquee** [comment]
Thanks Paul, for clarifying that. We go back to 4.7 on docs support.
Bear in mind: a Release Note is based off a particular enterprise branch, because Release Note content only appears in one version. They document features and issues that pertain to a new version of a new product. 
Our normal practice is  to announce something that is new in a specific release. It's not feasible to put this note into more than one Release Note - we would normally put it into the Release Note when that feature was released.
If we are updating all the versions, we need to find the topic where this Note is relevant.
Can you suggest a possible location?

**Comment by haircommander** [comment]
I am honestly not sure where the best place is

**Comment by tmulquee** [comment]
Peter, I've received the following guidance from the folks at editorial
level:

On Fri, Oct 7, 2022 at 6:36 PM Matt Werner ***@***.***> wrote:

> I think a good place to put a note about the workaround would be in this
> section on working with containers:
> https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/nodes/index#nodes-containers-using
>
>
> Thoughts?
>

What are your own thoughts on Matt's suggestion?
If we go this road, we're updating main with a Note and can then cherry
pick back through the applicable versions.
If we update a release note, we have to pick a specific release, as
our guidelines dictate that release notes are built on an enterprise branch
for that release. We can't make multiple duplicate entries to RNs for
several releases.
We could put in the info in the Known Issues section of the RN for
shortcomings like this, but it will only publicize the workaround to 4.10
users.
Let me know your thoughts, and we can meet for a huddle to discuss the
precise location in that area of the docs.
Best regards
/tonym

**Comment by haircommander** [comment]
I think the notes section makes sense. It's not applicable to 4.12 (we've dropped the inheritable capabilities again there), so the text between 4.12 and <4.11 would be different. We also could have a RN change to 4.12 and then a notes section change in <4.11

**Comment by tmulquee** [comment]
Peter, here's our proposed plan. Please let me know of any adjustment you
need to make to it.
We have a text signoff for the note. Item 2 will be a reword of the
workaround info, so I'll be asking you to review this too.

1. Provide a note for the workaround in the container / nodes section for
all releases prior to 4.12.
2. Update enterprise-4.12 with a release note in the Fixed Bugs section.
3. Update main branch on 4.12 to remove the workaround note from 4.12 and
all subsequent versions.


1. will require a number of PRs, our auto-cherry-picking only goes back to
4.9, after that we can do per release manual cherry-picking back as far as
4.6. Exactly how far back is the workaround applicable?
2. requires a PR for the release note for 4.12.
3. PR needed for 4.12 main.

Which indicates 4+ PRs to be signed off by you. Can you nominate a QE to
cross check the changes? I'll need /lgtms from both of you for all the PRs.
Our peer review squad is quite strict about that.
Thanks for your help in getting to this point.

/tonym

--

Tony Mulqueen

Senior Technical Writer

Red Hat EMEA <https://www.redhat.com/>

***@***.***    M: +353-8 <+353-86-8135554>7-9519778
<https://red.ht/sig>
I respect your work-life balance. There is no need to answer this email
outside of your office hours.

**Comment by haircommander** [comment]
I am ready to sign off on those PRs. @sunilcio are you or any of your teammates able to verify them as well?

**Pull request closed without merging**
