### PR TITLE
OSDOCS-9283: add admonition about overriding default worker pool configs

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.15+

Issue: https://issues.redhat.com/browse/OSDOCS-9283

Link to docs preview: https://70274--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/cluster-tasks#creating-infra-machines_post-install-cluster-tasks

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jldohmann** [comment]
@xueli181114 could you PTAL for QE ack? This PR adds a note about custom machine config pools overriding default worker pool configs. thank you 🙇 

CC: @cdoern

**Review by skrthomas — COMMENTED** [review]
/lgtm 🥳

**Pull request merged**
