### PR TITLE
Hybrid networking clarfications

### PR DESCRIPTION
**Pull request by codyhoag**
Preview: http://file.rdu.redhat.com/~choag/121820/hybrid-networking-clarifications/networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.html

### CODE REVIEW

**Review by christianh814 — COMMENTED** [review]
/lgtm

**Comment by codyhoag** [comment]
@christianh814 let me know what you think.

This is a counter-proposal to docs submitted in #28238

**Comment by codyhoag** [comment]
This is a simple structural improvement, so no QE review is required.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
