### PR TITLE
remove confusing sentence about containers in same pod behaving as if…

### PR DESCRIPTION
**Pull request by pwright**
remove confusing sentence about containers in same pod behaving as if on same host.

"The containers in a Pod are automatically co-located and co-scheduled on the same physical or virtual machine in the cluster." from https://kubernetes.io/docs/concepts/workloads/pods/ so there is no question about containers 'behaving' that way.

Version(s):

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@JoeAldinger, will you PTAL at this PR and help get it reviewed and merged?

**Comment by kalexand-rh** [comment]
@JoeAldinger, will you PTAL?

**Review by sheriff-rh — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
