### PR TITLE
[enterprise-4.3] Use same Distros for ExternalIP

### PR DESCRIPTION
**Pull request by jboxman**
@lamek, is this just for 4.3? I didn't notice this elsewhere.

Thanks.

### CODE REVIEW

**Comment by jboxman** [comment]
@lamek, ping?

**Comment by lamek** [comment]
@jboxman ARO content was originally added to the enterprise-4.3 branch only.

**Comment by lamek** [comment]
@jboxman was there a specific ask to add this to ARO? Right now we've got a separate networking guide in the Azure docs - https://docs.microsoft.com/en-us/azure/openshift/concepts-networking.

**Comment by jboxman** [comment]
@lamek, no, the reason I asked is, I had a cherry-pick conflict and it was the distro tag for this, so I thought maybe there's a reason 4.3 has distro tags for this in so many places. I didn't notice this distro tag for other versions, so I thought it might be important to include it if it matters here.

**Comment by jboxman** [comment]
@lamek, _ExternalIP_ is only useful for bare metal anyway, so I won't add it.

**Comment by lamek** [comment]
@jboxman sounds good.

@vikram-redhat I think I should just remove all openshift-aro tags from master. Do you see any issues with this?

**Pull request merged**
