### PR TITLE
OSDOCS#10138:Removing unsupported versions of OSSO and adding note ab…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…out no version available at GA

Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10138

Link to docs preview:

https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/index.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-configuring.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-uninstalling.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@ingvagabund @kasturinarra I realized that the existing OSSO versions are not going to be supported. This PR removes versions 1.2.0 and 1.2.1 and puts in a temporary note about the OSSO version for 4.16 coming soon.

Can you both PTAL?

Preview links:

https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/index.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-configuring.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.html
https://77126--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-uninstalling.html

**Comment by ingvagabund** [comment]
LGTM

**Pull request merged**
