### PR TITLE
[OSDOCS-11145] vSphere CPMS FD behavior clarification

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.15+

Issue:
[OSDOCS-11145](https://issues.redhat.com//browse/OSDOCS-11145)

Link to docs preview:
- [Sample VMware vSphere provider specification](https://78099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-vsphere.html#cpmso-yaml-provider-spec-vsphere_cpmso-config-options-vsphere)
- [Sample VMware vSphere failure domain configuration](https://78099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-vsphere.html#cpmso-yaml-failure-domain-vsphere_cpmso-config-options-vsphere)
- [Sample Azure provider specification](https://78099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure#cpmso-yaml-provider-spec-azure_cpmso-config-options-azure)
- [Sample Nutanix provider specification](https://78099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-nutanix#cpmso-yaml-provider-spec-nutanix_cpmso-config-options-nutanix)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
LGTM

**Review by maxwelldb — APPROVED** [review]

**Comment by jeana-redhat** [comment]
rebase/refresh for merge, no change

**Pull request merged**
