### PR TITLE
GH#21803 - Remove deprecated flag from `oc` command

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/21803

Needs QE.

### CODE REVIEW

**Comment by mffiedler** [comment]
The oc adm migrate storage example looks good.   --confirm is deprecated there.    For the second example it looks like reconcile-sccs is not an option for oc adm policy.   I tested on 3.11.306 (5-October) client and got this:

$ oc adm policy reconcile-sccs  
error: unknown command "reconcile-sccs"

./oc version
oc v3.11.306
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

@soltysh @stlaz Did the option get removed/moved?

**Comment by soltysh** [comment]
> @soltysh @stlaz Did the option get removed/moved?

with `oc v3.11.235` the command still exists there, and I wouldn't expect any such significant changes in the oc code between mine version and yours.

**Comment by jboxman** [comment]
@mffiedler @soltysh 

So this command exists in v3.11.232 and v3.11.306 in my testing.

```
~/Downloads/oc adm policy reconcile-sccs --help
Replace cluster SCCs to match the recommended bootstrap policy
...

oc adm policy reconcile-sccs --confirm -v=7
I1102 11:46:40.447135   24708 loader.go:359] Config loaded from file /Users/jasonb/.kube/config
I1102 11:46:40.447632   24708 round_trippers.go:415] GET https://api.crc.testing:6443/api/v1/namespaces/openshift-infra
I1102 11:46:40.447641   24708 round_trippers.go:422] Request Headers:
I1102 11:46:40.447645   24708 round_trippers.go:426]     Accept: application/json, */*
I1102 11:46:40.447648   24708 round_trippers.go:426]     User-Agent: oc/v1.11.0+d4cacc0 (darwin/amd64) kubernetes/d4cacc0
I1102 11:46:40.447653   24708 round_trippers.go:426]     Authorization: Bearer <masked>
...
```

And `confirm` is still an option listed in the help as well. So it looks like this instance of `confirm` is okay.

**Comment by mffiedler** [comment]
Something strange about my config then.  Maybe the mixed 4.x/3.x env.   @zhouying7780  should probably be the official reviewer in any case.

**Comment by jboxman** [comment]
@zhouying7780 ping; Can you help with this? Thanks!

**Pull request merged**
