### PR TITLE
TELCODOCS-860 RN: MGMT-10404 Use boot-artifacts API to fetch rootfs in minimal-iso (assisted-image-service)

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: [TELCODOCS-860 RN](https://issues.redhat.com/browse/TELCODOCS-860)

For: Version 4.11 

Doc Preview: https://49125--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-11-release-notes.html#ocp-4-11-scalability-and-performance

Signed-off-by: Katie Tothill ktothill@redhat.com

### CODE REVIEW

**Comment by ktothill** [comment]
Date and Time: August 15, 2022  16:33

Summary: Created [content](https://github.com/openshift/openshift-docs/pull/49123) and [RN](https://github.com/openshift/openshift-docs/pull/49125) PRs.

 

Next Steps: Requesting review from SME.

**Comment by ktothill** [comment]
@danielerez, could you please review the content and RN PRs? Any comments can be made directly in the PRs. If no changes are needed, please add an `lgtm` to each PR in Github. Thank you!

**Comment by ktothill** [comment]
@trewest, could you please review the content and RN PRs? Any comments can be made directly in the PRs. If no changes are needed, please add an `lgtm` to each PR in Github. Thank you!

**Comment by ktothill** [comment]
Date and Time: August 16, 2022  14:10
Summary: Received /lgtm from Daniel and Kerry. Requested Peer Review from Telco team. 

Next Steps: Implement feedback from Telco Peer Reviews and submit for OCP Review Squad feedback.

**Comment by ktothill** [comment]
Contact Method: Slack, [#forum-doc-review](https://coreos.slack.com/archives/C025XCRRH28/p1661446287635699)
Date and Time: August 25, 2022  12:51
Summary: Requested review from Peer Review Squad. 

Next Steps: Implement feedback from peer reviews and request merge.

**Review by opayne1 — COMMENTED** [review]
@ktothill Is this something that did not make in the release notes with 4.11 GA? If so, we will need to do change management to add that in.

If not, (which I think this is for ZTP that shipped after GA) we will need to work to add this into the appropriate z-stream which may or may not need CM depending on when this needs to merge. 

I can help with any questions you have on this. :)

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#forum-docs-review](https://coreos.slack.com/archives/C025XCRRH28/p1661533487936639?thread_ts=1661446287.635699&cid=C025XCRRH28)
**Date and Time:** August 26, 2022  13:23
**Summary:** Per the Peer Review Squad, RHACM 2.6 GAed on June 8th and that was a 4.10.z as 4.11 wasn't released yet. We may need to complete the Change Management process.

**Next Steps:** Need to confirm with Emily when she's back on Monday regarding the corresponding .z the content and RN were supposed to be in.

**Comment by ktothill** [comment]
**Contact Method:** Slack, [#forum-docs-review](https://coreos.slack.com/archives/C025XCRRH28/p1662992488128169)
**Date and Time:** September 12, 2022  10:22
**Summary:** Requested merge for content and RN.

**Next Steps:** Once PRs are merged, Jira can be closed.

**Comment by tradej** [comment]
This content should be added to the 4.11.3 RN section, not in the main RN.

**Comment by ktothill** [comment]
RN should have been placed in 4.11.3. See [PR 50328](https://github.com/openshift/openshift-docs/pull/50328) for correct location.

**Pull request merged**
