### PR TITLE
Follow up to #11541

### PR DESCRIPTION
**Pull request by vikram-redhat**
xref: #11541

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bparees - FYI. This should take care of everything we have in the email thread.

**Comment by bparees** [comment]
post hoc lgtm.

**Comment by vikram-redhat** [comment]
3.9: https://github.com/openshift/openshift-docs/pull/11714
3.10: https://github.com/openshift/openshift-docs/pull/11711
3.11: https://github.com/openshift/openshift-docs/pull/11713

**Pull request merged**
