### PR TITLE
CNV-40193: RN shell file 4.18

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s):
4.18

Issue:
[CNV-40193](https://issues.redhat.com/browse/CNV-40193)

Link to docs preview

QE review:
NA

Additional information:
```
Updated release notes file name and anchor IDs
Removed New and changed features content
Removed Bug fixes content
Removed Removed features content
Removed tech preview content
```

### CODE REVIEW

**Review by aspauldi — COMMENTED** [review]
This looks good!  I wanted to mention (and you probably already know this) that the version number in virt-supported-cluster-version.adoc (the include in line 29) will automatically update when we change the {product-version} closer to the GA. Also, we tag our OpenShift Virtualization PRs with /label cnv; I added that to this PR.

**Comment by adellape** [comment]
@MirzWeiss Looks good, just a (non-blocking) question: You mentioned in the description "Removed Bug fixes content", but I did notice a few bug fixes still hanging out in some of the subsections of https://84792--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/release_notes/virt-4-18-release-notes.html#virt-4-18-bug-fixes and wasn't sure if that was intentional or not. But if they still need to be removed, can be a follow-up PR.

**Pull request merged**
