### PR TITLE
OSDOCS-12282: Follow-up to OSD-25873/OSDOCS-12177

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Version(s): `enterprise-4.17`+

Issue: https://issues.redhat.com/browse/OSDOCS-12282

Link to docs preview:
- https://83190--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/aws-ccs.html
- https://83190--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.html
- https://83190--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_planning/rosa-sts-aws-prereqs.html

QE review:
- [ ] ~~QE has approved this change.~~

Additional information: This corrects a mistake introduced in [OSDOCS-12177](https://issues.redhat.com//browse/OSDOCS-12177).

### CODE REVIEW

**Comment by michaelryanmcneill** [comment]
Confirmed @laubai that this should apply to ROSA Classic and HCP, as well as OSD. Sorry for the confusion.

**Comment by laubai** [comment]
Correcting previous comment: this change is valid for ROSA Classic and HCP, and also OSD, so LGTM.

**Comment by gaurav-nelson** [comment]
LGTM

**Pull request merged**
