### PR TITLE
OSDOCS-3418: RN for liveness, readiness, and startup probe config

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):
4.11 RN

Issue:
Feature PR: https://github.com/openshift/openshift-docs/pull/43824#issuecomment-1125749329
Jira: https://issues.redhat.com/browse/NE-683

Link to docs preview:
RN link will resolve once feature PR is merged.

### CODE REVIEW

**Comment by skrthomas** [comment]
@ShudiLi can you PTAL at this RN for the liveness, readiness, and startup probes?

**Comment by ahardin-rh** [comment]
@ShudiLi PTAL. Thank you!

**Comment by ShudiLi** [comment]
/label qe-approved
@ahardin-rh thanks!

**Comment by ahardin-rh** [comment]
Thank you!

**Pull request merged**
