### PR TITLE
[enterprise-4.14]TELCODOCS-1916: Moving under scalability and performance section

### PR DESCRIPTION
**Pull request by rohennes**
[TELCODOCS-1916](https://issues.redhat.com//browse/TELCODOCS-1916): This content was added as a top level assembly. However, it should be in the scalability and performance assembly. No content changes - just moving the files and adjusting xref paths accordingly. 

Version(s):
4.14

Issue:
https://issues.redhat.com/browse/TELCODOCS-1916

Link to docs preview:
https://78427--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/telco_ref_design_specs/telco-ref-design-specs-overview

Additional information:
QE not required, just moving content as it was in the wrong place. This content is not in 4.16 or later yet, but it is published in 4.15 and 4.14, so that is why I am targeting the release branch. This is the 4.15 PR: #78459

### CODE REVIEW

**Review by kcarmichael08 — COMMENTED** [review]
Everything that you changed looks good! 

I did see a couple broken links when spot checking (not realizing I was spot checking files that you only renamed, and did not change the contents of). I will include the screenshots in case you want to fix these even though they're not in the scope of this PR.

Screenshot 2024-07-03 at 6 47 47 PM
Screenshot 2024-07-03 at 6 50 13 PM

**Comment by kcarmichael08** [comment]
Screenshot 2024-07-03 at 6 47 47 PM

**Comment by rohennes** [comment]
Fixed the links. Redirects are not needed for this move because this section was only published on July 2 so the traffic would be very low, if any.

**Pull request merged**
