### PR TITLE
Bug 1319884, updated 'oc describe clusterPolicy default' output

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1319884

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape PTAL. Thanks!

**Comment by ahardin-rh** [comment]
@bfallonf @tnguyen-rh @tpoitras PTAL as well. Thanks!

**Comment by tnguyen-rh** [comment]
@ahardin-rh It looks like the change replacing one chunk of captured output w/ another.  As such, LGTM.

**Comment by ahardin-rh** [comment]
@adellape I made a small addition per our conversation. PTAL and let me know if this is what you had in mind.

**Comment by ahardin-rh** [comment]
@adellape moved my pointer to Evaluating Authorization up in the docs (before the output) and made it a NOTE box.

**Comment by ahardin-rh** [comment]
[rev_history]
|link:../admin_guide/manage_authorization_policy.html[Managing Authorization Policies]
|Updated the `oc describe clusterPolicy default` output to include the new *deletecollection* verb and added a NOTE box with a pointer to the verb list in the link:../architecture/additional_concepts/authorization.html#evaluating-authorization[Evaluating Authorization] section.
%

**Pull request merged**
