### PR TITLE
[OSDOCS-3506] GA HW offload for ShiftStack

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.11+

Issue: [OSDOCS-3506](https://issues.redhat.com//browse/OSDOCS-3506)

Link to docs preview: 
- http://file.rdu.redhat.com/~mbridges/12JUL2022/hw-offload/post_installation_configuration/network-configuration.html#nw-osp-hardware-offload-attaching-network_post-install-network-configuration
- http://file.rdu.redhat.com/~mbridges/12JUL2022/hw-offload/networking/hardware_networks/configuring-hardware-offloading.html#nw-sriov-hwol-ref-openstack-sriov-policy_configuring-hardware-offloading

Preview last updated: Tue Jul 26 03:00:46 PM UTC 2022

TODOs:

- [x] Harmonize with existing HW offloading content
- [x] Rectify w/#46276

### CODE REVIEW

**Comment by maxwelldb** [comment]
FYI @EmilienM

**Comment by maxwelldb** [comment]
QE review in Jira item.

**Comment by ahardin-rh** [comment]
LGTM! Just needs a squash. :rocket:

**Pull request merged**
