### PR TITLE
Updates the table to remove that Manila CSI supports clone and resize

### LINKED ISSUE #37606: BZ1944598: Manila CSI Driver should remove the support clone and resize
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi
From OCP4.6

### What needs fixing?
Manila CSI Driver did not support clone and resize, please remove them in the Table 1. Supported CSI drivers and features in OpenShift Container Platform

https://bugzilla.redhat.com/show_bug.cgi?id=1944598

### PR DESCRIPTION
**Pull request by stevsmit**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1944598
GH Issue: https://github.com/openshift/openshift-docs/issues/37606

Preview: https://deploy-preview-37707--osdocs.netlify.app/openshift-enterprise/latest/storage/container_storage_interface/persistent-storage-csi.html#csi-drivers-supported_persistent-storage-csi

Applies to 4.6+

@duanwei33 please review.

### CODE REVIEW

**Comment by duanwei33** [comment]
@stevsmit Thanks for the update, it looks good to me.
And it should be updated in all 4.6+ releases.

**Comment by duanwei33** [comment]
@stevsmit Thanks for the update, it looks good to me.
And it should be updated in all 4.6+ releases.

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
