### PR TITLE
ECOPORJECT-201: Documentation for the Poison Pill Operator for 4.10

### PR DESCRIPTION
**Pull request by abhatt-rh**
https://issues.redhat.com/browse/TELCODOCS-451 Documentation for the Poison Pill Operator for 4.10

Applies to OpenShift version : 4.10 +

Preview:
[Understanding the Poison Pill Remediation Template configuration](https://deploy-preview-42794--osdocs.netlify.app/openshift-enterprise/latest/nodes/nodes/eco-poison-pill-operator.html#understanding-poison-pill-remediation-template-config_poison-pill-operator-remediate-nodes)

### CODE REVIEW

**Comment by abhatt-rh** [comment]
Hi @mshitrit and @prabinovRedhat 
Kindly review the documentation for for Poison Pill 4.10. (I have incorporated the changes that we discussed in the Gdoc).
Thank you!

**Review by lpettyjo — COMMENTED** [review]
LGTM

**Pull request merged**
