### PR TITLE
Fix indentation in example pod spec for ConfigMaps

### PR DESCRIPTION
**Pull request by nilsding**
Just a small indentation fix (which I also confirmed to work).  Gave me a bit of a headache when I looked at this part of the docs and tried to make sense of the invalid yaml snippet there

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@mdshuai, will you PTAL?

**Comment by kalexand-rh** [comment]
@mdshuai, will you PTAL or suggest another reviewer?

**Comment by wjiangjay** [comment]
@nilsding @kalexand-rh LGTM

```
# cat pod.yaml          
apiVersion: v1                                               
kind: Pod                   
metadata:                                   
  name: dapi-test-pod               
spec:                 
  containers:                     
    - name: test-container            
      image: gcr.io/google_containers/busybox    
      command: [ "/bin/sh", "-c", "env" ]     
      env:                   
        - name: SPECIAL_LEVEL_KEY                                         
          valueFrom:                      
            configMapKeyRef:          
              name: special-config                                        
              key: special.how         
        - name: SPECIAL_TYPE_KEY       
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
              optional: true
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never
# oc create -f pod.yaml
pod "dapi-test-pod" created
# oc get pods
NAME                       READY     STATUS      RESTARTS   AGE
dapi-test-pod              0/1       Completed   0          6s
# oc logs dapi-test-pod |grep -i spe
SPECIAL_TYPE_KEY=charm
SPECIAL_LEVEL_KEY=very
# oc logs dapi-test-pod |grep -i log
log_level=INFO
```

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Pull request merged**
