### PR TITLE
modules/nodes-descheduler-profiles: Clarify RemovePodsHavingTooManyRestarts as sum

### PR DESCRIPTION
**Pull request by wking**
Pods don't restart, although they can be deleted and replaced with new pods.  Containers within pods restart.  Previously it was unclear whether the threshold was "one of my containers has more than 100 restarts" or "summing over all of my containers, there have been more than 100 restarts".  This commit makes it clear that it's the latter, based on [the backing code][1].  For example, a pod with three containers, each with 50 restarts, would be eligible for descheduling.

I'm also not super exited about the "removes pods" language, since as the docs point out elsewhere, some pods are not descheduled (e.g. pods in the `openshift-*` and `kube-system` namespaces).  I'd prefer language like "Considers pods whose containers...".  But that's orthogonal enough that I'm leaving it out for this commit.

[1]: https://github.com/kubernetes-sigs/descheduler/blob/bfd5feaf60a202cecafcf2d30cf171a138c04885/pkg/descheduler/strategies/toomanyrestarts.go#L110-L122

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/lgtm
from scheduling side

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by wking** [comment]
Looks like the text I'm touching [goes back to 4.7][1], and the descheduler behavior in this space has not changed, so this doc fix should go back to 4.7 too.

[1]: https://github.com/openshift/openshift-docs/commit/8ab366b70b5d3472bbc6e7a9a69f38be9c64c9a6

**Pull request merged**
