### PR TITLE
BZ-2111362: Fix audit logging annotation removal

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://bugzilla.redhat.com/show_bug.cgi?id=2111362

Version(s):

- 4.12
- 4.11
- 4.10

Issue:

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@huiran0826, can you confirm this small fix? Thanks!

**Review by bscott-rh — APPROVED** [review]
LGTM.

**Comment by jboxman-rh** [comment]
@bscott-rh thanks!

**Pull request merged**
