### PR TITLE
HCP updates for IBM Power

### PR DESCRIPTION
**Pull request by alishaIBM**
Version(s): 4.17+

Issue: https://issues.redhat.com/browse/OSDOCS-11100

Link to docs preview: https://83754--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-deploy/hcp-deploy-ibmpower.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by dharaneeshvrd — COMMENTED** [review]
@alishaIBM I have a comment on  --release-image param's explanation on 10th point, it's currently suggesting to use `4.14.0-x86_64`. But we have to mention that user should pass a multi arch image instead of any particular arch release image.
Sample latest 4.17 multi arch image will look like this `quay.io/openshift-release-dev/ocp-release:4.17.0-multi`
Can we please update this?

**Comment by lahinson** [comment]
@dharaneeshvrd I can update those docs to mention multi arch. Good catch.

**Review by lahinson — COMMENTED** [review]
lgtm

**Pull request merged**
