### PR TITLE
[OSDOCS-12826]: Adding link to HCP-specific ACM doc from OCP docs

### PR DESCRIPTION
**Pull request by lahinson**
Version(s): 4.17+

Issue: https://issues.redhat.com/browse/OSDOCS-12826

Link to docs preview: https://85733--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/index.html#hcp-acm-discover_hcp-overview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by zanetworker** [comment]
Can we add it so that it's more visible in the table of contents? 
image

**Comment by lahinson** [comment]
@zanetworker This is the closest I can do: https://85733--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/index.html#hcp-acm-discover_hcp-overview

It would be wonderful if I could simply mirror the doc from RHACM in the OCP docs, but alas, we don't have that capability yet.

**Comment by zanetworker** [comment]
LGTM, thanks Laura!

**Review by bscott-rh — APPROVED** [review]
Peer review LGTM.

**Pull request merged**
