### PR TITLE
GH#31508 - Fix Debian package extension typo

### LINKED ISSUE #31508: [enterprise-4.7] Issue in file operators/understanding/olm/olm-understanding-olm.adoc
### Which section(s) is the issue in?
Cluster service version
second paragraph

### What needs fixing?
"think of the packaging step for OLM as the stage at which you make your rpm, dep, or apk bundle."
should be instead:
"think of the packaging step for OLM as the stage at which you make your rpm, deb, or apk bundle."

### PR DESCRIPTION
**Pull request by pneedle-rh**
Applies to master, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7 and branch/enterprise-4.8.

This relates to https://github.com/openshift/openshift-docs/issues/31508.

### CODE REVIEW

**Comment by pneedle-rh** [comment]
@openshift/team-documentation for peer review please.

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Pull request merged**
