### PR TITLE
BZ1997540: replacing virt object maximum doc with KBase link

### PR DESCRIPTION
**Pull request by ousleyp**
- https://bugzilla.redhat.com/show_bug.cgi?id=1997540
- original PR: https://github.com/openshift/openshift-docs/pull/39886/
- The purpose of this PR is to replace the existing documentation with a link to a KBase article where the limits will be maintained in the future. I'm also making a few minor changes to the existing assembly.
- [Preview build](https://deploy-preview-40294--osdocs.netlify.app/openshift-enterprise/latest/virt/install/virt-planning-environment-object-maximums.html)
- enterprise-4.9 and 4.10 only, per Fabian

@djfjeff What do you think of the current wording here? Specifically: "In most cases, exceeding these numbers results in lower overall performance. It does not necessarily mean that the cluster will fail." This strikes me as problematic, support-wise, but it's how the doc was originally phrased (I just moved it into a new file). Thanks!

### CODE REVIEW

**Comment by fabiand** [comment]
>  Please also confirm that this change applies to 4.8, 4.9, and 4.10 (I am assuming so based on the title of the KBase). Thanks! :)

Yes, the KBase is version specific, and can therefor referenced by this PR

**Comment by fabiand** [comment]
Actually, let's please only apply it to 4.9 and 4.10

**Comment by djfjeff** [comment]
@ousleyp yes, this wording could be problematic. How about something like this :

"The values described in the document represent limits tested by Red Hat to ensure optimal performance of the cluster and workload. Exceeding these numbers might results in unexpected behaviour and impact the overall performance."

What do you think?

**Comment by ousleyp** [comment]
@djfjeff What do you think of this rewrite? "Red Hat has tested these values to ensure optimal cluster and workload performance. Exceeding the documented limits might result in unexpected behavior and degraded performance."

**Comment by ousleyp** [comment]
@kbidarkar Can you please take a look at this from the QE perspective? Thanks!

**Comment by djfjeff** [comment]
@ousleyp This looks perfect!

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by kbidarkar** [comment]
LGTM

**Pull request merged**
