### PR TITLE
[OSDOCS-11921] Add PSC info to WIF OCM UI steps (Immediate POST GA)

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.17+
Issue:

https://issues.redhat.com/browse/OSDOCS-11921
Link to docs preview:

https://84914--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster-with-workload-identity-federation.html#create-wif-cluster-ocm_osd-creating-a-cluster-on-gcp-with-workload-identity-federation
QE review:
- [ ] QE has approved this change.

QE review NA. This is duplicate (with WIF consideration) of existing docs (specifically, the other creating an OSD cluster on GCP)   
Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
peer review approved/SME reviewed for this PR which includes duplicate info https://github.com/openshift/openshift-docs/pull/76600

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
