### PR TITLE
[WIP] [DO NOT MERGE] RHDEVDOCS-5552: Document ArgoCD CRD upgrade from v1alpha1 to v1beta1

### PR DESCRIPTION
**Pull request by eromanova97**
**For GitOps version 1.10**
Please **DO NOT** merge this issue. The intention is to keep the **PRs merge ready with all approvals**. The PR merging can happen only on the GA date (September 26th). So please hold off merging until I let you know. thank you!

• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.12 and later
• **JIRA issue**: [RHDEVDOCS-5552](https://issues.redhat.com/browse/RHDEVDOCS-5552)
• **Preview pages**: 
- [Enabling replicas for Argo CD server and repo server](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/setting-up-argocd-instance#gitops-enable-replicas-for-argo-cd-server_setting-up-argocd-instance)
- [Enabling notifications with Argo CD instance](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/argo-cd-custom-resource-properties#gitops-argo-cd-notification_argo-cd-custom-resource-properties)
- [Configuring secure communication with Redis](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-secure-communication-with-redis)
- [Enabling the Dex OpenShift OAuth Connector](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-sso-on-argo-cd-using-dex#gitops-creating-a-new-client-in-dex_configuring-sso-for-argo-cd-using-dex)
- [Configuring SSO for Argo CD using Keycloak](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-sso-for-argo-cd-using-keycloak)
- [Configuring workloads with resource requests and limits](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-resource-quota#configuring-workloads_configuring-resource-quota)
- [Monitoring Argo CD custom resource workloads](https://63781--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/monitoring-argo-cd-custom-resource-workloads)

• **SME Review**: Completed by @iam-veeramalla, @svghadi 
• **QE review**: Completed by @varshab1210 
• **Peer-review**: Completed by @Srivaralakshmi

### CODE REVIEW

**Comment by ekristova** [comment]
Hello @iam-veeramalla @varshab1210 PTAL and provide feedback. Thank you!

**Comment by varshab1210** [comment]
LGTM
cc: @svghadi

**Comment by iam-veeramalla** [comment]
LGTM

**Review by svghadi — APPROVED** [review]
lgtm
Thank You @ekristova

**Review by Srivaralakshmi — APPROVED** [review]
@ekristova Approved!

**Comment by ekristova** [comment]
Please **DO NOT** merge this issue. The intention is to keep the **PRs merge ready with all approvals**. The PR merging can happen only on the GA date (September 26th). So please hold off merging until I let you know. thank you!

**Comment by mburke5678** [comment]
merge review /lgtm

**Pull request closed without merging**
