### PR TITLE
TELCODOCS-1738 RN 4.16 Known Issues 

### PR DESCRIPTION
**Pull request by slovern**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/TELCODOCS-1738

Link to docs preview: https://77582--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes.html#ocp-4-16-known-issues_release-notes

QE review:
- [x] QE has approved this change.

QE approvals are as follows:
https://issues.redhat.com/browse/RHEL-9279 - @linuxquiao

Additional information:

### CODE REVIEW

**Comment by linuxqiao** [comment]
Issue RHEL-9279 Unresolved
/lgtm

**Review by xenolinux — COMMENTED** [review]
LGTM

I am not sure why but the preview link could not be opened for me. It might work for me after some time.

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by slovern** [comment]
thanks for the review @xenolinux

**Pull request merged**
