### PR TITLE
RHDEVDOCS-3953 Fix broken sentence

### PR DESCRIPTION
**Pull request by rolfedh**
Aligned team: Dev Tools
- For branches: 4.6+
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-3953
- Direct link to doc preview: https://deploy-preview-44260--osdocs.netlify.app/openshift-enterprise/latest/cicd/builds/build-strategies.html#builds-understanding-openshift-pipeline_build-strategies
- SME review completed by: @rupalibehera @piyush-garg 
- QE review: @ probably not needed
- Peer review completed by: @bmcelvee @sounix000 
- SME and two peer reviews complete, including the original author.

### CODE REVIEW

**Comment by bmcelvee** [comment]
LGTM! Thank you for fixing this!

**Review by rupalibehera — APPROVED** [review]

**Pull request merged**
