### PR TITLE
Add Central DB to Central services components

### PR DESCRIPTION
**Pull request by connorgorman**
Version(s):

Merge to rhacs-docs; cherry pick to rhacs-docs-4.0

Issue:

Link to docs preview:

https://58767--docspreview.netlify.app/openshift-acs/latest/architecture/acs-architecture.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by connorgorman** [comment]
@gaurav-nelson @kcarmichael08 please take a look. thanks!

**Comment by mburke5678** [comment]
@connorgorman Has this PR had any QE review yet?

**Comment by connorgorman** [comment]
@mburke5678 ACS does not have QE

**Comment by kcarmichael08** [comment]
Hi, I will usually note that in the body of the PR (that ACS has no QE) or just check the box for QE since an SME (Connor) has signed off on it. :)

**Comment by kcarmichael08** [comment]
> Version(s):
> 
> Merge for ACS 4.0
> 
> Issue:
> 
> Link to docs preview:
> 
> [58767--docspreview.netlify.app/openshift-acs/latest/architecture/acs-architecture.html](https://58767--docspreview.netlify.app/openshift-acs/latest/architecture/acs-architecture.html)
> 
> QE review:
> 
> * [ ]  QE has approved this change.
> 
> Additional information:

Also for versions - Merge to `rhacs-docs`; cherry pick to `rhacs-docs-4.0`

**Pull request merged**
