### PR TITLE
OSDOCS-9896: hardcoded 4.16 version number bump

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.16+

Issue:
https://issues.redhat.com/browse/OSDOCS-9896

Link to docs preview:
In progress

QE review:
This PR bumps hard coded version numbers; no SME/QE review required.

Additional information:
Touches a lot of distributions and associated projects.

### CODE REVIEW

**Review by maxwelldb — APPROVED** [review]
Looks like a version bump! I spot checked a few things; seems copacetic to me.

**Comment by sheriff-rh** [comment]
Fetched/rebased references; resolved conflicts. Merging to 4.16+.

**Pull request merged**
