### PR TITLE
OCPBUGS-31413: Remove mention of PtpConfigSlaveCvl.yaml from docs

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.16, 4.17., 4.18

Issue: https://issues.redhat.com/browse/OCPBUGS-31413

Link to docs preview:

- https://85629--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/policygenerator_for_ztp/ztp-advanced-policygenerator-config#ztp-configuring-ptp-fast-events_ztp-advanced-policygenerator-config
- https://85629--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/policygentemplate_for_ztp/ztp-advanced-policy-config#ztp-configuring-ptp-fast-events_ztp-advanced-policy-config

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]
/lgtm

**Review by bscott-rh — APPROVED** [review]
Peer review LGTM.

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM!

**Pull request merged**
