### PR TITLE
OSDOCS-333: Fixed ASB operator name and removed community warning

### PR DESCRIPTION
**Pull request by bergerhoffer**
@openshift/team-documentation For peer review please.

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@shawn-hurley I removed the community warnings and changed the name as you said the downstream operator would be named. Can you double check that this is right? Thanks!

Preview: http://file.rdu.redhat.com/~ahoffer/2019/OSDOCS-333/applications/service_brokers/installing-ansible-service-broker.html

**Comment by mburke5678** [comment]
@bergerhoffer LGTM from a writing sense. I do not see Openshift Ansible Service Broker in the OperatorHub to verify steps.

**Review by shawn-hurley — APPROVED** [review]
LGTM

**Comment by zihantang-rh** [comment]
@bergerhoffer in some sections, like this: http://file.rdu.redhat.com/~ahoffer/2019/OSDOCS-333/applications/service_brokers/installing-ansible-service-broker.html#sb-install-asb-operator_sb-installing-asb
some named as `OpenShift Ansible Service Broker Operator` , most are still named as `OpenShift Ansible Broker Operator` ,
`OpenShift Ansible Broker`  also should be `OpenShift Ansible Service Broker`.

**Comment by bergerhoffer** [comment]
Thanks @zihantang-rh, I've updated those last few instances.

Merging.

**Pull request merged**
