### PR TITLE
[RHDEVDOCS-3114] Helm chart side panel updates

### PR DESCRIPTION
**Pull request by rishumehra**
**Purpose**:

- Update regarding additional meta-data to Helm Charts

**PR information**:

- Aligned team: DevConsole
- For branches: OpenShift 4.9
- JIRA: https://issues.redhat.com/browse/RHDEVDOCS-3114
- Direct link to doc preview: https://deploy-preview-39406--osdocs.netlify.app/openshift-enterprise/latest/applications/working_with_helm_charts/configuring-custom-helm-chart-repositories
- SME Review: @rohitkrai03 
- QE Review: @karthikjeeyar 
- Peer Review: @Srivaralakshmi

### CODE REVIEW

**Review by Srivaralakshmi — CHANGES_REQUESTED** [review]
@rishumehra Nice work! LGTM :)

**Comment by rishumehra** [comment]
> @rishumehra Suggestion: Please include the doc file where the image change is required. In the image captured, can you try to cover the Documentation N/A area completely - in the left panel of the Helm Chart?
> 
> Thanks!

Done

**Review by rohitkrai03 — COMMENTED** [review]
/lgtm

**Pull request merged**
