### PR TITLE
Add oc create route subcommands docs

### PR DESCRIPTION
**Pull request by 0xmichalis**
Origin PR: https://github.com/openshift/origin/pull/6819

### CODE REVIEW

**Comment by thesteve0** [comment]
Can you put in some doc on where to start to learn more about TLS certs and different types of termination. For myself, I would know I want to add an SSL cert but I wouldn't be sure what kind of termination type I would want and how this would be different from just giving a cert to my hosting provider for SSL.  You don't have to explain it all - just a link to a good source on the basics and what the terms mean.
Thanks!

**Comment by kargakis** [comment]
@thesteve0 we already have docs about [generating certificates](https://docs.openshift.org/latest/install_config/install/deploy_router.html#using-secured-routes) and the [termination types](https://docs.openshift.org/latest/architecture/core_concepts/routes.html#secured-routes) we support. Aren't these enough?

**Comment by adellape** [comment]
@kargakis I see https://github.com/openshift/origin/pull/6056 was closed today. Should this docs PR get closed as well, or just hold off for now?

**Comment by kargakis** [comment]
No, let's leave this open and once `oc create route` and its relatives are in master (WIP plus waiting on the rebase to land) I will update this PR.

**Comment by kargakis** [comment]
Newest Origin PR: https://github.com/openshift/origin/pull/6819

**Comment by kargakis** [comment]
@adellape PTAL

**Comment by adellape** [comment]
LGTM.

Note to cherry-picker: will follow-up with another PR for style edits and split the dev_guide topic changes into a separate commit (and will label that PR w/ dedicated-3.1 as well).

**Pull request merged**
