### PR TITLE
Bug 1394185, Removed repetitive step

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1394185

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@adellape PTAL :octocat:

**Comment by adellape** [comment]
:+1: FYI @sdodson on removing this dupe step.

**Review by sdodson — APPROVED** [review]

**Comment by ahardin-rh** [comment]
Verified by QE in the BZ

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/upgrading/manual_upgrades.adoc#install-config-upgrading-manual-upgrades[Upgrading a Cluster -> Performing Manual In-place Cluster Upgrades]
|Removed a repetitive step within the xref:../install_config/upgrading/manual_upgrades.adoc#updating-the-default-image-streams-and-templates[Updating the Default Image Streams and Templates] section.
%

**Pull request merged**
