### PR TITLE
OSDOCS-1819: Noting control plane pods require root permissions

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-1819

Preview: https://deploy-preview-30273--osdocs.netlify.app/openshift-enterprise/latest/architecture/control-plane.html#defining-masters_control-plane

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@soltysh @deads2k This is the doc update per my question the other week on the installer/revision-pruner pods needing to be run as root. Can you please review and make sure this looks okay?

Preview: https://deploy-preview-30273--osdocs.netlify.app/openshift-enterprise/latest/architecture/control-plane.html#defining-masters_control-plane

**Review by pneedle-rh — COMMENTED** [review]
@bergerhoffer aside from one small suggestion, this looks good to me!

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by bergerhoffer** [comment]
@xingxingxia Can you please QE review (or help me find who would be best to review) this update? Thanks!

Preview: https://deploy-preview-30273--osdocs.netlify.app/openshift-enterprise/latest/architecture/control-plane.html#defining-masters_control-plane

**Comment by xingxingxia** [comment]
LGTM

**Pull request merged**
