### PR TITLE
OSDOCS-945: Updating references to oc flags that were removed

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-945

### CODE REVIEW

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
Hi @soltysh, can you double check these updates for the oc flags that were removed for 4.5? Thanks!

**Comment by bergerhoffer** [comment]
@zhouying7780 Can you please review these updates as well? Thanks!

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
