### PR TITLE
OCPBUGS#4332 Service Usage API is required, not optional

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.11 and 4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-4332

Link to docs preview:
https://53342--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-account.html#installation-gcp-enabling-api-services_installing-gcp-account

QE review:
- [X] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@gpei @r4f4 Please take a look at this docs update for https://issues.redhat.com//browse/OCPBUGS-4325. Thank you

**Review by Wiharris — COMMENTED** [review]
The backticks do not appear to be showing in the preview build. Otherwise, LGTM! 

image

**Comment by gpei** [comment]
@jianli-wei could you please help to take a look at this?

**Comment by bscott-rh** [comment]
> The backticks do not appear to be showing in the preview build. Otherwise, LGTM!
> 
> image

Hi Will, that's expected behavior as the backticks are putting the URL in monospace formatting. Thanks

**Review by jldohmann — APPROVED** [review]
LGTM

**Pull request merged**
