### PR TITLE
Fix bz1717258 ( Unify versions )

### PR DESCRIPTION
**Pull request by liangxia**
https://bugzilla.redhat.com/show_bug.cgi?id=1717258

Applies to enterprise-4.1 and above.

@openshift/team-documentation

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bergerhoffer @kalexand-rh PTAL.

**Comment by kalexand-rh** [comment]
This LGTM. Thank you @liangxia! 

@jboxman, FYI 

I'm going to go ahead and merge so the next build will pick it up.

**Pull request merged**
