### PR TITLE
 [enterprise-4.16]OSDOCS#10235: Add hosted control planes known issues

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.16

Issue: https://issues.redhat.com/browse/OSDOCS-10235

Link to docs preview: https://73977--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-16-release-notes#ocp-4-16-known-issues

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jparrill — COMMENTED** [review]
/lgtm

**Comment by xenolinux** [comment]
This PR needs to be closed in favor of https://issues.redhat.com/browse/ACM-11225
Context: These workarounds are actually steps that need to be documented in HCP sections in ACM.

**Pull request closed without merging**
