### PR TITLE
OSDOCS-3606: Add IPv6 family first bare metal support

### PR DESCRIPTION
**Pull request by jboxman-rh**
- https://issues.redhat.com/browse/OSDOCS-3606

Adds support for IPv6 primary dual stack for bare metal, and IPv4/IPv6 dual stack for vSphere.

Version(s): 4.13

Issue:

Link to docs preview:

- [vSphere: Network configuration parameters](https://57903--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html#installation-configuration-parameters-network_installing-vsphere-installer-provisioned-network-customizations)
- [IPI bare metal: Optional: Deploying with dual-stack networking](https://57903--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#modifying-install-config-for-dual-stack-network_ipi-install-installation-workflow)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@cybertron, this updates the documentation for bare metal IPv6 and vSphere dual stack support at installation time.

**Comment by sgoveas** [comment]
'IPI bare metal: Optional: Deploying with dual-stack networking' section looks good to me

**Comment by jboxman-rh** [comment]
@sgoveas, thanks!

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
@jboxman-rh I'm happy to report that my report is LGTM. :+1:

**Comment by jboxman-rh** [comment]
@GroceryBoyJr, thanks!

**Pull request merged**
