### PR TITLE
Fix 'contrib' directory in images and mention .sti/environment

### PR DESCRIPTION
**Pull request by mfojtik**
PR: https://github.com/openshift/source-to-image/pull/145
Trello: https://trello.com/c/NNu5gzT9/499-3-v2-marker-file-replacement-build-codefreeze
Origin support: https://github.com/openshift/origin/pull/1138

### CODE REVIEW

**Comment by mfojtik** [comment]
@jhadvig @soltysh @bparees PTAL

**Comment by jhadvig** [comment]
LGTM :+1:

**Comment by soltysh** [comment]
LGTM

**Comment by bparees** [comment]
@adellape @CowboysFan please review/merge.

**Comment by adellape** [comment]
@mfojtik Sorry, can you rebase this?

**Comment by mfojtik** [comment]
@adellape done

**Pull request merged**
