### PR TITLE
[OSDOCS-5013]: GCP CPMS support (rel notes)

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.13

Issue:
[OCPCLOUD-1774](https://issues.redhat.com//browse/OCPCLOUD-1774) | [OSDOCS-5013](https://issues.redhat.com//browse/OSDOCS-5013)

Link to docs preview:
[Additional platform support for control plane machine sets
](https://56750--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-mapi-cpms-platform-support)
QE review:
- [ ] QE has approved this change.

Additional information:
* Main docs: #56751
* Includes changes from #55409, will refresh after that PR is merged to show the true diff.

### CODE REVIEW

**Comment by jeana-redhat** [comment]
This is a pretty straightforward RN addition, just adds a new bullet on line 163 (the rest of the diff is GitHub parsing the format change). Requesting all reviews at once.

@odvarkadaniel @miyadav PTAL :pray: 

/label peer-review-needed

**Review by mjpytlak — COMMENTED** [review]
Peer review LGTM @jeana-redhat

**Comment by odvarkadaniel** [comment]
LGTM!

**Comment by miyadav** [comment]
LGTM , thanks

**Pull request merged**
