### PR TITLE
CNV-45185: Issue in file virt/virtual_machines/advanced_vm_management/virt-high-availability-for-vms.adoc

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-45185

CNV 4.12+
OCP 4.12+

Preview: https://81035--ocpdocs-pr.netlify.app/openshift-dedicated/latest/virt/virtual_machines/advanced_vm_management/virt-high-availability-for-vms.html

### CODE REVIEW

**Comment by stevsmit** [comment]
Commits need squashed.

**Comment by sbeskin-redhat** [comment]
@stevsmit  Done

**Pull request merged**
