### PR TITLE
[RHACS] ROX-19789: Build-time network policy tools GA doc updates

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.4

Issue:
https://issues.redhat.com/browse/ROX-19789

Link to docs preview:
https://71792--docspreview.netlify.app/openshift-acs/latest/operating/build-time-network-policy-tools

SME review:
- [x] SME has approved this change.

Additional information:
- Merge into `rhacs-docs` and cherry-pick to:
    - `rhacs-docs-4.4`

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]

**Review by Srivaralakshmi — COMMENTED** [review]
@agantony LGTM. Neat PR! Thank you!

As I am new to the peer review squad, I would ask @bmcelvee to give my review the go-ahead. Please wait until Brandi applies the peer-review-done label.

**Comment by bmcelvee** [comment]
LGTM!

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Pull request merged**
