### PR TITLE
OSDOCS-893: Adding release notes for etcd cluster operator

### PR DESCRIPTION
**Pull request by bergerhoffer**
https://issues.redhat.com/browse/OSDOCS-893

Preview: http://file.rdu.redhat.com/~ahoffer/2020/OSDOCS-893-rn/release_notes/ocp-4-4-release-notes.html#ocp-4-4-operators (internal)

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@codyhoag or @sheriff-rh Would you mind reviewing this addition to the release notes?

I also fixed a mismatched level heading that was throwing a warning when building - let me know if you have an objections to that.

**Review by codyhoag — APPROVED** [review]
LGTM!

I made that four-tiered section to keep it a level lower than the Unsupported and Deprecated sections that follow it. Alex already reached out to me about that section and proposing we update it, so I think your change makes sense. Better to avoid build errors! Thanks for submitting this!

**Comment by bergerhoffer** [comment]
Thanks @codyhoag. Yeah about the levels, you could always add a category heading for those general ones to be consistent if you really wanted those to be at the same level as the unsupported/deprecated ones.

Also, it looks like previous RN versions used the [discrete] tag above those headings so they don't show in the TOC, in case you guys wanted to add that for 4.4 too.

**Comment by codyhoag** [comment]
@bergerhoffer yeah, that `[discrete]` heading was going to be added in another PR. Feel free to add the `[discrete]` heading here. If not, we'll make sure it gets in there in a future PR.

**Comment by bergerhoffer** [comment]
Cool @codyhoag I went ahead and added it in just so we don't miss it. Thanks!

**Comment by bergerhoffer** [comment]
SME ack received, merging.

**Pull request merged**
