### PR TITLE
Simplify custom ingress certificate procedure

### PR DESCRIPTION
**Pull request by ironcladlou**
Use `oc patch` to simplify the procedure. Make the rollout note more
visible.

### CODE REVIEW

**Comment by Miciah** [comment]
What do you think of keeping the yaml source for illustrative purposes ("If you do an `oc get`, the resource definition should now look like this:")? If you grep for "should look", you can see other instances of the pattern of giving a command and then showing the yaml definition of the result.

**Comment by ironcladlou** [comment]
>What do you think of keeping the yaml source for illustrative purposes ("If you do an oc get, the resource definition should now look like this:")? If you grep for "should look", you can see other instances of the pattern of giving a command and then showing the yaml definition of the result.

Implemented in 6b4bd6636, PTAL

**Comment by bmcelvee** [comment]
@lihongan PTAL, thanks!

**Comment by lihongan** [comment]
LGTM - thanks

**Comment by bmcelvee** [comment]
Thanks!

@ironcladlou - would you mind squashing the two commits into one? Then I can merge. Thanks!

**Pull request merged**
