### PR TITLE
BZ2010739: Make correction to the Gt selector operator

### PR DESCRIPTION
**Pull request by lmandavi**
This PR is associated with https://bugzilla.redhat.com/show_bug.cgi?id=2010739. The selector operator was corrected as noted in the defect.

The Gt operator was changed to gt in this node example:
https://deploy-preview-38216--osdocs.netlify.app/openshift-enterprise/latest/virt/install/virt-specifying-nodes-for-virtualization-components.html#virt-example-node-placement-affinity-hyperconverged-cr_virt-specifying-nodes-for-virtualization-components

This PR applies to CNV 4.8 and 4.9 releases.

### CODE REVIEW

**Comment by ibesso-rh** [comment]
/lgtm

only a slight comment - i see a diff at the end:
https://github.com/openshift/openshift-docs/pull/38216/files#diff-ac25f56351f4cf17d21c00ace699f1b9836b93638a8492137850e02a9b01b40eL48-R48

although by the looks of it I did not see a diff between the updated page and the preview (also via page source).

**Comment by ibesso-rh** [comment]
@lmandavi , please see my comment about regarding the second diff.

**Comment by lmandavi** [comment]
Thanks for the verification @ibesso-rh. Noted your comment. Moving to peer review stage.

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Pull request merged**
