### PR TITLE
SRVOCF-366: Updates to docs on using functions with the default registry

### PR DESCRIPTION
**Pull request by rh-max**
For versions 4.6+
Jira: https://issues.redhat.com/browse/SRVOCF-366
Docs preview: https://deploy-preview-38796--osdocs.netlify.app/openshift-enterprise/latest/serverless/functions/serverless-functions-getting-started.html#serverless-functions-using-integrated-registry_serverless-functions-getting-started

### CODE REVIEW

**Comment by rh-max** [comment]
@jrangelramos Could you PTAL?

**Comment by jrangelramos** [comment]
LGTM
QE Approved

**Comment by rh-max** [comment]
Thanks @jrangelramos !

**Comment by sagidlow** [comment]
LGTM!

**Pull request merged**
