### PR TITLE
OSDOCS#CP-1892 - ROSA redirects to customer portal

### PR DESCRIPTION
**Pull request by unibrew**
This change handles redirects of ROSA documentation to customer portal.

Version(s): DNA

Issue: https://issues.redhat.com/browse/CP-1892

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by unibrew** [comment]
As for QA testing checkbox, there is no QA instance for docs so this change was tested only locally.

**Review by bscott-rh — APPROVED** [review]
LGTM.

**Comment by kalexand-rh** [comment]
@unibrew, please squash your commits so we can merge the change.

**Comment by unibrew** [comment]
squashed the commits

**Pull request merged**
