### PR TITLE
OSDOCS-4853: Add step to remove manifests for control plane machine set

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.13+

Issue:
This issue addresses [osdocs-4853](https://issues.redhat.com/browse/OSDOCS-4853)

Link to docs preview:

- (Azure) [Creating the Kubernetes manifest and Ignition config files](https://55061--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-user-infra) (step 3)
- (Azure Stack Hub) [Creating the Kubernetes manifest and Ignition config files](https://55061--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-stack-hub-user-infra) (step 3)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@rna-afk and @jinyunma Ready for SME and QE review. PTAL. Thank you.

**Comment by jinyunma** [comment]
seems missing the update in the doc [Installing a cluster on Azure Stack Hub using ARM templates](https://55061--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-stack-hub-user-infra) , which is UPI installation on azure stack hub.

**Comment by mjpytlak** [comment]
> seems missing the update in the doc [Installing a cluster on Azure Stack Hub using ARM templates](https://55061--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-stack-hub-user-infra) , which is UPI installation on azure stack hub.

@rna-afk Does your work also apply to Azure Stack Hub?

**Comment by rna-afk** [comment]
> @rna-afk Does your work also apply to Azure Stack Hub?
Yes, it should

**Comment by mjpytlak** [comment]
Thank you @rna-afk and @jinyunma I believe this should do it. Please take one more look. Thank you.

**Comment by aldiazRH** [comment]
Looks good to me! Someone else will check behind me too since I'm onboarding, but this is pretty straightforward.

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
