### PR TITLE
document new git noproxy field

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal.

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL. @bparees - is this for dedicated or online as well?

**Comment by bparees** [comment]
Anything running 3.4 and above.

Ben Parees | OpenShift

**Comment by bfallonf** [comment]
Thanks @bparees I don't think this needs a followup. I'll merge.

**Comment by bfallonf** [comment]
I don't think rev history is needed.

**Pull request merged**
