### PR TITLE
Slight changes to LoadBalancer OSD docs

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
@sheriff-rh Please review. These changes _only_ applied to OSDv4

**Comment by sheriff-rh** [comment]
No prob @wgordon17, LGTM. Merging.

**Comment by sheriff-rh** [comment]
/cherrypick-enterprise-4.4

**Comment by sheriff-rh** [comment]
/cherrypick-enterprise-4.3

**Pull request merged**
