### PR TITLE
OCPBUGS#4333 Sample install config file should not recommend None for capability set

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.11 and 4.12

Issue:
https://issues.redhat.com/browse/OCPBUGS-4333

Link to docs preview:
[Alibaba](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_alibaba/installing-alibaba-network-customizations.html#installation-alibaba-config-yaml_installing-alibaba-network-customizations)
[AWS](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-network-customizations.html#installation-aws-config-yaml_installing-aws-network-customizations)
[Azure](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-network-customizations.html#installation-azure-config-yaml_installing-azure-network-customizations)
[Azure Stack Hub](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.html#installation-azure-stack-hub-config-yaml_installing-azure-stack-hub-network-customizations)
[GCP](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_gcp/installing-gcp-network-customizations.html#installation-gcp-config-yaml_installing-gcp-network-customizations)
[IBM Cloud VPC](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.html#installation-ibm-cloud-config-yaml_installing-ibm-cloud-network-customizations)
[Bare metal](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-bare-metal-config-yaml_installing-bare-metal-network-customizations)
[Bare metal IPI](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configuring-the-install-config-file_ipi-install-installation-workflow)
[RHOSP](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-config-yaml_installing-openstack-installer-custom)
[RHOSP Kuryr](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-kuryr.html#installation-osp-kuryr-config-yaml_installing-openstack-installer-kuryr)
[RHV](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-example-install-config-yaml_installing-rhv-customizations)
[vSphere](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html#installation-installer-provisioned-vsphere-config-yaml_installing-vsphere-installer-provisioned-network-customizations)
[VMC](https://53345--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-vmc-network-customizations.html#installation-installer-provisioned-vsphere-config-yaml_installing-vmc-network-customizations)

QE review:
- [X] QE has approved this change.

Additional information:
Moving the sample yaml changes from https://github.com/openshift/openshift-docs/pull/52965 to this PR so they can be merged in the short term while the larger PR is in progress.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@gpei @jinyunma Hello, please take a look at this change removing the misleading `capabilities` stanza from the sample install-config files across all installation assemblies. Tagging you as you were the two who reviewed https://github.com/openshift/openshift-docs/pull/47209. Thank you

@bparees Following up on your PR https://github.com/openshift/openshift-docs/pull/52933. PTAL, thanks

**Comment by bparees** [comment]
lgtm

**Comment by jinyunma** [comment]
LGTM

**Comment by bscott-rh** [comment]
@jinyunma @gpei Thank you for reviewing. Can you please confirm that no additional QE is needed? This change does touch nearly all of the platforms but it's removing an optional parameter that results in default behavior when removed. I want to make sure that we don't need any additional review for this change. Thank you

**Comment by gpei** [comment]
@bscott-rh yeah, it looks good from QE side.

**Review by jldohmann — APPROVED** [review]
LGTM

**Comment by jldohmann** [comment]
@bscott-rh looks like the auto CP to 4.11 failed, so it'll need a manual CP to that branch

**Pull request merged**
