### PR TITLE
Bug 1588736 Added important box to cluster metrics for Kube rules

### PR DESCRIPTION
**Pull request by bfallonf**
For: https://bugzilla.redhat.com/show_bug.cgi?id=1588736

Will verify in the BZ

### CODE REVIEW

**Comment by bfallonf** [comment]
This should be ok for review.

PTAL @openshift/team-documentation

**Review by kalexand-rh — COMMENTED** [review]
I might move only: "metrics can be collected on only the default"
Otherwise, LGTM

**Comment by bfallonf** [comment]
Thanks @kalexand-rh . Done and merging.

**Comment by bfallonf** [comment]
Endless conflicts, but this is done.

Please never change anything ever again :sob:

**Pull request merged**
