### PR TITLE
OSSMDOC-289: Removing incorrect info in the removing operator topic

### PR DESCRIPTION
**Pull request by JStickler**
Removing incorrect information about additional actions performed by removing an Operator.

### CODE REVIEW

**Review by jmazzitelli — APPROVED** [review]
lgtm

**Review by neal-timpe — APPROVED** [review]

**Comment by JStickler** [comment]
Maistra QE (@tvieira, @yxun @gbaufake ) could one of you review please?

**Comment by tvieira** [comment]
checking it now. Sorry the delay @JStickler

**Review by tvieira — APPROVED** [review]
LGTM

**Comment by JStickler** [comment]
Closing, addressed in #31939

**Pull request closed without merging**
