### PR TITLE
GitHub issue 21433: Mention backward compatibility of single file etc…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…d backup

https://github.com/openshift/openshift-docs/issues/21433

Preview: http://file.rdu.redhat.com/~ahoffer/2020/github-21433/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html#dr-scenario-1-recover-master-hosts_dr-infrastructure-recovery

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@retroflexer Can you verify the wording of this note for the backward compatibility? Thanks!

**Comment by bergerhoffer** [comment]
Hi @geliu2016, can you please review this backward compatibility note? Thanks!

**Comment by lamek** [comment]
LGTM

**Comment by geliu2016** [comment]
LGTM， thanks

**Pull request merged**
