### PR TITLE
logging: manually import tags for deployment

### PR DESCRIPTION
**Pull request by sosiouxme**
Docs fix to bug 1338965
https://bugzilla.redhat.com/show_bug.cgi?id=1338965

This is an ugly workaround, but hopefully short-term.

### CODE REVIEW

**Comment by sosiouxme** [comment]
@ahardin-rh when you have a chance... this is really just needed for the enterprise 3.2 docs, though it's scoped so can go in origin too. Surprisingly I haven't heard of customers hitting this yet, but ops did.

**Comment by sosiouxme** [comment]
@ahardin-rh sorry, this is the one that's a priority.

**Comment by ahardin-rh** [comment]
@sosiouxme Looks good! Thanks!

**Comment by adellape** [comment]
[rev_history]
|link:../install_config/aggregate_logging.html[Aggregating Container Logs]
|Added an Important box on manually importing tags for deployment.
%

**Pull request merged**
