### PR TITLE
Fix vsphere docs 36

### PR DESCRIPTION
**Pull request by gnufied**

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@gnufied Looks like this is a duplicate of #5197

**Comment by gnufied** [comment]
@gaurav-nelson that was for master and this is for Openshift 3.6. I was thinking that master is already tracking Openshift 3.7 now..

**Comment by gaurav-nelson** [comment]
@gnufied We merge everything in `master` branch (origin docs) and then cherry-pick into other branches based on the labels. So I merged #5197 in `master` and cherry picked it in the `enterprise3.6` branch. The changes are already in the docs at [https://docs.openshift.com/container-platform/3.6/install_config/persistent_storage/persistent_storage_vsphere.html](https://docs.openshift.com/container-platform/3.6/install_config/persistent_storage/persistent_storage_vsphere.html). If this looks good can you please close this?

**Comment by gaurav-nelson** [comment]
Closing this one, already in docs.

**Pull request closed without merging**
