### PR TITLE
RHDEVDOCS-4513-change-image-format-of-monitoring-diagram-46-410

### PR DESCRIPTION
**Pull request by bburt-rh**
Summary: This PR changes the image format of the monitoring overview diagram from .svg to .png so that the image is not cut off on the RH Customer Portal web page. This version of the diagram includes the Grafana component, which was part of the monitoring stack in OCP 4.6-4.10.

QE and SME reviews are not required because no technical content has been changed.

- Aligned team: DevTools
- For branches: 4.6, 4.7, 4.8, 4.9, 4.10
- Jira: https://issues.redhat.com/browse/RHDEVDOCS-4513
- Direct link to doc preview (RH VPN access required): http://file.rdu.redhat.com/bburt/RHDEVDOCS-4513-change-image-format-of-monitoring-diagram-46-410/monitoring/monitoring-overview.html#understanding-the-monitoring-stack_monitoring-overview
- SME review: @ n/a
- QE review: @ n/a
- Peer review: @rolfedh

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]

**Comment by bburt-rh** [comment]
@kalexand-rh This is the PR I mentioned to you yesterday. It is ready to merge and CP to the branches listed in the description. Lmk if I'm good to proceed.

**Comment by kalexand-rh** [comment]
It's fine to use the bot to attempt to cherry-pick this to previous versions.

**Pull request merged**
