### PR TITLE
OSDOCS#5003: Updating list of supported AWS regions

### PR DESCRIPTION
**Pull request by mjpytlak**
Version(s):
4.11+

Issue:
This PR addresses [osdocs-5003](https://issues.redhat.com/browse/OSDOCS-5003).

Link to docs preview:

Supported AWS regions > [AWS public regions](https://56606--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-public_installing-aws-account)

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mjpytlak** [comment]
@yunjiang29 Ready for QE review. PTAL.

**Comment by yunjiang29** [comment]
@shaozha PTAL

**Pull request merged**
