### PR TITLE
OSDOCS#10760: Add machine config for hcp

### PR DESCRIPTION
**Pull request by xenolinux**
This PR adds:
- A new assembly for handling machine configurations for in hosted control planes. 
- Modules that are relevant to the newly added assembly.
- Deletes an outdated and unnecessary module: `debug-nodes-hcp.adoc`

Version(s): 4.14+

Issue: https://issues.redhat.com/browse/OSDOCS-10760

Link to docs preview: https://76759--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp-machine-config.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jeniferh** [comment]
LGTM, thanks

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
