### PR TITLE
OCPBUGS-30019#Correct links from OCP to ODF docs

### PR DESCRIPTION
**Pull request by lpettyjo**
**Changing OCP 4.13+ links to ODF 4.14**

Version(s): 4.13-4.15

Issue: https://issues.redhat.com/browse/OCPBUGS-30019

Link to docs preview: https://80596--ocpdocs-pr.netlify.app/openshift-enterprise/latest/post_installation_configuration/post-install-storage-configuration.html

QE review:
- [ ] QE has approved this change.

Additional information:

Replaces this PR https://github.com/openshift/openshift-docs/pull/72363, which only targeted the 4.14 branch.

**PTAL**: @kalexand-rh @sjhala-ccs @amulmule @tamireran @duanwei33

### CODE REVIEW

**Review by kalexand-rh — APPROVED** [review]
LGTM

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by duanwei33** [comment]
@lpettyjo Hi Lisa, I see it (using ODF 4.14) will merge into the master, but I think we need to update ODF version alined with OCP version, so we might need independent PR for different versions, and this should merge into 4.14 only.

**Comment by lpettyjo** [comment]
LGTM from [kash Mulmuley](https://github.com/amulmule) https://redhat-internal.slack.com/archives/D07H9S8PWMD/p1724210939510949

**Comment by lpettyjo** [comment]
LGTM from Eran Tamir https://redhat-internal.slack.com/archives/D07H9SJ8N0P/p1724220210942049

**Comment by lpettyjo** [comment]
> @lpettyjo Hi Lisa, I see it (using ODF 4.14) will merge into the master, but I think we need to update ODF version alined with OCP version, so we might need independent PR for different versions, and this should merge into 4.14 only.

@duanwei33 It looks like ODF 4.14 has been the correct version to link to since OCP 4.13+. The preview links all work. @kalexand-rh Does this make sense to you? There already was a PR pointed to 4.14, which I closed in order to do this change for all versions of OCP 4.13+.

**Comment by kalexand-rh** [comment]
@lpettyjo, I think that does make sense. If the version is the same, we can use the same PR.

**Comment by lpettyjo** [comment]
Checking with @tamireran about which versions of OCP should link to ODF:
OCP 4.13-4.15 -> ODF 4.14
OCP 4.16 -> ODF ?
OCP 4.17 -> ODF ?

**Comment by tamireran** [comment]
@lpettyjo ODF N always supports OCP N and OCP N+1.
ODF 4.12, ODF 4.13 support OCP 4.13
ODF 4.13, ODF 4.14 support OCP 4.14
ODF 4.14, ODF 4.15 support OCP 4.15
ODF 4.15, ODF 4.16 support OCP 4.16
ODF 4.16, ODF 4.17 support OCP 4.17
ODF 4.17, ODF 4.18 support OCP 4.18

**Comment by lpettyjo** [comment]
@tamireran OK. How do we want the linkage to work then? Have OCP link to the latest ODF that is supported? Is so...
OCP 4.13 -> ODF 4.13
OCP 4.14 -> ODF 4.14
OCP 4.15 -> ODF 4.15
OCP 4.16 -> ODF 4.16
OCP 4.17 -> ODF 4.17

**Comment by tamireran** [comment]
ODF is (up to) one month behind. Better use the N-1 and maybe add a comment that would reflect that once ODF with a matching release version is available, we recommend to use the matching version.

**Comment by lpettyjo** [comment]
Closing this PR to do individual PRs for each OCP release.

**Pull request closed without merging**
