### PR TITLE
Upgrading Clusters: Create a note about CNS earlier in the document

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1588524

The BZ asks to move a note. The request is to add a new note.

### CODE REVIEW

**Comment by mburke5678** [comment]
@thom-at-redhat PTAL

**Comment by mburke5678** [comment]
@jiajliu Can you please take a look at this PR? You have reviewed changes to this topic previously.

**Comment by mburke5678** [comment]
In BZ:
Thom Carlin 2018-08-23 10:25:24 EDT
Perfect for me...deferring approval to product QE

**Comment by mburke5678** [comment]
@jiajliu Can you please take a look at this PR? You have reviewed changes to this topic previously.

**Comment by mburke5678** [comment]
@prasanth-RH   Can you please take a look at this PR?

**Comment by mburke5678** [comment]
@prasanth-RH PTAL

cc @vikram-redhat

**Comment by mburke5678** [comment]
@prasanth-RH BUMP
I want to make sure the wording I have is correct:
_If your {product-title} cluster uses GlusterFS pods, you must perform the upgrade in multiple phases. _

@vikram-redhat

**Comment by vikram-redhat** [comment]
@mburke5678 go ahead and merge.

**Comment by mburke5678** [comment]
Merging to 3.7+, when the Special Considerations When Using Containerized GlusterFS section was added.

**Pull request merged**
