### PR TITLE
OSDOCS-2711 Information on project volume permission issues for Windows pods

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-2711

Preview: https://deploy-preview-37587--osdocs.netlify.app/openshift-enterprise/latest/nodes/containers/nodes-containers-projected-volumes.html#file-permission-handling-for-windows-pods_nodes-containers-projected-volumes

### CODE REVIEW

**Comment by codyhoag** [comment]
@aravindhp PTAL

**Review by aravindhp — COMMENTED** [review]
Thanks for working on this, @codyhoag 

/cc @deads2k

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by codyhoag** [comment]
@sgaoshang please verify from a QE perspective. Thanks!

**Comment by codyhoag** [comment]
This has been split up across several PRs (e.g., #38157, #37811, and #37061). Because of this, I'm closing this PR.

**Pull request closed without merging**
