### PR TITLE
TELCODOCS-321: remove docs about provisioningOSDownloadURL

### PR DESCRIPTION
**Pull request by zaneb**
Prior to 4.10, the provisioningOSDownloadURL of the Provisioning CR was
required for provisioning baremetal hosts. In clusters installed from
4.10 onwards, the default MachineSets use a custom install method in
ironic to write the CoreOS live image to disk, instead of requiring a
separate URL to a qcow image. Therefore, users should never need to set
this value; on older clusters it will already be set and on newer ones
it is not required.

Version(s):

Issue:

Link to docs preview:

Additional information:

### CODE REVIEW

**Comment by ktothill** [comment]
@zaneb Updated files as suggested. Updated files exist in [PR 42922](https://github.com/openshift/openshift-docs/pull/42922).

**Comment by ktothill** [comment]
This issue can be closed. See [PR 42922](https://github.com/openshift/openshift-docs/pull/42922).

**Comment by zaneb** [comment]
Fixed in #50271
/close

**Pull request closed without merging**
