### PR TITLE
Corrected indentation of collection section YAML

### PR DESCRIPTION
**Pull request by dhgautam99**
From:
~~~
  spec:
    collection:
    logs:
      type: "vector"
      vector: {}
~~~

To:
~~~
  spec:
    collection:
      logs:
        type: "vector"
        vector: {}
~~~

Version(s): 

4.10 , 4.11 , 4.12
Issue:

Link to docs preview:

https://docs.openshift.com/container-platform/4.10/logging/cluster-logging-loki.html#cluster-logging-vector-enable_cluster-logging-loki
QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by vimalk78** [comment]
Cc: @libander

**Review by libander — APPROVED** [review]
/lgtm

**Comment by rolfedh** [comment]
Treating this as QE-reviewed because @vimalk78 forwarded it to you, @libander.

**Comment by rolfedh** [comment]
@libander Cherry picking doesn't work because, I believe, the author might not have signed/configured their contribution correctly. 

See:
- https://stackoverflow.com/questions/43662048/getting-fatal-empty-ident-name-not-allowed-when-doing-git-commit-amend

**Pull request merged**
