### PR TITLE
Add example of external DB to external services doc

### PR DESCRIPTION
**Pull request by pmorie**
Added an example of an external DB after talking to @adellape

### CODE REVIEW

**Comment by adellape** [comment]
@pmorie https://github.com/openshift/openshift-docs/pull/196 was merged, so you can rebase here now.

**Comment by pmorie** [comment]
@adellape Cool, will rebase this afternoon

**Comment by pmorie** [comment]
@adellape PTAL

**Comment by adellape** [comment]
Awesome, thanks @pmorie!

**Comment by adellape** [comment]
FYI @bfallonf, as this PR was created in response to your question in https://github.com/openshift/openshift-docs/pull/168#issuecomment-75680244 and is related to your https://trello.com/c/r6ajV5Qd.

**Pull request merged**
