### PR TITLE
OSDOCS-7867: Update LICENSE to signify Red Hat, Inc. as copyright holder

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Version(s):

3.0+ 
4.0+

Issue:
[OSDOCS-7867](https://issues.redhat.com/browse/OSDOCS-7867)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@wgordon17, will you PTAL and confirm if this needs to be applied to other branches besides main?

**Comment by wgordon17** [comment]
I would _expect_ that this belonging in `main` should be sufficient. But I'm not aware of all the legal implications.

**Comment by kalexand-rh** [comment]
I'll see how far back I can cherrypick it, then. :ty:

**Comment by kalexand-rh** [comment]
@michaelryanmcneill, the bot disagrees with just about everything in our branching/Jira alignment. It's ok.

And this doesn't need QE.

**Comment by kalexand-rh** [comment]
@gaurav-nelson, @gabriel-rh, please cherry-pick this PR to your branches.

**Pull request merged**
