### PR TITLE
OCPBUGS#9123: Documented osServicePrincipal.json in installer docs

### PR DESCRIPTION
**Pull request by dfitzmau**
[OCPBUGS-9123](https://issues.redhat.com/browse/OCPBUGS-9123)

Version(s):
4.14, 4.13, 4.12, 4.11, and 4.10

Link to docs preview:
[Deploying a cluster](https://60120--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-default.html#installation-launching-installer_installing-azure-default)

QE review:
- [x] QE has approved this change.

Additional information:
[Slack request](https://redhat-internal.slack.com/archives/CCV9YF9PD/p1684506416473449)

### CODE REVIEW

**Comment by patrickdillon** [comment]
LGTM

**Comment by mgahagan73** [comment]
The Azure related bits look good  to me.

**Pull request merged**
