### PR TITLE
PR for SRVOCF-524: [DOC] Serverless section location on d.o.c

### PR DESCRIPTION
**Pull request by kaldesai**
**Affected versions for cherry-picking:** Openshift 4.10+

**Dedicated JIRA:** https://issues.redhat.com/browse/SRVOCF-524?src=confmacro

**Description:**  In `_topic_map.yml`, changed the location of the **Serverless** section. It is now present under the **Building application** section. 

**Doc preview:** 
NOTE: I was unable to provide a build preview and Netlify preview is also not generating so I have attached the screenshot of my local build preview. (You can see that Serverless is now present under Building applications.)
image

### CODE REVIEW

**Comment by ekristova** [comment]
LGTM

**Review by eromanova97 — APPROVED** [review]

**Comment by stevsmit** [comment]
I built this locally and it does build under "Building Applications." I believe that the content and PR itself are ready for review, however I cannot merge this until the commits are squashed. cc @kaldesai

**Comment by kaldesai** [comment]
> I built this locally and it does build under "Building Applications." I believe that the content and PR itself are ready for review, however I cannot merge this until the commits are squashed. cc @kaldesai

@stevsmit I will squash the commits and let you know. Thank you!

**Comment by kaldesai** [comment]
@stevsmit I have squashed the commits. Can you please merge this PR? Thank you!

**Comment by Preeticp** [comment]
Hey @stevsmit do we need another round of merge review or are we OK to merge this? Just wondering if the label needs to be updated to Ok to merge? Also merging this will help us close a humongous epic. Thank you!

**Pull request merged**
