### PR TITLE
clarify image-pusher role

### LINKED ISSUE #17341: Role system:image-pusher does not allow to push images.
The clusterrole system:image-pusher does NOT allow to push images.

##### Version
oc version
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lb.karmalabs.local:8443
openshift v3.6.173.0.49
kubernetes v1.6.1+5115d708d7

In OCP 3.5 does not work neither.

##### Steps To Reproduce
1. Give a user the role system:image-pusher
oc adm policy add-cluster-role-to-user system:image-pusher "USER"

2. Log into oc with that user
oc login "USER"..

3. Get user token
token=$(oc whoami -t)

4. Log into the registry with Docker cli
docker login <registry> -u "USER" -p $token

5. Try to push an image
docker push...

##### Current Result
"**denied: requested access to the resource is denied**" 

docker push myregistry.example.com/test-push/test-push:latest                                                                                                                                      
The push refers to a repository [myregistry.example.com/test-push/test-push]                                                                                                                         
a11fda45870e: Mounted from test-push/test-push                                                                                                                                                           
**denied: requested access to the resource is denied**

##### Expected Result

The docker push command to ends with no errors ;)

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/origin/issues/17341

### CODE REVIEW

**Comment by bparees** [comment]
@openshift/team-documentation ptal

**Comment by bparees** [comment]
applicable to all releases afaik

**Comment by mburke5678** [comment]
LGTM 
The _{create} "imagestream"_ construct looks odd. Think users will understand what that means? (I assume _oc create imagestream_). Maybe we should break out all those commands?? Like the following (which looks bad here, but can be cut and paste into the .adoc file)

`- The user must be authorized to use the following commands in the project:`
+
--
* `oc get imagestream`
* `oc get layers`
* `oc update imagestream`
* `oc update layers` 

In addition, since the image stream does not already exist, the user 
must be authorized to `oc create imagestream` in that project.  If you are a project 
administrator, then you would have these permissions.
--`

**Comment by bparees** [comment]
> The {create} "imagestream" construct looks odd. Think users will understand what that means? (I assume oc create imagestream).

no, it's not oc create imagestream.  It means the ability to perform the create verb on the imagestream resource.  I copied the syntax from what is already there for imagestream/layers. (`{get, update} "imagestream/layers"`)

**Pull request merged**
