### PR TITLE
TELCODOCS-1535-ocp-4.10: Updated correct YAML file for pod deployment

### PR DESCRIPTION
**Pull request by MirzWeiss**
Version(s):
4.10

Issue:
https://issues.redhat.com/browse/TELCODOCS-1535

Link to docs preview:

- https://64266--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads#sandboxed-containers-deploying-workloads-with-kata-runtime-web_deploying-sandboxed-containers
- https://64266--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads#sandboxed-containers-deploying-workloads-with-kata-runtime-cli_deploying-sandboxed-containers

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by MirzWeiss** [comment]
@adellape I can fix the nit, though it is out of scope and I need this bug to get closed, but also, you marked this as enterprise-4.10 all the way through to 4.14.

This is not correct. OSC was removed from the OCP docs and moced to its own repo starting in 4.13, and I have a separate PR for 4.10, 4.11, and 4.12/ Should this PR be labeled with all the other versions?

**Review by adellape — APPROVED** [review]

**Pull request merged**
