### PR TITLE
OSDOCS-11212 removing snippet from 4.17 branch

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.17

Issue: [OSDOCS-12212](https://issues.redhat.com/browse/OSDOCS-12212)

Link to docs preview: https://83799--ocpdocs-pr.netlify.app/openshift-enterprise/latest/nodes/pods/run_once_duration_override/run-once-duration-override-release-notes.html

QE review:
- [X] QE has approved this change.

Additional information: Removing the snippet from the 4.17 branch.

### CODE REVIEW

**Review by jneczypor — COMMENTED** [review]
LGTM
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by skrthomas** [comment]
Confirmed with Courtney that change management isn't needed for this, as its a snippet in the release notes file but not actually part of the release notes.

merge review /lgtm

**Pull request merged**
