### PR TITLE
Fix sidebar word overflow

### PR DESCRIPTION
**Pull request by lbarbeevargas**
This fixes word overflow in the sidebar, for example in the API reference.

@vikram-redhat @jboxman

### CODE REVIEW

**Comment by vikram-redhat** [comment]
LGTM - merge away (and CP to 4.1 at least).

**Comment by vikram-redhat** [comment]
I am gonna merge and CP this one @lbarbeevargas as I got another complaint.

**Comment by lbarbeevargas** [comment]
Thank you for merging @vikram-redhat. Looks like the fix went through. I had to do a hard refresh fyi. I'll open a separate PR for the sidenav padding.

@jboxman FYI

**Pull request merged**
