### PR TITLE
Highlighted the verification command

### PR DESCRIPTION
**Pull request by dpateriya**
Highlighted the verification command for etcd disk quota 

Version(s):
OCP 4.16+

Issue: The verification command for etcd disk quota was not highlighted correctly.

Link to docs preview:
 https://79971--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.html#etcd-change-db-size_recommended-etcd-practices

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Comment by xenolinux** [comment]
@dpateriya I saw one command without a `$` sign. Can you consider to update it with `$`? 

https://79971--ocpdocs-pr.netlify.app/openshift-enterprise/latest/scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.html#etcd-changing-hardware-speed-tolerance_recommended-etcd-practices 

```5. Wait for etcd pods to roll out:

oc get pods -n openshift-etcd -w
```

**Comment by dpateriya** [comment]
@xenolinux the recent change you suggested is done on https://github.com/openshift/openshift-docs/pull/79972

**Review by skopacz1 — APPROVED** [review]
merge review LGTM

**Pull request merged**
