### PR TITLE
Fix issues#12730: Correct the hostPath indentation

### PR DESCRIPTION
**Pull request by bysnupy**
Fix issue: https://github.com/openshift/openshift-docs/issues/12730

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@jhou1, will you PTAL? If you agree, will you also confirm that it's valid in only 3.10 and 3.11?

**Comment by jhou1** [comment]
@kalexand-rh looks nice, this is also valid for 3.x versions.

**Comment by kalexand-rh** [comment]
Thanks @jhou1! I'll try to send it back to 3.6, then. :)

**Comment by kalexand-rh** [comment]
This particular example was added in 3.10, so that's as far back as it's going. :)

**Pull request merged**
