### PR TITLE
Cleanup code block CSS

### PR DESCRIPTION
**Pull request by jboxman**
~Preview link: http://file.bos.redhat.com/jboxman/code-block-css/welcome/~

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
I agree that the bottom margin for code blocks was way too much. Am I reading the file changes correctly in that the bottom margin was changed to `0.25em`? The top margin for the code block in the screenshot looks like a good amount, but the bottom looks a little cramped against the next list item. New padding and colors look good.

**Comment by jboxman** [comment]
@lbarbeevargas, I can change that. It was 3 am. Evening naps are always a bad idea.

**Comment by jboxman** [comment]
@lbarbeevargas the spacing saga continues. It's starting to cascade into too many changes, which I wanted to avoid. Too much duct tape.

Screen Shot 2020-07-24 at 3 34 48 PM

**Comment by lbarbeevargas** [comment]
Yeah CSS cleanup is always fun and complicated hah. Can you isolate the code block and not change the margin and padding on the other elements (if they were otherwise okay in the first place)?

**Comment by jboxman** [comment]
@openshift/team-documentation,

What pages have code blocks that look interesting to confirm whether these changes break anything?

Thanks.

**Comment by jboxman** [comment]
Examples:

Screen Shot 2020-08-04 at 12 29 32 PM
Screen Shot 2020-08-04 at 12 35 55 PM

**Comment by lbarbeevargas** [comment]
Side note: I like the color of the callouts here better than the (alarming) red. 👍 Are the callout numbers centered within the circle? They look slllightly off center. 

Are the most recent changes you made for the code block spacing? If so, the spacing in the last screenshots above look a lot better and appropriately closer to the surrounding content.

**Pull request merged**
