### PR TITLE
Add release note for configuring hybrid networking

### PR DESCRIPTION
**Pull request by jab-rh**
Previously, this needed to be done at installation time. Now it can be done after installation.

- https://issues.redhat.com/browse/OSDOCS-4799

Version(s):

Issue:

Link to docs preview: https://61111--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-enable-hybrid-networking-windows-nodes-ovn-kubernetes

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by skopacz1 — COMMENTED** [review]
Left one suggestion, otherwise looks good! I am new to reviewing, so please wait until @adellape approves this review before proceeding. Thanks!

**Review by adellape — COMMENTED** [review]
@skopacz1 Peer review comments LGTM 👍 

@jab-rh Does this require change management?

**Comment by jab-rh** [comment]
@adellape, it does, and still waiting on outcome of: https://github.com/openshift/openshift-docs/pull/61108

**Comment by jab-rh** [comment]
Looks like I did this twice: https://github.com/openshift/openshift-docs/pull/61985

**Pull request closed without merging**
