### PR TITLE
add example for using templateinstance API

### PR DESCRIPTION
**Pull request by jim-minter**
@bparees wdyt?

https://trello.com/c/jjZREiDc/899-3-template-instantiate-rest-api-techdebttemplates

### CODE REVIEW

**Comment by bparees** [comment]
Content wise it looks great!  But I'm debating whether this new general "api examples" section is the best way to structure it.  I'm worried about it becoming a dumping ground.  (and for now it's really lonely).

Might it be better under an "advanced" section/topic under the existing templates content?

@bmcelvee wdyt (last commit only)?

**Comment by bparees** [comment]
(I should note i can see the value in doing it the way you have, too, since it provides a natural location for the  "here's how to invoke apis via curl in general" content).

**Comment by bmcelvee** [comment]
I can see the concern over the API Example section getting cluttered or becoming a dumping ground, but for now my vote is to keep it in it's current location. If the content gets out of hand, we can always reassess. The way you have it does provide a natural location for API examples. And if we move it under the existing templates content, keeping the example content up to date could be a challenge.

**Comment by bparees** [comment]
sounds good, thanks @bmcelvee 

this lgtm, though it's in line behind the other PRs to bring in the new api doc content.

**Comment by jim-minter** [comment]
@ahardin-rh this builds on #5029 and should also be for origin + anything we release subsequently.  Once #5029 merges please will you merge this?

**Comment by vikram-redhat** [comment]
@jim-minter A few questions:

1. Since #5029 already contains commit 5a4ba0f53bb064a18d6b2261e89e706973402a95 which is merged into master (origin), we don't need that commit in this PR. Any particular reason why that commit is here as well? 

2. You mentioned in #5029 that this should only go in origin. Is that correct for this PR as well? I am assuming so, but @bparees has added the labels, so I am not sure. You mentioned that it should go into origin now and anything that is branched in the future. Does that mean it should go into origin now, and the next time it should be in the enterprise docs is when 3.7 comes out (we don't publish separate docs for z stream releases so 3.6.1 won't count, but we can publish it for as 3.6 docs when 3.6.1 is released)? 

3. Finally, everything here does actually apply to dedicated and online?

Thanks!

**Comment by jim-minter** [comment]
Hi @vikram-redhat ,

1- I hoped git would do the right thing and eat the additional commit, but it didn't.  Rebased and repushed, thanks.

2- This and #5029 should go into origin and 3.7, but not 3.6.* because it includes API changes made since 3.6 (and I don't want to backport the document generation to 3.6).

3- I don't know exactly what codebases dedicated and online use.  As soon as each is running a version recent enough to contain /api/docs, we should pull the documentation into the relevant branches of openshift-docs.

**Comment by vikram-redhat** [comment]
Thanks @jim-minter. That makes a lot of sense! I have updated the labels. 

cc: @ahardin-rh. @aburdenthehand

**Comment by jim-minter** [comment]
bump - is anything blocking this from being merged?

**Comment by vikram-redhat** [comment]
@ahardin-rh not sure if @bmcelvee is still looking at this one but if you or Brandi have time tomorrow, could you please look at it? 

Does this require a follow up PR?

**Comment by ahardin-rh** [comment]
Sorry for the delay. I will get this merged, then we can do some minor style edits in a separate PR. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../ rest_api/examples.adoc#rest-api-examples[REST API Examples]
|Added a new REST API Examples topic.
%

**Pull request merged**
