### PR TITLE
Pipelines 1.13.0 cli download link version bump

### PR DESCRIPTION
**Pull request by SNiemann15**

### CODE REVIEW

**Comment by SNiemann15** [comment]
@Preeticp I've updated the links for all architectures.  Do we need a QE review on this?

**Comment by Preeticp** [comment]
Yes, please get the QE LGTM on the PR.

**Comment by SNiemann15** [comment]
@piyush-garg Can you do the QE review please?

**Comment by praveen4g0** [comment]
Looks Good to me :heart: 
- updated binaries & rpms links are apt.
cc: @ppitonak

**Review by ppitonak — APPROVED** [review]

**Review by bergerhoffer — COMMENTED** [review]
LGTM!

**Comment by bergerhoffer** [comment]
Per @Preeticp this should only go into 4.7. Adjusting labels and then will merge/CP to 4.7

**Pull request merged**
