### PR TITLE
OSDOCS-6613-M: update welcome page for 4.14

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.14
Issue:
https://issues.redhat.com/browse/OSDOCS-6613

Link to docs preview:
https://61887--docspreview.netlify.app/microshift/latest/welcome/index.html

QE review:
N/A Docs plumbing

Note: MicroShift uses "read," not "see" for links.
Replaces https://github.com/openshift/openshift-docs/pull/61861

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by bergerhoffer** [comment]
@ShaunaDiaz this is failing because #61628 was not cherry picked to 4.14. I'll ping you on slack, but that one needs to be cherry picked first before this one.

**Comment by ShaunaDiaz** [comment]
> @ShaunaDiaz this is failing because #61628 was not cherry picked to 4.14. I'll ping you on slack, but that one needs to be cherry picked first before this one.

@bergerhoffer https://github.com/openshift/openshift-docs/pull/61628 was just the stub file. That should not be cherry picked to 4.14 because it will overwrite the release notes file that already exists there. I can make a manual and remove the stub.

**Comment by bergerhoffer** [comment]
@ShaunaDiaz it wasn't just the stub file, it also contained changes to other files. I know I mentioned this on slack as well, but any changes to the release notes file have to go in a separate file just straight to 4.14. And any changes that touch other files have to go into a separate PR targeting main and then CPd to 4.14.

So please manual CP that other PR (minus the stub update) so that this PR will hopefully CP cleanly after.

**Comment by kalexand-rh** [comment]
> @ShaunaDiaz Also, I see the note about microshift using "read" instead of "see". I know I've pointed this out before to use "see". Is there a reason why microshift is deviating here? "read" doesn't sound right to me, and I think it would be best to be consistent with how the majority of the rest of our docs write it.
> 
> CC @kalexand-rh in case there is some reason for this deviation that I'm not aware of?

I am not aware of a reason for the difference. "See" aligns with the usage explained in both the SSG and the ISG, so I think that MicroShift should adhere to the style guides.

**Comment by bergerhoffer** [comment]
@ShaunaDiaz @kalexand-rh This has actually been brought up before, and even to the IBM style council. It wasn't something that they had heard of as being problematic. 

During the discussions, the main reason for it not being problematic was that "see" doesn't necessarily only mean to see with your eyes, but also many other things. See https://www.merriam-webster.com/dictionary/see - the first is to perceive by the eye, but there are many others that have alternative meanings. The majority of which are more like what we mean - to be aware of, to come to know, to examine, to read, and so on.

But if you'd like it to be discussed further, please feel free to raise it as an issue in the SSG repo and it can be discussed among the style council more deeply. Since the goal is to have our documentation have a single voice as much as possible, if a change needs to be made, it should be made across all docs, not just in one small subset.

[1] https://github.com/redhat-documentation/supplementary-style-guide

**Comment by ShaunaDiaz** [comment]
@bergerhoffer Thank you for the background; I can certainly bring a few accessibility items to the council for discussion. For today, I think it's better to maintain the consistency within the MicroShift docs, as I have not had any customers report the word "read" as problematic. Getting this content ready for GA is my main concern, and we have a long way to go yet. 
cc @kalexand-rh

**Comment by kalexand-rh** [comment]
@ShaunaDiaz, please open an issue to bring this issue to the style council. If "read" is not adopted, add add an item to the backlog to align this usage with the SSG.

**Comment by ShaunaDiaz** [comment]
@kalexand-rh @bergerhoffer https://github.com/redhat-documentation/supplementary-style-guide/issues/356

**Pull request merged**
