### PR TITLE
Issue 54578: Issue in file cicd/builds/creating-build-inputs.adoc

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.9
Issue:

https://github.com/openshift/openshift-docs/issues/54578
Link to docs preview:

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
Screenshot

**Comment by mletalie** [comment]
@xueli181114, Can you please review this for me? Thanks.

**Comment by xueli181114** [comment]
@mletalie Seems this is docs should be reviewed by OCP team.

**Comment by mletalie** [comment]
Internal for record keeping: Reached out to @xingxingxia via slack on 2/3/23 to see if he could tell me who would be QE for this ticket.

**Comment by mletalie** [comment]
Hello @jitendar-singh, could you please review me for this (QE review)? Thanks! ML

**Comment by mletalie** [comment]
Hello @opayne1,
   Thanks for taking a look at this issue, can you tell me if this looks okay and is done/ready to be merged? Thanks!

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Review by bergerhoffer — COMMENTED** [review]
LGTM merging!

**Pull request merged**
