### PR TITLE
CNV-20075: reversing placeholder text for CNV GA

### PR DESCRIPTION
**Pull request by ousleyp**
Version(s): 4.11  and 4.12

Issue: https://issues.redhat.com/browse/CNV-20075

Link to docs preview: https://48519--docspreview.netlify.app/openshift-enterprise/latest/virt/about-virt.html

Additional information: To be merged _when CNV 4.11 releases_, BEFORE merging https://github.com/openshift/openshift-docs/pull/48498

### CODE REVIEW

**Review by sjhala-ccs — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
It's fine to use the bot to CP this to 4.12.

**Comment by kalexand-rh** [comment]
It's normally concerning when CPs to 4.12 don't go through, but if this is _just_ because of the temporary redirect note, it's fine to make a manual CP to 4.12.

**Comment by ousleyp** [comment]
We didn't realize we needed to CP https://github.com/openshift/openshift-docs/pull/50312 to 4.12, so I just did that and will shortly try this auto-CP again.

**Pull request merged**
