### PR TITLE
Update nav and logos

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
Staging sites:

- https://commercial-docs-wgordon.e203.evg.openshiftapps.com/
- https://community-docs-wgordon.e203.evg.openshiftapps.com/

The staging sites reflect the _new_ fonts, and therefore will not be reflected in what Travis builds.

**Comment by vikram-redhat** [comment]
@ahardin-rh @adellape - FYI that this will need to be picked up Thursday (your time) and @wgordon17 will ping you to cherry pick some parts of it to various branches.

**Comment by vikram-redhat** [comment]
@openshift/team-documentation @openshift/team-aligned-docs FYI. New logo and styles.

**Comment by wgordon17** [comment]
#14647 will also need to be merged with this PR. These are separated to ensure for proper cherry-picking

**Comment by vikram-redhat** [comment]
This needs to be merged to master AND cherrypicked to enterprise-4.1

**Comment by ahardin-rh** [comment]
Got the okay to merge! :shipit:

**Pull request merged**
