### PR TITLE
fix chained build example indentation

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@csrwng ptal

**Comment by csrwng** [comment]
thx @bparees LGTM

**Comment by bparees** [comment]
@openshift/team-documentation ptal/merge.

**Comment by bmcelvee** [comment]
@bparees LGTM 🎆

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../dev_guide/builds/advanced_build_operations.adoc#dev-guide-advanced-build-operations[Advanced Build Operations]
|Corrected example chained build indentation in xref:../dev_guide/builds/advanced_build_operations.adoc#dev-guide-chaining-builds[Chaining Builds] section.
%

**Comment by adellape** [comment]
FYI @bparees: Since https://github.com/openshift/openshift-docs/pull/3829 was labeled 3.6 only, I've dropped the 3.5 label from this follow-up.

**Comment by bparees** [comment]
@adellape ok that's fine.  i put the label on because chained builds were valid in 3.5 but i guess the doc didn't exist.

**Pull request merged**
