### PR TITLE
WMCO#802 More appropriate example domain name

### PR DESCRIPTION
**Pull request by codyhoag**
From issue sent in openshift/windows-machine-config-operator#802

Previews:
- https://deploy-preview-38737--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/byoh-windows-instance.html#configuring-byoh-windows-instance
- https://deploy-preview-38737--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/byoh-windows-instance.html#removing-byoh-windows-instance

### CODE REVIEW

**Comment by codyhoag** [comment]
@sgaoshang @rrasouli PTAL. Thanks!

**Comment by sgaoshang** [comment]
@codyhoag /lgtm, thanks.

**Comment by sagidlow** [comment]
LGTM! :)

**Pull request merged**
