### PR TITLE
[enterprise-4.16] OBSDOCS-1235: Removed Logging 5.7z and 5.8z from 4.16

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Logging Z-Stream Release Notes - Content Improvement
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-1235

Fix Version: 4.16

Doc Preview: https://79962--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-9-release-notes

QE Review: @anpingli 
Peer Review: @xenolinux

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Review by skopacz1 — APPROVED** [review]
Merge review LGTM

**Pull request merged**
