### PR TITLE
Fix labelSelector syntax for PodAfinity docs - config

### PR DESCRIPTION
**Pull request by StevenBarre**
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lyman9966, will you PTAL and confirm which versions this change is valid for?

**Comment by vikram-redhat** [comment]
@xltian ^

**Comment by lyman9966** [comment]
@kalexand-rh 
I have tested, `- labelSelector` is correct.

**Comment by kalexand-rh** [comment]
Since `- labelSelector` is correct, I'm closing this PR. Thanks @sbarre-esit.

**Pull request closed without merging**
