### PR TITLE
Fixing bugs from Serverless GA install docs

### LINKED ISSUE #21712: [enterprise-4.3] Edit suggested in file serverless/installing_serverless/installing-knative-eventing.adoc
### Which section(s) is the issue in?
[Installing Knative Eventing using the web console](https://docs.openshift.com/container-platform/4.3/serverless/installing_serverless/installing-knative-eventing.html#serverless-install-eventing-web-console_installing-knative-eventing)

### What needs fixing?
Similar to #21709 

#### Problem 1: Using "Catalog->OperatorHub->Installed Operators"
In OCP43 I don't see this "Catalog" 
I see Administrator perspective, then under "Operators->Installed Operators"

#### Problem 2: Certain pictures need to be updated to reflect project scope knative-eventing
The pictures show `openshift-operators` and instead it should show the `knative-eventing` project
image

### PR DESCRIPTION
**Pull request by abrennan89**
Applies for OCP 4.3, 4.4, 4.5

Fixes #21712 and #21709

### CODE REVIEW

**Comment by maschmid** [comment]
the image in https://170issues--ocpdocs.netlify.app/openshift-enterprise/latest/serverless/installing_serverless/installing-knative-serving.html#serverless-install-serving-web-console_installing-knative-serving  

step 5 , still has "Project: openshift-operators"

**Comment by maschmid** [comment]
QE approved

**Review by sheriff-rh — APPROVED** [review]
LGTM!

**Pull request merged**
