### PR TITLE
RHDEVDOCS-6142 Fix Tekton Pipeline Management Commands

### PR DESCRIPTION
**Pull request by hemantkumarc**
This PR is raised to achieve the expected results mentioned in the [RHDEVDOCS-6142,](https://issues.redhat.com/browse/RHDEVDOCS-6142?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel) 

Version(s): `pipelines-docs-1.14`, `pipelines-docs-1.15`, `pipelines-docs-1.16`

Issue: [RHDEVDOCS-6142](https://issues.redhat.com/browse/RHDEVDOCS-6142?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel)

Link to docs preview:

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by hemantkumarc** [comment]
@eromanova97. Can you please review my PR again ? I have closed the old PR and raised a new one.
cc : @Srivaralakshmi

**Review by Srivaralakshmi — COMMENTED** [review]
Good work! The changes look good to me except for the content type attribute. Please implement the suggestion given. 

After L2, leave a line. Before L4, add this attribute:
:_mod-docs-content-type: REFERENCE

For more information, see: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#content-type-attributes and https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata

Thanks, @hemantkumarc.

**Comment by eromanova97** [comment]
Hello @hemantkumarc  please address the comment made by Sri: https://github.com/openshift/openshift-docs/pull/82312#pullrequestreview-2324800271
Otherwise changes look good to me. Thank you!

**Comment by hemantkumarc** [comment]
@Srivaralakshmi @eromanova97.
Please review my new changes.

**Comment by eromanova97** [comment]
Changes look good to me, thanks! 
/lgtm

**Review by JoeAldinger — COMMENTED** [review]
/lgtm

**Pull request merged**
