### PR TITLE
[OSDOCS-5263] EgressIP support for OpenStack - CloudPrivateIPConfig Mover interface

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.13

Issue: [OSDOCS-5263](https://issues.redhat.com//browse/OSDOCS-5263)

Link to docs preview: https://57524--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.html#nw-egress-ips-public-cloud-platform-considerations_configuring-egress-ips-ovn

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by eurijon** [comment]
Just to confirm, the note is removed from the ovn-k egressIP docs but not from the openshiftsdn egressIP docs, right?

**Comment by eurijon** [comment]
@maxwelldb I think so, @dulek can you please confirm?
cc: @rlobillo

**Comment by dulek** [comment]
Yes, at the moment OpenShift-SDN still suffers from the issue. I might not be able to fix that before the release, so it's better to keep the note there.

**Comment by maxwelldb** [comment]
OVN-k8s: https://57524--docspreview.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.html#nw-egress-ips-public-cloud-platform-considerations_configuring-egress-ips-ovn

OpenShift-SDN: https://57524--docspreview.netlify.app/openshift-enterprise/latest/networking/openshift_sdn/assigning-egress-ips.html#nw-egress-ips-public-cloud-platform-considerations_egress-ips

**Comment by eurijon** [comment]
lgtm

**Review by snarayan-redhat — COMMENTED** [review]
Looks good!

**Pull request merged**
