### PR TITLE
Bug 1412827, Added more information about disabling MAC filtering for the Egress Router

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1412827

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@danwinship @pravisankar @sferich888 PTAL

**Comment by danwinship** [comment]
I don't actually know the details of what needs to be done, but that all sounds like it's probably right.

Maybe add some generic text to the top of that section. Something like:

The egress router adds a second IP address and MAC address to the node's primary network interface. If you are not running {product-title} on bare metal, you may need to configure your hypervisor or cloud provider to allow the additional address.

**Comment by ahardin-rh** [comment]
@danwinship Thanks. Updated.

**Comment by danwinship** [comment]
lgtm

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/managing_pods.adoc#admin-guide-manage-pods[Managing Pods]
|Added more information about disabling MAC filtering for the Egress router.
%

**Pull request merged**
