### PR TITLE
Bug 1850495 Tolerations shouldn't be defined in rsyslog but in fluentd

### PR DESCRIPTION
**Pull request by rolfedh**
- For versions 4.5+
- https://bugzilla.redhat.com/show_bug.cgi?id=1850495
- Direct link to doc preview: https://deploy-preview-30439--osdocs.netlify.app/openshift-enterprise/latest/logging/config/cluster-logging-tolerations.html#cluster-logging-collector-tolerations_cluster-logging-tolerations
- Ready for QE review

### CODE REVIEW

**Comment by rolfedh** [comment]
@anpingli Please review and approve. Thanks.

**Comment by xltian** [comment]
@anpingli from OpenShift QE will review

**Review by anpingli — COMMENTED** [review]
/lgtm

**Review by codyhoag — APPROVED** [review]
LGTM!

**Pull request merged**
