### PR TITLE
Bug#1397521 - Ingress Configuration now links to cloud providers example

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://bugzilla.redhat.com/show_bug.cgi?id=1397521

- Removed the older note with no information on Cloud providers
- Highlighted a note which points to info on how to handle the same using Load balancers
- Other minor formatting fixes

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
[[DOCS] Ingress Configuration Should show examples for cloud providers.](https://trello.com/c/Ab8oBdLu/5-docs-ingress-configuration-should-show-examples-for-cloud-providers)

**Comment by gaurav-nelson** [comment]
@jhou1 PTAL

**Comment by jhou1** [comment]
@bmeng PTAL

**Comment by bmeng** [comment]
Changes look good. Thanks.

**Comment by gaurav-nelson** [comment]
Thanks @jhou1 @bmeng, I am moving the bug to verified.

**Comment by bfallonf** [comment]
@gaurav-nelson LGTM :boat:

**Comment by gaurav-nelson** [comment]
minor change no rev history needed.

**Pull request merged**
