### PR TITLE
OSDOCS-11780: 4.12.64 RN

### PR DESCRIPTION
**Pull request by obrown1205**
Version(s):
4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-11780

Link to docs preview:
https://81011--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes.html#ocp-4-12-64

QE review:
N/A

Additional information:
Errata URLs will return 404 until go-live (08/29/2024)

### CODE REVIEW

**Review by dfitzmau — APPROVED** [review]
/remove-label peer-review-in-progress

/label peer-review-done

**Review by opayne1 — COMMENTED** [review]
Hey! Could you squash your commits? It LGTM I will merge after!

**Pull request merged**
