### PR TITLE
[SRVCOM-3354] Correct inline pass-through to +++

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.32+

Issue:
https://issues.redhat.com/browse/SRVCOM-3354

Link to docs preview:
https://83922--ocpdocs-pr.netlify.app/openshift-serverless/latest/eventing/tuning/overriding-config-eventing.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Review by skopacz1 — APPROVED** [review]
LGTM

**Pull request merged**
