### PR TITLE
Typo in prerequisites regarding the firewall

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1572935

### CODE REVIEW

**Comment by mburke5678** [comment]
@sosiouxme 
Luke, it appears you added some info to the Aggregated Logging topic that included: 
"each PVC name will have a sequence number added to it, so `logging-es-1`, `logging-es-2`, etc."[1]

A BZ [2] suggests that the naming starts at `logging-es-0` not `logging-es-1`. Can you comment on whether the BZ is correct?

[4] https://github.com/openshift/openshift-docs/pull/2538/files#diff-0bd2e2c1a5da6f157682d4e95ecea473R454
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1585762

cc. @ahardin-rh

**Comment by mburke5678** [comment]
@knobunc  Is this something you can look at?

**Review by knobunc — APPROVED** [review]
LGTM thanks

**Comment by mburke5678** [comment]
@bmeng PTAL

**Comment by bmeng** [comment]
LGTM, thanks.

**Comment by mburke5678** [comment]
This command was added for 3.5+ via https://github.com/openshift/openshift-docs/pull/6881

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Comment by mburke5678** [comment]
@kalexand-rh ++ (have to do it here as I cannot access IRC!)

**Pull request merged**
