### PR TITLE
Bug 1404843, Added a note on certificate expiration

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1404843

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@rjhowe PTAL and let me know if this is what you are looking for. 
@ahardin-rh Please peer review.

**Comment by ahardin-rh** [comment]
LGTM 🎆

**Comment by tmorriso-rh** [comment]
@rjhowe Bump.

**Comment by tmorriso-rh** [comment]
[rev_history]
|xref:../install_config/redeploying_certificates.html [Redeploying Certificates]
|Added a note to the xref:../install_config/redeploying_certificates.html [Redeploying Certificates] section about certificate expiration.
%

**Pull request merged**
