### PR TITLE
OSDOCS#6645: Update the cert-manager subscription name

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.12+

Issue: https://issues.redhat.com/browse/OSDOCS-6645

Link to docs preview: https://61748--docspreview.netlify.app/openshift-enterprise/latest/security/cert_manager_operator/cert-manager-operator-proxy.html#cert-manager-proxy-support_cert-manager-operator-proxy

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xenolinux** [comment]
@swghosh Can you PTAL?

**Comment by swghosh** [comment]
/lgtm
/cc @xingxingxia 
(I'm closing on https://github.com/openshift/cert-manager-operator/pull/116 as we have this up now)

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Great catch, @xenolinux !
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
