### PR TITLE
update kubernetes to 1.6

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL to make sure this has correct milestone and label?

**Comment by bfallonf** [comment]
@mburke5678 LGTM. I saw the other PR where this is talked about.

**Comment by mburke5678** [comment]
See also: Update the current version of Kubernetes (1.7)
https://github.com/openshift/openshift-docs/pull/5104

**Comment by mburke5678** [comment]
@vikram-redhat PTAL at labelling as discussed.

**Comment by mburke5678** [comment]
No rev history required.

**Pull request merged**
