### PR TITLE
OSDOCS-4379: Correct filename and context for ROSA quickstart

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.11, 4.12

Issue:
https://issues.redhat.com/browse/OSDOCS-4379

Link to docs preview:
https://52246--docspreview.netlify.app/openshift-rosa/latest/rosa_getting_started/rosa-quickstart-guide-ui.html

No QE or SME review required.

Additional information:

### CODE REVIEW

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Comment by bmcelvee** [comment]
Update for https://github.com/openshift/openshift-docs/pull/51818

**Pull request merged**
