### PR TITLE
[enterprise-3.6] Bump latest-tag to 3.6.173.0.130

### PR DESCRIPTION
**Pull request by ghost**
To be released September 26, 2018

@ahardin-rh PTAL.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@vikram-redhat Can you take a look at the comment from the cherrypick robot? I'm not familiar with this type of message. Thanks.

**Comment by vikram-redhat** [comment]
@tmorriso-rh - this is already merged in 3.6. This doesn't need cherrypicking if it is already merged in the branch. Are you trying to cherrypick it somewhere else? The error is simply saying that you can't CP a commit to the same branch.

**Comment by tmorriso-rh** [comment]
> @tmorriso-rh - this is already merged in 3.6. This doesn't need cherrypicking if it is already merged in the branch. Are you trying to cherrypick it somewhere else? The error is simply saying that you can't CP a commit to the same branch.

Ok, I see. This change was made to the enterprise-3.6 branch, so no need to cherry-pick. Thanks.

**Pull request merged**
