### PR TITLE
CNV- 26972: 4.14.0 hco version

### PR DESCRIPTION
**Pull request by apinnick**
Version(s): 4.14.0

Issue: [CNV-26972](https://issues.redhat.com//browse/CNV-26972)

Link to docs preview: [Installing - CLI](https://63511--docspreview.netlify.app/openshift-enterprise/latest/virt/install/installing-virt#installing-virt-operator-cli_installing-virt)

QE review: NA
- [ ] QE has approved this change.

Additional information: To be merged on Oct. 23

### CODE REVIEW

**Comment by ShaunaDiaz** [comment]
@ousleyp Could you kindly verify my peer review? Thank you!

**Comment by ousleyp** [comment]
IIRC, we usually make the y-stream version number change in main and then cherrypick it, but I don't know if that matters. 

We will also need to update :VirtVersion: to 4.14, btw, so you might want to do both at once.

**Pull request closed without merging**
