### PR TITLE
OSDOCS#11438: Add OADP backup objects

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.16+

Issue: https://issues.redhat.com/browse/OSDOCS-11438 

Link to docs preview: https://79343--ocpdocs-pr.netlify.app/openshift-enterprise/latest/hosted_control_planes/hcp_high_availability/hcp-disaster-recovery-oadp.html#hcp-dr-oadp-backup-cp-workload_hcp-disaster-recovery-oadp

QE review:
- [x] QE has approved this change.

SME review:
- [x] SME has approved this change.

Additional information:

### CODE REVIEW

**Comment by zanetworker** [comment]
@LiangquanLi930 can you approve this one till we get to fully working state with testing.

**Review by lahinson — COMMENTED** [review]
LGTM

**Pull request merged**
