### PR TITLE
OSDOCS-1462 loglevel for Registry Config

### PR DESCRIPTION
**Pull request by bmcelvee**
https://issues.redhat.com/browse/OSDOCS-1462

### CODE REVIEW

**Comment by bmcelvee** [comment]
Removing the enterprise-4.6 label. Will relabel prior to merge.

**Comment by bmcelvee** [comment]
Preview build: https://osdocs-1462-loglevel-regconfig--ocpdocs.netlify.app/openshift-enterprise/latest/registry/configuring-registry-operator.html#registry-operator-configuration-resource-overview_configuring-registry-operator

**Comment by bmcelvee** [comment]
@wzheng1 would you mind reviewing this PR, please? It's very similar to the release notes content, but updating the parameters table.

**Comment by ahardin-rh** [comment]
LGTM!

**Pull request merged**
