### PR TITLE
Changed portalIP to clusterIP in example 3

### PR DESCRIPTION
**Pull request by ghost**
This is a follow up to PR https://github.com/openshift/openshift-docs/pull/5833.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation Please peer review.

@dlbewley Please review. Also, what doc versions does this change apply to?

**Comment by dlbewley** [comment]
Versions 1.4+ / 3.4+ I believe.

**Review by dlbewley — APPROVED** [review]

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Comment by tmorriso-rh** [comment]
No rev history needed.

**Pull request merged**
