### PR TITLE
RHDEVDOCS 6279 fix formatting in Results configuration for LokiStack

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

pipelines-docs-1.16, pipelines-docs-1.17

Issue:

RHDEVDOCS 6279

Link to docs preview:

https://85637--ocpdocs-pr.netlify.app/openshift-pipelines/latest/records/using-tekton-results-for-openshift-pipelines-observability.html#results-storage_using-tekton-results-for-openshift-pipelines-observability

QE review:
N/A

Additional information:

This is a trivial formatting fix

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6279

**Review by xenolinux — COMMENTED** [review]
LGTM

**Review by jeana-redhat — APPROVED** [review]
LGTM, let me know if there are other labels or anything for pipelines but I'll merge and pick as indicated :+1: 

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Comment by jeana-redhat** [comment]
@mramendi looks like the older version needs manual intervention :disappointed:

**Pull request merged**
