### PR TITLE
BZ1397996 Clarified Configuring Custom Certificates section

### PR DESCRIPTION
**Pull request by bmcelvee**
Fixes Bug 1397996

### CODE REVIEW

**Comment by bmcelvee** [comment]
@sjwalter2 PTAL

**Comment by bmcelvee** [comment]
|xref:../ install_config/certificate_customization.adoc#configuring-custom-certificates[Configuring Custom Certificates]
|Clarified custom certificate configuration locations in the xref:../install_config/certificate_customization.adoc#configuring-custom-certificates[Configuring Custom Certificates] section.
%

**Comment by bmcelvee** [comment]
@ahardin-rh PTAL

**Comment by ahardin-rh** [comment]
@bmcelvee LGTM! :stars:

**Pull request merged**
