### PR TITLE
BZ2102828: Cu requires guidance on windows container Vs OCP windows node version compatibility and best dev practices to avoid compatibility issues.

### PR DESCRIPTION
**Pull request by mburke5678**
** New PR replacing https://github.com/openshift/openshift-docs/pull/49446, which had issues in the topic map **

https://bugzilla.redhat.com/show_bug.cgi?id=2102828

Preview:[ Windows pod placement: Important note](http://file.rdu.redhat.com/mburke/BZ-2102828/windows_containers/scheduling-windows-workloads.html#windows-pod-placement_scheduling-windows-workloads)

### CODE REVIEW

**Comment by mburke5678** [comment]
All approvals are in https://github.com/openshift/openshift-docs/pull/49446

**Review by jfrancoa — COMMENTED** [review]
/lgtm

**Pull request merged**
