### PR TITLE
BZ1755794 update table 5

### PR DESCRIPTION
**Pull request by bobfuru**
[BZ 1755794](https://bugzilla.redhat.com/show_bug.cgi?id=1755794) - edit "Azure" to "Azure Disk" in table 5.
@openshift/team-documentation 
Can I please get a review, merge, and CP to 4.1 and 4.2?

### CODE REVIEW

**Review by kalexand-rh — COMMENTED** [review]
LGTM

**Comment by kalexand-rh** [comment]
Azure wasn't an option in 4.1, so I can't apply the change to that branch.

**Comment by vikram-redhat** [comment]
Yup this change is only for 4.2

**Pull request merged**
