### PR TITLE
OSDOCS-4082 Updating azure regions for 4.12

### PR DESCRIPTION
**Pull request by bscott-rh**
https://issues.redhat.com/browse/OSDOCS-4082

Applies to 4.12

Adding `qatarcentral` to azure regions per Patrick Dillon.

Preview: https://54592--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-account.html#installation-azure-regions_installing-azure-account

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@duanwei33 Hello, can you verify the addition of `qatarcentral` to the azure supported regions for 4.12? Thank you

**Review by mjpytlak — COMMENTED** [review]
Peer review LGTM @bscott-rh

**Comment by bscott-rh** [comment]
> The installation on region `qatarcentral` has been tested passed on QE side, see relevant bug [OCPBUGS-3803](https://issues.redhat.com/browse/OCPBUGS-3803) requested from QE side. We tested region `qatarcentral` on all supported releases, if this PR only use to track the update on 4.12, it looks good to me.

Yes, this PR is for 4.12 only. thank you.

/label merge-review-needed

**Pull request merged**
