### PR TITLE
Changed storageClass to storageClassName in CR

### PR DESCRIPTION
**Pull request by mburke5678**
Per slack chat https://coreos.slack.com/archives/CB3HXM2QK/p1571983355411400?thread_ts=1571983092.410900&cid=CB3HXM2QK

Also https://bugzilla.redhat.com/show_bug.cgi?id=1765440

### CODE REVIEW

**Comment by richm** [comment]
`size` should be at the same indentation level as `storageClassName` e.g.
```yaml
      storage:
        storageClassName: gp2
        size: 32G
```

**Comment by richm** [comment]
lgtm

**Comment by mburke5678** [comment]
@QiaolingTang Please take a look. Based on your Slack conversation with Mrugesh.

**Comment by QiaolingTang** [comment]
lgtm

**Comment by QiaolingTang** [comment]
Hi @mburke5678, could you please check if 4.1 has the same problem or not?  Thanks.

**Comment by QiaolingTang** [comment]
BTW, I opened a bz last Friday: https://bugzilla.redhat.com/show_bug.cgi?id=1765440

**Comment by mburke5678** [comment]
@QiaolingTang These changes are present in 4.1 and cherrpypicking is not needed.

https://docs.openshift.com/container-platform/4.1/logging/config/efk-logging-elasticsearch.html#efk-logging-elasticsearch-storage_efk-logging-elasticsearch
https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying-about.html#efk-logging-deploy-about-config_efk-logging-deploying-about

**Pull request merged**
