### PR TITLE
OBSDOCS-578: Update the information in document - Restrict to use clu…

### PR DESCRIPTION
**Pull request by eromanova97**
Version(s): `enterprise-4.12` and later

Issue: [OBSDOCS-578](https://issues.redhat.com/browse/OBSDOCS-578)

Link to docs preview: [Attaching additional labels to your time series and alerts](https://73136--ocpdocs-pr.netlify.app/openshift-enterprise/latest/monitoring/configuring-the-monitoring-stack#attaching-additional-labels-to-your-time-series-and-alerts_configuring-the-monitoring-stack)

QE review:
- [x] QE has approved this change.

Peer review:
- [x] Peer review done

**Additional information:**

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Review by xenolinux — COMMENTED** [review]
LGTM

/remove-label peer-review-needed
/remove-label peer-review-in-progress
/label peer-review-done

**Pull request merged**
