### PR TITLE
GH#37740:fix-eviction-pressure-transition-period

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/37740

### CODE REVIEW

**Comment by mburke5678** [comment]
@bshirren PTAL

**Comment by bshirren** [comment]
Thanks Michael - this is very close just missing the colon at end of "eviction-pressure-transition-period"

~~~
    kubeletArguments:
      eviction-pressure-transition-period:
      - 5m
~~~

**Comment by bshirren** [comment]
LGTM. Thanks Michael for taking care of this!

**Comment by mburke5678** [comment]
@lmurthyrh Can you please assign this PR for QE review? Thank you in advance.

**Comment by mburke5678** [comment]
@lmurthyrh Can you please assign this PR for QE review? Thank you in advance.

**Comment by lmurthyrh** [comment]
@sunilc@redhat.com - Please review this PR

**Review by skrthomas — APPROVED** [review]
/lgtm

**Pull request merged**
