### PR TITLE
Quota does not support limits.storage

### PR DESCRIPTION
**Pull request by derekwaynecarr**
this is an error in the doc.

quota only supports requests.storage.

/cc @mburke5678

### CODE REVIEW

**Comment by mburke5678** [comment]
@derekwaynecarr This parameter appears back to 3.2, when the topics was introduced. Want to verify that we are making this change to 3.3, 3.4. and 3.5.

**Comment by derekwaynecarr** [comment]
@mburke5678 -- it was changed in error here: https://github.com/openshift/openshift-docs/pull/3729

any version of doc that says we support limits.storage needs updating.

**Comment by mburke5678** [comment]
Removed 3.3 label. Will be addressed through separate PR and Bugzilla
https://bugzilla.redhat.com/show_bug.cgi?id=1466646

**Comment by mburke5678** [comment]
[rev_history]
|xref:../ admin_guide/quota.adoc#admin-guide-quota[Cluster Administration -> Setting Quotas]
|Removed unsupported limits.storage parameter.
%

**Pull request merged**
