### PR TITLE
Update builddefaults documentation.

### PR DESCRIPTION
**Pull request by barlik**
Update the documentation with the instructions how to keep the proxy settings, but disable it for the builds.

### CODE REVIEW

**Comment by vikram-redhat** [comment]
I am closing this PR as there is not enough context provided around why we need to change it. @barlik please feel free to submit a new one if this change needs to be made.

**Comment by barlik** [comment]
It's difficult to be motivated to create a new PR when the current one was ignored for 10 months and then closed without asking any questions. The context should be evident from the commit diff.
At a customer, we needed to set `openshift_http_proxy`, but not `openshift_builddefaults_http_proxy`. The only way to achieve that is by setting `openshift_builddefaults_http_proxy` to `false`. That was not easy to figure out, hence the documentation update.

**Comment by vikram-redhat** [comment]
@barlik thanks for that added context and I apologize for the delay in getting to this.

@jiajliu - can you please provide QE review?

@kalexand-rh - once we get QE review, can you PTAL?

**Comment by vikram-redhat** [comment]
@barlik - can you please rebase as well?

**Comment by kalexand-rh** [comment]
@jiajliu, @barlik, which versions is this change valid in?

@vikram-redhat, this file's been moved, so, depending on the valid versions, we'll probably need multiple unique PRs before it's over.

**Review by kalexand-rh — COMMENTED** [review]
I edited one of the definitions so it's clearer. Will you please update them?

**Comment by barlik** [comment]
I've rebased onto master branch and updated the documentation.

@kalexand-rh I've seen the behaviour in release 3.5 and I've just confirmed it with the master branch.

I would also like to point out that I'm not sure that the variable `builddefaults` should be inherited in the first place and setting it to `False` is probably an accidental 'solution' for the problem. So, please can anybody check with the engineers?

**Comment by kalexand-rh** [comment]
Thanks @barlik!

@sdodson, do you have an opinion on these `builddefaults` parameters?

**Comment by sdodson** [comment]
These changes look fine to me. I don't think there would be any changes that would prevent this from working in later releases. Thanks.

**Comment by kalexand-rh** [comment]
Thank you @sdodson!

@jiajliu, will you PTAL or suggest another QE reviewer?

**Comment by kalexand-rh** [comment]
@jianlinliu, will you PTAL?

**Comment by jianlinliu** [comment]
@ganhuang PTAL.

**Comment by ganhuang** [comment]
Tested with `False` set against those parameters, it definitely works.

LGTM. But it would be a little confusing that `false` won't work in such situation. It's be perfect if we could give a note here.

**Comment by kalexand-rh** [comment]
@ganhuang, thanks for confirming this! I think this whole flow is a little confusing. Will you please give me a little more information about what you'd like in the note?

**Comment by ganhuang** [comment]
@kalexand-rh I don't know how to change that words. Not a big deal. I'm fine to get it merged.

**Comment by kalexand-rh** [comment]
Thanks, @ganhuang!

**Pull request merged**
