### PR TITLE
OADP 3905 - Azure missing steps

### PR DESCRIPTION
**Pull request by CarmiWisemon**
OADP 1.3.2

OCP 4.13+

Resolves - https://issues.redhat.com/browse/OADP-3905

Deploy preview - 

OADP

https://74821--ocpdocs-pr.netlify.app/openshift-enterprise/latest/backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.html

Migration 3-4

https://74821--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/installing-3-4.html#migration-configuring-azure_installing-3-4

MTC

https://74821--ocpdocs-pr.netlify.app/openshift-enterprise/latest/migrating_from_ocp_3_to_4/installing-3-4.html#migration-configuring-azure_installing-3-4

### CODE REVIEW

**Comment by PrasadJoshi12** [comment]
LGTM, approved

azure

**Review by PrasadJoshi12 — APPROVED** [review]

**Comment by mburke5678** [comment]
/enterprise-4.13

**Comment by mburke5678** [comment]
/enterprise-4.14

**Comment by mburke5678** [comment]
/enterprise-4.15

**Comment by mburke5678** [comment]
/enterprise-4.16

**Pull request merged**
