### PR TITLE
BZ#2065695 - missing params

### PR DESCRIPTION
**Pull request by aireilly**
Fixing missing params that should have been in https://github.com/openshift/openshift-docs/pull/53084

Merge to main, CP to 4.8+

### CODE REVIEW

**Comment by shajmakh** [comment]
lgtm, thanks for the fixes!

**Review by abhatt-rh — COMMENTED** [review]
LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by snarayan-redhat** [comment]
@aireilly - 4.8, 4.9 and 4.10 need manual CPs. Let me know once you create those and I can merge for you. 4.11 and 4.12 are merged.

**Pull request merged**
