### PR TITLE
BZ2011435 - Document "needVhostNet" & "isRdma" for SriovNetworkNodePolicy

### PR DESCRIPTION
**Pull request by aireilly**
https://bugzilla.redhat.com/show_bug.cgi?id=2011430
https://bugzilla.redhat.com/show_bug.cgi?id=2011435

This work is for main, enterprise-4.9, enterprise-4.10

Preview: 

https://deploy-preview-37234--osdocs.netlify.app/openshift-enterprise/latest/networking/hardware_networks/configuring-sriov-device#nw-sriov-networknodepolicy-object_configuring-sriov-device

### CODE REVIEW

**Comment by aireilly** [comment]
@SchSeba - for review

**Review by SchSeba — COMMENTED** [review]
/lgtm

**Review by ctauchen — COMMENTED** [review]
Thanks, @aireilly. One small formatting fix and a question about a term.

**Review by SchSeba — COMMENTED** [review]
/lgtm

**Review by ctauchen — COMMENTED** [review]
Thanks, @aireilly 

/lgtm

**Review by mikemckiernan — COMMENTED** [review]
Some day, we'll all use \<.\> so we don't go blind.  Please let me know what I can clarify.

**Pull request merged**
