### PR TITLE
[enterprise-4.7] CICD -Build, Pipelines and GitOps docs restructure (#29252)

### PR DESCRIPTION
**Pull request by jboxman**
Restructure CI/CD content

This is for https://github.com/openshift/openshift-docs/pull/29252.

### CODE REVIEW

**Comment by jboxman** [comment]
cc @Preeticp

**Comment by jboxman** [comment]
@Preeticp looks like I got it wrong:

```
ERROR (applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc): "xref:../../serverless/installing_serverless/installing-openshift-serverless.adoc#serverless-install-web-console_installing-openshift-serverless[OpenShift Serverless]" appears to try to reference a file not included in the "openshift-enterprise" distro
```

Maybe I can sort it out; Trying to resolve a cherry-pick for unfamiliar content does not always go as planned.

**Comment by jboxman** [comment]
@Preeticp, this is merged.

**Comment by Preeticp** [comment]
Thanks a ton @jboxman I was trying to resolve build errors and merge conflicts on another PR of mine, hence did not see this till now. Thank you so much for fixing this!!

**Pull request merged**
