### PR TITLE
OSDOCS-12895:Updated OSD-GCP arch model images.

### PR DESCRIPTION
**Pull request by AedinC**
Version(s):
4.17+

Issue:
https://issues.redhat.com/browse/OSDOCS-12895

Link to docs preview:
https://86090--ocpdocs-pr.netlify.app/openshift-dedicated/latest/architecture/osd-architecture-models-gcp

SME review:
- [ ] SME has approved this change.

**QE approval is not required for this change.**

Additional information:

### CODE REVIEW

**Comment by AedinC** [comment]
Hi @svmrh, I have updated the OSD on GCP architecture model images so they have the same look and feel of the ROSA architecture ones. Can you please take a quick look to ensure they are correct? Many thanks.

**Comment by svmrh** [comment]
@AedinC : Thanks a lot for following up on the diagrams. I noticed the diagram for "Private OpenShift Dedicated on Google Cloud Platform (GCP) with Private Service Connect architecture model" is inline with the [OSD Architecture Diagrams slide deck](https://docs.google.com/presentation/d/1VvvpAeJzTPKdVO9SSs8knpRDY6vVs7x59unZesvGZnM/edit?usp=sharing) . 

However, the other two diagrams are not identical. 

- Private OpenShift Dedicated on Google Cloud Platform (GCP) without Private Service Connect (PSC) architecture model
- Public OpenShift Dedicated on Google Cloud Platform (GCP) architecture model

@michaelryanmcneill - can you also review these diagrams, please?
https://docs.openshift.com/dedicated/architecture/osd-architecture-models-gcp.html

**Comment by michaelryanmcneill** [comment]
The only thing I noticed is that in the following models, API is put in parentheses when it shouldn't be. 
- Private OpenShift Dedicated on Google Cloud Platform (GCP) without Private Service Connect (PSC) architecture model
- Public OpenShift Dedicated on Google Cloud Platform (GCP) architecture model

Other than that, these look good to me.

**Comment by AedinC** [comment]
Thanks @svmrh and @michaelryanmcneill for the feedback. I have made those changes.

**Pull request merged**
