### PR TITLE
Add platform compatibility note to OSP guides

### LINKED ISSUE #20826: ShiftStack installation guide prereqs need additional callout for platform
### Which section(s) is the issue in?

Related: https://github.com/openshift/openshift-docs/issues/20786

Prerequisites sections of all ShiftStack installation documentation

### What needs fixing?

@racedo Notes that customers may not find the the architecture document linked in the first prerequisite. 

To do: Add child to the first prereq that asks the reader to pay special attention to the Platform Availability section. 

Optional: Link to Support integration matrix. 

Reach: Get Support to add anchor link and intermediate-/long-term notes to OSP section.

### PR DESCRIPTION
**Pull request by maxwelldb**
Resolves #20826

### CODE REVIEW

**Comment by maxwelldb** [comment]
New, from lots of email discussions:

- Describe support as shown in https://access.redhat.com/articles/4679401

**Comment by maxwelldb** [comment]
I'll need to update 4.2 and 4.3 on their own.

**Comment by maxwelldb** [comment]
@openshift/team-documentation Could anyone take a look at this when they have a moment?

**Review by kalexand-rh — COMMENTED** [review]
You might want to update your UPI PR as well.

**Comment by maxwelldb** [comment]
> You might want to update your UPI PR as well.

True, true. @kalexand-rh

**Comment by maxwelldb** [comment]
Manual it is.

**Pull request merged**
