### PR TITLE
SPLAT-527: add external load balancer details for vSphere IPI installs

### PR DESCRIPTION
**Pull request by rvanderp3**
The intention of this PR is to add details to on configuring an external load balancer in the vSphere IPI install modules.

Version(s):
OpenShift 4.11

Issue:
https://issues.redhat.com/browse/SPLAT-409

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc: @GroceryBoyJr

**Comment by jinyunma** [comment]
@rvanderp3 the section of "Configuring an external load balancer" is only inserted into IPI installation on vsphere, missed in all IPI installation docs on VMC.

**Comment by rvanderp3** [comment]
> @rvanderp3 the section of "Configuring an external load balancer" is only inserted into IPI installation on vsphere, missed in all IPI installation docs on VMC.

good catch, this has been addressed.

**Review by GroceryBoyJr — COMMENTED** [review]
/lgtm - please stand by for further review and merge

**Comment by GroceryBoyJr** [comment]
I'm adding a link to this preview build so that the module can be seen in context: https://deploy-preview-45279--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_vmc/installing-restricted-networks-vmc.html#nw-osp-configuring-external-load-balancer_installing-restricted-networks-vmc

**Review by tmalove — COMMENTED** [review]
/LGTM

**Comment by GroceryBoyJr** [comment]
This PR is being closed because the content was recreated for PR 45896 and merged by @jeana-redhat .

**Pull request merged**
