### PR TITLE
BZ-2064084 updating pod restart description

### PR DESCRIPTION
**Pull request by bscott-rh**
[BZ#2064084](https://bugzilla.redhat.com/show_bug.cgi?id=2064084) 

Version(s):
4.8+

[Doc preview](https://51408--docspreview.netlify.app/openshift-enterprise/latest/nodes/pods/nodes-pods-configuring.html#nodes-pods-configuring-restart_nodes-pods-configuring)

### CODE REVIEW

**Comment by bscott-rh** [comment]
@sunilcio Hello Sunil, can you PTAL at this small change to the Node restart policy documentation? If this looks good, can you let me know if this applies to versions 4.8+? Thank you

**Comment by bscott-rh** [comment]
@sunilcio hello Sunil, have you had a chance to look at this PR? thank you

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Pull request merged**
