### PR TITLE
Updating optional steps per the style guide

### PR DESCRIPTION
**Pull request by kalexand-rh**
We had a few different formats for optional steps. The style guide uses the following format:

> Optional: Click Set password. In the Password field, type a password.

@openshift/team-documentation, PTAL

### CODE REVIEW

**Comment by mburke5678** [comment]
@kalexand-rh LGTM. Nice to have them consistent. Just curious, which style guide? IBM?

**Comment by kalexand-rh** [comment]
@mburke5678, thanks! Yes, the IBM style guide.

**Comment by jboxman** [comment]
Makes sense.

**Comment by kalexand-rh** [comment]
Great! Then I'm going to merge and add this change to the meeting agenda.

**Pull request merged**
