### PR TITLE
BZ1709936: Information bubble contains contradictory statement on feature availability

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1709936

Preview: [First note under Enabling Network Policy](http://file.rdu.redhat.com/~mburke/BZ1709936-fix-network-v1-note/admin_guide/managing_networking.html#admin-guide-networking-networkpolicy).

### CODE REVIEW

**Comment by mburke5678** [comment]
@bmeng @nekop @sheriff-rh  
Hello -- Forgive me if this older issue is no longer appropriate for your current roles. You were involved in adding and/or editing this note. [[1](https://github.com/openshift/openshift-docs/pull/11605/files#diff-924872855f9a6ea1a92d8bab741f0914300c225e69d787cc9f57c28a82b16e0fR1298)] [[2](https://github.com/openshift/openshift-docs/pull/14352/files#diff-924872855f9a6ea1a92d8bab741f0914300c225e69d787cc9f57c28a82b16e0fR1377)]

This is an old issue from 3.11 raised by @rvanderp3 that caught my attention as it does seem to be contradictory. 

`The v1 NetworkPolicy features are available only in OpenShift Container Platform. This means that egress policy types, IPBlock, and combining podSelector and namespaceSelector are not available in OpenShift Container Platform.`

I read this to mean that the listed features are in v1. Which makes it confusing that the features are _available only in OCP_, but _not available in OCP_. 

After much thinking, I assume that the listed features are in v1beta1? Thus, with the move to v1, the features are no longer available in OCP?

Also, I think that the original wording in [[1](https://github.com/openshift/openshift-docs/pull/11605/files#diff-924872855f9a6ea1a92d8bab741f0914300c225e69d787cc9f57c28a82b16e0fR1298)] is correct. The change in [[2](https://github.com/openshift/openshift-docs/pull/14352/files#diff-924872855f9a6ea1a92d8bab741f0914300c225e69d787cc9f57c28a82b16e0fR1377)] makes it seem that the v1 features are in OpenShift but nowhere else. 

Any thoughts would be appreciated.

**Comment by mburke5678** [comment]
@bmeng @nekop @sheriff-rh PTAL

**Comment by sheriff-rh** [comment]
I believe the original wording is fine too. As you said, this was a long time ago, I can't recall why this change was made or written (by me, unfortunately) in such a confusing manner.  My advice would be to clearly state what IS supported, rather than what is NOT supported/available. Hope this helps!

**Comment by bmeng** [comment]
I am not sure if the `v1` and `v1beta1` statement are correct here. Since the features may be added to v1 api group already.

Maybe we just mention the features we do not support, but do not mention the api version

**Comment by mburke5678** [comment]
@bmeng Do you know how to determine which features we do not support?

**Comment by mburke5678** [comment]
@bmeng PTAL and let me know if this meets your expectations. Thank you.

**Comment by lmurthyrh** [comment]
@weinliu@redhat.com - Can you please review this PR?

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
