### PR TITLE
OSDOCS-3363: Add ROSA and OSD x86 worker instance types

### PR DESCRIPTION
**Pull request by bmcelvee**
Version(s):
4.10, 4.11

Issue:
https://issues.redhat.com/browse/OSDOCS-3363
https://issues.redhat.com/browse/OSDOCS-3369

Link to docs preview:
ROSA: http://file.rdu.redhat.com/bmcelvee/20221207/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-aws-compute-types_rosa-service-definition
OSD: http://file.rdu.redhat.com/bmcelvee/20221207/osd_architecture/osd_policy/osd-service-definition.html#aws-compute-types-ccs_osd-service-definition

### CODE REVIEW

**Comment by arendej** [comment]
I noticed some intermixed capitalised instance sizes to fix.

**Review by jeana-redhat — APPROVED** [review]
A bit hard to check, but I dumped all the lists in an editor and had it highlight the vCPU and GiB labels (case-sensitively) and everything looked consistent to me.

**Comment by bmcelvee** [comment]
Hi @xueli181114 and @yuwang-RH! Would you mind reviewing this PR, please? Thank you!

**Pull request merged**
