### PR TITLE
OSDOCS-3340: Changing the title of the update chapters

### PR DESCRIPTION
**Pull request by sagidlow**
Applies to 4.6+
JIRA: https://issues.redhat.com/browse/OSDOCS-3340
QE ack not needed.
SME ack needed.
Preview Links:

- [Updating a cluster using the web console](https://deploy-preview-43007--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-within-minor.html)
- [Updating a cluster using the CLI](https://deploy-preview-43007--osdocs.netlify.app/openshift-enterprise/latest/updating/updating-cluster-cli.html)

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Review by adellape — COMMENTED** [review]
Just one instance of the "within a version" title still in:

https://github.com/openshift/openshift-docs/blame/main/updating/updating-cluster-within-minor.adoc#L13

**Review by adellape — APPROVED** [review]

**Pull request merged**
