### PR TITLE
BZ#2033767 Update ARM endpoint example

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=2033767

Preview: https://deploy-preview-40018--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra#installation-initializing-manual_installing-azure-stack-hub-user-infra

### CODE REVIEW

**Comment by codyhoag** [comment]
@mgahagan73 can you verify? Thanks!

**Comment by mjpytlak** [comment]
@codyhoag peer review LGTM.

**Pull request merged**
