### PR TITLE
Adding in Online Known Issues + Updated Distro_Map

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
Discussed with Online team and they do not want to maintain release notes. They only want a topic called Known Issues. https://blog.openshift.com/tag/release/ is their equivalent of release notes.

**Comment by ahardin-rh** [comment]
@tiwillia This is what I have so far. PTAL. 

@aheslin This is put in place instead of Release Notes

**Comment by tiwillia** [comment]
@ahardin-rh is the page called "Release Notes"? I'm not sure I like that name, just because we won't be communicating releases to users, only known issues.

Also, the single bug we have on the list is not externally visible, have we OK'd it with anyone to reveal details of that bug in docs? Do we often include private bugs in release notes?

**Comment by ahardin-rh** [comment]
@tiwillia Sorry, I wasn't clear. The page will be called Known Issues and will live under the About section. I updated the PR to remove the old (unbuilt) Release Notes page to get rid of any confusion. As for the described bug, this is the only one I was given to doc so far. However, if it is private, I can remove it.

**Review by tiwillia — APPROVED** [review]
:+1:

**Comment by ahardin-rh** [comment]
@abhgupta Can you please confirm that this BZ should be public?

**Comment by ahardin-rh** [comment]
Discussed with @abhgupta and removed the BZ# and link. The rest is approved.

**Comment by ahardin-rh** [comment]
Today I realized that the About page does not build in the Customer Portal. I discussed this with Tim and as a workaround we are including Known Issues as a section under Release Notes, but Release Notes simply points to the blog and Known Issues section.

**Comment by ahardin-rh** [comment]
Some adjustments made in https://github.com/openshift/openshift-docs/pull/4283

**Pull request merged**
