### PR TITLE
nodejs version change

### PR DESCRIPTION
**Pull request by Preeticp**
This PR needs to be cherry picked to all the 4. x versions of OCP docs and is reviewed by the SME

### CODE REVIEW

**Comment by siamaksade** [comment]
I suspect this section needs a change as well. @akram can confirm:
https://docs.openshift.com/container-platform/4.4/openshift_images/using_images/images-other-jenkins-agent.html#images-other-jenkins-agent-images_images-other-jenkins-agent

**Comment by akram** [comment]
hi @Preeticp , indeed we also need the change in the section pointed by @siamaksade

**Review by jkhelil — APPROVED** [review]

**Comment by jboxman** [comment]
@Preeticp, can you squash commit and force-push? Thanks!

**Comment by Preeticp** [comment]
@jboxman squashed the commits. Thank you.

**Comment by jboxman** [comment]
@Preeticp, this conflicts for 4.2, will need to look to understand why.

**Pull request merged**
