### PR TITLE
[OSDOCS-7478]: Role name is not precise for GCP service account

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.13+
Issue:

https://issues.redhat.com/browse/OSDOCS-7478
Link to docs preview:

https://66312--docspreview.netlify.app/openshift-dedicated/latest/osd_install_access_delete_cluster/creating-a-gcp-cluster#osd-create-gcp-cluster-ccs_osd-creating-a-cluster-on-gcp
QE review:
- [x] QE has approved this change.

Additional information:

image

### CODE REVIEW

**Comment by mletalie** [comment]
image

**Review by jeana-redhat — APPROVED** [review]
FYI your preview link has the wrong PR number in it. I was really scratching my head wondering what Netlify was doing :sweat_smile: Anyway I found it and LGTM!

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by mletalie** [comment]
> FYI your preview link has the wrong PR number in it. I was really scratching my head wondering what Netlify was doing 😅 Anyway I found it and LGTM!
> 
> /remove-label peer-review-in-progress /remove-label peer-review-needed /label peer-review-done

Thanks @jeana-redhat, appreciate the heads up!

**Pull request merged**
