### PR TITLE
Fixed link to Routes.adoc

### PR DESCRIPTION
**Pull request by ghost**
@jiri-fiala Please review. This is a follow-up to https://github.com/openshift/openshift-docs/issues/6491.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
No rev history needed.

**Review by jiri-fiala — APPROVED** [review]
lgtm

(It looks like there's a 301 redirect on `https://docs.openshift.com/online/architecture/core_concepts/routes.html` these days, that redirects this to [the correct document](https://docs.openshift.com/online/architecture/networking/routes.html) anyway.)

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL. No rev history needed.

**Comment by mburke5678** [comment]
@tmorriso-rh LGTM

**Pull request merged**
