### PR TITLE
OSDOCS-1612 Update AWS AMIs for 4.7

### PR DESCRIPTION
**Pull request by codyhoag**
https://issues.redhat.com/browse/OSDOCS-1612

### CODE REVIEW

**Comment by codyhoag** [comment]
@yunjiang29 PTAL

**Comment by yunjiang29** [comment]
@codyhoag LGTM

**Comment by codyhoag** [comment]
Preview: http://file.rdu.redhat.com/~choag/011321/aws-amis-4-7/installing/installing_aws/installing-aws-user-infra.html#installation-aws-user-infra-rhcos-ami_installing-aws-user-infra

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Pull request merged**
