### PR TITLE
OCPBUGS#3574: Add `spec.installNamespace` field to example CRs

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Version(s): 4.16

Issue: [OCPBUGS-35724](https://issues.redhat.com/browse/OCPBUGS-35724)

Link to docs preview:
* https://77639--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/arch/olmv1-operator-controller.html#olmv1-clusterextension-api
* https://77639--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/arch/olmv1-operator-controller.html#olmv1-about-target-versions_olmv1-operator-controller
* https://77639--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html#olmv1-version-range-comparisons_olmv1-installing-operator
* https://77639--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html#olmv1-about-target-versions_olmv1-installing-operator
* https://77639--ocpdocs-pr.netlify.app/openshift-enterprise/latest/operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.html#olmv1-forcing-an-update-or-rollback_olmv1-installing-operator

QE review:
- [x] QE has approved this change.

Additional information:

*NOTE*: This PR does not add the `spec.installNamespace` field to the modules for installing and updating cluster extensions. That content is fixed in #77274

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@jianzhangbjz PTAL

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Review by jldohmann — APPROVED** [review]
LGTM!

**Pull request merged**
