### PR TITLE
BZ 1831069: changing tuning to cnv-tuning

### PR DESCRIPTION
**Pull request by ousleyp**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1831069

After discussing this with @nellyc, I'm aligning the docs with reality :) 

CP to 4.3 (applies to CNV 2.2 docs), 4.4, and 4.5

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
LGTM

**Comment by ousleyp** [comment]
@myakove or @nellyc can you please verify this fix for BZ 1831069? thanks!

**Comment by myakove** [comment]
LGTM.
Once merged we can verify the bug.

**Pull request merged**
