### PR TITLE
[WIP] Kubernetes deployments

### PR DESCRIPTION
**Pull request by 0xmichalis**
@mfojtik still WIP but mostly done I think

https://trello.com/c/oAlPryPh/793-3-need-to-document-how-to-use-upstream-deployments

### CODE REVIEW

**Comment by adellape** [comment]
@kargakis Can you confirm my observations on these changes? Just to make sure I get what's being proposed so far.

- It looks like the main content for this PR is the new `deployments.adoc`, which mostly serves to describe the differences between kube deployments and openshift deploymentconfigs.
- The renamed `deployments.adoc` -> `deployment_configs.adoc` is largely unchanged.
- For actual info / usage on kube deployments, we're linking to the upstream kube docs (http://kubernetes.io/docs/user-guide/deployments/).

I have a WIP PR (https://github.com/openshift/openshift-docs/pull/3179) that breaks up the old, enormous `deployments.adoc` file into a subdirectory of multiple topics:

http://file.rdu.redhat.com/~adellape/110816/deployments_breakup/dev_guide/deployments/how_deployments_work.html

I can take your content/commits here and work it into the new subdirectory structure of my https://github.com/openshift/openshift-docs/pull/3179, but I want to make sure I understand to what lengths we want to document kube deployments in OpenShift docs, during this tech preview period (in particular, thinking about OCP 3.4). cc @mfojtik

**Comment by kargakis** [comment]
@adellape cool work in #3179! You've got it right about this PR. Let me finish the second commit and then you can take it over. I will remove the file change and include the change in a separate new file.

**Comment by mfojtik** [comment]
@kargakis I think we should also highlight when to choose Deployments over DeploymentConfigs (I guess we will be getting that questions sooner or latest). Initially I would say you can use upstream Deployments when you don't plan to have any hooks or run any custom strategies and you don't want to use ImageStream. We should mention that Deployments are supported sorely to make sure that the upstream examples/projects that use the Deployments over DeploymentConfigs are assured to work smoothly when running on OpenShift.

**Comment by kargakis** [comment]
> @kargakis I think we should also highlight when to choose Deployments over DeploymentConfigs (I guess we will be getting that questions sooner or latest). Initially I would say you can use upstream Deployments when you don't plan to have any hooks or run any custom strategies and you don't want to use ImageStream. We should mention that Deployments are supported sorely to make sure that the upstream examples/projects that use the Deployments over DeploymentConfigs are assured to work smoothly when running on OpenShift.

I would expect the reasons to choose D over DC would stem from the differences highlighted in this doc. We can make it explicit but it will essentially be a reiteration of the differences. Also I don't think we added Deployments just for upstream examples to work in OpenShift but also because Deployments are evolved out of DeploymentConfigs and since they are embraced in Kubernetes and we already have experience with DCs, we can drive their development (Deployments) and merge the two objects into one so the Kubernetes community can take advantage of what we have been using so long.

**Comment by kargakis** [comment]
Superseded by https://github.com/openshift/openshift-docs/pull/3255

**Pull request closed without merging**
