### PR TITLE
OCPBUGS-35079:updates additional resources

### PR DESCRIPTION
**Pull request by JoeAldinger**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OCPBUGS-35079

Link to docs preview:
https://79653--ocpdocs-pr.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#migrate-from-openshift-sdn-additional-resources

QE review:
- [x] QE has approved this change.

Additional information:
@anuragthehatter PTAL

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by anuragthehatter** [comment]
cc @huiran0826 @jechen0648 PTAL

**Pull request merged**
