### PR TITLE
OSDOCS-9768: adds 4.15.0 async release note MicroShift

### PR DESCRIPTION
**Pull request by ShaunaDiaz**
Version(s):
4.15

Issue:
[OSDOCS-9768](https://issues.redhat.com/browse/OSDOCS-9768)

Link to docs preview:
[4.15.0 async relnote](https://72078--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-15-release-notes#microshift-4-15-0-dp)

### CODE REVIEW

**Comment by aldiazRH** [comment]
LGTM!

**Review by kalexand-rh — APPROVED** [review]
Approved to merge during freeze.

**Pull request merged**
