### PR TITLE
virt: Update DPDK checkup's image name

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, the DPDK checkup image name is referring to an internal registry. Update the image name to refer to the public registry.

Version(s):

4.13+

Issue:

Link to docs preview:

https://60485--docspreview.netlify.app/openshift-enterprise/latest/virt/support/monitoring/virt-running-cluster-checkups.html#virt-checking-cluster-dpdk-readiness_virt-running-cluster-checkups

QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by yossisegev — COMMENTED** [review]
LGTM (CNV network QE).
Thanks Orel.

**Comment by apinnick** [comment]
/enterprise-4.13

**Pull request merged**
