### PR TITLE
Delete "Configuring a custom PKI"

### PR DESCRIPTION
**Pull request by Miciah**
Configuring a custom PKI using the proxy configuration is deprecated.  Components that need to trust the ingress controller's default certificate now do so through a mechanism described in [the `default-ingress-cert` enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/ingress/default-ingress-cert-configmap.md).

* `_topic_map.yml`: Delete entry.
* `builds/setting-up-trusted-ca.adoc`: Delete cross-reference.
* `modules/certificate-injection-using-operators.adoc`: Delete file.
* `modules/installation-configure-proxy.adoc`:
* `modules/nw-proxy-configure-object.adoc`: Delete "included in" entries.
* `networking/configuring-a-custom-pki.adoc`: Delete file.
* `networking/ingress-operator.adoc`:
* `operators/olm-configuring-proxy-support.adoc`: Delete cross-references.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Which version is this feature deprecated in?

@lihongan, will you PTAL?

**Comment by lihongan** [comment]
@Miciah will this be deprecated since 4.6? 
BTW, the link of `the default-ingress-cert enhancement` is 404, could you correct the link to the enhancement?

**Comment by Miciah** [comment]
> Which version is this feature deprecated in?

The procedure should be unnecessary as of 4.4.0.

> BTW, the link of `the default-ingress-cert enhancement` is 404, could you correct the link to the enhancement?

Sorry.  I've fixed the link.

**Comment by kalexand-rh** [comment]
Thanks! I've started the change management process that we need to complete before I can merge this PR.

**Comment by jianzhangbjz** [comment]
For OLM, /lgtm

**Comment by lihongan** [comment]
@Miciah I tested it with a cert signed by custom CA in latest 4.6 cluster, without the trustedCA setting, the authentication operator will be degraded and show error as below:
```
    message: 'RouterCertsDegraded: secret/v4-0-config-system-router-certs.spec.data[apps.hongli-pl137.xxxxx.openshift.com] -n openshift-authentication: certificate could not validate route hostname oauth-openshift.apps.hongli-pl137.xxxxx.openshift.com: x509: certificate signed by unknown authority'
    reason: RouterCerts_InvalidServerCertRouterCerts
    status: "True"
    type: Degraded
``` 
here is the test steps:
1. Generating Self-Signed root CA
2. Generating CSR
3. Issuing SSL Server Certificate
4. Replacing the ingress default certificate with the new cert

To make the cluster back to work, two steps below are required and they are part of the content to be removed.
```
oc create configmap user-ca-bundle --from-file=ca-bundle.crt=/path/to/ca.pem -n openshift-config
oc patch proxy/cluster --patch '{"spec":{"trustedCA":{"name":"user-ca-bundle"}}}' --type=merge
```
please correct me if I'm wrong.

**Comment by kalexand-rh** [comment]
@Miciah, do you have an opinion about the degraded auth operator? Is this an expected result, or an auth bug?

**Comment by Miciah** [comment]
The issue with the degraded auth operator is tracked in [BZ#1866818](https://bugzilla.redhat.com/show_bug.cgi?id=1866818) and was fixed in 4.6 in https://github.com/openshift/cluster-authentication-operator/pull/330.  I'll try to find out if https://github.com/openshift/cluster-authentication-operator/pull/330 will be backported to earlier releases.  If it isn't backported, then we'll need to keep the "Configuring a custom PKI" documentation for earlier releases.

**Comment by jboxman** [comment]
@Miciah, any news on this? Thanks!

**Pull request closed without merging**
