### PR TITLE
GH49619: Add provider agnostic to network table

### PR DESCRIPTION
**Pull request by mburke5678**
https://github.com/openshift/openshift-docs/issues/49619

Table 1. Platform networking support.
This table should be updated so that the verbiage matches and it also says 'bare metal or provider agnostic'

Preview: Table 1. [Platform networking support](http://file.rdu.redhat.com/~mburke/winc-fix-networking-table/windows_containers/windows-containers-release-notes-6-x.html#supported-networking).

### CODE REVIEW

**Comment by Anandnatraj** [comment]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
/lgtm

**Pull request merged**
