### PR TITLE
BZ2054660: Ingress controller sharding is not supported in AWS

### PR DESCRIPTION
**Pull request by xenolinux**
OCP version: 4.6+
[Preview ](https://deploy-preview-42336--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator.html#nw-ingress-sharding_configuring-ingress)
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2054660)
QE contact @lihongan

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
assign network-edge QE team @lihongan ^^

**Comment by lihongan** [comment]
This is not true.  @Miciah could you give some advice to enhance it?
see my comments in the doc bug: https://bugzilla.redhat.com/show_bug.cgi?id=2054660#c3

**Comment by Miciah** [comment]
Hongan is correct.  The cited Bugzilla report is inaccurate.  Sharding is supported on all platforms.  The issue in the BZ is not directly related to sharding but is rather related to using `spec.endpointPublishingStrategy.type: LoadBalancerService` and specifying a domain that is outside of the cluster's base domain.

**Comment by xenolinux** [comment]
Okay. As per the comments[1], [2], closing this pull request. Thanks for the review!! @Miciah @lihongan 

[1]https://github.com/openshift/openshift-docs/pull/42336#issuecomment-1049591461
[2]https://github.com/openshift/openshift-docs/pull/42336#issuecomment-1059510554

**Pull request closed without merging**
