### PR TITLE
OBSDOCS-1406: Fix section heading level and move one section

### PR DESCRIPTION
**Pull request by max-cx**
Version(s):

4.12, 4.13, 4.14, 4.15, 4.16, 4.17, 4.18

Issue:

https://issues.redhat.com/browse/OBSDOCS-1406

Link to docs preview:

https://83383--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/otel/otel-configuration-of-instrumentation.html#otel-instrumentation-config_otel-configuration-of-instrumentation

Currently published page: https://docs.openshift.com/container-platform/4.14/observability/otel/otel-configuration-of-instrumentation.html

QE review:
- N/A

Additional information:

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]

**Review by lpettyjo — COMMENTED** [review]
LGTM. 

However, I see in the metadata that you are applying this to 4.12-4.17. I"m assuming that you also want to apply it to 4.18 as well, and I've applied that tag. Please update the metadata accordingly, or let me know otherwise, and I'll remove the tag.

**Review by ShaunaDiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
