### PR TITLE
added warning for F5 router docs

### PR DESCRIPTION
**Pull request by gaurav-nelson**
For https://trello.com/c/W8SALr79/809-document-spike-deprecate-f5router-in-favour-of-container-connectorrouter

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
[Document: [spike] Deprecate F5Router in favour of container connector[router]](https://trello.com/c/W8SALr79/809-document-spike-deprecate-f5router-in-favour-of-container-connectorrouter)

**Comment by gaurav-nelson** [comment]
@rajatchopra PTAL

**Comment by rajatchopra** [comment]
We have to give a link to the f5 container connector solution that will be replacing this integration.

**Comment by gaurav-nelson** [comment]
Thanks @rajatchopra I have modified this to include the links to replacement. PTAL

**Review by rajatchopra — APPROVED** [review]
/lgtm

**Comment by gaurav-nelson** [comment]
@bfallonf PTAL

**Pull request merged**
