### PR TITLE
OSDOCS#10717 adding ca-west-1 region to AWS docs

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.16

Issue:
https://issues.redhat.com/browse/OSDOCS-10717

Link to docs preview:
https://77185--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_aws/installing-aws-account.html#installation-aws-public_installing-aws-account

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@yunjiang29 PTAL at this PR adding ca-west-1 for AWS. Thank you

**Comment by aldiazRH** [comment]
LGTM!

**Pull request merged**
