### PR TITLE
BZ2016892: No longer required for 4.8+

### PR DESCRIPTION
**Pull request by cowgirljessi**
Bug Link:
https://bugzilla.redhat.com/show_bug.cgi?id=2016892
Related PR:
https://github.com/openshift/openshift-docs/pull/39771

### CODE REVIEW

**Comment by cowgirljessi** [comment]
Preview:
https://deploy-preview-39818--osdocs.netlify.app/openshift-enterprise/latest/operators/admin/olm-restricted-networks.html#olm-mirror-catalog_olm-restricted-networks

The doc org changed between 4.8 and 4.9; need QE on this change as well.

@jianzhangbjz please provide QE

**Comment by bmcelvee** [comment]
LGTM!

**Comment by cowgirljessi** [comment]
@jianzhangbjz please check, same bug as https://github.com/openshift/openshift-docs/pull/39771 but different branch due to structuring in 4.8

**Comment by cowgirljessi** [comment]
QE ack already done on https://github.com/openshift/openshift-docs/pull/39771 , going forward with the merge here since it's the same

**Pull request merged**
