### PR TITLE
Bug 1328843, added missing host variables

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1328843

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vikram-redhat As discussed earlier today, the variable that I added seems to be the only missing one associated with this particular case/BZ. Please take a look and let me know what else we should do to satisfy this BZ request. Thanks!

**Comment by vikram-redhat** [comment]
@ahardin-rh . I think this looks good.

**Comment by adellape** [comment]
@ahardin-rh I think I heard something about one of these parameters today, let's sync up tomorrow and confirm before merging.

**Comment by ahardin-rh** [comment]
@adellape Thanks! In the BZ, QE noted that the option openshift_docker_disable_push_dockerhub is not supported for now: https://bugzilla.redhat.com/show_bug.cgi?id=1340723

**Comment by ahardin-rh** [comment]
Removed `*openshift_docker_disable_push_dockerhub*` for now. We will add it back in once it's functioning.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#configuring-host-variables[Installing -> Advanced Installation]
|Updated *openshift_router_selector*` to its new name of *openshift_hosted_router_selector*`.
%

**Pull request merged**
