### PR TITLE
TELCODOCS-1741 - RN-4.16 Telco RAN - software version table

### PR DESCRIPTION
**Pull request by slovern**
[TELCODOCS-1741](https://issues.redhat.com//browse/TELCODOCS-1741) - RN-4.16 Telco RAN - software version table

Version(s): 4.16

Issue: https://issues.redhat.com/browse/TELCODOCS-1741

Link to docs preview: [Telco RAN DU Branch Build validated software components](https://77378--ocpdocs-pr.netlify.app/openshift-enterprise/latest/edge_computing/ztp-preparing-the-hub-cluster.html#ztp-telco-ran-software-versions_ztp-preparing-the-hub-cluster)

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by slovern** [comment]
Thanks for the review @jeana-redhat

**Pull request merged**
