### PR TITLE
TRACING-3227 | Remove misleading comment in distributed tracing

### PR DESCRIPTION
**Pull request by pavolloffay**
Version(s):
All currently supported OCP versions

Issue:
https://issues.redhat.com/browse/TRACING-3227

Link to docs preview:
@rkratky @bburt-rh 

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bburt-rh** [comment]
@pavolloffay - LGTM. As soon as the content removal has QE approval, I will merge it.

**Review by frzifus — APPROVED** [review]

**Review by bburt-rh — APPROVED** [review]

**Pull request merged**
