### PR TITLE
Fix typo in dynamic plugin example

### PR DESCRIPTION
**Pull request by Bloom-P**
Version(s):
4.12+

Issue:
https://issues.redhat.com/browse/OSDOCS-9759

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by opayne1** [comment]
looks good to me pending a QE review cc @XiyunZhao @yapei

**Comment by kalexand-rh** [comment]
This PR needs to target `main` instead of `enterprise-4.15`. @opayne1, do you have a suggestion for a QE reviewer to confirm the change?

**Comment by opayne1** [comment]
@kalexand-rh @Bloom-P @yapei has [verified](https://github.com/openshift/openshift-docs/pull/72029#issuecomment-1979911750) the change. Please retarget to the main branch so we can get this merged.

**Comment by Bloom-P** [comment]
I have opened a new pull request as I was unable to retarget to the main branch.
https://github.com/openshift/openshift-docs/pull/73513 
@opayne1 @yapei  @kalexand-rh

**Pull request closed without merging**
