### PR TITLE
BZ 1255906

### PR DESCRIPTION
**Pull request by bfallonf**
Corrected a field in the Endpoints section, as per BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1255906

Onto tech review now, but will tag for next steps when given the thumbs up.

### CODE REVIEW

**Comment by adellape** [comment]
LGTM

**Comment by bfallonf** [comment]
@adellape I put in a link, but it seems to get screwey when you start a callout with a link:

<3> link:www.blah.com[Endpoints IPs cannot be] ...

Did not work. Odd. So I ended up just linking out from the "cannot be", as shown in here.

**Comment by adellape** [comment]
> it seems to get screwey when you start a callout with a link:

@bfallonf For links to external sites, you don't need the `link:` in front:

https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-to-external-websites

Maybe try that? I was originally thinking more like a "See Kubernetes documentation for more" at the end, but either way, LGTM.

**Comment by bfallonf** [comment]
@adellape K. Thanks for the tip. Edited. Also, as there's not really any extra info in the kubernetes docs, I kept as a in-sentence link. 

If nothing else, should be ok to merge now.

**Pull request merged**
