### PR TITLE
OSDOCS-1807: sr-iov supp x710

### PR DESCRIPTION
**Pull request by mikemckiernan**
Preview link: https://deploy-preview-31255--osdocs.netlify.app/openshift-enterprise/latest/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

The update is in the first bullet.

--------------------
@openshift/team-documention PTAL.

Applies to enterprise-4.8 and milestone Future Release. // Thanks Jeana. Some day, I'll be able to do this job.  I promise.

### CODE REVIEW

**Comment by zshi-redhat** [comment]
The newly added device looks good to me.

/cc @jboxman for doc format review.

**Review by jeana-redhat — APPROVED** [review]
lgtm

**Pull request merged**
