### PR TITLE
Docs: Updates to Egress router DNS proxy mode

### PR DESCRIPTION
**Pull request by pravisankar**
Updated based on feedback on https://github.com/openshift/origin/pull/15409 and https://github.com/openshift/openshift-docs/pull/4854

### CODE REVIEW

**Comment by pravisankar** [comment]
@danwinship  @bfallonf  PTAL

**Comment by bfallonf** [comment]
Thanks @pravisankar . @danwinship , any thoughts or should I go ahead and merge?

**Comment by bfallonf** [comment]
Updated to 3.8 as per conversation in #4854

**Comment by vikram-redhat** [comment]
@bfallonf  I have changed the labels and assigned to you. Will also require QE approval.

**Comment by pravisankar** [comment]
@openshift/team-documentation @bfallonf @knobunc @danwinship  updated, PTAL

**Review by knobunc — APPROVED** [review]
I just want the "why" part, but otherwise it's good.

**Comment by pravisankar** [comment]
@bfallonf @knobunc  updated, PTAL

**Pull request merged**
