### PR TITLE
Expand deployment documentation

### PR DESCRIPTION
**Pull request by ironcladlou**
Introduce rollback documentation. Expand and improve existing deployment docs.

### CODE REVIEW

**Comment by nhr** [comment]
Reviewed; looks good to me.

**Comment by ironcladlou** [comment]
cc @pweil- @pmorie

**Comment by pmorie** [comment]
LGTM

**Comment by pweil-** [comment]
LGTM

**Comment by ironcladlou** [comment]
@nhr tag and bag?

**Comment by nhr** [comment]
Done.

**Comment by nhr** [comment]
Done.

**Pull request merged**
