### PR TITLE
fix links in persistent storage Overview doc

### PR DESCRIPTION
**Pull request by jeffvance**
fix 404s and added a link to the pod storage security doc.

### CODE REVIEW

**Comment by adellape** [comment]
@jeffvance Were you observing the 404s while navigating the source in GitHub? The `link:`s should be to the html files (generated by AsciiBinder and published at docs.openshift) and not the adocs. The xrefs aren't intended to play nice the GitHub preview.

**Comment by jeffvance** [comment]
@adellape yes, you are correct. Sorry that I didn't realize this aspect of submitting a doc PR. I will rework the PR to only include the last sentence and not change any of the links.

**Comment by adellape** [comment]
I think the content in this PR is being handled now in https://github.com/openshift/openshift-docs/pull/1726. Closing here, please re-open if I'm mistaken.

**Comment by jeffvance** [comment]
Yes this pr should be closed.

**Pull request closed without merging**
