### PR TITLE
[MULTIARCH-3446, 3447] oc-mirror add IBM Z and Power architectures

### PR DESCRIPTION
**Pull request by krishnanshruthi**
Version(s): 4.14+

Issue:
 https://issues.redhat.com/browse/MULTIARCH-3446
and
https://issues.redhat.com/browse/MULTIARCH-3447

Link to docs preview:

https://63938--docspreview.netlify.app/openshift-enterprise/latest/installing/disconnected_install/installing-mirroring-disconnected#oc-mirror-imageset-config-params_installing-mirroring-disconnected

@jschintag Pls approve with /lgtm For IBM Z

@alishaIBM Please approve For IBM Power.

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Review by SNiemann15 — CHANGES_REQUESTED** [review]
Please change PR title to: 
[MULTIARCH-3470,3446] oc-mirror add IBM Z and Power architectures

**Review by prb112 — APPROVED** [review]
LGTM

**Comment by krishnanshruthi** [comment]
@subhtk Pls help me get the QE approval. Thanks much!

**Comment by stevsmit** [comment]
lgtm

**Pull request merged**
