### PR TITLE
Adds chunksize MiB to s3 storage docs

### PR DESCRIPTION
**Pull request by stevsmit**
Version(s):
4.17+
Issue:
https://issues.redhat.com/browse/OSDOCS-11612

Link to docs preview:
https://79998--ocpdocs-pr.netlify.app/openshift-enterprise/latest/registry/configuring_registry_storage/configuring-registry-storage-aws-user-infrastructure.html

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xiuwang** [comment]
LGTM

**Comment by stevsmit** [comment]
cherry-pick enterprise-4.17

**Pull request merged**
