### PR TITLE
Changed "Network Operator" table headings to "Network customization".

### PR DESCRIPTION
**Pull request by GroceryBoyJr**

### CODE REVIEW

**Comment by GroceryBoyJr** [comment]
This change applies to OpenShift installing-preparing.adoc This document is for OpenShift 4.7. The total of changes are only to update the row headings in the first two charts on how to choose what OpenShift installation document to use.

**Comment by GroceryBoyJr** [comment]
The location for this change in the end documents is: 
https://docs.openshift.com/container-platform/4.7/installing/installing-preparing.html

**Comment by pneedle-rh** [comment]
@GroceryBoyJr the change LGTM. You could either create another PR or we could manually cherry pick from this PR, to update this for 4.5 and 4.6 in the previous content location too. For those releases, the tables were in the following locations:

https://docs.openshift.com/container-platform/4.5/installing/install_config/installation-types.html
https://docs.openshift.com/container-platform/4.6/installing/install_config/installation-types.html

@sferich888 can you please review this PR? Does this address the requirement that you highlighted during our meeting? Thanks!

**Pull request merged**
