### PR TITLE
Adds known issue OCPBUGS-20548 to 4.14 RNs

### PR DESCRIPTION
**Pull request by jeana-redhat**
Version(s):
4.14

Issue:
[OSDOCS-8141](https://issues.redhat.com/browse/OSDOCS-8141?focusedId=23365700&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23365700)

Link to docs preview:
[Link to section immediately below](https://67070--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-asynchronous-errata-updates), scroll up :slightly_smiling_face: 

QE review:
- [x] QE has approved this change. (QE request to add this via Jira linked above)

Additional information:

### CODE REVIEW

**Comment by jeana-redhat** [comment]
@kalexand-rh requesting a merge exception for a missed bug text :bow:

**Review by kalexand-rh — APPROVED** [review]
When this passes peer review, it's fine to merge.

**Pull request merged**
