### PR TITLE
OSDOCS-4744: 4.8 changes

### PR DESCRIPTION
**Pull request by skopacz1**
[OSDOCS-4744](https://issues.redhat.com/browse/OSDOCS-4744)

This is the **4.8 PR** of #55448

**Current/live documentation**:
https://docs.openshift.com/container-platform/4.8/updating/updating-restricted-network-cluster/restricted-network-update-osus.html#update-service-mirror-release_updating-restricted-network-cluster-osus
and
https://docs.openshift.com/container-platform/4.8/updating/updating-restricted-network-cluster/restricted-network-update.html#updating-restricted-network-mirror-host

**Preview**: http://file.bos.redhat.com/skopacz/4744_4.8/updating/updating-restricted-network-cluster/mirroring-image-repository.html

### CODE REVIEW

**Comment by skopacz1** [comment]
@shellyyang1989 PTAL

**Comment by mburke5678** [comment]
@skopacz1 LGTM. Are we still merging to 4.8? We aren't publishing that branch on a daily basis.

**Comment by skopacz1** [comment]
@mburke5678 I got the go ahead from Kathryn to merge this one PR, which was in progress by the time 4.8 support was cut off. I just have to let them know when this is merged so the new changes can be published manually.

**Pull request merged**
