### PR TITLE
BZ1531449 - Added cloud integration note in Architecture

### PR DESCRIPTION
**Pull request by bobfuru**
Ready for SME review

### CODE REVIEW

**Comment by bobfuru** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1531449

**Comment by bobfuru** [comment]
@derekwaynecarr This is ready for review. Please let me know if the location and wording make sense, and if you have any other suggestions or edits. Thanks.

**Comment by vikram-redhat** [comment]
@derekwaynecarr - bump.

**Comment by bobfuru** [comment]
Approved by SME, change made on master-3 for CP to 3.9, 3.10, 3.11. Relates to [PR 16158 ](https://github.com/openshift/openshift-docs/pull/16158/), where note was added to master for 4.1, 4.2.

Content location has changed from 3.x (architecture/core_concepts/pods_and_services.adoc)
/to 4.x (modules/nodes-pods-configuring-restart.adoc), so note has been placed in same text location.

[BZ 1531449](https://bugzilla.redhat.com/show_bug.cgi?id=1531449)

@openshfit/team-documentation Peer Review Needed

**Comment by bobfuru** [comment]
Updated note approved by SME, squashed commits on master for CP to 3.9, 3.10, 3.11. Relates to [PR 16158](https://github.com/openshift/openshift-docs/pull/16158), where note was added to master for 4.1, 4.2.

[BZ 1531449](https://bugzilla.redhat.com/show_bug.cgi?id=1531449)

@openshift/team-documentation Peer Review Needed

**Review by adellape — APPROVED** [review]

**Pull request merged**
