### PR TITLE
sriov: add runtime config example for deployment

### PR DESCRIPTION
**Pull request by zenghui-shi**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
/cc @jboxman 

There are two BZs related to this topic, I'm adding an example of runtime config for deployment in this PR.
1) https://bugzilla.redhat.com/show_bug.cgi?id=1846333
2) https://bugzilla.redhat.com/show_bug.cgi?id=1840962

This will need be backported to 4.5/4.4/4.3 once merged.

**Comment by jboxman** [comment]
@zshi-redhat, because the content for SR-IOV continues to grow, it isn't always clear what the proper placement is.

It doesn't look like the Deployment specifically relates to _Configuring a SR-IOV network attachment_, so it might be better placed elsewhere. It doesn't look like it is uniquely specific to SR-IOV hardware networks?

**Comment by zshi-redhat** [comment]
> @zshi-redhat, because the content for SR-IOV continues to grow, it isn't always clear what the proper placement is.
> 
> It doesn't look like the Deployment specifically relates to _Configuring a SR-IOV network attachment_, so it might be better placed elsewhere. It doesn't look like it is uniquely specific to SR-IOV hardware networks?

@jboxman let me double check with @dougbtv and @s1061123 if they have similar issues with Multus adding other types of additional interfaces such as macvlan.

**Comment by jboxman** [comment]
@zshi-redhat, any news?

**Comment by zshi-redhat** [comment]
> @zshi-redhat, any news?

@jboxman sorry for the late response.
This change is specific to deployment using SR-IOV network-resources-injector. Multus-admission-controller doesn't require the `namespace` configuration. so for current and previous releases, this is required for SR-IOV deployment.

**Comment by zshi-redhat** [comment]
@jboxman ping, any update on this one?

**Comment by jboxman** [comment]
@zshi-redhat I haven't had time to consider where this content ought to live.

**Comment by jboxman** [comment]
@zshi-redhat and it can't merge as is, because a module can have only 1 `=` level header. That's because of our  _mod docs_ guidelines that all of Content Services must follow.

So I have decide if it makes sense to include as a `==` in the same module, or in some other module, or in a new module.

Meanwhile I've begun work on 4.6 content for October.

I'll try to figure this out this week.

Thanks.

**Comment by jboxman** [comment]
@zshi-redhat so this probably doesn't need to be an actual procedure; It makes more sense as an example.

**Comment by zshi-redhat** [comment]
> @zshi-redhat so this probably doesn't need to be an actual procedure; It makes more sense as an example.

cool, Jason, do I need to update the PR or is it ok to review?

**Comment by jboxman** [comment]
@zshi-redhat, just thinking out loud. I'll try to sort it out with a different PR. If it's an example deployment, it might make more sense to include it with the _Adding a Pod to an SR-IOV additional network_ content. But maybe not. OpenShift Virtualization now includes a lot of SR-IOV content directly, so I don't want to blow that up, either.

**Comment by jboxman** [comment]
Refs https://github.com/openshift/openshift-docs/pull/24439.

**Comment by jboxman** [comment]
A proper fix for this involves a lot more work. `k8s.v1.cni.cncf.io/networks` must be discussed separately, possibly as a dedicated topic, covering the basic and advanced (with JSON as a string) methods.

In the meanwhile, I might be able to rework _Adding a Pod to an additional network_ to discuss the advanced configuration instead. The basic string version seems useless. Some advanced configuration is apparently nearly always necessary anyway.

Then for the SR-IOV specific content, I can include a note about these BZs.

**Pull request closed without merging**
