### PR TITLE
BZ-1955683:Windows MachineSet diskDiB change disk size but doesn't affect the partition size

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1955683

Preview:  [Sample YAML for a Windows MachineSet object on vSphere](https://deploy-preview-43943--osdocs.netlify.app/openshift-enterprise/latest/windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.html#windows-machineset-vsphere_creating-windows-machineset-vsphere)

### CODE REVIEW

**Comment by mburke5678** [comment]
rbohne@redhat.com PTAL

**Comment by rbo** [comment]
LGTM

**Comment by mburke5678** [comment]
@sgaoshang You reviewed changes to this module previously. Is this an issue you can review? Thank you in advance.

**Pull request merged**
