### PR TITLE
BZ 1575933 - Add Azure File Object Definition section

### PR DESCRIPTION
**Pull request by ghost**
https://bugzilla.redhat.com/show_bug.cgi?id=1575933

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@jhou1 @liangxia QE review needed.

**Comment by liangxia** [comment]
@weherdh  Please check.

**Comment by weherdh** [comment]
This update is LGTM, thanks.

**Comment by tmorriso-rh** [comment]
@openshift/team-documentation PTAL.

**Comment by ahardin-rh** [comment]
@tmorriso-rh Just one comment from me. Otherwise, looks good!

**Pull request merged**
