### PR TITLE
Bug 1436817 added console and API port variables

### PR DESCRIPTION
**Pull request by mburke5678**

### CODE REVIEW

**Comment by mburke5678** [comment]
@thoraxe PTAL

Related to https://github.com/openshift/openshift-docs/issues/1616
https://bugzilla.redhat.com/show_bug.cgi?id=1436817

**Comment by thoraxe** [comment]
LGTM

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL to close an old, old issue.

**Comment by bmcelvee** [comment]
LGTM 🎆

**Comment by mburke5678** [comment]
[rev_history]
|xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Advanced Installation]
|Added information on xref:../install_config/install/advanced_install.adoc#advanced-master-ports[configuring the default ports used by the master API and web console].
%

**Comment by adellape** [comment]
@mburke5678 Reminder this needs labels/milestone.

**Comment by mburke5678** [comment]
@thoraxe I assume this issue affects 3.4+.

**Comment by thoraxe** [comment]
@mburke5678 I can't say for sure what version it started at. You'd have to go back and figure out when those variables were added as options to be fed to the installer. That would give you the "first" version...

Someone from productization might be able to help answer that.

**Pull request merged**
