### PR TITLE
4-6 Release Notes for Azure and GCP MachineSet non-guaranteed instances

### PR DESCRIPTION
**Pull request by lbarbeevargas**
Adding release notes for both Azure and GCP MachineSet spot/preemptible instances.

@JoelSpeed @enxebre PTAL for 4.6.

### CODE REVIEW

**Comment by lbarbeevargas** [comment]
Preview is available [here](http://file.bos.redhat.com/lbarbeev/09162020/4.6-release-notes-azure-gcp-non-guaranteed-instances/release_notes/ocp-4-6-release-notes.html#ocp-4-6-machine-api).

**Comment by lbarbeevargas** [comment]
@JoelSpeed @enxebre Bump. PTAL for 4.6, thank you!

**Comment by lbarbeevargas** [comment]
[New preview](http://file.bos.redhat.com/lbarbeev/09252020/4-6-release-notes-azure-gcp-non-guaranteed-instances/release_notes/ocp-4-6-release-notes.html#ocp-4-6-machine-api) with small updates based on peer review feedback in [PR-25427](https://github.com/openshift/openshift-docs/pull/25427).

@openshift/team-documentation PTAL.
@JoelSpeed @enxebre Please take a final look.

**Review by sheriff-rh — APPROVED** [review]
LGTM! 🎉 🥇 🌮

**Review by JoelSpeed — APPROVED** [review]
LGTM, thanks!

**Comment by lbarbeevargas** [comment]
Updated the commented-out links to the Spot VM and preemptible VM instance modules to reflect the headings for those modules.

**Pull request merged**
