### PR TITLE
Remove workaround for preventing Pods from being scheduled on control plane machines

### LINKED ISSUE #22901: [enterprise-4.5] Edit suggested in file installing/installing_azure/installing-azure-user-infra.adoc
### Which section(s) is the issue in?
Step 4 under:
https://docs.openshift.com/container-platform/4.5/installing/installing_azure/installing-azure-user-infra.html#installation-user-infra-generate-k8s-manifest-ignition_installing-azure-user-infra

### What needs fixing?
The entirety of step 4 may be removed because it is no longer necessary in 4.5. The edit to manifests/cluster-scheduler-02-config.yml already has mastersSchedulable set to False

### PR DESCRIPTION
**Pull request by codyhoag**
From #22901

### CODE REVIEW

**Comment by codyhoag** [comment]
@mgahagan73 can you review this? Also, this step is referenced throughout many cloud provider docs (GCP, bare metal, Azure, AWS, etc.). Does this removal also apply to all of those scenarios?

**Comment by codyhoag** [comment]
@jianlinliu can you review this? This step is referenced throughout many cloud provider docs (GCP, bare metal, Azure, AWS, vSphere, OpenStack, and IBM Z). Does this removal also apply to all of those scenarios?

**Comment by jianlinliu** [comment]
Wahoo, this is big change. Actually I did not get the point why we have this change. Especially we had a long discussion why introduce the edit to manifests/cluster-scheduler-02-config.yml setting mastersSchedulable set to False when worker replica is set to 0.
I run some testing again today.
`
[root@preserve-jialiu-ansible ~]# openshift-install version
openshift-install 4.5.0-0.nightly-2020-06-19-024326
built from commit 2874fb3204089822b561f98a0a3fe7b15a84da00
release image registry.svc.ci.openshift.org/ocp/release@sha256:32543706709a1b5439add6ed8156122941161adc582b6de44093fce8587cdb8e
[root@preserve-jialiu-ansible ~]# openshift-install create manifests --dir demo8
INFO Credentials loaded from file "/root/.azure/osServicePrincipal.json" 
INFO Consuming Install Config from target directory 
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings 
`
If not change MastersSchedulable to False, that will make master become schedulable, that will bring a lot of unexpected behavir for cluster .

**Comment by codyhoag** [comment]
@jianlinliu this was originally suggested in #22901 as an edit for Azure UPI. It was stated there that the `manifests/cluster-scheduler-02-config.yml` already has `mastersSchedulable` set to `False` in that context. I was checking if that was the case for all cloud providers.

**Comment by jianlinliu** [comment]
I already checked https://github.com/openshift/openshift-docs/issues/22901, but in this PR, replica is set to 0, masters will be set mastersSchedulable=True. I think my previous comment already listed the evidence.

**Comment by codyhoag** [comment]
@jianlinliu  so to confirm, this step is necessary for the docs that instruct setting the `compute.replicas` to `0`? Our [Azure](https://docs.openshift.com/container-platform/4.4/installing/installing_azure/installing-azure-user-infra.html) and [OpenStack](https://docs.openshift.com/container-platform/4.4/installing/installing_openstack/uninstalling-openstack-user.html) UPI docs appear to be the only docs that suggest the step I've removed in this PR, but don't explicitly instruct setting the replica to `0` (this doc module is referenced many times throughout our installation docs). All other cloud-provider procedures have both (e.g., [AWS](https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-user-infra.html), [GCP](https://docs.openshift.com/container-platform/4.4/installing/installing_gcp/installing-gcp-user-infra.html), etc.). Your test results suggest Azure does still need this step, so I'm confused why QE suggested it be removed in #22901.

I'll proceed to close this PR if the step is still required for all cloud providers. Let me know. Thanks!

**Comment by jianlinliu** [comment]
> this step is necessary for the docs that instruct setting the compute.replicas to 0?
Yes. Pls refer to https://bugzilla.redhat.com/show_bug.cgi?id=1738456
> Our Azure and OpenStack UPI docs appear to be the only docs that suggest the step I've removed in this PR, but don't explicitly instruct setting the replica to 0.
Interesting. I thought all platforms should keep the consistent behaviour (set replica to 0, set mastersSchedulable to false), but now sound like azure and OpenStack did not follow the common steps. If the previous steps did not mentioned set replica to 0, then maybe you can remove this explicitly instruct setting about mastersSchedulable. It is better to confirm with requester about this PR. @mgahagan73 . But personally I keep mastersSchedulable=false is a MUST, the step being removed in this PR is harmless.

**Comment by codyhoag** [comment]
@mgahagan73 based on Jianlin's feedback, perhaps this is something that should be reaffirmed with the installer team? It seems there may be a disconnect somewhere.

FYI, our [Azure UPI 4.3 docs](https://docs.openshift.com/container-platform/4.3/installing/installing_azure/installing-azure-user-infra.html) don't explicitly instruct setting replicas to `0` currently, so based on your previous comments, that'll need to be updated if we move forward with this:

> this was left over from instructions in the 4.3 timeframe where the user was directed to set `compute.replicas` to `0` in the `install-config.yaml`

Let me know. I'm happy to add the conditional for Azure (and possibly OpenStack) if this is a necessary change. Thanks!

**Pull request closed without merging**
