### PR TITLE
GH#53512: Fix resource requests and limits in the example of Scheduling Pods with resource requests 

### PR DESCRIPTION
**Pull request by auropondy**
fix for the issue : openshift#53512

Version(s):

Issue:

Link to docs preview:

https://docs.openshift.com/container-platform/4.11/security/compliance_operator/compliance-scans.html#compliance-scheduling-pods-with-resource-requests_compliance-operator-scans

QE review:
- [ ] QE has approved this change.

Additional information:

 @openshift/team-documentation

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@rhmdnd would you mind reviewing when you have a chance? I think the callouts we have in place are defined correctly in the documentation, however the issue referenced in the description (https://github.com/openshift/openshift-docs/issues/53512) says otherwise. 

Thanks!

**Comment by sheriff-rh** [comment]
Build preview:
[Scheduling Pods with resource requests](https://55135--docspreview.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-scans.html#compliance-scheduling-pods-with-resource-requests_compliance-operator-scans)

**Comment by sheriff-rh** [comment]
Hi @auropondy , I have spoken with engineering regarding this topic and they suggested different changes. I recommend closing this PR in favor of their suggestions in https://github.com/openshift/openshift-docs/pull/55479. Thank you!

**Comment by auropondy** [comment]
Closing this PR in favour of #55479.

**Pull request closed without merging**
