### PR TITLE
Removed reference to upstream

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1537937

### CODE REVIEW

**Comment by qinpingli** [comment]
In the table still is kube 1.9 or kube 1.10

**Comment by ahardin-rh** [comment]
@qinpingli Updated. Thank you!

**Comment by ahardin-rh** [comment]
@openshift/team-documentation PTAL

**Comment by kalexand-rh** [comment]
That looks good to me. :)

**Comment by qinpingli** [comment]
LGTM

**Pull request merged**
