### PR TITLE
ocpbugs23429m: fixing indentation error

### PR DESCRIPTION
**Pull request by DCChadwick**
Version(s): 4.14+

Issue: [OCPBUGS-23429](https://issues.redhat.com/browse/OCPBUGS-23429)

Link to docs preview: https://73209--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/install_config/enabling-cgroup-v1#nodes-clusters-cgroups-2-install_nodes-cluster-cgroups-1

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by DCChadwick** [comment]
@sunilcio This PR is ready for QE review.

**Comment by dfitzmau** [comment]
/remove-label peer-review-in-progress

/label peer-review-done

LGTM

**Pull request merged**
