### PR TITLE
Update getting token for automation

### PR DESCRIPTION
**Pull request by aweiteka**
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@aweiteka LGTM. Is this targeting OCP 3.6?

**Comment by aweiteka** [comment]
> Is this targeting OCP 3.6?

It works in 3.5 (possibly earlier) but whatever makes the most sense.

**Comment by ahardin-rh** [comment]
Thank you!

**Comment by ahardin-rh** [comment]
No release history needed

**Pull request merged**
