### PR TITLE
Remove Alibaba step in ASH install docs

### PR DESCRIPTION
**Pull request by mburke5678**
Per @mjpytlak in Slack

Removed all Alibaba artifacts from `manually-create-identity-access-management.adoc` that were added via https://github.com/openshift/openshift-docs/pull/41083/files#diff-aba65666970ec0397d998aa5b6083c7ea6e71a39ec5b3a3de7e2192bdccf2f26.

The info was added to Alibaba install via https://github.com/openshift/openshift-docs/pull/41083/files#diff-c6f98021c4bef2d720b6a7f7c7dba39d2805e68ba95191c08ebb4ab31e3d9fbf

Preview: [ASH Manually manage cloud credentials](https://deploy-preview-44564--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure_stack_hub/installing-azure-stack-hub-default.html#manually-create-iam_installing-azure-stack-hub-default)
[Alibaba Generating the required installation manifests](https://deploy-preview-44564--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_alibaba/installing-alibaba-customizations.html#manually-creating-alibaba-manifests_installing-alibaba-customizations)

### CODE REVIEW

**Comment by mburke5678** [comment]
@mjpytlak PTAL

**Comment by mjpytlak** [comment]
@mburke5678 Thanks for handling this. LGTM.

**Pull request merged**
