### PR TITLE
HCIDOCS-246: modify supported firmware for baremetal deployment on Dell

### PR DESCRIPTION
**Pull request by johnwilkins**
Added a new firmware version for 15th Gen Dell hardware.

Fixes: [HCIDOCS-246](https://issues.redhat.com//browse/HCIDOCS-246)

See https://issues.redhat.com/browse/HCIDOCS-246 for additional details.

Preview URL: http://jowilkin.com:8080/HCIDOCS-246/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#ipi-install-firmware-requirements-for-installing-with-virtual-media_ipi-install-prerequisites

For release(s): 4.16, 4.15
QE Review: 

- [x] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

### CODE REVIEW

**Comment by johnwilkins** [comment]
@elfosardo can you verify this change?

**Review by opayne1 — COMMENTED** [review]
/lgtm

**Pull request merged**
