### PR TITLE
PR for SRVCOM-3457: Update the Serverless 1.33.3 release notes

### PR DESCRIPTION
**Pull request by kaldesai**
Affected versions: serverless-docs-1.35

**Tracking JIRA:** https://issues.redhat.com/browse/SRVCOM-3457

**Doc preview:** [Serverless 1.33.3 release notes]()

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Comment by tmalove** [comment]
@kaldesai I couldn't access the preview from the link, but found it [here](https://85642--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/serverless-release-notes.html#serverless-rn-1-33-3_serverless-release-notes).

/remove-label peer-review-in-progress
/label peer-review-done
/lgtm

**Comment by nainaz** [comment]
could not see the preview. but found it from the link from above comment. 
LGTM

**Pull request merged**
