### PR TITLE
HCIDOCS-176: Remove Dell idrac9 firmware note

### PR DESCRIPTION
**Pull request by kdrake20**
Fixes: [HCIDOCS-176](https://issues.redhat.com/browse/HCIDOCS-176)

For: Version 4.12+

Doc Preview [here](https://75296--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#ipi-install-firmware-requirements-for-installing-with-virtual-media_ipi-install-prerequisites)

Signed-off-by: Katie Drake kdrake@redhat.com

### CODE REVIEW

**Comment by kdrake20** [comment]
**Who:**
@chadcrum 
@trewest 

**Timestamp:** April 29, 2024 2:18 PM

**Summary:** Hello, could one of you please review my https://github.com/openshift/openshift-docs/pull/75296 for this Jira issue? If changes need to be made, please comment in the PR with the desired updates.

If the PR is correct, please comment /lgtm. Thank you!

**Next Steps:**
- [ ] Receive approval from QE

**Review by cbippley — COMMENTED** [review]
LGTM! Did you get QE to sign off?

**Comment by kdrake20** [comment]
> LGTM! Did you get QE to sign off?

Not yet, but I've pinged them again. I figured I'd ask for a peer review while I was waiting. Thanks!

**Pull request merged**
