### PR TITLE
metering: Remove the stale note about the 4.4 Metering version in the 4.5 installation documentation.

### PR DESCRIPTION
**Pull request by timflannagan**

### CODE REVIEW

**Comment by timflannagan1** [comment]
This needs to be removed from the 4.4 documentation too now that Metering was shipped in 4.4.z.
/cherry-pick enterprise-4.4

**Comment by kalexand-rh** [comment]
@timflannagan1, please set this PR against the `master` branch.

**Comment by timflannagan1** [comment]
@kalexand-rh I might be a bit out of the loop for the openshift-docs workflow as I don't see a dedicated 4.6 branch, but this note isn't present in the master/4.6+ installation notes, which is why I opened this PR against the enterprise-4.5 branch. Is there something I'm missing?

**Comment by kalexand-rh** [comment]
My apologies, @timflannagan1.

**Comment by kalexand-rh** [comment]
@pruan-rht, will you PTAL?

**Review by pruan-rht — COMMENTED** [review]
/lgtm

**Pull request merged**
