### PR TITLE
[enterprise-4.6] Add OVN-Kubernetes egress firewall 8,000 rule limit

### PR DESCRIPTION
**Pull request by jboxman**
- https://issues.redhat.com/browse/OSDOCS-2306

Preview: https://deploy-preview-34537--osdocs.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/configuring-egress-firewall-ovn#limitations-of-an-egress-firewall_configuring-egress-firewall-ovn

### CODE REVIEW

**Comment by jboxman** [comment]
@huiran0826, can you confirm? Thanks!

**Comment by huiran0826** [comment]
I just know  50  is not correct for OVN EgressFirewall rule rule limit, but I am not sure about the exact number. @JacobTanenbaum Can you help confirm it ? Thanks!

**Comment by jboxman** [comment]
@huiran0826 thanks!

**Pull request merged**
