### PR TITLE
Netobservtopic

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.12+

Issue:

Adding the Network Observability topic to the left nav. Eng approves location of topic in this Google Doc: https://docs.google.com/document/d/15BO4tYHTf8TB77p0tAECh5j4iqmVi7eU6ZbeADswWf8/edit

Link to docs preview:
https://52966--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/installing-operators.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jboxman-rh** [comment]
@skrthomas, is this just to add the new section?

**Comment by skrthomas** [comment]
@jboxman Yes, its just adding the section so other writers can also begin adding modules.

**Comment by jboxman-rh** [comment]
@skrthomas LGTM

**Pull request merged**
