### PR TITLE
OCPBUGS#16396: Removed - in vSphere sample YAML file

### PR DESCRIPTION
**Pull request by dfitzmau**
[OCPBUGS-16396](https://issues.redhat.com/browse/OCPBUGS-16396)

Version(s):
4.14 and 4.13

Link to docs preview:
[Sample install-config.yaml file for VMware vSphere](https://62620--docspreview.netlify.app/openshift-enterprise/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html#installation-installer-provisioned-vsphere-config-yaml_installing-vsphere-installer-provisioned-network-customizations)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by r4f4** [comment]
If users were to copy the sample install-config, they'd meet the error
```
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field InstallConfig.controlPlane of type types.MachinePool
```
This PR fixes that.

/lgtm

**Review by skrthomas — APPROVED** [review]
/lgtm

**Pull request merged**
