### PR TITLE
OSDOCS-3848 updated procedure

### PR DESCRIPTION
**Pull request by sheriff-rh**
Version(s):
4.11+

Issue:
https://issues.redhat.com/browse/OSDOCS-3848

Link to docs preview:
[Creating a KubeletConfig CRD to edit kubelet parameters](http://file.rdu.redhat.com/antaylor/osdocs-3848/scalability_and_performance/recommended-host-practices.html#create-a-kubeletconfig-crd-to-edit-kubelet-parameters_recommended-host-practices)

### CODE REVIEW

**Comment by sheriff-rh** [comment]
@paigerube14 please review. Thanks!

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
