### PR TITLE
Operator's O should be in Capital

### PR DESCRIPTION
**Pull request by xenolinux**
Operator's O should be in Capital

Version(s): 4.8+

Issue: None

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by michaelryanpeter** [comment]
@xenolinux It looks like 4.8 needs a manual cherrypick. Would you PTAL?

**Comment by bergerhoffer** [comment]
@xenolinux The CP to 4.8 for this failed, can you please submit the manual cherry pick?

**Comment by xenolinux** [comment]
@bergerhoffer Thanks for noticing this, I had missed this PR. Here is the CP PR for 4.8 -  https://github.com/openshift/openshift-docs/pull/54570

**Pull request merged**
