### PR TITLE
Added information about no resource migration when upgrading to Online Pro

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://trello.com/c/B7ZOqgEW/802-3-document-the-import-export-process-since-there-is-no-resource-migration-in-online-pro

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@damemi @dgoodwin @abhgupta PTAL

**Comment by dgoodwin** [comment]
Hopefully we'll be able to offer something better for this in the future but right now, this LGTM.

**Comment by ahardin-rh** [comment]
@openshift/team-documentation Please peer review

**Comment by mburke5678** [comment]
@ahardin-rh From a grammar standpoint, LGTM.

But, I am not sure what the message is from a usage standpoint. It makes it seem like those commands are for upgrading only, or primarily. And, when performing the upgrade from Starter to Pro, do I primarily care about support for resource migration as a concept? Looking at the "related" Trello, the user wants to "take the work I have done on Starter and move it to Pro."

Maybe as a note:
"If you are upgrading from {product-title} Starter to {product-title} Pro, use `oc export all` to export all your existing objects. {product-title} Pro does not support per-object resource migration."

Does that make sense?

**Comment by ahardin-rh** [comment]
@mburke5678 Thanks! Updated.

**Comment by mburke5678** [comment]
LGTM

**Comment by bfallonf** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
No revision history needed

**Pull request merged**
