### PR TITLE
OSDOCS-12151: adds 4.14.39 relnotes Microshift

### PR DESCRIPTION
**Pull request by aravipra**
Version(s):
4.14

Issue:
[OSDOCS-12151](https://issues.redhat.com/browse/OSDOCS-12151)

Link to docs preview:
[4.1.4.39 async release notes](https://83742--ocpdocs-pr.netlify.app/microshift/latest/microshift_release_notes/microshift-4-14-release-notes.html#microshift-4-14-39-dp_release-notes)

QE review:
* N/A stock text, no other changes

### CODE REVIEW

**Comment by aravipra** [comment]
Only peer review is needed for now. Do not merge the PR until the merge labels are added.

**Review by skrthomas — COMMENTED** [review]
merge review lgtm

**Pull request merged**
