### PR TITLE
Added custom markup to CSS; updated guidelines doc accordingly

### PR DESCRIPTION
**Pull request by Bilhar-rh**
@spurtell @nhr Added the custom markup to stylesheets, if there are no issues I'll merge this. Also updated the guidelines doc to reflect these changes.

### CODE REVIEW

**Comment by nhr** [comment]
Is this based on @sg00dwin's feedback? If so, he should review.

**Comment by nhr** [comment]
Sorry, I may be getting my streams crossed. But what is the context of this change?

**Comment by CowboysFan** [comment]
@nhr Sorry, that should be Custom, not Customer. This is the custom markup to future proof our docs for translation and consistency. I've added styling to markup filenames, replaceables, or parameters so that they render differently from the normal text. This eliminates confusion and makes our content more consistent.

**Comment by nhr** [comment]
Okay; looks good to me.

**Pull request merged**
