### PR TITLE
[SRVCOM-2442] Improve links and linking for restructured content

### PR DESCRIPTION
**Pull request by ochromy**
Version(s):
serverless-docs-1.33+

Issue:
https://issues.redhat.com/browse/SRVCOM-2442

Link to docs preview:
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/about-knative-eventing.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/about-serverless.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/about/serverless-logic-overview.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/functions/serverless-functions-getting-started.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/install/preparing-serverless-install.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/integrations/serverless-pipelines-integration.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/knative-serving/serving-transport-encryption.html
https://84202--ocpdocs-pr.netlify.app/openshift-serverless/latest/observability/admin-metrics/serverless-admin-metrics.html
(link changes, additions)

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
LGTM from QE

**Comment by DCChadwick** [comment]
Looks good to me!

/remove-label peer-review-in-progress
/label peer-review-needed

**Comment by ochromy** [comment]
Thank you @DCChadwick 
/label merge-review-needed

**Comment by jab-rh** [comment]
@ochromy, looks like this doesn't merge cleanly into `1.33`.

**Pull request merged**
