### PR TITLE
OSDOCS-9397: An extraneous character broke autonumbering

### PR DESCRIPTION
**Pull request by johnwilkins**
Fixed an extraneous character that was breaking auto numbering and formatting, and performed some minor edits.

Fixes: [OSDOCS-9397](https://issues.redhat.com//browse/OSDOCS-9397)

See https://issues.redhat.com/browse/OSDOCS-9397 for additional details.

Preview URL: http://184.23.213.161:8080/HCIDOCS-149/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-establishing-communication-between-subnets_ipi-install-installation-workflow

For release(s): 4.15, 4.14
QE Review: 

- [x] QE has approved this change. 

Signed-off-by: John Wilkins <jowilkin@redhat.com>

### CODE REVIEW

**Comment by shipsing** [comment]
@johnwilkins, The PR changes look okay.
Just a quick question: Don't you think the note given in the end of step number 1 and 2: 	
`Adjust the commands to match your actual interface names and gateway.` should be given in the beginning. For example, before the .procedure label or just after step number 1 and 2, we can add this note:
Adjust the commands to match your actual interface names and gateway in the following procedure.

i mean after executing all the sub-steps of step 1 and 2, users get to know that they need to make adjustments based on the interface names and gateway. This information requires to be provided beforehand so that they can make those adjustments while performing those sub-steps, rather after completing the execution.

Since i am new to the peer review squad, i would ask @bburt-rh to give my review the go-ahead. Please wait until Brain applies the peer-review-done label.

**Review by bburt-rh — APPROVED** [review]
LGTM. Thanks @shipsing and @johnwilkins.

**Review by bergerhoffer — COMMENTED** [review]
LGTM for merging!

**Pull request merged**
