### PR TITLE
update pvc limitrange json

### PR DESCRIPTION
**Pull request by mdshuai**
Correct the json format about limitrange pvc admin_guide/limits.adoc
previous pr: https://github.com/openshift/openshift-docs/pull/3084

### CODE REVIEW

**Comment by mdshuai** [comment]
@ahardin-rh @bfallonf  @markturansky help review, thanks.

**Comment by markturansky** [comment]
LGTM!

**Comment by ahardin-rh** [comment]
LGTM. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../admin_guide/limits.adoc#admin-guide-limits[Setting Limit Ranges]
|Updated the PVC limit range within the  xref:../admin_guide/limits.adoc#jsonlimit-range-def[Limit Range Object Definition example].
%

**Pull request merged**
