### PR TITLE
RHDEVDOCS-5090: Update the subscription to the latest in the OCP GitO…

### PR DESCRIPTION
**Pull request by eromanova97**
• **Aligned team**: Dev Tools
• **OCP version for cherry-picking**: enterprise-4.9 and later
• **JIRA issue**: [RHDEVDOCS-5090](https://issues.redhat.com/browse/RHDEVDOCS-5090)
• **Preview page**: [Installing OpenShift GitOps Operator using CLI](https://57994--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/installing-openshift-gitops.html#installing-gitops-operator-using-cli_installing-openshift-gitops)
• **SME Review**: Completed by @iam-veeramalla 
• **QE review**: Completed by @varshab1210 
• **Peer-review**: Completed by @shipsing

### CODE REVIEW

**Comment by ekristova** [comment]
Hello @iam-veeramalla @varshab1210 PTAL and provide feedback. Thank you!

**Review by shipsing — APPROVED** [review]
LGTM @ekristova 
a minor suggestion regarding the content in the beginning of the file:
//
// * installing-openshift-gitops
:_content-type: PROCEDURE
[id="installing-gitops-operator-using-cli_{context}"]
= Installing OpenShift GitOps Operator using CLI

Please refer to this link to add metadata about this file correctly: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#module-file-metadata

Also, please provide the path for the assembly in which this module is included. I guess the path should be /cicd/gitops/installing-openshift-gitops.adoc

We can also use the attribute defined for the GitOps title in all the headings under this assembly --- Installing OpenShift GitOps.

**Pull request merged**
