### PR TITLE
Update tech preview snippet to match OCP docs and SSG

### PR DESCRIPTION
**Pull request by kcarmichael08**
Version(s):

- Merge to `rhacs-docs`
- Cherry pick to `rhacs-docs-3.73`
- Cherry pick to `rhacs-docs-3.74`
 
Issue: N/A

[Link to docs preview
](https://55046--docspreview.netlify.app/openshift-acs/latest/operating/manage-network-policies.html#using-build-time-network-policy-generator) (example of Tech Preview snippet)

QE review: N/A
- [ ] QE has approved this change.

Additional information:

Update snippet to match OCP docs which have been updated to match SSG. See https://github.com/openshift/openshift-docs/pull/54469

### CODE REVIEW

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by kelbrown20 — COMMENTED** [review]
Looks great! 
/lgtm

**Pull request merged**
