### PR TITLE
RHDEVDOCS 5867 enable building standalone doc for Pipelines 1.14

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

main only

Issue:

RHDEVDOCS 5867

Link to docs preview:

n/a

QE review:
- [ ] QE has approved this change.
n/a

Additional information:

This PR enables building a new version of a standalone documentation set on docs.openshift.com. This PR does not alter any documentation content, so no documentation preview is available.

### CODE REVIEW

**Review by libander — APPROVED** [review]
/lgtm

**Review by kalexand-rh — APPROVED** [review]
This is both important and not going to impact OCP GA, so I'm granting it a freeze exception.

**Pull request merged**
