### PR TITLE
Showing two different values for the Number of Secrets in the table

### PR DESCRIPTION
**Pull request by s-dharma**
We are referring document : https://docs.openshift.com/container-platform/4.9/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums-major-releases_object-limits The values for maximum tested Secrets is mentioned 40000 and 80000 both. These two entries are misguiding the customers and creating a confusion. Remove below section from the documented table :
~~~
| Number of secrets
| 40,000
| 40,000
~~~
And keep below section in the document :
~~~
| Number of secrets
| 80,000
| 80,000
~~~
The values are documented correctly for OCP 4.10 and OCP 4.11 . The document fix is required for the documents OCP 4.8 and OCP 4.9 .

Version(s):

Issue:

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by bmcelvee** [comment]
Hi! @Wiharris and @sheriff-rh! Would you mind reviewing this PR, please? Thanks!

**Comment by sheriff-rh** [comment]
Thanks @bmcelvee !

@rsevilla87 can you confirm the correct number of secrets for OCP 4.8 and 4.9? Thanks!

**Comment by rsevilla87** [comment]
> Thanks @bmcelvee !
> 
> @rsevilla87 can you confirm the correct number of secrets for OCP 4.8 and 4.9? Thanks!

80K is correct, lgtm!

**Comment by sheriff-rh** [comment]
@kalexand-rh seeking approval for changes to 4.8 and 4.9 only, as this issue exists only in these branches. Thank you!

**Comment by kalexand-rh** [comment]
That seems reasonable to me. It's fine to try to use the bot to apply this change to 4.8.

**Review by Wiharris — COMMENTED** [review]
Would recommend a preview build to ensure the changes are showing. Otherwise, looks good! 

/LGTM

**Comment by sheriff-rh** [comment]
Thanks William! Build preview added; looks good:
[OpenShift Container Platform tested cluster maximums for major releases](http://file.rdu.redhat.com/antaylor/patch-2/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums-major-releases_object-limits)

/label merge-review-needed

**Pull request merged**
