### PR TITLE
Need to add OperatorHub information in Upgrading cluster logging DOCS

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1782651

### CODE REVIEW

**Comment by mburke5678** [comment]
@gallettilance I added steps to update the `source` in the CSC based on your comment [1] and `source` and `sourceNamespace` in the Subscription based on the Customer Case [2]. I do not see a `source` in my CatalogSource. Can you please let me know if you think this is what is needed to solve the customer concern.


[1] https://coreos.slack.com/archives/C3VS0LV41/p1581974116182700?thread_ts=1581965814.173400&cid=C3VS0LV41
[2] https://access.redhat.com/support/cases/#/case/02535302?commentId=a0a2K00000SfpueQAB

**Comment by mburke5678** [comment]
@anpingli Can you please take a look at this PR? A customer found that they needed to edit the Elasticsearch Operator subscription object in order to upgrade from 4.1 to 4.2. Can you confirm?
```
  -   source: elasticsearch
  -   sourceNamespace: openshift-operators-redhat
  +   source: redhat-operators
  +   sourceNamespace: openshift-marketplace
```

**Comment by anpingli** [comment]
@mburke5678  Yes.  the channel need to be updated from 'preview' to '4.2'.

**Comment by mburke5678** [comment]
@anpingli Got it: https://github.com/openshift/openshift-docs/pull/19781/files#diff-05927de0b103463c6f2aee89c1868a99R108

**Pull request merged**
