### PR TITLE
Document HAProxy behavior when APIServer LB is down, and provide 3rd party recommendations.

### PR DESCRIPTION
**Pull request by acomabon**
Masters HA section needs re-writing, since it does not take into account what happens when the APIserver goes down.
The following PR has been discussed within the organization. Reach out to me privately if need more info.
https://bugzilla.redhat.com/1641896

### CODE REVIEW

**Comment by kalexand-rh** [comment]
/ok-to-test

@acomabon, please squash your commits.

@lihongan, will you PTAL and confirm the applicable versions for me? Based on the bug, I think it might be 3.5-3.11.

**Comment by acomabon** [comment]
@kalexand-rh squashed!

**Comment by acomabon** [comment]
@kalexand-rh @lihongan AFAIU it should be included in all 3.x versions, starting with 3.0, is there any reason why you thing it'd start with 3.5?

**Comment by lihongan** [comment]
The changes are very basic principle for API LB, I think should be included in all versions. Thanks

**Comment by kalexand-rh** [comment]
The bug referenced 3.5, but I'm happy to cherry-pick it back to 3.0. Thanks! Merging.

**Pull request merged**
