### PR TITLE
OSDOCS-10435: Issue in file rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly

### PR DESCRIPTION
**Pull request by jneczypor**
[OSDOCS-10435](https://issues.redhat.com//browse/OSDOCS-10435): Issue in file rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly

Version(s):
4.15+

Issue:
https://issues.redhat.com/browse/OSDOCS-10435

Link to docs preview:
https://75703--ocpdocs-pr.netlify.app/openshift-rosa/latest/rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.html

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jneczypor** [comment]
Hi @bchandra-ocp! Can you please review this quick change? Thank you!

**Comment by jneczypor** [comment]
Hi @yuwang-RH! Can you please provide a quick QE review for this change? Thanks!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
