### PR TITLE
OCPBUGS-31817: Added two workflow diagrams to OCI docs for ABI

### PR DESCRIPTION
**Pull request by dfitzmau**
Version(s):
4.14+

Issue:
[OCPBUGS-31817](https://issues.redhat.com/browse/OCPBUGS-31817)

Link to docs preview:
[The Agent-based Installer and OCI overview](https://77983--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_oci/installing-oci-agent-based-installer.html)

QE review:
- [x] SME has approved this change
- [x] QE has approved this change.

### CODE REVIEW

**Review by pawanpinjarkar — COMMENTED** [review]
/lgtm

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by mhanss** [comment]
LGTM

**Pull request merged**
