### PR TITLE
Updated Sandboxed containers common attributes

### PR DESCRIPTION
**Pull request by amolnar-gh**
Version(s): 4.14+

Issue: https://issues.redhat.com/browse/TELCODOCS-1441

Link to docs preview: https://68397--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-moved

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by abhbaner — APPROVED** [review]

**Comment by dfitzmau** [comment]
Hello @amolnar-rh . I was unable to verify any changes through the [preview link](https://68397--docspreview.netlify.app/openshift-enterprise/latest/sandboxed_containers/sandboxed-containers-moved) as the "OpenShift sandboxed containers documentation has been moved" provides links to two 404-error pages. 

What versions of OCP are impacted by these updates and is a change management needed?

**Comment by amolnar-rh** [comment]
@dfitzmau The OpenShift sandboxed containers 1.5 are shipping today. The docs are not published yet so the links won't work until that happens. However, I wanted to get ahead and start the reviews.
This is only for OCP 4.14, CM is not needed

**Comment by dfitzmau** [comment]
> @dfitzmau The OpenShift sandboxed containers 1.5 are shipping today. The docs are not published yet so the links won't work until that happens. However, I wanted to get ahead and start the reviews. This is only for OCP 4.14, CM is not needed

Thanks, @amolnar-rh , for confirming. I see that each attribute has been updated with higher version, so LGTM.

**Pull request merged**
