### PR TITLE
OSDOCS#8294: adding workaround to known issue

### PR DESCRIPTION
**Pull request by skopacz1**
https://issues.redhat.com/browse/OSDOCS-8294

Adding a workaround to a known issue in the release notes.

Version(s): 4.14

QE review:
- [x] QE has approved this change.

Preview: [Known Issue](https://66925--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-asynchronous-errata-updates:~:text=You%20can%20work%20around%20this%20issue%20by%20manually%20removing%20the%20node%20taint.)

### CODE REVIEW

**Comment by skopacz1** [comment]
@mhanss could you PTAL? Thanks

**Comment by mhanss** [comment]
LGTM

**Review by jeana-redhat — COMMENTED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
