### PR TITLE
Update docs with the new rollout commands

### PR DESCRIPTION
**Pull request by 0xmichalis**
@mfojtik PTAL, one more before the Kube docs

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

@openshift/team-documentation FYI

**Comment by vikram-redhat** [comment]
@ahardin-rh  - PTAL. @mfojtik - for Enterprise 3.4 or 3.3?

**Comment by kargakis** [comment]
3.4

**Comment by ahardin-rh** [comment]
LGTM. Thanks!

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../cli_reference/cli_by_example_content.adoc#cli-reference-cli-by-example-content[An Introduction to the Concepts and Types in {product-title}]
|Updated with new `oc rollout` commands.
%
|xref:../dev_guide/deployments.adoc#dev-guide-deployments[Deployments]
|Updated with new `oc rollout` commands.
%
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Updated with new `oc rollout` commands.
%
|xref:../install_config/registry/extended_registry_configuration.adoc#install-config-registry-extended-configuration[Setting up the Registry -> Extended Registry Configuration] 
|Updated with new `oc rollout` commands.
%

**Pull request merged**
