### PR TITLE
OSDOCS-2269: Deleting a ROSA cluster applies to PrivateLink clusters

### PR DESCRIPTION
**Pull request by kmccarron-rh**
JIRA: https://issues.redhat.com/browse/OSDOCS-2269

Additional Resource section updated here:
https://deploy-preview-33744--osdocs.netlify.app/openshift-rosa/latest/rosa_getting_started/osd-aws-privatelink-creating-cluster?utm_source=github&utm_campaign=bot_dp#additional-resources

### CODE REVIEW

**Comment by kmccarron-rh** [comment]
@wgordon17 - Please confirm - Following up on thread in slack channel.  Added link to address PrivateLink cluster deletion.

**Comment by kmccarron-rh** [comment]
@nermina-redhat  - Will G provide a thumbs-up to this approach on the PrivateLink channel.

**Comment by wgordon17** [comment]
👍🏻  From me

**Comment by kmccarron-rh** [comment]
@nermina-redhat - ready for peer review - does this need QE?

**Comment by nermina-redhat** [comment]
+1 from me. This is a simple enough change that doesn't require a QE check.

**Comment by kmccarron-rh** [comment]
Hi @sfortner-RH - This one is ready for merge.

**Comment by sfortner-RH** [comment]
LGTM! Merging.

**Pull request merged**
