### PR TITLE
Bug 1767065: Fix link and add Ceph info on raw requirement

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1767065

### CODE REVIEW

**Comment by codyhoag** [comment]
@liangxia can you review this for accuracy? Thanks!

**Comment by liangxia** [comment]
> @liangxia can you review this for accuracy? Thanks!

Perhaps OCS (OpenShift Container Storage) are more appropriate to verify the change.

**Comment by vikram-redhat** [comment]
@morenod are you able to review this?

**Comment by morenod** [comment]
lgtm

**Comment by codyhoag** [comment]
@maxwelldb do you mind merging/cherry picking for me? Thanks!

**Comment by maxwelldb** [comment]
Yeah. As we discussed, the note will likely be removed after https://bugzilla.redhat.com/show_bug.cgi?id=1763803 clears, but this looks fine.

**Comment by maxwelldb** [comment]
@codyhoag Remember to move the BZ ticket to `Verified` after QE gives it a look. :)

> @codyhoag: [Bugzilla bug 1767065](https://bugzilla.redhat.com/show_bug.cgi?id=1767065) is in an unrecognized state (ON_QA) and will not be moved to the MODIFIED state.
> 
> In response to [this](https://github.com/openshift/openshift-docs/pull/17839):
> 
> > Bug 1767065: Fix link and add Ceph info on raw requirement
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

**Comment by codyhoag** [comment]
@maxwelldb good catch! I definitely will!

**Pull request merged**
