### PR TITLE
Bug 1542726 Remove F-Frontend Metrics

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1542726

### CODE REVIEW

**Comment by vikram-redhat** [comment]
@bmcelvee - Hey Brandi, anything holding this up?

**Comment by bmcelvee** [comment]
Thanks, @vikram-redhat. It's up to date with QE's feedback.

**Comment by bmcelvee** [comment]
@openshift/team-documentation PTAL :four_leaf_clover:

**Comment by bfallonf** [comment]
@bmcelvee Looks fine to me :100:

**Comment by bmcelvee** [comment]
Thanks, @bfallonf! :sun_with_face:

**Pull request merged**
