### PR TITLE
BZ1753105: Openshift 3.11 installation ignores nodeIP edits in configmap

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1753105

Preview: https://deploy-preview-43136--osdocs.netlify.app/openshift-enterprise/latest/install_config/master_node_configuration.html#node-config-pod-and-node-config

### CODE REVIEW

**Comment by mburke5678** [comment]
@nee1esh PTAL

**Comment by mburke5678** [comment]
@lmurthyrh Can you please assign a QE resource? Thank you.

**Comment by lmurthyrh** [comment]
@mburke5678 You can reach out to  schoudha@redhat.com

**Comment by bmcelvee** [comment]
LGTM!

**Pull request merged**
