### PR TITLE
OSDOCS#8364: Adding OCPBUGS-7267 as bug fix

### PR DESCRIPTION
**Pull request by bergerhoffer**
Version(s):
4.14

Issue:
https://issues.redhat.com/browse/OSDOCS-8364

Link to docs preview:
https://66970--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-bug-fixes

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by bergerhoffer** [comment]
@xingxingxia Can you please review this bug fix?

https://66970--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-14-release-notes#ocp-4-14-bug-fixes

**Pull request merged**
