### PR TITLE
Document router behavior changes due to rhbz#1584701

### PR DESCRIPTION
**Pull request by mburke5678**
https://bugzilla.redhat.com/show_bug.cgi?id=1628615

### CODE REVIEW

**Comment by mburke5678** [comment]
@knobunc PTAL. Change to docs for new `oc set route-backend` behavior.

**Comment by fcami** [comment]
@mburke5678 maybe:
* "does accept persistent connections." => "does continue to serve existing persistent connections."
* please align (some lines seem too long)
but otherwise lgtm.

**Comment by mburke5678** [comment]
@anpingli PTAL

**Comment by mburke5678** [comment]
@zhaozhanqi approved in BZ.

**Review by kalexand-rh — COMMENTED** [review]
LGTM! :smile_cat:

**Pull request merged**
