### PR TITLE
GH#28781: Use SAN extension for wildcard on custom certificate

### PR DESCRIPTION
**Pull request by jboxman**
- https://github.com/openshift/openshift-docs/issues/28781

Worth fixing.

Preview: https://deploy-preview-34374--osdocs.netlify.app/openshift-enterprise/latest/networking/ingress-operator#nw-ingress-setting-a-custom-default-certificate_configuring-ingress

### CODE REVIEW

**Comment by lihongan** [comment]
LGTM. Thank you @jboxman

**Review by maxwelldb — APPROVED** [review]
lgtm.

**Pull request merged**
