### PR TITLE
OSDOCS-8517-Networking

### PR DESCRIPTION
**Pull request by cbippley**
Version(s): 4.15

Issue: [OSDOCS-8517](https://issues.redhat.com/browse/OSDOCS-8517)

Link to docs preview: [Scroll down to Networking under Bug Fixes](https://71891--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-15-release-notes#ocp-4-15-bug-fixes)

QE review:
Not needed

Additional information:

### CODE REVIEW

**Comment by sabrinajess** [comment]
LGTM

**Review by bscott-rh — COMMENTED** [review]
Two typo fixes here

**Comment by cbippley** [comment]
Changes made, thanks @bscott-rh !

**Pull request merged**
