### PR TITLE
RHDEVDOCS-4451 - Fixed the typo

### PR DESCRIPTION
**Pull request by DebarghoGhosh**
Aligned team: Dev Tools
OCP version for cherry-picking: enterprise- 4.10 - 4.12

JIRA issue:
https://issues.redhat.com/browse/RHDEVDOCS-4451

Preview pages: https://50521--docspreview.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html

SME+QE review: @wtam2018 @bluengo 
Peer-review: @gabriel-rh

### CODE REVIEW

**Comment by wtam2018** [comment]
LGTM

**Review by gabriel-rh — APPROVED** [review]
looks good to me

**Comment by rolfedh** [comment]
/enterprise-4.10

**Pull request merged**
