### PR TITLE
Bug 1428344 removed 'v' from tag

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1428344

### CODE REVIEW

**Comment by bmcelvee** [comment]
@ahardin-rh @adellape PTAL 😺

**Comment by bmcelvee** [comment]
@ahardin-rh @adellape peer review please 😺

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by bmcelvee** [comment]
Thanks, @ahardin-rh! 🌟

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../install_config/aggregate_logging.adoc#install-config-aggregate-logging[Aggregating Container Logs]
|Removed the 'v' from the 3.4.1 in the xref:../install_config/aggregate_logging.adoc#deploying-the-efk-stack[Deploying the EFK Stack] section.
%

**Pull request merged**
