### PR TITLE
Change _bootstrap_ to _live_ ignition filename in example commands

### PR DESCRIPTION
**Pull request by bobfuru**
Adds more clarification that this workflow is not supported by RH, and also updates `bootstrap.ign` filename to `live.ign' for continuity.

@bgilbert Does this look good, based on our conversation with Derrick?

### CODE REVIEW

**Comment by bobfuru** [comment]
@openshift/team-documentation PTAL

**Comment by bobfuru** [comment]
This might be impacted by https://github.com/openshift/openshift-docs/pull/26490 and the additional CP efforts that that will require.

**Review by sfortner-RH — APPROVED** [review]
LGTM!

**Comment by bobfuru** [comment]
Left comment in Slack thread, time-sensitive for GA so merging: https://coreos.slack.com/archives/C999USB0D/p1603140575283000?thread_ts=1603136869.280500&cid=C999USB0D

**Review by bgilbert — COMMENTED** [review]
LGTM

**Pull request merged**
