### PR TITLE
OSDOCS-2029: Mention that OAuth access token login requests are logge…

### PR DESCRIPTION
**Pull request by bergerhoffer**
…d for Default

https://issues.redhat.com/browse/OSDOCS-2029

Preview: https://deploy-preview-32053--osdocs.netlify.app/openshift-enterprise/latest/security/audit-log-policy-config.html#about-audit-log-profiles_audit-log-policy-config

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM!

**Review by EmilyM1 — COMMENTED** [review]
/lgtm

**Pull request merged**
