### PR TITLE
Removed deprecated Cluster Loader content

### PR DESCRIPTION
**Pull request by ahardin-rh**
A separate PR will update the 4.10 release notes

Preview: https://deploy-preview-41112--osdocs.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-10-release-notes.html#ocp-4-10-deprecated-removed-features

### CODE REVIEW

**Review by mffiedler — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Comment by mjpytlak** [comment]
@ahardin-rh peer review LGTM.

**Pull request merged**
