### PR TITLE
[SRVCOM-2213] Remove TP notes for features that went GA

### PR DESCRIPTION
**Pull request by rh-max**
Version(s):
4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-2213

Link to docs preview:
1) https://54234--docspreview.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-configuration.html#serverless-enabling-pvc-support_serverless-configuration
2) https://54234--docspreview.netlify.app/openshift-enterprise/latest/serverless/admin_guide/serverless-configuration.html#serverless-admin-init-containers_serverless-configuration

QE review:
- [ ] QE has approved this change.

### CODE REVIEW

**Comment by mgencur** [comment]
QE Approved

**Comment by kcarmichael08** [comment]
LGTM

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Pull request merged**
