### PR TITLE
OSDOCS#11397: Remove outdated toc item

### PR DESCRIPTION
**Pull request by laubai**
Version(s):
4.16 only; main already contains a similar change

Issue:
https://issues.redhat.com/browse/OSDOCS-11397

Link to docs preview:
- ROSA: https://82107--ocpdocs-pr.netlify.app/openshift-rosa/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes
- OSD: https://82107--ocpdocs-pr.netlify.app/openshift-dedicated/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by skopacz1** [comment]
Can't get the previews to work, I'm going to retest to see if that will help

**Comment by kalexand-rh** [comment]
@laubai, since OSD and ROSA have only a single version and we've switched them to track 4.17, please confirm that this change is present in 4.17. If so, no other work is required. If not, please open (or retarget) this PR against 4.17.

**Review by skopacz1 — APPROVED** [review]
LGTM

**Comment by laubai** [comment]
@kalexand-rh It doesn't already, but 4.17 and onward will contain the changes in https://github.com/openshift/openshift-docs/pull/81437 - this is the correct content for 4.16, and will be replaced with HCP/Classic split content in short order.

**Review by xenolinux — COMMENTED** [review]
Merge review LGTM

**Comment by eohartman** [comment]
@xenolinux 
Has this been merged yet? Is this able to be closed?

**Comment by xenolinux** [comment]
> @xenolinux Has this been merged yet? Is this able to be closed?

Yes :)  It was merged 2 weeks ago.

**Pull request merged**
