### PR TITLE
Bad command given in exposing HAProxy Router Metrics 

### LINKED ISSUE #12669: Bad command given in exposing HAProxy Router Metrics
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/install_config/router/default_haproxy_router.adoc#exposing-the-router-metrics

Affects 3.2-3.11

### What needs fixing?
CURRENTLY READS....
```
* To get metrics in a browser:
+
. Delete the following xref:../../architecture/networking/routes.adoc#env-variables[environment variables]
from the router deployment configuration file:
+
----
$ oc edit service router

- name: ROUTER_LISTEN_ADDR
  value: 0.0.0.0:1936
- name: ROUTER_METRICS_TYPE
  value: haproxy
----
```

SHOULD READ.....
```
* To get metrics in a browser:
+
. Delete the following xref:../../architecture/networking/routes.adoc#env-variables[environment variables]
from the router deployment configuration file:
+
----
$ oc edit dc router

- name: ROUTER_LISTEN_ADDR
  value: 0.0.0.0:1936
- name: ROUTER_METRICS_TYPE
  value: haproxy
----
```

### PR DESCRIPTION
**Pull request by bysnupy**
Fix: https://github.com/openshift/openshift-docs/issues/12669

I closed this PR by my mistake, so I open again this PR.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@knobunc, will you PTAL?

**Comment by kalexand-rh** [comment]
@zhaozhanqi, can you PTAL or suggest another reviewer?

**Comment by zhaozhanqi** [comment]
LGTM

**Comment by kalexand-rh** [comment]
Thanks! Merging.

**Comment by kalexand-rh** [comment]
The command is different in versions before 3.6, so I'm only applying it back that far.

**Pull request merged**
