### PR TITLE
OSDOCS#5598: Release notes for user-defined Azure tags

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.13

Issue: https://issues.redhat.com/browse/OSDOCS-5598

Link to docs preview:https://57615--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-13-release-notes.html#ocp-4-13-user-defined-tags-azure

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by jinyunma** [comment]
LGTM
cc: @bharath-b-rh to review

**Review by bharath-b-rh — APPROVED** [review]
/lgtm

**Review by snarayan-redhat — COMMENTED** [review]
Looks good!

**Pull request merged**
