### PR TITLE
BZ#1789120 Have additonalNetworks name match 'oc get' output

### PR DESCRIPTION
**Pull request by codyhoag**
https://bugzilla.redhat.com/show_bug.cgi?id=1789120

### CODE REVIEW

**Comment by codyhoag** [comment]
@zhaozhanqi can you confirm? Thanks!

Preview: http://file.rdu.redhat.com/~choag/012320/addn-network-name-match/networking/multiple-networks/configuring-host-device.html#nw-multus-create-network_configuring-host-device

**Comment by zhaozhanqi** [comment]
LGTM, sorry for late reply due to holiday in China.

**Comment by mburke5678** [comment]
@codyhoag LGTM

**Pull request merged**
