### PR TITLE
[RHACS] ROX-18662: Support ACS Secured cluster on IBM ROKS / RHOIC

### PR DESCRIPTION
**Pull request by agantony**
Version(s):
4.3+

Issue:
https://issues.redhat.com/browse/ROX-18662

Link to docs preview:
https://67403--docspreview.netlify.app/openshift-acs/latest/installing/acs-installation-platforms#:~:text=Yes-,Red%20Hat%20OpenShift%20on%20IBM%20Cloud,Yes,-Amazon%20Elastic%20Kubernetes

SME review:
- [x] SME has approved this change.

Additional information:
- Merge into `rhacs-docs` and cherry-pick to:
    - `rhacs-docs-4.3`

### CODE REVIEW

**Comment by agantony** [comment]
Tech review needed

**Review by davdhacs — APPROVED** [review]
looks good

**Comment by stevsmit** [comment]
LGTM, but needs rebased before going to merge review.

**Review by jeana-redhat — APPROVED** [review]
LGTM

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
