### PR TITLE
Removed modules/machineconfig-modify-registry.adoc procedure

### PR DESCRIPTION
**Pull request by ahardin-rh**
Removed the Configuring container image registry settings module, as it is no longer valid for 4.7+ and updated content was introduced in https://github.com/openshift/openshift-docs/pull/28152 per discussion in https://github.com/openshift/openshift-docs/pull/30805#discussion_r600473138

### CODE REVIEW

**Comment by ahardin-rh** [comment]
FYI @umohnani8 @mburke5678

**Comment by jeana-redhat** [comment]
LGTM

**Pull request merged**
