### PR TITLE
CNV-46268: DPDK example VM: Replace running with runStrategy

### PR DESCRIPTION
**Pull request by sbeskin-redhat**
Resolves: https://issues.redhat.com/browse/CNV-46268

OCP 4.18
CNV 4.18

Preview: https://85711--ocpdocs-pr.netlify.app/openshift-enterprise/latest/virt/vm_networking/virt-using-dpdk-with-sriov.html#virt-configuring-vm-dpdk_virt-using-dpdk-with-sriov

### CODE REVIEW

**Review by orelmisan — APPROVED** [review]
Thank you @sbeskin-redhat

**Review by xenolinux — COMMENTED** [review]
LGTM

**Comment by xenolinux** [comment]
@sbeskin-redhat Should this also be cherry-picked to 4.17 and earlier?

**Comment by sbeskin-redhat** [comment]
> @sbeskin-redhat Should this also be cherry-picked to 4.17 and earlier?

No, thank you, just 4.18.

**Pull request merged**
