### PR TITLE
Add example of custom deployment and remove dead link

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@kargakis @openshift/team-documentation PTAL

**Comment by kargakis** [comment]
Can you post example logs from the custom deployer?

**Comment by kargakis** [comment]
> Can you post example logs from the custom deployer?

s/post/add/

**Comment by mfojtik** [comment]
@kargakis good idea

**Comment by mfojtik** [comment]
updated.

**Comment by mfojtik** [comment]
@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
@mfojtik @kargakis Thanks! Is this for 3.4? Adding a to_followup label so that I can apply minor style edits in a separate PR.

**Comment by kargakis** [comment]
> Is this for 3.4?

No, this was added in https://github.com/openshift/origin/pull/8787 which was included in 3.3.

**Comment by ahardin-rh** [comment]
@kargakis Thank you for clarifying. Merging now.

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../dev_guide/deployments/deployment_strategies.adoc#dev-guide-deployment-strategies[Deployments -> Deployment Strategies]
|Added an example of custom deploymen to the txref:../dev_guide/deployments/deployment_strategies.adoc#custom-strategy[Custom Strategy] section.
%

**Pull request merged**
