### PR TITLE
OSSMDOC-483 distributed tracing 2.3 Release Notes.

### PR DESCRIPTION
**Pull request by JStickler**
Preview here -> https://deploy-preview-43218--osdocs.netlify.app/openshift-enterprise/latest/distr_tracing/distributed-tracing-release-notes.html

Eng review - 
QE review - jkandasa, iblancasa
Peer review - ahardin-rh

### CODE REVIEW

**Comment by JStickler** [comment]
Please review @rubenvp8510 @jkandasa @iblancasa

**Review by iblancasa — APPROVED** [review]

**Review by jkandasa — APPROVED** [review]

**Pull request merged**
