### PR TITLE
[enterprise-4.15] OBSDOCS-1235: Removed 5.7z from 4.15

### PR DESCRIPTION
**Pull request by shreyasiddhartha**
Change type: Doc update; Logging Z-Stream Release Notes - Content Improvement
Doc JIRA: https://issues.redhat.com/browse/OBSDOCS-1235

Fix Version: 4.15

Doc Preview: https://79963--ocpdocs-pr.netlify.app/openshift-enterprise/latest/observability/logging/logging_release_notes/logging-5-9-release-notes#logging-release-notes-5-9-4_logging-5-9-release-notes

QE Review: @anpingli 
Peer Review: @lpettyjo

### CODE REVIEW

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Comment by bscott-rh** [comment]
Merge review LGTM.

**Pull request merged**
