### PR TITLE
Bug 1468307, Added clarification about the latest version [enterprise-3.4]

### PR DESCRIPTION
**Pull request by ahardin-rh**
https://bugzilla.redhat.com/show_bug.cgi?id=1468307

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@ewolinetz PTAL

**Comment by ewolinetz** [comment]
@ahardin-rh just to clarify, for this version of the docs build `{latest-tag}` will be the `3.4.1` one?

**Comment by ahardin-rh** [comment]
@ewolinetz Correct. `3.4.1` is defined [in line 9 of the file's metadata](https://github.com/openshift/openshift-docs/pull/4908/files#diff-0bd2e2c1a5da6f157682d4e95ecea473L9).

**Review by ewolinetz — APPROVED** [review]

**Comment by ahardin-rh** [comment]
QE verified. No revision history needed.

**Pull request merged**
