### PR TITLE
Fixes pod autoscaling

### PR DESCRIPTION
**Pull request by kalexand-rh**
From https://github.com/openshift/openshift-docs/pull/13360

@vikram-redhat, I'm not sure who should approve this change. Micheal tagged @sunzhaohua2 a couple of times on the original PR, but I'm not sure if there's a better reviewr.

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
@kalexand-rh Sorry for the delay. I have been PTO  for the past two weeks. Maybe @sunilcio  is the right person for pod autoscaling.

**Comment by sunilcio** [comment]
Thanks @sunzhaohua2 . @weinliu could you please review this.

**Comment by weinliu** [comment]
Referring to [https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/](url), the updated yaml sample is correct. It LGTM

**Comment by kalexand-rh** [comment]
Thank you all! I'm going to merge.
Welcome back @sunzhaohua2! I hope you enjoyed your holiday.

**Pull request merged**
