### PR TITLE
ShiftStack - Replace lbFloatingIP with apiFloatingIP

### LINKED ISSUE #30721: [enterprise-4.7] Some ShiftStack content uses "lbFloatingIP" instead of "apiFloatingIP"
### What needs fixing?
lbFloatingIP has been renamed apiFloatingIP

### PR DESCRIPTION
**Pull request by maxwelldb**
Resolves #30721

@iamemilio Could you +1/-1 this?

### CODE REVIEW

**Comment by maxwelldb** [comment]
In need of QE, too. Preview link: https://deploy-preview-30797--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html

**Comment by iamemilio** [comment]
lgtm

**Comment by maxwelldb** [comment]
Thanks!

**Comment by EmilienM** [comment]
LGTM

**Comment by maxwelldb** [comment]
@udis Would you be able to QE+1 this?

**Review by udis — COMMENTED** [review]
lgtm

**Comment by maxwelldb** [comment]
@udis Thanks!

**Comment by maxwelldb** [comment]
@openshift/team-documentation PTAL at this when you have a sec. Should be pretty quick. Thanks!

**Review by kalexand-rh — COMMENTED** [review]
Unless this is something that you also need to telegraph in the 4.7 release notes, this LGTM.

**Pull request merged**
