### PR TITLE
updating CF templates per installer #2296

### PR DESCRIPTION
**Pull request by kalexand-rh**
Updating the CF templates per https://github.com/openshift/installer/pull/2296/files

@wking, is this valid for just 4.2 or for 4.1 as well?

@jianlinliu, will you PTAL?

### CODE REVIEW

**Comment by kalexand-rh** [comment]
Trevor confirmed that this was valid in 4.1 and 4.2 via Slack.

**Review by wking — APPROVED** [review]

**Comment by jianlinliu** [comment]
After applied the PR, installation get successful. LGTM.

**Comment by kalexand-rh** [comment]
Thank you both! Merging.

**Pull request merged**
