### PR TITLE
Router Sticky sessions

### PR DESCRIPTION
**Pull request by pweil-**
Fix broken formatting of router doc and add section about haproxy sticky sessions.

In support of https://github.com/openshift/origin/pull/2105

### CODE REVIEW

**Comment by adellape** [comment]
Thanks, @pweil-, LGTM. Will merge after code PR merges.

**Comment by adellape** [comment]
Code PR has merged. Merging docs.

**Comment by adellape** [comment]
@pweil- Hm, actually I think I was too quick on the merge (overwrote some recent changes). Reverting this, then it'll need a rebase I think.

**Comment by pweil-** [comment]
ok, will rebase.  Thanks

**Comment by adellape** [comment]
@pweil- Thanks, reverted.

**Pull request merged**
