### PR TITLE
[enterprise-3.6] Image tag bump for RHBA-2018:2654

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
Need to update the commit message.

**Comment by tmorriso-rh** [comment]
@ahardin-rh PTAL. Thanks.

**Comment by ahardin-rh** [comment]
@tmorriso-rh LGTM. Looks like the release note update also worked its way in here. That's fine as long as you also have it added to master elsewhere. To update your commit message, you can use:
 git commit --amend -m "New commit message that you want to use"

**Comment by tmorriso-rh** [comment]
Closed when resetting the enterprise-3.6 branch.

**Comment by tmorriso-rh** [comment]
Closed in favor of https://github.com/openshift/openshift-docs/pull/12034.

**Pull request closed without merging**
