### PR TITLE
fixing up issues for bad sshKey declaration in install-config.yaml

### PR DESCRIPTION
**Pull request by Ultimate-etamitlU**
Fixing up issues for bad sshKey declaration in install-config.yaml
and removing additional spaces before "EOF" for sample configs files
of agent-config.yaml and install-config.yaml
Signed-off-by: Ultimate-etamitlU <pskhedekar@gmail.com>

Version(s): 4.13 and above

Issue:
In https://github.com/openshift/openshift-docs/edit/main/modules/installing-ocp-agent-inputs.adoc
we have sample install-config as,
..
..
pullSecret: '<pull_secret>' <4>
sshKey: |
'<ssh_pub_key>' <5>
..
..
But when we add ssh key like that if fails to start services that creates initial cluster and infraenv though the node gets IP but we can't do ssh.
Changing it to something like below fixes it.
What needs fixing?

From this,

..
..
pullSecret: '<pull_secret>' <4>
sshKey: |
'<ssh_pub_key>' <5>
..
..

To this,

..
..
pullSecret: '<pull_secret>' <4>
sshKey: '<ssh_pub_key>' <5>
..
..

Tested this to my environment and seems not working with ABI somehow.

Also there are white spaces before "EOF" which break the copy paste operation of
the sample configs for user and needs that's adjusted manually so removing those.

Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

Earlier had separate PR for each of it and messed up with that by trying it by GUI so
correcting everything in a single commit to avoid kids noise!

### CODE REVIEW

**Comment by Ultimate-etamitlU** [comment]
@skopacz1 Erased all of the separates PR's I had and combined them all to one with this fresh one, can you please review this one.
Apologies as I thought using GUI would be easy to do this and it ended up in a lot work.

**Review by skopacz1 — APPROVED** [review]
LGTM. This is a redo of #66032 which was QE approved, so I believe this PR itself won't need QE review. Let me know if I need it reviewed anyways.

**Comment by kalexand-rh** [comment]
Since QE approved the other PR, it's fine to merge this one - it does appear to be the same change.

**Pull request merged**
