### PR TITLE
OCPBUGSM-42704: Update docs for SNO deployments

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGSM-42704

/assign @lpettyjo

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@lpettyjo, PTAL

**Comment by lpettyjo** [comment]
Doc changes here: https://github.com/openshift/openshift-docs/pull/54410

**Comment by kalexand-rh** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/54410.

**Pull request closed without merging**
