### PR TITLE
add glusterfs physical management page

### PR DESCRIPTION
**Pull request by jmferrer**
Added procedure to add physical blocks to containerized glusterfs  cluster.

### CODE REVIEW

**Comment by tmorriso-rh** [comment]
@jmferrer Hi Jose, the team is reviewing this PR. What OpenShift release is this for?

@childsb @gnufied @jsafrane Hi All, can someone from the Storage team review this PR?

@jhou1 @liangxia Hi, can you QE review this PR?

**Comment by jhou1** [comment]
@wkshi Can you please review?

**Comment by wkshi** [comment]
QE haven't tested this scenario, @jarrpa could you please help confirm this?

**Comment by jarrpa** [comment]
....this shouldn't work. Has this actually been run successfully??

**Comment by jmferrer** [comment]
Hi. I tested this scenario in 3.7 1 month ago and in 3.9 two weeks ago..

**Comment by jmferrer** [comment]
Last time I used the glusterfs playbook instead of config playbook. Let me change the PR.

**Comment by jmferrer** [comment]
History reviewed. This PR is valid for 3.9 .

**Comment by jarrpa** [comment]
Having finally had a chance to check the code, this does look like it could work. However, the roles was not designed for this and I worry there may be unforeseen consequences. I would definitely want it verified by QE before merging.

@wkshi If you have a look at this, please make sure in your tests that you verify the heketi topology and that dynamic provisioning still works against that Gluster cluster.

**Comment by wkshi** [comment]
@jarrpa @jmferrer I'd like to confirm which release are we going to support this feature? Is there any Trello Card tracking this? Rerun installer playbooks in installed OCP looks not safe in my view.

**Comment by jmferrer** [comment]
@wkshi , ansible playbooks, in theory, must be idempotent. Each time I want to reconfigure the cluster I change the inventory file and launch the installation playbook.

**Comment by wkshi** [comment]
@jmferrer In theory, yes, it should be. But for openshift-ansible, in some case, it's not.

**Comment by jarrpa** [comment]
@jmferrer Yeah, @wkshi is right: they SHOULD be idempotent but it is not a strict requirement. At present, the GlusterFS playbooks are not guaranteed to be idempotent though they may at times behave that way if you're lucky.

There are currently no official timelines to support this, but it is a general goal of mine to get the playbooks to a (mostly) idempotent state such that this would be guaranteed to be valid.

**Comment by jmferrer** [comment]
I **always** use playbooks when I want to change any parameter, from openshift_node_kubelet_args to openshift_hosted_router_replicas because, Ansible makes less mistakes than I. ;-)

I cannot say that playbooks are not idempotent to a customer. I know that programming idempotent playbooks is very difficult some times and some other times is nearly to be impossible. And I know you are overloaded.

But customers need guides to do basic operations like:
* increase gluster cluster space
* backup/restore gluster volumes
* monitoring volumes usage
Without those three guides is very difficult that containerized glusterfs could be accepted in a big customer.

I will use your playbooks as nearly idempotent. In @jarrpa ,  @wkshi and all openshift-ansible project we trust! :-)

**Comment by jarrpa** [comment]
@jmferrer Heh, thanks for the confidence. :)

While I agree that those are crucial features for our project, we do already have relatively large deployments of CNS in enterprise datacenters. We could potentially reach whole new scales with proper automation, but at least we are not doing too bad for now.

Since you agree to use these in a non-idempotent manner, would it make sense to close this PR? I do have some plans to address this functionality, but it will involve some development in the meantime.

**Comment by tmorriso-rh** [comment]
@jmferrer Bump. Please review the comment from @jarrpa about closing this PR. Thanks.

**Pull request closed without merging**
