### PR TITLE
Update iptables document for firewalld

### PR DESCRIPTION
**Pull request by danwinship**
@openshift/networking please review for content

### CODE REVIEW

**Comment by danwinship** [comment]
This applies to master and 3.5

**Review by pecameron — COMMENTED** [review]
LGTM

**Comment by bfallonf** [comment]
Thanks @danwinship . Let me know if there's any more content you'd like to add here or if it's ok to move forward with this. I can followup with this as part of BZ 1446436.

**Comment by danwinship** [comment]
As I said in email, we might want some additions to advanced_install too, but that could happen as a separate PR (and those details would come from the installer team anyway). So I think you can move forward with this.

**Comment by bfallonf** [comment]
@danwinship Sure thing. I'll merge this and do a followup PR, but also push for feedback, as we discussed over email. Thanks!

**Pull request merged**
