### PR TITLE
Update label names in s2i images

### PR DESCRIPTION
**Pull request by soltysh**
This can be merged only after https://github.com/openshift/origin/pull/3604 is merged into origin.

### CODE REVIEW

**Comment by soltysh** [comment]
@bparees ptal

**Comment by bparees** [comment]
lgtm.  @adellape please merge after 3604 merges.

**Comment by bparees** [comment]
3604 has merged.

**Comment by adellape** [comment]
@bparees @soltysh Applicable in OSE after 3.0.1?

**Comment by bparees** [comment]
yes

**Pull request merged**
