### PR TITLE
add wording regarding SDRS

### PR DESCRIPTION
**Pull request by dav1x**
Add some wording this and support.

I've had several queries regarding configurations using SDRS.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@listey, will you PTAL?

**Comment by vikram-redhat** [comment]
@listey are you still the right person to validate this?

**Comment by listey** [comment]
Hmm, not sure if I own validating this but I'm happy to +1

**Comment by kalexand-rh** [comment]
Thank you both! Davis confirmed that this change is valid for 4.2+.

**Pull request merged**
