### PR TITLE
[OCPBUGS#39132] Revise ShiftStack rootVolume and etcd local docs CPMS update step

### PR DESCRIPTION
**Pull request by maxwelldb**
Version(s): 4.17+

Issue: [OCPBUGS-39132](https://issues.redhat.com/browse/OCPBUGS-39132)

Link to docs preview: https://81888--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/deploying-openstack-with-rootVolume-etcd-on-local-disk.html

QE review:
- [x] QE has approved this change.

Additional information: What a silly typo in the branch name. :)

### CODE REVIEW

**Comment by rlobillo** [comment]
Hello @maxwelldb 

The steps 5 and 6 can be eliminated. To apply this procedure it is needed to create flavor with `--ephemeral 10` as it is already done in step 1.  Therefore, 5 and 6 are not correct.

**Comment by maxwelldb** [comment]
@rlobillo Steps 5 and 6 were removed from the module. Check out the new preview: https://81888--ocpdocs-pr.netlify.app/openshift-enterprise/latest/installing/installing_openstack/deploying-openstack-with-rootVolume-etcd-on-local-disk.html

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM. We are all ephemperal creatures, I suppose! :+1:

**Comment by GroceryBoyJr** [comment]
Wow. The openshift-ci bot is slow today.

**Comment by maxwelldb** [comment]
lgtmed already--removing request.

**Pull request merged**
