### PR TITLE
BZ2103622: Removes the spec.template.spec.toleration for a pod

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.6+

Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2103622

Link to docs preview: http://file.rdu.redhat.com/sdudhgao/BZ622/nodes/scheduling/nodes-scheduler-taints-tolerations.html#nodes-scheduler-taints-tolerations-special_nodes-scheduler-taints-tolerations

Additional information:

QE @sunilcio

### CODE REVIEW

**Review by kelbrown20 — COMMENTED** [review]
LGTM!

**Review by bergerhoffer — COMMENTED** [review]
LGTM too, merging!

**Pull request merged**
