### PR TITLE
OSDOCS-4533: CIT Remove xrefs in module and clean up 

### PR DESCRIPTION
**Pull request by michaelryanpeter**
Remove the `xrefs` in `modules/osdk-common-prereq.adoc` and replace `-` bullets with `*` in associated modules and assemblies.

Peer & merge review squad: I think that this PR does not need SME or QE review because it only fixes `xrefs` in modules and the bullet type. There are no changes to technical content. If you disagree, please let me know and I can get acks.

Version(s): 4.11+

Issue: [OSDOCS-4533](https://issues.redhat.com//browse/OSDOCS-4533)

Link to docs preview:
* [Ansible quickstart](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-quickstart.html#osdk-common-prereqs_osdk-ansible-quickstart)
* [Ansible tutorial](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/ansible/osdk-ansible-tutorial.html#osdk-common-prereqs_osdk-ansible-tutorial)
* [Go quickstart](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-quickstart.html#osdk-common-prereqs_osdk-golang-quickstart)
* [Go tutorial](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-common-prereqs_osdk-golang-tutorial)
* [Helm quickstart](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-quickstart.html#osdk-common-prereqs_osdk-helm-quickstart)
* [Helm tutorial](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-helm-tutorial.html#osdk-common-prereqs_osdk-helm-tutorial)
* [Hybrid helm](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/helm/osdk-hybrid-helm.html#osdk-common-prereqs_osdk-hybrid-helm)
* [Java quickstart](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-quickstart.html#osdk-common-prereqs_osdk-java-quickstart)
* [Java tutorial
](https://52711--docspreview.netlify.app/openshift-enterprise/latest/operators/operator_sdk/java/osdk-java-tutorial.html#osdk-common-prereqs_osdk-java-tutorial)
QE review:
- [ ] QE has approved this change.

Additional information:
* Issue for OCP 4.8 to 4.10: [OSDOCS-4534](https://issues.redhat.com//browse/OSDOCS-4534) (Backlog)

Doc clean up of list formatting and removing xrefs from a module.

### CODE REVIEW

**Comment by bscott-rh** [comment]
LGTM. I agree that no QE/SME ack is necessary due to the nature of the changes.

One question - is it expected that the breadcrumb above the page doesn't show the full directory path? 
Screenshot 2022-11-10 at 4 52 54 PM
In this case the breadcrumb doesn't show that I'm in the Java-based Operators directory. I'm guessing it's just a limitation of the publishing tool but thought I'd bring it up.

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Comment by michaelryanpeter** [comment]
Good looking out, @bscott-rh. I looked around the Operator docs in 4.11, and it looks like part of the sub-chapter/book info is cut off at a certain level. I wonder if this is a workaround for the breadcrumb issue that we were having a while ago on d.o.c? I will follow up in #team-docs to confirm if this is the expected behavior.

**Comment by michaelryanpeter** [comment]
Dear merge review squad, 
I can merge and cherrypick this PR but would you please perform the merge review?

/label merge-review-needed

**Comment by jeana-redhat** [comment]
LGTM for merge

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
