### PR TITLE
Dedidated 4.1 content port

### PR DESCRIPTION
**Pull request by ahardin-rh**

### CODE REVIEW

**Comment by ahardin-rh** [comment]
@vikram-redhat I am not able to build this locally for preview. No weird errors, but I don't see the branch show up for Dedicated so that I can preview. I am marking Dedicated content as openshift-dedicated. Not sure what I'm missing :confused:  Any ideas?

**Comment by jboxman** [comment]
@ahardin-rh, did you have a proper __distro_map.yml_ file? The committed one for the 4.1 branch lacks the necessary entries for the other release types.

**Comment by jboxman** [comment]
My suspicion is this might work.

```
---
openshift-enterprise:
  name: OpenShift Container Platform
  author: OpenShift Documentation Project <dev@lists.openshift.redhat.com>
  site: commercial
  site_name: Documentation
  site_url: https://docs.openshift.com/
  branches:
    enterprise-4.1:
      name: '4.1'
      dir: container-platform/4.1
openshift-dedicated:
  name: OpenShift Dedicated
  author: OpenShift Documentation Project <dev@lists.openshift.redhat.com>
  site: commercial
  site_name: Documentation
  site_url: https://docs.openshift.com/
  branches:
    enterprise-4.1:
      name: 'Latest'
      dir: dedicated
```

**Comment by ahardin-rh** [comment]
@jboxman Thanks! Yeah, Vikram and I discovered some constraints with what we're trying to do. I think we found a workaround though :+1:

**Comment by ahardin-rh** [comment]
:crossed_fingers:

**Pull request merged**
