### PR TITLE
BZ-2006797: updated yaml file with correct details

### PR DESCRIPTION
**Pull request by MirzWeiss**
[Bugzilla 2006797](https://bugzilla.redhat.com/show_bug.cgi?id=2006797) update for OpenShift Docs 4.8:

Preview link: https://deploy-preview-37013--osdocs.netlify.app/openshift-enterprise/latest/sandboxed_containers/deploying-sandboxed-container-workloads.html#sandboxed-containers-installing-operator-cli_deploying-sandboxed-containers

Review and approved by QE.

### CODE REVIEW

**Comment by cpmeadors** [comment]
Approved. I tested the new yaml on a 4.8.13 cluster and the operator was installed successfully.

**Review by ctauchen — COMMENTED** [review]
Regarding versions: Is this only for 4.8+?

/lgtm

**Comment by MirzWeiss** [comment]
> Regarding versions: Is this only for 4.8+?

Yes, this change is only relevant for 4.8.

**Comment by ctauchen** [comment]
Thanks for confirming, @MirzWeiss. I see that this bug was cloned just yesterday for 4.9. From what I can tell, it looks as if the suggested change in 4.9 is a like-for-like copy of the same YAML file.

But I may have that wrong. Just thought I'd mention it, because it could be easier to clear both bugs with the same PR.

That said, if you prefer to do these separately, then consider this LGTM.

**Pull request merged**
