### PR TITLE
GH#64725: add missing cloud providers for compute machine set

### PR DESCRIPTION
**Pull request by peterroth**
Version(s):
all

Issue:
GH [#64725](https://github.com/openshift/openshift-docs/issues/64725)

Preview: https://72099--ocpdocs-pr.netlify.app/openshift-enterprise/latest/machine_management/#machine-mgmt-intro-managing-compute_overview-of-machine-management

QE review:
N/A

### CODE REVIEW

**Comment by peterroth** [comment]
@bergerhoffer please review this change.
Hacktoberfest ended, I know, but it was still missing.

**Comment by bergerhoffer** [comment]
@peterroth yeah something weird is going on for sure. I have it happening on another PR as well, but some jobs on other PRs are completing just fine. We're investigating. I'm going to try closing/reopening the PR to see if that kicks off the jobs differently where they might succeed.

**Comment by peterroth** [comment]
Seems the ci-operator image is still unavailable :)

**Review by bergerhoffer — COMMENTED** [review]
Updates LGTM!

**Comment by bergerhoffer** [comment]
This update won't require QE.

Our repo is currently frozen, so we can't merge this today. I'll set a reminder for myself that hopefully we can merge it by the end of the week, but if you don't hear from me by then, please feel free to ping me again!

**Comment by peterroth** [comment]
Sure, @bergerhoffer; I'll check back on Friday.

**Comment by kalexand-rh** [comment]
The `branch/enterprise-4.16` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.15. And any PR going into `main` must also target the latest version branch (enterprise-4.16).

If the update in your PR does NOT apply to version 4.16 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Comment by bergerhoffer** [comment]
Repo is unfrozen, merging!

**Comment by bergerhoffer** [comment]
Thanks @peterroth for submitting! All versions have been merged. Versions 4.13+ are likely live already since they were merged yesterday, but 4.12 will take a bit longer to become live since it was just merged today.

**Pull request merged**
