### PR TITLE
OSDOCS-10978: Remove custom TLS ciphers tutorial

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Version(s): `enterprise-4.15`+

Issue: https://issues.redhat.com/browse/OSDOCS-10978

Link to docs preview: https://77771--ocpdocs-pr.netlify.app/openshift-rosa/latest/welcome/

QE review: Not required

Additional information: This article is out-of-date and no longer applicable due to the removal of the Custom Domain Operator.

### CODE REVIEW

**Review by mletalie — COMMENTED** [review]
/label peer-review-in-progress

**Review by mletalie — COMMENTED** [review]
/label peer-review-done
/remove-label peer-review-in-progress
/remove-label peer-review-needed
/lgtm

**Comment by mletalie** [comment]
Obsolete topic removed, lgtm!

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

**Pull request merged**
