### PR TITLE
added documentation for how to clear route status

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
Initial attempt to document how to clear a routes status field. 

Bug 1356819 [Link](https://bugzilla.redhat.com/show_bug.cgi?id=1356819)

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@openshift/team-documentation PTAL

**Comment by ahardin-rh** [comment]
@JacobTanenbaum Thanks! Is this for 3.5?

**Comment by JacobTanenbaum** [comment]
@ahardin-rh yes this is for 3.5

**Comment by ahardin-rh** [comment]
[rev_history]
|xref:../architecture/core_concepts/routes.adoc#architecture-core-concepts-routes[Core Concepts -> Routes]
|Added information on how to clear xref:../architecture/core_concepts/routes.adoc#route-status-field[route status].
%

**Pull request merged**
