### PR TITLE
OSDOCS-3633-RN enabling Azure DiskEncryptionSets

### PR DESCRIPTION
**Pull request by bscott-rh**
Release notes for https://issues.redhat.com/browse/CORS-1494
Doc preview: https://bscott-rh.github.io/openshift-docs/OSDOCS-3633-RN/release_notes/ocp-4-11-release-notes.html#ocp-4-11-azure-encryption
Doc PR: https://github.com/openshift/openshift-docs/pull/45685

### CODE REVIEW

**Comment by bscott-rh** [comment]
@mgahagan73 @Amoghrd Hello Mike and Amogh, could one of you please take a look at this release note for CORS-1494? I will circle back and update the "Additional information" link with a valid URL once the main PR for the documentation is complete. Thank you

**Comment by mgahagan73** [comment]
Release not looks good, the additional info url still has no content though.

**Comment by bscott-rh** [comment]
> Release not looks good, the additional info url still has no content though.

Thanks Mike - the URL will be present once https://github.com/openshift/openshift-docs/pull/45685 is merged. I will update this PR with the proper URL once that happens.

**Review by tmalove — COMMENTED** [review]
LGTM

**Pull request merged**
