### PR TITLE
[SRVCOM-1662] Update NVIDIA integration docs

### PR DESCRIPTION
**Pull request by abrennan89**
Version(s):
OCP 4.8+

Issue:
https://issues.redhat.com/browse/SRVCOM-1662

Link to docs preview:
https://57416--docspreview.netlify.app/openshift-enterprise/latest/serverless/integrations/gpu-resources.html

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by mvinkler** [comment]
/lgtm
QE Approved

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Comment by GroceryBoyJr** [comment]
Nice work, welcome back @abrennan89

**Pull request merged**
