### PR TITLE
OSDOCS-7852: Adding cluster-admin limitation stmt

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.11+
Issue:

https://issues.redhat.com/browse/OSDOCS-7852
Link to docs preview:

https://64964--docspreview.netlify.app/openshift-enterprise/latest/networking/network_observability/installing-operators
QE review:
- [X] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@jotak @nathan-weinberg can you PTAL at this limitation addition, TY!!

**Review by nathan-weinberg — COMMENTED** [review]
So IIRC (cc @memodi @Amoghrd to keep me honest) you only need `cluster-admin` privileges to create the `openshift-netobserv-operator` namespace - if that exists, I think any admin-level user can install the operator 

I also am not sure if this would only apply to Managed Services (ROSA, OSD, ARO, etc) or to all OCP installs. If no one else knows the answer to that I'm happy to run a quick test to confirm.

**Comment by jotak** [comment]
/lgtm
@nathan-weinberg yes this requirement was more specifically related to the namespace creation.
But not sure if we really need to go in the details about which step exactly requires being cluster-admin .. the way it's presented here is simple and efficient IMO

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Pull request merged**
