### PR TITLE
CNV-18297 - force stop

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.14+

Issue: [CNV-18297](https://issues.redhat.com//browse/CNV-18297)

Link to docs preview: 
https://63859--docspreview.netlify.app/openshift-enterprise/latest/virt/getting_started/virt-web-console-overview#virtualmachines-page_virt-web-console-overview
https://63859--docspreview.netlify.app/openshift-enterprise/latest/virt/getting_started/virt-web-console-overview#virtualmachine-details-page_virt-web-console-overview

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by sabrinajess** [comment]
@DanaOrr Ready for review.

**Review by skopacz1 — COMMENTED** [review]
Left a few small suggestions but otherwise looks good to me!

**Comment by DanaOrr** [comment]
@sabrinajess It's look good to me! :)

**Pull request merged**
