### PR TITLE
[OSDOCS-11388]:Remove "Permissions" section from OSD docs. 

### PR DESCRIPTION
**Pull request by mletalie**
Version(s):

4.16+
Issue:

https://issues.redhat.com/browse/OSDOCS-11388
Link to docs preview:

https://79117--ocpdocs-pr.netlify.app/openshift-dedicated/latest/osd_planning/gcp-ccs.html
QE review:
- [x] QE has approved this change.

Additional information:

**QE Reviewer: This conversational thread may provide further insight into the reason for the doc update. Thanks!
https://redhat-internal.slack.com/archives/C021EMWAQ76/p1721142115792919**
**PEER REVIEWER: PR is based on removing N/A section from docs.**

### CODE REVIEW

**Comment by svmrh** [comment]
the PR looks okay. 'Permissions' sub-topic that described the 'support service account' is removed. After [consultation with SREP](https://redhat-internal.slack.com/archives/C021EMWAQ76/p1721142115792919), it looks like there is nothing like 'support service account' in OSD-GCP for IAM Service Account based authentication-type.

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Pull request merged**
