### PR TITLE
OSDOCS-7520 Zstream release notes 4.12.30

### PR DESCRIPTION
**Pull request by cbippley**
Version(s):
4.12

Issue:
[OSDOCS-7520](https://issues.redhat.com/browse/OSDOCS-7520)

Link to docs preview:
[Preview](https://63773--docspreview.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-12-release-notes#ocp-4-12-30)

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by mletalie** [comment]
LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Updates also LGTM!

**Review by kelbrown20 — COMMENTED** [review]
Merge review LGTM!

**Pull request merged**
