### PR TITLE
OCPBUGS#5051: Set encrypt parameter to false

### PR DESCRIPTION
**Pull request by xenolinux**
Version(s): 4.11+

Issue: https://issues.redhat.com/browse/OCPBUGS-5051

Link to docs preview: https://56982--docspreview.netlify.app/openshift-enterprise/latest/registry/configuring_registry_storage/configuring-registry-storage-rhodf.html#registry-configuring-registry-storage-rhodf-cephrgw_configuring-registry-storage-rhodf

https://56982--docspreview.netlify.app/openshift-enterprise/latest/registry/configuring_registry_storage/configuring-registry-storage-rhodf.html#registry-configuring-registry-storage-rhodf-nooba_configuring-registry-storage-rhodf

QE review:
- [x] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by xiuwang** [comment]
@xenolinux Hi, then https://docs.openshift.com/container-platform/4.11/registry/configuring_registry_storage/configuring-registry-storage-rhodf.html#registry-configuring-registry-storage-rhodf-nooba_configuring-registry-storage-rhodf need update encrypt too, both need update in 4.11+ version
Thanks

**Comment by xenolinux** [comment]
@xiuwang I updated the PR, can you please re-review it?

**Comment by bscott-rh** [comment]
LGTM. 

/remove-label peer-review-in-progress
/remove-label peer-review-needed
/label peer-review-done

**Review by skrthomas — COMMENTED** [review]
Merge review LGTM

**Pull request merged**
