### PR TITLE
OSDOCS-12089 Adding azure capi known issues to RN

### PR DESCRIPTION
**Pull request by bscott-rh**
Version(s):
4.17

Issue:
https://issues.redhat.com/browse/OSDOCS-12089

Link to docs preview:
https://82295--ocpdocs-pr.netlify.app/openshift-enterprise/latest/release_notes/ocp-4-17-release-notes.html#ocp-4-17-known-issues_release-notes

QE review:
- [x] QE has approved this change.

### CODE REVIEW

**Comment by bscott-rh** [comment]
@jinyunma PTAL at this RN for Azure CAPI 4.17 known issues. TY

**Comment by jinyunma** [comment]
@bscott-rh current update looks good to me.

Would you mind also adding another know issue https://issues.redhat.com/browse/OCPBUGS-42349 into RN? The fix is merged but not included in 4.17 rc.3/rc.5, should be in next 4.17.1 z-stream.

**Comment by bscott-rh** [comment]
@jinyunma here is the PR for the known issue https://github.com/openshift/openshift-docs/pull/82365

**Pull request merged**
