### PR TITLE
RHDEVDOCS 6121 correct table formatting for chains

### PR DESCRIPTION
**Pull request by mramendi**
Version(s):

please cp to pipelines-docs-1.11, pipelines-docs-1.12, pipelines-docs-1.13, pipelines-docs-1.14, pipelines-docs-1.15, pipelines-docs-1.16

Issue:

RHDEVDOCS 6121

Link to docs preview:

https://79151--ocpdocs-pr.netlify.app/openshift-pipelines/latest/secure/using-tekton-chains-for-openshift-pipelines-supply-chain-security.html#supported-parameters-tekton-chains-configuration_using-tekton-chains-for-openshift-pipelines-supply-chain-security Table 10

QE review:
n/a

Additional information:

This is a fix for a mistake in table formatting. No documentation content is changed so no SME or QE review is needed.

### CODE REVIEW

**Comment by mramendi** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-6121

**Comment by michaelryanpeter** [comment]
pipelines-docs-1.16

**Pull request merged**
