### PR TITLE
Fix language detection files for Python

### PR DESCRIPTION
**Pull request by rhcarvalho**
Change introduced in early January via https://github.com/openshift/origin/pull/6587.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@openshift/team-documentation @tnguyen-rh PTAL

**Comment by rhcarvalho** [comment]
@adellape @tnguyen-rh PTAL

**Comment by adellape** [comment]
:+1: Thanks.

**Comment by adellape** [comment]
**revhistory note:**

(Dev Guide -> Creating New Applications)

```
Updated the link:../dev_guide/new_app.html#language-detection[Language Detection] section to show Python detection now looks for *_setup.py_* instead of *_config.py_*.
```

**Pull request merged**
