### PR TITLE
Document SBO RN for GA 1.0

### PR DESCRIPTION
**Pull request by Srivaralakshmi**
- **Aligned team**: Dev Tools
- **OCP version for cherry-picking**: enterprise-`4.9`
- **JIRA issues**: [RHDEVDOCS-2926](https://issues.redhat.com/browse/RHDEVDOCS-2926)
- **Preview pages**: [Service Binding Operator release notes](https://deploy-preview-36691--osdocs.netlify.app/openshift-enterprise/latest/applications/connecting_applications_to_services/sbo-release-notes.html)
- **SME Review**: Approved @pedjak , @baijum 
- **QE review**: Approved @pmacik,  IBM @Luvella Mcfadden, @lsmcfadden, @@pravin-dsilva (Power) and Holger Wolf @holgwolf (IBM Z)
- **Peer-review**:  Approved @Preeticp

### CODE REVIEW

**Comment by Srivaralakshmi** [comment]
@pedjak @baijum @pmacik Please review and provide your feedback. Thanks!

**Comment by Srivaralakshmi** [comment]
@pedjak Thanks for the review inputs. I have addressed all your comments. PTAL at the revised content and provide your feedback.

**Comment by Srivaralakshmi** [comment]
@pmacik PTAL at the revised content and provide feedback. Thank you.

**Review by Preeticp — COMMENTED** [review]
Hi @Srivaralakshmi left a few minor suggestions, PTAL

**Review by pedjak — APPROVED** [review]
lgtm

**Pull request merged**
