### PR TITLE
[enterprise-4.11] RN for OSDOCS-3501

### PR DESCRIPTION
**Pull request by jldohmann**
Version(s): 4.11

Issue: https://issues.redhat.com/browse/OSDOCS-3701

Link to docs preview: http://file.rdu.redhat.com/jdohmann/OSDOCS-3501-RN/release_notes/ocp-4-11-release-notes.html#ocp-4-11-ne-clb-timeouts

Additional information: RN entry for #45296

### CODE REVIEW

**Comment by jldohmann** [comment]
Closing and reopening to kick off another Travis build

**Comment by jldohmann** [comment]
Reopening again...

**Comment by jldohmann** [comment]
@quarterpin could you PTAL for QE? This is the RN entry for [NE-357](https://issues.redhat.com/browse/NE-357)

**Comment by quarterpin** [comment]
/lgtm 
thanks!

**Review by lpettyjo — COMMENTED** [review]
LGTM!

**Pull request merged**
