### PR TITLE
Added documentation for Volume CLI cmd

### PR DESCRIPTION
**Pull request by pravisankar**

### CODE REVIEW

**Comment by pravisankar** [comment]
@tpoitras @adellape

**Comment by adellape** [comment]
@pravisankar What's your thinking on this being separate "Volumes" and "Persistent Volumes" topics versus one single "Volumes" topic? Just that it was getting too long?

**Comment by pravisankar** [comment]
@adellape 
Persistent Volumes is a big topic, current doc covers how to create a PersistentVolume and PersistentVolumeClaim resources in OpenShift backed by persistent volumes. Supported persistent volumes: gce, aws, gluster, nfs, iscsi, ceph, rbd (https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/types.go#L218). We may want to document how to use nfs persistent volumes, etc. in openshift and Mark is already adding more docs.
This doc covers how to leverage all available volume sources (ephemeral/persistent) using CLI.
Ideally, I think there should be top level Volumes topic/doc that references several sub-topics like persistent volumes, CLI, etc. in a consumable manner.

**Comment by adellape** [comment]
@pravisankar OK, thanks. Merging and will follow up with edits.

BTW, an administrator topic on NFS persistent volumes is here:

http://docs.openshift.org/latest/admin_guide/persistent_storage_nfs.html

Which is currently going through minor edits in https://github.com/openshift/openshift-docs/pull/579, should merge soon.

**Pull request merged**
