### PR TITLE
Bug 1409761 Added information about the generator parameter

### PR DESCRIPTION
**Pull request by bmcelvee**
https://bugzilla.redhat.com/show_bug.cgi?id=1409761

### CODE REVIEW

**Comment by bmcelvee** [comment]
Bug 1409761: I added more context about the generator parameter. @xingxingxia PTAL

**Comment by xingxingxia** [comment]
@bmcelvee LGTM, thanks

**Comment by bmcelvee** [comment]
@ahardin-rh Please peer review. Thanks!

**Comment by ahardin-rh** [comment]
LGTM :star:

**Comment by bmcelvee** [comment]
[rev_history]
|xref:../cli_reference/basic_cli_operations.adoc#expose[Expose]
|Added additional information about the generator parameter in the xref:../cli_reference/basic_cli_operations.adoc#expose[Expose] section.
%

**Comment by vikram-redhat** [comment]
@bmcelvee - there is no tag [[expose]] for the expose section in the cli_reference/basic_cli_operations guide. :)

I have added one now for this release.

**Pull request merged**
