### PR TITLE
CNV-12271: Adding new tech preview feature RN

### PR DESCRIPTION
**Pull request by bgaydosrh**
for 4.8 only.

Jira: https://issues.redhat.com/browse/CNV-12271

Tagging @aglitke for code review.
Tagging @duyanyan for QE review.

Direct doc preview link: https://deploy-preview-34297--osdocs.netlify.app/openshift-enterprise/latest/virt/virt-4-8-release-notes.html#virt-4-8-technology-preview

### CODE REVIEW

**Comment by duyanyan** [comment]
LGTM

**Review by aglitke — APPROVED** [review]

**Review by ousleyp — COMMENTED** [review]
This LGTM, but I'd like to see an xref as we discussed. Let me know when you're ready for approval/merge. Thanks!

**Comment by bgaydosrh** [comment]
> This LGTM, but I'd like to see an xref as we discussed. Let me know when you're ready for approval/merge. Thanks!

Done, thanks!

**Review by ousleyp — APPROVED** [review]
lgtm

**Pull request merged**
