### PR TITLE
fixed formatting for svcat in 3.10 release notes

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Changed svcat to `svcat`

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@ahardin-rh Please check and merge.

**Comment by gaurav-nelson** [comment]
@bmcelvee PTAL

**Comment by bmcelvee** [comment]
Thanks, @gaurav-nelson! LGTM. I'll go ahead and merge/cherrypick.

**Pull request merged**
