### PR TITLE
OCPBUGS-15098: Add step to LokiStack procedure

### PR DESCRIPTION
**Pull request by skrthomas**
Version(s):

4.10+
Issue:

https://issues.redhat.com/browse/OCPBUGS-15098
Link to docs preview:

QE review:
- [ ] QE has approved this change.

Additional information:

### CODE REVIEW

**Comment by skrthomas** [comment]
@jotak @nathan-weinberg can you guys review this small change to the LokiStack procedure? We had a docs bug open up requesting some clarifications to the procedure. I've tested the updates in a cluster Nathan provided for me, so I think these updates are appropriate and helpful.

**Review by nathan-weinberg — COMMENTED** [review]
/label qe-approved

**Comment by lazharh** [comment]
LGTM

**Comment by GroceryBoyJr** [comment]
Full Preview Link: https://docs.openshift.com/container-platform/4.13/networking/network_observability/installing-operators.html

**Review by GroceryBoyJr — COMMENTED** [review]
LGTM

**Review by jotak — APPROVED** [review]

**Pull request merged**
