### PR TITLE
Add release notes entry for SR-IOV InfiniBand support

### PR DESCRIPTION
**Pull request by jboxman**
This adds a RN entry for OCP 4.6.

@zshi-redhat, do we have any specific additional information we want to include in the release notes for InfiniBand support? I'm going to link to the content for configuring these devices, once it's merged.

Thanks.

### CODE REVIEW

**Review by codyhoag — APPROVED** [review]
LGTM!

**Comment by zshi-redhat** [comment]
@jboxman SR-IOV Infiniband support will be GA.
do we need to explicitly call the infiniband support GA or it's fine to just not specifying it as TP?

**Comment by jboxman** [comment]
@zshi-redhat, I don't think it was ever listed as TP; @codyhoag does it make sense to explicitly state this is GA?

**Comment by codyhoag** [comment]
@jboxman when we state that we support something, I take that to mean it's GA. But, IMO, I don't think it would be wrong to state something as GA if it wasn't listed TP first. I think it's really up to the team for how they want to present it to the world. FWIW, the *What's New* presentation slide for SR-IOV Infiniband did not mention it as GA, but rather, just *now supported*.

**Pull request merged**
