### PR TITLE
BZ#1887623: Mention OVS on the About OVN-K page

### PR DESCRIPTION
**Pull request by mikemckiernan**
Review needed for the first paragraph at https://deploy-preview-29461--osdocs.netlify.app/openshift-enterprise/latest/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html

Applies to enterprise 4.6, 4.7, and newer.  Milestone Next-Release.

This can be merged after 4.7 GA.
/hold

### CODE REVIEW

**Comment by mikemckiernan** [comment]
@openshift/team-documentation , please review.

/hold cancel

**Comment by ahardin-rh** [comment]
LGTM!

**Comment by jboxman** [comment]
@mikemckiernan, sweet!

**Pull request merged**
