### PR TITLE
CNV23531: svg to png main branch

### PR DESCRIPTION
**Pull request by sabrinajess**
Version(s): 4.9+

Issue: [CNV-23531](https://issues.redhat.com//browse/CNV-23531)

Link to docs preview:

QE review: NO QE NEEDED
- [ ] QE has approved this change. 

Additional Information: Switching SVG to PNG due to SVG rendering incorrectly on customer portal.

### CODE REVIEW

**Comment by tmalove** [comment]
@sabrinajess  I will close the review for both PRs related to the updated file type when the preview link is updated in the 4.11 one. Thanks!

**Comment by jeana-redhat** [comment]
This is for 4.9+, but no CPs are required due to the inclusion of the same change in the following branch PRs:
* 4.9 #54482
* 4.10 #54505
* 4.11 #54510
* 4.12 #54513

/remove-label merge-review-in-progress
/remove-label merge-review-needed

**Pull request merged**
