### PR TITLE
BZ#2110059: Fix inaccuracies in ingress dest CA cert docs

### PR DESCRIPTION
**Pull request by Miciah**
* `modules/nw-ingress-creating-a-route-via-an-ingress.adoc`: Change "oc `create`" to "`oc create`".
* `modules/nw-ingress-reencrypt-route-custom-cert.adoc`: Change "an route" to "a route".  Replace "certificate (CA)" with "destination CA certificate".  State that the user *may* (not *must*) specify a certificate/key pair.  Change "Annotations:" to "annotations:" in the example yaml.

-------

Version(s):

4.11+

Issue:

https://bugzilla.redhat.com/show_bug.cgi?id=2110059

Link to docs preview:

Additional information:

The option to configure a destination CA certificate on an ingress object was added in OpenShift 4.11: https://issues.redhat.com/browse/NE-729

### CODE REVIEW

**Comment by ahardin-rh** [comment]
LGTM
@lihongan Can you please verify this update?

**Comment by bergerhoffer** [comment]
The enterprise-4.12 label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for enterprise-4.11. And any PR going into `main` must also target the latest version branch (enterprise-4.12).

If the update in your PR does NOT apply to version 4.12 onward, please re-target this PR to go directly into the appropriate version branch or branches (enterprise-4.x) instead of main.

**Pull request merged**
