### PR TITLE
BZ2006013: add a line which clarifies why additionalbundletrust does not work without proxy

### PR DESCRIPTION
**Pull request by chinmayi-chandrasekar**
Applies to 4.6+

https://bugzilla.redhat.com/show_bug.cgi?id=2006013

Requires QE ack from @xltian

### CODE REVIEW

**Review by adellape — APPROVED** [review]

**Comment by gpei** [comment]
LGTM

**Review by wking — APPROVED** [review]
/lgtm

**Comment by maxwelldb** [comment]
Okayed by Alex D. Swapping labels.

**Comment by maxwelldb** [comment]
@chinmayi-chandrasekar You'll need to resolve the merge conflict for 4.6 and 4.7 and open up separate PRs for those.

**Pull request merged**
