### PR TITLE
[enterprise-4.2] Replace NFS suggestion with OCS

### PR DESCRIPTION
**Pull request by codyhoag**
Suggested in #18036.

### CODE REVIEW

**Comment by codyhoag** [comment]
@duanwei33 can you confirm that we should avoid recommending NFS in this context?

I also sent this change for 4.1: #19305

**Comment by codyhoag** [comment]
@duanwei33 can you review this small change when you have a moment. Let me know if I should reach out to someone else. Thanks!

**Comment by duanwei33** [comment]
/LGTM
Sorry for the delay, I missed the last reminder. @codyhoag

**Comment by bmcelvee** [comment]
LGTM, though I'm a little surprised this is being changed again. @dmage or @coreydaley  would you mind also approving? Thanks!

**Comment by dmage** [comment]
If we don't like NFS, we should suggest another viable solution. What else can we recommend in 4.2 that works better than NFS?

**Comment by codyhoag** [comment]
@dmage do you recommend I reach out to someone to ask what would be a good solution to replace NFS in this context?

**Comment by codyhoag** [comment]
FYI, 4.3 docs have already removed the NFS suggestion in this context. If we'd like to add an alternate solution, I'll need to update the 4.3 doc too.

**Comment by dmage** [comment]
In our documentation we [have only 3 options](https://docs.openshift.com/container-platform/4.3/storage/understanding-persistent-storage.html#pv-access-modes_understanding-persistent-storage): Azure File, NFS, and Red Hat OpenShift Container Storage. Azure is not suitable for baremetal clusters, NFS can be problematic. Can we recommend OCS?

**Comment by codyhoag** [comment]
@duanwei33 can you take a second look at this? We've decided to recommend OCS *instead* of NFS. Do you agree?

I've made this change for 4.1 (#19305) and 4.3 (#19665) as well. Let me know if this doesn't make sense in those versions. Thanks

**Comment by duanwei33** [comment]
/LGTM
I also let @liangxia to see if he has any comments.

**Pull request merged**
